/**
 * Bag Best Guides rebuilt against the ~125-product bag market.
 * Distinct carry jobs only — no fake top-ten of identical paleteros.
 */
import type { BestGuide } from "@/domain/editorial/types";
import {
  PADEL_SPORT,
  baseGuide,
  bagCriteria,
  considered,
  method,
  pick,
} from "@/content/padel/best-guides/build";

export const padelBagsBackpacksGuide: BestGuide = baseGuide({
  id: "best-padel-backpacks",
  slug: "padel-backpacks",
  title: "Best Padel Backpacks",
  subtitle: "Commute and day-carry backpacks — not paletero duffels",
  shortDescription:
    "Backpack-form padel bags from the expanded market: Tecnifibre Tour Endurance, Bullpadel Vertex backpack, HEAD Tour 25L, Bullpadel Hack backpack.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-choose-padel-bag", "guide-padel-bag-vs-backpack"],
  ...method("published backpack-form padel bags with authentic packshots — paletero duffels stay out of awards"),
  intro:
    "A backpack is a commute job. From the expanded bag catalog we award Tecnifibre Tour Endurance, Bullpadel Vertex backpack, and HEAD Tour 25L. Large paleteros (RH Pro, AT10 Team, XXL) are considered as the opposite form — not ranked here.",
  whatMattersIntro: "Backpack form first, then shoe well / thermo if listed, then authentic packshot.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [
    { key: "form", label: "Backpack form", whyItMatters: "Paleteros are a different guide.", importance: "high" },
  ],
  criteriaChangePoints: [
    { label: "Form filter", explanation: "AT10 Team / RH Pro are paleteros — rejected from backpack awards." },
  ],
  quickTake: [
    "Tour Endurance for a day backpack with shoe well.",
    "Vertex backpack when you want Bullpadel thermo commute.",
    "HEAD Tour 25L for compact commute.",
  ],
  decisionShortcuts: [
    { need: "Day backpack", productId: "prod-tecnifibre-tour-endurance-backpack", reason: "Tour Endurance." },
    { need: "Thermo commute backpack", productId: "prod-bullpadel-vertex-backpack", reason: "Vertex backpack." },
  ],
  recommendations: [
    pick({
      productId: "prod-tecnifibre-tour-endurance-backpack",
      rank: 1,
      awardType: "best-overall",
      role: "Day backpack",
      summary: "Tecnifibre Tour Endurance backpack — shoe well, commute form.",
      whyWon: "Clearest day-backpack job with authentic packshot in the expanded catalog.",
      whyFits: [
        "I’d use this for bike/walk commute.",
        "I’d skip it if I need listed thermo for two match frames — that is a paletero.",
      ],
      bestFor: ["Commute backpack", "Shoe well"],
      tradeoff: "Exact racket count may be unpublished; not a tournament duffel.",
      avoid: ["Players who need listed thermo paletero specs"],
      instead: [
        { productId: "prod-nox-at10-team-bag", when: "you need a thermo club paletero", label: "AT10 Team" },
        { productId: "prod-bullpadel-vertex-backpack", when: "you want Bullpadel thermo backpack", label: "Vertex backpack" },
      ],
    }),
    pick({
      productId: "prod-bullpadel-vertex-backpack",
      rank: 2,
      awardType: "editors-pick",
      role: "Thermo commute backpack",
      summary: "Bullpadel Vertex backpack — thermo-leaning commute backpack.",
      whyWon: "Backpack form with Bullpadel thermo story — distinct from Tour Endurance’s shoe-well day bag.",
      whyFits: [
        "I’d pick Vertex backpack when Bullpadel kit and thermo commute matter.",
        "I’d skip it if I wanted maximum tournament volume.",
      ],
      bestFor: ["Thermo commute", "Bullpadel backpack"],
      tradeoff: "Not RH Pro tournament volume.",
      avoid: ["Players who need 4-racket duffels"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you want a simpler day backpack", label: "Tour Endurance" },
        { productId: "prod-babolat-rh-pro-padel", when: "you need tournament volume", label: "RH Pro" },
      ],
    }),
    pick({
      productId: "prod-head-tour-backpack-25l",
      rank: 3,
      awardType: "best-value",
      role: "Compact commute backpack",
      summary: "HEAD Tour 25L — compact commute backpack.",
      whyWon: "Compact backpack job from the expanded market without inventing a fourth identical day bag.",
      whyFits: [
        "I’d take Tour 25L when I want smaller commute volume.",
        "I’d skip it if I need thermo for two frames.",
      ],
      bestFor: ["Compact commute", "Light day carry"],
      tradeoff: "Limited volume vs larger backpacks/paleteros.",
      avoid: ["Tournament packers"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you need a fuller day backpack", label: "Tour Endurance" },
      ],
    }),
  ],
  consideredProducts: [
    considered("prod-bullpadel-bpm26002-hack", "Hack 2026 backpack — shortlisted signature commute alternative.", "shortlisted"),
    considered("prod-wilson-bela-backpack", "Bela backpack — shortlisted compact Bela lane.", "shortlisted"),
    considered("prod-babolat-court-backpack", "Babolat Court backpack — shortlisted.", "shortlisted"),
    considered("prod-head-elite-backpack", "HEAD Elite backpack — shortlisted.", "shortlisted"),
    considered("prod-nox-at10-team-bag", "Paletero — rejected from backpack awards.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-babolat-rh-pro-padel", "Tournament paletero — rejected here.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-nox-bag-10", "Unknown-dimension collection bag — rejected.", "rejected", { reasonCode: "insufficient-evidence" }),
  ],
  buyingAdvice: "Pick backpack form for commute. Pick a paletero when thermo and racket bays matter more than straps.",
  relatedGuideIds: ["best-padel-bags", "best-padel-bags-commuting"],
  hubImageSrc: "/images/padel/products/tecnifibre-tour-endurance-padel-backpack-hero.jpg",
  hubImageAlt: "Padel backpack",
});

export const padelBagsLargeGuide: BestGuide = baseGuide({
  id: "best-large-padel-bags",
  slug: "large-padel-bags",
  title: "Best Large Padel Bags",
  subtitle: "Tournament volume and XXL carry — not club-night minimalism",
  shortDescription:
    "Large/tournament bags from the expanded market: Babolat RH Pro, Nox AT10 XXL, Wilson Super Tour, Nox Competition Trolley.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-choose-padel-bag"],
  ...method("published high-capacity / tournament paleteros and XXL bags with authentic packshots"),
  intro:
    "Large bags are for tournament weekends and multi-racket kits. We award RH Pro, AT10 XXL, and Wilson Super Tour. Compact backpacks and 42 L club paleteros stay considered as the opposite job.",
  whatMattersIntro: "Published capacity / racket count first, then thermo, then whether you will actually haul the volume.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [{ key: "volume", label: "Large capacity", whyItMatters: "Club 42 L bags are a different guide.", importance: "high" }],
  criteriaChangePoints: [{ label: "Volume filter", explanation: "AT10 Team is a club paletero — not a large-bag award." }],
  quickTake: [
    "RH Pro for 62 L / four-racket tournament volume.",
    "AT10 XXL for maximum Nox volume.",
    "Wilson Super Tour for Bela tournament paletero.",
  ],
  decisionShortcuts: [
    { need: "Tournament 62 L", productId: "prod-babolat-rh-pro-padel", reason: "RH Pro." },
    { need: "XXL volume", productId: "prod-nox-at10-xxl-bag", reason: "AT10 XXL." },
  ],
  recommendations: [
    pick({
      productId: "prod-babolat-rh-pro-padel",
      rank: 1,
      awardType: "best-overall",
      role: "Tournament volume",
      summary: "Babolat RH Pro — 62 L, four rackets, insulated + shoe pockets.",
      whyWon: "Clearest published tournament volume job in the expanded catalog.",
      whyFits: [
        "I’d pack RH Pro for a tournament weekend.",
        "I’d skip it for a two-racket club night.",
      ],
      bestFor: ["Tournament weekends", "Four-racket kits"],
      tradeoff: "Overkill for commute minimalism.",
      avoid: ["Players who only carry two frames"],
      instead: [
        { productId: "prod-nox-at10-team-bag", when: "you want a 42 L club paletero", label: "AT10 Team" },
        { productId: "prod-nox-at10-xxl-bag", when: "you need even more volume", label: "AT10 XXL" },
      ],
    }),
    pick({
      productId: "prod-nox-at10-xxl-bag",
      rank: 2,
      awardType: "editors-pick",
      role: "XXL tournament volume",
      summary: "Nox AT10 XXL — maximum Nox tournament volume.",
      whyWon: "XXL job distinct from RH Pro’s 62 L — for players who genuinely fill the bag.",
      whyFits: [
        "I’d take XXL when Nox volume is the weekly problem.",
        "I’d skip it if RH Pro already feels huge.",
      ],
      bestFor: ["Maximum volume", "Nox tournament kits"],
      tradeoff: "Heavy empty; awkward on transit.",
      avoid: ["Commute minimalists"],
      instead: [
        { productId: "prod-babolat-rh-pro-padel", when: "62 L is enough", label: "RH Pro" },
      ],
    }),
    pick({
      productId: "prod-wilson-super-tour-padel",
      rank: 3,
      awardType: "editors-pick",
      role: "Bela tournament paletero",
      summary: "Wilson Super Tour — Bela tournament paletero.",
      whyWon: "Keeps Wilson tournament carry in the large-bag shortlist without a fourth identical XXL award.",
      whyFits: [
        "I’d pack Super Tour for Wilson/Bela tournament kits.",
        "I’d skip it if I’m already happy with RH Pro volume.",
      ],
      bestFor: ["Wilson tournament kits", "Large paletero"],
      tradeoff: "Overlaps RH Pro / XXL volume jobs.",
      avoid: ["Players who want the smallest possible bag"],
      instead: [
        { productId: "prod-babolat-rh-pro-padel", when: "you want the 62 L reference", label: "RH Pro" },
      ],
    }),
  ],
  consideredProducts: [
    considered("prod-nox-at10-competition-trolley", "Wheeled tournament trolley — shortlisted distinct carry mechanism.", "shortlisted"),
    considered("prod-nox-at10-team-bag", "42 L club paletero — rejected from large awards.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-tecnifibre-tour-endurance-backpack", "Backpack — rejected from large awards.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-adidas-protour-padel", "Adidas ProTour — shortlisted large Adidas paletero.", "shortlisted"),
    considered("prod-black-crown-spartan", "Black Crown Spartan — shortlisted specialist large bag.", "shortlisted"),
  ],
  buyingAdvice: "Only buy large if you fill it. Empty XXL volume is just weight.",
  relatedGuideIds: ["best-padel-bags", "best-padel-tournament-bags"],
  hubImageSrc: "/images/padel/products/babolat-rh-pro-padel-hero.jpg",
  hubImageAlt: "Large tournament padel bag",
});

export const padelBagsTournamentGuide: BestGuide = baseGuide({
  id: "best-padel-tournament-bags",
  slug: "padel-tournament-bags",
  title: "Best Tournament Padel Bags",
  subtitle: "Weekend kits: volume, thermo, shoes — not everyday backpacks",
  shortDescription:
    "Tournament-oriented bags: RH Pro, AT10 XXL, Wilson Super Tour, with trolley considered.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-choose-padel-bag"],
  ...method("bags whose published job is multi-racket tournament weekends"),
  intro:
    "Tournament bags prioritise racket count, thermo, and shoe isolation for weekend events. Awards mirror the large-bag shortlist with tournament framing; commute backpacks stay out.",
  whatMattersIntro: "Racket capacity, thermo, shoe separation, and whether wheeled carry helps.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [{ key: "tournament", label: "Tournament job", whyItMatters: "Commute backpacks are different.", importance: "high" }],
  criteriaChangePoints: [{ label: "Weekend kit", explanation: "Tour Endurance backpack is commute — rejected here." }],
  quickTake: [
    "RH Pro as the default tournament volume bag.",
    "XXL when you truly need maximum Nox volume.",
    "Consider a trolley if you hate shoulder hauls.",
  ],
  decisionShortcuts: [
    { need: "Default tournament bag", productId: "prod-babolat-rh-pro-padel", reason: "RH Pro." },
  ],
  recommendations: [
    pick({
      productId: "prod-babolat-rh-pro-padel",
      rank: 1,
      awardType: "best-overall",
      role: "Default tournament bag",
      summary: "Babolat RH Pro — tournament volume with insulated + shoe pockets.",
      whyWon: "Best default tournament weekend bag in the expanded catalog.",
      whyFits: [
        "I’d pack RH Pro for events.",
        "I’d skip it for club-night minimalism.",
      ],
      bestFor: ["Tournament weekends"],
      tradeoff: "Large for daily commute.",
      avoid: ["Daily bike commute only"],
      instead: [
        { productId: "prod-nox-at10-team-bag", when: "club nights only", label: "AT10 Team" },
        { productId: "prod-nox-at10-xxl-bag", when: "you need more volume", label: "XXL" },
      ],
    }),
    pick({
      productId: "prod-nox-at10-xxl-bag",
      rank: 2,
      awardType: "editors-pick",
      role: "Maximum tournament volume",
      summary: "Nox AT10 XXL — maximum volume tournament bag.",
      whyWon: "When RH Pro is not enough volume.",
      whyFits: [
        "I’d take XXL for packed tournament kits.",
        "I’d skip it if I’m already at my haul limit with RH Pro.",
      ],
      bestFor: ["Maximum tournament volume"],
      tradeoff: "Heavy and bulky empty.",
      avoid: ["Light travellers"],
      instead: [{ productId: "prod-babolat-rh-pro-padel", when: "62 L is enough", label: "RH Pro" }],
    }),
    pick({
      productId: "prod-wilson-super-tour-padel",
      rank: 3,
      awardType: "editors-pick",
      role: "Wilson tournament paletero",
      summary: "Wilson Super Tour — Bela tournament paletero.",
      whyWon: "Wilson tournament lane without duplicating RH Pro as a second #1.",
      whyFits: [
        "I’d pack Super Tour for Wilson kits.",
        "I’d skip it if RH Pro already covers volume.",
      ],
      bestFor: ["Wilson tournament kits"],
      tradeoff: "Overlaps other large awards.",
      avoid: ["Minimalist club players"],
      instead: [{ productId: "prod-babolat-rh-pro-padel", when: "you want the volume reference", label: "RH Pro" }],
    }),
  ],
  consideredProducts: [
    considered("prod-nox-at10-competition-trolley", "Wheeled trolley — shortlisted for shoulder-relief tournament carry.", "shortlisted"),
    considered("prod-tecnifibre-tour-endurance-backpack", "Commute backpack — rejected.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-nox-at10-team-bag", "Club paletero — shortlisted as lighter tournament alternative.", "shortlisted"),
  ],
  buyingAdvice: "Tournament bags earn their keep on event weekends — not as daily fashion luggage.",
  relatedGuideIds: ["best-large-padel-bags", "best-padel-bags"],
  hubImageSrc: "/images/padel/products/nox-at10-xxl-padel-bag-hero.jpg",
  hubImageAlt: "Nox AT10 XXL tournament padel bag",
});

export const padelBagsCommutingGuide: BestGuide = baseGuide({
  id: "best-padel-bags-commuting",
  slug: "padel-bags-commuting",
  title: "Best Padel Bags for Commuting",
  subtitle: "Hands-free and transit-friendly — not XXL tournament duffels",
  shortDescription:
    "Commute-friendly bags: backpacks and compact paleteros that survive bikes, trains, and walking.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-padel-bag-vs-backpack", "guide-choose-padel-bag"],
  ...method("bags suited to walk/bike/train commute — backpack straps or compact paletero volume"),
  intro:
    "Commuting punishes empty XXL volume. We award Tour Endurance, Vertex backpack, HEAD Tour 25L, and keep AT10 Team shortlisted when you still need thermo on transit.",
  whatMattersIntro: "Carry system, compact volume, shoe isolation, and whether thermo is worth the bulk.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [{ key: "commute", label: "Commute job", whyItMatters: "XXL tournament bags are wrong here.", importance: "high" }],
  criteriaChangePoints: [{ label: "Transit filter", explanation: "RH Pro / XXL rejected as commute winners." }],
  quickTake: [
    "Backpack first for hands-free commute.",
    "Compact Tour 25L when volume must stay small.",
    "AT10 Team only if thermo beats backpack simplicity.",
  ],
  decisionShortcuts: [
    { need: "Hands-free commute", productId: "prod-tecnifibre-tour-endurance-backpack", reason: "Tour Endurance." },
  ],
  recommendations: [
    pick({
      productId: "prod-tecnifibre-tour-endurance-backpack",
      rank: 1,
      awardType: "best-overall",
      role: "Hands-free commute",
      summary: "Tecnifibre Tour Endurance — day backpack for transit.",
      whyWon: "Best default commute form in the expanded catalog.",
      whyFits: [
        "I’d take Tour Endurance on bike/train days.",
        "I’d skip it if I need listed thermo for two frames.",
      ],
      bestFor: ["Bike/train commute", "Hands-free carry"],
      tradeoff: "Less thermo certainty than a club paletero.",
      avoid: ["Players who need XXL tournament volume daily"],
      instead: [
        { productId: "prod-bullpadel-vertex-backpack", when: "you want thermo commute", label: "Vertex backpack" },
        { productId: "prod-nox-at10-team-bag", when: "you need thermo paletero specs", label: "AT10 Team" },
      ],
    }),
    pick({
      productId: "prod-bullpadel-vertex-backpack",
      rank: 2,
      awardType: "editors-pick",
      role: "Thermo commute backpack",
      summary: "Bullpadel Vertex backpack — thermo-leaning commute.",
      whyWon: "Commute backpack with thermo story.",
      whyFits: [
        "I’d pick Vertex backpack when frames sit in a hot car after the commute.",
        "I’d skip it if shoe-well day bag is enough.",
      ],
      bestFor: ["Thermo commute"],
      tradeoff: "Still not a tournament duffel.",
      avoid: ["XXL tournament packers"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "simpler day backpack is enough", label: "Tour Endurance" },
      ],
    }),
    pick({
      productId: "prod-head-tour-backpack-25l",
      rank: 3,
      awardType: "best-value",
      role: "Compact commute",
      summary: "HEAD Tour 25L — compact commute backpack.",
      whyWon: "Smallest honest commute award without pretending it is a paletero.",
      whyFits: [
        "I’d take 25L when I travel light.",
        "I’d skip it if I carry shoes + two frames + balls regularly.",
      ],
      bestFor: ["Compact commute"],
      tradeoff: "Limited capacity.",
      avoid: ["Multi-racket tournament kits"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you need more day volume", label: "Tour Endurance" },
      ],
    }),
  ],
  consideredProducts: [
    considered("prod-nox-at10-team-bag", "Club paletero with straps — shortlisted when thermo beats backpack.", "shortlisted"),
    considered("prod-babolat-rh-pro-padel", "Tournament volume — rejected for commute awards.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-nox-at10-xxl-bag", "XXL — rejected for commute awards.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-bullpadel-bpm26002-hack", "Hack backpack — shortlisted.", "shortlisted"),
  ],
  buyingAdvice: "Commute bags should survive your transit mode. Empty XXL volume is dead weight.",
  relatedGuideIds: ["best-padel-backpacks", "best-padel-bags"],
  hubImageSrc: "/images/padel/products/bullpadel-vertex-geo-backpack-hero.jpg",
  hubImageAlt: "Bullpadel Vertex thermo commute backpack",
});

export const padelBagsShoeGuide: BestGuide = baseGuide({
  id: "best-padel-bags-shoe-compartment",
  slug: "padel-bags-with-shoe-compartments",
  title: "Best Padel Bags with Shoe Compartments",
  subtitle: "Keep court grit off dry kit — only when the shoe bay is real",
  shortDescription:
    "Bags with published shoe isolation: AT10 Team, RH Pro, Tour Endurance, Vertex backpack.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-choose-padel-bag"],
  ...method("bags with published shoe compartment / shoe well — not assumed from photos alone"),
  intro:
    "Shoe compartments matter when sand and turf grit ruin dry clothes. We award AT10 Team, RH Pro, and Tour Endurance where shoe isolation is part of the published job. Bags without a clear shoe bay stay out.",
  whatMattersIntro: "Published shoe pocket/well first. Then whether the rest of the bag matches club vs tournament vs commute.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [{ key: "shoes", label: "Shoe isolation", whyItMatters: "Must be a real compartment, not a marketing vibe.", importance: "high" }],
  criteriaChangePoints: [{ label: "Shoe bay required", explanation: "Unknown shoe storage cannot win this guide." }],
  quickTake: [
    "AT10 Team for club paletero + shoes.",
    "RH Pro for tournament bags with shoe pocket.",
    "Tour Endurance for backpack shoe well.",
  ],
  decisionShortcuts: [
    { need: "Club paletero + shoes", productId: "prod-nox-at10-team-bag", reason: "AT10 Team." },
    { need: "Backpack shoe well", productId: "prod-tecnifibre-tour-endurance-backpack", reason: "Tour Endurance." },
  ],
  recommendations: [
    pick({
      productId: "prod-nox-at10-team-bag",
      rank: 1,
      awardType: "best-overall",
      role: "Club paletero + shoes",
      summary: "Nox AT10 Team — thermo club paletero with shoe vent.",
      whyWon: "Best club-night shoe isolation + thermo combo in the expanded catalog.",
      whyFits: [
        "I’d take AT10 Team when shoes and frames share the bag.",
        "I’d skip it if I only need a backpack shoe well.",
      ],
      bestFor: ["Club nights", "Shoe + thermo"],
      tradeoff: "Not tournament XXL volume.",
      avoid: ["Players who never carry shoes in the bag"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you want backpack shoe well", label: "Tour Endurance" },
        { productId: "prod-babolat-rh-pro-padel", when: "you need tournament volume + shoes", label: "RH Pro" },
      ],
    }),
    pick({
      productId: "prod-babolat-rh-pro-padel",
      rank: 2,
      awardType: "editors-pick",
      role: "Tournament bag + shoes",
      summary: "Babolat RH Pro — tournament volume with shoe pocket.",
      whyWon: "Shoe isolation inside a true tournament bag.",
      whyFits: [
        "I’d pack RH Pro when shoes travel with a four-racket kit.",
        "I’d skip it for club-night minimalism.",
      ],
      bestFor: ["Tournament + shoes"],
      tradeoff: "Large for daily commute.",
      avoid: ["Light club commuters"],
      instead: [
        { productId: "prod-nox-at10-team-bag", when: "club volume is enough", label: "AT10 Team" },
      ],
    }),
    pick({
      productId: "prod-tecnifibre-tour-endurance-backpack",
      rank: 3,
      awardType: "editors-pick",
      role: "Backpack shoe well",
      summary: "Tecnifibre Tour Endurance — visible shoe well in backpack form.",
      whyWon: "Shoe isolation without forcing a paletero.",
      whyFits: [
        "I’d use Tour Endurance when commute + shoes matter.",
        "I’d skip it if I need thermo for two match frames.",
      ],
      bestFor: ["Commute + shoes"],
      tradeoff: "Less thermo certainty than AT10 Team.",
      avoid: ["Players who need listed thermo paletero specs"],
      instead: [
        { productId: "prod-nox-at10-team-bag", when: "you need thermo + shoes", label: "AT10 Team" },
      ],
    }),
  ],
  consideredProducts: [
    considered("prod-bullpadel-vertex-backpack", "Vertex backpack — shortlisted thermo commute with shoe potential.", "shortlisted"),
    considered("prod-nox-at10-xxl-bag", "XXL — shortlisted when shoe bay exists at max volume.", "shortlisted"),
    considered("prod-nox-bag-10", "Unknown shoe specs — rejected.", "rejected", { reasonCode: "insufficient-evidence" }),
  ],
  buyingAdvice: "If the shoe bay isn’t published, don’t invent it from a lifestyle photo.",
  relatedGuideIds: ["best-padel-bags", "best-padel-backpacks"],
  hubImageSrc: "/images/padel/products/nox-at10-team-paletero-hero.jpg",
  hubImageAlt: "Padel bag with shoe compartment",
});

export const padelBagsCompactGuide: BestGuide = baseGuide({
  id: "best-compact-padel-bags",
  slug: "compact-padel-bags",
  title: "Best Compact Padel Bags",
  subtitle: "Small carry for one–two rackets — not tournament luggage",
  shortDescription:
    "Compact bags and small backpacks from the expanded market for light club nights.",
  sportId: PADEL_SPORT,
  categoryId: "cat-padel-bags",
  guideKind: "use-case",
  rankingMode: "ranked",
  relatedBuyingGuideIds: ["guide-choose-padel-bag"],
  ...method("compact backpacks and smaller paleteros suited to one–two racket club nights"),
  intro:
    "Compact bags win when you hate hauling empty volume. We award HEAD Tour 25L, Tour Endurance, and keep AT10 Team as the smallest honest thermo paletero — while rejecting RH Pro/XXL.",
  whatMattersIntro: "Low volume, easy carry, enough for one–two rackets + shoes/balls.",
  selectionCriteria: bagCriteria,
  whatWeLookFor: [{ key: "compact", label: "Compact job", whyItMatters: "Large tournament bags are wrong here.", importance: "high" }],
  criteriaChangePoints: [{ label: "Size filter", explanation: "RH Pro / XXL rejected." }],
  quickTake: [
    "Tour 25L for the smallest commute backpack.",
    "Tour Endurance for a fuller day backpack still below tournament duffels.",
    "AT10 Team when you still need thermo without going XXL.",
  ],
  decisionShortcuts: [
    { need: "Smallest backpack", productId: "prod-head-tour-backpack-25l", reason: "Tour 25L." },
  ],
  recommendations: [
    pick({
      productId: "prod-head-tour-backpack-25l",
      rank: 1,
      awardType: "best-overall",
      role: "Compact commute backpack",
      summary: "HEAD Tour 25L — compact club/commute backpack.",
      whyWon: "Smallest clear backpack award in the expanded catalog.",
      whyFits: [
        "I’d take 25L when I travel light.",
        "I’d skip it if I regularly pack two frames + shoes + balls densely.",
      ],
      bestFor: ["Light club nights", "Compact commute"],
      tradeoff: "Limited capacity.",
      avoid: ["Tournament packers"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you need more day volume", label: "Tour Endurance" },
      ],
    }),
    pick({
      productId: "prod-tecnifibre-tour-endurance-backpack",
      rank: 2,
      awardType: "editors-pick",
      role: "Compact-enough day backpack",
      summary: "Tecnifibre Tour Endurance — day backpack without tournament bulk.",
      whyWon: "Still compact relative to RH Pro/XXL while covering shoes.",
      whyFits: [
        "I’d use Tour Endurance as the default non-paletero compact kit.",
        "I’d skip it if 25L is enough.",
      ],
      bestFor: ["Day backpack without XXL bulk"],
      tradeoff: "Larger than Tour 25L.",
      avoid: ["Players who want absolute minimum size"],
      instead: [
        { productId: "prod-head-tour-backpack-25l", when: "you want smaller", label: "Tour 25L" },
        { productId: "prod-nox-at10-team-bag", when: "you need thermo paletero", label: "AT10 Team" },
      ],
    }),
    pick({
      productId: "prod-nox-at10-team-bag",
      rank: 3,
      awardType: "editors-pick",
      role: "Compact thermo paletero",
      summary: "Nox AT10 Team — 42 L thermo club paletero (compact vs XXL).",
      whyWon: "Smallest honest thermo paletero award — not compact like a 25L backpack, but compact versus tournament duffels.",
      whyFits: [
        "I’d take AT10 Team when thermo matters more than backpack straps.",
        "I’d skip it if I want a true small backpack.",
      ],
      bestFor: ["Thermo without XXL", "Club paletero"],
      tradeoff: "Larger than backpack compact awards.",
      avoid: ["Players who refuse paletero form"],
      instead: [
        { productId: "prod-tecnifibre-tour-endurance-backpack", when: "you want backpack form", label: "Tour Endurance" },
      ],
    }),
  ],
  consideredProducts: [
    considered("prod-babolat-rh-pro-padel", "Tournament volume — rejected.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-nox-at10-xxl-bag", "XXL — rejected.", "rejected", { reasonCode: "context-mismatch" }),
    considered("prod-bullpadel-vertex-backpack", "Vertex backpack — shortlisted compact thermo alternative.", "shortlisted"),
  ],
  buyingAdvice: "Compact means you accept less spare-racket capacity. Be honest about what you carry.",
  relatedGuideIds: ["best-padel-backpacks", "best-padel-bags-commuting"],
  hubImageSrc: "/images/padel/bags/head-tour-team-elite-hero.jpg",
  hubImageAlt: "Compact padel bag",
});
