import type { ProductFamily } from "@/domain/products/types";

const cat = "cat-padel-rackets" as const;

export const padelRacketFamilies: ProductFamily[] = [
  {
    id: "fam-nox-at10",
    brandId: "brand-nox",
    name: "AT10 Genius",
    slug: "nox-at10-genius",
    categoryId: cat,
    description:
      "Agustín Tapia’s Genius line: drop/tear Genius vs diamond Attack, 12K vs 18K faces.",
    productIds: [
      "prod-nox-at10-18k-2026",
      "prod-nox-at10-12k-2026",
      "prod-nox-at10-attack-18k-2026",
      "prod-nox-at10-attack-12k-2026",
    ],
  },
  {
    id: "fam-nox-equation",
    brandId: "brand-nox",
    name: "Equation",
    slug: "nox-equation",
    categoryId: cat,
    description: "Nox Equation comfort/control rounds, including Equation Soft.",
    productIds: ["prod-nox-equation-soft-2026"],
  },
  {
    id: "fam-nox-ml10",
    brandId: "brand-nox",
    name: "ML10",
    slug: "nox-ml10",
    categoryId: cat,
    description: "Miguel Lamperti ML10 cup line.",
    productIds: ["prod-nox-ml10-pro-cup"],
  },
  {
    id: "fam-bullpadel-vertex",
    brandId: "brand-bullpadel",
    name: "Vertex",
    slug: "bullpadel-vertex",
    categoryId: cat,
    description: "Bullpadel Vertex family including Hybrid, W and Advance; 04 is previous-generation.",
    productIds: [
      "prod-bullpadel-vertex-05",
      "prod-bullpadel-vertex-05-hybrid",
      "prod-bullpadel-vertex-05-w",
      "prod-bullpadel-vertex-advance",
      "prod-bullpadel-vertex-04",
    ],
  },
  {
    id: "fam-bullpadel-hack",
    brandId: "brand-bullpadel",
    name: "Hack",
    slug: "bullpadel-hack",
    categoryId: cat,
    description: "Bullpadel Hack attack family including Hybrid and Comfort; 03 is previous-generation.",
    productIds: [
      "prod-bullpadel-hack-04",
      "prod-bullpadel-hack-04-hybrid",
      "prod-bullpadel-hack-04-comfort",
      "prod-bullpadel-hack-03",
    ],
  },
  {
    id: "fam-bullpadel-neuron",
    brandId: "brand-bullpadel",
    name: "Neuron",
    slug: "bullpadel-neuron",
    categoryId: cat,
    description: "Bullpadel Neuron control/precision line including Edge.",
    productIds: ["prod-bullpadel-neuron-02", "prod-bullpadel-neuron-02-edge"],
  },
  {
    id: "fam-bullpadel-xplo",
    brandId: "brand-bullpadel",
    name: "XPLO",
    slug: "bullpadel-xplo",
    categoryId: cat,
    description: "Bullpadel XPLO geometric power line including Comfort.",
    productIds: ["prod-bullpadel-xplo", "prod-bullpadel-xplo-comfort"],
  },
  {
    id: "fam-bullpadel-ionic",
    brandId: "brand-bullpadel",
    name: "Ionic",
    slug: "bullpadel-ionic",
    categoryId: cat,
    description: "Bullpadel Ionic intermediate line.",
    productIds: ["prod-bullpadel-ionic-light"],
  },
  {
    id: "fam-bullpadel-indiga",
    brandId: "brand-bullpadel",
    name: "Indiga",
    slug: "bullpadel-indiga",
    categoryId: cat,
    description: "Bullpadel Indiga beginner/club line.",
    productIds: ["prod-bullpadel-indiga-ctr"],
  },
  {
    id: "fam-adidas-metalbone",
    brandId: "brand-adidas-padel",
    name: "Metalbone",
    slug: "adidas-metalbone",
    categoryId: cat,
    description: "Adidas Metalbone 3.5 / 2026 family. 3.3 is previous-generation.",
    productIds: [
      "prod-adidas-metalbone-3-5-2026",
      "prod-adidas-metalbone-hrd",
      "prod-adidas-metalbone-ctrl",
      "prod-adidas-metalbone-team-light",
      "prod-adidas-metalbone-3-3-2026",
    ],
  },
  {
    id: "fam-adidas-cross-it",
    brandId: "brand-adidas-padel",
    name: "Cross It",
    slug: "adidas-cross-it",
    categoryId: cat,
    description: "Adidas Cross It aero/maneuverability line.",
    productIds: ["prod-adidas-cross-it-light", "prod-adidas-cross-it-ctrl"],
  },
  {
    id: "fam-adidas-arrow-hit",
    brandId: "brand-adidas-padel",
    name: "Arrow Hit",
    slug: "adidas-arrow-hit",
    categoryId: cat,
    description: "Adidas Arrow Hit 2026 balance-tuned line replacing older Adipower control slots.",
    productIds: ["prod-adidas-arrow-hit-ctrl", "prod-adidas-arrow-hit-attk"],
  },
  {
    id: "fam-adidas-rx",
    brandId: "brand-adidas-padel",
    name: "RX / Match",
    slug: "adidas-rx-match",
    categoryId: cat,
    description: "Adidas beginner/club Match and RX-adjacent frames.",
    productIds: ["prod-adidas-match-light"],
  },
  {
    id: "fam-head-coello",
    brandId: "brand-head-padel",
    name: "Coello",
    slug: "head-coello",
    categoryId: cat,
    description: "HEAD Arturo Coello diamond family: Pro, Motion, Team.",
    productIds: [
      "prod-head-coello-pro",
      "prod-head-coello-motion",
      "prod-head-coello-team",
    ],
  },
  {
    id: "fam-head-extreme",
    brandId: "brand-head-padel",
    name: "Extreme",
    slug: "head-extreme",
    categoryId: cat,
    description: "HEAD Extreme padel family: Pro, Motion.",
    productIds: ["prod-head-extreme-pro-padel", "prod-head-extreme-motion-2026"],
  },
  {
    id: "fam-head-gravity",
    brandId: "brand-head-padel",
    name: "Gravity",
    slug: "head-gravity",
    categoryId: cat,
    description: "HEAD Gravity control-oriented padel family.",
    productIds: ["prod-head-gravity-pro", "prod-head-gravity-motion"],
  },
  {
    id: "fam-head-speed-padel",
    brandId: "brand-head-padel",
    name: "Speed",
    slug: "head-speed-padel",
    categoryId: cat,
    description: "HEAD Speed padel family.",
    productIds: ["prod-head-speed-pro"],
  },
  {
    id: "fam-head-one",
    brandId: "brand-head-padel",
    name: "One",
    slug: "head-one",
    categoryId: cat,
    description: "HEAD One ultralight / beginner-accessible padel frames.",
    productIds: ["prod-head-one-ultralight"],
  },
  {
    id: "fam-babolat-viper",
    brandId: "brand-babolat-padel",
    name: "Viper",
    slug: "babolat-viper",
    categoryId: cat,
    description: "Babolat Viper family: Technical, Counter, Air.",
    productIds: [
      "prod-babolat-technical-viper",
      "prod-babolat-counter-viper",
      "prod-babolat-air-viper",
    ],
  },
  {
    id: "fam-babolat-veron",
    brandId: "brand-babolat-padel",
    name: "Veron",
    slug: "babolat-veron",
    categoryId: cat,
    description: "Babolat Veron / Air Veron accessible line.",
    productIds: ["prod-babolat-air-veron"],
  },
  {
    id: "fam-wilson-bela",
    brandId: "brand-wilson-padel",
    name: "Bela",
    slug: "wilson-bela",
    categoryId: cat,
    description: "Wilson Bela padel family.",
    productIds: ["prod-wilson-bela-pro"],
  },
  {
    id: "fam-wilson-blade-padel",
    brandId: "brand-wilson-padel",
    name: "Blade",
    slug: "wilson-blade-padel",
    categoryId: cat,
    description: "Wilson Blade padel family.",
    productIds: ["prod-wilson-blade-pro-padel"],
  },
  {
    id: "fam-siux-diablo",
    brandId: "brand-siux",
    name: "Diablo",
    slug: "siux-diablo",
    categoryId: cat,
    description: "Siux Diablo Pro racket line (not the Diablo shoe model).",
    productIds: ["prod-siux-diablo"],
  },
  {
    id: "fam-siux-electra",
    brandId: "brand-siux",
    name: "Electra",
    slug: "siux-electra",
    categoryId: cat,
    description: "Siux Electra racket line.",
    productIds: ["prod-siux-electra"],
  },
  {
    id: "fam-siux-fenix",
    brandId: "brand-siux",
    name: "Fenix",
    slug: "siux-fenix",
    categoryId: cat,
    description: "Siux Fenix racket line.",
    productIds: ["prod-siux-fenix"],
  },
  {
    id: "fam-starvie-titania",
    brandId: "brand-starvie",
    name: "Titania",
    slug: "starvie-titania",
    categoryId: cat,
    description: "StarVie Titania line.",
    productIds: ["prod-starvie-titania-kepler"],
  },
  {
    id: "fam-starvie-basalto",
    brandId: "brand-starvie",
    name: "Basalto",
    slug: "starvie-basalto",
    categoryId: cat,
    description: "StarVie Basalto line.",
    productIds: ["prod-starvie-basalto-osiris"],
  },
  {
    id: "fam-starvie-astrum",
    brandId: "brand-starvie",
    name: "Astrum",
    slug: "starvie-astrum",
    categoryId: cat,
    description: "StarVie Astrum current versatile line.",
    productIds: ["prod-starvie-astrum"],
  },
  {
    id: "fam-tecnifibre-wall",
    brandId: "brand-tecnifibre-padel",
    name: "Wall Breaker",
    slug: "tecnifibre-wall-breaker",
    categoryId: cat,
    description: "Tecnifibre Wall Breaker padel family.",
    productIds: ["prod-tecnifibre-wall-breaker-365-2026"],
  },
  {
    id: "fam-kuikma-pr",
    brandId: "brand-kuikma",
    name: "PR",
    slug: "kuikma-pr",
    categoryId: cat,
    description: "Kuikma PR Decathlon padel line.",
    productIds: [
      "prod-kuikma-pr-soft-500",
      "prod-kuikma-pr-hybrid-carbon",
      "prod-kuikma-pr-comfort-soft",
    ],
  },
  {
    id: "fam-drop-shot-canyon",
    brandId: "brand-drop-shot",
    name: "Canyon",
    slug: "drop-shot-canyon",
    categoryId: cat,
    description: "Drop Shot Canyon racket line.",
    productIds: ["prod-drop-shot-canyon-pro"],
  },
  {
    id: "fam-varlion-lw",
    brandId: "brand-varlion",
    name: "LW",
    slug: "varlion-lw",
    categoryId: cat,
    description: "Varlion LW racket line.",
    productIds: ["prod-varlion-lw-carbon-difusor"],
  },
  {
    id: "fam-oxdog-sense",
    brandId: "brand-oxdog",
    name: "Sense",
    slug: "oxdog-sense",
    categoryId: cat,
    description: "Oxdog Sense round/control family.",
    productIds: ["prod-oxdog-sense-pro-2026"],
  },
  {
    id: "fam-royal-m27",
    brandId: "brand-royal-padel",
    name: "M27",
    slug: "royal-padel-m27",
    categoryId: cat,
    description: "Royal Padel M27 control line.",
    productIds: ["prod-royal-padel-rp-m27-2026"],
  },
  {
    id: "fam-black-crown-special",
    brandId: "brand-black-crown",
    name: "Special",
    slug: "black-crown-special",
    categoryId: cat,
    description: "Black Crown Special line.",
    productIds: ["prod-black-crown-special-one-soft"],
  },
  {
    id: "fam-lok-maxx",
    brandId: "brand-lok",
    name: "Maxx",
    slug: "lok-maxx",
    categoryId: cat,
    description: "Lok Maxx racket line.",
    productIds: ["prod-lok-maxx-flow"],
  },
];
