import type { CatalogProductMediaSource } from "@/content/catalog-product-media";

/**
 * Authentic padel-racket packshots that are not already in CATALOG_PRODUCT_MEDIA.
 * CATALOG wins on ID collision — do not register logos, lifestyle og:images,
 * collages, or a different model's face print.
 */
export const PADEL_RACKET_PRODUCT_MEDIA: Record<string, CatalogProductMediaSource> = {
  "prod-adidas-metalbone-3-5-2026": {
    productId: "prod-adidas-metalbone-3-5-2026",
    src: "/images/padel/products/adidas-metalbone-3-5-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7521-padel-racket-adidas-metalbone-2026-ale-galan-8435739405802.html",
    source: "adidas official store (allforpadel.com) Metalbone 2026 — Ale Galán",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-metalbone-ctrl": {
    productId: "prod-adidas-metalbone-ctrl",
    src: "/images/padel/products/adidas-metalbone-ctrl-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7525-padel-racket-adidas-metalbone-ctrl-2026-8435739405819.html",
    source: "adidas official store (allforpadel.com) Metalbone CTRL 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-metalbone-team-light": {
    productId: "prod-adidas-metalbone-team-light",
    src: "/images/padel/products/adidas-metalbone-team-light-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7535-padel-racket-adidas-metalbone-team-light-2026-8435739405864.html",
    source: "adidas official store (allforpadel.com) Metalbone Team Light 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-arrow-hit-ctrl": {
    productId: "prod-adidas-arrow-hit-ctrl",
    src: "/images/padel/products/adidas-arrow-hit-ctrl-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7526-padel-racket-adidas-arrow-hit-ctrl-8435739405895.html",
    source: "adidas official store (allforpadel.com) Arrow Hit CTRL",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-match-light": {
    productId: "prod-adidas-match-light",
    src: "/images/padel/products/adidas-match-light-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7495-padel-racket-adidas-match-light-2026-8435739406076.html",
    source: "adidas official store (allforpadel.com) Match Light 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-nox-at10-attack-18k-2026": {
    productId: "prod-nox-at10-attack-18k-2026",
    src: "/images/padel/products/nox-at10-genius-attack-18k-2026-hero.jpg",
    sourceUrl:
      "https://noxsport.com/en/products/pala-at10-genius-attack-18k-alum-2026-by-agustin-tapia",
    source: "NOX (noxsport.com) AT10 Genius Attack 18K Alum 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-nox-equation-soft-2026": {
    productId: "prod-nox-equation-soft-2026",
    src: "/images/padel/products/nox-equation-soft-advanced-2026-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/pala-equation-soft-advanced",
    source: "NOX (noxsport.com) Equation Soft Advanced 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-starvie-astrum": {
    productId: "prod-starvie-astrum",
    src: "/images/padel/products/starvie-astrum-hero.jpg",
    sourceUrl: "https://starvie.com/en/products/astrum",
    source: "StarVie (starvie.com) Astrum+",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-kuikma-pr-comfort-soft": {
    productId: "prod-kuikma-pr-comfort-soft",
    src: "/images/padel/products/kuikma-pr-comfort-soft-hero.jpg",
    sourceUrl: "https://en.decathlon.com.sa/products/padel-racket-pr-comfort-soft",
    source: "Decathlon (Kuikma) PR Comfort Soft packshot",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-starvie-titania-kepler": {
    productId: "prod-starvie-titania-kepler",
    src: "/images/padel/products/starvie-titania-kepler-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.es/star-vie/8032-star-vie-titania-kepler-pro-20.html",
    source: "Zona de Padel CDN — StarVie Titania 2.0 Kepler packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-tecnifibre-wall-breaker-365-2026": {
    productId: "prod-tecnifibre-wall-breaker-365-2026",
    src: "/images/padel/products/tecnifibre-wall-breaker-365-hero.jpg",
    sourceUrl:
      "https://www.greavessports.com/products/wall-breaker-365-padel-racket-black-yellow",
    source: "Greaves Sports Shopify CDN — Tecnifibre Wall Breaker 365",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-bullpadel-vertex-05-hybrid": {
    productId: "prod-bullpadel-vertex-05-hybrid",
    src: "/images/padel/products/bullpadel-vertex-05-hybrid-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/bullpadel/13550-bullpadel-vertex-05-hybrid-2026.html",
    source: "Zona de Padel CDN — Bullpadel Vertex 05 Hybrid 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-vertex-05-w": {
    productId: "prod-bullpadel-vertex-05-w",
    src: "/images/padel/products/bullpadel-vertex-05-w-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/bullpadel/13552-bullpadel-vertex-05-woman-2026.html",
    source: "Zona de Padel CDN — Bullpadel Vertex 05 Woman 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-hack-04-hybrid": {
    productId: "prod-bullpadel-hack-04-hybrid",
    src: "/images/padel/products/bullpadel-hack-04-hybrid-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.es/bullpadel/13554-bullpadel-hack-04-hybrid-2026.html",
    source: "Zona de Padel CDN — Bullpadel Hack 04 Hybrid 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-hack-04-comfort": {
    productId: "prod-bullpadel-hack-04-comfort",
    src: "/images/padel/products/bullpadel-hack-04-comfort-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.es/bullpadel/13555-bullpadel-hack-04-comfort-2026.html",
    source: "Zona de Padel CDN — Bullpadel Hack 04 Comfort 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-neuron-02": {
    productId: "prod-bullpadel-neuron-02",
    src: "/images/padel/products/bullpadel-neuron-02-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.es/bullpadel/13556-bullpadel-neuron-02-2026.html",
    source: "Zona de Padel CDN — Bullpadel Neuron 02 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-neuron-02-edge": {
    productId: "prod-bullpadel-neuron-02-edge",
    src: "/images/padel/products/bullpadel-neuron-02-edge-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/bullpadel/13558-bullpadel-neuron-02-edge-2026.html",
    source: "Zona de Padel CDN — Bullpadel Neuron 02 Edge 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-xplo": {
    productId: "prod-bullpadel-xplo",
    src: "/images/padel/products/bullpadel-xplo-hero.jpg",
    sourceUrl: "https://www.zonadepadel.com/bullpadel/13559-bullpadel-xplo-2026.html",
    source: "Zona de Padel CDN — Bullpadel XPLO 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-xplo-comfort": {
    productId: "prod-bullpadel-xplo-comfort",
    src: "/images/padel/products/bullpadel-xplo-comfort-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.es/bullpadel/13560-bullpadel-xplo-comfort-2026.html",
    source: "Zona de Padel CDN — Bullpadel XPLO Comfort 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-ionic-light": {
    productId: "prod-bullpadel-ionic-light",
    src: "/images/padel/products/bullpadel-ionic-light-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/bullpadel/13575-bullpadel-ionic-light-2026.html",
    source: "Zona de Padel CDN — Bullpadel Ionic Light 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-vertex-advance": {
    productId: "prod-bullpadel-vertex-advance",
    src: "/images/padel/products/bullpadel-vertex-advance-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/bullpadel/14397-bullpadel-vertex-advance-2026.html",
    source: "Zona de Padel CDN — Bullpadel Vertex Advance 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-bullpadel-indiga-ctr": {
    productId: "prod-bullpadel-indiga-ctr",
    src: "/images/padel/products/bullpadel-indiga-ctr-hero.jpg",
    sourceUrl:
      "https://www.padelreference.com/en/padel-rackets/p/bullpadel-indiga-ctr-26",
    source: "Padelreference / authorized Bullpadel Indiga CTR 26 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
  },
  "prod-adidas-cross-it-light": {
    productId: "prod-adidas-cross-it-light",
    src: "/images/padel/products/adidas-cross-it-light-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7528-padel-racket-adidas-cross-it-light-2026-martita-ortega-8435739405956.html",
    source: "adidas official store (allforpadel.com) Cross It Light 2026 — Martita Ortega",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-cross-it-ctrl": {
    productId: "prod-adidas-cross-it-ctrl",
    src: "/images/padel/products/adidas-cross-it-ctrl-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7527-padel-racket-adidas-cross-it-ctrl-2026-8435739405949.html",
    source: "adidas official store (allforpadel.com) Cross It CTRL 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-arrow-hit-attk": {
    productId: "prod-adidas-arrow-hit-attk",
    src: "/images/padel/products/adidas-arrow-hit-attk-2026-hero.jpg",
    sourceUrl:
      "https://allforpadel.com/en/padel-rackets/7523-padel-racket-adidas-arrow-hit-8435739405888.html",
    source: "adidas official store (allforpadel.com) Arrow Hit 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-adidas-metalbone-3-3-2026": {
    productId: "prod-adidas-metalbone-3-3-2026",
    src: "/images/padel/products/adidas-metalbone-3-3-hero.jpg",
    sourceUrl: "https://www.zonadepadel.com/adidas-padel/9362-adidas-metalbone-33.html",
    source: "Zona de Padel CDN — Adidas Metalbone 3.3 packshot (not Pro EDT / 3.5)",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-head-coello-motion": {
    productId: "prod-head-coello-motion",
    src: "/images/padel/products/head-coello-motion-hero.jpg",
    sourceUrl: "https://padelusa.com/products/head-coello-motion-2026-padel-racket",
    source: "Padel USA Shopify CDN — HEAD Coello Motion 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-coello-team": {
    productId: "prod-head-coello-team",
    src: "/images/padel/products/head-coello-team-hero.jpg",
    sourceUrl: "https://padelusa.com/products/head-coello-team-2026-padel-racket",
    source: "Padel USA Shopify CDN — HEAD Coello Team 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-gravity-pro": {
    productId: "prod-head-gravity-pro",
    src: "/images/padel/products/head-gravity-pro-hero.jpg",
    sourceUrl: "https://www.padelreference.com/en/padel-rackets/p/head-gravity-pro-2024",
    source: "Padelreference — HEAD Gravity Pro (item 224004) packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-gravity-motion": {
    productId: "prod-head-gravity-motion",
    src: "/images/padel/products/head-gravity-motion-hero.jpg",
    sourceUrl:
      "https://www.padelreference.com/en/padel-rackets/p/head-gravity-motion-2024",
    source: "Padelreference — HEAD Gravity Motion (item 224014) packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-speed-pro": {
    productId: "prod-head-speed-pro",
    src: "/images/padel/products/head-speed-pro-hero.jpg",
    sourceUrl: "https://www.padelreference.com/en/palas-de-padel/p/head-speed-pro-2025",
    source: "Padelreference — HEAD Speed Pro (item 221065) packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-one-ultralight": {
    productId: "prod-head-one-ultralight",
    src: "/images/padel/products/head-one-ultralight-hero.jpg",
    sourceUrl:
      "https://www.padelreference.com/en/padelschlager/p/head-one-ultralight-black-2025",
    source: "Padelreference — HEAD One Ultralight packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 500,
    height: 500,
  },
  "prod-babolat-air-viper": {
    productId: "prod-babolat-air-viper",
    src: "/images/padel/products/babolat-air-viper-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/air-viper-2.6/150176.html",
    source: "Babolat (media.babolat.com) Air Viper 2.6 Face packshot",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-babolat-air-veron": {
    productId: "prod-babolat-air-veron",
    src: "/images/padel/products/babolat-air-veron-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/air-veron-2.6/150180.html",
    source: "Babolat (media.babolat.com) Air Veron 2.6 Face packshot",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-siux-electra": {
    productId: "prod-siux-electra",
    src: "/images/padel/products/siux-electra-pro-2026-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/siux/13932-siux-electra-pro-fire-red-2026.html",
    source: "Zona de Padel CDN — Siux Electra Pro Fire Red 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-siux-fenix": {
    productId: "prod-siux-fenix",
    src: "/images/padel/products/siux-fenix-pro-2026-hero.jpg",
    sourceUrl:
      "https://www.zonadepadel.com/siux/13935-siux-fenix-pro-black-2026.html",
    source: "Zona de Padel CDN — Siux Fenix Pro Black 2026 packshot",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
  },
  "prod-kuikma-pr-hybrid-carbon": {
    productId: "prod-kuikma-pr-hybrid-carbon",
    src: "/images/padel/products/kuikma-pr-hybrid-carbon-hero.jpg",
    sourceUrl:
      "https://www.decathlon.co.id/en-ID/p/padel-racket-pr-hybrid-carbon-coki-nieto-kuikma-8979558.html",
    source: "Decathlon (contents.mediadecathlon.com) Kuikma PR Hybrid Carbon Coki Nieto",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
};
