import type { Brand } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";

const meta = publishedMeta();

function b(
  id: string,
  name: string,
  slug: string,
  country: string,
  description: string,
  homepage?: string,
  logo?: string,
): Brand {
  return { id, name, slug, country, description, homepage, logo, ...meta };
}

/** Running brands added in Prompt 14 catalog expansion (beyond core seed brands). */
export const runningCatalogBrands: Brand[] = [
  b("brand-puma", "PUMA", "puma", "Germany", "Performance running footwear and apparel.", "https://www.puma.com", "/images/brands/puma-logo.svg"),
  b("brand-on", "On", "on", "Switzerland", "CloudTec road running shoes.", "https://www.on.com", "/images/brands/on-logo.svg"),
  b("brand-mizuno", "Mizuno", "mizuno", "Japan", "Wave plate running footwear.", "https://www.mizuno.com", "/images/brands/mizuno-logo.svg"),
  b("brand-altra", "Altra", "altra", "USA", "Zero-drop foot-shaped running shoes.", "https://www.altrarunning.com", "/images/brands/altra-logo.svg"),
  b("brand-topo", "Topo Athletic", "topo-athletic", "USA", "Roomy toe-box road and trail shoes.", "https://www.topoathletic.com", "/images/brands/topo-logo.svg"),
  b("brand-inov8", "Inov-8", "inov-8", "UK", "Trail and fell running footwear.", "https://www.inov-8.com", "/images/brands/inov8-logo.svg"),
  b("brand-polar", "Polar", "polar", "Finland", "Heart-rate training systems and GPS watches.", "https://www.polar.com", "/images/brands/polar-logo.svg"),
  b("brand-suunto", "Suunto", "suunto", "Finland", "Outdoor GPS watches for endurance sport.", "https://www.suunto.com", "/images/brands/suunto-logo.svg"),
  b("brand-apple", "Apple", "apple", "USA", "Apple Watch sports and smartwatch ecosystem.", "https://www.apple.com", "/images/brands/apple-logo.svg"),
  b("brand-samsung", "Samsung", "samsung", "South Korea", "Galaxy Watch sports and smartwatch ecosystem.", "https://www.samsung.com", "/images/brands/samsung-logo.svg"),
  b("brand-amazfit", "Amazfit", "amazfit", "China", "Value GPS sports watches for outdoor and running.", "https://www.amazfit.com", "/images/brands/amazfit-logo.svg"),
  b("brand-wahoo", "Wahoo", "wahoo", "USA", "Cycling and training sensors including HR straps.", "https://www.wahoofitness.com", "/images/brands/wahoo-logo.svg"),
  b("brand-scosche", "Scosche", "scosche", "USA", "Optical armband heart rate monitors for training.", "https://www.scosche.com", "/images/brands/scosche-logo.svg"),
  b("brand-nathan", "Nathan", "nathan", "USA", "Running hydration vests, belts and handhelds.", "https://www.nathansports.com", "/images/brands/nathan-logo.svg"),
  b("brand-ultimate-direction", "Ultimate Direction", "ultimate-direction", "USA", "Trail race vests and hydration systems.", "https://ultimatedirection.com", "/images/brands/ultimate-direction-logo.svg"),
  b("brand-camelbak", "CamelBak", "camelbak", "USA", "Hydration packs and reservoirs.", "https://www.camelbak.com", "/images/brands/camelbak-logo.svg"),
  b("brand-osprey", "Osprey", "osprey", "USA", "Running and hiking packs including Duro/Dyna.", "https://www.osprey.com", "/images/brands/osprey-logo.svg"),
  b("brand-flipbelt", "FlipBelt", "flipbelt", "USA", "Minimal stretch running waist belts.", "https://flipbelt.com", "/images/brands/flipbelt-logo.svg"),
  b("brand-spibelt", "SPIbelt", "spibelt", "USA", "Expandable running waist pouches.", "https://www.spibelt.com", "/images/brands/spibelt-logo.svg"),
  b("brand-hydrapak", "HydraPak", "hydrapak", "USA", "Soft flasks and hydration reservoirs.", "https://www.hydrapak.com", "/images/brands/hydrapak-logo.svg"),
  b("brand-patagonia", "Patagonia", "patagonia", "USA", "Trail running vests and outdoor apparel.", "https://www.patagonia.com", "/images/brands/patagonia-logo.svg"),
  b("brand-uswe", "USWE", "uswe", "Sweden", "No-bounce hydration vests with NDM harness.", "https://uswe.com", "/images/brands/uswe-logo.svg"),
  b("brand-ultraspire", "UltrAspire", "ultraspire", "USA", "Race vests and running belts for trail and ultra.", "https://ultraspire.com", "/images/brands/ultraspire-logo.svg"),
  b("brand-compressport", "Compressport", "compressport", "Switzerland", "Compression apparel, race belts and ultra packs.", "https://www.compressport.com", "/images/brands/compressport-logo.svg"),
  b("brand-raidlight", "RaidLight", "raidlight", "France", "Trail and ultra race vests and mountain gear.", "https://www.raidlight.com", "/images/brands/raidlight-logo.svg"),
  b("brand-nnormal", "NNormal", "nnormal", "Spain", "Kilian Jornet co-founded trail brand: Kjerag race-trail, Tomir long-technical, and a race vest.", "https://www.nnormal.com", "/images/brands/nnormal-logo.svg"),
  b("brand-naked", "Naked", "naked", "USA", "Minimal stretch running bands for race essentials.", "https://nakedrunningband.com", "/images/brands/naked-logo.svg"),
  b("brand-decathlon", "Decathlon", "decathlon", "France", "Value trail running gear including Kiprun vests.", "https://www.decathlon.com", "/images/brands/decathlon-logo.svg"),
  b("brand-tracksmith", "Tracksmith", "tracksmith", "USA", "Performance running apparel with collegiate aesthetic.", "https://www.tracksmith.com", "/images/brands/tracksmith-logo.svg"),
  b("brand-janji", "Janji", "janji", "USA", "Running apparel with storage-forward shorts and travel kits.", "https://www.janji.com", "/images/brands/janji-logo.svg"),
  b("brand-rabbit", "Rabbit", "rabbit", "USA", "Lightweight race and training running apparel.", "https://www.runinrabbit.com", "/images/brands/rabbit-logo.svg"),
  b("brand-the-north-face", "The North Face", "the-north-face", "USA", "Outdoor and Flight Series running apparel.", "https://www.thenorthface.com", "/images/brands/the-north-face-logo.svg"),
  b("brand-odlo", "Odlo", "odlo", "Switzerland", "Base layers and temperature-regulating run apparel.", "https://www.odlo.com", "/images/brands/odlo-logo.svg"),
  b("brand-ciele", "Ciele", "ciele", "Canada", "Technical running caps and headwear.", "https://www.cieleathletics.com", "/images/brands/ciele-logo.svg"),
  b("brand-smartwool", "Smartwool", "smartwool", "USA", "Merino running socks and cold-weather accessories.", "https://www.smartwool.com", "/images/brands/smartwool-logo.svg"),
  b("brand-darn-tough", "Darn Tough", "darn-tough", "USA", "Guaranteed merino performance socks.", "https://darntough.com", "/images/brands/darn-tough-logo.svg"),
  b("brand-stance", "Stance", "stance", "USA", "Performance and lifestyle socks including run lines.", "https://www.stance.com", "/images/brands/stance-logo.svg"),
  b("brand-saxx", "SAXX", "saxx", "Canada", "Performance underwear with BallPark pouch support.", "https://www.saxxunderwear.com", "/images/brands/saxx-logo.svg"),
  b("brand-leki", "LEKI", "leki", "Germany", "Trail poles and running pole quivers.", "https://www.leki.com", "/images/brands/leki-logo.svg"),
  b("brand-shokz", "Shokz", "shokz", "China", "Open-ear bone-conduction headphones for sport.", "https://www.shokz.com", "/images/brands/shokz-logo.svg"),
  b("brand-bose", "Bose", "bose", "USA", "Open-ear and sport audio products.", "https://www.bose.com", "/images/brands/bose-logo.svg"),
  b("brand-oakley", "Oakley", "oakley", "USA", "Performance sport eyewear.", "https://www.oakley.com", "/images/brands/oakley-logo.svg"),
  b("brand-goodr", "goodr", "goodr", "USA", "Affordable no-slip running sunglasses.", "https://www.goodr.com", "/images/brands/goodr-logo.svg"),
  b("brand-julbo", "Julbo", "julbo", "France", "Trail and mountain sport sunglasses.", "https://www.julbo.com"),
  b("brand-petzl", "Petzl", "petzl", "France", "Headlamps for trail and night running.", "https://www.petzl.com", "/images/brands/petzl-logo.svg"),
  b("brand-black-diamond", "Black Diamond", "black-diamond", "USA", "Outdoor headlamps and trail gear.", "https://www.blackdiamondequipment.com", "/images/brands/black-diamond-logo.svg"),
  b("brand-silva", "Silva", "silva", "Sweden", "Trail running headlamps and navigation tools.", "https://silvasweden.com"),
  b("brand-feetures", "Feetures", "feetures", "USA", "Anatomical performance running socks.", "https://www.feetures.com", "/images/brands/feetures-logo.svg"),
  b("brand-balega", "Balega", "balega", "South Africa", "Cushioned running socks.", "https://www.balega.com", "/images/brands/balega-logo.svg"),
  b("brand-injinji", "Injinji", "injinji", "USA", "Toe-sock designs for blister management.", "https://www.injinji.com"),
  b("brand-cep", "CEP", "cep", "Germany", "Compression socks and running apparel.", "https://www.cepcompression.com", "/images/brands/cep-logo.svg"),
  b("brand-bombas", "Bombas", "bombas", "USA", "Comfort-focused performance and lifestyle socks including running lines.", "https://bombas.com"),
  b("brand-swiftwick", "Swiftwick", "swiftwick", "USA", "Thin secure-fit performance running socks.", "https://www.swiftwick.com"),
  b("brand-hilly", "Hilly", "hilly", "UK", "Race and training running socks including Marathon Fresh.", "https://www.hillysocks.com"),
  b("brand-drymax", "Drymax", "drymax", "USA", "Dual-layer moisture-management running socks.", "https://www.drymaxsports.com"),
  b("brand-sockwell", "Sockwell", "sockwell", "USA", "Merino-blend compression and cushion running socks.", "https://www.sockwellusa.com"),
  b("brand-wrightsock", "Wrightsock", "wrightsock", "USA", "Dual-layer anti-blister running socks.", "https://www.wrightsock.com"),
  b("brand-fitletic", "Fitletic", "fitletic", "USA", "Race and essentials running belts.", "https://www.fitletic.com"),
  b("brand-buff", "BUFF", "buff", "Spain", "Multifunctional neckwear and headwear.", "https://www.buff.com", "/images/brands/buff-logo.svg"),
  b("brand-craft", "Craft", "craft", "Sweden", "Technical running apparel.", "https://www.craftsportswear.com", "/images/brands/craft-logo.svg"),
  b("brand-therabody", "Therabody", "therabody", "USA", "Percussive massage recovery devices.", "https://www.therabody.com", "/images/brands/therabody-logo.svg"),
  b("brand-hyperice", "Hyperice", "hyperice", "USA", "Recovery percussion and compression tools.", "https://hyperice.com", "/images/brands/hyperice-logo.svg"),
  b("brand-triggerpoint", "TriggerPoint", "triggerpoint", "USA", "Foam rollers and mobility tools.", "https://www.triggerpointtherapy.com"),
  b("brand-oofos", "OOFOS", "oofos", "USA", "Recovery footwear with cushioned midsoles.", "https://www.oofos.com", "/images/brands/oofos-logo.svg"),
  b("brand-nite-ize", "Nite Ize", "nite-ize", "USA", "Clip lights and outdoor visibility accessories.", "https://www.niteize.com"),
  b("brand-body-glide", "Body Glide", "body-glide", "USA", "Anti-chafe balms for runners.", "https://www.bodyglide.com"),
  b("brand-jabra", "Jabra", "jabra", "Denmark", "Sport true-wireless earbuds for training.", "https://www.jabra.com", "/images/brands/jabra-logo.svg"),
  b("brand-sony", "Sony", "sony", "Japan", "Open-ear and sport wireless audio.", "https://www.sony.com", "/images/brands/sony-logo.svg"),
  b("brand-beats", "Beats", "beats", "USA", "Ear-hook and sport true-wireless headphones.", "https://www.beatsbydre.com", "/images/brands/beats-logo.svg"),
  b("brand-soundcore", "soundcore", "soundcore", "China", "Value open-ear and sport earbuds from Anker.", "https://www.soundcore.com", "/images/brands/soundcore-logo.svg"),
  b("brand-huawei", "HUAWEI", "huawei", "China", "Open-ear clip earbuds for sport and commute.", "https://consumer.huawei.com"),
  b("brand-smith", "Smith", "smith", "USA", "Performance sport sunglasses with ChromaPop optics.", "https://www.smithoptics.com", "/images/brands/smith-logo.svg"),
  b("brand-rudy-project", "Rudy Project", "rudy-project", "Italy", "Race and trail performance eyewear.", "https://www.rudyproject.com"),
  b("brand-tifosi", "Tifosi", "tifosi", "USA", "Value performance running and cycling sunglasses.", "https://www.tifosioptics.com"),
  b("brand-100percent", "100%", "100-percent", "USA", "Shield and race sport eyewear.", "https://www.ride100percent.com"),
  b("brand-roka", "ROKA", "roka", "USA", "Lightweight performance sunglasses for endurance sport.", "https://www.roka.com"),
  b("brand-ledlenser", "Ledlenser", "ledlenser", "Germany", "Running and outdoor headlamps.", "https://www.ledlenser.com", "/images/brands/ledlenser-logo.svg"),
  b("brand-fenix", "Fenix", "fenix", "China", "High-output trail and outdoor headlamps.", "https://www.fenixlighting.com"),
  b("brand-biolite", "BioLite", "biolite", "USA", "Comfort-focused running headlamps.", "https://www.bioliteenergy.com"),
  b("brand-nitecore", "NITECORE", "nitecore", "China", "Compact rechargeable headlamps for night running.", "https://www.nitecore.com"),
  b("brand-knog", "Knog", "knog", "Australia", "Clip and wearable bike/run visibility lights.", "https://www.knog.com"),
  b("brand-amphipod", "Amphipod", "amphipod", "USA", "Visibility, handheld hydration and running carry accessories.", "https://www.amphipod.com"),
  b("brand-proviz", "Proviz", "proviz", "UK", "High-visibility reflective running apparel.", "https://www.provizsports.com"),
  b("brand-nightrunner", "Night Runner", "night-runner", "USA", "Shoe-mounted LED visibility lights.", "https://www.nightrunner.com"),
  b("brand-shes-birdie", "She's Birdie", "shes-birdie", "USA", "Legal personal safety alarms for runners.", "https://www.shesbirdie.com"),
  b("brand-road-id", "Road ID", "road-id", "USA", "ID bands and emergency contact wearables for runners.", "https://www.roadid.com"),
  b("brand-maurten", "Maurten", "maurten", "Sweden", "Hydrogel sports fuel for endurance racing.", "https://www.maurten.com"),
  b("brand-sis", "Science in Sport", "science-in-sport", "UK", "Gels, drink mixes and race fuel for endurance sport.", "https://www.scienceinsport.com"),
  b("brand-gu", "GU Energy", "gu-energy", "USA", "Energy gels, chews and drink mixes for runners.", "https://guenergy.com"),
  b("brand-precision-fuel", "Precision Fuel & Hydration", "precision-fuel-hydration", "UK", "Structured carb gels and electrolyte systems for endurance.", "https://www.precisionhydration.com"),
  b("brand-tailwind", "Tailwind", "tailwind", "USA", "All-in-one endurance drink mixes.", "https://www.tailwindnutrition.com"),
  b("brand-skratch", "Skratch Labs", "skratch-labs", "USA", "Real-food inspired sports drink mixes and chews.", "https://www.skratchlabs.com"),
  b("brand-clif", "Clif Bar", "clif-bar", "USA", "Energy bars, Bloks chews and shot gels.", "https://www.clifbar.com"),
  b("brand-honey-stinger", "Honey Stinger", "honey-stinger", "USA", "Honey-based gels, chews and waffles for endurance.", "https://www.honeystinger.com"),
  b("brand-spring-energy", "Spring Energy", "spring-energy", "USA", "Real-food texture energy gels for ultras.", "https://www.springenergy.co"),
  b("brand-neversecond", "Neversecond", "neversecond", "UK", "High-carb C-series race fuel gels and drinks.", "https://www.never2.com"),
  b("brand-high5", "High5", "high5", "UK", "Energy gels, drink mixes and tablets for endurance.", "https://highfive.co.uk"),
  b("brand-nuun", "Nuun", "nuun", "USA", "Electrolyte tablets for training hydration.", "https://nuunlife.com"),
  b("brand-saltstick", "SaltStick", "saltstick", "USA", "Electrolyte capsules and Fastchews for endurance sport.", "https://saltstick.com"),
  b("brand-powerbar", "PowerBar", "powerbar", "Germany", "Energy gels, bars and race fuel for endurance athletes.", "https://www.powerbar.com"),
  b("brand-enervit", "Enervit", "enervit", "Italy", "Carbo gels and race nutrition for endurance.", "https://www.enervit.com"),
  b("brand-226ers", "226ERS", "226ers", "Spain", "High-energy gels and drink mixes for endurance.", "https://www.226ers.com"),
  b("brand-huma", "Hüma", "huma", "USA", "Chia-based energy gels for runners.", "https://humagel.com"),
  b("brand-naak", "Näak", "naak", "Canada", "Ultra energy drink mixes and bars for long efforts.", "https://www.naak.com"),
  b("brand-styrkr", "STYRKR", "styrkr", "UK", "Dual-carb gels and drink mixes for endurance.", "https://styrkr.com"),
  b("brand-veloforte", "Veloforte", "veloforte", "UK", "Natural energy chews, bars and powders for endurance.", "https://www.veloforte.cc"),
  b("brand-renpho", "RENPHO", "renpho", "USA", "Value percussive massage guns for home recovery routines.", "https://renpho.com"),
  b("brand-opove", "OPOVE", "opove", "USA", "Percussive massage devices for athletes.", "https://opove.com"),
  b("brand-rad", "RAD Roller", "rad-roller", "USA", "Massage balls and mobility tools.", "https://www.radroller.com"),
  b("brand-rumbleroller", "RumbleRoller", "rumbleroller", "USA", "Textured foam rollers for soft-tissue work.", "https://www.rumbleroller.com"),
  b("brand-the-stick", "The Stick", "the-stick", "USA", "Handheld stick massage and mobility tools.", "https://www.thestick.com"),
  b("brand-2xu", "2XU", "2xu", "Australia", "Compression garments for training and recovery routines.", "https://www.2xu.com"),
  b("brand-timtam", "TimTam", "timtam", "USA", "Power massagers for athletes.", "https://timtam.tech"),
  b("brand-brazyn", "Brazyn", "brazyn", "USA", "Morph collapsible foam rollers for travel.", "https://brazynlife.com"),
  b("brand-squirrels-nut-butter", "Squirrel's Nut Butter", "squirrels-nut-butter", "USA", "Anti-chafe balms and sticks for runners.", "https://sqnutbutter.com"),
  b("brand-2toms", "2Toms", "2toms", "USA", "SportShield anti-chafe and blister-care products.", "https://www.2toms.com"),
  b("brand-dirty-girl", "Dirty Girl", "dirty-girl", "USA", "Lightweight trail running gaiters.", "https://dirtygirlgaiters.com"),
  b("brand-outdoor-research", "Outdoor Research", "outdoor-research", "USA", "Outdoor apparel and trail gaiters.", "https://www.outdoorresearch.com"),
];
