import type { ProductFamily } from "@/domain/products/types";

/** Running clothing / socks families for catalog wave 2. */
export const runningClothingFamilies: ProductFamily[] = [
  {
    id: "fam-adidas-own-the-run",
    brandId: "brand-adidas",
    name: "Own the Run",
    slug: "own-the-run",
    categoryId: "cat-running-clothing",
    description: "adidas Own the Run apparel.",
    productIds: ["prod-adidas-own-the-run-short-men", "prod-adidas-own-the-run-tee-men"],
  },
  {
    id: "fam-asics-race",
    brandId: "brand-asics",
    name: "Race",
    slug: "asics-race",
    categoryId: "cat-running-clothing",
    description: "ASICS Race singlets.",
    productIds: ["prod-asics-race-singlet-men"],
  },
  {
    id: "fam-balega-blister-resist",
    brandId: "brand-balega",
    name: "Blister Resist",
    slug: "balega-blister-resist",
    categoryId: "cat-running-socks",
    description: "Balega Blister Resist socks.",
    productIds: ["prod-balega-blister-resist"],
  },
  {
    id: "fam-brooks-canopy",
    brandId: "brand-brooks",
    name: "Canopy",
    slug: "brooks-canopy",
    categoryId: "cat-running-clothing",
    description: "Brooks Canopy run jackets.",
    productIds: ["prod-brooks-canopy-jacket-unisex"],
  },
  {
    id: "fam-brooks-chaser",
    brandId: "brand-brooks",
    name: "Chaser",
    slug: "brooks-chaser",
    categoryId: "cat-running-clothing",
    description: "Brooks Chaser run shorts.",
    productIds: ["prod-brooks-chaser-5-women"],
  },
  {
    id: "fam-brooks-dare",
    brandId: "brand-brooks",
    name: "Dare",
    slug: "brooks-dare",
    categoryId: "cat-running-clothing",
    description: "Brooks Dare run bras.",
    productIds: ["prod-brooks-dare-crossback"],
  },
  {
    id: "fam-brooks-lsd-thermal",
    brandId: "brand-brooks",
    name: "LSD Thermal",
    slug: "lsd-thermal",
    categoryId: "cat-running-clothing",
    description: "Brooks LSD Thermal run vests.",
    productIds: ["prod-brooks-lsd-thermal-vest-men"],
  },
  {
    id: "fam-brooks-method",
    brandId: "brand-brooks",
    name: "Method",
    slug: "brooks-method",
    categoryId: "cat-running-clothing",
    description: "Brooks Method run tights.",
    productIds: ["prod-brooks-method-tight-women"],
  },
  {
    id: "fam-brooks-notch-thermal",
    brandId: "brand-brooks",
    name: "Notch Thermal",
    slug: "notch-thermal",
    categoryId: "cat-running-clothing",
    description: "Brooks Notch Thermal cold layers.",
    productIds: ["prod-brooks-notch-thermal-men", "prod-brooks-notch-thermal-beanie"],
  },
  {
    id: "fam-brooks-sherpa",
    brandId: "brand-brooks",
    name: "Sherpa",
    slug: "brooks-sherpa",
    categoryId: "cat-running-clothing",
    description: "Brooks Sherpa run shorts.",
    productIds: ["prod-brooks-sherpa-7-men"],
  },
  {
    id: "fam-ciele-gocap",
    brandId: "brand-ciele",
    name: "GOCap",
    slug: "ciele-gocap",
    categoryId: "cat-running-clothing",
    description: "Ciele GOCap running caps.",
    productIds: ["prod-ciele-gocap-athletics"],
  },
  {
    id: "fam-craft-active-extreme",
    brandId: "brand-craft",
    name: "Active Extreme",
    slug: "craft-active-extreme",
    categoryId: "cat-running-clothing",
    description: "Craft Active Extreme base layers.",
    productIds: ["prod-craft-active-extreme-x-men"],
  },
  {
    id: "fam-craft-adv-essence",
    brandId: "brand-craft",
    name: "ADV Essence",
    slug: "craft-adv-essence",
    categoryId: "cat-running-clothing",
    description: "Craft ADV Essence apparel.",
    productIds: ["prod-craft-adv-essence-tight-men", "prod-craft-adv-essence-light-wind-men", "prod-craft-adv-essence-light-wind-vest-men"],
  },
  {
    id: "fam-craft-adv-lumen",
    brandId: "brand-craft",
    name: "ADV Lumen",
    slug: "craft-adv-lumen",
    categoryId: "cat-running-clothing",
    description: "Craft ADV Lumen hi-vis gloves.",
    productIds: ["prod-craft-adv-lumen-glove"],
  },
  {
    id: "fam-darn-tough-run",
    brandId: "brand-darn-tough",
    name: "Run",
    slug: "darn-tough-run",
    categoryId: "cat-running-socks",
    description: "Darn Tough run socks.",
    productIds: ["prod-darn-tough-run-1-4"],
  },
  {
    id: "fam-janji-multi",
    brandId: "brand-janji",
    name: "Multi",
    slug: "janji-multi",
    categoryId: "cat-running-clothing",
    description: "Janji Multi 2-in-1 shorts.",
    productIds: ["prod-janji-multi-short-men"],
  },
  {
    id: "fam-janji-pace",
    brandId: "brand-janji",
    name: "Pace",
    slug: "janji-pace",
    categoryId: "cat-running-clothing",
    description: "Janji Pace running shorts.",
    productIds: ["prod-janji-pace-short-women"],
  },
  {
    id: "fam-janji-rainrunner",
    brandId: "brand-janji",
    name: "Rainrunner",
    slug: "rainrunner",
    categoryId: "cat-running-clothing",
    description: "Janji Rainrunner rain jackets.",
    productIds: ["prod-janji-rainrunner-unisex"],
  },
  {
    id: "fam-janji-run-tee",
    brandId: "brand-janji",
    name: "Run Tee",
    slug: "janji-run-tee",
    categoryId: "cat-running-clothing",
    description: "Janji Run Tee.",
    productIds: ["prod-janji-run-tee-men"],
  },
  {
    id: "fam-lululemon-always-in-motion",
    brandId: "brand-lululemon",
    name: "Always In Motion",
    slug: "always-in-motion",
    categoryId: "cat-running-clothing",
    description: "lululemon Always In Motion underwear.",
    productIds: ["prod-lululemon-always-in-motion-men"],
  },
  {
    id: "fam-lululemon-energy",
    brandId: "brand-lululemon",
    name: "Energy",
    slug: "energy-bra",
    categoryId: "cat-running-clothing",
    description: "lululemon Energy bras.",
    productIds: ["prod-lululemon-energy-bra"],
  },
  {
    id: "fam-lululemon-fast-and-free",
    brandId: "brand-lululemon",
    name: "Fast and Free",
    slug: "fast-and-free",
    categoryId: "cat-running-clothing",
    description: "lululemon Fast and Free tights.",
    productIds: ["prod-lululemon-fast-and-free-women"],
  },
  {
    id: "fam-lululemon-hotty-hot",
    brandId: "brand-lululemon",
    name: "Hotty Hot",
    slug: "hotty-hot",
    categoryId: "cat-running-clothing",
    description: "lululemon Hotty Hot shorts.",
    productIds: ["prod-lululemon-hotty-hot-women"],
  },
  {
    id: "fam-lululemon-pace-breaker",
    brandId: "brand-lululemon",
    name: "Pace Breaker",
    slug: "pace-breaker",
    categoryId: "cat-running-clothing",
    description: "lululemon Pace Breaker shorts.",
    productIds: ["prod-lululemon-pace-breaker-men"],
  },
  {
    id: "fam-nb-rc-essential",
    brandId: "brand-new-balance",
    name: "RC Essential",
    slug: "nb-rc-essential",
    categoryId: "cat-running-clothing",
    description: "New Balance RC Essential shorts.",
    productIds: ["prod-nb-rc-essential-short-men"],
  },
  {
    id: "fam-nike-aerobill",
    brandId: "brand-nike",
    name: "AeroBill",
    slug: "nike-aerobill",
    categoryId: "cat-running-clothing",
    description: "Nike AeroBill / Dri-FIT run caps.",
    productIds: ["prod-nike-aerobill-cap"],
  },
  {
    id: "fam-nike-aeroswift",
    brandId: "brand-nike",
    name: "AeroSwift",
    slug: "aeroswift",
    categoryId: "cat-running-clothing",
    description: "Nike AeroSwift race singlets.",
    productIds: ["prod-nike-aeroswift-singlet-men"],
  },
  {
    id: "fam-nike-element",
    brandId: "brand-nike",
    name: "Element",
    slug: "nike-element",
    categoryId: "cat-running-clothing",
    description: "Nike Element / Therma long sleeves.",
    productIds: ["prod-nike-element-ls-men"],
  },
  {
    id: "fam-nike-fast",
    brandId: "brand-nike",
    name: "Fast",
    slug: "nike-fast",
    categoryId: "cat-running-clothing",
    description: "Nike Fast run tights.",
    productIds: ["prod-nike-fast-tight-men"],
  },
  {
    id: "fam-nike-impossibly-light",
    brandId: "brand-nike",
    name: "Impossibly Light",
    slug: "impossibly-light",
    categoryId: "cat-running-clothing",
    description: "Nike Impossibly Light jackets.",
    productIds: ["prod-nike-impossibly-light-men"],
  },
  {
    id: "fam-nike-miler",
    brandId: "brand-nike",
    name: "Miler",
    slug: "nike-miler",
    categoryId: "cat-running-clothing",
    description: "Nike Dri-FIT Miler tees.",
    productIds: ["prod-nike-dri-fit-miler-men", "prod-nike-dri-fit-miler-women"],
  },
  {
    id: "fam-nike-swoosh",
    brandId: "brand-nike",
    name: "Swoosh",
    slug: "nike-swoosh",
    categoryId: "cat-running-clothing",
    description: "Nike Swoosh sports bras.",
    productIds: ["prod-nike-swoosh-medium-support"],
  },
  {
    id: "fam-nike-therma-fit",
    brandId: "brand-nike",
    name: "Therma-FIT",
    slug: "nike-therma-fit",
    categoryId: "cat-running-clothing",
    description: "Nike Therma-FIT run gloves.",
    productIds: ["prod-nike-therma-fit-glove"],
  },
  {
    id: "fam-odlo-active-warm-eco",
    brandId: "brand-odlo",
    name: "Active Warm Eco",
    slug: "odlo-active-warm-eco",
    categoryId: "cat-running-clothing",
    description: "Odlo Active Warm Eco base layers.",
    productIds: ["prod-odlo-active-warm-eco-men", "prod-odlo-active-warm-eco-bottom-men"],
  },
  {
    id: "fam-on-performance",
    brandId: "brand-on",
    name: "Performance",
    slug: "on-performance",
    categoryId: "cat-running-clothing",
    description: "On Performance run apparel.",
    productIds: ["prod-on-performance-short-men", "prod-on-performance-tight-women"],
  },
  {
    id: "fam-on-weather",
    brandId: "brand-on",
    name: "Weather",
    slug: "on-weather",
    categoryId: "cat-running-clothing",
    description: "On Weather run jackets.",
    productIds: ["prod-on-weather-jacket-men"],
  },
  {
    id: "fam-patagonia-capilene-cool",
    brandId: "brand-patagonia",
    name: "Capilene Cool",
    slug: "capilene-cool",
    categoryId: "cat-running-clothing",
    description: "Patagonia Capilene Cool daily shirts.",
    productIds: ["prod-patagonia-capilene-cool-daily-men"],
  },
  {
    id: "fam-patagonia-capilene-midweight",
    brandId: "brand-patagonia",
    name: "Capilene Midweight",
    slug: "capilene-midweight",
    categoryId: "cat-running-clothing",
    description: "Patagonia Capilene Midweight layers.",
    productIds: ["prod-patagonia-capilene-midweight-zip-men"],
  },
  {
    id: "fam-patagonia-capilene-thermal",
    brandId: "brand-patagonia",
    name: "Capilene Thermal",
    slug: "capilene-thermal",
    categoryId: "cat-running-clothing",
    description: "Patagonia Capilene Thermal base layers.",
    productIds: ["prod-patagonia-capilene-thermal-crew-unisex"],
  },
  {
    id: "fam-patagonia-endless-run",
    brandId: "brand-patagonia",
    name: "Endless Run",
    slug: "endless-run",
    categoryId: "cat-running-clothing",
    description: "Patagonia Endless Run tights.",
    productIds: ["prod-patagonia-endless-run-tight-women"],
  },
  {
    id: "fam-patagonia-houdini",
    brandId: "brand-patagonia",
    name: "Houdini",
    slug: "houdini",
    categoryId: "cat-running-clothing",
    description: "Patagonia Houdini packable wind shells.",
    productIds: ["prod-patagonia-houdini-men"],
  },
  {
    id: "fam-patagonia-nano-puff",
    brandId: "brand-patagonia",
    name: "Nano-Puff",
    slug: "nano-puff",
    categoryId: "cat-running-clothing",
    description: "Patagonia Nano-Puff insulated pieces.",
    productIds: ["prod-patagonia-nano-puff-vest-men"],
  },
  {
    id: "fam-patagonia-strider",
    brandId: "brand-patagonia",
    name: "Strider",
    slug: "strider",
    categoryId: "cat-running-clothing",
    description: "Patagonia Strider run shorts.",
    productIds: ["prod-patagonia-strider-pro-men"],
  },
  {
    id: "fam-patagonia-trailfarer",
    brandId: "brand-patagonia",
    name: "Trailfarer",
    slug: "trailfarer",
    categoryId: "cat-running-clothing",
    description: "Patagonia Trailfarer trail shorts.",
    productIds: ["prod-patagonia-trailfarer-short-women"],
  },
  {
    id: "fam-rabbit-fuel-n-fly",
    brandId: "brand-rabbit",
    name: "Fuel n' Fly",
    slug: "fuel-n-fly",
    categoryId: "cat-running-clothing",
    description: "Rabbit Fuel n' Fly storage shorts.",
    productIds: ["prod-rabbit-fuel-n-fly-men"],
  },
  {
    id: "fam-salomon-bonatti",
    brandId: "brand-salomon",
    name: "Bonatti",
    slug: "bonatti",
    categoryId: "cat-running-clothing",
    description: "Salomon Bonatti waterproof run jackets.",
    productIds: ["prod-salomon-bonatti-wp-men", "prod-salomon-bonatti-wp-women"],
  },
  {
    id: "fam-saxx-kinetic",
    brandId: "brand-saxx",
    name: "Kinetic",
    slug: "saxx-kinetic",
    categoryId: "cat-running-clothing",
    description: "SAXX Kinetic run underwear.",
    productIds: ["prod-saxx-kinetic-hd-men"],
  },
  {
    id: "fam-smartwool-run",
    brandId: "brand-smartwool",
    name: "Run Targeted Cushion",
    slug: "smartwool-run",
    categoryId: "cat-running-socks",
    description: "Smartwool Run Targeted Cushion socks.",
    productIds: ["prod-smartwool-run-targeted-cushion"],
  },
  {
    id: "fam-smartwool-thermal-merino",
    brandId: "brand-smartwool",
    name: "Thermal Merino",
    slug: "smartwool-thermal-merino",
    categoryId: "cat-running-clothing",
    description: "Smartwool Thermal Merino gloves.",
    productIds: ["prod-smartwool-thermal-merino-glove"],
  },
  {
    id: "fam-stance-run",
    brandId: "brand-stance",
    name: "Run Crew",
    slug: "stance-run",
    categoryId: "cat-running-socks",
    description: "Stance Run crew socks.",
    productIds: ["prod-stance-run-crew"],
  },
  {
    id: "fam-tnf-flight",
    brandId: "brand-the-north-face",
    name: "Flight",
    slug: "tnf-flight",
    categoryId: "cat-running-clothing",
    description: "The North Face Flight rain shells.",
    productIds: ["prod-tnf-flight-series-jacket-men"],
  },
  {
    id: "fam-tracksmith-brighton",
    brandId: "brand-tracksmith",
    name: "Brighton",
    slug: "brighton",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Brighton cold-weather pieces.",
    productIds: ["prod-tracksmith-brighton-ls-men", "prod-tracksmith-brighton-bra"],
  },
  {
    id: "fam-tracksmith-harrier",
    brandId: "brand-tracksmith",
    name: "Harrier",
    slug: "harrier",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Harrier race singlets.",
    productIds: ["prod-tracksmith-harrier-singlet-men"],
  },
  {
    id: "fam-tracksmith-session",
    brandId: "brand-tracksmith",
    name: "Session",
    slug: "session",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Session training shorts.",
    productIds: ["prod-tracksmith-session-short-men", "prod-tracksmith-session-short-women"],
  },
  {
    id: "fam-tracksmith-turnover",
    brandId: "brand-tracksmith",
    name: "Turnover",
    slug: "turnover",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Turnover tights.",
    productIds: ["prod-tracksmith-turnover-tight-women"],
  },
  {
    id: "fam-tracksmith-twilight",
    brandId: "brand-tracksmith",
    name: "Twilight",
    slug: "twilight",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Twilight half tights.",
    productIds: ["prod-tracksmith-twilight-half-men"],
  },
  {
    id: "fam-tracksmith-van-cortlandt",
    brandId: "brand-tracksmith",
    name: "Van Cortlandt",
    slug: "van-cortlandt",
    categoryId: "cat-running-clothing",
    description: "Tracksmith Van Cortlandt tees.",
    productIds: ["prod-tracksmith-van-cortlandt-tee-men"],
  },
  // Pre-launch 05 — missing sock families referenced by products
  {
    id: "fam-swiftwick-aspire",
    brandId: "brand-swiftwick",
    name: "Aspire",
    slug: "swiftwick-aspire",
    categoryId: "cat-running-socks",
    description: "Swiftwick Aspire thin performance socks.",
    productIds: ["prod-swiftwick-aspire-four"],
  },
  {
    id: "fam-drymax-run",
    brandId: "brand-drymax",
    name: "Run",
    slug: "drymax-run",
    categoryId: "cat-running-socks",
    description: "Drymax Run moisture-management socks.",
    productIds: ["prod-drymax-run-lite-mesh"],
  },
  {
    id: "fam-wrightsock-coolmesh",
    brandId: "brand-wrightsock",
    name: "Coolmesh",
    slug: "wrightsock-coolmesh",
    categoryId: "cat-running-socks",
    description: "Wrightsock Coolmesh dual-layer anti-blister socks.",
    productIds: ["prod-wrightsock-coolmesh-ii"],
  },
  {
    id: "fam-balega-hidden-comfort",
    brandId: "brand-balega",
    name: "Hidden Comfort",
    slug: "balega-hidden-comfort",
    categoryId: "cat-running-socks",
    description: "Balega Hidden Comfort no-show socks.",
    productIds: ["prod-balega-hidden-comfort"],
  },
  {
    id: "fam-bombas-performance-running",
    brandId: "brand-bombas",
    name: "Performance Running",
    slug: "bombas-performance-running",
    categoryId: "cat-running-socks",
    description: "Bombas Performance Running socks.",
    productIds: ["prod-bombas-performance-running-quarter"],
  },
  {
    id: "fam-hilly-marathon-fresh",
    brandId: "brand-hilly",
    name: "Marathon Fresh",
    slug: "hilly-marathon-fresh",
    categoryId: "cat-running-socks",
    description: "Hilly Marathon Fresh race socks.",
    productIds: ["prod-hilly-marathon-fresh"],
  },
  {
    id: "fam-buff-neckwear",
    brandId: "brand-buff",
    name: "Multifunctional Neckwear",
    slug: "buff-neckwear",
    categoryId: "cat-running-clothing",
    description: "BUFF multifunctional neckwear and headwear.",
    productIds: [
      "prod-buff-original",
      "prod-buff-coolnet-uv",
      "prod-buff-merino-lightweight",
      "prod-buff-polar",
    ],
  },
  {
    id: "fam-sockwell-compression",
    brandId: "brand-sockwell",
    name: "Compression",
    slug: "sockwell-compression",
    categoryId: "cat-running-socks",
    description: "Sockwell compression running socks.",
    productIds: ["prod-sockwell-compression-light"],
  },
];
