import type { ProductFamily } from "@/domain/products/types";

/** Families introduced or expanded in Prompt 14. */
export const runningCatalogFamilies: ProductFamily[] = [
  {
    id: "fam-superblast",
    brandId: "brand-asics",
    name: "SUPERBLAST",
    slug: "superblast",
    categoryId: "cat-running-shoes",
    description: "Max-stack neutral trainer for long road efforts.",
    productIds: ["prod-superblast-2"],
  },
  {
    id: "fam-kayano",
    brandId: "brand-asics",
    name: "GEL-Kayano",
    slug: "gel-kayano",
    categoryId: "cat-running-shoes",
    description: "Stability daily trainer family.",
    productIds: ["prod-kayano-32"],
  },
  {
    id: "fam-cumulus",
    brandId: "brand-asics",
    name: "GEL-Cumulus",
    slug: "gel-cumulus",
    categoryId: "cat-running-shoes",
    description: "Neutral daily cushion trainer.",
    productIds: ["prod-cumulus-27"],
  },
  {
    id: "fam-metaspeed",
    brandId: "brand-asics",
    name: "METASPEED",
    slug: "metaspeed",
    categoryId: "cat-running-shoes",
    description: "Carbon race shoes for road racing.",
    productIds: ["prod-metaspeed-sky-paris"],
  },
  {
    id: "fam-gt2000",
    brandId: "brand-asics",
    name: "GT-2000",
    slug: "gt-2000",
    categoryId: "cat-running-shoes",
    description: "Supportive daily trainer.",
    productIds: ["prod-gt-2000-14"],
  },
  {
    id: "fam-vomero",
    brandId: "brand-nike",
    name: "Vomero",
    slug: "vomero",
    categoryId: "cat-running-shoes",
    description: "Cushioned Nike daily trainer.",
    productIds: ["prod-vomero-18"],
  },
  {
    id: "fam-invincible",
    brandId: "brand-nike",
    name: "Invincible",
    slug: "invincible",
    categoryId: "cat-running-shoes",
    description: "Max-cushion Nike recovery/daily shoe.",
    productIds: ["prod-invincible-3"],
  },
  {
    id: "fam-vaporfly",
    brandId: "brand-nike",
    name: "Vaporfly",
    slug: "vaporfly",
    categoryId: "cat-running-shoes",
    description: "Carbon road racing shoe.",
    productIds: ["prod-vaporfly-4"],
  },
  {
    id: "fam-alphafly",
    brandId: "brand-nike",
    name: "Alphafly",
    slug: "alphafly",
    categoryId: "cat-running-shoes",
    description: "Flagship Nike carbon race shoe.",
    productIds: ["prod-alphafly-3"],
  },
  {
    id: "fam-structure",
    brandId: "brand-nike",
    name: "Structure",
    slug: "structure",
    categoryId: "cat-running-shoes",
    description: "Nike stability trainers.",
    productIds: ["prod-structure-26", "prod-structure-plus"],
  },
  {
    id: "fam-glycerin",
    brandId: "brand-brooks",
    name: "Glycerin",
    slug: "glycerin",
    categoryId: "cat-running-shoes",
    description: "Premium soft daily trainer.",
    productIds: ["prod-glycerin-22", "prod-glycerin-21"],
  },
  {
    id: "fam-adrenaline",
    brandId: "brand-brooks",
    name: "Adrenaline GTS",
    slug: "adrenaline-gts",
    categoryId: "cat-running-shoes",
    description: "Brooks GuideRails stability trainer.",
    productIds: ["prod-adrenaline-gts-25"],
  },
  {
    id: "fam-bondi",
    brandId: "brand-hoka",
    name: "Bondi",
    slug: "bondi",
    categoryId: "cat-running-shoes",
    description: "Max-cushion HOKA road shoe.",
    productIds: ["prod-bondi-9", "prod-bondi-8"],
  },
  {
    id: "fam-endorphin-pro",
    brandId: "brand-saucony",
    name: "Endorphin Pro",
    slug: "endorphin-pro",
    categoryId: "cat-running-shoes",
    description: "Carbon race shoe.",
    productIds: ["prod-endorphin-pro-4", "prod-endorphin-pro-3"],
  },
  {
    id: "fam-ride",
    brandId: "brand-saucony",
    name: "Ride",
    slug: "ride",
    categoryId: "cat-running-shoes",
    description: "Balanced Saucony daily trainer.",
    productIds: ["prod-ride-18"],
  },
  {
    id: "fam-triumph",
    brandId: "brand-saucony",
    name: "Triumph",
    slug: "triumph",
    categoryId: "cat-running-shoes",
    description: "Soft max-cushion Saucony daily.",
    productIds: ["prod-triumph-22"],
  },
  {
    id: "fam-cloudmonster",
    brandId: "brand-on",
    name: "Cloudmonster",
    slug: "cloudmonster",
    categoryId: "cat-running-shoes",
    description: "Max-stack On road trainer.",
    productIds: ["prod-cloudmonster-2", "prod-cloudmonster-hyper"],
  },
  {
    id: "fam-ultraboost",
    brandId: "brand-adidas",
    name: "Ultraboost",
    slug: "ultraboost",
    categoryId: "cat-running-shoes",
    description: "Soft Boost daily and recovery trainers.",
    productIds: ["prod-ultraboost-5"],
  },
  {
    id: "fam-terrex-agravic",
    brandId: "brand-adidas",
    name: "Terrex Agravic",
    slug: "terrex-agravic",
    categoryId: "cat-running-shoes",
    description: "Adidas Terrex trail shoes for mixed singletrack.",
    productIds: ["prod-terrex-agravic-3"],
  },
  {
    id: "fam-altra-experience",
    brandId: "brand-altra",
    name: "Experience",
    slug: "altra-experience",
    categoryId: "cat-running-shoes",
    description: "Approachable Altra road shoes with foot-shaped toe boxes.",
    productIds: ["prod-experience-flow"],
  },
  {
    id: "fam-altra-paradigm",
    brandId: "brand-altra",
    name: "Paradigm",
    slug: "altra-paradigm",
    categoryId: "cat-running-shoes",
    description: "Zero-drop max-cushion Altra road shoes.",
    productIds: ["prod-paradigm-7"],
  },
  {
    id: "fam-trabuco",
    brandId: "brand-asics",
    name: "GEL-Trabuco",
    slug: "gel-trabuco",
    categoryId: "cat-running-shoes",
    description: "ASICS trail shoes for rocky and mixed terrain.",
    productIds: ["prod-trabuco-13"],
  },
  {
    id: "fam-gt-1000",
    brandId: "brand-asics",
    name: "GT-1000",
    slug: "gt-1000",
    categoryId: "cat-running-shoes",
    description: "Entry-to-mid ASICS stability daily trainers.",
    productIds: ["prod-gt-1000-13"],
  },
  {
    id: "fam-cascadia",
    brandId: "brand-brooks",
    name: "Cascadia",
    slug: "cascadia",
    categoryId: "cat-running-shoes",
    description: "Brooks trail workhorse family.",
    productIds: ["prod-cascadia-18"],
  },
  {
    id: "fam-glycerin-gts",
    brandId: "brand-brooks",
    name: "Glycerin GTS",
    slug: "glycerin-gts",
    categoryId: "cat-running-shoes",
    description: "Soft Glycerin cushioning with GuideRails stability.",
    productIds: ["prod-glycerin-gts-22"],
  },
  {
    id: "fam-arahi",
    brandId: "brand-hoka",
    name: "Arahi",
    slug: "arahi",
    categoryId: "cat-running-shoes",
    description: "HOKA J-Frame stability daily trainers.",
    productIds: ["prod-arahi-7"],
  },
  {
    id: "fam-gaviota",
    brandId: "brand-hoka",
    name: "Gaviota",
    slug: "gaviota",
    categoryId: "cat-running-shoes",
    description: "HOKA max-stability cushioned road shoes.",
    productIds: ["prod-gaviota-5"],
  },
  {
    id: "fam-860",
    brandId: "brand-new-balance",
    name: "Fresh Foam X 860",
    slug: "fresh-foam-860",
    categoryId: "cat-running-shoes",
    description: "New Balance Fresh Foam stability dailies.",
    productIds: ["prod-860-v14"],
  },
  {
    id: "fam-hierro",
    brandId: "brand-new-balance",
    name: "Fresh Foam X Hierro",
    slug: "fresh-foam-hierro",
    categoryId: "cat-running-shoes",
    description: "New Balance cushioned trail shoes.",
    productIds: ["prod-hierro-v9"],
  },
  {
    id: "fam-pegasus-trail",
    brandId: "brand-nike",
    name: "Pegasus Trail",
    slug: "pegasus-trail",
    categoryId: "cat-running-shoes",
    description: "Nike road-to-trail Pegasus variants.",
    productIds: ["prod-pegasus-trail-5"],
  },
  {
    id: "fam-react-infinity",
    brandId: "brand-nike",
    name: "React Infinity Run",
    slug: "react-infinity-run",
    categoryId: "cat-running-shoes",
    description: "Nike React stability-leaning daily trainers.",
    productIds: ["prod-react-infinity-4"],
  },
  {
    id: "fam-cloudsurfer",
    brandId: "brand-on",
    name: "Cloudsurfer",
    slug: "cloudsurfer",
    categoryId: "cat-running-shoes",
    description: "Soft On daily trainers with CloudTec Phase cushioning.",
    productIds: ["prod-cloudsurfer-2", "prod-cloudsurfer-next"],
  },
  {
    id: "fam-salomon-genesis",
    brandId: "brand-salomon",
    name: "Genesis",
    slug: "salomon-genesis",
    categoryId: "cat-running-shoes",
    description: "Salomon agile trail shoes.",
    productIds: ["prod-genesis-salomon"],
  },
  {
    id: "fam-ultra-glide",
    brandId: "brand-salomon",
    name: "Ultra Glide",
    slug: "ultra-glide",
    categoryId: "cat-running-shoes",
    description: "Salomon cushioned long-trail shoes.",
    productIds: ["prod-ultra-glide-2"],
  },
  {
    id: "fam-guide",
    brandId: "brand-saucony",
    name: "Guide",
    slug: "guide",
    categoryId: "cat-running-shoes",
    description: "Saucony stability daily trainers.",
    productIds: ["prod-guide-18"],
  },
  {
    id: "fam-xodus",
    brandId: "brand-saucony",
    name: "Xodus Ultra",
    slug: "xodus-ultra",
    categoryId: "cat-running-shoes",
    description: "Saucony protective ultra-trail shoes.",
    productIds: ["prod-xodus-ultra-3"],
  },
  {
    id: "fam-terraventure",
    brandId: "brand-topo",
    name: "Terraventure",
    slug: "terraventure",
    categoryId: "cat-running-shoes",
    description: "Topo wide-fit trail shoes.",
    productIds: ["prod-terraventure-4"],
  },
  {
    id: "fam-nnormal-kjerag",
    brandId: "brand-nnormal",
    name: "Kjerag",
    slug: "nnormal-kjerag",
    categoryId: "cat-running-shoes",
    description:
      "NNormal race-trail line for speed on technical terrain. Current: Kjerag 02. Not Tomir protection and not the Race Vest.",
    productIds: ["prod-nnormal-kjerag-02"],
  },
  {
    id: "fam-nnormal-tomir",
    brandId: "brand-nnormal",
    name: "Tomir",
    slug: "nnormal-tomir",
    categoryId: "cat-running-shoes",
    description:
      "NNormal long-technical trail line — more stack, 8 mm drop, deeper lugs than Kjerag. Current: Tomir 02.",
    productIds: ["prod-nnormal-tomir-02"],
  },
];
