/**
 * Suitability scores for running headlamps wave2.
 * Factors: brightness, beam-distance, runtime, comfort, weight, reactive, value.
 * Use cases: night-running, trail-training, ultra, winter-running, long-runs.
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const lampFactors = (scores: {
  brightness: number;
  beamDistance: number;
  runtime: number;
  comfort: number;
  weight: number;
  reactive: number;
  value: number;
}) => [
  {
    key: "brightness",
    label: "Brightness",
    score: scores.brightness,
    weight: 0.18,
    explanation: "Peak lumen output for dark roads and trails.",
  },
  {
    key: "beam-distance",
    label: "Beam distance",
    score: scores.beamDistance,
    weight: 0.14,
    explanation: "How far the useful beam reaches for pace and terrain reading.",
  },
  {
    key: "runtime",
    label: "Runtime",
    score: scores.runtime,
    weight: 0.16,
    explanation: "Usable burn time at realistic running outputs.",
  },
  {
    key: "comfort",
    label: "Comfort",
    score: scores.comfort,
    weight: 0.14,
    explanation: "Band fit, bounce control and all-night wearability.",
  },
  {
    key: "weight",
    label: "Weight",
    score: scores.weight,
    weight: 0.12,
    explanation: "On-head mass for long efforts (higher score = lighter).",
  },
  {
    key: "reactive",
    label: "Reactive lighting",
    score: scores.reactive,
    weight: 0.1,
    explanation: "Auto-adjusting output that saves battery and button presses.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.16,
    explanation: "Features and beam performance vs typical street price.",
  },
];

export const runningHeadlampsRecommendations: Recommendation[] = [
  // ── Petzl NAO RL ─────────────────────────────────────────────────────────
  {
    id: "rec-nao-rl-night-running",
    productId: "prod-petzl-nao-rl",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 94,
    factors: lampFactors({
      brightness: 96,
      beamDistance: 94,
      runtime: 88,
      comfort: 90,
      weight: 72,
      reactive: 98,
      value: 70,
    }),
    strengths: ["REACTIVE LIGHTING", "1500 lm / 200 m throw"],
    compromises: ["Premium price and weight vs Swift RL"],
    explanation:
      "Top reactive pick when night sections need auto-dimming and serious throw.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nao-rl-trail-training",
    productId: "prod-petzl-nao-rl",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 95,
    factors: lampFactors({
      brightness: 96,
      beamDistance: 95,
      runtime: 90,
      comfort: 90,
      weight: 70,
      reactive: 98,
      value: 70,
    }),
    strengths: ["Terrain-aware output", "Balanced rear battery"],
    compromises: ["Overkill for short lit loops"],
    explanation: "Best-in-class for technical night trail training.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nao-rl-ultra",
    productId: "prod-petzl-nao-rl",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 93,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 93,
      runtime: 92,
      comfort: 92,
      weight: 68,
      reactive: 98,
      value: 68,
    }),
    strengths: ["Reactive runtime stretch", "Rear red + top strap"],
    compromises: ["Heavier than ultralight backups"],
    explanation: "Ultra night sections where reactive stretch matters most.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nao-rl-winter-running",
    productId: "prod-petzl-nao-rl",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 88,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 92,
      runtime: 88,
      comfort: 88,
      weight: 70,
      reactive: 96,
      value: 68,
    }),
    strengths: ["Auto-dim in variable winter light", "Strong throw"],
    compromises: ["IPX4 only — Storm seals better in downpours"],
    explanation: "Strong winter trail lamp; pair sealed peers for dunking risk.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nao-rl-long-runs",
    productId: "prod-petzl-nao-rl",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 90,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 90,
      runtime: 90,
      comfort: 90,
      weight: 70,
      reactive: 96,
      value: 70,
    }),
    strengths: ["Reactive saves battery on long dark blocks", "Comfort cradle"],
    compromises: ["Pricey if most longs are lit roads"],
    explanation: "Excellent when long runs include real dark trail time.",
    evidenceIds: [...ev],
  },

  // ── Petzl Actik Core ─────────────────────────────────────────────────────
  {
    id: "rec-actik-core-night-running",
    productId: "prod-petzl-actik-core",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 86,
    factors: lampFactors({
      brightness: 82,
      beamDistance: 80,
      runtime: 84,
      comfort: 86,
      weight: 86,
      reactive: 20,
      value: 88,
    }),
    strengths: ["625 lm versatile beam", "Hybrid CORE/AAA bailout"],
    compromises: ["No reactive or rear red"],
    explanation: "Reliable all-round night road/trail lamp without RL pricing.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-actik-core-winter-running",
    productId: "prod-petzl-actik-core",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 85,
    factors: lampFactors({
      brightness: 80,
      beamDistance: 78,
      runtime: 86,
      comfort: 86,
      weight: 86,
      reactive: 20,
      value: 88,
    }),
    strengths: ["AAA swap if cold kills rechargeable", "Light enough for daily"],
    compromises: ["Manual output management"],
    explanation: "Winter commute and training pick with hybrid battery peace of mind.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-actik-core-long-runs",
    productId: "prod-petzl-actik-core",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: lampFactors({
      brightness: 80,
      beamDistance: 78,
      runtime: 84,
      comfort: 86,
      weight: 86,
      reactive: 20,
      value: 88,
    }),
    strengths: ["Hybrid runtime insurance", "88 g comfort"],
    compromises: ["Not a technical night-trail primary"],
    explanation: "Solid long dark-road and mild-trail companion.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-actik-core-trail-training",
    productId: "prod-petzl-actik-core",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 80,
    factors: lampFactors({
      brightness: 78,
      beamDistance: 78,
      runtime: 82,
      comfort: 84,
      weight: 86,
      reactive: 20,
      value: 86,
    }),
    strengths: ["Enough mixed beam for moderate trails", "Value"],
    compromises: ["Step up to NAO/Swift for technical nights"],
    explanation: "Fine for moderate night trails; not max-output technical.",
    evidenceIds: [...ev],
  },

  // ── Petzl IKO Core ───────────────────────────────────────────────────────
  {
    id: "rec-iko-core-night-running",
    productId: "prod-petzl-iko-core",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 82,
    factors: lampFactors({
      brightness: 74,
      beamDistance: 74,
      runtime: 82,
      comfort: 92,
      weight: 92,
      reactive: 20,
      value: 84,
    }),
    strengths: ["AIRFIT low bounce", "79 g hybrid"],
    compromises: ["500 lm ceiling"],
    explanation: "Ultralight comfort primary for easy night roads.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-iko-core-ultra",
    productId: "prod-petzl-iko-core",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: lampFactors({
      brightness: 72,
      beamDistance: 72,
      runtime: 86,
      comfort: 92,
      weight: 94,
      reactive: 20,
      value: 84,
    }),
    strengths: ["Packable AAA/CORE backup", "Negligible bounce"],
    compromises: ["Not a sole technical night lamp"],
    explanation: "Excellent ultra spare or easy-night primary.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-iko-core-long-runs",
    productId: "prod-petzl-iko-core",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 83,
    factors: lampFactors({
      brightness: 72,
      beamDistance: 72,
      runtime: 82,
      comfort: 92,
      weight: 92,
      reactive: 20,
      value: 84,
    }),
    strengths: ["Barely-there forehead feel", "Hybrid bailout"],
    compromises: ["Limited throw for fast descents"],
    explanation: "Long easy night miles where weight and bounce matter.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-iko-core-winter-running",
    productId: "prod-petzl-iko-core",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 80,
    factors: lampFactors({
      brightness: 72,
      beamDistance: 70,
      runtime: 84,
      comfort: 90,
      weight: 92,
      reactive: 20,
      value: 84,
    }),
    strengths: ["AAA option in cold", "Light daily wear"],
    compromises: ["No rear red for dark roads"],
    explanation: "Winter easy-road pick; add a clip light for traffic.",
    evidenceIds: [...ev],
  },

  // ── BD Storm 500-R ───────────────────────────────────────────────────────
  {
    id: "rec-storm-500-r-winter-running",
    productId: "prod-bd-storm-500-r",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 90,
    factors: lampFactors({
      brightness: 78,
      beamDistance: 82,
      runtime: 92,
      comfort: 84,
      weight: 74,
      reactive: 15,
      value: 84,
    }),
    strengths: ["IP67 sealed", "Long mid-mode burn"],
    compromises: ["No reactive / rear red"],
    explanation: "Winter foul-weather headlamp when sealing beats smart beam.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-storm-500-r-night-running",
    productId: "prod-bd-storm-500-r",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 84,
    factors: lampFactors({
      brightness: 78,
      beamDistance: 82,
      runtime: 90,
      comfort: 84,
      weight: 74,
      reactive: 15,
      value: 84,
    }),
    strengths: ["500 lm / 120 m", "PowerTap dimming"],
    compromises: ["Micro-USB era charging"],
    explanation: "Dependable night training lamp with strong weather sealing.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-storm-500-r-trail-training",
    productId: "prod-bd-storm-500-r",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: lampFactors({
      brightness: 76,
      beamDistance: 80,
      runtime: 88,
      comfort: 82,
      weight: 72,
      reactive: 15,
      value: 82,
    }),
    strengths: ["Sealed for wet trails", "Lock mode"],
    compromises: ["Not a 1000+ lm technical primary"],
    explanation: "Solid wet-trail night trainer under 600 lm.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-storm-500-r-long-runs",
    productId: "prod-bd-storm-500-r",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: lampFactors({
      brightness: 76,
      beamDistance: 80,
      runtime: 92,
      comfort: 84,
      weight: 72,
      reactive: 15,
      value: 84,
    }),
    strengths: ["Huge mid/low runtime", "IP67 peace of mind"],
    compromises: ["Heavier than ultralights"],
    explanation: "Long dark blocks where battery and weather matter.",
    evidenceIds: [...ev],
  },

  // ── BD Distance 1500 ─────────────────────────────────────────────────────
  {
    id: "rec-distance-1500-trail-training",
    productId: "prod-bd-distance-1500",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 92,
    factors: lampFactors({
      brightness: 96,
      beamDistance: 88,
      runtime: 86,
      comfort: 86,
      weight: 55,
      reactive: 15,
      value: 68,
    }),
    strengths: ["1500 lm boost", "IP67 + Comfort Cradle"],
    compromises: ["212 g on-head mass"],
    explanation: "High-output manual trail lamp for committing night sessions.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-distance-1500-ultra",
    productId: "prod-bd-distance-1500",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 90,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 86,
      runtime: 90,
      comfort: 86,
      weight: 52,
      reactive: 15,
      value: 66,
    }),
    strengths: ["Hot-swap rear pack", "Sustained high output"],
    compromises: ["Heavy vs reactive Petzl peers"],
    explanation: "Ultra nights when spare packs beat reactive auto-dim.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-distance-1500-night-running",
    productId: "prod-bd-distance-1500",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 88,
    factors: lampFactors({
      brightness: 96,
      beamDistance: 88,
      runtime: 84,
      comfort: 84,
      weight: 54,
      reactive: 15,
      value: 68,
    }),
    strengths: ["Serious throw", "Sealed body"],
    compromises: ["Overbuilt for lit roads"],
    explanation: "Night trail powerhouse; skip for easy lit loops.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-distance-1500-winter-running",
    productId: "prod-bd-distance-1500",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 88,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 86,
      runtime: 86,
      comfort: 84,
      weight: 52,
      reactive: 15,
      value: 66,
    }),
    strengths: ["IP67 in winter weather", "Spare pack in cold"],
    compromises: ["Weight shows on long road winter miles"],
    explanation: "Winter trail nights needing sealed high output.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-distance-1500-long-runs",
    productId: "prod-bd-distance-1500",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 86,
      runtime: 88,
      comfort: 84,
      weight: 52,
      reactive: 15,
      value: 66,
    }),
    strengths: ["Swappable packs for long dark blocks", "Cradle comfort"],
    compromises: ["Heavy if the long is mostly road"],
    explanation: "Long trail nights with battery logistics planned.",
    evidenceIds: [...ev],
  },

  // ── Silva Smini ──────────────────────────────────────────────────────────
  {
    id: "rec-smini-night-running",
    productId: "prod-silva-smini",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 82,
    factors: lampFactors({
      brightness: 58,
      beamDistance: 62,
      runtime: 70,
      comfort: 90,
      weight: 98,
      reactive: 15,
      value: 90,
    }),
    strengths: ["53 g + rear red", "Intelligent Light pattern"],
    compromises: ["250 lm ceiling / short max burn"],
    explanation: "Ultralight easy-road night primary or race spare.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smini-ultra",
    productId: "prod-silva-smini",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 86,
    factors: lampFactors({
      brightness: 55,
      beamDistance: 60,
      runtime: 68,
      comfort: 90,
      weight: 98,
      reactive: 15,
      value: 90,
    }),
    strengths: ["Near-zero backup weight", "Rear visibility"],
    compromises: ["Not a sole technical night lamp"],
    explanation: "Ultra backup that disappears in the vest until you need it.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smini-long-runs",
    productId: "prod-silva-smini",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 80,
    factors: lampFactors({
      brightness: 56,
      beamDistance: 60,
      runtime: 68,
      comfort: 90,
      weight: 98,
      reactive: 15,
      value: 90,
    }),
    strengths: ["No bounce tax", "USB-C"],
    compromises: ["Plan mid modes for longer dark blocks"],
    explanation: "Long easy night roads when grams and comfort win.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smini-winter-running",
    productId: "prod-silva-smini",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 78,
    factors: lampFactors({
      brightness: 55,
      beamDistance: 58,
      runtime: 66,
      comfort: 88,
      weight: 98,
      reactive: 15,
      value: 88,
    }),
    strengths: ["IPX5 + rear red", "Tiny daily carry"],
    compromises: ["Weak for unlit technical winter trails"],
    explanation: "Winter lit-road / easy path companion.",
    evidenceIds: [...ev],
  },

  // ── Ledlenser NEO9R ──────────────────────────────────────────────────────
  {
    id: "rec-neo9r-trail-training",
    productId: "prod-ledlenser-neo9r",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 91,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 94,
      runtime: 86,
      comfort: 88,
      weight: 60,
      reactive: 15,
      value: 76,
    }),
    strengths: ["Separated near/far beams", "200 m Boost"],
    compromises: ["199 g; IP54"],
    explanation: "Trail-running beam craft without Petzl reactive.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo9r-night-running",
    productId: "prod-ledlenser-neo9r",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 88,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 92,
      runtime: 84,
      comfort: 88,
      weight: 60,
      reactive: 15,
      value: 76,
    }),
    strengths: ["Rear red + balanced battery", "Chest-belt option"],
    compromises: ["Heavy for easy roads"],
    explanation: "High-output night lamp with road visibility extras.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo9r-ultra",
    productId: "prod-ledlenser-neo9r",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 87,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 92,
      runtime: 88,
      comfort: 86,
      weight: 58,
      reactive: 15,
      value: 74,
    }),
    strengths: ["Swappable rear pack", "Extension-cable option"],
    compromises: ["Mass vs NAO RL reactive"],
    explanation: "Ultra nights preferring manual beams and spare packs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo9r-long-runs",
    productId: "prod-ledlenser-neo9r",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: lampFactors({
      brightness: 90,
      beamDistance: 90,
      runtime: 86,
      comfort: 86,
      weight: 58,
      reactive: 15,
      value: 74,
    }),
    strengths: ["Strong continuous Power mode", "Comfort pad"],
    compromises: ["Overkill for lit long roads"],
    explanation: "Long dark trail blocks with sustained output needs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo9r-winter-running",
    productId: "prod-ledlenser-neo9r",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 82,
    factors: lampFactors({
      brightness: 90,
      beamDistance: 90,
      runtime: 84,
      comfort: 86,
      weight: 58,
      reactive: 15,
      value: 74,
    }),
    strengths: ["Rear red for dark roads", "High Power runtime"],
    compromises: ["IP54 trails Storm sealing"],
    explanation: "Winter trail/road mix when beam quality matters.",
    evidenceIds: [...ev],
  },

  // ── Ledlenser NEO5R ──────────────────────────────────────────────────────
  {
    id: "rec-neo5r-night-running",
    productId: "prod-ledlenser-neo5r",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 86,
    factors: lampFactors({
      brightness: 80,
      beamDistance: 78,
      runtime: 80,
      comfort: 90,
      weight: 80,
      reactive: 15,
      value: 86,
    }),
    strengths: ["Rear red + balance", "Chest belt included"],
    compromises: ["Not high-output trail"],
    explanation: "Mid-pack night road lamp with running-tuned pattern.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo5r-winter-running",
    productId: "prod-ledlenser-neo5r",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 85,
    factors: lampFactors({
      brightness: 78,
      beamDistance: 76,
      runtime: 80,
      comfort: 90,
      weight: 80,
      reactive: 15,
      value: 86,
    }),
    strengths: ["Road visibility rear light", "Comfortable daily wear"],
    compromises: ["IP54 in heavy rain"],
    explanation: "Winter dark-road training sweet spot in the NEO line.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo5r-long-runs",
    productId: "prod-ledlenser-neo5r",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: lampFactors({
      brightness: 78,
      beamDistance: 76,
      runtime: 80,
      comfort: 90,
      weight: 80,
      reactive: 15,
      value: 86,
    }),
    strengths: ["Low bounce rear battery", "Usable mid runtime"],
    compromises: ["Boost is brief, not all-night max"],
    explanation: "Long dark roads and mild paths without NEO9R weight.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-neo5r-trail-training",
    productId: "prod-ledlenser-neo5r",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 78,
    factors: lampFactors({
      brightness: 76,
      beamDistance: 74,
      runtime: 78,
      comfort: 88,
      weight: 80,
      reactive: 15,
      value: 84,
    }),
    strengths: ["Running beam pattern", "Comfort"],
    compromises: ["Step to NEO9R for technical nights"],
    explanation: "Mild night trails only; not a technical primary.",
    evidenceIds: [...ev],
  },

  // ── Fenix HM65R-T ────────────────────────────────────────────────────────
  {
    id: "rec-hm65r-t-trail-training",
    productId: "prod-fenix-hm65r-t",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 90,
    factors: lampFactors({
      brightness: 95,
      beamDistance: 90,
      runtime: 84,
      comfort: 72,
      weight: 70,
      reactive: 15,
      value: 82,
    }),
    strengths: ["Independent spot + flood", "IP68 toughness"],
    compromises: ["Front-heavy bounce if band is loose"],
    explanation: "Dual-beam trail night trainer for manual beam painters.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-hm65r-t-night-running",
    productId: "prod-fenix-hm65r-t",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 86,
    factors: lampFactors({
      brightness: 94,
      beamDistance: 90,
      runtime: 82,
      comfort: 70,
      weight: 70,
      reactive: 15,
      value: 80,
    }),
    strengths: ["1500 lm dual max", "Replaceable 18650"],
    compromises: ["No rear red"],
    explanation: "High-output night trail lamp with full beam control.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-hm65r-t-ultra",
    productId: "prod-fenix-hm65r-t",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 85,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 88,
      runtime: 86,
      comfort: 70,
      weight: 68,
      reactive: 15,
      value: 80,
    }),
    strengths: ["18650 / CR123A options", "Sealed body"],
    compromises: ["Bounce vs rear-battery peers"],
    explanation: "Ultra nights with spare cells and dual-beam needs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-hm65r-t-winter-running",
    productId: "prod-fenix-hm65r-t",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 88,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 88,
      runtime: 84,
      comfort: 70,
      weight: 68,
      reactive: 15,
      value: 80,
    }),
    strengths: ["IP68 in foul weather", "Strong throw"],
    compromises: ["Comfort band not SlimFit class"],
    explanation: "Winter trail nights needing sealed dual-beam power.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-hm65r-t-long-runs",
    productId: "prod-fenix-hm65r-t",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 82,
    factors: lampFactors({
      brightness: 90,
      beamDistance: 88,
      runtime: 84,
      comfort: 70,
      weight: 68,
      reactive: 15,
      value: 80,
    }),
    strengths: ["Long flood low modes", "Hot-swap cells"],
    compromises: ["Mass on easy long roads"],
    explanation: "Long dark trail efforts with cell logistics.",
    evidenceIds: [...ev],
  },

  // ── BioLite HeadLamp 800 Pro ─────────────────────────────────────────────
  {
    id: "rec-biolite-800-night-running",
    productId: "prod-biolite-headlamp-800",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 88,
    factors: lampFactors({
      brightness: 88,
      beamDistance: 84,
      runtime: 86,
      comfort: 96,
      weight: 70,
      reactive: 15,
      value: 84,
    }),
    strengths: ["SlimFit no-bounce band", "Rear red + 800 lm burst"],
    compromises: ["No reactive; micro-USB"],
    explanation: "Comfort-first high-output night runner.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-800-trail-training",
    productId: "prod-biolite-headlamp-800",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 86,
    factors: lampFactors({
      brightness: 86,
      beamDistance: 84,
      runtime: 84,
      comfort: 96,
      weight: 68,
      reactive: 15,
      value: 82,
    }),
    strengths: ["Stable on technical miles", "Spot/flood combo"],
    compromises: ["IPX4 vs sealed BD high-output"],
    explanation: "Trail nights where bounce control beats max sealed rating.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-800-long-runs",
    productId: "prod-biolite-headlamp-800",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 87,
    factors: lampFactors({
      brightness: 84,
      beamDistance: 82,
      runtime: 88,
      comfort: 96,
      weight: 68,
      reactive: 15,
      value: 84,
    }),
    strengths: ["All-night wear comfort", "Strong low-mode runtime"],
    compromises: ["Pass-Thru helps cold; still no hot-swap pack"],
    explanation: "Long dark efforts when forehead comfort is the limiter.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-800-ultra",
    productId: "prod-biolite-headlamp-800",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: lampFactors({
      brightness: 84,
      beamDistance: 82,
      runtime: 86,
      comfort: 96,
      weight: 66,
      reactive: 15,
      value: 82,
    }),
    strengths: ["Comfort over 10+ night hours", "Rear visibility"],
    compromises: ["Burst is timed, not reactive"],
    explanation: "Ultra nights prioritizing band comfort and rear red.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-800-winter-running",
    productId: "prod-biolite-headlamp-800",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 84,
    factors: lampFactors({
      brightness: 84,
      beamDistance: 82,
      runtime: 86,
      comfort: 94,
      weight: 68,
      reactive: 15,
      value: 82,
    }),
    strengths: ["Pass-Thru cold workaround", "Comfort band"],
    compromises: ["IPX4 sealing"],
    explanation: "Winter running when comfort and output beat sealed IP67.",
    evidenceIds: [...ev],
  },

  // ── BioLite HeadLamp 425 ─────────────────────────────────────────────────
  {
    id: "rec-biolite-425-night-running",
    productId: "prod-biolite-headlamp-425",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 84,
    factors: lampFactors({
      brightness: 70,
      beamDistance: 66,
      runtime: 76,
      comfort: 96,
      weight: 88,
      reactive: 15,
      value: 92,
    }),
    strengths: ["SlimFit + rear red", "Value"],
    compromises: ["425 lm for easy terrain only"],
    explanation: "Best comfort/value night-road headlamp in the wave.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-425-winter-running",
    productId: "prod-biolite-headlamp-425",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 83,
    factors: lampFactors({
      brightness: 68,
      beamDistance: 64,
      runtime: 76,
      comfort: 96,
      weight: 88,
      reactive: 15,
      value: 92,
    }),
    strengths: ["Daily winter wear comfort", "Rear visibility"],
    compromises: ["Not for technical unlit trails"],
    explanation: "Winter dark-road daily driver on a budget.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-425-long-runs",
    productId: "prod-biolite-headlamp-425",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 82,
    factors: lampFactors({
      brightness: 68,
      beamDistance: 64,
      runtime: 74,
      comfort: 96,
      weight: 88,
      reactive: 15,
      value: 92,
    }),
    strengths: ["No-bounce long miles", "Light weight"],
    compromises: ["Plan output; high mode is short"],
    explanation: "Long easy night roads where comfort wins.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-biolite-425-trail-training",
    productId: "prod-biolite-headlamp-425",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 72,
    factors: lampFactors({
      brightness: 66,
      beamDistance: 62,
      runtime: 72,
      comfort: 94,
      weight: 88,
      reactive: 15,
      value: 90,
    }),
    strengths: ["Comfort on mild trails", "Value"],
    compromises: ["Undergunned for technical night trail"],
    explanation: "Mild trail only — step up for roots and descents.",
    evidenceIds: [...ev],
  },

  // ── NITECORE NU25 UL ─────────────────────────────────────────────────────
  {
    id: "rec-nu25-night-running",
    productId: "prod-nitecore-nu25",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 80,
    factors: lampFactors({
      brightness: 68,
      beamDistance: 78,
      runtime: 70,
      comfort: 84,
      weight: 98,
      reactive: 15,
      value: 94,
    }),
    strengths: ["~47 g", "Surprising dual-beam throw"],
    compromises: ["Short high-mode runtime"],
    explanation: "Gram-shaving night-road primary or vest spare.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu25-ultra",
    productId: "prod-nitecore-nu25",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: lampFactors({
      brightness: 66,
      beamDistance: 76,
      runtime: 68,
      comfort: 84,
      weight: 98,
      reactive: 15,
      value: 94,
    }),
    strengths: ["Featherweight backup", "IP66"],
    compromises: ["Not a sole all-night technical lamp"],
    explanation: "Ultra spare that adds almost no vest weight.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu25-long-runs",
    productId: "prod-nitecore-nu25",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 78,
    factors: lampFactors({
      brightness: 66,
      beamDistance: 76,
      runtime: 68,
      comfort: 84,
      weight: 98,
      reactive: 15,
      value: 94,
    }),
    strengths: ["Zero bounce tax", "Value"],
    compromises: ["Manage modes carefully"],
    explanation: "Long easy nights when every gram counts.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu25-winter-running",
    productId: "prod-nitecore-nu25",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 78,
    factors: lampFactors({
      brightness: 66,
      beamDistance: 74,
      runtime: 68,
      comfort: 82,
      weight: 98,
      reactive: 15,
      value: 92,
    }),
    strengths: ["IP66 sealed ultralight", "USB-C"],
    compromises: ["No rear red"],
    explanation: "Winter easy-road ultralight; add a clip for traffic.",
    evidenceIds: [...ev],
  },

  // ── NITECORE NU43 ────────────────────────────────────────────────────────
  {
    id: "rec-nu43-night-running",
    productId: "prod-nitecore-nu43",
    sportId: "sport-running",
    useCaseId: "uc-night-running",
    score: 86,
    factors: lampFactors({
      brightness: 92,
      beamDistance: 82,
      runtime: 88,
      comfort: 76,
      weight: 78,
      reactive: 15,
      value: 88,
    }),
    strengths: ["1400 lm at 116 g", "Large cell runtime"],
    compromises: ["No rear red / reactive"],
    explanation: "Bright midweight night lamp without premium reactive cost.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu43-trail-training",
    productId: "prod-nitecore-nu43",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: lampFactors({
      brightness: 90,
      beamDistance: 82,
      runtime: 86,
      comfort: 74,
      weight: 76,
      reactive: 15,
      value: 86,
    }),
    strengths: ["Soft flood for trail reading", "High peak"],
    compromises: ["Manual modes only"],
    explanation: "Trail nights wanting lumen punch under 120 g.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu43-long-runs",
    productId: "prod-nitecore-nu43",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 85,
    factors: lampFactors({
      brightness: 88,
      beamDistance: 80,
      runtime: 90,
      comfort: 76,
      weight: 78,
      reactive: 15,
      value: 88,
    }),
    strengths: ["Deep low-mode runtime", "USB-C fast charge"],
    compromises: ["Integrated cell only"],
    explanation: "Long dark blocks with strong mid/low burn times.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu43-ultra",
    productId: "prod-nitecore-nu43",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 82,
    factors: lampFactors({
      brightness: 88,
      beamDistance: 80,
      runtime: 88,
      comfort: 74,
      weight: 76,
      reactive: 15,
      value: 86,
    }),
    strengths: ["High output / weight ratio", "Long ultralow"],
    compromises: ["No hot-swap pack"],
    explanation: "Ultra nights if one integrated high-capacity cell is enough.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nu43-winter-running",
    productId: "prod-nitecore-nu43",
    sportId: "sport-running",
    useCaseId: "uc-winter-running",
    score: 84,
    factors: lampFactors({
      brightness: 88,
      beamDistance: 80,
      runtime: 90,
      comfort: 74,
      weight: 76,
      reactive: 15,
      value: 86,
    }),
    strengths: ["IP66 + big cell for cold nights", "Brightness"],
    compromises: ["No rear visibility LED"],
    explanation: "Winter dark training with lumen headroom and sealed body.",
    evidenceIds: [...ev],
  },
];
