/**
 * Light suitability scores for running headphones wave2 (+ wave1 peers where useful).
 * Factors: awareness, secure-fit, battery, weather, sound, value, versatility.
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const hpFactors = (scores: {
  awareness: number;
  secureFit: number;
  battery: number;
  weather: number;
  sound: number;
  value: number;
  versatility: number;
}) => [
  {
    key: "awareness",
    label: "Awareness",
    score: scores.awareness,
    weight: 0.18,
    explanation: "Natural hearing of traffic and surroundings.",
  },
  {
    key: "secure-fit",
    label: "Secure fit",
    score: scores.secureFit,
    weight: 0.16,
    explanation: "Stay-put hold for sweat and hard efforts.",
  },
  {
    key: "battery",
    label: "Battery",
    score: scores.battery,
    weight: 0.14,
    explanation: "Single-charge and case endurance for training weeks.",
  },
  {
    key: "weather",
    label: "Weather",
    score: scores.weather,
    weight: 0.12,
    explanation: "Sweat and rain durability from IP rating and build.",
  },
  {
    key: "sound",
    label: "Sound",
    score: scores.sound,
    weight: 0.12,
    explanation: "Music and podcast clarity for the design type.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.14,
    explanation: "Features vs typical street price.",
  },
  {
    key: "versatility",
    label: "Versatility",
    score: scores.versatility,
    weight: 0.14,
    explanation: "Range across road, trail, gym and commute sessions.",
  },
];

export const runningHeadphonesRecommendations: Recommendation[] = [
  // ── Situational awareness ──────────────────────────────────────────────
  {
    id: "rec-shokz-openrun-situational-awareness",
    productId: "prod-shokz-openrun",
    sportId: "sport-running",
    useCaseId: "uc-situational-awareness",
    score: 92,
    factors: hpFactors({
      awareness: 96,
      secureFit: 90,
      battery: 78,
      weather: 94,
      sound: 70,
      value: 92,
      versatility: 86,
    }),
    strengths: ["Open bone conduction", "IP67 outdoor durability"],
    compromises: ["Bass limited vs sealed buds"],
    explanation: "Best value Shokz for traffic-aware road and easy trail miles.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-shokz-openfit-2-situational-awareness",
    productId: "prod-shokz-openfit-2",
    sportId: "sport-running",
    useCaseId: "uc-situational-awareness",
    score: 90,
    factors: hpFactors({
      awareness: 94,
      secureFit: 88,
      battery: 92,
      weather: 80,
      sound: 82,
      value: 80,
      versatility: 88,
    }),
    strengths: ["Open-ear hooks", "Long case endurance"],
    compromises: ["Not sealed for loud gym floors"],
    explanation: "Air-conduction open-ear pick when you want a case and no bone buzz.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-aerofit-2-situational-awareness",
    productId: "prod-soundcore-aerofit-2",
    sportId: "sport-running",
    useCaseId: "uc-situational-awareness",
    score: 88,
    factors: hpFactors({
      awareness: 93,
      secureFit: 88,
      battery: 90,
      weather: 80,
      sound: 80,
      value: 94,
      versatility: 86,
    }),
    strengths: ["Adjustable open hooks", "Strong value"],
    compromises: ["Brand polish trails Shokz/Bose"],
    explanation: "Value open-ear awareness for daily outdoor road runs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sony-linkbuds-open-situational-awareness",
    productId: "prod-sony-linkbuds-open",
    sportId: "sport-running",
    useCaseId: "uc-situational-awareness",
    score: 84,
    factors: hpFactors({
      awareness: 95,
      secureFit: 72,
      battery: 74,
      weather: 62,
      sound: 78,
      value: 74,
      versatility: 80,
    }),
    strengths: ["Ring open-ear hearing", "Sony app multipoint"],
    compromises: ["IPX4 weather only"],
    explanation: "Open ring buds for easy road awareness on Android stacks.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-suunto-wing-situational-awareness",
    productId: "prod-suunto-wing",
    sportId: "sport-running",
    useCaseId: "uc-situational-awareness",
    score: 87,
    factors: hpFactors({
      awareness: 95,
      secureFit: 90,
      battery: 84,
      weather: 92,
      sound: 72,
      value: 68,
      versatility: 84,
    }),
    strengths: ["Bone conduction awareness", "IP67 + night LED"],
    compromises: ["Premium vs OpenRun"],
    explanation: "Outdoor awareness with Suunto extras for night road visibility.",
    evidenceIds: [...ev],
  },

  // ── Daily training ─────────────────────────────────────────────────────
  {
    id: "rec-shokz-openfit-2-daily-training",
    productId: "prod-shokz-openfit-2",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 88,
    factors: hpFactors({
      awareness: 90,
      secureFit: 86,
      battery: 92,
      weather: 78,
      sound: 82,
      value: 80,
      versatility: 90,
    }),
    strengths: ["Comfortable daily open-ear", "Case covers a training week"],
    compromises: ["Gym noise still bleeds in"],
    explanation: "Versatile daily trainer for road and commute awareness miles.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-beats-powerbeats-pro-2-daily-training",
    productId: "prod-beats-powerbeats-pro-2",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 86,
    factors: hpFactors({
      awareness: 62,
      secureFit: 94,
      battery: 92,
      weather: 68,
      sound: 86,
      value: 74,
      versatility: 88,
    }),
    strengths: ["Hook secureFit", "Long battery"],
    compromises: ["Needs transparency outdoors"],
    explanation: "Daily Apple-ecosystem sport hooks for mixed road and gym weeks.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-aerofit-2-daily-training",
    productId: "prod-soundcore-aerofit-2",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 87,
    factors: hpFactors({
      awareness: 90,
      secureFit: 86,
      battery: 90,
      weather: 78,
      sound: 80,
      value: 94,
      versatility: 88,
    }),
    strengths: ["Value open-ear daily wear", "Adjustable hooks"],
    compromises: ["No ANC for treadmill rooms"],
    explanation: "Everyday outdoor training buds when budget matters.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-jabra-elite-8-active-daily-training",
    productId: "prod-jabra-elite-8-active",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 85,
    factors: hpFactors({
      awareness: 58,
      secureFit: 94,
      battery: 84,
      weather: 96,
      sound: 82,
      value: 76,
      versatility: 90,
    }),
    strengths: ["IP68 durability", "Secure sport fit"],
    compromises: ["Sealed awareness trade-off"],
    explanation: "Durable sealed daily trainer for mixed weather and hard efforts.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-apple-airpods-4-daily-training",
    productId: "prod-apple-airpods-4",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 74,
    factors: hpFactors({
      awareness: 70,
      secureFit: 48,
      battery: 68,
      weather: 70,
      sound: 80,
      value: 78,
      versatility: 82,
    }),
    strengths: ["Tip-free comfort", "iPhone pairing"],
    compromises: ["Weak hard-effort secureFit"],
    explanation: "Easy daily Apple miles when you hate tips and skip hard intervals.",
    evidenceIds: [...ev],
  },

  // ── Gym training ───────────────────────────────────────────────────────
  {
    id: "rec-jabra-elite-10-gym-training",
    productId: "prod-jabra-elite-10",
    sportId: "sport-running",
    useCaseId: "uc-gym-training",
    score: 90,
    factors: hpFactors({
      awareness: 48,
      secureFit: 78,
      battery: 72,
      weather: 82,
      sound: 92,
      value: 70,
      versatility: 84,
    }),
    strengths: ["Premium ANC", "ComfortFit for long indoor blocks"],
    compromises: ["Shorter ANC battery"],
    explanation: "Premium gym/treadmill ANC when comfort and spatial sound matter.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-jabra-elite-8-active-gym-training",
    productId: "prod-jabra-elite-8-active",
    sportId: "sport-running",
    useCaseId: "uc-gym-training",
    score: 91,
    factors: hpFactors({
      awareness: 50,
      secureFit: 96,
      battery: 84,
      weather: 96,
      sound: 82,
      value: 76,
      versatility: 88,
    }),
    strengths: ["SecureFit for hard sessions", "IP68 sweat armor"],
    compromises: ["Less refined ANC than Elite 10"],
    explanation: "Bombproof gym and HYROX-style sealed sport buds.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-beats-powerbeats-pro-2-gym-training",
    productId: "prod-beats-powerbeats-pro-2",
    sportId: "sport-running",
    useCaseId: "uc-gym-training",
    score: 89,
    factors: hpFactors({
      awareness: 52,
      secureFit: 96,
      battery: 92,
      weather: 68,
      sound: 86,
      value: 74,
      versatility: 86,
    }),
    strengths: ["Ear-hook hold", "ANC for noisy floors"],
    compromises: ["IPX4 only"],
    explanation: "Apple-hook gym pick when Fit Pro fins aren't enough hold.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-sport-x20-gym-training",
    productId: "prod-soundcore-sport-x20",
    sportId: "sport-running",
    useCaseId: "uc-gym-training",
    score: 88,
    factors: hpFactors({
      awareness: 50,
      secureFit: 94,
      battery: 94,
      weather: 96,
      sound: 78,
      value: 94,
      versatility: 86,
    }),
    strengths: ["IP68 + hooks", "Long battery value"],
    compromises: ["App polish trails flagships"],
    explanation: "Value sealed gym hooks with weather-grade durability.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sony-linkbuds-fit-gym-training",
    productId: "prod-sony-linkbuds-fit",
    sportId: "sport-running",
    useCaseId: "uc-gym-training",
    score: 82,
    factors: hpFactors({
      awareness: 55,
      secureFit: 76,
      battery: 66,
      weather: 64,
      sound: 86,
      value: 74,
      versatility: 80,
    }),
    strengths: ["ANC + LDAC", "Compact supporters"],
    compromises: ["Shorter battery"],
    explanation: "Compact Sony ANC for treadmill and indoor strength blocks.",
    evidenceIds: [...ev],
  },

  // ── Long runs ──────────────────────────────────────────────────────────
  {
    id: "rec-shokz-openrun-pro-2-long-runs",
    productId: "prod-shokz-openrun-pro-2",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 90,
    factors: hpFactors({
      awareness: 95,
      secureFit: 90,
      battery: 90,
      weather: 78,
      sound: 84,
      value: 78,
      versatility: 88,
    }),
    strengths: ["Open-ear long-run awareness", "Stronger sound vs OpenRun"],
    compromises: ["IP55 vs OpenRun IP67"],
    explanation: "Flagship Shokz long-run open-ear when battery and DualPitch matter.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-shokz-openfit-2-long-runs",
    productId: "prod-shokz-openfit-2",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 87,
    factors: hpFactors({
      awareness: 92,
      secureFit: 86,
      battery: 94,
      weather: 78,
      sound: 82,
      value: 80,
      versatility: 86,
    }),
    strengths: ["11h single-charge claim", "Open-ear comfort"],
    compromises: ["Case is extra carry vs wraparound"],
    explanation: "Open-ear long runs with case top-ups for marathon blocks.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-beats-powerbeats-pro-2-long-runs",
    productId: "prod-beats-powerbeats-pro-2",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: hpFactors({
      awareness: 58,
      secureFit: 94,
      battery: 94,
      weather: 66,
      sound: 86,
      value: 74,
      versatility: 82,
    }),
    strengths: ["10h hooks", "Stay-put on long efforts"],
    compromises: ["Awareness needs transparency"],
    explanation: "Long sealed efforts when hooks beat open-ear bass limits.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-sport-x20-long-runs",
    productId: "prod-soundcore-sport-x20",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 85,
    factors: hpFactors({
      awareness: 52,
      secureFit: 92,
      battery: 96,
      weather: 94,
      sound: 78,
      value: 94,
      versatility: 84,
    }),
    strengths: ["12h battery", "IP68 for long wet blocks"],
    compromises: ["Sealed awareness trade-off"],
    explanation: "Value long-run sealed hooks for weather and endurance days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-suunto-wing-long-runs",
    productId: "prod-suunto-wing",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 83,
    factors: hpFactors({
      awareness: 94,
      secureFit: 90,
      battery: 84,
      weather: 92,
      sound: 72,
      value: 68,
      versatility: 82,
    }),
    strengths: ["Open bone conduction", "IP67 longevity"],
    compromises: ["Heavier than OpenRun"],
    explanation: "Long outdoor miles with awareness and night LED optionality.",
    evidenceIds: [...ev],
  },

  // ── Trail training ─────────────────────────────────────────────────────
  {
    id: "rec-shokz-openrun-trail-training",
    productId: "prod-shokz-openrun",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 88,
    factors: hpFactors({
      awareness: 94,
      secureFit: 90,
      battery: 78,
      weather: 94,
      sound: 68,
      value: 90,
      versatility: 84,
    }),
    strengths: ["IP67 trail abuse", "Open awareness"],
    compromises: ["Shorter battery than Pro 2"],
    explanation: "Washable bone conduction for muddy awareness trail days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-jabra-elite-8-active-trail-training",
    productId: "prod-jabra-elite-8-active",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: hpFactors({
      awareness: 55,
      secureFit: 94,
      battery: 84,
      weather: 96,
      sound: 80,
      value: 76,
      versatility: 86,
    }),
    strengths: ["IP68 mud/rain", "SecureFit on technical trails"],
    compromises: ["Lower natural awareness"],
    explanation: "Sealed trail trainer when weather armor beats open-ear sound.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-suunto-wing-trail-training",
    productId: "prod-suunto-wing",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 85,
    factors: hpFactors({
      awareness: 94,
      secureFit: 90,
      battery: 84,
      weather: 92,
      sound: 70,
      value: 68,
      versatility: 82,
    }),
    strengths: ["Open-ear trail awareness", "IP67"],
    compromises: ["Price vs Shokz"],
    explanation: "Trail awareness bone conduction with Suunto outdoor positioning.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-sport-x20-trail-training",
    productId: "prod-soundcore-sport-x20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: hpFactors({
      awareness: 50,
      secureFit: 92,
      battery: 94,
      weather: 96,
      sound: 76,
      value: 92,
      versatility: 82,
    }),
    strengths: ["IP68 value", "Hook secureFit"],
    compromises: ["Sealed hearing"],
    explanation: "Budget sealed trail hooks for wet technical sessions.",
    evidenceIds: [...ev],
  },

  // ── Rain running ───────────────────────────────────────────────────────
  {
    id: "rec-shokz-openrun-rain-running",
    productId: "prod-shokz-openrun",
    sportId: "sport-running",
    useCaseId: "uc-rain-running",
    score: 93,
    factors: hpFactors({
      awareness: 94,
      secureFit: 90,
      battery: 78,
      weather: 96,
      sound: 68,
      value: 90,
      versatility: 84,
    }),
    strengths: ["IP67 rinseable", "Open-ear in wet traffic"],
    compromises: ["Magnetic charge port care"],
    explanation: "Top rain-day open bone conduction when washability matters.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-jabra-elite-8-active-rain-running",
    productId: "prod-jabra-elite-8-active",
    sportId: "sport-running",
    useCaseId: "uc-rain-running",
    score: 92,
    factors: hpFactors({
      awareness: 52,
      secureFit: 94,
      battery: 84,
      weather: 98,
      sound: 80,
      value: 76,
      versatility: 86,
    }),
    strengths: ["IP68-class weather", "SecureFit in wet conditions"],
    compromises: ["Sealed awareness"],
    explanation: "Sealed rain armor when you accept HearThrough vs open-ear.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soundcore-sport-x20-rain-running",
    productId: "prod-soundcore-sport-x20",
    sportId: "sport-running",
    useCaseId: "uc-rain-running",
    score: 91,
    factors: hpFactors({
      awareness: 50,
      secureFit: 92,
      battery: 94,
      weather: 98,
      sound: 76,
      value: 94,
      versatility: 84,
    }),
    strengths: ["IP68 value", "Long wet-block battery"],
    compromises: ["Not open-ear"],
    explanation: "Value IP68 hooks for rainy road and trail sessions.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-suunto-wing-rain-running",
    productId: "prod-suunto-wing",
    sportId: "sport-running",
    useCaseId: "uc-rain-running",
    score: 88,
    factors: hpFactors({
      awareness: 94,
      secureFit: 90,
      battery: 84,
      weather: 94,
      sound: 70,
      value: 68,
      versatility: 82,
    }),
    strengths: ["IP67 open-ear", "Wraparound fit"],
    compromises: ["Pricier than OpenRun"],
    explanation: "Rain-capable bone conduction with outdoor LED extras.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-shokz-openfit-2-rain-running",
    productId: "prod-shokz-openfit-2",
    sportId: "sport-running",
    useCaseId: "uc-rain-running",
    score: 78,
    factors: hpFactors({
      awareness: 90,
      secureFit: 86,
      battery: 90,
      weather: 78,
      sound: 80,
      value: 80,
      versatility: 84,
    }),
    strengths: ["IP55 open-ear", "Awareness in light rain"],
    compromises: ["Not OpenRun IP67 washability"],
    explanation: "Light-rain open-ear when you want hooks and a case, not IP67.",
    evidenceIds: [...ev],
  },
];
