import type { ProductFamily } from "@/domain/products/types";

/** Hydration / packs / belts families for running catalog wave 2. */
export const runningHydrationFamilies: ProductFamily[] = [
  {
    id: "fam-black-diamond-distance",
    brandId: "brand-black-diamond",
    name: "Distance",
    slug: "bd-distance",
    categoryId: "cat-packs-vests",
    description: "Black Diamond trail distance packs and fastpacking volumes.",
    productIds: [
      "prod-black-diamond-distance-8",
      "prod-black-diamond-distance-15",
      "prod-black-diamond-distance-22",
    ],
  },
  {
    id: "fam-camelbak-apex",
    brandId: "brand-camelbak",
    name: "Apex",
    slug: "apex",
    categoryId: "cat-packs-vests",
    description: "CamelBak premium trail run vests.",
    productIds: ["prod-camelbak-apex-pro"],
  },
  {
    id: "fam-camelbak-circuit",
    brandId: "brand-camelbak",
    name: "Circuit",
    slug: "circuit",
    categoryId: "cat-packs-vests",
    description: "CamelBak entry run vests.",
    productIds: ["prod-camelbak-circuit"],
  },
  {
    id: "fam-camelbak-crux",
    brandId: "brand-camelbak",
    name: "Crux",
    slug: "crux",
    categoryId: "cat-hydration",
    description: "CamelBak Crux reservoirs.",
    productIds: ["prod-camelbak-crux-15"],
  },
  {
    id: "fam-camelbak-zephyr",
    brandId: "brand-camelbak",
    name: "Zephyr",
    slug: "zephyr",
    categoryId: "cat-packs-vests",
    description: "CamelBak breathable run vests.",
    productIds: ["prod-camelbak-zephyr", "prod-camelbak-zephyr-pro"],
  },
  {
    id: "fam-compressport-free-belt",
    brandId: "brand-compressport",
    name: "Free Belt",
    slug: "compressport-free-belt",
    categoryId: "cat-running-belts",
    description: "Compressport race belts.",
    productIds: ["prod-compressport-free-belt-pro"],
  },
  {
    id: "fam-compressport-ultrun",
    brandId: "brand-compressport",
    name: "Ultrun",
    slug: "ultrun",
    categoryId: "cat-packs-vests",
    description: "Compressport ultra race packs.",
    productIds: ["prod-compressport-ultrun-s-pack"],
  },
  {
    id: "fam-hydrapak-shape-shift",
    brandId: "brand-hydrapak",
    name: "Shape-Shift",
    slug: "shape-shift",
    categoryId: "cat-hydration",
    description: "HydraPak Shape-Shift reservoirs.",
    productIds: ["prod-hydrapak-shape-shift-15"],
  },
  {
    id: "fam-hydrapak-skyflask",
    brandId: "brand-hydrapak",
    name: "SkyFlask",
    slug: "skyflask",
    categoryId: "cat-hydration",
    description: "HydraPak handheld soft flasks.",
    productIds: ["prod-hydrapak-skyflask-speed-500"],
  },
  {
    id: "fam-hydrapak-softflask",
    brandId: "brand-hydrapak",
    name: "SoftFlask",
    slug: "softflask",
    categoryId: "cat-hydration",
    description: "HydraPak soft flasks.",
    productIds: ["prod-hydrapak-softflask-500", "prod-hydrapak-softflask-speed-500", "prod-hydrapak-softflask-250"],
  },
  {
    id: "fam-hydrapak-tube-kit",
    brandId: "brand-hydrapak",
    name: "Tube Kit",
    slug: "hydrapak-tube-kit",
    categoryId: "cat-hydration",
    description: "HydraPak drink-tube accessories.",
    productIds: ["prod-hydrapak-tube-kit"],
  },
  {
    id: "fam-kiprun-trail",
    brandId: "brand-decathlon",
    name: "Kiprun Trail",
    slug: "kiprun-trail",
    categoryId: "cat-packs-vests",
    description: "Decathlon Kiprun trail vests.",
    productIds: ["prod-kiprun-trail-10"],
  },
  {
    id: "fam-kiprun-900-race",
    brandId: "brand-decathlon",
    name: "Kiprun 900 Race",
    slug: "kiprun-900-race",
    categoryId: "cat-packs-vests",
    description: "Kiprun 5L race flask vests.",
    productIds: ["prod-kiprun-900-race-5"],
  },
  {
    id: "fam-kiprun-proteam",
    brandId: "brand-decathlon",
    name: "Kiprun Proteam",
    slug: "kiprun-proteam",
    categoryId: "cat-packs-vests",
    description: "Kiprun Proteam race vests.",
    productIds: ["prod-kiprun-proteam-10"],
  },
  {
    id: "fam-naked-running-band",
    brandId: "brand-naked",
    name: "Running Band",
    slug: "naked-running-band",
    categoryId: "cat-running-belts",
    description: "Naked stretch race bands.",
    productIds: ["prod-naked-running-band"],
  },
  {
    id: "fam-nathan-peak",
    brandId: "brand-nathan",
    name: "Peak",
    slug: "nathan-peak",
    categoryId: "cat-running-belts",
    description: "Nathan hydration waist packs.",
    productIds: ["prod-nathan-peak"],
  },
  {
    id: "fam-nathan-pinnacle",
    brandId: "brand-nathan",
    name: "Pinnacle",
    slug: "pinnacle",
    categoryId: "cat-packs-vests",
    description: "Nathan bladder-oriented hydration vests.",
    productIds: ["prod-nathan-pinnacle-12"],
  },
  {
    id: "fam-nathan-speeddraw",
    brandId: "brand-nathan",
    name: "SpeedDraw",
    slug: "speeddraw",
    categoryId: "cat-hydration",
    description: "Nathan hard flasks for belts and handhelds.",
    productIds: ["prod-nathan-speeddraw-insulated"],
  },
  {
    id: "fam-nathan-vaporair",
    brandId: "brand-nathan",
    name: "VaporAir",
    slug: "vaporair",
    categoryId: "cat-packs-vests",
    description: "Nathan soft-flask race vests.",
    productIds: ["prod-nathan-vaporair-2", "prod-nathan-vaporair-4"],
  },
  {
    id: "fam-nnormal-race-vest",
    brandId: "brand-nnormal",
    name: "Race Vest",
    slug: "nnormal-race-vest",
    categoryId: "cat-packs-vests",
    description: "NNormal race-minimal hydration vests.",
    productIds: ["prod-nnormal-race-vest"],
  },
  {
    id: "fam-on-ultra-vest",
    brandId: "brand-on",
    name: "Ultra Vest",
    slug: "on-ultra-vest",
    categoryId: "cat-packs-vests",
    description: "On ultra-distance race vests.",
    productIds: ["prod-on-ultra-vest-pro"],
  },
  {
    id: "fam-osprey-duro",
    brandId: "brand-osprey",
    name: "Duro",
    slug: "duro",
    categoryId: "cat-packs-vests",
    description: "Osprey men's-fit running packs.",
    productIds: ["prod-osprey-duro-6", "prod-osprey-duro-lt", "prod-osprey-duro-15"],
  },
  {
    id: "fam-osprey-dyna",
    brandId: "brand-osprey",
    name: "Dyna",
    slug: "dyna",
    categoryId: "cat-packs-vests",
    description: "Osprey women's-fit running packs.",
    productIds: ["prod-osprey-dyna-6", "prod-osprey-dyna-lt"],
  },
  {
    id: "fam-osprey-hydraulics",
    brandId: "brand-osprey",
    name: "Hydraulics",
    slug: "hydraulics",
    categoryId: "cat-hydration",
    description: "Osprey Hydraulics reservoirs.",
    productIds: ["prod-osprey-hydraulics-15"],
  },
  {
    id: "fam-patagonia-slope-runner",
    brandId: "brand-patagonia",
    name: "Slope Runner",
    slug: "slope-runner",
    categoryId: "cat-packs-vests",
    description: "Patagonia lightweight trail race vests.",
    productIds: ["prod-patagonia-slope-runner"],
  },
  {
    id: "fam-raidlight-responsiv",
    brandId: "brand-raidlight",
    name: "Responsiv",
    slug: "responsiv",
    categoryId: "cat-packs-vests",
    description: "RaidLight trail race vests.",
    productIds: ["prod-raidlight-responsiv-12"],
  },
  {
    id: "fam-salomon-pulse-belt",
    brandId: "brand-salomon",
    name: "Pulse Belt",
    slug: "salomon-pulse-belt",
    categoryId: "cat-running-belts",
    description: "Salomon pulse race belts.",
    productIds: ["prod-salomon-pulse-belt"],
  },
  {
    id: "fam-ud-race-belt",
    brandId: "brand-ultimate-direction",
    name: "Race Belt",
    slug: "ud-race-belt",
    categoryId: "cat-running-belts",
    description: "Ultimate Direction race belts.",
    productIds: ["prod-ud-race-belt"],
  },
  {
    id: "fam-ud-race-vest",
    brandId: "brand-ultimate-direction",
    name: "Race Vest",
    slug: "ud-race-vest",
    categoryId: "cat-packs-vests",
    description: "Ultimate Direction race-day vests.",
    productIds: ["prod-ud-race-vest-6"],
  },
  {
    id: "fam-ud-ultra-belt",
    brandId: "brand-ultimate-direction",
    name: "Ultra Belt",
    slug: "ud-ultra-belt",
    categoryId: "cat-running-belts",
    description: "Ultimate Direction high-volume belts.",
    productIds: ["prod-ud-ultra-belt"],
  },
  {
    id: "fam-ultraspire-alpha",
    brandId: "brand-ultraspire",
    name: "Alpha",
    slug: "ultraspire-alpha",
    categoryId: "cat-packs-vests",
    description: "UltrAspire race vests.",
    productIds: ["prod-ultraspire-alpha-6"],
  },
  {
    id: "fam-ultraspire-fitted-race-belt",
    brandId: "brand-ultraspire",
    name: "Fitted Race Belt",
    slug: "ultraspire-fitted-race-belt",
    categoryId: "cat-running-belts",
    description: "UltrAspire fitted race belts.",
    productIds: ["prod-ultraspire-fitted-race-belt"],
  },
  {
    id: "fam-ultraspire-spry",
    brandId: "brand-ultraspire",
    name: "Spry",
    slug: "ultraspire-spry",
    categoryId: "cat-packs-vests",
    description: "UltrAspire compact race vests.",
    productIds: ["prod-ultraspire-spry-5"],
  },
  {
    id: "fam-uswe-pace",
    brandId: "brand-uswe",
    name: "Pace",
    slug: "uswe-pace",
    categoryId: "cat-packs-vests",
    description: "USWE NDM trail race vests.",
    productIds: ["prod-uswe-pace-8"],
  },
  // Pre-launch 06 — missing hydration / belt families
  {
    id: "fam-salomon-soft-flask",
    brandId: "brand-salomon",
    name: "Soft Flask",
    slug: "salomon-soft-flask",
    categoryId: "cat-hydration",
    description: "Salomon soft flasks for vests and belts.",
    productIds: ["prod-salomon-soft-flask-speed-500"],
  },
  {
    id: "fam-ud-body-bottle",
    brandId: "brand-ultimate-direction",
    name: "Body Bottle",
    slug: "ud-body-bottle",
    categoryId: "cat-hydration",
    description: "Ultimate Direction body bottles.",
    productIds: ["prod-ud-body-bottle-500"],
  },
  {
    id: "fam-nathan-softflask",
    brandId: "brand-nathan",
    name: "SoftFlask",
    slug: "nathan-softflask",
    categoryId: "cat-hydration",
    description: "Nathan soft flasks.",
    productIds: ["prod-nathan-softflask-18oz"],
  },
  {
    id: "fam-amphipod-hydraform",
    brandId: "brand-amphipod",
    name: "Hydraform",
    slug: "amphipod-hydraform",
    categoryId: "cat-hydration",
    description: "Amphipod Hydraform handhelds.",
    productIds: ["prod-amphipod-hydraform-handheld"],
  },
  {
    id: "fam-nathan-quickdraw",
    brandId: "brand-nathan",
    name: "QuickDraw",
    slug: "nathan-quickdraw",
    categoryId: "cat-hydration",
    description: "Nathan QuickDraw handhelds.",
    productIds: ["prod-nathan-quickdraw-plus"],
  },
  {
    id: "fam-camelbak-quick-grip",
    brandId: "brand-camelbak",
    name: "Quick Grip",
    slug: "camelbak-quick-grip",
    categoryId: "cat-hydration",
    description: "CamelBak Quick Grip handhelds.",
    productIds: ["prod-camelbak-quick-grip-chill"],
  },
  {
    id: "fam-hydrapak-contour",
    brandId: "brand-hydrapak",
    name: "Contour",
    slug: "hydrapak-contour",
    categoryId: "cat-hydration",
    description: "HydraPak Contour reservoirs.",
    productIds: ["prod-hydrapak-contour-2l"],
  },
  {
    id: "fam-salomon-soft-reservoir",
    brandId: "brand-salomon",
    name: "Soft Reservoir",
    slug: "salomon-soft-reservoir",
    categoryId: "cat-hydration",
    description: "Salomon soft reservoirs.",
    productIds: ["prod-salomon-soft-reservoir-15"],
  },
  {
    id: "fam-amphipod-airflow-belt",
    brandId: "brand-amphipod",
    name: "AirFlow Belt",
    slug: "amphipod-airflow-belt",
    categoryId: "cat-running-belts",
    description: "Amphipod AirFlow running belts.",
    productIds: ["prod-amphipod-airflow-lite-belt"],
  },
  {
    id: "fam-fitletic-fully-loaded",
    brandId: "brand-fitletic",
    name: "Fully Loaded",
    slug: "fitletic-fully-loaded",
    categoryId: "cat-running-belts",
    description: "Fitletic Fully Loaded running belts.",
    productIds: ["prod-fitletic-fully-loaded"],
  },
  {
    id: "fam-nathan-zipster",
    brandId: "brand-nathan",
    name: "Zipster",
    slug: "nathan-zipster",
    categoryId: "cat-running-belts",
    description: "Nathan Zipster running belts.",
    productIds: ["prod-nathan-zipster-lite"],
  },
  {
    id: "fam-kiprun-belt",
    brandId: "brand-decathlon",
    name: "Running Belt",
    slug: "kiprun-belt",
    categoryId: "cat-running-belts",
    description: "Kiprun running belts.",
    productIds: ["prod-kiprun-running-belt"],
  },
];
