/**
 * Light suitability scores for running nutrition wave 1.
 * Factors: format, carbohydrate-delivery, caffeine-preference, carrying,
 * taste-texture, race-use, value. Explanations stay non-medical.
 *
 * Not wired into recommendations aggregators yet (parent will wire).
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const nutFactors = (scores: {
  format: number;
  carbs: number;
  caffeine: number;
  carrying: number;
  taste: number;
  race: number;
  value: number;
}) => [
  {
    key: "format",
    label: "Format",
    score: scores.format,
    weight: 0.16,
    explanation: "Gel, chew, bar, powder, or tablet practicality for the session.",
  },
  {
    key: "carbohydrate-delivery",
    label: "Carbohydrate delivery",
    score: scores.carbs,
    weight: 0.2,
    explanation: "How well labeled carbs per serving support the fueling target.",
  },
  {
    key: "caffeine-preference",
    label: "Caffeine preference",
    score: scores.caffeine,
    weight: 0.12,
    explanation: "Fit for caffeinated vs non-caffeinated fueling preference.",
  },
  {
    key: "carrying",
    label: "Carrying",
    score: scores.carrying,
    weight: 0.14,
    explanation: "Pocket, vest, and belt practicality while running.",
  },
  {
    key: "taste-texture",
    label: "Taste / texture",
    score: scores.taste,
    weight: 0.12,
    explanation: "Flavour and mouthfeel for repeated use on long efforts.",
  },
  {
    key: "race-use",
    label: "Race use",
    score: scores.race,
    weight: 0.14,
    explanation: "Practicality for race-day fueling routines.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.12,
    explanation: "Cost relative to carbs, format convenience, and availability.",
  },
];

export const runningNutritionRecommendations: Recommendation[] = [
  // ── Maurten Gel 100 ────────────────────────────────────────────────────
  {
    id: "rec-maurten-gel-100-marathon",
    productId: "prod-maurten-gel-100",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 90,
    factors: nutFactors({ format: 92, carbs: 86, caffeine: 88, carrying: 94, taste: 84, race: 92, value: 66 }),
    strengths: ["25g carb sachets", "Firm hydrogel texture", "No caffeine"],
    compromises: ["Premium price", "Low sodium"],
    explanation: "Strong marathon gel when you want precise non-caf carb units.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-gel-100-high-carb",
    productId: "prod-maurten-gel-100",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 86,
    factors: nutFactors({ format: 90, carbs: 82, caffeine: 90, carrying: 92, taste: 84, race: 88, value: 64 }),
    strengths: ["Easy carb math", "Stacks with Gel 160 / drink mix"],
    compromises: ["Need more packets than 40g gels"],
    explanation: "Works in high-carb plans if you accept more sachets than Gel 160.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-gel-100-non-caf",
    productId: "prod-maurten-gel-100",
    sportId: "sport-running",
    useCaseId: "uc-non-caffeinated-fuel",
    score: 92,
    factors: nutFactors({ format: 92, carbs: 86, caffeine: 96, carrying: 94, taste: 84, race: 90, value: 66 }),
    strengths: ["Caffeine-free", "Neutral flavour"],
    compromises: ["Cost"],
    explanation: "Top pick when non-caffeinated hydrogel gels are the preference.",
    evidenceIds: [...ev],
  },

  // ── Maurten Gel 100 Caf ────────────────────────────────────────────────
  {
    id: "rec-maurten-gel-100-caf-caffeinated",
    productId: "prod-maurten-gel-100-caf",
    sportId: "sport-running",
    useCaseId: "uc-caffeinated-fuel",
    score: 93,
    factors: nutFactors({ format: 92, carbs: 86, caffeine: 96, carrying: 94, taste: 82, race: 92, value: 64 }),
    strengths: ["~100mg caffeine per sachet", "Same 25g carb dose"],
    compromises: ["Premium price"],
    explanation: "Best Maurten option when late-race caffeine preference is clear.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-gel-100-caf-marathon",
    productId: "prod-maurten-gel-100-caf",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 88,
    factors: nutFactors({ format: 92, carbs: 86, caffeine: 90, carrying: 94, taste: 82, race: 90, value: 64 }),
    strengths: ["Easy late-mile caffeine + carbs"],
    compromises: ["Use sparingly with a practiced plan"],
    explanation: "Strong for planned late-marathon caffeinated servings.",
    evidenceIds: [...ev],
  },

  // ── Maurten Gel 160 ────────────────────────────────────────────────────
  {
    id: "rec-maurten-gel-160-high-carb",
    productId: "prod-maurten-gel-160",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 94,
    factors: nutFactors({ format: 90, carbs: 96, caffeine: 90, carrying: 88, taste: 84, race: 94, value: 70 }),
    strengths: ["40g carbs per packet", "Fewer sachets per hour"],
    compromises: ["Larger single carb hit to practice"],
    explanation: "High-carb race gel when packet count is the constraint.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-gel-160-marathon",
    productId: "prod-maurten-gel-160",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 91,
    factors: nutFactors({ format: 90, carbs: 94, caffeine: 88, carrying: 88, taste: 84, race: 92, value: 68 }),
    strengths: ["Dense gel format", "Non-caffeinated"],
    compromises: ["Premium cost"],
    explanation: "Excellent marathon density gel for practiced high-carb plans.",
    evidenceIds: [...ev],
  },

  // ── SiS GO / Beta Fuel gels ────────────────────────────────────────────
  {
    id: "rec-sis-go-short-training",
    productId: "prod-sis-go-isotonic-gel",
    sportId: "sport-running",
    useCaseId: "uc-short-training",
    score: 88,
    factors: nutFactors({ format: 90, carbs: 74, caffeine: 90, carrying: 90, taste: 86, race: 78, value: 90 }),
    strengths: ["Thin isotonic texture", "Easy beginner format"],
    compromises: ["Lower carbs per packet"],
    explanation: "Approachable gel for shorter sessions and gel newcomers.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sis-go-easy-carry",
    productId: "prod-sis-go-isotonic-gel",
    sportId: "sport-running",
    useCaseId: "uc-easy-carry-fuel",
    score: 86,
    factors: nutFactors({ format: 88, carbs: 74, caffeine: 90, carrying: 92, taste: 86, race: 80, value: 90 }),
    strengths: ["Soft packet", "Wide flavour choice"],
    compromises: ["More packets for big carb targets"],
    explanation: "Easy vest/belt carry for everyday training gels.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sis-beta-gel-marathon",
    productId: "prod-sis-beta-fuel-gel",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 89,
    factors: nutFactors({ format: 88, carbs: 94, caffeine: 88, carrying: 86, taste: 80, race: 90, value: 80 }),
    strengths: ["40g carbs", "Dual-source race format"],
    compromises: ["Thicker than GO Isotonic"],
    explanation: "Strong SiS race gel when you want high carbs with retail availability.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sis-beta-gel-high-carb",
    productId: "prod-sis-beta-fuel-gel",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 90,
    factors: nutFactors({ format: 88, carbs: 95, caffeine: 88, carrying: 86, taste: 80, race: 90, value: 80 }),
    strengths: ["40g per gel", "Pairs with Beta Fuel drink"],
    compromises: ["Fewer flavours than GO"],
    explanation: "High-carb gel lane with matching drink-mix continuity.",
    evidenceIds: [...ev],
  },

  // ── GU gels ────────────────────────────────────────────────────────────
  {
    id: "rec-gu-energy-long-runs",
    productId: "prod-gu-energy-gel",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 82,
    factors: nutFactors({ format: 86, carbs: 76, caffeine: 84, carrying: 92, taste: 84, race: 80, value: 92 }),
    strengths: ["Ubiquitous flavours", "Great value"],
    compromises: ["~22g carbs only"],
    explanation: "Reliable long-run practice gel with easy shopping availability.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-gu-energy-easy-carry",
    productId: "prod-gu-energy-gel",
    sportId: "sport-running",
    useCaseId: "uc-easy-carry-fuel",
    score: 86,
    factors: nutFactors({ format: 88, carbs: 76, caffeine: 84, carrying: 94, taste: 84, race: 80, value: 92 }),
    strengths: ["Compact packets", "Belt-friendly"],
    compromises: ["Sticky texture for some"],
    explanation: "Classic easy-carry gel for training and racing.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-gu-roctane-ultra",
    productId: "prod-gu-roctane-gel",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 80,
    factors: nutFactors({ format: 86, carbs: 74, caffeine: 86, carrying: 92, taste: 80, race: 82, value: 76 }),
    strengths: ["Higher sodium than classic GU", "Caffeine flavours available"],
    compromises: ["Still not a 30–40g carb gel"],
    explanation: "Useful ultra variety when you want GU format with more sodium.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-gu-roctane-caffeinated",
    productId: "prod-gu-roctane-gel",
    sportId: "sport-running",
    useCaseId: "uc-caffeinated-fuel",
    score: 84,
    factors: nutFactors({ format: 86, carbs: 74, caffeine: 90, carrying: 92, taste: 80, race: 84, value: 76 }),
    strengths: ["Caffeinated flavour options", "Familiar GU packet"],
    compromises: ["Caffeine amount varies by flavour"],
    explanation: "Accessible caffeinated gel when Maurten Caf pricing is too high.",
    evidenceIds: [...ev],
  },

  // ── Precision / Neversecond gels ───────────────────────────────────────
  {
    id: "rec-pf30-gel-high-carb",
    productId: "prod-precision-pf30-gel",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 92,
    factors: nutFactors({ format: 92, carbs: 92, caffeine: 90, carrying: 94, taste: 88, race: 92, value: 76 }),
    strengths: ["Clean 30g units", "Mild low-stick texture"],
    compromises: ["Electrolytes sold separately"],
    explanation: "Modular high-carb gel math with low flavour fatigue.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-pf30-gel-marathon",
    productId: "prod-precision-pf30-gel",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 91,
    factors: nutFactors({ format: 92, carbs: 90, caffeine: 90, carrying: 94, taste: 88, race: 92, value: 76 }),
    strengths: ["Easy race counting", "Mild flavour"],
    compromises: ["Less retail ubiquity than GU"],
    explanation: "Excellent marathon gel for structured non-caf carb plans.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-c30-gel-marathon",
    productId: "prod-neversecond-c30-gel",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 90,
    factors: nutFactors({ format: 90, carbs: 90, caffeine: 88, carrying: 92, taste: 82, race: 90, value: 74 }),
    strengths: ["30g carbs", "Meaningful sodium in-packet"],
    compromises: ["Narrower retail footprint"],
    explanation: "Strong race gel when you want carbs and sodium in one unit.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-c30-gel-high-carb",
    productId: "prod-neversecond-c30-gel",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 89,
    factors: nutFactors({ format: 90, carbs: 90, caffeine: 88, carrying: 92, taste: 82, race: 88, value: 74 }),
    strengths: ["Matches C30 drink scoops", "Modular system"],
    compromises: ["Premium vs value gels"],
    explanation: "High-carb system gel that scales with C30 drink mix.",
    evidenceIds: [...ev],
  },

  // ── Real-food / honey gels ─────────────────────────────────────────────
  {
    id: "rec-spring-ultra",
    productId: "prod-spring-awesome-sauce",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 78,
    factors: nutFactors({ format: 80, carbs: 70, caffeine: 88, carrying: 84, taste: 86, race: 76, value: 62 }),
    strengths: ["Real-food texture variety", "Trail-friendly pouch"],
    compromises: ["Treat carb labels conservatively"],
    explanation: "Texture-break gel for ultras when syrup gels fatigue.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-huma-trail",
    productId: "prod-huma-gel-original",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: nutFactors({ format: 84, carbs: 80, caffeine: 90, carrying: 88, taste: 86, race: 78, value: 70 }),
    strengths: ["Chia/fruit texture", "Sea-salt sodium"],
    compromises: ["Seeds not for every runner"],
    explanation: "Good trail long-run alternative to syrup gels.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-honey-stinger-half",
    productId: "prod-honey-stinger-gel",
    sportId: "sport-running",
    useCaseId: "uc-half",
    score: 80,
    factors: nutFactors({ format: 86, carbs: 78, caffeine: 90, carrying: 90, taste: 86, race: 78, value: 82 }),
    strengths: ["Honey taste", "Easy training gel"],
    compromises: ["Not a high-carb race primary"],
    explanation: "Solid half-marathon / training gel for honey preference.",
    evidenceIds: [...ev],
  },

  // ── Chews ──────────────────────────────────────────────────────────────
  {
    id: "rec-clif-bloks-long-runs",
    productId: "prod-clif-bloks",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 88,
    factors: nutFactors({ format: 90, carbs: 90, caffeine: 84, carrying: 90, taste: 86, race: 82, value: 88 }),
    strengths: ["Portionable", "High carbs per packet"],
    compromises: ["Chewing under hard effort"],
    explanation: "Top chew for long runs when you want to nibble carbs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-clif-bloks-easy-carry",
    productId: "prod-clif-bloks",
    sportId: "sport-running",
    useCaseId: "uc-easy-carry-fuel",
    score: 87,
    factors: nutFactors({ format: 90, carbs: 88, caffeine: 84, carrying: 92, taste: 86, race: 80, value: 88 }),
    strengths: ["Pocket-friendly", "Split servings"],
    compromises: ["Heat can soften packets"],
    explanation: "Easy-carry chew format for belts and vest pockets.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-gu-chews-short",
    productId: "prod-gu-chews",
    sportId: "sport-running",
    useCaseId: "uc-short-training",
    score: 82,
    factors: nutFactors({ format: 88, carbs: 74, caffeine: 86, carrying: 90, taste: 84, race: 74, value: 84 }),
    strengths: ["Soft texture", "Familiar GU flavours"],
    compromises: ["Lower carbs per serving"],
    explanation: "Light chew option for shorter sessions and texture variety.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-skratch-chews-trail",
    productId: "prod-skratch-chews",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: nutFactors({ format: 86, carbs: 84, caffeine: 90, carrying: 88, taste: 88, race: 78, value: 72 }),
    strengths: ["Pairs with Skratch bottles", "Fruit-forward"],
    compromises: ["Premium vs Bloks"],
    explanation: "Trail chew that matches Skratch hydration taste preferences.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-veloforte-chews-ultra",
    productId: "prod-veloforte-chews",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 78,
    factors: nutFactors({ format: 84, carbs: 72, caffeine: 90, carrying: 86, taste: 88, race: 74, value: 70 }),
    strengths: ["Natural flavour break", "Ultra texture variety"],
    compromises: ["Confirm label carbs by SKU"],
    explanation: "Useful ultra chew when you want non-syrup flavour rotation.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-saltstick-fastchews-long",
    productId: "prod-saltstick-fastchews",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 80,
    factors: nutFactors({ format: 88, carbs: 40, caffeine: 90, carrying: 96, taste: 72, race: 82, value: 80 }),
    strengths: ["Tiny electrolyte carry", "No mixing"],
    compromises: ["Not a carb fuel"],
    explanation: "Carry-friendly electrolyte chew alongside separate carb gels.",
    evidenceIds: [...ev],
  },

  // ── Bars ───────────────────────────────────────────────────────────────
  {
    id: "rec-clif-bar-ultra",
    productId: "prod-clif-bar-original",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: nutFactors({ format: 82, carbs: 86, caffeine: 90, carrying: 84, taste: 84, race: 78, value: 90 }),
    strengths: ["Dense calories", "Widely available"],
    compromises: ["Hard to chew at race pace"],
    explanation: "Ultra aid-style bar for slower sections and real chewable fuel.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-naak-bar-ultra",
    productId: "prod-naak-ultra-energy-bar",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 86,
    factors: nutFactors({ format: 84, carbs: 82, caffeine: 90, carrying: 86, taste: 84, race: 82, value: 74 }),
    strengths: ["Ultra-oriented bar", "Carbs + protein"],
    compromises: ["Still a chewable format"],
    explanation: "Strong ultra bar when you want denser trail food than gels alone.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-powerbar-long-runs",
    productId: "prod-powerbar-energize",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 82,
    factors: nutFactors({ format: 82, carbs: 84, caffeine: 90, carrying: 84, taste: 78, race: 80, value: 80 }),
    strengths: ["Endurance bar carbs", "Race-table familiarity"],
    compromises: ["Needs fluid while chewing"],
    explanation: "Practical long-run bar alternative to endless gels.",
    evidenceIds: [...ev],
  },
  // ── Carb drinks / race fuel ────────────────────────────────────────────
  {
    id: "rec-maurten-160-drink-based",
    productId: "prod-maurten-drink-mix-160",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 90,
    factors: nutFactors({ format: 90, carbs: 88, caffeine: 90, carrying: 78, taste: 88, race: 88, value: 66 }),
    strengths: ["40g carbs per 500ml", "Mild taste"],
    compromises: ["Needs bottle capacity"],
    explanation: "Clean bottle fuel when you want hydrogel carbs without caffeine.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-320-high-carb",
    productId: "prod-maurten-drink-mix-320",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 95,
    factors: nutFactors({ format: 90, carbs: 98, caffeine: 90, carrying: 76, taste: 86, race: 94, value: 64 }),
    strengths: ["80g carbs per bottle", "Race-dense format"],
    compromises: ["Needs practiced tolerance"],
    explanation: "Flagship high-carb bottle mix for aggressive race fueling.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-maurten-320-marathon",
    productId: "prod-maurten-drink-mix-320",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 92,
    factors: nutFactors({ format: 90, carbs: 96, caffeine: 88, carrying: 76, taste: 86, race: 94, value: 64 }),
    strengths: ["Large carb share in one flask", "Mild flavour"],
    compromises: ["Premium cost"],
    explanation: "Top marathon drink-mix option for bottle-first carb plans.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-sis-beta-drink-high-carb",
    productId: "prod-sis-beta-fuel-drink",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 90,
    factors: nutFactors({ format: 88, carbs: 96, caffeine: 88, carrying: 76, taste: 78, race: 90, value: 78 }),
    strengths: ["~80g carb serving", "Matches Beta Fuel gels"],
    compromises: ["Sweetness can build"],
    explanation: "High-carb SiS bottle fuel with gel-line continuity.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tailwind-drink-based",
    productId: "prod-tailwind-endurance",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 92,
    factors: nutFactors({ format: 92, carbs: 84, caffeine: 88, carrying: 80, taste: 86, race: 86, value: 90 }),
    strengths: ["Carbs + sodium together", "Scalable scoops"],
    compromises: ["Single scoop is not 80g denserace fuel"],
    explanation: "Best all-in-one bottle approach for many long runs and ultras.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tailwind-ultra",
    productId: "prod-tailwind-endurance",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 90,
    factors: nutFactors({ format: 92, carbs: 84, caffeine: 88, carrying: 80, taste: 86, race: 88, value: 90 }),
    strengths: ["All-day bottle simplicity", "Strong value"],
    compromises: ["May still want gels for texture variety"],
    explanation: "Ultra favourite when drink-based fueling is the primary plan.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-pf30-drink-drink-based",
    productId: "prod-precision-pf30-drink",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 88,
    factors: nutFactors({ format: 90, carbs: 88, caffeine: 90, carrying: 78, taste: 88, race: 88, value: 74 }),
    strengths: ["30g modular units", "Mild flavour"],
    compromises: ["Sodium handled separately"],
    explanation: "Bottle fuel that matches PF 30 Gel counting for race systems.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-c30-drink-drink-based",
    productId: "prod-neversecond-c30-drink",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 89,
    factors: nutFactors({ format: 90, carbs: 88, caffeine: 90, carrying: 78, taste: 86, race: 88, value: 76 }),
    strengths: ["30g + 200mg sodium per scoop", "Scalable"],
    compromises: ["Multiple scoops for denser bottles"],
    explanation: "Modular drink-based fuel with sodium built into each scoop.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-styrkr-mix90-high-carb",
    productId: "prod-styrkr-mix90",
    sportId: "sport-running",
    useCaseId: "uc-high-carb-fueling",
    score: 93,
    factors: nutFactors({ format: 88, carbs: 98, caffeine: 90, carrying: 76, taste: 80, race: 92, value: 84 }),
    strengths: ["90g carbs per serving", "Strong value vs Maurten 320"],
    compromises: ["Dense mix needs practice"],
    explanation: "High-carb bottle mix when you want maximum carbs per flask.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-styrkr-mix90-marathon",
    productId: "prod-styrkr-mix90",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 88,
    factors: nutFactors({ format: 86, carbs: 96, caffeine: 88, carrying: 74, taste: 80, race: 90, value: 84 }),
    strengths: ["Single dense bottle", "Dual-carb format"],
    compromises: ["Confirm non-caf SKU"],
    explanation: "Marathon bottle option for advanced high-carb drink plans.",
    evidenceIds: [...ev],
  },

  // ── Electrolytes ───────────────────────────────────────────────────────
  {
    id: "rec-skratch-hydration-long",
    productId: "prod-skratch-sport-hydration",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 88,
    factors: nutFactors({ format: 90, carbs: 70, caffeine: 90, carrying: 78, taste: 90, race: 82, value: 78 }),
    strengths: ["Light carbs + solid sodium", "Great everyday taste"],
    compromises: ["Not enough carbs alone for race dens plans"],
    explanation: "Everyday long-run bottle mix when you want electrolytes plus light carbs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-skratch-hydration-drink-based",
    productId: "prod-skratch-sport-hydration",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 84,
    factors: nutFactors({ format: 90, carbs: 68, caffeine: 90, carrying: 78, taste: 90, race: 80, value: 78 }),
    strengths: ["Easy bottle routine", "Real-fruit flavours"],
    compromises: ["Add gels for higher carb targets"],
    explanation: "Drink-based training fuel for moderate carb + electrolyte needs.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-ph1500-long",
    productId: "prod-precision-ph1500",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 86,
    factors: nutFactors({ format: 86, carbs: 35, caffeine: 90, carrying: 76, taste: 78, race: 86, value: 72 }),
    strengths: ["High sodium separate from carbs", "Pairs with PF gels"],
    compromises: ["Not a carb source"],
    explanation: "Electrolyte-first mix when carb fueling is handled elsewhere.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-ph1500-marathon",
    productId: "prod-precision-ph1500",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 84,
    factors: nutFactors({ format: 84, carbs: 32, caffeine: 90, carrying: 74, taste: 78, race: 88, value: 72 }),
    strengths: ["Keeps sodium independent of gel math"],
    compromises: ["Strength may be high for light sweaters"],
    explanation: "Race electrolyte option alongside separate carb gels or PF 30.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nuun-short",
    productId: "prod-nuun-sport",
    sportId: "sport-running",
    useCaseId: "uc-short-training",
    score: 90,
    factors: nutFactors({ format: 94, carbs: 40, caffeine: 90, carrying: 96, taste: 84, race: 78, value: 92 }),
    strengths: ["Tube portability", "Low carb"],
    compromises: ["Not race carb fuel"],
    explanation: "Easiest electrolyte tablet for short training bottles.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nuun-easy-carry",
    productId: "prod-nuun-sport",
    sportId: "sport-running",
    useCaseId: "uc-easy-carry-fuel",
    score: 91,
    factors: nutFactors({ format: 94, carbs: 40, caffeine: 90, carrying: 98, taste: 84, race: 80, value: 92 }),
    strengths: ["Tiny tube carry", "Drop-in bottle format"],
    compromises: ["Minimal carbs"],
    explanation: "Best easy-carry electrolyte format for travel and race bags.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-high5-zero-drink-based",
    productId: "prod-high5-zero",
    sportId: "sport-running",
    useCaseId: "uc-drink-based-fueling",
    score: 84,
    factors: nutFactors({ format: 92, carbs: 30, caffeine: 92, carrying: 94, taste: 82, race: 80, value: 94 }),
    strengths: ["Zero-carb bottle", "Excellent value"],
    compromises: ["Need gels for carbs"],
    explanation: "Zero-carb tablet when drink bottles should stay electrolyte-only.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-saltstick-caps-ultra",
    productId: "prod-saltstick-caps",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: nutFactors({ format: 86, carbs: 25, caffeine: 90, carrying: 96, taste: 70, race: 86, value: 84 }),
    strengths: ["Pocket electrolytes", "Zero carb"],
    compromises: ["Swallowing capsules mid-effort"],
    explanation: "Ultra capsule electrolytes when bottles are already full of carbs or water.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-saltstick-caps-marathon",
    productId: "prod-saltstick-caps",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 80,
    factors: nutFactors({ format: 84, carbs: 25, caffeine: 90, carrying: 96, taste: 70, race: 84, value: 84 }),
    strengths: ["Tiny carry", "Doesn’t change gel carb math"],
    compromises: ["Not a flavoured drink"],
    explanation: "Marathon electrolyte top-up format alongside gel-based carbs.",
    evidenceIds: [...ev],
  },
];
