import type { ProductFamily } from "@/domain/products/types";

/**
 * Running nutrition / fuel families for wave 1 gels, chews, bars, drink mixes,
 * and electrolytes. Not wired into families aggregators yet (parent will wire).
 */
export const runningNutritionFamilies: ProductFamily[] = [
  {
    id: "fam-maurten-gel",
    brandId: "brand-maurten",
    name: "Maurten Gel",
    slug: "maurten-gel",
    categoryId: "cat-nutrition",
    description: "Maurten hydrogel energy gels for training and racing.",
    productIds: [
      "prod-maurten-gel-100",
      "prod-maurten-gel-100-caf",
      "prod-maurten-gel-160",
    ],
  },
  {
    id: "fam-maurten-drink-mix",
    brandId: "brand-maurten",
    name: "Maurten Drink Mix",
    slug: "maurten-drink-mix",
    categoryId: "cat-nutrition",
    description: "Maurten hydrogel carbohydrate drink mixes.",
    productIds: ["prod-maurten-drink-mix-160", "prod-maurten-drink-mix-320"],
  },
  {
    id: "fam-sis-go",
    brandId: "brand-sis",
    name: "SiS GO",
    slug: "sis-go",
    categoryId: "cat-nutrition",
    description: "Science in Sport GO isotonic gels and everyday fuel.",
    productIds: ["prod-sis-go-isotonic-gel"],
  },
  {
    id: "fam-sis-beta-fuel",
    brandId: "brand-sis",
    name: "SiS Beta Fuel",
    slug: "sis-beta-fuel",
    categoryId: "cat-nutrition",
    description: "Science in Sport Beta Fuel dual-source gels and drink mixes.",
    productIds: ["prod-sis-beta-fuel-gel", "prod-sis-beta-fuel-drink"],
  },
  {
    id: "fam-gu-energy",
    brandId: "brand-gu",
    name: "GU Energy Gel",
    slug: "gu-energy-gel",
    categoryId: "cat-nutrition",
    description: "Classic GU Energy gels.",
    productIds: ["prod-gu-energy-gel"],
  },
  {
    id: "fam-gu-roctane",
    brandId: "brand-gu",
    name: "GU Roctane",
    slug: "gu-roctane",
    categoryId: "cat-nutrition",
    description: "GU Roctane gels with higher sodium and caffeine options.",
    productIds: ["prod-gu-roctane-gel"],
  },
  {
    id: "fam-gu-chews",
    brandId: "brand-gu",
    name: "GU Energy Chews",
    slug: "gu-energy-chews",
    categoryId: "cat-nutrition",
    description: "GU soft energy chews.",
    productIds: ["prod-gu-chews"],
  },
  {
    id: "fam-precision-pf30",
    brandId: "brand-precision-fuel",
    name: "PF 30",
    slug: "precision-pf30",
    categoryId: "cat-nutrition",
    description: "Precision Fuel & Hydration modular 30g carb gels and drink mixes.",
    productIds: ["prod-precision-pf30-gel", "prod-precision-pf30-drink"],
  },
  {
    id: "fam-precision-ph",
    brandId: "brand-precision-fuel",
    name: "PH Electrolytes",
    slug: "precision-ph",
    categoryId: "cat-nutrition",
    description: "Precision Fuel & Hydration electrolyte drink mixes.",
    productIds: ["prod-precision-ph1500"],
  },
  {
    id: "fam-neversecond-c30",
    brandId: "brand-neversecond",
    name: "Neversecond C30",
    slug: "neversecond-c30",
    categoryId: "cat-nutrition",
    description: "Neversecond C30 modular gels and sports drink mixes.",
    productIds: ["prod-neversecond-c30-gel", "prod-neversecond-c30-drink"],
  },
  {
    id: "fam-spring-energy-gels",
    brandId: "brand-spring-energy",
    name: "Spring Energy Gels",
    slug: "spring-energy-gels",
    categoryId: "cat-nutrition",
    description: "Spring Energy real-food texture gels.",
    productIds: ["prod-spring-awesome-sauce"],
  },
  {
    id: "fam-huma-gel",
    brandId: "brand-huma",
    name: "Hüma Gel",
    slug: "huma-gel",
    categoryId: "cat-nutrition",
    description: "Hüma chia-based energy gels.",
    productIds: ["prod-huma-gel-original"],
  },
  {
    id: "fam-honey-stinger-gel",
    brandId: "brand-honey-stinger",
    name: "Honey Stinger Gel",
    slug: "honey-stinger-gel",
    categoryId: "cat-nutrition",
    description: "Honey Stinger organic energy gels.",
    productIds: ["prod-honey-stinger-gel"],
  },
  {
    id: "fam-clif-bloks",
    brandId: "brand-clif",
    name: "CLIF BLOKS",
    slug: "clif-bloks",
    categoryId: "cat-nutrition",
    description: "CLIF BLOKS energy chews.",
    productIds: ["prod-clif-bloks"],
  },
  {
    id: "fam-clif-bar",
    brandId: "brand-clif",
    name: "CLIF Bar",
    slug: "clif-bar",
    categoryId: "cat-nutrition",
    description: "CLIF Bar original energy bars.",
    productIds: ["prod-clif-bar-original"],
  },
  {
    id: "fam-skratch-chews",
    brandId: "brand-skratch",
    name: "Skratch Energy Chews",
    slug: "skratch-energy-chews",
    categoryId: "cat-nutrition",
    description: "Skratch Labs sport energy chews.",
    productIds: ["prod-skratch-chews"],
  },
  {
    id: "fam-skratch-hydration",
    brandId: "brand-skratch",
    name: "Skratch Sport Hydration",
    slug: "skratch-sport-hydration",
    categoryId: "cat-nutrition",
    description: "Skratch Labs sport hydration drink mixes.",
    productIds: ["prod-skratch-sport-hydration"],
  },
  {
    id: "fam-veloforte-chews",
    brandId: "brand-veloforte",
    name: "Veloforte Chews",
    slug: "veloforte-chews",
    categoryId: "cat-nutrition",
    description: "Veloforte natural energy chews.",
    productIds: ["prod-veloforte-chews"],
  },
  {
    id: "fam-saltstick-fastchews",
    brandId: "brand-saltstick",
    name: "SaltStick Fastchews",
    slug: "saltstick-fastchews",
    categoryId: "cat-nutrition",
    description: "SaltStick electrolyte Fastchews.",
    productIds: ["prod-saltstick-fastchews"],
  },
  {
    id: "fam-saltstick-caps",
    brandId: "brand-saltstick",
    name: "SaltStick Caps",
    slug: "saltstick-caps",
    categoryId: "cat-nutrition",
    description: "SaltStick electrolyte capsules.",
    productIds: ["prod-saltstick-caps"],
  },
  {
    id: "fam-naak-ultra",
    brandId: "brand-naak",
    name: "Näak Ultra Energy",
    slug: "naak-ultra-energy",
    categoryId: "cat-nutrition",
    description: "Näak ultra energy bars for long efforts.",
    productIds: ["prod-naak-ultra-energy-bar"],
  },
  {
    id: "fam-powerbar-energize",
    brandId: "brand-powerbar",
    name: "PowerBar Energize",
    slug: "powerbar-energize",
    categoryId: "cat-nutrition",
    description: "PowerBar Energize endurance bars.",
    productIds: ["prod-powerbar-energize"],
  },
  {
    id: "fam-tailwind-endurance",
    brandId: "brand-tailwind",
    name: "Tailwind Endurance Fuel",
    slug: "tailwind-endurance-fuel",
    categoryId: "cat-nutrition",
    description: "Tailwind all-in-one endurance drink mixes.",
    productIds: ["prod-tailwind-endurance"],
  },
  {
    id: "fam-styrkr-mix",
    brandId: "brand-styrkr",
    name: "STYRKR MIX",
    slug: "styrkr-mix",
    categoryId: "cat-nutrition",
    description: "STYRKR dual-carb high-carb drink mixes.",
    productIds: ["prod-styrkr-mix90"],
  },
  {
    id: "fam-nuun-sport",
    brandId: "brand-nuun",
    name: "Nuun Sport",
    slug: "nuun-sport",
    categoryId: "cat-nutrition",
    description: "Nuun Sport electrolyte tablets.",
    productIds: ["prod-nuun-sport"],
  },
  {
    id: "fam-high5-zero",
    brandId: "brand-high5",
    name: "High5 ZERO",
    slug: "high5-zero",
    categoryId: "cat-nutrition",
    description: "High5 ZERO electrolyte tablets.",
    productIds: ["prod-high5-zero"],
  },
  {
    id: "fam-high5-energy-gel",
    brandId: "brand-high5",
    name: "High5 Energy Gel",
    slug: "high5-energy-gel",
    categoryId: "cat-nutrition",
    description: "High5 single-serve energy gels.",
    productIds: ["prod-high5-energy-gel"],
  },
  {
    id: "fam-226ers-high-energy-gel",
    brandId: "brand-226ers",
    name: "226ERS High Energy Gel",
    slug: "226ers-high-energy-gel",
    categoryId: "cat-nutrition",
    description: "226ERS high-carbohydrate gels.",
    productIds: ["prod-226ers-high-energy-gel"],
  },
  {
    id: "fam-enervit-carbo-gel",
    brandId: "brand-enervit",
    name: "Enervit Carbo Gel",
    slug: "enervit-carbo-gel",
    categoryId: "cat-nutrition",
    description: "Enervit C2:1 carbohydrate gels.",
    productIds: ["prod-enervit-carbo-gel"],
  },
  {
    id: "fam-styrkr-gel",
    brandId: "brand-styrkr",
    name: "STYRKR GEL",
    slug: "styrkr-gel",
    categoryId: "cat-nutrition",
    description: "STYRKR dual-carb gels.",
    productIds: ["prod-styrkr-gel30"],
  },
  {
    id: "fam-naak-ultra-drink",
    brandId: "brand-naak",
    name: "Näak Ultra Energy Drink",
    slug: "naak-ultra-energy-drink",
    categoryId: "cat-nutrition",
    description: "Näak ultra drink mixes for long efforts.",
    productIds: ["prod-naak-ultra-energy-drink"],
  },
  {
    id: "fam-veloforte-bar",
    brandId: "brand-veloforte",
    name: "Veloforte Energy Bar",
    slug: "veloforte-energy-bar",
    categoryId: "cat-nutrition",
    description: "Veloforte natural-style energy bars.",
    productIds: ["prod-veloforte-bar"],
  },
];
