/**
 * Light suitability scores for packs & carry wave2 (fastpacking packs,
 * running backpacks, quivers, stash accessories).
 * Factors: capacity, bounce-control, race-kit, pole-carry, versatility, weight, value.
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const packFactors = (scores: {
  capacity: number;
  bounce: number;
  raceKit: number;
  poles: number;
  versatility: number;
  weight: number;
  value: number;
}) => [
  {
    key: "capacity",
    label: "Capacity",
    score: scores.capacity,
    weight: 0.18,
    explanation: "Carry volume for layers, food and overnight kit.",
  },
  {
    key: "bounce-control",
    label: "Bounce control",
    score: scores.bounce,
    weight: 0.16,
    explanation: "Stability while running with a loaded pack.",
  },
  {
    key: "race-kit",
    label: "Race-kit capacity",
    score: scores.raceKit,
    weight: 0.14,
    explanation: "Room for mandatory race layers and kit.",
  },
  {
    key: "pole-carry",
    label: "Pole carry",
    score: scores.poles,
    weight: 0.12,
    explanation: "Pole attachment or quiver compatibility.",
  },
  {
    key: "versatility",
    label: "Versatility",
    score: scores.versatility,
    weight: 0.14,
    explanation: "Trail, ultra, commute and fastpacking flexibility.",
  },
  {
    key: "weight",
    label: "Weight",
    score: scores.weight,
    weight: 0.12,
    explanation: "Pack weight when empty.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.14,
    explanation: "Features vs typical street price.",
  },
];

const accessoryFactors = (scores: {
  capacity: number;
  bounce: number;
  raceKit: number;
  poles: number;
  versatility: number;
  weight: number;
  value: number;
}) => packFactors(scores);

export const runningPacksCarryRecommendations: Recommendation[] = [
  // ── Fastpack 20 ──────────────────────────────────────────────────────
  {
    id: "rec-fastpack-20-fastpacking",
    productId: "prod-ud-fastpack-20",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 94,
    factors: packFactors({
      capacity: 92,
      bounce: 86,
      raceKit: 88,
      poles: 90,
      versatility: 88,
      weight: 72,
      value: 80,
    }),
    strengths: ["Vest-harness front access", "Real overnight rear volume"],
    compromises: ["Heavier than a race vest"],
    explanation: "Top Fastpack pick for overnight and big-day trail kit.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-20-trail-training",
    productId: "prod-ud-fastpack-20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 86,
    factors: packFactors({
      capacity: 90,
      bounce: 84,
      raceKit: 82,
      poles: 90,
      versatility: 86,
      weight: 70,
      value: 80,
    }),
    strengths: ["Big trail-day capacity", "Front bottles + rear roll-top"],
    compromises: ["Overkill for short trail sessions"],
    explanation: "Strong when training days need layers and poles beyond ADV Skin.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-20-ultra",
    productId: "prod-ud-fastpack-20",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 82,
    factors: packFactors({
      capacity: 90,
      bounce: 80,
      raceKit: 86,
      poles: 90,
      versatility: 84,
      weight: 68,
      value: 78,
    }),
    strengths: ["Remote ultra training volume", "Pole-friendly carry"],
    compromises: ["Race-day bounce usually favors ADV Skin"],
    explanation: "Useful for ultra training volume; race days often stay on a vest.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-20-long-runs",
    productId: "prod-ud-fastpack-20",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 78,
    factors: packFactors({
      capacity: 88,
      bounce: 80,
      raceKit: 78,
      poles: 88,
      versatility: 82,
      weight: 66,
      value: 78,
    }),
    strengths: ["Capacity for cold long trail days"],
    compromises: ["Usually more pack than a road long needs"],
    explanation: "Only when long runs need real rear volume and poles.",
    evidenceIds: [...ev],
  },

  // ── FastpackHer 20 ───────────────────────────────────────────────────
  {
    id: "rec-fastpack-her-20-fastpacking",
    productId: "prod-ud-fastpack-her-20",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 94,
    factors: packFactors({
      capacity: 92,
      bounce: 86,
      raceKit: 88,
      poles: 90,
      versatility: 88,
      weight: 72,
      value: 80,
    }),
    strengths: ["Women’s Fastpack patterning", "Overnight-capable volume"],
    compromises: ["Heavier than a race vest"],
    explanation: "Women’s Fastpack starting point for overnight trail kit.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-her-20-trail-training",
    productId: "prod-ud-fastpack-her-20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 86,
    factors: packFactors({
      capacity: 90,
      bounce: 84,
      raceKit: 82,
      poles: 90,
      versatility: 86,
      weight: 70,
      value: 80,
    }),
    strengths: ["Women’s fit for big trail days"],
    compromises: ["Overkill for short sessions"],
    explanation: "Women’s Fastpack when trail days exceed race-vest volume.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-her-20-ultra",
    productId: "prod-ud-fastpack-her-20",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 82,
    factors: packFactors({
      capacity: 90,
      bounce: 80,
      raceKit: 86,
      poles: 90,
      versatility: 84,
      weight: 68,
      value: 78,
    }),
    strengths: ["Remote ultra training capacity"],
    compromises: ["Race days often prefer a vest"],
    explanation: "Women’s Fastpack for volume-heavy ultra training.",
    evidenceIds: [...ev],
  },

  // ── Fastpack 30 ──────────────────────────────────────────────────────
  {
    id: "rec-fastpack-30-fastpacking",
    productId: "prod-ud-fastpack-30",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 96,
    factors: packFactors({
      capacity: 96,
      bounce: 82,
      raceKit: 92,
      poles: 90,
      versatility: 84,
      weight: 64,
      value: 76,
    }),
    strengths: ["Highest Fastpack volume", "Multi-day kit room"],
    compromises: ["Heavier and warmer than Fastpack 20"],
    explanation: "Step-up Fastpack when overnight kit outgrows the 20.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-30-trail-training",
    productId: "prod-ud-fastpack-30",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 80,
    factors: packFactors({
      capacity: 94,
      bounce: 78,
      raceKit: 86,
      poles: 90,
      versatility: 78,
      weight: 60,
      value: 74,
    }),
    strengths: ["Cold-weather big-day capacity"],
    compromises: ["Too much pack for most training days"],
    explanation: "Only for training days that need near-overnight volume.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-fastpack-30-ultra",
    productId: "prod-ud-fastpack-30",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 78,
    factors: packFactors({
      capacity: 94,
      bounce: 76,
      raceKit: 90,
      poles: 90,
      versatility: 76,
      weight: 58,
      value: 74,
    }),
    strengths: ["Mandatory kit + overnight food room"],
    compromises: ["Race bounce favors lighter vests/packs"],
    explanation: "Volume play for supported ultra adventures, not pure race pace.",
    evidenceIds: [...ev],
  },

  // ── Talon Velocity 20 ────────────────────────────────────────────────
  {
    id: "rec-talon-velocity-20-fastpacking",
    productId: "prod-osprey-talon-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 88,
    factors: packFactors({
      capacity: 86,
      bounce: 84,
      raceKit: 84,
      poles: 86,
      versatility: 88,
      weight: 74,
      value: 80,
    }),
    strengths: ["Osprey Velocity organization", "Light fastpacking volume"],
    compromises: ["Men’s patterning — women start with Tempest"],
    explanation: "Osprey men’s Velocity for light fastpacking and big days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-talon-velocity-20-trail-training",
    productId: "prod-osprey-talon-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 90,
    factors: packFactors({
      capacity: 86,
      bounce: 86,
      raceKit: 82,
      poles: 86,
      versatility: 90,
      weight: 76,
      value: 82,
    }),
    strengths: ["Trail-day organization", "Running-oriented Osprey fit"],
    compromises: ["Not a bounce-free race vest"],
    explanation: "Strong Talon Velocity pick for big trail training days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-talon-velocity-20-long-runs",
    productId: "prod-osprey-talon-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: packFactors({
      capacity: 84,
      bounce: 84,
      raceKit: 78,
      poles: 84,
      versatility: 88,
      weight: 74,
      value: 80,
    }),
    strengths: ["Day-pack volume for long trail efforts"],
    compromises: ["Road longs usually need less pack"],
    explanation: "When long runs need more than a race vest but not overnight kit.",
    evidenceIds: [...ev],
  },

  // ── Tempest Velocity 20 ──────────────────────────────────────────────
  {
    id: "rec-tempest-velocity-20-fastpacking",
    productId: "prod-osprey-tempest-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 88,
    factors: packFactors({
      capacity: 86,
      bounce: 84,
      raceKit: 84,
      poles: 86,
      versatility: 88,
      weight: 74,
      value: 80,
    }),
    strengths: ["Women’s Velocity fit", "Light fastpacking volume"],
    compromises: ["Not a pure race vest"],
    explanation: "Women’s Osprey Velocity for light fastpacking days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tempest-velocity-20-trail-training",
    productId: "prod-osprey-tempest-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 90,
    factors: packFactors({
      capacity: 86,
      bounce: 86,
      raceKit: 82,
      poles: 86,
      versatility: 90,
      weight: 76,
      value: 82,
    }),
    strengths: ["Women’s trail-day pack fit"],
    compromises: ["Overkill for short flask-only days"],
    explanation: "Women’s Velocity peer to Talon for big trail training.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tempest-velocity-20-long-runs",
    productId: "prod-osprey-tempest-velocity-20",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: packFactors({
      capacity: 84,
      bounce: 84,
      raceKit: 78,
      poles: 84,
      versatility: 88,
      weight: 74,
      value: 80,
    }),
    strengths: ["Day-pack long-run volume"],
    compromises: ["Road longs often prefer belts/vests"],
    explanation: "Women’s Velocity when long runs need pack volume.",
    evidenceIds: [...ev],
  },

  // ── Talon Velocity 30 ────────────────────────────────────────────────
  {
    id: "rec-talon-velocity-30-fastpacking",
    productId: "prod-osprey-talon-velocity-30",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 92,
    factors: packFactors({
      capacity: 94,
      bounce: 80,
      raceKit: 90,
      poles: 88,
      versatility: 82,
      weight: 66,
      value: 76,
    }),
    strengths: ["Higher Velocity overnight volume"],
    compromises: ["Heavier than Velocity 20"],
    explanation: "Osprey Velocity step-up for overnight-leaning days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-talon-velocity-30-trail-training",
    productId: "prod-osprey-talon-velocity-30",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: packFactors({
      capacity: 92,
      bounce: 78,
      raceKit: 84,
      poles: 86,
      versatility: 78,
      weight: 64,
      value: 74,
    }),
    strengths: ["Cold big-day capacity"],
    compromises: ["Too much for most training days"],
    explanation: "Use when trail training needs near-overnight kit.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-talon-velocity-30-ultra",
    productId: "prod-osprey-talon-velocity-30",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 80,
    factors: packFactors({
      capacity: 92,
      bounce: 76,
      raceKit: 88,
      poles: 86,
      versatility: 76,
      weight: 62,
      value: 74,
    }),
    strengths: ["Remote ultra kit room"],
    compromises: ["Race bounce favors lighter carry"],
    explanation: "Volume option for supported ultra adventures.",
    evidenceIds: [...ev],
  },

  // ── Distance 15 ──────────────────────────────────────────────────────
  {
    id: "rec-bd-distance-15-trail-training",
    productId: "prod-black-diamond-distance-15",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 88,
    factors: packFactors({
      capacity: 84,
      bounce: 86,
      raceKit: 84,
      poles: 90,
      versatility: 86,
      weight: 78,
      value: 78,
    }),
    strengths: ["BD Distance trail fit", "Pole-friendly mid volume"],
    compromises: ["Less overnight room than Distance 22"],
    explanation: "Black Diamond mid-capacity for alpine-leaning trail days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-bd-distance-15-fastpacking",
    productId: "prod-black-diamond-distance-15",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 82,
    factors: packFactors({
      capacity: 82,
      bounce: 84,
      raceKit: 82,
      poles: 90,
      versatility: 82,
      weight: 78,
      value: 76,
    }),
    strengths: ["Light fastpacking mid-volume"],
    compromises: ["Step to Distance 22 for true overnight"],
    explanation: "Light fastpacking when Distance 22 is more pack than needed.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-bd-distance-15-ultra",
    productId: "prod-black-diamond-distance-15",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 84,
    factors: packFactors({
      capacity: 84,
      bounce: 84,
      raceKit: 86,
      poles: 90,
      versatility: 84,
      weight: 76,
      value: 76,
    }),
    strengths: ["Mountain ultra training volume"],
    compromises: ["Race days may prefer a vest"],
    explanation: "Distance 15 for mountain ultra training above race-vest capacity.",
    evidenceIds: [...ev],
  },

  // ── Distance 22 ──────────────────────────────────────────────────────
  {
    id: "rec-bd-distance-22-fastpacking",
    productId: "prod-black-diamond-distance-22",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 92,
    factors: packFactors({
      capacity: 94,
      bounce: 82,
      raceKit: 90,
      poles: 92,
      versatility: 84,
      weight: 68,
      value: 76,
    }),
    strengths: ["Overnight-leaning Distance volume", "Pole-strong BD carry"],
    compromises: ["Heavier than Distance 15 / race vests"],
    explanation: "BD Distance fastpacking pick for mountain overnight days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-bd-distance-22-trail-training",
    productId: "prod-black-diamond-distance-22",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: packFactors({
      capacity: 92,
      bounce: 80,
      raceKit: 86,
      poles: 92,
      versatility: 80,
      weight: 66,
      value: 74,
    }),
    strengths: ["Big mountain training capacity"],
    compromises: ["Too much for shorter trail days"],
    explanation: "When trail training needs near-overnight mountain kit.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-bd-distance-22-ultra",
    productId: "prod-black-diamond-distance-22",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 82,
    factors: packFactors({
      capacity: 92,
      bounce: 78,
      raceKit: 88,
      poles: 92,
      versatility: 78,
      weight: 64,
      value: 74,
    }),
    strengths: ["Remote ultra kit + poles"],
    compromises: ["Race bounce favors lighter packs/vests"],
    explanation: "Volume option for alpine ultra adventures.",
    evidenceIds: [...ev],
  },

  // ── XA 15 ────────────────────────────────────────────────────────────
  {
    id: "rec-xa-15-trail-training",
    productId: "prod-salomon-xa-15",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 90,
    factors: packFactors({
      capacity: 86,
      bounce: 86,
      raceKit: 84,
      poles: 88,
      versatility: 88,
      weight: 80,
      value: 84,
    }),
    strengths: ["Mid-capacity above ADV Skin", "Salomon trail ecosystem"],
    compromises: ["Not overnight Fastpack volume"],
    explanation: "Best XA lane for trail days that outgrow race vests.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-xa-15-ultra",
    productId: "prod-salomon-xa-15",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 86,
    factors: packFactors({
      capacity: 86,
      bounce: 84,
      raceKit: 88,
      poles: 88,
      versatility: 84,
      weight: 78,
      value: 82,
    }),
    strengths: ["Ultra kit between vest and fastpack"],
    compromises: ["Still not a bounce-free race vest"],
    explanation: "Mid-capacity Salomon option for ultra training volume.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-xa-15-fastpacking",
    productId: "prod-salomon-xa-15",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 78,
    factors: packFactors({
      capacity: 80,
      bounce: 82,
      raceKit: 80,
      poles: 86,
      versatility: 80,
      weight: 80,
      value: 82,
    }),
    strengths: ["Light fastpacking mid-volume"],
    compromises: ["Fastpack 20 / Distance 22 carry more overnight kit"],
    explanation: "Light fastpacking only — step up for true overnight.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-xa-15-long-runs",
    productId: "prod-salomon-xa-15",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: packFactors({
      capacity: 84,
      bounce: 84,
      raceKit: 80,
      poles: 86,
      versatility: 86,
      weight: 80,
      value: 84,
    }),
    strengths: ["Long trail day capacity"],
    compromises: ["Road longs usually need less"],
    explanation: "Solid when long runs need more than ADV Skin rear volume.",
    evidenceIds: [...ev],
  },

  // ── Octane 22 ────────────────────────────────────────────────────────
  {
    id: "rec-octane-22-long-runs",
    productId: "prod-camelbak-octane-22",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 86,
    factors: packFactors({
      capacity: 90,
      bounce: 80,
      raceKit: 82,
      poles: 78,
      versatility: 86,
      weight: 72,
      value: 82,
    }),
    strengths: ["Bladder-forward ~22 L volume", "Big long-day capacity"],
    compromises: ["Less vest-like front flask focus than Fastpack"],
    explanation: "CamelBak Octane for long trail days with reservoir emphasis.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-octane-22-trail-training",
    productId: "prod-camelbak-octane-22",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 84,
    factors: packFactors({
      capacity: 90,
      bounce: 80,
      raceKit: 80,
      poles: 78,
      versatility: 84,
      weight: 70,
      value: 82,
    }),
    strengths: ["Trail-day bladder capacity"],
    compromises: ["Not a race-vest bounce king"],
    explanation: "Octane when training days want pack volume + reservoir.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-octane-22-fastpacking",
    productId: "prod-camelbak-octane-22",
    sportId: "sport-running",
    useCaseId: "uc-fastpacking",
    score: 86,
    factors: packFactors({
      capacity: 90,
      bounce: 78,
      raceKit: 84,
      poles: 78,
      versatility: 82,
      weight: 70,
      value: 80,
    }),
    strengths: ["Light fastpacking volume class"],
    compromises: ["UD Fastpack still stronger vest-harness layout"],
    explanation: "Bladder-first light fastpacking alternative to Fastpack.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-octane-22-ultra",
    productId: "prod-camelbak-octane-22",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 80,
    factors: packFactors({
      capacity: 88,
      bounce: 76,
      raceKit: 84,
      poles: 76,
      versatility: 80,
      weight: 68,
      value: 80,
    }),
    strengths: ["Remote day volume"],
    compromises: ["Race days often stay on a vest"],
    explanation: "Octane for volume-heavy ultra training, not pure race pace.",
    evidenceIds: [...ev],
  },

  // ── Trailblazer 20 ───────────────────────────────────────────────────
  {
    id: "rec-trailblazer-20-commute-running",
    productId: "prod-salomon-trailblazer-20",
    sportId: "sport-running",
    useCaseId: "uc-commute-running",
    score: 90,
    factors: packFactors({
      capacity: 88,
      bounce: 72,
      raceKit: 60,
      poles: 50,
      versatility: 92,
      weight: 78,
      value: 88,
    }),
    strengths: ["Commute / daypack versatility", "Strong value"],
    compromises: ["Not a bounce-free race or trail vest"],
    explanation: "Best Trailblazer lane for run-commute and mixed day carry.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-trailblazer-20-long-runs",
    productId: "prod-salomon-trailblazer-20",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 72,
    factors: packFactors({
      capacity: 86,
      bounce: 70,
      raceKit: 62,
      poles: 52,
      versatility: 84,
      weight: 76,
      value: 86,
    }),
    strengths: ["Cheap day volume"],
    compromises: ["Bounce and race-kit lag dedicated running packs"],
    explanation: "Budget long-day pack when Velocity / Fastpack are more than you need.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-trailblazer-20-trail-training",
    productId: "prod-salomon-trailblazer-20",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 70,
    factors: packFactors({
      capacity: 86,
      bounce: 68,
      raceKit: 60,
      poles: 52,
      versatility: 82,
      weight: 76,
      value: 86,
    }),
    strengths: ["Value trail daypack"],
    compromises: ["Prefer XA / Fastpack for serious trail bounce"],
    explanation: "Entry trail daypack — step up for race-oriented trail days.",
    evidenceIds: [...ev],
  },

  // ── Custom Quiver ────────────────────────────────────────────────────
  {
    id: "rec-custom-quiver-trail-training",
    productId: "prod-salomon-custom-quiver",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 88,
    factors: accessoryFactors({
      capacity: 40,
      bounce: 82,
      raceKit: 70,
      poles: 96,
      versatility: 84,
      weight: 92,
      value: 86,
    }),
    strengths: ["Dedicated Salomon pole stow", "Pairs with ADV Skin"],
    compromises: ["Accessory only — no pack capacity"],
    explanation: "Pole-carry accessory for Salomon race vests on trail days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-custom-quiver-ultra",
    productId: "prod-salomon-custom-quiver",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 90,
    factors: accessoryFactors({
      capacity: 40,
      bounce: 82,
      raceKit: 78,
      poles: 96,
      versatility: 82,
      weight: 92,
      value: 86,
    }),
    strengths: ["Ultra pole management", "Light add-on"],
    compromises: ["Needs a host vest/pack"],
    explanation: "Custom Quiver for ultra days that need poles on ADV Skin.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-custom-quiver-long-runs",
    productId: "prod-salomon-custom-quiver",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 78,
    factors: accessoryFactors({
      capacity: 40,
      bounce: 80,
      raceKit: 66,
      poles: 94,
      versatility: 78,
      weight: 92,
      value: 84,
    }),
    strengths: ["Clean pole stow on long trail efforts"],
    compromises: ["Unnecessary without poles"],
    explanation: "Only when long runs include poles on a Salomon vest.",
    evidenceIds: [...ev],
  },

  // ── LEKI quiver ──────────────────────────────────────────────────────
  {
    id: "rec-leki-quiver-trail-training",
    productId: "prod-leki-trail-running-quiver",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 86,
    factors: accessoryFactors({
      capacity: 38,
      bounce: 80,
      raceKit: 68,
      poles: 94,
      versatility: 82,
      weight: 90,
      value: 84,
    }),
    strengths: ["LEKI pole ecosystem quiver", "Works with ADV Skin"],
    compromises: ["Accessory only"],
    explanation: "LEKI trail quiver for pole days on race vests.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-leki-quiver-ultra",
    productId: "prod-leki-trail-running-quiver",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 88,
    factors: accessoryFactors({
      capacity: 38,
      bounce: 80,
      raceKit: 74,
      poles: 94,
      versatility: 80,
      weight: 90,
      value: 84,
    }),
    strengths: ["Ultra pole stow"],
    compromises: ["Needs a host vest"],
    explanation: "LEKI quiver for ultra pole management on ADV Skin-class vests.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-leki-quiver-long-runs",
    productId: "prod-leki-trail-running-quiver",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 76,
    factors: accessoryFactors({
      capacity: 38,
      bounce: 78,
      raceKit: 64,
      poles: 92,
      versatility: 76,
      weight: 90,
      value: 82,
    }),
    strengths: ["Light pole add-on"],
    compromises: ["Skip if you do not carry poles"],
    explanation: "Long-run accessory when poles are part of the session.",
    evidenceIds: [...ev],
  },

  // ── Utility Bag ──────────────────────────────────────────────────────
  {
    id: "rec-utility-bag-long-runs",
    productId: "prod-ud-utility-bag",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: accessoryFactors({
      capacity: 62,
      bounce: 78,
      raceKit: 72,
      poles: 40,
      versatility: 86,
      weight: 90,
      value: 88,
    }),
    strengths: ["Modular UD storage add-on", "Pairs with Race Vest / Fastpack"],
    compromises: ["Not a standalone pack"],
    explanation: "UD Utility Bag expands vest/pack pocketing on long days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-utility-bag-trail-training",
    productId: "prod-ud-utility-bag",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: accessoryFactors({
      capacity: 62,
      bounce: 78,
      raceKit: 70,
      poles: 40,
      versatility: 84,
      weight: 90,
      value: 88,
    }),
    strengths: ["Extra fuel/phone stash"],
    compromises: ["Accessory-only capacity"],
    explanation: "Utility Bag when trail days need one more organized pocket.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-utility-bag-ultra",
    productId: "prod-ud-utility-bag",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 80,
    factors: accessoryFactors({
      capacity: 64,
      bounce: 76,
      raceKit: 78,
      poles: 40,
      versatility: 82,
      weight: 90,
      value: 86,
    }),
    strengths: ["Race-kit overflow pocket"],
    compromises: ["Does not replace vest capacity"],
    explanation: "Modular overflow for UD Race Vest / Fastpack ultra days.",
    evidenceIds: [...ev],
  },

  // ── Soft Flask Stash ─────────────────────────────────────────────────
  {
    id: "rec-soft-flask-stash-long-runs",
    productId: "prod-salomon-soft-flask-stash",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 84,
    factors: accessoryFactors({
      capacity: 58,
      bounce: 80,
      raceKit: 70,
      poles: 35,
      versatility: 82,
      weight: 94,
      value: 86,
    }),
    strengths: ["Holds Soft Flask 500", "Pairs with ADV Skin"],
    compromises: ["Accessory only"],
    explanation: "Soft Flask Stash for extra flask pocketing on long days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soft-flask-stash-trail-training",
    productId: "prod-salomon-soft-flask-stash",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: accessoryFactors({
      capacity: 58,
      bounce: 80,
      raceKit: 68,
      poles: 35,
      versatility: 80,
      weight: 94,
      value: 86,
    }),
    strengths: ["Trail flask overflow"],
    compromises: ["Needs Soft Flask + host vest"],
    explanation: "Trail accessory when ADV Skin needs another flask stash.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-soft-flask-stash-ultra",
    productId: "prod-salomon-soft-flask-stash",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 80,
    factors: accessoryFactors({
      capacity: 60,
      bounce: 78,
      raceKit: 74,
      poles: 35,
      versatility: 78,
      weight: 94,
      value: 84,
    }),
    strengths: ["Ultra flask expansion"],
    compromises: ["Not a capacity fix for overnight kit"],
    explanation: "Soft Flask Stash for ultra flask overflow on ADV Skin.",
    evidenceIds: [...ev],
  },

  // ── Nathan Zippered Stash ────────────────────────────────────────────
  {
    id: "rec-nathan-stash-long-runs",
    productId: "prod-nathan-zippered-stash",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 82,
    factors: accessoryFactors({
      capacity: 56,
      bounce: 78,
      raceKit: 68,
      poles: 30,
      versatility: 84,
      weight: 94,
      value: 88,
    }),
    strengths: ["Zippered phone/gel overflow", "Strong value"],
    compromises: ["Accessory only"],
    explanation: "Nathan stash pouch for long-run essentials overflow.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nathan-stash-trail-training",
    productId: "prod-nathan-zippered-stash",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 80,
    factors: accessoryFactors({
      capacity: 56,
      bounce: 78,
      raceKit: 66,
      poles: 30,
      versatility: 82,
      weight: 94,
      value: 88,
    }),
    strengths: ["Secure trail pocket add-on"],
    compromises: ["Does not add hydration volume"],
    explanation: "Zippered stash when trail days need one more secure pocket.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-nathan-stash-ultra",
    productId: "prod-nathan-zippered-stash",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 76,
    factors: accessoryFactors({
      capacity: 56,
      bounce: 76,
      raceKit: 72,
      poles: 30,
      versatility: 78,
      weight: 94,
      value: 86,
    }),
    strengths: ["Small race-kit overflow"],
    compromises: ["Not a vest capacity substitute"],
    explanation: "Nathan stash for small ultra essentials overflow.",
    evidenceIds: [...ev],
  },
];
