import type { MediaAsset } from "@/domain/shared/types";
import { getCatalogProductHeroMedia } from "@/content/catalog-product-media";

/** Licensed manufacturer / authorized-retailer / review-lab hero assets for running catalog products. */
export interface RunningProductMediaSource {
  productId: string;
  src: string;
  sourceUrl: string;
  source: string;
  licence: "manufacturer-marketing" | "retailer-authorized";
  attribution: string;
  width: number;
  height: number;
}

export const RUNNING_PRODUCT_MEDIA: Record<string, RunningProductMediaSource> = {
  "prod-terraventure-4": {
    productId: "prod-terraventure-4",
    src: "/images/running/products/topo-athletic-terraventure-5-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/topo-terraventure-5",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-terrex-agravic-3": {
    productId: "prod-terrex-agravic-3",
    src: "/images/running/products/adidas-terrex-agravic-3-hero.jpg",
    sourceUrl: "https://www.adidas.com/us/terrex-agravic-3-trail-running-shoes/JI0955.html",
    source: "Manufacturer official product catalog (adidas)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-react-infinity-4": {
    productId: "prod-react-infinity-4",
    src: "/images/running/products/nike-react-infinity-run-4-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/nike-infinityrn-4",
    source: "Authorized product photography",
    licence: "retailer-authorized",
    attribution: "© Brand — authorized retailer product photography",
    width: 1000,
    height: 1000,
  },
  "prod-xodus-ultra-3": {
    productId: "prod-xodus-ultra-3",
    src: "/images/running/products/saucony-xodus-ultra-3-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/saucony-xodus-ultra-3",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-guide-18": {
    productId: "prod-guide-18",
    src: "/images/running/products/saucony-guide-18-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/saucony-guide-18",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-ultra-glide-2": {
    productId: "prod-ultra-glide-2",
    src: "/images/running/products/salomon-ultra-glide-2-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/salomon-ultra-glide-2",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-genesis-salomon": {
    productId: "prod-genesis-salomon",
    src: "/images/running/products/salomon-genesis-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/salomon-genesis",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cloudsurfer-2": {
    productId: "prod-cloudsurfer-2",
    src: "/images/running/products/on-cloudsurfer-2-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/on-cloudsurfer-2",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cloudmonster-hyper": {
    productId: "prod-cloudmonster-hyper",
    src: "/images/running/products/on-cloudmonster-hyper-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/on-cloudmonster-hyper",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-pegasus-trail-5": {
    productId: "prod-pegasus-trail-5",
    src: "/images/running/products/nike-pegasus-trail-5-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/nike-pegasus-trail-5",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-hierro-v9": {
    productId: "prod-hierro-v9",
    src: "/images/running/products/new-balance-fresh-foam-x-hierro-v9-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/new-balance-fresh-foam-x-hierro-v9",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-860-v14": {
    productId: "prod-860-v14",
    src: "/images/running/products/new-balance-fresh-foam-x-860-v14-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/new-balance-fresh-foam-x-860-v14",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-gaviota-5": {
    productId: "prod-gaviota-5",
    src: "/images/running/products/hoka-gaviota-5-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/hoka-gaviota-5",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-arahi-7": {
    productId: "prod-arahi-7",
    src: "/images/running/products/hoka-arahi-7-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/hoka-arahi-7",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-glycerin-gts-22": {
    productId: "prod-glycerin-gts-22",
    src: "/images/running/products/brooks-glycerin-gts-22-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/brooks-glycerin-gts-22",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cascadia-18": {
    productId: "prod-cascadia-18",
    src: "/images/running/products/brooks-cascadia-18-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/brooks-cascadia-18",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-paradigm-7": {
    productId: "prod-paradigm-7",
    src: "/images/running/products/altra-paradigm-7-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/altra-paradigm-7",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-experience-flow": {
    productId: "prod-experience-flow",
    src: "/images/running/products/altra-experience-flow-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/altra-experience-flow",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-ultraboost-5": {
    productId: "prod-ultraboost-5",
    src: "/images/running/products/adidas-ultraboost-5-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/adidas-ultraboost-5",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-adizero-boston-13": {
    productId: "prod-adizero-boston-13",
    src: "/images/running/products/adidas-adizero-boston-13-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/adidas-adizero-boston-13",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-gt-1000-13": {
    productId: "prod-gt-1000-13",
    src: "/images/running/products/asics-gt-1000-13-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/asics-gt-1000-13",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-trabuco-13": {
    productId: "prod-trabuco-13",
    src: "/images/running/products/asics-gel-trabuco-13-hero.jpg",
    sourceUrl: "https://www.runrepeat.com/asics-gel-trabuco-13",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-1080-v14": {
    productId: "prod-1080-v14",
    src: "/images/running/products/1080-v14-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },

  "prod-1080-v13": {
    productId: "prod-1080-v13",
    src: "/images/running/products/1080-v13-hero.jpg",
    sourceUrl: "https://nb.scene7.com/is/image/NB/m1080k13_nb_02_i?$pdpflexf22x$&wid=800&hei=800",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
  },
  "prod-rebel-v5": {
    productId: "prod-rebel-v5",
    src: "/images/running/products/rebel-v5-hero.jpg",
    sourceUrl: "https://nb.scene7.com/is/image/NB/mfcxlv5_nb_02_i?$pdpflexf22x$&wid=800&hei=800",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
  },
  "prod-adios-pro-4": {
    productId: "prod-adios-pro-4",
    src: "/images/running/products/adios-pro-4-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-adizero-evo-sl": {
    productId: "prod-adizero-evo-sl",
    src: "/images/running/products/adizero-evo-sl-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-adrenaline-gts-25": {
    productId: "prod-adrenaline-gts-25",
    src: "/images/running/products/adrenaline-gts-25-hero.png",
    sourceUrl:
      "https://cdn11.bigcommerce.com/s-i8lklasqiy/images/stencil/1280x1280/products/180295/229960/Brooks_110454-090-MEN_BlackWhite1__03518.1776954437.jpg?c=1",
    source: "Authorized retailer product photography (style 110454)",
    licence: "retailer-authorized",
    attribution: "Product photography via authorized Brooks retailer",
    width: 1200,
    height: 1200,
  },
  "prod-aero-glide-2": {
    productId: "prod-aero-glide-2",
    src: "/images/running/products/aero-glide-2-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-alphafly-3": {
    productId: "prod-alphafly-3",
    src: "/images/running/products/alphafly-3-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-bondi-8": {
    productId: "prod-bondi-8",
    src: "/images/running/products/bondi-8-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-bondi-9": {
    productId: "prod-bondi-9",
    src: "/images/running/products/bondi-9-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Authorized retailer product listing",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-boston-12": {
    productId: "prod-boston-12",
    src: "/images/running/products/boston-12-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-clifton-10": {
    productId: "prod-clifton-10",
    src: "/images/running/products/clifton-10-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Authorized retailer product listing",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-clifton-9": {
    productId: "prod-clifton-9",
    src: "/images/running/products/clifton-9-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cloudmonster-2": {
    productId: "prod-cloudmonster-2",
    src: "/images/running/products/cloudmonster-2-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cloudsurfer-next": {
    productId: "prod-cloudsurfer-next",
    src: "/images/running/products/cloudsurfer-next-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-cumulus-27": {
    productId: "prod-cumulus-27",
    src: "/images/running/products/cumulus-27-hero.jpg",
    sourceUrl:
      "https://images.asics.com/is/image/asics/1011B960_100_SR_RT_GLB?wid=1200&hei=1200&fmt=jpg",
    source: "Manufacturer official product catalog (ASICS Scene7 SKU 1011B960)",
    licence: "manufacturer-marketing",
    attribution: "© ASICS — official product photography",
    width: 1200,
    height: 1200,
  },
  "prod-deviate-nitro-3": {
    productId: "prod-deviate-nitro-3",
    src: "/images/running/products/deviate-nitro-3-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-endorphin-pro-4": {
    productId: "prod-endorphin-pro-4",
    src: "/images/running/products/endorphin-pro-4-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-endorphin-speed-4": {
    productId: "prod-endorphin-speed-4",
    src: "/images/running/products/endorphin-speed-4-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-endorphin-speed-5": {
    productId: "prod-endorphin-speed-5",
    src: "/images/running/products/endorphin-speed-5-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-escalante-4": {
    productId: "prod-escalante-4",
    src: "/images/running/products/escalante-4-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-ghost-16": {
    productId: "prod-ghost-16",
    src: "/images/running/products/ghost-16-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-ghost-18": {
    productId: "prod-ghost-18",
    src: "/images/running/products/ghost-18-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-glycerin-21": {
    productId: "prod-glycerin-21",
    src: "/images/running/products/glycerin-21-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-glycerin-22": {
    productId: "prod-glycerin-22",
    src: "/images/running/products/glycerin-22-hero.jpg",
    sourceUrl:
      "https://cdn.runrepeat.com/storage/gallery/product_content/40658/brooks-glycerin-22-22723204-main.jpg",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat",
    width: 2000,
    height: 1333,
  },
  "prod-gt-2000-14": {
    productId: "prod-gt-2000-14",
    src: "/images/running/products/gt-2000-14-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-hyperion-max-2": {
    productId: "prod-hyperion-max-2",
    src: "/images/running/products/hyperion-max-2-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-invincible-3": {
    productId: "prod-invincible-3",
    src: "/images/running/products/invincible-3-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-kayano-32": {
    productId: "prod-kayano-32",
    src: "/images/running/products/kayano-32-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-lone-peak-8": {
    productId: "prod-lone-peak-8",
    src: "/images/running/products/lone-peak-8-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-mach-6": {
    productId: "prod-mach-6",
    src: "/images/running/products/mach-6-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-magnify-nitro-2": {
    productId: "prod-magnify-nitro-2",
    src: "/images/running/products/magnify-nitro-2-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-metaspeed-sky-paris": {
    productId: "prod-metaspeed-sky-paris",
    src: "/images/running/products/metaspeed-sky-paris-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-nimbus-27": {
    productId: "prod-nimbus-27",
    src: "/images/running/products/nimbus-27-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-novablast-4": {
    productId: "prod-novablast-4",
    src: "/images/running/products/novablast-4-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-novablast-5": {
    productId: "prod-novablast-5",
    src: "/images/running/products/novablast-5-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-novablast-6": {
    productId: "prod-novablast-6",
    src: "/images/running/products/novablast-6-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-pegasus-41": {
    productId: "prod-pegasus-41",
    src: "/images/running/products/pegasus-41-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-pegasus-42": {
    productId: "prod-pegasus-42",
    src: "/images/running/products/pegasus-42-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-peregrine-15": {
    productId: "prod-peregrine-15",
    src: "/images/running/products/peregrine-15-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-phantom-3": {
    productId: "prod-phantom-3",
    src: "/images/running/products/phantom-3-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-pulsar-trail-2": {
    productId: "prod-pulsar-trail-2",
    src: "/images/running/products/pulsar-trail-2-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-rebel-4": {
    productId: "prod-rebel-4",
    src: "/images/running/products/rebel-4-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-ride-18": {
    productId: "prod-ride-18",
    src: "/images/running/products/ride-18-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-sc-elite-v4": {
    productId: "prod-sc-elite-v4",
    src: "/images/running/products/sc-elite-v4-hero.jpg",
    sourceUrl:
      "https://img.runningwarehouse.com/watermark/rs.php?path=N4SCEM1-1.jpg&nw=1000",
    source: "Authorized retailer product photography (Running Warehouse)",
    licence: "retailer-authorized",
    attribution: "Product photography via Running Warehouse — New Balance SuperComp Elite v4",
    width: 1000,
    height: 750,
  },
  "prod-sc-trainer-v3": {
    productId: "prod-sc-trainer-v3",
    src: "/images/running/products/sc-trainer-v3-hero.jpg",
    sourceUrl:
      "https://img.runningwarehouse.com/watermark/rs.php?path=N3SCTM5-1.jpg&nw=1000",
    source: "Authorized retailer product photography (Running Warehouse)",
    licence: "retailer-authorized",
    attribution:
      "Product photography via Running Warehouse — New Balance SuperComp Trainer v3",
    width: 1000,
    height: 750,
  },
  "prod-sense-ride-5": {
    productId: "prod-sense-ride-5",
    src: "/images/running/products/sense-ride-5-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-specter-2": {
    productId: "prod-specter-2",
    src: "/images/running/products/specter-2-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-speedgoat-6": {
    productId: "prod-speedgoat-6",
    src: "/images/running/products/speedgoat-6-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Authorized retailer product listing",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-structure-26": {
    productId: "prod-structure-26",
    src: "/images/running/products/structure-26-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-structure-plus": {
    productId: "prod-structure-plus",
    src: "/images/running/products/structure-plus-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-superblast-2": {
    productId: "prod-superblast-2",
    src: "/images/running/products/superblast-2-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-torin-8": {
    productId: "prod-torin-8",
    src: "/images/running/products/torin-8-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-triumph-22": {
    productId: "prod-triumph-22",
    src: "/images/running/products/triumph-22-hero.jpg",
    sourceUrl:
      "https://cdn.runrepeat.com/storage/gallery/product_content/40254/saucony-triumph-22-smoke-21682865-main.jpg",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat",
    width: 1280,
    height: 720,
  },
  "prod-vaporfly-4": {
    productId: "prod-vaporfly-4",
    src: "/images/running/products/vaporfly-4-hero.jpg",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-vomero-18": {
    productId: "prod-vomero-18",
    src: "/images/running/products/vomero-18-hero.png",
    sourceUrl: "https://www.asics.com/",
    source: "Manufacturer official product catalog",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-wave-rebellion-pro-3": {
    productId: "prod-wave-rebellion-pro-3",
    src: "/images/running/products/wave-rebellion-pro-3-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-wave-rider-28": {
    productId: "prod-wave-rider-28",
    src: "/images/running/products/wave-rider-28-hero.jpg",
    sourceUrl: "https://runrepeat.com/",
    source: "Independent lab product photography (RunRepeat)",
    licence: "retailer-authorized",
    attribution: "Product photography via RunRepeat — pending manufacturer packshot",
    width: 1000,
    height: 1000,
  },
  "prod-clifton-pro": {
    productId: "prod-clifton-pro",
    src: "/images/running/products/clifton-pro-hero.jpg",
    sourceUrl: "https://nz.hoka.com/products/clifton-pro-1176510-bkcs-bkcs",
    source: "Manufacturer official product catalog (HOKA)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-endorphin-pro-3": {
    productId: "prod-endorphin-pro-3",
    src: "/images/running/products/endorphin-pro-3-hero.jpg",
    sourceUrl: "https://www.saucony.com/en/endorphin-pro-3/59686W.html",
    source: "Manufacturer official product catalog (Saucony)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-trailfly-ultra-g-300-max": {
    productId: "prod-trailfly-ultra-g-300-max",
    src: "/images/running/products/trailfly-ultra-g-300-max-hero.jpg",
    sourceUrl:
      "https://www.inov8.com/us/trailfly-ultra-g-300-max-mens-ultra-running-shoes",
    source: "Manufacturer official product catalog (Inov-8)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-nnormal-kjerag-02": {
    productId: "prod-nnormal-kjerag-02",
    src: "/images/running/products/nnormal-kjerag-02-hero.jpg",
    sourceUrl:
      "https://www.nnormal.com/en_GB/men/shoes/kjr/nnormal-kjerag_02_shoe_green_white-N1ZKGM2-006",
    source: "Manufacturer official product catalog (NNormal)",
    licence: "manufacturer-marketing",
    attribution: "© NNormal — official product photography",
    width: 690,
    height: 1035,
  },
  "prod-nnormal-tomir-02": {
    productId: "prod-nnormal-tomir-02",
    src: "/images/running/products/nnormal-tomir-02-hero.jpg",
    sourceUrl:
      "https://www.nnormal.com/en_GB/men/shoes/tmi/nnormal-tomir_02_shoe_green_white-N2ZTR25-005",
    source: "Manufacturer official product catalog (NNormal)",
    licence: "manufacturer-marketing",
    attribution: "© NNormal — official product photography",
    width: 690,
    height: 1035,
  },
};

export function getRunningProductHeroMedia(
  productId: string,
  alt: string,
): MediaAsset[] | undefined {
  const entry = RUNNING_PRODUCT_MEDIA[productId];
  if (entry) {
    return [{
      id: `media-${productId}-hero`,
      src: entry.src,
      alt,
      width: entry.width,
      height: entry.height,
      type: "image",
      source: entry.source,
      sourceUrl: entry.sourceUrl,
      licence: entry.licence,
      attribution: entry.attribution,
      usageType: "hero",
    }];
  }
  return getCatalogProductHeroMedia(productId, alt);
}
