import type { ProductFamily } from "@/domain/products/types";

/**
 * Running Recovery Gear families for wave 2.
 * NOT wired into families.ts aggregators yet (parent will wire).
 */
export const runningRecoveryFamilies: ProductFamily[] = [
  {
    id: "fam-theragun",
    brandId: "brand-therabody",
    name: "Theragun",
    slug: "theragun",
    categoryId: "cat-recovery-gear",
    description: "Therabody percussive massage devices for soft-tissue comfort routines.",
    productIds: [
      "prod-theragun-mini",
      "prod-theragun-relief",
      "prod-theragun-prime",
      "prod-theragun-pro",
    ],
  },
  {
    id: "fam-hypervolt",
    brandId: "brand-hyperice",
    name: "Hypervolt",
    slug: "hypervolt",
    categoryId: "cat-recovery-gear",
    description: "Hyperice Hypervolt percussion massagers.",
    productIds: ["prod-hypervolt-go-2", "prod-hypervolt-2"],
  },
  {
    id: "fam-renpho-r3",
    brandId: "brand-renpho",
    name: "R3",
    slug: "renpho-r3",
    categoryId: "cat-recovery-gear",
    description: "RENPHO value percussion massage guns.",
    productIds: ["prod-renpho-r3"],
  },
  {
    id: "fam-opove-m3",
    brandId: "brand-opove",
    name: "M3",
    slug: "opove-m3",
    categoryId: "cat-recovery-gear",
    description: "OPOVE M3-series percussion massagers.",
    productIds: ["prod-opove-m3-pro"],
  },
  {
    id: "fam-timtam-power-massager",
    brandId: "brand-timtam",
    name: "Power Massager",
    slug: "timtam-power-massager",
    categoryId: "cat-recovery-gear",
    description: "TimTam athletic percussion massagers.",
    productIds: ["prod-timtam-power-massager-v3.7"],
  },
  {
    id: "fam-triggerpoint-grid",
    brandId: "brand-triggerpoint",
    name: "GRID",
    slug: "triggerpoint-grid",
    categoryId: "cat-recovery-gear",
    description: "TriggerPoint GRID foam rollers.",
    productIds: [
      "prod-triggerpoint-grid",
      "prod-triggerpoint-grid-x",
      "prod-triggerpoint-grid-travel",
    ],
  },
  {
    id: "fam-rumbleroller",
    brandId: "brand-rumbleroller",
    name: "RumbleRoller",
    slug: "rumbleroller",
    categoryId: "cat-recovery-gear",
    description: "RumbleRoller ridged foam rollers.",
    productIds: ["prod-rumbleroller-original"],
  },
  {
    id: "fam-brazyn-morph",
    brandId: "brand-brazyn",
    name: "Morph",
    slug: "brazyn-morph",
    categoryId: "cat-recovery-gear",
    description: "Brazyn collapsible Morph foam rollers.",
    productIds: ["prod-brazyn-morph"],
  },
  {
    id: "fam-blackroll",
    brandId: "brand-blackroll",
    name: "BLACKROLL",
    slug: "blackroll",
    categoryId: "cat-recovery-gear",
    description:
      "BLACKROLL foam rollers — running recovery wave lists PRO; Standard lives in fitness catalog.",
    productIds: ["prod-blackroll-pro", "prod-blackroll-standard"],
  },
  {
    id: "fam-triggerpoint-mb",
    brandId: "brand-triggerpoint",
    name: "MB",
    slug: "triggerpoint-mb",
    categoryId: "cat-recovery-gear",
    description: "TriggerPoint massage balls.",
    productIds: ["prod-triggerpoint-mb1", "prod-triggerpoint-mbx"],
  },
  {
    id: "fam-rad-atom",
    brandId: "brand-rad",
    name: "Atom",
    slug: "rad-atom",
    categoryId: "cat-recovery-gear",
    description: "RAD Atom massage balls.",
    productIds: ["prod-rad-atom"],
  },
  {
    id: "fam-normatec",
    brandId: "brand-hyperice",
    name: "Normatec",
    slug: "normatec",
    categoryId: "cat-recovery-gear",
    description: "Hyperice Normatec pneumatic compression systems.",
    productIds: ["prod-normatec-3", "prod-normatec-go"],
  },
  {
    id: "fam-therabody-recoveryair",
    brandId: "brand-therabody",
    name: "RecoveryAir",
    slug: "therabody-recoveryair",
    categoryId: "cat-recovery-gear",
    description: "Therabody RecoveryAir / JetBoots compression boots.",
    productIds: ["prod-therabody-recoveryair"],
  },
  {
    id: "fam-oofos",
    brandId: "brand-oofos",
    name: "OOFOS",
    slug: "oofos",
    categoryId: "cat-recovery-gear",
    description: "OOFOS OOfoam recovery sandals and slides.",
    productIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oolala",
      "prod-oofos-oocandoo",
    ],
  },
  {
    id: "fam-hoka-ora",
    brandId: "brand-hoka",
    name: "Ora",
    slug: "hoka-ora",
    categoryId: "cat-recovery-gear",
    description: "HOKA Ora recovery slides.",
    productIds: ["prod-hoka-ora-recovery-slide"],
  },
  {
    id: "fam-cep-calf",
    brandId: "brand-cep",
    name: "Calf Sleeves",
    slug: "cep-calf",
    categoryId: "cat-recovery-gear",
    description: "CEP graduated compression calf sleeves.",
    productIds: ["prod-cep-calf-sleeves", "prod-cep-the-run-calf"],
  },
  {
    id: "fam-compressport-r2",
    brandId: "brand-compressport",
    name: "R2",
    slug: "compressport-r2",
    categoryId: "cat-recovery-gear",
    description: "Compressport R2 calf sleeves.",
    productIds: ["prod-compressport-r2"],
  },
  {
    id: "fam-2xu-refresh",
    brandId: "brand-2xu",
    name: "Refresh Recovery",
    slug: "2xu-refresh",
    categoryId: "cat-recovery-gear",
    description: "2XU Refresh Recovery compression garments.",
    productIds: ["prod-2xu-refresh-recovery"],
  },
  {
    id: "fam-the-stick",
    brandId: "brand-the-stick",
    name: "The Stick",
    slug: "the-stick",
    categoryId: "cat-recovery-gear",
    description: "The Stick handheld mobility rollers.",
    productIds: ["prod-the-stick"],
  },
  {
    id: "fam-triggerpoint-stp",
    brandId: "brand-triggerpoint",
    name: "STP",
    slug: "triggerpoint-stp",
    categoryId: "cat-recovery-gear",
    description: "TriggerPoint STP massage sticks.",
    productIds: ["prod-triggerpoint-stp"],
  },
  {
    id: "fam-hyperice-vyper",
    brandId: "brand-hyperice",
    name: "Vyper",
    slug: "hyperice-vyper",
    categoryId: "cat-recovery-gear",
    description: "Hyperice Vyper vibrating foam rollers.",
    productIds: ["prod-hyperice-vyper-3"],
  },
];
