/**
 * Prompt 14 recommendation expansion for Finder / Rotation readiness.
 * Scores are context-specific and intentionally discriminate — not clustered 90+.
 * No affiliate influence. No fabricated personal-test claims.
 */
import type {
  AlternativeRelationship,
  Recommendation,
} from "@/domain/recommendations/types";

export const runningCatalogRecommendations: Recommendation[] = [
  // ── Novablast 6 ──────────────────────────────────────────────
  {
    id: "rec-nb6-daily",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 94,
    factors: [
      { key: "cushion", score: 93, weight: 0.3, explanation: "High stack soft daily ride." },
      { key: "energy", score: 95, weight: 0.35, explanation: "FF Turbo Squared forefoot pod adds toe-off pop vs gen 5." },
      { key: "versatility", score: 90, weight: 0.2, explanation: "Easy-to-moderate paces without needing a second shoe." },
      { key: "grip", score: 88, weight: 0.15, explanation: "ASICSGRIP forefoot improves wet-road confidence." },
    ],
    strengths: ["Bouncy daily trainer", "Improved wet traction vs 5"],
    compromises: ["Not a stability shoe", "Not a pure race shoe"],
    explanation: "Top-tier soft daily trainer for neutral road runners in 2026.",
    evidenceIds: ["ev-novablast-6-mfr", "ev-catalog-editorial"],
  },
  {
    id: "rec-nb6-long",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 93,
    factors: [
      { key: "protection", score: 94, weight: 0.5, explanation: "41.5 mm heel stack protects on long efforts." },
      { key: "energy", score: 92, weight: 0.5, explanation: "Bounce helps late in long runs." },
    ],
    strengths: [
      "Excellent long-run companion",
      "Late-run energy from FF TURBO SQUARED",
      "Light for the protective stack",
    ],
    compromises: ["Wide-last runners may prefer other brands"],
    explanation:
      "Strong long-run road option when you want soft protection with enough bounce for progression finishes — not a pure recovery mush shoe.",
    evidenceIds: ["ev-novablast-6-mfr", "ev-catalog-editorial"],
  },
  {
    id: "rec-nb6-easy",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-easy-runs",
    score: 95,
    factors: [
      { key: "comfort", score: 96, weight: 0.55, explanation: "Soft FF Blast Max landing." },
      { key: "energy", score: 92, weight: 0.45, explanation: "Keeps easy miles lively." },
    ],
    strengths: ["Comfortable easy-day shoe"],
    compromises: ["May feel too soft for runners who prefer firm dailies"],
    explanation: "Excellent for easy and recovery-paced road miles.",
    evidenceIds: ["ev-novablast-6-mfr", "ev-catalog-editorial"],
  },
  {
    id: "rec-nb6-tempo",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-tempo-runs",
    score: 80,
    factors: [
      { key: "responsiveness", score: 84, weight: 0.55, explanation: "Forefoot pod helps moderate tempos." },
      { key: "weight", score: 74, weight: 0.45, explanation: "Heavier than dedicated tempo shoes." },
    ],
    strengths: ["Usable for moderate tempos"],
    compromises: ["Tempo specialists (Speed 5, Boston) score higher"],
    explanation: "Serviceable occasional tempo shoe; not a workout specialist.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-nb6-trail",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 20,
    factors: [
      { key: "grip", score: 15, weight: 0.6, explanation: "Road outsole." },
      { key: "protection", score: 28, weight: 0.4, explanation: "No rock plate." },
    ],
    strengths: [],
    compromises: ["Wrong tool for trail"],
    explanation: "Not recommended for trail running.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-nb6-recovery",
    productId: "prod-novablast-6",
    sportId: "sport-running",
    useCaseId: "uc-recovery-runs",
    score: 90,
    factors: [
      { key: "cushion", score: 92, weight: 0.6, explanation: "Soft high stack." },
      { key: "comfort", score: 88, weight: 0.4, explanation: "Forgiving ride for easy days." },
    ],
    strengths: ["Soft recovery-friendly ride"],
    compromises: ["Bondi/Nimbus are plusher for pure recovery"],
    explanation: "Works well for easy recovery jogging.",
    evidenceIds: ["ev-catalog-editorial"],
  },

  // ── Ghost 18 ─────────────────────────────────────────────────
  {
    id: "rec-ghost18-daily",
    productId: "prod-ghost-18",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 91,
    factors: [
      { key: "comfort", score: 94, weight: 0.35, explanation: "Predictable soft daily cushioning." },
      { key: "widths", score: 96, weight: 0.3, explanation: "Broad official width range." },
      { key: "versatility", score: 86, weight: 0.2, explanation: "Covers most easy/steady mileage." },
      { key: "energy", score: 78, weight: 0.15, explanation: "Less lively than Novablast." },
    ],
    strengths: ["Beginner-friendly", "Width options"],
    compromises: ["Less energetic than bouncy dailies"],
    explanation: "Reliable versatile daily trainer, especially for fit-sensitive runners.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-ghost18-beginners",
    productId: "prod-ghost-18",
    sportId: "sport-running",
    useCaseId: "uc-beginners",
    score: 94,
    factors: [
      { key: "forgiveness", score: 95, weight: 0.45, explanation: "Approachable soft ride." },
      { key: "widths", score: 96, weight: 0.3, explanation: "Fit success across widths." },
      { key: "availability", score: 90, weight: 0.25, explanation: "Easy to try and buy." },
    ],
    strengths: ["Strong first serious running shoe"],
    compromises: ["Advanced speed work needs another shoe"],
    explanation: "Top beginner daily trainer recommendation.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-ghost18-easy",
    productId: "prod-ghost-18",
    sportId: "sport-running",
    useCaseId: "uc-easy-runs",
    score: 92,
    factors: [
      { key: "comfort", score: 94, weight: 0.6, explanation: "Calm soft landing." },
      { key: "durability", score: 88, weight: 0.4, explanation: "Built for easy volume." },
    ],
    strengths: ["Easy-mile reliability"],
    compromises: ["Not a tempo shoe"],
    explanation: "Excellent easy-run daily.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-ghost18-long",
    productId: "prod-ghost-18",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 88,
    factors: [
      { key: "protection", score: 88, weight: 0.5, explanation: "Adequate long-run cushion." },
      { key: "comfort", score: 90, weight: 0.5, explanation: "Fit holds up as feet swell." },
    ],
    strengths: ["Long-run friendly daily"],
    compromises: ["Max-cushion shoes score higher for recovery-focused longs"],
    explanation: "Solid long-run daily trainer.",
    evidenceIds: ["ev-catalog-editorial"],
  },

  // ── Clifton 10 / Bondi 9 ─────────────────────────────────────
  {
    id: "rec-clifton10-daily",
    productId: "prod-clifton-10",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 89,
    factors: [
      { key: "cushion", score: 92, weight: 0.4, explanation: "Max-cushion HOKA stack." },
      { key: "weight", score: 88, weight: 0.3, explanation: "Relatively light for the cushion." },
      { key: "versatility", score: 84, weight: 0.3, explanation: "Easy/long focused." },
    ],
    strengths: ["Soft rockered daily"],
    compromises: ["Fit can run short for some"],
    explanation: "Strong soft daily / long-run shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-clifton10-long",
    productId: "prod-clifton-10",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 91,
    factors: [
      { key: "protection", score: 92, weight: 0.55, explanation: "High stack protection." },
      { key: "comfort", score: 90, weight: 0.45, explanation: "Smooth meta-rocker." },
    ],
    strengths: [
      "Long-run protection",
      "Smooth meta-rocker on sustained easy pace",
      "Lighter long-day package than Bondi",
    ],
    compromises: ["Less responsive for workouts"],
    explanation:
      "Excellent long easy miles when you want HOKA rocker and high-stack protection without max-Bondi weight.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-clifton10-recovery",
    productId: "prod-clifton-10",
    sportId: "sport-running",
    useCaseId: "uc-recovery-runs",
    score: 90,
    factors: [
      { key: "cushion", score: 93, weight: 0.6, explanation: "Plush max cushion." },
      { key: "comfort", score: 88, weight: 0.4, explanation: "Easy recovery pacing." },
    ],
    strengths: ["Recovery-friendly"],
    compromises: ["Bondi is plusher still"],
    explanation: "Good recovery/easy option.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-bondi9-recovery",
    productId: "prod-bondi-9",
    sportId: "sport-running",
    useCaseId: "uc-recovery-runs",
    score: 96,
    factors: [
      { key: "cushion", score: 98, weight: 0.7, explanation: "Category max-cushion benchmark." },
      { key: "protection", score: 94, weight: 0.3, explanation: "Very high stack." },
    ],
    strengths: ["Maximum easy-day cushion"],
    compromises: ["Heavy and slow for workouts"],
    explanation: "Obvious max-cushion recovery / easy shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-bondi9-easy",
    productId: "prod-bondi-9",
    sportId: "sport-running",
    useCaseId: "uc-easy-runs",
    score: 94,
    factors: [
      { key: "cushion", score: 97, weight: 0.6, explanation: "Plush landing." },
      { key: "comfort", score: 92, weight: 0.4, explanation: "Protective easy miles." },
    ],
    strengths: ["Soft easy miles"],
    compromises: ["Not versatile for speed"],
    explanation: "Best-in-class soft easy/recovery road shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-bondi9-long",
    productId: "prod-bondi-9",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 93,
    factors: [
      { key: "protection", score: 97, weight: 0.55, explanation: "Max stack for protective long easy miles." },
      { key: "cushion", score: 96, weight: 0.45, explanation: "Category-leading plush underfoot." },
    ],
    strengths: [
      "Maximum cushion for long easy protection",
      "Soft recovery-paced long-run role",
      "Wide options for volume training",
    ],
    compromises: ["Heavy and slow if the long run includes faster work"],
    explanation:
      "Top max-cushion long-run option when softness and joint protection matter more than late-run energy.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-bondi9-tempo",
    productId: "prod-bondi-9",
    sportId: "sport-running",
    useCaseId: "uc-tempo-runs",
    score: 42,
    factors: [
      { key: "responsiveness", score: 40, weight: 0.5, explanation: "Max cushion is slow for tempos." },
      { key: "weight", score: 35, weight: 0.5, explanation: "Heavy vs tempo shoes." },
    ],
    strengths: [],
    compromises: ["Wrong tool for tempo"],
    explanation: "Poor tempo choice — use a workout shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },

  // ── Tempo / race ─────────────────────────────────────────────
  {
    id: "rec-speed5-tempo",
    productId: "prod-endorphin-speed-5",
    sportId: "sport-running",
    useCaseId: "uc-tempo-runs",
    score: 94,
    factors: [
      { key: "responsiveness", score: 95, weight: 0.45, explanation: "Nylon plate + PWRRUN PB for workouts." },
      { key: "versatility", score: 92, weight: 0.3, explanation: "Covers tempo to race." },
      { key: "weight", score: 90, weight: 0.25, explanation: "Light for a trainer-racer." },
    ],
    strengths: ["Workout specialist", "Race-capable"],
    compromises: ["Overkill for pure recovery jogs"],
    explanation: "Benchmark nylon-plated tempo / race hybrid.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-speed5-intervals",
    productId: "prod-endorphin-speed-5",
    sportId: "sport-running",
    useCaseId: "uc-intervals",
    score: 92,
    factors: [
      { key: "responsiveness", score: 94, weight: 0.55, explanation: "Quick turnover for intervals." },
      { key: "weight", score: 90, weight: 0.45, explanation: "Light enough for repeats." },
    ],
    strengths: ["Interval-ready"],
    compromises: ["Carbon racers edge it for pure race day"],
    explanation: "Excellent interval / speed session shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-speed5-half",
    productId: "prod-endorphin-speed-5",
    sportId: "sport-running",
    useCaseId: "uc-half",
    score: 90,
    factors: [
      { key: "race-efficiency", score: 90, weight: 0.5, explanation: "Plated platform for HM effort." },
      { key: "protection", score: 86, weight: 0.3, explanation: "Enough stack for half distance." },
      { key: "weight", score: 88, weight: 0.2, explanation: "Raceable weight." },
    ],
    strengths: ["Strong HM race option"],
    compromises: ["Dedicated carbon racers score higher for PBs"],
    explanation: "Very strong half-marathon race/workout shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-speed5-easy",
    productId: "prod-endorphin-speed-5",
    sportId: "sport-running",
    useCaseId: "uc-easy-runs",
    score: 58,
    factors: [
      { key: "comfort", score: 60, weight: 0.5, explanation: "Firmer/faster geometry than easy dailies." },
      { key: "cushion", score: 55, weight: 0.5, explanation: "Not a recovery max-cushion shoe." },
    ],
    strengths: ["Can do easy if it is your only shoe"],
    compromises: ["Better saved for quality sessions"],
    explanation: "Usable but suboptimal for pure easy days.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-vaporfly4-marathon",
    productId: "prod-vaporfly-4",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 95,
    factors: [
      { key: "race-efficiency", score: 97, weight: 0.5, explanation: "Carbon race platform." },
      { key: "weight", score: 94, weight: 0.3, explanation: "Race-day light." },
      { key: "protection", score: 88, weight: 0.2, explanation: "Adequate marathon stack." },
    ],
    strengths: ["Marathon PB tool"],
    compromises: ["Expensive", "Not a daily trainer"],
    explanation: "Obvious marathon race shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-vaporfly4-5k",
    productId: "prod-vaporfly-4",
    sportId: "sport-running",
    useCaseId: "uc-5k",
    score: 88,
    factors: [
      { key: "race-weight", score: 90, weight: 0.5, explanation: "Light racer." },
      { key: "responsiveness", score: 92, weight: 0.5, explanation: "Carbon pop for shorter races." },
    ],
    strengths: ["Fast road racer"],
    compromises: ["Overbuilt for some 5K specialists who prefer flats"],
    explanation: "Strong 5K–marathon race option.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-vaporfly4-daily",
    productId: "prod-vaporfly-4",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 35,
    factors: [
      { key: "durability", score: 30, weight: 0.5, explanation: "Race foam not for high easy mileage." },
      { key: "versatility", score: 40, weight: 0.5, explanation: "Wrong geometry for easy days." },
    ],
    strengths: [],
    compromises: ["Not a daily trainer"],
    explanation: "Do not use as a daily trainer.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-alphafly3-marathon",
    productId: "prod-alphafly-3",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 96,
    factors: [
      {
        key: "race-efficiency",
        score: 98,
        weight: 0.4,
        explanation: "Dual Air Zoom + ZoomX carbon stack for race economy.",
      },
      {
        key: "protection",
        score: 94,
        weight: 0.3,
        explanation: "Maximum marathon stack and cushioning.",
      },
      {
        key: "responsiveness",
        score: 95,
        weight: 0.3,
        explanation: "Top-tier pop for race-day pace.",
      },
    ],
    strengths: ["Maximum race-day stack and pop", "Marathon specialist geometry"],
    compromises: ["Expensive", "Overkill for shorter / easy runs"],
    explanation: "Nike’s premium marathon race platform.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-alphafly3-half",
    productId: "prod-alphafly-3",
    sportId: "sport-running",
    useCaseId: "uc-half",
    score: 90,
    factors: [
      {
        key: "race-efficiency",
        score: 94,
        weight: 0.5,
        explanation: "Race geometry carries well to the half.",
      },
      {
        key: "weight",
        score: 86,
        weight: 0.5,
        explanation: "Heavier than some shorter-distance racers.",
      },
    ],
    strengths: ["Half and full race specialist"],
    compromises: ["May feel overbuilt for some half specialists"],
    explanation: "Strong half-marathon race option for runners who want Alphafly geometry.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-alphafly3-daily",
    productId: "prod-alphafly-3",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 28,
    factors: [
      {
        key: "durability",
        score: 25,
        weight: 0.5,
        explanation: "Race foam and units are not for high easy mileage.",
      },
      {
        key: "versatility",
        score: 30,
        weight: 0.5,
        explanation: "Wrong tool for daily training.",
      },
    ],
    strengths: [],
    compromises: ["Not a daily trainer"],
    explanation: "Do not use as a daily trainer.",
    evidenceIds: ["ev-catalog-editorial"],
  },

  // ── Stability / trail ────────────────────────────────────────
  {
    id: "rec-kayano-daily",
    productId: "prod-kayano-32",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 88,
    factors: [
      { key: "stability", score: 94, weight: 0.4, explanation: "Dedicated stability platform." },
      { key: "cushion", score: 88, weight: 0.3, explanation: "Protective daily cushion." },
      { key: "comfort", score: 86, weight: 0.3, explanation: "Supportive long-wear comfort." },
    ],
    strengths: ["Stability daily"],
    compromises: ["Heavier than neutral dailies"],
    explanation: "Strong stability daily trainer.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-adrenaline-daily",
    productId: "prod-adrenaline-gts-25",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 87,
    factors: [
      { key: "stability", score: 92, weight: 0.4, explanation: "GuideRails support." },
      { key: "widths", score: 94, weight: 0.3, explanation: "Strong width range." },
      { key: "comfort", score: 85, weight: 0.3, explanation: "Approachable daily ride." },
    ],
    strengths: ["Stability + widths"],
    compromises: ["Less lively than neutral bouncy trainers"],
    explanation: "Versatile stability daily.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-speedgoat-trail",
    productId: "prod-speedgoat-6",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 94,
    factors: [
      { key: "grip", score: 96, weight: 0.45, explanation: "Aggressive trail outsole." },
      { key: "protection", score: 92, weight: 0.35, explanation: "Trail stack and underfoot protection." },
      { key: "cushion", score: 88, weight: 0.2, explanation: "HOKA cushion for long trail days." },
    ],
    strengths: ["Trail grip", "Long trail comfort"],
    compromises: ["Not a road daily"],
    explanation: "Obvious capable trail shoe.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-peregrine-trail",
    productId: "prod-peregrine-15",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 90,
    factors: [
      { key: "grip", score: 92, weight: 0.5, explanation: "Trail lug pattern." },
      { key: "protection", score: 86, weight: 0.3, explanation: "Trail upper/outsole protection." },
      { key: "weight", score: 84, weight: 0.2, explanation: "Manageable trail weight." },
    ],
    strengths: ["Versatile trail shoe"],
    compromises: ["Less max cushion than Speedgoat"],
    explanation: "Strong general trail trainer.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-pegasus42-daily",
    productId: "prod-pegasus-42",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 90,
    factors: [
      { key: "versatility", score: 94, weight: 0.4, explanation: "Covers easy-to-moderate paces." },
      { key: "durability", score: 88, weight: 0.3, explanation: "Workhorse reputation." },
      { key: "responsiveness", score: 84, weight: 0.3, explanation: "Firmer than plush dailies; better for mixed weeks." },
    ],
    strengths: ["One-shoe versatility"],
    compromises: ["Not max cushion"],
    explanation: "Versatile daily trainer for mixed training weeks.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-pegasus42-tempo",
    productId: "prod-pegasus-42",
    sportId: "sport-running",
    useCaseId: "uc-tempo-runs",
    score: 82,
    factors: [
      { key: "responsiveness", score: 84, weight: 0.55, explanation: "Handles steady tempos." },
      { key: "weight", score: 78, weight: 0.45, explanation: "Heavier than dedicated tempo shoes." },
    ],
    strengths: ["Can cover moderate tempos"],
    compromises: ["Speed 5 / Boston score higher for quality sessions"],
    explanation: "Capable occasional tempo daily.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-pegasus42-treadmill",
    productId: "prod-pegasus-42",
    sportId: "sport-running",
    useCaseId: "uc-treadmill",
    score: 88,
    factors: [
      { key: "versatility", score: 90, weight: 0.5, explanation: "Works well indoor/outdoor." },
      { key: "durability", score: 86, weight: 0.5, explanation: "Durable for belt miles." },
    ],
    strengths: ["Treadmill-friendly daily"],
    compromises: ["Not a trail shoe"],
    explanation: "Good treadmill / mixed surface daily.",
    evidenceIds: ["ev-catalog-editorial"],
  },

  // ── Nimbus 27 ────────────────────────────────────────────────
  {
    id: "rec-nimbus27-daily",
    productId: "prod-nimbus-27",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 92,
    factors: [
      { key: "cushion", score: 96, weight: 0.4, explanation: "Maximum cushion daily platform." },
      { key: "comfort", score: 94, weight: 0.35, explanation: "Plush easy-mile comfort." },
      { key: "versatility", score: 78, weight: 0.25, explanation: "Less suited to mixed faster work." },
    ],
    strengths: ["Protective daily cushioning", "Width options"],
    compromises: ["Heavier and less lively than Novablast"],
    explanation: "Strong max-cushion daily when comfort is the priority.",
    evidenceIds: ["ev-nimbus-editorial", "ev-catalog-editorial"],
  },
  {
    id: "rec-nimbus27-long",
    productId: "prod-nimbus-27",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 95,
    factors: [
      { key: "protection", score: 96, weight: 0.55, explanation: "Maximum stack for long easy miles." },
      { key: "comfort", score: 94, weight: 0.45, explanation: "Comfort-first long-run ride." },
    ],
    strengths: [
      "Long-run protection",
      "Max-cushion PureGEL / FF BLAST PLUS ECO platform",
      "Width options for high-mileage fit",
    ],
    compromises: ["Not ideal for long runs that include faster segments"],
    explanation:
      "Top pick when long runs prioritise plush ASICS protection and width depth over late-run bounce.",
    evidenceIds: ["ev-nimbus-mfr", "ev-nimbus-editorial"],
  },
  {
    id: "rec-superblast2-long",
    productId: "prod-superblast-2",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 92,
    factors: [
      { key: "protection", score: 93, weight: 0.45, explanation: "High stack protects on long efforts." },
      { key: "energy", score: 90, weight: 0.55, explanation: "More range than pure plush recovery shoes." },
    ],
    strengths: [
      "Protective high-mileage long-run platform",
      "Works for steady endurance pacing",
    ],
    compromises: ["Premium price for shuffle-only long runs"],
    explanation:
      "Strong long-run / endurance option when you want stack with more pace range than max-plush shoes.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-kayano-long",
    productId: "prod-kayano-32",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 90,
    factors: [
      { key: "stability", score: 94, weight: 0.5, explanation: "Guided support for long volume." },
      { key: "protection", score: 90, weight: 0.5, explanation: "Protective cushion for endurance sessions." },
    ],
    strengths: ["Stability for long easy volume", "Protective cushion"],
    compromises: ["Heavier than neutral long-run shoes"],
    explanation:
      "Primary stability long-run pick when guidance matters as much as cushion.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-glycerin22-long",
    productId: "prod-glycerin-22",
    sportId: "sport-running",
    useCaseId: "uc-long-runs",
    score: 89,
    factors: [
      { key: "cushion", score: 93, weight: 0.55, explanation: "Soft DNA LOFT protection." },
      { key: "comfort", score: 90, weight: 0.45, explanation: "Width-friendly soft long-run daily." },
    ],
    strengths: ["Soft long-run ride", "Brooks width options"],
    compromises: ["Less energetic for progression finishes"],
    explanation:
      "Soft Brooks long-run daily when Bondi/Nimbus aren’t the right brand or fit.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-nimbus27-recovery",
    productId: "prod-nimbus-27",
    sportId: "sport-running",
    useCaseId: "uc-recovery-runs",
    score: 96,
    factors: [
      { key: "cushion", score: 97, weight: 0.6, explanation: "Softest protective recovery feel in this pair." },
      { key: "comfort", score: 95, weight: 0.4, explanation: "Easy recovery pacing." },
    ],
    strengths: ["Recovery-friendly cushioning"],
    compromises: ["Slow for anything beyond easy pace"],
    explanation: "Excellent recovery / easy shoe.",
    evidenceIds: ["ev-nimbus-editorial"],
  },
  {
    id: "rec-nimbus27-tempo",
    productId: "prod-nimbus-27",
    sportId: "sport-running",
    useCaseId: "uc-tempo-runs",
    score: 55,
    factors: [
      { key: "responsiveness", score: 50, weight: 0.55, explanation: "Max cushion is slow for tempos." },
      { key: "weight", score: 48, weight: 0.45, explanation: "Heavier than tempo tools." },
    ],
    strengths: [],
    compromises: ["Wrong tool for dedicated tempos"],
    explanation: "Poor tempo choice versus livelier dailies.",
    evidenceIds: ["ev-catalog-editorial"],
  },
  {
    id: "rec-nimbus27-easy",
    productId: "prod-nimbus-27",
    sportId: "sport-running",
    useCaseId: "uc-easy-runs",
    score: 94,
    factors: [
      { key: "comfort", score: 96, weight: 0.6, explanation: "Plush easy landings." },
      { key: "cushion", score: 96, weight: 0.4, explanation: "Maximum cushion feel." },
    ],
    strengths: ["Easy-mile comfort"],
    compromises: ["Less energetic than Novablast"],
    explanation: "Strong easy-day max-cushion option.",
    evidenceIds: ["ev-nimbus-editorial"],
  },
];
export const runningCatalogAlternatives: AlternativeRelationship[] = [
  {
    id: "alt-nb6-nb5",
    sourceProductId: "prod-novablast-6",
    alternativeProductId: "prod-novablast-5",
    similarityScore: 90,
    reasons: ["Same family previous generation", "Often better value when discounted"],
    relationshipType: "better-value",
  },
  {
    id: "alt-nb6-ghost18",
    sourceProductId: "prod-novablast-6",
    alternativeProductId: "prod-ghost-18",
    similarityScore: 80,
    reasons: ["Both neutral dailies", "Ghost offers more width options"],
    relationshipType: "beginner-friendly",
  },
  {
    id: "alt-nb6-clifton10",
    sourceProductId: "prod-novablast-6",
    alternativeProductId: "prod-clifton-10",
    similarityScore: 82,
    reasons: ["Both soft high-stack dailies", "Clifton more max-cushion oriented"],
    relationshipType: "more-cushioned",
  },
  {
    id: "alt-ghost18-peg42",
    sourceProductId: "prod-ghost-18",
    alternativeProductId: "prod-pegasus-42",
    similarityScore: 84,
    reasons: ["Direct daily trainer competitors", "Pegasus firmer/more versatile for pace changes"],
    relationshipType: "faster",
  },
  {
    id: "alt-speed5-boston",
    sourceProductId: "prod-endorphin-speed-5",
    alternativeProductId: "prod-boston-12",
    similarityScore: 86,
    reasons: ["Both plated tempo platforms"],
    relationshipType: "faster",
  },
  {
    id: "alt-vaporfly-alphafly",
    sourceProductId: "prod-vaporfly-4",
    alternativeProductId: "prod-alphafly-3",
    similarityScore: 88,
    reasons: ["Same brand carbon race family", "Alphafly is premium race option"],
    relationshipType: "premium",
  },
  {
    id: "alt-alphafly-vaporfly",
    sourceProductId: "prod-alphafly-3",
    alternativeProductId: "prod-vaporfly-4",
    similarityScore: 88,
    reasons: ["Same race family", "Vaporfly lighter and often cheaper"],
    relationshipType: "lighter",
  },
  {
    id: "alt-alphafly-metaspeed",
    sourceProductId: "prod-alphafly-3",
    alternativeProductId: "prod-metaspeed-sky-paris",
    similarityScore: 84,
    reasons: ["Premium marathon racers", "Different plate/foam philosophies"],
    relationshipType: "faster",
  },
  {
    id: "alt-alphafly-endorphin-pro",
    sourceProductId: "prod-alphafly-3",
    alternativeProductId: "prod-endorphin-pro-4",
    similarityScore: 82,
    reasons: ["Carbon race competitors", "Endorphin Pro often better value"],
    relationshipType: "better-value",
  },
  {
    id: "alt-speedgoat-peregrine",
    sourceProductId: "prod-speedgoat-6",
    alternativeProductId: "prod-peregrine-15",
    similarityScore: 82,
    reasons: ["Trail competitors", "Peregrine often lighter/lower stack"],
    relationshipType: "lighter",
  },
  {
    id: "alt-fr970-fr965",
    sourceProductId: "prod-forerunner-970",
    alternativeProductId: "prod-forerunner-965",
    similarityScore: 88,
    reasons: ["Previous flagship generation", "Often better value"],
    relationshipType: "better-value",
  },
  {
    id: "alt-fr970-pacepro",
    sourceProductId: "prod-forerunner-970",
    alternativeProductId: "prod-coros-pace-pro",
    similarityScore: 75,
    reasons: ["AMOLED maps competitors", "Pace Pro lighter/cheaper"],
    relationshipType: "cheaper",
  },
  {
    id: "alt-kayano-adrenaline",
    sourceProductId: "prod-kayano-32",
    alternativeProductId: "prod-adrenaline-gts-25",
    similarityScore: 85,
    reasons: ["Stability daily competitors"],
    relationshipType: "more-stable",
  },
];
