/**
 * Light suitability scores for Running Safety / Visibility wave 2.
 * Factors: visibility, comfort, battery, weather, usability, value.
 * Use cases: night-running, commute-running, winter-running, beginners
 * (plus daily-training where relevant).
 *
 * NOT wired into recommendations.ts aggregators yet (parent will wire).
 * NOTE: Best Safety / Visibility buying guide will be added by parent.
 *
 * Existing gear-wave1 peers (prod-nathan-reflective-vest, prod-nite-ize-radiant-clip)
 * are referenced as alternatives in product records but not rescored here.
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const safetyFactors = (scores: {
  visibility: number;
  comfort: number;
  battery: number;
  weather: number;
  usability: number;
  value: number;
}) => [
  {
    key: "visibility",
    label: "Visibility",
    score: scores.visibility,
    weight: 0.28,
    explanation: "How well drivers and others can see you in low light.",
  },
  {
    key: "comfort",
    label: "Comfort",
    score: scores.comfort,
    weight: 0.16,
    explanation: "Wearability over a full run without chafe or bounce.",
  },
  {
    key: "battery",
    label: "Battery",
    score: scores.battery,
    weight: 0.14,
    explanation: "Runtime, recharge/replace ease for illuminated gear.",
  },
  {
    key: "weather",
    label: "Weather",
    score: scores.weather,
    weight: 0.12,
    explanation: "Wet/cold reliability and water resistance.",
  },
  {
    key: "usability",
    label: "Usability",
    score: scores.usability,
    weight: 0.16,
    explanation: "On/off, modes, mounting and everyday ease of use.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.14,
    explanation: "Features vs typical street price.",
  },
];

function rec(
  id: string,
  productId: string,
  useCaseId: string,
  score: number,
  scores: Parameters<typeof safetyFactors>[0],
  strengths: string[],
  compromises: string[],
  explanation: string,
): Recommendation {
  return {
    id,
    productId,
    sportId: "sport-running",
    useCaseId,
    score,
    factors: safetyFactors(scores),
    strengths,
    compromises,
    explanation,
    evidenceIds: [...ev],
  };
}

export const runningSafetyRecommendations: Recommendation[] = [
  // ── Amphipod Xinglet ───────────────────────────────────────────────────
  rec(
    "rec-amphipod-xinglet-night-running",
    "prod-amphipod-xinglet",
    "uc-night-running",
    86,
    { visibility: 82, comfort: 90, battery: 70, weather: 62, usability: 88, value: 88 },
    ["360° reflective sash", "LED pads for Vizlet add-ons"],
    ["Passive until you add LEDs"],
    "Lightweight night-road reflective default when you want less bulk than a full vest.",
  ),
  rec(
    "rec-amphipod-xinglet-commute-running",
    "prod-amphipod-xinglet",
    "uc-commute-running",
    84,
    { visibility: 80, comfort: 90, battery: 70, weather: 64, usability: 90, value: 88 },
    ["Throws on over work layers", "SwiftClip on/off"],
    ["Needs active light for unlit streets"],
    "Commute-friendly reflective sash over jackets and day kit.",
  ),
  rec(
    "rec-amphipod-xinglet-winter-running",
    "prod-amphipod-xinglet",
    "uc-winter-running",
    80,
    { visibility: 78, comfort: 86, battery: 70, weather: 60, usability: 86, value: 86 },
    ["Works over winter layers", "Pads for clip LEDs"],
    ["Passive coverage only"],
    "Winter layering-friendly sash; pair with LEDs for dark roads.",
  ),
  rec(
    "rec-amphipod-xinglet-beginners",
    "prod-amphipod-xinglet",
    "uc-beginners",
    88,
    { visibility: 82, comfort: 92, battery: 72, weather: 62, usability: 92, value: 90 },
    ["Simple throw-on visibility", "Affordable entry"],
    ["Not illuminated out of the box"],
    "Beginner-friendly first visibility buy before illuminated vests.",
  ),

  // ── Amphipod Xinglet Optic Beam ────────────────────────────────────────
  rec(
    "rec-amphipod-xinglet-optic-beam-night-running",
    "prod-amphipod-xinglet-optic-beam",
    "uc-night-running",
    92,
    { visibility: 94, comfort: 84, battery: 78, weather: 76, usability: 86, value: 80 },
    ["Built-in rechargeable LEDs", "360° active + reflective"],
    ["Heavier than passive Xinglet"],
    "Top illuminated-vest pick for dark night road miles.",
  ),
  rec(
    "rec-amphipod-xinglet-optic-beam-commute-running",
    "prod-amphipod-xinglet-optic-beam",
    "uc-commute-running",
    90,
    { visibility: 92, comfort: 84, battery: 78, weather: 78, usability: 86, value: 80 },
    ["Active visibility for traffic", "USB rechargeable"],
    ["Charge before multi-leg weeks"],
    "Strong commute vest when headlights and dark streets both matter.",
  ),
  rec(
    "rec-amphipod-xinglet-optic-beam-winter-running",
    "prod-amphipod-xinglet-optic-beam",
    "uc-winter-running",
    91,
    { visibility: 94, comfort: 82, battery: 76, weather: 78, usability: 84, value: 80 },
    ["Active glow in deep winter dark", "Reflective backup"],
    ["Battery cold-drain awareness"],
    "Winter night default when passive reflection alone is thin.",
  ),
  rec(
    "rec-amphipod-xinglet-optic-beam-beginners",
    "prod-amphipod-xinglet-optic-beam",
    "uc-beginners",
    86,
    { visibility: 92, comfort: 84, battery: 78, weather: 76, usability: 84, value: 78 },
    ["One-piece lit vest", "Clear on/off modes"],
    ["Higher price than passive sash"],
    "Beginner night-road vest if budget allows an illuminated first buy.",
  ),

  // ── Amphipod Vizlet ────────────────────────────────────────────────────
  rec(
    "rec-amphipod-vizlet-night-running",
    "prod-amphipod-vizlet",
    "uc-night-running",
    82,
    { visibility: 80, comfort: 92, battery: 68, weather: 70, usability: 90, value: 92 },
    ["Magnet clip anywhere", "Flash + reflective disc"],
    ["Coin-cell maintenance"],
    "Cheap active points of light to stack on vest or kit.",
  ),
  rec(
    "rec-amphipod-vizlet-commute-running",
    "prod-amphipod-vizlet",
    "uc-commute-running",
    84,
    { visibility: 80, comfort: 92, battery: 68, weather: 72, usability: 92, value: 92 },
    ["Clips to bags and belts", "One-touch flash"],
    ["Not a primary light"],
    "Commute marker light for packs and clothing.",
  ),
  rec(
    "rec-amphipod-vizlet-beginners",
    "prod-amphipod-vizlet",
    "uc-beginners",
    88,
    { visibility: 78, comfort: 94, battery: 70, weather: 70, usability: 94, value: 94 },
    ["Low cost entry LED", "Pairs with Xinglet"],
    ["Coin cells to replace"],
    "Easiest beginner add-on LED for existing reflective gear.",
  ),
  rec(
    "rec-amphipod-vizlet-daily-training",
    "prod-amphipod-vizlet",
    "uc-daily-training",
    80,
    { visibility: 76, comfort: 92, battery: 68, weather: 70, usability: 90, value: 92 },
    ["Forgettable on kit", "Quick attach"],
    ["Small visible area alone"],
    "Daily dusk training marker when you already own a vest or belt.",
  ),

  // ── Proviz Reflect360 ──────────────────────────────────────────────────
  rec(
    "rec-proviz-reflect360-vest-night-running",
    "prod-proviz-reflect360-vest",
    "uc-night-running",
    88,
    { visibility: 90, comfort: 82, battery: 72, weather: 74, usability: 84, value: 82 },
    ["High Reflect360 coverage", "Works under headlights"],
    ["Passive only"],
    "High-coverage reflective vest for lit-road night running.",
  ),
  rec(
    "rec-proviz-reflect360-vest-commute-running",
    "prod-proviz-reflect360-vest",
    "uc-commute-running",
    90,
    { visibility: 92, comfort: 82, battery: 72, weather: 76, usability: 86, value: 82 },
    ["Vehicle-light punch", "Open vest over layers"],
    ["Add LEDs for unlit segments"],
    "Commute vest when car headlights are the main risk.",
  ),
  rec(
    "rec-proviz-reflect360-vest-winter-running",
    "prod-proviz-reflect360-vest",
    "uc-winter-running",
    89,
    { visibility: 90, comfort: 80, battery: 72, weather: 76, usability: 84, value: 82 },
    ["Fits over winter jackets", "Strong headlight return"],
    ["Bulkier than a sash"],
    "Winter road vest for dark, headlight-heavy routes.",
  ),
  rec(
    "rec-proviz-reflect360-vest-beginners",
    "prod-proviz-reflect360-vest",
    "uc-beginners",
    87,
    { visibility: 90, comfort: 84, battery: 74, weather: 74, usability: 88, value: 84 },
    ["Obvious hi-vis coverage", "No charging required"],
    ["Not illuminated"],
    "Beginner-friendly full reflective vest without battery hassle.",
  ),

  // ── Knog Frog V3 ───────────────────────────────────────────────────────
  rec(
    "rec-knog-frog-v3-night-running",
    "prod-knog-frog-v3",
    "uc-night-running",
    86,
    { visibility: 86, comfort: 88, battery: 90, weather: 88, usability: 88, value: 84 },
    ["Front+rear twin pack", "Long eco runtime"],
    ["Marker light, not path light"],
    "Rechargeable twin clip lights for multi-point night visibility.",
  ),
  rec(
    "rec-knog-frog-v3-commute-running",
    "prod-knog-frog-v3",
    "uc-commute-running",
    90,
    { visibility: 88, comfort: 88, battery: 90, weather: 90, usability: 90, value: 84 },
    ["Bike/run dual use", "IP65 weather seal"],
    ["USB-C cable often separate"],
    "Top commute clip-light set for run and bike legs.",
  ),
  rec(
    "rec-knog-frog-v3-winter-running",
    "prod-knog-frog-v3",
    "uc-winter-running",
    88,
    { visibility: 86, comfort: 86, battery: 90, weather: 90, usability: 86, value: 84 },
    ["Waterproof strap mounts", "Long winter flash life"],
    ["Silicone can stiffen in deep cold"],
    "Winter-ready active markers with strong weather resistance.",
  ),
  rec(
    "rec-knog-frog-v3-beginners",
    "prod-knog-frog-v3",
    "uc-beginners",
    85,
    { visibility: 84, comfort: 88, battery: 88, weather: 86, usability: 90, value: 84 },
    ["Simple one-button modes", "Twin pack value"],
    ["More modes than beginners need"],
    "Beginner-friendly rechargeable clip lights with clear mounts.",
  ),

  // ── Knog Cobber Mid ────────────────────────────────────────────────────
  rec(
    "rec-knog-cobber-mid-night-running",
    "prod-knog-cobber-mid",
    "uc-night-running",
    84,
    { visibility: 90, comfort: 78, battery: 80, weather: 88, usability: 80, value: 76 },
    ["Wide-angle COB punch", "Side visibility"],
    ["Bulkier than Frog"],
    "Brighter wearable/clip marker for dark night corridors.",
  ),
  rec(
    "rec-knog-cobber-mid-commute-running",
    "prod-knog-cobber-mid",
    "uc-commute-running",
    88,
    { visibility: 92, comfort: 78, battery: 80, weather: 90, usability: 82, value: 76 },
    ["Traffic-facing beam width", "Tool-free strap"],
    ["Overkill for short lit jogs"],
    "Commute visibility step-up when Frog output is thin.",
  ),
  rec(
    "rec-knog-cobber-mid-winter-running",
    "prod-knog-cobber-mid",
    "uc-winter-running",
    86,
    { visibility: 90, comfort: 76, battery: 78, weather: 90, usability: 80, value: 76 },
    ["Strong wet-weather seal", "High output flash"],
    ["Larger pack/belt footprint"],
    "Winter dark-road marker with wide approach visibility.",
  ),

  // ── Night Runner 270 ───────────────────────────────────────────────────
  rec(
    "rec-nightrunner-270-night-running",
    "prod-nightrunner-270",
    "uc-night-running",
    87,
    { visibility: 90, comfort: 80, battery: 78, weather: 74, usability: 82, value: 76 },
    ["Shoe-level traffic cue", "Frees torso kit"],
    ["Shoe fit varies"],
    "Night-road shoe lights when you want light at footstrike height.",
  ),
  rec(
    "rec-nightrunner-270-commute-running",
    "prod-nightrunner-270",
    "uc-commute-running",
    85,
    { visibility: 88, comfort: 80, battery: 78, weather: 74, usability: 82, value: 76 },
    ["Visible to low headlights", "Dedicated run mount"],
    ["Not a headlamp path light"],
    "Commute shoe lights for drivers looking at road level.",
  ),
  rec(
    "rec-nightrunner-270-winter-running",
    "prod-nightrunner-270",
    "uc-winter-running",
    84,
    { visibility: 88, comfort: 78, battery: 76, weather: 72, usability: 80, value: 76 },
    ["Active glow in deep dark", "Independent of jackets"],
    ["Cold battery management"],
    "Winter night option when jackets cover torso lights.",
  ),
  rec(
    "rec-nightrunner-270-daily-training",
    "prod-nightrunner-270",
    "uc-daily-training",
    80,
    { visibility: 84, comfort: 82, battery: 78, weather: 72, usability: 82, value: 76 },
    ["Hands-free shoe mount", "Reusable each session"],
    ["Setup time vs clip lights"],
    "Daily dusk training when you prefer shoe-mounted lights.",
  ),

  // ── Nathan LightBender RX ──────────────────────────────────────────────
  rec(
    "rec-nathan-lightbender-night-running",
    "prod-nathan-lightbender",
    "uc-night-running",
    90,
    { visibility: 88, comfort: 86, battery: 90, weather: 84, usability: 88, value: 86 },
    ["Long flash runtime", "RGB armband glow"],
    ["Better over sleeves"],
    "Go-to wearable LED armband for night road visibility.",
  ),
  rec(
    "rec-nathan-lightbender-commute-running",
    "prod-nathan-lightbender",
    "uc-commute-running",
    88,
    { visibility: 86, comfort: 86, battery: 90, weather: 84, usability: 88, value: 86 },
    ["Low-profile on arm", "USB recharge"],
    ["Marker only"],
    "Commute wearable light that stays out of pack straps.",
  ),
  rec(
    "rec-nathan-lightbender-winter-running",
    "prod-nathan-lightbender",
    "uc-winter-running",
    89,
    { visibility: 88, comfort: 88, battery: 88, weather: 86, usability: 86, value: 86 },
    ["IPX4 wet runs", "Comfortable over sleeves"],
    ["6 lm is visibility not path light"],
    "Winter dusk/dark armband with strong battery life.",
  ),
  rec(
    "rec-nathan-lightbender-beginners",
    "prod-nathan-lightbender",
    "uc-beginners",
    90,
    { visibility: 86, comfort: 88, battery: 90, weather: 84, usability: 90, value: 88 },
    ["Simple color/mode controls", "Comfortable first LED"],
    ["Not a vest substitute for full coverage"],
    "Beginner-friendly first illuminated wearable.",
  ),

  // ── Nathan Lux Strobe RX ───────────────────────────────────────────────
  rec(
    "rec-nathan-strobe-night-running",
    "prod-nathan-strobe",
    "uc-night-running",
    86,
    { visibility: 84, comfort: 90, battery: 84, weather: 82, usability: 88, value: 86 },
    ["Multiple flash patterns", "Clips anywhere"],
    ["Smaller than armband glow"],
    "Stackable clip strobe for night multi-point lighting.",
  ),
  rec(
    "rec-nathan-strobe-commute-running",
    "prod-nathan-strobe",
    "uc-commute-running",
    87,
    { visibility: 84, comfort: 90, battery: 84, weather: 84, usability: 90, value: 86 },
    ["RGB clip versatility", "USB recharge"],
    ["Easy to forget to charge"],
    "Commute clip light peer to Radiant / Vizlet with more modes.",
  ),
  rec(
    "rec-nathan-strobe-winter-running",
    "prod-nathan-strobe",
    "uc-winter-running",
    85,
    { visibility: 84, comfort: 88, battery: 82, weather: 84, usability: 86, value: 86 },
    ["IPX4 weather seal", "RUN flash mode"],
    ["Clip placement on bulky layers"],
    "Winter clip strobe for jackets, belts and packs.",
  ),
  rec(
    "rec-nathan-strobe-beginners",
    "prod-nathan-strobe",
    "uc-beginners",
    86,
    { visibility: 82, comfort: 92, battery: 84, weather: 82, usability: 90, value: 88 },
    ["Clip-and-go setup", "Clear mode cycling"],
    ["Many modes to learn"],
    "Beginner clip LED that upgrades basic Radiant-style markers.",
  ),

  // ── Road ID Wrist ──────────────────────────────────────────────────────
  rec(
    "rec-road-id-wrist-night-running",
    "prod-road-id-wrist",
    "uc-night-running",
    74,
    { visibility: 40, comfort: 92, battery: 95, weather: 90, usability: 90, value: 88 },
    ["Always-on ICE info", "No battery to die"],
    ["Zero active visibility"],
    "Night solo runs: ID layer alongside lights and reflective gear.",
  ),
  rec(
    "rec-road-id-wrist-commute-running",
    "prod-road-id-wrist",
    "uc-commute-running",
    78,
    { visibility: 40, comfort: 92, battery: 95, weather: 90, usability: 92, value: 90 },
    ["Emergency contacts on wrist", "Daily wear comfort"],
    ["Does not help drivers see you"],
    "Commute safety ID that works when phones are locked or dead.",
  ),
  rec(
    "rec-road-id-wrist-beginners",
    "prod-road-id-wrist",
    "uc-beginners",
    82,
    { visibility: 40, comfort: 94, battery: 95, weather: 90, usability: 94, value: 92 },
    ["Simple set-and-forget", "Great value"],
    ["Must pair with visibility gear"],
    "Beginner essential ID band for solo training confidence.",
  ),
  rec(
    "rec-road-id-wrist-daily-training",
    "prod-road-id-wrist",
    "uc-daily-training",
    80,
    { visibility: 40, comfort: 94, battery: 95, weather: 90, usability: 92, value: 90 },
    ["Wear every session", "Waterproof"],
    ["Not a visibility product"],
    "Daily training ID habit for solo and early/late miles.",
  ),

  // ── She's Birdie ───────────────────────────────────────────────────────
  rec(
    "rec-shes-birdie-alarm-night-running",
    "prod-shes-birdie-alarm",
    "uc-night-running",
    84,
    { visibility: 70, comfort: 88, battery: 80, weather: 72, usability: 86, value: 82 },
    ["~130 dB pull siren", "Strobe attention cue"],
    ["Not a substitute for being seen"],
    "Night solo audible deterrent — alarm only, no weapons.",
  ),
  rec(
    "rec-shes-birdie-alarm-commute-running",
    "prod-shes-birdie-alarm",
    "uc-commute-running",
    86,
    { visibility: 68, comfort: 90, battery: 82, weather: 72, usability: 88, value: 84 },
    ["Keychain daily carry", "Travel-legal alarm"],
    ["Limited continuous runtime"],
    "Commute and early/late run personal alarm for peace of mind.",
  ),
  rec(
    "rec-shes-birdie-alarm-beginners",
    "prod-shes-birdie-alarm",
    "uc-beginners",
    88,
    { visibility: 68, comfort: 92, battery: 82, weather: 72, usability: 90, value: 86 },
    ["Simple pull activation", "No regulated weapon rules"],
    ["Must still build visibility kit"],
    "Beginner personal-alarm pick that stays legal and non-weapon.",
  ),
  rec(
    "rec-shes-birdie-alarm-daily-training",
    "prod-shes-birdie-alarm",
    "uc-daily-training",
    82,
    { visibility: 66, comfort: 90, battery: 80, weather: 72, usability: 88, value: 84 },
    ["Rechargeable EDC", "Flashlight mode"],
    ["Siren is last-resort only"],
    "Daily-carry alarm for solo training routes.",
  ),

  // ── FlipBelt Zipper Reflective ─────────────────────────────────────────
  rec(
    "rec-flipbelt-zippered-reflective-night-running",
    "prod-flipbelt-zippered-reflective",
    "uc-night-running",
    84,
    { visibility: 82, comfort: 90, battery: 72, weather: 64, usability: 90, value: 86 },
    ["360° reflective tube", "Phone + key carry"],
    ["Passive only"],
    "Night road reflective belt that replaces a separate vest for many runners.",
  ),
  rec(
    "rec-flipbelt-zippered-reflective-commute-running",
    "prod-flipbelt-zippered-reflective",
    "uc-commute-running",
    86,
    { visibility: 82, comfort: 90, battery: 72, weather: 66, usability: 92, value: 86 },
    ["Carry + visibility in one", "Zip valuables pocket"],
    ["Add LEDs for dark streets"],
    "Commute reflective accessory with everyday FlipBelt carry.",
  ),
  rec(
    "rec-flipbelt-zippered-reflective-winter-running",
    "prod-flipbelt-zippered-reflective",
    "uc-winter-running",
    82,
    { visibility: 80, comfort: 88, battery: 72, weather: 62, usability: 88, value: 84 },
    ["Works over layers", "360° reflective"],
    ["Less coverage than Reflect360 vest"],
    "Winter dusk reflective belt when you still need phone carry.",
  ),
  rec(
    "rec-flipbelt-zippered-reflective-beginners",
    "prod-flipbelt-zippered-reflective",
    "uc-beginners",
    88,
    { visibility: 82, comfort: 92, battery: 74, weather: 64, usability: 94, value: 88 },
    ["Familiar FlipBelt fit", "No charging"],
    ["Not illuminated"],
    "Beginner reflective accessory that doubles as phone belt.",
  ),
];
