import type { GearSetup } from "@/domain/editorial/types";
import { publishedMeta } from "@/content/config";

const pub = publishedMeta();

/** Running gear setups — Product IDs + roles; prices from Offers */
export const runningGearSetups: GearSetup[] = [
  {
    id: "setup-first-marathon",
    slug: "first-marathon-kit",
    title: "First Marathon Kit",
    sportId: "sport-running",
    disciplineId: "disc-running-racing",
    description:
      "Practical kit for first-marathon training — daily/long shoe, optional tempo/race option, GPS watch and optional HR strap. Essential vs optional roles marked on items.",
    useCaseIds: ["uc-first-marathon", "uc-long-runs", "uc-marathon"],
    budgetRange: { min: 400, max: 1000, currency: "EUR" },
    eyebrow: "GEAR KIT",
    goalLabel: "First marathon training",
    experienceLevel: "First-time marathoners",
    items: [
      {
        productId: "prod-novablast-6",
        role: "Daily / long-run shoe",
        roleLabel: "DAILY TRAINER",
        importance: "required",
        rationale:
          "Forgiving daily trainer for the bulk of marathon training mileage.",
        strengths: [
          "Soft daily ride for high mileage",
          "Strong long-run fit in our catalog",
          "Keeps plate shoes for race day only",
        ],
      },
      {
        productId: "prod-endorphin-speed-5",
        role: "Tempo / race option",
        roleLabel: "TEMPO SHOE",
        importance: "recommended",
        optional: true,
        rationale: "Useful faster session shoe once training volume is set.",
        strengths: [
          "Responsive for tempo work",
          "Optional until race pace sessions matter",
          "Bridges daily trainer and race shoe",
        ],
      },
      {
        productId: "prod-forerunner-570",
        role: "Training watch",
        roleLabel: "GPS WATCH",
        importance: "required",
        rationale: "GPS watch for pacing and training load during the build.",
        strengths: [
          "Reliable GPS for long runs",
          "Training features without flagship cost",
          "Works with optional chest strap",
        ],
      },
      {
        productId: "prod-hrm-pro-plus",
        role: "Heart rate strap",
        roleLabel: "HR STRAP",
        importance: "optional",
        optional: true,
        notes: "Useful if you distrust wrist optical on key sessions",
        rationale: "Optional chest strap when optical HR is unreliable.",
        strengths: [
          "Chest HR for key workouts",
          "Pairs with Garmin training watches",
          "Skip if wrist HR is trusted",
        ],
      },
      {
        productId: "prod-feetures-elite-light-cushion",
        role: "Race & training socks",
        roleLabel: "SOCKS",
        importance: "recommended",
        optional: true,
        rationale: "Anatomical sock for blister control on long days.",
        strengths: [
          "Light cushion for long runs",
          "Anatomical fit",
          "Useful on race day too",
        ],
      },
    ],
    ...pub,
  },
  {
    id: "setup-marathon-race-day",
    slug: "marathon-race-day-kit",
    slugAliases: ["marathon-race-day"],
    title: "Marathon Race-Day Kit",
    sportId: "sport-running",
    disciplineId: "disc-running-racing",
    description:
      "Everything you need for race day, selected to work together from start to finish.",
    useCaseIds: ["uc-marathon", "uc-pb"],
    budgetRange: { min: 350, max: 900, currency: "EUR" },
    eyebrow: "GEAR KIT",
    heroImageSrc: "/images/running/category/use-race.jpg",
    whyTitle: "Why a complete race-day kit?",
    whyReasons: [
      "Covers the core gear categories for race day",
      "Items selected for the same marathon race context",
      "Reduces gaps and unnecessary duplication",
      "Provides clear alternatives where needs differ",
    ],
    summaryFocus: [
      {
        title: "Performance focused",
        detail: "Light, fast and reliable",
      },
      {
        title: "Race-day ready",
        detail: "Built for marathon context",
      },
    ],
    curatedBy: "Kitletics running team",
    nextReviewAt: "2026-11-15T10:00:00.000Z",
    goalLabel: "Marathon race-day performance",
    experienceLevel: "All marathon runners",
    setupType: "editorial",
    finderToolSlug: "running-shoe-finder",
    howWeChooseHref: "/guides/how-to-choose-running-shoes",
    variantSetupIds: [
      "setup-first-marathon",
      "setup-half-marathon",
      "setup-beginner",
    ],
    relatedGuideIds: ["guide-shoe-rotation", "guide-choose-shoes"],
    relatedBestGuideIds: ["best-marathon-shoes", "best-race-shoes"],
    checklist: [
      "Race shoes broken in on shorter races or workouts",
      "Race apparel tested on a long run",
      "Nutrition plan confirmed (bring your own strategy)",
      "Weather and kit layers checked",
      "Race number / belt ready",
      "Watch charged",
    ],
    items: [
      {
        productId: "prod-vaporfly-4",
        role: "Race shoes",
        roleLabel: "RACE SHOES",
        importance: "required",
        rationale: "Our race-shoe pick for marathon road racing.",
        strengths: [
          "Lightweight plated race ride",
          "Strong marathon use-case fit",
          "Current generation in catalog",
        ],
        alternativeProductIds: ["prod-alphafly-3", "prod-adios-pro-4"],
      },
      {
        productId: "prod-forerunner-970",
        role: "GPS watch",
        roleLabel: "GPS WATCH",
        importance: "required",
        rationale:
          "Flagship GPS watch for race pacing, splits and course navigation.",
        strengths: [
          "Race pacing and lap tools",
          "Long battery for marathon day",
          "Maps and training depth when you want them",
        ],
        alternativeProductIds: ["prod-forerunner-570", "prod-coros-pace-pro"],
      },
      {
        productId: "prod-goodr-ogs",
        role: "Sunglasses",
        roleLabel: "SUNGLASSES",
        importance: "recommended",
        rationale:
          "Lightweight no-slip sunglasses for bright race conditions.",
        strengths: [
          "Secure fit for running",
          "Light enough for race day",
          "Skip in low-light or indoor starts if preferred",
        ],
        alternativeProductIds: ["prod-julbo-aerolite", "prod-oakley-encoder"],
      },
      {
        productId: "prod-asics-race-short",
        role: "Race apparel",
        roleLabel: "RACE APPAREL",
        importance: "required",
        rationale:
          "Light race short selected for warm-weather marathon conditions.",
        strengths: [
          "Split race cut",
          "Breathable fabric for race effort",
          "Test on a long run before race day",
        ],
        alternativeProductIds: ["prod-nike-stride-short", "prod-craft-adv-essence-short"],
      },
      {
        productId: "prod-feetures-elite-light-cushion",
        role: "Socks",
        roleLabel: "SOCKS",
        importance: "required",
        rationale: "Anatomical race sock aimed at blister control.",
        strengths: [
          "Light cushion for race distance",
          "Anatomical left/right fit",
          "Pair with broken-in race shoes",
        ],
        alternativeProductIds: ["prod-balega-hidden-comfort"],
      },
      {
        productId: "prod-spibelt-original",
        role: "Race belt",
        roleLabel: "RACE BELT",
        importance: "recommended",
        optional: true,
        rationale:
          "Minimal belt for gels and small race essentials you already trust.",
        strengths: [
          "Low-bounce carry for gels",
          "Keeps hands free",
          "Optional if you use shorts pockets only",
        ],
        alternativeProductIds: ["prod-flipbelt-classic", "prod-nathan-mirage"],
      },
      {
        productId: "prod-hrm-pro-plus",
        role: "Chest strap",
        roleLabel: "HR STRAP",
        importance: "optional",
        optional: true,
        notes: "Useful if you distrust wrist optical on race day",
        rationale:
          "Optional chest strap when you want more reliable race-day heart rate.",
        strengths: [
          "Chest HR accuracy when needed",
          "Pairs with Garmin race watches",
          "Skip if wrist HR is enough",
        ],
      },
    ],
    nextItems: [
      {
        productId: "prod-hrm-pro-plus",
        role: "Heart rate monitor",
        roleLabel: "HR MONITOR",
        contextLabel: "TRAINING / RECOVERY ADD-ONS",
        notes: "If you did not already include a chest strap in the core kit.",
      },
      {
        productId: "prod-ud-adventure-vest",
        role: "Hydration vest",
        roleLabel: "HYDRATION",
        contextLabel: "TRAINING / RECOVERY ADD-ONS",
        notes: "For long training runs — not typically race-day carry on road marathons.",
      },
      {
        productId: "prod-triggerpoint-grid",
        role: "Foam roller",
        roleLabel: "RECOVERY",
        contextLabel: "TRAINING / RECOVERY ADD-ONS",
      },
      {
        productId: "prod-cep-run-compression-sock",
        role: "Compression socks",
        roleLabel: "RECOVERY",
        contextLabel: "TRAINING / RECOVERY ADD-ONS",
        notes: "Recovery use — not required race-day carry.",
      },
    ],
    seoTitle: "Marathon Race-Day Gear Kit",
    seoDescription:
      "Curated marathon race-day gear kit: race shoes, GPS watch, apparel, socks and accessories — with roles, rationale and live regional prices.",
    ...pub,
  },
  {
    id: "setup-beginner",
    slug: "beginner-running-setup",
    title: "Beginner Running Setup",
    sportId: "sport-running",
    description:
      "Essentials-first starter kit: forgiving daily trainer, socks, optional watch and belt. Avoid overbuying race plates and max kits early.",
    useCaseIds: ["uc-beginners", "uc-first-5k"],
    budgetRange: { min: 150, max: 450, currency: "EUR" },
    eyebrow: "STARTER KIT",
    goalLabel: "Start running consistently",
    experienceLevel: "Beginners",
    items: [
      {
        productId: "prod-ghost-18",
        role: "Primary daily trainer",
        roleLabel: "DAILY TRAINER",
        importance: "required",
        rationale: "Forgiving daily shoe to start with.",
        strengths: [
          "Comfortable daily trainer",
          "Broad fit for new runners",
          "Avoids race-plate spend early",
        ],
      },
      {
        productId: "prod-feetures-elite-light-cushion",
        role: "Socks",
        roleLabel: "SOCKS",
        importance: "required",
        rationale: "Dedicated running sock for blister control.",
        strengths: [
          "Running-specific fit",
          "Light cushion",
          "Essential with new shoes",
        ],
      },
      {
        productId: "prod-forerunner-165",
        role: "GPS watch",
        roleLabel: "GPS WATCH",
        importance: "recommended",
        optional: true,
        rationale: "Entry GPS watch when you want paced runs.",
        strengths: [
          "Simple GPS tracking",
          "Lower cost than flagship watches",
          "Optional early on",
        ],
      },
      {
        productId: "prod-flipbelt-classic",
        role: "Phone belt",
        roleLabel: "BELT",
        importance: "optional",
        optional: true,
        rationale: "Optional phone carry for safety and music.",
        strengths: [
          "Hands-free phone carry",
          "Skip if pockets work",
          "Useful on solo runs",
        ],
      },
    ],
    ...pub,
  },
  {
    id: "setup-half-marathon",
    slug: "half-marathon-kit",
    title: "Half Marathon Kit",
    sportId: "sport-running",
    disciplineId: "disc-running-racing",
    description:
      "Daily trainer plus a faster option and GPS watch for half-marathon training blocks.",
    useCaseIds: ["uc-half", "uc-first-half", "uc-long-runs"],
    budgetRange: { min: 350, max: 850, currency: "EUR" },
    eyebrow: "GEAR KIT",
    goalLabel: "Half marathon training",
    experienceLevel: "Intermediate",
    items: [
      {
        productId: "prod-pegasus-42",
        role: "Daily trainer",
        roleLabel: "DAILY TRAINER",
        importance: "required",
        rationale: "Reliable daily trainer for half-marathon blocks.",
        strengths: [
          "Versatile daily miles",
          "Works for most half training weeks",
          "Pairs with optional faster shoe",
        ],
      },
      {
        productId: "prod-endorphin-speed-5",
        role: "Tempo / race shoe",
        roleLabel: "TEMPO SHOE",
        importance: "recommended",
        optional: true,
        rationale: "Faster option for workouts and race day.",
        strengths: [
          "Responsive tempo ride",
          "Useful race-day shoe for many halves",
          "Optional if budget is tight",
        ],
      },
      {
        productId: "prod-forerunner-570",
        role: "GPS watch",
        roleLabel: "GPS WATCH",
        importance: "required",
        rationale: "GPS watch for pacing through the half build.",
        strengths: [
          "Training and race pacing",
          "Solid mid-tier Garmin option",
          "Covers key half-marathon sessions",
        ],
      },
    ],
    ...pub,
  },
  {
    id: "setup-trail-starter",
    slug: "trail-running-starter-kit",
    title: "Trail Running Starter Kit",
    sportId: "sport-running",
    disciplineId: "disc-running-trail",
    description:
      "Starter trail kit: trail shoes, hydration vest, optional watch and headlamp. Environment varies — treat this as a starting template, not universal mandatory kit.",
    useCaseIds: ["uc-trail-training", "uc-long-runs"],
    budgetRange: { min: 350, max: 900, currency: "EUR" },
    eyebrow: "STARTER KIT",
    goalLabel: "Trail running starter",
    experienceLevel: "Beginner to intermediate trail",
    items: [
      {
        productId: "prod-speedgoat-6",
        role: "Trail shoes",
        roleLabel: "TRAIL SHOES",
        importance: "required",
        rationale: "Aggressive trail shoe for mixed terrain starts.",
        strengths: [
          "Trail grip for mixed terrain",
          "Cushion for longer trail days",
          "Core footwear role",
        ],
      },
      {
        productId: "prod-adv-skin-12",
        role: "Hydration vest",
        roleLabel: "HYDRATION VEST",
        importance: "required",
        rationale: "Vest for water and layers on unsupported trails.",
        strengths: [
          "Hands-free hydration",
          "Storage for layers and fuel",
          "Core trail carry role",
        ],
      },
      {
        productId: "prod-soft-flask-500",
        role: "Soft flasks",
        roleLabel: "FLASKS",
        importance: "recommended",
        optional: true,
        rationale: "Soft flasks that pair with the vest.",
        strengths: [
          "Compatible vest hydration",
          "Easy on-trail access",
          "Optional if vest includes flasks",
        ],
      },
      {
        productId: "prod-coros-pace-pro",
        role: "GPS watch",
        roleLabel: "GPS WATCH",
        importance: "recommended",
        optional: true,
        rationale: "GPS watch with strong battery for trail days.",
        strengths: [
          "Long battery for trail",
          "Navigation tools",
          "Optional early on",
        ],
      },
      {
        productId: "prod-petzl-swift-rl",
        role: "Headlamp",
        roleLabel: "HEADLAMP",
        importance: "optional",
        optional: true,
        rationale: "Headlamp when dark starts or finishes are likely.",
        strengths: [
          "Dark-condition safety",
          "Skip for daytime-only trails",
          "Condition-dependent",
        ],
      },
    ],
    ...pub,
  },
];
