/**
 * Suitability scores for running sunglasses wave2.
 * Factors: coverage, optics, fit, stability, light-versatility, value.
 */
import type { Recommendation } from "@/domain/recommendations/types";

const ev = ["ev-catalog-editorial"] as const;

const sgFactors = (scores: {
  coverage: number;
  optics: number;
  fit: number;
  stability: number;
  lightVersatility: number;
  value: number;
}) => [
  {
    key: "coverage",
    label: "Coverage",
    score: scores.coverage,
    weight: 0.18,
    explanation: "Peripheral and cheek/brow shelter from sun, wind and debris.",
  },
  {
    key: "optics",
    label: "Optics",
    score: scores.optics,
    weight: 0.18,
    explanation: "Contrast, clarity and glare control for running surfaces.",
  },
  {
    key: "fit",
    label: "Fit",
    score: scores.fit,
    weight: 0.16,
    explanation: "Face size match, nose pad comfort and pressure points.",
  },
  {
    key: "stability",
    label: "Stability",
    score: scores.stability,
    weight: 0.16,
    explanation: "Bounce and slip resistance when sweating at race pace.",
  },
  {
    key: "light-versatility",
    label: "Light versatility",
    score: scores.lightVersatility,
    weight: 0.16,
    explanation: "Photochromic or interchangeable options across light changes.",
  },
  {
    key: "value",
    label: "Value",
    score: scores.value,
    weight: 0.16,
    explanation: "Performance vs typical street price.",
  },
];

export const runningSunglassesRecommendations: Recommendation[] = [
  // ── Radar EV Path ────────────────────────────────────────────────────────
  {
    id: "rec-oakley-radar-ev-path-bright-sun",
    productId: "prod-oakley-radar-ev-path",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 92,
    factors: sgFactors({
      coverage: 90,
      optics: 94,
      fit: 88,
      stability: 92,
      lightVersatility: 86,
      value: 72,
    }),
    strengths: ["Prizm contrast in hard sun", "Secure Unobtainium grip"],
    compromises: ["Premium once spare lenses add up"],
    explanation: "Top interchangeable wrap for bright road and open trail glare.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-oakley-radar-ev-path-daily-training",
    productId: "prod-oakley-radar-ev-path",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 88,
    factors: sgFactors({
      coverage: 88,
      optics: 92,
      fit: 88,
      stability: 90,
      lightVersatility: 84,
      value: 70,
    }),
    strengths: ["Daily sport retention", "Lens ecosystem for conditions"],
    compromises: ["Overbuilt vs Goodr for easy miles"],
    explanation: "Excellent daily outdoor trainer when you want real sport optics.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-oakley-radar-ev-path-marathon",
    productId: "prod-oakley-radar-ev-path",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 90,
    factors: sgFactors({
      coverage: 90,
      optics: 94,
      fit: 86,
      stability: 92,
      lightVersatility: 82,
      value: 72,
    }),
    strengths: ["All-day grip", "Bright-road Prizm clarity"],
    compromises: ["Fixed sunny tint unless you pack a spare"],
    explanation: "Race-day wrap confidence for sunny marathons.",
    evidenceIds: [...ev],
  },

  // ── Sutro Lite ───────────────────────────────────────────────────────────
  {
    id: "rec-oakley-sutro-lite-bright-sun",
    productId: "prod-oakley-sutro-lite",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 93,
    factors: sgFactors({
      coverage: 96,
      optics: 92,
      fit: 84,
      stability: 88,
      lightVersatility: 62,
      value: 70,
    }),
    strengths: ["Huge shield coverage", "Open-rim airflow"],
    compromises: ["Fixed lens; large on small faces"],
    explanation: "Best-in-wave shield coverage for hard sun road days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-oakley-sutro-lite-marathon",
    productId: "prod-oakley-sutro-lite",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 90,
    factors: sgFactors({
      coverage: 95,
      optics: 92,
      fit: 82,
      stability: 88,
      lightVersatility: 60,
      value: 70,
    }),
    strengths: ["Glare shelter for long road races", "Ventilated vs full Sutro"],
    compromises: ["Not for mixed canopy trail"],
    explanation: "Strong marathon pick when sun and wind are the main threats.",
    evidenceIds: [...ev],
  },

  // ── Kato ─────────────────────────────────────────────────────────────────
  {
    id: "rec-oakley-kato-bright-sun",
    productId: "prod-oakley-kato",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 91,
    factors: sgFactors({
      coverage: 94,
      optics: 94,
      fit: 86,
      stability: 90,
      lightVersatility: 58,
      value: 68,
    }),
    strengths: ["Panoramic race FOV", "Prizm road contrast"],
    compromises: ["Bold look; no lens interchange"],
    explanation: "Race-shield optics for bright road efforts.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-oakley-kato-marathon",
    productId: "prod-oakley-kato",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 89,
    factors: sgFactors({
      coverage: 93,
      optics: 94,
      fit: 84,
      stability: 90,
      lightVersatility: 56,
      value: 68,
    }),
    strengths: ["Stable nosepiece at race effort", "Wide FOV"],
    compromises: ["Premium price for a single-tint shield"],
    explanation: "Elite road-race shield when coverage and clarity matter most.",
    evidenceIds: [...ev],
  },

  // ── Flak 2.0 XL ──────────────────────────────────────────────────────────
  {
    id: "rec-oakley-flak-2xl-bright-sun",
    productId: "prod-oakley-flak-2xl",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 88,
    factors: sgFactors({
      coverage: 90,
      optics: 90,
      fit: 92,
      stability: 88,
      lightVersatility: 84,
      value: 74,
    }),
    strengths: ["XL fit for larger faces", "Interchangeable Prizm"],
    compromises: ["Wide on smaller heads"],
    explanation: "Go-to large-face wrap for sunny road training.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-oakley-flak-2xl-daily-training",
    productId: "prod-oakley-flak-2xl",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 86,
    factors: sgFactors({
      coverage: 88,
      optics: 90,
      fit: 90,
      stability: 86,
      lightVersatility: 82,
      value: 74,
    }),
    strengths: ["Comfortable daily XL coverage", "Lens swap flexibility"],
    compromises: ["Still Oakley money vs Tifosi"],
    explanation: "Daily outdoor miles for runners who need a larger wrap.",
    evidenceIds: [...ev],
  },

  // ── Smith Shift MAG ──────────────────────────────────────────────────────
  {
    id: "rec-smith-shift-mag-bright-sun",
    productId: "prod-smith-shift-mag",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 90,
    factors: sgFactors({
      coverage: 88,
      optics: 92,
      fit: 88,
      stability: 90,
      lightVersatility: 90,
      value: 76,
    }),
    strengths: ["ChromaPop contrast", "Fast MAG swaps"],
    compromises: ["Photochromic MAG lens is usually an upgrade"],
    explanation: "Premium wrap for bright days with real lens-change workflow.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smith-shift-mag-mixed-light",
    productId: "prod-smith-shift-mag",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 91,
    factors: sgFactors({
      coverage: 86,
      optics: 90,
      fit: 88,
      stability: 88,
      lightVersatility: 94,
      value: 76,
    }),
    strengths: ["MAG + optional photochromic path", "Clear spare in many kits"],
    compromises: ["Still carry/swap unless photochromic SKU"],
    explanation: "Strong mixed-light road/trail pick when MAG versatility matters.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smith-shift-mag-marathon",
    productId: "prod-smith-shift-mag",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 87,
    factors: sgFactors({
      coverage: 86,
      optics: 92,
      fit: 88,
      stability: 90,
      lightVersatility: 84,
      value: 74,
    }),
    strengths: ["Race retention", "ChromaPop road detail"],
    compromises: ["Less shield coverage than Sutro Lite"],
    explanation: "Marathon-capable wrap with optics and stability to match.",
    evidenceIds: [...ev],
  },

  // ── Smith Attack MAG ─────────────────────────────────────────────────────
  {
    id: "rec-smith-attack-mag-trail-training",
    productId: "prod-smith-attack-mag",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 92,
    factors: sgFactors({
      coverage: 94,
      optics: 90,
      fit: 86,
      stability: 88,
      lightVersatility: 92,
      value: 74,
    }),
    strengths: ["Max trail coverage", "Ventilated MAG optics"],
    compromises: ["Trail-shaped more than casual road"],
    explanation: "Trail-first MAG wrap for technical training days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smith-attack-mag-mixed-light",
    productId: "prod-smith-attack-mag",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 93,
    factors: sgFactors({
      coverage: 92,
      optics: 90,
      fit: 86,
      stability: 86,
      lightVersatility: 96,
      value: 74,
    }),
    strengths: ["Bright + low-light MAG kit", "Photochromic SKUs available"],
    compromises: ["Premium vs Julbo Reactiv one-lens simplicity"],
    explanation: "Excellent canopy-to-open light tool with MAG or photochromic paths.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-smith-attack-mag-ultra",
    productId: "prod-smith-attack-mag",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 88,
    factors: sgFactors({
      coverage: 94,
      optics: 88,
      fit: 84,
      stability: 86,
      lightVersatility: 92,
      value: 72,
    }),
    strengths: ["Debris/wind shelter", "Lens versatility over long days"],
    compromises: ["Heavier package than Julbo Rush class"],
    explanation: "Ultra training coverage when light keeps changing on trail.",
    evidenceIds: [...ev],
  },

  // ── Julbo Ultimate ────────────────────────────────────────────────────────
  {
    id: "rec-julbo-ultimate-mixed-light",
    productId: "prod-julbo-ultimate",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 95,
    factors: sgFactors({
      coverage: 90,
      optics: 90,
      fit: 86,
      stability: 86,
      lightVersatility: 98,
      value: 78,
    }),
    strengths: ["Reactiv auto-tint", "Trail wrap coverage"],
    compromises: ["Photochromic lag vs instant spare swap"],
    explanation: "Best one-lens mixed-light trail answer in this wave.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-julbo-ultimate-trail-training",
    productId: "prod-julbo-ultimate",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 93,
    factors: sgFactors({
      coverage: 92,
      optics: 90,
      fit: 86,
      stability: 86,
      lightVersatility: 96,
      value: 78,
    }),
    strengths: ["Mountain coverage", "No spare-lens juggling"],
    compromises: ["Less race-shield FOV than Kato"],
    explanation: "Trail-day default when shade and alpine glare trade places.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-julbo-ultimate-ultra",
    productId: "prod-julbo-ultimate",
    sportId: "sport-running",
    useCaseId: "uc-ultra",
    score: 92,
    factors: sgFactors({
      coverage: 90,
      optics: 88,
      fit: 84,
      stability: 84,
      lightVersatility: 96,
      value: 78,
    }),
    strengths: ["All-day Reactiv range", "Light trail frame"],
    compromises: ["Regional Reactiv pricing varies"],
    explanation: "Ultra kit pick when you want photochromic set-and-forget.",
    evidenceIds: [...ev],
  },

  // ── Julbo Rush ───────────────────────────────────────────────────────────
  {
    id: "rec-julbo-rush-trail-training",
    productId: "prod-julbo-rush",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 88,
    factors: sgFactors({
      coverage: 86,
      optics: 88,
      fit: 88,
      stability: 84,
      lightVersatility: 94,
      value: 80,
    }),
    strengths: ["Compact Reactiv wrap", "Good trail ventilation"],
    compromises: ["Less panoramic than Ultimate / Attack"],
    explanation: "Tighter trail wrap when Ultimate feels oversized.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-julbo-rush-mixed-light",
    productId: "prod-julbo-rush",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 90,
    factors: sgFactors({
      coverage: 84,
      optics: 88,
      fit: 88,
      stability: 84,
      lightVersatility: 96,
      value: 80,
    }),
    strengths: ["Reactiv versatility", "Lighter trail package"],
    compromises: ["Not a bright-only race shield"],
    explanation: "Mixed-light trail tool with Reactiv convenience.",
    evidenceIds: [...ev],
  },

  // ── Rudy Cutline ─────────────────────────────────────────────────────────
  {
    id: "rec-rudy-cutline-bright-sun",
    productId: "prod-rudy-cutline",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 88,
    factors: sgFactors({
      coverage: 92,
      optics: 88,
      fit: 88,
      stability: 88,
      lightVersatility: 86,
      value: 78,
    }),
    strengths: ["Race shield FOV", "Quick lens swaps"],
    compromises: ["Heavier than Kato class"],
    explanation: "Bright-road race shield with adjustable fit hardware.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-rudy-cutline-marathon",
    productId: "prod-rudy-cutline",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 86,
    factors: sgFactors({
      coverage: 92,
      optics: 88,
      fit: 86,
      stability: 88,
      lightVersatility: 82,
      value: 78,
    }),
    strengths: ["Adjustable race fit", "Shield glare control"],
    compromises: ["ImpactX photochromic is a SKU choice"],
    explanation: "Marathon/road race shield alternative to Kato and S3.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-rudy-cutline-mixed-light",
    productId: "prod-rudy-cutline",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 84,
    factors: sgFactors({
      coverage: 90,
      optics: 86,
      fit: 86,
      stability: 86,
      lightVersatility: 90,
      value: 78,
    }),
    strengths: ["Interchange + ImpactX options", "Adjustable temples/nose"],
    compromises: ["Base dark lens alone is less versatile"],
    explanation: "Mixed light works when ImpactX or spare lenses are in the kit.",
    evidenceIds: [...ev],
  },

  // ── 100% S3 ──────────────────────────────────────────────────────────────
  {
    id: "rec-100-s3-bright-sun",
    productId: "prod-100-s3",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 87,
    factors: sgFactors({
      coverage: 92,
      optics: 88,
      fit: 84,
      stability: 86,
      lightVersatility: 78,
      value: 82,
    }),
    strengths: ["HiPER race contrast", "Spare lens kits common"],
    compromises: ["Fingerprint-prone swaps vs MAG"],
    explanation: "Value-leaning race shield for hard sun road days.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-100-s3-marathon",
    productId: "prod-100-s3",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 85,
    factors: sgFactors({
      coverage: 90,
      optics: 88,
      fit: 84,
      stability: 86,
      lightVersatility: 74,
      value: 82,
    }),
    strengths: ["Shield coverage under Kato money", "Secure race fit"],
    compromises: ["Not a trail photochromic tool"],
    explanation: "Solid marathon shield when budget beats Oakley race pricing.",
    evidenceIds: [...ev],
  },

  // ── ROKA Phantom Air ─────────────────────────────────────────────────────
  {
    id: "rec-roka-phantom-air-daily-training",
    productId: "prod-roka-phantom-air",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 86,
    factors: sgFactors({
      coverage: 78,
      optics: 88,
      fit: 88,
      stability: 90,
      lightVersatility: 64,
      value: 72,
    }),
    strengths: ["Ultralight comfort", "Sweat-grippy contact points"],
    compromises: ["Less coverage than Sutro / Attack"],
    explanation: "Light daily performance wrap when weight and grip come first.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-roka-phantom-air-marathon",
    productId: "prod-roka-phantom-air",
    sportId: "sport-running",
    useCaseId: "uc-marathon",
    score: 84,
    factors: sgFactors({
      coverage: 76,
      optics: 88,
      fit: 86,
      stability: 90,
      lightVersatility: 62,
      value: 70,
    }),
    strengths: ["All-day light frame", "Stable when sweating"],
    compromises: ["Want more cheek coverage in desert sun"],
    explanation: "Marathon option for runners who hate heavy shields.",
    evidenceIds: [...ev],
  },

  // ── Tifosi Rail ──────────────────────────────────────────────────────────
  {
    id: "rec-tifosi-rail-daily-training",
    productId: "prod-tifosi-rail",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 88,
    factors: sgFactors({
      coverage: 88,
      optics: 80,
      fit: 84,
      stability: 78,
      lightVersatility: 90,
      value: 94,
    }),
    strengths: ["Interchange kit value", "High coverage wrap"],
    compromises: ["Retention below Oakley / Smith"],
    explanation: "Best value daily wrap when you want spare/Fototec lenses.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tifosi-rail-bright-sun",
    productId: "prod-tifosi-rail",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 86,
    factors: sgFactors({
      coverage: 90,
      optics: 80,
      fit: 84,
      stability: 78,
      lightVersatility: 86,
      value: 94,
    }),
    strengths: ["Dark interchange tints", "Coverage near premium wraps"],
    compromises: ["Optics/grip not Oakley-class"],
    explanation: "Bright-sun performance at a fraction of Radar EV pricing.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tifosi-rail-mixed-light",
    productId: "prod-tifosi-rail",
    sportId: "sport-running",
    useCaseId: "uc-mixed-light",
    score: 87,
    factors: sgFactors({
      coverage: 86,
      optics: 78,
      fit: 84,
      stability: 76,
      lightVersatility: 94,
      value: 94,
    }),
    strengths: ["Fototec photochromic SKUs", "Multi-lens kits"],
    compromises: ["Race-pace stability trails premium peers"],
    explanation: "Value mixed-light answer via Fototec or packed spares.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tifosi-rail-trail-training",
    productId: "prod-tifosi-rail",
    sportId: "sport-running",
    useCaseId: "uc-trail-training",
    score: 82,
    factors: sgFactors({
      coverage: 88,
      optics: 78,
      fit: 82,
      stability: 74,
      lightVersatility: 90,
      value: 92,
    }),
    strengths: ["Coverage + lens options on a budget"],
    compromises: ["Bounce control can lag on tech trail"],
    explanation: "Capable trail budget wrap; Julbo still wins photochromic feel.",
    evidenceIds: [...ev],
  },

  // ── Tifosi Vogel ─────────────────────────────────────────────────────────
  {
    id: "rec-tifosi-vogel-daily-training",
    productId: "prod-tifosi-vogel",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 80,
    factors: sgFactors({
      coverage: 70,
      optics: 74,
      fit: 84,
      stability: 76,
      lightVersatility: 55,
      value: 90,
    }),
    strengths: ["Light everyday comfort", "Strong value"],
    compromises: ["Not interchangeable or race-shield deep"],
    explanation: "Simple daily outdoor trainer below Rail complexity.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-tifosi-vogel-bright-sun",
    productId: "prod-tifosi-vogel",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 74,
    factors: sgFactors({
      coverage: 68,
      optics: 74,
      fit: 82,
      stability: 74,
      lightVersatility: 52,
      value: 90,
    }),
    strengths: ["UV400 at low cost"],
    compromises: ["Limited coverage vs wraps/shields"],
    explanation: "Fine for casual sunny easy runs; step up for hard glare races.",
    evidenceIds: [...ev],
  },

  // ── Goodr Circle Gs ──────────────────────────────────────────────────────
  {
    id: "rec-goodr-circle-gs-daily-training",
    productId: "prod-goodr-circle-gs",
    sportId: "sport-running",
    useCaseId: "uc-daily-training",
    score: 82,
    factors: sgFactors({
      coverage: 58,
      optics: 72,
      fit: 80,
      stability: 78,
      lightVersatility: 48,
      value: 96,
    }),
    strengths: ["Polarized value", "No-slip coating", "Very light"],
    compromises: ["Low coverage vs sport wraps"],
    explanation: "Everyday easy-mile polarized pick when style and price win.",
    evidenceIds: [...ev],
  },
  {
    id: "rec-goodr-circle-gs-bright-sun",
    productId: "prod-goodr-circle-gs",
    sportId: "sport-running",
    useCaseId: "uc-bright-sun",
    score: 72,
    factors: sgFactors({
      coverage: 55,
      optics: 74,
      fit: 78,
      stability: 76,
      lightVersatility: 45,
      value: 96,
    }),
    strengths: ["Polarized glare cut for the money"],
    compromises: ["Round frame leaves cheeks/brows open"],
    explanation: "Budget bright-day casual runner; not a marathon shield.",
    evidenceIds: [...ev],
  },
];
