import type { ProductFamily } from "@/domain/products/types";

/**
 * Running sunglasses families for wave 2 (performance wraps, race shields,
 * trail photochromics, everyday value). Gear-wave1 Encoder / OGs / Aerolite
 * stay outside these family rows until a later merge.
 */
export const runningSunglassesFamilies: ProductFamily[] = [
  {
    id: "fam-oakley-radar-ev",
    brandId: "brand-oakley",
    name: "Radar EV",
    slug: "oakley-radar-ev",
    categoryId: "cat-sunglasses",
    description: "Oakley Radar EV interchangeable performance wraps.",
    productIds: ["prod-oakley-radar-ev-path"],
  },
  {
    id: "fam-oakley-sutro",
    brandId: "brand-oakley",
    name: "Sutro",
    slug: "oakley-sutro",
    categoryId: "cat-sunglasses",
    description: "Oakley Sutro / Sutro Lite shield-coverage sport sunglasses.",
    productIds: ["prod-oakley-sutro-lite"],
  },
  {
    id: "fam-oakley-kato",
    brandId: "brand-oakley",
    name: "Kato",
    slug: "oakley-kato",
    categoryId: "cat-sunglasses",
    description: "Oakley Kato frameless race shields.",
    productIds: ["prod-oakley-kato"],
  },
  {
    id: "fam-oakley-flak",
    brandId: "brand-oakley",
    name: "Flak",
    slug: "oakley-flak",
    categoryId: "cat-sunglasses",
    description: "Oakley Flak performance wraps including Flak 2.0 XL.",
    productIds: ["prod-oakley-flak-2xl"],
  },
  {
    id: "fam-smith-shift-mag",
    brandId: "brand-smith",
    name: "Shift MAG",
    slug: "smith-shift-mag",
    categoryId: "cat-sunglasses",
    description: "Smith Shift MAG magnetic interchangeable sport sunglasses.",
    productIds: ["prod-smith-shift-mag"],
  },
  {
    id: "fam-smith-attack-mag",
    brandId: "brand-smith",
    name: "Attack MAG",
    slug: "smith-attack-mag",
    categoryId: "cat-sunglasses",
    description: "Smith Attack MAG trail-coverage magnetic sunglasses.",
    productIds: ["prod-smith-attack-mag"],
  },
  {
    id: "fam-julbo-ultimate",
    brandId: "brand-julbo",
    name: "Ultimate",
    slug: "julbo-ultimate",
    categoryId: "cat-sunglasses",
    description: "Julbo Ultimate trail wraps with Reactiv photochromic options.",
    productIds: ["prod-julbo-ultimate"],
  },
  {
    id: "fam-julbo-rush",
    brandId: "brand-julbo",
    name: "Rush",
    slug: "julbo-rush",
    categoryId: "cat-sunglasses",
    description: "Julbo Rush compact trail sunglasses.",
    productIds: ["prod-julbo-rush"],
  },
  {
    id: "fam-rudy-cutline",
    brandId: "brand-rudy-project",
    name: "Cutline",
    slug: "rudy-project-cutline",
    categoryId: "cat-sunglasses",
    description: "Rudy Project Cutline race shields.",
    productIds: ["prod-rudy-cutline"],
  },
  {
    id: "fam-100-s3",
    brandId: "brand-100percent",
    name: "S3",
    slug: "100-percent-s3",
    categoryId: "cat-sunglasses",
    description: "100% S3 race shields with HiPER optics.",
    productIds: ["prod-100-s3"],
  },
  {
    id: "fam-roka-phantom-air",
    brandId: "brand-roka",
    name: "Phantom Air",
    slug: "roka-phantom-air",
    categoryId: "cat-sunglasses",
    description: "ROKA Phantom Air ultralight performance wraps.",
    productIds: ["prod-roka-phantom-air"],
  },
  {
    id: "fam-tifosi-rail",
    brandId: "brand-tifosi",
    name: "Rail",
    slug: "tifosi-rail",
    categoryId: "cat-sunglasses",
    description: "Tifosi Rail value interchangeable wraps.",
    productIds: ["prod-tifosi-rail"],
  },
  {
    id: "fam-tifosi-vogel",
    brandId: "brand-tifosi",
    name: "Vogel",
    slug: "tifosi-vogel",
    categoryId: "cat-sunglasses",
    description: "Tifosi Vogel everyday value sport sunglasses.",
    productIds: ["prod-tifosi-vogel"],
  },
  {
    id: "fam-goodr-circle-gs",
    brandId: "brand-goodr",
    name: "Circle Gs",
    slug: "goodr-circle-gs",
    categoryId: "cat-sunglasses",
    description: "Goodr Circle Gs polarized everyday running sunglasses.",
    productIds: ["prod-goodr-circle-gs"],
  },
];
