import type { SpecificationDefinition } from "@/domain/products/types";
import { fitnessSpecificationDefinitions } from "@/content/fitness";

function def(
  partial: Omit<SpecificationDefinition, "comparisonPriority"> & {
    comparisonPriority?: number;
  },
): SpecificationDefinition {
  return {
    comparisonPriority: 50,
    ...partial,
  };
}

export const runningShoeSpecs: SpecificationDefinition[] = [
  def({ id: "spec-shoe-weight", categoryId: "cat-running-shoes", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-heel-stack", categoryId: "cat-running-shoes", key: "heelStack", label: "Heel Stack", type: "measurement", unit: "mm", comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-forefoot-stack", categoryId: "cat-running-shoes", key: "forefootStack", label: "Forefoot Stack", type: "measurement", unit: "mm", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-drop", categoryId: "cat-running-shoes", key: "drop", label: "Drop", type: "measurement", unit: "mm", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-cushion-level", categoryId: "cat-running-shoes", key: "cushionLevel", label: "Cushion Level", type: "enum", enumValues: ["minimal", "low", "medium", "high", "maximum"], comparisonPriority: 92, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-cushion-feel", categoryId: "cat-running-shoes", key: "cushionFeel", label: "Cushion Feel", type: "enum", enumValues: ["firm", "balanced", "soft", "plush"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-stability", categoryId: "cat-running-shoes", key: "stability", label: "Stability", type: "enum", enumValues: ["neutral", "mild-stability", "stability", "maximum-stability"], comparisonPriority: 91, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-ride", categoryId: "cat-running-shoes", key: "rideCharacter", label: "Ride Character", type: "enum", enumValues: ["smooth", "rockered", "responsive", "protective"], comparisonPriority: 60, finderRelevant: true, filterable: false }),
  def({ id: "spec-shoe-energy", categoryId: "cat-running-shoes", key: "energyReturn", label: "Energy Return", type: "enum", enumValues: ["low", "moderate", "high", "very-high"], comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-flex", categoryId: "cat-running-shoes", key: "flexibility", label: "Flexibility", type: "enum", enumValues: ["stiff", "moderate", "flexible"], comparisonPriority: 55, finderRelevant: false, filterable: true }),
  def({ id: "spec-shoe-upper", categoryId: "cat-running-shoes", key: "upper", label: "Upper", type: "string", comparisonPriority: 30, finderRelevant: false, filterable: false }),
  def({ id: "spec-shoe-midsole", categoryId: "cat-running-shoes", key: "midsole", label: "Midsole", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-shoe-outsole", categoryId: "cat-running-shoes", key: "outsole", label: "Outsole", type: "string", comparisonPriority: 35, finderRelevant: false, filterable: false }),
  def({ id: "spec-shoe-plate", categoryId: "cat-running-shoes", key: "plate", label: "Plate", type: "boolean", comparisonPriority: 86, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-plate-material", categoryId: "cat-running-shoes", key: "plateMaterial", label: "Plate Material", type: "enum", enumValues: ["none", "nylon", "carbon", "composite"], comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-terrain", categoryId: "cat-running-shoes", key: "terrain", label: "Terrain", type: "multi-enum", enumValues: ["road", "track", "trail", "treadmill", "mixed"], comparisonPriority: 84, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-width", categoryId: "cat-running-shoes", key: "widthOptions", label: "Width Options", type: "multi-enum", enumValues: ["narrow", "standard", "wide", "extra-wide"], comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-arch", categoryId: "cat-running-shoes", key: "archSupport", label: "Arch Support", type: "enum", enumValues: ["low", "medium", "high"], comparisonPriority: 50, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-grip", categoryId: "cat-running-shoes", key: "grip", label: "Grip", type: "enum", enumValues: ["road", "light-trail", "aggressive-trail"], comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-durability", categoryId: "cat-running-shoes", key: "durability", label: "Durability", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 52, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-breathability", categoryId: "cat-running-shoes", key: "breathability", label: "Breathability", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 45, finderRelevant: false, filterable: true }),
  def({ id: "spec-shoe-race-legal", categoryId: "cat-running-shoes", key: "raceLegal", label: "Race Legal", type: "boolean", comparisonPriority: 48, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-pace", categoryId: "cat-running-shoes", key: "recommendedPaceRange", label: "Recommended Pace Range", type: "range", unit: "min/km", comparisonPriority: 72, finderRelevant: true, filterable: false }),
  def({ id: "spec-shoe-distance", categoryId: "cat-running-shoes", key: "recommendedDistance", label: "Recommended Distance", type: "multi-enum", enumValues: ["5k", "10k", "half", "marathon", "ultra", "daily"], comparisonPriority: 74, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-runner-weight", categoryId: "cat-running-shoes", key: "recommendedRunnerWeightRange", label: "Recommended Runner Weight Range", type: "range", unit: "kg", comparisonPriority: 68, finderRelevant: true, filterable: false }),
  def({ id: "spec-shoe-training-types", categoryId: "cat-running-shoes", key: "trainingTypes", label: "Training Types", type: "multi-enum", enumValues: ["easy", "long", "tempo", "intervals", "race", "recovery"], comparisonPriority: 76, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-surface", categoryId: "cat-running-shoes", key: "surface", label: "Surface", type: "multi-enum", enumValues: ["asphalt", "track", "trail", "treadmill", "mixed"], comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-shoe-weather", categoryId: "cat-running-shoes", key: "weatherSuitability", label: "Weather Suitability", type: "multi-enum", enumValues: ["dry", "wet", "cold", "hot", "all-season"], comparisonPriority: 42, finderRelevant: false, filterable: true }),
  def({ id: "spec-shoe-gender", categoryId: "cat-running-shoes", key: "genderFit", label: "Fit / Sizing", type: "multi-enum", enumValues: ["men", "women", "unisex"], comparisonPriority: 88, finderRelevant: true, filterable: true }),
];

export const gpsWatchSpecs: SpecificationDefinition[] = [
  def({ id: "spec-watch-weight", categoryId: "cat-gps-watches", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-display-type", categoryId: "cat-gps-watches", key: "displayType", label: "Display Type", type: "enum", enumValues: ["mip", "amoled", "lcd", "retina"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-display-size", categoryId: "cat-gps-watches", key: "displaySize", label: "Display Size", type: "measurement", unit: "mm", comparisonPriority: 60, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-case-size", categoryId: "cat-gps-watches", key: "caseSizeMm", label: "Case Size", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-touch", categoryId: "cat-gps-watches", key: "touchscreen", label: "Touchscreen", type: "boolean", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-buttons", categoryId: "cat-gps-watches", key: "physicalButtons", label: "Physical Buttons", type: "boolean", comparisonPriority: 52, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-battery-smart", categoryId: "cat-gps-watches", key: "batterySmartwatch", label: "Battery Smartwatch", type: "measurement", unit: "days", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-battery-gps", categoryId: "cat-gps-watches", key: "batteryGps", label: "Battery GPS", type: "measurement", unit: "hours", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-battery-multiband", categoryId: "cat-gps-watches", key: "batteryMultiBand", label: "Battery Multi-band GPS", type: "measurement", unit: "hours", comparisonPriority: 86, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-solar", categoryId: "cat-gps-watches", key: "solar", label: "Solar Charging", type: "boolean", comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-multiband", categoryId: "cat-gps-watches", key: "multiBandGps", label: "Multi-band GPS", type: "boolean", comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-gnss", categoryId: "cat-gps-watches", key: "gnssSystems", label: "GNSS Systems", type: "multi-enum", enumValues: ["gps", "glonass", "galileo", "beidou", "qzss"], comparisonPriority: 74, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-maps", categoryId: "cat-gps-watches", key: "maps", label: "Maps", type: "boolean", comparisonPriority: 84, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-offline-maps", categoryId: "cat-gps-watches", key: "offlineMaps", label: "Offline Maps", type: "boolean", comparisonPriority: 83, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-nav", categoryId: "cat-gps-watches", key: "navigation", label: "Navigation", type: "boolean", comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-music", categoryId: "cat-gps-watches", key: "music", label: "Music", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-payments", categoryId: "cat-gps-watches", key: "payments", label: "Payments", type: "boolean", comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-wifi", categoryId: "cat-gps-watches", key: "wifi", label: "Wi-Fi", type: "boolean", comparisonPriority: 48, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-lte", categoryId: "cat-gps-watches", key: "lte", label: "LTE / Cellular", type: "boolean", comparisonPriority: 54, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-hr", categoryId: "cat-gps-watches", key: "heartRate", label: "Heart Rate", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-ecg", categoryId: "cat-gps-watches", key: "ecg", label: "ECG", type: "boolean", comparisonPriority: 55, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-spo2", categoryId: "cat-gps-watches", key: "spo2", label: "SpO2", type: "boolean", comparisonPriority: 50, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-baro", categoryId: "cat-gps-watches", key: "barometricAltimeter", label: "Barometric Altimeter", type: "boolean", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-dynamics", categoryId: "cat-gps-watches", key: "runningDynamics", label: "Running Dynamics", type: "boolean", comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-readiness", categoryId: "cat-gps-watches", key: "trainingReadiness", label: "Training Readiness", type: "boolean", comparisonPriority: 66, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-recovery", categoryId: "cat-gps-watches", key: "recoveryMetrics", label: "Recovery Metrics", type: "boolean", comparisonPriority: 64, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-triathlon", categoryId: "cat-gps-watches", key: "triathlonMode", label: "Triathlon / Multisport", type: "boolean", comparisonPriority: 67, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-strava", categoryId: "cat-gps-watches", key: "stravaSync", label: "Strava Sync", type: "boolean", comparisonPriority: 45, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-platform", categoryId: "cat-gps-watches", key: "mobilePlatform", label: "Mobile Platform", type: "multi-enum", enumValues: ["ios", "android"], comparisonPriority: 56, finderRelevant: true, filterable: true }),
  def({ id: "spec-watch-water", categoryId: "cat-gps-watches", key: "waterRating", label: "Water Rating", type: "string", comparisonPriority: 58, finderRelevant: false, filterable: true }),
  def({ id: "spec-watch-compact", categoryId: "cat-gps-watches", key: "compactFit", label: "Compact / Small Wrist", type: "boolean", comparisonPriority: 61, finderRelevant: true, filterable: true }),
];

export const hrmSpecs: SpecificationDefinition[] = [
  def({ id: "spec-hrm-type", categoryId: "cat-hrm", key: "type", label: "Type", type: "enum", enumValues: ["chest-strap", "armband", "optical", "bra-band"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-placement", categoryId: "cat-hrm", key: "placement", label: "Placement", type: "enum", enumValues: ["chest", "forearm", "upper-arm", "wrist", "sports-bra"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-sensing", categoryId: "cat-hrm", key: "sensingMethod", label: "Sensing Method", type: "enum", enumValues: ["ecg-electrical", "optical"], comparisonPriority: 92, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-connectivity", categoryId: "cat-hrm", key: "connectivity", label: "Connectivity", type: "multi-enum", enumValues: ["ant+", "bluetooth", "wifi"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-bt-simultaneous", categoryId: "cat-hrm", key: "simultaneousBluetooth", label: "Simultaneous Bluetooth Connections", type: "number", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-battery", categoryId: "cat-hrm", key: "battery", label: "Battery", type: "string", comparisonPriority: 75, finderRelevant: true, filterable: false }),
  def({ id: "spec-hrm-battery-type", categoryId: "cat-hrm", key: "batteryType", label: "Battery Type", type: "enum", enumValues: ["rechargeable", "replaceable-coin-cell"], comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-battery-life-hours", categoryId: "cat-hrm", key: "batteryLifeHours", label: "Battery Life (claimed hours)", type: "measurement", unit: "h", comparisonPriority: 70, finderRelevant: false, filterable: true }),
  def({ id: "spec-hrm-dynamics", categoryId: "cat-hrm", key: "runningDynamics", label: "Running Dynamics", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-pace-distance", categoryId: "cat-hrm", key: "paceDistanceSupport", label: "Pace / Distance Support", type: "boolean", comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-standalone", categoryId: "cat-hrm", key: "standaloneRecording", label: "Standalone Recording", type: "boolean", comparisonPriority: 74, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-swim", categoryId: "cat-hrm", key: "swimmingSupport", label: "Swimming Support", type: "boolean", comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-memory", categoryId: "cat-hrm", key: "internalMemory", label: "Internal Memory", type: "boolean", comparisonPriority: 55, finderRelevant: false, filterable: true }),
  def({ id: "spec-hrm-water", categoryId: "cat-hrm", key: "waterResistance", label: "Water Resistance", type: "string", comparisonPriority: 60, finderRelevant: false, filterable: true }),
  def({ id: "spec-hrm-weight", categoryId: "cat-hrm", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-replaceable-strap", categoryId: "cat-hrm", key: "replaceableStrap", label: "Replaceable Strap", type: "boolean", comparisonPriority: 50, finderRelevant: false, filterable: true }),
  def({ id: "spec-hrm-strap-size", categoryId: "cat-hrm", key: "strapSizeRange", label: "Strap Size Range", type: "string", comparisonPriority: 48, finderRelevant: false, filterable: false }),
  def({ id: "spec-hrm-ant", categoryId: "cat-hrm", key: "antPlus", label: "ANT+", type: "boolean", comparisonPriority: 76, finderRelevant: true, filterable: true }),
  def({ id: "spec-hrm-bluetooth", categoryId: "cat-hrm", key: "bluetooth", label: "Bluetooth", type: "boolean", comparisonPriority: 76, finderRelevant: true, filterable: true }),
];

export const hydrationVestSpecs: SpecificationDefinition[] = [
  def({ id: "spec-vest-capacity", categoryId: "cat-packs-vests", key: "capacity", label: "Capacity", type: "measurement", unit: "L", comparisonPriority: 90, finderRelevant: true, filterable: true, directionality: "contextual" }),
  def({ id: "spec-vest-weight", categoryId: "cat-packs-vests", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 85, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-vest-flasks", categoryId: "cat-packs-vests", key: "includedFlasks", label: "Included Flasks", type: "number", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-flask-vol", categoryId: "cat-packs-vests", key: "includedFlaskVolume", label: "Included Flask Volume", type: "measurement", unit: "ml", comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-flask-count", categoryId: "cat-packs-vests", key: "flaskCount", label: "Flask Pockets", type: "number", comparisonPriority: 66, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-bladder", categoryId: "cat-packs-vests", key: "bladderCompatible", label: "Bladder Compatible", type: "boolean", comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-reservoir-compat", categoryId: "cat-packs-vests", key: "reservoirCompatible", label: "Reservoir Compatible", type: "boolean", comparisonPriority: 64, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-reservoir-incl", categoryId: "cat-packs-vests", key: "reservoirIncluded", label: "Reservoir Included", type: "boolean", comparisonPriority: 63, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-total-hyd", categoryId: "cat-packs-vests", key: "totalHydrationCapacity", label: "Total Hydration Capacity", type: "measurement", unit: "ml", comparisonPriority: 88, finderRelevant: true, filterable: true, directionality: "contextual" }),
  def({ id: "spec-vest-bottle", categoryId: "cat-packs-vests", key: "bottleCapacity", label: "Bottle Capacity", type: "measurement", unit: "ml", comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-storage", categoryId: "cat-packs-vests", key: "storage", label: "Storage", type: "string", comparisonPriority: 50, finderRelevant: false, filterable: false }),
  def({ id: "spec-vest-front-storage", categoryId: "cat-packs-vests", key: "frontStorage", label: "Front Storage", type: "string", comparisonPriority: 48, finderRelevant: false, filterable: false }),
  def({ id: "spec-vest-rear-storage", categoryId: "cat-packs-vests", key: "rearStorage", label: "Rear Storage", type: "string", comparisonPriority: 47, finderRelevant: false, filterable: false }),
  def({ id: "spec-vest-pockets", categoryId: "cat-packs-vests", key: "pockets", label: "Pockets", type: "string", comparisonPriority: 45, finderRelevant: false, filterable: false }),
  def({ id: "spec-vest-phone", categoryId: "cat-packs-vests", key: "phoneStorage", label: "Phone Storage", type: "boolean", comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-poles", categoryId: "cat-packs-vests", key: "poleAttachment", label: "Pole Attachment", type: "boolean", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-quiver", categoryId: "cat-packs-vests", key: "quiverCompatible", label: "Quiver Compatible", type: "boolean", comparisonPriority: 55, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-race-kit", categoryId: "cat-packs-vests", key: "raceKitCapacity", label: "Race-Required Gear Capacity", type: "boolean", comparisonPriority: 74, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-helmet", categoryId: "cat-packs-vests", key: "helmetCompatible", label: "Helmet Carry", type: "boolean", comparisonPriority: 42, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-compression", categoryId: "cat-packs-vests", key: "compression", label: "Compression Carry", type: "boolean", comparisonPriority: 48, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-bib", categoryId: "cat-packs-vests", key: "raceBibAttachment", label: "Race Bib Features", type: "boolean", comparisonPriority: 44, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-bounce", categoryId: "cat-packs-vests", key: "bounceControl", label: "Bounce Control", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-breath", categoryId: "cat-packs-vests", key: "breathability", label: "Breathability", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-reflective", categoryId: "cat-packs-vests", key: "reflectivity", label: "Reflectivity", type: "boolean", comparisonPriority: 40, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-whistle", categoryId: "cat-packs-vests", key: "whistle", label: "Whistle", type: "boolean", comparisonPriority: 35, finderRelevant: false, filterable: true }),
  def({ id: "spec-vest-water", categoryId: "cat-packs-vests", key: "waterResistance", label: "Water Resistance", type: "enum", enumValues: ["none", "water-resistant", "waterproof"], comparisonPriority: 42, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-fit-system", categoryId: "cat-packs-vests", key: "fitSystem", label: "Fit System", type: "string", comparisonPriority: 52, finderRelevant: true, filterable: false }),
  def({ id: "spec-vest-size-range", categoryId: "cat-packs-vests", key: "sizeRange", label: "Size Range", type: "string", comparisonPriority: 54, finderRelevant: true, filterable: false }),
  def({ id: "spec-vest-sizing", categoryId: "cat-packs-vests", key: "sizing", label: "Sizing", type: "string", comparisonPriority: 55, finderRelevant: true, filterable: false }),
  def({ id: "spec-vest-gender", categoryId: "cat-packs-vests", key: "genderFit", label: "Gender Fit", type: "enum", enumValues: ["unisex", "men", "women"], comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-race", categoryId: "cat-packs-vests", key: "raceSuitability", label: "Race Suitability", type: "multi-enum", enumValues: ["trail", "ultra", "road", "adventure"], comparisonPriority: 72, finderRelevant: true, filterable: true }),
];

export const headphoneSpecs: SpecificationDefinition[] = [
  def({ id: "spec-hp-type", categoryId: "cat-headphones", key: "type", label: "Type", type: "enum", enumValues: ["in-ear", "open-ear", "bone-conduction", "ear-hook", "over-ear"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-weight", categoryId: "cat-headphones", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 70, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-hp-battery", categoryId: "cat-headphones", key: "battery", label: "Battery (earbuds)", type: "measurement", unit: "hours", comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-case-battery", categoryId: "cat-headphones", key: "caseBattery", label: "Case Battery", type: "measurement", unit: "hours", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-charging", categoryId: "cat-headphones", key: "charging", label: "Charging", type: "string", comparisonPriority: 50, finderRelevant: false, filterable: false }),
  def({ id: "spec-hp-water", categoryId: "cat-headphones", key: "waterRating", label: "Water Rating", type: "string", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-open", categoryId: "cat-headphones", key: "openEar", label: "Open Ear", type: "boolean", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-bone", categoryId: "cat-headphones", key: "boneConduction", label: "Bone Conduction", type: "boolean", comparisonPriority: 86, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-anc", categoryId: "cat-headphones", key: "anc", label: "ANC", type: "boolean", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-transparency", categoryId: "cat-headphones", key: "transparency", label: "Transparency Mode", type: "boolean", comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-mic", categoryId: "cat-headphones", key: "microphone", label: "Microphone", type: "boolean", comparisonPriority: 55, finderRelevant: false, filterable: true }),
  def({ id: "spec-hp-secure", categoryId: "cat-headphones", key: "secureFit", label: "Secure Fit", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-controls", categoryId: "cat-headphones", key: "controls", label: "Controls", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-hp-multipoint", categoryId: "cat-headphones", key: "multipoint", label: "Multipoint", type: "boolean", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-hp-codec", categoryId: "cat-headphones", key: "codec", label: "Codec", type: "string", comparisonPriority: 35, finderRelevant: false, filterable: false }),
  def({ id: "spec-hp-awareness", categoryId: "cat-headphones", key: "safetyAwareness", label: "Safety Awareness", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 92, finderRelevant: true, filterable: true }),
];

export const runningClothingSpecs: SpecificationDefinition[] = [
  def({ id: "spec-cloth-material", categoryId: "cat-running-clothing", key: "material", label: "Material", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-cloth-weight", categoryId: "cat-running-clothing", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 65, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-cloth-fit", categoryId: "cat-running-clothing", key: "fit", label: "Fit", type: "enum", enumValues: ["relaxed", "regular", "fitted", "compression"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-inseam", categoryId: "cat-running-clothing", key: "inseam", label: "Inseam", type: "measurement", unit: "in", comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-pockets", categoryId: "cat-running-clothing", key: "pockets", label: "Pockets", type: "boolean", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-phone-pocket", categoryId: "cat-running-clothing", key: "phonePocket", label: "Phone Pocket", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-liner", categoryId: "cat-running-clothing", key: "liner", label: "Liner", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-compression", categoryId: "cat-running-clothing", key: "compression", label: "Compression", type: "boolean", comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-reflective", categoryId: "cat-running-clothing", key: "reflective", label: "Reflective", type: "boolean", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-water-res", categoryId: "cat-running-clothing", key: "waterResistance", label: "Water Resistance", type: "enum", enumValues: ["none", "water-resistant", "waterproof"], comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-waterproof-rating", categoryId: "cat-running-clothing", key: "waterproofRating", label: "Waterproof Rating", type: "string", comparisonPriority: 55, finderRelevant: false, filterable: false }),
  def({ id: "spec-cloth-breath", categoryId: "cat-running-clothing", key: "breathability", label: "Breathability", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-wind", categoryId: "cat-running-clothing", key: "windResistance", label: "Wind Resistance", type: "enum", enumValues: ["none", "wind-resistant", "windproof"], comparisonPriority: 76, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-hood", categoryId: "cat-running-clothing", key: "hood", label: "Hood", type: "boolean", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-packable", categoryId: "cat-running-clothing", key: "packability", label: "Packability", type: "enum", enumValues: ["none", "pocket-stow", "packable"], comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-seams", categoryId: "cat-running-clothing", key: "seams", label: "Seams", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-cloth-anti-chafe", categoryId: "cat-running-clothing", key: "antiChafe", label: "Anti-Chafe Design", type: "boolean", comparisonPriority: 66, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-temp", categoryId: "cat-running-clothing", key: "temperatureSuitability", label: "Temperature Suitability", type: "multi-enum", enumValues: ["hot", "mild", "cold", "frigid"], comparisonPriority: 84, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-weather", categoryId: "cat-running-clothing", key: "weather", label: "Weather", type: "multi-enum", enumValues: ["hot", "mild", "cold", "wet"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-season", categoryId: "cat-running-clothing", key: "season", label: "Season", type: "multi-enum", enumValues: ["spring", "summer", "autumn", "winter", "all-season"], comparisonPriority: 74, finderRelevant: true, filterable: true }),
  def({ id: "spec-cloth-upf", categoryId: "cat-running-clothing", key: "upf", label: "UPF", type: "string", comparisonPriority: 45, finderRelevant: false, filterable: false }),
  def({ id: "spec-cloth-size-range", categoryId: "cat-running-clothing", key: "sizeRange", label: "Size Range", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-cloth-colors", categoryId: "cat-running-clothing", key: "colors", label: "Colors", type: "string", comparisonPriority: 30, finderRelevant: false, filterable: false }),
  def({ id: "spec-cloth-care", categoryId: "cat-running-clothing", key: "care", label: "Care", type: "string", comparisonPriority: 25, finderRelevant: false, filterable: false }),
  def({ id: "spec-cloth-gender", categoryId: "cat-running-clothing", key: "genderFit", label: "Gender", type: "enum", enumValues: ["men", "women", "unisex"], comparisonPriority: 95, finderRelevant: true, filterable: true }),
];

export const padelRacketSpecs: SpecificationDefinition[] = [
  def({
    id: "spec-padel-shape",
    categoryId: "cat-padel-rackets",
    key: "shape",
    label: "Shape",
    type: "enum",
    enumValues: ["round", "teardrop", "diamond", "hybrid", "other", "unknown"],
    comparisonPriority: 95,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-balance",
    categoryId: "cat-padel-rackets",
    key: "balance",
    label: "Balance",
    type: "enum",
    enumValues: ["low", "mid-low", "medium", "mid-high", "high", "head-heavy", "unknown"],
    comparisonPriority: 92,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-weight-min",
    categoryId: "cat-padel-rackets",
    key: "weightMin",
    label: "Weight Min",
    type: "measurement",
    unit: "g",
    comparisonPriority: 88,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-weight-max",
    categoryId: "cat-padel-rackets",
    key: "weightMax",
    label: "Weight Max",
    type: "measurement",
    unit: "g",
    comparisonPriority: 87,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-thickness",
    categoryId: "cat-padel-rackets",
    key: "thicknessMm",
    label: "Thickness",
    type: "measurement",
    unit: "mm",
    comparisonPriority: 70,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-core",
    categoryId: "cat-padel-rackets",
    key: "core",
    label: "Core",
    type: "enum",
    enumValues: ["EVA", "soft-EVA", "medium-EVA", "hard-EVA", "foam", "multi-density", "other", "unknown"],
    comparisonPriority: 80,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-face",
    categoryId: "cat-padel-rackets",
    key: "face",
    label: "Face",
    type: "string",
    comparisonPriority: 70,
    finderRelevant: true,
    filterable: false,
  }),
  def({
    id: "spec-padel-sweet",
    categoryId: "cat-padel-rackets",
    key: "sweetSpot",
    label: "Sweet Spot",
    type: "enum",
    enumValues: ["large", "medium-large", "medium", "compact", "unknown"],
    comparisonPriority: 75,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-power",
    categoryId: "cat-padel-rackets",
    key: "powerPositioning",
    label: "Power Positioning",
    type: "enum",
    enumValues: ["low", "moderate", "balanced", "high", "unknown"],
    comparisonPriority: 85,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-padel-control",
    categoryId: "cat-padel-rackets",
    key: "controlPositioning",
    label: "Control Positioning",
    type: "enum",
    enumValues: ["low", "moderate", "balanced", "high", "unknown"],
    comparisonPriority: 85,
    finderRelevant: true,
    filterable: true,
  }),
];

export const tennisRacketSpecs: SpecificationDefinition[] = [
  def({
    id: "spec-tennis-head",
    categoryId: "cat-tennis-rackets",
    key: "headSizeSqIn",
    label: "Head Size",
    type: "measurement",
    unit: "in²",
    comparisonPriority: 95,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-tennis-weight",
    categoryId: "cat-tennis-rackets",
    key: "strungWeightG",
    label: "Strung Weight",
    type: "measurement",
    unit: "g",
    comparisonPriority: 92,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-tennis-balance",
    categoryId: "cat-tennis-rackets",
    key: "balance",
    label: "Balance",
    type: "enum",
    enumValues: ["head-light", "even", "head-heavy", "unknown"],
    comparisonPriority: 88,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-tennis-pattern",
    categoryId: "cat-tennis-rackets",
    key: "stringPattern",
    label: "String Pattern",
    type: "string",
    comparisonPriority: 80,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-tennis-power",
    categoryId: "cat-tennis-rackets",
    key: "powerPositioning",
    label: "Power Positioning",
    type: "enum",
    enumValues: ["control", "balanced", "power", "unknown"],
    comparisonPriority: 90,
    finderRelevant: true,
    filterable: true,
  }),
];

export const pickleballPaddleSpecs: SpecificationDefinition[] = [
  def({
    id: "spec-pb-weight",
    categoryId: "cat-pickleball-paddles",
    key: "weightOz",
    label: "Weight",
    type: "measurement",
    unit: "oz",
    comparisonPriority: 90,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-pb-thickness",
    categoryId: "cat-pickleball-paddles",
    key: "thicknessMm",
    label: "Thickness",
    type: "measurement",
    unit: "mm",
    comparisonPriority: 85,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-pb-core",
    categoryId: "cat-pickleball-paddles",
    key: "coreMaterial",
    label: "Core",
    type: "string",
    comparisonPriority: 75,
    finderRelevant: true,
    filterable: false,
  }),
];

export const badmintonRacketSpecs: SpecificationDefinition[] = [
  def({
    id: "spec-bad-class",
    categoryId: "cat-badminton-rackets",
    key: "weightClass",
    label: "Weight Class",
    type: "enum",
    enumValues: ["3U", "4U", "5U", "other", "unknown"],
    comparisonPriority: 95,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-bad-balance",
    categoryId: "cat-badminton-rackets",
    key: "balance",
    label: "Balance",
    type: "enum",
    enumValues: ["head-light", "even", "head-heavy", "unknown"],
    comparisonPriority: 90,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-bad-flex",
    categoryId: "cat-badminton-rackets",
    key: "flex",
    label: "Flex",
    type: "enum",
    enumValues: ["flexible", "medium", "stiff", "extra-stiff", "unknown"],
    comparisonPriority: 85,
    finderRelevant: true,
    filterable: true,
  }),
];

export const squashRacketSpecs: SpecificationDefinition[] = [
  def({
    id: "spec-sq-weight",
    categoryId: "cat-squash-rackets",
    key: "weightG",
    label: "Weight",
    type: "measurement",
    unit: "g",
    comparisonPriority: 90,
    finderRelevant: true,
    filterable: true,
  }),
  def({
    id: "spec-sq-balance",
    categoryId: "cat-squash-rackets",
    key: "balance",
    label: "Balance",
    type: "enum",
    enumValues: ["head-light", "even", "head-heavy", "unknown"],
    comparisonPriority: 85,
    finderRelevant: true,
    filterable: true,
  }),
];

export const hydrationSpecs: SpecificationDefinition[] = [
  def({ id: "spec-hyd-capacity", categoryId: "cat-hydration", key: "capacity", label: "Capacity", type: "measurement", unit: "ml", comparisonPriority: 90, finderRelevant: true, filterable: true, directionality: "contextual" }),
  def({ id: "spec-hyd-volume", categoryId: "cat-hydration", key: "volume", label: "Volume", type: "measurement", unit: "ml", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-weight", categoryId: "cat-hydration", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 70, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-hyd-type", categoryId: "cat-hydration", key: "type", label: "Type", type: "enum", enumValues: ["handheld", "soft-flask", "hard-bottle", "reservoir", "accessory"], comparisonPriority: 92, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-soft-hard", categoryId: "cat-hydration", key: "softHard", label: "Bottle Construction", type: "enum", enumValues: ["soft", "hard"], comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-hand-strap", categoryId: "cat-hydration", key: "handStrap", label: "Hand Strap", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-pocket", categoryId: "cat-hydration", key: "pocket", label: "Pocket", type: "boolean", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-phone", categoryId: "cat-hydration", key: "phoneCapacity", label: "Phone Capacity", type: "boolean", comparisonPriority: 55, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-bite", categoryId: "cat-hydration", key: "biteValve", label: "Bite Valve", type: "boolean", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-insulation", categoryId: "cat-hydration", key: "insulation", label: "Insulation", type: "boolean", comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-material", categoryId: "cat-hydration", key: "material", label: "Material", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-hyd-flasks", categoryId: "cat-hydration", key: "includedFlasks", label: "Included Flasks", type: "number", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-hyd-bladder", categoryId: "cat-hydration", key: "bladderCompatible", label: "Bladder Compatible", type: "boolean", comparisonPriority: 55, finderRelevant: true, filterable: true }),
];

export const runningBeltSpecs: SpecificationDefinition[] = [
  def({ id: "spec-belt-capacity", categoryId: "cat-running-belts", key: "capacity", label: "Capacity", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-belt-weight", categoryId: "cat-running-belts", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 65, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-belt-phone", categoryId: "cat-running-belts", key: "phoneCompatible", label: "Phone Compatible", type: "boolean", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-bottle", categoryId: "cat-running-belts", key: "bottleCompatible", label: "Bottle Compatible", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-bottle-incl", categoryId: "cat-running-belts", key: "bottleIncluded", label: "Bottle Included", type: "boolean", comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-flask-incl", categoryId: "cat-running-belts", key: "flaskIncluded", label: "Flask Included", type: "boolean", comparisonPriority: 76, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-phone-fit", categoryId: "cat-running-belts", key: "phoneFit", label: "Phone Fit", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-belt-poles", categoryId: "cat-running-belts", key: "poles", label: "Pole Carry", type: "boolean", comparisonPriority: 50, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-bib", categoryId: "cat-running-belts", key: "bibAttachment", label: "Bib Attachment", type: "boolean", comparisonPriority: 45, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-gels", categoryId: "cat-running-belts", key: "gelStorage", label: "Gel Storage", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-adjust", categoryId: "cat-running-belts", key: "adjustability", label: "Adjustability", type: "string", comparisonPriority: 55, finderRelevant: true, filterable: false }),
  def({ id: "spec-belt-bounce", categoryId: "cat-running-belts", key: "bounce", label: "Bounce Control", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-material", categoryId: "cat-running-belts", key: "material", label: "Material", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-belt-water", categoryId: "cat-running-belts", key: "waterResistance", label: "Water Resistance", type: "enum", enumValues: ["none", "water-resistant", "waterproof"], comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-belt-reflective", categoryId: "cat-running-belts", key: "reflective", label: "Reflective", type: "boolean", comparisonPriority: 55, finderRelevant: true, filterable: true }),
];

export const runningSockSpecs: SpecificationDefinition[] = [
  def({ id: "spec-sock-cushion", categoryId: "cat-running-socks", key: "cushionLevel", label: "Cushion Level", type: "enum", enumValues: ["light", "medium", "heavy"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-sock-height", categoryId: "cat-running-socks", key: "height", label: "Height", type: "enum", enumValues: ["no-show", "ankle", "quarter", "crew", "knee"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-sock-material", categoryId: "cat-running-socks", key: "material", label: "Material", type: "string", comparisonPriority: 50, finderRelevant: false, filterable: false }),
  def({ id: "spec-sock-compression", categoryId: "cat-running-socks", key: "compression", label: "Compression", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-sock-blister", categoryId: "cat-running-socks", key: "blisterFocus", label: "Blister-Focused Design", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-sock-toe", categoryId: "cat-running-socks", key: "toeSeparation", label: "Toe Separation", type: "boolean", comparisonPriority: 70, finderRelevant: true, filterable: true }),
];

export const sunglassesSpecs: SpecificationDefinition[] = [
  def({ id: "spec-sg-lens", categoryId: "cat-sunglasses", key: "lensType", label: "Lens Type", type: "string", comparisonPriority: 80, finderRelevant: true, filterable: false }),
  def({ id: "spec-sg-frame", categoryId: "cat-sunglasses", key: "frameStyle", label: "Frame Style", type: "enum", enumValues: ["shield", "wrap", "rectangle", "sport", "classic"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-weight", categoryId: "cat-sunglasses", key: "weight", label: "Frame Weight", type: "measurement", unit: "g", comparisonPriority: 75, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-sg-polarized", categoryId: "cat-sunglasses", key: "polarized", label: "Polarized", type: "boolean", comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-photochromic", categoryId: "cat-sunglasses", key: "photochromic", label: "Photochromic", type: "boolean", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-vlt", categoryId: "cat-sunglasses", key: "vlt", label: "VLT", type: "string", comparisonPriority: 78, finderRelevant: true, filterable: false }),
  def({ id: "spec-sg-uv", categoryId: "cat-sunglasses", key: "uvProtection", label: "UV Protection", type: "string", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-coverage", categoryId: "cat-sunglasses", key: "coverage", label: "Coverage", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-vent", categoryId: "cat-sunglasses", key: "ventilation", label: "Ventilation", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-interchange", categoryId: "cat-sunglasses", key: "interchangeableLenses", label: "Interchangeable Lenses", type: "boolean", comparisonPriority: 65, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-rx", categoryId: "cat-sunglasses", key: "prescriptionCompatible", label: "Prescription Compatible", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-fit", categoryId: "cat-sunglasses", key: "fit", label: "Fit", type: "enum", enumValues: ["small", "medium", "large", "unisex"], comparisonPriority: 84, finderRelevant: true, filterable: true }),
  def({ id: "spec-sg-nose", categoryId: "cat-sunglasses", key: "noseAdjustment", label: "Nose Adjustment", type: "boolean", comparisonPriority: 68, finderRelevant: true, filterable: true }),
];

export const runningLightSpecs: SpecificationDefinition[] = [
  def({ id: "spec-light-lumens", categoryId: "cat-running-lights", key: "lumens", label: "Max Lumens", type: "measurement", unit: "lm", comparisonPriority: 95, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-beam-modes", categoryId: "cat-running-lights", key: "beamModes", label: "Beam Modes", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-light-distance", categoryId: "cat-running-lights", key: "beamDistance", label: "Beam Distance", type: "measurement", unit: "m", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-battery", categoryId: "cat-running-lights", key: "battery", label: "Battery", type: "string", comparisonPriority: 80, finderRelevant: true, filterable: false }),
  def({ id: "spec-light-runtime", categoryId: "cat-running-lights", key: "runtime", label: "Runtime", type: "string", comparisonPriority: 88, finderRelevant: true, filterable: false }),
  def({ id: "spec-light-weight", categoryId: "cat-running-lights", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 85, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-light-recharge", categoryId: "cat-running-lights", key: "rechargeable", label: "Rechargeable", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-replaceable", categoryId: "cat-running-lights", key: "replaceableBatteries", label: "Replaceable Batteries", type: "boolean", comparisonPriority: 62, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-rear", categoryId: "cat-running-lights", key: "rearLight", label: "Rear Light", type: "boolean", comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-reactive", categoryId: "cat-running-lights", key: "reactiveLighting", label: "Reactive Lighting", type: "boolean", comparisonPriority: 78, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-lock", categoryId: "cat-running-lights", key: "lockMode", label: "Lock Mode", type: "boolean", comparisonPriority: 55, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-comfort", categoryId: "cat-running-lights", key: "comfort", label: "Comfort", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 74, finderRelevant: true, filterable: true }),
  def({ id: "spec-light-water", categoryId: "cat-running-lights", key: "waterproofRating", label: "Water Rating", type: "string", comparisonPriority: 65, finderRelevant: true, filterable: false }),
];

export const safetyGearSpecs: SpecificationDefinition[] = [
  def({ id: "spec-safety-type", categoryId: "cat-safety", key: "type", label: "Type", type: "enum", enumValues: ["reflective-vest", "clip-light", "wearable-light", "id-band", "alarm", "reflective-accessory"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-safety-weight", categoryId: "cat-safety", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 60, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-safety-reflective", categoryId: "cat-safety", key: "reflective", label: "Reflective", type: "boolean", comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-safety-illum", categoryId: "cat-safety", key: "illuminated", label: "Illuminated", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-safety-recharge", categoryId: "cat-safety", key: "rechargeable", label: "Rechargeable", type: "boolean", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-safety-modes", categoryId: "cat-safety", key: "lightModes", label: "Light Modes", type: "string", comparisonPriority: 58, finderRelevant: false, filterable: false }),
  def({ id: "spec-safety-runtime", categoryId: "cat-safety", key: "runtime", label: "Runtime", type: "string", comparisonPriority: 62, finderRelevant: true, filterable: false }),
  def({ id: "spec-safety-alarm", categoryId: "cat-safety", key: "alarmDecibels", label: "Alarm Output", type: "string", comparisonPriority: 75, finderRelevant: true, filterable: false }),
  def({ id: "spec-safety-water", categoryId: "cat-safety", key: "waterResistance", label: "Water Resistance", type: "enum", enumValues: ["none", "water-resistant", "waterproof"], comparisonPriority: 55, finderRelevant: true, filterable: true }),
];

export const recoveryGearSpecs: SpecificationDefinition[] = [
  def({ id: "spec-rec-type", categoryId: "cat-recovery-gear", key: "type", label: "Type", type: "enum", enumValues: ["massage-gun", "percussive-massage", "foam-roller", "massage-ball", "compression-boot", "recovery-sandal", "compression-garment", "mobility-tool"], comparisonPriority: 95, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-weight", categoryId: "cat-recovery-gear", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 78, finderRelevant: true, filterable: true, directionality: "lower-better" }),
  def({ id: "spec-rec-battery", categoryId: "cat-recovery-gear", key: "battery", label: "Battery", type: "string", comparisonPriority: 75, finderRelevant: true, filterable: false }),
  def({ id: "spec-rec-portable", categoryId: "cat-recovery-gear", key: "portable", label: "Portable", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  // Massage guns
  def({ id: "spec-rec-amplitude", categoryId: "cat-recovery-gear", key: "amplitude", label: "Amplitude", type: "measurement", unit: "mm", comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-stall", categoryId: "cat-recovery-gear", key: "stallForce", label: "Stall Force", type: "string", comparisonPriority: 72, finderRelevant: true, filterable: false }),
  def({ id: "spec-rec-speeds", categoryId: "cat-recovery-gear", key: "speeds", label: "Speeds", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: false }),
  def({ id: "spec-rec-attachments", categoryId: "cat-recovery-gear", key: "attachments", label: "Attachments", type: "string", comparisonPriority: 65, finderRelevant: false, filterable: false }),
  def({ id: "spec-rec-noise", categoryId: "cat-recovery-gear", key: "noise", label: "Noise", type: "enum", enumValues: ["quiet", "moderate", "loud"], comparisonPriority: 68, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-size", categoryId: "cat-recovery-gear", key: "sizeClass", label: "Size", type: "enum", enumValues: ["mini", "compact", "full-size", "travel"], comparisonPriority: 74, finderRelevant: true, filterable: true }),
  // Foam rollers / balls
  def({ id: "spec-rec-length", categoryId: "cat-recovery-gear", key: "length", label: "Length", type: "measurement", unit: "cm", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-diameter", categoryId: "cat-recovery-gear", key: "diameter", label: "Diameter", type: "measurement", unit: "cm", comparisonPriority: 58, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-density", categoryId: "cat-recovery-gear", key: "density", label: "Density", type: "enum", enumValues: ["soft", "medium", "firm", "multi-density"], comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-surface", categoryId: "cat-recovery-gear", key: "surface", label: "Surface", type: "enum", enumValues: ["smooth", "textured", "ridged", "multi"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-material", categoryId: "cat-recovery-gear", key: "material", label: "Material", type: "string", comparisonPriority: 50, finderRelevant: false, filterable: false }),
  // Compression systems
  def({ id: "spec-rec-zones", categoryId: "cat-recovery-gear", key: "zones", label: "Zones", type: "string", comparisonPriority: 76, finderRelevant: true, filterable: false }),
  def({ id: "spec-rec-pressure", categoryId: "cat-recovery-gear", key: "pressureSettings", label: "Pressure Settings", type: "string", comparisonPriority: 74, finderRelevant: true, filterable: false }),
  def({ id: "spec-rec-boot-sizes", categoryId: "cat-recovery-gear", key: "bootSizes", label: "Boot / Garment Sizes", type: "string", comparisonPriority: 55, finderRelevant: false, filterable: false }),
  // Sandals / garments
  def({ id: "spec-rec-cushion", categoryId: "cat-recovery-gear", key: "cushionLevel", label: "Cushion Level", type: "enum", enumValues: ["low", "medium", "high", "maximum"], comparisonPriority: 72, finderRelevant: true, filterable: true }),
  def({ id: "spec-rec-gender", categoryId: "cat-recovery-gear", key: "genderFit", label: "Gender Fit", type: "enum", enumValues: ["unisex", "men", "women"], comparisonPriority: 48, finderRelevant: true, filterable: true }),
];

export const accessorySpecs: SpecificationDefinition[] = [
  def({ id: "spec-acc-type", categoryId: "cat-accessories", key: "type", label: "Type", type: "enum", enumValues: ["neckwear", "neck-gaiter", "gaiter", "calf-sleeve", "arm-sleeve", "anti-chafe", "pole-accessory", "phone-holder", "reflective", "race-belt", "other"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-acc-weight", categoryId: "cat-accessories", key: "weight", label: "Weight", type: "measurement", unit: "g", comparisonPriority: 60, finderRelevant: true, filterable: true }),
  def({ id: "spec-acc-material", categoryId: "cat-accessories", key: "material", label: "Material", type: "string", comparisonPriority: 40, finderRelevant: false, filterable: false }),
  def({ id: "spec-acc-compression", categoryId: "cat-accessories", key: "compression", label: "Compression", type: "boolean", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-acc-water", categoryId: "cat-accessories", key: "waterResistance", label: "Water Resistance", type: "enum", enumValues: ["none", "water-resistant", "waterproof"], comparisonPriority: 50, finderRelevant: true, filterable: true }),
  def({ id: "spec-acc-weather", categoryId: "cat-accessories", key: "weather", label: "Weather", type: "multi-enum", enumValues: ["hot", "mild", "cold", "wet"], comparisonPriority: 65, finderRelevant: true, filterable: true }),
];

/** Running nutrition / race fuel — factual label fields only; no medical claims. */
export const nutritionSpecs: SpecificationDefinition[] = [
  def({ id: "spec-nut-type", categoryId: "cat-nutrition", key: "type", label: "Type", type: "enum", enumValues: ["gel", "chew", "bar", "sports-drink", "electrolyte-mix", "carb-mix", "electrolyte-tablet", "race-fuel"], comparisonPriority: 95, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-serving", categoryId: "cat-nutrition", key: "servingSize", label: "Serving Size", type: "string", comparisonPriority: 88, finderRelevant: true, filterable: false }),
  def({ id: "spec-nut-calories", categoryId: "cat-nutrition", key: "calories", label: "Calories", type: "measurement", unit: "kcal", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-carbs", categoryId: "cat-nutrition", key: "carbsPerServing", label: "Carbohydrate", type: "measurement", unit: "g", comparisonPriority: 92, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-sugars", categoryId: "cat-nutrition", key: "sugars", label: "Sugars", type: "measurement", unit: "g", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-sodium", categoryId: "cat-nutrition", key: "sodium", label: "Sodium", type: "measurement", unit: "mg", comparisonPriority: 82, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-caffeine", categoryId: "cat-nutrition", key: "caffeine", label: "Contains Caffeine", type: "boolean", comparisonPriority: 86, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-caffeine-mg", categoryId: "cat-nutrition", key: "caffeineAmount", label: "Caffeine Amount", type: "measurement", unit: "mg", comparisonPriority: 84, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-protein", categoryId: "cat-nutrition", key: "protein", label: "Protein", type: "measurement", unit: "g", comparisonPriority: 55, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-fluid", categoryId: "cat-nutrition", key: "fluidRequired", label: "Fluid Required", type: "string", comparisonPriority: 75, finderRelevant: true, filterable: false }),
  def({ id: "spec-nut-form", categoryId: "cat-nutrition", key: "form", label: "Texture / Form", type: "enum", enumValues: ["gel", "chew", "bar", "powder", "tablet", "liquid"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-nut-flavour", categoryId: "cat-nutrition", key: "flavour", label: "Flavour", type: "string", comparisonPriority: 50, finderRelevant: false, filterable: false }),
  def({ id: "spec-nut-pack", categoryId: "cat-nutrition", key: "packSize", label: "Pack Size", type: "string", comparisonPriority: 45, finderRelevant: false, filterable: false }),
  def({ id: "spec-nut-dietary", categoryId: "cat-nutrition", key: "dietaryLabels", label: "Dietary Labels", type: "string", comparisonPriority: 48, finderRelevant: false, filterable: false }),
  def({ id: "spec-nut-allergens", categoryId: "cat-nutrition", key: "allergens", label: "Allergen Information", type: "string", comparisonPriority: 60, finderRelevant: false, filterable: false }),
];

/**
 * Minimal specs for accessory / niche categories (see category-spec-policy.ts).
 * Keep filterable keys aligned with values already stored on products.
 */
export const minimalAccessorySpecs: SpecificationDefinition[] = [
  // Court shoes
  def({ id: "spec-padel-shoe-cushion", categoryId: "cat-padel-shoes", key: "cushioning", label: "Cushioning", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-shoe-outsole", categoryId: "cat-padel-shoes", key: "outsole", label: "Outsole", type: "string", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-shoe-support", categoryId: "cat-padel-shoes", key: "support", label: "Support", type: "enum", enumValues: ["neutral", "stability", "high"], comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-shoe-gender", categoryId: "cat-padel-shoes", key: "genderFit", label: "Gender", type: "enum", enumValues: ["men", "women", "unisex"], comparisonPriority: 88, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-shoe-surface", categoryId: "cat-tennis-shoes", key: "courtSurface", label: "Court Surface", type: "enum", enumValues: ["hard", "clay", "grass", "all-court"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-shoe-stability", categoryId: "cat-tennis-shoes", key: "stability", label: "Stability", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-shoe-cushion", categoryId: "cat-tennis-shoes", key: "cushioning", label: "Cushioning", type: "enum", enumValues: ["low", "moderate", "high"], comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-shoe-weight-class", categoryId: "cat-tennis-shoes", key: "weightClass", label: "Weight Class", type: "enum", enumValues: ["light", "medium", "heavy"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-shoe-gender", categoryId: "cat-tennis-shoes", key: "genderFit", label: "Gender", type: "enum", enumValues: ["men", "women", "unisex"], comparisonPriority: 88, finderRelevant: true, filterable: true }),

  // Tennis strings / padel soft goods
  def({ id: "spec-tennis-string-gauge", categoryId: "cat-tennis-strings", key: "gaugeMm", label: "Gauge", type: "measurement", unit: "mm", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-string-material", categoryId: "cat-tennis-strings", key: "material", label: "Material", type: "enum", enumValues: ["polyester", "multifilament", "natural-gut", "hybrid", "other"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-tennis-string-profile", categoryId: "cat-tennis-strings", key: "profile", label: "Profile", type: "enum", enumValues: ["round", "shaped", "textured"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-bag-capacity", categoryId: "cat-padel-bags", key: "capacity", label: "Capacity", type: "string", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-ball-type", categoryId: "cat-padel-balls", key: "ballType", label: "Ball Type", type: "enum", enumValues: ["official", "training", "pressureless"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-padel-grip-type", categoryId: "cat-padel-grips", key: "gripType", label: "Grip Type", type: "enum", enumValues: ["overgrip", "replacement", "cushion"], comparisonPriority: 85, finderRelevant: true, filterable: true }),

  // Fitness accessories
  def({ id: "spec-kb-material", categoryId: "cat-kettlebells", key: "material", label: "Material", type: "enum", enumValues: ["cast-iron", "competition", "adjustable", "other"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-kb-window", categoryId: "cat-kettlebells", key: "window", label: "Handle Window", type: "enum", enumValues: ["standard", "competition", "wide"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-para-material", categoryId: "cat-parallettes", key: "material", label: "Material", type: "enum", enumValues: ["wood", "steel", "aluminum", "other"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-para-height", categoryId: "cat-parallettes", key: "height", label: "Height", type: "measurement", unit: "mm", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-rings-material", categoryId: "cat-gymnastic-rings", key: "material", label: "Material", type: "enum", enumValues: ["wood", "plastic", "composite"], comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-rings-strap", categoryId: "cat-gymnastic-rings", key: "strapLength", label: "Strap Length", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-max", categoryId: "cat-weighted-vests", key: "maxLoad", label: "Max Load", type: "measurement", unit: "kg", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-vest-adj", categoryId: "cat-weighted-vests", key: "adjustable", label: "Adjustable", type: "boolean", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-func-weight", categoryId: "cat-functional-fitness", key: "weightKg", label: "Weight", type: "measurement", unit: "kg", comparisonPriority: 85, finderRelevant: true, filterable: true }),
  def({ id: "spec-func-max-load", categoryId: "cat-functional-fitness", key: "maxLoad", label: "Max Load", type: "measurement", unit: "kg", comparisonPriority: 80, finderRelevant: true, filterable: true }),
  def({ id: "spec-func-loadable", categoryId: "cat-functional-fitness", key: "loadable", label: "Loadable", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true }),
  def({ id: "spec-floor-thick", categoryId: "cat-gym-flooring", key: "thicknessMm", label: "Thickness", type: "measurement", unit: "mm", comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-storage-type", categoryId: "cat-gym-storage", key: "storageType", label: "Storage Type", type: "enum", enumValues: ["plate-tree", "bar-holder", "dumbbell-rack", "shelf", "other"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-lift-acc-type", categoryId: "cat-lifting-accessories", key: "type", label: "Type", type: "enum", enumValues: ["foam-roller", "belt", "straps", "sleeves", "bands", "other"], comparisonPriority: 90, finderRelevant: true, filterable: true }),
  def({ id: "spec-lift-acc-density", categoryId: "cat-lifting-accessories", key: "density", label: "Density", type: "enum", enumValues: ["soft", "medium", "firm"], comparisonPriority: 70, finderRelevant: true, filterable: true }),
];

export const allSpecificationDefinitions: SpecificationDefinition[] = [
  ...runningShoeSpecs,
  ...gpsWatchSpecs,
  ...hrmSpecs,
  ...hydrationVestSpecs,
  ...hydrationSpecs,
  ...runningBeltSpecs,
  ...headphoneSpecs,
  ...runningClothingSpecs,
  ...runningSockSpecs,
  ...sunglassesSpecs,
  ...runningLightSpecs,
  ...safetyGearSpecs,
  ...recoveryGearSpecs,
  ...accessorySpecs,
  ...nutritionSpecs,
  ...minimalAccessorySpecs,
  ...padelRacketSpecs,
  ...tennisRacketSpecs,
  ...pickleballPaddleSpecs,
  ...badmintonRacketSpecs,
  ...squashRacketSpecs,
  ...fitnessSpecificationDefinitions,
];
