import type { ProductCategory } from "@/domain/sports/types";
import { publishedMeta } from "@/content/config";
import { padelCategories } from "@/content/padel/seed";
import { racketCategories } from "@/content/racket";
import { fitnessCategories } from "@/content/fitness";

const meta = publishedMeta();

function cat(
  id: string,
  name: string,
  slug: string,
  pathSegment: string,
  icon: string,
  description: string,
  sportIds: string[],
  sortOrder: number,
): ProductCategory {
  return {
    id,
    name,
    slug,
    pathSegment,
    icon,
    description,
    sportIds,
    sortOrder,
    ...meta,
  };
}

/** Running categories (primary launch vertical) + shared cross-sport categories */
export const categories: ProductCategory[] = [
  {
    id: "cat-running-shoes",
    name: "Running Shoes",
    slug: "running-shoes",
    pathSegment: "shoes",
    icon: "Footprints",
    description: "Daily trainers, racers, trail and recovery shoes.",
    sportIds: ["sport-running", "sport-hyrox"],
    sortOrder: 10,
    seoTitle: "Running Shoes: Compare Trainers, Race & Trail Shoes",
    seoDescription:
      "Compare running shoes by cushion, stability, drop and terrain. Browse daily trainers, race shoes and trail options — or use the Running Shoe Finder.",
    ...meta,
  },
  cat(
    "cat-gps-watches",
    "GPS Watches",
    "gps-watches",
    "watches",
    "Watch",
    "Multisport watches with training metrics and maps.",
    ["sport-running", "sport-cycling", "sport-swimming", "sport-training", "sport-hyrox"],
    20,
  ),
  cat(
    "cat-hrm",
    "Heart Rate Monitors",
    "heart-rate-monitors",
    "heart-rate-monitors",
    "HeartPulse",
    "Chest straps and optical HR monitors.",
    ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    30,
  ),
  cat(
    "cat-running-clothing",
    "Running Clothing",
    "running-clothing",
    "clothing",
    "Shirt",
    "Tops, shorts, tights and weather layers.",
    ["sport-running"],
    40,
  ),
  cat(
    "cat-running-socks",
    "Running Socks",
    "running-socks",
    "socks",
    "Footprints",
    "Performance socks for blister prevention and fit.",
    ["sport-running"],
    50,
  ),
  cat(
    "cat-hydration",
    "Hydration",
    "hydration",
    "hydration",
    "Droplets",
    "Vests, belts, bottles and soft flasks.",
    ["sport-running", "sport-cycling", "sport-hyrox", "sport-training"],
    60,
  ),
  cat(
    "cat-packs-vests",
    "Running Packs & Vests",
    "running-packs-vests",
    "packs",
    "Backpack",
    "Race vests, running backpacks, fastpacking packs and carry add-ons — hydration vests are shared products, not duplicates.",
    ["sport-running"],
    70,
  ),
  cat(
    "cat-headphones",
    "Headphones",
    "headphones",
    "headphones",
    "Headphones",
    "Bone conduction, earbuds and sweat-proof audio.",
    ["sport-running", "sport-training", "sport-cycling"],
    80,
  ),
  cat(
    "cat-sunglasses",
    "Sunglasses",
    "sunglasses",
    "sunglasses",
    "Sun",
    "Performance lenses for outdoor sport.",
    ["sport-running", "sport-cycling"],
    90,
  ),
  cat(
    "cat-running-lights",
    "Running Lights",
    "running-lights",
    "lights",
    "Lightbulb",
    "Headlamps and wearable lights for dark runs.",
    ["sport-running"],
    100,
  ),
  cat(
    "cat-safety",
    "Safety Gear",
    "safety-gear",
    "safety",
    "Shield",
    "Reflective gear and personal safety devices.",
    ["sport-running", "sport-cycling"],
    110,
  ),
  cat(
    "cat-running-belts",
    "Running Belts",
    "running-belts",
    "belts",
    "Sparkles",
    "Phone, race and hydration waist belts — flask-capable belts are shared with Hydration, not duplicated.",
    ["sport-running"],
    120,
  ),
  cat(
    "cat-recovery-gear",
    "Recovery",
    "recovery",
    "recovery",
    "HeartPulse",
    "Massage, compression and mobility tools.",
    ["sport-recovery", "sport-running", "sport-training", "sport-hyrox"],
    130,
  ),
  cat(
    "cat-accessories",
    "Accessories",
    "accessories",
    "accessories",
    "Sparkles",
    "Anti-chafe sticks and roll-ons for known hotspots — not audio, lights or sunglasses.",
    ["sport-running", "sport-training", "sport-hyrox"],
    140,
  ),
  cat(
    "cat-nutrition",
    "Nutrition & Fuel",
    "nutrition-fuel",
    "nutrition",
    "Apple",
    "Gels, drinks and race-day fueling.",
    ["sport-running", "sport-cycling", "sport-hyrox"],
    150,
  ),
  ...padelCategories,
  ...racketCategories,
  ...fitnessCategories,
];
