import type { Sport } from "@/domain/sports/types";
import { publishedMeta } from "@/content/config";

const meta = publishedMeta();

/**
 * Complete Kitletics sport taxonomy.
 * Deep content initially only on Running (`available: true`).
 */
export const sports: Sport[] = [
  {
    id: "sport-running",
    name: "Running",
    slug: "running",
    description:
      "Shoes, watches, apparel and race-day gear for road, trail, track and ultra.",
    icon: "Footprints",
    color: "#0a84ff",
    featured: true,
    available: true,
    contentStatus: "live",
    sortOrder: 10,
    seoTitle: "Running Gear, Shoes, Watches & Buying Advice",
    seoDescription:
      "Find running shoes, GPS watches, hydration and clothing matched to how you train. Compare gear, use finders and browse structured recommendations.",
    ...meta,
  },
  {
    id: "sport-training",
    name: "Fitness & Training",
    slug: "fitness",
    description:
      "Gym equipment, home gyms, strength, HYROX, calisthenics, conditioning and recovery gear.",
    icon: "Dumbbell",
    color: "#1a1f2b",
    featured: true,
    available: true,
    contentStatus: "live",
    sortOrder: 20,
    seoTitle: "Fitness & Training Gear: Home Gym, Strength, HYROX & More",
    seoDescription:
      "Build the right setup for how you train. Compare racks, dumbbells, training shoes, cardio machines and recovery tools — or use Kitletics finders and the Home Gym Builder.",
    ...meta,
  },
  {
    id: "sport-hyrox",
    name: "HYROX",
    slug: "hyrox",
    description:
      "Race-specific footwear, apparel and station gear for HYROX athletes.",
    icon: "Flame",
    color: "#ef4444",
    featured: true,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-training",
    sortOrder: 25,
    seoTitle: "HYROX Gear: Shoes, Training Setup & Race Day Essentials",
    seoDescription:
      "Find HYROX race and training shoes, conditioning equipment and race-day kits with structured Kitletics recommendations.",
    ...meta,
  },
  {
    id: "sport-calisthenics",
    name: "Calisthenics",
    slug: "calisthenics",
    description: "Bars, grips, rings and bodyweight training essentials.",
    icon: "PersonStanding",
    color: "#12a150",
    featured: false,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-training",
    sortOrder: 26,
    seoTitle: "Calisthenics Gear: Pull-Up Bars, Rings & Parallettes",
    seoDescription:
      "Choose pull-up bars, parallettes, rings and weighted progression gear for home or outdoor calisthenics.",
    ...meta,
  },
  {
    id: "sport-combat",
    name: "Combat Sports",
    slug: "combat",
    description: "Boxing, kickboxing, MMA and martial arts training gear.",
    icon: "Swords",
    color: "#d97706",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 50,
    ...meta,
  },
  {
    id: "sport-padel",
    name: "Padel",
    slug: "padel",
    description:
      "Find the right racket for how you play. Structured recommendations, finders, comparisons and court gear.",
    icon: "CircleDot",
    color: "#c8f542",
    featured: true,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-racket",
    sortOrder: 55,
    seoTitle: "Padel Gear, Rackets, Shoes & Equipment | Kitletics",
    seoDescription:
      "Find padel rackets, shoes, bags and court gear with structured recommendations, finders, comparisons and buying guides.",
    ...meta,
  },
  {
    id: "sport-tennis",
    name: "Tennis",
    slug: "tennis",
    description:
      "Tennis rackets, shoes and strings matched to how you play.",
    icon: "CircleDot",
    color: "#f5f5f5",
    featured: true,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-racket",
    sortOrder: 56,
    seoTitle: "Tennis Rackets, Shoes & Gear | Kitletics",
    seoDescription:
      "Compare tennis rackets by head size, weight and playing style — or use the Tennis Racket Finder.",
    ...meta,
  },
  {
    id: "sport-pickleball",
    name: "Pickleball",
    slug: "pickleball",
    description: "Pickleball paddles and court equipment.",
    icon: "CircleDot",
    color: "#22c55e",
    featured: false,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-racket",
    sortOrder: 57,
    seoTitle: "Pickleball Paddles & Gear | Kitletics",
    seoDescription:
      "Browse pickleball paddles with structured specs, comparisons and buying guidance.",
    ...meta,
  },
  {
    id: "sport-badminton",
    name: "Badminton",
    slug: "badminton",
    description: "Badminton rackets, shuttlecocks and court shoes.",
    icon: "CircleDot",
    color: "#eab308",
    featured: false,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-racket",
    sortOrder: 58,
    seoTitle: "Badminton Rackets & Gear | Kitletics",
    seoDescription:
      "Compare badminton rackets by weight class, balance and flex.",
    ...meta,
  },
  {
    id: "sport-squash",
    name: "Squash",
    slug: "squash",
    description: "Squash rackets and protective eyewear.",
    icon: "CircleDot",
    color: "#a855f7",
    featured: false,
    available: true,
    contentStatus: "live",
    parentSportId: "sport-racket",
    sortOrder: 59,
    seoTitle: "Squash Rackets & Gear | Kitletics",
    seoDescription: "Compare squash rackets by weight, balance and play style.",
    ...meta,
  },
  {
    id: "sport-racket",
    name: "Racket Sports",
    slug: "racket",
    description:
      "Choose your sport — padel, tennis, pickleball, badminton or squash — then find the right equipment.",
    icon: "CircleDot",
    color: "#0a84ff",
    featured: true,
    available: true,
    contentStatus: "live",
    sortOrder: 54,
    seoTitle: "Racket Sports Gear | Kitletics",
    seoDescription:
      "Padel, tennis, pickleball, badminton and squash equipment discovery, finders and buying guides.",
    ...meta,
  },
  {
    id: "sport-cycling",
    name: "Cycling",
    slug: "cycling",
    description: "Road, gravel, MTB, commuting and indoor cycling equipment.",
    icon: "Bike",
    color: "#3d4554",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 70,
    ...meta,
  },
  {
    id: "sport-swimming",
    name: "Swimming",
    slug: "swimming",
    description: "Pool, open water and triathlon swimming gear.",
    icon: "Waves",
    color: "#0284c7",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 80,
    ...meta,
  },
  {
    id: "sport-watersports",
    name: "Watersports",
    slug: "watersports",
    description: "SUP, kayaking, canoeing and surfing equipment.",
    icon: "Sailboat",
    color: "#0891b2",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 90,
    ...meta,
  },
  {
    id: "sport-diving",
    name: "Diving",
    slug: "diving",
    description: "Scuba, freediving and snorkeling gear.",
    icon: "Fish",
    color: "#0369a1",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 100,
    ...meta,
  },
  {
    id: "sport-fishing",
    name: "Fishing",
    slug: "fishing",
    description:
      "Carp, predator, fly, sea, freshwater and kayak fishing tackle.",
    icon: "Fish",
    color: "#4d7c0f",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 110,
    ...meta,
  },
  {
    id: "sport-target",
    name: "Target Sports",
    slug: "target",
    description: "Archery and darts equipment.",
    icon: "Target",
    color: "#b45309",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 120,
    ...meta,
  },
  {
    id: "sport-indoor",
    name: "Indoor Sports",
    slug: "indoor",
    description: "Pool, snooker, table tennis and foosball.",
    icon: "Table",
    color: "#64748b",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 130,
    ...meta,
  },
  {
    id: "sport-winter",
    name: "Winter Sports",
    slug: "winter",
    description: "Skiing and snowboarding equipment.",
    icon: "Snowflake",
    color: "#38bdf8",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 140,
    ...meta,
  },
  {
    id: "sport-recovery",
    name: "Recovery",
    slug: "recovery",
    description:
      "Mobility, massage, compression, sauna and cold plunge tools.",
    icon: "HeartPulse",
    color: "#7c3aed",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 150,
    ...meta,
  },
  {
    id: "sport-recreation",
    name: "Recreation",
    slug: "recreation",
    description: "Sim racing and recreational performance gear.",
    icon: "Gamepad2",
    color: "#525252",
    featured: false,
    available: false,
    contentStatus: "coming-soon",
    sortOrder: 160,
    ...meta,
  },
];
