import type { ProductSubcategory } from "@/domain/sports/types";
import { fitnessSubcategories } from "@/content/fitness";

function sub(
  id: string,
  categoryId: string,
  name: string,
  slug: string,
  description: string,
  sortOrder: number,
): ProductSubcategory {
  return { id, categoryId, name, slug, description, sortOrder };
}

export const subcategories: ProductSubcategory[] = [
  sub("sub-daily-trainers", "cat-running-shoes", "Daily Trainers", "daily-trainers", "Versatile shoes for most of your weekly mileage.", 10),
  sub("sub-max-cushion", "cat-running-shoes", "Max Cushion Shoes", "max-cushion", "Maximum stack and soft landings for protection and long days.", 20),
  sub("sub-tempo", "cat-running-shoes", "Tempo Shoes", "tempo", "Faster daily and workout shoes.", 30),
  sub("sub-race", "cat-running-shoes", "Race Shoes", "race", "Lightweight race-day footwear for faster efforts.", 40),
  sub("sub-carbon", "cat-running-shoes", "Carbon Plate Shoes", "carbon-plate", "Plated racing and speed shoes.", 50),
  sub("sub-stability", "cat-running-shoes", "Stability Shoes", "stability", "Guidance and support when you need a more controlled ride.", 60),
  sub("sub-neutral", "cat-running-shoes", "Neutral Shoes", "neutral", "Neutral cushioned trainers.", 70),
  sub("sub-trail", "cat-running-shoes", "Trail Shoes", "trail", "Aggressive grip and protection for off-road terrain.", 80),
  sub("sub-road-trail", "cat-running-shoes", "Road-to-Trail Shoes", "road-to-trail", "Hybrid road and light trail.", 90),
  sub("sub-minimalist", "cat-running-shoes", "Minimalist Shoes", "minimalist", "Low stack, natural feel.", 100),
  sub("sub-zero-drop", "cat-running-shoes", "Zero Drop Shoes", "zero-drop", "Zero heel-to-toe drop.", 110),
  sub("sub-wide", "cat-running-shoes", "Wide Running Shoes", "wide", "Wide lasts and width options for a roomier fit.", 120),
  sub("sub-recovery-walk", "cat-running-shoes", "Recovery / Walking Shoes", "recovery-walking", "Easy recovery and walking.", 130),

  // GPS running watches — only lanes with real catalog depth
  sub(
    "sub-gps-entry",
    "cat-gps-watches",
    "Entry-Level Running Watches",
    "entry-running-watches",
    "Approachable GPS watches for first miles and simple training.",
    10,
  ),
  sub(
    "sub-gps-performance",
    "cat-gps-watches",
    "Performance Running Watches",
    "performance-running-watches",
    "Midrange GPS watches for serious road training without adventure flagship pricing.",
    20,
  ),
  sub(
    "sub-gps-premium",
    "cat-gps-watches",
    "Premium Running Watches",
    "premium-running-watches",
    "Flagship road and multisport watches with maps, deep metrics and full ecosystems.",
    30,
  ),
  sub(
    "sub-gps-ultra-adventure",
    "cat-gps-watches",
    "Ultra / Adventure Watches",
    "ultra-adventure-watches",
    "Long-battery, rugged and mapped watches for trail, ultra and expedition days.",
    40,
  ),
  sub(
    "sub-gps-compact",
    "cat-gps-watches",
    "Small-Wrist / Compact Watches",
    "compact-running-watches",
    "Lighter cases and compact sizes that still train seriously.",
    50,
  ),

  // Heart rate monitors — inventory-backed lanes only
  sub(
    "sub-hrm-chest",
    "cat-hrm",
    "Chest Straps",
    "chest-straps",
    "ECG/electrical chest straps for accurate training and interval work.",
    10,
  ),
  sub(
    "sub-hrm-armband",
    "cat-hrm",
    "Arm-Band HR Monitors",
    "armband-hr-monitors",
    "Optical arm/forearm sensors when chest straps are uncomfortable.",
    20,
  ),
  sub(
    "sub-hrm-optical",
    "cat-hrm",
    "Optical HR Monitors",
    "optical-hr-monitors",
    "Optical sensors (armband or specialty form factors) as an alternative to ECG straps.",
    30,
  ),
  sub(
    "sub-hrm-dynamics",
    "cat-hrm",
    "Running Dynamics / Advanced Sensor Straps",
    "running-dynamics-straps",
    "Chest straps that unlock running dynamics, power, or advanced Garmin metrics.",
    40,
  ),

  // Clothing IA — inventory-backed lanes only (wave2 populates these)
  sub("sub-running-shorts", "cat-running-clothing", "Running Shorts", "shorts", "Race and training shorts.", 10),
  sub("sub-running-tights", "cat-running-clothing", "Running Tights", "tights", "Full-length and cropped run tights.", 20),
  sub(
    "sub-running-tees",
    "cat-running-clothing",
    "Running T-Shirts",
    "t-shirts",
    "Short-sleeve performance run tees.",
    30,
  ),
  sub(
    "sub-running-singlets",
    "cat-running-clothing",
    "Running Singlets / Tanks",
    "singlets-tanks",
    "Race singlets and training tanks.",
    40,
  ),
  sub(
    "sub-running-long-sleeve",
    "cat-running-clothing",
    "Long-Sleeve Running Tops",
    "long-sleeve-tops",
    "Long-sleeve training and race tops.",
    50,
  ),
  sub("sub-running-jackets", "cat-running-clothing", "Running Jackets", "jackets", "Wind shells and soft weather jackets.", 60),
  sub(
    "sub-running-rain-jackets",
    "cat-running-clothing",
    "Running Rain Jackets",
    "rain-jackets",
    "Waterproof and highly water-resistant run shells.",
    70,
  ),
  sub("sub-running-vests-apparel", "cat-running-clothing", "Running Vests", "vests", "Insulated and wind vests for running.", 80),
  sub("sub-running-base", "cat-running-clothing", "Base Layers", "base-layers", "Baselayers for cold training.", 90),
  sub("sub-running-underwear", "cat-running-clothing", "Running Underwear", "underwear", "Run-specific briefs and boxers.", 100),
  sub(
    "sub-running-sports-bras",
    "cat-running-clothing",
    "Sports Bras",
    "sports-bras",
    "Run-specific sports bras and crop supports.",
    110,
  ),
  sub("sub-running-caps", "cat-running-clothing", "Running Hats / Caps", "hats-caps", "Caps, visors and run beanies.", 120),
  sub("sub-running-gloves", "cat-running-clothing", "Gloves", "gloves", "Cold-weather running gloves.", 130),

  // Packs, vests & carry (inventory-backed; hydration vests shared — no duplicate products)
  sub(
    "sub-pack-hydration-vests",
    "cat-packs-vests",
    "Hydration Vests",
    "hydration-vests",
    "Soft-flask and reservoir race/trail vests.",
    10,
  ),
  sub(
    "sub-pack-race-vests",
    "cat-packs-vests",
    "Race Vests",
    "race-vests",
    "Low-bounce race-day vests — often the same products as hydration vests.",
    20,
  ),
  sub(
    "sub-pack-running-backpacks",
    "cat-packs-vests",
    "Running Backpacks",
    "running-backpacks",
    "Vest-harness daypacks for trail days and high-capacity carry.",
    30,
  ),
  sub(
    "sub-pack-fastpacking",
    "cat-packs-vests",
    "Fastpacking Packs",
    "fastpacking-packs",
    "Run-capable overnight and multi-day packs (≈15–40 L).",
    40,
  ),
  sub(
    "sub-pack-pole-quivers",
    "cat-packs-vests",
    "Pole Quivers",
    "pole-quivers",
    "Add-on or integrated quivers for trail poles.",
    50,
  ),
  sub(
    "sub-pack-accessory-pouches",
    "cat-packs-vests",
    "Accessory Pouches",
    "accessory-pouches",
    "Bolt-on phone, gel and stash pouches for vests and belts.",
    60,
  ),

  // Running belts
  sub(
    "sub-belt-phone",
    "cat-running-belts",
    "Phone / Essentials Belts",
    "phone-belts",
    "Minimal waist belts for phone, keys and gels.",
    10,
  ),
  sub(
    "sub-belt-hydration",
    "cat-running-belts",
    "Hydration Belts",
    "hydration-belts",
    "Waist belts and packs that carry bottles or soft flasks.",
    20,
  ),
  sub(
    "sub-belt-race",
    "cat-running-belts",
    "Race Belts",
    "race-belts",
    "Low-profile race belts for bibs, gels and minimal fuel.",
    30,
  ),

  // Hydration consumables & carry (cat-hydration)
  sub("sub-handheld", "cat-hydration", "Handheld Bottles", "handhelds", "Handheld bottles and soft-flask sleeves.", 10),
  sub("sub-soft-flasks", "cat-hydration", "Soft Flasks", "soft-flasks", "Soft flasks for vests, belts and handhelds.", 20),
  sub(
    "sub-reservoirs",
    "cat-hydration",
    "Hydration Bladders / Reservoirs",
    "reservoirs",
    "Rear reservoirs for bladder-compatible vests and packs.",
    30,
  ),

  // Headphones (cat-headphones)
  sub(
    "sub-hp-open-ear",
    "cat-headphones",
    "Open-Ear Headphones",
    "open-ear",
    "Open-ear designs that leave the ear canal mostly free.",
    10,
  ),
  sub(
    "sub-hp-bone-conduction",
    "cat-headphones",
    "Bone Conduction Headphones",
    "bone-conduction",
    "Bone-conduction transducers for open-ear awareness.",
    20,
  ),
  sub(
    "sub-hp-true-wireless",
    "cat-headphones",
    "True Wireless Earbuds",
    "true-wireless",
    "Fully wireless in-ear or sport TWS earbuds.",
    30,
  ),
  sub(
    "sub-hp-ear-hook",
    "cat-headphones",
    "Ear-Hook Headphones",
    "ear-hook",
    "Ear-hook or clip-on secure-fit sport headphones.",
    40,
  ),

  // Sunglasses (cat-sunglasses)
  sub(
    "sub-sg-performance-wrap",
    "cat-sunglasses",
    "Performance Wrap",
    "performance-wrap",
    "Wrapped sport frames for road and trail coverage.",
    10,
  ),
  sub(
    "sub-sg-shield",
    "cat-sunglasses",
    "Shield / Race",
    "shield-race",
    "Shield and race-oriented sport eyewear.",
    20,
  ),
  sub(
    "sub-sg-photochromic",
    "cat-sunglasses",
    "Photochromic",
    "photochromic",
    "Lenses that adapt across mixed light.",
    30,
  ),
  sub(
    "sub-sg-everyday-value",
    "cat-sunglasses",
    "Everyday / Value",
    "everyday-value",
    "Affordable daily training sunglasses.",
    40,
  ),

  // Running lights / headlamps (cat-running-lights)
  sub(
    "sub-light-headlamps",
    "cat-running-lights",
    "Headlamps",
    "headlamps",
    "Forehead-mounted running and trail headlamps.",
    10,
  ),
  sub(
    "sub-light-waist",
    "cat-running-lights",
    "Waist / Hybrid Lights",
    "waist-hybrid-lights",
    "Waist-belt or hybrid body-worn run lights.",
    20,
  ),
  sub(
    "sub-light-high-output",
    "cat-running-lights",
    "High-Output Headlamps",
    "high-output-headlamps",
    "High-lumen lamps for technical night trail and ultra.",
    30,
  ),

  // Safety / visibility (cat-safety)
  sub(
    "sub-safety-clip-lights",
    "cat-safety",
    "Clip Lights",
    "clip-lights",
    "Clip-on LED lights for clothing and packs.",
    10,
  ),
  sub(
    "sub-safety-wearable-lights",
    "cat-safety",
    "Wearable Lights",
    "wearable-lights",
    "Armband, shoe and body-worn visibility lights.",
    20,
  ),
  sub(
    "sub-safety-reflective",
    "cat-safety",
    "Reflective Gear",
    "reflective-gear",
    "Reflective bands, strips and soft visibility accessories.",
    30,
  ),
  sub(
    "sub-safety-visibility-vests",
    "cat-safety",
    "Visibility Vests",
    "visibility-vests",
    "Reflective and illuminated running visibility vests.",
    40,
  ),
  sub(
    "sub-safety-personal-alarms",
    "cat-safety",
    "Personal Alarms",
    "personal-alarms",
    "Legal personal safety alarms for runners — not weapons.",
    50,
  ),

  // Recovery gear (evidence-aware product coverage — no unsupported medical claims)
  sub(
    "sub-rec-foam-rollers",
    "cat-recovery-gear",
    "Foam Rollers",
    "foam-rollers",
    "Foam rollers for self-myofascial work after training.",
    10,
  ),
  sub(
    "sub-rec-massage-guns",
    "cat-recovery-gear",
    "Massage Guns",
    "massage-guns",
    "Percussive massage devices for targeted post-run muscle work.",
    20,
  ),
  sub(
    "sub-rec-massage-balls",
    "cat-recovery-gear",
    "Massage Balls",
    "massage-balls",
    "Massage balls and peanut rollers for feet, glutes and small areas.",
    30,
  ),
  sub(
    "sub-rec-compression-boots",
    "cat-recovery-gear",
    "Compression Boots",
    "compression-boots",
    "Pneumatic compression boot systems for legs.",
    40,
  ),
  sub(
    "sub-rec-recovery-sandals",
    "cat-recovery-gear",
    "Recovery Sandals",
    "recovery-sandals",
    "Cushioned recovery sandals and slides for easy walking days.",
    50,
  ),
  sub(
    "sub-rec-compression-garments",
    "cat-recovery-gear",
    "Compression Garments",
    "compression-garments",
    "Recovery-oriented compression sleeves and garments.",
    60,
  ),
  sub(
    "sub-rec-mobility-tools",
    "cat-recovery-gear",
    "Mobility Tools",
    "mobility-tools",
    "Sticks, rods and other mobility tools for soft-tissue work.",
    70,
  ),

  // Nutrition / race fuel (sports products — factual label data only; no medical claims)
  sub("sub-energy-gels", "cat-nutrition", "Energy Gels", "energy-gels", "Single-serve energy gels for training and racing.", 10),
  sub("sub-energy-chews", "cat-nutrition", "Energy Chews", "energy-chews", "Chewable carbohydrate fuel for training and racing.", 20),
  sub("sub-energy-bars", "cat-nutrition", "Energy Bars", "energy-bars", "Portable energy bars for long runs and ultras.", 30),
  sub(
    "sub-sports-drinks",
    "cat-nutrition",
    "Sports Drinks",
    "sports-drinks",
    "Ready-to-drink or bottle sports beverages with carbs and/or electrolytes.",
    40,
  ),
  sub(
    "sub-electrolyte-mixes",
    "cat-nutrition",
    "Electrolyte Drink Mixes",
    "electrolyte-drink-mixes",
    "Powdered electrolyte drink mixes (lower carb focus).",
    50,
  ),
  sub(
    "sub-carb-drink-mixes",
    "cat-nutrition",
    "Carbohydrate Drink Mixes",
    "carbohydrate-drink-mixes",
    "Higher-carb drink mixes for bottle or flask fueling.",
    60,
  ),
  sub(
    "sub-electrolyte-tablets",
    "cat-nutrition",
    "Electrolyte Tablets",
    "electrolyte-tablets",
    "Effervescent or tablet electrolytes for bottles.",
    70,
  ),
  sub(
    "sub-race-fuel",
    "cat-nutrition",
    "Race Fuel Systems",
    "race-fuel",
    "High-carb race fuel formats designed for structured endurance fueling.",
    80,
  ),

  sub(
    "sub-acc-stick-balm",
    "cat-accessories",
    "Anti-Chafe Sticks",
    "anti-chafe-sticks",
    "Stick balms you can apply on the move without a bottle.",
    10,
  ),
  sub(
    "sub-acc-roll-on",
    "cat-accessories",
    "Anti-Chafe Roll-Ons",
    "anti-chafe-roll-ons",
    "Liquid roll-on barriers for thin coverage under tight kits.",
    20,
  ),

  ...fitnessSubcategories,
];
