import type { ProductResearchConfig } from "@/domain/onboarding/types";

export const runningShoesResearchConfig: ProductResearchConfig = {
  categoryId: "cat-running-shoes",
  categorySlug: "running-shoes",
  sportId: "sport-running",
  identityFields: [
    "brand",
    "family",
    "generation",
    "model",
    "lifecycle",
    "releaseDate",
  ],
  requiredSpecs: [
    "drop",
    "cushionLevel",
    "stability",
    "terrain",
    "plateMaterial",
  ],
  importantSpecs: [
    "weight",
    "heelStack",
    "forefootStack",
    "midsole",
    "upper",
    "outsole",
    "plate",
    "widthOptions",
  ],
  optionalSpecs: [
    "lugDepth",
    "rockPlate",
    "waterproof",
    "raceLegal",
    "recommendedDistance",
  ],
  recommendationContexts: [
    "uc-daily-training",
    "uc-easy-runs",
    "uc-long-runs",
    "uc-tempo-runs",
    "uc-recovery-runs",
    "uc-5k",
    "uc-10k",
    "uc-half",
    "uc-marathon",
    "uc-trail-training",
  ],
  mediaRequirements: ["hero", "side"],
  trustedSourcePatterns: [
    "asics.com",
    "nike.com",
    "adidas.com",
    "brooksrunning.com",
    "hoka.com",
    "saucony.com",
    "newbalance.com",
    "on.com",
    "salomon.com",
    "mizuno.com",
    "altra.com",
  ],
  outlierBounds: {
    weight: { min: 120, max: 450, unit: "g" },
    drop: { min: 0, max: 16, unit: "mm" },
    heelStack: { min: 10, max: 55, unit: "mm" },
    forefootStack: { min: 8, max: 50, unit: "mm" },
  },
};

export const gpsWatchesResearchConfig: ProductResearchConfig = {
  categoryId: "cat-gps-watches",
  categorySlug: "gps-watches",
  sportId: "sport-running",
  identityFields: ["brand", "family", "generation", "model", "lifecycle"],
  requiredSpecs: ["displayType", "multiBandGps", "heartRate"],
  importantSpecs: [
    "weight",
    "batterySmartwatch",
    "batteryGps",
    "batteryMultiBand",
    "maps",
    "music",
    "waterRating",
  ],
  optionalSpecs: ["ecg", "spo2", "payments", "dimensions"],
  recommendationContexts: [],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [
    "garmin.com",
    "coros.com",
    "polar.com",
    "suunto.com",
    "apple.com",
  ],
  outlierBounds: {
    weight: { min: 20, max: 120, unit: "g" },
    batteryGps: { min: 5, max: 200, unit: "h" },
  },
};

/** Non-Running fixture proving pipeline is category-plugin based */
export const padelRacketsResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-rackets",
  categorySlug: "padel-rackets",
  sportId: "sport-padel",
  identityFields: ["brand", "family", "generation", "model", "lifecycle"],
  requiredSpecs: ["shape", "balance", "weightMin"],
  importantSpecs: [
    "weightMax",
    "thicknessMm",
    "core",
    "face",
    "faceMaterial",
    "frameMaterial",
    "surfaceTexture",
    "playerLevel",
  ],
  optionalSpecs: [
    "sweetSpot",
    "feel",
    "faceCarbonWeave",
    "manufacturerCoreName",
    "manufacturerPositioning",
    "technologies",
  ],
  recommendationContexts: [
    "uc-padel-beginner",
    "uc-padel-intermediate",
    "uc-padel-advanced",
    "uc-padel-control",
    "uc-padel-balanced",
    "uc-padel-power",
    "uc-padel-arm-comfort",
    "uc-padel-easy-power",
    "uc-padel-maneuverability",
    "uc-padel-maximum-power",
  ],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [
    "bullpadel.com",
    "noxsport.com",
    "noxpadel.com",
    "babolat.com",
    "head.com",
    "allforpadel.com",
    "siuxpadel.com",
    "wilson.com",
    "starvie.com",
    "decathlon.nl",
    "decathlon.com",
    "tecnifibre.com",
    "varlion.com",
  ],
  outlierBounds: {
    weight: { min: 300, max: 400, unit: "g" },
    weightMin: { min: 300, max: 400, unit: "g" },
    thicknessMm: { min: 36, max: 40, unit: "mm" },
  },
};

const PADEL_TRUSTED_SOURCES = [
  "bullpadel.com",
  "noxsport.com",
  "noxpadel.com",
  "babolat.com",
  "head.com",
  "allforpadel.com",
  "siuxpadel.com",
  "wilson.com",
  "starvie.com",
  "decathlon.nl",
  "decathlon.com",
  "tecnifibre.com",
  "varlion.com",
  "asics.com",
  "adidas.com",
  "joma-sport.com",
] as const;

/** Court shoes — padel-evidenced SKUs only. Never onboard running shoes. */
export const padelShoesResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-shoes",
  categorySlug: "padel-shoes",
  sportId: "sport-padel",
  identityFields: ["brand", "model", "lifecycle", "genderFit"],
  requiredSpecs: ["surfaceCompatibility"],
  importantSpecs: [
    "courtOutsole",
    "outsole",
    "lateralStability",
    "cushioning",
    "support",
    "genderFit",
  ],
  optionalSpecs: [
    "tractionPattern",
    "courtFeel",
    "durability",
    "weight",
    "upper",
    "fit",
    "width",
  ],
  recommendationContexts: [
    "uc-padel-beginner",
    "uc-padel-intermediate",
    "uc-padel-advanced",
    "uc-padel-competitive",
  ],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [...PADEL_TRUSTED_SOURCES],
  outlierBounds: {
    weight: { min: 250, max: 450, unit: "g" },
  },
};

export const padelBallsResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-balls",
  categorySlug: "padel-balls",
  sportId: "sport-padel",
  identityFields: ["brand", "model", "lifecycle"],
  requiredSpecs: ["use", "pressurization", "packSize"],
  importantSpecs: [
    "speed",
    "durability",
    "officialApproval",
    "ballType",
    "ballsPerCan",
  ],
  optionalSpecs: [
    "ballPositioning",
    "generation",
    "freshnessStatus",
    "cansPerBox",
    "feltMaterial",
    "coreMaterial",
    "diameter",
    "weight",
    "bounceSpec",
    "intendedConditions",
    "manufacturerPositioning",
  ],
  recommendationContexts: ["uc-padel-beginner", "uc-padel-competitive"],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [...PADEL_TRUSTED_SOURCES],
  outlierBounds: {},
};

export const padelBagsResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-bags",
  categorySlug: "padel-bags",
  sportId: "sport-padel",
  identityFields: ["brand", "model", "lifecycle"],
  requiredSpecs: ["form"],
  importantSpecs: [
    "capacity",
    "racketCompartments",
    "shoeCompartment",
    "thermalProtection",
  ],
  optionalSpecs: [
    "dimensions",
    "carryStyle",
    "volume",
    "racketCapacity",
    "thermalRacketCompartment",
    "wetCompartment",
    "accessoryPockets",
    "laptopCompartment",
    "bottleStorage",
    "carrySystem",
    "backpackStraps",
    "handles",
    "materials",
    "waterResistance",
    "colorVariants",
  ],
  recommendationContexts: ["uc-padel-beginner", "uc-padel-competitive"],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [...PADEL_TRUSTED_SOURCES],
  outlierBounds: {},
};

export const padelGripsResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-grips",
  categorySlug: "padel-grips",
  sportId: "sport-padel",
  identityFields: ["brand", "model", "lifecycle"],
  requiredSpecs: ["gripType"],
  importantSpecs: ["thickness", "tack", "absorption", "packQuantity"],
  optionalSpecs: [
    "feel",
    "material",
    "perforated",
    "texture",
    "length",
    "width",
    "weight",
    "colors",
    "function",
    "installationMethod",
    "handleThicknessEffect",
    "claimedBenefits",
  ],
  recommendationContexts: ["uc-padel-beginner", "uc-padel-competitive"],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [...PADEL_TRUSTED_SOURCES, "hesacore.com"],
  outlierBounds: {},
};

export const padelAccessoriesResearchConfig: ProductResearchConfig = {
  categoryId: "cat-padel-accessories",
  categorySlug: "padel-accessories",
  sportId: "sport-padel",
  identityFields: ["brand", "model", "lifecycle", "type"],
  requiredSpecs: ["type"],
  importantSpecs: [
    "compatibility",
    "capacityBalls",
    "manualOrElectric",
    "pressureSystem",
    "weightGrams",
  ],
  optionalSpecs: [
    "pressureRange",
    "powerSource",
    "transparentOrColored",
    "materials",
    "installationMethod",
    "generation",
  ],
  recommendationContexts: ["uc-padel-beginner", "uc-padel-competitive"],
  mediaRequirements: ["hero"],
  trustedSourcePatterns: [
    ...PADEL_TRUSTED_SOURCES,
    "pascalbox.com",
    "tubo.plus",
    "ballrescuer.com",
  ],
  outlierBounds: {},
};

const BY_CATEGORY: Record<string, ProductResearchConfig> = {
  "cat-running-shoes": runningShoesResearchConfig,
  "running-shoes": runningShoesResearchConfig,
  "cat-gps-watches": gpsWatchesResearchConfig,
  "gps-watches": gpsWatchesResearchConfig,
  "cat-padel-rackets": padelRacketsResearchConfig,
  "padel-rackets": padelRacketsResearchConfig,
  "cat-padel-shoes": padelShoesResearchConfig,
  "padel-shoes": padelShoesResearchConfig,
  "cat-padel-balls": padelBallsResearchConfig,
  "padel-balls": padelBallsResearchConfig,
  "cat-padel-bags": padelBagsResearchConfig,
  "padel-bags": padelBagsResearchConfig,
  "cat-padel-grips": padelGripsResearchConfig,
  "padel-grips": padelGripsResearchConfig,
  "cat-padel-accessories": padelAccessoriesResearchConfig,
  "padel-accessories": padelAccessoriesResearchConfig,
};

export function getProductResearchConfig(
  categoryIdOrSlug: string,
): ProductResearchConfig | undefined {
  return BY_CATEGORY[categoryIdOrSlug];
}

export function listProductResearchConfigs(): ProductResearchConfig[] {
  return [
    runningShoesResearchConfig,
    gpsWatchesResearchConfig,
    padelRacketsResearchConfig,
    padelShoesResearchConfig,
    padelBallsResearchConfig,
    padelBagsResearchConfig,
    padelGripsResearchConfig,
    padelAccessoriesResearchConfig,
  ];
}
