import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 Running Accessories — gap-fill for cat-accessories (wave1 only had Buff + Body Glide;
 * CEP calf sleeves live under recovery).
 *
 * Media draft until authentic heroes land. Claim-safe: comfort / preference language only.
 */
export const runningAccessoriesWave2Raw: Product[] = [
  // ─── BUFF neckwear ───────────────────────────────────────────────────────
  {
    id: "prod-buff-coolnet-uv",
    slug: "buff-coolnet-uv",
    brandId: "brand-buff",
    familyId: "fam-buff-neckwear",
    generation: "CoolNet UV+",
    name: "CoolNet UV+",
    fullName: "BUFF CoolNet UV+ Multifunctional Neckwear",
    shortDescription:
      "Hot-weather Buff tube (~37 g CoolNet fabric, UPF 50 rating) for sweat, dust and sun on bright road and trail days — not a winter insulator.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-caps"],
    useCaseIds: ["uc-trail-training", "uc-daily-training", "uc-long-runs", "uc-bright-sun"],
    specifications: {
      genderFit: "unisex",
      type: "neck-gaiter",
      material: "95% recycled polyester / 5% elastane (CoolNet)",
      weight: 37,
      fit: "fitted",
      weather: ["hot", "mild"],
      temperatureSuitability: ["hot", "mild"],
      season: ["spring", "summer"],
      breathability: "high",
      packability: "packable",
      windResistance: "none",
      waterResistance: "none",
      compression: false,
      pockets: false,
      reflective: false,
      antiChafe: true,
      seams: "Seamless tubular",
      upf: "UPF 50 (AS/NZS 4399; CoolNet UV+ fabric)",
      care: "Machine wash 40°C; do not tumble dry",
      sizeRange: "One size; ~53 × 22.5 cm tube",
    },
    strengths: [
      "Lightest Buff in this family (~37 g) for hot miles",
      "Manufacturer UPF 50 fabric rating on CoolNet UV+",
      "Packs into a pocket and still covers neck, face or head",
    ],
    weaknesses: [
      "No warmth story for winter or freezing starts",
      "UPF 50 is a fabric rating — coverage depends on how you wear it",
    ],
    recommendationScore: 82,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-buff-coolnet-uv",
      "BUFF CoolNet UV+ — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-buff-original",
      "prod-buff-merino-lightweight",
      "prod-buff-polar",
    ],
    alternativeProductIds: [
      "prod-buff-original",
      "prod-buff-merino-lightweight",
    ],
    ...pub,
  },
  {
    id: "prod-buff-merino-lightweight",
    slug: "buff-merino-lightweight",
    brandId: "brand-buff",
    familyId: "fam-buff-neckwear",
    generation: "Lightweight Merino Wool",
    name: "Lightweight Merino Wool",
    fullName: "BUFF Lightweight Merino Wool Multifunctional Neckwear",
    shortDescription:
      "100% merino Buff tube (~48 g, 125 g/m²) for cool mornings and shoulder-season trail — odor-resistant warmth without Polar fleece bulk.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-caps"],
    useCaseIds: ["uc-trail-training", "uc-winter-running", "uc-long-runs", "uc-daily-training"],
    specifications: {
      genderFit: "unisex",
      type: "neck-gaiter",
      material: "100% merino wool (125 g/m² Lightweight Merino)",
      weight: 48,
      fit: "fitted",
      weather: ["mild", "cold"],
      temperatureSuitability: ["mild", "cold"],
      season: ["autumn", "winter", "spring"],
      breathability: "moderate",
      packability: "packable",
      windResistance: "none",
      waterResistance: "none",
      compression: false,
      pockets: false,
      reflective: false,
      antiChafe: true,
      seams: "Seamless tubular",
      care: "Hand wash; do not tumble dry",
      sizeRange: "One size; ~57 cm tube",
    },
    strengths: [
      "Merino odor resistance on multi-day cool-weather trips",
      "Warmer than CoolNet without Polar’s fleece bulk",
      "Same multi-wear tube (neck, face, headband) as Original",
    ],
    weaknesses: [
      "Too warm as a face cover on hot climbs",
      "Hand-wash care vs 40°C machine-wash synthetics",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-buff-merino-lightweight",
      "BUFF Lightweight Merino Wool — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-buff-original",
      "prod-buff-coolnet-uv",
      "prod-buff-polar",
    ],
    alternativeProductIds: [
      "prod-buff-polar",
      "prod-buff-coolnet-uv",
      "prod-buff-original",
    ],
    ...pub,
  },
  {
    id: "prod-buff-polar",
    slug: "buff-polar",
    brandId: "brand-buff",
    familyId: "fam-buff-neckwear",
    generation: "Polar",
    name: "Polar",
    fullName: "BUFF Polar Multifunctional Neckwear",
    shortDescription:
      "Longer fleece-backed Buff (~66 g, ~76 cm) for cold and windy road or trail — PrimaLoft Bio lining when CoolNet or Lightweight Merino is not enough.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-caps"],
    useCaseIds: ["uc-winter-running", "uc-daily-training", "uc-commute-running"],
    specifications: {
      genderFit: "unisex",
      type: "neck-gaiter",
      material: "Original EcoStretch + PrimaLoft Bio fleece lining",
      weight: 66,
      fit: "fitted",
      weather: ["cold"],
      temperatureSuitability: ["cold", "frigid"],
      season: ["winter"],
      breathability: "moderate",
      packability: "pocket-stow",
      windResistance: "wind-resistant",
      waterResistance: "none",
      compression: false,
      pockets: false,
      reflective: false,
      antiChafe: true,
      seams: "Seamless tubular with fleece panel",
      care: "Machine wash 40°C; do not tumble dry",
      sizeRange: "One size; ~76 cm tube (longer than Original)",
    },
    strengths: [
      "Warmest tube in this Buff family for winter mornings",
      "Fleece lining plus longer tube for face and neck coverage",
      "Still a stretch tubular — not a bulky balaclava",
    ],
    weaknesses: [
      "Too warm once the day is mild or the workout is hard",
      "Bulkier in a pocket than CoolNet or Original",
    ],
    recommendationScore: 78,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-buff-polar",
      "BUFF Polar — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-buff-merino-lightweight",
      "prod-buff-coolnet-uv",
      "prod-buff-original",
    ],
    alternativeProductIds: [
      "prod-buff-merino-lightweight",
      "prod-buff-original",
      "prod-buff-coolnet-uv",
    ],
    ...pub,
  },

  // ─── Arm sleeves (Compressport — CEP calf lives in recovery) ─────────────
  {
    id: "prod-compressport-armforce",
    slug: "compressport-armforce",
    brandId: "brand-compressport",
    generation: "ArmForce",
    name: "ArmForce Ultralight",
    fullName: "Compressport ArmForce Ultralight Arm Sleeves",
    shortDescription:
      "Light arm sleeves for sun coverage, early-start chill, and race-kit packing — comfort/preference apparel, not an injury-prevention or medical claim.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-accessories",
    subcategoryIds: [],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-trail-training", "uc-bright-sun"],
    specifications: {
      type: "arm-sleeve",
      material: "Compressport knit (verify current)",
      weight: null,
      weather: ["hot", "mild", "cold"],
      compression: true,
      waterResistance: "none",
    },
    strengths: [
      "Easy on/off when mornings warm up",
      "Sun and light-chill coverage without long sleeves",
      "Packs tiny for race and travel kits",
    ],
    weaknesses: [
      "Must size carefully for comfort",
      "Warm on truly hot mid-day blocks",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 76,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-compressport-armforce",
      "Compressport ArmForce Ultralight — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-compressport-r2",
      "prod-buff-coolnet-uv",
      "prod-body-glide-original",
    ],
    alternativeProductIds: ["prod-buff-coolnet-uv"],
    ...pub,
  },

  // ─── Anti-chafe ──────────────────────────────────────────────────────────
  {
    id: "prod-squirrels-nut-butter",
    slug: "squirrels-nut-butter",
    brandId: "brand-squirrels-nut-butter",
    generation: "Original",
    name: "Original Anti-Chafe",
    fullName: "Squirrel's Nut Butter Original Anti-Chafe Balm",
    shortDescription:
      "Stick and tin anti-chafe balm popular with ultra and long-run athletes — an alternative texture/feel to Body Glide for skin rub on long efforts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-accessories",
    subcategoryIds: ["sub-acc-stick-balm"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-ultra", "uc-half"],
    specifications: {
      type: "anti-chafe",
      material: "Balm (stick / tin formats)",
      weight: null,
      waterResistance: "water-resistant",
      compression: false,
    },
    strengths: [
      "Cult ultra favorite alongside Body Glide",
      "Stick and tin formats for kit preference",
      "Simple pre-run skin prep staple",
    ],
    weaknesses: [
      "Some athletes prefer stick-only Body Glide ergonomics",
      "Needs reapplication on very long efforts for some runners",
    ],
    recommendationScore: 84,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-squirrels-nut-butter",
      "Squirrel's Nut Butter Original — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-body-glide-original",
      "prod-2toms-sportshield",
    ],
    alternativeProductIds: [
      "prod-body-glide-original",
      "prod-2toms-sportshield",
    ],
    ...pub,
  },
  {
    id: "prod-2toms-sportshield",
    slug: "2toms-sportshield",
    brandId: "brand-2toms",
    generation: "SportShield",
    name: "SportShield",
    fullName: "2Toms SportShield Anti-Chafe Roll-On",
    shortDescription:
      "Roll-on anti-chafe barrier for long runs and race day — liquid application alternative when stick balms feel messy or you want thin coverage under apparel.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-accessories",
    subcategoryIds: ["sub-acc-roll-on"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-half", "uc-ultra"],
    specifications: {
      type: "anti-chafe",
      material: "Roll-on liquid barrier",
      weight: null,
      waterResistance: "water-resistant",
      compression: false,
    },
    strengths: [
      "Roll-on application for thin, even coverage",
      "Useful under race kits and seams",
      "Travel-friendly bottle vs open tin balms",
    ],
    weaknesses: [
      "Less ‘grab and go’ than a stick for some kits",
      "May need dry-time before pulling on tight apparel",
    ],
    recommendationScore: 81,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-2toms-sportshield",
      "2Toms SportShield — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-body-glide-original",
      "prod-squirrels-nut-butter",
    ],
    alternativeProductIds: [
      "prod-body-glide-original",
      "prod-squirrels-nut-butter",
    ],
    ...pub,
  },

  // ─── Reflective armband ──────────────────────────────────────────────────
  {
    id: "prod-amphipod-reflective-armband",
    slug: "amphipod-reflective-armband",
    brandId: "brand-amphipod",
    generation: "Reflective",
    name: "Reflective Armband",
    fullName: "Amphipod Reflective Armband",
    shortDescription:
      "Simple high-visibility armband for night and winter road miles — passive reflective accessory when you want a light add-on without a full vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-accessories",
    subcategoryIds: [],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training"],
    specifications: {
      type: "reflective",
      material: "Reflective fabric / elastic band",
      weight: null,
      weather: ["mild", "cold", "wet"],
      waterResistance: "water-resistant",
      compression: false,
    },
    strengths: [
      "Low-bulk night visibility add-on",
      "Works over sleeves or bare arms",
      "Cheaper / lighter than a full reflective vest",
    ],
    weaknesses: [
      "Passive only — no active LED",
      "Less 360° coverage than a sash or vest",
    ],
    recommendationScore: 75,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-amphipod-reflective-armband",
      "Amphipod Reflective Armband — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-xinglet",
      "prod-nathan-reflective-vest",
      "prod-nite-ize-radiant-clip",
    ],
    alternativeProductIds: [
      "prod-amphipod-xinglet",
      "prod-nathan-reflective-vest",
    ],
    ...pub,
  },

  // ─── Trail gaiters ───────────────────────────────────────────────────────
  {
    id: "prod-dirty-girl-gaiters",
    slug: "dirty-girl-gaiters",
    brandId: "brand-dirty-girl",
    generation: "Classic",
    name: "Gaiters",
    fullName: "Dirty Girl Gaiters",
    shortDescription:
      "Lightweight trail gaiters that keep grit and debris out of shoes — colorful, packable debris barriers for rocky and sandy singletrack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-accessories",
    subcategoryIds: [],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      type: "gaiter",
      material: "Lightweight stretch fabric",
      weight: null,
      weather: ["hot", "mild", "dry"],
      waterResistance: "none",
      compression: false,
    },
    strengths: [
      "Cult trail staple for debris control",
      "Very light vs hiking gaiters",
      "Wide print options if you care about kit personality",
    ],
    weaknesses: [
      "Not waterproof storm gaiters",
      "Attachment method varies by shoe eyelets / lace setup",
    ],
    recommendationScore: 83,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-dirty-girl-gaiters",
      "Dirty Girl Gaiters — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-outdoor-research-ferrosi-gaiters",
      "prod-buff-coolnet-uv",
    ],
    alternativeProductIds: ["prod-outdoor-research-ferrosi-gaiters"],
    ...pub,
  },
  {
    id: "prod-outdoor-research-ferrosi-gaiters",
    slug: "outdoor-research-ferrosi-gaiters",
    brandId: "brand-outdoor-research",
    generation: "Ferrosi",
    name: "Ferrosi Thru Gaiters",
    fullName: "Outdoor Research Ferrosi Thru Gaiters",
    shortDescription:
      "Stretch Ferrosi fabric trail gaiters for grit and brush — a more technical Outdoor Research option when Dirty Girl’s ultralight prints are not the priority.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-accessories",
    subcategoryIds: [],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      type: "gaiter",
      material: "Ferrosi stretch woven",
      weight: null,
      weather: ["mild", "wet", "cold"],
      waterResistance: "water-resistant",
      compression: false,
    },
    strengths: [
      "More durable stretch fabric than ultralight print gaiters",
      "Familiar Outdoor Research trail build",
      "Better brush/abrasion feel for rough singletrack",
    ],
    weaknesses: [
      "Heavier / warmer than Dirty Girl-style ultralights",
      "Overkill for smooth gravel roads",
    ],
    recommendationScore: 79,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-outdoor-research-ferrosi-gaiters",
      "Outdoor Research Ferrosi Thru Gaiters — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-dirty-girl-gaiters",
      "prod-buff-coolnet-uv",
    ],
    alternativeProductIds: ["prod-dirty-girl-gaiters"],
    ...pub,
  },

  // ─── Phone armband ───────────────────────────────────────────────────────
  {
    id: "prod-amphipod-airflow-armband",
    slug: "amphipod-airflow-armband",
    brandId: "brand-amphipod",
    generation: "AirFlow",
    name: "AirFlow Phone Armband",
    fullName: "Amphipod AirFlow Phone Armband",
    shortDescription:
      "Breathable phone armband for runners who want phone carry off the waist — an arm-mounted alternative when FlipBelt / SPIbelt bounce or fit is not preferred.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill"],
    categoryId: "cat-accessories",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-commute-running", "uc-beginners"],
    specifications: {
      type: "phone-holder",
      material: "Mesh / stretch armband",
      weight: null,
      weather: ["hot", "mild"],
      waterResistance: "none",
      compression: false,
    },
    strengths: [
      "Keeps phone off the waist for belt-sensitive runners",
      "Screen-access friendly for music / maps glances",
      "Pairs well with minimal shorts that lack pockets",
    ],
    weaknesses: [
      "Can bounce or chafe if sized poorly",
      "Sweat can reach phone without a case on hot days",
      "Less race-kit elegant than a FlipBelt or SPIbelt for many",
    ],
    recommendationScore: 72,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-amphipod-airflow-armband",
      "Amphipod AirFlow Phone Armband — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-spibelt-original",
      "prod-flipbelt-classic",
      "prod-amphipod-reflective-armband",
    ],
    alternativeProductIds: [
      "prod-spibelt-original",
      "prod-flipbelt-classic",
    ],
    ...pub,
  },
];

/** All wave-2 accessories await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningAccessoriesWave2Raw.map((p) => p.id),
);

export const runningAccessoriesWave2: Product[] = applyMediaPublishGate(runningAccessoriesWave2Raw, MEDIA_PENDING_DRAFT_IDS);
