import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 1 running gear beyond shoes — packs, belts, hydration, apparel, socks,
 * audio, eyewear, lights, safety, recovery, and small accessories.
 */
export const runningGearWave1Raw: Product[] = [
  // ─── Packs & vests ───────────────────────────────────────────────────────
  {
    id: "prod-nathan-vaporair-2",
    slug: "nathan-vaporair-2",
    brandId: "brand-nathan",
    familyId: "fam-nathan-vaporair",
    generation: "2",
    name: "VaporAir 2",
    fullName: "Nathan VaporAir 2",
    shortDescription:
      "Lightweight race vest with soft-flask front pockets for road and trail long runs.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra", "uc-marathon"],
    specifications: {
      capacity: 7,
      weight: 220,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bladderCompatible: false,
      bottleCapacity: 1000,
      phoneStorage: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: true,
      waterResistance: "none",
      fitSystem: "Adjustable sternum + side straps",
      sizeRange: "S–XL",
      storage: "Front soft-flask pockets plus rear stash",
      poleAttachment: false,
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "road", "ultra"],
    },
    strengths: ["Stable bounce-free race fit", "Easy front-flask access"],
    weaknesses: ["Less total volume than larger adventure vests"],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-nathan-vaporair-2",
      "Nathan VaporAir 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-ud-adventure-vest", "prod-camelbak-zephyr", "prod-nathan-exoshot"],
    alternativeProductIds: ["prod-osprey-duro-6", "prod-ud-adventure-vest"],
    ...pub,
  },
  {
    id: "prod-ud-adventure-vest",
    slug: "ultimate-direction-adventure-vest",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-race-vest",
    generation: "5",
    name: "Adventure Vest",
    fullName: "Ultimate Direction Adventure Vest",
    shortDescription:
      "Versatile trail vest with expandable storage for long days and mountain efforts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 12,
      weight: 280,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bladderCompatible: true,
      bottleCapacity: 1000,
      phoneStorage: true,
      bounceControl: "high",
      breathability: "moderate",
      reflectivity: false,
      whistle: true,
      waterResistance: "none",
      raceKitCapacity: true,
      quiverCompatible: true,
      fitSystem: "Comfort Cinch",
      sizeRange: "S–L",
      storage: "Front pockets, rear compartment, trekking-pole loops",
      poleAttachment: true,
      sizing: "S–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: ["Expandable adventure capacity", "Pole attachment options"],
    weaknesses: ["Can feel busy for short road races"],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-adventure-vest",
      "Ultimate Direction Adventure Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nathan-vaporair-2", "prod-osprey-duro-6", "prod-camelbak-zephyr"],
    alternativeProductIds: ["prod-camelbak-zephyr", "prod-nathan-vaporair-2"],
    ...pub,
  },
  {
    id: "prod-camelbak-zephyr",
    slug: "camelbak-zephyr",
    brandId: "brand-camelbak",
    generation: "Zephyr",
    name: "Zephyr",
    fullName: "CamelBak Zephyr",
    shortDescription:
      "Breathable running vest with Crux reservoir compatibility for long trail days.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 10,
      weight: 260,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2000,
      bladderCompatible: true,
      bottleCapacity: 1000,
      phoneStorage: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: true,
      waterResistance: "none",
      raceKitCapacity: true,
      fitSystem: "Ventilated harness",
      sizeRange: "S–XL",
      storage: "Front stretch pockets and rear reservoir sleeve",
      poleAttachment: true,
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: ["Strong bladder ecosystem", "Ventilated harness feel"],
    weaknesses: ["Reservoir cleaning overhead vs soft flasks"],
    recommendationScore: 81,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-camelbak-zephyr",
      "CamelBak Zephyr — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-ud-adventure-vest", "prod-osprey-duro-6"],
    alternativeProductIds: ["prod-ud-adventure-vest", "prod-nathan-vaporair-2"],
    ...pub,
  },
  {
    id: "prod-osprey-duro-6",
    slug: "osprey-duro-6",
    brandId: "brand-osprey",
    generation: "6",
    name: "Duro 6",
    fullName: "Osprey Duro 6",
    shortDescription:
      "Men’s-fit 6L running pack with Hydraulics reservoir option for long road and trail runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra"],
    specifications: {
      capacity: 6,
      weight: 310,
      includedFlasks: 0,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bladderCompatible: true,
      bottleCapacity: 1000,
      phoneStorage: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      raceKitCapacity: true,
      quiverCompatible: true,
      fitSystem: "BioStretch harness",
      sizeRange: "S–L",
      storage: "Dual soft-flask compatible front pockets and rear compartment",
      poleAttachment: true,
      sizing: "S–L (verify current chart)",
      genderFit: "men",
      raceSuitability: ["trail", "road", "ultra"],
    },
    strengths: ["Stable Osprey harness", "Clear 6L day-run capacity"],
    weaknesses: ["Men’s patterning — Dyna is the women’s counterpart"],
    recommendationScore: 83,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-duro-6",
      "Osprey Duro 6 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-osprey-dyna-6", "prod-nathan-vaporair-2", "prod-camelbak-zephyr"],
    alternativeProductIds: ["prod-osprey-dyna-6", "prod-nathan-vaporair-2"],
    ...pub,
  },
  {
    id: "prod-osprey-dyna-6",
    slug: "osprey-dyna-6",
    brandId: "brand-osprey",
    familyId: "fam-osprey-dyna",
    generation: "6",
    name: "Dyna 6",
    fullName: "Osprey Dyna 6",
    shortDescription:
      "Women’s-fit 6L running pack matched to the Duro platform for long training days.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra"],
    specifications: {
      capacity: 6,
      weight: 300,
      includedFlasks: 0,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bladderCompatible: true,
      bottleCapacity: 1000,
      phoneStorage: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      raceKitCapacity: true,
      quiverCompatible: true,
      fitSystem: "Women-specific BioStretch",
      sizeRange: "XS–L",
      storage: "Dual soft-flask compatible front pockets and rear compartment",
      poleAttachment: true,
      sizing: "XS–L (verify current chart)",
      genderFit: "women",
      raceSuitability: ["trail", "road", "ultra"],
    },
    strengths: ["Women-specific harness shaping", "Same practical 6L layout as Duro"],
    weaknesses: ["Overbuilt for short road races without gear needs"],
    recommendationScore: 83,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-dyna-6",
      "Osprey Dyna 6 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-osprey-duro-6", "prod-ud-adventure-vest"],
    alternativeProductIds: ["prod-osprey-duro-6", "prod-ud-adventure-vest"],
    ...pub,
  },

  // ─── Running belts ───────────────────────────────────────────────────────
  {
    id: "prod-flipbelt-classic",
    slug: "flipbelt-classic",
    brandId: "brand-flipbelt",
    generation: "Classic",
    name: "Classic",
    fullName: "FlipBelt Classic",
    shortDescription:
      "Tubular waist belt for phone, keys, and soft gels without bouncing zippers.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon"],
    specifications: {
      capacity: null,
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      gelStorage: true,
      bibAttachment: false,
      poles: false,
      bounce: "low",
      adjustability: "Sized stretch tube / strap",
      material: "Lycra blend",
      waterResistance: "none",
      reflective: false,
    },
    strengths: ["Low-bounce stretch tube design", "Simple no-zipper access"],
    weaknesses: ["Sweat can reach phone without a case", "Not ideal for large bottles"],
    recommendationScore: 85,
    valueScore: 87,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-flipbelt-classic",
      "FlipBelt Classic — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-spibelt-original", "prod-nathan-mirage"],
    alternativeProductIds: ["prod-spibelt-original", "prod-nathan-mirage"],
    ...pub,
  },
  {
    id: "prod-nathan-mirage",
    slug: "nathan-mirage-pak",
    brandId: "brand-nathan",
    generation: "Mirage",
    name: "Mirage Pak",
    fullName: "Nathan Mirage Pak",
    shortDescription:
      "Minimal zippered running belt for phone and race-day essentials.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-5k", "uc-10k", "uc-half"],
    specifications: {
      capacity: null,
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      gelStorage: true,
      bibAttachment: false,
      poles: false,
      bounce: "low",
      adjustability: "Sized stretch tube / strap",
      material: "Stretch woven",
      waterResistance: "water-resistant",
      reflective: true,
    },
    strengths: ["Secure zippered pocket", "Low profile for racing"],
    weaknesses: ["Limited storage vs larger packs", "Phone size limits apply"],
    recommendationScore: 78,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-nathan-mirage",
      "Nathan Mirage Pak — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-flipbelt-classic", "prod-spibelt-original"],
    alternativeProductIds: ["prod-flipbelt-classic", "prod-spibelt-original"],
    ...pub,
  },
  {
    id: "prod-spibelt-original",
    slug: "spibelt-original",
    brandId: "brand-spibelt",
    generation: "Original",
    name: "Original",
    fullName: "SPIbelt Original",
    shortDescription:
      "Expandable bounce-free waist pack popular for phones and small race fuel.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-beginners"],
    specifications: {
      capacity: null,
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      gelStorage: true,
      bibAttachment: false,
      poles: false,
      bounce: "low",
      adjustability: "Sized stretch tube / strap",
      material: "Elastic + weather-resistant pouch",
      waterResistance: "water-resistant",
      reflective: false,
    },
    strengths: ["Expandable pouch", "Widely available sizing"],
    weaknesses: ["Single-pouch organization", "Can ride up if sized poorly"],
    recommendationScore: 80,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-spibelt-original",
      "SPIbelt Original — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-flipbelt-classic", "prod-nathan-mirage"],
    alternativeProductIds: ["prod-flipbelt-classic"],
    ...pub,
  },

  // ─── Hydration ───────────────────────────────────────────────────────────
  {
    id: "prod-nathan-exoshot",
    slug: "nathan-exoshot-2",
    brandId: "brand-nathan",
    generation: "2",
    name: "ExoShot 2",
    fullName: "Nathan ExoShot 2",
    shortDescription:
      "Insulated handheld soft flask with secure hand strap for long road and trail runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-trail-training"],
    specifications: {
      capacity: 535,
      volume: 535,
      weight: 95,
      type: "handheld",
      softHard: "soft",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: true,
      insulation: true,
      material: "TPU soft flask + insulated sleeve",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: ["Comfortable handheld carry", "Insulated sleeve option"],
    weaknesses: ["One-handed volume limit", "Less ideal than a vest for ultras"],
    recommendationScore: 79,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-nathan-exoshot",
      "Nathan ExoShot 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-soft-flask-500", "prod-nathan-vaporair-2"],
    alternativeProductIds: ["prod-soft-flask-500"],
    ...pub,
  },
  {
    id: "prod-soft-flask-500",
    slug: "salomon-soft-flask-500",
    brandId: "brand-salomon",
    generation: "500",
    name: "Soft Flask 500",
    fullName: "Salomon Soft Flask 500 ml",
    shortDescription:
      "500 ml soft flask designed for vest front pockets and handheld sleeves.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: 38,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: ["Standard vest-pocket size", "Compresses as you drink"],
    weaknesses: ["Needs a vest or handheld sleeve", "Cleaning required after sugary drinks"],
    recommendationScore: 82,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-soft-flask-500",
      "Salomon Soft Flask 500 ml — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nathan-exoshot", "prod-nathan-vaporair-2", "prod-ud-adventure-vest"],
    alternativeProductIds: ["prod-nathan-exoshot"],
    ...pub,
  },
  {
    id: "prod-hydrapak-softflask-500",
    slug: "hydrapak-softflask-500",
    brandId: "brand-hydrapak",
    generation: "500",
    name: "SoftFlask 500",
    fullName: "HydraPak SoftFlask 500 ml",
    shortDescription:
      "Flexible 500 ml soft flask with high-flow bite valve for running vest pockets.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: 45,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: ["Widely vest-compatible shape", "Easy-open fill"],
    weaknesses: ["Accessory only — no carry system included"],
    recommendationScore: 80,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-softflask-500",
      "HydraPak SoftFlask 500 ml — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-soft-flask-500", "prod-ud-adventure-vest"],
    alternativeProductIds: ["prod-soft-flask-500"],
    ...pub,
  },

  // ─── Clothing ────────────────────────────────────────────────────────────
  {
    id: "prod-asics-race-short",
    slug: "asics-core-split-short",
    brandId: "brand-asics",
    generation: "Core",
    name: "Core Split Short",
    fullName: "ASICS Core Split Short",
    shortDescription:
      "Lightweight split racing short for track sessions, tempos, and race day.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-running-racing"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-shorts"],
    useCaseIds: ["uc-tempo-runs", "uc-intervals", "uc-5k", "uc-10k", "uc-pb"],
    specifications: {
      genderFit: "men",
      sizeRange: "Confirm manufacturer size chart",
      material: "Lightweight woven polyester",
      weight: null,
      fit: "fitted",
      weather: ["hot", "mild"],
      season: ["spring", "summer"],
      reflective: false,
      pockets: false,
      waterResistance: "none",
      windResistance: "none",
      breathability: "high",
    },
    strengths: ["Minimal race weight", "Free stride for faster sessions"],
    weaknesses: ["Minimal storage", "Not a cold-weather layer"],
    recommendationScore: 77,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-clothing",
      "prod-asics-race-short",
      "ASICS Core Split Short — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nike-stride-short", "prod-craft-adv-essence-short"],
    alternativeProductIds: ["prod-nike-stride-short"],
    ...pub,
  },
  {
    id: "prod-nike-stride-short",
    slug: "nike-dri-fit-stride-short",
    brandId: "brand-nike",
    generation: "Stride",
    name: "Dri-FIT Stride Short",
    fullName: "Nike Dri-FIT Stride Short",
    shortDescription:
      "Everyday Dri-FIT running short with brief liner for training and racing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-shorts"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-tempo-runs"],
    specifications: {
      genderFit: "men",
      sizeRange: "Confirm manufacturer size chart",
      material: "Dri-FIT polyester",
      weight: null,
      fit: "regular",
      weather: ["hot", "mild"],
      season: ["spring", "summer", "autumn"],
      reflective: false,
      pockets: true,
      waterResistance: "none",
      windResistance: "none",
      breathability: "high",
    },
    strengths: ["Versatile daily short", "Built-in liner"],
    weaknesses: ["Fit varies by length option", "Not insulated for winter"],
    recommendationScore: 81,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-clothing",
      "prod-nike-stride-short",
      "Nike Dri-FIT Stride Short — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-asics-race-short", "prod-brooks-ghost-short-sleeve"],
    alternativeProductIds: ["prod-asics-race-short", "prod-craft-adv-essence-short"],
    ...pub,
  },
  {
    id: "prod-brooks-ghost-short-sleeve",
    slug: "brooks-ghost-short-sleeve",
    brandId: "brand-brooks",
    generation: "Ghost",
    name: "Ghost Short Sleeve",
    fullName: "Brooks Ghost Short Sleeve",
    shortDescription:
      "Soft everyday running tee matched to Brooks’ comfort-first training lineup.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-tees"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-beginners", "uc-comfort"],
    specifications: {
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
      material: "Soft knit polyester blend",
      weight: null,
      fit: "regular",
      weather: ["mild", "hot"],
      season: ["spring", "summer", "autumn"],
      reflective: true,
      pockets: false,
      waterResistance: "none",
      windResistance: "none",
      breathability: "high",
    },
    strengths: ["Comfortable daily training top", "Reflective accents"],
    weaknesses: ["Not a race-minimal singlet", "Limited weather protection"],
    recommendationScore: 76,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-clothing",
      "prod-brooks-ghost-short-sleeve",
      "Brooks Ghost Short Sleeve — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-brooks-cascadia-jacket", "prod-nike-stride-short"],
    alternativeProductIds: ["prod-craft-adv-essence-short"],
    ...pub,
  },
  {
    id: "prod-brooks-cascadia-jacket",
    slug: "brooks-cascadia-jacket",
    brandId: "brand-brooks",
    generation: "Cascadia",
    name: "Cascadia Jacket",
    fullName: "Brooks Cascadia Jacket",
    shortDescription:
      "Packable trail weather layer for wind and light rain on Cascadia-style adventures.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-jackets"],
    useCaseIds: ["uc-trail-training", "uc-long-runs", "uc-ultra"],
    specifications: {
      genderFit: "men",
      sizeRange: "Confirm manufacturer size chart",
      material: "Ripstop shell with DWR",
      weight: null,
      fit: "regular",
      weather: ["cold", "wet", "mild"],
      season: ["autumn", "winter", "spring"],
      reflective: true,
      pockets: true,
      waterResistance: "water-resistant",
      windResistance: "windproof",
      breathability: "moderate",
    },
    strengths: ["Packable trail protection", "Useful stash pockets"],
    weaknesses: ["Not a fully waterproof shell", "Warmer than a summer wind shirt"],
    recommendationScore: 79,
    valueScore: 77,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-clothing",
      "prod-brooks-cascadia-jacket",
      "Brooks Cascadia Jacket — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-brooks-ghost-short-sleeve", "prod-buff-original"],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-craft-adv-essence-short",
    slug: "craft-adv-essence-short",
    brandId: "brand-craft",
    generation: "ADV Essence",
    name: "ADV Essence Short",
    fullName: "Craft ADV Essence Short",
    shortDescription:
      "Functional training short from Craft’s ADV Essence line for daily road mileage.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-shorts"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-intermediate"],
    specifications: {
      genderFit: "men",
      sizeRange: "Confirm manufacturer size chart",
      material: "Recycled polyester blend",
      weight: null,
      fit: "regular",
      weather: ["hot", "mild"],
      season: ["spring", "summer"],
      reflective: true,
      pockets: true,
      waterResistance: "none",
      windResistance: "none",
      breathability: "high",
    },
    strengths: ["Practical pocketing", "Solid everyday training short"],
    weaknesses: ["Less race-minimal than split shorts"],
    recommendationScore: 74,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-clothing",
      "prod-craft-adv-essence-short",
      "Craft ADV Essence Short — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nike-stride-short", "prod-asics-race-short"],
    alternativeProductIds: ["prod-nike-stride-short"],
    ...pub,
  },

  // ─── Socks ───────────────────────────────────────────────────────────────
  {
    id: "prod-feetures-elite-light-cushion",
    slug: "feetures-elite-light-cushion",
    brandId: "brand-feetures",
    generation: "Elite",
    name: "Elite Light Cushion",
    fullName: "Feetures Elite Light Cushion",
    shortDescription:
      "Anatomical left/right running sock with light cushioning and a secure no-slip fit.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-marathon"],
    specifications: {
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
      cushionLevel: "light",
      height: "quarter",
      material: "Nylon / spandex blend",
      compression: false,
      blisterFocus: true,
    },
    strengths: ["Targeted anatomical fit", "Light cushion without bulk"],
    weaknesses: ["Higher price than basic athletic socks"],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-feetures-elite-light-cushion",
      "Feetures Elite Light Cushion — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-balega-hidden-comfort", "prod-injinji-run-midweight"],
    alternativeProductIds: ["prod-balega-hidden-comfort", "prod-cep-run-compression-sock"],
    ...pub,
  },
  {
    id: "prod-balega-hidden-comfort",
    slug: "balega-hidden-comfort",
    brandId: "brand-balega",
    generation: "Hidden Comfort",
    name: "Hidden Comfort",
    fullName: "Balega Hidden Comfort",
    shortDescription:
      "No-show running sock with plush Drynamix cushioning for easy daily miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-comfort", "uc-beginners"],
    specifications: {
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
      cushionLevel: "medium",
      height: "no-show",
      material: "Drynamix polyester blend",
      compression: false,
      blisterFocus: true,
    },
    strengths: ["Soft comfort-focused cushion", "Stays hidden in low trainers"],
    weaknesses: ["Can slip in very aggressive race shoes", "Less structured than compression socks"],
    recommendationScore: 83,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-balega-hidden-comfort",
      "Balega Hidden Comfort — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-feetures-elite-light-cushion"],
    alternativeProductIds: ["prod-feetures-elite-light-cushion"],
    ...pub,
  },
  {
    id: "prod-injinji-run-midweight",
    slug: "injinji-run-midweight",
    brandId: "brand-injinji",
    generation: "Run Midweight",
    name: "Run Midweight",
    fullName: "Injinji Run Midweight",
    shortDescription:
      "Toe-sock design that separates digits to reduce between-toe friction on long runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-marathon"],
    specifications: {
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
      cushionLevel: "medium",
      height: "crew",
      material: "COOLMAX / nylon / Lycra",
      compression: false,
      blisterFocus: true,
      toeSeparation: true,
    },
    strengths: ["Separates toes to limit hot spots", "Popular ultra/trail option"],
    weaknesses: ["Adaptation period for first-time toe-sock users"],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-injinji-run-midweight",
      "Injinji Run Midweight — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-feetures-elite-light-cushion", "prod-cep-run-compression-sock"],
    alternativeProductIds: ["prod-feetures-elite-light-cushion"],
    ...pub,
  },
  {
    id: "prod-cep-run-compression-sock",
    slug: "cep-run-compression-sock-3",
    brandId: "brand-cep",
    generation: "3.0",
    name: "Run Compression Sock 3.0",
    fullName: "CEP Run Compression Sock 3.0",
    shortDescription:
      "Graduated compression crew sock for runners wanting a locked-in lower-leg feel.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-half", "uc-high-mileage"],
    specifications: {
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
      cushionLevel: "light",
      height: "crew",
      material: "Polyamide / elastane",
      compression: true,
      blisterFocus: true,
    },
    strengths: ["Secure graduated compression fit", "Supportive for long road efforts"],
    weaknesses: ["Sizing must be precise", "Warmer than ultralight race socks"],
    recommendationScore: 81,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-cep-run-compression-sock",
      "CEP Run Compression Sock 3.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-cep-calf-sleeves", "prod-feetures-elite-light-cushion"],
    alternativeProductIds: ["prod-feetures-elite-light-cushion"],
    ...pub,
  },

  // ─── Headphones ──────────────────────────────────────────────────────────
  {
    id: "prod-shokz-openrun-pro-2",
    slug: "shokz-openrun-pro-2",
    brandId: "brand-shokz",
    generation: "2",
    name: "OpenRun Pro 2",
    fullName: "Shokz OpenRun Pro 2",
    shortDescription:
      "Open-ear bone-conduction headphones that keep situational awareness on outdoor runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-bone-conduction", "sub-hp-open-ear"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-long-runs", "uc-situational-awareness", "uc-trail-training"],
    specifications: {
      type: "bone-conduction",
      weight: null,
      battery: null,
      waterRating: "IP55",
      openEar: true,
      boneConduction: true,
      anc: false,
      microphone: true,
      controls: "Multifunction buttons",
    },
    strengths: ["Open-ear awareness for road running", "Secure wraparound fit"],
    weaknesses: ["Bass limited vs in-ear buds", "Sound leakage in quiet spaces"],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-shokz-openrun-pro-2",
      "Shokz OpenRun Pro 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-bose-ultra-open", "prod-airpods-pro-2"],
    alternativeProductIds: ["prod-bose-ultra-open", "prod-airpods-pro-2"],
    ...pub,
  },
  {
    id: "prod-airpods-pro-2",
    slug: "apple-airpods-pro-2",
    brandId: "brand-apple",
    generation: "2",
    name: "AirPods Pro 2",
    fullName: "Apple AirPods Pro 2",
    shortDescription:
      "ANC in-ear buds with Adaptive Audio for treadmill and phone-centric training.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-treadmill", "disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: ["uc-treadmill", "uc-gym-training", "uc-daily-training", "uc-easy-runs"],
    specifications: {
      type: "in-ear",
      weight: null,
      battery: null,
      waterRating: "IP54",
      openEar: false,
      boneConduction: false,
      anc: true,
      microphone: true,
      controls: "Force sensor / touch",
    },
    strengths: ["Excellent ANC for indoor miles", "Seamless iPhone pairing"],
    weaknesses: ["In-ear seal reduces outdoor awareness", "Fit can loosen when very sweaty"],
    recommendationScore: 82,
    valueScore: 74,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-airpods-pro-2",
      "Apple AirPods Pro 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-apple-watch-ultra-2", "prod-shokz-openrun-pro-2"],
    alternativeProductIds: ["prod-shokz-openrun-pro-2", "prod-bose-ultra-open"],
    ...pub,
  },
  {
    id: "prod-bose-ultra-open",
    slug: "bose-ultra-open-earbuds",
    brandId: "brand-bose",
    generation: "Ultra Open",
    name: "Ultra Open Earbuds",
    fullName: "Bose Ultra Open Earbuds",
    shortDescription:
      "Open-ear clip earbuds for runners who want spatial audio without blocking the ear canal.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-ear-hook"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-situational-awareness"],
    specifications: {
      type: "open-ear",
      weight: null,
      battery: null,
      waterRating: null,
      openEar: true,
      boneConduction: false,
      anc: false,
      microphone: true,
      controls: "Touch",
    },
    strengths: ["Open-ear awareness with clip comfort", "Strong Bose sound signature"],
    weaknesses: ["Less secure than wraparound Shokz for some runners", "Premium price"],
    recommendationScore: 79,
    valueScore: 72,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-bose-ultra-open",
      "Bose Ultra Open Earbuds — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-shokz-openrun-pro-2", "prod-airpods-pro-2"],
    alternativeProductIds: ["prod-shokz-openrun-pro-2"],
    ...pub,
  },

  // ─── Sunglasses ──────────────────────────────────────────────────────────
  {
    id: "prod-oakley-encoder",
    slug: "oakley-encoder",
    brandId: "brand-oakley",
    generation: "Encoder",
    name: "Encoder",
    fullName: "Oakley Encoder",
    shortDescription:
      "Shield-style performance sunglasses with Prizm lenses for road and trail glare control.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-shield", "sub-sg-performance-wrap"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-trail-training"],
    specifications: {
      lensType: "Prizm",
      frameStyle: "shield",
      weight: null,
      polarized: null,
      interchangeableLenses: false,
    },
    strengths: ["Wide field of view", "Secure sport fit"],
    weaknesses: ["Premium pricing", "Bold aesthetic is polarizing"],
    recommendationScore: 85,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-oakley-encoder",
      "Oakley Encoder — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-julbo-aerolite", "prod-goodr-ogs"],
    alternativeProductIds: ["prod-julbo-aerolite", "prod-goodr-ogs"],
    ...pub,
  },
  {
    id: "prod-goodr-ogs",
    slug: "goodr-ogs",
    brandId: "brand-goodr",
    generation: "OGs",
    name: "OGs",
    fullName: "Goodr OGs",
    shortDescription:
      "Affordable no-slip running sunglasses with polarized lenses for daily outdoor miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-everyday-value"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-beginners"],
    specifications: {
      lensType: "Polarized",
      frameStyle: "classic",
      weight: null,
      polarized: true,
      interchangeableLenses: false,
    },
    strengths: ["Strong value", "Grip coating resists sweat slip"],
    weaknesses: ["Less coverage than shield styles", "Build is lighter-duty than premium optics"],
    recommendationScore: 80,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-goodr-ogs",
      "Goodr OGs — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-oakley-encoder", "prod-julbo-aerolite"],
    alternativeProductIds: ["prod-oakley-encoder"],
    ...pub,
  },
  {
    id: "prod-julbo-aerolite",
    slug: "julbo-aerolite",
    brandId: "brand-julbo",
    generation: "Aerolite",
    name: "Aerolite",
    fullName: "Julbo Aerolite",
    shortDescription:
      "Ultralight trail sunglasses with wide coverage for mountain and desert running.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      lensType: "Spectron / Reactiv options",
      frameStyle: "wrap",
      weight: null,
      polarized: null,
      interchangeableLenses: null,
    },
    strengths: ["Trail-oriented coverage", "Very light frame"],
    weaknesses: ["Retail availability varies by region", "Lens options add complexity"],
    recommendationScore: 82,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-julbo-aerolite",
      "Julbo Aerolite — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-oakley-encoder", "prod-goodr-ogs"],
    alternativeProductIds: ["prod-oakley-encoder"],
    ...pub,
  },

  // ─── Lights ──────────────────────────────────────────────────────────────
  {
    id: "prod-petzl-swift-rl",
    slug: "petzl-swift-rl",
    brandId: "brand-petzl",
    generation: "Swift RL",
    name: "Swift RL",
    fullName: "Petzl Swift RL",
    shortDescription:
      "Reactive Lighting headlamp for night trail running with high lumen output.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-night-running", "uc-long-runs"],
    specifications: {
      lumens: 1200,
      weight: 92,
      rechargeable: true,
      reactiveLighting: true,
      battery: "Li-ion 2250 mAh USB-C",
      waterproofRating: "IPX4",
    },
    strengths: [
      "REACTIVE LIGHTING auto-adjusts output",
      "High lumen-to-weight ratio (1200 lm / 92 g)",
    ],
    weaknesses: ["Premium price", "Overkill for short lit-road jogs"],
    recommendationScore: 87,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-petzl-swift-rl",
      "Petzl Swift RL — product image unavailable",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-bd-spot-400-r", "prod-silva-trail-runner-free"],
    alternativeProductIds: ["prod-bd-spot-400-r", "prod-silva-trail-runner-free"],
    ...pub,
  },
  {
    id: "prod-bd-spot-400-r",
    slug: "black-diamond-spot-400-r",
    brandId: "brand-black-diamond",
    generation: "400-R",
    name: "Spot 400-R",
    fullName: "Black Diamond Spot 400-R",
    shortDescription:
      "Compact rechargeable 400-lumen headlamp for dark road and trail runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: ["uc-trail-training", "uc-night-running", "uc-daily-training"],
    specifications: {
      lumens: 400,
      weight: null,
      rechargeable: true,
      reactiveLighting: false,
      battery: "Rechargeable",
      waterproofRating: "IP67",
    },
    strengths: ["Approachable lumen rating", "Sealed weather resistance"],
    weaknesses: ["Less intelligent beam control than Petzl RL models"],
    recommendationScore: 81,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-bd-spot-400-r",
      "Black Diamond Spot 400-R — product image unavailable",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-petzl-swift-rl", "prod-silva-trail-runner-free"],
    alternativeProductIds: ["prod-silva-trail-runner-free", "prod-petzl-swift-rl"],
    ...pub,
  },
  {
    id: "prod-silva-trail-runner-free",
    slug: "silva-trail-runner-free-2",
    brandId: "brand-silva",
    generation: "2",
    name: "Trail Runner Free 2",
    fullName: "Silva Trail Runner Free 2",
    shortDescription:
      "Hybrid headlamp system with free-move head unit popular for winter and trail runners.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-waist"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-night-running", "uc-long-runs"],
    specifications: {
      lumens: 450,
      weight: 60,
      rechargeable: true,
      reactiveLighting: false,
      battery: "Hybrid pack / 3×AAA (450 lm AAA; 500 lm hybrid)",
      waterproofRating: "IPX5",
    },
    strengths: [
      "Free-move head unit comfort for running",
      "450–500 lm Intelligent Light beam pattern",
    ],
    weaknesses: ["System is bulkier than minimal headlamps"],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-silva-trail-runner-free",
      "Silva Trail Runner Free 2 — product image unavailable",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-petzl-swift-rl", "prod-bd-spot-400-r"],
    alternativeProductIds: ["prod-petzl-swift-rl", "prod-bd-spot-400-r"],
    ...pub,
  },

  // ─── Safety ──────────────────────────────────────────────────────────────
  {
    id: "prod-nathan-reflective-vest",
    slug: "nathan-streak-reflective-vest",
    brandId: "brand-nathan",
    generation: "Streak",
    name: "Streak Reflective Vest",
    fullName: "Nathan Streak Reflective Vest",
    shortDescription:
      "Lightweight reflective running vest for low-light road visibility.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-visibility-vests", "sub-safety-reflective"],
    useCaseIds: ["uc-daily-training", "uc-night-running", "uc-commute-running", "uc-beginners"],
    specifications: {
      type: "reflective-vest",
      reflective: true,
      illuminated: false,
      weight: null,
      waterResistance: "none",
    },
    strengths: ["360° reflective coverage", "Packs small"],
    weaknesses: ["Passive only — no active light", "Can flap in strong wind if oversized"],
    recommendationScore: 75,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-nathan-reflective-vest",
      "Nathan Streak Reflective Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nite-ize-radiant-clip", "prod-bd-spot-400-r"],
    alternativeProductIds: ["prod-nite-ize-radiant-clip"],
    ...pub,
  },
  {
    id: "prod-nite-ize-radiant-clip",
    slug: "nite-ize-radiant-rechargeable-clip-light",
    brandId: "brand-nite-ize",
    generation: "Radiant",
    name: "Radiant Rechargeable Clip Light",
    fullName: "Nite Ize Radiant Rechargeable Clip Light",
    shortDescription:
      "Clip-on LED marker light for adding active visibility to a vest, belt, or pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-commute"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-clip-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training"],
    specifications: {
      type: "clip-light",
      reflective: false,
      illuminated: true,
      weight: null,
      rechargeable: true,
      waterResistance: "water-resistant",
    },
    strengths: ["Cheap active visibility add-on", "Clips to existing gear"],
    weaknesses: ["Not a primary headlamp", "Battery life varies by flash mode"],
    recommendationScore: 72,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-nite-ize-radiant-clip",
      "Nite Ize Radiant Rechargeable Clip Light — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-nathan-reflective-vest", "prod-bd-spot-400-r"],
    alternativeProductIds: ["prod-nathan-reflective-vest"],
    ...pub,
  },

  // ─── Recovery ────────────────────────────────────────────────────────────
  {
    id: "prod-theragun-mini",
    slug: "therabody-theragun-mini-2",
    brandId: "brand-therabody",
    generation: "mini 2nd Gen",
    name: "Theragun mini",
    fullName: "Therabody Theragun mini",
    shortDescription:
      "Compact percussive massage device for convenient post-run soft-tissue work on the go — useful for comfort routines, not a medical treatment.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage", "disc-running-road"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: ["uc-recovery-runs", "uc-post-run-recovery", "uc-travel-recovery", "uc-high-mileage", "uc-comfort"],
    specifications: {
      type: "percussive-massage",
      weight: null,
      battery: "Rechargeable",
      amplitude: null,
      portable: true,
    },
    strengths: ["Travel-friendly size", "Quick post-run convenience"],
    weaknesses: [
      "Less power than full-size guns",
      "Not a substitute for rest or medical care",
    ],
    recommendationScore: 78,
    valueScore: 75,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-theragun-mini",
      "Therabody Theragun mini — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-hypervolt-go-2", "prod-triggerpoint-grid"],
    alternativeProductIds: ["prod-hypervolt-go-2"],
    ...pub,
  },
  {
    id: "prod-hypervolt-go-2",
    slug: "hyperice-hypervolt-go-2",
    brandId: "brand-hyperice",
    generation: "Go 2",
    name: "Hypervolt Go 2",
    fullName: "Hyperice Hypervolt Go 2",
    shortDescription:
      "Portable percussion massager for targeted post-training muscle work.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: ["uc-recovery-runs", "uc-post-run-recovery", "uc-travel-recovery", "uc-high-mileage"],
    specifications: {
      type: "percussive-massage",
      weight: null,
      battery: "Rechargeable",
      amplitude: null,
      portable: true,
    },
    strengths: ["Compact Hyperice option", "Simple speed controls"],
    weaknesses: [
      "Attachment ecosystem smaller than full Hypervolt",
      "Does not treat injuries",
    ],
    recommendationScore: 76,
    valueScore: 77,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-hypervolt-go-2",
      "Hyperice Hypervolt Go 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-theragun-mini", "prod-triggerpoint-grid"],
    alternativeProductIds: ["prod-theragun-mini"],
    ...pub,
  },
  {
    id: "prod-triggerpoint-grid",
    slug: "triggerpoint-grid-foam-roller",
    brandId: "brand-triggerpoint",
    generation: "GRID",
    name: "GRID Foam Roller",
    fullName: "TriggerPoint GRID Foam Roller",
    shortDescription:
      "Structured foam roller for self-myofascial work before or after runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: ["uc-recovery-runs", "uc-post-run-recovery", "uc-home-recovery", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "foam-roller",
      weight: null,
      length: null,
      density: "multi-density",
      portable: false,
    },
    strengths: ["Durable hollow core design", "Widely used mobility staple"],
    weaknesses: ["Bulky for travel", "Technique-dependent results"],
    recommendationScore: 84,
    valueScore: 89,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-grid",
      "TriggerPoint GRID Foam Roller — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-theragun-mini", "prod-oofos-ooriginal"],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-oofos-ooriginal",
    slug: "oofos-ooriginal",
    brandId: "brand-oofos",
    generation: "OOriginal",
    name: "OOriginal",
    fullName: "OOFOS OOriginal",
    shortDescription:
      "Recovery sandal with OOfoam cushioning for easy walking after hard training days.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-recovery-sandals"],
    useCaseIds: ["uc-recovery-runs", "uc-post-run-recovery", "uc-comfort", "uc-high-mileage"],
    specifications: {
      type: "recovery-sandal",
      weight: null,
      cushionLevel: "high",
      material: "OOfoam",
      portable: true,
    },
    strengths: ["Soft post-run walking cushion", "Machine-washable foam"],
    weaknesses: [
      "Not a running shoe",
      "Fit can feel narrow for some",
    ],
    recommendationScore: 77,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-oofos-ooriginal",
      "OOFOS OOriginal — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-triggerpoint-grid"],
    alternativeProductIds: [],
    ...pub,
  },

  // ─── Accessories ─────────────────────────────────────────────────────────
  {
    id: "prod-buff-original",
    slug: "buff-original",
    brandId: "brand-buff",
    familyId: "fam-buff-neckwear",
    generation: "Original",
    name: "Original",
    fullName: "Buff Original Multifunctional Headwear",
    shortDescription:
      "Year-round Original EcoStretch Buff (~40 g) — the versatile microfiber tube for sweat, dust and cool starts when you do not need CoolNet’s UPF 50 or Polar fleece.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-running-clothing",
    subcategoryIds: ["sub-running-caps"],
    useCaseIds: ["uc-trail-training", "uc-daily-training", "uc-long-runs"],
    specifications: {
      genderFit: "unisex",
      type: "neck-gaiter",
      material: "95% recycled polyester / 5% elastane (Original EcoStretch)",
      weight: 40,
      fit: "fitted",
      weather: ["hot", "mild", "cold"],
      temperatureSuitability: ["hot", "mild", "cold"],
      season: ["all-season"],
      breathability: "high",
      packability: "packable",
      windResistance: "none",
      waterResistance: "none",
      compression: false,
      pockets: false,
      reflective: false,
      antiChafe: true,
      seams: "Seamless tubular",
      care: "Machine wash 40°C; do not tumble dry",
      sizeRange: "One size; ~53 cm tube",
    },
    strengths: [
      "Most versatile Buff tube if you want one always-pack layer",
      "Machine-wash EcoStretch vs merino hand-wash",
      "Same multi-wear configurations without Polar bulk",
    ],
    weaknesses: [
      "Not as warm as Polar on freezing starts",
      "No manufacturer UPF 50 rating like CoolNet UV+",
    ],
    recommendationScore: 79,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-buff-original",
      "Buff Original Multifunctional Headwear — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: [
      "prod-buff-coolnet-uv",
      "prod-buff-merino-lightweight",
      "prod-buff-polar",
    ],
    alternativeProductIds: [
      "prod-buff-coolnet-uv",
      "prod-buff-merino-lightweight",
      "prod-buff-polar",
    ],
    ...pub,
  },
  {
    id: "prod-cep-calf-sleeves",
    slug: "cep-calf-sleeves-3",
    brandId: "brand-cep",
    generation: "3.0",
    name: "Calf Sleeves 3.0",
    fullName: "CEP Calf Sleeves 3.0",
    shortDescription:
      "Graduated compression calf sleeves for runners who prefer lower-leg coverage without full socks — comfort/preference apparel, not an injury-prevention claim.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-recovery-compression"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-garments"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-high-mileage", "uc-post-run-recovery"],
    specifications: {
      type: "compression-garment",
      material: "Polyamide / elastane",
      portable: true,
      weight: null,
      bootSizes: "Sized by calf circumference — check CEP chart",
      genderFit: "unisex",
    },
    strengths: ["Wearable calf coverage without changing socks", "Easy to pack for races and travel"],
    weaknesses: [
      "Must size carefully for comfort",
      "Warm in hot weather",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 74,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-cep-calf-sleeves",
      "CEP Calf Sleeves 3.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-cep-run-compression-sock", "prod-buff-original"],
    alternativeProductIds: ["prod-cep-run-compression-sock"],
    ...pub,
  },
  {
    id: "prod-body-glide-original",
    slug: "body-glide-original",
    brandId: "brand-body-glide",
    generation: "Original",
    name: "Original Anti-Chafe Balm",
    fullName: "Body Glide Original Anti-Chafe Balm",
    shortDescription:
      "Anti-chafe balm stick for skin protection on long runs and race day.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-accessories",
    subcategoryIds: ["sub-acc-stick-balm"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-ultra", "uc-half"],
    specifications: {
      type: "anti-chafe",
      material: "Balm stick",
      waterResistance: "water-resistant",
      weight: null,
    },
    strengths: ["Simple chafe prevention staple", "Travel-friendly stick form"],
    weaknesses: ["Needs reapplication on very long efforts for some athletes"],
    recommendationScore: 85,
    valueScore: 91,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-accessories",
      "prod-body-glide-original",
      "Body Glide Original Anti-Chafe Balm — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-editorial"],
    relatedProductIds: ["prod-buff-original"],
    alternativeProductIds: [],
    ...pub,
  },
];

/** Hold accessories / apparel without authentic heroes out of published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set([
  "prod-hydrapak-softflask-500",

  "prod-asics-race-short",
  "prod-nike-stride-short",
  "prod-brooks-ghost-short-sleeve",
  "prod-brooks-cascadia-jacket",
  "prod-craft-adv-essence-short",
  "prod-balega-hidden-comfort",
  "prod-injinji-run-midweight",
  "prod-cep-run-compression-sock",
  "prod-oakley-encoder",
  "prod-goodr-ogs",
  "prod-julbo-aerolite",
  "prod-nite-ize-radiant-clip",
  "prod-hypervolt-go-2",
  "prod-triggerpoint-grid",
  "prod-buff-original",
  "prod-cep-calf-sleeves",
  "prod-body-glide-original",
]);

export const runningGearWave1: Product[] = applyMediaPublishGate(runningGearWave1Raw, MEDIA_PENDING_DRAFT_IDS);
