import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 running headphones catalog — open-ear, bone conduction, ear-hook and
 * sport TWS beyond the three published SKUs in gear-wave1 (OpenRun Pro 2,
 * AirPods Pro 2, Bose Ultra Open).
 */
export const runningHeadphonesWave2Raw: Product[] = [
  // ─── Shokz ───────────────────────────────────────────────────────────────
  {
    id: "prod-shokz-openrun",
    slug: "shokz-openrun",
    brandId: "brand-shokz",
    familyId: "fam-shokz-openrun",
    generation: "OpenRun",
    name: "OpenRun",
    fullName: "Shokz OpenRun",
    shortDescription:
      "Value bone-conduction open-ear for outdoor miles — pick it when you want IP67 washability and a lower price than OpenRun Pro 2, and you can live with shorter battery and simpler sound.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-bone-conduction", "sub-hp-open-ear"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-long-runs",
      "uc-trail-training",
      "uc-rain-running",
      "uc-easy-runs",
    ],
    specifications: {
      type: "bone-conduction",
      weight: 26,
      battery: 8,
      caseBattery: null,
      charging: "Magnetic induction",
      waterRating: "IP67",
      openEar: true,
      boneConduction: true,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "high",
      controls: "Multifunction buttons",
      multipoint: true,
      codec: "SBC",
      safetyAwareness: "high",
    },
    strengths: [
      "IP67 is the washable Shokz for sweat and rain days",
      "Secure wraparound titanium fit for road and easy trail",
      "Clear step down in price from OpenRun Pro 2 without losing awareness",
    ],
    weaknesses: [
      "8-hour battery and magnetic charge trail the Pro 2 USB-C pack",
      "Bass and detail sit behind DualPitch Pro models",
      "Still leaks sound in quiet indoor spaces",
    ],
    recommendationScore: 86,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-shokz-openrun",
      "Shokz OpenRun — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-openrun-pro-2",
      "prod-suunto-wing",
      "prod-shokz-openfit-2",
      "prod-bose-ultra-open",
    ],
    alternativeProductIds: [
      "prod-shokz-openrun-pro-2",
      "prod-suunto-wing",
      "prod-soundcore-aerofit-2",
      "prod-bose-ultra-open",
    ],
    ...pub,
  },
  {
    id: "prod-shokz-openfit-2",
    slug: "shokz-openfit-2",
    brandId: "brand-shokz",
    familyId: "fam-shokz-openfit",
    generation: "2",
    name: "OpenFit 2",
    fullName: "Shokz OpenFit 2",
    shortDescription:
      "Open-ear hook buds when you want air-conduction sound and a charging case — I'd shortlist them for daily road/awareness miles if bone vibration isn't your thing and Bose Ultra Open feels too spendy.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-ear-hook"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-long-runs",
      "uc-commute-running",
    ],
    specifications: {
      type: "open-ear",
      weight: 9.4,
      battery: 11,
      caseBattery: 48,
      charging: "USB-C",
      waterRating: "IP55",
      openEar: true,
      boneConduction: false,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "high",
      controls: "Physical buttons + touch",
      multipoint: true,
      codec: "SBC, AAC",
      safetyAwareness: "high",
    },
    strengths: [
      "Long single-charge and case total for training blocks",
      "Ear-hook open-ear fit without bone-conduction buzz",
      "IP55 covers sweat and light rain for most road sessions",
    ],
    weaknesses: [
      "Not the sealed ANC tool for noisy gym floors",
      "Leakage and wind can still color outdoor volume",
      "Case is another pocket item vs wraparound OpenRun",
    ],
    recommendationScore: 87,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-shokz-openfit-2",
      "Shokz OpenFit 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-opendots-one",
      "prod-shokz-openrun-pro-2",
      "prod-bose-ultra-open",
      "prod-soundcore-aerofit-2",
    ],
    alternativeProductIds: [
      "prod-bose-ultra-open",
      "prod-soundcore-aerofit-2",
      "prod-sony-linkbuds-open",
      "prod-huawei-freeclip",
    ],
    ...pub,
  },
  {
    id: "prod-shokz-opendots-one",
    slug: "shokz-opendots-one",
    brandId: "brand-shokz",
    familyId: "fam-shokz-openfit",
    generation: "One",
    name: "OpenDots One",
    fullName: "Shokz OpenDots One",
    shortDescription:
      "Clip-on open TWS for runners who want Bose Ultra Open comfort without the Bose ticket — current Shokz clip line (not OpenFit Air); I'd pause if your sessions are hard sweat intervals and you need a firmer hook.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-true-wireless", "sub-hp-ear-hook"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-commute-running",
    ],
    specifications: {
      type: "open-ear",
      weight: 6.5,
      battery: 10,
      caseBattery: 40,
      charging: "USB-C + wireless",
      waterRating: "IP54",
      openEar: true,
      boneConduction: false,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "moderate",
      controls: "Touch",
      multipoint: true,
      codec: "SBC, AAC",
      safetyAwareness: "high",
    },
    strengths: [
      "Very light clip-on open-ear for all-day + easy run wear",
      "Wireless charging case and solid 10h single-charge claim",
      "Closer Bose Ultra Open rival than older OpenFit Air",
    ],
    weaknesses: [
      "IP54 and clip hold trail OpenFit 2 / AeroFit hooks for hard efforts",
      "Still open-ear leakage in quiet offices or shared gyms",
      "Not bone conduction if you specifically want temple transducers",
    ],
    recommendationScore: 83,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-shokz-opendots-one",
      "Shokz OpenDots One — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-openfit-2",
      "prod-bose-ultra-open",
      "prod-huawei-freeclip",
      "prod-soundcore-aerofit-2",
    ],
    alternativeProductIds: [
      "prod-bose-ultra-open",
      "prod-huawei-freeclip",
      "prod-shokz-openfit-2",
      "prod-sony-linkbuds-open",
    ],
    ...pub,
  },

  // ─── Sony ────────────────────────────────────────────────────────────────
  {
    id: "prod-sony-linkbuds-open",
    slug: "sony-linkbuds-open",
    brandId: "brand-sony",
    familyId: "fam-sony-linkbuds",
    generation: "Open",
    name: "LinkBuds Open",
    fullName: "Sony LinkBuds Open",
    shortDescription:
      "Ring-style open-ear TWS for Android-heavy runners who want Sony app EQ and multipoint — I'd rotate them for easy road/awareness days, not as your only rainy long-run pair.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-true-wireless"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-commute-running",
    ],
    specifications: {
      type: "open-ear",
      weight: null,
      battery: 8,
      caseBattery: 22,
      charging: "USB-C",
      waterRating: "IPX4",
      openEar: true,
      boneConduction: false,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "moderate",
      controls: "Touch / Speak-to-Chat",
      multipoint: true,
      codec: "SBC, AAC, LC3",
      safetyAwareness: "high",
    },
    strengths: [
      "Natural open ring keeps traffic and trail chatter audible",
      "Sony Sound Connect features and multipoint for phone + watch workflows",
      "Improved single-charge life vs older doughnut LinkBuds",
    ],
    weaknesses: [
      "IPX4 is splash-only — pause for heavy rain or rinse habits",
      "Case total trails Shokz OpenFit / AeroFit open-ear packs",
      "Fin/supporter fit still needs a try-on vs dedicated sport hooks",
    ],
    recommendationScore: 80,
    valueScore: 76,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-sony-linkbuds-open",
      "Sony LinkBuds Open — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-sony-linkbuds-fit",
      "prod-shokz-openfit-2",
      "prod-shokz-opendots-one",
      "prod-bose-ultra-open",
    ],
    alternativeProductIds: [
      "prod-shokz-openfit-2",
      "prod-shokz-opendots-one",
      "prod-soundcore-aerofit-2",
      "prod-bose-ultra-open",
    ],
    ...pub,
  },
  {
    id: "prod-sony-linkbuds-fit",
    slug: "sony-linkbuds-fit",
    brandId: "brand-sony",
    familyId: "fam-sony-linkbuds",
    generation: "Fit",
    name: "LinkBuds Fit",
    fullName: "Sony LinkBuds Fit",
    shortDescription:
      "Compact ANC TWS with Air Fitting Supporters for treadmill and gym blocks — I'd shortlist them when you want Sony LDAC and ambient modes, not when open-ear road awareness is non-negotiable.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-treadmill", "disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-treadmill",
      "uc-daily-training",
      "uc-easy-runs",
    ],
    specifications: {
      type: "in-ear",
      weight: null,
      battery: 5.5,
      caseBattery: 21,
      charging: "USB-C",
      waterRating: "IPX4",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "moderate",
      controls: "Touch",
      multipoint: true,
      codec: "SBC, AAC, LDAC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "ANC + ambient modes for gym noise or street transparency",
      "LDAC path for Android hi-res listening",
      "Supporters help vs plain stem buds on sweaty easy runs",
    ],
    weaknesses: [
      "5.5h ANC battery is short for long outdoor blocks",
      "IPX4 and in-ear seal are weaker outdoor-awareness picks than open-ear",
      "Secure fit still behind dedicated hook sport buds",
    ],
    recommendationScore: 78,
    valueScore: 74,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-sony-linkbuds-fit",
      "Sony LinkBuds Fit — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-sony-linkbuds-open",
      "prod-jabra-elite-10",
      "prod-airpods-pro-2",
      "prod-beats-fit-pro",
    ],
    alternativeProductIds: [
      "prod-jabra-elite-8-active",
      "prod-jabra-elite-10",
      "prod-airpods-pro-2",
      "prod-beats-fit-pro",
    ],
    ...pub,
  },

  // ─── Jabra ───────────────────────────────────────────────────────────────
  {
    id: "prod-jabra-elite-8-active",
    slug: "jabra-elite-8-active",
    brandId: "brand-jabra",
    familyId: "fam-jabra-elite",
    generation: "8 Active Gen 2",
    name: "Elite 8 Active",
    fullName: "Jabra Elite 8 Active Gen 2",
    shortDescription:
      "Current Elite 8 Active Gen 2 — IP68 sealed sport TWS when secure fit and weather abuse matter more than open-ear awareness; I'd pause for road traffic runs where you need natural hearing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-treadmill"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-rain-running",
      "uc-daily-training",
      "uc-trail-training",
      "uc-long-runs",
      "uc-treadmill",
    ],
    specifications: {
      type: "in-ear",
      weight: null,
      battery: 8,
      caseBattery: 32,
      charging: "USB-C",
      waterRating: "IP68",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "high",
      controls: "Buttons",
      multipoint: true,
      codec: "SBC, AAC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "IP68-class durability for rain, mud and hard sweat blocks",
      "High secureFit for intervals and HYROX-style sessions",
      "ANC with HearThrough when you need gym focus or street awareness",
    ],
    weaknesses: [
      "Sealed fit still reduces natural outdoor awareness vs open-ear",
      "Sound/tuning is sport-first, not audiophile-first",
      "Premium vs value sport hooks like Sport X20",
    ],
    recommendationScore: 89,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-jabra-elite-8-active",
      "Jabra Elite 8 Active Gen 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-jabra-elite-10",
      "prod-soundcore-sport-x20",
      "prod-beats-powerbeats-pro-2",
      "prod-shokz-openrun",
    ],
    alternativeProductIds: [
      "prod-soundcore-sport-x20",
      "prod-beats-powerbeats-pro-2",
      "prod-jabra-elite-10",
      "prod-beats-fit-pro",
    ],
    ...pub,
  },
  {
    id: "prod-jabra-elite-10",
    slug: "jabra-elite-10",
    brandId: "brand-jabra",
    familyId: "fam-jabra-elite",
    generation: "10 Gen 2",
    name: "Elite 10",
    fullName: "Jabra Elite 10 Gen 2",
    shortDescription:
      "Current Elite 10 Gen 2 — premium ANC TWS for gym and treadmill when comfort and spatial sound matter; I'd rotate to Elite 8 Active or open-ear when rain abuse or road awareness is the real job.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-treadmill", "disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-treadmill",
      "uc-daily-training",
      "uc-easy-runs",
    ],
    specifications: {
      type: "in-ear",
      weight: 5.7,
      battery: 6,
      caseBattery: 27,
      charging: "USB-C + wireless",
      waterRating: "IP57",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "moderate",
      controls: "Touch",
      multipoint: true,
      codec: "SBC, AAC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "Stronger ANC / spatial package than Elite 8 Active for indoor focus",
      "ComfortFit oval gels for longer treadmill blocks",
      "IP57 and wireless charging for gym-bag life",
    ],
    weaknesses: [
      "Shorter ANC battery than many sport-first peers",
      "Less bombproof than Elite 8 Active IP68 for muddy trail rain",
      "Not an open-ear traffic tool without HearThrough discipline",
    ],
    recommendationScore: 84,
    valueScore: 72,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-jabra-elite-10",
      "Jabra Elite 10 Gen 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-jabra-elite-8-active",
      "prod-airpods-pro-2",
      "prod-sony-linkbuds-fit",
      "prod-apple-airpods-4",
    ],
    alternativeProductIds: [
      "prod-airpods-pro-2",
      "prod-jabra-elite-8-active",
      "prod-sony-linkbuds-fit",
      "prod-beats-fit-pro",
    ],
    ...pub,
  },

  // ─── Beats ───────────────────────────────────────────────────────────────
  {
    id: "prod-beats-powerbeats-pro-2",
    slug: "beats-powerbeats-pro-2",
    brandId: "brand-beats",
    familyId: "fam-beats-powerbeats",
    generation: "Pro 2",
    name: "Powerbeats Pro 2",
    fullName: "Beats Powerbeats Pro 2",
    shortDescription:
      "Ear-hook Apple-ecosystem sport TWS with ANC — I'd shortlist them for hard efforts and gym when Fit Pro fins aren't enough hold, and keep a separate open-ear pair for traffic-heavy roads.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-ear-hook", "sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-daily-training",
      "uc-long-runs",
      "uc-treadmill",
      "uc-intervals",
    ],
    specifications: {
      type: "ear-hook",
      weight: null,
      battery: 10,
      caseBattery: 45,
      charging: "USB-C",
      waterRating: "IPX4",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "high",
      controls: "Physical buttons",
      multipoint: false,
      codec: "AAC, SBC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "Hook secureFit that stays put on intervals and sweaty long runs",
      "Long single-charge plus large case total for training weeks",
      "ANC/transparency with Apple Watch / iPhone pairing ease",
    ],
    weaknesses: [
      "IPX4 only — not Elite 8 Active weather armor",
      "In-ear seal still needs transparency discipline outdoors",
      "Android multipoint / feature parity trails Jabra/Sony",
    ],
    recommendationScore: 88,
    valueScore: 76,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-beats-powerbeats-pro-2",
      "Beats Powerbeats Pro 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-beats-fit-pro",
      "prod-jabra-elite-8-active",
      "prod-soundcore-sport-x20",
      "prod-airpods-pro-2",
    ],
    alternativeProductIds: [
      "prod-jabra-elite-8-active",
      "prod-beats-fit-pro",
      "prod-soundcore-sport-x20",
      "prod-airpods-pro-2",
    ],
    ...pub,
  },
  {
    id: "prod-beats-fit-pro",
    slug: "beats-fit-pro",
    brandId: "brand-beats",
    familyId: "fam-beats-powerbeats",
    generation: "Fit Pro",
    name: "Fit Pro",
    fullName: "Beats Fit Pro",
    shortDescription:
      "Ear-fin Apple TWS when you want ANC without full Powerbeats hooks — still useful beside Powerbeats Pro 2 for pocketable gym/travel days; skip if hooks are the only secureFit that works for you.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-treadmill", "disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-treadmill",
      "uc-daily-training",
      "uc-easy-runs",
    ],
    specifications: {
      type: "in-ear",
      weight: null,
      battery: 6,
      caseBattery: 24,
      charging: "USB-C",
      waterRating: "IPX4",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "high",
      controls: "Physical buttons",
      multipoint: false,
      codec: "AAC, SBC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "Wing-tip secureFit in a smaller case than Powerbeats",
      "ANC/transparency with Apple spatial audio features",
      "Often cheaper street price than Powerbeats Pro 2",
    ],
    weaknesses: [
      "Shorter battery and less hook confidence than Powerbeats Pro 2",
      "IPX4 splash rating only",
      "Aging vs newest Powerbeats Pro 2 feature set",
    ],
    recommendationScore: 81,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-beats-fit-pro",
      "Beats Fit Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-beats-powerbeats-pro-2",
      "prod-airpods-pro-2",
      "prod-apple-airpods-4",
      "prod-sony-linkbuds-fit",
    ],
    alternativeProductIds: [
      "prod-beats-powerbeats-pro-2",
      "prod-airpods-pro-2",
      "prod-jabra-elite-8-active",
      "prod-apple-airpods-4",
    ],
    ...pub,
  },

  // ─── soundcore ───────────────────────────────────────────────────────────
  {
    id: "prod-soundcore-aerofit-2",
    slug: "soundcore-aerofit-2",
    brandId: "brand-soundcore",
    familyId: "fam-soundcore-aerofit",
    generation: "2",
    name: "AeroFit 2",
    fullName: "soundcore AeroFit 2",
    shortDescription:
      "Adjustable open-ear hook value pick — I'd shortlist it when OpenFit 2 / Bose feel expensive and you still want awareness plus LDAC on Android, not when you need sealed gym ANC.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-ear-hook"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-long-runs",
      "uc-commute-running",
    ],
    specifications: {
      type: "open-ear",
      weight: 10,
      battery: 10,
      caseBattery: 42,
      charging: "USB-C + wireless",
      waterRating: "IP55",
      openEar: true,
      boneConduction: false,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "high",
      controls: "Touch",
      multipoint: true,
      codec: "SBC, AAC, LDAC",
      safetyAwareness: "high",
    },
    strengths: [
      "4-level adjustable hooks for odd ear shapes",
      "Strong battery/case total at open-ear value pricing",
      "LDAC + IP55 for Android outdoor training weeks",
    ],
    weaknesses: [
      "Open-ear bass still trails sealed sport buds",
      "Brand prestige and retail support trail Shokz/Bose",
      "Not an ANC gym tool",
    ],
    recommendationScore: 85,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-soundcore-aerofit-2",
      "soundcore AeroFit 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-openfit-2",
      "prod-soundcore-sport-x20",
      "prod-huawei-freeclip",
      "prod-bose-ultra-open",
    ],
    alternativeProductIds: [
      "prod-shokz-openfit-2",
      "prod-shokz-opendots-one",
      "prod-bose-ultra-open",
      "prod-sony-linkbuds-open",
    ],
    ...pub,
  },
  {
    id: "prod-soundcore-sport-x20",
    slug: "soundcore-sport-x20",
    brandId: "brand-soundcore",
    generation: "X20",
    name: "Sport X20",
    fullName: "soundcore Sport X20",
    shortDescription:
      "Adjustable-hook in-ear sport TWS with IP68 and long battery — value sealed alternative to Elite 8 Active when you want secureFit and weather armor without open-ear awareness.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-treadmill"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless", "sub-hp-ear-hook"],
    useCaseIds: [
      "uc-gym-training",
      "uc-rain-running",
      "uc-daily-training",
      "uc-trail-training",
      "uc-long-runs",
      "uc-treadmill",
    ],
    specifications: {
      type: "ear-hook",
      weight: 6.62,
      battery: 12,
      caseBattery: 48,
      charging: "USB-C",
      waterRating: "IP68",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "high",
      controls: "Buttons",
      multipoint: true,
      codec: "SBC, AAC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "IP68 + rotatable/extendable hooks for abuse and odd ears",
      "12h / 48h battery claims that cover long blocks",
      "ANC sport package at soundcore value pricing",
    ],
    weaknesses: [
      "Sealed design needs transparency discipline on busy roads",
      "App polish and call quality trail Jabra/Apple flagships",
      "Hooks add bulk vs stem-only commute buds",
    ],
    recommendationScore: 86,
    valueScore: 93,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-soundcore-sport-x20",
      "soundcore Sport X20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-jabra-elite-8-active",
      "prod-beats-powerbeats-pro-2",
      "prod-soundcore-aerofit-2",
      "prod-jabra-elite-10",
    ],
    alternativeProductIds: [
      "prod-jabra-elite-8-active",
      "prod-beats-powerbeats-pro-2",
      "prod-beats-fit-pro",
      "prod-soundcore-aerofit-2",
    ],
    ...pub,
  },

  // ─── HUAWEI / Suunto / Apple ─────────────────────────────────────────────
  {
    id: "prod-huawei-freeclip",
    slug: "huawei-freeclip",
    brandId: "brand-huawei",
    generation: "2",
    name: "FreeClip 2",
    fullName: "HUAWEI FreeClip 2",
    shortDescription:
      "Current FreeClip 2 clip-on open-ear (replaces original FreeClip in this catalog) — light awareness buds for easy road/commute; I'd pause on deep Apple/Android ecosystem lock-in markets and for hard hook-only workouts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-open-ear", "sub-hp-ear-hook", "sub-hp-true-wireless"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-commute-running",
    ],
    specifications: {
      type: "open-ear",
      weight: 5.1,
      battery: 8,
      caseBattery: null,
      charging: "USB-C",
      waterRating: "IP57",
      openEar: true,
      boneConduction: false,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "moderate",
      controls: "Touch",
      multipoint: true,
      codec: null,
      safetyAwareness: "high",
    },
    strengths: [
      "Very light C-bridge clip for all-day open-ear wear",
      "IP57 earbuds step up weather tolerance vs many open clips",
      "Distinctive fit when hooks irritate behind the ear",
    ],
    weaknesses: [
      "Regional availability and app ecosystem vary widely",
      "Clip secureFit still trails dedicated sport hooks on hard intervals",
      "Case total hours less consistently published than Shokz/soundcore peers",
    ],
    recommendationScore: 79,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-huawei-freeclip",
      "HUAWEI FreeClip 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-opendots-one",
      "prod-bose-ultra-open",
      "prod-shokz-openfit-2",
      "prod-soundcore-aerofit-2",
    ],
    alternativeProductIds: [
      "prod-shokz-opendots-one",
      "prod-bose-ultra-open",
      "prod-soundcore-aerofit-2",
      "prod-sony-linkbuds-open",
    ],
    ...pub,
  },
  {
    id: "prod-suunto-wing",
    slug: "suunto-wing",
    brandId: "brand-suunto",
    generation: "Wing",
    name: "Wing",
    fullName: "Suunto Wing",
    shortDescription:
      "Bone-conduction open-ear with IP67 and built-in LED for night visibility — I'd consider it when you want Shokz-like awareness plus Suunto ecosystem extras; skip if OpenRun value or OpenRun Pro 2 sound is enough.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-bone-conduction", "sub-hp-open-ear"],
    useCaseIds: [
      "uc-situational-awareness",
      "uc-night-running",
      "uc-daily-training",
      "uc-trail-training",
      "uc-rain-running",
      "uc-long-runs",
    ],
    specifications: {
      type: "bone-conduction",
      weight: 33,
      battery: 10,
      caseBattery: null,
      charging: "USB-C",
      waterRating: "IP67",
      openEar: true,
      boneConduction: true,
      anc: false,
      transparency: false,
      microphone: true,
      secureFit: "high",
      controls: "Buttons",
      multipoint: true,
      codec: null,
      safetyAwareness: "high",
    },
    strengths: [
      "IP67 bone conduction with integrated LED for night road visibility",
      "10-hour claim plus wraparound secureFit for outdoor miles",
      "Suunto branding for athletes already in that watch ecosystem",
    ],
    weaknesses: [
      "Heavier and usually pricier than Shokz OpenRun",
      "Sound still limited vs sealed ANC sport buds",
      "Smaller retail footprint than Shokz for try-before-buy",
    ],
    recommendationScore: 82,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-suunto-wing",
      "Suunto Wing — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shokz-openrun",
      "prod-shokz-openrun-pro-2",
      "prod-bose-ultra-open",
      "prod-shokz-openfit-2",
    ],
    alternativeProductIds: [
      "prod-shokz-openrun",
      "prod-shokz-openrun-pro-2",
      "prod-soundcore-aerofit-2",
      "prod-bose-ultra-open",
    ],
    ...pub,
  },
  {
    id: "prod-apple-airpods-4",
    slug: "apple-airpods-4",
    brandId: "brand-apple",
    generation: "4",
    name: "AirPods 4",
    fullName: "Apple AirPods 4",
    shortDescription:
      "Open-ish stem TWS with optional ANC SKU and strong transparency — I'd use them for easy/gym Apple days when you hate tips, and keep Pro 2 or open-ear for serious outdoor awareness or sweaty secureFit.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-treadmill", "disc-running-road"],
    categoryId: "cat-headphones",
    subcategoryIds: ["sub-hp-true-wireless"],
    useCaseIds: [
      "uc-gym-training",
      "uc-daily-training",
      "uc-easy-runs",
      "uc-treadmill",
      "uc-commute-running",
    ],
    specifications: {
      type: "in-ear",
      weight: 4.3,
      battery: 5,
      caseBattery: 30,
      charging: "USB-C + wireless (case)",
      waterRating: "IP54",
      openEar: false,
      boneConduction: false,
      anc: true,
      transparency: true,
      microphone: true,
      secureFit: "low",
      controls: "Force sensor / tap",
      multipoint: false,
      codec: "AAC, SBC",
      safetyAwareness: "moderate",
    },
    strengths: [
      "Tip-free open-ish fit with Adaptive Audio / transparency on ANC model",
      "Seamless iPhone pairing for mixed commute + easy run days",
      "Lighter and more pocketable than hook sport buds",
    ],
    weaknesses: [
      "SecureFit is the weak link for hard sweaty intervals",
      "Shorter single-charge than dedicated sport TWS",
      "Not a substitute for true open-ear traffic awareness hardware",
    ],
    recommendationScore: 76,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-headphones",
      "prod-apple-airpods-4",
      "Apple AirPods 4 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-airpods-pro-2",
      "prod-beats-fit-pro",
      "prod-beats-powerbeats-pro-2",
      "prod-jabra-elite-10",
    ],
    alternativeProductIds: [
      "prod-airpods-pro-2",
      "prod-beats-fit-pro",
      "prod-shokz-opendots-one",
      "prod-bose-ultra-open",
    ],
    ...pub,
  },
];

/** All wave-2 headphone SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningHeadphonesWave2Raw.map((p) => p.id),
);

export const runningHeadphonesWave2: Product[] = applyMediaPublishGate(runningHeadphonesWave2Raw, MEDIA_PENDING_DRAFT_IDS);
