import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 running headlamps — expands beyond Swift RL / Spot 400-R /
 * Trail Runner Free 2 into a commercially useful night-running catalog.
 * All SKUs stay draft until authentic product heroes land (media-gated).
 *
 * Do not duplicate gear-wave1: prod-petzl-swift-rl, prod-bd-spot-400-r,
 * prod-silva-trail-runner-free.
 */
export const runningHeadlampsWave2Raw: Product[] = [
  // ─── Petzl ───────────────────────────────────────────────────────────────
  {
    id: "prod-petzl-nao-rl",
    slug: "petzl-nao-rl",
    brandId: "brand-petzl",
    familyId: "fam-petzl-nao",
    generation: "RL",
    name: "NAO RL",
    fullName: "Petzl NAO RL",
    shortDescription:
      "1500-lumen REACTIVE LIGHTING trail/ultra headlamp with balanced rear battery and red rear visibility — the brighter, more committing sibling to the Swift RL when you want auto-dimming on long night sections without babysitting the button.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: [
      "uc-night-running",
      "uc-trail-training",
      "uc-ultra",
      "uc-long-runs",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 1500,
      beamModes: "REACTIVE LIGHTING or STANDARD; wide/mixed white; red rear",
      beamDistance: 200,
      battery: "Li-ion R1 3200 mAh USB-C (3.7 V / 11.84 Wh)",
      runtime: "Up to ~2 h max power STANDARD; longer in REACTIVE; up to ~80 h max burn (mfr)",
      weight: 145,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: true,
      reactiveLighting: true,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IPX4",
    },
    strengths: [
      "REACTIVE LIGHTING stretches runtime when terrain opens and dims when you look close",
      "1500 lm / 200 m throw for technical night trails without a waist lamp",
      "Rear red + top strap balance reduce bounce on long ultra night sections",
    ],
    weaknesses: [
      "Heavier and pricier than Swift RL — overkill for short lit-road jogs",
      "IPX4 only — fine in rain/sweat, not a sealed storm lamp like BD Storm",
    ],
    recommendationScore: 91,
    valueScore: 72,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-petzl-nao-rl",
      "Petzl NAO RL — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-petzl-swift-rl",
      "prod-bd-distance-1500",
      "prod-ledlenser-neo9r",
      "prod-fenix-hm65r-t",
    ],
    alternativeProductIds: [
      "prod-petzl-swift-rl",
      "prod-bd-distance-1500",
      "prod-ledlenser-neo9r",
      "prod-biolite-headlamp-800",
    ],
    ...pub,
  },
  {
    id: "prod-petzl-actik-core",
    slug: "petzl-actik-core",
    brandId: "brand-petzl",
    familyId: "fam-petzl-actik",
    generation: "CORE",
    name: "Actik Core",
    fullName: "Petzl Actik Core",
    shortDescription:
      "625-lumen hybrid rechargeable (CORE or 3×AAA) all-rounder — enough mixed beam for dark roads and moderate trails when you want Petzl ergonomics without Swift/NAO reactive pricing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-night-running",
      "uc-winter-running",
      "uc-long-runs",
      "uc-trail-training",
    ],
    specifications: {
      lumens: 625,
      beamModes: "Wide or mixed white (3 levels); red continuous/strobe",
      beamDistance: 115,
      battery: "CORE 1250 mAh USB-C rechargeable or 3×AAA/LR03 (HYBRID CONCEPT)",
      runtime: "Up to ~2 h max power CORE; ~7 h STANDARD; up to ~100 h max burn (mfr)",
      weight: 88,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: false,
      reactiveLighting: false,
      lockMode: false,
      comfort: "high",
      waterproofRating: "IPX4",
    },
    strengths: [
      "Hybrid CORE/AAA means you can finish a long night if the rechargeable dies",
      "625 lm mixed beam covers most road and moderate trail night runs",
      "88 g stays comfortable when the lamp is on for the whole winter commute week",
    ],
    weaknesses: [
      "No REACTIVE LIGHTING — you manage output yourself vs Swift/NAO RL",
      "No dedicated rear red — pair with a clip light or reflective vest on roads",
    ],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-petzl-actik-core",
      "Petzl Actik Core — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-petzl-iko-core",
      "prod-petzl-swift-rl",
      "prod-bd-spot-400-r",
      "prod-biolite-headlamp-425",
    ],
    alternativeProductIds: [
      "prod-bd-spot-400-r",
      "prod-ledlenser-neo5r",
      "prod-biolite-headlamp-425",
      "prod-petzl-iko-core",
    ],
    ...pub,
  },
  {
    id: "prod-petzl-iko-core",
    slug: "petzl-iko-core",
    brandId: "brand-petzl",
    familyId: "fam-petzl-iko",
    generation: "CORE",
    name: "IKO Core",
    fullName: "Petzl IKO Core",
    shortDescription:
      "500-lumen ultralight AIRFIT hybrid — rear-battery balance and a fold-flat body when you want Petzl beam quality with minimal forehead bounce on easy night roads and backup ultra miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-night-running",
      "uc-long-runs",
      "uc-ultra",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 500,
      beamModes: "Wide or mixed white (3 levels); HYBRID CORE/AAA",
      beamDistance: 100,
      battery: "CORE 1250 mAh rechargeable or 3×AAA/LR03 (HYBRID CONCEPT)",
      runtime: "Up to ~2.5 h max power; ~9 h STANDARD; up to ~100 h max burn (mfr)",
      weight: 79,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: false,
      reactiveLighting: false,
      lockMode: false,
      comfort: "high",
      waterproofRating: "IPX4",
    },
    strengths: [
      "AIRFIT + rear CORE keeps bounce low on long easy night miles",
      "79 g packable backup that still throws a usable 100 m mixed beam",
      "Hybrid batteries matter on unsupported ultras when USB is scarce",
    ],
    weaknesses: [
      "500 lm is not a technical night-trail primary like NAO RL / Distance 1500",
      "No rear safety LED — add a red clip if you share dark roads",
    ],
    recommendationScore: 82,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-petzl-iko-core",
      "Petzl IKO Core — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-petzl-actik-core",
      "prod-silva-smini",
      "prod-nitecore-nu25",
      "prod-petzl-swift-rl",
    ],
    alternativeProductIds: [
      "prod-silva-smini",
      "prod-nitecore-nu25",
      "prod-biolite-headlamp-425",
      "prod-petzl-actik-core",
    ],
    ...pub,
  },

  // ─── Black Diamond ───────────────────────────────────────────────────────
  {
    id: "prod-bd-storm-500-r",
    slug: "black-diamond-storm-500-r",
    brandId: "brand-black-diamond",
    familyId: "fam-bd-storm",
    generation: "500-R",
    name: "Storm 500-R",
    fullName: "Black Diamond Storm 500-R",
    shortDescription:
      "Sealed IP67 500-lumen rechargeable with PowerTap dimming and strong mid-mode runtime — the storm/winter pick when sweat, rain and accidental dunking matter more than reactive auto-brightness.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-winter-running",
      "uc-night-running",
      "uc-trail-training",
      "uc-long-runs",
    ],
    specifications: {
      lumens: 500,
      beamModes: "Proximity/distance white; dimming; strobe; RGB night-vision; lock",
      beamDistance: 120,
      battery: "Integrated BD 2400 mAh Li-ion (micro-USB)",
      runtime: "High ~7 h · Medium ~19 h · Low ~350 h (ANSI FL1, mfr)",
      weight: 120,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: false,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IP67",
    },
    strengths: [
      "IP67 sealed body shrugs off winter rain and sweaty night miles",
      "2400 mAh mid-mode runtime covers long dark training blocks",
      "PowerTap + lock mode keep you from pocket-firing the lamp in a vest",
    ],
    weaknesses: [
      "No reactive lighting and no rear red — smarter peers exist for pure trail racing",
      "Micro-USB and ~120 g feel dated next to USB-C ultralights",
    ],
    recommendationScore: 83,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-bd-storm-500-r",
      "Black Diamond Storm 500-R — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-bd-spot-400-r",
      "prod-bd-distance-1500",
      "prod-petzl-actik-core",
      "prod-biolite-headlamp-425",
    ],
    alternativeProductIds: [
      "prod-bd-spot-400-r",
      "prod-petzl-actik-core",
      "prod-ledlenser-neo5r",
      "prod-biolite-headlamp-800",
    ],
    ...pub,
  },
  {
    id: "prod-bd-distance-1500",
    slug: "black-diamond-distance-1500",
    brandId: "brand-black-diamond",
    familyId: "fam-bd-distance-headlamp",
    generation: "1500",
    name: "Distance 1500",
    fullName: "Black Diamond Distance 1500",
    shortDescription:
      "1500-lumen high-output with Comfort Cradle top strap and swappable rear battery pack — choose it when you want sustained trail throw and mid-race battery swaps more than Petzl-style reactive auto-dimming.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: [
      "uc-trail-training",
      "uc-ultra",
      "uc-night-running",
      "uc-long-runs",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 1500,
      beamModes: "Boost / high / medium / low spot-flood mix; lock",
      beamDistance: 117,
      battery: "Detachable magnetic Li-ion pack (USB rechargeable; hot-swap capable)",
      runtime: "Boost brief; high ~4–5 h class; low ~40 h (mfr / field class)",
      weight: 212,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: false,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IP67",
    },
    strengths: [
      "1500 lm boost + IP67 sealed performance for committing night trails",
      "Magnetic rear pack swaps keep ultras lit without a full lamp change",
      "Comfort Cradle top strap tames bounce despite the heavier pack",
    ],
    weaknesses: [
      "212 g is a lot on the head vs Swift RL / NAO RL for all-night ultras",
      "No reactive lighting — output management is fully manual",
    ],
    recommendationScore: 88,
    valueScore: 70,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-bd-distance-1500",
      "Black Diamond Distance 1500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-petzl-nao-rl",
      "prod-petzl-swift-rl",
      "prod-ledlenser-neo9r",
      "prod-fenix-hm65r-t",
    ],
    alternativeProductIds: [
      "prod-petzl-nao-rl",
      "prod-ledlenser-neo9r",
      "prod-fenix-hm65r-t",
      "prod-biolite-headlamp-800",
    ],
    ...pub,
  },

  // ─── Silva ───────────────────────────────────────────────────────────────
  {
    id: "prod-silva-smini",
    slug: "silva-smini",
    brandId: "brand-silva",
    familyId: "fam-silva-smini",
    generation: "Smini",
    name: "Smini",
    fullName: "Silva Smini",
    shortDescription:
      "250-lumen palm-size USB-C runner with Intelligent Light spot/flood and included rear red — ultralight primary for easy night roads or a near-zero-penalty ultra backup next to Trail Runner Free.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-night-running",
      "uc-long-runs",
      "uc-ultra",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 250,
      beamModes: "Intelligent Light min/med/max white; red; rear red steady/blink",
      beamDistance: 80,
      battery: "Integrated Li-ion 700 mAh USB-C (+ rear-light cell)",
      runtime: "Max ~1.5 h · Med ~2.5 h · Min ~20 h (mfr)",
      weight: 53,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: true,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IPX5",
    },
    strengths: [
      "53 g with rear light barely notices on long easy night miles",
      "Intelligent Light spot+flood avoids tunnel vision at modest lumen counts",
      "Built-in rear red helps road visibility without a second device",
    ],
    weaknesses: [
      "250 lm / short max burn is not enough as sole light on technical night trails",
      "Integrated cells — no AAA swap mid-ultra like Petzl HYBRID models",
    ],
    recommendationScore: 80,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-silva-smini",
      "Silva Smini — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-silva-trail-runner-free",
      "prod-nitecore-nu25",
      "prod-petzl-iko-core",
      "prod-ledlenser-neo5r",
    ],
    alternativeProductIds: [
      "prod-nitecore-nu25",
      "prod-petzl-iko-core",
      "prod-biolite-headlamp-425",
      "prod-silva-trail-runner-free",
    ],
    ...pub,
  },

  // ─── Ledlenser ───────────────────────────────────────────────────────────
  {
    id: "prod-ledlenser-neo9r",
    slug: "ledlenser-neo9r",
    brandId: "brand-ledlenser",
    familyId: "fam-ledlenser-neo",
    generation: "9R",
    name: "NEO9R",
    fullName: "Ledlenser NEO9R",
    shortDescription:
      "1200-lumen trail-running lamp with separated short/long beams, rear-mounted battery/red light and optional chest belt — high continuous output when you prefer manual beam craft over Petzl reactive.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output", "sub-light-waist"],
    useCaseIds: [
      "uc-trail-training",
      "uc-night-running",
      "uc-ultra",
      "uc-long-runs",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 1200,
      beamModes: "Boost / Power / Mid / Low; separated near + far beams; rear red",
      beamDistance: 200,
      battery: "Removable rear Li-ion (magnetic charge; extension cable compatible)",
      runtime: "Power ~5 h · Mid ~12 h · Low ~120 h (mfr; Boost untimed)",
      weight: 199,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: true,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IP54",
    },
    strengths: [
      "Running-tuned near/far beam image for technical descents at night",
      "Rear battery + red light balances weight and road visibility",
      "Chest-belt option moves mass off the head when bounce creeps in",
    ],
    weaknesses: [
      "199 g and IP54 trail behind sealed BD Distance / Storm for foul weather",
      "No reactive auto-dim — you ride the buttons on variable canopy trails",
    ],
    recommendationScore: 87,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-ledlenser-neo9r",
      "Ledlenser NEO9R — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ledlenser-neo5r",
      "prod-petzl-nao-rl",
      "prod-petzl-swift-rl",
      "prod-bd-distance-1500",
    ],
    alternativeProductIds: [
      "prod-petzl-nao-rl",
      "prod-petzl-swift-rl",
      "prod-bd-distance-1500",
      "prod-fenix-hm65r-t",
    ],
    ...pub,
  },
  {
    id: "prod-ledlenser-neo5r",
    slug: "ledlenser-neo5r",
    brandId: "brand-ledlenser",
    familyId: "fam-ledlenser-neo",
    generation: "5R",
    name: "NEO5R",
    fullName: "Ledlenser NEO5R",
    shortDescription:
      "600-lumen mid-pack runner with rear battery/red light and chest-belt option — the NEO sweet spot for dark roads and mild trails without NEO9R weight or cost.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-waist"],
    useCaseIds: [
      "uc-night-running",
      "uc-winter-running",
      "uc-long-runs",
      "uc-trail-training",
    ],
    specifications: {
      lumens: 600,
      beamModes: "Boost / Power / Mid / Low; running-optimized pattern; rear red",
      beamDistance: 100,
      battery: "Integrated rear Li-ion (magnetic charge)",
      runtime: "Power ~4 h · Mid ~8 h · Low ~35 h (mfr; Boost untimed)",
      weight: 104,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: true,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IP54",
    },
    strengths: [
      "Rear-weight balance + red rear light for dark road safety",
      "600 lm Boost covers most night roads and mild trails",
      "Chest strap included when forehead bounce or heat bothers you",
    ],
    weaknesses: [
      "Not a high-output technical-trail primary like NEO9R / NAO RL",
      "IP54 and fixed battery trail Storm 500-R for foul-weather winters",
    ],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-ledlenser-neo5r",
      "Ledlenser NEO5R — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ledlenser-neo9r",
      "prod-biolite-headlamp-425",
      "prod-bd-spot-400-r",
      "prod-petzl-actik-core",
    ],
    alternativeProductIds: [
      "prod-biolite-headlamp-425",
      "prod-petzl-actik-core",
      "prod-bd-spot-400-r",
      "prod-ledlenser-neo9r",
    ],
    ...pub,
  },

  // ─── Fenix ───────────────────────────────────────────────────────────────
  {
    id: "prod-fenix-hm65r-t",
    slug: "fenix-hm65r-t",
    brandId: "brand-fenix",
    familyId: "fam-fenix-hm65",
    generation: "HM65R-T",
    name: "HM65R-T",
    fullName: "Fenix HM65R-T",
    shortDescription:
      "1500-lumen magnesium dual-beam trail lamp (independent spot + flood) on a 18650 with USB-C in-lamp charge — manual beam craft and IP68 toughness when you want separate near/far control without reactive lighting.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: [
      "uc-trail-training",
      "uc-night-running",
      "uc-ultra",
      "uc-winter-running",
      "uc-long-runs",
    ],
    specifications: {
      lumens: 1500,
      beamModes: "Independent spotlight + floodlight levels; dual max combo",
      beamDistance: 170,
      battery: "Included 3400 mAh 18650 USB-C in-lamp; optional 2×CR123A",
      runtime: "Spot high ~4 h class · flood low up to ~300 h (mfr mode table)",
      weight: 150,
      rechargeable: true,
      replaceableBatteries: true,
      rearLight: false,
      reactiveLighting: false,
      lockMode: true,
      comfort: "moderate",
      waterproofRating: "IP68",
    },
    strengths: [
      "Independent spot/flood lets you paint technical trail without one mushy beam",
      "IP68 + magnesium body for wet winter trail nights",
      "Hot-swappable 18650 / CR123A backup for long unsupported efforts",
    ],
    weaknesses: [
      "Front-heavy vs rear-battery NEO/NAO — bounce shows up if the band is loose",
      "No rear red or reactive lighting for road-shared night miles",
    ],
    recommendationScore: 86,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-fenix-hm65r-t",
      "Fenix HM65R-T — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-petzl-nao-rl",
      "prod-bd-distance-1500",
      "prod-ledlenser-neo9r",
      "prod-nitecore-nu43",
    ],
    alternativeProductIds: [
      "prod-petzl-nao-rl",
      "prod-bd-distance-1500",
      "prod-ledlenser-neo9r",
      "prod-petzl-swift-rl",
    ],
    ...pub,
  },

  // ─── BioLite ─────────────────────────────────────────────────────────────
  {
    id: "prod-biolite-headlamp-800",
    slug: "biolite-headlamp-800-pro",
    brandId: "brand-biolite",
    familyId: "fam-biolite-headlamp",
    generation: "800 Pro",
    name: "HeadLamp 800 Pro",
    fullName: "BioLite HeadLamp 800 Pro",
    shortDescription:
      "800-lumen comfort-first runner with 3D SlimFit no-bounce band, rear red and burst mode — high output when forehead comfort and rear visibility matter as much as raw trail throw.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: [
      "uc-night-running",
      "uc-trail-training",
      "uc-long-runs",
      "uc-ultra",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 800,
      beamModes: "Spot / flood / combo; strobe; red; rear red; 30 s burst",
      beamDistance: 135,
      battery: "Integrated 3000 mAh Li-ion (micro-USB; Pass-Thru Plus capable)",
      runtime: "High ~7 h · Low ~150 h; burst 30 s then reverts (mfr)",
      weight: 150,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: true,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IPX4",
    },
    strengths: [
      "3D SlimFit band is among the least bouncy feels in the high-output class",
      "800 lm burst + 135 m reach covers most trail nights without NAO pricing",
      "Rear red keeps you visible on shared dark roads and aid-station approaches",
    ],
    weaknesses: [
      "Micro-USB and IPX4 trail Storm/Distance for foul sealed weather",
      "No reactive lighting — burst is timed, not terrain-aware",
    ],
    recommendationScore: 85,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-biolite-headlamp-800",
      "BioLite HeadLamp 800 Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-biolite-headlamp-425",
      "prod-petzl-swift-rl",
      "prod-ledlenser-neo9r",
      "prod-bd-storm-500-r",
    ],
    alternativeProductIds: [
      "prod-petzl-swift-rl",
      "prod-ledlenser-neo9r",
      "prod-bd-distance-1500",
      "prod-biolite-headlamp-425",
    ],
    ...pub,
  },
  {
    id: "prod-biolite-headlamp-425",
    slug: "biolite-headlamp-425",
    brandId: "brand-biolite",
    familyId: "fam-biolite-headlamp",
    generation: "425",
    name: "HeadLamp 425",
    fullName: "BioLite HeadLamp 425",
    shortDescription:
      "425-lumen SlimFit value runner with rear red — the comfort/value pick for dark roads and easy trails when you want BioLite’s no-bounce band without 800 Pro power or price.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-night-running",
      "uc-winter-running",
      "uc-long-runs",
      "uc-trail-training",
    ],
    specifications: {
      lumens: 425,
      beamModes: "Spot / flood / combo; red; rear red steady/strobe",
      beamDistance: 78,
      battery: "Integrated Li-ion (USB rechargeable)",
      runtime: "High ~3.5–4 h · Low ~60 h (mfr class)",
      weight: 78,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: true,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IPX4",
    },
    strengths: [
      "SlimFit comfort at a mid-pack lumen count for daily night roads",
      "Rear red included — uncommon at this price/weight",
      "Light enough for long easy miles without a top strap fight",
    ],
    weaknesses: [
      "425 lm / ~78 m is thin for fast technical night trail",
      "Integrated battery only — no AAA bailout like Petzl HYBRID",
    ],
    recommendationScore: 81,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-biolite-headlamp-425",
      "BioLite HeadLamp 425 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-biolite-headlamp-800",
      "prod-ledlenser-neo5r",
      "prod-bd-spot-400-r",
      "prod-petzl-actik-core",
    ],
    alternativeProductIds: [
      "prod-bd-spot-400-r",
      "prod-ledlenser-neo5r",
      "prod-petzl-actik-core",
      "prod-silva-smini",
    ],
    ...pub,
  },

  // ─── NITECORE ────────────────────────────────────────────────────────────
  {
    id: "prod-nitecore-nu25",
    slug: "nitecore-nu25-ul",
    brandId: "brand-nitecore",
    familyId: "fam-nitecore-nu",
    generation: "NU25 UL",
    name: "NU25 UL",
    fullName: "NITECORE NU25 UL",
    shortDescription:
      "400-lumen ~47 g ultralight USB-C with dual-beam optics and red mode — gram-shaving primary for easy night roads or a featherweight ultra spare when every forehead gram counts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps"],
    useCaseIds: [
      "uc-night-running",
      "uc-long-runs",
      "uc-ultra",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 400,
      beamModes: "White high/med/low/ultralow; red; dual flood/spot optic",
      beamDistance: 132,
      battery: "Built-in 650–700 mAh Li-ion USB-C",
      runtime: "High ~2.5–2.7 h · lower modes into double-digit hours (mfr class)",
      weight: 47,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: false,
      reactiveLighting: false,
      lockMode: true,
      comfort: "high",
      waterproofRating: "IP66",
    },
    strengths: [
      "Sub-50 g with a surprisingly long dual-beam throw for the weight",
      "IP66 sealed enough for wet winter roads",
      "Cheap, packable ultra backup that still hits 400 lm when needed",
    ],
    weaknesses: [
      "Short high-mode runtime — not a sole light for all-night technical trails",
      "No rear red; band comfort is fine but not BioLite SlimFit class",
    ],
    recommendationScore: 79,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-nitecore-nu25",
      "NITECORE NU25 UL — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-silva-smini",
      "prod-petzl-iko-core",
      "prod-nitecore-nu43",
      "prod-biolite-headlamp-425",
    ],
    alternativeProductIds: [
      "prod-silva-smini",
      "prod-petzl-iko-core",
      "prod-biolite-headlamp-425",
      "prod-bd-spot-400-r",
    ],
    ...pub,
  },
  {
    id: "prod-nitecore-nu43",
    slug: "nitecore-nu43",
    brandId: "brand-nitecore",
    familyId: "fam-nitecore-nu",
    generation: "NU43",
    name: "NU43",
    fullName: "NITECORE NU43",
    shortDescription:
      "1400-lumen lightweight 18650-class integrated lamp (~116 g) with soft TrueVision flood — mid/high output when you want serious brightness without Distance 1500 mass or Petzl reactive cost.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-running-lights",
    subcategoryIds: ["sub-light-headlamps", "sub-light-high-output"],
    useCaseIds: [
      "uc-night-running",
      "uc-trail-training",
      "uc-long-runs",
      "uc-ultra",
      "uc-winter-running",
    ],
    specifications: {
      lumens: 1400,
      beamModes: "White 8/100/300/600/1400 lm; red; beacon/SOS",
      beamDistance: 130,
      battery: "Built-in 3400 mAh 18650-class Li-ion USB-C (5V/2A)",
      runtime: "Ultralow up to ~165 h; high modes shorter (mfr)",
      weight: 116,
      rechargeable: true,
      replaceableBatteries: false,
      rearLight: false,
      reactiveLighting: false,
      lockMode: true,
      comfort: "moderate",
      waterproofRating: "IP66",
    },
    strengths: [
      "1400 lm at 116 g punches above most mid-weight running lamps",
      "Large integrated cell supports long low-mode winter nights",
      "Soft uniform flood is easy on eyes for road and smooth trail",
    ],
    weaknesses: [
      "No rear light or reactive system — peers win for road visibility / auto-dim",
      "Integrated cell only — no hot-swap pack like Distance 1500",
    ],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-lights",
      "prod-nitecore-nu43",
      "NITECORE NU43 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nitecore-nu25",
      "prod-fenix-hm65r-t",
      "prod-petzl-swift-rl",
      "prod-biolite-headlamp-800",
    ],
    alternativeProductIds: [
      "prod-petzl-swift-rl",
      "prod-biolite-headlamp-800",
      "prod-fenix-hm65r-t",
      "prod-ledlenser-neo9r",
    ],
    ...pub,
  },
];

/** All wave-2 headlamp SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningHeadlampsWave2Raw.map((p) => p.id),
);

export const runningHeadlampsWave2: Product[] = applyMediaPublishGate(runningHeadlampsWave2Raw, MEDIA_PENDING_DRAFT_IDS);
