import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

/**
 * Wave 2 heart-rate monitors — expands beyond H10 + a few peers to a
 * commercially useful running/training HRM catalog (chest, armband, dynamics).
 */
export const runningHrmWave2: Product[] = [
  // ─── Garmin entry / specialty ────────────────────────────────────────────
  {
    id: "prod-garmin-hrm-200",
    slug: "garmin-hrm-200",
    brandId: "brand-garmin",
    familyId: "fam-hrm-pro",
    generation: "200",
    name: "HRM 200",
    fullName: "Garmin HRM 200",
    shortDescription:
      "Entry Garmin ECG chest strap with ANT+/Bluetooth — accurate HR without running-dynamics extras.",
    releaseDate: "2024-10-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-intermediate", "uc-beginners", "uc-daily-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 1,
      battery: "Replaceable CR2032 (~1 year — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: "3 ATM",
      weight: 63,
      replaceableStrap: true,
      strapSizeRange: "Typical adult chest sizes (verify fit)",
    },
    strengths: [
      "Accurate ECG HR at Garmin entry pricing",
      "Detachable module for easier strap washing",
      "ANT+ and Bluetooth for watches, trainers and apps",
    ],
    weaknesses: [
      "No running dynamics or swim store-and-forward",
      "Not the strap for FR970 Step Speed Loss / economy metrics",
    ],
    recommendationScore: 82,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-garmin-hrm-200",
      "Garmin HRM 200 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-hrm-600", "prod-hrm-pro-plus", "prod-polar-h10"],
    alternativeProductIds: ["prod-polar-h10", "prod-wahoo-trackr", "prod-polar-h9"],
    ...pub,
  },
  {
    id: "prod-garmin-hrm-fit",
    slug: "garmin-hrm-fit",
    brandId: "brand-garmin",
    familyId: "fam-hrm-pro",
    generation: "Fit",
    name: "HRM-Fit",
    fullName: "Garmin HRM-Fit",
    shortDescription:
      "ECG HR module designed for sports-bra wear — chest-accurate HR without a traditional strap.",
    releaseDate: "2024-03-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-daily-training", "uc-intermediate", "uc-beginners"],
    specifications: {
      type: "bra-band",
      placement: "sports-bra",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 1,
      battery: "Replaceable coin cell (~1 year — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: false,
      internalMemory: true,
      waterResistance: "3 ATM",
      replaceableStrap: false,
      strapSizeRange: "Clips to compatible sports bras",
    },
    strengths: [
      "ECG accuracy without wrapping a classic chest strap",
      "Built for runners who train in sports bras",
      "Stores HR during timed activities for later sync",
    ],
    weaknesses: [
      "Requires a suitable sports-bra mounting setup",
      "No Garmin running-dynamics suite like HRM 600 / Pro Plus",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-garmin-hrm-fit",
      "Garmin HRM-Fit — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-garmin-hrm-200", "prod-polar-h10", "prod-coros-hrm"],
    alternativeProductIds: ["prod-garmin-hrm-200", "prod-polar-verity-sense", "prod-coros-hrm"],
    ...pub,
  },

  // ─── Polar budget chest ──────────────────────────────────────────────────
  {
    id: "prod-polar-h9",
    slug: "polar-h9",
    brandId: "brand-polar",
    familyId: "fam-polar-h",
    generation: "H9",
    name: "H9",
    fullName: "Polar H9",
    shortDescription:
      "Budget Polar ECG chest strap with Bluetooth and ANT+ — simpler sibling to the H10.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-beginners", "uc-intervals", "uc-daily-training", "uc-intermediate"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 1,
      battery: "Replaceable CR2025 (~400 h — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      batteryLifeHours: 400,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: true,
      internalMemory: false,
      waterResistance: "30 m",
      replaceableStrap: true,
    },
    strengths: [
      "Polar ECG accuracy story at a lower price than H10",
      "Works across watches, bikes and gym apps via BLE/ANT+",
      "Simple strap when you do not need H10 dual Bluetooth memory",
    ],
    weaknesses: [
      "Fewer simultaneous Bluetooth connections than H10",
      "No onboard session memory like H10",
    ],
    recommendationScore: 84,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-hrm", "prod-polar-h9", "Polar H9 — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-polar-h10", "prod-wahoo-trackr"],
    alternativeProductIds: ["prod-polar-h10", "prod-garmin-hrm-200", "prod-wahoo-tickr"],
    ...pub,
  },

  // ─── Wahoo current + armband ─────────────────────────────────────────────
  {
    id: "prod-wahoo-trackr",
    slug: "wahoo-trackr",
    brandId: "brand-wahoo",
    familyId: "fam-wahoo-tickr",
    generation: "TRACKR",
    name: "TRACKR Heart Rate",
    fullName: "Wahoo TRACKR Heart Rate",
    shortDescription:
      "Current Wahoo rechargeable ECG chest strap — lighter successor to TICKR for run and indoor training.",
    releaseDate: "2024-09-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-daily-training", "uc-intermediate", "uc-hyrox-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 3,
      battery: "Rechargeable (~100 h — manufacturer claim)",
      batteryType: "rechargeable",
      batteryLifeHours: 100,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: "IPX7",
      replaceableStrap: true,
    },
    strengths: [
      "Rechargeable modern chest strap replacing coin-cell TICKR",
      "Strong for Zwift / trainer / multi-device Bluetooth pairing",
      "Light everyday strap for HYROX and interval blocks",
    ],
    weaknesses: [
      "No onboard memory like older TICKR X",
      "Not a swim HR transmitter underwater",
    ],
    recommendationScore: 86,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-wahoo-trackr",
      "Wahoo TRACKR — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-wahoo-tickr", "prod-wahoo-tickr-x", "prod-polar-h10"],
    alternativeProductIds: ["prod-polar-h10", "prod-garmin-hrm-200", "prod-wahoo-tickr-fit"],
    ...pub,
  },
  {
    id: "prod-wahoo-tickr-fit",
    slug: "wahoo-tickr-fit",
    brandId: "brand-wahoo",
    familyId: "fam-wahoo-tickr",
    generation: "TICKR FIT",
    name: "TICKR FIT",
    fullName: "Wahoo TICKR FIT",
    shortDescription:
      "Optical armband HR monitor for runners who want Wahoo connectivity without a chest strap.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-armband", "sub-hrm-optical"],
    useCaseIds: ["uc-daily-training", "uc-intervals", "uc-intermediate", "uc-hyrox-training"],
    specifications: {
      type: "armband",
      placement: "upper-arm",
      sensingMethod: "optical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 3,
      battery: "Rechargeable",
      batteryType: "rechargeable",
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: "IPX7",
      replaceableStrap: true,
    },
    strengths: [
      "Comfort-first optical armband with multi-device pairing",
      "Useful when chest straps chafe in HYROX / gym blocks",
      "Same Wahoo app ecosystem as TRACKR/TICKR",
    ],
    weaknesses: [
      "Optical lag can show up on hard intervals vs ECG straps",
      "Not a swimming HR solution",
    ],
    recommendationScore: 79,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-wahoo-tickr-fit",
      "Wahoo TICKR FIT — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-wahoo-trackr", "prod-coros-hrm", "prod-polar-verity-sense"],
    alternativeProductIds: ["prod-coros-hrm", "prod-polar-verity-sense", "prod-scosche-rhythm24"],
    ...pub,
  },

  // ─── Scosche optical ─────────────────────────────────────────────────────
  {
    id: "prod-scosche-rhythm-plus-2",
    slug: "scosche-rhythm-plus-2",
    brandId: "brand-scosche",
    familyId: "fam-scosche-rhythm",
    generation: "Rhythm+ 2.0",
    name: "Rhythm+ 2.0",
    fullName: "Scosche Rhythm+ 2.0",
    shortDescription:
      "Optical upper-arm HR monitor with dual BLE/ANT+ — comfort-first live streaming for runs, gym, and apps.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-armband", "sub-hrm-optical"],
    useCaseIds: ["uc-daily-training", "uc-intervals", "uc-beginners", "uc-hyrox-training"],
    specifications: {
      type: "armband",
      placement: "upper-arm",
      sensingMethod: "optical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      battery: "Rechargeable (~24 h — manufacturer claim)",
      batteryType: "rechargeable",
      batteryLifeHours: 24,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: "IP68",
      replaceableStrap: true,
    },
    strengths: [
      "Upper-arm comfort when chest straps chafe",
      "Dual Bluetooth and ANT+ for watches, phones, and trainers",
      "Green + yellow optical array aimed at broader skin-tone coverage (manufacturer claim)",
      "Pairs with a wide set of training apps — not locked to one watch brand",
    ],
    weaknesses: [
      "Still optical — more lag on hard intervals than Polar H10 or Garmin HRM 600",
      "No Garmin-style running dynamics",
      "Scosche ecosystem polish is smaller than Polar / Garmin / Wahoo peers",
    ],
    recommendationScore: 78,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-scosche-rhythm-plus-2",
      "Scosche Rhythm+ 2.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-scosche-rhythm24",
      "prod-polar-verity-sense",
      "prod-coros-hrm",
      "prod-wahoo-tickr-fit",
    ],
    alternativeProductIds: [
      "prod-scosche-rhythm24",
      "prod-polar-verity-sense",
      "prod-coros-hrm",
      "prod-wahoo-tickr-fit",
      "prod-polar-h10",
    ],
    ...pub,
  },
  {
    id: "prod-scosche-rhythm24",
    slug: "scosche-rhythm24",
    brandId: "brand-scosche",
    familyId: "fam-scosche-rhythm",
    generation: "Rhythm24",
    name: "Rhythm24",
    fullName: "Scosche Rhythm24",
    shortDescription:
      "Optical armband with onboard recording — Scosche specialist for watch-free and chest-free training.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-armband", "sub-hrm-optical"],
    useCaseIds: ["uc-daily-training", "uc-intervals", "uc-intermediate"],
    specifications: {
      type: "armband",
      placement: "upper-arm",
      sensingMethod: "optical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      battery: "Rechargeable (~24 h+ — manufacturer claim)",
      batteryType: "rechargeable",
      batteryLifeHours: 24,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: true,
      swimmingSupport: false,
      internalMemory: true,
      waterResistance: "IP68",
      replaceableStrap: true,
    },
    strengths: [
      "Standalone optical recording when you train watch-free",
      "Upper-arm optical alternative when chest straps chafe",
    ],
    weaknesses: [
      "Still optical — more lag than Polar H10 on all-out intervals",
      "Smaller ecosystem polish than Polar/COROS/Wahoo peers",
    ],
    recommendationScore: 76,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-scosche-rhythm24",
      "Scosche Rhythm24 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-scosche-rhythm-plus-2",
      "prod-polar-verity-sense",
      "prod-coros-hrm",
      "prod-wahoo-tickr-fit",
    ],
    alternativeProductIds: [
      "prod-scosche-rhythm-plus-2",
      "prod-polar-verity-sense",
      "prod-coros-hrm",
      "prod-wahoo-tickr-fit",
    ],
    ...pub,
  },

  // ─── Suunto chest ────────────────────────────────────────────────────────
  {
    id: "prod-suunto-smart-hr-belt",
    slug: "suunto-smart-heart-rate-belt",
    brandId: "brand-suunto",
    familyId: "fam-suunto-hrm",
    generation: "Smart HR Belt",
    name: "Smart Heart Rate Belt",
    fullName: "Suunto Smart Heart Rate Belt",
    shortDescription:
      "Suunto ECG chest strap with memory — natural pairing for Suunto watches and cross-brand BLE/ANT+.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-track"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-intermediate", "uc-advanced", "uc-daily-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      battery: "Replaceable coin cell (~500 h — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      batteryLifeHours: 500,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: true,
      swimmingSupport: true,
      internalMemory: true,
      waterResistance: "30 m",
      replaceableStrap: true,
    },
    strengths: [
      "Straightforward Suunto-ecosystem chest strap",
      "Onboard memory for watch-free stretches",
      "Long coin-cell life for low-maintenance training",
    ],
    weaknesses: [
      "No Garmin-style running dynamics extras",
      "Less third-party validation buzz than Polar H10",
    ],
    recommendationScore: 81,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-suunto-smart-hr-belt",
      "Suunto Smart Heart Rate Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-suunto-race", "prod-polar-h10", "prod-wahoo-trackr"],
    alternativeProductIds: ["prod-polar-h10", "prod-wahoo-trackr", "prod-garmin-hrm-200"],
    ...pub,
  },
];
