import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 3 gap-fill — soft flasks / handhelds / reservoirs (cat-hydration),
 * major sock brands (cat-running-socks), and phone/race belts (cat-running-belts)
 * beyond wave-1 gear and hydration-wave2 / clothing-wave2 seeds.
 *
 * Skipped duplicates: prod-soft-flask-500 (Salomon Soft Flask 500 already in gear-wave1).
 * Media draft until authentic heroes land. Claim-safe preference language only.
 */
export const runningHydrationSocksBeltsWave3Raw: Product[] = [
  // ─── Soft flasks (cat-hydration) ─────────────────────────────────────────
  {
    id: "prod-salomon-soft-flask-speed-500",
    slug: "salomon-soft-flask-speed-500",
    brandId: "brand-salomon",
    familyId: "fam-salomon-soft-flask",
    generation: "Speed 500",
    name: "Soft Flask Speed 500",
    fullName: "Salomon Soft Flask Speed 500",
    shortDescription:
      "500 ml Salomon Soft Flask Speed with high-flow valve — vest-front spare that upgrades classic Soft Flask 500 sipping when you want faster on-the-move drinking in ADV Skin sleeves.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-marathon"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: null,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU Soft Flask Speed",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "High-flow Speed valve for faster vest-pocket sipping",
      "Standard 500 ml footprint for Salomon/UD race sleeves",
      "Compresses as you drink — less front-panel bounce when empty",
    ],
    weaknesses: [
      "Accessory only — needs a vest, belt or handheld sleeve",
      "Sugary mixes need thorough cleaning like any soft flask",
    ],
    recommendationScore: 87,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-salomon-soft-flask-speed-500",
      "Salomon Soft Flask Speed 500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-soft-flask-500",
      "prod-hydrapak-softflask-speed-500",
      "prod-salomon-adv-skin-5",
      "prod-salomon-pulse-belt",
    ],
    alternativeProductIds: [
      "prod-soft-flask-500",
      "prod-hydrapak-softflask-speed-500",
      "prod-ud-body-bottle-500",
    ],
    ...pub,
  },
  {
    id: "prod-ud-body-bottle-500",
    slug: "ultimate-direction-body-bottle-500",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-body-bottle",
    generation: "500",
    name: "Body Bottle 500",
    fullName: "Ultimate Direction Body Bottle 500",
    shortDescription:
      "500 ml UD Body Bottle / soft-flask style vest flask — shaped for Ultimate Direction front sleeves when you want brand-matched spares for Race Vest and Adventure Vest setups.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-marathon"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: null,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU soft flask (Body Bottle)",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Matches UD Race Vest / Adventure Vest front-pocket geometry",
      "500 ml race-standard volume for flask-only long runs",
      "Compresses flat when empty for low bounce",
    ],
    weaknesses: [
      "Not a handheld — needs vest or belt sleeves",
      "Less universal retail presence than HydraPak SoftFlask Speed",
    ],
    recommendationScore: 84,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-ud-body-bottle-500",
      "Ultimate Direction Body Bottle 500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-race-vest-6",
      "prod-ud-adventure-vest",
      "prod-ud-race-belt",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-salomon-soft-flask-speed-500",
      "prod-soft-flask-500",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-softflask-18oz",
    slug: "nathan-softflask-18oz",
    brandId: "brand-nathan",
    familyId: "fam-nathan-softflask",
    generation: "18oz",
    name: "SoftFlask 18oz",
    fullName: "Nathan SoftFlask 18oz",
    shortDescription:
      "~535 ml Nathan SoftFlask for vest and belt sleeves — brand-matched spare for VaporAir / Pinnacle runners who prefer Nathan flasks over HydraPak SoftFlask Speed.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-marathon"],
    specifications: {
      capacity: 535,
      volume: 535,
      weight: null,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU SoftFlask",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Nathan-ecosystem spare for VaporAir and Peak setups",
      "~18 oz / 535 ml covers most long-run flask refills",
      "Soft construction compresses as volume drops",
    ],
    weaknesses: [
      "Accessory only — no strap or vest included",
      "Cleaning overhead after electrolyte mixes",
    ],
    recommendationScore: 82,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-nathan-softflask-18oz",
      "Nathan SoftFlask 18oz — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-vaporair-4",
      "prod-nathan-peak",
      "prod-nathan-exoshot",
      "prod-hydrapak-softflask-500",
    ],
    alternativeProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-soft-flask-500",
      "prod-ud-body-bottle-500",
    ],
    ...pub,
  },

  // ─── Handhelds (cat-hydration) ───────────────────────────────────────────
  {
    id: "prod-amphipod-hydraform-handheld",
    slug: "amphipod-hydraform-ergo-lite-handheld",
    brandId: "brand-amphipod",
    familyId: "fam-amphipod-hydraform",
    generation: "Ergo-Lite",
    name: "Hydraform Ergo-Lite Handheld",
    fullName: "Amphipod Hydraform Ergo-Lite Handheld",
    shortDescription:
      "Amphipod Hydraform Ergo-Lite handheld bottle — ergonomic hard-bottle handheld for road longs when you want Amphipod carry without a belt or vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: null,
      type: "handheld",
      softHard: "hard",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: false,
      insulation: false,
      material: "Hard bottle + Hydraform hand strap",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Ergonomic hard bottle is easy to fill at aid stations",
      "Hand strap keeps carry secure without a vest",
      "Small stash pocket for gels/keys on many Hydraform kits",
    ],
    weaknesses: [
      "Does not compress — more swing than soft-flask handhelds",
      "Occupies a hand vs waist-belt hydration",
    ],
    recommendationScore: 78,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-amphipod-hydraform-handheld",
      "Amphipod Hydraform Ergo-Lite Handheld — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-airflow-lite-belt",
      "prod-nathan-quickdraw-plus",
      "prod-camelbak-quick-grip-chill",
      "prod-nathan-exoshot",
    ],
    alternativeProductIds: [
      "prod-nathan-quickdraw-plus",
      "prod-camelbak-quick-grip-chill",
      "prod-hydrapak-skyflask-speed-500",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-quickdraw-plus",
    slug: "nathan-quickdraw-plus-handheld",
    brandId: "brand-nathan",
    familyId: "fam-nathan-quickdraw",
    generation: "Plus",
    name: "QuickDraw Plus",
    fullName: "Nathan QuickDraw Plus Handheld",
    shortDescription:
      "Nathan QuickDraw Plus handheld — classic hard-bottle handheld with hand strap for road longs; simpler sibling to SpeedDraw Insulated when insulation is not the priority.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon", "uc-beginners"],
    specifications: {
      capacity: 535,
      volume: 535,
      weight: null,
      type: "handheld",
      softHard: "hard",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: false,
      insulation: false,
      material: "Hard bottle + QuickDraw hand strap",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Widely stocked Nathan handheld for first-time bottle runners",
      "Easy aid-station refill vs soft flasks",
      "Pairs cleanly with Nathan Peak waist-pack days",
    ],
    weaknesses: [
      "No insulation — fluids warm faster than SpeedDraw Insulated",
      "Hard bottle swing vs ExoShot / SkyFlask soft handhelds",
    ],
    recommendationScore: 80,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-nathan-quickdraw-plus",
      "Nathan QuickDraw Plus — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-speeddraw-insulated",
      "prod-nathan-exoshot",
      "prod-nathan-peak",
      "prod-amphipod-hydraform-handheld",
    ],
    alternativeProductIds: [
      "prod-nathan-speeddraw-insulated",
      "prod-nathan-exoshot",
      "prod-camelbak-quick-grip-chill",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-quick-grip-chill",
    slug: "camelbak-quick-grip-chill",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-quick-grip",
    generation: "Chill",
    name: "Quick Grip Chill",
    fullName: "CamelBak Quick Grip Chill Handheld",
    shortDescription:
      "Insulated CamelBak Quick Grip Chill handheld — keeps fluids cooler on hot road longs when you want CamelBak bite-valve familiarity without a Crux vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: null,
      type: "handheld",
      softHard: "hard",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: true,
      insulation: true,
      material: "Insulated hard bottle + Quick Grip strap",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Insulation helps on hot summer road blocks",
      "CamelBak bite-valve sipping without a reservoir vest",
      "Hand strap + pocket for gels on simpler long runs",
    ],
    weaknesses: [
      "Heavier than bare soft-flask handhelds",
      "One-handed volume limit vs belt or vest carry",
    ],
    recommendationScore: 81,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-camelbak-quick-grip-chill",
      "CamelBak Quick Grip Chill — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-speeddraw-insulated",
      "prod-nathan-quickdraw-plus",
      "prod-camelbak-crux-15",
      "prod-hydrapak-skyflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-nathan-speeddraw-insulated",
      "prod-nathan-quickdraw-plus",
      "prod-hydrapak-skyflask-speed-500",
    ],
    ...pub,
  },

  // ─── Reservoirs (cat-hydration) ──────────────────────────────────────────
  {
    id: "prod-hydrapak-contour-2l",
    slug: "hydrapak-contour-2l",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-contour",
    generation: "2L",
    name: "Contour 2L",
    fullName: "HydraPak Contour 2L Soft Reservoir",
    shortDescription:
      "2L HydraPak Contour soft reservoir — higher bladder volume than Shape-Shift 1.5L for hot ultras and adventure days when 1.5L refills are not enough.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-reservoirs"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training"],
    specifications: {
      capacity: 2000,
      volume: 2000,
      weight: null,
      type: "reservoir",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU Contour reservoir",
      includedFlasks: 0,
      bladderCompatible: true,
    },
    strengths: [
      "2L covers sparse-aid ultra days better than 1.5L bladders",
      "HydraPak ecosystem matches SoftFlask Speed / Shape-Shift spares",
      "Soft Contour profile aims to sit flatter in vest sleeves",
    ],
    weaknesses: [
      "More back weight and cleaning than flask-only race days",
      "Overkill when aid stations are dense",
    ],
    recommendationScore: 85,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-contour-2l",
      "HydraPak Contour 2L — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hydrapak-shape-shift-15",
      "prod-camelbak-crux-15",
      "prod-salomon-soft-reservoir-15",
      "prod-nathan-pinnacle-12",
    ],
    alternativeProductIds: [
      "prod-hydrapak-shape-shift-15",
      "prod-camelbak-crux-15",
      "prod-salomon-soft-reservoir-15",
    ],
    ...pub,
  },
  {
    id: "prod-salomon-soft-reservoir-15",
    slug: "salomon-soft-reservoir-15",
    brandId: "brand-salomon",
    familyId: "fam-salomon-soft-reservoir",
    generation: "1.5L",
    name: "Soft Reservoir 1.5L",
    fullName: "Salomon Soft Reservoir 1.5L",
    shortDescription:
      "1.5L Salomon Soft Reservoir — bladder option for ADV Skin / adventure-vest days when you want continuous sipping instead of front Soft Flask Speed refills alone.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-reservoirs"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training"],
    specifications: {
      capacity: 1500,
      volume: 1500,
      weight: null,
      type: "reservoir",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU Soft Reservoir",
      includedFlasks: 0,
      bladderCompatible: true,
    },
    strengths: [
      "Brand-matched bladder for Salomon vest sleeve geometry",
      "1.5L covers most long trail days without mid-run flask juggling",
      "Pairs with Soft Flask Speed spares for mixed hydration setups",
    ],
    weaknesses: [
      "Cleaning overhead vs flask-only race vests",
      "Adds back warmth vs front Soft Flask workflow",
    ],
    recommendationScore: 83,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-salomon-soft-reservoir-15",
      "Salomon Soft Reservoir 1.5L — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-soft-flask-500",
      "prod-salomon-soft-flask-speed-500",
      "prod-adv-skin-12",
      "prod-hydrapak-shape-shift-15",
    ],
    alternativeProductIds: [
      "prod-hydrapak-shape-shift-15",
      "prod-camelbak-crux-15",
      "prod-hydrapak-contour-2l",
    ],
    ...pub,
  },

  // ─── Socks (cat-running-socks) ───────────────────────────────────────────
  {
    id: "prod-bombas-performance-running-quarter",
    slug: "bombas-performance-running-quarter",
    brandId: "brand-bombas",
    familyId: "fam-bombas-performance-running",
    generation: "Performance Running Quarter",
    name: "Performance Running Quarter",
    fullName: "Bombas Performance Running Quarter",
    shortDescription:
      "Bombas Performance Running Quarter — cushioned everyday run sock with Bombas’ comfort-first fit story; approachable alternative when Balega Hidden Comfort plush is the benchmark.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-beginners", "uc-half"],
    specifications: {
      cushionLevel: "medium",
      height: "quarter",
      material: "Performance synthetic blend",
      compression: false,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Comfort-forward cushion for easy and daily road miles",
      "Quarter height stays put better than no-shows for many runners",
      "Widely available Bombas retail footprint",
    ],
    weaknesses: [
      "Less race-minimal than Feetures Elite Light Cushion",
      "Not a merino odor story like Darn Tough / Smartwool",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-bombas-performance-running-quarter",
      "Bombas Performance Running Quarter — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-balega-hidden-comfort",
      "prod-balega-blister-resist",
      "prod-feetures-elite-light-cushion",
      "prod-swiftwick-aspire-four",
    ],
    alternativeProductIds: [
      "prod-balega-hidden-comfort",
      "prod-feetures-elite-light-cushion",
      "prod-wrightsock-coolmesh-ii",
    ],
    ...pub,
  },
  {
    id: "prod-swiftwick-aspire-four",
    slug: "swiftwick-aspire-four",
    brandId: "brand-swiftwick",
    familyId: "fam-swiftwick-aspire",
    generation: "Aspire Four",
    name: "Aspire Four",
    fullName: "Swiftwick Aspire Four",
    shortDescription:
      "Swiftwick Aspire Four — thin, secure-fit quarter/crew-height performance sock for runners who want lock-down feel without plush Balega cushion.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-10k", "uc-half", "uc-marathon"],
    specifications: {
      cushionLevel: "light",
      height: "crew",
      material: "Olefin / nylon performance knit",
      compression: false,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Thin race-adjacent cushion with secure Swiftwick fit",
      "Popular among runners who dislike thick plush socks",
      "Strong blister-focus reputation for long road blocks",
    ],
    weaknesses: [
      "Too thin if you prefer Balega-style plush",
      "Premium vs basic athletic socks",
    ],
    recommendationScore: 86,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-swiftwick-aspire-four",
      "Swiftwick Aspire Four — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-feetures-elite-light-cushion",
      "prod-hilly-marathon-fresh",
      "prod-drymax-run-lite-mesh",
      "prod-darn-tough-run-1-4",
    ],
    alternativeProductIds: [
      "prod-feetures-elite-light-cushion",
      "prod-drymax-run-lite-mesh",
      "prod-hilly-marathon-fresh",
    ],
    ...pub,
  },
  {
    id: "prod-hilly-marathon-fresh",
    slug: "hilly-marathon-fresh",
    brandId: "brand-hilly",
    familyId: "fam-hilly-marathon-fresh",
    generation: "Marathon Fresh",
    name: "Marathon Fresh",
    fullName: "Hilly Marathon Fresh Socks",
    shortDescription:
      "Hilly Marathon Fresh — UK race/training sock staple with odor-management Fresh yarn story; value-leaning alternative to Feetures / Swiftwick for marathon blocks.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-10k"],
    specifications: {
      cushionLevel: "light",
      height: "crew",
      material: "Performance synthetic with Fresh yarn",
      compression: false,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Race/training staple with light cushion for marathon pace",
      "Fresh yarn odor story for high-mileage weeks",
      "Typically sharper value than US premium sock brands",
    ],
    weaknesses: [
      "Less plush than Balega Blister Resist",
      "Narrower US specialty distribution than Feetures",
    ],
    recommendationScore: 83,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-hilly-marathon-fresh",
      "Hilly Marathon Fresh — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-swiftwick-aspire-four",
      "prod-feetures-elite-light-cushion",
      "prod-cep-run-compression-sock",
      "prod-sockwell-compression-light",
    ],
    alternativeProductIds: [
      "prod-swiftwick-aspire-four",
      "prod-feetures-elite-light-cushion",
      "prod-drymax-run-lite-mesh",
    ],
    ...pub,
  },
  {
    id: "prod-drymax-run-lite-mesh",
    slug: "drymax-run-lite-mesh",
    brandId: "brand-drymax",
    familyId: "fam-drymax-run",
    generation: "Run Lite-Mesh",
    name: "Run Lite-Mesh",
    fullName: "Drymax Run Lite-Mesh",
    shortDescription:
      "Drymax Run Lite-Mesh — thin moisture-management run sock for hot days and blister-prone runners; Drymax dual-layer feel without thick cushion.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-trail-training"],
    specifications: {
      cushionLevel: "light",
      height: "crew",
      material: "Drymax dual-layer performance yarn",
      compression: false,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Moisture-focused Lite-Mesh build for hot long runs",
      "Blister-oriented dual-layer approach many runners swear by",
      "Light cushion stays race-adjacent",
    ],
    weaknesses: [
      "Fit preference is personal — try before race day",
      "Less plush comfort than Balega / Bombas",
    ],
    recommendationScore: 85,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-drymax-run-lite-mesh",
      "Drymax Run Lite-Mesh — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-swiftwick-aspire-four",
      "prod-injinji-run-midweight",
      "prod-balega-blister-resist",
      "prod-wrightsock-coolmesh-ii",
    ],
    alternativeProductIds: [
      "prod-wrightsock-coolmesh-ii",
      "prod-swiftwick-aspire-four",
      "prod-injinji-run-midweight",
    ],
    ...pub,
  },
  {
    id: "prod-sockwell-compression-light",
    slug: "sockwell-compression-light-cushion",
    brandId: "brand-sockwell",
    familyId: "fam-sockwell-compression",
    generation: "Compression Light Cushion",
    name: "Compression Light Cushion",
    fullName: "Sockwell Compression Light Cushion",
    shortDescription:
      "Sockwell light-cushion compression sock — milder graduated compression feel than CEP Run 3.0 with merino-blend comfort for daily and long road miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-high-mileage"],
    specifications: {
      cushionLevel: "light",
      height: "crew",
      material: "Merino wool blend with compression knit",
      compression: true,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Lighter compression entry than CEP race socks for many runners",
      "Merino-blend comfort and odor resistance",
      "Useful daily option when full medical-grade compression is not the goal",
    ],
    weaknesses: [
      "Less race-specific than CEP Run Compression Sock 3.0",
      "Sizing still matters for compression comfort",
    ],
    recommendationScore: 81,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-sockwell-compression-light",
      "Sockwell Compression Light Cushion — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-cep-run-compression-sock",
      "prod-smartwool-run-targeted-cushion",
      "prod-darn-tough-run-1-4",
      "prod-hilly-marathon-fresh",
    ],
    alternativeProductIds: [
      "prod-cep-run-compression-sock",
      "prod-smartwool-run-targeted-cushion",
      "prod-darn-tough-run-1-4",
    ],
    ...pub,
  },
  {
    id: "prod-wrightsock-coolmesh-ii",
    slug: "wrightsock-coolmesh-ii",
    brandId: "brand-wrightsock",
    familyId: "fam-wrightsock-coolmesh",
    generation: "Coolmesh II",
    name: "Coolmesh II",
    fullName: "Wrightsock Coolmesh II",
    shortDescription:
      "Wrightsock Coolmesh II — dual-layer anti-blister sock for hot road and trail miles; mesh ventilation when Drymax Lite-Mesh or Injinji toe separation is the blister strategy.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-socks",
    subcategoryIds: [],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-trail-training"],
    specifications: {
      cushionLevel: "light",
      height: "crew",
      material: "Dual-layer Coolmesh synthetic",
      compression: false,
      blisterFocus: true,
      genderFit: "unisex",
      sizeRange: "Confirm manufacturer size chart",
    },
    strengths: [
      "Dual-layer blister-focus design for hot long runs",
      "Mesh ventilation for warm-weather training",
      "Distinct approach vs single-layer Feetures / Balega socks",
    ],
    weaknesses: [
      "Dual-layer feel is an adaptation for some runners",
      "Less plush than Balega Hidden Comfort",
    ],
    recommendationScore: 84,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-socks",
      "prod-wrightsock-coolmesh-ii",
      "Wrightsock Coolmesh II — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-drymax-run-lite-mesh",
      "prod-injinji-run-midweight",
      "prod-balega-blister-resist",
      "prod-swiftwick-aspire-four",
    ],
    alternativeProductIds: [
      "prod-drymax-run-lite-mesh",
      "prod-injinji-run-midweight",
      "prod-balega-blister-resist",
    ],
    ...pub,
  },

  // ─── Belts (cat-running-belts) ───────────────────────────────────────────
  {
    id: "prod-amphipod-airflow-lite-belt",
    slug: "amphipod-airflow-lite-belt",
    brandId: "brand-amphipod",
    familyId: "fam-amphipod-airflow-belt",
    generation: "AirFlow Lite",
    name: "AirFlow Lite",
    fullName: "Amphipod AirFlow Lite Belt",
    shortDescription:
      "Amphipod AirFlow Lite running belt — breathable phone/essentials waist carry when FlipBelt or SPIbelt fit is not preferred; lighter sibling story to AirFlow armband carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone", "sub-belt-race"],
    useCaseIds: ["uc-daily-training", "uc-5k", "uc-10k", "uc-half", "uc-beginners"],
    specifications: {
      capacity: "Zip / stretch essentials pouch",
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Most modern phones (verify pocket size)",
      poles: false,
      bibAttachment: false,
      gelStorage: true,
      adjustability: "Dual-side webbing adjustment",
      bounce: "low",
      material: "Breathable mesh / stretch woven",
      waterResistance: "water-resistant",
      reflective: true,
    },
    strengths: [
      "Breathable AirFlow mesh for hot road miles",
      "Phone-first carry without FlipBelt stretch-tube feel",
      "Pairs with Amphipod Hydraform handhelds on longer days",
    ],
    weaknesses: [
      "Not built for bottles or large soft flasks",
      "Less cult bounce reputation than Naked Running Band",
    ],
    recommendationScore: 79,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-amphipod-airflow-lite-belt",
      "Amphipod AirFlow Lite Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-airflow-armband",
      "prod-amphipod-hydraform-handheld",
      "prod-spibelt-original",
      "prod-flipbelt-classic",
    ],
    alternativeProductIds: [
      "prod-spibelt-original",
      "prod-flipbelt-classic",
      "prod-nathan-zipster-lite",
    ],
    ...pub,
  },
  {
    id: "prod-fitletic-fully-loaded",
    slug: "fitletic-fully-loaded",
    brandId: "brand-fitletic",
    familyId: "fam-fitletic-fully-loaded",
    generation: "Fully Loaded",
    name: "Fully Loaded",
    fullName: "Fitletic Fully Loaded Running Belt",
    shortDescription:
      "Fitletic Fully Loaded race/essentials belt — multi-pocket phone and fuel carry for road races when you want structured pouches instead of FlipBelt stretch tubes.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-half", "uc-marathon", "uc-10k", "uc-5k"],
    specifications: {
      capacity: "Multi-pocket race belt",
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Phone in dedicated pocket (verify size)",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Dual-side buckle adjust",
      bounce: "low",
      material: "Stretch woven with zip pouches",
      waterResistance: "water-resistant",
      reflective: true,
    },
    strengths: [
      "Organized multi-pocket layout for gels and phone",
      "Bib-friendly race-day carry without a vest",
      "Structured alternative to FlipBelt / Naked stretch bands",
    ],
    weaknesses: [
      "Not hydration-first — bottles need a separate handheld or Peak pack",
      "More hardware than minimal stretch tubes",
    ],
    recommendationScore: 81,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-fitletic-fully-loaded",
      "Fitletic Fully Loaded — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-zipster-lite",
      "prod-ultraspire-fitted-race-belt",
      "prod-flipbelt-classic",
      "prod-kiprun-running-belt",
    ],
    alternativeProductIds: [
      "prod-nathan-zipster-lite",
      "prod-ultraspire-fitted-race-belt",
      "prod-spibelt-original",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-zipster-lite",
    slug: "nathan-zipster-lite",
    brandId: "brand-nathan",
    familyId: "fam-nathan-zipster",
    generation: "ZipSter Lite",
    name: "ZipSter Lite",
    fullName: "Nathan ZipSter Lite",
    shortDescription:
      "Nathan ZipSter Lite — low-profile zippered race belt for phone, gels and keys; lighter phone-first Nathan option vs Peak hydration waist pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone", "sub-belt-race"],
    useCaseIds: ["uc-daily-training", "uc-5k", "uc-10k", "uc-half", "uc-beginners"],
    specifications: {
      capacity: "Zippered essentials belt",
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Most phones in zip pocket (verify size)",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Dual-side webbing adjustment",
      bounce: "low",
      material: "Stretch woven with zip pocket",
      waterResistance: "water-resistant",
      reflective: true,
    },
    strengths: [
      "Zippered security for phone/keys on race day",
      "Low profile vs Peak bottle pack when hydration is handheld-only",
      "Nathan retail availability for beginners",
    ],
    weaknesses: [
      "No bottle holster — pair with QuickDraw / ExoShot if you need water",
      "Less minimal than Naked / FlipBelt stretch tubes",
    ],
    recommendationScore: 80,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-nathan-zipster-lite",
      "Nathan ZipSter Lite — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-mirage",
      "prod-nathan-peak",
      "prod-nathan-quickdraw-plus",
      "prod-fitletic-fully-loaded",
    ],
    alternativeProductIds: [
      "prod-nathan-mirage",
      "prod-spibelt-original",
      "prod-fitletic-fully-loaded",
    ],
    ...pub,
  },
  {
    id: "prod-kiprun-running-belt",
    slug: "kiprun-running-belt",
    brandId: "brand-decathlon",
    familyId: "fam-kiprun-belt",
    generation: "Running Belt",
    name: "Running Belt",
    fullName: "Kiprun Running Belt",
    shortDescription:
      "Decathlon Kiprun running belt — high-value phone/essentials waist carry for beginners who want race-day storage without FlipBelt or Nathan pricing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-phone", "sub-belt-race"],
    useCaseIds: ["uc-beginners", "uc-daily-training", "uc-5k", "uc-10k", "uc-half"],
    specifications: {
      capacity: "Essentials pouch belt",
      weight: null,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Phone in pouch (verify current size)",
      poles: false,
      bibAttachment: false,
      gelStorage: true,
      adjustability: "Adjustable webbing",
      bounce: "moderate",
      material: "Stretch woven / value race belt",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Excellent price entry via Decathlon retail",
      "Enough phone/gel carry for 5K–half beginners",
      "Natural companion to Kiprun Trail 10 vest on longer days",
    ],
    weaknesses: [
      "Bounce and polish lag FlipBelt / Naked / Fitletic",
      "Not a hydration belt — no bottle holster",
    ],
    recommendationScore: 76,
    valueScore: 94,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-kiprun-running-belt",
      "Kiprun Running Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-kiprun-trail-10",
      "prod-kiprun-900-race-5",
      "prod-fitletic-fully-loaded",
      "prod-spibelt-original",
      "prod-ultraspire-fitted-race-belt",
    ],
    alternativeProductIds: [
      "prod-spibelt-original",
      "prod-ultraspire-fitted-race-belt",
      "prod-amphipod-airflow-lite-belt",
    ],
    ...pub,
  },
];

/** Hold wave-3 SKUs without authentic heroes out of published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningHydrationSocksBeltsWave3Raw.map((p) => p.id),
);

export const runningHydrationSocksBeltsWave3: Product[] = applyMediaPublishGate(runningHydrationSocksBeltsWave3Raw, MEDIA_PENDING_DRAFT_IDS);
