import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 hydration catalog — race/trail vests, running belts, soft flasks,
 * handhelds and reservoirs beyond the wave-1 seeds.
 */
export const runningHydrationWave2Raw: Product[] = [
  // ─── Vests ───────────────────────────────────────────────────────────────
  {
    id: "prod-salomon-adv-skin-5",
    slug: "salomon-adv-skin-5",
    brandId: "brand-salomon",
    familyId: "fam-adv-skin",
    generation: "5",
    name: "ADV Skin 5",
    fullName: "Salomon ADV Skin 5",
    shortDescription:
      "5L race vest with twin 500 ml soft flasks — enough for gels, phone and jacket without the ADV Skin 12 bulk; trades rear volume for a lighter bounce-controlled fit on trail, ultra and road longs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs", "uc-marathon"],
    specifications: {
      capacity: 5,
      weight: 230,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Front soft-flask + stretch stash, rear zip compartment",
      frontStorage: "Twin soft-flask sleeves, gel loops, phone-capable stretch",
      rearStorage: "Main zip compartment for jacket/layer",
      pockets: "Multiple front stretch + rear main",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Sensifit custom dial / sternum straps",
      sizeRange: "XXS–XL",
      sizing: "XXS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Stable Salomon Sensifit race harness with low bounce",
      "Twin 500 ml flasks cover most long-run hydration without a bladder",
      "Enough rear volume for mandatory race kit without ADV Skin 12 bulk",
    ],
    weaknesses: [
      "No reservoir sleeve — bladder days need a larger ADV Skin or adventure vest",
      "5L fills fast once poles, jacket and food stack up on ultras",
    ],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-salomon-adv-skin-5",
      "Salomon ADV Skin 5 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-adv-skin-12",
      "prod-soft-flask-500",
      "prod-hydrapak-softflask-speed-500",
      "prod-ud-race-vest-6",
      "prod-nnormal-race-vest",
    ],
    alternativeProductIds: [
      "prod-ud-race-vest-6",
      "prod-nathan-vaporair-4",
      "prod-ultraspire-alpha-6",
      "prod-adv-skin-12",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-vaporair-4",
    slug: "nathan-vaporair-4",
    brandId: "brand-nathan",
    familyId: "fam-nathan-vaporair",
    generation: "4.0",
    name: "VaporAir 4.0",
    fullName: "Nathan VaporAir 4.0 8L",
    shortDescription:
      "Current-gen 8L Nathan race vest with twin front flasks — more rear stash than older VaporAirs for trail and road longs, still lighter than bladder-first adventure packs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra", "uc-marathon"],
    specifications: {
      capacity: 8,
      weight: 241,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Front flasks, side stretch, rear main compartment",
      frontStorage: "Soft-flask sleeves and fuel pockets",
      rearStorage: "8L-class main compartment",
      pockets: "Front stretch + rear zip/stretch mix",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Adaptive Fit / sternum ladder",
      sizeRange: "XS–XL",
      sizing: "XS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "8L capacity covers race kit without jumping to a 12L adventure vest",
      "Front-flask workflow stays fast on the move",
      "Clear upgrade path from VaporAir 2 for runners who outgrew rear stash",
    ],
    weaknesses: [
      "Not bladder-first — long desert/hot ultras may prefer Zephyr Pro or Pinnacle",
      "Unisex patterning may need careful sizing vs Osprey Duro/Dyna",
    ],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-nathan-vaporair-4",
      "Nathan VaporAir 4.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-vaporair-2",
      "prod-nathan-pinnacle-12",
      "prod-nathan-exoshot",
      "prod-ud-race-vest-6",
      "prod-salomon-adv-skin-5",
    ],
    alternativeProductIds: [
      "prod-nathan-vaporair-2",
      "prod-ud-race-vest-6",
      "prod-salomon-adv-skin-5",
      "prod-uswe-pace-8",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-pinnacle-12",
    slug: "nathan-pinnacle-12",
    brandId: "brand-nathan",
    familyId: "fam-nathan-pinnacle",
    generation: "12",
    name: "Pinnacle 12",
    fullName: "Nathan Pinnacle 12L",
    shortDescription:
      "Bladder-focused 12L Nathan vest for long trail and adventure days — reservoir-first hydration with room for layers, poles and food when soft flasks alone are not enough.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 12,
      weight: 320,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: true,
      totalHydrationCapacity: 1600,
      bottleCapacity: null,
      bladderCompatible: true,
      storage: "Rear reservoir sleeve plus large main pack volume",
      frontStorage: "Stretch pockets for flasks/fuel",
      rearStorage: "12L main + bladder sleeve",
      pockets: "Front stretch, side, rear main",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Sternum straps + side compression",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Reservoir-first layout suits hot, remote or mandatory-kit ultras",
      "12L volume absorbs jacket, food and poles without overstuffing front pockets",
      "Pairs cleanly with Nathan/HydraPak bladders already in the catalog",
    ],
    weaknesses: [
      "Heavier and warmer on the back than a flask-only race vest",
      "Reservoir cleaning overhead vs SoftFlask Speed workflow",
    ],
    recommendationScore: 84,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-nathan-pinnacle-12",
      "Nathan Pinnacle 12 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-vaporair-4",
      "prod-hydrapak-shape-shift-15",
      "prod-camelbak-crux-15",
      "prod-ud-adventure-vest",
      "prod-osprey-duro-15",
    ],
    alternativeProductIds: [
      "prod-ud-adventure-vest",
      "prod-camelbak-zephyr-pro",
      "prod-osprey-duro-15",
      "prod-adv-skin-12",
    ],
    ...pub,
  },
  {
    id: "prod-ud-race-vest-6",
    slug: "ultimate-direction-race-vest-6",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-race-vest",
    generation: "6.0",
    name: "Race Vest 6.0",
    fullName: "Ultimate Direction Race Vest 6.0",
    shortDescription:
      "Race-day 6L UD vest with twin front flasks — built for mandatory kit and fast front access, not max adventure volume; lighter trade-off vs the Adventure Vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs", "uc-marathon"],
    specifications: {
      capacity: 6,
      weight: 215,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Front flasks and race-kit pockets, compact rear",
      frontStorage: "Soft-flask sleeves, gel loops, phone stretch",
      rearStorage: "Compact main for jacket/kit",
      pockets: "UD front-pocket dense layout",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Comfort Cinch / Comfort Fit",
      sizeRange: "XS–XL",
      sizing: "XS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Classic UD front-pocket race layout for gels and flasks",
      "6L hits the sweet spot for trail race mandatory kit",
      "Lighter day-to-day than Adventure Vest or 12L packs",
    ],
    weaknesses: [
      "Limited rear volume for multi-day adventure packing",
      "No included bladder path — stick to flasks or step up to Adventure Vest",
    ],
    recommendationScore: 89,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-race-vest-6",
      "Ultimate Direction Race Vest 6.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-adventure-vest",
      "prod-ud-race-belt",
      "prod-hydrapak-softflask-speed-500",
      "prod-salomon-adv-skin-5",
      "prod-nathan-vaporair-4",
    ],
    alternativeProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-nathan-vaporair-4",
      "prod-ultraspire-alpha-6",
      "prod-ud-adventure-vest",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-zephyr-pro",
    slug: "camelbak-zephyr-pro",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-zephyr",
    generation: "Pro",
    name: "Zephyr Pro",
    fullName: "CamelBak Zephyr Pro",
    shortDescription:
      "~11L CamelBak race/trail vest combining Crux reservoir compatibility with front flask options — for runners who want bladder volume plus race-kit space without a hiking pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 11,
      weight: 340,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Front flasks, rear Crux sleeve, large stretch compartments",
      frontStorage: "Soft-flask sleeves and fuel pockets",
      rearStorage: "Main pack + reservoir sleeve (~11L)",
      pockets: "Front stretch, side, rear main",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Ventilated harness with sternum straps",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Bladder + flask flexibility for hot ultras and aid-sparse routes",
      "~11L covers layers and mandatory kit without a 15L run-hike pack",
      "Upgrades the standard Zephyr for runners who need more organization",
    ],
    weaknesses: [
      "Heavier than flask-only 5–6L race vests",
      "Crux reservoir sold separately on many kits — budget accordingly",
    ],
    recommendationScore: 86,
    valueScore: 77,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-camelbak-zephyr-pro",
      "CamelBak Zephyr Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-zephyr",
      "prod-camelbak-apex-pro",
      "prod-camelbak-crux-15",
      "prod-camelbak-circuit",
      "prod-nathan-pinnacle-12",
    ],
    alternativeProductIds: [
      "prod-camelbak-zephyr",
      "prod-camelbak-apex-pro",
      "prod-nathan-pinnacle-12",
      "prod-ud-adventure-vest",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-circuit",
    slug: "camelbak-circuit-run-vest",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-circuit",
    generation: "Circuit",
    name: "Circuit Run Vest",
    fullName: "CamelBak Circuit Run Vest",
    shortDescription:
      "Beginner-friendly ~5–5.5L CamelBak run vest often bundled with a Crux reservoir — simple bladder carry for long road/trail days before stepping up to Zephyr Pro or Apex Pro.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-beginners", "uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon"],
    specifications: {
      capacity: 5.5,
      weight: 280,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: true,
      reservoirIncluded: true,
      totalHydrationCapacity: 1500,
      bottleCapacity: null,
      bladderCompatible: true,
      storage: "Rear reservoir sleeve and modest stretch pockets",
      frontStorage: "Stretch pockets for phone/gels",
      rearStorage: "Crux reservoir + light stash",
      pockets: "Simple front/rear stretch layout",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Adjustable sternum / side straps",
      sizeRange: "S–L",
      sizing: "S–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["road", "trail"],
    },
    strengths: [
      "Approachable entry vest with reservoir often included",
      "Enough capacity for marathon/half longs without race-vest complexity",
      "Easy CamelBak Crux ecosystem for first-time bladder users",
    ],
    weaknesses: [
      "Not built for dense trail race mandatory kits or poles",
      "Less refined bounce control than Zephyr Pro / ADV Skin race fits",
    ],
    recommendationScore: 78,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-camelbak-circuit",
      "CamelBak Circuit Run Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-crux-15",
      "prod-camelbak-zephyr",
      "prod-camelbak-zephyr-pro",
      "prod-osprey-duro-lt",
      "prod-kiprun-trail-10",
    ],
    alternativeProductIds: [
      "prod-camelbak-zephyr",
      "prod-osprey-duro-6",
      "prod-kiprun-trail-10",
      "prod-ultraspire-spry-5",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-apex-pro",
    slug: "camelbak-apex-pro",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-apex",
    generation: "Pro",
    name: "Apex Pro Run Vest",
    fullName: "CamelBak Apex Pro Run Vest",
    shortDescription:
      "Premium ~11L CamelBak run vest for serious trail/ultra days — refined harness and storage over Circuit/Zephyr when you want bladder capacity and race organization in one pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-running-backpacks"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 11,
      weight: 350,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Premium front/rear organization with Crux sleeve",
      frontStorage: "Flask sleeves, zip and stretch fuel pockets",
      rearStorage: "~11L main + reservoir",
      pockets: "High-count race organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Premium ventilated harness",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Top CamelBak run-vest build for long ultra storage needs",
      "Bladder + flask dual hydration for variable aid spacing",
      "More refined organization than Circuit entry models",
    ],
    weaknesses: [
      "Premium price vs Circuit or Kiprun Trail 10 value picks",
      "Overbuilt for short road races or flask-only tempos",
    ],
    recommendationScore: 87,
    valueScore: 74,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-camelbak-apex-pro",
      "CamelBak Apex Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-zephyr-pro",
      "prod-camelbak-crux-15",
      "prod-camelbak-circuit",
      "prod-on-ultra-vest-pro",
      "prod-osprey-duro-15",
    ],
    alternativeProductIds: [
      "prod-camelbak-zephyr-pro",
      "prod-on-ultra-vest-pro",
      "prod-nathan-pinnacle-12",
      "prod-raidlight-responsiv-12",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-duro-lt",
    slug: "osprey-duro-lt",
    brandId: "brand-osprey",
    familyId: "fam-osprey-duro",
    generation: "LT",
    name: "Duro LT",
    fullName: "Osprey Duro LT",
    shortDescription:
      "Men’s minimal Osprey race vest in the soft-flask class (~1.5L pack volume) — for fast days when you only need twin flasks, phone and a thin layer, not a 6–15L pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon", "uc-trail-training"],
    specifications: {
      capacity: 1.5,
      weight: 160,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Minimal front flask focus with tiny rear stash",
      frontStorage: "Soft-flask sleeves and small stretch",
      rearStorage: "Minimal race stash",
      pockets: "Minimal front-centric",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: false,
      waterResistance: "none",
      fitSystem: "Osprey BioStretch harness (men)",
      sizeRange: "S–L",
      sizing: "S–L men’s (verify current chart)",
      genderFit: "men",
      raceSuitability: ["road", "trail"],
    },
    strengths: [
      "Truly minimal race carry with Osprey harness stability",
      "Ideal when Duro 6 / 15 would be empty dead weight",
      "Men’s patterning matches the wider Duro family",
    ],
    weaknesses: [
      "No reservoir and almost no mandatory-kit volume",
      "Women should look at Dyna LT instead",
    ],
    recommendationScore: 82,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-duro-lt",
      "Osprey Duro LT — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-dyna-lt",
      "prod-osprey-duro-6",
      "prod-osprey-duro-15",
      "prod-hydrapak-softflask-speed-500",
      "prod-nnormal-race-vest",
    ],
    alternativeProductIds: [
      "prod-osprey-dyna-lt",
      "prod-osprey-duro-6",
      "prod-salomon-adv-skin-5",
      "prod-compressport-ultrun-s-pack",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-dyna-lt",
    slug: "osprey-dyna-lt",
    brandId: "brand-osprey",
    familyId: "fam-osprey-dyna",
    generation: "LT",
    name: "Dyna LT",
    fullName: "Osprey Dyna LT",
    shortDescription:
      "Women’s counterpart to the Duro LT — minimal soft-flask race vest with Dyna harness shaping for fast road and trail days without 6L+ bulk.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon", "uc-trail-training"],
    specifications: {
      capacity: 1.5,
      weight: 155,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Minimal front flask focus with tiny rear stash",
      frontStorage: "Soft-flask sleeves and small stretch",
      rearStorage: "Minimal race stash",
      pockets: "Minimal front-centric",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: false,
      waterResistance: "none",
      fitSystem: "Osprey BioStretch harness (women)",
      sizeRange: "XS–L",
      sizing: "XS–L women’s (verify current chart)",
      genderFit: "women",
      raceSuitability: ["road", "trail"],
    },
    strengths: [
      "Women-specific Dyna harness on a true minimal race vest",
      "Soft-flask workflow without carrying empty Dyna 6 volume",
      "Pairs with Hydraulics LT if you later step up to Dyna 6 / larger packs",
    ],
    weaknesses: [
      "Not enough volume for pole-heavy trail ultras",
      "Men need Duro LT — this is gender-specific patterning",
    ],
    recommendationScore: 82,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-dyna-lt",
      "Osprey Dyna LT — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-duro-lt",
      "prod-osprey-dyna-6",
      "prod-hydrapak-softflask-speed-500",
      "prod-salomon-adv-skin-5",
      "prod-compressport-ultrun-s-pack",
    ],
    alternativeProductIds: [
      "prod-osprey-duro-lt",
      "prod-osprey-dyna-6",
      "prod-salomon-adv-skin-5",
      "prod-patagonia-slope-runner",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-duro-15",
    slug: "osprey-duro-15",
    brandId: "brand-osprey",
    familyId: "fam-osprey-duro",
    generation: "15",
    name: "Duro 15",
    fullName: "Osprey Duro 15",
    shortDescription:
      "Men’s 15L run-hike Osprey with Hydraulics reservoir support — for long trail days, adventure runs and kit-heavy ultras when Duro 6 / LT run out of rear volume.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking", "sub-pack-hydration-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 15,
      weight: 490,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bottleCapacity: null,
      bladderCompatible: true,
      storage: "Large rear pack volume with Hydraulics sleeve and front stretch",
      frontStorage: "Flask-compatible stretch and zip pockets",
      rearStorage: "15L main + reservoir sleeve",
      pockets: "Front, side, lid/rear organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Osprey BioStretch (men)",
      sizeRange: "S–L",
      sizing: "S–L men’s (verify current chart)",
      genderFit: "men",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "True run-hike capacity for cold starts, poles and big food loads",
      "Hydraulics ecosystem matches Osprey hiking kits",
      "Stable men’s Duro harness at high pack volume",
    ],
    weaknesses: [
      "Too much pack for road races or flask-only training",
      "Heavier bounce risk if under-packed — size down to Duro 6 / LT when possible",
    ],
    recommendationScore: 83,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-duro-15",
      "Osprey Duro 15 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-duro-6",
      "prod-osprey-duro-lt",
      "prod-osprey-hydraulics-15",
      "prod-osprey-dyna-6",
      "prod-black-diamond-distance-8",
    ],
    alternativeProductIds: [
      "prod-osprey-duro-6",
      "prod-nathan-pinnacle-12",
      "prod-raidlight-responsiv-12",
      "prod-on-ultra-vest-pro",
    ],
    ...pub,
  },
  {
    id: "prod-patagonia-slope-runner",
    slug: "patagonia-slope-runner-vest",
    brandId: "brand-patagonia",
    familyId: "fam-patagonia-slope-runner",
    generation: "Slope Runner",
    name: "Slope Runner Vest",
    fullName: "Patagonia Slope Runner Vest",
    shortDescription:
      "4L Patagonia race vest with twin flasks — stripped trail carry for runners who want light storage and brand durability without 8–12L adventure bulk.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-trail-training", "uc-long-runs", "uc-ultra"],
    specifications: {
      capacity: 4,
      weight: 195,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Front flasks and compact rear stretch",
      frontStorage: "Soft-flask sleeves and fuel stretch",
      rearStorage: "Compact 4L-class stash",
      pockets: "Minimal race layout",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Adjustable sternum straps",
      sizeRange: "XS–L",
      sizing: "XS–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Light 4L race profile with twin-flask hydration",
      "Durable Patagonia build for repeated trail seasons",
      "Less overpack temptation than 8–12L vests",
    ],
    weaknesses: [
      "Tight on big mandatory kits and jackets",
      "Fewer retail touchpoints than Salomon/UD/Nathan race staples",
    ],
    recommendationScore: 81,
    valueScore: 75,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-patagonia-slope-runner",
      "Patagonia Slope Runner Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-nnormal-race-vest",
      "prod-hydrapak-softflask-speed-500",
      "prod-osprey-dyna-lt",
      "prod-ultraspire-spry-5",
    ],
    alternativeProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-ud-race-vest-6",
      "prod-nnormal-race-vest",
      "prod-compressport-ultrun-s-pack",
    ],
    ...pub,
  },
  {
    id: "prod-uswe-pace-8",
    slug: "uswe-pace-8",
    brandId: "brand-uswe",
    familyId: "fam-uswe-pace",
    generation: "8",
    name: "Pace 8",
    fullName: "USWE Pace 8L",
    shortDescription:
      "8L USWE race vest with NDM no-dance harness — for runners who prioritize bounce control on technical trail and want more rear volume than a 5–6L flask vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 8,
      weight: 290,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2000,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "NDM harness with 8L rear and front flasks",
      frontStorage: "Soft-flask sleeves and fuel",
      rearStorage: "8L main compartment",
      pockets: "Front + rear race organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "USWE NDM (No Dancing Monkey) harness",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: [
      "NDM harness is purpose-built for low bounce on technical terrain",
      "8L bridges race-vest and light adventure capacity",
      "Supports flasks with optional bladder expansion",
    ],
    weaknesses: [
      "Brand niche — harder to try on than Salomon/Osprey/UD",
      "Harness learning curve vs standard sternum-ladder vests",
    ],
    recommendationScore: 85,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-uswe-pace-8",
      "USWE Pace 8 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-vaporair-4",
      "prod-black-diamond-distance-8",
      "prod-ud-race-vest-6",
      "prod-hydrapak-softflask-speed-500",
      "prod-ultraspire-alpha-6",
    ],
    alternativeProductIds: [
      "prod-nathan-vaporair-4",
      "prod-black-diamond-distance-8",
      "prod-salomon-adv-skin-5",
      "prod-ud-race-vest-6",
    ],
    ...pub,
  },
  {
    id: "prod-ultraspire-alpha-6",
    slug: "ultraspire-alpha-6",
    brandId: "brand-ultraspire",
    familyId: "fam-ultraspire-alpha",
    generation: "6.0",
    name: "Alpha 6.0",
    fullName: "UltrAspire Alpha 6.0 Race Vest",
    shortDescription:
      "6L UltrAspire race vest for trail and ultra race days — competitive with UD/Salomon flask layouts at a typically sharper value, with solid front access and race-kit room.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 6,
      weight: 220,
      includedFlasks: 2,
      includedFlaskVolume: 550,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1100,
      bottleCapacity: 1100,
      bladderCompatible: false,
      storage: "Front flasks and 6L race rear",
      frontStorage: "Bottle sleeves and gel/phone stretch",
      rearStorage: "Main race compartment",
      pockets: "Alpha race pocket layout",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "ErgoFit / Max O2 ventilated",
      sizeRange: "XS–XL",
      sizing: "XS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Strong value race vest against Salomon/UD pricing",
      "6L race-kit capacity with twin-flask hydration",
      "Ventilated UltrAspire harness for warm trail races",
    ],
    weaknesses: [
      "Less brand retail presence than Salomon or CamelBak",
      "Not bladder-oriented for desert ultra styles",
    ],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ultraspire-alpha-6",
      "UltrAspire Alpha 6.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ultraspire-spry-5",
      "prod-ultraspire-fitted-race-belt",
      "prod-ud-race-vest-6",
      "prod-salomon-adv-skin-5",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-ud-race-vest-6",
      "prod-salomon-adv-skin-5",
      "prod-ultraspire-spry-5",
      "prod-nathan-vaporair-4",
    ],
    ...pub,
  },
  {
    id: "prod-ultraspire-spry-5",
    slug: "ultraspire-spry-5",
    brandId: "brand-ultraspire",
    familyId: "fam-ultraspire-spry",
    generation: "5.0",
    name: "Spry 5.0",
    fullName: "UltrAspire Spry 5.0",
    shortDescription:
      "Budget-leaning ~3.5–5L UltrAspire race vest — entry race carry for flasks, phone and light kit when Alpha 6.0 or ADV Skin pricing feels like overkill.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-beginners", "uc-long-runs", "uc-trail-training", "uc-half"],
    specifications: {
      capacity: 5,
      weight: 200,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Compact race vest with front flasks",
      frontStorage: "Soft-flask sleeves and stretch",
      rearStorage: "Small main stash (~5L class)",
      pockets: "Simplified race layout",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Adjustable sternum straps",
      sizeRange: "S–L",
      sizing: "S–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "road", "ultra"],
    },
    strengths: [
      "Approachable price for a true race-vest layout",
      "Enough capacity for most road/trail long runs",
      "Natural step into UltrAspire before Alpha 6.0",
    ],
    weaknesses: [
      "Less polish and pocket count than Alpha / ADV Skin",
      "Limited pole and adventure storage",
    ],
    recommendationScore: 79,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ultraspire-spry-5",
      "UltrAspire Spry 5.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ultraspire-alpha-6",
      "prod-kiprun-trail-10",
      "prod-camelbak-circuit",
      "prod-hydrapak-softflask-500",
      "prod-ultraspire-fitted-race-belt",
    ],
    alternativeProductIds: [
      "prod-ultraspire-alpha-6",
      "prod-camelbak-circuit",
      "prod-kiprun-trail-10",
      "prod-salomon-adv-skin-5",
    ],
    ...pub,
  },
  {
    id: "prod-compressport-ultrun-s-pack",
    slug: "compressport-ultrun-s-pack",
    brandId: "brand-compressport",
    familyId: "fam-compressport-ultrun",
    generation: "S Pack",
    name: "Ultrun S Pack",
    fullName: "Compressport Ultrun S Pack",
    shortDescription:
      "Compression-fit Compressport race vest for trail/ultra — second-skin bounce control and flask carry for racers who want apparel-like fit over traditional pack volume.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs", "uc-marathon"],
    specifications: {
      capacity: 5,
      weight: 180,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Compression body with flask sleeves and stretch stash",
      frontStorage: "Soft-flask and gel pockets",
      rearStorage: "Compression rear stash",
      pockets: "Integrated stretch panels",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "none",
      fitSystem: "Compression second-skin sizing",
      sizeRange: "XS–XL",
      sizing: "Compression sizing — size carefully",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Second-skin compression fit keeps flasks planted",
      "Light race profile for fast mountain and road ultras",
      "Pairs with Compressport Free Belt Pro for extra fuel",
    ],
    weaknesses: [
      "Compression sizing is unforgiving if you size wrong",
      "Limited structured volume vs 8–12L adventure vests",
    ],
    recommendationScore: 83,
    valueScore: 76,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-compressport-ultrun-s-pack",
      "Compressport Ultrun S Pack — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-compressport-free-belt-pro",
      "prod-nnormal-race-vest",
      "prod-salomon-adv-skin-5",
      "prod-osprey-duro-lt",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-nnormal-race-vest",
      "prod-salomon-adv-skin-5",
      "prod-ud-race-vest-6",
      "prod-patagonia-slope-runner",
    ],
    ...pub,
  },
  {
    id: "prod-raidlight-responsiv-12",
    slug: "raidlight-responsiv-12",
    brandId: "brand-raidlight",
    familyId: "fam-raidlight-responsiv",
    generation: "12",
    name: "Responsiv 12",
    fullName: "RaidLight Responsiv 12L",
    shortDescription:
      "12L RaidLight trail/ultra vest for kit-heavy mountain days — European race staple with flask and storage density when you need more than a 6L race vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 12,
      weight: 310,
      includedFlasks: 2,
      includedFlaskVolume: 600,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2200,
      bottleCapacity: 1200,
      bladderCompatible: true,
      storage: "Dense front pockets plus 12L rear",
      frontStorage: "Large flask sleeves and race pockets",
      rearStorage: "12L main compartment",
      pockets: "High-count trail race layout",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Responsiv adjustable harness",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "12L mountain capacity with race-vest front access",
      "Strong European ultra race pedigree",
      "Handles poles, jacket and food without a hiking pack",
    ],
    weaknesses: [
      "Heavier than 5–6L flask-only race days",
      "Less common in US specialty shops than Salomon/Nathan",
    ],
    recommendationScore: 84,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-raidlight-responsiv-12",
      "RaidLight Responsiv 12 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-adv-skin-12",
      "prod-nathan-pinnacle-12",
      "prod-osprey-duro-15",
      "prod-ud-adventure-vest",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-adv-skin-12",
      "prod-nathan-pinnacle-12",
      "prod-camelbak-zephyr-pro",
      "prod-ud-adventure-vest",
    ],
    ...pub,
  },
  {
    id: "prod-nnormal-race-vest",
    slug: "nnormal-race-vest",
    brandId: "brand-nnormal",
    familyId: "fam-nnormal-race-vest",
    generation: "Race",
    name: "Race Vest",
    fullName: "NNormal Race Vest",
    shortDescription:
      "Race-minimal NNormal vest for fast trail and ultra efforts — stripped storage for flasks and essentials when you refuse adventure-pack bulk.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 5,
      weight: 170,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "Minimal race flask and stretch stash",
      frontStorage: "Soft-flask sleeves",
      rearStorage: "Minimal race kit pocket",
      pockets: "Race-minimal",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: true,
      waterResistance: "none",
      fitSystem: "Minimal sternum adjustment",
      sizeRange: "S–L",
      sizing: "S–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: [
      "True race-minimal profile for fast mountain efforts",
      "Low weight keeps the focus on running, not packing",
      "Aligns with NNormal trail-racing ethos",
    ],
    weaknesses: [
      "Little forgiveness for big jackets or adventure days",
      "Premium pricing for a deliberately small feature set",
    ],
    recommendationScore: 82,
    valueScore: 70,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-nnormal-race-vest",
      "NNormal Race Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-compressport-ultrun-s-pack",
      "prod-osprey-duro-lt",
      "prod-patagonia-slope-runner",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-compressport-ultrun-s-pack",
      "prod-ud-race-vest-6",
      "prod-osprey-duro-lt",
    ],
    ...pub,
  },
  {
    id: "prod-on-ultra-vest-pro",
    slug: "on-ultra-vest-pro",
    brandId: "brand-on",
    familyId: "fam-on-ultra-vest",
    generation: "Pro",
    name: "Ultra Vest Pro",
    fullName: "On Ultra Vest Pro",
    shortDescription:
      "On’s ~15L ultra vest for long mountain days — large rear volume and race organization when CloudTec runners want a matching high-capacity trail pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking", "sub-pack-hydration-vests"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 15,
      weight: 420,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Large ultra rear with front flasks",
      frontStorage: "Soft-flask and fuel pockets",
      rearStorage: "~15L main + optional bladder",
      pockets: "Premium ultra organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "On ultra harness",
      sizeRange: "XS–XL",
      sizing: "XS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "15L ultra capacity for cold, remote mountain races",
      "Premium On fit/finish for brand-loyal trail runners",
      "Supports flasks plus optional reservoir",
    ],
    weaknesses: [
      "Overkill for road longs and short trail races",
      "Premium price vs RaidLight / Osprey Duro 15 value peers",
    ],
    recommendationScore: 85,
    valueScore: 72,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-on-ultra-vest-pro",
      "On Ultra Vest Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-apex-pro",
      "prod-osprey-duro-15",
      "prod-raidlight-responsiv-12",
      "prod-hydrapak-shape-shift-15",
      "prod-black-diamond-distance-8",
    ],
    alternativeProductIds: [
      "prod-osprey-duro-15",
      "prod-camelbak-apex-pro",
      "prod-raidlight-responsiv-12",
      "prod-nathan-pinnacle-12",
    ],
    ...pub,
  },
  {
    id: "prod-black-diamond-distance-8",
    slug: "black-diamond-distance-8",
    brandId: "brand-black-diamond",
    familyId: "fam-black-diamond-distance",
    generation: "8",
    name: "Distance 8",
    fullName: "Black Diamond Distance 8",
    shortDescription:
      "8L Black Diamond running vest for alpine trail days — flask-friendly race capacity with mountain-brand durability when poles and light layers matter.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-hydration-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 8,
      weight: 275,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "8L trail race vest with front flasks",
      frontStorage: "Soft-flask sleeves and stretch",
      rearStorage: "8L main compartment",
      pockets: "Trail race layout with pole options",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Distance adjustable harness",
      sizeRange: "S–L",
      sizing: "S–L (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Mountain-brand build quality for rocky alpine trails",
      "8L hits race + light adventure without a 15L pack",
      "Strong pole attachment story for BD users",
    ],
    weaknesses: [
      "Narrower running specialty distribution than Salomon/UD",
      "No bladder sleeve for reservoir-first ultras",
    ],
    recommendationScore: 83,
    valueScore: 77,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-black-diamond-distance-8",
      "Black Diamond Distance 8 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-uswe-pace-8",
      "prod-nathan-vaporair-4",
      "prod-osprey-duro-15",
      "prod-on-ultra-vest-pro",
      "prod-hydrapak-softflask-speed-500",
    ],
    alternativeProductIds: [
      "prod-uswe-pace-8",
      "prod-nathan-vaporair-4",
      "prod-ud-race-vest-6",
      "prod-salomon-adv-skin-5",
    ],
    ...pub,
  },
  {
    id: "prod-kiprun-trail-10",
    slug: "kiprun-trail-10",
    brandId: "brand-decathlon",
    familyId: "fam-kiprun-trail",
    generation: "10",
    name: "Trail 10",
    fullName: "Kiprun Trail 10L Running Vest",
    shortDescription:
      "Budget Decathlon/Kiprun 10L trail vest — high value for beginners and volume seekers who want flask/race storage without premium Salomon or CamelBak pricing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-beginners", "uc-long-runs", "uc-trail-training", "uc-ultra"],
    specifications: {
      capacity: 10,
      weight: 300,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2000,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "10L trail vest with front flasks and rear stash",
      frontStorage: "Soft-flask sleeves and stretch",
      rearStorage: "10L main compartment",
      pockets: "Value trail layout",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Adjustable sternum / side straps",
      sizeRange: "S–XL",
      sizing: "S–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Excellent capacity-per-euro for first trail vest buyers",
      "10L covers race kit and layers on a beginner budget",
      "Widely available via Decathlon retail",
    ],
    weaknesses: [
      "Harness polish lags Salomon ADV Skin / Osprey Duro",
      "Long-term durability and bounce control are trade-offs for the price",
    ],
    recommendationScore: 80,
    valueScore: 94,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-kiprun-trail-10",
      "Kiprun Trail 10 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ultraspire-spry-5",
      "prod-camelbak-circuit",
      "prod-osprey-duro-6",
      "prod-hydrapak-softflask-500",
      "prod-ud-adventure-vest",
    ],
    alternativeProductIds: [
      "prod-ultraspire-spry-5",
      "prod-camelbak-circuit",
      "prod-osprey-duro-6",
      "prod-ultraspire-alpha-6",
    ],
    ...pub,
  },
  {
    id: "prod-kiprun-900-race-5",
    slug: "kiprun-900-race-5",
    brandId: "brand-decathlon",
    familyId: "fam-kiprun-900-race",
    generation: "900 Race 5L",
    name: "900 Race 5L",
    fullName: "Kiprun 900 Race 5L",
    shortDescription:
      "Kiprun’s current 5L race vest — 190 g, 10 pockets, twin 500 ml flask sleeves (flasks not included), three chest clips, sizes 2XS–XL — for road/trail race kit at Decathlon value, not a bladder ultra pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-road",
      "disc-running-racing",
    ],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: [
      "uc-trail-training",
      "uc-marathon",
      "uc-long-runs",
      "uc-beginners",
    ],
    specifications: {
      capacity: 5,
      weight: 190,
      includedFlasks: 0,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "5L race vest, 10 pockets, front flask sleeves",
      frontStorage: "Twin 500 ml flask sleeves (flasks sold separately) plus stretch stash",
      rearStorage: "Light race stash — not a 10L ultra bag",
      pockets: "10 pockets",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "high",
      reflectivity: true,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Three chest clips",
      sizeRange: "2XS–XL",
      sizing: "2XS–XL (verify current Decathlon chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "road", "ultra"],
    },
    strengths: [
      "190 g 5L race vest at Decathlon pricing",
      "Twin 500 ml flask workflow with 10 pockets and three chest clips",
      "Size ladder from 2XS–XL for a value race vest",
    ],
    weaknesses: [
      "Flasks not included; no bladder sleeve or pole quiver",
      "Harness polish lags Salomon ADV Skin / Osprey Duro on technical bounce days",
    ],
    recommendationScore: 78,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-kiprun-900-race-5",
      "Kiprun 900 Race 5L — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-kiprun-proteam-10",
      "prod-kiprun-running-belt",
      "prod-salomon-adv-skin-5",
    ],
    alternativeProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-ultraspire-spry-5",
      "prod-kiprun-proteam-10",
    ],
    ...pub,
  },
  {
    id: "prod-kiprun-proteam-10",
    slug: "kiprun-proteam-10",
    brandId: "brand-decathlon",
    familyId: "fam-kiprun-proteam",
    generation: "Proteam 10",
    name: "Proteam 10",
    fullName: "Kiprun Proteam 10",
    shortDescription:
      "Kiprun’s current 10L race vest — 170 g in M, 14 pockets, 2–3×500 ml flask sleeves (flasks not included), quiver compatible, no bladder — for race-kit trail days when the older Trail 10 naming is no longer the current aisle.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-ultra",
      "disc-running-racing",
    ],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: [
      "uc-trail-training",
      "uc-ultra",
      "uc-long-runs",
      "uc-intermediate",
    ],
    specifications: {
      capacity: 10,
      weight: 170,
      includedFlasks: 0,
      includedFlaskVolume: 500,
      flaskCount: 3,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1500,
      bottleCapacity: 1500,
      bladderCompatible: false,
      storage: "10L race vest, 14 pockets, flask-first, no bladder",
      frontStorage: "2–3×500 ml flask sleeves (flasks sold separately)",
      rearStorage: "10L race-kit stash",
      pockets: "14 pockets",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "moderate",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Adjustable race harness, 6 sizes",
      sizeRange: "6 sizes (verify current chart)",
      sizing: "Six sizes (verify current Decathlon chart); 170 g listed at M",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: [
      "170 g (M) 10L flask vest with 14 pockets and quiver compatibility",
      "Current Kiprun 10L race aisle — Blandine L’Hirondelle UTMB 2026 vest",
      "No bladder required: 2–3×500 ml flask workflow",
    ],
    weaknesses: [
      "Flasks not included; no reservoir sleeve if you want a back bladder",
      "Not a Salomon Sensifit / Osprey BioStretch polish story",
    ],
    recommendationScore: 82,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-kiprun-proteam-10",
      "Kiprun Proteam 10 — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-kiprun-900-race-5",
      "prod-ultraspire-spry-5",
      "prod-camelbak-circuit",
    ],
    alternativeProductIds: [
      "prod-ultraspire-spry-5",
      "prod-camelbak-circuit",
      "prod-kiprun-900-race-5",
    ],
    ...pub,
  },

  // ─── Belts ───────────────────────────────────────────────────────────────
  {
    id: "prod-nathan-peak",
    slug: "nathan-peak-hydration-waist-pack",
    brandId: "brand-nathan",
    familyId: "fam-nathan-peak",
    generation: "Peak",
    name: "Peak",
    fullName: "Nathan Peak Hydration Waist Pack",
    shortDescription:
      "Hydration waist pack with included ~535 ml SpeedDraw bottle — for runners who want bottle carry on the hips without a vest, trading capacity for simple road/trail longs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-hydration"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon"],
    specifications: {
      capacity: "~535 ml bottle + zip pocket",
      weight: 185,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: true,
      flaskIncluded: false,
      phoneFit: "Most modern phones in zip pocket (verify size)",
      poles: false,
      bibAttachment: false,
      gelStorage: true,
      adjustability: "Dual-side webbing adjustment",
      bounce: "moderate",
      material: "Stretch woven + molded bottle holster",
      waterResistance: "water-resistant",
      reflective: true,
    },
    strengths: [
      "Included SpeedDraw bottle means ready-to-run hydration",
      "Keeps hands free vs handhelds on road longs",
      "Phone + gels fit alongside the bottle for marathon training",
    ],
    weaknesses: [
      "Single-bottle volume limits hot ultras vs a vest",
      "More bounce than a well-fitted Naked Band or FlipBelt if sized poorly",
    ],
    recommendationScore: 81,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-nathan-peak",
      "Nathan Peak — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-speeddraw-insulated",
      "prod-nathan-mirage",
      "prod-ud-race-belt",
      "prod-nathan-exoshot",
      "prod-nathan-vaporair-4",
    ],
    alternativeProductIds: [
      "prod-ud-race-belt",
      "prod-ud-ultra-belt",
      "prod-nathan-exoshot",
      "prod-flipbelt-classic",
    ],
    ...pub,
  },
  {
    id: "prod-ud-race-belt",
    slug: "ultimate-direction-race-belt",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-race-belt",
    generation: "Race Belt",
    name: "Race Belt",
    fullName: "Ultimate Direction Race Belt",
    shortDescription:
      "UD soft-flask-capable race belt for gels, phone and lightweight hydration — vest alternative on road races and shorter trail days when you still want flask access.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-hydration"],
    useCaseIds: ["uc-long-runs", "uc-half", "uc-marathon", "uc-10k", "uc-trail-training"],
    specifications: {
      capacity: "Soft-flask pockets + stretch stash",
      weight: 90,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Phone in stretch pocket (size-dependent)",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Elastic + buckle / cord adjust",
      bounce: "low",
      material: "Stretch woven",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Soft-flask capable without buying a full vest",
      "Bib loops help race-day organization",
      "Low profile vs bottle holster packs like Peak",
    ],
    weaknesses: [
      "Flasks sold separately — budget SoftFlask Speed or 500 ml",
      "Less total volume than Ultra Belt for hot long runs",
    ],
    recommendationScore: 83,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-ud-race-belt",
      "Ultimate Direction Race Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-ultra-belt",
      "prod-ud-race-vest-6",
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-softflask-250",
      "prod-salomon-pulse-belt",
    ],
    alternativeProductIds: [
      "prod-ud-ultra-belt",
      "prod-nathan-peak",
      "prod-salomon-pulse-belt",
      "prod-naked-running-band",
    ],
    ...pub,
  },
  {
    id: "prod-ud-ultra-belt",
    slug: "ultimate-direction-ultra-belt",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-ultra-belt",
    generation: "Ultra Belt",
    name: "Ultra Belt",
    fullName: "Ultimate Direction Ultra Belt",
    shortDescription:
      "High-volume UD hydration belt for longer efforts — more flask/fuel capacity than Race Belt when you want waist carry instead of a vest on hot ultras and road longs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-hydration", "sub-belt-race"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-marathon", "uc-trail-training"],
    specifications: {
      capacity: "Multi soft-flask + large stretch volume",
      weight: 120,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Large stretch accommodates phone + flasks",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Wide elastic with dual adjust",
      bounce: "moderate",
      material: "High-stretch woven",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Highest UD belt volume for flask-heavy long runs",
      "Still lighter and cooler than most race vests",
      "Works with SoftFlask 250/500 and Speed flasks",
    ],
    weaknesses: [
      "Can bounce if overstuffed or sized large",
      "Not a substitute for mandatory-kit mountain vests",
    ],
    recommendationScore: 82,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-ud-ultra-belt",
      "Ultimate Direction Ultra Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-race-belt",
      "prod-ud-adventure-vest",
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-softflask-250",
      "prod-nathan-peak",
    ],
    alternativeProductIds: [
      "prod-ud-race-belt",
      "prod-nathan-peak",
      "prod-ud-race-vest-6",
      "prod-naked-running-band",
    ],
    ...pub,
  },
  {
    id: "prod-naked-running-band",
    slug: "naked-running-band",
    brandId: "brand-naked",
    familyId: "fam-naked-running-band",
    generation: "Running Band",
    name: "Running Band",
    fullName: "Naked Running Band",
    shortDescription:
      "Ultra-minimal stretch waist band for phone, gels and optional soft flasks — bounce-free essentials carry for runners who hate traditional zippered belts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-5k", "uc-10k"],
    specifications: {
      capacity: "Full-circumference stretch tube",
      weight: 55,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Most phones + soft flasks in stretch (size-dependent)",
      poles: false,
      bibAttachment: false,
      gelStorage: true,
      adjustability: "Sized stretch — pick circumference carefully",
      bounce: "low",
      material: "High-stretch knit",
      waterResistance: "none",
      reflective: false,
    },
    strengths: [
      "Industry-leading low bounce when sized correctly",
      "Can hold soft flasks without a dedicated holster belt",
      "No zipper snags on race day",
    ],
    weaknesses: [
      "Sweat reaches contents — phone case recommended",
      "Sizing is critical; wrong size = slip or squeeze",
    ],
    recommendationScore: 88,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-naked-running-band",
      "Naked Running Band — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-flipbelt-classic",
      "prod-compressport-free-belt-pro",
      "prod-salomon-pulse-belt",
      "prod-hydrapak-softflask-250",
      "prod-spibelt-original",
    ],
    alternativeProductIds: [
      "prod-flipbelt-classic",
      "prod-compressport-free-belt-pro",
      "prod-salomon-pulse-belt",
      "prod-ultraspire-fitted-race-belt",
    ],
    ...pub,
  },
  {
    id: "prod-ultraspire-fitted-race-belt",
    slug: "ultraspire-fitted-race-belt-2",
    brandId: "brand-ultraspire",
    familyId: "fam-ultraspire-fitted-race-belt",
    generation: "3.0",
    name: "Fitted Race Belt 3.0",
    fullName: "UltrAspire Fitted Race Belt 3.0",
    shortDescription:
      "Budget UltrAspire phone/essentials belt — fitted waist carry for gels, keys and phone when FlipBelt/Naked pricing or fit is not the priority.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-beginners", "uc-5k", "uc-10k", "uc-half"],
    specifications: {
      capacity: "Fitted stretch pocket belt",
      weight: 70,
      phoneCompatible: true,
      bottleCompatible: false,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Standard smartphone in fitted pocket",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Fitted sizes + minor adjust",
      bounce: "low",
      material: "Stretch knit",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Affordable race-belt option with bib loops",
      "Low profile for 5K–half essentials",
      "Pairs with UltrAspire Spry/Alpha if you later add a vest",
    ],
    weaknesses: [
      "Not built for bottles or large soft flasks",
      "Less cult fit reputation than Naked or FlipBelt",
    ],
    recommendationScore: 76,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-ultraspire-fitted-race-belt",
      "UltrAspire Fitted Race Belt 3.0 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ultraspire-spry-5",
      "prod-ultraspire-alpha-6",
      "prod-spibelt-original",
      "prod-nathan-mirage",
      "prod-flipbelt-classic",
    ],
    alternativeProductIds: [
      "prod-spibelt-original",
      "prod-flipbelt-classic",
      "prod-nathan-mirage",
      "prod-naked-running-band",
    ],
    ...pub,
  },
  {
    id: "prod-compressport-free-belt-pro",
    slug: "compressport-free-belt-pro",
    brandId: "brand-compressport",
    familyId: "fam-compressport-free-belt",
    generation: "Pro",
    name: "Free Belt Pro",
    fullName: "Compressport Free Belt Pro",
    shortDescription:
      "Compression waist belt for phone, gels and light flasks — Pro version of Compressport’s free-belt idea for race fuel without a pack, pairing well with Ultrun S Pack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-ultra"],
    specifications: {
      capacity: "Compression stretch circumference",
      weight: 48,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Phone + soft flasks in compression panels",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Sized compression — choose carefully",
      bounce: "low",
      material: "Compression knit",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Very low bounce compression fit",
      "Race-day gel/phone storage without a vest",
      "Natural companion to Compressport Ultrun S Pack",
    ],
    weaknesses: [
      "Compression sizing can feel tight over apparel layers",
      "Limited structured bottle holster vs Nathan Peak",
    ],
    recommendationScore: 85,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-compressport-free-belt-pro",
      "Compressport Free Belt Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-compressport-ultrun-s-pack",
      "prod-naked-running-band",
      "prod-salomon-pulse-belt",
      "prod-hydrapak-softflask-250",
      "prod-flipbelt-classic",
    ],
    alternativeProductIds: [
      "prod-naked-running-band",
      "prod-salomon-pulse-belt",
      "prod-flipbelt-classic",
      "prod-ud-race-belt",
    ],
    ...pub,
  },
  {
    id: "prod-salomon-pulse-belt",
    slug: "salomon-pulse-belt",
    brandId: "brand-salomon",
    familyId: "fam-salomon-pulse-belt",
    generation: "Pulse",
    name: "Pulse Belt",
    fullName: "Salomon Pulse Belt",
    shortDescription:
      "Salomon stretch race belt for phone, soft flasks and gels — low-profile waist carry that matches ADV Skin flask ecosystem on days you skip the vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-running-belts",
    subcategoryIds: ["sub-belt-race", "sub-belt-hydration", "sub-belt-phone"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-half", "uc-marathon", "uc-10k"],
    specifications: {
      capacity: "Stretch belt with flask-capable pockets",
      weight: 65,
      phoneCompatible: true,
      bottleCompatible: true,
      bottleIncluded: false,
      flaskIncluded: false,
      phoneFit: "Phone in dedicated stretch sleeve",
      poles: false,
      bibAttachment: true,
      gelStorage: true,
      adjustability: "Elastic with buckle adjust",
      bounce: "low",
      material: "Stretch woven",
      waterResistance: "none",
      reflective: true,
    },
    strengths: [
      "Works with Salomon/HydraPak soft flasks you already own",
      "Low bounce for marathon and trail race essentials",
      "Lighter alternative to ADV Skin 5 on cool, aid-dense courses",
    ],
    weaknesses: [
      "Less total hydration than Peak bottle pack or Ultra Belt",
      "Not a substitute for mandatory-kit trail vests",
    ],
    recommendationScore: 84,
    valueScore: 81,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-running-belts",
      "prod-salomon-pulse-belt",
      "Salomon Pulse Belt — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-salomon-adv-skin-5",
      "prod-soft-flask-500",
      "prod-hydrapak-softflask-250",
      "prod-naked-running-band",
      "prod-ud-race-belt",
    ],
    alternativeProductIds: [
      "prod-naked-running-band",
      "prod-compressport-free-belt-pro",
      "prod-ud-race-belt",
      "prod-flipbelt-classic",
    ],
    ...pub,
  },

  // ─── Handhelds / flasks / reservoirs ─────────────────────────────────────
  {
    id: "prod-hydrapak-softflask-speed-500",
    slug: "hydrapak-softflask-speed-500",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-softflask",
    generation: "Speed 500",
    name: "SoftFlask Speed 500",
    fullName: "HydraPak SoftFlask Speed 500",
    shortDescription:
      "500 ml SoftFlask Speed with high-flow bite valve — vest front standard for race vests; compresses as you drink and replaces classic SoftFlask 500 when you want faster sipping.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-marathon"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: 42,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU SoftFlask Speed",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "High-flow bite valve speeds drinking on the move",
      "Standard 500 ml vest-pocket footprint",
      "Compresses flat as volume drops — less bounce in front sleeves",
    ],
    weaknesses: [
      "Accessory only — needs a vest, belt or handheld sleeve",
      "Sugary drinks need thorough cleaning",
    ],
    recommendationScore: 88,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-softflask-speed-500",
      "HydraPak SoftFlask Speed 500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hydrapak-softflask-500",
      "prod-hydrapak-softflask-250",
      "prod-hydrapak-skyflask-speed-500",
      "prod-hydrapak-tube-kit",
      "prod-salomon-adv-skin-5",
      "prod-ud-race-vest-6",
    ],
    alternativeProductIds: [
      "prod-hydrapak-softflask-500",
      "prod-soft-flask-500",
      "prod-hydrapak-skyflask-speed-500",
    ],
    ...pub,
  },
  {
    id: "prod-hydrapak-skyflask-speed-500",
    slug: "hydrapak-skyflask-speed-500",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-skyflask",
    generation: "Speed 500",
    name: "SkyFlask Speed 500",
    fullName: "HydraPak SkyFlask Speed 500",
    shortDescription:
      "500 ml handheld SoftFlask with hand strap — for runners who want SoftFlask Speed flow without a vest, trading pack storage for simple one-bottle long runs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-trail-training"],
    specifications: {
      capacity: 500,
      volume: 500,
      weight: 68,
      type: "handheld",
      softHard: "soft",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU SoftFlask + handheld strap",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "True handheld SoftFlask Speed with secure strap",
      "Compresses as you drink — less water-bottle swing",
      "Small stash pocket for gels/keys on the sleeve",
    ],
    weaknesses: [
      "One-handed volume limit on hot ultras",
      "Occupies a hand vs belt or vest carry",
    ],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-skyflask-speed-500",
      "HydraPak SkyFlask Speed 500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-nathan-exoshot",
      "prod-nathan-speeddraw-insulated",
      "prod-soft-flask-500",
      "prod-naked-running-band",
    ],
    alternativeProductIds: [
      "prod-nathan-exoshot",
      "prod-nathan-speeddraw-insulated",
      "prod-hydrapak-softflask-speed-500",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-speeddraw-insulated",
    slug: "nathan-speeddraw-plus-insulated-18oz",
    brandId: "brand-nathan",
    familyId: "fam-nathan-speeddraw",
    generation: "Plus Insulated 18oz",
    name: "SpeedDraw Plus Insulated",
    fullName: "Nathan SpeedDraw Plus Insulated 18oz",
    shortDescription:
      "Insulated ~535 ml Nathan handheld hard bottle — keeps fluids cooler on hot road longs; pairs with Peak waist pack or solo handheld carry when soft flasks are not preferred.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-handheld"],
    useCaseIds: ["uc-long-runs", "uc-daily-training", "uc-half", "uc-marathon"],
    specifications: {
      capacity: 535,
      volume: 535,
      weight: 120,
      type: "handheld",
      softHard: "hard",
      handStrap: true,
      pocket: true,
      phoneCapacity: false,
      biteValve: false,
      insulation: true,
      material: "Insulated hard bottle + hand strap",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Insulation helps on hot summer road longs",
      "Hard bottle is easier to fill/clean for some runners than soft flasks",
      "Matches Nathan Peak holster ecosystem",
    ],
    weaknesses: [
      "Does not compress — more swing than SoftFlask Speed",
      "Heavier than a bare 500 ml soft flask",
    ],
    recommendationScore: 80,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-nathan-speeddraw-insulated",
      "Nathan SpeedDraw Plus Insulated — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-peak",
      "prod-nathan-exoshot",
      "prod-hydrapak-skyflask-speed-500",
      "prod-nathan-mirage",
      "prod-nathan-vaporair-4",
    ],
    alternativeProductIds: [
      "prod-nathan-exoshot",
      "prod-hydrapak-skyflask-speed-500",
      "prod-nathan-peak",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-crux-15",
    slug: "camelbak-crux-15",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-crux",
    generation: "1.5L",
    name: "Crux 1.5L",
    fullName: "CamelBak Crux 1.5L Reservoir",
    shortDescription:
      "1.5L CamelBak Crux reservoir with bite valve — the bladder standard for Zephyr, Circuit and Apex Pro run vests when you want continuous sipping without front flasks.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-reservoirs"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training"],
    specifications: {
      capacity: 1500,
      volume: 1500,
      weight: 145,
      type: "reservoir",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "Crux TPU reservoir",
      includedFlasks: 0,
      bladderCompatible: true,
    },
    strengths: [
      "Widely compatible with CamelBak run vests",
      "1.5L covers most long trail days without mid-run refills",
      "High-flow Crux bite valve is easy to drink from while moving",
    ],
    weaknesses: [
      "Cleaning overhead vs soft flasks",
      "Adds back weight and warmth in a vest sleeve",
    ],
    recommendationScore: 86,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-camelbak-crux-15",
      "CamelBak Crux 1.5L — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-zephyr",
      "prod-camelbak-zephyr-pro",
      "prod-camelbak-circuit",
      "prod-camelbak-apex-pro",
      "prod-osprey-hydraulics-15",
      "prod-hydrapak-shape-shift-15",
    ],
    alternativeProductIds: [
      "prod-osprey-hydraulics-15",
      "prod-hydrapak-shape-shift-15",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-hydraulics-15",
    slug: "osprey-hydraulics-lt-15",
    brandId: "brand-osprey",
    familyId: "fam-osprey-hydraulics",
    generation: "LT 1.5L",
    name: "Hydraulics LT 1.5L",
    fullName: "Osprey Hydraulics LT 1.5L Reservoir",
    shortDescription:
      "1.5L Osprey Hydraulics LT reservoir — lightweight bladder for Duro/Dyna packs when you want continuous hydration without stacking front flasks.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-reservoirs"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training"],
    specifications: {
      capacity: 1500,
      volume: 1500,
      weight: 135,
      type: "reservoir",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "Hydraulics LT TPU",
      includedFlasks: 0,
      bladderCompatible: true,
    },
    strengths: [
      "Designed for Osprey Duro/Dyna sleeve geometry",
      "LT build keeps reservoir weight down for running",
      "Reliable bite-valve sipping on long trail days",
    ],
    weaknesses: [
      "Best inside Osprey-compatible packs — less universal than HydraPak Shape-Shift",
      "Same cleaning chore as any bladder",
    ],
    recommendationScore: 85,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-osprey-hydraulics-15",
      "Osprey Hydraulics LT 1.5L — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-duro-6",
      "prod-osprey-duro-15",
      "prod-osprey-dyna-6",
      "prod-camelbak-crux-15",
      "prod-hydrapak-shape-shift-15",
    ],
    alternativeProductIds: [
      "prod-camelbak-crux-15",
      "prod-hydrapak-shape-shift-15",
    ],
    ...pub,
  },
  {
    id: "prod-hydrapak-shape-shift-15",
    slug: "hydrapak-shape-shift-15",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-shape-shift",
    generation: "1.5L",
    name: "Shape-Shift 1.5L",
    fullName: "HydraPak Shape-Shift 1.5L",
    shortDescription:
      "1.5L HydraPak Shape-Shift reservoir with internal baffle — stays flatter in vest sleeves for Nathan Pinnacle, CamelBak and other bladder-compatible race packs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-reservoirs"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training"],
    specifications: {
      capacity: 1500,
      volume: 1500,
      weight: 140,
      type: "reservoir",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU Shape-Shift with baffle",
      includedFlasks: 0,
      bladderCompatible: true,
    },
    strengths: [
      "Internal baffle reduces water-brick bounce in the back panel",
      "Brand-agnostic fit for many race/adventure vests",
      "Same HydraPak ecosystem as SoftFlask Speed spares",
    ],
    weaknesses: [
      "Still requires thorough cleaning after electrolyte mixes",
      "Not needed if you prefer flask-only race vests",
    ],
    recommendationScore: 87,
    valueScore: 85,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-shape-shift-15",
      "HydraPak Shape-Shift 1.5L — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-pinnacle-12",
      "prod-camelbak-crux-15",
      "prod-osprey-hydraulics-15",
      "prod-hydrapak-tube-kit",
      "prod-camelbak-zephyr-pro",
      "prod-on-ultra-vest-pro",
    ],
    alternativeProductIds: [
      "prod-camelbak-crux-15",
      "prod-osprey-hydraulics-15",
    ],
    ...pub,
  },
  {
    id: "prod-hydrapak-softflask-250",
    slug: "hydrapak-softflask-250",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-softflask",
    generation: "250",
    name: "SoftFlask 250",
    fullName: "HydraPak SoftFlask 250 ml",
    shortDescription:
      "250 ml SoftFlask for vest front lower pockets and race belts — smaller sibling to 500 ml Speed flasks when you want gels-adjacent sip volume or dual-size vest setups.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-daily-training"],
    specifications: {
      capacity: 250,
      volume: 250,
      weight: 28,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "TPU SoftFlask",
      includedFlasks: 1,
      bladderCompatible: false,
    },
    strengths: [
      "Fits tighter vest pockets and many race belts",
      "Light way to carry electrolytes alongside 500 ml water flasks",
      "Compresses almost flat when empty",
    ],
    weaknesses: [
      "Too small as sole hydration on hot long runs",
      "Same cleaning needs as larger SoftFlasks",
    ],
    recommendationScore: 81,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-softflask-250",
      "HydraPak SoftFlask 250 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-softflask-500",
      "prod-ud-race-belt",
      "prod-salomon-pulse-belt",
      "prod-naked-running-band",
      "prod-salomon-adv-skin-5",
    ],
    alternativeProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-softflask-500",
      "prod-soft-flask-500",
    ],
    ...pub,
  },
  {
    id: "prod-hydrapak-tube-kit",
    slug: "hydrapak-tube-kit",
    brandId: "brand-hydrapak",
    familyId: "fam-hydrapak-tube-kit",
    generation: "Tube Kit",
    name: "Tube Kit",
    fullName: "HydraPak Tube Kit",
    shortDescription:
      "HydraPak drink-tube accessory kit for SoftFlask and reservoir setups — convert front flasks or bladders to tube sipping; not a hydration vessel itself (capacity 0).",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-hydration",
    subcategoryIds: ["sub-soft-flasks"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-long-runs"],
    specifications: {
      capacity: 0,
      volume: 0,
      weight: 35,
      type: "soft-flask",
      softHard: "soft",
      handStrap: false,
      pocket: false,
      phoneCapacity: false,
      biteValve: true,
      insulation: false,
      material: "Drink tube + connectors (accessory kit)",
      includedFlasks: 0,
      bladderCompatible: true,
      storage: "Accessory tube kit — no fluid capacity",
    },
    strengths: [
      "Lets you tube-sip SoftFlasks or reservoirs hands-free",
      "Spare parts extend SoftFlask Speed / Shape-Shift life",
      "Useful for runners who dislike tipping flasks at race pace",
    ],
    weaknesses: [
      "Adds tube cleaning and routing complexity",
      "Zero capacity alone — must pair with flasks or a bladder",
    ],
    recommendationScore: 72,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hydration",
      "prod-hydrapak-tube-kit",
      "HydraPak Tube Kit — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-softflask-500",
      "prod-hydrapak-shape-shift-15",
      "prod-hydrapak-softflask-250",
      "prod-salomon-adv-skin-5",
    ],
    alternativeProductIds: [
      "prod-hydrapak-softflask-speed-500",
      "prod-hydrapak-shape-shift-15",
    ],
    ...pub,
  },
];

/** Hold wave-2 hydration SKUs without authentic heroes out of published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set([
  "prod-camelbak-zephyr-pro",
  "prod-osprey-dyna-lt",
  "prod-osprey-duro-15",
  "prod-patagonia-slope-runner",
  "prod-compressport-ultrun-s-pack",
  "prod-raidlight-responsiv-12",
  "prod-kiprun-trail-10",
  "prod-compressport-free-belt-pro",
  "prod-osprey-hydraulics-15",
  "prod-hydrapak-shape-shift-15",
  "prod-hydrapak-tube-kit",
]);

export const runningHydrationWave2: Product[] = applyMediaPublishGate(runningHydrationWave2Raw, MEDIA_PENDING_DRAFT_IDS);
