import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 1 Running Nutrition / Fuel catalog — gels, chews, bars, carb drink mixes,
 * and electrolyte products for training and racing.
 *
 * Sports-product decision content only. Label numbers use published values when
 * known; null when uncertain. No medical claims, no invented allergen labels.
 *
 */
export const runningNutritionWave1Raw: Product[] = [
  // ─── Energy gels ─────────────────────────────────────────────────────────
  {
    id: "prod-maurten-gel-100",
    slug: "maurten-gel-100",
    brandId: "brand-maurten",
    familyId: "fam-maurten-gel",
    generation: "100",
    name: "Gel 100",
    fullName: "Maurten Gel 100",
    shortDescription:
      "Hydrogel sachet delivering 25g carbs (~100 kcal) per label in a firm, near-neutral texture — designed for precise race and long-run carb stacking when you want a compact gel without caffeine.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra", "disc-running-trail"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-long-runs",
      "uc-half",
      "uc-marathon",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
      "uc-high-carb-fueling",
    ],
    specifications: {
      type: "gel",
      servingSize: "40g sachet",
      calories: 100,
      carbsPerServing: 25,
      sugars: 25,
      sodium: 22,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Optional — often taken without extra water",
      form: "gel",
      flavour: "Neutral / unflavoured",
      packSize: "Box of 12",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "25g carbs per sachet makes hourly fueling math straightforward",
      "Firm hydrogel texture many runners prefer over sticky syrup gels",
      "No caffeine — easy to mix with separate caffeinated servings later",
    ],
    weaknesses: [
      "Premium price per gram of carbohydrate vs mainstream gels",
      "Near-neutral flavour is polarising if you want bright fruit taste",
      "Low sodium — pair with a separate electrolyte plan when needed",
    ],
    recommendationScore: 90,
    valueScore: 68,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-maurten-gel-100",
      "Maurten Gel 100 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-gel-100-caf",
      "prod-maurten-gel-160",
      "prod-maurten-drink-mix-160",
      "prod-precision-pf30-gel",
      "prod-neversecond-c30-gel",
    ],
    alternativeProductIds: [
      "prod-precision-pf30-gel",
      "prod-sis-go-isotonic-gel",
      "prod-gu-energy-gel",
      "prod-neversecond-c30-gel",
    ],
    ...pub,
  },
  {
    id: "prod-maurten-gel-100-caf",
    slug: "maurten-gel-100-caf-100",
    brandId: "brand-maurten",
    familyId: "fam-maurten-gel",
    generation: "100 Caf 100",
    name: "Gel 100 Caf 100",
    fullName: "Maurten Gel 100 Caf 100",
    shortDescription:
      "Same 25g-carb hydrogel format as Gel 100 with ~100mg caffeine per sachet — designed for late-race or key-session preference when you want carb + caffeine in one easy-carry packet.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-marathon",
      "uc-half",
      "uc-long-runs",
      "uc-caffeinated-fuel",
      "uc-easy-carry-fuel",
      "uc-high-carb-fueling",
    ],
    specifications: {
      type: "gel",
      servingSize: "40g sachet",
      calories: 100,
      carbsPerServing: 25,
      sugars: 25,
      sodium: 22,
      caffeine: true,
      caffeineAmount: 100,
      protein: 0,
      fluidRequired: "Optional — often taken without extra water",
      form: "gel",
      flavour: "Neutral / unflavoured",
      packSize: "Box of 12",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "100mg caffeine option stacks cleanly with non-caf Gel 100 servings",
      "Same firm hydrogel texture and 25g carb dose as the base gel",
      "Compact race-vest carry for late miles",
    ],
    weaknesses: [
      "Caffeine timing still needs a practiced race plan",
      "Same premium pricing as other Maurten gels",
      "Not ideal if you want zero-caffeine fuel only",
    ],
    recommendationScore: 89,
    valueScore: 66,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-maurten-gel-100-caf",
      "Maurten Gel 100 Caf 100 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-gel-100",
      "prod-maurten-gel-160",
      "prod-gu-roctane-gel",
      "prod-precision-pf30-gel",
    ],
    alternativeProductIds: [
      "prod-maurten-gel-100",
      "prod-gu-roctane-gel",
      "prod-sis-beta-fuel-gel",
      "prod-neversecond-c30-gel",
    ],
    ...pub,
  },
  {
    id: "prod-maurten-gel-160",
    slug: "maurten-gel-160",
    brandId: "brand-maurten",
    familyId: "fam-maurten-gel",
    generation: "160",
    name: "Gel 160",
    fullName: "Maurten Gel 160",
    shortDescription:
      "Higher-carb Maurten hydrogel delivering 40g carbs (~160 kcal) per sachet — designed for high-carb race fueling when you want fewer packets to hit the same hourly carb target.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: [
      "uc-marathon",
      "uc-ultra",
      "uc-high-carb-fueling",
      "uc-long-runs",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "1 sachet",
      calories: 160,
      carbsPerServing: 40,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Optional — often taken without extra water",
      form: "gel",
      flavour: "Neutral / unflavoured",
      packSize: "Box of 10",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "40g carbs per packet reduces packet count on high-carb race plans",
      "Same hydrogel family as Gel 100 for consistent texture preference",
      "Non-caffeinated — flexible alongside separate caffeine servings",
    ],
    weaknesses: [
      "Larger carb hit needs gut practice before race day",
      "Premium cost and limited flavour variety",
      "Still low sodium vs dedicated electrolyte products",
    ],
    recommendationScore: 91,
    valueScore: 70,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-maurten-gel-160",
      "Maurten Gel 160 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-gel-100",
      "prod-maurten-drink-mix-320",
      "prod-sis-beta-fuel-gel",
      "prod-precision-pf30-gel",
    ],
    alternativeProductIds: [
      "prod-sis-beta-fuel-gel",
      "prod-maurten-drink-mix-320",
      "prod-styrkr-mix90",
      "prod-neversecond-c30-gel",
    ],
    ...pub,
  },
  {
    id: "prod-sis-go-isotonic-gel",
    slug: "sis-go-isotonic-gel",
    brandId: "brand-sis",
    familyId: "fam-sis-go",
    generation: "GO Isotonic",
    name: "GO Isotonic Gel",
    fullName: "Science in Sport GO Isotonic Energy Gel",
    shortDescription:
      "Thinner isotonic gel with 22g carbs (~87 kcal) per 60ml sachet — designed for runners who want an easy-take gel that typically needs little or no extra fluid at the moment of use.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-trail"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-short-training",
      "uc-half",
      "uc-marathon",
      "uc-long-runs",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "gel",
      servingSize: "60ml sachet",
      calories: 87,
      carbsPerServing: 22,
      sugars: 0.6,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Low — marketed as isotonic / often without extra water",
      form: "gel",
      flavour: "Multiple fruit flavours",
      packSize: "Box of 30",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "Thinner isotonic texture is approachable for gel beginners",
      "Widely available and strong value per serving",
      "Broad flavour range for training variety",
    ],
    weaknesses: [
      "22g carbs means more packets to hit high hourly carb targets",
      "Single-source carb profile vs modern dual-carb race gels",
      "Less carb-dense than Beta Fuel / PF30 / Gel 160 formats",
    ],
    recommendationScore: 82,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-sis-go-isotonic-gel",
      "SiS GO Isotonic Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-sis-beta-fuel-gel",
      "prod-gu-energy-gel",
      "prod-honey-stinger-gel",
      "prod-high5-zero",
    ],
    alternativeProductIds: [
      "prod-gu-energy-gel",
      "prod-honey-stinger-gel",
      "prod-precision-pf30-gel",
      "prod-sis-beta-fuel-gel",
    ],
    ...pub,
  },
  {
    id: "prod-sis-beta-fuel-gel",
    slug: "sis-beta-fuel-gel",
    brandId: "brand-sis",
    familyId: "fam-sis-beta-fuel",
    generation: "Beta Fuel",
    name: "Beta Fuel Gel",
    fullName: "Science in Sport Beta Fuel Dual Source Energy Gel",
    shortDescription:
      "High-carb dual-source gel with 40g carbs (~158 kcal) per serving — designed for marathon and long race fueling when you want SiS availability with fewer packets than GO Isotonic.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: [
      "uc-marathon",
      "uc-ultra",
      "uc-high-carb-fueling",
      "uc-long-runs",
      "uc-half",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "60ml sachet",
      calories: 158,
      carbsPerServing: 40,
      sugars: 19,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water available recommended for thicker dual-carb gels",
      form: "gel",
      flavour: "Orange / Lemon & Lime (typical)",
      packSize: "Box of 30",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "40g carbs per gel supports high-carb race targets with fewer packets",
      "Dual-source maltodextrin/fructose format for structured endurance fueling",
      "Strong retail availability vs niche race-fuel brands",
    ],
    weaknesses: [
      "Thicker than GO Isotonic — practice fluid timing on long runs",
      "Fewer flavour options than the GO range",
      "Still not a high-sodium electrolyte product",
    ],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-sis-beta-fuel-gel",
      "SiS Beta Fuel Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-sis-beta-fuel-drink",
      "prod-sis-go-isotonic-gel",
      "prod-maurten-gel-160",
      "prod-precision-pf30-gel",
    ],
    alternativeProductIds: [
      "prod-maurten-gel-160",
      "prod-precision-pf30-gel",
      "prod-neversecond-c30-gel",
      "prod-sis-go-isotonic-gel",
    ],
    ...pub,
  },
  {
    id: "prod-gu-energy-gel",
    slug: "gu-energy-gel",
    brandId: "brand-gu",
    familyId: "fam-gu-energy",
    generation: "Energy Gel",
    name: "Energy Gel",
    fullName: "GU Energy Gel",
    shortDescription:
      "Classic ~22g-carb energy gel with wide flavour choice — designed as an accessible training and race staple when you want easy retail availability and familiar packet size for vest or belt carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-short-training",
      "uc-long-runs",
      "uc-half",
      "uc-marathon",
      "uc-easy-carry-fuel",
      "uc-trail-training",
      "uc-beginners",
    ],
    specifications: {
      type: "gel",
      servingSize: "32g packet",
      calories: 100,
      carbsPerServing: 22,
      sugars: null,
      sodium: 60,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water recommended with thicker classic gels",
      form: "gel",
      flavour: "Multiple flavours (caffeine varies by SKU)",
      packSize: "Box of 24",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Ubiquitous retail availability and flavour variety",
      "Compact packets pack easily in belts and vest pockets",
      "Strong value for everyday long-run practice",
    ],
    weaknesses: [
      "22g carbs is lower density than modern 30–40g race gels",
      "Stickier syrup texture vs hydrogel / isotonic options",
      "Check flavour SKUs carefully — some include caffeine",
    ],
    recommendationScore: 78,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-gu-energy-gel",
      "GU Energy Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-gu-roctane-gel",
      "prod-gu-chews",
      "prod-sis-go-isotonic-gel",
      "prod-honey-stinger-gel",
    ],
    alternativeProductIds: [
      "prod-sis-go-isotonic-gel",
      "prod-honey-stinger-gel",
      "prod-gu-roctane-gel",
      "prod-clif-bloks",
    ],
    ...pub,
  },
  {
    id: "prod-gu-roctane-gel",
    slug: "gu-roctane-gel",
    brandId: "brand-gu",
    familyId: "fam-gu-roctane",
    generation: "Roctane",
    name: "Roctane Energy Gel",
    fullName: "GU Roctane Energy Gel",
    shortDescription:
      "GU’s denser electrolyte-leaning gel line (~100 kcal / ~21–22g carbs per label) with higher sodium than classic GU and optional caffeine flavours — designed for longer efforts when you want familiar GU packaging with a more race-oriented electrolyte profile.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-ultra",
      "uc-trail-training",
      "uc-easy-carry-fuel",
      "uc-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "32g packet",
      calories: 100,
      carbsPerServing: 21,
      sugars: null,
      sodium: 125,
      caffeine: true,
      caffeineAmount: 35,
      protein: 0,
      fluidRequired: "Water recommended",
      form: "gel",
      flavour: "Multiple (caffeine amount varies by flavour)",
      packSize: "Box of 24",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Higher sodium than classic GU for longer warm efforts",
      "Caffeine flavours available for late-race preference",
      "Same easy-carry packet format as standard GU",
    ],
    weaknesses: [
      "Carb dose still sits around ~21–22g — not a high-carb race gel",
      "Caffeine content varies by flavour — verify the SKU",
      "Pricier than classic GU Energy Gel",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-gu-roctane-gel",
      "GU Roctane Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-gu-energy-gel",
      "prod-maurten-gel-100-caf",
      "prod-saltstick-caps",
      "prod-gu-chews",
    ],
    alternativeProductIds: [
      "prod-gu-energy-gel",
      "prod-neversecond-c30-gel",
      "prod-honey-stinger-gel",
      "prod-maurten-gel-100-caf",
    ],
    ...pub,
  },
  {
    id: "prod-precision-pf30-gel",
    slug: "precision-pf30-gel",
    brandId: "brand-precision-fuel",
    familyId: "fam-precision-pf30",
    generation: "PF 30",
    name: "PF 30 Gel",
    fullName: "Precision Fuel & Hydration PF 30 Gel",
    shortDescription:
      "Mild, low-stick gel delivering 30g carbs per serving — designed for structured high-carb race plans when you want modular 30g units that are easy to count and carry without strong flavour fatigue.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: [
      "uc-marathon",
      "uc-half",
      "uc-high-carb-fueling",
      "uc-long-runs",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "1 gel",
      calories: 120,
      carbsPerServing: 30,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Low — marketed as less sticky / easier without immediate wash-down",
      form: "gel",
      flavour: "Original (mild / neutral)",
      packSize: "Boxes of 15 / 30 / 60",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "Clean 30g carb unit simplifies race fueling math",
      "Mild flavour and low-stick texture suit long efforts",
      "Pairs cleanly with PF 30 Drink Mix and PH electrolytes",
    ],
    weaknesses: [
      "Less flavour excitement if you prefer bold fruit gels",
      "Not a high-sodium gel — electrolytes come from PH line",
      "Availability can be narrower than GU / SiS in some shops",
    ],
    recommendationScore: 90,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-precision-pf30-gel",
      "Precision PF 30 Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-precision-pf30-drink",
      "prod-precision-ph1500",
      "prod-neversecond-c30-gel",
      "prod-maurten-gel-100",
    ],
    alternativeProductIds: [
      "prod-neversecond-c30-gel",
      "prod-maurten-gel-100",
      "prod-sis-beta-fuel-gel",
      "prod-maurten-gel-160",
    ],
    ...pub,
  },
  {
    id: "prod-neversecond-c30-gel",
    slug: "neversecond-c30-gel",
    brandId: "brand-neversecond",
    familyId: "fam-neversecond-c30",
    generation: "C30",
    name: "C30 Gel",
    fullName: "Neversecond C30 Energy Gel",
    shortDescription:
      "Modular 30g-carb gel (~200mg sodium per label) designed as part of the Neversecond C-series — pick it when you want gel + drink mix units that add up cleanly for high-carb race fueling.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: [
      "uc-marathon",
      "uc-high-carb-fueling",
      "uc-long-runs",
      "uc-half",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "1 gel",
      calories: 120,
      carbsPerServing: 30,
      sugars: null,
      sodium: 200,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water available recommended",
      form: "gel",
      flavour: "Multiple / unflavoured options",
      packSize: "Box packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "30g carb + meaningful sodium in one race packet",
      "Matches C30 Drink Mix for modular bottle + gel plans",
      "Built for structured endurance carb targets",
    ],
    weaknesses: [
      "Less ubiquitous on race tables than GU / SiS",
      "Premium positioning vs value supermarket gels",
      "Flavour range narrower than classic GU",
    ],
    recommendationScore: 89,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-neversecond-c30-gel",
      "Neversecond C30 Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-neversecond-c30-drink",
      "prod-precision-pf30-gel",
      "prod-sis-beta-fuel-gel",
      "prod-maurten-gel-100",
    ],
    alternativeProductIds: [
      "prod-precision-pf30-gel",
      "prod-sis-beta-fuel-gel",
      "prod-maurten-gel-160",
      "prod-gu-roctane-gel",
    ],
    ...pub,
  },
  {
    id: "prod-spring-awesome-sauce",
    slug: "spring-energy-awesome-sauce",
    brandId: "brand-spring-energy",
    familyId: "fam-spring-energy-gels",
    generation: "Awesome Sauce",
    name: "Awesome Sauce",
    fullName: "Spring Energy Awesome Sauce",
    shortDescription:
      "Real-food texture gel pouch aimed at ultra and long trail days — choose it when you want a thicker, food-like mouthfeel versus syrup gels; treat carb math conservatively and confirm the current label for your batch.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-ultra",
      "uc-trail-training",
      "uc-long-runs",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "~54g pouch",
      calories: null,
      carbsPerServing: null,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water helpful with thicker real-food texture",
      form: "gel",
      flavour: "Awesome Sauce (fruit / real-food profile)",
      packSize: "Single pouches / multi-packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Real-food texture breaks up syrup-gel monotony on ultras",
      "Pouch format still vest-pocket friendly",
      "Popular among trail runners who prefer food-like fuel",
    ],
    weaknesses: [
      "Label carb precision has been disputed — verify current packaging",
      "Thicker texture can feel harder late in hot races",
      "Higher price and less modular carb counting than PF30 / C30",
    ],
    recommendationScore: 74,
    valueScore: 62,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-spring-awesome-sauce",
      "Spring Energy Awesome Sauce — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-huma-gel-original",
      "prod-naak-ultra-energy-bar",
      "prod-veloforte-chews",
      "prod-honey-stinger-gel",
    ],
    alternativeProductIds: [
      "prod-huma-gel-original",
      "prod-honey-stinger-gel",
      "prod-clif-bloks",
      "prod-naak-ultra-energy-bar",
    ],
    ...pub,
  },
  {
    id: "prod-huma-gel-original",
    slug: "huma-gel-original",
    brandId: "brand-huma",
    familyId: "fam-huma-gel",
    generation: "Original",
    name: "Original Gel",
    fullName: "Hüma Original Energy Gel",
    shortDescription:
      "Chia-based real-food gel delivering ~24–25g carbs (~100 kcal) per pouch — designed for runners who want fruit-forward texture and sea-salt sodium without classic maltodextrin syrup feel.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-long-runs",
      "uc-trail-training",
      "uc-ultra",
      "uc-half",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "1 pouch",
      calories: 100,
      carbsPerServing: 25,
      sugars: null,
      sodium: 110,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water helpful",
      form: "gel",
      flavour: "Multiple fruit flavours",
      packSize: "Multi-packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Real-food / chia texture alternative to syrup gels",
      "~25g carbs with noticeable sodium from sea salt",
      "Good trail long-run variety option",
    ],
    weaknesses: [
      "Texture and seeds are polarising late in races",
      "Carb dose below dedicated 30–40g race gels",
      "Pricier than mainstream GU / SiS",
    ],
    recommendationScore: 81,
    valueScore: 70,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-huma-gel-original",
      "Hüma Original Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-spring-awesome-sauce",
      "prod-honey-stinger-gel",
      "prod-gu-energy-gel",
      "prod-veloforte-chews",
    ],
    alternativeProductIds: [
      "prod-honey-stinger-gel",
      "prod-spring-awesome-sauce",
      "prod-gu-energy-gel",
      "prod-clif-bloks",
    ],
    ...pub,
  },
  {
    id: "prod-honey-stinger-gel",
    slug: "honey-stinger-organic-energy-gel",
    brandId: "brand-honey-stinger",
    familyId: "fam-honey-stinger-gel",
    generation: "Organic Energy Gel",
    name: "Organic Energy Gel",
    fullName: "Honey Stinger Organic Energy Gel",
    shortDescription:
      "Honey-based organic energy gel with ~24g carbs (~90 kcal) per packet — designed for runners who prefer honey sweetness and an easy-carry classic gel format for training and racing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: [
      "uc-short-training",
      "uc-long-runs",
      "uc-half",
      "uc-easy-carry-fuel",
      "uc-trail-training",
      "uc-non-caffeinated-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "gel",
      servingSize: "31g packet",
      calories: 90,
      carbsPerServing: 24,
      sugars: null,
      sodium: 45,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water recommended",
      form: "gel",
      flavour: "Multiple (Gold / fruit)",
      packSize: "Box of 24",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Honey-forward taste many runners find easier than maltodextrin syrup",
      "Organic positioning and wide US retail availability",
      "Simple training gel for shorter and mid-distance efforts",
    ],
    weaknesses: [
      "Carb density below modern 30–40g race gels",
      "Honey sweetness can fatigue on very long races",
      "Not dual-tagged as a high-carb race-fuel system",
    ],
    recommendationScore: 76,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-honey-stinger-gel",
      "Honey Stinger Organic Energy Gel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-gu-energy-gel",
      "prod-huma-gel-original",
      "prod-clif-bloks",
      "prod-sis-go-isotonic-gel",
    ],
    alternativeProductIds: [
      "prod-gu-energy-gel",
      "prod-sis-go-isotonic-gel",
      "prod-huma-gel-original",
      "prod-clif-bloks",
    ],
    ...pub,
  },

  // ─── Energy chews ────────────────────────────────────────────────────────
  {
    id: "prod-clif-bloks",
    slug: "clif-bloks-energy-chews",
    brandId: "brand-clif",
    familyId: "fam-clif-bloks",
    generation: "Bloks",
    name: "Bloks Energy Chews",
    fullName: "CLIF BLOKS Energy Chews",
    shortDescription:
      "Portionable energy chews with ~48g carbs (~200 kcal) per full packet — designed when you want to nibble carbs over time instead of taking a full gel in one go, with easy belt/vest carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-chews"],
    useCaseIds: [
      "uc-long-runs",
      "uc-half",
      "uc-marathon",
      "uc-trail-training",
      "uc-easy-carry-fuel",
      "uc-short-training",
      "uc-beginners",
    ],
    specifications: {
      type: "chew",
      servingSize: "1 packet (6 bloks)",
      calories: 200,
      carbsPerServing: 48,
      sugars: null,
      sodium: 50,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water recommended while chewing",
      form: "chew",
      flavour: "Multiple (some SKUs caffeinated)",
      packSize: "18-count boxes common",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Easy to split — eat 2–3 bloks at a time on the move",
      "High carb per full packet for the chew format",
      "Widely available and beginner-friendly texture",
    ],
    weaknesses: [
      "Chewing while breathing hard is harder than gels for some",
      "Sticky in heat; can harden in cold",
      "Caffeine varies by flavour — check the packet",
    ],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-clif-bloks",
      "CLIF BLOKS — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-gu-chews",
      "prod-skratch-chews",
      "prod-clif-bar-original",
      "prod-gu-energy-gel",
    ],
    alternativeProductIds: [
      "prod-gu-chews",
      "prod-skratch-chews",
      "prod-veloforte-chews",
      "prod-honey-stinger-gel",
    ],
    ...pub,
  },
  {
    id: "prod-gu-chews",
    slug: "gu-energy-chews",
    brandId: "brand-gu",
    familyId: "fam-gu-chews",
    generation: "Energy Chews",
    name: "Energy Chews",
    fullName: "GU Energy Chews",
    shortDescription:
      "Soft energy chews for runners who want a gel-brand alternative texture — designed for portionable mid-run carbs with familiar GU flavours and easy pocket carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-chews"],
    useCaseIds: [
      "uc-long-runs",
      "uc-half",
      "uc-short-training",
      "uc-easy-carry-fuel",
      "uc-trail-training",
      "uc-beginners",
    ],
    specifications: {
      type: "chew",
      servingSize: "4 chews (typical serving)",
      calories: 80,
      carbsPerServing: 20,
      sugars: null,
      sodium: 40,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water recommended while chewing",
      form: "chew",
      flavour: "Multiple",
      packSize: "Packet / multi-packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Soft chew texture pairs well with GU gel rotation",
      "Easy to portion across a long run",
      "Broad flavour availability",
    ],
    weaknesses: [
      "Lower carbs per labeled serving than a full Bloks packet",
      "Still requires chewing under race breathing",
      "Not a high-carb race-fuel primary for 90g+/hr plans",
    ],
    recommendationScore: 77,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-gu-chews",
      "GU Energy Chews — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-gu-energy-gel",
      "prod-clif-bloks",
      "prod-gu-roctane-gel",
      "prod-skratch-chews",
    ],
    alternativeProductIds: [
      "prod-clif-bloks",
      "prod-skratch-chews",
      "prod-veloforte-chews",
      "prod-gu-energy-gel",
    ],
    ...pub,
  },
  {
    id: "prod-skratch-chews",
    slug: "skratch-sport-energy-chews",
    brandId: "brand-skratch",
    familyId: "fam-skratch-chews",
    generation: "Sport Energy Chews",
    name: "Sport Energy Chews",
    fullName: "Skratch Labs Sport Energy Chews",
    shortDescription:
      "Fruit-forward energy chews designed to match Skratch’s real-food tasting drink mix line — pick them when you want chewable carbs with a lighter, less candy-syrup profile on long runs and trail days.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-chews"],
    useCaseIds: [
      "uc-long-runs",
      "uc-trail-training",
      "uc-ultra",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "chew",
      servingSize: "1 pouch",
      calories: 160,
      carbsPerServing: 36,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water recommended while chewing",
      form: "chew",
      flavour: "Fruit flavours (e.g. fruit drops / sport chews)",
      packSize: "Single pouches / boxes",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Pairs naturally with Skratch Sport Hydration bottles",
      "Less candy-like profile than many chews",
      "Portionable for long trail days",
    ],
    weaknesses: [
      "Chew format still slower than gels under hard race effort",
      "Premium pricing vs Bloks",
      "Confirm current pouch carb label — line naming varies by market",
    ],
    recommendationScore: 80,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-skratch-chews",
      "Skratch Sport Energy Chews — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-skratch-sport-hydration",
      "prod-clif-bloks",
      "prod-veloforte-chews",
      "prod-gu-chews",
    ],
    alternativeProductIds: [
      "prod-clif-bloks",
      "prod-veloforte-chews",
      "prod-gu-chews",
      "prod-huma-gel-original",
    ],
    ...pub,
  },
  {
    id: "prod-veloforte-chews",
    slug: "veloforte-energy-chews",
    brandId: "brand-veloforte",
    familyId: "fam-veloforte-chews",
    generation: "Energy Chews",
    name: "Energy Chews",
    fullName: "Veloforte Energy Chews",
    shortDescription:
      "Natural-leaning energy chews/bites for runners who want real-fruit flavour and a non-syrup texture — designed for long training and ultra variety when classic maltodextrin gels fatigue.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-chews"],
    useCaseIds: [
      "uc-long-runs",
      "uc-trail-training",
      "uc-ultra",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "chew",
      servingSize: "1 serving / pouch",
      calories: null,
      carbsPerServing: null,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended while chewing",
      form: "chew",
      flavour: "Natural fruit profiles",
      packSize: "Multi-packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Natural fruit profile breaks gel monotony",
      "Handy chew format for trail pacing",
      "Pairs with Veloforte bars for ultra food variety",
    ],
    weaknesses: [
      "Exact label carbs vary by SKU — confirm packaging",
      "UK-centric availability vs GU / Clif in some regions",
      "Chewing under race intensity is not for everyone",
    ],
    recommendationScore: 75,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-veloforte-chews",
      "Veloforte Energy Chews — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-skratch-chews",
      "prod-clif-bloks",
      "prod-spring-awesome-sauce",
      "prod-naak-ultra-energy-bar",
    ],
    alternativeProductIds: [
      "prod-clif-bloks",
      "prod-skratch-chews",
      "prod-gu-chews",
      "prod-huma-gel-original",
    ],
    ...pub,
  },
  {
    id: "prod-saltstick-fastchews",
    slug: "saltstick-fastchews",
    brandId: "brand-saltstick",
    familyId: "fam-saltstick-fastchews",
    generation: "Fastchews",
    name: "Fastchews",
    fullName: "SaltStick Fastchews",
    shortDescription:
      "Electrolyte chew tablets for bottle-free sodium top-ups — designed as a carry-friendly electrolyte format, not a primary carbohydrate fuel; pair with gels or drink mix for carbs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-chews", "sub-electrolyte-tablets"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-ultra",
      "uc-trail-training",
      "uc-easy-carry-fuel",
      "uc-half",
    ],
    specifications: {
      type: "chew",
      servingSize: "2 Fastchews (typical)",
      calories: null,
      carbsPerServing: null,
      sugars: null,
      sodium: 90,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Water available recommended",
      form: "chew",
      flavour: "Multiple (e.g. orange, lemon-lime)",
      packSize: "Roll / bottle packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Tiny carry for electrolyte top-ups without mixing a bottle",
      "Chew format works mid-race without capsules",
      "Useful alongside separate carb gels or drink mix",
    ],
    weaknesses: [
      "Not a carbohydrate fuel — do not count as race gels",
      "Sodium dose is modest vs PH 1500 / SaltStick Caps plans",
      "Flavour chalkiness is polarising",
    ],
    recommendationScore: 78,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-saltstick-fastchews",
      "SaltStick Fastchews — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-saltstick-caps",
      "prod-nuun-sport",
      "prod-precision-ph1500",
      "prod-gu-energy-gel",
    ],
    alternativeProductIds: [
      "prod-saltstick-caps",
      "prod-nuun-sport",
      "prod-high5-zero",
      "prod-precision-ph1500",
    ],
    ...pub,
  },

  // ─── Energy bars ─────────────────────────────────────────────────────────
  {
    id: "prod-clif-bar-original",
    slug: "clif-bar-original",
    brandId: "brand-clif",
    familyId: "fam-clif-bar",
    generation: "Original",
    name: "Clif Bar",
    fullName: "CLIF Bar Original",
    shortDescription:
      "Dense energy bar (~250 kcal / ~45g carbs / ~10g protein typical Chocolate Chip label) — designed for lower-intensity long runs, ultras, and aid-station style fueling when a gel feels too thin and you can chew.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-bars"],
    useCaseIds: [
      "uc-long-runs",
      "uc-ultra",
      "uc-trail-training",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "bar",
      servingSize: "68g bar",
      calories: 250,
      carbsPerServing: 45,
      sugars: null,
      sodium: 150,
      caffeine: false,
      caffeineAmount: null,
      protein: 10,
      fluidRequired: "Water recommended while eating",
      form: "bar",
      flavour: "Multiple (Chocolate Chip classic)",
      packSize: "12-count boxes common",
      dietaryLabels: null,
      allergens: "Contains soy",
    },
    strengths: [
      "Substantial calories for long, slower efforts",
      "Easy to find almost anywhere",
      "More satisfying texture than gels on ultra days",
    ],
    weaknesses: [
      "Hard to chew at marathon race pace",
      "Dense and filling if gut is already loaded",
      "Contains soy — check allergens if relevant",
    ],
    recommendationScore: 79,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-clif-bar-original",
      "CLIF Bar Original — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-clif-bloks",
      "prod-naak-ultra-energy-bar",
      "prod-powerbar-energize",
      "prod-veloforte-chews",
    ],
    alternativeProductIds: [
      "prod-powerbar-energize",
      "prod-naak-ultra-energy-bar",
      "prod-clif-bloks",
      "prod-spring-awesome-sauce",
    ],
    ...pub,
  },
  {
    id: "prod-naak-ultra-energy-bar",
    slug: "naak-ultra-energy-bar",
    brandId: "brand-naak",
    familyId: "fam-naak-ultra",
    generation: "Ultra Energy Bar",
    name: "Ultra Energy Bar",
    fullName: "Näak Ultra Energy Bar",
    shortDescription:
      "Ultra-oriented energy bar with carbs plus meaningful protein — designed for long trail and ultra efforts when you want a denser chewable fuel than gels and a more race-focused bar than a grocery snack bar.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-bars"],
    useCaseIds: [
      "uc-ultra",
      "uc-trail-training",
      "uc-long-runs",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "bar",
      servingSize: "1 bar",
      calories: null,
      carbsPerServing: 28,
      sugars: null,
      sodium: 180,
      caffeine: false,
      caffeineAmount: null,
      protein: 7,
      fluidRequired: "Water recommended while eating",
      form: "bar",
      flavour: "Multiple ultra flavours",
      packSize: "Multi-packs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Built for ultra / trail food variety beyond gels",
      "Protein + carbs for longer slower sections",
      "More race-oriented positioning than grocery bars",
    ],
    weaknesses: [
      "Still requires chewing — not ideal at road marathon pace",
      "Availability narrower than Clif in many shops",
      "Exact calories vary by flavour — confirm label",
    ],
    recommendationScore: 82,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-naak-ultra-energy-bar",
      "Näak Ultra Energy Bar — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-clif-bar-original",
      "prod-spring-awesome-sauce",
      "prod-powerbar-energize",
      "prod-veloforte-chews",
    ],
    alternativeProductIds: [
      "prod-clif-bar-original",
      "prod-powerbar-energize",
      "prod-clif-bloks",
      "prod-spring-awesome-sauce",
    ],
    ...pub,
  },
  {
    id: "prod-powerbar-energize",
    slug: "powerbar-energize",
    brandId: "brand-powerbar",
    familyId: "fam-powerbar-energize",
    generation: "Energize",
    name: "Energize",
    fullName: "PowerBar Energize",
    shortDescription:
      "Classic endurance energy bar (~39–45g carbs depending on flavour) — designed for long training and racing when you want a chewable carb bar with broad European race-table familiarity.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-bars"],
    useCaseIds: [
      "uc-long-runs",
      "uc-half",
      "uc-marathon",
      "uc-ultra",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "bar",
      servingSize: "1 bar",
      calories: null,
      carbsPerServing: 39,
      sugars: null,
      sodium: 190,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended while eating",
      form: "bar",
      flavour: "Multiple",
      packSize: "Boxes / singles",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Familiar race-fuel bar format across many European events",
      "Meaningful carbs with some sodium",
      "Good long-run alternative to endless gels",
    ],
    weaknesses: [
      "Chewing at high intensity remains the limiter",
      "Texture can feel dry without fluid",
      "Less ‘real food’ positioning than Näak / Veloforte",
    ],
    recommendationScore: 80,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-powerbar-energize",
      "PowerBar Energize — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-clif-bar-original",
      "prod-naak-ultra-energy-bar",
      "prod-veloforte-chews",
      "prod-sis-go-isotonic-gel",
    ],
    alternativeProductIds: [
      "prod-clif-bar-original",
      "prod-naak-ultra-energy-bar",
      "prod-clif-bloks",
      "prod-spring-awesome-sauce",
    ],
    ...pub,
  },
  // ─── Carb drink mixes / race fuel ────────────────────────────────────────
  {
    id: "prod-maurten-drink-mix-160",
    slug: "maurten-drink-mix-160",
    brandId: "brand-maurten",
    familyId: "fam-maurten-drink-mix",
    generation: "160",
    name: "Drink Mix 160",
    fullName: "Maurten Drink Mix 160",
    shortDescription:
      "Hydrogel drink mix delivering 40g carbs (~160 kcal) in 500ml — designed for bottle-based fueling on long runs and races when you want mild taste and structured carb delivery without caffeine.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-sports-drinks"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-drink-based-fueling",
      "uc-high-carb-fueling",
      "uc-half",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "carb-mix",
      servingSize: "1 sachet in 500ml water",
      calories: 160,
      carbsPerServing: 40,
      sugars: null,
      sodium: 160,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "500ml water per sachet",
      form: "powder",
      flavour: "Mild / neutral",
      packSize: "Box of 18",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "40g carbs per bottle simplifies mid-effort fueling",
      "Mild flavour reduces sweetness fatigue",
      "Pairs with Gel 100/160 for mixed gel + drink plans",
    ],
    weaknesses: [
      "Requires accurate 500ml mixing and shaking",
      "Sodium is modest vs Tailwind / Skratch sweat plans",
      "Premium price per serving",
    ],
    recommendationScore: 88,
    valueScore: 66,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-maurten-drink-mix-160",
      "Maurten Drink Mix 160 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-drink-mix-320",
      "prod-maurten-gel-100",
      "prod-sis-beta-fuel-drink",
      "prod-precision-pf30-drink",
    ],
    alternativeProductIds: [
      "prod-sis-beta-fuel-drink",
      "prod-tailwind-endurance",
      "prod-precision-pf30-drink",
      "prod-neversecond-c30-drink",
    ],
    ...pub,
  },
  {
    id: "prod-maurten-drink-mix-320",
    slug: "maurten-drink-mix-320",
    brandId: "brand-maurten",
    familyId: "fam-maurten-drink-mix",
    generation: "320",
    name: "Drink Mix 320",
    fullName: "Maurten Drink Mix 320",
    shortDescription:
      "High-carb race drink mix with 80g carbs (~320 kcal) in 500ml — designed for bottle-first high-carb fueling when one flask is meant to carry a large share of hourly carbs.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-race-fuel", "sub-sports-drinks"],
    useCaseIds: [
      "uc-marathon",
      "uc-high-carb-fueling",
      "uc-drink-based-fueling",
      "uc-ultra",
      "uc-long-runs",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "race-fuel",
      servingSize: "1 sachet in 500ml water",
      calories: 320,
      carbsPerServing: 80,
      sugars: null,
      sodium: 200,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "500ml water per sachet",
      form: "powder",
      flavour: "Mild / neutral",
      packSize: "Box of 14",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "80g carbs per bottle supports aggressive race carb targets",
      "Hydrogel drink format many athletes prefer for dense bottles",
      "Clear step up from Drink Mix 160 for race intensity",
    ],
    weaknesses: [
      "Hypertonic density needs practiced gut tolerance",
      "Still not a high-sodium all-in-one like Tailwind",
      "Expensive per serving",
    ],
    recommendationScore: 92,
    valueScore: 64,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-maurten-drink-mix-320",
      "Maurten Drink Mix 320 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-drink-mix-160",
      "prod-sis-beta-fuel-drink",
      "prod-styrkr-mix90",
      "prod-maurten-gel-160",
    ],
    alternativeProductIds: [
      "prod-sis-beta-fuel-drink",
      "prod-styrkr-mix90",
      "prod-tailwind-endurance",
      "prod-precision-pf30-drink",
    ],
    ...pub,
  },
  {
    id: "prod-sis-beta-fuel-drink",
    slug: "sis-beta-fuel-drink",
    brandId: "brand-sis",
    familyId: "fam-sis-beta-fuel",
    generation: "Beta Fuel",
    name: "Beta Fuel Drink",
    fullName: "Science in Sport Beta Fuel Energy Drink Mix",
    shortDescription:
      "Dual-source high-carb powder (~80g carbs per labeled serving) — designed for bottle-based race fueling when you want SiS Beta Fuel continuity between gel and drink formats.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-race-fuel", "sub-sports-drinks"],
    useCaseIds: [
      "uc-marathon",
      "uc-high-carb-fueling",
      "uc-drink-based-fueling",
      "uc-long-runs",
      "uc-ultra",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "race-fuel",
      servingSize: "1 serving in ~500–750ml water",
      calories: null,
      carbsPerServing: 80,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Mix to bottle volume per label",
      form: "powder",
      flavour: "Orange / Lemon (typical)",
      packSize: "Sachets / tubs",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "High carb dose aligns with Beta Fuel gel race plans",
      "Strong retail availability vs niche powders",
      "Dual-source format for structured endurance fueling",
    ],
    weaknesses: [
      "Sweetness can fatigue vs Maurten’s milder profile",
      "Confirm exact sodium on your regional label",
      "Needs accurate mixing for intended concentration",
    ],
    recommendationScore: 87,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-sis-beta-fuel-drink",
      "SiS Beta Fuel Drink — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-sis-beta-fuel-gel",
      "prod-maurten-drink-mix-320",
      "prod-styrkr-mix90",
      "prod-tailwind-endurance",
    ],
    alternativeProductIds: [
      "prod-maurten-drink-mix-320",
      "prod-styrkr-mix90",
      "prod-precision-pf30-drink",
      "prod-neversecond-c30-drink",
    ],
    ...pub,
  },
  {
    id: "prod-tailwind-endurance",
    slug: "tailwind-endurance-fuel",
    brandId: "brand-tailwind",
    familyId: "fam-tailwind-endurance",
    generation: "Endurance Fuel",
    name: "Endurance Fuel",
    fullName: "Tailwind Endurance Fuel",
    shortDescription:
      "All-in-one endurance drink mix with ~25g carbs and ~300mg sodium per scoop — designed for drink-based fueling when you want calories and electrolytes in the same bottle without separate gels every mile.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-sports-drinks"],
    useCaseIds: [
      "uc-long-runs",
      "uc-ultra",
      "uc-trail-training",
      "uc-drink-based-fueling",
      "uc-marathon",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "carb-mix",
      servingSize: "1 scoop",
      calories: 100,
      carbsPerServing: 25,
      sugars: 25,
      sodium: 310,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Mix to taste / bottle volume (often 500–750ml)",
      form: "powder",
      flavour: "Multiple (Naked / fruit)",
      packSize: "Stick packs / tubs",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Carbs + higher sodium in one scoop simplifies bottle plans",
      "Scalable — 1–2 scoops depending on effort length",
      "Strong value for all-day trail and ultra training",
    ],
    weaknesses: [
      "Single scoop (~25g carbs) is not a Maurten 320-style high-carb hit",
      "Sweetness can build across many bottles",
      "Caffeinated SKUs exist — verify if you need non-caf",
    ],
    recommendationScore: 86,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-tailwind-endurance",
      "Tailwind Endurance Fuel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-skratch-sport-hydration",
      "prod-maurten-drink-mix-160",
      "prod-neversecond-c30-drink",
      "prod-precision-pf30-drink",
    ],
    alternativeProductIds: [
      "prod-skratch-sport-hydration",
      "prod-maurten-drink-mix-160",
      "prod-sis-beta-fuel-drink",
      "prod-neversecond-c30-drink",
    ],
    ...pub,
  },
  {
    id: "prod-precision-pf30-drink",
    slug: "precision-pf30-drink-mix",
    brandId: "brand-precision-fuel",
    familyId: "fam-precision-pf30",
    generation: "PF 30",
    name: "PF 30 Drink Mix",
    fullName: "Precision Fuel & Hydration PF 30 Drink Mix",
    shortDescription:
      "Modular 30g-carb drink mix matching PF 30 Gel units — designed for bottle + gel race plans when you want clean carb math and mild flavour across Precision’s fuel system.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-sports-drinks"],
    useCaseIds: [
      "uc-marathon",
      "uc-high-carb-fueling",
      "uc-drink-based-fueling",
      "uc-long-runs",
      "uc-half",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "carb-mix",
      servingSize: "1 serving (30g carbs)",
      calories: 120,
      carbsPerServing: 30,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Mix to bottle volume per label",
      form: "powder",
      flavour: "Mild / neutral",
      packSize: "Sachets / multi-packs",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "Same 30g unit as PF 30 Gel for modular race plans",
      "Mild flavour suits long efforts",
      "Pairs with PH 1500 when you need separate sodium",
    ],
    weaknesses: [
      "Not an all-in-one high-sodium mix like Tailwind",
      "Less ‘one bottle = 80g carbs’ density than Mix 320 / Beta Fuel drink",
      "Requires combining servings for higher hourly targets",
    ],
    recommendationScore: 87,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-precision-pf30-drink",
      "Precision PF 30 Drink Mix — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-precision-pf30-gel",
      "prod-precision-ph1500",
      "prod-neversecond-c30-drink",
      "prod-maurten-drink-mix-160",
    ],
    alternativeProductIds: [
      "prod-neversecond-c30-drink",
      "prod-maurten-drink-mix-160",
      "prod-tailwind-endurance",
      "prod-sis-beta-fuel-drink",
    ],
    ...pub,
  },
  {
    id: "prod-neversecond-c30-drink",
    slug: "neversecond-c30-sports-drink",
    brandId: "brand-neversecond",
    familyId: "fam-neversecond-c30",
    generation: "C30",
    name: "C30 Sports Drink",
    fullName: "Neversecond C30 Sports Drink",
    shortDescription:
      "Modular drink mix with 30g carbs and 200mg sodium per scoop — designed for bottle fueling you can scale (1–3 scoops) to match training and race carb targets alongside C30 gels.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-sports-drinks"],
    useCaseIds: [
      "uc-marathon",
      "uc-drink-based-fueling",
      "uc-high-carb-fueling",
      "uc-long-runs",
      "uc-half",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "sports-drink",
      servingSize: "32g scoop",
      calories: 120,
      carbsPerServing: 30,
      sugars: 12,
      sodium: 200,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Typically 500–750ml per 1–3 scoops",
      form: "powder",
      flavour: "Unflavoured / lightly flavoured",
      packSize: "640g tub / sachets",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "30g carb + 200mg sodium per scoop is easy to scale",
      "Neutral taste works with gels in the same hour",
      "Matches C30 Gel for system-style fueling",
    ],
    weaknesses: [
      "Need multiple scoops to match 80–90g bottle targets",
      "Less ‘set and forget’ than single-serve Maurten sachets",
      "Narrower retail footprint than Tailwind / SiS",
    ],
    recommendationScore: 88,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-neversecond-c30-drink",
      "Neversecond C30 Sports Drink — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-neversecond-c30-gel",
      "prod-precision-pf30-drink",
      "prod-tailwind-endurance",
      "prod-maurten-drink-mix-160",
    ],
    alternativeProductIds: [
      "prod-precision-pf30-drink",
      "prod-tailwind-endurance",
      "prod-sis-beta-fuel-drink",
      "prod-maurten-drink-mix-160",
    ],
    ...pub,
  },
  {
    id: "prod-styrkr-mix90",
    slug: "styrkr-mix90",
    brandId: "brand-styrkr",
    familyId: "fam-styrkr-mix",
    generation: "MIX90",
    name: "MIX90",
    fullName: "STYRKR MIX90 Dual-Carb Drink Mix",
    shortDescription:
      "High-carb dual-source drink mix delivering 90g carbs per serving in ~500ml — designed for advanced high-carb bottle fueling when you want a single dense mix for long races and key sessions.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-race-fuel"],
    useCaseIds: [
      "uc-high-carb-fueling",
      "uc-marathon",
      "uc-drink-based-fueling",
      "uc-ultra",
      "uc-long-runs",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "race-fuel",
      servingSize: "1 serving in 500ml water",
      calories: null,
      carbsPerServing: 90,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "500ml water per serving",
      form: "powder",
      flavour: "Dual-carb mix flavours",
      packSize: "12-pack sachets",
      dietaryLabels: "vegan",
      allergens: null,
    },
    strengths: [
      "90g carbs per bottle targets high-carb race plans in one mix",
      "Dual-carb 1:0.8 maltodextrin/fructose format",
      "Strong value positioning vs Maurten 320",
    ],
    weaknesses: [
      "Dense mix needs practiced tolerance before race day",
      "Confirm sodium on current label if sweat losses are high",
      "Caffeinated MIX90 variant exists — pick the non-caf SKU deliberately",
    ],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-styrkr-mix90",
      "STYRKR MIX90 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-maurten-drink-mix-320",
      "prod-sis-beta-fuel-drink",
      "prod-precision-pf30-drink",
      "prod-neversecond-c30-drink",
    ],
    alternativeProductIds: [
      "prod-maurten-drink-mix-320",
      "prod-sis-beta-fuel-drink",
      "prod-tailwind-endurance",
      "prod-maurten-gel-160",
    ],
    ...pub,
  },

  // ─── Electrolyte mixes / tablets ─────────────────────────────────────────
  {
    id: "prod-skratch-sport-hydration",
    slug: "skratch-sport-hydration-mix",
    brandId: "brand-skratch",
    familyId: "fam-skratch-hydration",
    generation: "Sport Hydration",
    name: "Sport Hydration Drink Mix",
    fullName: "Skratch Labs Sport Hydration Drink Mix",
    shortDescription:
      "Lower-carb electrolyte drink mix (~80 kcal / ~20–21g carbs / ~380–400mg sodium per serving) — designed for everyday long runs when you want light carbs plus meaningful sodium rather than a dense race-fuel bottle.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-electrolyte-mixes", "sub-sports-drinks"],
    useCaseIds: [
      "uc-long-runs",
      "uc-trail-training",
      "uc-drink-based-fueling",
      "uc-half",
      "uc-short-training",
      "uc-non-caffeinated-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "electrolyte-mix",
      servingSize: "1 serving (~22g)",
      calories: 80,
      carbsPerServing: 20,
      sugars: 18,
      sodium: 400,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Mix to bottle volume per label",
      form: "powder",
      flavour: "Real-fruit flavours",
      packSize: "Stick packs / pouches / bags",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Meaningful sodium with light carbs for training bottles",
      "Real-fruit taste profile many runners prefer",
      "Better everyday hydration mix than dense race fuels",
    ],
    weaknesses: [
      "Not enough carbs alone for high-carb marathon plans",
      "Premium vs tablet electrolytes",
      "Need gels/chews alongside for bigger carb targets",
    ],
    recommendationScore: 85,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-skratch-sport-hydration",
      "Skratch Sport Hydration — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-skratch-chews",
      "prod-tailwind-endurance",
      "prod-nuun-sport",
      "prod-precision-ph1500",
    ],
    alternativeProductIds: [
      "prod-tailwind-endurance",
      "prod-nuun-sport",
      "prod-high5-zero",
      "prod-precision-ph1500",
    ],
    ...pub,
  },
  {
    id: "prod-precision-ph1500",
    slug: "precision-ph1500",
    brandId: "brand-precision-fuel",
    familyId: "fam-precision-ph",
    generation: "PH 1500",
    name: "PH 1500",
    fullName: "Precision Fuel & Hydration PH 1500",
    shortDescription:
      "High-sodium electrolyte drink mix (~1500mg sodium per liter when mixed as directed) with minimal carbs — designed when you want electrolytes separate from carb gels/drink mixes for salty-sweat or hot long efforts.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-electrolyte-mixes"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-ultra",
      "uc-drink-based-fueling",
      "uc-trail-training",
      "uc-half",
    ],
    specifications: {
      type: "electrolyte-mix",
      servingSize: "1 serving mixed to 1L (typical)",
      calories: null,
      carbsPerServing: 1.5,
      sugars: null,
      sodium: 1500,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Mix to labeled volume (often 500ml–1L options)",
      form: "powder",
      flavour: "Mild electrolyte flavours",
      packSize: "Sachets",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "High sodium dose for athletes who want electrolytes separate from carbs",
      "Minimal carbs — won’t compete with PF 30 / gel math",
      "Pairs cleanly with Precision carb products",
    ],
    weaknesses: [
      "Not a carbohydrate fuel",
      "1500mg/L strength is too much for some lighter sweat profiles",
      "Needs bottle mixing vs grab-and-go tablets",
    ],
    recommendationScore: 84,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-precision-ph1500",
      "Precision PH 1500 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-precision-pf30-gel",
      "prod-precision-pf30-drink",
      "prod-saltstick-caps",
      "prod-nuun-sport",
    ],
    alternativeProductIds: [
      "prod-saltstick-caps",
      "prod-nuun-sport",
      "prod-high5-zero",
      "prod-skratch-sport-hydration",
    ],
    ...pub,
  },
  {
    id: "prod-nuun-sport",
    slug: "nuun-sport",
    brandId: "brand-nuun",
    familyId: "fam-nuun-sport",
    generation: "Sport",
    name: "Sport",
    fullName: "Nuun Sport Electrolyte Tablets",
    shortDescription:
      "Effervescent electrolyte tablets (~15 kcal / ~4g carbs / ~300mg sodium per tablet) — designed for easy bottle electrolytes on training runs when you do not need a full carb drink mix.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-electrolyte-tablets"],
    useCaseIds: [
      "uc-short-training",
      "uc-long-runs",
      "uc-half",
      "uc-drink-based-fueling",
      "uc-easy-carry-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "electrolyte-tablet",
      servingSize: "1 tablet",
      calories: 15,
      carbsPerServing: 4,
      sugars: null,
      sodium: 300,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Drop in ~500ml water",
      form: "tablet",
      flavour: "Multiple",
      packSize: "Tube of 10",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Ultra-portable tubes for travel and race bags",
      "Low carb — leaves room for separate gel fueling",
      "Strong value and wide availability",
    ],
    weaknesses: [
      "Not a primary carbohydrate source",
      "Fizz and flavour are polarising in soft flasks",
      "Sodium lower than PH 1500 / some SaltStick plans",
    ],
    recommendationScore: 82,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-nuun-sport",
      "Nuun Sport — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-high5-zero",
      "prod-saltstick-fastchews",
      "prod-skratch-sport-hydration",
      "prod-gu-energy-gel",
    ],
    alternativeProductIds: [
      "prod-high5-zero",
      "prod-saltstick-fastchews",
      "prod-precision-ph1500",
      "prod-skratch-sport-hydration",
    ],
    ...pub,
  },
  {
    id: "prod-high5-zero",
    slug: "high5-zero",
    brandId: "brand-high5",
    familyId: "fam-high5-zero",
    generation: "ZERO",
    name: "ZERO",
    fullName: "High5 ZERO Electrolyte Tablets",
    shortDescription:
      "Near-zero-calorie electrolyte tablets for bottles — designed when you want light flavour and electrolytes without adding meaningful carbs to a gel-based fueling plan.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-electrolyte-tablets"],
    useCaseIds: [
      "uc-short-training",
      "uc-long-runs",
      "uc-half",
      "uc-drink-based-fueling",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
      "uc-beginners",
    ],
    specifications: {
      type: "electrolyte-tablet",
      servingSize: "1 tablet",
      calories: 0,
      carbsPerServing: 0,
      sugars: 0,
      sodium: 250,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Drop in ~500–750ml water",
      form: "tablet",
      flavour: "Multiple",
      packSize: "Tube of 20",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Zero-carb bottle option alongside separate gels",
      "Affordable and widely stocked in UK/EU running shops",
      "Light flavour for all-day bottles",
    ],
    weaknesses: [
      "Not a carbohydrate fuel",
      "Sodium mid-range — heavy sweaters may want more",
      "Effervescent tablets can foam in soft flasks",
    ],
    recommendationScore: 80,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-high5-zero",
      "High5 ZERO — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nuun-sport",
      "prod-sis-go-isotonic-gel",
      "prod-saltstick-caps",
      "prod-skratch-sport-hydration",
    ],
    alternativeProductIds: [
      "prod-nuun-sport",
      "prod-saltstick-fastchews",
      "prod-precision-ph1500",
      "prod-skratch-sport-hydration",
    ],
    ...pub,
  },
  {
    id: "prod-saltstick-caps",
    slug: "saltstick-caps",
    brandId: "brand-saltstick",
    familyId: "fam-saltstick-caps",
    generation: "Caps",
    name: "Caps",
    fullName: "SaltStick Caps",
    shortDescription:
      "Electrolyte capsules (~215mg sodium per cap typical) with no meaningful carbs — designed as a pocket electrolyte top-up alongside gels or water, not as a carbohydrate gel replacement.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-electrolyte-tablets"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-ultra",
      "uc-trail-training",
      "uc-easy-carry-fuel",
      "uc-half",
    ],
    specifications: {
      type: "electrolyte-tablet",
      servingSize: "1 capsule",
      calories: 0,
      carbsPerServing: 0,
      sugars: 0,
      sodium: 215,
      caffeine: false,
      caffeineAmount: null,
      protein: 0,
      fluidRequired: "Take with water",
      form: "tablet",
      flavour: "Unflavoured capsule",
      packSize: "Bottles of 100",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Tiny carry for electrolyte top-ups without mixing",
      "Zero carb — won’t disrupt gel/drink carb counting",
      "Familiar ultra / marathon aid-station format",
    ],
    weaknesses: [
      "Not a carbohydrate fuel and not a flavoured drink",
      "Swallowing capsules mid-race is awkward for some",
      "Need a separate carb plan (gels/mixes)",
    ],
    recommendationScore: 81,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-nutrition",
      "prod-saltstick-caps",
      "SaltStick Caps — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-saltstick-fastchews",
      "prod-precision-ph1500",
      "prod-nuun-sport",
      "prod-gu-roctane-gel",
    ],
    alternativeProductIds: [
      "prod-saltstick-fastchews",
      "prod-precision-ph1500",
      "prod-nuun-sport",
      "prod-high5-zero",
    ],
    ...pub,
  },

  // ─── Additional brand breadth (EU / value race formats) ──────────────────
  {
    id: "prod-high5-energy-gel",
    slug: "high5-energy-gel",
    brandId: "brand-high5",
    familyId: "fam-high5-energy-gel",
    generation: "Energy Gel",
    name: "Energy Gel",
    fullName: "High5 Energy Gel",
    shortDescription:
      "Compact carbohydrate gel for easy vest/belt carry — a practical non-Maurten option when you want simple single-serve fuel without a premium hydrogel price.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels"],
    useCaseIds: ["uc-long-runs", "uc-half", "uc-marathon", "uc-easy-carry-fuel", "uc-short-training"],
    specifications: {
      type: "gel",
      servingSize: "1 gel sachet",
      calories: null,
      carbsPerServing: 23,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended with gel",
      form: "gel",
      flavour: "Multiple flavours",
      packSize: "Box of 20",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Easy-to-carry single-serve format for long runs and races",
      "Broad flavour range for taste preference testing in training",
      "Value-oriented vs premium hydrogel gels",
    ],
    weaknesses: [
      "Label carb delivery sits below many 30–40g race gels",
      "Needs water for many runners — not an isotonic take-anywhere story",
    ],
    recommendationScore: 78,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-nutrition", "prod-high5-energy-gel", "High5 Energy Gel — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-high5-zero", "prod-sis-go-isotonic-gel", "prod-gu-energy-gel"],
    alternativeProductIds: ["prod-sis-go-isotonic-gel", "prod-gu-energy-gel", "prod-honey-stinger-gel"],
    ...pub,
  },
  {
    id: "prod-226ers-high-energy-gel",
    slug: "226ers-high-energy-gel",
    brandId: "brand-226ers",
    familyId: "fam-226ers-high-energy-gel",
    generation: "High Energy Gel",
    name: "High Energy Gel",
    fullName: "226ERS High Energy Gel",
    shortDescription:
      "Higher-carb gel format aimed at long efforts when you want more carbohydrate per sachet than a classic 20–25g gel — compare label carbs and caffeine variants before race day.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-ultra", "disc-running-racing"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-ultra", "uc-high-carb-fueling", "uc-easy-carry-fuel"],
    specifications: {
      type: "gel",
      servingSize: "1 gel sachet",
      calories: null,
      carbsPerServing: 50,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended",
      form: "gel",
      flavour: "Multiple flavours",
      packSize: "Single / box",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "High carbohydrate per sachet reduces how many packets you carry",
      "Useful when practising higher g/hour fueling on long runs",
    ],
    weaknesses: [
      "Larger carb hit can be harder to tolerate if unpractised",
      "Still a gel — not a bottle-based fueling system",
    ],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage("cat-nutrition", "prod-226ers-high-energy-gel", "226ERS High Energy Gel — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-maurten-gel-160", "prod-sis-beta-fuel-gel", "prod-styrkr-mix90"],
    alternativeProductIds: ["prod-sis-beta-fuel-gel", "prod-maurten-gel-160", "prod-precision-pf30-gel"],
    ...pub,
  },
  {
    id: "prod-enervit-carbo-gel",
    slug: "enervit-c2-1-carbo-gel",
    brandId: "brand-enervit",
    familyId: "fam-enervit-carbo-gel",
    generation: "C2:1 Carbo Gel",
    name: "C2:1 Carbo Gel",
    fullName: "Enervit C2:1 Carbo Gel",
    shortDescription:
      "Dual-source carbohydrate gel in an easy-carry sachet — a European race-fuel option when you want gel format with a C2:1 carb story rather than hydrogel.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: ["uc-long-runs", "uc-marathon", "uc-ultra", "uc-high-carb-fueling", "uc-easy-carry-fuel"],
    specifications: {
      type: "gel",
      servingSize: "1 gel sachet",
      calories: null,
      carbsPerServing: 30,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended",
      form: "gel",
      flavour: "Multiple flavours",
      packSize: "Single / box",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "≈30g carbs per serving aligns with common gel stacking math",
      "Compact carry for marathon and ultra vest pockets",
    ],
    weaknesses: [
      "Flavour and texture tolerance still need training practice",
      "Caffeine variants (if used) must be checked on the specific SKU label",
    ],
    recommendationScore: 82,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-nutrition", "prod-enervit-carbo-gel", "Enervit C2:1 Carbo Gel — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-sis-beta-fuel-gel", "prod-precision-pf30-gel", "prod-neversecond-c30-gel"],
    alternativeProductIds: ["prod-precision-pf30-gel", "prod-neversecond-c30-gel", "prod-sis-go-isotonic-gel"],
    ...pub,
  },
  {
    id: "prod-styrkr-gel30",
    slug: "styrkr-gel30",
    brandId: "brand-styrkr",
    familyId: "fam-styrkr-gel",
    generation: "GEL30",
    name: "GEL30",
    fullName: "STYRKR GEL30",
    shortDescription:
      "Dual-carb gel delivering about 30g carbohydrate per serving — built for runners who want gel carry with the same dual-carb approach as STYRKR drink mixes.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-ultra"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-gels", "sub-race-fuel"],
    useCaseIds: [
      "uc-long-runs",
      "uc-marathon",
      "uc-ultra",
      "uc-high-carb-fueling",
      "uc-easy-carry-fuel",
      "uc-non-caffeinated-fuel",
    ],
    specifications: {
      type: "gel",
      servingSize: "1 gel sachet",
      calories: null,
      carbsPerServing: 30,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water recommended",
      form: "gel",
      flavour: "Multiple flavours",
      packSize: "Single / box",
      dietaryLabels: "Vegan (brand-marketed)",
      allergens: null,
    },
    strengths: [
      "30g carbs per gel keeps hourly planning simple",
      "Pairs cleanly with STYRKR MIX90 for mixed gel + bottle race plans",
    ],
    weaknesses: [
      "Newer brand distribution varies by region",
      "Not a hydrogel — texture differs from Maurten",
    ],
    recommendationScore: 83,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-nutrition", "prod-styrkr-gel30", "STYRKR GEL30 — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-styrkr-mix90", "prod-precision-pf30-gel", "prod-neversecond-c30-gel"],
    alternativeProductIds: ["prod-precision-pf30-gel", "prod-neversecond-c30-gel", "prod-sis-beta-fuel-gel"],
    ...pub,
  },
  {
    id: "prod-naak-ultra-energy-drink",
    slug: "naak-ultra-energy-drink-mix",
    brandId: "brand-naak",
    familyId: "fam-naak-ultra-drink",
    generation: "Ultra Energy Drink Mix",
    name: "Ultra Energy Drink Mix",
    fullName: "Näak Ultra Energy Drink Mix",
    shortDescription:
      "Drink-mix carbohydrate fuel aimed at ultra-distance bottle fueling — choose this when you want drink-based carbs alongside Näak bars rather than gel-only carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-ultra", "disc-running-trail"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-carb-drink-mixes", "sub-sports-drinks"],
    useCaseIds: ["uc-ultra", "uc-long-runs", "uc-trail-training", "uc-drink-based-fueling", "uc-high-carb-fueling"],
    specifications: {
      type: "carb-mix",
      servingSize: "1 serving (see pouch label)",
      calories: null,
      carbsPerServing: null,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Mix with water in bottle/flask per label",
      form: "powder",
      flavour: "Multiple flavours",
      packSize: "Single-serve / pouch",
      dietaryLabels: null,
      allergens: null,
    },
    strengths: [
      "Drink-based fueling reduces gel packet count on ultras",
      "Pairs with Näak Ultra Energy Bar for mixed-format long efforts",
    ],
    weaknesses: [
      "Requires bottle/flask capacity and mixing discipline",
      "Confirm current label carbs/sodium on the specific flavour pouch",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-nutrition", "prod-naak-ultra-energy-drink", "Näak Ultra Energy Drink Mix — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-naak-ultra-energy-bar", "prod-tailwind-endurance", "prod-maurten-drink-mix-160"],
    alternativeProductIds: ["prod-tailwind-endurance", "prod-sis-beta-fuel-drink", "prod-styrkr-mix90"],
    ...pub,
  },
  {
    id: "prod-veloforte-bar",
    slug: "veloforte-energy-bar",
    brandId: "brand-veloforte",
    familyId: "fam-veloforte-bar",
    generation: "Energy Bar",
    name: "Energy Bar",
    fullName: "Veloforte Energy Bar",
    shortDescription:
      "Natural-style energy bar for long runs when chewable solid fuel sits better than gels — easier early-mile fueling than late-race sachets for many runners.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-ultra", "disc-running-trail"],
    categoryId: "cat-nutrition",
    subcategoryIds: ["sub-energy-bars"],
    useCaseIds: ["uc-long-runs", "uc-ultra", "uc-trail-training", "uc-easy-carry-fuel"],
    specifications: {
      type: "bar",
      servingSize: "1 bar",
      calories: null,
      carbsPerServing: null,
      sugars: null,
      sodium: null,
      caffeine: false,
      caffeineAmount: null,
      protein: null,
      fluidRequired: "Water helpful with solid bars",
      form: "bar",
      flavour: "Multiple flavours",
      packSize: "Single bar",
      dietaryLabels: null,
      allergens: "May contain nuts — check specific bar label",
    },
    strengths: [
      "Solid format for runners who fatigue of gel sweetness",
      "Works well early in long runs before switching to gels/drinks",
    ],
    weaknesses: [
      "Harder to chew late in a race than a gel",
      "Allergen profiles vary by flavour — verify the wrapper",
    ],
    recommendationScore: 79,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-nutrition", "prod-veloforte-bar", "Veloforte Energy Bar — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-veloforte-chews", "prod-clif-bar-original", "prod-naak-ultra-energy-bar"],
    alternativeProductIds: ["prod-clif-bar-original", "prod-powerbar-energize", "prod-naak-ultra-energy-bar"],
    ...pub,
  },
];

/** All nutrition wave-1 SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningNutritionWave1Raw.map((p) => p.id),
);

export const runningNutritionWave1: Product[] = applyMediaPublishGate(runningNutritionWave1Raw, MEDIA_PENDING_DRAFT_IDS);
