import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 packs & carry catalog — running backpacks, fastpacking packs,
 * pole quivers and accessory pouches. Intentionally excludes race/hydration
 * vests and belts already seeded in gear-wave1 / hydration-wave2.
 */
export const runningPacksCarryWave2Raw: Product[] = [
  // ─── Fastpacking / running backpacks ───────────────────────────────────
  {
    id: "prod-ud-fastpack-20",
    slug: "ultimate-direction-fastpack-20",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-fastpack",
    generation: "20",
    name: "Fastpack 20",
    fullName: "Ultimate Direction Fastpack 20",
    shortDescription:
      "Vest-harness day/fastpack (~23L) for long trail days and overnight kit — choose this when ADV Skin / Race Vest 6 run out of rear volume for layers, food and poles, not when you want a bounce-free race vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-fastpacking", "sub-pack-running-backpacks"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 23,
      weight: 590,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Roll-top main with full-side zip access; front bottle/flask pockets; side and rear stretch stash",
      frontStorage: "Twin front bottle/flask sleeves plus stretch harness pockets for phone, maps and fuel",
      rearStorage: "Roll-top ~23L main compartment with side zip panel access",
      pockets: "Front flasks, harness stash, side stretch, rear stretch, internal organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Infiknit / FastFlow vest harness with sliding sternum rails",
      sizeRange: "S/M–M/L",
      sizing: "S/M–M/L chest (verify current UD chart)",
      genderFit: "men",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Vest-like front access with real pack volume for fastpacking and big trail days",
      "Reservoir sleeve plus front bottles cover long remote efforts",
      "Roll-top + side zip makes kit changes faster than a sealed race-vest rear",
    ],
    weaknesses: [
      "Heavier and warmer than a flask-only race vest for road/trail races",
      "Men’s Fastpack patterning — women should start with FastpackHer 20",
    ],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-fastpack-20",
      "Ultimate Direction Fastpack 20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-fastpack-her-20",
      "prod-ud-fastpack-30",
      "prod-ud-race-vest-6",
      "prod-ud-adventure-vest",
      "prod-ud-utility-bag",
    ],
    alternativeProductIds: [
      "prod-ud-race-vest-6",
      "prod-adv-skin-12",
      "prod-osprey-talon-velocity-20",
      "prod-black-diamond-distance-15",
    ],
    ...pub,
  },
  {
    id: "prod-ud-fastpack-her-20",
    slug: "ultimate-direction-fastpack-her-20",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-fastpack",
    generation: "20",
    name: "FastpackHer 20",
    fullName: "Ultimate Direction FastpackHer 20",
    shortDescription:
      "Women’s-specific Fastpack 20 sibling — same ~23L fastpacking role (overnight kit, layers, poles) with a shorter/narrower harness when men’s Fastpack bounce or torso length feels wrong.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-fastpacking", "sub-pack-running-backpacks"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 23,
      weight: 580,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Roll-top main with side zip; women’s FastpackHer harness and front bottle pockets",
      frontStorage: "Front bottle/flask sleeves and women’s-cut harness stash",
      rearStorage: "Roll-top ~23L main with side access",
      pockets: "Front flasks, harness pockets, side/rear stretch",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Women’s Infiknit / FastFlow FastpackHer harness",
      sizeRange: "XS/S–M/L",
      sizing: "XS/S–M/L (verify current UD women’s chart)",
      genderFit: "women",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Women’s torso/chest patterning without dropping Fastpack volume",
      "Same front-bottle + roll-top workflow as the men’s Fastpack 20",
      "Clear step up from Race Vest 6 when mandatory kit and layers stack up",
    ],
    weaknesses: [
      "Still a pack — not the lightest choice for flask-only race days",
      "Sizing still needs a careful chest/torso check vs Osprey Tempest Velocity",
    ],
    recommendationScore: 87,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-fastpack-her-20",
      "Ultimate Direction FastpackHer 20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-fastpack-20",
      "prod-ud-fastpack-30",
      "prod-osprey-tempest-velocity-20",
      "prod-ud-race-vest-6",
      "prod-ud-utility-bag",
    ],
    alternativeProductIds: [
      "prod-osprey-tempest-velocity-20",
      "prod-ud-race-vest-6",
      "prod-adv-skin-12",
      "prod-ud-fastpack-20",
    ],
    ...pub,
  },
  {
    id: "prod-ud-fastpack-30",
    slug: "ultimate-direction-fastpack-30",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-fastpack",
    generation: "30",
    name: "Fastpack 30",
    fullName: "Ultimate Direction Fastpack 30",
    shortDescription:
      "30L Fastpack for multi-day fastpacking and heavy mandatory-kit ultras — pick it when Fastpack 20 is tight on sleep system or cold-weather layers; skip it for race-vest tempo days.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-fastpacking", "sub-pack-running-backpacks"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 30,
      weight: 700,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Larger roll-top Fastpack main with vest harness and front bottle pockets",
      frontStorage: "Front bottle/flask sleeves and harness stash",
      rearStorage: "30L roll-top main for overnight / heavy kit",
      pockets: "Front flasks, harness, side/rear stretch, internal organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Infiknit / FastFlow vest harness with sternum rails",
      sizeRange: "S/M–M/L",
      sizing: "S/M–M/L (verify current UD chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "True overnight fastpacking volume while keeping vest-style front access",
      "Reservoir + bottles scale hydration for remote multi-day routes",
      "Compression keeps a half-full pack from bouncing like a hiking daypack",
    ],
    weaknesses: [
      "Overkill and warm for supported ultras or road longs",
      "Heavier empty than Fastpack 20 or alpine Distance packs",
    ],
    recommendationScore: 85,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-fastpack-30",
      "Ultimate Direction Fastpack 30 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-fastpack-20",
      "prod-ud-fastpack-her-20",
      "prod-osprey-talon-velocity-30",
      "prod-black-diamond-distance-22",
      "prod-ud-adventure-vest",
    ],
    alternativeProductIds: [
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-30",
      "prod-black-diamond-distance-22",
      "prod-camelbak-octane-22",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-talon-velocity-20",
    slug: "osprey-talon-velocity-20",
    brandId: "brand-osprey",
    familyId: "fam-osprey-talon-velocity",
    generation: "20",
    name: "Talon Velocity 20",
    fullName: "Osprey Talon Velocity 20",
    shortDescription:
      "Men’s 20L multi-sport running daypack with vest-inspired harness — stronger structured pack feel than Duro race vests; shortlist for trail days, peak bagging and light fastpacking, not minimal race-vest carry.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 20,
      weight: 870,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Top-cinch main, soft-flask harness pockets, hipbelt pockets, stretch shove-it, external hydration sleeve",
      frontStorage: "Soft-flask compatible harness pockets plus zip phone/stash",
      rearStorage: "20L main (S/M; L/XL closer to 22L) with stretch mesh shove-it",
      pockets: "Harness flasks, phone zip, hipbelt, dual-access side stretch, shove-it",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: true,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "BioStretch vest harness + adjustable torso / AirScape backpanel",
      sizeRange: "S/M–L/XL",
      sizing: "S/M–L/XL torso (verify current Osprey chart)",
      genderFit: "men",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Osprey fit system dials torso length better than most race vests",
      "Helmet-capable shove-it and pole/axe points suit alpine trail days",
      "External hydration sleeve keeps bladder days clean vs flask-only vests",
    ],
    weaknesses: [
      "Heavier empty than UD Fastpack 20 or BD Distance 15",
      "Men’s Talon cut — women should look at Tempest Velocity 20",
    ],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-talon-velocity-20",
      "Osprey Talon Velocity 20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-tempest-velocity-20",
      "prod-osprey-talon-velocity-30",
      "prod-osprey-duro-15",
      "prod-ud-fastpack-20",
      "prod-salomon-custom-quiver",
    ],
    alternativeProductIds: [
      "prod-ud-fastpack-20",
      "prod-osprey-duro-15",
      "prod-black-diamond-distance-15",
      "prod-adv-skin-12",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-tempest-velocity-20",
    slug: "osprey-tempest-velocity-20",
    brandId: "brand-osprey",
    familyId: "fam-osprey-tempest-velocity",
    generation: "20",
    name: "Tempest Velocity 20",
    fullName: "Osprey Tempest Velocity 20",
    shortDescription:
      "Women’s counterpart to Talon Velocity 20 — same ~20L running/fastpacking daypack role with Tempest harness shaping when men’s Talon bounce or torso length fights your fit.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 20,
      weight: 850,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Women’s Tempest Velocity main with soft-flask harness, hipbelt pockets and external hydration sleeve",
      frontStorage: "Soft-flask harness pockets and zip phone/stash",
      rearStorage: "~20L main with stretch shove-it for helmet/layer",
      pockets: "Harness, hipbelt, side stretch, shove-it",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: true,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Women’s BioStretch Tempest Velocity harness + adjustable torso",
      sizeRange: "XS/S–S/M",
      sizing: "XS/S–S/M (verify current Osprey Tempest chart)",
      genderFit: "women",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Women’s Osprey patterning with the same Velocity multi-sport feature set",
      "Helmet and pole carry for alpine trail days beyond a race vest",
      "Pairs cleanly with Osprey Hydraulics reservoirs already in catalog",
    ],
    weaknesses: [
      "Not as light or race-minimal as ADV Skin / Dyna race vests",
      "Pack structure can feel warm on hot road/trail tempo days",
    ],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-tempest-velocity-20",
      "Osprey Tempest Velocity 20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-talon-velocity-20",
      "prod-ud-fastpack-her-20",
      "prod-osprey-dyna-lt",
      "prod-osprey-duro-15",
      "prod-salomon-custom-quiver",
    ],
    alternativeProductIds: [
      "prod-ud-fastpack-her-20",
      "prod-osprey-talon-velocity-20",
      "prod-adv-skin-12",
      "prod-ud-race-vest-6",
    ],
    ...pub,
  },
  {
    id: "prod-osprey-talon-velocity-30",
    slug: "osprey-talon-velocity-30",
    brandId: "brand-osprey",
    familyId: "fam-osprey-talon-velocity",
    generation: "30",
    name: "Talon Velocity 30",
    fullName: "Osprey Talon Velocity 30",
    shortDescription:
      "Men’s 30L Talon Velocity for heavier fastpacking and alpine day loads — step up from the 20 when sleep kit or cold layers overflow; still more run-capable than a hiking daypack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 30,
      weight: 980,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "Larger Velocity main with vest harness flasks, hipbelt pockets and external hydration sleeve",
      frontStorage: "Soft-flask harness pockets and zip phone/stash",
      rearStorage: "30L-class main for overnight / heavy alpine kit",
      pockets: "Harness, hipbelt, side stretch, shove-it, compression straps",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: true,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "BioStretch Talon Velocity harness + adjustable torso",
      sizeRange: "S/M–L/XL",
      sizing: "S/M–L/XL (verify current Osprey chart)",
      genderFit: "men",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Osprey load carry scales better than stuffing a 12L race vest",
      "Helmet and pole/axe attachments for technical alpine approaches",
      "Clear size step from Talon Velocity 20 inside one family",
    ],
    weaknesses: [
      "Too much pack for supported ultras and road training",
      "Heavier and less race-vest agile than UD Fastpack 30 on pure run miles",
    ],
    recommendationScore: 84,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-osprey-talon-velocity-30",
      "Osprey Talon Velocity 30 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-osprey-talon-velocity-20",
      "prod-ud-fastpack-30",
      "prod-black-diamond-distance-22",
      "prod-camelbak-octane-22",
      "prod-osprey-duro-15",
    ],
    alternativeProductIds: [
      "prod-ud-fastpack-30",
      "prod-osprey-talon-velocity-20",
      "prod-black-diamond-distance-22",
      "prod-camelbak-octane-22",
    ],
    ...pub,
  },
  {
    id: "prod-black-diamond-distance-15",
    slug: "black-diamond-distance-15",
    brandId: "brand-black-diamond",
    familyId: "fam-black-diamond-distance",
    generation: "15",
    name: "Distance 15",
    fullName: "Black Diamond Distance 15 Backpack",
    shortDescription:
      "15L alpine running backpack (not the Distance 8 race vest) — vest harness with real pack volume for long mountain days, poles and light technical kit when 8L is too tight.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs", "uc-fastpacking"],
    specifications: {
      capacity: 15,
      weight: 330,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "15L alpine pack body with vest harness, soft-flask pockets and built-in Z-pole sleeves",
      frontStorage: "Twin soft-flask holsters plus zip/stretch shoulder pockets",
      rearStorage: "15L main with front stretch shove-it and side stash",
      pockets: "Flask holsters, shoulder zip/stretch, side stash, internal zip",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Distance vest harness with SETT stitchless edge taping",
      sizeRange: "S–L",
      sizing: "S–L torso (verify current BD Distance chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Much lighter empty than most 15–20L running backpacks",
      "Built-in Z-pole sleeves beat dangling race-vest pole loops on alpine terrain",
      "Clear capacity step up from Distance 8 without jumping to a 22L pack",
    ],
    weaknesses: [
      "No bladder sleeve — reservoir-first ultras stay on Pinnacle / Zephyr / Fastpack",
      "Alpine focus is narrower than Osprey Velocity multi-sport versatility",
    ],
    recommendationScore: 87,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-black-diamond-distance-15",
      "Black Diamond Distance 15 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-black-diamond-distance-8",
      "prod-black-diamond-distance-22",
      "prod-salomon-xa-15",
      "prod-ud-fastpack-20",
      "prod-leki-trail-running-quiver",
    ],
    alternativeProductIds: [
      "prod-black-diamond-distance-8",
      "prod-salomon-xa-15",
      "prod-adv-skin-12",
      "prod-osprey-talon-velocity-20",
    ],
    ...pub,
  },
  {
    id: "prod-black-diamond-distance-22",
    slug: "black-diamond-distance-22",
    brandId: "brand-black-diamond",
    familyId: "fam-black-diamond-distance",
    generation: "22",
    name: "Distance 22",
    fullName: "Black Diamond Distance 22 Backpack",
    shortDescription:
      "22L Distance alpine/running pack for long mountain days and light overnights — more rear volume than Distance 15 while staying run-capable; still not a soft race vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks", "sub-pack-fastpacking"],
    useCaseIds: ["uc-fastpacking", "uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 22,
      weight: 400,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: 1000,
      bottleCapacity: 1000,
      bladderCompatible: false,
      storage: "22L alpine pack with vest harness, soft-flask pockets, Z-pole sleeves and front stretch pocket",
      frontStorage: "Soft-flask holsters plus zip/stretch shoulder pockets",
      rearStorage: "22L main for layers, food and light overnight kit",
      pockets: "Flask holsters, shoulder pockets, side stash, front stretch, internal zip",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Distance vest harness with SETT edge taping and side compression",
      sizeRange: "S–L",
      sizing: "S–L torso (verify current BD Distance chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Light for 22L — strong fast-and-light alpine overnight option",
      "Z-pole and piolet carry suit technical mountain objectives",
      "Compression keeps partial loads stable while running",
    ],
    weaknesses: [
      "Still flask-first — no reservoir sleeve for hot desert ultras",
      "Less everyday commute/daypack versatility than Trailblazer or Octane",
    ],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-black-diamond-distance-22",
      "Black Diamond Distance 22 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-black-diamond-distance-15",
      "prod-black-diamond-distance-8",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
      "prod-leki-trail-running-quiver",
    ],
    alternativeProductIds: [
      "prod-black-diamond-distance-15",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
      "prod-camelbak-octane-22",
    ],
    ...pub,
  },
  {
    id: "prod-salomon-xa-15",
    slug: "salomon-xa-15",
    brandId: "brand-salomon",
    familyId: "fam-salomon-xa-pack",
    generation: "15",
    name: "XA 15",
    fullName: "Salomon XA 15",
    shortDescription:
      "15L Salomon trail running backpack for long dirt days — more structured rear volume than ADV Skin race vests when you need layers and food without jumping to a 20–30L Fastpack.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs", "uc-fastpacking"],
    specifications: {
      capacity: 15,
      weight: 450,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 1000,
      bladderCompatible: true,
      storage: "15L trail pack with Sensifit-style harness pockets and rear main for layers/food",
      frontStorage: "Soft-flask / bottle harness pockets and fuel stash",
      rearStorage: "15L main compartment for jacket, food and trail kit",
      pockets: "Front flasks, harness stash, side/rear organization",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "Salomon trail harness with sternum adjustment",
      sizeRange: "S–L",
      sizing: "S–L (verify current Salomon XA chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Familiar Salomon harness feel with backpack-scale rear volume",
      "Quiver-friendly pole story pairs with Custom Quiver add-ons",
      "Sweet spot between ADV Skin 12 and Fastpack 20 for long trail days",
    ],
    weaknesses: [
      "Not as overnight-capable as Fastpack 30 / Distance 22",
      "Less alpine-specific pole/ice tool story than BD Distance packs",
    ],
    recommendationScore: 85,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-salomon-xa-15",
      "Salomon XA 15 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-adv-skin-12",
      "prod-salomon-adv-skin-5",
      "prod-salomon-custom-quiver",
      "prod-salomon-soft-flask-stash",
      "prod-black-diamond-distance-15",
    ],
    alternativeProductIds: [
      "prod-adv-skin-12",
      "prod-black-diamond-distance-15",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
    ],
    ...pub,
  },
  {
    id: "prod-camelbak-octane-22",
    slug: "camelbak-octane-22",
    brandId: "brand-camelbak",
    familyId: "fam-camelbak-octane",
    generation: "22",
    name: "Octane 22",
    fullName: "CamelBak Octane 22",
    shortDescription:
      "22L CamelBak running/daypack with bladder-first DNA — better when you want structured backpack carry and reservoir workflow than a soft race vest like Zephyr or ADV Skin.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra", "uc-fastpacking"],
    specifications: {
      capacity: 22,
      weight: 740,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: true,
      reservoirIncluded: true,
      totalHydrationCapacity: 2000,
      bottleCapacity: null,
      bladderCompatible: true,
      storage: "22L day/running pack with reservoir sleeve, harness stash and rear main",
      frontStorage: "Harness stretch pockets for phone/fuel",
      rearStorage: "22L main plus dedicated reservoir compartment",
      pockets: "Harness stash, side stretch, hipbelt/organization depending on generation",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: false,
      raceKitCapacity: true,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: true,
      waterResistance: "water-resistant",
      fitSystem: "CamelBak running/day harness with sternum and hipbelt",
      sizeRange: "One size / adjustable",
      sizing: "Adjustable torso/hip (verify current CamelBak chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "adventure"],
    },
    strengths: [
      "Reservoir-first carry suits hot long days better than flask-only race vests",
      "22L absorbs layers and food without forcing a dedicated fastpack",
      "Familiar CamelBak tube workflow for runners already on Crux bladders",
    ],
    weaknesses: [
      "Less race-vest agile and bounce-controlled than ADV Skin / VaporAir",
      "Heavier empty than BD Distance or Salomon XA trail packs",
    ],
    recommendationScore: 82,
    valueScore: 77,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-camelbak-octane-22",
      "CamelBak Octane 22 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-camelbak-zephyr",
      "prod-camelbak-crux-15",
      "prod-salomon-trailblazer-20",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
    ],
    alternativeProductIds: [
      "prod-camelbak-zephyr",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
      "prod-salomon-trailblazer-20",
    ],
    ...pub,
  },
  {
    id: "prod-salomon-trailblazer-20",
    slug: "salomon-trailblazer-20",
    brandId: "brand-salomon",
    familyId: "fam-salomon-trailblazer",
    generation: "20",
    name: "Trailblazer 20",
    fullName: "Salomon Trailblazer 20",
    shortDescription:
      "20L Salomon daypack for commute-to-trail and light hiking carry — choose it for everyday backpack utility; pick XA 15 / Fastpack when you need a run-first vest harness.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-running-backpacks"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-commute-running"],
    specifications: {
      capacity: 20,
      weight: 560,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: null,
      bladderCompatible: true,
      storage: "20L daypack main with simple organization for commute, trail and travel days",
      frontStorage: "Limited harness/front stash vs race vests — more traditional daypack access",
      rearStorage: "20L zip main for layers, shoes or work/trail kit",
      pockets: "Main compartment, exterior stash/organization",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: true,
      raceBibAttachment: false,
      bounceControl: "moderate",
      breathability: "moderate",
      reflectivity: true,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Daypack shoulder harness with sternum strap",
      sizeRange: "One size / adjustable",
      sizing: "Adjustable straps (verify current Salomon chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "adventure"],
    },
    strengths: [
      "Simple 20L daypack utility for commute + light trail days",
      "Cheaper everyday carry than a dedicated Fastpack or Velocity",
      "Reservoir sleeve option without race-vest complexity",
    ],
    weaknesses: [
      "Not a bounce-controlled race or trail-running harness",
      "Weak pole/race-kit story vs XA 15, Distance or Fastpack",
    ],
    recommendationScore: 74,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-salomon-trailblazer-20",
      "Salomon Trailblazer 20 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-salomon-xa-15",
      "prod-camelbak-octane-22",
      "prod-ud-fastpack-20",
      "prod-adv-skin-12",
      "prod-salomon-soft-flask-stash",
    ],
    alternativeProductIds: [
      "prod-salomon-xa-15",
      "prod-camelbak-octane-22",
      "prod-ud-fastpack-20",
      "prod-osprey-talon-velocity-20",
    ],
    ...pub,
  },

  // ─── Pole quivers ──────────────────────────────────────────────────────
  {
    id: "prod-salomon-custom-quiver",
    slug: "salomon-custom-quiver",
    brandId: "brand-salomon",
    familyId: "fam-salomon-custom-quiver",
    generation: "1",
    name: "Custom Quiver",
    fullName: "Salomon Custom Quiver",
    shortDescription:
      "Soft-flask-style pole quiver add-on for Salomon race vests and trail packs — carry collapsed poles on the harness without stuffing them through rear loops on every climb.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-pole-quivers"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: null,
      weight: 45,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: null,
      bladderCompatible: false,
      storage: "Dedicated soft quiver sleeve for collapsed trail poles; mounts to compatible Salomon vest/pack daisy or flask architecture",
      frontStorage: "Harness-mounted quiver access while running",
      rearStorage: "N/A — quiver is the carry product",
      pockets: "Single pole quiver sleeve",
      phoneStorage: false,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: false,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Attaches to compatible Salomon ADV Skin / XA ecosystem",
      sizeRange: "One size",
      sizing: "One size — verify vest compatibility",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: [
      "Clean on-the-move pole stow for Salomon vest users",
      "Lighter and simpler than carrying a dedicated alpine pack just for poles",
      "Pairs with ADV Skin / XA when race-vest loops feel fiddly",
    ],
    weaknesses: [
      "Salomon-ecosystem focused — not a universal quiver for every vest",
      "Adds harness bulk on hot road days when poles stay home",
    ],
    recommendationScore: 80,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-salomon-custom-quiver",
      "Salomon Custom Quiver — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-adv-skin-12",
      "prod-salomon-adv-skin-5",
      "prod-salomon-xa-15",
      "prod-leki-trail-running-quiver",
      "prod-salomon-soft-flask-stash",
    ],
    alternativeProductIds: [
      "prod-leki-trail-running-quiver",
      "prod-adv-skin-12",
      "prod-salomon-xa-15",
    ],
    ...pub,
  },
  {
    id: "prod-leki-trail-running-quiver",
    slug: "leki-trail-running-quiver",
    brandId: "brand-leki",
    familyId: "fam-leki-trail-quiver",
    generation: "1",
    name: "Trail Running Quiver",
    fullName: "LEKI Trail Running Quiver",
    shortDescription:
      "LEKI trail-running pole quiver for quick stow/deploy on climbs and descends — brand-agnostic add-on when your vest’s built-in pole loops are slow or overloaded.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-pole-quivers"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: null,
      weight: 55,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: null,
      bladderCompatible: false,
      storage: "Trail-running pole quiver sleeve designed for LEKI foldable poles; straps/clips to vest or pack harness",
      frontStorage: "Harness-reachable quiver access",
      rearStorage: "N/A — quiver accessory",
      pockets: "Single quiver sleeve",
      phoneStorage: false,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: false,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Strap/clip mount to vest or pack",
      sizeRange: "One size",
      sizing: "One size — verify pole diameter and vest mount",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: [
      "Purpose-built for LEKI foldable trail poles",
      "Works as an add-on when vest pole loops are already full of kit",
      "Keeps poles off your hands on steep hike-a-bike climbs",
    ],
    weaknesses: [
      "Best with LEKI poles — other brands may need adapters or different fit",
      "Another moving part vs packs with integrated Z-pole sleeves (BD Distance)",
    ],
    recommendationScore: 78,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-leki-trail-running-quiver",
      "LEKI Trail Running Quiver — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-salomon-custom-quiver",
      "prod-black-diamond-distance-15",
      "prod-black-diamond-distance-22",
      "prod-adv-skin-12",
      "prod-ud-race-vest-6",
    ],
    alternativeProductIds: [
      "prod-salomon-custom-quiver",
      "prod-black-diamond-distance-15",
      "prod-ud-race-vest-6",
    ],
    ...pub,
  },

  // ─── Accessory pouches ─────────────────────────────────────────────────
  {
    id: "prod-ud-utility-bag",
    slug: "ultimate-direction-utility-bag",
    brandId: "brand-ultimate-direction",
    familyId: "fam-ud-utility",
    generation: "1",
    name: "Utility Bag",
    fullName: "Ultimate Direction Utility Bag",
    shortDescription:
      "UD front utility / stash pouch for race vests and Fastpacks — add phone, food or small kit volume without jumping vest sizes when front stretch pockets are maxed.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-accessory-pouches"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra", "uc-marathon"],
    specifications: {
      capacity: 1,
      weight: 35,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: null,
      bladderCompatible: false,
      storage: "Detachable/attachable front utility pouch for phone, gels and small kit on UD harness daisy points",
      frontStorage: "Zip or stretch utility volume on the chest/harness",
      rearStorage: "N/A — front accessory pouch",
      pockets: "Single utility pouch",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: false,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Attaches to compatible UD vest/pack harness",
      sizeRange: "One size",
      sizing: "One size — verify UD mount compatibility",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Expands front access without buying a larger vest",
      "Phone-capable stash for Race Vest / Fastpack users",
      "Lightweight add-on vs carrying a second belt",
    ],
    weaknesses: [
      "UD-ecosystem focused — not universal across every brand vest",
      "Extra pouch can bounce if overstuffed or poorly clipped",
    ],
    recommendationScore: 76,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-ud-utility-bag",
      "Ultimate Direction Utility Bag — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-ud-race-vest-6",
      "prod-ud-adventure-vest",
      "prod-ud-fastpack-20",
      "prod-salomon-soft-flask-stash",
      "prod-nathan-zippered-stash",
    ],
    alternativeProductIds: [
      "prod-salomon-soft-flask-stash",
      "prod-nathan-zippered-stash",
      "prod-ud-race-vest-6",
    ],
    ...pub,
  },
  {
    id: "prod-salomon-soft-flask-stash",
    slug: "salomon-soft-flask-stash",
    brandId: "brand-salomon",
    familyId: "fam-salomon-soft-flask-stash",
    generation: "1",
    name: "Soft Flask Stash",
    fullName: "Salomon Soft Flask Stash / Pocket",
    shortDescription:
      "Salomon ADV Skin–ecosystem soft-flask stash / accessory pocket — add front volume for phone, flask or fuel when stock Sensifit pockets are already full.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-accessory-pouches"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-ultra", "uc-marathon"],
    specifications: {
      capacity: 0.5,
      weight: 30,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 1,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: 500,
      bladderCompatible: false,
      storage: "Accessory soft-flask / stash pocket for Salomon ADV Skin and compatible harness mounts",
      frontStorage: "Extra front flask or phone/fuel stash pocket",
      rearStorage: "N/A — front accessory",
      pockets: "Single soft-flask stash pocket",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: false,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Compatible with Salomon ADV Skin / custom pocket mounts",
      sizeRange: "One size",
      sizing: "One size — verify ADV Skin generation compatibility",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Modular front capacity without upsizing the whole vest",
      "Keeps phone/fuel reachable in the Salomon Sensifit workflow",
      "Pairs with Custom Quiver for a full ADV Skin add-on kit",
    ],
    weaknesses: [
      "Salomon-specific — limited value on Nathan/Osprey/UD harnesses",
      "Easy to overstuff and create bounce if used as a catch-all dump pocket",
    ],
    recommendationScore: 77,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-salomon-soft-flask-stash",
      "Salomon Soft Flask Stash — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-adv-skin-12",
      "prod-salomon-adv-skin-5",
      "prod-salomon-custom-quiver",
      "prod-soft-flask-500",
      "prod-ud-utility-bag",
    ],
    alternativeProductIds: [
      "prod-ud-utility-bag",
      "prod-nathan-zippered-stash",
      "prod-salomon-adv-skin-5",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-zippered-stash",
    slug: "nathan-zippered-stash",
    brandId: "brand-nathan",
    familyId: "fam-nathan-stash",
    generation: "1",
    name: "Zippered Stash",
    fullName: "Nathan Zippered Stash / Phone Pouch",
    shortDescription:
      "Nathan zippered phone/stash pouch for vests and belts — secure small-kit carry when stretch pockets feel too open for a phone on race or trail days.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-accessory-pouches"],
    useCaseIds: ["uc-long-runs", "uc-trail-training", "uc-marathon", "uc-ultra"],
    specifications: {
      capacity: 0.4,
      weight: 28,
      includedFlasks: 0,
      includedFlaskVolume: null,
      flaskCount: 0,
      reservoirCompatible: false,
      reservoirIncluded: false,
      totalHydrationCapacity: null,
      bottleCapacity: null,
      bladderCompatible: false,
      storage: "Zippered phone/stash pouch that clips or straps to compatible Nathan vest/belt carry points",
      frontStorage: "Secure zip phone/fuel pouch",
      rearStorage: "N/A — accessory pouch",
      pockets: "Single zippered stash",
      phoneStorage: true,
      poleAttachment: false,
      quiverCompatible: false,
      raceKitCapacity: false,
      helmetCompatible: false,
      compression: false,
      raceBibAttachment: false,
      bounceControl: "high",
      breathability: "high",
      reflectivity: true,
      whistle: false,
      waterResistance: "water-resistant",
      fitSystem: "Clip/strap to compatible Nathan pack or belt",
      sizeRange: "One size",
      sizing: "One size — verify mount compatibility",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra", "road"],
    },
    strengths: [
      "Zip closure feels safer for phones than open stretch mesh",
      "Lightweight way to add secure stash without a larger vest",
      "Useful across Nathan VaporAir / Peak ecosystems",
    ],
    weaknesses: [
      "Not a hydration solution — still need flasks or a belt bottle",
      "Mount quality varies by vest generation and daisy-point layout",
    ],
    recommendationScore: 75,
    valueScore: 81,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-packs-vests",
      "prod-nathan-zippered-stash",
      "Nathan Zippered Stash — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-vaporair-4",
      "prod-nathan-vaporair-2",
      "prod-nathan-peak",
      "prod-ud-utility-bag",
      "prod-salomon-soft-flask-stash",
    ],
    alternativeProductIds: [
      "prod-ud-utility-bag",
      "prod-salomon-soft-flask-stash",
      "prod-nathan-mirage",
    ],
    ...pub,
  },
];

/** All wave-2 packs/carry SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningPacksCarryWave2Raw.map((p) => p.id),
);

export const runningPacksCarryWave2: Product[] = applyMediaPublishGate(runningPacksCarryWave2Raw, MEDIA_PENDING_DRAFT_IDS);
