import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 Running Recovery Gear catalog.
 *
 * Expands beyond gear-wave1 seeds (prod-theragun-mini, prod-hypervolt-go-2,
 * prod-triggerpoint-grid, prod-oofos-ooriginal).
 *
 * Claim policy: no injury-prevention / healing / circulation / lactic-acid claims.
 * Prefer practical comfort / soft-tissue / portability language; mark mfr marketing.
 *
 * ID collisions avoided (already in other catalogs):
 * - prod-cep-calf-sleeves (gear-wave1 accessories) → prod-cep-the-run-calf
 * - prod-blackroll-standard (fitness seed) → prod-blackroll-pro
 *
 * Skipped: Hyperice Venom (not a massage gun). Hypervolt Go already in wave1.
 *
 * NOT wired into products.ts aggregators yet (parent will wire).
 */
export const runningRecoveryWave2Raw: Product[] = [
  // ─── Massage guns ────────────────────────────────────────────────────────
  {
    id: "prod-theragun-prime",
    slug: "therabody-theragun-prime",
    brandId: "brand-therabody",
    familyId: "fam-theragun",
    generation: "Prime",
    name: "Theragun Prime",
    fullName: "Therabody Theragun Prime",
    shortDescription:
      "Mid-tier percussive massager with 16 mm amplitude for home post-run soft-tissue work — useful for comfort routines on calves and quads; not a medical treatment.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-comfort",
      "uc-recovery-runs",
    ],
    specifications: {
      type: "percussive-massage",
      weight: 820,
      battery: "~120 min (manufacturer claim)",
      portable: true,
      amplitude: 16,
      stallForce: "~30 lb class (verify current gen)",
      speeds: "5",
      attachments: "4 (typical Prime kit)",
      noise: "quiet",
      sizeClass: "full-size",
    },
    strengths: [
      "16 mm stroke covers most runner soft-tissue sessions at home",
      "Triangle grip reaches hard-to-hold angles on calves and glutes",
      "Clear step up from Mini without Pro-tier price",
    ],
    weaknesses: [
      "Bulkier than Mini / Go for race-weekend bags",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 84,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-theragun-prime",
      "Therabody Theragun Prime — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-theragun-mini",
      "prod-theragun-pro",
      "prod-theragun-relief",
      "prod-hypervolt-2",
    ],
    alternativeProductIds: [
      "prod-theragun-mini",
      "prod-hypervolt-2",
      "prod-opove-m3-pro",
    ],
    ...pub,
  },
  {
    id: "prod-theragun-pro",
    slug: "therabody-theragun-pro",
    brandId: "brand-therabody",
    familyId: "fam-theragun",
    generation: "Pro / Pro Plus",
    name: "Theragun Pro",
    fullName: "Therabody Theragun Pro",
    shortDescription:
      "Full-size Theragun flagship for high-mileage home soft-tissue kits — more force and attachments than Prime; Kitletics rates it as a comfort tool, not injury care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "percussive-massage",
      weight: 1100,
      battery: "~120–150 min (manufacturer claim; verify gen)",
      portable: false,
      amplitude: 16,
      stallForce: "High / Pro Plus class (manufacturer claim)",
      speeds: "5+",
      attachments: "6–8 depending on kit",
      noise: "quiet",
      sizeClass: "full-size",
    },
    strengths: [
      "Highest Therabody force/attachment depth for dedicated home setups",
      "OLED / app features on current Pro Plus (manufacturer marketing)",
      "Suits athletes who already own Mini and want a desk-side unit",
    ],
    weaknesses: [
      "Heavy and expensive vs portable guns for travel",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 82,
    valueScore: 68,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-theragun-pro",
      "Therabody Theragun Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-theragun-prime",
      "prod-theragun-mini",
      "prod-normatec-3",
      "prod-hypervolt-2",
    ],
    alternativeProductIds: [
      "prod-theragun-prime",
      "prod-hypervolt-2",
      "prod-timtam-power-massager-v3.7",
    ],
    ...pub,
  },
  {
    id: "prod-theragun-relief",
    slug: "therabody-theragun-relief",
    brandId: "brand-therabody",
    familyId: "fam-theragun",
    generation: "Relief",
    name: "Theragun Relief",
    fullName: "Therabody Theragun Relief",
    shortDescription:
      "Entry Theragun with 10 mm amplitude and simple one-button speeds — gentle portable percussion for comfort routines; quieter and milder than Prime.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-comfort",
      "uc-home-recovery",
    ],
    specifications: {
      type: "percussive-massage",
      weight: 620,
      battery: "~120 min (manufacturer claim)",
      portable: true,
      amplitude: 10,
      stallForce: "~20 lb class (third-party / verify)",
      speeds: "3",
      attachments: "3 (Ball, Dampener, Thumb)",
      noise: "quiet",
      sizeClass: "compact",
    },
    strengths: [
      "Lightest full-grip Theragun for beginners and gentle sessions",
      "USB-C charging and simple controls",
      "Quieter comfort-first option vs deeper-stroke models",
    ],
    weaknesses: [
      "Shallower stroke and lower force than Prime / Pro",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 76,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-theragun-relief",
      "Therabody Theragun Relief — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-theragun-mini",
      "prod-theragun-prime",
      "prod-renpho-r3",
    ],
    alternativeProductIds: [
      "prod-theragun-mini",
      "prod-hypervolt-go-2",
      "prod-renpho-r3",
    ],
    ...pub,
  },
  {
    id: "prod-hypervolt-2",
    slug: "hyperice-hypervolt-2",
    brandId: "brand-hyperice",
    familyId: "fam-hypervolt",
    generation: "2 / 2 Pro",
    name: "Hypervolt 2",
    fullName: "Hyperice Hypervolt 2",
    shortDescription:
      "Full-size Hyperice percussion massager for post-run soft-tissue work at home — Bluetooth app speeds are manufacturer features; Kitletics treats it as a comfort tool.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "percussive-massage",
      weight: 900,
      battery: "~3 hrs (manufacturer claim; verify model)",
      portable: true,
      amplitude: null,
      stallForce: "Hypervolt 2 / 2 Pro class (manufacturer claim)",
      speeds: "5 (app-adjustable on Bluetooth models)",
      attachments: "5 typical Hypervolt kit",
      noise: "quiet",
      sizeClass: "full-size",
    },
    strengths: [
      "Quiet Hyperice motor with familiar attachment ecosystem",
      "Step up from Hypervolt Go 2 for home sessions",
      "Pairs cleanly with Normatec in the same brand stack",
    ],
    weaknesses: [
      "Less packable than Go 2 for travel kits",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 83,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-hypervolt-2",
      "Hyperice Hypervolt 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-hypervolt-go-2",
      "prod-theragun-prime",
      "prod-normatec-3",
      "prod-hyperice-vyper-3",
    ],
    alternativeProductIds: [
      "prod-theragun-prime",
      "prod-hypervolt-go-2",
      "prod-opove-m3-pro",
    ],
    ...pub,
  },
  {
    id: "prod-renpho-r3",
    slug: "renpho-r3",
    brandId: "brand-renpho",
    familyId: "fam-renpho-r3",
    generation: "R3",
    name: "R3",
    fullName: "RENPHO R3 Massage Gun",
    shortDescription:
      "Value portable percussion gun for travel and apartment soft-tissue routines — practical comfort tool at a lower price than Theragun/Hypervolt mid-tiers.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-home-recovery",
      "uc-comfort",
    ],
    specifications: {
      type: "massage-gun",
      weight: null,
      battery: "Rechargeable (verify current claim)",
      portable: true,
      amplitude: null,
      stallForce: null,
      speeds: "Multi-speed",
      attachments: "Multiple included heads (kit-dependent)",
      noise: "moderate",
      sizeClass: "compact",
    },
    strengths: [
      "Strong value for first percussion purchase",
      "Portable enough for race-weekend bags",
      "Simple controls without app lock-in",
    ],
    weaknesses: [
      "Build/noise/support may trail premium brands",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 74,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-renpho-r3",
      "RENPHO R3 Massage Gun — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-opove-m3-pro",
      "prod-theragun-relief",
      "prod-theragun-mini",
    ],
    alternativeProductIds: [
      "prod-opove-m3-pro",
      "prod-theragun-relief",
      "prod-hypervolt-go-2",
    ],
    ...pub,
  },
  {
    id: "prod-opove-m3-pro",
    slug: "opove-m3-pro",
    brandId: "brand-opove",
    familyId: "fam-opove-m3",
    generation: "M3 Pro",
    name: "M3 Pro",
    fullName: "OPOVE M3 Pro Massage Gun",
    shortDescription:
      "Athlete-oriented percussion massager with strong stall-force class for home post-run soft-tissue work — portable enough for travel kits without Theragun pricing.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-travel-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "massage-gun",
      weight: null,
      battery: "Rechargeable (verify current claim)",
      portable: true,
      amplitude: null,
      stallForce: "High stall-force class (manufacturer claim)",
      speeds: "Multi-speed",
      attachments: "Multiple included heads",
      noise: "moderate",
      sizeClass: "compact",
    },
    strengths: [
      "Forceful mid-price alternative to Prime / Hypervolt 2",
      "Carrying case friendly for travel recovery kits",
      "Broad attachment set for calves, quads and feet",
    ],
    weaknesses: [
      "Brand support and noise vary vs Therabody/Hyperice",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 78,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-opove-m3-pro",
      "OPOVE M3 Pro Massage Gun — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-renpho-r3",
      "prod-theragun-prime",
      "prod-timtam-power-massager-v3.7",
    ],
    alternativeProductIds: [
      "prod-renpho-r3",
      "prod-theragun-prime",
      "prod-hypervolt-2",
    ],
    ...pub,
  },
  {
    id: "prod-timtam-power-massager-v3.7",
    slug: "timtam-power-massager-v3-7",
    brandId: "brand-timtam",
    familyId: "fam-timtam-power-massager",
    generation: "V3.7",
    name: "Power Massager V3.7",
    fullName: "TimTam Power Massager V3.7",
    shortDescription:
      "Athlete-focused percussion massager for post-session soft-tissue work — marketed for training recovery; Kitletics rates it as a practical comfort tool, not clinical care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-massage"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-guns"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-travel-recovery",
    ],
    specifications: {
      type: "percussive-massage",
      weight: null,
      battery: "Rechargeable (verify current claim)",
      portable: true,
      amplitude: null,
      stallForce: null,
      speeds: "Multi-speed",
      attachments: "Multiple included heads",
      noise: "moderate",
      sizeClass: "full-size",
    },
    strengths: [
      "Built for athletic soft-tissue routines after hard sessions",
      "Alternative ecosystem if you prefer not to buy Theragun/Hyperice",
      "Useful home unit when Mini-class guns feel too light",
    ],
    weaknesses: [
      "Fewer retail demo points than big two brands",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 77,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-timtam-power-massager-v3.7",
      "TimTam Power Massager V3.7 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-opove-m3-pro",
      "prod-theragun-prime",
      "prod-hypervolt-2",
    ],
    alternativeProductIds: [
      "prod-opove-m3-pro",
      "prod-theragun-prime",
      "prod-hypervolt-2",
    ],
    ...pub,
  },

  // ─── Foam rollers ────────────────────────────────────────────────────────
  {
    id: "prod-triggerpoint-grid-x",
    slug: "triggerpoint-grid-x",
    brandId: "brand-triggerpoint",
    familyId: "fam-triggerpoint-grid",
    generation: "GRID X",
    name: "GRID X",
    fullName: "TriggerPoint GRID X Foam Roller",
    shortDescription:
      "Firmer GRID-pattern roller for runners who want denser post-run soft-tissue work than the original GRID — home mobility staple, not a healing device.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-recovery-runs",
    ],
    specifications: {
      type: "foam-roller",
      weight: null,
      portable: false,
      length: 33,
      diameter: 14,
      density: "firm",
      surface: "textured",
      material: "EVA foam / EVA + polypropylene core",
    },
    strengths: [
      "Firmer than standard GRID for athletes who outgrew soft rollers",
      "Same hollow-core durability pattern as GRID",
      "Clear density step without changing brand ecosystem",
    ],
    weaknesses: [
      "Too aggressive for beginners or sensitive tissue days",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 82,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-grid-x",
      "TriggerPoint GRID X Foam Roller — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid",
      "prod-triggerpoint-grid-travel",
      "prod-rumbleroller-original",
      "prod-triggerpoint-mbx",
    ],
    alternativeProductIds: [
      "prod-triggerpoint-grid",
      "prod-rumbleroller-original",
      "prod-blackroll-pro",
    ],
    ...pub,
  },
  {
    id: "prod-triggerpoint-grid-travel",
    slug: "triggerpoint-grid-travel",
    brandId: "brand-triggerpoint",
    familyId: "fam-triggerpoint-grid",
    generation: "GRID 13\" / Travel",
    name: "GRID Travel",
    fullName: "TriggerPoint GRID Foam Roller 13\"",
    shortDescription:
      "Shorter GRID-length roller that packs easier than the full GRID — designed for travel and race-weekend soft-tissue routines without claiming medical benefits.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: [
      "uc-travel-recovery",
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-comfort",
    ],
    specifications: {
      type: "foam-roller",
      weight: null,
      portable: true,
      length: 33,
      diameter: 14,
      density: "multi-density",
      surface: "textured",
      material: "EVA foam / polypropylene core",
      sizeClass: "travel",
    },
    strengths: [
      "Packs into race bags better than 26\" rollers",
      "Same GRID surface language athletes already know",
      "Solid travel alternative when Morph price feels high",
    ],
    weaknesses: [
      "Less coverage per pass than full-length rollers",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 80,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-grid-travel",
      "TriggerPoint GRID Foam Roller 13\" — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid",
      "prod-brazyn-morph",
      "prod-triggerpoint-grid-x",
      "prod-theragun-mini",
    ],
    alternativeProductIds: [
      "prod-brazyn-morph",
      "prod-triggerpoint-grid",
      "prod-triggerpoint-mb1",
    ],
    ...pub,
  },
  {
    id: "prod-rumbleroller-original",
    slug: "rumbleroller-original",
    brandId: "brand-rumbleroller",
    familyId: "fam-rumbleroller",
    generation: "Original",
    name: "RumbleRoller",
    fullName: "RumbleRoller Original",
    shortDescription:
      "Ridged foam roller for aggressive self-massage after hard training — intense surface texture for soft-tissue work; start gently and skip injured areas.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "foam-roller",
      weight: null,
      portable: false,
      length: null,
      diameter: null,
      density: "firm",
      surface: "ridged",
      material: "High-density foam",
    },
    strengths: [
      "Distinct ridged surface vs smooth GRID-style rollers",
      "Durable home roller for athletes who like aggressive texture",
      "Long-standing option in runner mobility kits",
    ],
    weaknesses: [
      "Too intense for many beginners and recovery-run days",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 78,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-rumbleroller-original",
      "RumbleRoller Original — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid-x",
      "prod-triggerpoint-grid",
      "prod-blackroll-pro",
    ],
    alternativeProductIds: [
      "prod-triggerpoint-grid-x",
      "prod-blackroll-pro",
      "prod-triggerpoint-mbx",
    ],
    ...pub,
  },
  {
    id: "prod-brazyn-morph",
    slug: "brazyn-morph",
    brandId: "brand-brazyn",
    familyId: "fam-brazyn-morph",
    generation: "Morph",
    name: "Morph",
    fullName: "Brazyn Morph Collapsible Foam Roller",
    shortDescription:
      "Collapsible foam roller designed for travel recovery kits — packs down when you need soft-tissue work on the road without a full-length tube in the suitcase.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: [
      "uc-travel-recovery",
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "foam-roller",
      weight: null,
      portable: true,
      length: null,
      diameter: null,
      density: "medium",
      surface: "smooth",
      material: "Collapsible foam segments",
      sizeClass: "travel",
    },
    strengths: [
      "Best-in-class packability among full-diameter rollers",
      "Useful race-weekend alternative to skipping roller work",
      "Still usable at home when expanded",
    ],
    weaknesses: [
      "Premium price vs a fixed GRID Travel",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 81,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-brazyn-morph",
      "Brazyn Morph Collapsible Foam Roller — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid-travel",
      "prod-theragun-mini",
      "prod-normatec-go",
    ],
    alternativeProductIds: [
      "prod-triggerpoint-grid-travel",
      "prod-triggerpoint-mb1",
      "prod-rad-atom",
    ],
    ...pub,
  },
  {
    id: "prod-blackroll-pro",
    slug: "blackroll-pro",
    brandId: "brand-blackroll",
    familyId: "fam-blackroll",
    generation: "PRO",
    name: "BLACKROLL PRO",
    fullName: "BLACKROLL PRO Foam Roller",
    shortDescription:
      "Firm BLACKROLL foam roller for home post-run soft-tissue routines — denser than the Standard (already in fitness catalog); practical mobility tool, not clinical care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-foam-rollers"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "foam-roller",
      weight: null,
      portable: false,
      length: 30,
      diameter: 15,
      density: "firm",
      surface: "smooth",
      material: "BLACKROLL foam",
    },
    strengths: [
      "Firm density for athletes who find Standard too soft",
      "Simple durable European roller staple",
      "Pairs with BLACKROLL balls already in broader catalog",
    ],
    weaknesses: [
      "Bulky for travel vs Morph / GRID Travel",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 79,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-blackroll-pro",
      "BLACKROLL PRO Foam Roller — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid-x",
      "prod-rumbleroller-original",
      "prod-triggerpoint-grid",
    ],
    alternativeProductIds: [
      "prod-triggerpoint-grid-x",
      "prod-triggerpoint-grid",
      "prod-rumbleroller-original",
    ],
    ...pub,
  },

  // ─── Massage balls ───────────────────────────────────────────────────────
  {
    id: "prod-triggerpoint-mb1",
    slug: "triggerpoint-mb1",
    brandId: "brand-triggerpoint",
    familyId: "fam-triggerpoint-mb",
    generation: "MB1",
    name: "MB1",
    fullName: "TriggerPoint MB1 Massage Ball",
    shortDescription:
      "Soft massage ball for targeted foot and hip soft-tissue work after runs — portable comfort aid for spots a roller cannot reach.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-balls"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-home-recovery",
      "uc-comfort",
    ],
    specifications: {
      type: "massage-ball",
      weight: null,
      portable: true,
      diameter: null,
      density: "soft",
      surface: "textured",
      material: "Foam",
      sizeClass: "mini",
    },
    strengths: [
      "Gentle entry ball for feet and glutes",
      "Tiny pack size for travel recovery kits",
      "Complements GRID rollers without extra bulk",
    ],
    weaknesses: [
      "Too soft for athletes wanting firmer focal pressure",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 80,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-mb1",
      "TriggerPoint MB1 Massage Ball — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-mbx",
      "prod-triggerpoint-grid",
      "prod-rad-atom",
    ],
    alternativeProductIds: ["prod-triggerpoint-mbx", "prod-rad-atom"],
    ...pub,
  },
  {
    id: "prod-triggerpoint-mbx",
    slug: "triggerpoint-mbx",
    brandId: "brand-triggerpoint",
    familyId: "fam-triggerpoint-mb",
    generation: "MBX",
    name: "MBX",
    fullName: "TriggerPoint MBX Massage Ball",
    shortDescription:
      "Firmer TriggerPoint massage ball for deeper focal soft-tissue work on hips, calves and arches — use carefully; not for injured tissue.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-balls"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
      "uc-travel-recovery",
    ],
    specifications: {
      type: "massage-ball",
      weight: null,
      portable: true,
      diameter: null,
      density: "firm",
      surface: "textured",
      material: "Foam",
      sizeClass: "mini",
    },
    strengths: [
      "Firmer than MB1 for experienced roller athletes",
      "Still packable for race travel",
      "Same brand language as GRID / MB1 kits",
    ],
    weaknesses: [
      "Can feel too sharp for beginners",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 81,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-mbx",
      "TriggerPoint MBX Massage Ball — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-mb1",
      "prod-rad-atom",
      "prod-triggerpoint-grid-x",
    ],
    alternativeProductIds: ["prod-rad-atom", "prod-triggerpoint-mb1"],
    ...pub,
  },
  {
    id: "prod-rad-atom",
    slug: "rad-atom",
    brandId: "brand-rad",
    familyId: "fam-rad-atom",
    generation: "Atom",
    name: "Atom",
    fullName: "RAD Atom",
    shortDescription:
      "Small hard RAD massage ball for precise soft-tissue spots — highly portable post-run comfort tool for feet and hips when a roller is too broad.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-massage-balls"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "massage-ball",
      weight: null,
      portable: true,
      diameter: null,
      density: "firm",
      surface: "smooth",
      material: "High-density polymer",
      sizeClass: "mini",
    },
    strengths: [
      "Tiny and durable for every race bag",
      "Precise pressure vs larger soft balls",
      "Strong RAD ecosystem if you already use RAD tools",
    ],
    weaknesses: [
      "Hard surface can be intense — ease in",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 79,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-rad-atom",
      "RAD Atom — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-mbx",
      "prod-triggerpoint-mb1",
      "prod-the-stick",
    ],
    alternativeProductIds: ["prod-triggerpoint-mbx", "prod-triggerpoint-mb1"],
    ...pub,
  },

  // ─── Compression boots ───────────────────────────────────────────────────
  {
    id: "prod-normatec-3",
    slug: "hyperice-normatec-3",
    brandId: "brand-hyperice",
    familyId: "fam-normatec",
    generation: "3",
    name: "Normatec 3",
    fullName: "Hyperice Normatec 3",
    shortDescription:
      "Full-leg pneumatic compression boots for home recovery routines after hard sessions — manufacturer markets recovery benefits; Kitletics frames them as comfort/routine tools, not medical devices.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-compression"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-boots"],
    useCaseIds: [
      "uc-home-recovery",
      "uc-post-run-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "compression-boot",
      weight: null,
      battery: "Control unit rechargeable (verify claim)",
      portable: false,
      zones: "7-zone leg attachments (manufacturer claim)",
      pressureSettings: "Multiple Level / Zone Boost (manufacturer claim)",
      bootSizes: "Standard / tall options (verify chart)",
      sizeClass: "full-size",
    },
    strengths: [
      "Hands-free full-leg routine while you sit after long runs",
      "Mature Hyperice ecosystem with app controls (mfr feature)",
      "Clear home-setup pick vs portable Go calves-only",
    ],
    weaknesses: [
      "Expensive and not travel-friendly",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 80,
    valueScore: 62,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-normatec-3",
      "Hyperice Normatec 3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-normatec-go",
      "prod-therabody-recoveryair",
      "prod-hypervolt-2",
    ],
    alternativeProductIds: [
      "prod-therabody-recoveryair",
      "prod-normatec-go",
    ],
    ...pub,
  },
  {
    id: "prod-normatec-go",
    slug: "hyperice-normatec-go",
    brandId: "brand-hyperice",
    familyId: "fam-normatec",
    generation: "Go",
    name: "Normatec Go",
    fullName: "Hyperice Normatec Go",
    shortDescription:
      "Portable calf-focused pneumatic compression sleeves for travel and hotel recovery routines — manufacturer recovery claims exist; treat as a comfort aid on race weekends.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-compression"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-boots"],
    useCaseIds: [
      "uc-travel-recovery",
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "compression-boot",
      weight: null,
      battery: "Integrated rechargeable (manufacturer claim)",
      portable: true,
      zones: "Calf-focused segmented compression",
      pressureSettings: "Multiple levels (manufacturer claim)",
      bootSizes: "One-size-class with fit range (verify)",
      sizeClass: "travel",
    },
    strengths: [
      "Actually fits in a race bag unlike full Normatec 3",
      "Targets calves — a common runner soft-tissue focus",
      "Battery-powered without a separate bulky control unit",
    ],
    weaknesses: [
      "Calves only — not full-leg coverage",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 78,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-normatec-go",
      "Hyperice Normatec Go — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-normatec-3",
      "prod-brazyn-morph",
      "prod-theragun-mini",
      "prod-therabody-recoveryair",
    ],
    alternativeProductIds: [
      "prod-normatec-3",
      "prod-cep-the-run-calf",
      "prod-compressport-r2",
    ],
    ...pub,
  },
  {
    id: "prod-therabody-recoveryair",
    slug: "therabody-recoveryair",
    brandId: "brand-therabody",
    familyId: "fam-therabody-recoveryair",
    generation: "RecoveryAir / JetBoots",
    name: "RecoveryAir",
    fullName: "Therabody RecoveryAir",
    shortDescription:
      "Therabody pneumatic compression boots (RecoveryAir / JetBoots class) for home post-session comfort routines — manufacturer markets recovery; Kitletics does not treat them as medical care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-compression"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-boots"],
    useCaseIds: [
      "uc-home-recovery",
      "uc-post-run-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "compression-boot",
      weight: null,
      battery: "Control unit / JetBoots integrated (verify SKU)",
      portable: false,
      zones: "Multi-chamber leg boots (manufacturer claim)",
      pressureSettings: "Multiple TruGrade / sequential settings (mfr)",
      bootSizes: "Sized boots (verify chart)",
      sizeClass: "full-size",
    },
    strengths: [
      "Therabody alternative if you already own Theragun gear",
      "Full-leg home routine after long runs",
      "JetBoots variants reduce hose clutter (SKU-dependent)",
    ],
    weaknesses: [
      "Premium price and storage footprint",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 79,
    valueScore: 64,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-therabody-recoveryair",
      "Therabody RecoveryAir — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-normatec-3",
      "prod-theragun-pro",
      "prod-theragun-prime",
    ],
    alternativeProductIds: ["prod-normatec-3", "prod-normatec-go"],
    ...pub,
  },

  // ─── Recovery sandals ────────────────────────────────────────────────────
  {
    id: "prod-oofos-oolala",
    slug: "oofos-oolala",
    brandId: "brand-oofos",
    familyId: "fam-oofos",
    generation: "OOlala",
    name: "OOlala",
    fullName: "OOFOS OOlala",
    shortDescription:
      "Thong-style OOfoam recovery sandal for cushioned walking after hard sessions — comfort footwear for easy days, not a running shoe or treatment.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-recovery-sandals"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-comfort",
      "uc-high-mileage",
      "uc-recovery-runs",
    ],
    specifications: {
      type: "recovery-sandal",
      weight: null,
      portable: true,
      cushionLevel: "high",
      material: "OOfoam",
      genderFit: "women",
      sizeClass: "compact",
    },
    strengths: [
      "High OOfoam cushion for post-run walking",
      "Thong silhouette for warm-weather recovery days",
      "Machine-washable foam like other OOFOS",
    ],
    weaknesses: [
      "Not for running or technical trails",
      "Thong fit is polarizing vs slides",
    ],
    recommendationScore: 76,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-oofos-oolala",
      "OOFOS OOlala — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oocandoo",
      "prod-hoka-ora-recovery-slide",
    ],
    alternativeProductIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oocandoo",
      "prod-hoka-ora-recovery-slide",
    ],
    ...pub,
  },
  {
    id: "prod-oofos-oocandoo",
    slug: "oofos-oocandoo",
    brandId: "brand-oofos",
    familyId: "fam-oofos",
    generation: "OOcandoo",
    name: "OOcandoo",
    fullName: "OOFOS OOcandoo",
    shortDescription:
      "Active OOfoam recovery slide with more coverage than OOriginal — cushioned walking after hard sessions when you want a secure slide fit.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-recovery-sandals"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-comfort",
      "uc-high-mileage",
      "uc-travel-recovery",
    ],
    specifications: {
      type: "recovery-sandal",
      weight: null,
      portable: true,
      cushionLevel: "high",
      material: "OOfoam",
      genderFit: "unisex",
      sizeClass: "compact",
    },
    strengths: [
      "More secure upper than classic OOriginal thong",
      "Same soft post-run walking cushion philosophy",
      "Easy throw-on after long runs or races",
    ],
    weaknesses: [
      "Still not a training shoe",
      "Fit runs brand-specific — try before racing in them",
    ],
    recommendationScore: 78,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-oofos-oocandoo",
      "OOFOS OOcandoo — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oolala",
      "prod-hoka-ora-recovery-slide",
    ],
    alternativeProductIds: [
      "prod-oofos-ooriginal",
      "prod-hoka-ora-recovery-slide",
    ],
    ...pub,
  },
  {
    id: "prod-hoka-ora-recovery-slide",
    slug: "hoka-ora-recovery-slide",
    brandId: "brand-hoka",
    familyId: "fam-hoka-ora",
    generation: "Ora Recovery Slide",
    name: "Ora Recovery Slide",
    fullName: "HOKA Ora Recovery Slide",
    shortDescription:
      "Max-cushion HOKA recovery slide for easy walking after hard sessions — plush everyday comfort when you want a brand peer to OOFOS.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-recovery-sandals"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-comfort",
      "uc-high-mileage",
      "uc-recovery-runs",
    ],
    specifications: {
      type: "recovery-sandal",
      weight: null,
      portable: true,
      cushionLevel: "maximum",
      material: "Compression-molded EVA",
      genderFit: "unisex",
      sizeClass: "compact",
    },
    strengths: [
      "Very plush HOKA cushion for post-run walking",
      "Secure slide strap vs open thongs",
      "Natural pick if you already wear HOKA trainers",
    ],
    weaknesses: [
      "Bulkier than OOriginal for packing",
      "Not a substitute for rest or medical care; not for running",
    ],
    recommendationScore: 80,
    valueScore: 76,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-hoka-ora-recovery-slide",
      "HOKA Ora Recovery Slide — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oocandoo",
      "prod-oofos-oolala",
    ],
    alternativeProductIds: [
      "prod-oofos-ooriginal",
      "prod-oofos-oocandoo",
    ],
    ...pub,
  },

  // ─── Compression garments ────────────────────────────────────────────────
  {
    id: "prod-cep-the-run-calf",
    slug: "cep-the-run-calf-sleeves",
    brandId: "brand-cep",
    familyId: "fam-cep-calf",
    generation: "The Run",
    name: "The Run Calf Sleeves",
    fullName: "CEP The Run Calf Sleeves",
    shortDescription:
      "Graduated compression calf sleeves for long-run and high-mileage comfort routines — manufacturer compression claims exist; Kitletics treats them as supportive apparel, not injury prevention. (Distinct from gear-wave1 prod-cep-calf-sleeves 3.0.)",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-compression", "disc-running-road"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-garments"],
    useCaseIds: [
      "uc-high-mileage",
      "uc-post-run-recovery",
      "uc-comfort",
      "uc-travel-recovery",
    ],
    specifications: {
      type: "compression-garment",
      weight: null,
      portable: true,
      material: "Polyamide / elastane (verify current)",
      genderFit: "unisex",
      bootSizes: "Sized by calf circumference (verify chart)",
    },
    strengths: [
      "Pairs with any sock height for long-run comfort routines",
      "Packs tiny for travel",
      "Familiar CEP graduated compression patterning",
    ],
    weaknesses: [
      "Must size carefully — wrong fit feels useless or too tight",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 76,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-cep-the-run-calf",
      "CEP The Run Calf Sleeves — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-compressport-r2",
      "prod-2xu-refresh-recovery",
      "prod-cep-calf-sleeves",
    ],
    alternativeProductIds: [
      "prod-compressport-r2",
      "prod-cep-calf-sleeves",
      "prod-2xu-refresh-recovery",
    ],
    ...pub,
  },
  {
    id: "prod-compressport-r2",
    slug: "compressport-r2",
    brandId: "brand-compressport",
    familyId: "fam-compressport-r2",
    generation: "R2",
    name: "R2",
    fullName: "Compressport R2 Calf Sleeves",
    shortDescription:
      "Compressport R2 calf sleeves for training and post-run comfort wear — light, packable compression apparel; not marketed here as injury treatment.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-compression", "disc-running-road", "disc-running-trail"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-garments"],
    useCaseIds: [
      "uc-high-mileage",
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-comfort",
    ],
    specifications: {
      type: "compression-garment",
      weight: null,
      portable: true,
      material: "Compressport knit (verify current)",
      genderFit: "unisex",
      bootSizes: "Sized by calf (verify chart)",
    },
    strengths: [
      "Trail- and road-friendly light calf sleeve",
      "Tiny travel footprint",
      "Strong Compressport race-kit brand familiarity",
    ],
    weaknesses: [
      "Compression feel is brand-specific vs CEP",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 77,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-compressport-r2",
      "Compressport R2 Calf Sleeves — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-cep-the-run-calf",
      "prod-2xu-refresh-recovery",
      "prod-normatec-go",
    ],
    alternativeProductIds: [
      "prod-cep-the-run-calf",
      "prod-cep-calf-sleeves",
    ],
    ...pub,
  },
  {
    id: "prod-2xu-refresh-recovery",
    slug: "2xu-refresh-recovery-tights",
    brandId: "brand-2xu",
    familyId: "fam-2xu-refresh",
    generation: "Refresh Recovery",
    name: "Refresh Recovery Tights",
    fullName: "2XU Refresh Recovery Tights",
    shortDescription:
      "2XU recovery-line compression tights for easy post-run lounging and travel days — comfort garment with graduated compression patterning; not clinical care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery"],
    disciplineIds: ["disc-recovery-compression"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-compression-garments"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-home-recovery",
      "uc-comfort",
      "uc-high-mileage",
    ],
    specifications: {
      type: "compression-garment",
      weight: null,
      portable: true,
      material: "PWX-class compression fabric (verify current)",
      genderFit: "unisex",
      bootSizes: "Sized apparel range (verify chart)",
    },
    strengths: [
      "Full-leg coverage vs calf sleeves alone",
      "Useful plane/hotel comfort layer after races",
      "Clear recovery-line positioning (mfr) without race-sock clutter",
    ],
    weaknesses: [
      "Warm in hot weather; sizing must be precise",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 75,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-2xu-refresh-recovery",
      "2XU Refresh Recovery Tights — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-cep-the-run-calf",
      "prod-compressport-r2",
      "prod-oofos-ooriginal",
    ],
    alternativeProductIds: [
      "prod-cep-the-run-calf",
      "prod-compressport-r2",
    ],
    ...pub,
  },

  // ─── Mobility tools ──────────────────────────────────────────────────────
  {
    id: "prod-the-stick",
    slug: "the-stick",
    brandId: "brand-the-stick",
    familyId: "fam-the-stick",
    generation: "Original",
    name: "The Stick",
    fullName: "The Stick",
    shortDescription:
      "Handheld stick roller for quick soft-tissue passes on calves and quads — portable mobility tool for post-run comfort routines without electricity.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-mobility-tools"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-travel-recovery",
      "uc-home-recovery",
      "uc-high-mileage",
    ],
    specifications: {
      type: "mobility-tool",
      weight: null,
      portable: true,
      length: null,
      material: "Flexible stick with spindles",
      sizeClass: "travel",
    },
    strengths: [
      "No battery — always ready in a race bag",
      "Fast calf/quad passes while standing",
      "Classic runner mobility staple",
    ],
    weaknesses: [
      "Less precise than a massage ball on tiny spots",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 82,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-the-stick",
      "The Stick — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-stp",
      "prod-triggerpoint-mb1",
      "prod-rad-atom",
    ],
    alternativeProductIds: ["prod-triggerpoint-stp", "prod-triggerpoint-mbx"],
    ...pub,
  },
  {
    id: "prod-triggerpoint-stp",
    slug: "triggerpoint-stp",
    brandId: "brand-triggerpoint",
    familyId: "fam-triggerpoint-stp",
    generation: "STP",
    name: "STP",
    fullName: "TriggerPoint STP Massage Stick",
    shortDescription:
      "TriggerPoint massage stick for self-guided soft-tissue passes — designed for post-run mobility routines; complements GRID rollers and MB balls.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-mobility-tools"],
    useCaseIds: [
      "uc-post-run-recovery",
      "uc-home-recovery",
      "uc-travel-recovery",
      "uc-comfort",
    ],
    specifications: {
      type: "mobility-tool",
      weight: null,
      portable: true,
      length: null,
      material: "Stick with contoured rollers",
      density: "medium",
      sizeClass: "travel",
    },
    strengths: [
      "Stays in the TriggerPoint ecosystem with GRID / MB",
      "Good standing calf work without getting on the floor",
      "Packable vs full foam rollers",
    ],
    weaknesses: [
      "Another stick option if you already own The Stick",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 78,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-triggerpoint-stp",
      "TriggerPoint STP Massage Stick — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-the-stick",
      "prod-triggerpoint-grid",
      "prod-triggerpoint-mb1",
    ],
    alternativeProductIds: ["prod-the-stick", "prod-rad-atom"],
    ...pub,
  },
  {
    id: "prod-hyperice-vyper-3",
    slug: "hyperice-vyper-3",
    brandId: "brand-hyperice",
    familyId: "fam-hyperice-vyper",
    generation: "3",
    name: "Vyper 3",
    fullName: "Hyperice Vyper 3",
    shortDescription:
      "Vibrating foam roller for home mobility sessions — manufacturer markets vibration recovery benefits; Kitletics rates it as a powered soft-tissue comfort tool, not medical care.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-recovery", "sport-training"],
    disciplineIds: ["disc-recovery-mobility"],
    categoryId: "cat-recovery-gear",
    subcategoryIds: ["sub-rec-mobility-tools"],
    useCaseIds: [
      "uc-home-recovery",
      "uc-post-run-recovery",
      "uc-high-mileage",
      "uc-comfort",
    ],
    specifications: {
      type: "mobility-tool",
      weight: null,
      battery: "Rechargeable (manufacturer claim)",
      portable: false,
      length: null,
      diameter: null,
      density: "medium",
      surface: "smooth",
      material: "Vibrating roller shell",
      speeds: "3 vibration speeds (manufacturer claim)",
      sizeClass: "full-size",
    },
    strengths: [
      "Powered vibration adds a different feel vs static rollers",
      "Fits Hyperice home stacks with Hypervolt / Normatec",
      "Useful when you prefer less bodyweight pressure",
    ],
    weaknesses: [
      "Needs charging; bulkier than The Stick for travel",
      "Not a substitute for rest, load management or medical care",
    ],
    recommendationScore: 77,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-recovery-gear",
      "prod-hyperice-vyper-3",
      "Hyperice Vyper 3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-triggerpoint-grid",
      "prod-hypervolt-2",
      "prod-the-stick",
      "prod-brazyn-morph",
    ],
    alternativeProductIds: [
      "prod-triggerpoint-grid",
      "prod-the-stick",
      "prod-brazyn-morph",
    ],
    ...pub,
  },
];

/** All wave-2 recovery SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningRecoveryWave2Raw.map((p) => p.id),
);

export const runningRecoveryWave2: Product[] = applyMediaPublishGate(runningRecoveryWave2Raw, MEDIA_PENDING_DRAFT_IDS);
