import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 Running Safety / Visibility catalog.
 *
 * Expands beyond gear-wave1 seeds (prod-nathan-reflective-vest, prod-nite-ize-radiant-clip).
 * Personal alarms only — no pepper spray, stun guns, knives, or regulated weapons.
 *
 * NOT wired into products.ts aggregators yet (parent will wire).
 * NOTE: Best Safety / Visibility buying guide will be added by parent.
 */
export const runningSafetyWave2Raw: Product[] = [
  // ─── Visibility vests / sashes ───────────────────────────────────────────
  {
    id: "prod-amphipod-xinglet",
    slug: "amphipod-xinglet",
    brandId: "brand-amphipod",
    familyId: "fam-amphipod-xinglet",
    generation: "Xinglet",
    name: "Xinglet",
    fullName: "Amphipod Xinglet Reflective Sash",
    shortDescription:
      "Cross-body reflective sash with 360° coverage and LED clip pads — lighter than a full vest for night road miles when you want bounce-free passive visibility you can throw over any kit.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-visibility-vests", "sub-safety-reflective"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "reflective-vest",
      weight: null,
      reflective: true,
      illuminated: false,
      rechargeable: false,
      waterResistance: "none",
    },
    strengths: [
      "360° high-brilliance reflective coverage in a soft sash cut",
      "Front/rear pads ready for Vizlet or clip LEDs",
      "SwiftClip on/off over jackets without a bulky vest feel",
    ],
    weaknesses: [
      "Passive only until you add active LEDs",
      "Less coverage than a full Reflect360-style vest",
    ],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-amphipod-xinglet",
      "Amphipod Xinglet Reflective Sash — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-vizlet",
      "prod-amphipod-xinglet-optic-beam",
      "prod-nathan-reflective-vest",
      "prod-proviz-reflect360-vest",
    ],
    alternativeProductIds: [
      "prod-nathan-reflective-vest",
      "prod-proviz-reflect360-vest",
      "prod-amphipod-xinglet-optic-beam",
    ],
    ...pub,
  },
  {
    id: "prod-amphipod-xinglet-optic-beam",
    slug: "amphipod-xinglet-optic-beam",
    brandId: "brand-amphipod",
    familyId: "fam-amphipod-xinglet",
    generation: "Optic Beam",
    name: "Xinglet Optic Beam",
    fullName: "Amphipod Xinglet Optic Beam Rechargeable Vest",
    shortDescription:
      "Xinglet silhouette with built-in rechargeable LED tubing — active 360° glow plus reflectivity when passive sash coverage alone is not enough for dark roads.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-visibility-vests", "sub-safety-wearable-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training"],
    specifications: {
      type: "reflective-vest",
      weight: null,
      reflective: true,
      illuminated: true,
      rechargeable: true,
      lightModes: "Solid, flash, and intermediate LED modes (manufacturer claim)",
      runtime: "Up to ~5 hrs flash / ~3 hrs solid (manufacturer claim)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Active LED + reflective coverage in one throw-on vest",
      "USB rechargeable — no coin cells for the main light path",
      "Stronger night-road signal than passive Xinglet alone",
    ],
    weaknesses: [
      "Heavier / warmer than a passive sash on mild nights",
      "Battery management required before multi-hour winter blocks",
    ],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-amphipod-xinglet-optic-beam",
      "Amphipod Xinglet Optic Beam — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-xinglet",
      "prod-amphipod-vizlet",
      "prod-proviz-reflect360-vest",
      "prod-nathan-lightbender",
    ],
    alternativeProductIds: [
      "prod-amphipod-xinglet",
      "prod-proviz-reflect360-vest",
      "prod-nathan-reflective-vest",
    ],
    ...pub,
  },
  {
    id: "prod-amphipod-vizlet",
    slug: "amphipod-vizlet-led",
    brandId: "brand-amphipod",
    familyId: "fam-amphipod-vizlet",
    generation: "Vizlet LED",
    name: "Vizlet LED",
    fullName: "Amphipod Vizlet LED Reflector",
    shortDescription:
      "Magnet-clip reflective discs with integrated flashing LED — add active points of light to a Xinglet, belt, cap, or shirt without buying a full illuminated vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-clip-lights", "sub-safety-reflective"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "clip-light",
      weight: null,
      reflective: true,
      illuminated: true,
      rechargeable: false,
      lightModes: "One-touch flashing LED",
      runtime: "CR2032 coin cell (replaceable)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Dual-magnet attach to fabric, belts and Xinglet pads",
      "Reflective body plus active flash in a tiny package",
      "Cheap way to stack multiple light points",
    ],
    weaknesses: [
      "Coin-cell maintenance vs USB-rechargeable peers",
      "Not a primary path light — visibility marker only",
    ],
    recommendationScore: 80,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-amphipod-vizlet",
      "Amphipod Vizlet LED — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amphipod-xinglet",
      "prod-nite-ize-radiant-clip",
      "prod-nathan-strobe",
      "prod-knog-frog-v3",
    ],
    alternativeProductIds: [
      "prod-nite-ize-radiant-clip",
      "prod-nathan-strobe",
      "prod-knog-frog-v3",
    ],
    ...pub,
  },
  {
    id: "prod-proviz-reflect360-vest",
    slug: "proviz-reflect360-running-vest",
    brandId: "brand-proviz",
    familyId: "fam-proviz-reflect360",
    generation: "Reflect360",
    name: "Reflect360 Running Vest",
    fullName: "Proviz Reflect360 Running Vest",
    shortDescription:
      "Full reflective running vest that lights up under headlights — UK hi-vis specialist coverage for dark commute and winter road blocks when a sash feels too minimal.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-visibility-vests", "sub-safety-reflective"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "reflective-vest",
      weight: null,
      reflective: true,
      illuminated: false,
      rechargeable: false,
      waterResistance: "water-resistant",
    },
    strengths: [
      "High-coverage Reflect360 material under vehicle lights",
      "Open vest cut works over jackets and layers",
      "Strong winter/commute default vs thin sashes",
    ],
    weaknesses: [
      "Passive only — pair with clip or wearable LEDs for unlit roads",
      "Bulkier than Xinglet for short mild-night jogs",
    ],
    recommendationScore: 86,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-proviz-reflect360-vest",
      "Proviz Reflect360 Running Vest — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-reflective-vest",
      "prod-amphipod-xinglet",
      "prod-amphipod-xinglet-optic-beam",
      "prod-nathan-lightbender",
    ],
    alternativeProductIds: [
      "prod-nathan-reflective-vest",
      "prod-amphipod-xinglet",
      "prod-amphipod-xinglet-optic-beam",
    ],
    ...pub,
  },

  // ─── Clip / wearable lights ──────────────────────────────────────────────
  {
    id: "prod-knog-frog-v3",
    slug: "knog-frog-v3",
    brandId: "brand-knog",
    familyId: "fam-knog-frog",
    generation: "V3",
    name: "Frog V3",
    fullName: "Knog Frog V3 Twin Pack",
    shortDescription:
      "USB-C rechargeable Frog V3 front/rear pair — silicone-strap clip lights runners and bike-commuters use as compact active markers on packs, belts and bars.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-commute"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-clip-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training", "uc-winter-running"],
    specifications: {
      type: "clip-light",
      weight: 40,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "9 modes (steady, flash, side patterns)",
      runtime: "Up to ~80 hrs front / ~60 hrs rear eco modes (manufacturer claim)",
      waterResistance: "waterproof",
    },
    strengths: [
      "Front+rear twin pack covers two body points out of the box",
      "Flexible silicone mount clips to gear without tools",
      "IP65 and long eco runtimes for frequent winter use",
    ],
    weaknesses: [
      "Bike-first design — not a path-illuminating headlamp",
      "USB-C cable usually sold separately",
    ],
    recommendationScore: 85,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-knog-frog-v3",
      "Knog Frog V3 Twin Pack — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-knog-cobber-mid",
      "prod-nite-ize-radiant-clip",
      "prod-nathan-strobe",
      "prod-amphipod-vizlet",
    ],
    alternativeProductIds: [
      "prod-nite-ize-radiant-clip",
      "prod-nathan-strobe",
      "prod-knog-cobber-mid",
    ],
    ...pub,
  },
  {
    id: "prod-knog-cobber-mid",
    slug: "knog-cobber-mid",
    brandId: "brand-knog",
    familyId: "fam-knog-cobber",
    generation: "Mid",
    name: "Cobber Mid",
    fullName: "Knog Cobber Mid",
    shortDescription:
      "Wide-angle Cobber Mid COB light with silicone strap mount — brighter wearable/clip visibility marker for commute and night-road runners who want more punch than Frog.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-commute"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-wearable-lights", "sub-safety-clip-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running"],
    specifications: {
      type: "wearable-light",
      weight: null,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "Multiple steady and flash modes (ModeMaker programmable on some units)",
      runtime: "Mode-dependent (manufacturer claim — verify SKU)",
      waterResistance: "waterproof",
    },
    strengths: [
      "Wide side-visibility COB beam for traffic approaches",
      "Tool-free silicone strap for packs, belts or bike mounts",
      "Step up in output vs Frog for darker commute corridors",
    ],
    weaknesses: [
      "Bulkier than Frog / Lux Strobe for minimalist runners",
      "Primarily bike-oriented — overkill for short lit-neighborhood jogs",
    ],
    recommendationScore: 83,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-knog-cobber-mid",
      "Knog Cobber Mid — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-knog-frog-v3",
      "prod-nathan-lightbender",
      "prod-nightrunner-270",
      "prod-nite-ize-radiant-clip",
    ],
    alternativeProductIds: [
      "prod-knog-frog-v3",
      "prod-nathan-lightbender",
      "prod-nightrunner-270",
    ],
    ...pub,
  },
  {
    id: "prod-nightrunner-270",
    slug: "night-runner-270",
    brandId: "brand-nightrunner",
    familyId: "fam-night-runner-270",
    generation: "270",
    name: "Night Runner 270",
    fullName: "Night Runner 270 Shoe Lights",
    shortDescription:
      "Shoe-mounted LED lights that throw a ~270° ground-level glow — frees the torso from clip clutter and puts active light where drivers see footstrike first.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-wearable-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training"],
    specifications: {
      type: "wearable-light",
      weight: null,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "Multiple brightness / flash modes (manufacturer claim)",
      runtime: "Mode-dependent (manufacturer claim — verify current kit)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Shoe-level light is highly noticeable to approaching traffic",
      "Keeps chest/vest free for hydration or reflective layers",
      "Dedicated run product vs bike lights adapted to packs",
    ],
    weaknesses: [
      "Attaches to shoes — fit/clearance varies by upper and lace setup",
      "Does not replace a headlamp for unlit trail path-finding",
    ],
    recommendationScore: 82,
    valueScore: 76,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-nightrunner-270",
      "Night Runner 270 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-lightbender",
      "prod-knog-cobber-mid",
      "prod-amphipod-xinglet-optic-beam",
      "prod-nathan-strobe",
    ],
    alternativeProductIds: [
      "prod-nathan-lightbender",
      "prod-knog-frog-v3",
      "prod-amphipod-xinglet-optic-beam",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-lightbender",
    slug: "nathan-lightbender-rx",
    brandId: "brand-nathan",
    familyId: "fam-nathan-lightbender",
    generation: "RX",
    name: "LightBender RX",
    fullName: "Nathan LightBender RX Armband Light",
    shortDescription:
      "Rechargeable RGB LED armband (~6 lm) with steady/flash modes — low-profile wearable visibility for dusk road miles without a full illuminated vest.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-wearable-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "wearable-light",
      weight: 43,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "Red / green / blue × steady or flashing",
      runtime: "Steady ~8 hrs; flashing ~16 hrs (manufacturer claim)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Comfortable armband form factor with long flash runtime",
      "RGB modes help customize visibility against clothing colors",
      "IPX4 and USB recharge for wet winter training",
    ],
    weaknesses: [
      "Can chafe on bare arms — better over sleeves",
      "Marker light only — not a trail headlamp substitute",
    ],
    recommendationScore: 87,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-nathan-lightbender",
      "Nathan LightBender RX — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-strobe",
      "prod-nathan-reflective-vest",
      "prod-nightrunner-270",
      "prod-knog-cobber-mid",
    ],
    alternativeProductIds: [
      "prod-nathan-strobe",
      "prod-nightrunner-270",
      "prod-knog-frog-v3",
    ],
    ...pub,
  },
  {
    id: "prod-nathan-strobe",
    slug: "nathan-lux-strobe-rx",
    brandId: "brand-nathan",
    familyId: "fam-nathan-lux-strobe",
    generation: "Lux Strobe RX",
    name: "Lux Strobe RX",
    fullName: "Nathan Lux Strobe RX",
    shortDescription:
      "Slim USB-rechargeable RGB clip strobe (~8 lm) — stackable active marker for vest, belt, or pack when you want Nathan visibility without an armband.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-clip-lights"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training", "uc-winter-running"],
    specifications: {
      type: "clip-light",
      weight: null,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "Steady, strobe, pulse, burst, RUN; RGB color select",
      runtime: "Steady ~5+ hrs; strobe ~8+ hrs; pulse/burst/RUN ~10+ hrs (manufacturer claim)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Multiple flash patterns including RUN mode",
      "Clips anywhere — easy multi-point lighting",
      "USB rechargeable RGB peer to LightBender",
    ],
    weaknesses: [
      "Smaller visible area than armband or shoe lights",
      "Clip can snag loose fabric if poorly placed",
    ],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-nathan-strobe",
      "Nathan Lux Strobe RX — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-nathan-lightbender",
      "prod-nite-ize-radiant-clip",
      "prod-amphipod-vizlet",
      "prod-nathan-reflective-vest",
    ],
    alternativeProductIds: [
      "prod-nite-ize-radiant-clip",
      "prod-amphipod-vizlet",
      "prod-knog-frog-v3",
    ],
    ...pub,
  },

  // ─── ID / personal alarm (alarms only — no weapons) ──────────────────────
  {
    id: "prod-road-id-wrist",
    slug: "road-id-wrist-id",
    brandId: "brand-road-id",
    familyId: "fam-road-id-wrist",
    generation: "Wrist ID / Elite",
    name: "Wrist ID",
    fullName: "Road ID Wrist ID",
    shortDescription:
      "Laser-engraved wrist ID band for emergency contacts — non-electronic safety layer for solo night and commute runs when phones or watches fail.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-reflective"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training", "uc-beginners", "uc-winter-running"],
    specifications: {
      type: "id-band",
      weight: null,
      reflective: false,
      illuminated: false,
      rechargeable: false,
      waterResistance: "waterproof",
    },
    strengths: [
      "Always-on ICE info without battery or phone unlock",
      "Comfortable wrist form for daily training wear",
      "Complements lights/vests rather than replacing them",
    ],
    weaknesses: [
      "No active visibility — pair with reflective or LED gear",
      "Engraving must stay current when contacts change",
    ],
    recommendationScore: 78,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-road-id-wrist",
      "Road ID Wrist ID — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-shes-birdie-alarm",
      "prod-nathan-reflective-vest",
      "prod-flipbelt-zippered-reflective",
      "prod-nathan-lightbender",
    ],
    alternativeProductIds: ["prod-shes-birdie-alarm"],
    ...pub,
  },
  {
    id: "prod-shes-birdie-alarm",
    slug: "shes-birdie-personal-alarm",
    brandId: "brand-shes-birdie",
    familyId: "fam-shes-birdie",
    generation: "Birdie 3.0",
    name: "Birdie 3.0",
    fullName: "She's Birdie Personal Safety Alarm",
    shortDescription:
      "Legal personal safety alarm (~130 dB) with strobe — pull-activated siren for runners who want an audible deterrent without pepper spray or other regulated weapons.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-personal-alarms"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "alarm",
      weight: null,
      reflective: false,
      illuminated: true,
      rechargeable: true,
      lightModes: "Flashing strobe + separate flashlight mode",
      alarmDecibels: "~130 dB (manufacturer claim)",
      waterResistance: "water-resistant",
    },
    strengths: [
      "Loud pull-pin siren plus strobe for attention",
      "Travel-legal alarm — not a spray or stun device",
      "USB-C rechargeable Birdie 3.0 with on/off switch",
    ],
    weaknesses: [
      "Does not replace situational awareness or visibility gear",
      "Continuous alarm drain is limited — verify charge before long blocks",
    ],
    recommendationScore: 86,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-shes-birdie-alarm",
      "She's Birdie Personal Safety Alarm — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-road-id-wrist",
      "prod-nathan-lightbender",
      "prod-flipbelt-zippered-reflective",
      "prod-amphipod-xinglet",
    ],
    alternativeProductIds: ["prod-road-id-wrist"],
    ...pub,
  },

  // ─── Reflective accessory ────────────────────────────────────────────────
  {
    id: "prod-flipbelt-zippered-reflective",
    slug: "flipbelt-zipper-reflective",
    brandId: "brand-flipbelt",
    familyId: "fam-flipbelt-reflective",
    generation: "Zipper Reflective",
    name: "Zipper Reflective",
    fullName: "FlipBelt Zipper Reflective",
    shortDescription:
      "360° reflective FlipBelt with zippered valuables pocket — reflective safety accessory that doubles as bounce-free phone/key carry for night and winter road miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-safety",
    subcategoryIds: ["sub-safety-reflective"],
    useCaseIds: ["uc-night-running", "uc-commute-running", "uc-winter-running", "uc-daily-training", "uc-beginners"],
    specifications: {
      type: "reflective-accessory",
      weight: null,
      reflective: true,
      illuminated: false,
      rechargeable: false,
      waterResistance: "none",
    },
    strengths: [
      "True 360° reflective tube vs logo-only belts",
      "Zip pocket + FlipBelt carry for phone and keys",
      "Wearable safety layer that replaces a separate vest for many lit roads",
    ],
    weaknesses: [
      "Passive only — add clip LEDs for unlit corridors",
      "Still a carry belt — less coverage than Proviz Reflect360",
    ],
    recommendationScore: 83,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-safety",
      "prod-flipbelt-zippered-reflective",
      "FlipBelt Zipper Reflective — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-flipbelt-classic",
      "prod-nathan-reflective-vest",
      "prod-amphipod-xinglet",
      "prod-nathan-strobe",
    ],
    alternativeProductIds: [
      "prod-nathan-reflective-vest",
      "prod-amphipod-xinglet",
      "prod-proviz-reflect360-vest",
    ],
    ...pub,
  },
];

/** All wave-2 safety SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(runningSafetyWave2Raw.map((p) => p.id));

export const runningSafetyWave2: Product[] = applyMediaPublishGate(runningSafetyWave2Raw, MEDIA_PENDING_DRAFT_IDS);
