/**
 * Wave 3 — Fill thin running-shoe niches (trail, stability, zero-drop, road-to-trail)
 * and broaden shallow brands (Adidas, On, New Balance trail). Numeric specs stay
 * null when unverified. Merged via products.ts.
 */

import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

type Draft = {
  id: string;
  slug: string;
  brandId: string;
  name: string;
  fullName: string;
  shortDescription: string;
  generation?: string;
  subcategoryIds: string[];
  useCaseIds: string[];
  disciplineIds?: string[];
  terrain?: string[];
  cushionLevel?: string;
  cushionFeel?: string;
  stability?: string;
  rideCharacter?: string;
  plate?: boolean;
  plateMaterial?: string;
  drop?: number | null;
  weight?: number | null;
  widthOptions?: string[];
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  experienceLevels?: Product["experienceLevels"];
  relatedProductIds?: string[];
  alternativeProductIds?: string[];
};

function shoe(d: Draft): Product {
  const terrain = d.terrain ?? ["road"];
  const isTrail = terrain.includes("trail");
  return {
    id: d.id,
    slug: d.slug,
    brandId: d.brandId,
    generation: d.generation,
    name: d.name,
    fullName: d.fullName,
    shortDescription: d.shortDescription,
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds:
      d.disciplineIds ??
      (isTrail
        ? ["disc-running-trail", "disc-running-road"]
        : ["disc-running-road", "disc-running-treadmill"]),
    categoryId: "cat-running-shoes",
    subcategoryIds: d.subcategoryIds,
    useCaseIds: d.useCaseIds,
    specifications: {
      weight: d.weight ?? null,
      heelStack: null,
      forefootStack: null,
      drop: d.drop ?? null,
      cushionLevel: d.cushionLevel ?? "moderate",
      cushionFeel: d.cushionFeel ?? "balanced",
      stability: d.stability ?? "neutral",
      rideCharacter: d.rideCharacter ?? "smooth",
      energyReturn: "moderate",
      flexibility: "moderate",
      upper: null,
      midsole: null,
      outsole: null,
      plate: d.plate ?? false,
      plateMaterial: d.plateMaterial ?? "none",
      terrain,
      widthOptions: d.widthOptions ?? ["standard"],
      archSupport: "medium",
      grip: isTrail ? "trail" : "road",
      durability: "moderate",
      breathability: "moderate",
      raceLegal: true,
      recommendedPaceRange: null,
      recommendedDistance: isTrail
        ? ["daily", "trail", "ultra"]
        : ["daily", "half", "marathon"],
      recommendedRunnerWeightRange: null,
      trainingTypes: ["easy", "long"],
      surface: isTrail ? ["trail", "mixed"] : ["asphalt", "treadmill"],
      weatherSuitability: ["dry", "wet", "all-season"],
    },
    strengths: d.strengths,
    weaknesses: d.weaknesses,
    recommendationScore: d.recommendationScore,
    valueScore: d.valueScore,
    experienceLevels: d.experienceLevels ?? [
      "beginner",
      "intermediate",
      "advanced",
    ],
    images: categoryFallbackImage(
      "cat-running-shoes",
      d.id,
      `${d.fullName} — catalog placeholder`,
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: d.relatedProductIds ?? [],
    alternativeProductIds: d.alternativeProductIds ?? [],
    ...pub,
  };
}

const DRAFTS: Draft[] = [
  // ── Trail ──────────────────────────────────────────────────────────────
  {
    id: "prod-cascadia-18",
    slug: "brooks-cascadia-18",
    brandId: "brand-brooks",
    name: "Cascadia 18",
    fullName: "Brooks Cascadia 18",
    shortDescription:
      "Protective trail daily trainer with Ballistic Rock Shield and a stable trail platform for mixed dirt and rock.",
    generation: "18",
    subcategoryIds: ["sub-trail"],
    useCaseIds: ["uc-trail-training", "uc-long-runs", "uc-beginner"],
    terrain: ["trail"],
    cushionLevel: "high",
    stability: "neutral",
    drop: 8,
    strengths: ["Trail protection", "Stable mixed-terrain ride", "Durable outsole"],
    weaknesses: ["Heavier than race-trail shoes", "Not a road daily"],
    recommendationScore: 88,
    valueScore: 84,
    relatedProductIds: ["prod-speedgoat-6", "prod-peregrine-15"],
    alternativeProductIds: ["prod-sense-ride-5", "prod-lone-peak-8"],
  },
  {
    id: "prod-pegasus-trail-5",
    slug: "nike-pegasus-trail-5",
    brandId: "brand-nike",
    name: "Pegasus Trail 5",
    fullName: "Nike Pegasus Trail 5",
    shortDescription:
      "Road-to-trail Nike daily with ReactX cushioning and aggressive enough lugs for light trails.",
    generation: "5",
    subcategoryIds: ["sub-trail", "sub-road-trail", "sub-daily-trainers"],
    useCaseIds: ["uc-trail-training", "uc-daily-training", "uc-intermediate"],
    terrain: ["trail", "road"],
    cushionLevel: "moderate",
    drop: 10,
    strengths: ["Versatile road-to-trail", "Familiar Pegasus fit", "Good value"],
    weaknesses: ["Not for technical alpine mud", "Less max stack than Speedgoat"],
    recommendationScore: 86,
    valueScore: 87,
    relatedProductIds: ["prod-pegasus-42", "prod-cascadia-18"],
    alternativeProductIds: ["prod-aero-glide-2", "prod-sense-ride-5"],
  },
  {
    id: "prod-trabuco-13",
    slug: "asics-gel-trabuco-13",
    brandId: "brand-asics",
    name: "Gel-Trabuco 13",
    fullName: "ASICS Gel-Trabuco 13",
    shortDescription:
      "ASICS trail shoe with GEL cushioning and ASICSGRIP for rocky and mixed trail long runs.",
    generation: "13",
    subcategoryIds: ["sub-trail", "sub-max-cushion"],
    useCaseIds: ["uc-trail-training", "uc-long-runs", "uc-ultra"],
    terrain: ["trail"],
    cushionLevel: "high",
    drop: 8,
    strengths: ["Trail cushioning", "Grip on rock", "Protective ride"],
    weaknesses: ["Not a minimalist trail shoe", "Bulkier than race-trail flats"],
    recommendationScore: 87,
    valueScore: 85,
    relatedProductIds: ["prod-speedgoat-6", "prod-cascadia-18"],
    alternativeProductIds: ["prod-peregrine-15", "prod-hierro-v9"],
  },
  {
    id: "prod-xodus-ultra-3",
    slug: "saucony-xodus-ultra-3",
    brandId: "brand-saucony",
    name: "Xodus Ultra 3",
    fullName: "Saucony Xodus Ultra 3",
    shortDescription:
      "Max-cushion trail shoe for long mountain days when you want protection without a full race plate.",
    generation: "3",
    subcategoryIds: ["sub-trail", "sub-max-cushion"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    terrain: ["trail"],
    cushionLevel: "maximum",
    drop: 6,
    strengths: ["Ultra-friendly stack", "Trail protection", "Soft trail ride"],
    weaknesses: ["Tall for technical scrambling", "Heavier than short-trail shoes"],
    recommendationScore: 85,
    valueScore: 82,
    relatedProductIds: ["prod-speedgoat-6", "prod-triumph-22"],
    alternativeProductIds: ["prod-trabuco-13", "prod-cascadia-18"],
  },
  {
    id: "prod-hierro-v9",
    slug: "new-balance-fresh-foam-x-hierro-v9",
    brandId: "brand-new-balance",
    name: "Fresh Foam X Hierro v9",
    fullName: "New Balance Fresh Foam X Hierro v9",
    shortDescription:
      "Cushioned New Balance trail shoe with Vibram outsole options for durable dirt and rock mileage.",
    generation: "v9",
    subcategoryIds: ["sub-trail", "sub-max-cushion", "sub-wide"],
    useCaseIds: ["uc-trail-training", "uc-long-runs", "uc-wide-feet"],
    terrain: ["trail"],
    cushionLevel: "high",
    drop: 8,
    widthOptions: ["standard", "wide"],
    strengths: ["Trail cushion", "Width options", "Durable outsole"],
    weaknesses: ["Less precise than race-trail shoes"],
    recommendationScore: 86,
    valueScore: 86,
    relatedProductIds: ["prod-1080-v14", "prod-cascadia-18"],
    alternativeProductIds: ["prod-speedgoat-6", "prod-trabuco-13"],
  },
  {
    id: "prod-terrex-agravic-3",
    slug: "adidas-terrex-agravic-3",
    brandId: "brand-adidas",
    name: "Terrex Agravic 3",
    fullName: "Adidas Terrex Agravic 3",
    shortDescription:
      "Adidas trail shoe with Lightstrike cushioning and Continental rubber for mixed trail grip.",
    generation: "3",
    subcategoryIds: ["sub-trail"],
    useCaseIds: ["uc-trail-training", "uc-intermediate"],
    terrain: ["trail"],
    cushionLevel: "moderate",
    drop: 8,
    strengths: ["Trail grip", "Secure fit", "Versatile dirt mileage"],
    weaknesses: ["Less max plush than Hierro/Speedgoat"],
    recommendationScore: 84,
    valueScore: 83,
    relatedProductIds: ["prod-adios-pro-4", "prod-peregrine-15"],
    alternativeProductIds: ["prod-cascadia-18", "prod-sense-ride-5"],
  },
  {
    id: "prod-ultra-glide-2",
    slug: "salomon-ultra-glide-2",
    brandId: "brand-salomon",
    name: "Ultra Glide 2",
    fullName: "Salomon Ultra Glide 2",
    shortDescription:
      "Soft, protective Salomon trail shoe for long easy trail days when comfort outranks race precision.",
    generation: "2",
    subcategoryIds: ["sub-trail", "sub-max-cushion"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-comfort"],
    terrain: ["trail"],
    cushionLevel: "high",
    cushionFeel: "soft",
    drop: 6,
    strengths: ["Soft trail cushion", "Easy all-day fit", "Ultra-friendly"],
    weaknesses: ["Less precise on technical descents"],
    recommendationScore: 85,
    valueScore: 84,
    relatedProductIds: ["prod-sense-ride-5", "prod-xodus-ultra-3"],
    alternativeProductIds: ["prod-speedgoat-6", "prod-hierro-v9"],
  },
  {
    id: "prod-terraventure-4",
    slug: "topo-athletic-terraventure-5",
    brandId: "brand-topo",
    name: "Terraventure 5",
    fullName: "Topo Athletic Terraventure 5",
    shortDescription:
      "Wide-toe-box trail shoe with moderate stack for natural trail feel and durable grip.",
    generation: "5",
    subcategoryIds: ["sub-trail", "sub-wide", "sub-zero-drop"],
    useCaseIds: ["uc-trail-training", "uc-wide-feet", "uc-zero-drop"],
    terrain: ["trail"],
    cushionLevel: "moderate",
    drop: 3,
    widthOptions: ["standard", "wide"],
    strengths: ["Wide toe box", "Natural trail geometry", "Grip"],
    weaknesses: ["Lower stack than max-cushion trail shoes"],
    recommendationScore: 83,
    valueScore: 85,
    relatedProductIds: ["prod-lone-peak-8", "prod-phantom-3"],
    alternativeProductIds: ["prod-cascadia-18", "prod-sense-ride-5"],
  },

  // ── Stability ──────────────────────────────────────────────────────────
  {
    id: "prod-guide-18",
    slug: "saucony-guide-18",
    brandId: "brand-saucony",
    name: "Guide 18",
    fullName: "Saucony Guide 18",
    shortDescription:
      "Daily stability trainer with Center Path Technology for runners who want guidance without a harsh post.",
    generation: "18",
    subcategoryIds: ["sub-stability", "sub-daily-trainers", "sub-neutral"],
    useCaseIds: ["uc-stability", "uc-daily-training", "uc-beginner"],
    cushionLevel: "moderate",
    stability: "stability",
    drop: 8,
    strengths: ["Approachable guidance", "Daily durability", "Smooth ride"],
    weaknesses: ["Not max cushion", "Less support than Gaviota-class"],
    recommendationScore: 87,
    valueScore: 88,
    relatedProductIds: ["prod-adrenaline-gts-25", "prod-ride-18"],
    alternativeProductIds: ["prod-kayano-32", "prod-gt-2000-14"],
  },
  {
    id: "prod-arahi-7",
    slug: "hoka-arahi-7",
    brandId: "brand-hoka",
    name: "Arahi 7",
    fullName: "HOKA Arahi 7",
    shortDescription:
      "Lightweight HOKA stability shoe with J-Frame guidance for daily miles that need support.",
    generation: "7",
    subcategoryIds: ["sub-stability", "sub-daily-trainers"],
    useCaseIds: ["uc-stability", "uc-daily-training", "uc-easy-runs"],
    cushionLevel: "high",
    stability: "stability",
    rideCharacter: "rockered",
    drop: 5,
    strengths: ["Light for stability", "J-Frame guidance", "Rockered daily ride"],
    weaknesses: ["Fit can run short", "Less max support than Gaviota"],
    recommendationScore: 88,
    valueScore: 85,
    relatedProductIds: ["prod-clifton-10", "prod-adrenaline-gts-25"],
    alternativeProductIds: ["prod-guide-18", "prod-gaviota-5"],
  },
  {
    id: "prod-gaviota-5",
    slug: "hoka-gaviota-5",
    brandId: "brand-hoka",
    name: "Gaviota 5",
    fullName: "HOKA Gaviota 5",
    shortDescription:
      "Max-cushion HOKA stability shoe for runners who want plush stack plus stronger guidance.",
    generation: "5",
    subcategoryIds: ["sub-stability", "sub-max-cushion", "sub-daily-trainers"],
    useCaseIds: ["uc-stability", "uc-comfort", "uc-long-runs"],
    cushionLevel: "maximum",
    cushionFeel: "soft",
    stability: "stability",
    rideCharacter: "rockered",
    drop: 5,
    strengths: ["Max cushion + support", "Long-run friendly", "Stable base"],
    weaknesses: ["Heavier than Arahi", "Tall stack may feel soft late"],
    recommendationScore: 86,
    valueScore: 82,
    relatedProductIds: ["prod-arahi-7", "prod-bondi-9"],
    alternativeProductIds: ["prod-adrenaline-gts-25", "prod-kayano-32"],
  },
  {
    id: "prod-860-v14",
    slug: "new-balance-fresh-foam-x-860-v14",
    brandId: "brand-new-balance",
    name: "Fresh Foam X 860 v14",
    fullName: "New Balance Fresh Foam X 860 v14",
    shortDescription:
      "Workhorse stability daily trainer with Fresh Foam X and reliable medial support for high mileage.",
    generation: "v14",
    subcategoryIds: ["sub-stability", "sub-daily-trainers", "sub-wide"],
    useCaseIds: ["uc-stability", "uc-daily-training", "uc-high-mileage", "uc-wide-feet"],
    cushionLevel: "moderate",
    stability: "stability",
    drop: 8,
    widthOptions: ["standard", "wide", "2E", "4E"],
    strengths: ["Width ladder", "Durable daily stability", "Reliable guidance"],
    weaknesses: ["Less exciting foam than race-day shoes"],
    recommendationScore: 87,
    valueScore: 89,
    relatedProductIds: ["prod-1080-v14", "prod-guide-18"],
    alternativeProductIds: ["prod-adrenaline-gts-25", "prod-gt-2000-14"],
  },
  {
    id: "prod-gt-1000-13",
    slug: "asics-gt-1000-13",
    brandId: "brand-asics",
    name: "GT-1000 13",
    fullName: "ASICS GT-1000 13",
    shortDescription:
      "Value ASICS stability shoe when GT-2000 / Kayano is more shoe than you need or want to pay for.",
    generation: "13",
    subcategoryIds: ["sub-stability", "sub-daily-trainers"],
    useCaseIds: ["uc-stability", "uc-beginner", "uc-daily-training"],
    cushionLevel: "moderate",
    stability: "stability",
    drop: 8,
    strengths: ["Strong value", "Approachable stability", "Durable daily use"],
    weaknesses: ["Less premium foam than Kayano", "Heavier than race trainers"],
    recommendationScore: 83,
    valueScore: 92,
    relatedProductIds: ["prod-gt-2000-14", "prod-kayano-32"],
    alternativeProductIds: ["prod-guide-18", "prod-860-v14"],
  },
  {
    id: "prod-glycerin-gts-22",
    slug: "brooks-glycerin-gts-22",
    brandId: "brand-brooks",
    name: "Glycerin GTS 22",
    fullName: "Brooks Glycerin GTS 22",
    shortDescription:
      "Plush Brooks daily with GuideRails — soft Glycerin cushioning plus stability for long easy miles.",
    generation: "22",
    subcategoryIds: ["sub-stability", "sub-max-cushion", "sub-daily-trainers"],
    useCaseIds: ["uc-stability", "uc-comfort", "uc-long-runs"],
    cushionLevel: "maximum",
    cushionFeel: "soft",
    stability: "stability",
    drop: 10,
    strengths: ["Plush + GuideRails", "Long-run comfort", "Smooth transitions"],
    weaknesses: ["Premium price", "Softer ride than firmer stability shoes"],
    recommendationScore: 88,
    valueScore: 80,
    relatedProductIds: ["prod-glycerin-22", "prod-adrenaline-gts-25"],
    alternativeProductIds: ["prod-gaviota-5", "prod-kayano-32"],
  },
  {
    id: "prod-react-infinity-4",
    slug: "nike-react-infinity-run-4",
    brandId: "brand-nike",
    name: "React Infinity Run 4",
    fullName: "Nike React Infinity Run 4",
    shortDescription:
      "Broad-base Nike daily trainer that uses geometry and React foam for a planted, injury-conscious ride.",
    generation: "4",
    subcategoryIds: ["sub-stability", "sub-daily-trainers", "sub-max-cushion"],
    useCaseIds: ["uc-stability", "uc-daily-training", "uc-beginner"],
    cushionLevel: "high",
    stability: "stability",
    drop: 8,
    strengths: ["Planted geometry", "Daily comfort", "Broad base"],
    weaknesses: ["Not a traditional medial-post shoe", "Can feel bulky"],
    recommendationScore: 85,
    valueScore: 84,
    relatedProductIds: ["prod-structure-26", "prod-invincible-3"],
    alternativeProductIds: ["prod-arahi-7", "prod-guide-18"],
  },

  // ── Zero-drop / road-to-trail / brand depth ─────────────────────────────
  {
    id: "prod-paradigm-7",
    slug: "altra-paradigm-7",
    brandId: "brand-altra",
    name: "Paradigm 7",
    fullName: "Altra Paradigm 7",
    shortDescription:
      "Max-cushion zero-drop Altra with GuideRail-style support cues for runners who want stack without heel offset.",
    generation: "7",
    subcategoryIds: ["sub-zero-drop", "sub-max-cushion", "sub-stability", "sub-wide"],
    useCaseIds: ["uc-zero-drop", "uc-stability", "uc-comfort", "uc-wide-feet"],
    cushionLevel: "maximum",
    stability: "stability",
    drop: 0,
    widthOptions: ["standard", "wide"],
    strengths: ["Zero-drop + cushion", "Wide toe box", "Supportive platform"],
    weaknesses: ["Adaptation needed from high-drop shoes", "Tall stack"],
    recommendationScore: 84,
    valueScore: 81,
    relatedProductIds: ["prod-torin-8", "prod-lone-peak-8"],
    alternativeProductIds: ["prod-gaviota-5", "prod-terraventure-4"],
  },
  {
    id: "prod-experience-flow",
    slug: "altra-experience-flow",
    brandId: "brand-altra",
    name: "Experience Flow",
    fullName: "Altra Experience Flow",
    shortDescription:
      "Lower-stack Altra road shoe bridging toward traditional drop while keeping a roomy foot-shaped toe box.",
    subcategoryIds: ["sub-daily-trainers", "sub-neutral", "sub-wide"],
    useCaseIds: ["uc-daily-training", "uc-beginner", "uc-wide-feet"],
    cushionLevel: "moderate",
    drop: 4,
    widthOptions: ["standard", "wide"],
    strengths: ["Approachable Altra entry", "Wide toe box", "Daily versatility"],
    weaknesses: ["Not zero-drop", "Less max cushion than Paradigm"],
    recommendationScore: 82,
    valueScore: 86,
    relatedProductIds: ["prod-escalante-4", "prod-torin-8"],
    alternativeProductIds: ["prod-phantom-3", "prod-ride-18"],
  },
  {
    id: "prod-adizero-boston-13",
    slug: "adidas-adizero-boston-13",
    brandId: "brand-adidas",
    name: "Adizero Boston 13",
    fullName: "Adidas Adizero Boston 13",
    shortDescription:
      "Tempo-capable Adidas trainer bridging daily miles and faster sessions with Lightstrike Pro foam.",
    generation: "13",
    subcategoryIds: ["sub-tempo", "sub-daily-trainers", "sub-neutral"],
    useCaseIds: ["uc-tempo", "uc-daily-training", "uc-intermediate"],
    cushionLevel: "moderate",
    rideCharacter: "responsive",
    drop: 6,
    plate: true,
    plateMaterial: "nylon",
    strengths: ["Tempo versatility", "Snappy ride", "Race-week useful"],
    weaknesses: ["Less plush than max-cushion dailies", "Demanding for easy recovery"],
    recommendationScore: 87,
    valueScore: 84,
    relatedProductIds: ["prod-adios-pro-4", "prod-adizero-evo-sl"],
    alternativeProductIds: ["prod-endorphin-speed-5", "prod-mach-6"],
  },
  {
    id: "prod-ultraboost-5",
    slug: "adidas-ultraboost-5",
    brandId: "brand-adidas",
    name: "Ultraboost 5",
    fullName: "Adidas Ultraboost 5",
    shortDescription:
      "Soft Boost daily trainer for easy miles and recovery when cushion comfort is the priority.",
    generation: "5",
    subcategoryIds: ["sub-daily-trainers", "sub-max-cushion", "sub-neutral", "sub-recovery-walk"],
    useCaseIds: ["uc-easy-runs", "uc-recovery", "uc-comfort", "uc-daily-training"],
    cushionLevel: "high",
    cushionFeel: "soft",
    drop: 10,
    strengths: ["Soft Boost cushion", "Easy-mile comfort", "Familiar fit"],
    weaknesses: ["Heavier than tempo shoes", "Not a race-day racer"],
    recommendationScore: 84,
    valueScore: 80,
    relatedProductIds: ["prod-adizero-boston-13", "prod-cloudmonster-2"],
    alternativeProductIds: ["prod-bondi-9", "prod-glycerin-22"],
  },
  {
    id: "prod-cloudsurfer-2",
    slug: "on-cloudsurfer-2",
    brandId: "brand-on",
    name: "Cloudsurfer 2",
    fullName: "On Cloudsurfer 2",
    shortDescription:
      "Soft On daily trainer with CloudTec Phase cushioning for smooth easy and long road miles.",
    generation: "2",
    subcategoryIds: ["sub-daily-trainers", "sub-max-cushion", "sub-neutral"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-long-runs", "uc-comfort"],
    cushionLevel: "high",
    cushionFeel: "soft",
    rideCharacter: "rockered",
    drop: 8,
    strengths: ["Soft daily ride", "Smooth transitions", "Easy-mile focus"],
    weaknesses: ["Premium price", "Less firm for fast sessions"],
    recommendationScore: 86,
    valueScore: 78,
    relatedProductIds: ["prod-cloudmonster-2", "prod-cloudsurfer-next"],
    alternativeProductIds: ["prod-clifton-10", "prod-ultraboost-5"],
  },
  {
    id: "prod-cloudmonster-hyper",
    slug: "on-cloudmonster-hyper",
    brandId: "brand-on",
    name: "Cloudmonster Hyper",
    fullName: "On Cloudmonster Hyper",
    shortDescription:
      "Faster Cloudmonster variant for tempo and long efforts when you want On geometry with more snap.",
    subcategoryIds: ["sub-tempo", "sub-max-cushion", "sub-neutral"],
    useCaseIds: ["uc-tempo", "uc-long-runs", "uc-intermediate"],
    cushionLevel: "high",
    rideCharacter: "responsive",
    drop: 6,
    strengths: ["Energetic max stack", "Tempo-capable", "Distinct On ride"],
    weaknesses: ["Fit learning curve", "Premium pricing"],
    recommendationScore: 85,
    valueScore: 76,
    relatedProductIds: ["prod-cloudmonster-2", "prod-adizero-boston-13"],
    alternativeProductIds: ["prod-superblast-2", "prod-endorphin-speed-5"],
  },
  {
    id: "prod-genesis-salomon",
    slug: "salomon-genesis",
    brandId: "brand-salomon",
    name: "Genesis",
    fullName: "Salomon Genesis",
    shortDescription:
      "Road-to-trail Salomon shoe for runners mixing pavement approaches with light dirt singletrack.",
    subcategoryIds: ["sub-road-trail", "sub-trail", "sub-daily-trainers"],
    useCaseIds: ["uc-trail-training", "uc-daily-training", "uc-intermediate"],
    terrain: ["road", "trail"],
    cushionLevel: "moderate",
    drop: 8,
    strengths: ["True road-to-trail", "Secure Salomon fit", "Mixed-surface grip"],
    weaknesses: ["Compromised vs pure road or pure trail specialists"],
    recommendationScore: 84,
    valueScore: 83,
    relatedProductIds: ["prod-pegasus-trail-5", "prod-aero-glide-2"],
    alternativeProductIds: ["prod-sense-ride-5", "prod-cascadia-18"],
  },
];

export const runningShoesWave3: Product[] = DRAFTS.map(shoe);
