import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { applyMediaPublishGate } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

/**
 * Wave 2 running sunglasses catalog — performance wraps, race shields,
 * trail photochromics and everyday value frames beyond gear-wave1
 * (Encoder / Goodr OGs / Julbo Aerolite).
 */
export const runningSunglassesWave2Raw: Product[] = [
  // ─── Oakley ──────────────────────────────────────────────────────────────
  {
    id: "prod-oakley-radar-ev-path",
    slug: "oakley-radar-ev-path",
    brandId: "brand-oakley",
    familyId: "fam-oakley-radar-ev",
    generation: "Radar EV Path",
    name: "Radar EV Path",
    fullName: "Oakley Radar EV Path",
    shortDescription:
      "Interchangeable Prizm wrap (~28–29 g) for bright road and trail glare — pick Path when you want proven Unobtainium grip and lens swaps; skip if you want a frameless race shield like Kato or Encoder.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap"],
    useCaseIds: [
      "uc-bright-sun",
      "uc-daily-training",
      "uc-trail-training",
      "uc-marathon",
      "uc-long-runs",
    ],
    specifications: {
      lensType: "Prizm (interchangeable; polarized / photochromic options)",
      frameStyle: "wrap",
      weight: 29,
      polarized: null,
      photochromic: false,
      vlt: "12–36%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Proven sport retention with Unobtainium nose and temples",
      "True interchangeable Prizm ecosystem for sun and trail tints",
      "High coverage without a full race-shield aesthetic",
    ],
    weaknesses: [
      "Premium pricing once spare Prizm lenses stack up",
      "Bulkier on small faces than Flak or value wraps",
    ],
    recommendationScore: 90,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-oakley-radar-ev-path",
      "Oakley Radar EV Path — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oakley-flak-2xl",
      "prod-oakley-sutro-lite",
      "prod-oakley-encoder",
      "prod-smith-shift-mag",
    ],
    alternativeProductIds: [
      "prod-smith-shift-mag",
      "prod-tifosi-rail",
      "prod-oakley-flak-2xl",
      "prod-oakley-encoder",
    ],
    ...pub,
  },
  {
    id: "prod-oakley-sutro-lite",
    slug: "oakley-sutro-lite",
    brandId: "brand-oakley",
    familyId: "fam-oakley-sutro",
    generation: "Sutro Lite",
    name: "Sutro Lite",
    fullName: "Oakley Sutro Lite",
    shortDescription:
      "Open-rim shield/wrap (~32 g) with big Prizm coverage and more airflow than full Sutro — shortlist for bright road miles and marathon glare; pause if you need photochromic trail versatility.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-shield", "sub-sg-performance-wrap"],
    useCaseIds: [
      "uc-bright-sun",
      "uc-daily-training",
      "uc-marathon",
      "uc-long-runs",
    ],
    specifications: {
      lensType: "Prizm",
      frameStyle: "shield",
      weight: 32,
      polarized: null,
      photochromic: false,
      vlt: "11–20%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "high",
      interchangeableLenses: false,
      prescriptionCompatible: false,
      fit: "large",
      noseAdjustment: true,
    },
    strengths: [
      "Wide shield coverage with better airflow than closed Sutro",
      "Strong road glare control for sunny marathon and daily miles",
      "Secure Oakley sport fit on medium-to-large faces",
    ],
    weaknesses: [
      "Fixed lens — no mid-run tint swap",
      "Large silhouette can overwhelm smaller faces",
    ],
    recommendationScore: 88,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-oakley-sutro-lite",
      "Oakley Sutro Lite — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oakley-kato",
      "prod-oakley-radar-ev-path",
      "prod-100-s3",
      "prod-oakley-encoder",
    ],
    alternativeProductIds: [
      "prod-oakley-kato",
      "prod-100-s3",
      "prod-rudy-cutline",
      "prod-oakley-encoder",
    ],
    ...pub,
  },
  {
    id: "prod-oakley-kato",
    slug: "oakley-kato",
    brandId: "brand-oakley",
    familyId: "fam-oakley-kato",
    generation: "Kato",
    name: "Kato",
    fullName: "Oakley Kato",
    shortDescription:
      "Frameless race shield with panoramic Prizm optics — I'd shortlist for bright road racing and tempo days; skip if you need interchangeable lenses or a subtler everyday look.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-shield"],
    useCaseIds: ["uc-bright-sun", "uc-marathon", "uc-5k", "uc-daily-training"],
    specifications: {
      lensType: "Prizm",
      frameStyle: "shield",
      weight: 30,
      polarized: null,
      photochromic: false,
      vlt: "12–20%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: false,
      prescriptionCompatible: false,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Wide uninterrupted race field of view",
      "Secure nosepiece geometry for hard efforts",
      "Prizm contrast tuned for bright road surfaces",
    ],
    weaknesses: [
      "Bold aesthetic and premium price",
      "Less trail-flexible than photochromic Julbo wraps",
    ],
    recommendationScore: 87,
    valueScore: 68,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-oakley-kato",
      "Oakley Kato — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oakley-sutro-lite",
      "prod-100-s3",
      "prod-rudy-cutline",
      "prod-oakley-encoder",
    ],
    alternativeProductIds: [
      "prod-100-s3",
      "prod-rudy-cutline",
      "prod-oakley-encoder",
      "prod-oakley-sutro-lite",
    ],
    ...pub,
  },
  {
    id: "prod-oakley-flak-2xl",
    slug: "oakley-flak-2-0-xl",
    brandId: "brand-oakley",
    familyId: "fam-oakley-flak",
    generation: "Flak 2.0 XL",
    name: "Flak 2.0 XL",
    fullName: "Oakley Flak 2.0 XL",
    shortDescription:
      "Larger-face Prizm wrap (~26 g) with interchangeable lenses — choose when Radar EV Path feels narrow; still a daily/road performer more than a trail photochromic tool.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap"],
    useCaseIds: [
      "uc-bright-sun",
      "uc-daily-training",
      "uc-marathon",
      "uc-long-runs",
    ],
    specifications: {
      lensType: "Prizm (interchangeable)",
      frameStyle: "wrap",
      weight: 26,
      polarized: null,
      photochromic: false,
      vlt: "12–20%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "large",
      noseAdjustment: true,
    },
    strengths: [
      "XL coverage for larger faces without jumping to Sutro bulk",
      "Interchangeable Prizm lenses and Rx-friendly platform",
      "Light for the coverage class",
    ],
    weaknesses: [
      "Can feel wide on smaller heads",
      "Trail mixed-light still wants a photochromic peer",
    ],
    recommendationScore: 86,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-oakley-flak-2xl",
      "Oakley Flak 2.0 XL — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-oakley-sutro-lite",
      "prod-tifosi-rail",
      "prod-oakley-encoder",
    ],
    alternativeProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-tifosi-rail",
      "prod-smith-shift-mag",
    ],
    ...pub,
  },

  // ─── Smith ───────────────────────────────────────────────────────────────
  {
    id: "prod-smith-shift-mag",
    slug: "smith-shift-mag",
    brandId: "brand-smith",
    familyId: "fam-smith-shift-mag",
    generation: "Shift MAG",
    name: "Shift MAG",
    fullName: "Smith Shift MAG",
    shortDescription:
      "ChromaPop wrap with magnetic lens swaps (~29 g) — strong for road and mixed sessions; photochromic MAG lenses are a known option when you want one-lens versatility without carrying spares.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-bright-sun",
      "uc-mixed-light",
      "uc-daily-training",
      "uc-marathon",
      "uc-trail-training",
    ],
    specifications: {
      lensType: "ChromaPop (MAG interchangeable; photochromic option)",
      frameStyle: "wrap",
      weight: 29,
      polarized: null,
      photochromic: null,
      vlt: null,
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Fast MAG lens changes without fingerprints on the optic",
      "ChromaPop contrast plus optional photochromic MAG lenses",
      "Secure Megol nose/temples for hard efforts",
    ],
    weaknesses: [
      "Premium street price vs Tifosi Rail-class value wraps",
      "Default kit is fixed-tint + clear — photochromic is an add-on",
    ],
    recommendationScore: 89,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-smith-shift-mag",
      "Smith Shift MAG — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-smith-attack-mag",
      "prod-oakley-radar-ev-path",
      "prod-julbo-ultimate",
      "prod-tifosi-rail",
    ],
    alternativeProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-julbo-ultimate",
      "prod-tifosi-rail",
    ],
    ...pub,
  },
  {
    id: "prod-smith-attack-mag",
    slug: "smith-attack-mag",
    brandId: "brand-smith",
    familyId: "fam-smith-attack-mag",
    generation: "Attack MAG",
    name: "Attack MAG",
    fullName: "Smith Attack MAG",
    shortDescription:
      "Maximum-coverage trail wrap with MAG lens swaps and ventilated ChromaPop optics — I'd rotate this for technical trail and ultra training when Shift MAG feels too road-flat.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-trail-training",
      "uc-mixed-light",
      "uc-ultra",
      "uc-long-runs",
      "uc-bright-sun",
    ],
    specifications: {
      lensType: "ChromaPop (MAG interchangeable; photochromic SKUs available)",
      frameStyle: "wrap",
      weight: 28,
      polarized: null,
      photochromic: null,
      vlt: null,
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "high",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Trail-first coverage with lens ventilation against fog",
      "MAG system for bright-to-low-light ChromaPop swaps",
      "Photochromic clear-to-gray SKUs when mixed canopy light dominates",
    ],
    weaknesses: [
      "More MTB/trail-shaped than subtle road daily wear",
      "Price sits with premium Smith / Oakley peers",
    ],
    recommendationScore: 88,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-smith-attack-mag",
      "Smith Attack MAG — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-smith-shift-mag",
      "prod-julbo-ultimate",
      "prod-julbo-rush",
      "prod-julbo-aerolite",
    ],
    alternativeProductIds: [
      "prod-julbo-ultimate",
      "prod-julbo-rush",
      "prod-julbo-aerolite",
      "prod-smith-shift-mag",
    ],
    ...pub,
  },

  // ─── Julbo ───────────────────────────────────────────────────────────────
  {
    id: "prod-julbo-ultimate",
    slug: "julbo-ultimate",
    brandId: "brand-julbo",
    familyId: "fam-julbo-ultimate",
    generation: "Ultimate",
    name: "Ultimate",
    fullName: "Julbo Ultimate",
    shortDescription:
      "Trail wrap built around Reactiv photochromic lenses — shortlist for ultra and mixed-canopy days when you refuse to carry spare lenses; less of a bright-only race shield than Kato or S3.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-trail-training",
      "uc-mixed-light",
      "uc-ultra",
      "uc-long-runs",
      "uc-bright-sun",
    ],
    specifications: {
      lensType: "Reactiv photochromic (Spectron fixed-tint options)",
      frameStyle: "wrap",
      weight: 26,
      polarized: null,
      photochromic: true,
      vlt: "7–82%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "high",
      interchangeableLenses: false,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Reactiv auto-tint covers shade-to-alpine glare without swaps",
      "Trail-oriented wrap coverage and ventilation",
      "Light enough for long ultra days",
    ],
    weaknesses: [
      "Photochromic lag in rapid light changes vs a swapped spare",
      "Regional stock and Reactiv SKU pricing vary",
    ],
    recommendationScore: 90,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-julbo-ultimate",
      "Julbo Ultimate — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-julbo-rush",
      "prod-julbo-aerolite",
      "prod-smith-attack-mag",
      "prod-smith-shift-mag",
    ],
    alternativeProductIds: [
      "prod-julbo-aerolite",
      "prod-julbo-rush",
      "prod-smith-attack-mag",
      "prod-smith-shift-mag",
    ],
    ...pub,
  },
  {
    id: "prod-julbo-rush",
    slug: "julbo-rush",
    brandId: "brand-julbo",
    familyId: "fam-julbo-rush",
    generation: "Rush",
    name: "Rush",
    fullName: "Julbo Rush",
    shortDescription:
      "Compact trail wrap with Reactiv options — I'd pick Rush when Ultimate feels oversized but you still want photochromic mountain versatility for training and ultras.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-trail-training",
      "uc-mixed-light",
      "uc-ultra",
      "uc-long-runs",
    ],
    specifications: {
      lensType: "Reactiv photochromic / Spectron options",
      frameStyle: "wrap",
      weight: 27,
      polarized: null,
      photochromic: true,
      vlt: "9–75%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "high",
      interchangeableLenses: false,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Reactiv trail optics in a slightly tighter wrap than Ultimate",
      "Good ventilation for humid climb efforts",
      "Lighter trail package than most race shields",
    ],
    weaknesses: [
      "Less panoramic than Kato / S3 race shields",
      "Fixed Reactiv lens — no MAG-style mid-run swap",
    ],
    recommendationScore: 86,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-julbo-rush",
      "Julbo Rush — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-julbo-ultimate",
      "prod-julbo-aerolite",
      "prod-smith-attack-mag",
      "prod-roka-phantom-air",
    ],
    alternativeProductIds: [
      "prod-julbo-ultimate",
      "prod-julbo-aerolite",
      "prod-smith-attack-mag",
    ],
    ...pub,
  },

  // ─── Rudy Project / 100% / ROKA ──────────────────────────────────────────
  {
    id: "prod-rudy-cutline",
    slug: "rudy-project-cutline",
    brandId: "brand-rudy-project",
    familyId: "fam-rudy-cutline",
    generation: "Cutline",
    name: "Cutline",
    fullName: "Rudy Project Cutline",
    shortDescription:
      "Race shield (~34 g) with quick-swap lenses and adjustable nose/temples — shortlist for bright road racing; ImpactX photochromic lenses are a known path when mixed light matters.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-shield", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-bright-sun",
      "uc-marathon",
      "uc-mixed-light",
      "uc-daily-training",
      "uc-5k",
    ],
    specifications: {
      lensType: "RP Optics / ImpactX photochromic options",
      frameStyle: "shield",
      weight: 34,
      polarized: null,
      photochromic: null,
      vlt: null,
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Button-style lens interchange with optional ImpactX photochromics",
      "Adjustable fit hardware for race retention",
      "Wide shield FOV for road racing",
    ],
    weaknesses: [
      "Heavier than Kato / Phantom Air class",
      "Default dark lenses still need a photochromic or spare for canopy miles",
    ],
    recommendationScore: 85,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-rudy-cutline",
      "Rudy Project Cutline — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-100-s3",
      "prod-oakley-kato",
      "prod-oakley-encoder",
      "prod-oakley-sutro-lite",
    ],
    alternativeProductIds: [
      "prod-100-s3",
      "prod-oakley-kato",
      "prod-oakley-encoder",
    ],
    ...pub,
  },
  {
    id: "prod-100-s3",
    slug: "100-percent-s3",
    brandId: "brand-100percent",
    familyId: "fam-100-s3",
    generation: "S3",
    name: "S3",
    fullName: "100% S3",
    shortDescription:
      "HiPER race shield with simple lens swaps — strong bright-sun road tool under Kato money; not the first pick for photochromic trail ultras.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-shield"],
    useCaseIds: ["uc-bright-sun", "uc-marathon", "uc-daily-training", "uc-5k"],
    specifications: {
      lensType: "HiPER (interchangeable)",
      frameStyle: "shield",
      weight: 32,
      polarized: false,
      photochromic: false,
      vlt: "14%",
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: false,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Race-shield coverage at a sharper price than Oakley Kato",
      "Spare clear/low-light lens common in kits",
      "Secure sport fit for hard road efforts",
    ],
    weaknesses: [
      "Lens swaps leave fingerprints more easily than MAG systems",
      "Less trail-photochromic versatile than Julbo Reactiv wraps",
    ],
    recommendationScore: 84,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-100-s3",
      "100% S3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-rudy-cutline",
      "prod-oakley-kato",
      "prod-oakley-sutro-lite",
      "prod-oakley-encoder",
    ],
    alternativeProductIds: [
      "prod-rudy-cutline",
      "prod-oakley-kato",
      "prod-oakley-encoder",
    ],
    ...pub,
  },
  {
    id: "prod-roka-phantom-air",
    slug: "roka-phantom-air",
    brandId: "brand-roka",
    familyId: "fam-roka-phantom-air",
    generation: "Phantom Air",
    name: "Phantom Air",
    fullName: "ROKA Phantom Air",
    shortDescription:
      "Ultralight performance wrap for road and triathlon-adjacent running — I'd shortlist when Kato/Sutro feel heavy and you still want premium optics; not a budget daily Goodr.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap"],
    useCaseIds: [
      "uc-daily-training",
      "uc-bright-sun",
      "uc-marathon",
      "uc-long-runs",
    ],
    specifications: {
      lensType: "ROKA GEKO / impact polycarbonate",
      frameStyle: "wrap",
      weight: 23,
      polarized: null,
      photochromic: false,
      vlt: null,
      uvProtection: "UV400",
      coverage: "moderate",
      ventilation: "high",
      interchangeableLenses: false,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Very light frame for long road and marathon days",
      "Grippy GEKO-style contact points stay put when sweating",
      "Cleaner silhouette than full race shields",
    ],
    weaknesses: [
      "Less coverage than Sutro Lite / Attack MAG",
      "Premium price vs Tifosi / Goodr value lanes",
    ],
    recommendationScore: 84,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-roka-phantom-air",
      "ROKA Phantom Air — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-julbo-rush",
      "prod-oakley-flak-2xl",
      "prod-tifosi-rail",
    ],
    alternativeProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-tifosi-rail",
      "prod-julbo-rush",
    ],
    ...pub,
  },

  // ─── Tifosi / Goodr value ────────────────────────────────────────────────
  {
    id: "prod-tifosi-rail",
    slug: "tifosi-rail",
    brandId: "brand-tifosi",
    familyId: "fam-tifosi-rail",
    generation: "Rail",
    name: "Rail",
    fullName: "Tifosi Rail",
    shortDescription:
      "Value interchangeable wrap (~31–32 g) — often ships with multiple lenses or Fototec photochromic SKUs; shortlist when Radar EV Path performance matters but Oakley money doesn't.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-cycling-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-performance-wrap", "sub-sg-photochromic"],
    useCaseIds: [
      "uc-daily-training",
      "uc-bright-sun",
      "uc-mixed-light",
      "uc-trail-training",
      "uc-marathon",
    ],
    specifications: {
      lensType: "Polycarbonate interchange / Fototec photochromic options",
      frameStyle: "wrap",
      weight: 32,
      polarized: null,
      photochromic: null,
      vlt: null,
      uvProtection: "UV400",
      coverage: "high",
      ventilation: "moderate",
      interchangeableLenses: true,
      prescriptionCompatible: true,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Interchange kit value far below premium MAG / Prizm peers",
      "Fototec photochromic SKUs cover mixed light without spares",
      "High coverage wrap for road and trail training",
    ],
    weaknesses: [
      "Retention and optics sit below Oakley / Smith premium feel",
      "Some runners find the frameless rail less locked-in at race pace",
    ],
    recommendationScore: 83,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-tifosi-rail",
      "Tifosi Rail — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-tifosi-vogel",
      "prod-oakley-radar-ev-path",
      "prod-smith-shift-mag",
      "prod-goodr-circle-gs",
    ],
    alternativeProductIds: [
      "prod-oakley-radar-ev-path",
      "prod-smith-shift-mag",
      "prod-tifosi-vogel",
      "prod-goodr-ogs",
    ],
    ...pub,
  },
  {
    id: "prod-tifosi-vogel",
    slug: "tifosi-vogel",
    brandId: "brand-tifosi",
    familyId: "fam-tifosi-vogel",
    generation: "Vogel",
    name: "Vogel",
    fullName: "Tifosi Vogel",
    shortDescription:
      "Light everyday/value sport frame (~24 g class) — daily training and easy miles when you want UV400 without a race-shield silhouette; step up to Rail for interchangeable coverage.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-everyday-value"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-bright-sun"],
    specifications: {
      lensType: "Polycarbonate",
      frameStyle: "sport",
      weight: 24,
      polarized: null,
      photochromic: false,
      vlt: null,
      uvProtection: "UV400",
      coverage: "moderate",
      ventilation: "moderate",
      interchangeableLenses: false,
      prescriptionCompatible: false,
      fit: "medium",
      noseAdjustment: true,
    },
    strengths: [
      "Light, approachable daily runner frame",
      "Strong value vs premium wraps",
      "Comfortable for easy and steady outdoor miles",
    ],
    weaknesses: [
      "Less coverage and race retention than Rail / Radar EV",
      "Not a photochromic trail tool",
    ],
    recommendationScore: 78,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-tifosi-vogel",
      "Tifosi Vogel — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-tifosi-rail",
      "prod-goodr-circle-gs",
      "prod-goodr-ogs",
    ],
    alternativeProductIds: [
      "prod-goodr-ogs",
      "prod-goodr-circle-gs",
      "prod-tifosi-rail",
    ],
    ...pub,
  },
  {
    id: "prod-goodr-circle-gs",
    slug: "goodr-circle-gs",
    brandId: "brand-goodr",
    familyId: "fam-goodr-circle-gs",
    generation: "Circle Gs",
    name: "Circle Gs",
    fullName: "Goodr Circle Gs",
    shortDescription:
      "Polarized round everyday runners (~19 g) — shortlist for easy/daily miles and style-first training; skip when you need wrap coverage for bright marathon glare or technical trail.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-sunglasses",
    subcategoryIds: ["sub-sg-everyday-value"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs", "uc-bright-sun"],
    specifications: {
      lensType: "Polarized TAC",
      frameStyle: "classic",
      weight: 19,
      polarized: true,
      photochromic: false,
      vlt: null,
      uvProtection: "UV400",
      coverage: "low",
      ventilation: "high",
      interchangeableLenses: false,
      prescriptionCompatible: false,
      fit: "small",
      noseAdjustment: false,
    },
    strengths: [
      "Polarized value with Goodr no-slip coating",
      "Very light for easy daily outdoor miles",
      "Round shape for runners who hate race-shield look",
    ],
    weaknesses: [
      "Low coverage vs performance wraps and shields",
      "Smaller fit and less race stability than Flak / Radar EV",
    ],
    recommendationScore: 76,
    valueScore: 94,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-sunglasses",
      "prod-goodr-circle-gs",
      "Goodr Circle Gs — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-goodr-ogs",
      "prod-tifosi-vogel",
      "prod-tifosi-rail",
    ],
    alternativeProductIds: [
      "prod-goodr-ogs",
      "prod-tifosi-vogel",
      "prod-tifosi-rail",
    ],
    ...pub,
  },
];

/** All wave-2 sunglasses SKUs await authentic heroes before published catalog. */
const MEDIA_PENDING_DRAFT_IDS = new Set(
  runningSunglassesWave2Raw.map((p) => p.id),
);

export const runningSunglassesWave2: Product[] = applyMediaPublishGate(runningSunglassesWave2Raw, MEDIA_PENDING_DRAFT_IDS);
