import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

/**
 * Wave 1 GPS watches and heart-rate monitors for the running catalog.
 * Skip duplicates already seeded in products.ts (FR965, FR255, Pace 3, HRM-Pro Plus).
 */
export const runningWatchesAndHrm: Product[] = [
  // ─── Garmin watches ──────────────────────────────────────────────────────
  {
    id: "prod-forerunner-970",
    slug: "garmin-forerunner-970",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "970",
    name: "Forerunner 970",
    fullName: "Garmin Forerunner 970",
    shortDescription:
      "AMOLED flagship running watch with full maps, ECG, multi-band GPS, and advanced training metrics.",
    releaseDate: "2025-05-15",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
      "disc-running-ultra",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-premium"],
    useCaseIds: [
      "uc-advanced",
      "uc-high-mileage",
      "uc-marathon",
      "uc-pb",
      "uc-ultra",
    ],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: 15,
      batteryGps: 26,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Full offline maps on a bright AMOLED",
      "ECG and advanced running metrics with HRM 600",
      "Complete Garmin training ecosystem",
    ],
    weaknesses: [
      "Premium price",
      "GPS-mode battery shorter than some MIP ultralight watches",
    ],
    recommendationScore: 91,
    valueScore: 68,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-970",
      "Garmin Forerunner 970 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-fr970-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-570", "prod-hrm-600", "prod-coros-pace-pro"],
    alternativeProductIds: ["prod-forerunner-570", "prod-coros-apex-2-pro", "prod-suunto-race"],
    ...pub,
  },
  {
    id: "prod-forerunner-570",
    slug: "garmin-forerunner-570",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "570",
    name: "Forerunner 570",
    fullName: "Garmin Forerunner 570",
    shortDescription:
      "AMOLED mid-range running watch with multi-band GPS, music, and strong training tools without onboard maps.",
    releaseDate: "2025-05-15",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-trail"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: [
      "uc-intermediate",
      "uc-advanced",
      "uc-marathon",
      "uc-half",
      "uc-high-mileage",
    ],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: 11,
      batteryGps: 18,
      multiBandGps: true,
      maps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Bright AMOLED without flagship price",
      "Available in multiple case sizes",
      "Full Garmin coaching and recovery suite",
    ],
    weaknesses: ["No full offline maps", "Shorter GPS battery than 970"],
    recommendationScore: 87,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-570",
      "Garmin Forerunner 570 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-970", "prod-forerunner-265", "prod-coros-pace-pro"],
    alternativeProductIds: ["prod-forerunner-265", "prod-coros-pace-pro", "prod-polar-pacer-pro"],
    ...pub,
  },
  {
    id: "prod-forerunner-265",
    slug: "garmin-forerunner-265",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "265",
    name: "Forerunner 265",
    fullName: "Garmin Forerunner 265",
    shortDescription:
      "Previous-generation AMOLED Forerunner midrange, often discounted after the 570 launch.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: ["uc-intermediate", "uc-half", "uc-marathon", "uc-beginners"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Proven AMOLED daily runner", "Strong clearance value vs 570"],
    weaknesses: ["Superseded by Forerunner 570", "No full maps"],
    recommendationScore: 80,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-265",
      "Garmin Forerunner 265 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-570"],
    alternativeProductIds: ["prod-forerunner-570", "prod-coros-pace-pro"],
    ...pub,
  },
  {
    id: "prod-forerunner-165",
    slug: "garmin-forerunner-165",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "165",
    name: "Forerunner 165",
    fullName: "Garmin Forerunner 165",
    shortDescription:
      "Entry AMOLED running watch with core Garmin training metrics for newer runners.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: ["uc-beginners", "uc-first-5k", "uc-first-10k", "uc-first-half"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: false,
      maps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Approachable price", "Bright AMOLED for first GPS watch"],
    weaknesses: ["Fewer advanced metrics", "No music or maps"],
    recommendationScore: 76,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-165",
      "Garmin Forerunner 165 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-55", "prod-forerunner-570"],
    alternativeProductIds: ["prod-forerunner-55", "prod-polar-pacer-pro"],
    ...pub,
  },
  {
    id: "prod-forerunner-55",
    slug: "garmin-forerunner-55",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "55",
    name: "Forerunner 55",
    fullName: "Garmin Forerunner 55",
    shortDescription:
      "Budget MIP running watch focused on simple GPS tracking and beginner coaching.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: ["uc-beginners", "uc-first-5k", "uc-first-10k"],
    specifications: {
      weight: null,
      displayType: "mip",
      displaySize: null,
      touchscreen: false,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: false,
      maps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: false,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: false,
      waterRating: "5 ATM",
    },
    strengths: ["Lowest-cost Garmin runner entry", "Long MIP battery"],
    weaknesses: ["Dated display and feature set", "Limited multisport depth"],
    recommendationScore: 68,
    valueScore: 92,
    experienceLevels: ["beginner"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-55",
      "Garmin Forerunner 55 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-165"],
    alternativeProductIds: ["prod-forerunner-165"],
    ...pub,
  },

  // ─── COROS ───────────────────────────────────────────────────────────────
  {
    id: "prod-coros-pace-pro",
    slug: "coros-pace-pro",
    brandId: "brand-coros",
    familyId: "fam-coros-pace",
    generation: "Pro",
    name: "Pace Pro",
    fullName: "COROS Pace Pro",
    shortDescription:
      "Lightweight AMOLED running watch with maps, multi-band GPS, and class-leading battery claims.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
      "disc-running-ultra",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-premium"],
    useCaseIds: [
      "uc-intermediate",
      "uc-advanced",
      "uc-high-mileage",
      "uc-marathon",
      "uc-ultra",
    ],
    specifications: {
      weight: 37,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: 20,
      batteryGps: 38,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Very light for maps + AMOLED", "Excellent stated GPS battery"],
    weaknesses: ["Smaller third-party app ecosystem than Garmin", "No payments"],
    recommendationScore: 89,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-coros-pace-pro",
      "COROS Pace Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-coros-apex-2-pro", "prod-forerunner-570", "prod-coros-hrm"],
    alternativeProductIds: ["prod-forerunner-570", "prod-suunto-race-s"],
    ...pub,
  },
  {
    id: "prod-coros-apex-2-pro",
    slug: "coros-apex-2-pro",
    brandId: "brand-coros",
    familyId: "fam-coros-apex",
    generation: "2 Pro",
    name: "Apex 2 Pro",
    fullName: "COROS Apex 2 Pro",
    shortDescription:
      "Durable sapphire MIP endurance watch built for ultra and multi-day adventures.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: ["uc-ultra", "uc-trail-training", "uc-advanced", "uc-high-mileage"],
    specifications: {
      weight: null,
      displayType: "mip",
      displaySize: null,
      touchscreen: false,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "10 ATM",
    },
    strengths: ["Long GPS endurance profile", "Rugged sapphire build"],
    weaknesses: ["MIP less vivid than AMOLED indoors", "Heavier than Pace Pro"],
    recommendationScore: 85,
    valueScore: 80,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-coros-apex-2-pro",
      "COROS Apex 2 Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-coros-pace-pro", "prod-suunto-race", "prod-forerunner-970"],
    alternativeProductIds: ["prod-suunto-race", "prod-forerunner-970"],
    ...pub,
  },

  // ─── Polar ───────────────────────────────────────────────────────────────
  {
    id: "prod-polar-vantage-v3",
    slug: "polar-vantage-v3",
    brandId: "brand-polar",
    familyId: "fam-polar-vantage",
    generation: "V3",
    name: "Vantage V3",
    fullName: "Polar Vantage V3",
    shortDescription:
      "AMOLED multisport watch with Polar’s training load tools, ECG, and dual-frequency GPS.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: ["disc-running-road", "disc-running-racing", "disc-running-trail"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: ["uc-advanced", "uc-marathon", "uc-pb", "uc-high-mileage"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Strong Polar HR and training analytics", "AMOLED with maps"],
    weaknesses: ["Smaller music/payment feature set", "Fewer third-party integrations"],
    recommendationScore: 82,
    valueScore: 74,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-polar-vantage-v3",
      "Polar Vantage V3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-polar-pacer-pro", "prod-polar-h10", "prod-forerunner-970"],
    alternativeProductIds: ["prod-forerunner-970", "prod-suunto-race"],
    ...pub,
  },
  {
    id: "prod-polar-pacer-pro",
    slug: "polar-pacer-pro",
    brandId: "brand-polar",
    familyId: "fam-polar-pacer",
    generation: "Pro",
    name: "Pacer Pro",
    fullName: "Polar Pacer Pro",
    shortDescription:
      "Lightweight MIP running watch focused on accurate training guidance and barometric tools.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: ["uc-intermediate", "uc-beginners", "uc-half", "uc-marathon"],
    specifications: {
      weight: null,
      displayType: "mip",
      displaySize: null,
      touchscreen: false,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: false,
      maps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: false,
      runningDynamics: true,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Light running-focused tool", "Solid Polar coaching value"],
    weaknesses: ["No maps or music", "Less multisport breadth than flagships"],
    recommendationScore: 79,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-polar-pacer-pro",
      "Polar Pacer Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-polar-vantage-v3", "prod-forerunner-165"],
    alternativeProductIds: ["prod-forerunner-165", "prod-coros-pace-pro"],
    ...pub,
  },

  // ─── Suunto ──────────────────────────────────────────────────────────────
  {
    id: "prod-suunto-race",
    slug: "suunto-race",
    brandId: "brand-suunto",
    familyId: "fam-suunto-race",
    generation: "Race",
    name: "Race",
    fullName: "Suunto Race",
    shortDescription:
      "AMOLED adventure watch with offline maps and strong outdoor battery for trail and ultra.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra", "disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-advanced", "uc-long-runs"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "100 m",
    },
    strengths: ["Offline maps for trail navigation", "Rugged outdoor focus"],
    weaknesses: ["Smaller music ecosystem", "Training coaching less deep than Garmin"],
    recommendationScore: 83,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-suunto-race",
      "Suunto Race — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-suunto-race-s", "prod-coros-apex-2-pro", "prod-forerunner-970"],
    alternativeProductIds: ["prod-coros-apex-2-pro", "prod-forerunner-970"],
    ...pub,
  },
  {
    id: "prod-suunto-race-s",
    slug: "suunto-race-s",
    brandId: "brand-suunto",
    familyId: "fam-suunto-race",
    generation: "Race S",
    name: "Race S",
    fullName: "Suunto Race S",
    shortDescription:
      "Smaller, lighter Suunto Race sibling with AMOLED maps for everyday and trail running.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-compact"],
    useCaseIds: ["uc-intermediate", "uc-trail-training", "uc-marathon"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "100 m",
    },
    strengths: ["Lighter Race form factor", "Maps without flagship bulk"],
    weaknesses: ["Shorter battery than full Race", "Fewer smart features than Apple/Garmin"],
    recommendationScore: 81,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-suunto-race-s",
      "Suunto Race S — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-suunto-race", "prod-coros-pace-pro"],
    alternativeProductIds: ["prod-coros-pace-pro", "prod-forerunner-570"],
    ...pub,
  },

  // ─── Apple ───────────────────────────────────────────────────────────────
  {
    id: "prod-apple-watch-ultra-2",
    slug: "apple-watch-ultra-2",
    brandId: "brand-apple",
    familyId: "fam-apple-watch-ultra",
    generation: "Ultra 2",
    name: "Watch Ultra 2",
    fullName: "Apple Watch Ultra 2",
    shortDescription:
      "Rugged AMOLED smartwatch hybrid for runners already in the Apple ecosystem.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: ["uc-intermediate", "uc-advanced", "uc-daily-training", "uc-half"],
    specifications: {
      weight: null,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "100 m",
    },
    strengths: [
      "Best iPhone integration and apps",
      "Bright always-on display and dual speakers",
    ],
    weaknesses: [
      "Shorter battery than dedicated running watches",
      "Less specialized endurance coaching than Garmin/COROS",
    ],
    recommendationScore: 78,
    valueScore: 70,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-apple-watch-ultra-2",
      "Apple Watch Ultra 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-airpods-pro-2", "prod-forerunner-970"],
    alternativeProductIds: ["prod-forerunner-970", "prod-coros-pace-pro"],
    ...pub,
  },

  // ─── HRM ─────────────────────────────────────────────────────────────────
  {
    id: "prod-hrm-600",
    slug: "garmin-hrm-600",
    brandId: "brand-garmin",
    familyId: "fam-hrm-pro",
    generation: "600",
    name: "HRM 600",
    fullName: "Garmin HRM 600",
    shortDescription:
      "Rechargeable advanced chest strap with running dynamics, standalone recording, and FR970 economy metrics.",
    releaseDate: "2025-05-15",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-running-racing"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest", "sub-hrm-dynamics"],
    useCaseIds: ["uc-advanced", "uc-intervals", "uc-pb", "uc-marathon", "uc-hyrox-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 3,
      battery: "Rechargeable (approx. 2 months per charge — manufacturer claim)",
      batteryType: "rechargeable",
      runningDynamics: true,
      paceDistanceSupport: true,
      standaloneRecording: true,
      swimmingSupport: true,
      internalMemory: true,
      waterResistance: "5 ATM",
      replaceableStrap: true,
    },
    strengths: [
      "Required for FR970 running economy / step speed loss metrics",
      "Rechargeable vs coin-cell straps",
    ],
    weaknesses: ["Chest-strap comfort varies", "Premium accessory cost"],
    recommendationScore: 88,
    valueScore: 72,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-hrm-600",
      "Garmin HRM 600 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-970", "prod-forerunner-570"],
    alternativeProductIds: ["prod-polar-h10", "prod-wahoo-tickr-x"],
    ...pub,
  },
  {
    id: "prod-polar-h10",
    slug: "polar-h10",
    brandId: "brand-polar",
    familyId: "fam-polar-h",
    generation: "H10",
    name: "H10",
    fullName: "Polar H10",
    shortDescription:
      "Benchmark ECG chest strap with dual Bluetooth, ANT+, and one-session memory.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-training", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-advanced", "uc-pb", "uc-intermediate", "uc-hyrox-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 2,
      battery: "Replaceable CR2025 coin cell (~400 h — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      batteryLifeHours: 400,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: true,
      swimmingSupport: true,
      internalMemory: true,
      waterResistance: "30 m",
      replaceableStrap: true,
    },
    strengths: ["Broad device compatibility", "Trusted chest-strap accuracy reputation"],
    weaknesses: ["Coin-cell swaps", "No Garmin-native running dynamics"],
    recommendationScore: 90,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-polar-h10",
      "Polar H10 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-polar-verity-sense", "prod-polar-vantage-v3"],
    alternativeProductIds: ["prod-hrm-600", "prod-wahoo-tickr"],
    ...pub,
  },
  {
    id: "prod-polar-verity-sense",
    slug: "polar-verity-sense",
    brandId: "brand-polar",
    familyId: "fam-polar-verity",
    generation: "Verity Sense",
    name: "Verity Sense",
    fullName: "Polar Verity Sense",
    shortDescription:
      "Optical armband HR monitor for runners who prefer not to wear a chest strap.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-swimming", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-armband", "sub-hrm-optical"],
    useCaseIds: ["uc-intervals", "uc-daily-training", "uc-intermediate", "uc-hyrox-training"],
    specifications: {
      type: "armband",
      placement: "upper-arm",
      sensingMethod: "optical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 2,
      battery: "Rechargeable (~30 h — manufacturer claim)",
      batteryType: "rechargeable",
      batteryLifeHours: 30,
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: true,
      swimmingSupport: true,
      internalMemory: true,
      waterResistance: "20 m",
      replaceableStrap: true,
    },
    strengths: ["Comfortable alternative to chest straps", "Works across many apps/devices"],
    weaknesses: ["Optical HR can lag in intervals vs good chest straps"],
    recommendationScore: 84,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-polar-verity-sense",
      "Polar Verity Sense — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-polar-h10", "prod-coros-hrm"],
    alternativeProductIds: ["prod-coros-hrm", "prod-polar-h10"],
    ...pub,
  },
  {
    id: "prod-wahoo-tickr",
    slug: "wahoo-tickr",
    brandId: "brand-wahoo",
    familyId: "fam-wahoo-tickr",
    generation: "TICKR",
    name: "TICKR",
    fullName: "Wahoo TICKR",
    shortDescription:
      "Previous-generation dual-band chest HR strap — superseded by TRACKR for most new buyers.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-cycling-road", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest"],
    useCaseIds: ["uc-intervals", "uc-intermediate", "uc-daily-training"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      battery: "Replaceable coin cell",
      batteryType: "replaceable-coin-cell",
      runningDynamics: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: "IPX7",
      replaceableStrap: true,
    },
    strengths: ["Simple dual connectivity", "Still useful on clearance vs TRACKR"],
    weaknesses: ["Superseded by TRACKR", "Fewer advanced metrics than TICKR X / Garmin HRM 600"],
    recommendationScore: 74,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-wahoo-tickr",
      "Wahoo TICKR — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-wahoo-trackr", "prod-wahoo-tickr-x"],
    alternativeProductIds: ["prod-wahoo-trackr", "prod-polar-h10", "prod-polar-h9"],
    ...pub,
  },
  {
    id: "prod-wahoo-tickr-x",
    slug: "wahoo-tickr-x",
    brandId: "brand-wahoo",
    familyId: "fam-wahoo-tickr",
    generation: "TICKR X",
    name: "TICKR X",
    fullName: "Wahoo TICKR X",
    shortDescription:
      "Previous-generation chest strap with workout memory — clearance alternative when TRACKR lacks onboard storage.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-track", "disc-training-gym"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest", "sub-hrm-dynamics"],
    useCaseIds: ["uc-intervals", "uc-advanced", "uc-pb"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      battery: "Replaceable coin cell",
      batteryType: "replaceable-coin-cell",
      runningDynamics: false,
      paceDistanceSupport: false,
      standaloneRecording: true,
      swimmingSupport: false,
      internalMemory: true,
      waterResistance: "IPX7",
      replaceableStrap: true,
    },
    strengths: ["Onboard memory for phone-free sessions", "Extra motion/cadence insights"],
    weaknesses: ["Superseded by TRACKR for most buyers", "Not Garmin running-dynamics native"],
    recommendationScore: 76,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-wahoo-tickr-x",
      "Wahoo TICKR X — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-wahoo-trackr", "prod-wahoo-tickr", "prod-polar-h10"],
    alternativeProductIds: ["prod-hrm-600", "prod-polar-h10", "prod-wahoo-trackr"],
    ...pub,
  },
  {
    id: "prod-coros-hrm",
    slug: "coros-heart-rate-monitor",
    brandId: "brand-coros",
    familyId: "fam-coros-hrm",
    generation: "HRM",
    name: "Heart Rate Monitor",
    fullName: "COROS Heart Rate Monitor",
    shortDescription:
      "Optical armband HR monitor designed to pair cleanly with COROS watches and apps.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-track"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-armband", "sub-hrm-optical"],
    useCaseIds: ["uc-intervals", "uc-daily-training", "uc-advanced"],
    specifications: {
      type: "armband",
      placement: "upper-arm",
      connectivity: ["ant+", "bluetooth"],
      battery: "Rechargeable",
      runningDynamics: false,
      swimmingSupport: false,
      internalMemory: false,
      waterResistance: null,
    },
    strengths: ["Comfortable arm placement", "Native COROS pairing"],
    weaknesses: ["Optical accuracy trade-offs vs chest straps in hard intervals"],
    recommendationScore: 81,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-hrm",
      "prod-coros-hrm",
      "COROS Heart Rate Monitor — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-coros-pace-pro", "prod-polar-verity-sense"],
    alternativeProductIds: ["prod-polar-verity-sense", "prod-polar-h10"],
    ...pub,
  },
];
