import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

/**
 * Wave 2 GPS running watches (2024–2026 current market).
 * Broadens the catalog beyond Wave 1 watches-hrm with adventure flagships,
 * ultra-battery MIP options, lifestyle AMOLEDs, value COROS/Amazfit, and
 * previous-gen Forerunner/Epix clearance peers. Heroes registered via
 * catalog-product-media + public/images/watches/products/.
 *
 * Products: Fenix 8, Enduro 3, Instinct 3, Vivoactive 6, COROS Apex 4 / Pace 4 /
 * Vertix 2S, Suunto Vertical 2 / Run, Polar Grit X2 / Pacer, Apple Watch Ultra 3 /
 * Series 10, Galaxy Watch Ultra, Amazfit T-Rex 3 Pro / Active 2, Forerunner 265S,
 * Epix Pro Gen 2.
 */
export const runningWatchesWave2: Product[] = [
  // ─── Garmin ──────────────────────────────────────────────────────────────
  {
    id: "prod-fenix-8",
    slug: "garmin-fenix-8",
    brandId: "brand-garmin",
    familyId: "fam-fenix",
    generation: "8",
    name: "Fenix 8 AMOLED 47mm",
    fullName: "Garmin Fenix 8 AMOLED 47mm",
    shortDescription:
      "Adventure multisport flagship with bright AMOLED maps, multi-band GPS, music, payments, and ECG.",
    releaseDate: "2024-08-27",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-ultra",
      "disc-running-racing",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-advanced",
      "uc-ultra",
      "uc-trail-training",
      "uc-high-mileage",
      "uc-marathon",
    ],
    specifications: {
      weight: 73,
      displayType: "amoled",
      displaySize: 1.4,
      touchscreen: true,
      caseSizeMm: 47,
      solar: false,
      batterySmartwatch: 16,
      batteryGps: 37,
      batteryMultiBand: 35,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Full TopoActive maps on a bright always-on-capable AMOLED",
      "ECG, dive-ready build, speaker/mic, and Garmin Pay in one chassis",
      "Deep Garmin training, recovery, and multi-sport ecosystem",
    ],
    weaknesses: [
      "Premium price versus dedicated ultra-battery MIP watches",
      "Heavier and thicker than running-focused Forerunners",
    ],
    recommendationScore: 92,
    valueScore: 64,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-fenix-8",
      "Garmin Fenix 8 AMOLED 47mm — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-enduro-3",
      "prod-garmin-epix-pro-gen2",
      "prod-forerunner-970",
    ],
    alternativeProductIds: [
      "prod-enduro-3",
      "prod-coros-apex-4",
      "prod-suunto-vertical-2",
    ],
    ...pub,
  },
  {
    id: "prod-enduro-3",
    slug: "garmin-enduro-3",
    brandId: "brand-garmin",
    familyId: "fam-enduro",
    generation: "3",
    name: "Enduro 3",
    fullName: "Garmin Enduro 3",
    shortDescription:
      "Ultralight MIP solar ultra watch with maps, multi-band GNSS, and class-leading GPS endurance.",
    releaseDate: "2024-08-27",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-ultra",
      "disc-running-trail",
      "disc-running-road",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-ultra",
      "uc-trail-training",
      "uc-advanced",
      "uc-high-mileage",
      "uc-long-runs",
    ],
    specifications: {
      weight: 63,
      displayType: "mip",
      displaySize: 1.4,
      touchscreen: false,
      caseSizeMm: 51,
      solar: true,
      batterySmartwatch: 36,
      batteryGps: 120,
      batteryMultiBand: 60,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Extremely long GPS battery with Power Sapphire solar",
      "Light 63 g UltraFit build for multi-day ultras",
      "TopoActive maps without Fenix bulk or AMOLED drain",
    ],
    weaknesses: [
      "MIP is less vivid indoors than AMOLED flagships",
      "No speaker/mic or ECG versus Fenix 8",
    ],
    recommendationScore: 88,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-enduro-3",
      "Garmin Enduro 3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-fenix-8",
      "prod-coros-vertix-2s",
      "prod-forerunner-970",
    ],
    alternativeProductIds: [
      "prod-fenix-8",
      "prod-coros-vertix-2s",
      "prod-suunto-vertical-2",
    ],
    ...pub,
  },
  {
    id: "prod-instinct-3",
    slug: "garmin-instinct-3",
    brandId: "brand-garmin",
    familyId: "fam-instinct",
    generation: "3",
    name: "Instinct 3",
    fullName: "Garmin Instinct 3",
    shortDescription:
      "Rugged adventure watch (MIP Solar or AMOLED) with strong battery, flashlight, and outdoor tools.",
    releaseDate: "2025-04-03",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: ["disc-running-trail", "disc-running-road", "disc-running-ultra"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-trail-training",
      "uc-intermediate",
      "uc-advanced",
      "uc-long-runs",
    ],
    specifications: {
      weight: 52,
      displayType: "mip",
      displaySize: null,
      touchscreen: false,
      caseSizeMm: 45,
      solar: true,
      batterySmartwatch: 24,
      batteryGps: 40,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: false,
      offlineMaps: false,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: true,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Tough fiber-reinforced case and metal-reinforced bezel",
      "Excellent stated battery, especially with Solar charging",
      "Adventure tools (flashlight, ABC sensors) below Fenix pricing",
    ],
    weaknesses: [
      "No full offline maps like Enduro/Fenix",
      "Fewer smart features (music/payments) than lifestyle Garmins",
    ],
    recommendationScore: 82,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-instinct-3",
      "Garmin Instinct 3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-enduro-3",
      "prod-amazfit-t-rex-3-pro",
      "prod-fenix-8",
    ],
    alternativeProductIds: [
      "prod-amazfit-t-rex-3-pro",
      "prod-enduro-3",
      "prod-coros-apex-4",
    ],
    ...pub,
  },
  {
    id: "prod-vivoactive-6",
    slug: "garmin-vivoactive-6",
    brandId: "brand-garmin",
    familyId: "fam-vivoactive",
    generation: "6",
    name: "Vivoactive 6",
    fullName: "Garmin Vivoactive 6",
    shortDescription:
      "Lightweight AMOLED lifestyle-plus-running watch with Garmin Coach plans and broad sport apps.",
    releaseDate: "2025-04-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: [
      "uc-beginners",
      "uc-intermediate",
      "uc-daily-training",
      "uc-first-half",
      "uc-half",
    ],
    specifications: {
      weight: 23,
      displayType: "amoled",
      displaySize: 1.2,
      touchscreen: true,
      caseSizeMm: 42,
      solar: false,
      batterySmartwatch: 11,
      batteryGps: 20,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: false,
      offlineMaps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: false,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Very light daily wear with a bright AMOLED",
      "Garmin Coach running and strength plans in a mid price band",
      "Music and Garmin Pay without Forerunner complexity",
    ],
    weaknesses: [
      "Shorter GPS battery than dedicated running watches",
      "No full maps or deepest advanced training metrics",
    ],
    recommendationScore: 78,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-vivoactive-6",
      "Garmin Vivoactive 6 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-forerunner-165",
      "prod-forerunner-570",
      "prod-amazfit-active-2",
    ],
    alternativeProductIds: [
      "prod-forerunner-165",
      "prod-coros-pace-4",
      "prod-suunto-run",
    ],
    ...pub,
  },
  {
    id: "prod-forerunner-265s",
    slug: "garmin-forerunner-265s",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "265S",
    name: "Forerunner 265S",
    fullName: "Garmin Forerunner 265S",
    shortDescription:
      "Compact previous-generation AMOLED Forerunner midrange—still a strong clearance pick for smaller wrists.",
    releaseDate: "2023-03-01",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-compact"],
    useCaseIds: [
      "uc-intermediate",
      "uc-half",
      "uc-marathon",
      "uc-beginners",
    ],
    specifications: {
      weight: 39,
      displayType: "amoled",
      displaySize: 1.1,
      touchscreen: true,
      caseSizeMm: 42,
      solar: false,
      batterySmartwatch: 15,
      batteryGps: 24,
      batteryMultiBand: 15,
      multiBandGps: true,
      maps: false,
      offlineMaps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Smaller 42 mm AMOLED fit without losing Forerunner training tools",
      "Strong clearance value after the 570 launch",
      "Multi-band GPS with music and Garmin Pay",
    ],
    weaknesses: [
      "Superseded by Forerunner 570 / 570S",
      "No full offline maps",
    ],
    recommendationScore: 80,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-forerunner-265s",
      "Garmin Forerunner 265S — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-forerunner-265",
      "prod-forerunner-570",
      "prod-coros-pace-4",
    ],
    alternativeProductIds: [
      "prod-forerunner-570",
      "prod-forerunner-265",
      "prod-coros-pace-4",
    ],
    ...pub,
  },
  {
    id: "prod-garmin-epix-pro-gen2",
    slug: "garmin-epix-pro-gen-2",
    brandId: "brand-garmin",
    familyId: "fam-epix",
    generation: "Pro Gen 2",
    name: "Epix Pro (Gen 2)",
    fullName: "Garmin Epix Pro (Gen 2)",
    shortDescription:
      "Previous-generation AMOLED maps flagship—now a value adventure buy versus Fenix 8.",
    releaseDate: "2023-05-01",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-road",
      "disc-running-ultra",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-advanced",
      "uc-trail-training",
      "uc-ultra",
      "uc-marathon",
      "uc-high-mileage",
    ],
    specifications: {
      weight: 70,
      displayType: "amoled",
      displaySize: 1.3,
      touchscreen: true,
      caseSizeMm: 47,
      solar: false,
      batterySmartwatch: 16,
      batteryGps: 42,
      batteryMultiBand: 20,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "AMOLED maps experience close to current Fenix at clearance prices",
      "ECG, flashlight, and full Garmin coaching stack",
      "Proven sapphire multi-band adventure build",
    ],
    weaknesses: [
      "Replaced by Fenix 8 AMOLED in the lineup",
      "Multi-band GPS battery shorter than Enduro / Fenix 8",
    ],
    recommendationScore: 83,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-garmin-epix-pro-gen2",
      "Garmin Epix Pro Gen 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-fenix-8",
      "prod-forerunner-970",
      "prod-enduro-3",
    ],
    alternativeProductIds: [
      "prod-fenix-8",
      "prod-suunto-vertical-2",
      "prod-coros-apex-4",
    ],
    ...pub,
  },

  // ─── COROS ───────────────────────────────────────────────────────────────
  {
    id: "prod-coros-apex-4",
    slug: "coros-apex-4",
    brandId: "brand-coros",
    familyId: "fam-coros-apex",
    generation: "4",
    name: "Apex 4",
    fullName: "COROS Apex 4",
    shortDescription:
      "Titanium MIP mountain watch with offline maps, dual-frequency GPS, and long endurance battery.",
    releaseDate: "2025-10-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-ultra",
      "disc-running-road",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-ultra",
      "uc-trail-training",
      "uc-advanced",
      "uc-high-mileage",
      "uc-long-runs",
    ],
    specifications: {
      weight: 52,
      displayType: "mip",
      displaySize: 1.3,
      touchscreen: false,
      caseSizeMm: 46,
      solar: false,
      batterySmartwatch: 24,
      batteryGps: 53,
      batteryMultiBand: 41,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Full offline topo/street maps on a durable sapphire MIP",
      "Strong dual-frequency GPS battery on the 46 mm size",
      "Titanium bezel build lighter than Vertix for most trail days",
    ],
    weaknesses: [
      "No music storage or contactless payments",
      "Smaller third-party app ecosystem than Garmin",
    ],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-coros-apex-4",
      "COROS Apex 4 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-coros-vertix-2s",
      "prod-coros-pace-4",
      "prod-coros-apex-2-pro",
    ],
    alternativeProductIds: [
      "prod-fenix-8",
      "prod-suunto-vertical-2",
      "prod-enduro-3",
    ],
    ...pub,
  },
  {
    id: "prod-coros-pace-4",
    slug: "coros-pace-4",
    brandId: "brand-coros",
    familyId: "fam-coros-pace",
    generation: "4",
    name: "Pace 4",
    fullName: "COROS Pace 4",
    shortDescription:
      "Ultralight AMOLED value runner with dual-frequency GPS and standout stated battery for the price.",
    releaseDate: "2025-11-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-racing",
      "disc-running-trail",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-compact"],
    useCaseIds: [
      "uc-intermediate",
      "uc-advanced",
      "uc-marathon",
      "uc-high-mileage",
      "uc-half",
    ],
    specifications: {
      weight: 32,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: null,
      solar: false,
      batterySmartwatch: 19,
      batteryGps: 41,
      batteryMultiBand: 31,
      multiBandGps: true,
      maps: false,
      offlineMaps: false,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Just 32 g with nylon band—easy all-day racing weight",
      "41 hours all-systems / 31 hours dual-frequency GPS claims",
      "Strong price-to-performance versus mid Garmin Forerunners",
    ],
    weaknesses: [
      "No full offline maps (step up to Apex 4 / Pace Pro)",
      "No music or payments",
    ],
    recommendationScore: 86,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-coros-pace-4",
      "COROS Pace 4 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-coros-pace-pro",
      "prod-coros-apex-4",
      "prod-forerunner-570",
    ],
    alternativeProductIds: [
      "prod-coros-pace-pro",
      "prod-forerunner-570",
      "prod-forerunner-265s",
    ],
    ...pub,
  },
  {
    id: "prod-coros-vertix-2s",
    slug: "coros-vertix-2s",
    brandId: "brand-coros",
    familyId: "fam-coros-vertix",
    generation: "2S",
    name: "Vertix 2S",
    fullName: "COROS Vertix 2S",
    shortDescription:
      "Extreme-battery sapphire adventure watch built for ultras, mountaineering, and multi-day expeditions.",
    releaseDate: "2024-03-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-ultra",
      "disc-running-trail",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-ultra",
      "uc-trail-training",
      "uc-advanced",
      "uc-high-mileage",
    ],
    specifications: {
      weight: 87,
      displayType: "mip",
      displaySize: 1.4,
      touchscreen: false,
      caseSizeMm: 50,
      solar: false,
      batterySmartwatch: 40,
      batteryGps: 118,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Among the longest GPS battery claims in the adventure class",
      "Full-metal rugged case with sapphire glass",
      "Offline maps suited to remote ultra and alpine routes",
    ],
    weaknesses: [
      "Heavier than Apex 4 / Enduro for pure road racing",
      "Aging versus newer Apex 4 feature set",
    ],
    recommendationScore: 89,
    valueScore: 76,
    experienceLevels: ["advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-coros-vertix-2s",
      "COROS Vertix 2S — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-coros-apex-4",
      "prod-enduro-3",
      "prod-suunto-vertical-2",
    ],
    alternativeProductIds: [
      "prod-enduro-3",
      "prod-fenix-8",
      "prod-suunto-vertical-2",
    ],
    ...pub,
  },

  // ─── Suunto ──────────────────────────────────────────────────────────────
  {
    id: "prod-suunto-vertical-2",
    slug: "suunto-vertical-2",
    brandId: "brand-suunto",
    familyId: "fam-suunto-vertical",
    generation: "2",
    name: "Vertical 2",
    fullName: "Suunto Vertical 2",
    shortDescription:
      "Outdoor AMOLED adventure watch with offline maps, dual-band GPS, LED flashlight, and long training battery.",
    releaseDate: "2025-09-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-ultra",
      "disc-running-road",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-trail-training",
      "uc-ultra",
      "uc-advanced",
      "uc-long-runs",
    ],
    specifications: {
      weight: 74,
      displayType: "amoled",
      displaySize: 1.5,
      touchscreen: true,
      caseSizeMm: 49,
      solar: false,
      batterySmartwatch: 20,
      batteryGps: 65,
      batteryMultiBand: 65,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "100 m",
    },
    strengths: [
      "Bright 1.5″ AMOLED with free offline outdoor maps",
      "Up to 65 hours in multi-band performance tracking",
      "Built-in LED flashlight and climb-focused navigation tools",
    ],
    weaknesses: [
      "Training coaching less deep than Garmin/Polar flagships",
      "No onboard music storage",
    ],
    recommendationScore: 85,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-suunto-vertical-2",
      "Suunto Vertical 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-suunto-race",
      "prod-coros-apex-4",
      "prod-fenix-8",
    ],
    alternativeProductIds: [
      "prod-fenix-8",
      "prod-coros-apex-4",
      "prod-polar-grit-x2",
    ],
    ...pub,
  },
  {
    id: "prod-suunto-run",
    slug: "suunto-run",
    brandId: "brand-suunto",
    familyId: "fam-suunto-run",
    generation: "1",
    name: "Run",
    fullName: "Suunto Run",
    shortDescription:
      "Beginner-friendly AMOLED running watch around $200 with dual-band GPS and simple recovery tools.",
    releaseDate: "2025-06-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: [
      "uc-beginners",
      "uc-first-5k",
      "uc-first-10k",
      "uc-first-half",
      "uc-intermediate",
    ],
    specifications: {
      weight: 36,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: null,
      solar: false,
      batterySmartwatch: 12,
      batteryGps: 20,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: false,
      offlineMaps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: false,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Light 36 g AMOLED daily runner at an entry price",
      "Dual-band GPS unusual at this budget",
      "Simple crown UI and run-specific tools (intervals, Ghost Runner)",
    ],
    weaknesses: [
      "Training battery (~20 h) shorter than COROS Pace class",
      "No maps, music, or deep multisport stack",
    ],
    recommendationScore: 76,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-suunto-run",
      "Suunto Run — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-suunto-race-s",
      "prod-coros-pace-4",
      "prod-forerunner-165",
    ],
    alternativeProductIds: [
      "prod-coros-pace-4",
      "prod-amazfit-active-2",
      "prod-polar-pacer",
    ],
    ...pub,
  },

  // ─── Polar ───────────────────────────────────────────────────────────────
  {
    id: "prod-polar-grit-x2",
    slug: "polar-grit-x2",
    brandId: "brand-polar",
    familyId: "fam-polar-grit",
    generation: "X2",
    name: "Grit X2",
    fullName: "Polar Grit X2",
    shortDescription:
      "Compact outdoor Polar challenger with sapphire AMOLED, dual-frequency GPS, and full-color maps.",
    releaseDate: "2025-01-15",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-road",
      "disc-running-ultra",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-trail-training",
      "uc-advanced",
      "uc-marathon",
      "uc-intermediate",
    ],
    specifications: {
      weight: 62,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: null,
      solar: false,
      batterySmartwatch: 7,
      batteryGps: 30,
      batteryMultiBand: 30,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Polar training/recovery analytics with outdoor maps",
      "Sapphire AMOLED and dual-frequency GPS in a compact chassis",
      "Military-grade durability claims for trail abuse",
    ],
    weaknesses: [
      "Smartwatch battery (~7 days) shorter than Garmin/COROS peers",
      "No music or payments",
    ],
    recommendationScore: 84,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-polar-grit-x2",
      "Polar Grit X2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-polar-vantage-v3",
      "prod-suunto-vertical-2",
      "prod-fenix-8",
    ],
    alternativeProductIds: [
      "prod-polar-vantage-v3",
      "prod-suunto-race",
      "prod-coros-apex-4",
    ],
    ...pub,
  },
  {
    id: "prod-polar-pacer",
    slug: "polar-pacer",
    brandId: "brand-polar",
    familyId: "fam-polar-pacer",
    generation: "1",
    name: "Pacer",
    fullName: "Polar Pacer",
    shortDescription:
      "Entry Polar GPS running watch focused on accurate training guidance without adventure bulk.",
    releaseDate: "2022-04-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: [
      "uc-beginners",
      "uc-first-5k",
      "uc-first-10k",
      "uc-intermediate",
      "uc-half",
    ],
    specifications: {
      weight: 40,
      displayType: "mip",
      displaySize: null,
      touchscreen: false,
      caseSizeMm: null,
      solar: false,
      batterySmartwatch: 7,
      batteryGps: 35,
      batteryMultiBand: null,
      multiBandGps: false,
      maps: false,
      offlineMaps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: false,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: false,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Simple Polar Flow coaching at an accessible price",
      "Light MIP runner that prioritizes training metrics",
      "Solid GPS training battery for weekly mileage",
    ],
    weaknesses: [
      "No maps, multi-band GPS, or music",
      "Fewer lifestyle features than AMOLED beginners’ watches",
    ],
    recommendationScore: 73,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-polar-pacer",
      "Polar Pacer — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-polar-pacer-pro",
      "prod-forerunner-165",
      "prod-suunto-run",
    ],
    alternativeProductIds: [
      "prod-polar-pacer-pro",
      "prod-coros-pace-4",
      "prod-suunto-run",
    ],
    ...pub,
  },

  // ─── Apple ───────────────────────────────────────────────────────────────
  {
    id: "prod-apple-watch-ultra-3",
    slug: "apple-watch-ultra-3",
    brandId: "brand-apple",
    familyId: "fam-apple-watch-ultra",
    generation: "Ultra 3",
    name: "Watch Ultra 3",
    fullName: "Apple Watch Ultra 3",
    shortDescription:
      "Best smartwatch for runners in the Apple ecosystem—bright rugged display, dual-frequency GPS, shorter dedicated GPS battery.",
    releaseDate: "2025-09-01",
    lifecycleStatus: "current",
    sportIds: [
      "sport-running",
      "sport-cycling",
      "sport-swimming",
      "sport-training",
    ],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-intermediate",
      "uc-advanced",
      "uc-daily-training",
      "uc-half",
      "uc-marathon",
    ],
    specifications: {
      weight: 61.6,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: 49,
      solar: false,
      batterySmartwatch: 2,
      batteryGps: 14,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "100 m",
    },
    strengths: [
      "Best iPhone app ecosystem, Apple Pay, and cellular options",
      "Rugged titanium build with dual-frequency GPS and siren",
      "Multiday claim (~42 h normal / 72 h Low Power) beats Series watches",
    ],
    weaknesses: [
      "Still shorter continuous GPS endurance than Garmin/COROS ultras",
      "Less specialized long-term training coaching than dedicated run watches",
    ],
    recommendationScore: 87,
    valueScore: 68,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-apple-watch-ultra-3",
      "Apple Watch Ultra 3 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-apple-watch-ultra-2",
      "prod-apple-watch-series-10",
      "prod-forerunner-970",
    ],
    alternativeProductIds: [
      "prod-fenix-8",
      "prod-forerunner-970",
      "prod-samsung-galaxy-watch-ultra",
    ],
    ...pub,
  },
  {
    id: "prod-apple-watch-series-10",
    slug: "apple-watch-series-10",
    brandId: "brand-apple",
    familyId: "fam-apple-watch",
    generation: "Series 10",
    name: "Watch Series 10",
    fullName: "Apple Watch Series 10",
    shortDescription:
      "Daily Apple smartwatch for casual runners who want metrics, apps, and payments more than multi-day GPS.",
    releaseDate: "2024-09-20",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-swimming"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-compact"],
    useCaseIds: [
      "uc-beginners",
      "uc-daily-training",
      "uc-first-5k",
      "uc-first-10k",
    ],
    specifications: {
      weight: 30,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: 42,
      solar: false,
      batterySmartwatch: 1,
      batteryGps: 8,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: false,
      stravaSync: true,
      waterRating: "50 m",
    },
    strengths: [
      "Thinnest modern Apple Watch with excellent everyday UX",
      "Seamless health, notifications, and Apple Pay for iPhone users",
      "Capable GPS for shorter runs and races",
    ],
    weaknesses: [
      "Daily charging—poor fit for ultras or multi-day events",
      "Not a specialized endurance coaching platform",
    ],
    recommendationScore: 74,
    valueScore: 70,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-apple-watch-series-10",
      "Apple Watch Series 10 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-apple-watch-ultra-3",
      "prod-vivoactive-6",
      "prod-forerunner-165",
    ],
    alternativeProductIds: [
      "prod-apple-watch-ultra-3",
      "prod-vivoactive-6",
      "prod-coros-pace-4",
    ],
    ...pub,
  },

  // ─── Samsung ─────────────────────────────────────────────────────────────
  {
    id: "prod-samsung-galaxy-watch-ultra",
    slug: "samsung-galaxy-watch-ultra",
    brandId: "brand-samsung",
    familyId: "fam-galaxy-watch",
    generation: "Ultra 2025",
    name: "Galaxy Watch Ultra",
    fullName: "Samsung Galaxy Watch Ultra",
    shortDescription:
      "Samsung’s titanium flagship sport watch with dual-frequency GPS, sapphire AMOLED, and Galaxy AI insights.",
    releaseDate: "2025-07-25",
    lifecycleStatus: "current",
    sportIds: [
      "sport-running",
      "sport-cycling",
      "sport-swimming",
      "sport-training",
    ],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-intermediate",
      "uc-advanced",
      "uc-daily-training",
      "uc-trail-training",
    ],
    specifications: {
      weight: 60.5,
      displayType: "amoled",
      displaySize: 1.47,
      touchscreen: true,
      caseSizeMm: 47,
      solar: false,
      batterySmartwatch: 3,
      batteryGps: 48,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Rugged titanium + sapphire with L1/L5 dual-frequency GPS",
      "Strong Galaxy phone integration and Wear OS apps",
      "Exercise power-saving GPS claims up to ~48 hours",
    ],
    weaknesses: [
      "Best experience locked to Samsung/Android phones",
      "Shorter everyday battery than MIP ultra watches",
    ],
    recommendationScore: 80,
    valueScore: 72,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-samsung-galaxy-watch-ultra",
      "Samsung Galaxy Watch Ultra — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-apple-watch-ultra-3",
      "prod-samsung-galaxy-watch-ultra-2",
      "prod-fenix-8",
      "prod-polar-grit-x2",
    ],
    alternativeProductIds: [
      "prod-apple-watch-ultra-3",
      "prod-fenix-8",
      "prod-amazfit-t-rex-3-pro",
    ],
    ...pub,
  },

  // ─── Amazfit ─────────────────────────────────────────────────────────────
  {
    id: "prod-amazfit-t-rex-3-pro",
    slug: "amazfit-t-rex-3-pro",
    brandId: "brand-amazfit",
    familyId: "fam-amazfit-t-rex",
    generation: "3 Pro",
    name: "T-Rex 3 Pro",
    fullName: "Amazfit T-Rex 3 Pro",
    shortDescription:
      "Value rugged AMOLED GPS watch with long stated battery for trail and adventure without flagship pricing.",
    releaseDate: "2025-09-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-cycling"],
    disciplineIds: [
      "disc-running-trail",
      "disc-running-road",
      "disc-running-ultra",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-trail-training",
      "uc-intermediate",
      "uc-beginners",
      "uc-long-runs",
    ],
    specifications: {
      weight: 59,
      displayType: "amoled",
      displaySize: 1.5,
      touchscreen: true,
      caseSizeMm: 48,
      solar: false,
      batterySmartwatch: 25,
      batteryGps: 38,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Rugged adventure styling at a value price",
      "Long typical-use and GPS battery claims for the money",
      "Bright large AMOLED with offline route tools",
    ],
    weaknesses: [
      "Training ecosystem less mature than Garmin/COROS/Polar",
      "Optical HR and maps polish trail flagships",
    ],
    recommendationScore: 79,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-amazfit-t-rex-3-pro",
      "Amazfit T-Rex 3 Pro — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-instinct-3",
      "prod-amazfit-active-2",
      "prod-amazfit-balance-3",
      "prod-coros-apex-4",
    ],
    alternativeProductIds: [
      "prod-instinct-3",
      "prod-suunto-vertical-2",
      "prod-samsung-galaxy-watch-ultra",
    ],
    ...pub,
  },
  {
    id: "prod-amazfit-active-2",
    slug: "amazfit-active-2",
    brandId: "brand-amazfit",
    familyId: "fam-amazfit-active",
    generation: "2",
    name: "Active 2",
    fullName: "Amazfit Active 2",
    shortDescription:
      "Budget entry AMOLED runner for first GPS miles, daily activity, and basic training tracking.",
    releaseDate: "2024-10-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-entry"],
    useCaseIds: [
      "uc-beginners",
      "uc-first-5k",
      "uc-first-10k",
      "uc-daily-training",
    ],
    specifications: {
      weight: 27,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      caseSizeMm: null,
      solar: false,
      batterySmartwatch: 10,
      batteryGps: 22,
      batteryMultiBand: null,
      multiBandGps: false,
      maps: false,
      offlineMaps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: false,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Low entry price for a bright AMOLED GPS watch",
      "Light daily wear for new runners",
      "Decent stated battery versus phone-armband apps",
    ],
    weaknesses: [
      "Accuracy and coaching lag dedicated running brands",
      "Limited navigation and multisport depth",
    ],
    recommendationScore: 72,
    valueScore: 90,
    experienceLevels: ["beginner"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-amazfit-active-2",
      "Amazfit Active 2 — catalog placeholder",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amazfit-t-rex-3-pro",
      "prod-amazfit-cheetah-2-pro",
      "prod-suunto-run",
      "prod-forerunner-165",
    ],
    alternativeProductIds: [
      "prod-suunto-run",
      "prod-polar-pacer",
      "prod-vivoactive-6",
    ],
    ...pub,
  },
];
