/**
 * Fix 75 — current Amazfit and Samsung Running GPS watches.
 * Specs from manufacturer pages 2026-09-10. Unpublished GPS hours stay null.
 */

import type { Product } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

/**
 * Sources (manufacturer, 2026-09-10):
 * - Balance 3: https://us.amazfit.com/products/balance-3
 *   1.5" AMOLED sapphire, dual-band 6-satellite GNSS, 64GB contour maps,
 *   HybridCharge, HYROX modes, flashlight, 10 ATM.
 *   Weight without strap: Titanium Black 55 g / Stainless 62 g (primary = titanium).
 *   Case 51.4×51.4 mm. Typical 21 days; Accuracy GPS 41 h; Power-saving GPS 84 h.
 * - Cheetah 2 Pro: https://us.amazfit.com/products/cheetah-2-pro
 *   Grade 5 titanium, 1.32" AMOLED 3000 nits, 48×48 mm, 45.6 g without strap,
 *   dual-band GNSS, 32GB offline maps, Zepp Coach 5K–marathon, gait / running
 *   power / lactate threshold, flashlight, 5 ATM.
 *   Typical 20 days; Accurate GPS 31 h; GPS+music 15 h; Power-saving GPS 69 h.
 * - Galaxy Watch Ultra2: Samsung Unpacked Jul 2026 product pages
 *   47 mm, 61.5 g, 1.52" Super AMOLED to 5000 nits, Snapdragon Wear Elite,
 *   800 mAh, IP69K + 10 ATM, L1+L5 dual GPS, 64GB, Running Coach.
 *   Smartwatch usage claimed up to 60 h AOD on. Dedicated GPS hours not published.
 * - Galaxy Watch9: Samsung Watch9 40 mm primary
 *   31.5 g, 1.3", 390 mAh, up to 40 h AOD off / 30 h AOD on, dual GPS, NFC, Wear OS.
 *   Variant: 44 mm 34 g / 445 mAh. Dedicated GPS hours not published.
 *
 * Not ingested: Bip (lifestyle), T-Rex 3 non-Pro (overlap with 3 Pro),
 * T-Rex Ultra 2, Balance Ultra, Balance 2, Watch8 (discontinued 2026-07-22),
 * Watch FE, Classic / LTE duplicate SKUs.
 */
export const runningWatchesP75Gaps: Product[] = [
  {
    id: "prod-amazfit-balance-3",
    slug: "amazfit-balance-3",
    brandId: "brand-amazfit",
    familyId: "fam-amazfit-balance",
    generation: "3",
    name: "Balance 3",
    fullName: "Amazfit Balance 3",
    shortDescription:
      "Amazfit’s current hybrid-training GPS watch — 1.5\" sapphire AMOLED, dual-band six-system GNSS, 64GB contour maps, HybridCharge, and HYROX modes — for mixed run/strength weeks without Garmin flagship money.",
    releaseDate: "2026-01-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: [
      "uc-daily-training",
      "uc-intermediate",
      "uc-hyrox-training",
      "uc-half",
      "uc-marathon",
    ],
    specifications: {
      weight: 55,
      displayType: "amoled",
      displaySize: 1.5,
      touchscreen: true,
      caseSizeMm: 51,
      solar: false,
      batterySmartwatch: 21,
      batteryGps: 41,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "1.5\" sapphire AMOLED with preloaded contour maps and turn-by-turn",
      "Dual-band six-system GNSS plus HybridCharge for mixed training weeks",
      "HYROX sport modes on a value hybrid chassis versus Fenix/Vivoactive money",
    ],
    weaknesses: [
      "51 mm case and Zepp coaching still trail Garmin Connect for serious periodization",
      "Contactless payments not documented — not an Apple/Samsung daily-pay watch",
    ],
    recommendationScore: 82,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-amazfit-balance-3",
      "Amazfit Balance 3 — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amazfit-cheetah-2-pro",
      "prod-amazfit-t-rex-3-pro",
      "prod-vivoactive-6",
    ],
    alternativeProductIds: [
      "prod-vivoactive-6",
      "prod-forerunner-570",
      "prod-amazfit-cheetah-2-pro",
    ],
    ...pub,
  },
  {
    id: "prod-amazfit-cheetah-2-pro",
    slug: "amazfit-cheetah-2-pro",
    brandId: "brand-amazfit",
    familyId: "fam-amazfit-cheetah",
    generation: "2 Pro",
    name: "Cheetah 2 Pro",
    fullName: "Amazfit Cheetah 2 Pro",
    shortDescription:
      "Amazfit’s dedicated runner — Grade 5 titanium, 45.6 g without strap, 1.32\" 3000-nit AMOLED, dual-band GNSS, 32GB offline maps, and Zepp Coach from 5K to marathon with gait, running power and lactate-threshold tools.",
    releaseDate: "2026-01-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: [
      "disc-running-road",
      "disc-running-racing",
      "disc-running-trail",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: [
      "uc-daily-training",
      "uc-5k",
      "uc-half",
      "uc-marathon",
      "uc-advanced",
    ],
    specifications: {
      weight: 45.6,
      displayType: "amoled",
      displaySize: 1.32,
      touchscreen: true,
      caseSizeMm: 48,
      solar: false,
      batterySmartwatch: 20,
      batteryGps: 31,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Titanium runner-first chassis at 45.6 g without strap",
      "Zepp Coach 5K–marathon plus gait, running power and lactate threshold",
      "Dual-band GNSS with 32GB offline maps at a mid-pack Amazfit price",
    ],
    weaknesses: [
      "5 ATM and no documented payments — not a swim/pay daily smartwatch",
      "Training ecosystem still Zepp, not Garmin Connect or COROS Training Hub",
    ],
    recommendationScore: 84,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-amazfit-cheetah-2-pro",
      "Amazfit Cheetah 2 Pro — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-amazfit-balance-3",
      "prod-coros-pace-4",
      "prod-forerunner-570",
    ],
    alternativeProductIds: [
      "prod-coros-pace-4",
      "prod-forerunner-570",
      "prod-amazfit-balance-3",
    ],
    ...pub,
  },
  {
    id: "prod-samsung-galaxy-watch-ultra-2",
    slug: "samsung-galaxy-watch-ultra-2",
    brandId: "brand-samsung",
    familyId: "fam-galaxy-watch",
    generation: "Ultra2",
    name: "Galaxy Watch Ultra2",
    fullName: "Samsung Galaxy Watch Ultra2",
    shortDescription:
      "Samsung’s 2026 titanium adventure Wear OS watch — 47 mm, 61.5 g, 1.52\" Super AMOLED to 5000 nits, L1+L5 dual GPS, 64GB, IP69K / 10 ATM, Running Coach — for Galaxy athletes who want a rugged smartwatch more than a MIP ultra trainer.",
    releaseDate: "2026-07-01",
    lifecycleStatus: "current",
    sportIds: [
      "sport-running",
      "sport-cycling",
      "sport-swimming",
      "sport-training",
    ],
    disciplineIds: [
      "disc-running-road",
      "disc-running-trail",
      "disc-running-racing",
    ],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-ultra-adventure"],
    useCaseIds: [
      "uc-daily-training",
      "uc-intermediate",
      "uc-advanced",
      "uc-trail-training",
    ],
    specifications: {
      weight: 61.5,
      displayType: "amoled",
      displaySize: 1.52,
      touchscreen: true,
      caseSizeMm: 47,
      solar: false,
      batterySmartwatch: 2.5,
      batteryGps: null,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "10 ATM",
    },
    strengths: [
      "Titanium 47 mm chassis with 5000-nit Super AMOLED and IP69K / 10 ATM",
      "L1+L5 dual GPS plus 64GB Wear OS maps, music and Samsung Pay",
      "Running Coach on the current Galaxy Health stack for Android athletes",
    ],
    weaknesses: [
      "Dedicated GPS hours unpublished — not an Enduro/Vertix battery tool",
      "Best experience locked to Samsung/Android; iPhone and Garmin coaching still win elsewhere",
    ],
    recommendationScore: 81,
    valueScore: 68,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-samsung-galaxy-watch-ultra-2",
      "Samsung Galaxy Watch Ultra2 — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-samsung-galaxy-watch-ultra",
      "prod-samsung-galaxy-watch-9",
      "prod-apple-watch-ultra-3",
    ],
    alternativeProductIds: [
      "prod-apple-watch-ultra-3",
      "prod-fenix-8",
      "prod-samsung-galaxy-watch-ultra",
    ],
    ...pub,
  },
  {
    id: "prod-samsung-galaxy-watch-9",
    slug: "samsung-galaxy-watch-9",
    brandId: "brand-samsung",
    familyId: "fam-galaxy-watch",
    generation: "Watch9",
    name: "Galaxy Watch9",
    fullName: "Samsung Galaxy Watch9",
    shortDescription:
      "Samsung’s current daily Wear OS runner — 40 mm / 31.5 g primary with dual GPS, NFC, Galaxy Health and Running Coach — for Galaxy-phone athletes who want a compact smartwatch more than a dedicated Forerunner.",
    releaseDate: "2026-07-01",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-training", "sport-swimming"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-compact"],
    useCaseIds: [
      "uc-beginners",
      "uc-daily-training",
      "uc-first-5k",
      "uc-first-10k",
    ],
    specifications: {
      weight: 31.5,
      displayType: "amoled",
      displaySize: 1.3,
      touchscreen: true,
      caseSizeMm: 40,
      solar: false,
      batterySmartwatch: 1.5,
      batteryGps: null,
      batteryMultiBand: null,
      multiBandGps: true,
      maps: true,
      offlineMaps: false,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: true,
      spo2: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      barometricAltimeter: true,
      stravaSync: true,
      waterRating: "5 ATM",
    },
    strengths: [
      "Compact 40 mm / 31.5 g Wear OS daily with dual GPS and Samsung Pay",
      "Galaxy Health + Running Coach for Android athletes who already live on a Galaxy phone",
      "44 mm / 34 g variant when a larger display is the fit",
    ],
    weaknesses: [
      "Typical use around 30–40 hours — daily charging, not a long-event GPS tool",
      "Not a Garmin/COROS training platform; GPS hours unpublished",
    ],
    recommendationScore: 76,
    valueScore: 74,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage(
      "cat-gps-watches",
      "prod-samsung-galaxy-watch-9",
      "Samsung Galaxy Watch9 — manufacturer packshot",
    ),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [
      "prod-samsung-galaxy-watch-ultra-2",
      "prod-vivoactive-6",
      "prod-forerunner-165",
    ],
    alternativeProductIds: [
      "prod-forerunner-165",
      "prod-vivoactive-6",
      "prod-samsung-galaxy-watch-ultra-2",
    ],
    ...pub,
  },
];
