/**
 * Training shoes catalog expansion — brings cat-training-shoes from seed (12)
 * toward a proper multi-brand catalog (~48). Numeric specs stay null when
 * unverified. Merged via fitness/index.ts.
 */

import type { Product, Brand } from "@/domain/products/types";
import type { Offer } from "@/domain/commerce/types";
import type { Evidence } from "@/domain/recommendations/types";
import { publishedMeta, SEED_DATES } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();

function offerTriplet(
  productId: string,
  slug: string,
  priceEur: number,
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  return [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
}

type Suit = "very-low" | "low" | "moderate" | "high" | "very-high";
type Stab = "flexible" | "moderate" | "stable" | "very-stable" | "maximum";

function trainingShoe(input: {
  id: string;
  slug: string;
  brandId: string;
  name: string;
  fullName: string;
  shortDescription: string;
  generation?: string;
  familyId?: string;
  lifecycleStatus?: Product["lifecycleStatus"];
  subcategoryIds: string[];
  useCaseIds: string[];
  disciplineIds?: string[];
  sportIds?: string[];
  stability: Stab;
  hyrox: Suit;
  lifting: Suit;
  running: Suit;
  weight?: number | null;
  drop?: number | null;
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  priceEur: number;
  relatedProductIds?: string[];
  alternativeProductIds?: string[];
  experienceLevels?: Product["experienceLevels"];
  status?: Product["status"];
}): Product {
  const sports = input.sportIds ?? (
    input.hyrox === "high" || input.hyrox === "very-high"
      ? ["sport-training", "sport-hyrox"]
      : ["sport-training"]
  );
  return {
    id: input.id,
    slug: input.slug,
    brandId: input.brandId,
    generation: input.generation,
    familyId: input.familyId,
    name: input.name,
    fullName: input.fullName,
    shortDescription: input.shortDescription,
    lifecycleStatus: input.lifecycleStatus ?? "current",
    sportIds: sports,
    disciplineIds: input.disciplineIds ?? [
      "disc-training-gym",
      "disc-training-functional",
    ],
    categoryId: "cat-training-shoes",
    subcategoryIds: input.subcategoryIds,
    useCaseIds: input.useCaseIds,
    specifications: {
      weight: input.weight ?? null,
      drop: input.drop ?? null,
      stability: input.stability,
      hyroxSuitability: input.hyrox,
      liftingSuitability: input.lifting,
      runningSuitability: input.running,
      genderFit: "unisex",
    },
    strengths: input.strengths,
    weaknesses: input.weaknesses,
    recommendationScore: input.recommendationScore,
    valueScore: input.valueScore,
    experienceLevels: input.experienceLevels ?? [
      "beginner",
      "intermediate",
      "advanced",
    ],
    images: categoryFallbackImage(
      "cat-training-shoes",
      input.id,
      `${input.fullName} — product image unavailable`,
    ),
    videos: [],
    offerIds: [
      `offer-${input.slug}-nl`,
      `offer-${input.slug}-de`,
      `offer-${input.slug}-uk`,
    ],
    evidenceIds: ["ev-fitness-mfr", "ev-training-shoes-wave-editorial"],
    relatedProductIds: input.relatedProductIds ?? [
      "prod-nike-metcon-9",
      "prod-reebok-nano-x4",
    ],
    alternativeProductIds: input.alternativeProductIds ?? [
      "prod-nike-metcon-9",
      "prod-reebok-nano-x4",
    ],
    ...pub,
    ...(input.status ? { status: input.status } : {}),
  };
}

export const trainingShoesWaveBrands: Brand[] = [
  {
    id: "brand-under-armour",
    name: "Under Armour",
    slug: "under-armour",
    country: "USA",
    description: "TriBase training shoes and Project Rock performance footwear.",
    homepage: "https://www.underarmour.com",
    logo: "/images/brands/under-armour-logo.svg",
    ...pub,
  },
  {
    id: "brand-lululemon",
    name: "lululemon",
    slug: "lululemon",
    country: "Canada",
    description: "Training footwear including Strongfeel for studio and gym floors.",
    homepage: "https://www.lululemon.com",
    logo: "/images/brands/lululemon-logo.svg",
    ...pub,
  },
  {
    id: "brand-xero",
    name: "Xero Shoes",
    slug: "xero-shoes",
    country: "USA",
    description: "Minimalist barefoot-style trainers for gym and everyday movement.",
    homepage: "https://xeroshoes.com",
    logo: "/images/brands/xero-shoes-logo.svg",
    ...pub,
  },
  {
    id: "brand-vivobarefoot",
    name: "Vivobarefoot",
    slug: "vivobarefoot",
    country: "UK",
    description: "Wide-toe barefoot training shoes for natural foot strength.",
    homepage: "https://www.vivobarefoot.com",
    logo: "/images/brands/vivobarefoot-logo.svg",
    ...pub,
  },
  {
    id: "brand-bear-komplex",
    name: "Bear KompleX",
    slug: "bear-komplex",
    country: "USA",
    description: "Functional fitness and HYROX-oriented training shoes and grips.",
    homepage: "https://bearkomplex.com",
    logo: "/images/brands/bear-komplex-logo.svg",
    ...pub,
  },
  {
    id: "brand-domyos",
    name: "Domyos",
    slug: "domyos",
    country: "France",
    description: "Decathlon training brand for gym shoes and fitness apparel.",
    homepage: "https://www.decathlon.com",
    logo: "/images/brands/domyos-logo.svg",
    ...pub,
  },
  {
    id: "brand-salming",
    name: "Salming",
    slug: "salming",
    country: "Sweden",
    description: "Court and race shoes popular with HYROX and indoor athletes.",
    homepage: "https://www.salming.com",
    logo: "/images/brands/salming-logo.svg",
    ...pub,
  },
  {
    id: "brand-do-win",
    name: "Do-Win",
    slug: "do-win",
    country: "China",
    description: "Classic elevated weightlifting shoes used in Olympic lifting gyms.",
    homepage: "https://www.dowin.com",
    logo: "/images/brands/do-win-logo.svg",
    ...pub,
  },
  {
    id: "brand-zeraus",
    name: "Zeraus",
    slug: "zeraus",
    country: "USA",
    description: "Weightlifting shoes focused on a stable raised heel platform.",
    homepage: "https://www.zeraus.com",
    logo: "/images/brands/zeraus-logo.svg",
    ...pub,
  },
];

export const trainingShoesWaveEvidence: Evidence[] = [
  {
    id: "ev-training-shoes-wave-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — training shoes catalog",
    summary:
      "Category placement, suitability enums and strengths/weaknesses derived from product design role (cross-training, weightlifting, HYROX). Not personal wear testing.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];

const X = "sub-cross-training";
const W = "sub-weightlifting-shoes";
const H = "sub-hyrox-shoes";
const G = "sub-gym-shoes";

export const trainingShoesWaveProducts: Product[] = [
  // ─── Cross-training / gym ───────────────────────────────────────────────
  trainingShoe({
    id: "prod-nike-free-metcon-6",
    slug: "nike-free-metcon-6",
    brandId: "brand-nike",
    generation: "6",
    name: "Free Metcon 6",
    fullName: "Nike Free Metcon 6",
    shortDescription:
      "Flexible Free forefoot with Metcon-stable heel for mixed gym and conditioning sessions.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-hyrox-training", "uc-home-gym"],
    stability: "stable",
    hyrox: "high",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Flexible forefoot for agility work", "Stable enough for moderate loads"],
    weaknesses: ["Less planted than a full Metcon under max lifts"],
    recommendationScore: 86,
    valueScore: 80,
    priceEur: 130,
    alternativeProductIds: ["prod-nike-metcon-9", "prod-reebok-nano-x4"],
  }),
  trainingShoe({
    id: "prod-nike-metcon-8",
    slug: "nike-metcon-8",
    brandId: "brand-nike",
    generation: "8",
    name: "Metcon 8",
    fullName: "Nike Metcon 8",
    shortDescription:
      "Previous-generation Metcon still widely available for flat-base gym and CrossFit-style work.",
    lifecycleStatus: "previous-generation",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "stable",
    hyrox: "high",
    lifting: "high",
    running: "moderate",
    strengths: ["Proven stable Metcon platform", "Often priced below current Metcon"],
    weaknesses: ["Superseded by Metcon 9 materials and fit updates"],
    recommendationScore: 82,
    valueScore: 86,
    priceEur: 110,
    alternativeProductIds: ["prod-nike-metcon-9", "prod-adidas-dropset-3"],
  }),
  trainingShoe({
    id: "prod-ua-tribase-reign-6",
    slug: "ua-tribase-reign-6",
    brandId: "brand-under-armour",
    generation: "6",
    name: "TriBase Reign 6",
    fullName: "Under Armour TriBase Reign 6",
    shortDescription:
      "Low TriBase platform built for weightlifting stability and functional fitness.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-beginner-strength", "uc-home-gym"],
    stability: "very-stable",
    hyrox: "moderate",
    lifting: "high",
    running: "low",
    strengths: ["Wide stable TriBase footprint", "Strong for lifts and floor work"],
    weaknesses: ["Not ideal for longer run intervals"],
    recommendationScore: 85,
    valueScore: 81,
    priceEur: 125,
    alternativeProductIds: ["prod-nike-metcon-9", "prod-adidas-dropset-3"],
  }),
  trainingShoe({
    id: "prod-ua-project-rock-bsr-4",
    slug: "ua-project-rock-bsr-4",
    brandId: "brand-under-armour",
    generation: "4",
    name: "Project Rock BSR 4",
    fullName: "Under Armour Project Rock BSR 4",
    shortDescription:
      "Project Rock training shoe aimed at gym floors, circuits and strength sessions.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-bodybuilding", "uc-home-gym"],
    stability: "stable",
    hyrox: "moderate",
    lifting: "high",
    running: "low",
    strengths: ["Supportive for strength circuits", "Durable gym outsole"],
    weaknesses: ["Limited run cushion vs HYROX specialists"],
    recommendationScore: 83,
    valueScore: 78,
    priceEur: 135,
    alternativeProductIds: ["prod-ua-tribase-reign-6", "prod-nike-metcon-9"],
  }),
  trainingShoe({
    id: "prod-puma-fuse-3",
    slug: "puma-fuse-3",
    brandId: "brand-puma",
    generation: "3",
    name: "Fuse 3.0",
    fullName: "PUMA Fuse 3.0",
    shortDescription:
      "Versatile Fuse trainer for CrossFit-style sessions, lifts and short conditioning runs.",
    subcategoryIds: [X, H, G],
    useCaseIds: ["uc-general-fitness", "uc-hyrox-training"],
    stability: "stable",
    hyrox: "high",
    lifting: "high",
    running: "moderate",
    strengths: ["Balanced lift-and-move platform", "Good value vs premium trainers"],
    weaknesses: ["Less race-specific than TYR/NOBULL HYROX shoes"],
    recommendationScore: 84,
    valueScore: 84,
    priceEur: 120,
    alternativeProductIds: ["prod-reebok-nano-x4", "prod-nike-metcon-9"],
  }),
  trainingShoe({
    id: "prod-nb-minimus-tr",
    slug: "nb-minimus-tr",
    brandId: "brand-new-balance",
    name: "Minimus TR",
    fullName: "New Balance Minimus TR",
    shortDescription:
      "Low-profile Minimus trainer for gym floors, agility work and light conditioning.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "moderate",
    hyrox: "moderate",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Low-to-ground feel", "Flexible for dynamic gym work"],
    weaknesses: ["Less rigid for heavy Olympic lifts"],
    recommendationScore: 80,
    valueScore: 82,
    priceEur: 115,
    alternativeProductIds: ["prod-inov8-flite-235-v3", "prod-xero-prio"],
  }),
  trainingShoe({
    id: "prod-adidas-the-total",
    slug: "adidas-the-total",
    brandId: "brand-adidas",
    name: "The Total",
    fullName: "adidas The Total",
    shortDescription:
      "Wide-base strength trainer for heavy lifts, machines and general gym sessions.",
    subcategoryIds: [X, G, W],
    useCaseIds: ["uc-bodybuilding", "uc-beginner-strength", "uc-powerlifting"],
    stability: "very-stable",
    hyrox: "low",
    lifting: "very-high",
    running: "low",
    strengths: ["Wide stable lifting base", "Strong lateral support"],
    weaknesses: ["Poor choice for run-heavy HYROX work"],
    recommendationScore: 86,
    valueScore: 80,
    priceEur: 130,
    alternativeProductIds: ["prod-adidas-dropset-3", "prod-ua-tribase-reign-6"],
  }),
  trainingShoe({
    id: "prod-adidas-rapidmove-adv",
    slug: "adidas-rapidmove-adv",
    brandId: "brand-adidas",
    name: "Rapidmove ADV",
    fullName: "adidas Rapidmove ADV",
    shortDescription:
      "Light agile trainer for HIIT, studio classes and fast gym floor movement.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "moderate",
    hyrox: "moderate",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Light and agile", "Comfortable for class-based training"],
    weaknesses: ["Not a max-lift platform"],
    recommendationScore: 79,
    valueScore: 83,
    priceEur: 110,
    alternativeProductIds: ["prod-nike-free-metcon-6", "prod-inov8-flite-235-v3"],
  }),
  trainingShoe({
    id: "prod-reebok-nano-x3",
    slug: "reebok-nano-x3",
    brandId: "brand-reebok",
    generation: "X3",
    name: "Nano X3",
    fullName: "Reebok Nano X3",
    shortDescription:
      "Previous Nano generation still strong for CrossFit-style and functional fitness.",
    lifecycleStatus: "previous-generation",
    subcategoryIds: [X, H],
    useCaseIds: ["uc-general-fitness", "uc-hyrox-training"],
    stability: "stable",
    hyrox: "high",
    lifting: "high",
    running: "moderate",
    strengths: ["Proven Nano versatility", "Often better value than X4"],
    weaknesses: ["Fit and foam updated in X4"],
    recommendationScore: 81,
    valueScore: 85,
    priceEur: 105,
    alternativeProductIds: ["prod-reebok-nano-x4", "prod-nike-metcon-9"],
  }),
  trainingShoe({
    id: "prod-reebok-nano-court",
    slug: "reebok-nano-court",
    brandId: "brand-reebok",
    name: "Nano Court",
    fullName: "Reebok Nano Court",
    shortDescription:
      "Court-influenced Nano for lateral drills, gym floors and indoor conditioning.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-hyrox-training"],
    stability: "stable",
    hyrox: "high",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Strong lateral grip", "Indoor court-friendly outsole"],
    weaknesses: ["Less run cushion than Outwork-style HYROX shoes"],
    recommendationScore: 82,
    valueScore: 80,
    priceEur: 120,
    alternativeProductIds: ["prod-reebok-nano-x4", "prod-puma-fuse-3"],
  }),
  trainingShoe({
    id: "prod-inov8-flite-260",
    slug: "inov8-f-lite-260",
    brandId: "brand-inov8",
    name: "F-Lite 260",
    fullName: "Inov-8 F-Lite 260",
    shortDescription:
      "Slightly more protective F-Lite for gym floors and light conditioning runs.",
    subcategoryIds: [X, G],
    useCaseIds: ["uc-general-fitness", "uc-hyrox-training"],
    weight: 260,
    stability: "moderate",
    hyrox: "high",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Light flexible ride", "Good gym-to-run transition"],
    weaknesses: ["Less rigid for heavy Olympic lifting"],
    recommendationScore: 83,
    valueScore: 83,
    priceEur: 125,
    alternativeProductIds: ["prod-inov8-flite-235-v3", "prod-nobull-trainer"],
  }),
  trainingShoe({
    id: "prod-nobull-trainer-plus",
    slug: "nobull-trainer-plus",
    brandId: "brand-nobull",
    name: "Trainer+",
    fullName: "NOBULL Trainer+",
    shortDescription:
      "Updated Trainer platform with more structure for functional fitness and HYROX prep.",
    subcategoryIds: [X, H, G],
    useCaseIds: ["uc-hyrox-training", "uc-hyrox-race", "uc-general-fitness"],
    stability: "stable",
    hyrox: "very-high",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Stable low profile", "Popular HYROX training choice"],
    weaknesses: ["Less cushioned for high run volume"],
    recommendationScore: 87,
    valueScore: 74,
    priceEur: 145,
    alternativeProductIds: ["prod-nobull-trainer", "prod-tyr-cxt-2"],
  }),
  trainingShoe({
    id: "prod-asics-gel-quantum-360-8",
    slug: "asics-gel-quantum-360-8",
    brandId: "brand-asics",
    generation: "8",
    name: "GEL-Quantum 360 8",
    fullName: "ASICS GEL-Quantum 360 8",
    shortDescription:
      "Cushioned Quantum trainer for gym floors, all-day wear and lighter training days.",
    subcategoryIds: [G, X],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "moderate",
    hyrox: "moderate",
    lifting: "moderate",
    running: "moderate",
    strengths: ["Plush GEL cushioning", "Comfortable for mixed gym days"],
    weaknesses: ["Softer under heavy barbell work than Metcon-class shoes"],
    recommendationScore: 78,
    valueScore: 79,
    priceEur: 150,
    alternativeProductIds: ["prod-hoka-transport", "prod-lululemon-strongfeel"],
  }),
  trainingShoe({
    id: "prod-lululemon-strongfeel",
    slug: "lululemon-strongfeel",
    brandId: "brand-lululemon",
    name: "Strongfeel",
    fullName: "lululemon Strongfeel Training Shoe",
    shortDescription:
      "Studio-to-gym trainer with a stable base for strength and group fitness.",
    subcategoryIds: [G, X],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "stable",
    hyrox: "moderate",
    lifting: "high",
    running: "low",
    strengths: ["Stable training base", "Comfortable for studio/gym mix"],
    weaknesses: ["Limited distribution vs Nike/Reebok", "Not a run shoe"],
    recommendationScore: 81,
    valueScore: 72,
    priceEur: 148,
    alternativeProductIds: ["prod-nike-metcon-9", "prod-adidas-dropset-3"],
  }),
  trainingShoe({
    id: "prod-xero-prio",
    slug: "xero-prio",
    brandId: "brand-xero",
    name: "Prio",
    fullName: "Xero Shoes Prio",
    shortDescription:
      "Minimalist zero-drop trainer for barefoot-style gym work and light movement.",
    subcategoryIds: [G, X],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    drop: 0,
    stability: "flexible",
    hyrox: "low",
    lifting: "moderate",
    running: "low",
    strengths: ["Zero-drop barefoot feel", "Wide toe box"],
    weaknesses: ["Minimal protection for long runs or heavy Olympic lifts"],
    recommendationScore: 76,
    valueScore: 85,
    priceEur: 90,
    experienceLevels: ["beginner", "intermediate"],
    alternativeProductIds: ["prod-vivobarefoot-primus-lite-iii", "prod-nb-minimus-tr"],
  }),
  trainingShoe({
    id: "prod-vivobarefoot-primus-lite-iii",
    slug: "vivobarefoot-primus-lite-iii",
    brandId: "brand-vivobarefoot",
    generation: "III",
    name: "Primus Lite III",
    fullName: "Vivobarefoot Primus Lite III",
    shortDescription:
      "Wide barefoot trainer for gym floors, mobility work and natural foot strength.",
    subcategoryIds: [G, X],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    drop: 0,
    stability: "flexible",
    hyrox: "low",
    lifting: "moderate",
    running: "low",
    strengths: ["Wide anatomical fit", "Thin flexible sole"],
    weaknesses: ["Not for run-heavy HYROX or max Olympic lifts"],
    recommendationScore: 77,
    valueScore: 78,
    priceEur: 130,
    alternativeProductIds: ["prod-xero-prio", "prod-nb-minimus-tr"],
  }),
  trainingShoe({
    id: "prod-bear-komplex-valor",
    slug: "bear-komplex-valor",
    brandId: "brand-bear-komplex",
    name: "Valor",
    fullName: "Bear KompleX Valor",
    shortDescription:
      "Functional fitness trainer aimed at CrossFit-style and HYROX station work.",
    subcategoryIds: [X, H],
    useCaseIds: ["uc-hyrox-training", "uc-general-fitness"],
    disciplineIds: ["disc-training-functional", "disc-training-hyrox"],
    stability: "stable",
    hyrox: "high",
    lifting: "high",
    running: "moderate",
    strengths: ["Stable for lifts and stations", "HYROX-friendly design brief"],
    weaknesses: ["Narrower retail availability in EU"],
    recommendationScore: 84,
    valueScore: 79,
    priceEur: 140,
    alternativeProductIds: ["prod-nobull-trainer", "prod-tyr-cxt-1"],
    /** No authentic manufacturer/retailer hero available — withhold from public catalog. */
    status: "review",
  }),
  trainingShoe({
    id: "prod-domyos-mid-500",
    slug: "domyos-mid-500",
    brandId: "brand-domyos",
    name: "Mid 500",
    fullName: "Domyos Mid 500",
    shortDescription:
      "Budget Decathlon gym shoe for machines, free weights and general fitness.",
    subcategoryIds: [G],
    useCaseIds: ["uc-general-fitness", "uc-beginner-strength", "uc-home-gym"],
    stability: "stable",
    hyrox: "low",
    lifting: "moderate",
    running: "low",
    strengths: ["Accessible price", "Decent flat gym base"],
    weaknesses: ["Build and longevity below premium trainers"],
    recommendationScore: 72,
    valueScore: 92,
    priceEur: 45,
    experienceLevels: ["beginner", "intermediate"],
    alternativeProductIds: ["prod-adidas-dropset-3", "prod-ua-charged-commit-4"],
    /** Decathlon CDN blocks automated fetch; no verified hero on disk yet. */
    status: "review",
  }),

  // ─── Weightlifting ──────────────────────────────────────────────────────
  trainingShoe({
    id: "prod-nike-savaleos",
    slug: "nike-savaleos",
    brandId: "brand-nike",
    name: "Savaleos",
    fullName: "Nike Savaleos",
    shortDescription:
      "Entry Olympic lifting shoe with an elevated heel for squats and cleans.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-beginner-strength"],
    disciplineIds: ["disc-training-strength"],
    stability: "very-stable",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Raised heel for squat depth", "More approachable price than Romaleos"],
    weaknesses: ["Single-purpose lifting shoe"],
    recommendationScore: 85,
    valueScore: 84,
    priceEur: 140,
    alternativeProductIds: ["prod-nike-romaleos-5", "prod-adidas-powerlift-5"],
  }),
  trainingShoe({
    id: "prod-nike-romaleos-4",
    slug: "nike-romaleos-4",
    brandId: "brand-nike",
    generation: "4",
    name: "Romaleos 4",
    fullName: "Nike Romaleos 4",
    shortDescription:
      "Previous Romaleos generation — rock-solid platform still common in lifting gyms.",
    lifecycleStatus: "previous-generation",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "maximum",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Proven competition platform", "Often available below Romaleos 5"],
    weaknesses: ["Unsuitable for running or metcons"],
    recommendationScore: 88,
    valueScore: 80,
    priceEur: 170,
    alternativeProductIds: ["prod-nike-romaleos-5", "prod-adidas-adipower-3"],
  }),
  trainingShoe({
    id: "prod-adidas-powerlift-5",
    slug: "adidas-powerlift-5",
    brandId: "brand-adidas",
    generation: "5",
    name: "Powerlift 5",
    fullName: "adidas Powerlift 5",
    shortDescription:
      "Accessible weightlifting shoe for squats, presses and Olympic lift practice.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-beginner-strength", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "very-stable",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Strong value for a raised-heel lifter", "Secure midfoot lockdown"],
    weaknesses: ["Not for conditioning runs"],
    recommendationScore: 86,
    valueScore: 88,
    priceEur: 120,
    alternativeProductIds: ["prod-nike-savaleos", "prod-do-win-classic"],
  }),
  trainingShoe({
    id: "prod-do-win-classic",
    slug: "do-win-classic",
    brandId: "brand-do-win",
    name: "Classic",
    fullName: "Do-Win Classic Weightlifting Shoe",
    shortDescription:
      "Traditional elevated weightlifting shoe used widely in Olympic lifting gyms.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "maximum",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Classic stable heel wedge", "Strong value for dedicated lifters"],
    weaknesses: ["Narrow sizing for some feet", "Single-purpose shoe"],
    recommendationScore: 87,
    valueScore: 90,
    priceEur: 100,
    alternativeProductIds: ["prod-adidas-powerlift-5", "prod-zeraus-classic"],
  }),
  trainingShoe({
    id: "prod-inov8-fastlift-power-g-380",
    slug: "inov8-fastlift-power-g-380",
    brandId: "brand-inov8",
    name: "Fastlift Power G 380",
    fullName: "Inov-8 Fastlift Power G 380",
    shortDescription:
      "Graphene-enhanced Fastlift for Olympic lifts with a lighter raised-heel feel.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-beginner-strength"],
    disciplineIds: ["disc-training-strength"],
    weight: 380,
    stability: "very-stable",
    hyrox: "low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Lighter Fastlift platform", "Stable heel for squats"],
    weaknesses: ["Not for run intervals"],
    recommendationScore: 84,
    valueScore: 80,
    priceEur: 165,
    alternativeProductIds: ["prod-inov8-fastlift-360", "prod-nike-savaleos"],
  }),
  trainingShoe({
    id: "prod-ua-reign-lifter",
    slug: "ua-reign-lifter",
    brandId: "brand-under-armour",
    name: "Reign Lifter",
    fullName: "Under Armour Reign Lifter",
    shortDescription:
      "Elevated TriBase lifter for squats and Olympic lifts in the gym.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "maximum",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Raised heel with TriBase stability", "Secure lockdown"],
    weaknesses: ["Single-purpose lifting shoe"],
    recommendationScore: 85,
    valueScore: 78,
    priceEur: 155,
    alternativeProductIds: ["prod-adidas-powerlift-5", "prod-nike-romaleos-5"],
  }),
  trainingShoe({
    id: "prod-reebok-lifter-pr-iii",
    slug: "reebok-lifter-pr-iii",
    brandId: "brand-reebok",
    generation: "III",
    name: "Lifter PR III",
    fullName: "Reebok Lifter PR III",
    shortDescription:
      "Competition-leaning weightlifting shoe bridging CrossFit and Olympic lifting.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength", "disc-training-functional"],
    stability: "maximum",
    hyrox: "low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Tall stable heel", "Secure for heavy pulls and squats"],
    weaknesses: ["Heavy for mixed metcon work"],
    recommendationScore: 86,
    valueScore: 76,
    priceEur: 180,
    alternativeProductIds: ["prod-reebok-legacy-lifter-iii", "prod-adidas-adipower-3"],
  }),
  trainingShoe({
    id: "prod-zeraus-classic",
    slug: "zeraus-classic",
    brandId: "brand-zeraus",
    name: "Classic",
    fullName: "Zeraus Classic Weightlifting Shoe",
    shortDescription:
      "Dedicated raised-heel weightlifting shoe for squats and Olympic lifts.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "maximum",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Stable elevated platform", "Focused lifting design"],
    weaknesses: ["Limited brand retail footprint"],
    recommendationScore: 82,
    valueScore: 86,
    priceEur: 95,
    alternativeProductIds: ["prod-do-win-classic", "prod-adidas-powerlift-5"],
    /** No verified manufacturer/retailer hero located. */
    status: "review",
  }),
  trainingShoe({
    id: "prod-adidas-adipower-weightlifting-2",
    slug: "adidas-adipower-weightlifting-2",
    brandId: "brand-adidas",
    generation: "2",
    name: "Adipower Weightlifting 2",
    fullName: "adidas Adipower Weightlifting 2",
    shortDescription:
      "Previous Adipower lifter still used in clubs for competition-style sessions.",
    lifecycleStatus: "previous-generation",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    stability: "maximum",
    hyrox: "very-low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Firm elevated heel", "Often discounted vs current Adipower"],
    weaknesses: ["Single-purpose lifting shoe"],
    recommendationScore: 84,
    valueScore: 82,
    priceEur: 150,
    alternativeProductIds: ["prod-adidas-adipower-3", "prod-nike-romaleos-4"],
  }),
  trainingShoe({
    id: "prod-inov8-fastlift-400",
    slug: "inov8-fastlift-400",
    brandId: "brand-inov8",
    name: "Fastlift 400",
    fullName: "Inov-8 Fastlift 400",
    shortDescription:
      "Heavier Fastlift option for athletes wanting a more planted Olympic lifting shoe.",
    subcategoryIds: [W],
    useCaseIds: ["uc-olympic-lifting", "uc-powerlifting"],
    disciplineIds: ["disc-training-strength"],
    weight: 400,
    stability: "very-stable",
    hyrox: "low",
    lifting: "very-high",
    running: "very-low",
    strengths: ["Planted Fastlift platform", "Stable heel wedge"],
    weaknesses: ["Heavier than Fastlift 360"],
    recommendationScore: 83,
    valueScore: 79,
    priceEur: 155,
    alternativeProductIds: ["prod-inov8-fastlift-360", "prod-inov8-fastlift-power-g-380"],
  }),

  // ─── HYROX / hybrid ─────────────────────────────────────────────────────
  trainingShoe({
    id: "prod-salming-race-9",
    slug: "salming-race-9",
    brandId: "brand-salming",
    generation: "9",
    name: "Race 9",
    fullName: "Salming Race 9",
    shortDescription:
      "Light indoor race shoe often used for HYROX run legs and station transitions.",
    subcategoryIds: [H],
    useCaseIds: ["uc-hyrox-race", "uc-hyrox-training"],
    disciplineIds: ["disc-training-hyrox", "disc-training-conditioning"],
    stability: "moderate",
    hyrox: "very-high",
    lifting: "low",
    running: "high",
    strengths: ["Light for 1 km run legs", "Quick indoor grip"],
    weaknesses: ["Less stable for heavy sled/farmer carries than gym shoes"],
    recommendationScore: 88,
    valueScore: 78,
    priceEur: 140,
    experienceLevels: ["intermediate", "advanced", "elite"],
    alternativeProductIds: ["prod-tyr-cxt-2", "prod-nobull-outwork"],
  }),
  trainingShoe({
    id: "prod-salming-rebel",
    slug: "salming-rebel",
    brandId: "brand-salming",
    name: "Rebel",
    fullName: "Salming Rebel",
    shortDescription:
      "Cushioned Salming trainer balancing HYROX stations with more run comfort.",
    subcategoryIds: [H, X],
    useCaseIds: ["uc-hyrox-race", "uc-hyrox-training"],
    disciplineIds: ["disc-training-hyrox", "disc-training-conditioning"],
    stability: "moderate",
    hyrox: "very-high",
    lifting: "moderate",
    running: "high",
    strengths: ["More cushion than Race for run volume", "HYROX-friendly ride"],
    weaknesses: ["Less planted under max lifts"],
    recommendationScore: 86,
    valueScore: 77,
    priceEur: 145,
    alternativeProductIds: ["prod-salming-race-9", "prod-nobull-outwork"],
  }),
  trainingShoe({
    id: "prod-nobull-trail",
    slug: "nobull-trail",
    brandId: "brand-nobull",
    name: "Trail",
    fullName: "NOBULL Trail",
    shortDescription:
      "Aggressive-outsole NOBULL for outdoor conditioning, trails and hybrid HYROX prep.",
    subcategoryIds: [H, X],
    useCaseIds: ["uc-hyrox-training", "uc-general-fitness"],
    disciplineIds: ["disc-training-hyrox", "disc-training-conditioning"],
    stability: "stable",
    hyrox: "high",
    lifting: "moderate",
    running: "high",
    strengths: ["Trail grip for outdoor sessions", "Hybrid training use"],
    weaknesses: ["Overbuilt for pure indoor gym floors"],
    recommendationScore: 80,
    valueScore: 74,
    priceEur: 150,
    alternativeProductIds: ["prod-nobull-outwork", "prod-inov8-flite-235-v3"],
    /** Discontinued / renamed line — no authorized hero on disk yet. */
    status: "review",
  }),
  trainingShoe({
    id: "prod-puma-fuse-fasted",
    slug: "puma-fuse-fasted",
    brandId: "brand-puma",
    name: "Fuse Fasted",
    fullName: "PUMA Fuse Fasted",
    shortDescription:
      "Faster Fuse variant biased toward conditioning runs and HYROX-style sessions.",
    subcategoryIds: [H, X],
    useCaseIds: ["uc-hyrox-training", "uc-hyrox-race", "uc-general-fitness"],
    disciplineIds: ["disc-training-hyrox", "disc-training-functional"],
    stability: "moderate",
    hyrox: "very-high",
    lifting: "moderate",
    running: "high",
    strengths: ["Lighter Fuse ride for run legs", "Still usable for stations"],
    weaknesses: ["Less rigid than Dropset for heavy lifts"],
    recommendationScore: 85,
    valueScore: 82,
    priceEur: 125,
    alternativeProductIds: ["prod-puma-fuse-3", "prod-nobull-outwork"],
  }),
  trainingShoe({
    id: "prod-hoka-transport",
    slug: "hoka-transport",
    brandId: "brand-hoka",
    name: "Transport",
    fullName: "HOKA Transport",
    shortDescription:
      "Cushioned HOKA for walking, travel and light gym days — not a pure lifting shoe.",
    subcategoryIds: [G],
    useCaseIds: ["uc-general-fitness", "uc-home-gym"],
    stability: "moderate",
    hyrox: "moderate",
    lifting: "low",
    running: "moderate",
    strengths: ["High cushion comfort", "Everyday gym-and-walk versatility"],
    weaknesses: ["Too soft for heavy Olympic lifts"],
    recommendationScore: 74,
    valueScore: 76,
    priceEur: 140,
    alternativeProductIds: ["prod-asics-gel-quantum-360-8", "prod-lululemon-strongfeel"],
  }),
  trainingShoe({
    id: "prod-ua-charged-commit-4",
    slug: "ua-charged-commit-4",
    brandId: "brand-under-armour",
    generation: "4",
    name: "Charged Commit 4",
    fullName: "Under Armour Charged Commit 4",
    shortDescription:
      "Value training shoe for machines, light free weights and general gym use.",
    subcategoryIds: [G, X],
    useCaseIds: ["uc-general-fitness", "uc-beginner-strength", "uc-home-gym"],
    stability: "stable",
    hyrox: "moderate",
    lifting: "moderate",
    running: "low",
    strengths: ["Accessible price", "Solid everyday gym shoe"],
    weaknesses: ["Not a specialist HYROX or Olympic lifter"],
    recommendationScore: 76,
    valueScore: 88,
    priceEur: 80,
    experienceLevels: ["beginner", "intermediate"],
    alternativeProductIds: ["prod-domyos-mid-500", "prod-ua-tribase-reign-6"],
  }),
  trainingShoe({
    id: "prod-tyr-cxt1-trainer",
    slug: "tyr-cxt1-trainer",
    brandId: "brand-tyr",
    familyId: "fam-tyr-cxt-1",
    generation: "1",
    name: "CXT-1 Trainer",
    fullName: "TYR CXT-1 Trainer",
    shortDescription:
      "CXT-1 Neon/Black colorway — same CXT-1 platform as the Black/Gum listing, kept as a distinct SKU with its own packshot (never share hero bytes).",
    subcategoryIds: [H, X],
    useCaseIds: ["uc-hyrox-training", "uc-hyrox-race"],
    disciplineIds: ["disc-training-hyrox"],
    stability: "stable",
    hyrox: "very-high",
    lifting: "moderate",
    running: "high",
    strengths: ["HYROX-oriented geometry", "Good station-to-run balance"],
    weaknesses: ["Narrower availability than Nike/Reebok"],
    recommendationScore: 86,
    valueScore: 75,
    priceEur: 150,
    experienceLevels: ["intermediate", "advanced", "elite"],
    relatedProductIds: ["prod-tyr-cxt-1", "prod-tyr-cxt-2"],
    alternativeProductIds: ["prod-tyr-cxt-1", "prod-tyr-cxt-2"],
  }),
  trainingShoe({
    id: "prod-adidas-dropset-2",
    slug: "adidas-dropset-2",
    brandId: "brand-adidas",
    generation: "2",
    name: "Dropset 2",
    fullName: "adidas Dropset 2",
    shortDescription:
      "Previous Dropset strength trainer — wide base for lifts still common in gyms.",
    lifecycleStatus: "previous-generation",
    subcategoryIds: [W, G],
    useCaseIds: ["uc-bodybuilding", "uc-beginner-strength", "uc-powerlifting"],
    stability: "very-stable",
    hyrox: "low",
    lifting: "very-high",
    running: "low",
    strengths: ["Wide stable lifting base", "Often better value than Dropset 3"],
    weaknesses: ["Poor choice for longer run intervals"],
    recommendationScore: 81,
    valueScore: 85,
    priceEur: 100,
    alternativeProductIds: ["prod-adidas-dropset-3", "prod-adidas-the-total"],
  }),
];

export const trainingShoesWaveOffers: Offer[] = trainingShoesWaveProducts.flatMap(
  (p) => {
    const priceById: Record<string, number> = {
      "prod-nike-free-metcon-6": 130,
      "prod-nike-metcon-8": 110,
      "prod-ua-tribase-reign-6": 125,
      "prod-ua-project-rock-bsr-4": 135,
      "prod-puma-fuse-3": 120,
      "prod-nb-minimus-tr": 115,
      "prod-adidas-the-total": 130,
      "prod-adidas-rapidmove-adv": 110,
      "prod-reebok-nano-x3": 105,
      "prod-reebok-nano-court": 120,
      "prod-inov8-flite-260": 125,
      "prod-nobull-trainer-plus": 145,
      "prod-asics-gel-quantum-360-8": 150,
      "prod-lululemon-strongfeel": 148,
      "prod-xero-prio": 90,
      "prod-vivobarefoot-primus-lite-iii": 130,
      "prod-bear-komplex-valor": 140,
      "prod-domyos-mid-500": 45,
      "prod-nike-savaleos": 140,
      "prod-nike-romaleos-4": 170,
      "prod-adidas-powerlift-5": 120,
      "prod-do-win-classic": 100,
      "prod-inov8-fastlift-power-g-380": 165,
      "prod-ua-reign-lifter": 155,
      "prod-reebok-lifter-pr-iii": 180,
      "prod-zeraus-classic": 95,
      "prod-adidas-adipower-weightlifting-2": 150,
      "prod-inov8-fastlift-400": 155,
      "prod-salming-race-9": 140,
      "prod-salming-rebel": 145,
      "prod-nobull-trail": 150,
      "prod-puma-fuse-fasted": 125,
      "prod-hoka-transport": 140,
      "prod-ua-charged-commit-4": 80,
      "prod-tyr-cxt1-trainer": 150,
      "prod-adidas-dropset-2": 100,
    };
    return offerTriplet(p.id, p.slug, priceById[p.id] ?? 120);
  },
);
