/**
 * Prompt 24 — Fitness/HYROX catalog population & gap fill.
 * Merged via fitness/index.ts. Do not invent unverified manufacturer claims.
 */

import type { Product, Brand, SpecificationDefinition } from "@/domain/products/types";
import type {
  BestGuide,
  BuyingGuide,
  Comparison,
  GearSetup,
} from "@/domain/editorial/types";
import type { Tool } from "@/domain/tools/types";
import type { Offer } from "@/domain/commerce/types";
import type { Recommendation, Evidence } from "@/domain/recommendations/types";
import { publishedMeta, SEED_DATES } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";

const pub = publishedMeta();
const sportTraining = "sport-training" as const;

function offerTriplet(
  productId: string,
  slug: string,
  priceEur: number,
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  return [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
}

export const wave24Brands: Brand[] = [
  {
    id: "brand-atx",
    name: "ATX",
    slug: "atx",
    country: "Germany",
    description: "European home gym racks, benches and strength equipment.",
    homepage: "https://www.atx-equipment.com",
    ...pub,
  },
  {
    id: "brand-hydrow",
    name: "Hydrow",
    slug: "hydrow",
    country: "USA",
    description: "Connected water-feel rowing machines for home.",
    homepage: "https://hydrow.com",
    ...pub,
  },
  {
    id: "brand-sole",
    name: "Sole Fitness",
    slug: "sole-fitness",
    country: "USA",
    description: "Home treadmills and cardio equipment.",
    homepage: "https://www.soletreadmills.com",
    ...pub,
  },
  {
    id: "brand-horizon",
    name: "Horizon Fitness",
    slug: "horizon-fitness",
    country: "USA",
    description: "Home treadmills and cardio.",
    homepage: "https://www.horizonfitness.com",
    ...pub,
  },
  {
    id: "brand-woodway",
    name: "Woodway",
    slug: "woodway",
    country: "USA",
    description: "Curved and commercial treadmills.",
    homepage: "https://www.woodway.com",
    ...pub,
  },
  {
    id: "brand-waterrower",
    name: "WaterRower",
    slug: "waterrower",
    country: "USA",
    description: "Water-resistance rowing machines.",
    homepage: "https://www.waterrower.com",
    ...pub,
  },
  {
    id: "brand-schwinn",
    name: "Schwinn",
    slug: "schwinn",
    country: "USA",
    description: "Airdyne air bikes and home cardio.",
    homepage: "https://www.schwinnfitness.com",
    ...pub,
  },
  {
    id: "brand-xebex",
    name: "Xebex Fitness",
    slug: "xebex",
    country: "USA",
    description: "Functional fitness cardio including ski ergs.",
    homepage: "https://xebexfitness.com",
    ...pub,
  },
];

export const wave24SpecificationDefinitions: SpecificationDefinition[] = [
  { id: "spec-bench-type", categoryId: "cat-weight-benches", key: "benchType", label: "Bench Type", type: "enum", enumValues: ["flat", "adjustable", "fid", "utility"], comparisonPriority: 90, finderRelevant: true, filterable: true },
  { id: "spec-bench-cap", categoryId: "cat-weight-benches", key: "weightCapacity", label: "Rated Capacity", type: "measurement", unit: "kg", comparisonPriority: 85, finderRelevant: true, filterable: true },
  { id: "spec-bench-w", categoryId: "cat-weight-benches", key: "widthMm", label: "Width", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-bench-d", categoryId: "cat-weight-benches", key: "depthMm", label: "Length", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-bench-fold", categoryId: "cat-weight-benches", key: "foldable", label: "Foldable", type: "boolean", comparisonPriority: 75, finderRelevant: true, filterable: true },
  { id: "spec-plate-type", categoryId: "cat-weight-plates", key: "plateType", label: "Plate Type", type: "enum", enumValues: ["bumper", "iron", "competition", "change", "fractional"], comparisonPriority: 90, finderRelevant: true, filterable: true },
  { id: "spec-plate-diam", categoryId: "cat-weight-plates", key: "diameterMm", label: "Diameter", type: "measurement", unit: "mm", comparisonPriority: 80, finderRelevant: true, filterable: true },
  { id: "spec-plate-mat", categoryId: "cat-weight-plates", key: "material", label: "Material", type: "enum", enumValues: ["rubber", "urethane", "cast-iron", "steel", "other"], comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-tm-motor", categoryId: "cat-treadmills", key: "motorised", label: "Motorised", type: "boolean", comparisonPriority: 95, finderRelevant: true, filterable: true },
  { id: "spec-tm-fold", categoryId: "cat-treadmills", key: "foldable", label: "Foldable", type: "boolean", comparisonPriority: 88, finderRelevant: true, filterable: true },
  { id: "spec-tm-user", categoryId: "cat-treadmills", key: "maxUserWeight", label: "Max User Weight", type: "measurement", unit: "kg", comparisonPriority: 80, finderRelevant: true, filterable: true },
  { id: "spec-tm-speed", categoryId: "cat-treadmills", key: "maxSpeedKph", label: "Max Speed", type: "measurement", unit: "km/h", comparisonPriority: 85, finderRelevant: true, filterable: true },
  { id: "spec-tm-w", categoryId: "cat-treadmills", key: "widthMm", label: "Width", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-tm-d", categoryId: "cat-treadmills", key: "depthMm", label: "Depth", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-air-user", categoryId: "cat-air-bikes", key: "maxUserWeight", label: "Max User Weight", type: "measurement", unit: "kg", comparisonPriority: 75, finderRelevant: true, filterable: true },
  { id: "spec-air-w", categoryId: "cat-air-bikes", key: "widthMm", label: "Width", type: "measurement", unit: "mm", comparisonPriority: 65, finderRelevant: true, filterable: true },
  { id: "spec-air-d", categoryId: "cat-air-bikes", key: "depthMm", label: "Depth", type: "measurement", unit: "mm", comparisonPriority: 65, finderRelevant: true, filterable: true },
  { id: "spec-ski-mount", categoryId: "cat-ski-ergs", key: "mountType", label: "Mount Type", type: "enum", enumValues: ["wall", "floor-stand", "optional"], comparisonPriority: 92, finderRelevant: true, filterable: true },
  { id: "spec-ski-w", categoryId: "cat-ski-ergs", key: "widthMm", label: "Width", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
  { id: "spec-ski-d", categoryId: "cat-ski-ergs", key: "depthMm", label: "Depth", type: "measurement", unit: "mm", comparisonPriority: 70, finderRelevant: true, filterable: true },
];

function cardioProduct(input: {
  id: string;
  slug: string;
  brandId: string;
  name: string;
  fullName: string;
  shortDescription: string;
  categoryId: string;
  useCaseIds: string[];
  specifications: Product["specifications"];
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  priceEur: number;
  relatedProductIds?: string[];
}): Product {
  return {
    id: input.id,
    slug: input.slug,
    brandId: input.brandId,
    name: input.name,
    fullName: input.fullName,
    shortDescription: input.shortDescription,
    lifecycleStatus: "current",
    sportIds: ["sport-training", "sport-hyrox"],
    disciplineIds: ["disc-training-conditioning", "disc-training-home", "disc-training-hyrox"],
    categoryId: input.categoryId,
    subcategoryIds: [],
    useCaseIds: input.useCaseIds,
    specifications: input.specifications,
    strengths: input.strengths,
    weaknesses: input.weaknesses,
    recommendationScore: input.recommendationScore,
    valueScore: input.valueScore,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage(
      input.categoryId,
      input.id,
      `${input.fullName} — product image unavailable`,
    ),
    videos: [],
    offerIds: [
      `offer-${input.slug}-nl`,
      `offer-${input.slug}-de`,
      `offer-${input.slug}-uk`,
    ],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: input.relatedProductIds ?? [],
    alternativeProductIds: [],
    ...pub,
  };
}

export const wave24Products: Product[] = [
  // —— Weight plates (canonical Eleiko / Mirafit / ATX SKUs) ——
  {
    id: "prod-eleiko-sport-bumper",
    slug: "eleiko-sport-bumper-set",
    brandId: "brand-eleiko",
    name: "Sport Bumper Set",
    fullName: "Eleiko Sport Bumper Plate Set",
    shortDescription: "Premium competition-diameter bumper set for Olympic lifting and home platforms.",
    lifecycleStatus: "current",
    sportIds: [sportTraining],
    disciplineIds: ["disc-training-strength", "disc-training-home"],
    categoryId: "cat-weight-plates",
    subcategoryIds: [],
    useCaseIds: ["uc-home-gym", "uc-olympic-lifting", "uc-garage-gym"],
    specifications: {
      plateType: "bumper",
      diameterMm: 450,
      material: "rubber",
    },
    strengths: ["Consistent diameter for platform work", "Premium build"],
    weaknesses: ["High price vs training bumpers"],
    recommendationScore: 91,
    valueScore: 62,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage("cat-weight-plates", "prod-eleiko-sport-bumper", "Eleiko Sport Bumper Plate Set — product image unavailable"),
    videos: [],
    offerIds: ["offer-eleiko-sport-bumper-set-nl", "offer-eleiko-sport-bumper-set-de", "offer-eleiko-sport-bumper-set-uk"],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: ["prod-rogue-echo-bumper"],
    alternativeProductIds: ["prod-rogue-echo-bumper"],
    ...pub,
  },
  {
    id: "prod-mirafit-bumper-set",
    slug: "mirafit-bumper-plate-set",
    brandId: "brand-mirafit",
    name: "Bumper Plate Set",
    fullName: "Mirafit Bumper Plate Set",
    shortDescription: "Value bumper set for home Olympic lifting and garage gyms in UK/EU.",
    lifecycleStatus: "current",
    sportIds: [sportTraining],
    disciplineIds: ["disc-training-strength", "disc-training-home"],
    categoryId: "cat-weight-plates",
    subcategoryIds: [],
    useCaseIds: ["uc-home-gym", "uc-garage-gym", "uc-beginner-strength"],
    specifications: {
      plateType: "bumper",
      diameterMm: 450,
      material: "rubber",
    },
    strengths: ["Strong EU/UK availability", "Good value entry bumpers"],
    weaknesses: ["Less refined than competition plates"],
    recommendationScore: 80,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage("cat-weight-plates", "prod-mirafit-bumper-set", "Mirafit Bumper Plate Set — product image unavailable"),
    videos: [],
    offerIds: ["offer-mirafit-bumper-plate-set-nl", "offer-mirafit-bumper-plate-set-de", "offer-mirafit-bumper-plate-set-uk"],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: ["prod-eleiko-sport-bumper"],
    alternativeProductIds: ["prod-eleiko-sport-bumper"],
    ...pub,
  },
  {
    id: "prod-atx-cast-iron-set",
    slug: "atx-cast-iron-plate-set",
    brandId: "brand-atx",
    name: "Cast Iron Plate Set",
    fullName: "ATX Cast Iron Olympic Plate Set",
    shortDescription: "Compact iron plates for strength training where bumper diameter is unnecessary.",
    lifecycleStatus: "current",
    sportIds: [sportTraining],
    disciplineIds: ["disc-training-strength", "disc-training-home"],
    categoryId: "cat-weight-plates",
    subcategoryIds: [],
    useCaseIds: ["uc-home-gym", "uc-small-space", "uc-powerlifting"],
    specifications: {
      plateType: "iron",
      diameterMm: null,
      material: "cast-iron",
    },
    strengths: ["Smaller diameter for rack storage", "EU brand"],
    weaknesses: ["Not for dropped Olympic lifts"],
    recommendationScore: 78,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-weight-plates", "prod-atx-cast-iron-set", "ATX Cast Iron Olympic Plate Set — product image unavailable"),
    videos: [],
    offerIds: ["offer-atx-cast-iron-plate-set-nl", "offer-atx-cast-iron-plate-set-de", "offer-atx-cast-iron-plate-set-uk"],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: ["prod-mirafit-bumper-set"],
    alternativeProductIds: [],
    ...pub,
  },

  // —— Treadmills ——
  cardioProduct({
    id: "prod-sole-f80",
    slug: "sole-f80-treadmill",
    brandId: "brand-sole",
    name: "F80 Treadmill",
    fullName: "Sole F80 Treadmill",
    shortDescription: "Motorised folding treadmill aimed at serious home running mileage.",
    categoryId: "cat-treadmills",
    useCaseIds: ["uc-home-gym", "uc-garage-gym"],
    specifications: {
      motorised: true,
      foldable: true,
      maxUserWeight: 170,
      maxSpeedKph: 20,
      widthMm: 890,
      depthMm: 2080,
    },
    strengths: ["Strong home-running deck", "Folds for storage"],
    weaknesses: ["Large footprint when open", "Shipping/install heavy"],
    recommendationScore: 86,
    valueScore: 74,
    priceEur: 1899,
    relatedProductIds: ["prod-mirafit-treadmill", "prod-assault-runner"],
  }),
  cardioProduct({
    id: "prod-horizon-t202",
    slug: "horizon-t202-treadmill",
    brandId: "brand-horizon",
    name: "T202 Treadmill",
    fullName: "Horizon Fitness T202 Treadmill",
    shortDescription: "Approachable folding treadmill for walking and jogging at home.",
    categoryId: "cat-treadmills",
    useCaseIds: ["uc-apartment-gym", "uc-small-space", "uc-home-gym", "uc-beginner-strength"],
    specifications: {
      motorised: true,
      foldable: true,
      maxUserWeight: 136,
      maxSpeedKph: 16,
      widthMm: 850,
      depthMm: 1750,
    },
    strengths: ["Apartment-friendly fold", "Lower entry price band"],
    weaknesses: ["Not built for elite sprint intervals"],
    recommendationScore: 74,
    valueScore: 88,
    priceEur: 799,
    relatedProductIds: ["prod-mirafit-treadmill", "prod-sole-f80"],
  }),
  cardioProduct({
    id: "prod-woodway-curve",
    slug: "woodway-curve-trainer",
    brandId: "brand-woodway",
    name: "Curve Trainer",
    fullName: "Woodway Curve Trainer",
    shortDescription: "Non-motorised curved treadmill for high-intensity sprint conditioning.",
    categoryId: "cat-treadmills",
    useCaseIds: ["uc-garage-gym", "uc-hyrox-training"],
    specifications: {
      motorised: false,
      foldable: false,
      maxUserWeight: 180,
      widthMm: 860,
      depthMm: 1750,
    },
    strengths: ["Self-paced sprint stimulus", "Commercial-grade feel"],
    weaknesses: ["Premium price", "Not foldable"],
    recommendationScore: 88,
    valueScore: 58,
    priceEur: 4990,
    relatedProductIds: ["prod-assault-runner", "prod-assault-runner-elite"],
  }),

  // —— Rowers ——
  cardioProduct({
    id: "prod-hydrow-wave",
    slug: "hydrow-wave",
    brandId: "brand-hydrow",
    name: "Wave",
    fullName: "Hydrow Wave",
    shortDescription: "Connected rower with on-demand coaching; quieter than air rowers for apartments.",
    categoryId: "cat-rowing-machines",
    useCaseIds: ["uc-apartment-gym", "uc-home-gym", "uc-general-fitness"],
    specifications: {
      resistanceType: "magnetic",
      maxUserWeight: 170,
      dimensions: "compact connected rower",
    },
    strengths: ["Quiet magnetic resistance", "Guided workouts"],
    weaknesses: ["Subscription ecosystem", "Not Concept2 score standard"],
    recommendationScore: 79,
    valueScore: 68,
    priceEur: 1499,
    relatedProductIds: ["prod-concept2-rowerg", "prod-mirafit-rower"],
  }),
  cardioProduct({
    id: "prod-waterrower-a1",
    slug: "waterrower-a1",
    brandId: "brand-waterrower",
    name: "A1 Home",
    fullName: "WaterRower A1 Home",
    shortDescription: "Wood-frame water rower for quiet home conditioning with natural resistance feel.",
    categoryId: "cat-rowing-machines",
    useCaseIds: ["uc-home-gym", "uc-apartment-gym", "uc-general-fitness"],
    specifications: {
      resistanceType: "water",
      maxUserWeight: 160,
      dimensions: "wood water rower",
    },
    strengths: ["Quiet water resistance", "Living-room aesthetic"],
    weaknesses: ["Not Concept2 race-score standard"],
    recommendationScore: 77,
    valueScore: 72,
    priceEur: 999,
    relatedProductIds: ["prod-concept2-rowerg", "prod-hydrow-wave"],
  }),

  // —— Air bikes ——
  cardioProduct({
    id: "prod-concept2-bikeerg",
    slug: "concept2-bikeerg",
    brandId: "brand-concept2",
    name: "BikeErg",
    fullName: "Concept2 BikeErg",
    shortDescription: "Air-resistance bike sharing Concept2 monitor ecosystem with RowErg and SkiErg.",
    categoryId: "cat-air-bikes",
    useCaseIds: ["uc-home-gym", "uc-hyrox-training", "uc-garage-gym"],
    specifications: {
      maxUserWeight: 160,
      widthMm: 610,
      depthMm: 1220,
    },
    strengths: ["PM5 ecosystem", "Comparable scores"],
    weaknesses: ["Different stimulus than dual-action AssaultBike"],
    recommendationScore: 89,
    valueScore: 78,
    priceEur: 1190,
    relatedProductIds: ["prod-rogue-echo-bike", "prod-assault-elite"],
  }),
  cardioProduct({
    id: "prod-schwinn-airdyne-ad8",
    slug: "schwinn-airdyne-ad8",
    brandId: "brand-schwinn",
    name: "Airdyne AD8",
    fullName: "Schwinn Airdyne AD8",
    shortDescription: "Dual-action air bike for HIIT and home conditioning.",
    categoryId: "cat-air-bikes",
    useCaseIds: ["uc-home-gym", "uc-general-fitness", "uc-garage-gym"],
    specifications: {
      maxUserWeight: 159,
      widthMm: 660,
      depthMm: 1280,
    },
    strengths: ["Proven air-bike format", "Broad retail availability"],
    weaknesses: ["Less HYROX-specific than Echo/Assault"],
    recommendationScore: 81,
    valueScore: 80,
    priceEur: 899,
    relatedProductIds: ["prod-rogue-echo-bike", "prod-assault-elite"],
  }),
  cardioProduct({
    id: "prod-mirafit-air-bike",
    slug: "mirafit-air-bike",
    brandId: "brand-mirafit",
    name: "Air Bike",
    fullName: "Mirafit Air Bike",
    shortDescription: "Budget dual-action air bike for UK/EU home gyms.",
    categoryId: "cat-air-bikes",
    useCaseIds: ["uc-home-gym", "uc-apartment-gym", "uc-beginner-strength"],
    specifications: {
      maxUserWeight: 150,
      widthMm: 640,
      depthMm: 1250,
    },
    strengths: ["Lower price", "EU/UK shipping friendliness"],
    weaknesses: ["Less refined than Echo/Assault"],
    recommendationScore: 72,
    valueScore: 92,
    priceEur: 449,
    relatedProductIds: ["prod-schwinn-airdyne-ad8", "prod-rogue-echo-bike"],
  }),

  // —— Ski erg ——
  cardioProduct({
    id: "prod-xebex-skierg",
    slug: "xebex-ski-erg",
    brandId: "brand-xebex",
    name: "Ski Erg",
    fullName: "Xebex Ski Erg",
    shortDescription: "Air ski erg for HYROX station practice with optional floor stand.",
    categoryId: "cat-ski-ergs",
    useCaseIds: ["uc-hyrox-training", "uc-home-gym", "uc-garage-gym"],
    specifications: {
      mountType: "optional",
      widthMm: 610,
      depthMm: 1220,
    },
    strengths: ["HYROX station familiarisation", "Optional freestanding"],
    weaknesses: ["Not Concept2 PM5 ecosystem"],
    recommendationScore: 76,
    valueScore: 82,
    priceEur: 799,
    relatedProductIds: ["prod-concept2-skierg", "prod-concept2-skierg-stand"],
  }),
  cardioProduct({
    id: "prod-concept2-skierg-pm5-bundle",
    slug: "concept2-skierg-with-stand",
    brandId: "brand-concept2",
    name: "SkiErg + Floor Stand",
    fullName: "Concept2 SkiErg with Floor Stand Bundle",
    shortDescription: "Complete freestanding SkiErg package when wall mounting is not allowed.",
    categoryId: "cat-ski-ergs",
    useCaseIds: ["uc-hyrox-training", "uc-apartment-gym", "uc-home-gym"],
    specifications: {
      mountType: "floor-stand",
      widthMm: 610,
      depthMm: 1320,
    },
    strengths: ["No wall drilling", "PM5 standard"],
    weaknesses: ["Higher package cost than wall-only"],
    recommendationScore: 90,
    valueScore: 70,
    priceEur: 1290,
    relatedProductIds: ["prod-concept2-skierg", "prod-concept2-skierg-stand"],
  }),
  cardioProduct({
    id: "prod-skierg2-wall",
    slug: "skierg2-wall-mount",
    brandId: "brand-xebex",
    name: "SkiErg2 Wall",
    fullName: "SkiErg2 Wall-Mount Trainer",
    shortDescription: "Compact wall-mounted ski erg alternative for HYROX station practice when Concept2 is unavailable.",
    categoryId: "cat-ski-ergs",
    useCaseIds: ["uc-hyrox-training", "uc-home-gym", "uc-small-space"],
    specifications: {
      mountType: "wall",
      widthMm: 580,
      depthMm: 500,
    },
    strengths: ["Smaller depth than freestanding packages", "Station familiarisation"],
    weaknesses: ["Requires suitable wall structure", "Not Concept2 PM5"],
    recommendationScore: 74,
    valueScore: 80,
    priceEur: 699,
    relatedProductIds: ["prod-concept2-skierg", "prod-xebex-skierg"],
  }),

  // —— Bench ——
  {
    id: "prod-atx-fid-bench",
    slug: "atx-fid-bench",
    brandId: "brand-atx",
    name: "FID Bench",
    fullName: "ATX Flat Incline Decline Bench",
    shortDescription: "Adjustable FID bench for European home gyms with solid pad width.",
    lifecycleStatus: "current",
    sportIds: [sportTraining],
    disciplineIds: ["disc-training-strength", "disc-training-home"],
    categoryId: "cat-weight-benches",
    subcategoryIds: [],
    useCaseIds: ["uc-home-gym", "uc-garage-gym", "uc-bodybuilding"],
    specifications: {
      benchType: "fid",
      weightCapacity: 400,
      widthMm: 700,
      depthMm: 1400,
      foldable: false,
    },
    strengths: ["Full FID adjustability", "EU availability"],
    weaknesses: ["Not the lightest to move"],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-weight-benches", "prod-atx-fid-bench", "ATX Flat Incline Decline Bench — product image unavailable"),
    videos: [],
    offerIds: ["offer-atx-fid-bench-nl", "offer-atx-fid-bench-de", "offer-atx-fid-bench-uk"],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: ["prod-rogue-adjustable-bench-3"],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-rep-ab-5200",
    slug: "rep-ab-5200",
    brandId: "brand-rep",
    name: "AB-5200",
    fullName: "REP AB-5200 Adjustable Bench",
    shortDescription: "Wide-pad adjustable bench popular in garage strength setups.",
    lifecycleStatus: "current",
    sportIds: [sportTraining],
    disciplineIds: ["disc-training-strength", "disc-training-home"],
    categoryId: "cat-weight-benches",
    subcategoryIds: [],
    useCaseIds: ["uc-garage-gym", "uc-home-gym", "uc-powerlifting"],
    specifications: {
      benchType: "adjustable",
      weightCapacity: 454,
      widthMm: 762,
      depthMm: 1422,
      foldable: false,
    },
    strengths: ["Wide pad", "High rated capacity"],
    weaknesses: ["Larger footprint than utility benches"],
    recommendationScore: 88,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-weight-benches", "prod-rep-ab-5200", "REP AB-5200 Adjustable Bench — product image unavailable"),
    videos: [],
    offerIds: ["offer-rep-ab-5200-nl", "offer-rep-ab-5200-de", "offer-rep-ab-5200-uk"],
    evidenceIds: ["ev-fitness-mfr", "ev-wave24-editorial"],
    relatedProductIds: ["prod-rogue-adjustable-bench-3", "prod-atx-fid-bench"],
    alternativeProductIds: ["prod-atx-fid-bench"],
    ...pub,
  },
];

// (brand ids set inline on products above)

export const wave24Evidence: Evidence[] = [
  {
    id: "ev-wave24-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — fitness catalog",
    summary:
      "Category placement, publicly listed dimensions/features and positioning from manufacturer pages and reputable retailers. Not personal lab testing.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];

export const wave24Recommendations: Recommendation[] = [
  {
    id: "rec-sole-f80-home",
    productId: "prod-sole-f80",
    sportId: sportTraining,
    useCaseId: "uc-home-gym",
    score: 86,
    factors: [
      { key: "running", label: "Home running", score: 88, weight: 0.5 },
      { key: "fold", label: "Storage", score: 80, weight: 0.3 },
      { key: "value", label: "Value", score: 72, weight: 0.2 },
    ],
    strengths: ["Serious home mileage deck"],
    compromises: ["Heavy shipping / large when open"],
    explanation: "Strong motorised treadmill when running at home is the primary goal.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-horizon-t202-apt",
    productId: "prod-horizon-t202",
    sportId: sportTraining,
    useCaseId: "uc-apartment-gym",
    score: 78,
    factors: [
      { key: "fold", label: "Folding", score: 86, weight: 0.45 },
      { key: "noise", label: "Apartment fit", score: 78, weight: 0.35 },
      { key: "value", label: "Value", score: 88, weight: 0.2 },
    ],
    strengths: ["Folding apartment option"],
    compromises: ["Not elite sprint hardware"],
    explanation: "Budget folding treadmill when space and quiet matter more than max speed.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-bikeerg-hyrox",
    productId: "prod-concept2-bikeerg",
    sportId: "sport-hyrox",
    useCaseId: "uc-hyrox-conditioning",
    score: 84,
    factors: [
      { key: "ecosystem", label: "Concept2 ecosystem", score: 92, weight: 0.5 },
      { key: "conditioning", label: "Conditioning", score: 86, weight: 0.5 },
    ],
    strengths: ["PM5 ecosystem with Row/Ski"],
    compromises: ["Different pattern than dual-action fan bike"],
    explanation: "Useful HYROX conditioning bike when Concept2 scores matter.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-skierg-bundle-home",
    productId: "prod-concept2-skierg-pm5-bundle",
    sportId: "sport-hyrox",
    useCaseId: "uc-hyrox-home-training",
    score: 90,
    factors: [
      { key: "station", label: "Station familiarity", score: 94, weight: 0.55 },
      { key: "mount", label: "No-wall option", score: 90, weight: 0.45 },
    ],
    strengths: ["Floor stand when walls cannot be drilled"],
    compromises: ["Higher package cost"],
    explanation: "Best Concept2 SkiErg path for apartments without wall mounting.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-eleiko-plates-oly",
    productId: "prod-eleiko-sport-bumper",
    sportId: sportTraining,
    useCaseId: "uc-olympic-lifting",
    score: 92,
    factors: [
      { key: "diameter", label: "Competition diameter", score: 95, weight: 0.5 },
      { key: "quality", label: "Build", score: 94, weight: 0.5 },
    ],
    strengths: ["Premium bumper standard"],
    compromises: ["Expensive"],
    explanation: "Flagship bumper choice when Olympic lifting quality matters.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-mirafit-plates-value",
    productId: "prod-mirafit-bumper-set",
    sportId: sportTraining,
    useCaseId: "uc-home-gym",
    score: 82,
    factors: [
      { key: "value", label: "Value", score: 92, weight: 0.5 },
      { key: "availability", label: "EU/UK availability", score: 88, weight: 0.5 },
    ],
    strengths: ["Strong value for home platforms"],
    compromises: ["Less refined than Eleiko"],
    explanation: "Value bumper set for EU/UK home gyms.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-rep-bench-garage",
    productId: "prod-rep-ab-5200",
    sportId: sportTraining,
    useCaseId: "uc-garage-gym",
    score: 88,
    factors: [
      { key: "pad", label: "Pad width", score: 90, weight: 0.45 },
      { key: "capacity", label: "Capacity", score: 90, weight: 0.55 },
    ],
    strengths: ["Wide stable pad"],
    compromises: ["Larger footprint"],
    explanation: "Garage strength adjustable bench with high capacity.",
    evidenceIds: ["ev-wave24-editorial"],
  },
  {
    id: "rec-flite-hyrox-race-w24",
    productId: "prod-inov8-flite-235-v3",
    sportId: "sport-hyrox",
    useCaseId: "uc-hyrox-race",
    score: 83,
    factors: [
      { key: "running", label: "Running", score: 91, weight: 0.5 },
      { key: "stability", label: "Stations", score: 70, weight: 0.5 },
    ],
    strengths: ["Running-first race option"],
    compromises: ["Less planted than Metcon/Nano"],
    explanation: "Running-biased HYROX race shoe when pace dominates stations.",
    evidenceIds: ["ev-wave24-editorial"],
  },
];

export const wave24Offers: Offer[] = [
  ...offerTriplet("prod-eleiko-sport-bumper", "eleiko-sport-bumper-set", 1899),
  ...offerTriplet("prod-mirafit-bumper-set", "mirafit-bumper-plate-set", 549),
  ...offerTriplet("prod-atx-cast-iron-set", "atx-cast-iron-plate-set", 399),
  ...offerTriplet("prod-sole-f80", "sole-f80-treadmill", 1899),
  ...offerTriplet("prod-horizon-t202", "horizon-t202-treadmill", 799),
  ...offerTriplet("prod-woodway-curve", "woodway-curve-trainer", 4990),
  ...offerTriplet("prod-hydrow-wave", "hydrow-wave", 1499),
  ...offerTriplet("prod-waterrower-a1", "waterrower-a1", 999),
  ...offerTriplet("prod-concept2-bikeerg", "concept2-bikeerg", 1190),
  ...offerTriplet("prod-schwinn-airdyne-ad8", "schwinn-airdyne-ad8", 899),
  ...offerTriplet("prod-mirafit-air-bike", "mirafit-air-bike", 449),
  ...offerTriplet("prod-xebex-skierg", "xebex-ski-erg", 799),
  ...offerTriplet("prod-concept2-skierg-pm5-bundle", "concept2-skierg-with-stand", 1290),
  ...offerTriplet("prod-skierg2-wall", "skierg2-wall-mount", 699),
  ...offerTriplet("prod-atx-fid-bench", "atx-fid-bench", 349),
  ...offerTriplet("prod-rep-ab-5200", "rep-ab-5200", 499),
];

export const wave24BestGuides: BestGuide[] = [
  {
    id: "best-adjustable-benches",
    slug: "adjustable-benches",
    title: "Best Adjustable Benches",
    sportId: sportTraining,
    categoryId: "cat-weight-benches",
    useCaseIds: ["uc-home-gym", "uc-garage-gym"],
    rankingMode: "category-picks",
    intro: "Adjustable benches for pressing, accessories and garage strength setups.",
    selectionMethodology: "Pad width, adjustability, capacity, footprint and regional availability.",
    selectionCriteria: [
      { key: "adjust", label: "Adjustability", description: "FID vs incline-only." },
      { key: "pad", label: "Pad", description: "Width and stability under load." },
      { key: "value", label: "Value", description: "Price vs durability positioning." },
    ],
    recommendations: [
      { productId: "prod-rep-ab-5200", rank: 1, awardType: "best-overall", rationale: "Wide pad and high capacity for garage gyms." },
      { productId: "prod-rogue-adjustable-bench-3", rank: 2, badge: "Best Premium", rationale: "Rogue ecosystem and build reputation." },
      { productId: "prod-atx-fid-bench", rank: 3, awardType: "best-value", rationale: "Strong EU FID option." },
    ],
    comparisonProductIds: ["prod-rep-ab-5200", "prod-rogue-adjustable-bench-3", "prod-atx-fid-bench"],
    buyingAdvice: "Match pad width to your pressing style; check folded vs open footprint for small rooms.",
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder"],
    ...pub,
  },
  {
    id: "best-air-bikes",
    slug: "air-bikes",
    title: "Best Air Bikes",
    sportId: sportTraining,
    categoryId: "cat-air-bikes",
    useCaseIds: ["uc-home-gym", "uc-hyrox-training"],
    rankingMode: "category-picks",
    intro: "Dual-action and Concept2 air bikes for HIIT and conditioning.",
    selectionMethodology: "Drive type, durability positioning, monitor ecosystem and EU/UK availability.",
    selectionCriteria: [
      { key: "stimulus", label: "Stimulus", description: "Dual-action vs BikeErg pattern." },
      { key: "ecosystem", label: "Ecosystem", description: "PM5 / comparable scores." },
      { key: "value", label: "Value", description: "Price band vs build." },
    ],
    recommendations: [
      { productId: "prod-rogue-echo-bike", rank: 1, awardType: "best-overall", rationale: "Proven dual-action conditioning bike." },
      { productId: "prod-concept2-bikeerg", rank: 2, badge: "Best Ecosystem", rationale: "Shares Concept2 PM5 with Row/Ski." },
      { productId: "prod-assault-elite", rank: 3, badge: "Best Assault", rationale: "AssaultBike lineage for HIIT." },
      { productId: "prod-mirafit-air-bike", rank: 4, awardType: "best-value", rationale: "Budget EU/UK entry." },
    ],
    comparisonProductIds: ["prod-rogue-echo-bike", "prod-concept2-bikeerg", "prod-assault-elite"],
    buyingAdvice: "Choose Echo/Assault for dual-action metcons; BikeErg when Concept2 scores matter.",
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder"],
    ...pub,
  },
  {
    id: "best-treadmills-home",
    slug: "treadmills-for-home",
    title: "Best Treadmills for Home",
    sportId: sportTraining,
    categoryId: "cat-treadmills",
    useCaseIds: ["uc-home-gym", "uc-apartment-gym"],
    rankingMode: "category-picks",
    intro: "Motorised and curved treadmills that fit real home spaces.",
    selectionMethodology: "Motor vs curved, foldability, user weight, noise and footprint.",
    selectionCriteria: [
      { key: "use", label: "Use", description: "Walking, jogging, sprint conditioning." },
      { key: "space", label: "Space", description: "Folding and footprint." },
      { key: "noise", label: "Apartment", description: "Neighbour-friendly options." },
    ],
    recommendations: [
      { productId: "prod-sole-f80", rank: 1, awardType: "best-overall", rationale: "Serious home running deck." },
      { productId: "prod-horizon-t202", rank: 2, badge: "Best Apartment", rationale: "Folding entry for smaller spaces." },
      { productId: "prod-assault-runner", rank: 3, badge: "Best Curved", rationale: "Non-motorised sprint conditioning." },
      { productId: "prod-mirafit-treadmill", rank: 4, awardType: "best-value", rationale: "Budget fold for EU/UK." },
    ],
    comparisonProductIds: ["prod-sole-f80", "prod-horizon-t202", "prod-assault-runner"],
    buyingAdvice: "Curved self-powered decks for sprints; motorised fold for daily jogging mileage.",
    faqIds: [],
    relatedToolSlugs: ["treadmill-finder", "home-gym-builder"],
    ...pub,
  },
  {
    id: "best-weight-plates",
    slug: "weight-plates",
    title: "Best Weight Plates",
    sportId: sportTraining,
    categoryId: "cat-weight-plates",
    useCaseIds: ["uc-home-gym", "uc-olympic-lifting"],
    rankingMode: "category-picks",
    intro: "Bumper and iron plates for home platforms and strength training.",
    selectionMethodology: "Plate type, diameter, material and regional value.",
    selectionCriteria: [
      { key: "type", label: "Type", description: "Bumper vs iron." },
      { key: "diameter", label: "Diameter", description: "Competition vs compact." },
      { key: "value", label: "Value", description: "Price per kg positioning." },
    ],
    recommendations: [
      { productId: "prod-eleiko-sport-bumper", rank: 1, awardType: "best-overall", rationale: "Premium competition-diameter bumpers." },
      { productId: "prod-rogue-echo-bumper", rank: 2, badge: "Best Training Bumper", rationale: "Durable training bumpers." },
      { productId: "prod-mirafit-bumper-set", rank: 3, awardType: "best-value", rationale: "EU/UK value set." },
      { productId: "prod-atx-cast-iron-set", rank: 4, badge: "Best Compact", rationale: "Iron when bumper diameter is unnecessary." },
    ],
    comparisonProductIds: ["prod-eleiko-sport-bumper", "prod-mirafit-bumper-set", "prod-atx-cast-iron-set"],
    buyingAdvice: "Bumpers if you drop Olympic lifts; iron if storage diameter matters more.",
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder"],
    ...pub,
  },
];

export const wave24BuyingGuides: BuyingGuide[] = [
  {
    id: "guide-choose-power-rack",
    slug: "how-to-choose-a-power-rack",
    title: "How to Choose a Power Rack",
    sportId: sportTraining,
    categoryId: "cat-power-racks",
    relatedProductIds: ["prod-rogue-rml-390f", "prod-rep-pr-4000", "prod-mirafit-m3"],
    relatedUseCaseIds: ["uc-home-gym", "uc-garage-gym", "uc-small-space"],
    sections: [
      { id: "s1", heading: "Height first", body: "Ceiling clearance must exceed rack height plus bar path. Home Gym Builder rejects impossible geometry." },
      { id: "s2", heading: "Mounting", body: "Freestanding vs floor-bolted vs wall-mounted changes what rooms allow. Do not infer mounting from brand alone." },
      { id: "s3", heading: "Ecosystem", body: "Attachment compatibility is series-specific — same brand does not guarantee fit." },
    ],
    faqIds: [],
    relatedToolSlugs: ["power-rack-finder", "home-gym-builder"],
    ...pub,
  },
  {
    id: "guide-choose-bench",
    slug: "how-to-choose-a-weight-bench",
    title: "How to Choose a Weight Bench",
    sportId: sportTraining,
    categoryId: "cat-weight-benches",
    relatedProductIds: ["prod-rep-ab-5200", "prod-atx-fid-bench"],
    relatedUseCaseIds: ["uc-home-gym"],
    sections: [
      { id: "s1", heading: "Flat vs adjustable", body: "Flat benches are simpler; FID expands press angles at the cost of bulk." },
      { id: "s2", heading: "Pad width", body: "Wider pads feel stable for heavy pressing; narrower can help setup for some lifters." },
    ],
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder"],
    ...pub,
  },
  {
    id: "guide-choose-adb",
    slug: "how-to-choose-adjustable-dumbbells",
    title: "How to Choose Adjustable Dumbbells",
    sportId: sportTraining,
    categoryId: "cat-adjustable-dumbbells",
    relatedProductIds: ["prod-nuobell-80", "prod-powerblock-pro-100"],
    relatedUseCaseIds: ["uc-home-gym", "uc-apartment-gym"],
    sections: [
      { id: "s1", heading: "Range vs footprint", body: "Higher max weight often means longer handles or larger cradles — measure storage." },
      { id: "s2", heading: "Adjustment speed", body: "Dial vs twist-lock vs selector pin changes workout flow." },
    ],
    faqIds: [],
    relatedToolSlugs: ["adjustable-dumbbell-finder"],
    ...pub,
  },
  {
    id: "guide-choose-treadmill",
    slug: "how-to-choose-a-home-treadmill",
    title: "How to Choose a Home Treadmill",
    sportId: sportTraining,
    categoryId: "cat-treadmills",
    relatedProductIds: ["prod-sole-f80", "prod-horizon-t202", "prod-assault-runner"],
    relatedUseCaseIds: ["uc-home-gym", "uc-apartment-gym"],
    sections: [
      { id: "s1", heading: "Motorised vs curved", body: "Motorised for steady jogging; curved self-powered for sprint conditioning." },
      { id: "s2", heading: "Folding", body: "Folding helps apartments but does not shrink operating length while running." },
    ],
    faqIds: [],
    relatedToolSlugs: ["treadmill-finder"],
    ...pub,
  },
  {
    id: "guide-choose-rower",
    slug: "how-to-choose-a-rowing-machine",
    title: "How to Choose a Rowing Machine",
    sportId: sportTraining,
    categoryId: "cat-rowing-machines",
    relatedProductIds: ["prod-concept2-rowerg", "prod-hydrow-wave", "prod-waterrower-a1"],
    relatedUseCaseIds: ["uc-home-gym", "uc-hyrox-training"],
    sections: [
      { id: "s1", heading: "Air vs magnetic vs water", body: "Air (Concept2) for comparable scores; magnetic/water often quieter for apartments." },
      { id: "s2", heading: "HYROX", body: "Race stations use Concept2-class air rowers — practice specificity matters if competing." },
    ],
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder"],
    ...pub,
  },
  {
    id: "guide-home-gym-space",
    slug: "how-much-space-do-you-need-for-a-home-gym",
    title: "How Much Space Do You Need for a Home Gym?",
    sportId: sportTraining,
    relatedProductIds: ["prod-rogue-rml-390f", "prod-nuobell-80"],
    relatedUseCaseIds: ["uc-home-gym", "uc-small-space", "uc-apartment-gym"],
    sections: [
      { id: "s1", heading: "Operating vs stored", body: "Racks and treadmills need operating clearance beyond shipping dimensions." },
      { id: "s2", heading: "Use the planner", body: "Home Gym Builder models footprints in mm — prefer planner-ready Products." },
    ],
    faqIds: [],
    relatedToolSlugs: ["home-gym-builder", "power-rack-finder"],
    ...pub,
  },
  {
    id: "guide-bumper-vs-iron",
    slug: "bumper-plates-vs-iron-plates",
    title: "Bumper Plates vs Iron Plates",
    sportId: sportTraining,
    categoryId: "cat-weight-plates",
    relatedProductIds: ["prod-eleiko-sport-bumper", "prod-atx-cast-iron-set"],
    relatedUseCaseIds: ["uc-home-gym", "uc-olympic-lifting"],
    sections: [
      { id: "s1", heading: "Dropping", body: "Bumpers tolerate drops on platforms; iron does not." },
      { id: "s2", heading: "Diameter", body: "Competition bumpers stay ~450 mm; iron is often smaller for storage." },
    ],
    faqIds: [],
    ...pub,
  },
];

export const wave24Comparisons: Comparison[] = [
  {
    id: "cmp-echo-vs-assault",
    slug: "rogue-echo-bike-vs-assaultbike-elite",
    title: "Rogue Echo Bike vs AssaultBike Elite",
    categoryId: "cat-air-bikes",
    productIds: ["prod-rogue-echo-bike", "prod-assault-elite"],
    comparisonType: "hybrid",
    summary: "Two flagship dual-action air bikes for HIIT and garage conditioning.",
    verdict: "Both excel at dual-action metcons; pick on availability, budget and preferred monitor/ecosystem.",
    criteria: [
      { key: "stimulus", label: "Stimulus" },
      { key: "value", label: "Value", winnerProductId: "prod-rogue-echo-bike" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-hyrox-training",
        productId: "prod-rogue-echo-bike",
        rationale: "Widely available dual-action conditioning bike.",
      },
      {
        useCaseId: "uc-garage-gym",
        productId: "prod-assault-elite",
        rationale: "AssaultBike lineage for serious HIIT spaces.",
      },
    ],
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-sole-vs-horizon",
    slug: "sole-f80-vs-horizon-t202",
    title: "Sole F80 vs Horizon T202",
    categoryId: "cat-treadmills",
    productIds: ["prod-sole-f80", "prod-horizon-t202"],
    comparisonType: "hybrid",
    summary: "Serious home-running deck versus apartment-friendly folding entry treadmill.",
    verdict: "Choose Sole F80 for mileage quality; Horizon T202 when fold and budget dominate.",
    criteria: [
      { key: "running", label: "Running quality", winnerProductId: "prod-sole-f80" },
      { key: "apartment", label: "Apartment fit", winnerProductId: "prod-horizon-t202" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-home-gym",
        productId: "prod-sole-f80",
        rationale: "Better deck for regular running mileage.",
      },
      {
        useCaseId: "uc-apartment-gym",
        productId: "prod-horizon-t202",
        rationale: "Folding and lower entry price.",
      },
    ],
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-c2-vs-hydrow",
    slug: "concept2-rowerg-vs-hydrow-wave",
    title: "Concept2 RowErg vs Hydrow Wave",
    categoryId: "cat-rowing-machines",
    productIds: ["prod-concept2-rowerg", "prod-hydrow-wave"],
    comparisonType: "hybrid",
    summary: "Comparable-score air rower versus quiet connected coaching rower.",
    verdict: "Concept2 for scores and HYROX practice; Hydrow when quiet guided workouts matter more.",
    criteria: [
      { key: "scores", label: "Comparable scores", winnerProductId: "prod-concept2-rowerg" },
      { key: "quiet", label: "Apartment quiet", winnerProductId: "prod-hydrow-wave" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-hyrox-training",
        productId: "prod-concept2-rowerg",
        rationale: "Race-station familiarity and scores.",
      },
      {
        useCaseId: "uc-apartment-gym",
        productId: "prod-hydrow-wave",
        rationale: "Quieter magnetic connected rower.",
      },
    ],
    faqIds: [],
    ...pub,
  },
];

export const wave24GearSetups: GearSetup[] = [
  {
    id: "setup-budget-home-gym",
    slug: "budget-home-gym",
    title: "Budget Home Gym",
    sportId: sportTraining,
    description:
      "Lean starter strength setup: adjustable dumbbells, doorway pull-up and mats. Dynamic regional Offers apply — no hardcoded currency claims.",
    useCaseIds: ["uc-home-gym", "uc-apartment-gym", "uc-beginner-strength"],
    budgetRange: { min: 400, max: 1000, currency: "EUR" },
    items: [
      { productId: "prod-nuobell-50", role: "Adjustable Dumbbells" },
      { productId: "prod-pullup-dip-doorway", role: "Pull-Up Bar" },
      { productId: "prod-mirafit-flooring", role: "Flooring" },
      { productId: "prod-atx-fid-bench", role: "Bench", optional: true },
    ],
    ...pub,
  },
  {
    id: "setup-hyrox-home-training",
    slug: "hyrox-home-training",
    title: "HYROX Home Training Setup",
    sportId: "sport-hyrox",
    description:
      "Capability-based home HYROX practice: rower or ski, wall ball path, and race shoes — sled only when space allows.",
    useCaseIds: ["uc-hyrox-home-training", "uc-hyrox-training"],
    budgetRange: { min: 1500, max: 4000, currency: "EUR" },
    items: [
      { productId: "prod-concept2-rowerg", role: "Rower" },
      { productId: "prod-concept2-skierg-pm5-bundle", role: "SkiErg (no wall)", optional: true },
      { productId: "prod-tyr-cxt-2", role: "HYROX Shoes" },
      { productId: "prod-rogue-wall-ball", role: "Wall Ball", optional: true },
    ],
    ...pub,
  },
];

export const wave24Tools: Tool[] = [
  {
    id: "tool-treadmill-finder",
    name: "Treadmill Finder",
    slug: "treadmill-finder",
    description:
      "Match home treadmills to walking, jogging, sprint conditioning, folding needs and budget.",
    type: "finder",
    sportIds: [sportTraining],
    categoryIds: ["cat-treadmills"],
    useCaseIds: ["uc-home-gym", "uc-apartment-gym"],
    goalTags: ["treadmill", "cardio", "home-gym"],
    icon: "Activity",
    available: true,
    ...pub,
  },
];
