/**
 * Prompt 25 — Racket sports catalog (tennis, pickleball, badminton, squash).
 * Sports live in taxonomy — do not export sports from this file.
 * Merged via content index when wired.
 */

import type { Product, Brand } from "@/domain/products/types";
import type { ProductCategory, UseCase } from "@/domain/sports/types";
import type {
  BestGuide,
  BuyingGuide,
  Comparison,
  GearSetup,
} from "@/domain/editorial/types";
import type { Tool } from "@/domain/tools/types";
import type { Offer } from "@/domain/commerce/types";
import type { Recommendation, Evidence } from "@/domain/recommendations/types";
import { publishedMeta, SEED_DATES } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { hasRegisteredProductHero } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();

const sportTennis = "sport-tennis" as const;
const sportPickleball = "sport-pickleball" as const;
const sportBadminton = "sport-badminton" as const;
const sportSquash = "sport-squash" as const;
const sportPadel = "sport-padel" as const;

function offerTriplet(
  productId: string,
  slug: string,
  priceEur: number,
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  return [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
}

export const racketUseCases: UseCase[] = [
  {
    id: "uc-padel-beginner",
    sportId: sportPadel,
    group: "general",
    name: "Padel Beginner",
    slug: "padel-beginner",
    description: "Forgiving, easy-handling padel rackets for new players.",
  },
  {
    id: "uc-padel-control",
    sportId: sportPadel,
    group: "general",
    name: "Padel Control",
    slug: "padel-control",
    description: "Control-first padel frames for placement and defence.",
  },
  {
    id: "uc-padel-power",
    sportId: sportPadel,
    group: "general",
    name: "Padel Power",
    slug: "padel-power",
    description: "Attacking padel rackets biased toward finishing power.",
  },
  {
    id: "uc-padel-balanced",
    sportId: sportPadel,
    group: "general",
    name: "Padel Balanced",
    slug: "padel-balanced",
    description: "Hybrid all-court padel rackets balancing control and power.",
  },
  {
    id: "uc-tennis-beginner",
    sportId: sportTennis,
    group: "general",
    name: "Tennis Beginner",
    slug: "tennis-beginner",
    description: "Forgiving tennis rackets for players building consistency.",
  },
  {
    id: "uc-tennis-control",
    sportId: sportTennis,
    group: "general",
    name: "Tennis Control",
    slug: "tennis-control",
    description: "Control-oriented tennis frames for precision players.",
  },
  {
    id: "uc-tennis-power",
    sportId: sportTennis,
    group: "general",
    name: "Tennis Power",
    slug: "tennis-power",
    description: "Power-biased tennis rackets that add ball speed easily.",
  },
  {
    id: "uc-tennis-spin",
    sportId: sportTennis,
    group: "general",
    name: "Tennis Spin",
    slug: "tennis-spin",
    description: "Open-pattern and aero-shaped frames that favour spin.",
  },
  {
    id: "uc-tennis-balanced",
    sportId: sportTennis,
    group: "general",
    name: "Tennis Balanced",
    slug: "tennis-balanced",
    description: "All-court tennis rackets without a strong power or control bias.",
  },
  {
    id: "uc-pickleball-general",
    sportId: sportPickleball,
    group: "general",
    name: "Pickleball General",
    slug: "pickleball-general",
    description: "Everyday pickleball paddles for recreational and club play.",
  },
  {
    id: "uc-badminton-general",
    sportId: sportBadminton,
    group: "general",
    name: "Badminton General",
    slug: "badminton-general",
    description: "All-round badminton rackets for club and training play.",
  },
  {
    id: "uc-squash-general",
    sportId: sportSquash,
    group: "general",
    name: "Squash General",
    slug: "squash-general",
    description: "Club and competitive squash rackets for general play.",
  },
];

export const racketCategories: ProductCategory[] = [
  {
    id: "cat-tennis-rackets",
    name: "Tennis Rackets",
    slug: "tennis-rackets",
    pathSegment: "rackets",
    icon: "CircleDot",
    description: "Control, power and spin tennis rackets.",
    sportIds: [sportTennis],
    sortOrder: 10,
    seoTitle: "Tennis Rackets: Compare Control, Power & Spin Frames",
    seoDescription:
      "Compare tennis rackets by head size, weight and play style. Browse Kitletics shortlists or use the Tennis Racket Finder.",
    ...pub,
  },
  {
    id: "cat-tennis-shoes",
    name: "Tennis Shoes",
    slug: "tennis-shoes",
    pathSegment: "shoes",
    icon: "Footprints",
    description: "Court shoes built for tennis movement and grip.",
    sportIds: [sportTennis],
    sortOrder: 20,
    ...pub,
  },
  {
    id: "cat-tennis-strings",
    name: "Tennis Strings",
    slug: "tennis-strings",
    pathSegment: "strings",
    icon: "Layers",
    description: "Polyester, multifilament and hybrid tennis strings.",
    sportIds: [sportTennis],
    sortOrder: 30,
    ...pub,
  },
  {
    id: "cat-pickleball-paddles",
    name: "Pickleball Paddles",
    slug: "pickleball-paddles",
    pathSegment: "paddles",
    icon: "CircleDot",
    description: "Control and power pickleball paddles.",
    sportIds: [sportPickleball],
    sortOrder: 40,
    seoTitle: "Pickleball Paddles: Compare Weight, Core & Face",
    seoDescription:
      "Compare pickleball paddles by weight, thickness and materials with structured Kitletics picks.",
    ...pub,
  },
  {
    id: "cat-badminton-rackets",
    name: "Badminton Rackets",
    slug: "badminton-rackets",
    pathSegment: "rackets",
    icon: "CircleDot",
    description: "Head-heavy, even and head-light badminton rackets.",
    sportIds: [sportBadminton],
    sortOrder: 50,
    ...pub,
  },
  {
    id: "cat-squash-rackets",
    name: "Squash Rackets",
    slug: "squash-rackets",
    pathSegment: "rackets",
    icon: "CircleDot",
    description: "Lightweight squash rackets for club and match play.",
    sportIds: [sportSquash],
    sortOrder: 60,
    ...pub,
  },
];

/** New racket brands only — reuse brand-head-padel, brand-babolat-padel, brand-wilson-padel for Head/Babolat/Wilson. */
export const racketBrands: Brand[] = [
  {
    id: "brand-yonex",
    name: "Yonex",
    slug: "yonex",
    country: "Japan",
    description: "Tennis, badminton and squash rackets.",
    homepage: "https://www.yonex.com",
    logo: "/images/brands/yonex-logo.svg",
    ...pub,
  },
  {
    id: "brand-tecnifibre",
    name: "Tecnifibre",
    slug: "tecnifibre",
    country: "France",
    description: "Tennis and squash rackets and strings.",
    homepage: "https://www.tecnifibre.com",
    logo: "/images/brands/tecnifibre-logo.svg",
    ...pub,
  },
  {
    id: "brand-dunlop-racket",
    name: "Dunlop",
    slug: "dunlop",
    country: "UK",
    description: "Tennis and squash rackets and balls.",
    homepage: "https://www.dunlopsports.com",
    ...pub,
  },
  {
    id: "brand-prince",
    name: "Prince",
    slug: "prince",
    country: "USA",
    description: "Tennis rackets and court gear.",
    homepage: "https://www.princetennis.com",
    ...pub,
  },
  {
    id: "brand-selkirk",
    name: "Selkirk",
    slug: "selkirk",
    country: "USA",
    description: "Pickleball paddles and accessories.",
    homepage: "https://www.selkirk.com",
    ...pub,
  },
  {
    id: "brand-joola",
    name: "JOOLA",
    slug: "joola",
    country: "Germany",
    description: "Table tennis and pickleball paddles.",
    homepage: "https://www.joola.com",
    ...pub,
  },
  {
    id: "brand-victor",
    name: "Victor",
    slug: "victor",
    country: "Taiwan",
    description: "Badminton rackets and shuttlecocks.",
    homepage: "https://www.victorsport.com",
    ...pub,
  },
  {
    id: "brand-li-ning",
    name: "Li-Ning",
    slug: "li-ning",
    country: "China",
    description: "Badminton rackets and court apparel.",
    homepage: "https://www.li-ning.com",
    ...pub,
  },
  {
    id: "brand-asics-racket",
    name: "ASICS Court",
    slug: "asics-racket",
    country: "Japan",
    description: "Court shoes for tennis and racket sports (ASICS vertical entity).",
    homepage: "https://www.asics.com",
    logo: "/images/brands/asics-logo.svg",
    logoOnDark: "/images/brands/asics-logo-white.svg",
    ...pub,
  },
];

type ProductDraft = {
  id: string;
  slug: string;
  brandId: string;
  name: string;
  fullName: string;
  shortDescription: string;
  categoryId: string;
  sportId: string;
  useCaseIds: string[];
  specifications: Product["specifications"];
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  experienceLevels: Product["experienceLevels"];
  priceEur: number;
  relatedProductIds?: string[];
  alternativeProductIds?: string[];
  generation?: string;
};

function racketProduct(input: ProductDraft): Product {
  return {
    id: input.id,
    slug: input.slug,
    brandId: input.brandId,
    generation: input.generation,
    name: input.name,
    fullName: input.fullName,
    shortDescription: input.shortDescription,
    lifecycleStatus: "current",
    sportIds: [input.sportId],
    disciplineIds: [],
    categoryId: input.categoryId,
    subcategoryIds: [],
    useCaseIds: input.useCaseIds,
    specifications: input.specifications,
    strengths: input.strengths,
    weaknesses: input.weaknesses,
    recommendationScore: input.recommendationScore,
    valueScore: input.valueScore,
    experienceLevels: input.experienceLevels,
    images: categoryFallbackImage(
      input.categoryId,
      input.id,
      `${input.fullName} — product image unavailable (Kitletics category fallback)`,
    ),
    videos: [],
    offerIds: [
      `offer-${input.slug}-nl`,
      `offer-${input.slug}-de`,
      `offer-${input.slug}-uk`,
    ],
    evidenceIds: ["ev-racket-editorial"],
    relatedProductIds: input.relatedProductIds ?? [],
    alternativeProductIds: input.alternativeProductIds ?? [],
    ...pub,
  };
}

const tennisRacketDrafts: ProductDraft[] = [
  {
    id: "prod-babolat-pure-drive-2025",
    slug: "babolat-pure-drive-2025",
    brandId: "brand-babolat-padel",
    name: "Pure Drive 2025",
    fullName: "Babolat Pure Drive 2025",
    shortDescription:
      "Power-friendly 100 sq in frame with easy depth for intermediate all-court players.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-power", "uc-tennis-beginner"],
    generation: "2025",
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 318,
      balance: "even",
      stringPattern: "16x19",
      powerPositioning: "power",
      playerLevel: "intermediate",
    },
    strengths: ["Accessible power", "Broad sweet spot"],
    weaknesses: ["Less surgical than dense control frames"],
    recommendationScore: 92,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 249,
    relatedProductIds: ["prod-babolat-pure-aero-2023"],
    alternativeProductIds: ["prod-yonex-ezone-98-2024"],
  },
  {
    id: "prod-babolat-pure-aero-2023",
    slug: "babolat-pure-aero-2023",
    brandId: "brand-babolat-padel",
    name: "Pure Aero 2023",
    fullName: "Babolat Pure Aero 2023",
    shortDescription:
      "Aero-shaped spin racket for players who shape the ball with heavy topspin.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-spin", "uc-tennis-power"],
    generation: "2023",
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 318,
      balance: "even",
      stringPattern: "16x19",
      powerPositioning: "power",
      playerLevel: "intermediate",
    },
    strengths: ["Spin potential", "Easy depth on high-bouncing balls"],
    weaknesses: ["Can feel lively for flat hitters"],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 259,
    relatedProductIds: ["prod-babolat-pure-drive-2025"],
    alternativeProductIds: ["prod-yonex-vcore-100-2023"],
  },
  {
    id: "prod-wilson-clash-100-v2",
    slug: "wilson-clash-100-v2",
    brandId: "brand-wilson-padel",
    name: "Clash 100 v2",
    fullName: "Wilson Clash 100 v2",
    shortDescription:
      "Flexible, arm-friendly 100 sq in frame for players prioritising comfort and free swing.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-power"],
    generation: "v2",
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 309,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "balanced",
      playerLevel: "beginner-intermediate",
    },
    strengths: ["Comfort", "Easy swing weight"],
    weaknesses: ["Less plow-through on heavy balls"],
    recommendationScore: 88,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 239,
    relatedProductIds: ["prod-babolat-pure-drive-2025"],
    alternativeProductIds: ["prod-head-speed-mp-2024"],
  },
  {
    id: "prod-wilson-blade-98-v8",
    slug: "wilson-blade-98-v8",
    brandId: "brand-wilson-padel",
    name: "Blade 98 16x19 v8",
    fullName: "Wilson Blade 98 16x19 v8",
    shortDescription:
      "Modern control racket with connected feel for intermediate to advanced baseliners.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control"],
    generation: "v8",
    specifications: {
      headSizeSqIn: 98,
      strungWeightG: 321,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "control",
      playerLevel: "advanced",
    },
    strengths: ["Precision", "Stable on contact"],
    weaknesses: ["Demands cleaner timing than 100 sq in frames"],
    recommendationScore: 91,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 249,
    relatedProductIds: ["prod-yonex-ezone-98-2024"],
    alternativeProductIds: ["prod-tecnifibre-tf40-305"],
  },
  {
    id: "prod-head-speed-mp-2024",
    slug: "head-speed-mp-2024",
    brandId: "brand-head-padel",
    name: "Speed MP 2024",
    fullName: "Head Speed MP 2024",
    shortDescription:
      "Versatile midplus Speed frame for players who want speed through the court.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-power", "uc-tennis-beginner"],
    generation: "2024",
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 315,
      balance: "even",
      stringPattern: "16x19",
      powerPositioning: "balanced",
      playerLevel: "intermediate",
    },
    strengths: ["All-court versatility", "Accessible handling"],
    weaknesses: ["Not the stiffest plow-through option"],
    recommendationScore: 89,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 245,
    relatedProductIds: ["prod-head-radical-mp-2023"],
    alternativeProductIds: ["prod-wilson-clash-100-v2"],
  },
  {
    id: "prod-head-radical-mp-2023",
    slug: "head-radical-mp-2023",
    brandId: "brand-head-padel",
    name: "Radical MP 2023",
    fullName: "Head Radical MP 2023",
    shortDescription:
      "Balanced Radical midplus for players mixing spin, pace and redirection.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control", "uc-tennis-spin"],
    generation: "2023",
    specifications: {
      headSizeSqIn: 98,
      strungWeightG: 315,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "balanced",
      playerLevel: "intermediate",
    },
    strengths: ["Balanced play profile", "Solid redirect stability"],
    weaknesses: ["Less raw free power than Pure Drive"],
    recommendationScore: 87,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 239,
    relatedProductIds: ["prod-head-speed-mp-2024"],
    alternativeProductIds: ["prod-wilson-blade-98-v8"],
  },
  {
    id: "prod-yonex-ezone-98-2024",
    slug: "yonex-ezone-98-2024",
    brandId: "brand-yonex",
    name: "EZONE 98 2024",
    fullName: "Yonex EZONE 98 2024",
    shortDescription:
      "Crisp 98 sq in EZONE with a blend of plow-through and pocketing feel.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control", "uc-tennis-power"],
    generation: "2024",
    specifications: {
      headSizeSqIn: 98,
      strungWeightG: 323,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "balanced",
      playerLevel: "advanced",
    },
    strengths: ["Connected feel", "Stable on stretch"],
    weaknesses: ["Heavier swing than Clash-class frames"],
    recommendationScore: 93,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 269,
    relatedProductIds: ["prod-wilson-blade-98-v8"],
    alternativeProductIds: ["prod-tecnifibre-tf40-305"],
  },
  {
    id: "prod-yonex-vcore-100-2023",
    slug: "yonex-vcore-100-2023",
    brandId: "brand-yonex",
    name: "VCORE 100 2023",
    fullName: "Yonex VCORE 100 2023",
    shortDescription:
      "Spin-oriented 100 sq in VCORE for players who lift and shape the ball.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-spin"],
    generation: "2023",
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 318,
      balance: "even",
      stringPattern: "16x19",
      powerPositioning: "power",
      playerLevel: "intermediate",
    },
    strengths: ["Spin window", "Easy launch angle"],
    weaknesses: ["Flatter hitters may prefer EZONE"],
    recommendationScore: 88,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 259,
    relatedProductIds: ["prod-babolat-pure-aero-2023"],
    alternativeProductIds: ["prod-babolat-pure-drive-2025"],
  },
  {
    id: "prod-tecnifibre-tf40-305",
    slug: "tecnifibre-tf40-305",
    brandId: "brand-tecnifibre",
    name: "TF40 305 16x19",
    fullName: "Tecnifibre TF40 305 16x19",
    shortDescription:
      "Dense control frame for advanced players who want feedback and precision.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control"],
    specifications: {
      headSizeSqIn: 98,
      strungWeightG: 322,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "control",
      playerLevel: "advanced",
    },
    strengths: ["Precision", "Classic control response"],
    weaknesses: ["Less free power for developing players"],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    priceEur: 249,
    relatedProductIds: ["prod-wilson-blade-98-v8"],
    alternativeProductIds: ["prod-dunlop-cx-200"],
  },
  {
    id: "prod-dunlop-cx-200",
    slug: "dunlop-cx-200",
    brandId: "brand-dunlop-racket",
    name: "CX 200",
    fullName: "Dunlop CX 200",
    shortDescription:
      "User-friendly control midplus with a soft response for all-court play.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control", "uc-tennis-beginner"],
    specifications: {
      headSizeSqIn: 95,
      strungWeightG: 315,
      balance: "head-light",
      stringPattern: "16x19",
      powerPositioning: "control",
      playerLevel: "intermediate",
    },
    strengths: ["Feel", "Maneuverability"],
    weaknesses: ["Smaller head than modern 100 sq in options"],
    recommendationScore: 84,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 199,
    relatedProductIds: ["prod-tecnifibre-tf40-305"],
    alternativeProductIds: ["prod-prince-textreme-tour-100p"],
  },
  {
    id: "prod-prince-textreme-tour-100p",
    slug: "prince-textreme-tour-100p",
    brandId: "brand-prince",
    name: "Textreme Tour 100P",
    fullName: "Prince Textreme Tour 100P",
    shortDescription:
      "Modern player's 100 with Textreme reinforcement for stable control.",
    categoryId: "cat-tennis-rackets",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control", "uc-tennis-power"],
    specifications: {
      headSizeSqIn: 100,
      strungWeightG: 320,
      balance: "head-light",
      stringPattern: "16x18",
      powerPositioning: "balanced",
      playerLevel: "intermediate-advanced",
    },
    strengths: ["Stable on contact", "Useful modern control"],
    weaknesses: ["Less mass-market visibility than Blade/EZONE"],
    recommendationScore: 83,
    valueScore: 87,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 219,
    relatedProductIds: ["prod-wilson-blade-98-v8"],
    alternativeProductIds: ["prod-dunlop-cx-200"],
  },
];

const tennisShoeDrafts: ProductDraft[] = [
  {
    id: "prod-asics-gel-resolution-9",
    slug: "asics-gel-resolution-9",
    brandId: "brand-asics-racket",
    name: "Gel-Resolution 9",
    fullName: "ASICS Gel-Resolution 9",
    shortDescription:
      "Stable tennis shoe with strong lateral support for baseliners.",
    categoryId: "cat-tennis-shoes",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-beginner"],
    generation: "9",
    specifications: { courtSurface: "hard", stability: "high", cushioning: "moderate" },
    strengths: ["Lateral stability", "Durable outsole"],
    weaknesses: ["Heavier than speed-oriented shoes"],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 149,
  },
  {
    id: "prod-wilson-rush-pro-4",
    slug: "wilson-rush-pro-4-0",
    brandId: "brand-wilson-padel",
    name: "Rush Pro 4.0",
    fullName: "Wilson Rush Pro 4.0",
    shortDescription:
      "Court shoe balancing cushion and court feel for all-court movement.",
    categoryId: "cat-tennis-shoes",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-beginner"],
    generation: "4.0",
    specifications: { courtSurface: "hard", stability: "moderate", cushioning: "high" },
    strengths: ["Cushion", "Approachable fit"],
    weaknesses: ["Less planted than Resolution-class shoes"],
    recommendationScore: 84,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 129,
  },
];

const tennisStringDrafts: ProductDraft[] = [
  {
    id: "prod-babolat-rpm-blast",
    slug: "babolat-rpm-blast-1-25",
    brandId: "brand-babolat-padel",
    name: "RPM Blast 1.25",
    fullName: "Babolat RPM Blast 1.25",
    shortDescription:
      "Shaped polyester string popular for spin and durability.",
    categoryId: "cat-tennis-strings",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-spin"],
    specifications: {
      gaugeMm: 1.25,
      material: "polyester",
      profile: "shaped",
      spinPotential: "high",
    },
    strengths: ["Spin bite", "Tension maintenance for poly"],
    weaknesses: ["Firm on the arm vs multifilament"],
    recommendationScore: 88,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 14,
  },
  {
    id: "prod-tecnifibre-black-code",
    slug: "tecnifibre-black-code-1-28",
    brandId: "brand-tecnifibre",
    name: "Black Code 1.28",
    fullName: "Tecnifibre Black Code 1.28",
    shortDescription:
      "Control-oriented polyester with a firmer response for precise hitters.",
    categoryId: "cat-tennis-strings",
    sportId: sportTennis,
    useCaseIds: ["uc-tennis-control"],
    specifications: {
      gaugeMm: 1.28,
      material: "polyester",
      profile: "round",
      spinPotential: "moderate",
    },
    strengths: ["Control", "Durable gauge options"],
    weaknesses: ["Less spin-shaped than RPM"],
    recommendationScore: 85,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 13,
  },
];

const pickleballDrafts: ProductDraft[] = [
  {
    id: "prod-selkirk-vanguard-power-air",
    slug: "selkirk-vanguard-power-air",
    brandId: "brand-selkirk",
    name: "Vanguard Power Air Invikta",
    fullName: "Selkirk Vanguard Power Air Invikta",
    shortDescription:
      "Power-biased elongated paddle with a larger sweet spot for aggressive drivers.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "elongated",
      weightOz: 8.0,
      thicknessMm: 16,
      coreMaterial: "polymer honeycomb",
      faceMaterial: "raw carbon",
    },
    strengths: ["Reach", "Drive power"],
    weaknesses: ["Less pop-control than thicker control paddles"],
    recommendationScore: 90,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 229,
  },
  {
    id: "prod-joola-ben-johns-hyperion-cfs",
    slug: "joola-ben-johns-hyperion-cfs-16",
    brandId: "brand-joola",
    name: "Ben Johns Hyperion CFS 16",
    fullName: "JOOLA Ben Johns Hyperion CFS 16",
    shortDescription:
      "Tournament-proven Hyperion with carbon face and 16 mm control thickness.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "elongated",
      weightOz: 7.8,
      thicknessMm: 16,
      coreMaterial: "Reactive honeycomb",
      faceMaterial: "Carbon Friction Surface",
    },
    strengths: ["Spin texture", "All-court balance"],
    weaknesses: ["Premium price"],
    recommendationScore: 93,
    valueScore: 76,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 249,
  },
  {
    id: "prod-joola-perseus-16",
    slug: "joola-perseus-16",
    brandId: "brand-joola",
    name: "Perseus 16",
    fullName: "JOOLA Perseus 16",
    shortDescription:
      "Elongated Perseus shape tuned for reach and controlled power.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "elongated",
      weightOz: 8.0,
      thicknessMm: 16,
      coreMaterial: "polymer",
      faceMaterial: "carbon",
    },
    strengths: ["Reach", "Stable at contact"],
    weaknesses: ["Less forgiving for beginners than widebody shapes"],
    recommendationScore: 89,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 219,
  },
  {
    id: "prod-selkirk-ampsed-epic",
    slug: "selkirk-ampsed-epic",
    brandId: "brand-selkirk",
    name: "Amped Epic",
    fullName: "Selkirk Amped Epic",
    shortDescription:
      "Wider face Amped paddle for forgiveness and soft-game control.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "widebody",
      weightOz: 7.9,
      thicknessMm: 16,
      coreMaterial: "X5 honeycomb",
      faceMaterial: "fiberglass",
    },
    strengths: ["Forgiving sweet spot", "Soft game feel"],
    weaknesses: ["Less raw pop than raw-carbon power paddles"],
    recommendationScore: 86,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 159,
  },
  {
    id: "prod-head-extreme-pro-pickleball",
    slug: "head-extreme-pro-pickleball",
    brandId: "brand-head-padel",
    name: "Extreme Pro Pickleball",
    fullName: "Head Extreme Pro Pickleball",
    shortDescription:
      "Power-leaning Head paddle for players stepping up from recreational gear.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "standard",
      weightOz: 8.1,
      thicknessMm: 14,
      coreMaterial: "polymer",
      faceMaterial: "carbon/fiberglass",
    },
    strengths: ["Accessible power", "Brand support network"],
    weaknesses: ["Thinner core than 16 mm control paddles"],
    recommendationScore: 82,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 139,
  },
  {
    id: "prod-wilson-blade-elite-pickleball",
    slug: "wilson-blade-elite-v2-pickleball",
    brandId: "brand-wilson-padel",
    name: "Blade Elite v2",
    fullName: "Wilson Blade Elite v2 Pickleball",
    shortDescription:
      "Balanced Wilson Blade paddle for all-court recreational and club play.",
    categoryId: "cat-pickleball-paddles",
    sportId: sportPickleball,
    useCaseIds: ["uc-pickleball-general"],
    specifications: {
      shape: "standard",
      weightOz: 7.9,
      thicknessMm: 16,
      coreMaterial: "polymer",
      faceMaterial: "raw carbon",
    },
    strengths: ["Balanced feel", "Spin-friendly face"],
    weaknesses: ["Less elongated reach than Hyperion/Perseus"],
    recommendationScore: 85,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 169,
  },
];

const badmintonDrafts: ProductDraft[] = [
  {
    id: "prod-yonex-astrox-88d-pro",
    slug: "yonex-astrox-88d-pro",
    brandId: "brand-yonex",
    name: "Astrox 88D Pro",
    fullName: "Yonex Astrox 88D Pro",
    shortDescription:
      "Head-heavy doubles attack racket tuned for steep smash angles.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "4U",
      balance: "head-heavy",
      flex: "stiff",
      playerLevel: "advanced",
    },
    strengths: ["Smash power", "Doubles attacking profile"],
    weaknesses: ["Demanding for beginners"],
    recommendationScore: 94,
    valueScore: 80,
    experienceLevels: ["advanced", "elite"],
    priceEur: 219,
  },
  {
    id: "prod-yonex-nanoflare-800-pro",
    slug: "yonex-nanoflare-800-pro",
    brandId: "brand-yonex",
    name: "Nanoflare 800 Pro",
    fullName: "Yonex Nanoflare 800 Pro",
    shortDescription:
      "Head-light speed racket for rapid exchanges and flat drives.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "4U",
      balance: "head-light",
      flex: "stiff",
      playerLevel: "advanced",
    },
    strengths: ["Racket head speed", "Drive defence"],
    weaknesses: ["Less smash plow than Astrox 88D"],
    recommendationScore: 91,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 209,
  },
  {
    id: "prod-yonex-astrox-99-pro",
    slug: "yonex-astrox-99-pro",
    brandId: "brand-yonex",
    name: "Astrox 99 Pro",
    fullName: "Yonex Astrox 99 Pro",
    shortDescription:
      "Singles-oriented head-heavy Astrox for steep clears and smash pressure.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "3U",
      balance: "head-heavy",
      flex: "extra-stiff",
      playerLevel: "elite",
    },
    strengths: ["Singles power", "Steep smash"],
    weaknesses: ["Heavy swing for casual doubles"],
    recommendationScore: 90,
    valueScore: 76,
    experienceLevels: ["advanced", "elite"],
    priceEur: 229,
  },
  {
    id: "prod-yonex-arcsaber-11-pro",
    slug: "yonex-arcsaber-11-pro",
    brandId: "brand-yonex",
    name: "ArcSaber 11 Pro",
    fullName: "Yonex ArcSaber 11 Pro",
    shortDescription:
      "Even-balance control racket for precise placement and counterplay.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "4U",
      balance: "even",
      flex: "stiff",
      playerLevel: "advanced",
    },
    strengths: ["Control", "Shuttle hold"],
    weaknesses: ["Less raw smash than Astrox line"],
    recommendationScore: 88,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 215,
  },
  {
    id: "prod-victor-thruster-k-falcon",
    slug: "victor-thruster-k-falcon",
    brandId: "brand-victor",
    name: "Thruster K Falcon",
    fullName: "Victor Thruster K Falcon",
    shortDescription:
      "Thruster-style attacking racket for players wanting steep power without Yonex branding.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "4U",
      balance: "head-heavy",
      flex: "stiff",
      playerLevel: "intermediate-advanced",
    },
    strengths: ["Attacking geometry", "Value vs flagship Yonex"],
    weaknesses: ["Less EU retail ubiquity than Yonex"],
    recommendationScore: 85,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 169,
  },
  {
    id: "prod-li-ning-aeronaut-9000",
    slug: "li-ning-aeronaut-9000-c",
    brandId: "brand-li-ning",
    name: "Aeronaut 9000 C",
    fullName: "Li-Ning Aeronaut 9000 C",
    shortDescription:
      "Even-to-slightly head-heavy all-rounder for club singles and doubles.",
    categoryId: "cat-badminton-rackets",
    sportId: sportBadminton,
    useCaseIds: ["uc-badminton-general"],
    specifications: {
      weightClass: "3U",
      balance: "even",
      flex: "medium",
      playerLevel: "intermediate",
    },
    strengths: ["All-round versatility", "Accessible flex"],
    weaknesses: ["Less specialised smash than 88D/99"],
    recommendationScore: 83,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 149,
  },
];

const squashDrafts: ProductDraft[] = [
  {
    id: "prod-tecnifibre-carboflex-125",
    slug: "tecnifibre-carboflex-125-x-top",
    brandId: "brand-tecnifibre",
    name: "Carboflex 125 X-Top",
    fullName: "Tecnifibre Carboflex 125 X-Top",
    shortDescription:
      "Lightweight control squash racket favoured by attacking players.",
    categoryId: "cat-squash-rackets",
    sportId: sportSquash,
    useCaseIds: ["uc-squash-general"],
    specifications: {
      weightG: 125,
      headSize: "500 cm²",
      balance: "head-light",
      playerLevel: "advanced",
    },
    strengths: ["Maneuverability", "Precision"],
    weaknesses: ["Less plow than heavier frames"],
    recommendationScore: 93,
    valueScore: 82,
    experienceLevels: ["advanced", "elite"],
    priceEur: 189,
  },
  {
    id: "prod-dunlop-sonic-core-revelation",
    slug: "dunlop-sonic-core-revelation-pro",
    brandId: "brand-dunlop-racket",
    name: "Sonic Core Revelation Pro",
    fullName: "Dunlop Sonic Core Revelation Pro",
    shortDescription:
      "Power-friendly Revelation frame with Sonic Core damping for club attackers.",
    categoryId: "cat-squash-rackets",
    sportId: sportSquash,
    useCaseIds: ["uc-squash-general"],
    specifications: {
      weightG: 130,
      headSize: "500 cm²",
      balance: "even",
      playerLevel: "intermediate",
    },
    strengths: ["Accessible power", "Comfort"],
    weaknesses: ["Less surgical than Carboflex 125"],
    recommendationScore: 87,
    valueScore: 86,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 159,
  },
  {
    id: "prod-head-extreme-120-squash",
    slug: "head-extreme-120-squash",
    brandId: "brand-head-padel",
    name: "Extreme 120 Squash",
    fullName: "Head Extreme 120 Squash",
    shortDescription:
      "Light Extreme squash frame for speed through the ball and volleys.",
    categoryId: "cat-squash-rackets",
    sportId: sportSquash,
    useCaseIds: ["uc-squash-general"],
    specifications: {
      weightG: 120,
      headSize: "500 cm²",
      balance: "head-light",
      playerLevel: "intermediate-advanced",
    },
    strengths: ["Light handling", "Quick preparation"],
    weaknesses: ["Less mass on heavy drives"],
    recommendationScore: 85,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 149,
  },
  {
    id: "prod-wilson-blade-black-squash",
    slug: "wilson-blade-black-squash",
    brandId: "brand-wilson-padel",
    name: "Blade Black Squash",
    fullName: "Wilson Blade Black Squash",
    shortDescription:
      "Blade-family squash racket for players wanting a connected control feel.",
    categoryId: "cat-squash-rackets",
    sportId: sportSquash,
    useCaseIds: ["uc-squash-general"],
    specifications: {
      weightG: 135,
      headSize: "495 cm²",
      balance: "even",
      playerLevel: "intermediate",
    },
    strengths: ["Control feel", "Stable contact"],
    weaknesses: ["Heavier than Carboflex 125"],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 139,
  },
  {
    id: "prod-dunlop-cx-200-squash",
    slug: "dunlop-cx-tour-squash",
    brandId: "brand-dunlop-racket",
    name: "CX Tour Squash",
    fullName: "Dunlop CX Tour Squash",
    shortDescription:
      "All-round CX Tour squash racket for club players building consistency.",
    categoryId: "cat-squash-rackets",
    sportId: sportSquash,
    useCaseIds: ["uc-squash-general"],
    specifications: {
      weightG: 135,
      headSize: "500 cm²",
      balance: "even",
      playerLevel: "beginner-intermediate",
    },
    strengths: ["Forgiving for club play", "Value"],
    weaknesses: ["Not elite-light"],
    recommendationScore: 80,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 119,
  },
];

const allDrafts: ProductDraft[] = [
  ...tennisRacketDrafts,
  ...tennisShoeDrafts,
  ...tennisStringDrafts,
  ...pickleballDrafts,
  ...badmintonDrafts,
  ...squashDrafts,
];

const RACKET_MEDIA_PENDING_DRAFT = new Set([
  "prod-babolat-rpm-blast",
  "prod-tecnifibre-black-code",
  "prod-selkirk-vanguard-power-air",
  "prod-joola-ben-johns-hyperion-cfs",
  "prod-joola-perseus-16",
  "prod-selkirk-ampsed-epic",
  "prod-head-extreme-pro-pickleball",
  "prod-wilson-blade-elite-pickleball",
  "prod-yonex-astrox-88d-pro",
  "prod-yonex-nanoflare-800-pro",
  "prod-yonex-astrox-99-pro",
  "prod-yonex-arcsaber-11-pro",
  "prod-victor-thruster-k-falcon",
  "prod-li-ning-aeronaut-9000-c",
  "prod-li-ning-aeronaut-9000",
  "prod-tecnifibre-carboflex-125-x-top",
  "prod-tecnifibre-carboflex-125",
  "prod-dunlop-sonic-core-revelation-pro",
  "prod-dunlop-sonic-core-revelation",
  "prod-head-extreme-120-squash",
  "prod-wilson-blade-black-squash",
  "prod-dunlop-cx-tour-squash",
  "prod-dunlop-cx-200-squash",
  "prod-luxilon-alu-power",
]);

export const racketProducts: Product[] = allDrafts
  .map(racketProduct)
  .map((p) =>
    RACKET_MEDIA_PENDING_DRAFT.has(p.id) && !hasRegisteredProductHero(p.id)
      ? { ...p, status: "draft" as const }
      : p,
  );

export const racketOffers: Offer[] = allDrafts.flatMap((d) =>
  offerTriplet(d.id, d.slug, d.priceEur),
);

export const racketEvidence: Evidence[] = [
  {
    id: "ev-racket-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — racket catalog",
    summary:
      "Category placement and publicly listed specs/positioning from manufacturer pages and reputable retailers. Not personal lab testing.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];

export const racketRecommendations: Recommendation[] = [
  {
    id: "rec-clash-tennis-beginner",
    productId: "prod-wilson-clash-100-v2",
    sportId: sportTennis,
    useCaseId: "uc-tennis-beginner",
    score: 92,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 94, weight: 0.45 },
      { key: "comfort", label: "Comfort", score: 92, weight: 0.35 },
      { key: "value", label: "Value", score: 86, weight: 0.2 },
    ],
    strengths: ["Arm-friendly flex", "Easy swing weight"],
    compromises: ["Less plow-through for heavy hitters"],
    explanation:
      "Strong starter racket when comfort and free swing matter more than dense control.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-pure-drive-tennis-power",
    productId: "prod-babolat-pure-drive-2025",
    sportId: sportTennis,
    useCaseId: "uc-tennis-power",
    score: 93,
    factors: [
      { key: "power", label: "Power", score: 95, weight: 0.5 },
      { key: "sweetspot", label: "Sweet spot", score: 90, weight: 0.3 },
      { key: "value", label: "Value", score: 84, weight: 0.2 },
    ],
    strengths: ["Accessible depth", "Broad appeal"],
    compromises: ["Less surgical than Blade/TF40"],
    explanation: "Default power-friendly midplus for intermediate all-court players.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-pure-aero-tennis-spin",
    productId: "prod-babolat-pure-aero-2023",
    sportId: sportTennis,
    useCaseId: "uc-tennis-spin",
    score: 91,
    factors: [
      { key: "spin", label: "Spin", score: 96, weight: 0.55 },
      { key: "power", label: "Power", score: 88, weight: 0.25 },
      { key: "control", label: "Control", score: 78, weight: 0.2 },
    ],
    strengths: ["Aero spin window", "High-bounce friendliness"],
    compromises: ["Can feel lively for flat hitters"],
    explanation: "Spin-first choice when shaping the ball is the priority.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-vcore-tennis-spin",
    productId: "prod-yonex-vcore-100-2023",
    sportId: sportTennis,
    useCaseId: "uc-tennis-spin",
    score: 88,
    factors: [
      { key: "spin", label: "Spin", score: 92, weight: 0.5 },
      { key: "feel", label: "Feel", score: 86, weight: 0.3 },
      { key: "value", label: "Value", score: 82, weight: 0.2 },
    ],
    strengths: ["Spin launch", "Yonex pocketing feel"],
    compromises: ["Slightly less mass-market power than Pure Aero"],
    explanation: "Alternative spin frame when players prefer Yonex geometry.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-blade-tennis-control",
    productId: "prod-wilson-blade-98-v8",
    sportId: sportTennis,
    useCaseId: "uc-tennis-control",
    score: 92,
    factors: [
      { key: "control", label: "Control", score: 94, weight: 0.5 },
      { key: "stability", label: "Stability", score: 90, weight: 0.3 },
      { key: "feel", label: "Feel", score: 88, weight: 0.2 },
    ],
    strengths: ["Precision", "Modern control feel"],
    compromises: ["Needs cleaner contact than 100 sq in frames"],
    explanation: "Go-to control midplus for intermediate/advanced baseliners.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-ezone-tennis-control",
    productId: "prod-yonex-ezone-98-2024",
    sportId: sportTennis,
    useCaseId: "uc-tennis-control",
    score: 94,
    factors: [
      { key: "control", label: "Control", score: 92, weight: 0.4 },
      { key: "plow", label: "Plow-through", score: 93, weight: 0.35 },
      { key: "feel", label: "Feel", score: 90, weight: 0.25 },
    ],
    strengths: ["Connected feel", "Stable stretch defence"],
    compromises: ["Heavier swing than Clash"],
    explanation: "Premium control/power blend when players want feedback with depth.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-tf40-tennis-control",
    productId: "prod-tecnifibre-tf40-305",
    sportId: sportTennis,
    useCaseId: "uc-tennis-control",
    score: 87,
    factors: [
      { key: "control", label: "Control", score: 95, weight: 0.55 },
      { key: "feedback", label: "Feedback", score: 92, weight: 0.3 },
      { key: "power", label: "Power", score: 70, weight: 0.15 },
    ],
    strengths: ["Classic control response", "Precision"],
    compromises: ["Less free power"],
    explanation: "Advanced control pick when feedback outweighs easy depth.",
    evidenceIds: ["ev-racket-editorial"],
  },
  {
    id: "rec-speed-mp-tennis-beginner",
    productId: "prod-head-speed-mp-2024",
    sportId: sportTennis,
    useCaseId: "uc-tennis-beginner",
    score: 86,
    factors: [
      { key: "versatility", label: "Versatility", score: 90, weight: 0.45 },
      { key: "handling", label: "Handling", score: 88, weight: 0.35 },
      { key: "value", label: "Value", score: 85, weight: 0.2 },
    ],
    strengths: ["All-court versatility", "Approachable Speed geometry"],
    compromises: ["Not the softest Clash-like flex"],
    explanation: "Balanced beginner-to-intermediate option with room to grow.",
    evidenceIds: ["ev-racket-editorial"],
  },
];

export const racketBestGuides: BestGuide[] = [
  {
    id: "best-tennis-rackets",
    slug: "tennis-rackets",
    title: "Best Tennis Rackets",
    sportId: sportTennis,
    categoryId: "cat-tennis-rackets",
    useCaseIds: [
      "uc-tennis-beginner",
      "uc-tennis-control",
      "uc-tennis-power",
      "uc-tennis-spin",
    ],
    rankingMode: "category-picks",
    intro:
      "A structured shortlist of tennis rackets mapped to power, control and spin — not a generic top-10 list.",
    selectionMethodology:
      "Products are scored via explainable recommendation factors (power, control, spin, forgiveness, value) against play profiles. Specs load from Product entities.",
    selectionCriteria: [
      {
        key: "powerPositioning",
        label: "Power vs control",
        description: "How freely the frame adds ball speed versus precision.",
      },
      {
        key: "headSize",
        label: "Head size",
        description: "Forgiveness and launch window.",
      },
      {
        key: "value",
        label: "Value",
        description: "Performance relative to street price.",
      },
    ],
    recommendations: [
      {
        productId: "prod-yonex-ezone-100-2025",
        rank: 1,
        awardType: "best-overall",
        rationale:
          "Forgiving 100 sq in power-comfort blend that suits a wide intermediate range without forcing a specialist identity.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
      {
        productId: "prod-wilson-blade-98-v9",
        rank: 2,
        badge: "Best Control",
        rationale: "Current Blade 98 16x19 for connected, precision-first baseliners.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
      {
        productId: "prod-babolat-pure-drive-gen11",
        rank: 3,
        badge: "Best Power",
        rationale: "Pure Drive Gen11 for accessible depth and modern aggressive pace.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
      {
        productId: "prod-babolat-pure-aero-2026",
        rank: 4,
        badge: "Best Spin",
        rationale: "Current Pure Aero for players who shape the ball with heavy topspin.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
      {
        productId: "prod-wilson-clash-100-v3",
        rank: 5,
        badge: "Best Beginner / Comfort",
        rationale: "Clash 100 v3 prioritises arm-friendly forgiveness for newer players.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
      {
        productId: "prod-head-speed-mp-2026",
        rank: 6,
        awardType: "best-value",
        rationale: "Speed MP 2026 as a versatile all-court intermediate frame.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
    ],
    comparisonProductIds: [
      "prod-yonex-ezone-100-2025",
      "prod-wilson-blade-98-v9",
      "prod-babolat-pure-drive-gen11",
      "prod-babolat-pure-aero-2026",
      "prod-wilson-clash-100-v3",
      "prod-head-speed-mp-2026",
    ],
    buyingAdvice:
      "Match head size and power positioning to your level first, then refine by string and swing weight.",
    faqIds: [],
    relatedToolSlugs: ["tennis-racket-finder"],
    ...pub,
  },
];

export const racketBuyingGuides: BuyingGuide[] = [
  {
    id: "guide-choose-tennis-racket",
    slug: "how-to-choose-a-tennis-racket",
    title: "How to Choose a Tennis Racket",
    sportId: sportTennis,
    categoryId: "cat-tennis-rackets",
    relatedProductIds: [
      "prod-wilson-clash-100-v3",
      "prod-babolat-pure-drive-gen11",
      "prod-wilson-blade-98-v9",
      "prod-babolat-pure-aero-2026",
      "prod-yonex-ezone-100-2025",
    ],
    relatedUseCaseIds: [
      "uc-tennis-beginner",
      "uc-tennis-control",
      "uc-tennis-power",
      "uc-tennis-spin",
    ],
    sections: [
      {
        id: "s1",
        heading: "Start with head size and weight",
        body: "Larger heads (100 sq in) forgive off-centre hits; denser 98s reward cleaner timing. Strung weight around 300–320 g suits most club players — go lighter for easier handling, heavier for plow-through when you can accelerate the frame.",
      },
      {
        id: "s2",
        heading: "Power vs control vs spin",
        body: "Power frames (Pure Drive Gen11) add depth easily. Control frames (Blade v9, TF40) prioritise placement. Spin frames (Pure Aero 2026, VCORE) open the launch window for topspin. Match the bias to how you already play — pattern and stiffness are contributors, not absolute rules.",
      },
      {
        id: "s3",
        heading: "Balance, swingweight, and beam",
        body: "Head-light balance aids maneuverability; even or head-heavy setups can add plow. Swingweight should only be compared when measured/verified — do not invent it from weight and balance. Beam width affects power potential and torsional feel.",
      },
      {
        id: "s4",
        heading: "Grip size",
        body: "Measure from the middle crease of your palm to the tip of your ring finger, or use retailer size charts (L1–L5 / 4 1/8–4 5/8). Too small encourages overgripping; too large reduces wrist snap. This is sizing guidance, not medical advice.",
      },
      {
        id: "s5",
        heading: "Strings finish the setup",
        body: "A stiff polyester like Luxilon ALU Power or RPM Blast increases spin potential and durability; softer multifilaments spare the arm. Hybrid setups often balance both. Tension ranges on the frame are manufacturer guidance — restring before the string dies.",
      },
      {
        id: "s6",
        heading: "Use the Finder next",
        body: "When you know level, priorities, and budget — especially if you have a current racket and want more spin or easier handling — run the Tennis Racket Finder, then compare top matches and check regional Offers.",
      },
    ],
    faqIds: [],
    ...pub,
  },
];

export const racketComparisons: Comparison[] = [
  {
    id: "cmp-pure-drive-vs-clash",
    slug: "babolat-pure-drive-2025-vs-wilson-clash-100-v2",
    title: "Babolat Pure Drive 2025 vs Wilson Clash 100 v2",
    productIds: ["prod-babolat-pure-drive-2025", "prod-wilson-clash-100-v2"],
    categoryId: "cat-tennis-rackets",
    comparisonType: "hybrid",
    summary: "Accessible power versus flexible comfort for intermediate players.",
    criteria: [
      { key: "power", label: "Power", winnerProductId: "prod-babolat-pure-drive-2025" },
      { key: "comfort", label: "Comfort", winnerProductId: "prod-wilson-clash-100-v2" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-tennis-power",
        productId: "prod-babolat-pure-drive-2025",
        rationale: "Easier depth and ball speed.",
      },
      {
        useCaseId: "uc-tennis-beginner",
        productId: "prod-wilson-clash-100-v2",
        rationale: "Softer flex and freer swing.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-babolat-pure-drive-2025",
        reason: "You want free power and a lively midplus.",
      },
      {
        productId: "prod-wilson-clash-100-v2",
        reason: "You prioritise comfort and arm-friendly flex.",
      },
    ],
    verdict: "Choose Pure Drive for power; Clash for comfort-first play.",
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-blade-vs-ezone",
    slug: "wilson-blade-98-v8-vs-yonex-ezone-98-2024",
    title: "Wilson Blade 98 v8 vs Yonex EZONE 98 2024",
    productIds: ["prod-wilson-blade-98-v8", "prod-yonex-ezone-98-2024"],
    categoryId: "cat-tennis-rackets",
    comparisonType: "editorial",
    summary: "Two premium 98 sq in control frames with different plow-through characters.",
    criteria: [
      { key: "control", label: "Control", winnerProductId: "prod-wilson-blade-98-v8" },
      { key: "plow", label: "Plow-through", winnerProductId: "prod-yonex-ezone-98-2024" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-tennis-control",
        productId: "prod-wilson-blade-98-v8",
        rationale: "Tighter, more connected control feel.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-wilson-blade-98-v8",
        reason: "You want precise, connected control.",
      },
      {
        productId: "prod-yonex-ezone-98-2024",
        reason: "You want control with more plow-through depth.",
      },
    ],
    verdict: "Blade for pure control feel; EZONE when you want control plus heavier ball.",
    faqIds: [],
    ...pub,
  },
];

export const racketSetups: GearSetup[] = [
  {
    id: "setup-tennis-starter",
    slug: "tennis-starter-kit",
    title: "Tennis Starter Kit",
    sportId: sportTennis,
    description:
      "A practical starter kit: forgiving racket, stable shoes and a spin-friendly polyester string.",
    useCaseIds: ["uc-tennis-beginner"],
    budgetRange: { min: 250, max: 450, currency: "EUR" },
    items: [
      { productId: "prod-wilson-clash-100-v2", role: "Tennis Racket" },
      { productId: "prod-asics-gel-resolution-9", role: "Tennis Shoes" },
      { productId: "prod-babolat-rpm-blast", role: "Tennis String" },
    ],
    ...pub,
  },
];

export const racketTools: Tool[] = [
  {
    id: "tool-tennis-racket-finder",
    name: "Tennis Racket Finder",
    slug: "tennis-racket-finder",
    description:
      "Answer questions about level, power vs control priorities and budget to get structured racket matches.",
    type: "finder",
    sportIds: [sportTennis],
    categoryIds: ["cat-tennis-rackets"],
    useCaseIds: [
      "uc-tennis-beginner",
      "uc-tennis-control",
      "uc-tennis-power",
      "uc-tennis-spin",
    ],
    goalTags: ["tennis", "racket", "recommendation"],
    icon: "CircleDot",
    available: true,
    ...pub,
  },
  {
    id: "tool-pickleball-paddle-finder",
    name: "Pickleball Paddle Finder",
    slug: "pickleball-paddle-finder",
    description: "Match pickleball paddles to play style and budget.",
    type: "finder",
    sportIds: [sportPickleball],
    categoryIds: ["cat-pickleball-paddles"],
    useCaseIds: ["uc-pickleball-general"],
    goalTags: ["pickleball", "paddle", "recommendation"],
    icon: "CircleDot",
    available: false,
    ...pub,
    status: "archived",
  },
  {
    id: "tool-badminton-racket-finder",
    name: "Badminton Racket Finder",
    slug: "badminton-racket-finder",
    description: "Match badminton rackets by weight class, balance and flex.",
    type: "finder",
    sportIds: [sportBadminton],
    categoryIds: ["cat-badminton-rackets"],
    useCaseIds: ["uc-badminton-general"],
    goalTags: ["badminton", "racket", "recommendation"],
    icon: "CircleDot",
    available: false,
    ...pub,
    status: "archived",
  },
  {
    id: "tool-squash-racket-finder",
    name: "Squash Racket Finder",
    slug: "squash-racket-finder",
    description: "Match squash rackets by weight, balance and play level.",
    type: "finder",
    sportIds: [sportSquash],
    categoryIds: ["cat-squash-rackets"],
    useCaseIds: ["uc-squash-general"],
    goalTags: ["squash", "racket", "recommendation"],
    icon: "CircleDot",
    available: false,
    ...pub,
    status: "archived",
  },
];
