/**
 * Wave 28 — Expand tennis court-shoe catalog from ~7 toward a full multi-brand
 * set (~30). Specs stay high-level; null numeric fields when unverified.
 */

import type { Product, Brand } from "@/domain/products/types";
import type { Offer } from "@/domain/commerce/types";
import type { Evidence } from "@/domain/recommendations/types";
import { publishedMeta, SEED_DATES } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { hasRegisteredProductHero } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();
const sportTennis = "sport-tennis" as const;
const sportPadel = "sport-padel" as const;

function offerTriplet(
  productId: string,
  slug: string,
  priceEur: number,
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  return [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
}

export const wave28TennisShoeBrands: Brand[] = [
  {
    id: "brand-k-swiss",
    name: "K-Swiss",
    slug: "k-swiss",
    country: "USA",
    description: "Court footwear brand known for Hypercourt and Express lines.",
    homepage: "https://www.kswiss.com",
    ...pub,
  },
];

type Draft = {
  id: string;
  slug: string;
  brandId: string;
  name: string;
  fullName: string;
  shortDescription: string;
  generation?: string;
  genderFit?: "men" | "women" | "unisex";
  courtSurface: string;
  stability: string;
  cushioning: string;
  weightClass: string;
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  experienceLevels: Product["experienceLevels"];
  priceEur: number;
  useCaseIds?: string[];
};

function toProduct(d: Draft): Product {
  return {
    id: d.id,
    slug: d.slug,
    brandId: d.brandId,
    generation: d.generation,
    name: d.name,
    fullName: d.fullName,
    shortDescription: d.shortDescription,
    lifecycleStatus: "current",
    sportIds: [sportTennis, sportPadel],
    disciplineIds: [],
    categoryId: "cat-tennis-shoes",
    subcategoryIds: [],
    useCaseIds: d.useCaseIds ?? ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      courtSurface: d.courtSurface,
      stability: d.stability,
      cushioning: d.cushioning,
      weightClass: d.weightClass,
      genderFit: d.genderFit ?? "unisex",
    },
    strengths: d.strengths,
    weaknesses: d.weaknesses,
    recommendationScore: d.recommendationScore,
    valueScore: d.valueScore,
    experienceLevels: d.experienceLevels,
    images: categoryFallbackImage(
      "cat-tennis-shoes",
      d.id,
      `${d.fullName} — product image unavailable`,
    ),
    videos: [],
    offerIds: [
      `offer-${d.slug}-nl`,
      `offer-${d.slug}-de`,
      `offer-${d.slug}-uk`,
    ],
    evidenceIds: ["ev-wave28-tennis-shoes-editorial"],
    relatedProductIds: ["prod-asics-gel-resolution-9", "prod-adidas-barricade-13"],
    alternativeProductIds: [
      "prod-asics-gel-challenger-15",
      "prod-wilson-rush-pro-5",
    ],
    ...pub,
  };
}

const DRAFTS: Draft[] = [
  {
    id: "prod-asics-solution-speed-ff-3",
    slug: "asics-solution-speed-ff-3",
    brandId: "brand-asics-racket",
    name: "Solution Speed FF 3",
    fullName: "ASICS Solution Speed FF 3",
    shortDescription:
      "Lightweight ASICS court shoe for players who prioritise speed and court feel over max stability.",
    generation: "3",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "light",
    strengths: ["Quick court feel", "Light upper", "Speed-biased geometry"],
    weaknesses: ["Less planted than Resolution / Barricade"],
    recommendationScore: 87,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 145,
  },
  {
    id: "prod-asics-gel-dedicate-8",
    slug: "asics-gel-dedicate-8",
    brandId: "brand-asics-racket",
    name: "Gel-Dedicate 8",
    fullName: "ASICS Gel-Dedicate 8",
    shortDescription:
      "Accessible ASICS hard-court shoe for club players who want GEL cushioning without Resolution pricing.",
    generation: "8",
    courtSurface: "hard",
    stability: "high",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Strong value", "Stable base", "Durable outsole"],
    weaknesses: ["Less premium foam than Resolution"],
    recommendationScore: 84,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 89,
    useCaseIds: ["uc-tennis-beginner"],
  },
  {
    id: "prod-asics-gel-resolution-9-clay",
    slug: "asics-gel-resolution-9-clay",
    brandId: "brand-asics-racket",
    name: "Gel-Resolution 9 Clay",
    fullName: "ASICS Gel-Resolution 9 Clay",
    shortDescription:
      "Clay-specific Resolution outsole for sliding on terre battue while keeping Resolution lockdown.",
    generation: "9",
    courtSurface: "clay",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Clay outsole", "Resolution stability", "Match durability"],
    weaknesses: ["Specialised for clay", "Heavier than speed shoes"],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 165,
    useCaseIds: ["uc-tennis-control", "uc-tennis-balanced"],
  },
  {
    id: "prod-nike-zoom-gp-turbo-2",
    slug: "nike-zoom-gp-turbo-hc-2",
    brandId: "brand-nike",
    name: "Zoom GP Turbo HC 2",
    fullName: "NikeCourt Air Zoom GP Turbo HC 2",
    shortDescription:
      "Responsive Nike hard-court shoe with Zoom Air for aggressive baseliners who want snap and support.",
    generation: "2",
    courtSurface: "hard",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Zoom response", "Hard-court durability", "Secure lockdown"],
    weaknesses: ["Premium price", "Less light than Vapor Pro"],
    recommendationScore: 87,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 160,
  },
  {
    id: "prod-nike-court-lite-4",
    slug: "nike-court-lite-4",
    brandId: "brand-nike",
    name: "Court Lite 4",
    fullName: "NikeCourt Lite 4",
    shortDescription:
      "Entry Nike hard-court shoe for beginners and recreational players needing durable value.",
    generation: "4",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Strong value", "Durable outsole", "Beginner-friendly"],
    weaknesses: ["Less premium cushioning", "Heavier than race-court shoes"],
    recommendationScore: 80,
    valueScore: 93,
    experienceLevels: ["beginner"],
    priceEur: 75,
    useCaseIds: ["uc-tennis-beginner"],
  },
  {
    id: "prod-nike-vapor-cage-4",
    slug: "nike-court-air-zoom-vapor-cage-4",
    brandId: "brand-nike",
    name: "Vapor Cage 4",
    fullName: "NikeCourt Air Zoom Vapor Cage 4 Rafa",
    shortDescription:
      "Durable Nike hard-court shoe with reinforced cage for heavy baseliners who wear through uppers.",
    generation: "4",
    courtSurface: "hard",
    stability: "high",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Upper durability", "Hard-court grip", "Supportive fit"],
    weaknesses: ["Heavier than Vapor Pro", "Stiffer break-in"],
    recommendationScore: 86,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 150,
  },
  {
    id: "prod-adidas-solematch-control-2",
    slug: "adidas-solematch-control-2",
    brandId: "brand-adidas",
    name: "Solematch Control 2",
    fullName: "Adidas Solematch Control 2",
    shortDescription:
      "Stable Adidas hard-court shoe with Bounce cushioning for controlled baseline movement.",
    generation: "2",
    courtSurface: "hard",
    stability: "high",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Lateral control", "Durable build", "Club-to-match use"],
    weaknesses: ["Less soft than Boost models"],
    recommendationScore: 85,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 120,
  },
  {
    id: "prod-adidas-courtjam-control-3",
    slug: "adidas-courtjam-control-3",
    brandId: "brand-adidas",
    name: "CourtJam Control 3",
    fullName: "Adidas CourtJam Control 3",
    shortDescription:
      "Everyday Adidas court shoe for recreational hard-court play with Adiwear durability.",
    generation: "3",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Club value", "Durable outsole", "Approachable fit"],
    weaknesses: ["Less match-day stability than Barricade"],
    recommendationScore: 81,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 95,
    useCaseIds: ["uc-tennis-beginner"],
  },
  {
    id: "prod-adidas-gamecourt-2",
    slug: "adidas-gamecourt-2",
    brandId: "brand-adidas",
    name: "Gamecourt 2",
    fullName: "Adidas Gamecourt 2",
    shortDescription:
      "Budget Adidas hard-court shoe for casual players and first racket-bag footwear.",
    generation: "2",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "low",
    weightClass: "moderate",
    strengths: ["Lowest price tier", "Simple durable build"],
    weaknesses: ["Basic cushioning", "Less support for aggressive play"],
    recommendationScore: 76,
    valueScore: 94,
    experienceLevels: ["beginner"],
    priceEur: 65,
    useCaseIds: ["uc-tennis-beginner"],
  },
  {
    id: "prod-wilson-kaos-rapide-30",
    slug: "wilson-kaos-rapide-3-0",
    brandId: "brand-wilson-padel",
    name: "Kaos Rapide 3.0",
    fullName: "Wilson Kaos Rapide 3.0",
    shortDescription:
      "Lightweight Wilson court shoe for quick first steps and all-court movement.",
    generation: "3.0",
    courtSurface: "hard-clay",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "light",
    strengths: ["Light weight", "Quick feel", "All-court use"],
    weaknesses: ["Less max stability than Rush Pro Ace"],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 130,
  },
  {
    id: "prod-wilson-rush-pro-ace",
    slug: "wilson-rush-pro-ace",
    brandId: "brand-wilson-padel",
    name: "Rush Pro Ace",
    fullName: "Wilson Rush Pro Ace",
    shortDescription:
      "Support-biased Wilson hard-court shoe for players who want more lockdown than standard Rush Pro.",
    courtSurface: "hard",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Supportive lockdown", "Cushioned ride", "Hard-court durability"],
    weaknesses: ["Heavier than Kaos Rapide"],
    recommendationScore: 86,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 145,
  },
  {
    id: "prod-babolat-propulse-fury-3",
    slug: "babolat-propulse-fury-3",
    brandId: "brand-babolat-padel",
    name: "Propulse Fury 3",
    fullName: "Babolat Propulse Fury 3",
    shortDescription:
      "Durable Babolat hard-court shoe for aggressive baseliners needing Michelin outsole grip.",
    generation: "3",
    courtSurface: "hard",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Michelin durability", "Stable base", "Match-ready cushion"],
    weaknesses: ["Heavier than Jet Mach", "Premium vs club shoes"],
    recommendationScore: 87,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 155,
  },
  {
    id: "prod-babolat-jet-mach-3",
    slug: "babolat-jet-mach-3",
    brandId: "brand-babolat-padel",
    name: "Jet Mach 3",
    fullName: "Babolat Jet Mach 3",
    shortDescription:
      "Light Babolat court shoe for players who want speed and lower weight than Propulse.",
    generation: "3",
    courtSurface: "hard-clay",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "light",
    strengths: ["Light weight", "Quick movement", "Flexible fit"],
    weaknesses: ["Less planted than Propulse Fury"],
    recommendationScore: 85,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 140,
  },
  {
    id: "prod-head-revolt-pro-45",
    slug: "head-revolt-pro-4-5",
    brandId: "brand-head-padel",
    name: "Revolt Pro 4.5",
    fullName: "HEAD Revolt Pro 4.5",
    shortDescription:
      "Supportive HEAD hard-court shoe with durable construction for frequent club and match play.",
    generation: "4.5",
    courtSurface: "hard",
    stability: "high",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Durable build", "Stable platform", "All-week club use"],
    weaknesses: ["Less light than Sprint Pro"],
    recommendationScore: 85,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 135,
  },
  {
    id: "prod-head-sprint-pro-35",
    slug: "head-sprint-pro-3-5",
    brandId: "brand-head-padel",
    name: "Sprint Pro 3.5",
    fullName: "HEAD Sprint Pro 3.5",
    shortDescription:
      "Lighter HEAD court shoe for players who want speed with enough structure for hard courts.",
    generation: "3.5",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "light",
    strengths: ["Lighter than Revolt Pro", "Quick first step", "Breathable upper"],
    weaknesses: ["Less max lateral support"],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 125,
  },
  {
    id: "prod-nb-lav-v2",
    slug: "new-balance-fresh-foam-x-lav-v2",
    brandId: "brand-new-balance",
    name: "Fresh Foam X Lav v2",
    fullName: "New Balance Fresh Foam X Lav v2",
    shortDescription:
      "Cushioned New Balance hard-court shoe with width options for players who need room and Fresh Foam comfort.",
    generation: "v2",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "high",
    weightClass: "moderate",
    genderFit: "unisex",
    strengths: ["Width options", "Soft cushioning", "Comfort-first court ride"],
    weaknesses: ["Less race-light than Vapor-class shoes"],
    recommendationScore: 86,
    valueScore: 87,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 140,
  },
  {
    id: "prod-nb-996-v5",
    slug: "new-balance-996-v5",
    brandId: "brand-new-balance",
    name: "996 v5",
    fullName: "New Balance 996 v5",
    shortDescription:
      "Classic New Balance tennis shoe updated for modern hard-court grip and everyday club durability.",
    generation: "v5",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Width ladder", "Durable classic fit", "Club workhorse"],
    weaknesses: ["Less modern energy return"],
    recommendationScore: 83,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 120,
  },
  {
    id: "prod-yonex-eclipsion-5",
    slug: "yonex-power-cushion-eclipsion-5",
    brandId: "brand-yonex",
    name: "Eclipsion 5",
    fullName: "Yonex Power Cushion Eclipsion 5",
    shortDescription:
      "Supportive Yonex hard-court shoe with Power Cushion for players who want planted lateral stability.",
    generation: "5",
    courtSurface: "hard",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Power Cushion comfort", "Lateral stability", "Durable outsole"],
    weaknesses: ["Heavier than Sonicage"],
    recommendationScore: 86,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 155,
  },
  {
    id: "prod-yonex-sonicage-3",
    slug: "yonex-power-cushion-sonicage-3",
    brandId: "brand-yonex",
    name: "Sonicage 3",
    fullName: "Yonex Power Cushion Sonicage 3",
    shortDescription:
      "Lighter Yonex court shoe for all-court speed with Power Cushion underfoot.",
    generation: "3",
    courtSurface: "hard-clay",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "light",
    strengths: ["Light weight", "Power Cushion", "All-court feel"],
    weaknesses: ["Less max support than Eclipsion"],
    recommendationScore: 84,
    valueScore: 85,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 130,
  },
  {
    id: "prod-kswiss-hypercourt-express-2",
    slug: "k-swiss-hypercourt-express-2",
    brandId: "brand-k-swiss",
    name: "Hypercourt Express 2",
    fullName: "K-Swiss Hypercourt Express 2",
    shortDescription:
      "Durable K-Swiss hard-court shoe known for lasting club and teaching-pro mileage.",
    generation: "2",
    courtSurface: "hard",
    stability: "high",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Outsole durability", "Stable platform", "Teaching-pro favourite"],
    weaknesses: ["Heavier than speed shoes", "Less plush foam"],
    recommendationScore: 85,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 115,
  },
  {
    id: "prod-kswiss-ultrashot-3",
    slug: "k-swiss-ultrashot-3",
    brandId: "brand-k-swiss",
    name: "Ultrashot 3",
    fullName: "K-Swiss Ultrashot 3",
    shortDescription:
      "Cushioned K-Swiss performance court shoe for players wanting more underfoot comfort than Express.",
    generation: "3",
    courtSurface: "hard",
    stability: "high",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Cushioned ride", "Supportive fit", "Hard-court durability"],
    weaknesses: ["Premium vs Express", "Not the lightest shoe"],
    recommendationScore: 86,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 145,
  },
  {
    id: "prod-mizuno-wave-exceed-tour-5",
    slug: "mizuno-wave-exceed-tour-5",
    brandId: "brand-mizuno",
    name: "Wave Exceed Tour 5",
    fullName: "Mizuno Wave Exceed Tour 5",
    shortDescription:
      "Mizuno Wave court shoe balancing cushion and court feel for competitive hard-court play.",
    generation: "5",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "high",
    weightClass: "moderate",
    strengths: ["Wave cushioning", "Court feel", "Secure fit"],
    weaknesses: ["Narrower EU availability", "Fit can run snug"],
    recommendationScore: 84,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 140,
  },
  {
    id: "prod-prince-t22",
    slug: "prince-t22",
    brandId: "brand-prince",
    name: "T22",
    fullName: "Prince T22",
    shortDescription:
      "Value Prince hard-court shoe for recreational players needing durable basic court footwear.",
    courtSurface: "hard",
    stability: "moderate",
    cushioning: "moderate",
    weightClass: "moderate",
    strengths: ["Accessible price", "Simple durable build"],
    weaknesses: ["Basic cushioning", "Less refined fit than premium brands"],
    recommendationScore: 78,
    valueScore: 91,
    experienceLevels: ["beginner"],
    priceEur: 70,
    useCaseIds: ["uc-tennis-beginner"],
  },
];

/** Published only when authentic hero media is registered for the product. */
export const wave28TennisShoeProducts: Product[] = DRAFTS.map(toProduct).map((p) =>
  hasRegisteredProductHero(p.id) ? p : { ...p, status: "draft" as const },
);
export const wave28TennisShoeOffers: Offer[] = DRAFTS.flatMap((d) =>
  offerTriplet(d.id, d.slug, d.priceEur),
);

export const wave28TennisShoeEvidence: Evidence[] = [
  {
    id: "ev-wave28-tennis-shoes-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — tennis court shoes catalog",
    summary:
      "Category placement and strengths/weaknesses from manufacturer lines and retailer listings. Not personal wear testing.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];
