/**
 * Prompt 26 — Tennis catalog population (current 2026-relevant frames, strings, shoes).
 * Does not mutate racket/seed.ts — new products plus overlay patches for merge.
 * Specs from manufacturer pages and reputable retailers; editorial-research only.
 */

import type { Product, Brand, ProductFamily } from "@/domain/products/types";
import type { Offer } from "@/domain/commerce/types";
import type {
  Recommendation,
  Evidence,
  AlternativeRelationship,
} from "@/domain/recommendations/types";
import type { Comparison } from "@/domain/editorial/types";
import type { ProductRelationship } from "@/domain/relationships/types";
import { publishedMeta, SEED_DATES } from "@/content/config";
import { categoryFallbackImage } from "@/content/running/media";
import { hasRegisteredProductHero } from "@/content/running/products/media-publish-gate";

const pub = publishedMeta();
const sportTennis = "sport-tennis" as const;

const RACKET_PLACEHOLDERS = [
  "/images/padel/products/racket-1.svg",
  "/images/padel/products/racket-2.svg",
  "/images/padel/products/racket-3.svg",
  "/images/padel/products/racket-4.svg",
  "/images/padel/products/racket-5.svg",
] as const;

function tennisRacketImg(productId: string, index: number, fullName: string) {
  return [
    {
      id: `img-${productId}`,
      src: RACKET_PLACEHOLDERS[index % RACKET_PLACEHOLDERS.length]!,
      alt: `${fullName} — catalog placeholder (tennis product photograph unavailable)`,
      type: "image" as const,
      source: "Kitletics padel placeholder reused for tennis",
      usageType: "hero" as const,
      licence: "kitletics-owned" as const,
      attribution:
        "Kitletics intentional placeholder — not a manufacturer product photograph",
    },
  ];
}

function offerTriplet(
  productId: string,
  slug: string,
  priceEur: number,
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  return [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
}

const relMeta = {
  status: "approved" as const,
  createdAt: SEED_DATES.created,
  updatedAt: SEED_DATES.updated,
  lastVerifiedAt: SEED_DATES.verified,
};

/** Brands not already in racket/seed — Luxilon for ALU Power; Solinco reserved for string SKUs. */
export const wave26TennisBrands: Brand[] = [
  {
    id: "brand-luxilon",
    name: "Luxilon",
    slug: "luxilon",
    country: "Belgium",
    description: "Polyester tennis strings including ALU Power.",
    homepage: "https://www.luxilon.com",
    ...pub,
  },
  {
    id: "brand-solinco",
    name: "Solinco",
    slug: "solinco",
    country: "USA",
    description: "Tennis strings and court accessories.",
    homepage: "https://www.solinco.com",
    ...pub,
  },
];

type Draft = {
  id: string;
  slug: string;
  brandId: string;
  familyId?: string;
  generation?: string;
  name: string;
  fullName: string;
  shortDescription: string;
  categoryId: string;
  sportIds: string[];
  useCaseIds: string[];
  specifications: Product["specifications"];
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  experienceLevels: Product["experienceLevels"];
  priceEur: number;
  imgIndex?: number;
  relatedProductIds?: string[];
  alternativeProductIds?: string[];
  useCategoryFallback?: boolean;
};

const racketDrafts: Draft[] = [
  {
    id: "prod-wilson-blade-98-v9",
    slug: "wilson-blade-98-v9",
    brandId: "brand-wilson-padel",
    familyId: "fam-wilson-blade",
    generation: "v9",
    name: "Blade 98 16x19 v9",
    fullName: "Wilson Blade 98 16x19 v9",
    shortDescription:
      "Current Blade control midplus (16x19) for intermediate to advanced baseliners seeking connected feel.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-control"],
    specifications: {
      headSizeSqIn: 98,
      unstrungWeightG: 305,
      strungWeightG: 321,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 20.6,
      powerPositioning: "control",
      controlPositioning: "high",
      spinPositioning: "moderate",
      stiffnessRa: 62,
      playerLevel: "advanced",
    },
    strengths: ["Precision", "Stable connected feel", "Modern control geometry"],
    weaknesses: ["Demands cleaner timing than 100 sq in frames"],
    recommendationScore: 94,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 259,
    imgIndex: 0,
    relatedProductIds: ["prod-wilson-blade-98-v8", "prod-wilson-blade-100-v9"],
    alternativeProductIds: [
      "prod-yonex-ezone-98-2024",
      "prod-tecnifibre-tfight-300s-2025",
    ],
  },
  {
    id: "prod-wilson-clash-100-v3",
    slug: "wilson-clash-100-v3",
    brandId: "brand-wilson-padel",
    familyId: "fam-wilson-clash",
    generation: "v3",
    name: "Clash 100 v3",
    fullName: "Wilson Clash 100 v3",
    shortDescription:
      "Comfort-first 100 sq in frame with flexible FreeFlex response for forgiveness and free swing.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 295,
      strungWeightG: 309,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 24.5,
      powerPositioning: "balanced",
      controlPositioning: "moderate",
      spinPositioning: "moderate",
      stiffnessRa: 55,
      playerLevel: "beginner-intermediate",
    },
    strengths: ["Arm-friendly flex", "Forgiving sweet spot", "Easy handling"],
    weaknesses: ["Less plow-through on heavy balls than denser frames"],
    recommendationScore: 91,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 249,
    imgIndex: 1,
    relatedProductIds: ["prod-wilson-clash-100-v2"],
    alternativeProductIds: [
      "prod-yonex-ezone-100-2025",
      "prod-head-speed-mp-2026",
    ],
  },
  {
    id: "prod-babolat-pure-drive-gen11",
    slug: "babolat-pure-drive-gen11",
    brandId: "brand-babolat-padel",
    familyId: "fam-babolat-pure-drive",
    generation: "Gen11",
    name: "Pure Drive Gen11 100",
    fullName: "Babolat Pure Drive Gen11 100",
    shortDescription:
      "Current Pure Drive power midplus — accessible depth and a broad sweet spot for intermediate all-court play.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-power", "uc-tennis-balanced"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 300,
      strungWeightG: 318,
      balance: "even",
      stringPattern: "16x19",
      beamWidthMm: 23,
      powerPositioning: "power",
      controlPositioning: "moderate",
      spinPositioning: "moderate",
      stiffnessRa: 72,
      playerLevel: "intermediate",
    },
    strengths: ["Accessible power", "Broad sweet spot", "Easy depth"],
    weaknesses: ["Less surgical than dense control frames"],
    recommendationScore: 93,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 269,
    imgIndex: 2,
    relatedProductIds: ["prod-babolat-pure-drive-2025", "prod-babolat-pure-aero-2026"],
    alternativeProductIds: [
      "prod-yonex-ezone-100-2025",
      "prod-wilson-blade-98-v9",
    ],
  },
  {
    id: "prod-babolat-pure-aero-2026",
    slug: "babolat-pure-aero-2026",
    brandId: "brand-babolat-padel",
    familyId: "fam-babolat-pure-aero",
    generation: "Gen9-2026",
    name: "Pure Aero 100 Gen9 2026",
    fullName: "Babolat Pure Aero 100 Gen9 2026",
    shortDescription:
      "Current aero spin frame for players who shape heavy topspin with an open 16x19 pattern.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-spin", "uc-tennis-power"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 300,
      strungWeightG: 318,
      balance: "even",
      stringPattern: "16x19",
      powerPositioning: "power",
      controlPositioning: "moderate",
      spinPositioning: "high",
      stiffnessRa: 69,
      playerLevel: "intermediate",
    },
    strengths: ["Spin window", "Aero swing speed", "High-bounce friendliness"],
    weaknesses: ["Can feel lively for flat hitters"],
    recommendationScore: 92,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 269,
    imgIndex: 3,
    relatedProductIds: ["prod-babolat-pure-aero-2023", "prod-babolat-pure-drive-gen11"],
    alternativeProductIds: [
      "prod-yonex-vcore-98-2026",
      "prod-yonex-vcore-100-2023",
    ],
  },
  {
    id: "prod-head-speed-mp-2026",
    slug: "head-speed-mp-2026",
    brandId: "brand-head-padel",
    familyId: "fam-head-speed",
    generation: "2026",
    name: "Speed MP 2026",
    fullName: "Head Speed MP 2026",
    shortDescription:
      "Current Speed midplus all-rounder — controllable power and Auxetic 2 feel for intermediate to advanced players.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-balanced", "uc-tennis-power", "uc-tennis-beginner"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 300,
      strungWeightG: 318,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 23,
      powerPositioning: "balanced",
      controlPositioning: "balanced",
      spinPositioning: "moderate",
      stiffnessRa: 60,
      playerLevel: "intermediate",
    },
    strengths: ["All-court versatility", "Connected Speed feel", "Accessible handling"],
    weaknesses: ["Not the softest Clash-class flex"],
    recommendationScore: 90,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 259,
    imgIndex: 4,
    relatedProductIds: ["prod-head-speed-mp-2024", "prod-head-radical-mp-2023"],
    alternativeProductIds: [
      "prod-wilson-clash-100-v3",
      "prod-yonex-ezone-100-2025",
    ],
  },
  {
    id: "prod-yonex-ezone-100-2025",
    slug: "yonex-ezone-100-2025",
    brandId: "brand-yonex",
    familyId: "fam-yonex-ezone",
    generation: "8th-gen-2025",
    name: "EZONE 100 2025",
    fullName: "Yonex EZONE 100 8th Gen 2025",
    shortDescription:
      "Forgiving power midplus with ISOMETRIC sweet spot — plush comfort and easy depth for club to advanced players.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-power", "uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 300,
      strungWeightG: 315,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 24.5,
      powerPositioning: "power",
      controlPositioning: "moderate",
      spinPositioning: "moderate",
      stiffnessRa: 68,
      playerLevel: "intermediate",
    },
    strengths: ["Forgiving power", "Plush comfort", "Large effective sweet spot"],
    weaknesses: ["Less dense control than EZONE 98 / Blade 98"],
    recommendationScore: 94,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 269,
    imgIndex: 0,
    relatedProductIds: ["prod-yonex-ezone-98-2024"],
    alternativeProductIds: [
      "prod-babolat-pure-drive-gen11",
      "prod-wilson-clash-100-v3",
    ],
  },
  {
    id: "prod-yonex-vcore-98-2026",
    slug: "yonex-vcore-98-2026",
    brandId: "brand-yonex",
    familyId: "fam-yonex-vcore",
    generation: "8th-gen-2026",
    name: "VCORE 98 2026",
    fullName: "Yonex VCORE 98 8th Gen 2026",
    shortDescription:
      "Current VCORE spin 98 — aero beam and open pattern for intermediate to advanced players shaping topspin.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-spin", "uc-tennis-control"],
    specifications: {
      headSizeSqIn: 98,
      unstrungWeightG: 305,
      strungWeightG: 323,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 23,
      powerPositioning: "balanced",
      controlPositioning: "high",
      spinPositioning: "high",
      stiffnessRa: 63,
      playerLevel: "advanced",
    },
    strengths: ["Spin access", "Precise 98 targeting", "Aero swing"],
    weaknesses: ["Less free power than Pure Aero 100"],
    recommendationScore: 91,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 279,
    imgIndex: 1,
    relatedProductIds: ["prod-yonex-vcore-100-2023"],
    alternativeProductIds: [
      "prod-babolat-pure-aero-2026",
      "prod-wilson-blade-98-v9",
    ],
  },
  {
    id: "prod-wilson-blade-100-v9",
    slug: "wilson-blade-100-v9",
    brandId: "brand-wilson-padel",
    familyId: "fam-wilson-blade",
    generation: "v9-100",
    name: "Blade 100 v9",
    fullName: "Wilson Blade 100 v9",
    shortDescription:
      "More forgiving Blade variant — 100 sq in head with Blade feel for players wanting control geometry with extra margin.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-control", "uc-tennis-balanced", "uc-tennis-beginner"],
    specifications: {
      headSizeSqIn: 100,
      unstrungWeightG: 300,
      strungWeightG: 316,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 22,
      powerPositioning: "balanced",
      controlPositioning: "high",
      spinPositioning: "moderate",
      stiffnessRa: 60,
      playerLevel: "intermediate",
    },
    strengths: ["Blade feel with more forgiveness", "Spin-friendly 16x19", "Stable midplus"],
    weaknesses: ["Less precise than Blade 98 for dense control hitters"],
    recommendationScore: 89,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 249,
    imgIndex: 2,
    relatedProductIds: ["prod-wilson-blade-98-v9"],
    alternativeProductIds: [
      "prod-yonex-ezone-100-2025",
      "prod-head-speed-mp-2026",
    ],
  },
  {
    id: "prod-tecnifibre-tfight-300s-2025",
    slug: "tecnifibre-tfight-300s-2025",
    brandId: "brand-tecnifibre",
    familyId: "fam-tecnifibre-tfight",
    generation: "2025-300S",
    name: "TFight 300S 2025",
    fullName: "Tecnifibre TFight 300S 2025",
    shortDescription:
      "Current TFight control midplus (98 / 16x19, 300 g unstrung) — distinct from denser TF40 305 for modern control/power blend.",
    categoryId: "cat-tennis-rackets",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-control", "uc-tennis-balanced"],
    specifications: {
      headSizeSqIn: 98,
      unstrungWeightG: 300,
      strungWeightG: 318,
      balance: "head-light",
      stringPattern: "16x19",
      beamWidthMm: 22.5,
      powerPositioning: "balanced",
      controlPositioning: "high",
      spinPositioning: "moderate",
      stiffnessRa: 66,
      playerLevel: "advanced",
    },
    strengths: ["Precise targeting", "Modern RS beam power", "Tour-proven control line"],
    weaknesses: ["Less free power than Pure Drive-class 100s"],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 249,
    imgIndex: 3,
    relatedProductIds: ["prod-tecnifibre-tf40-305"],
    alternativeProductIds: [
      "prod-wilson-blade-98-v9",
      "prod-yonex-ezone-98-2024",
    ],
  },
];

const stringDrafts: Draft[] = [
  {
    id: "prod-luxilon-alu-power",
    slug: "luxilon-alu-power",
    brandId: "brand-luxilon",
    name: "ALU Power",
    fullName: "Luxilon ALU Power",
    shortDescription:
      "Stiff co-polyester control string — gauge options as specs, not separate colour SKUs.",
    categoryId: "cat-tennis-strings",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-control"],
    specifications: {
      material: "co-polyester",
      profile: "round",
      gaugeOptionsMm: ["1.10", "1.25", "1.30"],
      gaugeMm: 1.25,
      spinPotential: "moderate",
      feel: "crisp-control",
    },
    strengths: ["Control", "Tension maintenance for poly", "Tour staple"],
    weaknesses: ["Firm on the arm vs multifilament"],
    recommendationScore: 90,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 16,
    useCategoryFallback: true,
  },
  {
    id: "prod-wilson-nxt",
    slug: "wilson-nxt",
    brandId: "brand-wilson-padel",
    name: "NXT",
    fullName: "Wilson NXT",
    shortDescription:
      "Comfort multifilament for players prioritising arm feel — gauge options as specs.",
    categoryId: "cat-tennis-strings",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      material: "multifilament",
      profile: "round",
      gaugeOptionsMm: ["1.24", "1.30", "1.35"],
      gaugeMm: 1.30,
      spinPotential: "low-moderate",
      feel: "soft-comfort",
    },
    strengths: ["Arm comfort", "Power-friendly pocketing", "Beginner-friendly"],
    weaknesses: ["Less durable / spin bite than shaped poly"],
    recommendationScore: 86,
    valueScore: 85,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 18,
    useCategoryFallback: true,
  },
  {
    id: "prod-tecnifibre-x-one-biphase",
    slug: "tecnifibre-x-one-biphase",
    brandId: "brand-tecnifibre",
    name: "X-One Biphase",
    fullName: "Tecnifibre X-One Biphase",
    shortDescription:
      "Power-oriented multifilament with soft response — gauge options as specs, not colour variants.",
    categoryId: "cat-tennis-strings",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-power", "uc-tennis-beginner"],
    specifications: {
      material: "multifilament",
      profile: "round",
      gaugeOptionsMm: ["1.18", "1.24", "1.30"],
      gaugeMm: 1.24,
      spinPotential: "low-moderate",
      feel: "soft-power",
    },
    strengths: ["Easy power", "Comfort", "Club-player friendly"],
    weaknesses: ["Not a spin-poly substitute"],
    recommendationScore: 85,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 17,
    useCategoryFallback: true,
  },
  {
    id: "prod-solinco-hyper-g",
    slug: "solinco-hyper-g",
    brandId: "brand-solinco",
    name: "Hyper-G",
    fullName: "Solinco Hyper-G",
    shortDescription:
      "Shaped co-polyester for spin and control — gauge options as specs (complements RPM Blast already in seed).",
    categoryId: "cat-tennis-strings",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-spin", "uc-tennis-control"],
    specifications: {
      material: "co-polyester",
      profile: "shaped",
      gaugeOptionsMm: ["1.10", "1.15", "1.20", "1.25", "1.30"],
      gaugeMm: 1.25,
      spinPotential: "high",
      feel: "firm-spin",
    },
    strengths: ["Spin bite", "Control", "Popular shaped poly"],
    weaknesses: ["Firm vs multifilament comfort strings"],
    recommendationScore: 88,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 13,
    useCategoryFallback: true,
  },
];

/** New court shoes only — Gel-Resolution 9 and Rush Pro 4.0 already in racket/seed. */
const shoeDrafts: Draft[] = [
  {
    id: "prod-nike-court-vapor-pro-3",
    slug: "nike-court-vapor-pro-3",
    brandId: "brand-nike",
    generation: "3",
    name: "Court Vapor Pro 3",
    fullName: "Nike Court Air Zoom Vapor Pro 3",
    shortDescription:
      "Lightweight tennis shoe for players who want speed and court feel over max stability.",
    categoryId: "cat-tennis-shoes",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      courtSurface: "hard",
      stability: "moderate",
      cushioning: "moderate",
      weightClass: "light",
    },
    strengths: ["Low-to-ground feel", "Quick direction changes", "Breathable upper"],
    weaknesses: ["Less planted than Resolution-class stability shoes"],
    recommendationScore: 86,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 139,
    useCategoryFallback: true,
  },
  {
    id: "prod-adidas-barricade-13",
    slug: "adidas-barricade-13",
    brandId: "brand-adidas",
    generation: "13",
    name: "Barricade 13",
    fullName: "Adidas Barricade 13",
    shortDescription:
      "Stable hard-court tennis shoe with Geofit lock-down for aggressive baseliners.",
    categoryId: "cat-tennis-shoes",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-control"],
    specifications: {
      courtSurface: "hard",
      stability: "high",
      cushioning: "moderate",
      weightClass: "moderate",
    },
    strengths: ["Lateral lock-down", "Durable outsole", "Supportive fit"],
    weaknesses: ["Heavier than speed-oriented court shoes"],
    recommendationScore: 88,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 149,
    useCategoryFallback: true,
  },
  {
    id: "prod-babolat-jet-tere",
    slug: "babolat-jet-tere",
    brandId: "brand-babolat-padel",
    name: "Jet Tere",
    fullName: "Babolat Jet Tere",
    shortDescription:
      "Light court shoe for all-court movement — shared tennis/padel court use where surfaces allow.",
    categoryId: "cat-tennis-shoes",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      courtSurface: "hard-clay",
      stability: "moderate",
      cushioning: "moderate",
      weightClass: "light",
    },
    strengths: ["Light weight", "Flexible fit", "Approachable price"],
    weaknesses: ["Less max stability than Barricade / Resolution"],
    recommendationScore: 82,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 119,
    useCategoryFallback: true,
  },
  {
    id: "prod-asics-gel-challenger-15",
    slug: "asics-gel-challenger-15",
    brandId: "brand-asics-racket",
    generation: "15",
    name: "Gel-Challenger 15",
    fullName: "ASICS Gel-Challenger 15",
    shortDescription:
      "Value-oriented ASICS court shoe — stability-biased alternative when Gel-Resolution is over budget.",
    categoryId: "cat-tennis-shoes",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner"],
    specifications: {
      courtSurface: "hard",
      stability: "high",
      cushioning: "moderate",
      weightClass: "moderate",
    },
    strengths: ["Stable platform", "Strong value vs Resolution", "Durable court outsole"],
    weaknesses: ["Less premium cushioning than Resolution 9"],
    recommendationScore: 84,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 119,
    useCategoryFallback: true,
  },
  {
    id: "prod-wilson-rush-pro-5",
    slug: "wilson-rush-pro-5-0",
    brandId: "brand-wilson-padel",
    generation: "5.0",
    name: "Rush Pro 5.0",
    fullName: "Wilson Rush Pro 5.0",
    shortDescription:
      "Current Rush Pro court shoe balancing cushion and court feel (succeeds Rush Pro 4.0 in seed).",
    categoryId: "cat-tennis-shoes",
    sportIds: [sportTennis],
    useCaseIds: ["uc-tennis-beginner", "uc-tennis-balanced"],
    specifications: {
      courtSurface: "hard",
      stability: "moderate",
      cushioning: "high",
      weightClass: "moderate",
    },
    strengths: ["Cushion", "Approachable fit", "All-court movement"],
    weaknesses: ["Less planted than Barricade / Resolution"],
    recommendationScore: 85,
    valueScore: 86,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 135,
    useCategoryFallback: true,
  },
];

const allDrafts: Draft[] = [...racketDrafts, ...stringDrafts, ...shoeDrafts];

function toProduct(d: Draft): Product {
  const images = d.useCategoryFallback
    ? categoryFallbackImage(
        d.categoryId,
        d.id,
        `${d.fullName} — product image unavailable (Kitletics category fallback)`,
      )
    : tennisRacketImg(d.id, d.imgIndex ?? 0, d.fullName);

  return {
    id: d.id,
    slug: d.slug,
    brandId: d.brandId,
    familyId: d.familyId,
    generation: d.generation,
    name: d.name,
    fullName: d.fullName,
    shortDescription: d.shortDescription,
    lifecycleStatus: "current",
    sportIds: d.sportIds,
    disciplineIds: [],
    categoryId: d.categoryId,
    subcategoryIds: [],
    useCaseIds: d.useCaseIds,
    specifications: d.specifications,
    strengths: d.strengths,
    weaknesses: d.weaknesses,
    recommendationScore: d.recommendationScore,
    valueScore: d.valueScore,
    experienceLevels: d.experienceLevels,
    images,
    videos: [],
    offerIds: [
      `offer-${d.slug}-nl`,
      `offer-${d.slug}-de`,
      `offer-${d.slug}-uk`,
    ],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    relatedProductIds: d.relatedProductIds ?? [],
    alternativeProductIds: d.alternativeProductIds ?? [],
    ...pub,
  };
}

/** Hold SKUs without authentic heroes out of published catalog until packshots exist. */
const WAVE26_MEDIA_PENDING_DRAFT = new Set([
  "prod-babolat-jet-tere",
  "prod-wilson-rush-pro-5",
]);

export const wave26TennisProducts: Product[] = allDrafts.map(toProduct).map((p) =>
  (p.categoryId === "cat-tennis-strings" || WAVE26_MEDIA_PENDING_DRAFT.has(p.id)) &&
  !hasRegisteredProductHero(p.id)
    ? { ...p, status: "draft" as const }
    : p,
);

export const wave26TennisOffers: Offer[] = allDrafts.flatMap((d) =>
  offerTriplet(d.id, d.slug, d.priceEur),
);

/**
 * Overlay patches for existing seed products — apply at merge time; do not mutate seed.ts.
 * Marks superseded frames previous-generation and attaches family/generation.
 */
export const wave26TennisPatches: Record<string, Partial<Product>> = {
  "prod-wilson-clash-100-v2": {
    lifecycleStatus: "previous-generation",
    familyId: "fam-wilson-clash",
    generation: "v2",
    relatedProductIds: ["prod-wilson-clash-100-v3"],
    alternativeProductIds: ["prod-wilson-clash-100-v3", "prod-head-speed-mp-2024"],
  },
  "prod-wilson-blade-98-v8": {
    lifecycleStatus: "previous-generation",
    familyId: "fam-wilson-blade",
    generation: "v8",
    relatedProductIds: ["prod-wilson-blade-98-v9", "prod-yonex-ezone-98-2024"],
    alternativeProductIds: ["prod-wilson-blade-98-v9", "prod-tecnifibre-tf40-305"],
  },
  "prod-babolat-pure-aero-2023": {
    lifecycleStatus: "previous-generation",
    familyId: "fam-babolat-pure-aero",
    generation: "2023",
    relatedProductIds: ["prod-babolat-pure-aero-2026"],
    alternativeProductIds: ["prod-babolat-pure-aero-2026", "prod-yonex-vcore-100-2023"],
  },
  "prod-head-speed-mp-2024": {
    lifecycleStatus: "previous-generation",
    familyId: "fam-head-speed",
    generation: "2024",
    relatedProductIds: ["prod-head-speed-mp-2026", "prod-head-radical-mp-2023"],
    alternativeProductIds: ["prod-head-speed-mp-2026", "prod-wilson-clash-100-v2"],
  },
  "prod-babolat-pure-drive-2025": {
    lifecycleStatus: "previous-generation",
    familyId: "fam-babolat-pure-drive",
    generation: "2025",
    relatedProductIds: ["prod-babolat-pure-drive-gen11"],
    alternativeProductIds: [
      "prod-babolat-pure-drive-gen11",
      "prod-yonex-ezone-98-2024",
    ],
  },
  "prod-yonex-ezone-98-2024": {
    familyId: "fam-yonex-ezone",
    generation: "2024",
  },
  "prod-yonex-vcore-100-2023": {
    familyId: "fam-yonex-vcore",
    generation: "2023",
  },
  "prod-tecnifibre-tf40-305": {
    familyId: "fam-tecnifibre-tfight",
    generation: "TF40-305",
  },
  "prod-wilson-rush-pro-4": {
    lifecycleStatus: "previous-generation",
    generation: "4.0",
    relatedProductIds: ["prod-wilson-rush-pro-5"],
  },
  "prod-asics-gel-resolution-9": {
    generation: "9",
  },
};

export const wave26TennisFamilies: ProductFamily[] = [
  {
    id: "fam-wilson-blade",
    brandId: "brand-wilson-padel",
    name: "Blade",
    slug: "wilson-blade",
    categoryId: "cat-tennis-rackets",
    description: "Wilson Blade control family — connected feel midplus frames.",
    productIds: [
      "prod-wilson-blade-98-v9",
      "prod-wilson-blade-100-v9",
      "prod-wilson-blade-98-v8",
    ],
  },
  {
    id: "fam-wilson-clash",
    brandId: "brand-wilson-padel",
    name: "Clash",
    slug: "wilson-clash",
    categoryId: "cat-tennis-rackets",
    description: "Wilson Clash comfort/forgiveness family.",
    productIds: ["prod-wilson-clash-100-v3", "prod-wilson-clash-100-v2"],
  },
  {
    id: "fam-babolat-pure-drive",
    brandId: "brand-babolat-padel",
    name: "Pure Drive",
    slug: "babolat-pure-drive",
    categoryId: "cat-tennis-rackets",
    description: "Babolat Pure Drive power midplus family.",
    productIds: [
      "prod-babolat-pure-drive-gen11",
      "prod-babolat-pure-drive-2025",
    ],
  },
  {
    id: "fam-babolat-pure-aero",
    brandId: "brand-babolat-padel",
    name: "Pure Aero",
    slug: "babolat-pure-aero",
    categoryId: "cat-tennis-rackets",
    description: "Babolat Pure Aero spin family.",
    productIds: [
      "prod-babolat-pure-aero-2026",
      "prod-babolat-pure-aero-2023",
    ],
  },
  {
    id: "fam-head-speed",
    brandId: "brand-head-padel",
    name: "Speed",
    slug: "head-speed",
    categoryId: "cat-tennis-rackets",
    description: "Head Speed all-court midplus family.",
    productIds: ["prod-head-speed-mp-2026", "prod-head-speed-mp-2024"],
  },
  {
    id: "fam-yonex-ezone",
    brandId: "brand-yonex",
    name: "EZONE",
    slug: "yonex-ezone",
    categoryId: "cat-tennis-rackets",
    description: "Yonex EZONE power/comfort ISOMETRIC family.",
    productIds: ["prod-yonex-ezone-100-2025", "prod-yonex-ezone-98-2024"],
  },
  {
    id: "fam-yonex-vcore",
    brandId: "brand-yonex",
    name: "VCORE",
    slug: "yonex-vcore",
    categoryId: "cat-tennis-rackets",
    description: "Yonex VCORE spin family.",
    productIds: ["prod-yonex-vcore-98-2026", "prod-yonex-vcore-100-2023"],
  },
  {
    id: "fam-tecnifibre-tfight",
    brandId: "brand-tecnifibre",
    name: "TFight",
    slug: "tecnifibre-tfight",
    categoryId: "cat-tennis-rackets",
    description: "Tecnifibre TFight / TF40 control family grouping.",
    productIds: ["prod-tecnifibre-tfight-300s-2025", "prod-tecnifibre-tf40-305"],
  },
];

export const wave26TennisEvidence: Evidence[] = [
  {
    id: "ev-wave26-tennis-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — tennis catalog",
    summary:
      "Category placement and publicly listed specs/positioning from manufacturer pages (Wilson, Babolat, Head, Yonex, Tecnifibre) and reputable retailers. Not personal lab or on-court testing. Swingweight omitted unless not applicable; stiffnessRa included only when published by manufacturer or major review labs.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];

export const wave26TennisRecommendations: Recommendation[] = [
  {
    id: "rec-w26-clash-v3-beginner",
    productId: "prod-wilson-clash-100-v3",
    sportId: sportTennis,
    useCaseId: "uc-tennis-beginner",
    score: 94,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 95, weight: 0.45 },
      { key: "comfort", label: "Comfort", score: 94, weight: 0.35 },
      { key: "value", label: "Value", score: 86, weight: 0.2 },
    ],
    strengths: ["Flexible FreeFlex comfort", "Easy swing weight"],
    compromises: ["Less plow-through for heavy hitters"],
    explanation:
      "Primary beginner/comfort pick when forgiveness outweighs dense control.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-ezone-100-beginner",
    productId: "prod-yonex-ezone-100-2025",
    sportId: sportTennis,
    useCaseId: "uc-tennis-beginner",
    score: 90,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 92, weight: 0.4 },
      { key: "power", label: "Power", score: 90, weight: 0.35 },
      { key: "comfort", label: "Comfort", score: 88, weight: 0.25 },
    ],
    strengths: ["Large ISOMETRIC sweet spot", "Plush power"],
    compromises: ["Premium price vs Clash"],
    explanation:
      "Forgiving power alternative when players want more ball speed than Clash.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-blade-v9-control",
    productId: "prod-wilson-blade-98-v9",
    sportId: sportTennis,
    useCaseId: "uc-tennis-control",
    score: 94,
    factors: [
      { key: "control", label: "Control", score: 95, weight: 0.5 },
      { key: "stability", label: "Stability", score: 91, weight: 0.3 },
      { key: "feel", label: "Feel", score: 90, weight: 0.2 },
    ],
    strengths: ["Connected Blade feel", "Precise 98 targeting"],
    compromises: ["Needs cleaner contact than 100 sq in frames"],
    explanation:
      "Current go-to control midplus for intermediate/advanced baseliners.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-tfight-control",
    productId: "prod-tecnifibre-tfight-300s-2025",
    sportId: sportTennis,
    useCaseId: "uc-tennis-control",
    score: 88,
    factors: [
      { key: "control", label: "Control", score: 92, weight: 0.45 },
      { key: "maneuverability", label: "Maneuverability", score: 90, weight: 0.3 },
      { key: "power", label: "Power", score: 82, weight: 0.25 },
    ],
    strengths: ["Modern TFight targeting", "Faster than denser TF40"],
    compromises: ["Less free power than Pure Drive"],
    explanation:
      "Control alternative when players prefer Tecnifibre RS beam over Blade.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-pure-drive-gen11-power",
    productId: "prod-babolat-pure-drive-gen11",
    sportId: sportTennis,
    useCaseId: "uc-tennis-power",
    score: 95,
    factors: [
      { key: "power", label: "Power", score: 96, weight: 0.5 },
      { key: "sweetspot", label: "Sweet spot", score: 92, weight: 0.3 },
      { key: "value", label: "Value", score: 84, weight: 0.2 },
    ],
    strengths: ["Accessible depth", "Broad appeal"],
    compromises: ["Less surgical than Blade / TFight"],
    explanation:
      "Default power-friendly midplus for intermediate all-court players.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-ezone-100-power",
    productId: "prod-yonex-ezone-100-2025",
    sportId: sportTennis,
    useCaseId: "uc-tennis-power",
    score: 92,
    factors: [
      { key: "power", label: "Power", score: 93, weight: 0.45 },
      { key: "comfort", label: "Comfort", score: 90, weight: 0.3 },
      { key: "forgiveness", label: "Forgiveness", score: 91, weight: 0.25 },
    ],
    strengths: ["Plush power", "Forgiving launch"],
    compromises: ["Different pocketing than Pure Drive"],
    explanation:
      "Power pick when comfort and ISOMETRIC forgiveness matter as much as raw pop.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-pure-aero-2026-spin",
    productId: "prod-babolat-pure-aero-2026",
    sportId: sportTennis,
    useCaseId: "uc-tennis-spin",
    score: 94,
    factors: [
      { key: "spin", label: "Spin", score: 97, weight: 0.55 },
      { key: "power", label: "Power", score: 88, weight: 0.25 },
      { key: "control", label: "Control", score: 78, weight: 0.2 },
    ],
    strengths: ["Aero spin window", "Easy RPMs on high-bounce balls"],
    compromises: ["Can feel lively for flat hitters"],
    explanation: "Spin-first choice for shaping heavy topspin.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-vcore-98-spin",
    productId: "prod-yonex-vcore-98-2026",
    sportId: sportTennis,
    useCaseId: "uc-tennis-spin",
    score: 90,
    factors: [
      { key: "spin", label: "Spin", score: 94, weight: 0.5 },
      { key: "control", label: "Control", score: 88, weight: 0.3 },
      { key: "feel", label: "Feel", score: 86, weight: 0.2 },
    ],
    strengths: ["Spin with 98 precision", "Aero 2026 beam"],
    compromises: ["Less free power than Pure Aero 100"],
    explanation:
      "Spin alternative when players want denser targeting than a 100 sq in Aero.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-speed-mp-balanced",
    productId: "prod-head-speed-mp-2026",
    sportId: sportTennis,
    useCaseId: "uc-tennis-balanced",
    score: 91,
    factors: [
      { key: "versatility", label: "Versatility", score: 93, weight: 0.45 },
      { key: "feel", label: "Feel", score: 88, weight: 0.3 },
      { key: "value", label: "Value", score: 85, weight: 0.25 },
    ],
    strengths: ["All-court blend", "Connected Auxetic feel"],
    compromises: ["Not extreme power or extreme control"],
    explanation:
      "Balanced all-court pick without a strong power or control bias.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
  {
    id: "rec-w26-blade-100-balanced",
    productId: "prod-wilson-blade-100-v9",
    sportId: sportTennis,
    useCaseId: "uc-tennis-balanced",
    score: 88,
    factors: [
      { key: "control", label: "Control", score: 88, weight: 0.35 },
      { key: "forgiveness", label: "Forgiveness", score: 86, weight: 0.35 },
      { key: "feel", label: "Feel", score: 87, weight: 0.3 },
    ],
    strengths: ["Blade feel with more margin", "Spin-friendly pattern"],
    compromises: ["Less precise than Blade 98"],
    explanation:
      "Balanced control-leaning option when 98 is too demanding.",
    evidenceIds: ["ev-wave26-tennis-editorial"],
  },
];

/** Generation + competitor edges (ProductRelationship supports previous/next-generation). */
export const wave26TennisRelationships: ProductRelationship[] = [
  {
    id: "rel-w26-blade-v9-v8-prev",
    sourceProductId: "prod-wilson-blade-98-v9",
    targetProductId: "prod-wilson-blade-98-v8",
    type: "previous-generation",
    categoryId: "cat-tennis-rackets",
    strength: 92,
    reasons: ["Same Blade 98 16x19 family; v8 is immediate prior generation"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-blade-v8-v9-next",
    sourceProductId: "prod-wilson-blade-98-v8",
    targetProductId: "prod-wilson-blade-98-v9",
    type: "next-generation",
    categoryId: "cat-tennis-rackets",
    strength: 92,
    reasons: ["Current Blade 98 16x19 succeeding v8"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-clash-v3-v2-prev",
    sourceProductId: "prod-wilson-clash-100-v3",
    targetProductId: "prod-wilson-clash-100-v2",
    type: "previous-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Same Clash 100 family; v2 often better value when discounted"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-clash-v2-v3-next",
    sourceProductId: "prod-wilson-clash-100-v2",
    targetProductId: "prod-wilson-clash-100-v3",
    type: "next-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Current Clash 100 succeeding v2"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-pure-drive-gen11-2025-prev",
    sourceProductId: "prod-babolat-pure-drive-gen11",
    targetProductId: "prod-babolat-pure-drive-2025",
    type: "previous-generation",
    categoryId: "cat-tennis-rackets",
    strength: 88,
    reasons: ["Same Pure Drive family; seed 2025 listing treated as prior vs Gen11"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-pure-drive-2025-gen11-next",
    sourceProductId: "prod-babolat-pure-drive-2025",
    targetProductId: "prod-babolat-pure-drive-gen11",
    type: "next-generation",
    categoryId: "cat-tennis-rackets",
    strength: 88,
    reasons: ["Current Pure Drive Gen11 succeeding seed 2025 entry"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-pure-aero-2026-2023-prev",
    sourceProductId: "prod-babolat-pure-aero-2026",
    targetProductId: "prod-babolat-pure-aero-2023",
    type: "previous-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Same Pure Aero 100 family; 2023 is prior aero spin generation"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-pure-aero-2023-2026-next",
    sourceProductId: "prod-babolat-pure-aero-2023",
    targetProductId: "prod-babolat-pure-aero-2026",
    type: "next-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Current Pure Aero Gen9 2026 succeeding 2023"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-speed-2026-2024-prev",
    sourceProductId: "prod-head-speed-mp-2026",
    targetProductId: "prod-head-speed-mp-2024",
    type: "previous-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Same Speed MP family; 2024 is immediate prior"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-speed-2024-2026-next",
    sourceProductId: "prod-head-speed-mp-2024",
    targetProductId: "prod-head-speed-mp-2026",
    type: "next-generation",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Current Speed MP 2026 succeeding 2024"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-blade-vs-pure-drive",
    sourceProductId: "prod-wilson-blade-98-v9",
    targetProductId: "prod-babolat-pure-drive-gen11",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 84,
    reasons: [
      "Control midplus vs power midplus decision pair",
      "Common Blade vs Pure Drive / Pure Strike-style shop comparison",
    ],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-ezone-vs-pure-drive",
    sourceProductId: "prod-yonex-ezone-100-2025",
    targetProductId: "prod-babolat-pure-drive-gen11",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 88,
    reasons: ["Both forgiving power 100s; different pocketing and beam character"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-ezone-vs-clash",
    sourceProductId: "prod-yonex-ezone-100-2025",
    targetProductId: "prod-wilson-clash-100-v3",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 86,
    reasons: ["Both beginner-friendly 100s; power/comfort vs flex/forgiveness"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-aero-vs-vcore",
    sourceProductId: "prod-babolat-pure-aero-2026",
    targetProductId: "prod-yonex-vcore-100-2023",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 85,
    reasons: ["Spin-oriented 100s across Babolat Aero and Yonex VCORE lines"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-blade-vs-tfight",
    sourceProductId: "prod-wilson-blade-98-v9",
    targetProductId: "prod-tecnifibre-tfight-300s-2025",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 87,
    reasons: ["Both modern 98 control frames with open 16x19 patterns"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-blade98-vs-blade100-v9",
    sourceProductId: "prod-wilson-blade-98-v9",
    targetProductId: "prod-wilson-blade-100-v9",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 90,
    reasons: ["Same Blade v9 family: 98 control density vs 100 forgiveness"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-vcore98-vs-aero",
    sourceProductId: "prod-yonex-vcore-98-2026",
    targetProductId: "prod-babolat-pure-aero-2026",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 84,
    reasons: ["Spin-oriented frames: denser VCORE 98 vs Aero 100 launch window"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-ezone98-vs-blade98",
    sourceProductId: "prod-yonex-ezone-98-2024",
    targetProductId: "prod-wilson-blade-98-v9",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 88,
    reasons: ["Premium 98 control pair with different pocketing character"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-tf40-vs-blade98",
    sourceProductId: "prod-tecnifibre-tf40-305",
    targetProductId: "prod-wilson-blade-98-v9",
    type: "direct-competitor",
    categoryId: "cat-tennis-rackets",
    strength: 86,
    reasons: ["Dense control 98s for advanced baseliners"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-dunlop-vs-radical",
    sourceProductId: "prod-dunlop-cx-200",
    targetProductId: "prod-head-radical-mp-2023",
    type: "similar",
    categoryId: "cat-tennis-rackets",
    strength: 76,
    reasons: ["Classic player-frame alternatives outside the newest flagship SKUs"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-prince-vs-clash",
    sourceProductId: "prod-prince-textreme-tour-100p",
    targetProductId: "prod-wilson-clash-100-v3",
    type: "similar",
    categoryId: "cat-tennis-rackets",
    strength: 74,
    reasons: ["100 sq in comfort-oriented frames for accessible club play"],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    directional: false,
    ...relMeta,
  },
];

/** Legacy AlternativeRelationship view for recommendation merges. */
export const wave26TennisAlternatives: AlternativeRelationship[] = [
  {
    id: "alt-w26-blade-v8-to-v9",
    sourceProductId: "prod-wilson-blade-98-v8",
    alternativeProductId: "prod-wilson-blade-98-v9",
    similarityScore: 92,
    reasons: ["Same Blade 98 16x19 family", "v9 is current generation"],
    relationshipType: "premium",
  },
  {
    id: "alt-w26-clash-v2-to-v3",
    sourceProductId: "prod-wilson-clash-100-v2",
    alternativeProductId: "prod-wilson-clash-100-v3",
    similarityScore: 90,
    reasons: ["Same Clash 100 comfort line", "v3 is current generation"],
    relationshipType: "premium",
  },
  {
    id: "alt-w26-pure-drive-to-gen11",
    sourceProductId: "prod-babolat-pure-drive-2025",
    alternativeProductId: "prod-babolat-pure-drive-gen11",
    similarityScore: 88,
    reasons: ["Same Pure Drive power role", "Gen11 is current listing"],
    relationshipType: "premium",
  },
  {
    id: "alt-w26-aero-2023-to-2026",
    sourceProductId: "prod-babolat-pure-aero-2023",
    alternativeProductId: "prod-babolat-pure-aero-2026",
    similarityScore: 90,
    reasons: ["Same Pure Aero spin role", "Gen9 2026 is current"],
    relationshipType: "premium",
  },
  {
    id: "alt-w26-speed-2024-to-2026",
    sourceProductId: "prod-head-speed-mp-2024",
    alternativeProductId: "prod-head-speed-mp-2026",
    similarityScore: 90,
    reasons: ["Same Speed MP all-court role", "2026 is current"],
    relationshipType: "premium",
  },
  {
    id: "alt-w26-blade-vs-pure-drive",
    sourceProductId: "prod-wilson-blade-98-v9",
    alternativeProductId: "prod-babolat-pure-drive-gen11",
    similarityScore: 72,
    reasons: [
      "Control vs power midplus decision",
      "Pure Strike / Pure Drive style alternative to Blade",
    ],
    relationshipType: "faster",
  },
  {
    id: "alt-w26-ezone-vs-pure-drive",
    sourceProductId: "prod-yonex-ezone-100-2025",
    alternativeProductId: "prod-babolat-pure-drive-gen11",
    similarityScore: 86,
    reasons: ["Both accessible power 100s", "Different beam and pocketing"],
    relationshipType: "faster",
  },
  {
    id: "alt-w26-ezone-vs-clash",
    sourceProductId: "prod-yonex-ezone-100-2025",
    alternativeProductId: "prod-wilson-clash-100-v3",
    similarityScore: 84,
    reasons: ["Both forgiving 100s", "Clash prioritises flex comfort"],
    relationshipType: "beginner-friendly",
  },
  {
    id: "alt-w26-aero-vs-vcore100",
    sourceProductId: "prod-babolat-pure-aero-2026",
    alternativeProductId: "prod-yonex-vcore-100-2023",
    similarityScore: 82,
    reasons: ["Both spin-oriented 100s", "Yonex vs Babolat geometry"],
    relationshipType: "better-value",
  },
  {
    id: "alt-w26-blade-vs-tfight",
    sourceProductId: "prod-wilson-blade-98-v9",
    alternativeProductId: "prod-tecnifibre-tfight-300s-2025",
    similarityScore: 85,
    reasons: ["Both modern 98 control frames", "Open 16x19 patterns"],
    relationshipType: "lighter",
  },
  {
    id: "alt-w26-clash-v3-value",
    sourceProductId: "prod-wilson-clash-100-v3",
    alternativeProductId: "prod-wilson-clash-100-v2",
    similarityScore: 88,
    reasons: ["Prior Clash often discounted", "Similar comfort brief"],
    relationshipType: "cheaper",
  },
];

export const wave26TennisComparisons: Comparison[] = [
  {
    id: "cmp-w26-blade98-v9-vs-pure-drive-gen11",
    slug: "wilson-blade-98-v9-vs-babolat-pure-drive-gen11",
    title: "Wilson Blade 98 v9 vs Babolat Pure Drive Gen11",
    shortDescription: "Control 98 vs power 100 — classic shop decision.",
    productIds: ["prod-wilson-blade-98-v9", "prod-babolat-pure-drive-gen11"],
    categoryId: "cat-tennis-rackets",
    comparisonType: "editorial",
    summary:
      "Blade 98 v9 prioritises connected control; Pure Drive Gen11 prioritises accessible power and forgiveness.",
    criteria: [
      {
        key: "control",
        label: "Control",
        winnerProductId: "prod-wilson-blade-98-v9",
      },
      {
        key: "power",
        label: "Power",
        winnerProductId: "prod-babolat-pure-drive-gen11",
      },
      {
        key: "forgiveness",
        label: "Forgiveness",
        winnerProductId: "prod-babolat-pure-drive-gen11",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-tennis-control",
        productId: "prod-wilson-blade-98-v9",
        rationale: "Denser 98 targeting and Blade feel.",
      },
      {
        useCaseId: "uc-tennis-power",
        productId: "prod-babolat-pure-drive-gen11",
        rationale: "Easier depth from a lively 100.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-wilson-blade-98-v9",
        reason: "You want precise, connected control and already time the ball well.",
      },
      {
        productId: "prod-babolat-pure-drive-gen11",
        reason: "You want free power and a more forgiving midplus.",
      },
    ],
    keyDifferences: [
      {
        label: "Head size & brief",
        productImpacts: [
          { productId: "prod-wilson-blade-98-v9", impact: "98 control" },
          { productId: "prod-babolat-pure-drive-gen11", impact: "100 power" },
        ],
        explanation:
          "Different jobs: placement vs easy ball speed — not a universal winner.",
        evidenceIds: ["ev-wave26-tennis-editorial"],
      },
    ],
    verdict:
      "Choose Blade 98 v9 for control; Pure Drive Gen11 for accessible power. Context beats a single winner.",
    faqIds: [],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    ...pub,
  },
  {
    id: "cmp-w26-ezone-100-vs-clash-100-v3",
    slug: "yonex-ezone-100-2025-vs-wilson-clash-100-v3",
    title: "Yonex EZONE 100 2025 vs Wilson Clash 100 v3",
    shortDescription: "Forgiving power versus flexible comfort.",
    productIds: ["prod-yonex-ezone-100-2025", "prod-wilson-clash-100-v3"],
    categoryId: "cat-tennis-rackets",
    comparisonType: "editorial",
    summary:
      "Both are approachable 100s; EZONE leans plush power, Clash leans soft flex and arm comfort.",
    criteria: [
      {
        key: "power",
        label: "Power",
        winnerProductId: "prod-yonex-ezone-100-2025",
      },
      {
        key: "comfort",
        label: "Comfort / flex",
        winnerProductId: "prod-wilson-clash-100-v3",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-tennis-power",
        productId: "prod-yonex-ezone-100-2025",
        rationale: "More free depth with a large sweet spot.",
      },
      {
        useCaseId: "uc-tennis-beginner",
        productId: "prod-wilson-clash-100-v3",
        rationale: "Softer flex when arm comfort is the priority.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-yonex-ezone-100-2025",
        reason: "You want forgiving power with a plush ISOMETRIC response.",
      },
      {
        productId: "prod-wilson-clash-100-v3",
        reason: "You prioritise flexible comfort and free swing.",
      },
    ],
    verdict:
      "EZONE 100 for power-oriented forgiveness; Clash v3 for comfort-first play.",
    faqIds: [],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    ...pub,
  },
  {
    id: "cmp-w26-pure-aero-2026-vs-vcore-100",
    slug: "babolat-pure-aero-2026-vs-yonex-vcore-100-2023",
    title: "Babolat Pure Aero 2026 vs Yonex VCORE 100",
    shortDescription: "Two spin-first 100 sq in approaches.",
    productIds: ["prod-babolat-pure-aero-2026", "prod-yonex-vcore-100-2023"],
    categoryId: "cat-tennis-rackets",
    comparisonType: "editorial",
    summary:
      "Pure Aero Gen9 2026 is the current Babolat spin flagship; VCORE 100 2023 remains a strong Yonex spin alternative (often value).",
    criteria: [
      {
        key: "spin",
        label: "Spin access",
        winnerProductId: "prod-babolat-pure-aero-2026",
        notes: "Aero shape bias; both are spin-capable 100s.",
      },
      {
        key: "value",
        label: "Value",
        winnerProductId: "prod-yonex-vcore-100-2023",
        notes: "Prior VCORE generation frequently discounted.",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-tennis-spin",
        productId: "prod-babolat-pure-aero-2026",
        rationale: "Current Aero spin platform.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-babolat-pure-aero-2026",
        reason: "You want the current Pure Aero spin package.",
      },
      {
        productId: "prod-yonex-vcore-100-2023",
        reason: "You prefer Yonex geometry or find strong previous-gen pricing.",
      },
    ],
    upgradeAdvice: {
      upgradeIf: [
        "You want the current Pure Aero Gen9 updates and colourways",
        "You are replacing a worn Pure Aero and care about current platform continuity",
      ],
      keepOlderIf: [
        "VCORE 100 2023 is heavily discounted and still matches your spin brief",
        "You already prefer Yonex ISOMETRIC feel",
      ],
    },
    verdict:
      "Choose Pure Aero 2026 for the current spin flagship; VCORE 100 when Yonex feel or discount value wins.",
    faqIds: [],
    evidenceIds: ["ev-wave26-tennis-editorial"],
    ...pub,
  },
];
