/**
 * Deterministic synonym map for Kitletics search.
 * Keys are normalized query tokens; values expand the query.
 */
export const SEARCH_SYNONYMS: Record<string, string[]> = {
  trainers: ["running shoes", "shoes", "daily trainers"],
  "running trainers": ["running shoes", "daily trainers"],
  "running shoes": ["shoes", "trainers"],
  shoes: ["running shoes", "trainers"],
  novablast: ["asics novablast", "nova blast", "asics nova"],
  "nova blast": ["novablast", "asics novablast"],
  "asics nova": ["novablast", "asics novablast"],
  nimbus: ["gel-nimbus", "asics nimbus", "gel nimbus"],
  "gel nimbus": ["nimbus", "gel-nimbus"],
  pegaus: ["pegasus", "nike pegasus"],
  pegasus: ["nike pegasus"],
  vaporfly: ["nike vaporfly", "carbon race shoe"],
  "carbon race shoe": ["vaporfly", "alphafly", "endorphin pro", "metaspeed"],
  "forerunner 965": ["fr965", "garmin forerunner 965"],
  fr965: ["forerunner 965", "garmin forerunner 965"],
  "forerunner 970": ["fr970", "garmin forerunner 970"],
  fr970: ["forerunner 970", "garmin forerunner 970"],
  "garmin running watch": ["forerunner", "gps watch", "gps watches"],
  "heart rate strap": ["hrm", "heart rate monitor", "chest strap"],
  "trail hydration vest": ["adv skin", "hydration", "running packs", "vest"],
  "running headphones": ["headphones", "shokz", "bone conduction", "open-ear"],
  shokz: ["running headphones", "bone conduction", "open-ear"],
  "gps watch": ["gps watches", "running watch", "sports watch", "forerunner"],
  "gps watches": ["gps watch", "running watch", "sports watch"],
  "running watch": ["gps watch", "gps watches", "sports watch"],
  "sports watch": ["gps watch", "gps watches", "running watch"],
  watch: ["gps watch", "gps watches"],
  "shoe finder": [
    "running shoe finder",
    "find running shoes",
    "running shoes",
  ],
  "running shoe finder": [
    "shoe finder",
    "find running shoes",
    "what running shoes should I buy",
  ],
  "find running shoes": ["running shoe finder", "shoe finder"],
  "what running shoes should I buy": ["running shoe finder", "shoe finder"],
  finder: ["running shoe finder", "shoe finder", "padel racket finder"],
  "pace calculator": [
    "running pace calculator",
    "running pace",
    "marathon pace",
  ],
  "running pace": ["pace calculator", "running pace calculator", "marathon pace"],
  "marathon pace": ["pace calculator", "running pace"],
  "race predictor": [
    "race time predictor",
    "race time calculator",
    "5k predictor",
    "marathon predictor",
  ],
  "race time predictor": ["race predictor", "race time calculator"],
  "race time calculator": ["race predictor", "race time predictor"],
  "5k predictor": ["race predictor", "race time predictor"],
  "marathon predictor": ["race predictor", "race time predictor"],
  "shoe rotation": [
    "shoe rotation planner",
    "running shoe rotation",
    "how many running shoes",
  ],
  "shoe rotation planner": [
    "shoe rotation",
    "running shoe rotation",
    "build running shoe rotation",
  ],
  "running shoe rotation": ["shoe rotation planner", "shoe rotation"],
  "how many running shoes": ["shoe rotation planner", "shoe rotation"],
  "build running shoe rotation": ["shoe rotation planner"],
  vest: ["running packs", "hydration", "adv skin"],
  vests: ["running packs", "hydration"],
  hydration: ["vest", "flask", "packs"],
  hrm: ["heart rate", "heart rate monitor", "chest strap"],
  "heart rate": ["hrm", "heart rate monitor"],
  padel: ["padel racket", "padel racquet", "racket sports", "padel shoes", "padel balls"],
  "padel racket": [
    "padel racquet",
    "padel bat",
    "padel racket finder",
    "best padel racket",
  ],
  "padel racquet": ["padel racket", "padel bat"],
  "padel bat": ["padel racket", "padel racquet"],
  "padel racket finder": ["padel racket", "find padel racket"],
  "best padel racket": ["padel rackets", "padel racket finder"],
  "control padel racket": ["padel control", "padel racket"],
  "power padel racket": ["padel power", "padel racket"],
  "padel shoes": ["padel shoe", "court shoes padel", "best padel shoes"],
  "padel shoe": ["padel shoes"],
  "padel balls": [
    "padel ball",
    "fast padel balls",
    "competition padel balls",
    "best padel balls",
  ],
  "padel ball": ["padel balls"],
  "fast padel balls": ["padel balls", "speed padel balls", "wilson premier speed"],
  "competition padel balls": ["padel balls", "head padel pro"],
  "training padel balls": ["padel balls", "tecnifibre padel team"],
  "padel bags": ["padel bag", "paletero", "padel backpack", "at10 bag"],
  "padel bag": ["padel bags", "paletero"],
  "at10 bag": ["nox at10 team bag", "padel bags", "at10"],
  "padel backpack": ["padel bags", "tour endurance backpack"],
  paletero: ["padel bags", "padel bag"],
  "padel grips": ["overgrip", "padel overgrip", "hesacore"],
  overgrip: ["padel overgrip", "padel grips"],
  "padel overgrip": ["overgrip", "wilson overgrip", "bullpadel hac"],
  "overgrip sweaty hands": ["bullpadel hac", "padel overgrip", "absorption overgrip"],
  "sweaty hands overgrip": ["overgrip sweaty hands", "bullpadel hac"],
  "padel ball pressurizer": [
    "pascal box",
    "head x3 pressurizer",
    "ball pressurizer",
    "padel accessories",
  ],
  "ball pressurizer": ["padel ball pressurizer", "pascal box"],
  "bullpadel protector": [
    "bullpadel frame protector",
    "frame protector",
    "padel accessories",
  ],
  "frame protector": ["bullpadel protector", "nox frame protector"],
  at10: ["nox at10", "at10 genius", "at10 bag", "padel racket"],
  "at10 genius": ["nox at10", "at10"],
  ml10: ["nox ml10", "ml10 pro cup", "padel racket"],
  vertex: ["bullpadel vertex", "vertex 05", "padel racket"],
  hack: ["bullpadel hack", "hack 04", "padel racket"],
  coello: ["head coello", "coello pro", "padel racket"],
  bela: ["wilson bela", "bela pro", "padel racket"],
  metalbone: ["adidas metalbone", "padel racket"],
  "padel accessories": ["frame protector", "pressurizer", "padel ball pressurizer"],
  tennis: ["tennis racket", "tennis racquet", "racket sports"],
  "tennis racket": ["tennis racquet", "tennis racket finder", "best tennis racket"],
  "tennis racquet": ["tennis racket"],
  "tennis racket finder": ["tennis racket", "find tennis racket"],
  pickleball: ["pickleball paddle", "pickleball bat"],
  "pickleball paddle": ["pickleball bat", "paddle"],
  "pickleball bat": ["pickleball paddle"],
  badminton: ["badminton racket", "badminton racquet"],
  "badminton racket": ["badminton racquet"],
  squash: ["squash racket", "squash racquet"],
  "squash racket": ["squash racquet"],
  racquet: ["racket"],
  racket: ["racquet"],
  marathon: ["racing", "race"],
  tempo: ["speed", "workout"],
  hyrox: [
    "hyrox shoes",
    "hyrox race shoes",
    "hyrox training",
    "fitness hyrox",
  ],
  "hyrox shoes": [
    "hyrox shoe finder",
    "best hyrox shoes",
    "hyrox race shoes",
    "hyrox training shoes",
  ],
  "hyrox race shoes": ["hyrox shoes", "hyrox shoe finder", "best hyrox shoes"],
  "hyrox training shoes": ["hyrox shoes", "hyrox shoe finder"],
  "hyrox shoe finder": ["hyrox shoes", "best hyrox shoes"],
  "hyrox watch": ["gps watch", "forerunner", "fitness watch"],
  "hyrox heart rate": ["heart rate monitor", "chest strap", "hrm"],
  "hyrox heart rate monitor": ["heart rate monitor", "chest strap", "hrm"],
  "hyrox sled": ["sled", "how to choose a hyrox training sled"],
  "hyrox wall ball": ["wall ball", "functional fitness"],
  "hyrox sandbag": ["sandbag", "functional fitness"],
  "hyrox home gym": ["home gym builder", "hyrox home training"],
  "hyrox race time": ["hyrox race time calculator", "race plan"],
  "hyrox pace": ["hyrox race time calculator", "running pace calculator"],
  "hyrox race kit": ["hyrox race kit builder"],
  rack: ["power rack", "squat rack", "power cage"],
  "power rack": ["squat rack", "power cage", "power-rack-finder"],
  "squat rack": ["power rack", "power cage"],
  "power cage": ["power rack", "squat rack"],
  "home gym rack": ["power rack", "power-rack-finder", "home gym builder"],
  rower: ["rowing machine", "rowerg", "concept2"],
  rowerg: ["rowing machine", "concept2 rowerg", "rower"],
  "rowing machine": ["rower", "rowerg", "concept2"],
  airbike: ["air bike", "fan bike", "assault bike", "echo bike"],
  "air bike": ["airbike", "fan bike", "assault bike"],
  "fan bike": ["air bike", "airbike", "assault bike"],
  "assault bike": ["air bike", "echo bike", "fan bike"],
  "ski erg": ["skierg", "concept2 skierg"],
  skierg: ["ski erg", "concept2 skierg"],
  pullup: ["pull-up", "pull up bar", "pull-up bar"],
  "pull-up": ["pullup", "pull up bar"],
  "pull up bar": ["pull-up bar", "pullup"],
  "adjustable dumbbell": ["adjustable dumbbells", "dumbbells"],
  dumbbell: ["adjustable dumbbells", "dumbbells"],
  dumbbells: ["adjustable dumbbells", "adjustable dumbbell"],
  treadmill: ["treadmill finder", "home treadmill"],
  "massage gun": ["theragun", "recovery", "percussion"],
  "hydration vest": [
    "running packs",
    "adv skin",
    "trail hydration vest",
    "hydration",
  ],
  "running belt": ["belts", "flipbelt", "spibelt", "race belt"],
  "running jacket": ["jackets", "running clothing", "rain jacket"],
  "women's running jacket": ["running jacket", "jackets", "running clothing"],
  "womens running jacket": ["running jacket", "jackets", "running clothing"],
  "women's running shoes": [
    "running shoes",
    "women's trainers",
    "womens running shoes",
  ],
  "womens running shoes": [
    "running shoes",
    "women's running shoes",
    "women's trainers",
  ],
  "women's trainers": ["women's running shoes", "running shoes"],
  "mens running shoes": ["men's running shoes", "running shoes"],
  "men's running shoes": ["running shoes", "mens running shoes"],
  "energy gel": ["gels", "nutrition", "race fuel", "maurten", "gu"],
  gel: ["energy gel", "gels", "nutrition", "race fuel"],
  gels: ["energy gel", "nutrition", "race fuel"],
  "foam roller": ["recovery", "blackroll", "triggerpoint", "massage"],
  "trail headlamp": ["headlamp", "running lights", "petzl", "biolite"],
  headlamp: ["running lights", "trail headlamp", "petzl"],
  "running sunglasses": ["sunglasses", "oakley", "julbo"],
  "soft flask": ["soft flasks", "hydrapak", "hydration"],
  "soft flasks": ["soft flask", "hydrapak", "hydration"],
  handheld: ["handhelds", "hydration", "skyflask"],
  "chest strap": ["hrm", "heart rate monitor", "heart rate strap"],
};

export function expandQueryWithSynonyms(query: string): string[] {
  const normalized = query.trim().toLowerCase().replace(/\s+/g, " ");
  if (!normalized) return [];

  const expansions = new Set<string>([normalized]);
  expansions.add(normalized);

  if (SEARCH_SYNONYMS[normalized]) {
    for (const syn of SEARCH_SYNONYMS[normalized]) expansions.add(syn);
  }

  const tokens = normalized.split(" ");
  for (const token of tokens) {
    if (SEARCH_SYNONYMS[token]) {
      for (const syn of SEARCH_SYNONYMS[token]) expansions.add(syn);
    }
  }

  return [...expansions];
}
