import type { ExplainerBlock } from "@/lib/guides/explainer-blocks";
import { tocFromExplainer } from "@/lib/guides/explainer-blocks";
import type { LongFormGuideConfig } from "@/lib/guides/long-form-config";

const CARBON_VS_NYLON_BLOCKS: ExplainerBlock[] = [
  {
    id: "quick-definition",
    type: "prose",
    title: "Carbon vs nylon plates: the short answer",
    intro: "Both plates shape how a shoe bends. They usually serve different jobs.",
    paragraphs: [
      "A carbon-plated running shoe typically uses a stiff carbon-fibre plate with responsive foam and aggressive geometry to make fast running more efficient. The complete system matters: the plate alone does not create the result.",
      "A nylon-plated shoe usually bends more readily and is commonly tuned for workouts, uptempo long runs and mixed training. It can deliver structure and a rolling transition without the same stiffness, price or race-day focus as a carbon super shoe.",
      "These are tendencies, not rules. Plate material does not tell you the whole ride. Foam, plate shape, placement, rocker, stack, outsole and fit can make two shoes with the same plate material feel very different.",
    ],
  },
  {
    id: "purpose",
    type: "factor-cards",
    title: "What a plate actually does",
    intro: "Treat the plate as one component in a tuned midsole system.",
    cards: [
      {
        id: "stiffness",
        title: "Controls bending",
        whatItIs: "A shaped layer embedded in or between midsole foam.",
        howItChanges: "Raises longitudinal stiffness and changes where the shoe flexes.",
        whatYouNotice: "A more structured toe-off than an unplated, flexible trainer.",
      },
      {
        id: "geometry",
        title: "Works with the rocker",
        whatItIs: "The plate follows a brand-specific curve inside the shoe.",
        howItChanges: "Helps the foam and rocker move the shoe through transition as a system.",
        whatYouNotice: "A rolling or tipping sensation that becomes more obvious at pace.",
      },
      {
        id: "foam",
        title: "Stabilises soft foam",
        whatItIs: "A rigid or semi-rigid element surrounded by compliant foam.",
        howItChanges: "Adds structure so tall, soft foam deforms in a more controlled way.",
        whatYouNotice: "A platform that can feel both cushioned and directed.",
      },
      {
        id: "load",
        title: "Redistributes load",
        whatItIs: "A plate spanning a meaningful portion of the shoe.",
        howItChanges: "Changes leverage and how forces move through the platform.",
        whatYouNotice: "Less local flex, but potentially more demand elsewhere if the setup feels unnatural.",
      },
    ],
  },
  {
    id: "comparison",
    type: "comparison-table",
    title: "Carbon and nylon plates compared",
    columns: ["Carbon plate", "Nylon plate"],
    rows: [
      { label: "Typical stiffness", values: ["Higher", "Moderate / more flexible"] },
      { label: "Typical role", values: ["Racing and fastest sessions", "Tempo, workouts and versatile training"] },
      { label: "Ride tendency", values: ["More rigid and aggressive", "More forgiving and familiar"] },
      { label: "Foam pairing", values: ["Often premium, highly responsive foam", "Varies from premium to durable training foam"] },
      { label: "Durability priority", values: ["Race performance first", "Training repeatability more often prioritised"] },
      { label: "Price tendency", values: ["Usually higher", "Often lower"] },
    ],
    footnote: "Model design overrides category averages. Compare the complete shoe, not the plate label.",
  },
  {
    id: "energy",
    type: "prose",
    title: "Stiffness, energy return and running economy",
    paragraphs: [
      "A plate does not generate free energy. Midsole foam stores and returns part of the energy used to compress it; the plate and geometry influence how the platform deforms and how quickly you move through toe-off.",
      "Research on advanced racing footwear evaluates complete shoe systems, not isolated plate materials. Benefits vary by runner, pace, mechanics, shoe fit and model. A carbon shoe that is fast for one runner can feel unstable, harsh or awkward for another.",
      "Nylon is not simply a cheaper carbon substitute. Greater flexibility can be the design goal: enough structure for a responsive transition, with a ride that is easier to train in regularly.",
    ],
  },
  {
    id: "race-vs-training",
    type: "use-case-cards",
    title: "Match plate type to the session",
    cards: [
      { id: "race", title: "Goal race", description: "Carbon is the usual performance-first choice when the shoe is comfortable, legal for the event and suited to your pace.", href: "/best/race-shoes" },
      { id: "tempo", title: "Tempo / threshold", description: "Nylon-plated trainers often balance speed, control and durability for repeat workouts.", href: "/best/tempo-running-shoes" },
      { id: "intervals", title: "Intervals", description: "Either can work. Use carbon for race-specific feel; use nylon when you want a less aggressive training tool." },
      { id: "long", title: "Faster long run", description: "A plated trainer can hold steady or progression pace without spending every mile in a race shoe.", href: "/best/running-shoes-long-runs" },
      { id: "easy", title: "Easy / recovery", description: "Most runners are better served by a comfortable daily trainer; a plate is not required for easy mileage.", href: "/best/daily-trainers" },
    ],
  },
  {
    id: "who-benefits",
    type: "prose",
    title: "Who benefits from a plated shoe?",
    paragraphs: [
      "Runners chasing a race result are the clearest audience for carbon racing shoes. The useful question is not whether carbon works in general, but whether a specific shoe improves your pace-to-effort relationship without compromising fit, control or comfort.",
      "Nylon-plated trainers suit runners who want a faster-workout shoe that remains usable across more sessions. They are also a sensible bridge for runners who find full carbon racers too rigid or unstable.",
      "Beginners do not need to earn the right to wear plated shoes, and faster runners do not need them for every run. Try the shoe at intended pace before race day and judge the complete experience.",
    ],
  },
  {
    id: "guardrail",
    type: "callout",
    title: "A plate is not an injury treatment",
    tone: "caution",
    body: "Do not buy carbon or nylon plates to diagnose, prevent or treat an injury. Stiffness changes how the shoe loads and moves; it is not automatically safer. If running is painful or you have a clinical concern, seek qualified medical advice.",
  },
  {
    id: "tradeoffs",
    type: "pros-tradeoffs",
    title: "What plated shoes add — and what they cost",
    gains: [
      "A structured, directed transition at faster paces",
      "Potential running-economy benefit from the complete carbon race-shoe system",
      "Soft foam with added bending control",
      "Clear separation between workout/race and easy-day tools",
    ],
    giveUps: [
      "Higher price, especially for carbon racers",
      "Less flexibility and ground feel",
      "Possible instability or awkwardness at slower paces",
      "Performance foams and minimal outsoles may prioritise speed over lifespan",
    ],
    footnote: "The size of every gain or trade-off depends on the runner and the specific model.",
  },
  {
    id: "nylon-alternatives",
    type: "prose",
    title: "Why choose nylon — or no plate at all?",
    paragraphs: [
      "Choose nylon when the job is repeatable faster training rather than maximum race-day efficiency. A good nylon trainer can cover tempo runs, intervals and faster long runs while feeling less demanding during warm-ups and cooldowns.",
      "Choose an unplated shoe when flexibility, simplicity, lower cost or easy-pace comfort matters more. Modern foams and rockers can produce a lively ride without a plate.",
      "A practical two-shoe setup is an unplated daily trainer plus a nylon workout shoe. Add a carbon racer only when racing goals and budget justify a specialised third tool.",
    ],
  },
  {
    id: "misconceptions",
    type: "mistakes",
    title: "Common plate misconceptions",
    mistakes: [
      { id: "spring", title: "The plate is a spring", body: "The foam, plate and geometry work together. Plate material alone does not explain energy return." },
      { id: "always-faster", title: "Carbon is faster for everyone", body: "Average benefits do not guarantee a benefit in a specific model for a specific runner." },
      { id: "daily", title: "Carbon should replace a daily trainer", body: "Race geometry can feel awkward at easy pace and is unnecessary for most routine mileage." },
      { id: "nylon", title: "Nylon means low performance", body: "Nylon is often deliberately chosen for a more flexible, training-friendly tune." },
      { id: "injury", title: "A plate prevents injury", body: "Footwear cannot diagnose or guarantee prevention. Pain requires appropriate assessment." },
      { id: "material", title: "All carbon shoes feel alike", body: "Foam, plate shape, rocker, width and fit create major differences." },
    ],
  },
  {
    id: "decision",
    type: "decision-flow",
    title: "Choose the right plate strategy",
    steps: [
      { id: "job", title: "Define the job", body: "Race-day maximum, repeatable workouts, or general daily mileage?" },
      { id: "pace", title: "Test at intended pace", body: "A race shoe should feel controlled at race pace; a workout shoe must also handle transitions between reps." },
      { id: "fit", title: "Check fit and stability", body: "Reject heel slip, toe pressure or a platform you cannot control, regardless of plate material." },
      { id: "feel", title: "Choose stiffness by feel", body: "Prefer carbon for an aggressive race setup, nylon for more flex, or unplated for a natural transition." },
      { id: "budget", title: "Price the role", body: "Do not pay a race-shoe premium for a job your daily or tempo trainer already covers." },
      { id: "trial", title: "Trial before race day", body: "Use at least one representative session to confirm comfort and pacing." },
    ],
    branches: {
      question: "What is the primary job?",
      options: [
        { label: "Goal racing", result: "Start with carbon racers, then filter hard on fit, control and event legality." },
        { label: "Weekly speed work", result: "Start with nylon-plated or durable plated tempo trainers." },
        { label: "Mostly easy miles", result: "Start with an unplated daily trainer; a plate is optional." },
      ],
    },
  },
  {
    id: "examples",
    type: "product-examples",
    title: "Real-world plate examples",
    disclaimer: "Examples illustrate distinct roles, not a universal ranking. Product construction and availability can change by generation.",
    examples: [
      {
        productId: "prod-vaporfly-4",
        approachLabel: "Carbon race shoe",
        whyIllustrates: "A specialised, lightweight carbon-plated road racer built around fast race-day use.",
        bestFor: ["Road racing", "Race-pace sessions", "Runners wanting aggressive geometry"],
        tradeoff: "Specialised ride, premium price and less everyday versatility.",
      },
      {
        productId: "prod-endorphin-speed-5",
        approachLabel: "Nylon-plated tempo trainer",
        whyIllustrates: "Shows why nylon remains relevant: structured speed with a more training-friendly role.",
        bestFor: ["Tempo runs", "Intervals", "Faster long runs"],
        tradeoff: "Not the same maximum-performance proposition as a dedicated carbon racer.",
      },
      {
        productId: "prod-novablast-6",
        approachLabel: "Unplated versatile trainer",
        whyIllustrates: "Demonstrates that responsive foam and geometry can create an energetic daily ride without a plate.",
        bestFor: ["Daily mileage", "Steady running", "One-shoe versatility"],
        tradeoff: "Less specialised for all-out racing than a carbon platform.",
      },
    ],
  },
  {
    id: "product-comparison",
    type: "product-comparison",
    title: "Compare race, tempo and daily approaches",
    productIds: ["prod-vaporfly-4", "prod-endorphin-speed-5", "prod-novablast-6"],
    bestGuideHref: "/best/tempo-running-shoes",
    bestGuideLabel: "Best Tempo Running Shoes →",
    compareHref: "/compare?category=running-shoes&products=nike-vaporfly-4,saucony-endorphin-speed-5,asics-novablast-6",
  },
  {
    id: "finder-cta",
    type: "cta",
    title: "Need a shoe for your actual training?",
    variant: "finder",
    body: "Use the Running Shoe Finder to match session role, fit, cushioning and budget. Plate material is one filter, not the decision.",
    ctaLabel: "Find my running shoes →",
    href: "/tools/running-shoe-finder",
  },
  {
    id: "buying-checklist",
    type: "prose",
    title: "The plate buying checklist",
    paragraphs: [
      "State the role in one sentence. Set a budget. Compare full-shoe weight, foam, geometry, outsole, fit and stability — then consider plate material.",
      "For racing, confirm event rules and practise in the shoe. For training, ask whether it remains comfortable through warm-up, reps and cooldown. If the answers are unclear, the shoe is not decision-ready.",
    ],
  },
  {
    id: "best-cta",
    type: "cta",
    title: "Ready for current recommendations?",
    variant: "best-guide",
    body: "Compare dedicated race shoes for maximum performance or tempo shoes for repeatable faster training.",
    ctaLabel: "See the best race shoes →",
    href: "/best/race-shoes",
  },
];

export const carbonVsNylonPlatesConfig: LongFormGuideConfig = {
  guideSlug: "carbon-vs-nylon-plates",
  layout: "explainer",
  eyebrow: "Explainer",
  displayTitle: "Carbon vs Nylon Plates in Running Shoes",
  deck: "What plate stiffness changes, why carbon dominates race shoes, where nylon makes more sense, and how to choose without buying the marketing shorthand.",
  heroImageSrc: "/images/running/products/vaporfly-4-hero.jpg",
  heroImageAlt: "Nike Vaporfly 4 carbon-plated racing shoe",
  finder: {
    toolSlug: "running-shoe-finder",
    title: "Match the shoe to the session",
    description: "Build a shortlist from training role, fit, cushion and budget — not plate material alone.",
    ctaLabel: "Find my running shoes →",
  },
  decisionLinks: [
    { label: "Best race shoes →", href: "/best/race-shoes" },
    { label: "Best tempo shoes →", href: "/best/tempo-running-shoes" },
    { label: "Best running shoes →", href: "/best/running-shoes" },
  ],
  glossaryHref: "/guides/running-shoe-terminology",
  glossaryTerms: [
    { id: "carbon-plate", term: "Carbon plate", definition: "A stiff carbon-fibre element used to control bending and shape transition.", icon: "layers" },
    { id: "nylon-plate", term: "Nylon plate", definition: "A typically more flexible plate often tuned for training and tempo use.", icon: "layers" },
    { id: "stiffness", term: "Longitudinal stiffness", definition: "Resistance to bending from heel to toe.", icon: "gauge" },
    { id: "rocker", term: "Rocker", definition: "Curved sole geometry designed to roll the shoe through transition.", icon: "circle" },
    { id: "energy-return", term: "Energy return", definition: "The share of deformation energy returned by the shoe materials.", icon: "scale" },
    { id: "stack", term: "Stack height", definition: "The amount of material between foot and ground.", icon: "ruler" },
  ],
  needs: [],
  factors: [],
  fit: [],
  toc: tocFromExplainer([...CARBON_VS_NYLON_BLOCKS]),
  productExampleRoles: [
    { productId: "prod-vaporfly-4", roleLabel: "Carbon race shoe" },
    { productId: "prod-endorphin-speed-5", roleLabel: "Nylon tempo trainer" },
    { productId: "prod-novablast-6", roleLabel: "Unplated daily trainer" },
  ],
  productRailTitle: "Compare plated and unplated approaches",
  productRailBrowseHref: "/running/shoes",
  productRailBrowseLabel: "Browse running shoes →",
  explainer: {
    layout: "explainer",
    quickAnswerBullets: [
      "Carbon plates are typically stiffer and paired with premium foam for race-day performance.",
      "Nylon plates usually flex more, making them practical for tempo runs and repeat workouts.",
      "The plate does not create free energy; foam, geometry and plate work as one system.",
      "Plate material alone cannot predict whether a shoe will be faster, comfortable or stable for you.",
      "Most easy mileage does not require a plated shoe.",
    ],
    medicalNote: "Kitletics explains footwear design, not injury treatment. A plated shoe does not diagnose, prevent or cure injury. Seek qualified clinical advice for pain or medical concerns.",
    methodologyNote: "This guide separates established mechanical principles from category tendencies. Product roles use current Kitletics catalog data and manufacturer construction details; prices and comparison specifications render from live product data.",
    blocks: [...CARBON_VS_NYLON_BLOCKS],
  },
};
