/**
 * Compact explainer plans for the padel equipment knowledge center.
 * Generated by scripts/tmp/generate-padel-knowledge-center.mjs
 */

import type { FAQ } from "@/domain/editorial/types";
import {
  buildExplainerFromPlan,
  type CompactExplainerPlan,
} from "@/lib/guides/build-explainer-from-plan";
import { resolveHeroFromProductIds } from "@/lib/guides/guide-product-hero";
import { PADEL_KNOWLEDGE_UNIQUE } from "@/lib/guides/explainers/padel-knowledge-unique";

type PadelKnowledgeSpec = {
  slug: string;
  title: string;
  subject: string;
  outcome: string;
  factors: [string, string, string, string, ...string[]];
  comparison: [string, string];
  products: [string, string, string, ...string[]];
  tool?: "padel-racket-finder";
  bestHref: string;
  browseHref: string;
};

/** Dedicated editorial heroes where we have authentic padel guide photography. */
const PADEL_GUIDE_HEROES: Record<string, { src: string; alt: string }> = {
  "how-to-choose-a-padel-racket": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Padel racket selection — shapes and frames for choosing a racket",
  },
  "padel-racket-shapes-explained": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Padel racket shapes for round, teardrop and diamond buying decisions",
  },
  "round-vs-teardrop-vs-diamond-padel-rackets": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Comparing round, teardrop and diamond padel racket silhouettes",
  },
  "padel-racket-balance-explained": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Padel rackets illustrating balance and handling differences",
  },
  "padel-racket-weight-explained": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Padel rackets for comparing published weight bands",
  },
  "how-to-choose-padel-shoes": {
    src: "/images/padel/guides/choose-shoes.jpg",
    alt: "Padel court shoes for grip and lateral stability decisions",
  },
  "padel-vs-tennis-shoes": {
    src: "/images/padel/guides/choose-shoes.jpg",
    alt: "Court shoes compared for padel vs tennis use",
  },
  "padel-shoe-outsoles-explained": {
    src: "/images/padel/guides/choose-shoes.jpg",
    alt: "Padel shoe outsoles for clay and hard-court grip",
  },
  "padel-grips-overgrips-explained": {
    src: "/images/padel/guides/grips.jpg",
    alt: "Padel grips and overgrips for tack versus absorption",
  },
  "padel-grip-vs-overgrip": {
    src: "/images/padel/guides/grips.jpg",
    alt: "Base grip versus overgrip layers on a padel handle",
  },
  "how-often-should-you-replace-a-padel-overgrip": {
    src: "/images/padel/guides/grips.jpg",
    alt: "Padel overgrips showing when to replace a worn wrap",
  },
  "beginner-padel-gear-guide": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Beginner padel gear — forgiving racket and court kit",
  },
  "complete-padel-gear-checklist": {
    src: "/images/padel/guides/choose-racket.jpg",
    alt: "Complete padel gear checklist — racket, shoes, bag and consumables",
  },
};

const PADEL_KNOWLEDGE_SPECS: PadelKnowledgeSpec[] = [
  {
    slug: "how-to-choose-a-padel-racket",
    title: "How to Choose a Padel Racket",
    subject: "a padel racket",
    outcome: "match forgiveness, handling and power to your current level and playing style",
    factors: ["Player level","Shape and sweet spot","Weight and balance","Core and face feel","Playing style","Budget"],
    comparison: ["Forgiving control frame","Power-focused frame"],
    products: ["prod-bullpadel-indiga-ctr","prod-nox-ml10-pro-cup","prod-bullpadel-vertex-05","prod-bullpadel-hack-04"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "padel-racket-shapes-explained",
    title: "Padel Racket Shapes Explained",
    subject: "padel racket shapes",
    outcome: "map round, teardrop and diamond silhouettes to sweet-spot and play roles without treating shape as the whole decision",
    factors: ["Sweet-spot location","Balance tendency","Forgiveness on mishits","Attacking reward","Your preparation speed"],
    comparison: ["Round control shape","Diamond attack shape"],
    products: ["prod-bullpadel-indiga-ctr","prod-bullpadel-vertex-05-hybrid","prod-bullpadel-hack-04","prod-nox-at10-12k-2026"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "round-vs-teardrop-vs-diamond-padel-rackets",
    title: "Round vs Teardrop vs Diamond Padel Rackets",
    subject: "round vs teardrop vs diamond padel rackets",
    outcome: "pick the silhouette family that matches your mishit rate and finishing ability",
    factors: ["Mishit rate","Finishing need","Preparation timing","Core softness","Balance confirmation"],
    comparison: ["Round / soft control","Diamond attack"],
    products: ["prod-bullpadel-indiga-ctr","prod-nox-at10-12k-2026","prod-bullpadel-hack-04"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-all-round",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "padel-racket-balance-explained",
    title: "Padel Racket Balance Explained",
    subject: "padel racket balance",
    outcome: "use low vs high balance as a handling filter instead of inferring it from shape marketing alone",
    factors: ["Balance point","Swing preparation","Stability on hard contact","Arm fatigue","Shape vs measured balance"],
    comparison: ["Low / mid-low balance","Mid-high / high balance"],
    products: ["prod-bullpadel-indiga-ctr","prod-head-extreme-motion-2026","prod-bullpadel-hack-04","prod-adidas-metalbone-3-5-2026"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-maneuverability",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "padel-racket-weight-explained",
    title: "Padel Racket Weight Explained",
    subject: "padel racket weight",
    outcome: "choose a wearable published weight range before comparing carbon marketing",
    factors: ["Published weight range","Balance interaction","Session length","Shoulder/elbow comfort","Light vs stable preference"],
    comparison: ["Lighter handling frame","Heavier stable frame"],
    products: ["prod-bullpadel-ionic-light","prod-head-extreme-motion-2026","prod-bullpadel-vertex-05","prod-adidas-metalbone-3-5-2026"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-lightweight",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "padel-racket-materials-explained",
    title: "Padel Racket Materials Explained",
    subject: "padel racket materials",
    outcome: "read face and frame materials as feel inputs rather than a prestige ladder",
    factors: ["Face material","Frame construction","Core pairing","Durability expectations","Marketing weave claims"],
    comparison: ["Accessible glass face","Stiffer carbon face"],
    products: ["prod-kuikma-pr-comfort-soft","prod-bullpadel-hack-04-comfort","prod-nox-at10-12k-2026","prod-bullpadel-hack-04"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "carbon-vs-fiberglass-padel-rackets",
    title: "Carbon vs Fiberglass Padel Rackets",
    subject: "carbon vs fiberglass padel rackets",
    outcome: "choose face fibre for feel and forgiveness goals instead of prestige",
    factors: ["Desired face feel","Mishit kindness","Precision preference","Core pairing","Budget"],
    comparison: ["Fiberglass-accessible face","Carbon performance face"],
    products: ["prod-kuikma-pr-comfort-soft","prod-nox-equation-soft-2026","prod-nox-at10-12k-2026","prod-babolat-technical-viper"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-comfort",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "padel-racket-cores-eva-foam-explained",
    title: "Padel Racket Cores / EVA Foam Explained",
    subject: "padel racket cores and EVA foam",
    outcome: "treat soft vs hard EVA (and multi-density cores) as feel and forgiveness filters",
    factors: ["Core hardness","Ball exit feel","Arm comfort","Temperature sensitivity","Marketing core names"],
    comparison: ["Soft EVA package","Harder EVA package"],
    products: ["prod-nox-equation-soft-2026","prod-kuikma-pr-comfort-soft","prod-bullpadel-vertex-05","prod-bullpadel-hack-04"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-comfort",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "soft-vs-hard-padel-rackets",
    title: "Soft vs Hard Padel Rackets",
    subject: "soft vs hard padel rackets",
    outcome: "choose soft packages for forgiveness and hard packages for crisp exit when contact quality supports it",
    factors: ["Contact consistency","Arm comfort","Desired ball exit","Playing style","Shape pairing"],
    comparison: ["Soft forgiving package","Hard crisp package"],
    products: ["prod-nox-equation-soft-2026","prod-kuikma-pr-comfort-soft","prod-bullpadel-hack-04","prod-adidas-metalbone-3-5-2026"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-comfort",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "how-padel-racket-sweet-spots-work",
    title: "How Padel Racket Sweet Spots Work",
    subject: "padel racket sweet spots",
    outcome: "interpret sweet-spot claims as forgiveness geometry rather than guaranteed power maps",
    factors: ["Sweet-spot size claims","Sweet-spot height","Shape correlation","Evidence quality","Your mishit pattern"],
    comparison: ["Centred forgiving sweet zone","Higher attacking sweet zone"],
    products: ["prod-bullpadel-indiga-ctr","prod-nox-ml10-pro-cup","prod-bullpadel-vertex-05","prod-bullpadel-hack-04"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-control",
    browseHref: "/padel/gear?category=padel-rackets",
  },
  {
    slug: "how-to-choose-padel-shoes",
    title: "How to Choose Padel Shoes",
    subject: "padel shoes",
    outcome: "get predictable court grip and lateral support without sacrificing lockdown",
    factors: ["Outsole and court surface","Lateral stability","Fit and lockdown","Cushion and durability","Session length"],
    comparison: ["Stable court shoe","Lighter speed shoe"],
    products: ["prod-asics-gel-resolution-padel","prod-adidas-courtstabil","prod-babolat-jet-premura","prod-joma-t-slam"],
    
    bestHref: "/best/padel-shoes",
    browseHref: "/padel/gear?category=padel-shoes",
  },
  {
    slug: "padel-vs-tennis-shoes",
    title: "Padel vs Tennis Shoes",
    subject: "padel vs tennis shoes",
    outcome: "decide when a tennis court shoe is enough and when a padel-specific model is the better tool",
    factors: ["Court surface","Movement pattern","Outsole pattern","Brand padel line","Fit"],
    comparison: ["Padel-specific court shoe","Tennis crossover shoe"],
    products: ["prod-asics-gel-resolution-padel","prod-head-revolt-pro-court","prod-adidas-courtstabil","prod-babolat-jet-premura"],
    
    bestHref: "/best/padel-shoes",
    browseHref: "/padel/gear?category=padel-shoes",
  },
  {
    slug: "padel-shoe-outsoles-explained",
    title: "Padel Shoe Outsoles Explained",
    subject: "padel shoe outsoles",
    outcome: "match outsole pattern and compound to your club’s surface instead of buying by upper colour",
    factors: ["Surface type","Herringbone vs omni","Dust/sand behaviour","Durability","Indoor vs outdoor"],
    comparison: ["High-grip sand-ready outsole","Faster connected outsole"],
    products: ["prod-adidas-courtstabil","prod-asics-gel-resolution-padel","prod-babolat-jet-premura","prod-joma-t-slam"],
    
    bestHref: "/best/padel-shoes",
    browseHref: "/padel/gear?category=padel-shoes",
  },
  {
    slug: "how-long-do-padel-balls-last",
    title: "How Long Do Padel Balls Last?",
    subject: "padel ball lifespan",
    outcome: "set realistic session expectations for pressurized cans instead of guessing from tennis habits alone",
    factors: ["Pressure loss","Felt wear","Court abrasion","Temperature/humidity","Match vs training use"],
    comparison: ["Fresh pressurized can","Tired training ball"],
    products: ["prod-head-padel-pro-s","prod-kuikma-pb-speed","prod-head-padel-pro-s"],
    
    bestHref: "/padel/gear?category=padel-balls",
    browseHref: "/padel/gear?category=padel-balls",
  },
  {
    slug: "how-to-choose-padel-balls",
    title: "How to Choose Padel Balls",
    subject: "padel balls",
    outcome: "pick a pressurized competition can that matches court speed preference with honest catalog limits",
    factors: ["Speed/control preference","Official vs training","Court conditions","Pack format","Freshness"],
    comparison: ["Faster competition can","Control-oriented competition can"],
    products: ["prod-head-padel-pro-s","prod-kuikma-pb-speed","prod-head-padel-pro-s"],
    
    bestHref: "/padel/gear?category=padel-balls",
    browseHref: "/padel/gear?category=padel-balls",
  },
  {
    slug: "how-to-choose-a-padel-bag",
    title: "How to Choose a Padel Bag",
    subject: "a padel bag",
    outcome: "match paletero volume, thermo needs and commute style to how you actually travel to court",
    factors: ["Form factor","Volume / racket count","Thermo compartment","Shoe pocket","Carry comfort"],
    comparison: ["Club paletero","Tournament volume bag"],
    products: ["prod-nox-at10-team-bag","prod-babolat-rh-pro-padel","prod-nox-at10-team-bag"],
    
    bestHref: "/best/padel-bags",
    browseHref: "/padel/gear?category=padel-bags",
  },
  {
    slug: "padel-grips-overgrips-explained",
    title: "Padel Grips & Overgrips Explained",
    subject: "padel grips and overgrips",
    outcome: "set a comfortable handle diameter while maintaining tack and moisture control",
    factors: ["Base-grip condition","Handle thickness","Tack and absorption","Replacement frequency"],
    comparison: ["Replacement grip","Overgrip"],
    products: ["prod-wilson-overgrip","prod-bullpadel-gb1200","prod-wilson-overgrip"],
    
    bestHref: "/best/padel-overgrips",
    browseHref: "/padel/gear?category=padel-grips",
  },
  {
    slug: "padel-grip-vs-overgrip",
    title: "Padel Grip vs Overgrip",
    subject: "padel grip vs overgrip",
    outcome: "know when to rebuild the base grip versus refreshing an overgrip",
    factors: ["Handle foundation","Diameter change needed","Tack vs absorption","Cost per week"],
    comparison: ["Base replacement grip","Overgrip refresh"],
    products: ["prod-wilson-overgrip","prod-bullpadel-gb1200","prod-wilson-overgrip"],
    
    bestHref: "/best/padel-overgrips",
    browseHref: "/padel/gear?category=padel-grips",
  },
  {
    slug: "how-often-should-you-replace-a-padel-overgrip",
    title: "How Often Should You Replace a Padel Overgrip?",
    subject: "padel overgrip replacement frequency",
    outcome: "replace overgrips based on tack and sweat failure, not an arbitrary calendar myth",
    factors: ["Sweat rate","Match length","Climate","Overgrip type","Hygiene"],
    comparison: ["Tack-first overgrip","Absorption-first overgrip"],
    products: ["prod-wilson-overgrip","prod-bullpadel-gb1200","prod-wilson-overgrip"],
    
    bestHref: "/best/padel-overgrips",
    browseHref: "/padel/gear?category=padel-grips",
  },
  {
    slug: "beginner-padel-gear-guide",
    title: "Beginner Padel Gear Guide",
    subject: "beginner padel gear",
    outcome: "build a forgiving first kit without copying pro diamonds",
    factors: ["Forgiving racket","Court shoes","Fresh balls","Overgrips","Optional bag"],
    comparison: ["Forgiving starter kit","Pro-copy kit"],
    products: ["prod-bullpadel-indiga-ctr","prod-adidas-courtstabil","prod-head-padel-pro-s","prod-wilson-overgrip"],
    tool: "padel-racket-finder",
    bestHref: "/best/padel-rackets-beginners",
    browseHref: "/padel/gear",
  },
  {
    slug: "complete-padel-gear-checklist",
    title: "Complete Padel Gear Checklist",
    subject: "a complete padel gear checklist",
    outcome: "verify required vs optional kit before a match or trip without overspending",
    factors: ["Required match kit","Optional extras","Travel constraints","Climate","Level"],
    comparison: ["Essential match kit","Expanded tournament kit"],
    products: ["prod-bullpadel-indiga-ctr","prod-asics-gel-resolution-padel","prod-nox-at10-team-bag","prod-wilson-overgrip"],
    
    bestHref: "/best/padel-rackets",
    browseHref: "/padel/gear",
  },
];

function makePlan(spec: PadelKnowledgeSpec): CompactExplainerPlan {
  const u = PADEL_KNOWLEDGE_UNIQUE[spec.slug];
  if (!u) throw new Error(`Missing PADEL_KNOWLEDGE_UNIQUE for ${spec.slug}`);

  const toolHref = spec.tool ? `/tools/${spec.tool}` : spec.browseHref;
  const examples = spec.products.slice(0, Math.min(4, spec.products.length)).map((productId, index) => ({
    productId,
    approachLabel: u.exampleLabels[index] ?? `Approach ${index + 1}`,
    whyIllustrates:
      u.exampleWhys[index] ??
      "A concrete catalog example for this decision — check current generation and feel before you buy.",
    bestFor: [
      spec.factors[Math.min(index, spec.factors.length - 1)]!,
      spec.comparison[index % 2]!,
    ],
    tradeoff: u.exampleTradeoffs[index] ?? "Verify fit and the complete setup.",
  }));

  const dedicatedHero = PADEL_GUIDE_HEROES[spec.slug];
  const hero = dedicatedHero
    ? {
        heroImageSrc: dedicatedHero.src,
        heroImageAlt: dedicatedHero.alt,
      }
    : resolveHeroFromProductIds(
        spec.products,
        "/images/padel/hero.jpg",
        `Padel equipment: ${spec.subject}`,
      );

  return {
    slug: spec.slug,
    displayTitle: spec.title,
    deck: u.deck,
    eyebrow: "Buying Guide",
    ...hero,    quickAnswerBullets: u.quickAnswerBullets,
    methodologyNote:
      "Needs-research guide: manufacturer specifications and normalized catalog fields establish the comparison. Unverified marketing claims are treated as claims rather than measured performance. Catalog examples are roles, not affiliate rankings.",
    finder: spec.tool
      ? {
          toolSlug: spec.tool,
          title: `Find ${spec.subject}`,
          description: "Turn hard constraints into an explainable shortlist.",
          ctaLabel: "Open the finder →",
        }
      : undefined,
    decisionLinks: [
      {
        label: spec.tool ? "Use the finder →" : "Browse current options →",
        href: toolHref,
      },
      { label: "See related recommendations →", href: spec.bestHref },
      {
        label: "Browse the padel catalog →",
        href: spec.browseHref,
      },
    ],
    definition: {
      title: u.definitionTitle,
      intro: u.definitionIntro,
      paragraphs: [...u.definitionParas],
    },
    whyItMatters: {
      title: u.whyTitle,
      paragraphs: [...u.whyParas],
    },
    factors: {
      title: `${spec.factors.length} factors that should drive the choice`,
      intro:
        "Use these as connected filters for this guide’s job — not a generic equipment checklist.",
      cards: spec.factors.map((title, index) => ({
        id: `factor-${index + 1}`,
        title,
        whatItIs: u.factorWhat[index] ?? `The ${title.toLowerCase()} requirement.`,
        howItChanges:
          u.factorChanges[index] ??
          "Your level and conditions change the useful range.",
        whatYouNotice:
          u.factorNotices[index] ??
          "Whether the choice still works late in a match.",
      })),
    },
    comparison: {
      title: `${spec.comparison[0]} vs ${spec.comparison[1]}`,
      columns: [spec.comparison[0], spec.comparison[1], "Choose based on"],
      rows: u.comparisonRows,
      footnote:
        "Category tendencies are starting points, not guarantees of individual feel.",
    },
    tradeoffs: {
      title: "What you gain — and give up",
      gains: u.tradeoffs.gains,
      giveUps: u.tradeoffs.giveUps,
      footnote: u.tradeoffs.footnote,
    },
    callouts: [
      {
        id: "marketing-limit",
        title: u.callout.title,
        body: u.callout.body,
        tone: "caution",
      },
    ],
    decision: {
      title: "Decision steps for this guide",
      steps: u.decisionSteps,
      branches: {
        question: u.branchQuestion,
        options: u.branchOptions,
      },
    },
    examples: {
      title: `${examples.length} approaches for this decision`,
      disclaimer:
        "These products demonstrate distinct roles rather than a ranking. Verify current specifications and availability.",
      items: examples,
    },
    compareProductIds: spec.products,
    bestGuideHref: spec.bestHref,
    bestGuideLabel: "See related recommendations →",
    mistakes: u.mistakes,
    ctaFinder: {
      title: spec.tool
        ? "Turn the framework into a shortlist"
        : "Compare current catalog options",
      body: spec.tool
        ? "Use hard constraints before optional features."
        : "Browse after the role is clear.",
      ctaLabel: spec.tool ? "Open the finder →" : "Browse options →",
      href: toolHref,
    },
    ctaBest: {
      title: "Want current recommendations?",
      body: "Open the related Best guide after non-negotiables are set.",
      ctaLabel: "See related recommendations →",
      href: spec.bestHref,
    },
    productExampleRoles: examples.map((example) => ({
      productId: example.productId,
      roleLabel: example.approachLabel,
    })),
    productRailTitle: `Examples for this ${spec.subject} decision`,
    productRailBrowseHref: spec.browseHref,
    productRailBrowseLabel: "Browse current options →",
  };
}

export const PADEL_KNOWLEDGE_PLANS: CompactExplainerPlan[] =
  PADEL_KNOWLEDGE_SPECS.map(makePlan);

export const padelKnowledgeConfigs = PADEL_KNOWLEDGE_PLANS.map(
  buildExplainerFromPlan,
);

export const padelKnowledgeFaqs: FAQ[] = PADEL_KNOWLEDGE_SPECS.flatMap((spec) => {
  const u = PADEL_KNOWLEDGE_UNIQUE[spec.slug]!;
  return u.faqs.map((faq, index) => ({
    id: `faq-${spec.slug}-${index + 1}`,
    question: faq.question,
    answer: faq.answer,
    sportId: "sport-padel" as const,
  }));
});
