/**
 * Road vs Trail Running Shoes — terrain-led comparison and decision guide.
 */
import type { ExplainerBlock } from "@/lib/guides/explainer-blocks";
import { tocFromExplainer } from "@/lib/guides/explainer-blocks";
import type { LongFormGuideConfig } from "@/lib/guides/long-form-config";

const ROAD_VS_TRAIL_BLOCKS: ExplainerBlock[] = [
  {
    id: "difference",
    type: "prose",
    title: "Road and trail shoes solve different contact problems",
    intro: "Choose for the surface you actually run—not the tougher-looking upper.",
    paragraphs: [
      "Road shoes are tuned for repeated contact with pavement, track, treadmill and other firm, predictable surfaces. Smooth transitions, lower weight, cushioning and road-rubber durability usually lead the design.",
      "Trail shoes are tuned for variable ground. Their outsoles use lugs and compounds intended to grip dirt, rock or mud; uppers often add security and protection; platforms balance cushioning with control on uneven terrain.",
      "Neither category is automatically better built or safer. A trail outsole can feel awkward on pavement, while a road shoe can lack traction and protection on technical ground. Match the tool to the surface and conditions.",
    ],
  },
  {
    id: "key-differences",
    type: "comparison-table",
    title: "Road vs trail running shoes at a glance",
    columns: ["Road shoe tendency", "Trail shoe tendency", "Why it matters"],
    rows: [
      { label: "Outsole", values: ["Flatter tread and strategic rubber", "Deeper, spaced lugs and off-road compounds", "Grip depends on surface, moisture and tread pattern"] },
      { label: "Stack / protection", values: ["Cushioning for firm repetitive impact", "Protection balanced with uneven-ground control", "Very tall or soft platforms can feel less precise on technical terrain"] },
      { label: "Fit", values: ["Comfort and road-speed lockdown", "Secure midfoot/heel with room for descents", "Foot movement inside the shoe is costly on cambers and downhills"] },
      { label: "Rock protection", values: ["Usually minimal", "May use a rock plate, firmer layer or protective geometry", "Helps blunt sharp trail contact but can reduce flexibility"] },
      { label: "Upper", values: ["Breathable, lightweight mesh", "Reinforcement and debris resistance", "Protection can add heat, stiffness and weight"] },
      { label: "Weight", values: ["Often lighter for comparable role", "Often heavier from rubber and protection", "Terrain confidence may be worth more than pace efficiency"] },
    ],
    footnote: "These are category tendencies. Door-to-trail, gravel and race models deliberately blur them.",
  },
  {
    id: "terrain-factors",
    type: "factor-cards",
    title: "The five factors that should drive the choice",
    cards: [
      {
        id: "outsole",
        title: "Outsole and lugs",
        whatItIs: "The rubber compound, coverage and tread projections contacting the ground.",
        howItChanges: "Flatter tread suits pavement; deeper or spaced lugs bite loose soil and clear mud.",
        whatYouNotice: "Smooth road contact versus traction and tread sensation off-road.",
      },
      {
        id: "protection",
        title: "Stack and protection",
        whatItIs: "Foam height plus rock plates, films, firmer layers and protective geometry.",
        howItChanges: "Separates the foot from impact and sharp objects while affecting ground feel.",
        whatYouNotice: "More isolation, or more precision when protection is lower.",
      },
      {
        id: "fit",
        title: "Last and lockdown",
        whatItIs: "The shoe shape plus how securely the upper holds heel and midfoot.",
        howItChanges: "Controls internal foot movement on turns, cambers, climbs and descents.",
        whatYouNotice: "Confidence without toe impact or pressure—if the shape suits your foot.",
      },
      {
        id: "upper",
        title: "Upper construction",
        whatItIs: "Mesh, overlays, toe protection, tongue and debris-management features.",
        howItChanges: "Trades breathability and low weight for security and protection.",
        whatYouNotice: "Cooler road comfort or a more armoured trail feel.",
      },
      {
        id: "weight",
        title: "Weight and agility",
        whatItIs: "The mass of foam, rubber, upper reinforcement and protective structures.",
        howItChanges: "Less material can feel quicker; more structure can improve confidence and durability.",
        whatYouNotice: "Road efficiency versus trail security, with wide variation inside each category.",
      },
    ],
  },
  {
    id: "when-road",
    type: "prose",
    title: "When a road shoe is the right choice",
    paragraphs: [
      "Use a road shoe when most of the run is pavement, track, treadmill or smooth hard-packed path in predictable conditions. Its flatter outsole presents stable contact on hard surfaces and usually rolls more smoothly than aggressive trail lugs.",
      "Road shoes also offer the widest range of specialised roles: easy, daily, tempo, max-cushion and carbon race. Pick within that category for the session rather than assuming every road model is versatile.",
      "Short, dry park paths do not automatically require a trail shoe. If the surface is firm, non-technical and your road outsole grips securely, staying in the road category may be simpler and lighter.",
    ],
  },
  {
    id: "when-trail",
    type: "prose",
    title: "When a trail shoe earns its place",
    paragraphs: [
      "Use a trail shoe when loose soil, mud, wet rock, roots, sharp stones, steep grades or sustained uneven terrain make traction and protection central to the run. The more technical the route, the less useful a road shoe’s weight advantage becomes.",
      "Choose tread for the actual trail. Widely spaced aggressive lugs suit mud and loose ground; lower-profile tread is often smoother on hardpack and mixed routes. No outsole compound grips every wet surface equally.",
      "For long trail days, cushioning still matters, but so do platform control, upper security and swelling room. Maximum stack without suitable geometry can feel vague on off-camber ground.",
    ],
  },
  {
    id: "hybrid-shoes",
    type: "prose",
    title: "Hybrid and door-to-trail shoes are compromises by design",
    paragraphs: [
      "A hybrid or door-to-trail shoe uses moderate tread and road-friendly geometry to cover pavement connectors, gravel and non-technical trail. It can be the most practical one-shoe answer when every run mixes surfaces.",
      "The compromise appears at the extremes. Hybrid lugs may lack bite in deep mud, while their tread and reinforcement may feel heavier or less smooth than a dedicated road daily trainer.",
      "“Approach shoe” can mean a climbing-oriented hiking shoe built for scrambling to a route, not a running hybrid. Check whether the product is designed for sustained running before using the label as a substitute for specifications.",
    ],
  },
  {
    id: "surface-scenarios",
    type: "use-case-cards",
    title: "Match the shoe to the route",
    cards: [
      { id: "road", title: "Pavement / treadmill", description: "Choose a road shoe for smooth contact, lower weight and the broadest choice of training roles.", href: "/best/running-shoes" },
      { id: "park", title: "Dry park paths", description: "Road tread often works when surfaces are firm and non-technical; judge grip from conditions." },
      { id: "gravel", title: "Gravel / mixed route", description: "A hybrid or mild-lug trail shoe can add confidence without making road connectors miserable." },
      { id: "technical", title: "Rocky technical trail", description: "Prioritise secure fit, protective stack geometry, suitable tread and underfoot protection.", href: "/best/trail-running-shoes" },
      { id: "mud", title: "Mud / loose ground", description: "Deeper, well-spaced lugs matter more than maximum cushioning or road speed." },
      { id: "ultra", title: "Long trail day", description: "Balance grip and protection with sustained fit, cushioning and weight." },
    ],
  },
  {
    id: "tradeoffs",
    type: "pros-tradeoffs",
    title: "What trail capability adds—and costs",
    gains: [
      "More suitable traction on loose, wet or uneven ground",
      "A more secure upper for turns, cambers and descents",
      "Added toe and underfoot protection",
      "Durability features aimed at trail abrasion",
    ],
    giveUps: [
      "More rubber and reinforcement can add weight",
      "Aggressive lugs can feel rough or unstable on pavement",
      "Protective structures can reduce flexibility and ground feel",
      "Trail fit and upper protection may feel warmer or less relaxed",
    ],
    footnote: "A dedicated trail shoe is valuable when these gains solve recurring terrain problems—not simply because it looks more rugged.",
  },
  {
    id: "rock-plate-note",
    type: "callout",
    title: "Rock protection is not the same as a propulsion plate",
    tone: "accent",
    body: "A trail rock plate or protective film spreads sharp underfoot contact. A carbon or nylon propulsion plate is tuned with foam and rocker for stiffness and transition. Catalog plate fields may focus on the latter, so also read the trail shoe’s construction and protection notes.",
  },
  {
    id: "decision-flow",
    type: "decision-flow",
    title: "Choose road, trail or hybrid step by step",
    steps: [
      { id: "surface", title: "Count the surfaces", body: "Estimate how much of the actual route is pavement, smooth path, gravel or technical trail." },
      { id: "conditions", title: "Check likely conditions", body: "Dry hardpack, mud, wet rock and snow demand different tread and compounds." },
      { id: "technicality", title: "Rate technicality", body: "Roots, rocks, cambers and steep descents raise the value of lockdown, control and protection." },
      { id: "outsole", title: "Select enough outsole", body: "Use the least aggressive tread that reliably handles the hardest recurring section." },
      { id: "fit", title: "Confirm terrain-ready fit", body: "Secure heel and midfoot while preserving toe room for descents and longer runs." },
      { id: "ride", title: "Choose cushioning and weight", body: "After grip and fit, select the protection and agility appropriate to distance and pace." },
      { id: "specialise", title: "Decide whether to specialise", body: "If one route contains opposite extremes, a road/trail rotation may beat one compromised hybrid." },
    ],
    branches: {
      question: "Where does most of the run happen?",
      options: [
        { label: "Road / treadmill", result: "Choose a road shoe unless off-road sections create a real traction problem." },
        { label: "Road + smooth trail", result: "Consider a door-to-trail model or a road shoe with dependable all-surface grip." },
        { label: "Mostly trail", result: "Choose trail tread for the conditions, then refine protection, cushion and fit." },
        { label: "Technical / muddy", result: "Prioritise aggressive grip, secure fit and protection over road smoothness." },
      ],
    },
  },
  {
    id: "product-examples",
    type: "product-examples",
    title: "Road and trail designs in the catalog",
    disclaimer: "These examples illustrate terrain-led design differences. They are not an automatic ranking; use the linked Best guides for current recommendations.",
    examples: [
      {
        productId: "prod-peregrine-15",
        approachLabel: "Agile aggressive-grip trail example",
        whyIllustrates: "PWRTRAC aggressive trail grip, a reinforced mesh upper, medium balanced cushioning and a 4 mm drop target technical singletrack and muddy conditions.",
        bestFor: ["Technical trail", "Mud and loose ground", "Runners wanting a more connected trail platform"],
        tradeoff: "Aggressive tread and firmer hardpack feel make long road connectors a weak fit.",
      },
      {
        productId: "prod-speedgoat-6",
        approachLabel: "Protective long-trail example",
        whyIllustrates: "High balanced cushioning, a protective ride and Vibram Megagrip with Traction Lug prioritise technical terrain and longer mountain days.",
        bestFor: ["Long trail runs", "Technical terrain", "Runners wanting more cushioning and trail grip"],
        tradeoff: "More trail structure and rubber than needed for routine pavement running.",
      },
      {
        productId: "prod-novablast-6",
        approachLabel: "Lively high-cushion road example",
        whyIllustrates: "A road-focused outsole, soft high cushioning, high energy return and rockered neutral ride favour varied road mileage rather than technical grip.",
        bestFor: ["Daily road training", "Long road runs", "Runners wanting soft plus lively"],
        tradeoff: "Tall soft road geometry and tread are not designed for loose or technical trail.",
      },
      {
        productId: "prod-ghost-18",
        approachLabel: "Conventional durable road example",
        whyIllustrates: "Smooth high-cushion road construction, a rubber outsole and broad width ladder emphasise predictable daily fit and durability.",
        bestFor: ["Daily pavement", "Beginners", "Runners needing narrow through extra-wide options"],
        tradeoff: "Road grip and breathable mesh offer less technical traction and protection than dedicated trail designs.",
      },
    ],
  },
  {
    id: "product-comparison",
    type: "product-comparison",
    title: "Compare two trail and two road shoes",
    productIds: ["prod-peregrine-15", "prod-speedgoat-6", "prod-novablast-6", "prod-ghost-18"],
    bestGuideHref: "/best/trail-running-shoes",
    bestGuideLabel: "Best Trail Running Shoes →",
    compareHref:
      "/compare?category=running-shoes&products=saucony-peregrine-15,hoka-speedgoat-6,asics-novablast-6,brooks-ghost-18",
  },
  {
    id: "mistakes",
    type: "mistakes",
    title: "Common road-vs-trail mistakes",
    mistakes: [
      { id: "rugged", title: "Buying the most rugged shoe", body: "More lug, reinforcement and protection can be unnecessary weight and stiffness on smooth routes." },
      { id: "road-anywhere", title: "Taking road grip onto technical trail", body: "A comfortable road shoe can still lack traction, lockdown and underfoot protection." },
      { id: "trail-road", title: "Using aggressive trail shoes for road volume", body: "Deep lugs can feel awkward, wear differently and make pavement transitions less smooth." },
      { id: "all-trails", title: "Treating every trail alike", body: "Dry hardpack, mud, wet rock and alpine scree place different demands on tread." },
      { id: "stack", title: "Choosing stack without control", body: "More cushioning can help long days, but tall soft platforms need suitable geometry on uneven ground." },
      { id: "fit", title: "Sizing only for standing comfort", body: "Trail descents and cambers expose heel slip, toe impact and lateral movement." },
      { id: "injury", title: "Treating terrain categories as injury prevention", body: "Shoe type does not diagnose or guarantee prevention. Persistent pain needs qualified assessment." },
    ],
  },
  {
    id: "compare-cta",
    type: "cta",
    title: "See the trade-offs side by side",
    variant: "compare",
    body: "Compare terrain, grip, cushioning, stability, drop, widths and construction across the four examples.",
    ctaLabel: "Compare road and trail shoes →",
    href: "/compare?category=running-shoes&products=saucony-peregrine-15,hoka-speedgoat-6,asics-novablast-6,brooks-ghost-18",
  },
  {
    id: "finder-cta",
    type: "cta",
    title: "Start with your terrain",
    variant: "finder",
    body: "The Running Shoe Finder combines terrain with training role, fit, cushioning and support preferences to build a shortlist.",
    ctaLabel: "Find my running shoes →",
    href: "/tools/running-shoe-finder",
  },
  {
    id: "best-trail-cta",
    type: "cta",
    title: "Need dedicated trail recommendations?",
    variant: "best-guide",
    body: "See current trail picks for different terrain and running roles. For pavement-first choices, use Best Running Shoes.",
    ctaLabel: "Best Trail Running Shoes →",
    href: "/best/trail-running-shoes",
  },
];

export const roadVsTrailRunningShoesConfig: LongFormGuideConfig = {
  guideSlug: "road-vs-trail-running-shoes",
  layout: "explainer",
  eyebrow: "Explainer",
  displayTitle: "Road vs Trail Running Shoes",
  deck: "How outsole, protection, fit, rock plates, cushioning and weight change across terrain—and when a road, trail or hybrid shoe is the practical choice.",
  heroImageSrc: "/images/running/products/peregrine-15-hero.jpg",
  heroImageAlt: "Saucony Peregrine 15 trail running shoe",
  finder: {
    toolSlug: "running-shoe-finder",
    title: "Find shoes for your terrain",
    description: "Combine surface and conditions with training role, fit, cushion and support preferences.",
    ctaLabel: "Find my running shoes →",
  },
  decisionLinks: [
    {
      label: "Compare road and trail shoes →",
      href: "/compare?category=running-shoes&products=saucony-peregrine-15,hoka-speedgoat-6,asics-novablast-6,brooks-ghost-18",
    },
    { label: "Best trail running shoes →", href: "/best/trail-running-shoes" },
    { label: "Best running shoes →", href: "/best/running-shoes" },
  ],
  glossaryHref: "/guides/running-shoe-terminology",
  glossaryTerms: [
    { id: "road-outsole", term: "Road outsole", definition: "Flatter ground-contact tread designed for firm surfaces.", icon: "circle" },
    { id: "trail-lugs", term: "Trail lugs", definition: "Raised tread that bites into loose or uneven ground.", icon: "layers" },
    { id: "rock-plate", term: "Rock plate", definition: "Protective layer intended to spread sharp underfoot contact.", icon: "shield" },
    { id: "door-to-trail", term: "Door-to-trail", definition: "Hybrid design for pavement connectors and non-technical trail.", icon: "gauge" },
    { id: "lockdown", term: "Lockdown", definition: "How securely the upper holds heel and midfoot.", icon: "shield" },
    { id: "technical-trail", term: "Technical trail", definition: "Uneven terrain involving features such as rocks, roots, cambers or steep grades.", icon: "scale" },
  ],
  needs: [],
  factors: [],
  fit: [],
  toc: tocFromExplainer([...ROAD_VS_TRAIL_BLOCKS]),
  productExampleRoles: [
    { productId: "prod-peregrine-15", roleLabel: "Agile technical trail" },
    { productId: "prod-speedgoat-6", roleLabel: "Protective long trail" },
    { productId: "prod-novablast-6", roleLabel: "Lively road daily" },
    { productId: "prod-ghost-18", roleLabel: "Smooth road daily" },
  ],
  productRailTitle: "Road and trail design examples",
  productRailBrowseHref: "/running/shoes",
  productRailBrowseLabel: "Browse running shoes →",
  explainer: {
    layout: "explainer",
    quickAnswerBullets: [
      "Road shoes prioritise smooth hard-surface transitions; trail shoes prioritise variable-ground grip, security and protection.",
      "Outsole pattern and compound should match the hardest recurring terrain—not simply look rugged.",
      "Trail fit needs secure heel and midfoot lockdown plus enough toe room for descents and long-run swelling.",
      "A rock plate protects against sharp contact; it is not the same as a carbon propulsion plate.",
      "Hybrid shoes work well on mixed, moderate routes but give up road smoothness and extreme-trail grip.",
      "Choose terrain first, then refine cushioning, protection, fit and weight for the run.",
    ],
    medicalNote:
      "Kitletics explains footwear design and terrain suitability. Road or trail classifications do not prevent injury, diagnose pain or replace medical assessment. Consult a qualified clinician for persistent symptoms or medical footwear needs.",
    methodologyNote:
      "This comparison uses controlled catalog terrain, grip, cushionLevel, stability, upper, outsole, plate and width fields alongside manufacturer construction details. Product examples and comparison specifications render from the current catalog rather than hardcoded prices.",
    blocks: [...ROAD_VS_TRAIL_BLOCKS],
  },
};
