/**
 * Running Shoe Terminology — a decision-useful glossary for comparing shoes.
 */
import type { ExplainerBlock } from "@/lib/guides/explainer-blocks";
import { tocFromExplainer } from "@/lib/guides/explainer-blocks";
import type { LongFormGuideConfig } from "@/lib/guides/long-form-config";

const TERMINOLOGY_BLOCKS: ExplainerBlock[] = [
  {
    id: "how-to-read-terms",
    type: "prose",
    title: "Running shoe terms should answer shopping questions",
    intro: "A specification matters only when it changes the fit, ride or job a shoe can do.",
    paragraphs: [
      "Running-shoe language mixes measurable specifications, controlled catalog categories and brand marketing. Stack and drop describe geometry. Cushion level, stability and energy return classify ride or design intent. Names such as “super foam” are less standardised.",
      "Do not choose from one number or label. A high-stack shoe can feel firm; a neutral shoe can feel planted; a plated shoe can be a training tool rather than a racer. Read related terms together, then connect them to the runs you actually do.",
      "Kitletics uses structured fields to make cross-brand comparison clearer. Those fields describe products, not your anatomy, gait or medical needs.",
    ],
  },
  {
    id: "geometry-terms",
    type: "factor-cards",
    title: "Geometry terms: stack, drop, rocker and last",
    intro: "These terms describe the platform beneath and around the foot.",
    cards: [
      {
        id: "stack",
        title: "Stack height",
        whatItIs: "The amount of material between the foot and ground, usually stated at heel and forefoot.",
        howItChanges: "More stack can add protection and space for foam, while also increasing platform height and bulk.",
        whatYouNotice: "More or less ground separation—not guaranteed softness.",
      },
      {
        id: "drop",
        title: "Heel-to-toe drop",
        whatItIs: "The difference between heel and forefoot stack, normally measured in millimetres.",
        howItChanges: "Alters platform geometry and how the shoe may load through transition.",
        whatYouNotice: "A flatter or more heel-elevated stance, with adaptation varying by runner.",
      },
      {
        id: "rocker",
        title: "Rocker",
        whatItIs: "Curved sole geometry that encourages the shoe to roll through stance.",
        howItChanges: "Can smooth transitions, especially when the platform is tall or stiff.",
        whatYouNotice: "An obvious rolling sensation—or little effect, depending on pace and stride.",
      },
      {
        id: "last",
        title: "Last",
        whatItIs: "The three-dimensional form around which the shoe is shaped.",
        howItChanges: "Influences toe-box shape, midfoot volume, heel shape and the overall fit character.",
        whatYouNotice: "Whether the shoe feels tapered, roomy, secure, shallow or high-volume.",
      },
    ],
  },
  {
    id: "stack-drop-together",
    type: "comparison-table",
    title: "Read stack and drop together",
    columns: ["What it tells you", "Useful shopping question", "Common mistake"],
    rows: [
      {
        label: "Heel stack",
        values: ["Material height under the heel", "How tall is the rear platform?", "Treating height as softness"],
      },
      {
        label: "Forefoot stack",
        values: ["Material height under the forefoot", "How much forefoot protection is present?", "Ignoring it when comparing two equal-drop shoes"],
      },
      {
        label: "Drop",
        values: ["Heel stack minus forefoot stack", "How flat or elevated is the geometry?", "Treating a number as a medical prescription"],
      },
      {
        label: "Rocker",
        values: ["Curvature and transition design", "Does the shoe roll or flex through toe-off?", "Assuming every tall shoe has the same transition"],
      },
    ],
    footnote: "Measurement methods can differ by source. Compare like-for-like data and allow for manufacturing tolerance.",
  },
  {
    id: "ride-terms",
    type: "factor-cards",
    title: "Ride terms: cushion level, feel and energy return",
    cards: [
      {
        id: "cushion-level",
        title: "Cushioning",
        whatItIs: "Kitletics’ controlled category for cushioning amount: minimal, low, medium, high or maximum.",
        howItChanges: "Helps filter broad protection and stack intent across the catalog.",
        whatYouNotice: "How much cushioning the shoe is built around—not exactly how soft it feels.",
      },
      {
        id: "cushion-feel",
        title: "Cushion feel",
        whatItIs: "The underfoot compression character, such as plush, soft, balanced or firm.",
        howItChanges: "Separates the sensation of foam from the amount of material.",
        whatYouNotice: "More sink, support or firmness under load.",
      },
      {
        id: "energy-return",
        title: "Energy return",
        whatItIs: "How readily the complete midsole system rebounds after compression.",
        howItChanges: "Contributes to a relaxed, lively or highly responsive ride.",
        whatYouNotice: "More or less rebound; it is not free energy or a guarantee of faster running.",
      },
      {
        id: "ride-character",
        title: "Ride character",
        whatItIs: "The overall transition label, such as smooth, rockered, responsive or protective.",
        howItChanges: "Summarises how foam, geometry, stiffness and outsole work together.",
        whatYouNotice: "The shoe’s dominant motion rather than one isolated material property.",
      },
    ],
  },
  {
    id: "support-terms",
    type: "factor-cards",
    title: "Support terms: neutral, stability and plates",
    cards: [
      {
        id: "neutral",
        title: "Neutral",
        whatItIs: "A platform with minimal dedicated guidance structures.",
        howItChanges: "Usually allows a freer path through the shoe, although broad geometry can still feel planted.",
        whatYouNotice: "Less deliberate guidance—not an inherently unstable shoe.",
      },
      {
        id: "stability",
        title: "Stability",
        whatItIs: "A design category using geometry, sidewalls, rails, posts or other structures for a more guided platform.",
        howItChanges: "Can make the ride feel more controlled or secure.",
        whatYouNotice: "Mild to obvious guidance, depending on the model—not a diagnosis or treatment.",
      },
      {
        id: "plate",
        title: "Plate",
        whatItIs: "A carbon, nylon or other stiffening structure embedded in the sole.",
        howItChanges: "Works with foam and rocker to manage bending and transition.",
        whatYouNotice: "Potentially more snap or rigidity; not every plate is built for racing.",
      },
      {
        id: "platform",
        title: "Platform width",
        whatItIs: "The width of the midsole footprint under the foot.",
        howItChanges: "A broader base can make tall or soft foam feel more planted.",
        whatYouNotice: "Geometric security, separate from whether the upper is sold in wide sizing.",
      },
    ],
  },
  {
    id: "construction-terms",
    type: "factor-cards",
    title: "Construction terms: midsole, outsole and upper",
    cards: [
      {
        id: "midsole",
        title: "Midsole",
        whatItIs: "The foam and structural system between footbed and outsole.",
        howItChanges: "Provides most cushioning, rebound, guidance and underfoot geometry.",
        whatYouNotice: "The core ride, although the plate and outsole can change it.",
      },
      {
        id: "outsole",
        title: "Outsole",
        whatItIs: "The ground-contact layer, commonly rubber with road tread or trail lugs.",
        howItChanges: "Controls grip, contributes durability and can add weight or stiffness.",
        whatYouNotice: "Traction and confidence on the intended surface.",
      },
      {
        id: "upper",
        title: "Upper",
        whatItIs: "The mesh, knit, overlays, tongue and heel structure wrapping the foot.",
        howItChanges: "Creates lockdown, volume, breathability and some protection.",
        whatYouNotice: "Fit security, pressure points, ventilation and debris resistance.",
      },
      {
        id: "lug-depth",
        title: "Lugs",
        whatItIs: "Raised outsole projections designed to bite into loose or uneven ground.",
        howItChanges: "Improves trail traction while making road contact less smooth.",
        whatYouNotice: "More grip off-road and more tread sensation on pavement.",
      },
    ],
  },
  {
    id: "fit-language",
    type: "prose",
    title: "Fit language is not interchangeable",
    paragraphs: [
      "Last, width option, toe-box shape and upper volume describe different things. “Wide” may mean an official width SKU, a naturally roomy last, a broad forefoot, or simply a reviewer’s impression.",
      "Check the offered width first, then read model-specific fit notes. A broad midsole platform does not guarantee a roomy upper, and an extra-wide upper does not tell you how broad the foam base is.",
      "Allow practical toe room and secure the heel without excessive lace pressure. If fit changes your stride or creates persistent discomfort, the specification sheet cannot make that shoe the right choice.",
    ],
  },
  {
    id: "shopping-translation",
    type: "decision-flow",
    title: "Translate terminology into a shortlist",
    steps: [
      { id: "job", title: "Name the shoe’s job", body: "Start with daily, easy, long, workout, race or trail use." },
      { id: "terrain", title: "Choose the terrain", body: "Outsole and upper needs change sharply between pavement and technical trail." },
      { id: "fit", title: "Set fit constraints", body: "Confirm length, official widths, last shape and lockdown before chasing ride details." },
      { id: "ride", title: "Choose ride character", body: "Combine cushion level, cushion feel, energy return and rocker." },
      { id: "geometry", title: "Check geometry", body: "Read heel stack, forefoot stack, drop, platform width and flexibility together." },
      { id: "support", title: "Select guidance preference", body: "Compare neutral, mild-stability and stability as product designs—not diagnoses." },
      { id: "tradeoffs", title: "Accept the compromise", body: "More grip, stack, structure or rebound usually carries a cost in weight, flexibility, durability or price." },
    ],
    branches: {
      question: "Which term matters first?",
      options: [
        { label: "Fit problem", result: "Start with last, width options, upper volume and heel lockdown." },
        { label: "Ride preference", result: "Start with cushion feel, energy return, rocker and flexibility." },
        { label: "Terrain need", result: "Start with outsole, grip, lugs, upper protection and stack protection." },
        { label: "Support preference", result: "Compare stability classification, platform width and guidance approach." },
      ],
    },
  },
  {
    id: "terms-by-session",
    type: "use-case-cards",
    title: "Which terms matter most by use",
    cards: [
      { id: "daily", title: "Daily training", description: "Fit, outsole durability, cushion feel and versatility usually matter more than one headline technology.", href: "/best/daily-trainers" },
      { id: "easy", title: "Easy / recovery", description: "Cushion level, feel, platform width and relaxed transitions are useful comparison points." },
      { id: "workout", title: "Tempo / intervals", description: "Weight, energy return, rocker, flexibility and plate construction become more relevant.", href: "/best/tempo-running-shoes" },
      { id: "race", title: "Road racing", description: "Race fit, premium foam, plate, stack legality and tested pace comfort matter.", href: "/best/race-shoes" },
      { id: "trail", title: "Trail running", description: "Outsole compound, lugs, upper security, protection and terrain suitability lead the decision.", href: "/best/trail-running-shoes" },
    ],
  },
  {
    id: "medical-boundary",
    type: "callout",
    title: "Specifications describe shoes, not diagnoses",
    tone: "caution",
    body: "Drop, cushioning, stability and rocker can change how a shoe feels, but no catalog term diagnoses gait, prescribes footwear or guarantees injury prevention. Seek qualified clinical advice for persistent pain, injury or medical footwear needs.",
  },
  {
    id: "product-examples",
    type: "product-examples",
    title: "Four products, four terminology profiles",
    disclaimer: "These examples show how terms combine; they are not ranked recommendations. Product specifications render from current catalog data.",
    examples: [
      {
        productId: "prod-novablast-6",
        approachLabel: "High-cushion, high-return neutral daily",
        whyIllustrates: "Its 8 mm drop, soft high cushioning, high energy return, rockered ride and unplated neutral platform show why one word cannot describe a shoe.",
        bestFor: ["Mixed daily mileage", "Long runs", "Runners wanting soft plus lively"],
        tradeoff: "Tall, soft geometry may feel less direct than a lower or firmer trainer.",
      },
      {
        productId: "prod-ghost-18",
        approachLabel: "Smooth neutral daily with broad widths",
        whyIllustrates: "A 12 mm drop, soft high cushioning, moderate energy return and extensive width ladder make fit and conventional daily comfort the leading terms.",
        bestFor: ["Daily road running", "Beginners", "Narrow through extra-wide sizing needs"],
        tradeoff: "Less energetic and specialised than performance-focused options.",
      },
      {
        productId: "prod-peregrine-15",
        approachLabel: "Protective aggressive-grip trail shoe",
        whyIllustrates: "Medium balanced cushioning, 4 mm drop, reinforced upper and aggressive PWRTRAC outsole shift the vocabulary from road smoothness to grip and protection.",
        bestFor: ["Technical singletrack", "Muddy conditions", "Runners wanting trail feel"],
        tradeoff: "Aggressive tread can feel firm and awkward on long paved connectors.",
      },
      {
        productId: "prod-vaporfly-4",
        approachLabel: "Carbon-plated race system",
        whyIllustrates: "High cushioning, firm feel, very-high energy return and a carbon plate demonstrate that responsive race cushioning is not the same as plush daily cushioning.",
        bestFor: ["Road racing", "Race-specific workouts", "Runners comfortable with stiff geometry"],
        tradeoff: "Specialised fit, feel, durability and price make it a poor default daily shoe.",
      },
    ],
  },
  {
    id: "product-comparison",
    type: "product-comparison",
    title: "Compare terminology in real products",
    productIds: ["prod-novablast-6", "prod-ghost-18", "prod-peregrine-15", "prod-vaporfly-4"],
    bestGuideHref: "/best/running-shoes",
    bestGuideLabel: "Best Running Shoes →",
    compareHref:
      "/compare?category=running-shoes&products=asics-novablast-6,brooks-ghost-18,saucony-peregrine-15,nike-vaporfly-4",
  },
  {
    id: "misconceptions",
    type: "mistakes",
    title: "Common terminology misconceptions",
    mistakes: [
      { id: "stack-soft", title: "High stack means soft", body: "Stack is height. Foam, geometry and stiffness determine how the platform compresses." },
      { id: "drop-best", title: "One drop is healthiest", body: "Drop is geometry, not a universal prescription. Comfort, adaptation and the complete shoe matter." },
      { id: "neutral-unstable", title: "Neutral means unstable", body: "A neutral shoe can use a broad, planted platform without dedicated guidance structures." },
      { id: "plate-fast", title: "Every plate makes you faster", body: "Plate material and purpose vary; performance comes from the whole foam-geometry system and the runner." },
      { id: "energy", title: "Energy return creates free energy", body: "The term describes rebound behaviour, not energy generation or a guaranteed performance gain." },
      { id: "wide", title: "Wide platform means wide fit", body: "Midsole footprint and upper width are separate. Check both." },
      { id: "trail-road", title: "More outsole is always better", body: "Aggressive lugs improve loose-ground traction but can add weight and feel awkward on pavement." },
    ],
  },
  {
    id: "finder-cta",
    type: "cta",
    title: "Use the terms without building the shortlist yourself",
    variant: "finder",
    body: "The Running Shoe Finder combines training role, terrain, fit, cushioning and support preferences into product matches.",
    ctaLabel: "Find my running shoes →",
    href: "/tools/running-shoe-finder",
  },
  {
    id: "best-cta",
    type: "cta",
    title: "Ready for current recommendations?",
    variant: "best-guide",
    body: "Use the Best Running Shoes guide for role-based picks, then compare the specifications you now understand.",
    ctaLabel: "See the best running shoes →",
    href: "/best/running-shoes",
  },
];

export const runningShoeTerminologyConfig: LongFormGuideConfig = {
  guideSlug: "running-shoe-terminology",
  layout: "explainer",
  eyebrow: "Explainer",
  displayTitle: "Running Shoe Terminology Explained",
  deck: "A practical glossary of stack, drop, rocker, cushioning, energy return, stability, plates, fit, outsoles and uppers—and how to use those terms when shopping.",
  heroImageSrc: "/images/running/products/novablast-6-hero.jpg",
  heroImageAlt: "ASICS Novablast 6 running shoe illustrating modern shoe terminology",
  finder: {
    toolSlug: "running-shoe-finder",
    title: "Turn specifications into a shortlist",
    description: "Match terrain, fit, cushion, support and training use without relying on one headline term.",
    ctaLabel: "Find my running shoes →",
  },
  decisionLinks: [
    { label: "Find my running shoes →", href: "/tools/running-shoe-finder" },
    { label: "Best running shoes →", href: "/best/running-shoes" },
    {
      label: "Compare terminology examples →",
      href: "/compare?category=running-shoes&products=asics-novablast-6,brooks-ghost-18,saucony-peregrine-15,nike-vaporfly-4",
    },
  ],
  glossaryTerms: [
    { id: "stack", term: "Stack height", definition: "Material height between the foot and ground.", icon: "layers" },
    { id: "drop", term: "Heel-to-toe drop", definition: "Difference between heel and forefoot stack.", icon: "ruler" },
    { id: "rocker", term: "Rocker", definition: "Curved sole geometry that encourages a rolling transition.", icon: "gauge" },
    { id: "cushion-level", term: "Cushioning", definition: "How much cushioning the shoe is built around—not exactly how soft it feels.", icon: "scale" },
    { id: "energy-return", term: "Energy return", definition: "How readily the midsole system rebounds after compression.", icon: "gauge" },
    { id: "stability", term: "Stability", definition: "Designs intended to create a more guided platform.", icon: "shield" },
    { id: "plate", term: "Plate", definition: "A stiffening structure working with foam and geometry.", icon: "layers" },
    { id: "last", term: "Last", definition: "The three-dimensional form that shapes the shoe’s fit.", icon: "circle" },
    { id: "outsole", term: "Outsole", definition: "The ground-contact layer providing tread and durability.", icon: "scale" },
    { id: "upper", term: "Upper", definition: "The structure wrapping and securing the foot.", icon: "circle" },
  ],
  needs: [],
  factors: [],
  fit: [],
  toc: tocFromExplainer([...TERMINOLOGY_BLOCKS]),
  productExampleRoles: [
    { productId: "prod-novablast-6", roleLabel: "Soft, lively neutral daily" },
    { productId: "prod-ghost-18", roleLabel: "Smooth, broad-width daily" },
    { productId: "prod-peregrine-15", roleLabel: "Aggressive-grip trail" },
    { productId: "prod-vaporfly-4", roleLabel: "Carbon-plated race" },
  ],
  productRailTitle: "Examples with different terminology profiles",
  productRailBrowseHref: "/running/shoes",
  productRailBrowseLabel: "Browse running shoes →",
  explainer: {
    layout: "explainer",
    quickAnswerBullets: [
      "Stack is platform height; drop is the difference between heel and forefoot stack.",
      "Cushioning describes amount; cushion feel describes compression; energy return describes rebound.",
      "Neutral and stability describe platform design—not gait diagnoses or medical prescriptions.",
      "A plate works with foam and rocker geometry; it does not automatically make every runner faster.",
      "Last and upper shape determine fit, while platform width describes the midsole footprint.",
      "Use terms in groups: start with role and terrain, confirm fit, then compare ride and geometry.",
    ],
    medicalNote:
      "Kitletics explains product terminology and construction. Shoe specifications do not diagnose gait, prescribe medical footwear, prevent injury or treat pain. Consult a qualified clinician for persistent symptoms or medical footwear questions.",
    methodologyNote:
      "Definitions align with controlled Kitletics catalog fields and common industry usage, while separating measurable geometry from subjective ride labels and unstandardised marketing language. Product examples and comparison data render from the current catalog.",
    blocks: [...TERMINOLOGY_BLOCKS],
  },
};
