import type { ExplainerBlock } from "@/lib/guides/explainer-blocks";
import { tocFromExplainer } from "@/lib/guides/explainer-blocks";
import type { LongFormGuideConfig } from "@/lib/guides/long-form-config";

const ROTATION_BLOCKS: ExplainerBlock[] = [
  {
    id: "definition",
    type: "prose",
    title: "What is a running shoe rotation?",
    intro: "A rotation assigns shoes to jobs. It is not a requirement to own more shoes.",
    paragraphs: [
      "A running shoe rotation is the set of shoes you actively use across a training week. The useful version is role-based: a dependable daily trainer covers ordinary mileage, while another pair may handle faster sessions, long runs, trails or racing.",
      "One versatile shoe is a valid rotation. Add a second pair when one shoe cannot comfortably solve two conflicting jobs — for example, soft easy mileage and sharp intervals. Add a third only when it fills a real gap.",
      "Rotation is about coverage, not collecting. Every pair should have a defined session, fit your current training and receive enough use to justify its cost.",
    ],
  },
  {
    id: "why-rotate",
    type: "factor-cards",
    title: "Why runners rotate shoes",
    cards: [
      {
        id: "roles",
        title: "Match the session",
        whatItIs: "Different shoes assigned to easy, fast, long or race roles.",
        howItChanges: "Lets cushioning, weight and geometry fit the work.",
        whatYouNotice: "Easy shoes feel comfortable; faster shoes feel less compromised.",
      },
      {
        id: "wear",
        title: "Spread wear",
        whatItIs: "Mileage divided between two or more pairs.",
        howItChanges: "Extends calendar time before any single pair reaches its wear limit.",
        whatYouNotice: "Fewer emergency replacements, but not necessarily lower total cost per kilometre.",
      },
      {
        id: "conditions",
        title: "Cover conditions",
        whatItIs: "Different outsole, upper or terrain capabilities.",
        howItChanges: "Keeps wet roads, trails or winter sessions from dictating one compromised choice.",
        whatYouNotice: "Better grip or protection when conditions demand it.",
      },
      {
        id: "backup",
        title: "Keep a known backup",
        whatItIs: "A second serviceable pair ready when the primary shoe is wet, worn or unavailable.",
        howItChanges: "Reduces dependence on a single pair.",
        whatYouNotice: "Training can continue without rushing a replacement purchase.",
      },
    ],
  },
  {
    id: "sessions",
    type: "use-case-cards",
    title: "The main rotation roles",
    cards: [
      { id: "daily", title: "Daily mileage", description: "The default pair: comfortable, predictable and durable enough for most weekly running.", href: "/best/daily-trainers" },
      { id: "easy", title: "Easy / recovery", description: "Prioritises comfort and protection when pace is not the goal." },
      { id: "long", title: "Long run", description: "Fit, sustained comfort and late-run stability matter more as time on feet rises.", href: "/best/running-shoes-long-runs" },
      { id: "tempo", title: "Tempo / intervals", description: "A lighter, more responsive tool for controlled faster work.", href: "/best/tempo-running-shoes" },
      { id: "race", title: "Race day", description: "The most specialised role; only necessary when racing goals justify it.", href: "/best/race-shoes" },
      { id: "trail", title: "Trail / poor conditions", description: "Grip and protection create a genuine role that road shoes may not cover." },
    ],
  },
  {
    id: "how-many",
    type: "comparison-table",
    title: "How many running shoes do you need?",
    columns: ["Setup", "Best use"],
    rows: [
      { label: "1 shoe", values: ["Versatile daily trainer", "Simple schedules, new runners, controlled budget"] },
      { label: "2 shoes", values: ["Daily/easy + tempo/race", "Most road runners adding weekly faster work"] },
      { label: "3 shoes", values: ["Daily + easy/long + tempo/race", "Higher volume or clearly separated session demands"] },
      { label: "4+ shoes", values: ["Role-specific additions", "Frequent racing, mixed terrain or strong preferences"] },
    ],
    footnote: "Count is not a performance target. Start with the smallest setup that covers your actual week.",
  },
  {
    id: "simple-rotations",
    type: "prose",
    title: "Build the smallest useful rotation",
    paragraphs: [
      "Start from your recurring week, not an aspirational race calendar. List the sessions you completed over the last month. If most runs were easy, buy the daily trainer first.",
      "For two shoes, separate ordinary mileage from faster work: a daily or cushioned trainer plus a tempo shoe. If long-run comfort is the bigger gap, pair the daily with a more protective long-run shoe instead.",
      "For three shoes, avoid redundant pairs. Daily plus easy/long plus tempo/race is clearer than three similar daily trainers. A race shoe can share the speed role until training volume or durability makes a separate tempo shoe worthwhile.",
    ],
  },
  {
    id: "foam-recovery",
    type: "callout",
    title: "Do midsoles need 24–48 hours to recover?",
    tone: "neutral",
    body: "Foams can show time-dependent compression recovery, but there is no universal waiting rule that makes every shoe safer or longer-lived. Rotate primarily for session fit, condition coverage and convenience — not because marketing claims a mandatory recovery window.",
  },
  {
    id: "cost-math",
    type: "prose",
    title: "The honest cost math",
    paragraphs: [
      "Owning two pairs spreads mileage; it does not make kilometres disappear. If each pair delivers similar usable mileage, buying both generally delays the next purchase in calendar time but does not automatically reduce long-run cost.",
      "A rotation can save money when it keeps premium shoes out of low-value sessions. Using a durable daily trainer for easy miles preserves a high-priced tempo or race shoe for the sessions where its design matters.",
      "Calculate cost per expected use, not just retail price. Include how often the role appears, whether another shoe already covers it and whether you will reach the shoe's useful life before age, preference or training changes retire it.",
    ],
  },
  {
    id: "cost-table",
    type: "comparison-table",
    title: "Price the rotation by role",
    columns: ["Poor allocation", "Better allocation"],
    rows: [
      { label: "Easy runs", values: ["Premium race shoe", "Durable daily or cushioned trainer"] },
      { label: "Tempo sessions", values: ["Heavy recovery shoe", "Responsive tempo trainer"] },
      { label: "Occasional races", values: ["Separate shoe for every distance", "One proven racer across compatible events"] },
      { label: "Replacement", values: ["Buy only after failure", "Track wear and shop before the primary pair is finished"] },
    ],
    footnote: "Actual value depends on local price, fit, durability and use. Kitletics does not promise fixed shoe lifespan.",
  },
  {
    id: "tradeoffs",
    type: "pros-tradeoffs",
    title: "What a rotation improves — and complicates",
    gains: [
      "Better match between shoe design and session",
      "A backup when one pair is wet or worn",
      "Less low-value mileage on specialised race shoes",
      "Clear options for terrain and weather",
    ],
    giveUps: [
      "More cash paid upfront",
      "More decisions and mileage to track",
      "Risk of buying overlapping shoes",
      "Pairs can become outdated or underused before they wear out",
    ],
    footnote: "A larger rotation is only better when every added shoe solves a recurring problem.",
  },
  {
    id: "decision",
    type: "decision-flow",
    title: "Build your rotation step by step",
    steps: [
      { id: "week", title: "Audit your real week", body: "Count easy, long, fast, trail and race sessions from recent training." },
      { id: "anchor", title: "Choose the anchor", body: "Start with the comfortable daily trainer that can handle the largest share of mileage." },
      { id: "gap", title: "Find the largest gap", body: "Is the daily too heavy for speed, too lean for long runs or wrong for terrain?" },
      { id: "second", title: "Add one complementary shoe", body: "Choose a pair that solves that gap without duplicating the anchor." },
      { id: "review", title: "Run the rotation", body: "Track which pair you actually reach for over four to six weeks." },
      { id: "third", title: "Add only with evidence", body: "A third pair needs a recurring role the first two genuinely cannot cover." },
    ],
    branches: {
      question: "What does your daily trainer fail to do?",
      options: [
        { label: "Nothing important", result: "Keep the one-shoe setup and replace it on condition." },
        { label: "Faster workouts", result: "Add a tempo trainer; let it share racing if appropriate." },
        { label: "Long-run comfort", result: "Add a protective long-run or max-cushion option." },
        { label: "Trails / weather", result: "Add the outsole and upper required for those conditions." },
      ],
    },
  },
  {
    id: "examples",
    type: "product-examples",
    title: "A practical four-role example",
    disclaimer: "These products demonstrate roles, not a prescription to own all four. Start with the minimum that fits your week.",
    examples: [
      {
        productId: "prod-pegasus-42",
        approachLabel: "Dependable daily anchor",
        whyIllustrates: "A conventional daily-training role for regular road mileage and broad weekly use.",
        bestFor: ["Daily miles", "Easy runs", "Simple one-shoe setups"],
        tradeoff: "Less specialised for maximum cushion or race-day speed.",
      },
      {
        productId: "prod-bondi-9",
        approachLabel: "Easy / recovery specialist",
        whyIllustrates: "Shows how a protective max-cushion shoe can separate easy volume from faster work.",
        bestFor: ["Easy runs", "Recovery pace", "Runners prioritising cushioning"],
        tradeoff: "Added weight and bulk make it a poor speed-role substitute.",
      },
      {
        productId: "prod-endorphin-speed-5",
        approachLabel: "Tempo and workout tool",
        whyIllustrates: "A nylon-plated faster trainer that complements rather than duplicates a daily shoe.",
        bestFor: ["Tempo", "Intervals", "Faster long runs"],
        tradeoff: "More specialised and potentially less relaxed for easy mileage.",
      },
      {
        productId: "prod-vaporfly-4",
        approachLabel: "Race-day specialist",
        whyIllustrates: "A carbon racer with a narrow, performance-first role at the top of a developed rotation.",
        bestFor: ["Road racing", "Race-specific sessions", "Performance-focused runners"],
        tradeoff: "Highest specialisation and weakest value when used indiscriminately.",
      },
    ],
  },
  {
    id: "product-comparison",
    type: "product-comparison",
    title: "Compare rotation roles side by side",
    productIds: ["prod-pegasus-42", "prod-bondi-9", "prod-endorphin-speed-5", "prod-vaporfly-4"],
    bestGuideHref: "/best/running-shoes",
    bestGuideLabel: "Best Running Shoes →",
    compareHref: "/compare?category=running-shoes&products=nike-pegasus-42,hoka-bondi-9,saucony-endorphin-speed-5,nike-vaporfly-4",
  },
  {
    id: "mistakes",
    type: "mistakes",
    title: "Common rotation mistakes",
    mistakes: [
      { id: "count", title: "Chasing a shoe count", body: "Two complementary shoes beat four overlapping pairs. Buy roles, not a number." },
      { id: "race-daily", title: "Using a racer for everything", body: "Premium race shoes add cost and specialised geometry where a daily trainer often works better." },
      { id: "duplicates", title: "Buying the same ride repeatedly", body: "If two shoes solve the same sessions equally, the second adds little coverage." },
      { id: "calendar", title: "Replacing by calendar alone", body: "Inspect outsole, foam feel, upper integrity and comfort; there is no universal expiry date." },
      { id: "tracking", title: "Not tracking mileage or condition", body: "Approximate logs and regular inspection make replacement less reactive." },
      { id: "pain", title: "Treating rotation as injury prevention", body: "A rotation does not diagnose or cure pain. Seek qualified assessment for clinical concerns." },
    ],
  },
  {
    id: "planner-cta",
    type: "cta",
    title: "Turn your week into clear roles",
    variant: "finder",
    body: "Use the Shoe Rotation Planner to map current pairs, find coverage gaps and avoid buying duplicates.",
    ctaLabel: "Build my shoe rotation →",
    href: "/tools/shoe-rotation-planner",
  },
  {
    id: "rotation-check",
    type: "prose",
    title: "Know when the rotation is complete",
    paragraphs: [
      "Your rotation is complete when every recurring session has a comfortable option and no pair lacks a clear role. It does not need to cover hypothetical events or every pace.",
      "Review when training changes, a shoe is retired or a genuine gap appears. Otherwise, keep running. The best rotation is the one you use, understand and can replace without financial strain.",
    ],
  },
  {
    id: "best-cta",
    type: "cta",
    title: "Choose the anchor pair first",
    variant: "best-guide",
    body: "Start with a strong daily trainer, then add a complementary shoe only when your training creates a clear gap.",
    ctaLabel: "See the best daily trainers →",
    href: "/best/daily-trainers",
  },
];

export const runningShoeRotationConfig: LongFormGuideConfig = {
  guideSlug: "running-shoe-rotation",
  layout: "explainer",
  eyebrow: "Explainer",
  displayTitle: "How to Build a Running Shoe Rotation",
  deck: "How many shoes you actually need, which training roles matter, what foam recovery claims miss, and how to build a rotation without paying for duplicates.",
  heroImageSrc: "/images/running/products/pegasus-42-hero.jpg",
  heroImageAlt: "Nike Pegasus 42 daily running shoe",
  finder: {
    toolSlug: "running-shoe-finder",
    title: "Find the next shoe by role",
    description: "Match a shoe to the gap in your training rather than adding another version of what you own.",
    ctaLabel: "Find my running shoes →",
  },
  decisionLinks: [
    { label: "Plan my rotation →", href: "/tools/shoe-rotation-planner" },
    { label: "Best daily trainers →", href: "/best/daily-trainers" },
    { label: "Best running shoes →", href: "/best/running-shoes" },
  ],
  glossaryHref: "/guides/running-shoe-terminology",
  glossaryTerms: [
    { id: "rotation", term: "Shoe rotation", definition: "The set of shoes actively assigned to roles in a training week.", icon: "circle" },
    { id: "daily", term: "Daily trainer", definition: "A versatile shoe intended to cover most routine mileage.", icon: "shield" },
    { id: "tempo", term: "Tempo shoe", definition: "A lighter, responsive shoe tuned for sustained faster running.", icon: "gauge" },
    { id: "max-cushion", term: "Max cushion", definition: "A high-cushion category prioritising protection and comfort.", icon: "layers" },
    { id: "compression-set", term: "Compression set", definition: "Persistent material deformation after repeated loading.", icon: "scale" },
    { id: "cost-per-use", term: "Cost per use", definition: "Purchase price divided by meaningful sessions completed.", icon: "ruler" },
  ],
  needs: [],
  factors: [],
  fit: [],
  toc: tocFromExplainer([...ROTATION_BLOCKS]),
  productExampleRoles: [
    { productId: "prod-pegasus-42", roleLabel: "Daily anchor" },
    { productId: "prod-bondi-9", roleLabel: "Easy / recovery" },
    { productId: "prod-endorphin-speed-5", roleLabel: "Tempo / workout" },
    { productId: "prod-vaporfly-4", roleLabel: "Race day" },
  ],
  productRailTitle: "Examples of distinct rotation roles",
  productRailBrowseHref: "/running/shoes",
  productRailBrowseLabel: "Browse running shoes →",
  explainer: {
    layout: "explainer",
    quickAnswerBullets: [
      "One versatile daily trainer is a complete rotation when it covers your actual training.",
      "A useful two-shoe setup usually separates daily/easy mileage from faster workouts or racing.",
      "Add shoes to solve recurring role conflicts, not to reach a target count.",
      "Rotating spreads wear across pairs but does not automatically lower total cost per kilometre.",
      "There is no universal 24–48-hour midsole recovery rule for every foam and runner.",
    ],
    medicalNote: "A shoe rotation is a training and purchasing framework, not medical care. It cannot diagnose, prevent or treat injury. Seek qualified clinical advice when running is painful.",
    methodologyNote: "This guide maps common training sessions to catalog shoe roles, separates material behaviour from unsupported recovery rules, and treats value as role coverage plus actual use. Product specifications and prices render from current catalog data.",
    blocks: [...ROTATION_BLOCKS],
  },
};
