import {
  buildExplainerFromPlan,
  CompactExplainerPlan,
} from "@/lib/guides/build-explainer-from-plan";

export const RUNNING_REMAINING_PLANS: CompactExplainerPlan[] = [
  {
    slug: "how-to-choose-heart-rate-monitor",
    displayTitle: "How to Choose a Heart-Rate Monitor for Running",
    deck: "Choose between chest and optical sensors by the sessions you run, the fit you can maintain and the devices you need to connect.",
    eyebrow: "Buying Guide",
    heroImageSrc: "/images/hrm/products/polar-h10-hero.png",
    heroImageAlt: "Polar H10 chest heart-rate monitor",
    quickAnswerBullets: [
      "Choose a chest strap when fast interval response and consistent contact matter most.",
      "Choose an optical arm sensor when comfort and easy placement matter more than the quickest response.",
      "Verify Bluetooth, ANT+ and simultaneous connection support against every device you use.",
      "A secure fit and fresh battery matter more than extra metrics you will not act on.",
      "Heart-rate readings are training inputs, not diagnoses.",
    ],
    medicalNote: "Heart-rate monitors estimate pulse for training. They do not diagnose or rule out a medical condition. Seek qualified medical advice for symptoms, unusual readings or health decisions.",
    definition: {
      title: "What a running heart-rate monitor does",
      paragraphs: [
        "A heart-rate monitor measures pulse during activity and sends the result to a watch, phone, bike computer or training app. Dedicated sensors usually use either electrical sensing at the chest or optical sensing on the arm.",
        "Chest straps detect the electrical timing of heartbeats through skin contact. Optical sensors shine light into tissue and estimate changes in blood flow; moving them from wrist to upper arm often improves stability during running.",
        "The useful choice is not the sensor with the longest feature list. It is the one that stays in place, connects to your equipment and produces dependable enough data for the decisions in your training.",
      ],
    },
    whyItMatters: {
      title: "Why sensor choice changes the data",
      paragraphs: [
        "Intervals, hills and abrupt pace changes expose lag or poor contact more clearly than steady running. If you use heart rate to control repetitions or thresholds, response and signal stability matter.",
        "A technically capable sensor still fails if it chafes, slips, dries out or cannot connect to two devices at once. Fit, protocol support and maintenance determine whether it becomes a routine tool.",
      ],
    },
    factors: {
      title: "Five factors to check",
      cards: [
        { id: "sensor", title: "Sensor method", whatItIs: "Electrical chest sensing or optical arm sensing.", howItChanges: "Electrical sensing responds directly to cardiac signals; optical sensing estimates blood-flow changes.", whatYouNotice: "Different response speed, placement and comfort." },
        { id: "fit", title: "Placement and fit", whatItIs: "How the strap or band maintains contact.", howItChanges: "Movement, dry electrodes and loose tension can interrupt readings.", whatYouNotice: "Fewer spikes, dropouts and distractions." },
        { id: "connections", title: "Connections", whatItIs: "Bluetooth, ANT+ and concurrent device limits.", howItChanges: "Protocols determine which watches, apps and gym equipment can receive data.", whatYouNotice: "Whether your full setup works without re-pairing." },
        { id: "battery", title: "Battery and care", whatItIs: "Replaceable-cell or rechargeable runtime plus cleaning needs.", howItChanges: "Storage, sweat and charging habits affect reliability.", whatYouNotice: "Less chance of a dead sensor before a key run." },
        { id: "extras", title: "Stored data and extras", whatItIs: "Onboard memory, running dynamics or standalone recording.", howItChanges: "Extra functions can help when a watch is absent or a platform supports them.", whatYouNotice: "Useful workflow gains only when your devices can consume the data." },
      ],
    },
    comparison: {
      title: "Chest strap or optical arm sensor?",
      columns: ["Chest strap", "Optical arm sensor", "Decision"],
      rows: [
        { label: "Fast changes", values: ["Usually strongest", "May show some lag", "Chest for tightly controlled intervals"] },
        { label: "Comfort", values: ["Pressure around torso", "Band on upper or lower arm", "Choose the placement you will keep wearing"] },
        { label: "Contact", values: ["Electrodes need skin contact", "Optical fit must block movement and light", "Both require deliberate setup"] },
        { label: "Maintenance", values: ["Wash strap; often replace coin cell", "Wipe sensor; recharge", "Match your routine"] },
      ],
      footnote: "Individual fit and conditions can outweigh category tendencies.",
    },
    tradeoffs: {
      title: "Accuracy, comfort and convenience",
      gains: ["Cleaner workout data than a poorly fitted wrist sensor", "More stable readings in many hard sessions", "Direct connection to compatible training devices"],
      giveUps: ["Another item to fit, clean and power", "Chest straps can chafe or feel restrictive", "Optical arm sensors can lag during rapid intensity changes"],
    },
    callouts: [{ id: "hr-not-diagnosis", title: "Heart rate is not a diagnosis", body: "Treat the number as training information. A consumer sensor cannot explain symptoms, diagnose a condition or confirm that a concerning reading is harmless.", tone: "caution" }],
    decision: {
      title: "Choose a monitor in six steps",
      steps: [
        { id: "use", title: "Define the workout", body: "State whether you need steady trends, interval response or standalone recording." },
        { id: "method", title: "Choose the sensor method", body: "Start with chest for rapid response or arm optical for placement comfort." },
        { id: "devices", title: "List every receiver", body: "Include watch, phone, treadmill, bike computer and app." },
        { id: "protocols", title: "Verify protocols", body: "Confirm Bluetooth, ANT+ and simultaneous connection limits." },
        { id: "fit", title: "Test fit in motion", body: "Reject slipping, pressure, chafing or inconsistent contact." },
        { id: "care", title: "Accept the upkeep", body: "Choose a battery and cleaning routine you will actually maintain." },
      ],
    },
    examples: {
      title: "Three useful sensor approaches",
      disclaimer: "These products illustrate different approaches, not a universal ranking. Check current compatibility before buying.",
      items: [
        { productId: "prod-hrm-pro-plus", approachLabel: "Connected chest strap", whyIllustrates: "Shows a feature-rich electrical strap with broad training-device integration.", bestFor: ["Intervals", "Garmin users", "Multi-device training"], tradeoff: "Chest placement and a premium feature set are more than some runners need." },
        { productId: "prod-polar-h10", approachLabel: "Accuracy-first chest strap", whyIllustrates: "Represents a focused chest sensor widely used for stable heart-rate capture.", bestFor: ["Structured workouts", "Broad app use", "Runners prioritising signal quality"], tradeoff: "Still requires chest contact, strap care and compatibility checks." },
        { productId: "prod-polar-verity-sense", approachLabel: "Optical arm sensor", whyIllustrates: "Demonstrates the comfort and placement alternative to a chest strap.", bestFor: ["Chest-strap avoiders", "Steady running", "Multi-sport use"], tradeoff: "Optical sensing may respond less quickly to sharp intensity changes." },
      ],
    },
    compareProductIds: ["prod-hrm-pro-plus", "prod-polar-h10", "prod-polar-verity-sense"],
    bestGuideHref: "/best/heart-rate-monitors-running",
    bestGuideLabel: "Best Heart-Rate Monitors for Running →",
    mistakes: [
      { id: "method-only", title: "Buying by sensor method alone", body: "Fit and connection support can matter as much as chest versus optical." },
      { id: "protocol", title: "Assuming every device connects", body: "Check protocols and simultaneous connection limits before purchase." },
      { id: "dry", title: "Ignoring contact preparation", body: "A loose optical band or dry chest electrodes can create bad data." },
      { id: "care", title: "Skipping cleaning and battery care", body: "Sweat residue and weak power undermine reliability." },
      { id: "medical", title: "Treating readings as medical certainty", body: "A training sensor does not diagnose symptoms or disease." },
    ],
    ctaBest: { title: "Compare current heart-rate monitors", body: "See current picks by accuracy, comfort, connectivity and value.", ctaLabel: "Best heart-rate monitors →", href: "/best/heart-rate-monitors-running" },
    productExampleRoles: [
      { productId: "prod-hrm-pro-plus", roleLabel: "Connected chest strap" },
      { productId: "prod-polar-h10", roleLabel: "Accuracy-first chest strap" },
      { productId: "prod-polar-verity-sense", roleLabel: "Optical arm sensor" },
    ],
    productRailTitle: "Compare heart-rate sensor approaches",
  },
  {
    slug: "how-to-choose-running-hydration-vest",
    displayTitle: "How to Choose a Running Hydration Vest",
    deck: "Size the vest around water, mandatory kit and fit at full load—not a claimed capacity you may never use.",
    eyebrow: "Buying Guide",
    heroImageSrc: "/images/packs/products/salomon-adv-skin-12-hero.jpg",
    heroImageAlt: "Salomon ADV Skin 12 running hydration vest",
    quickAnswerBullets: [
      "Choose capacity from your longest unsupported outing and mandatory kit.",
      "Test fit with the flasks filled and every pocket loaded.",
      "Front flasks make drinking and refilling simple; a bladder shifts more water to the back.",
      "Pocket access, bounce control and chafe prevention matter more than unused litres.",
      "Confirm replacement flask and bladder compatibility before committing.",
    ],
    definition: {
      title: "What a hydration vest is",
      paragraphs: [
        "A running hydration vest is a close-fitting pack that spreads water and gear across the torso. It uses shoulder, side and sternum adjustment to limit bounce while keeping key items reachable.",
        "Capacity includes both fluid and storage. Small vests suit short supported runs; larger models carry layers, food, safety equipment and water for long or remote outings.",
        "The right volume is the smallest one that carries the required load comfortably. An oversized vest can encourage overpacking, while an undersized vest forces awkward pockets or leaves essentials behind.",
      ],
    },
    whyItMatters: {
      title: "Why load and fit come first",
      paragraphs: [
        "A vest that feels fine empty can bounce, compress breathing or rub once flasks and kit add weight. Fit must be judged in the loaded condition you will actually run in.",
        "Storage layout changes how often you stop. Reachable food, phone, poles and layers make a modest capacity more useful than a larger pack with inaccessible pockets.",
      ],
    },
    factors: {
      title: "Five hydration-vest decisions",
      cards: [
        { id: "capacity", title: "Usable capacity", whatItIs: "Space for fluid, layers, food and required equipment.", howItChanges: "Longer gaps between support increase the load.", whatYouNotice: "Whether gear fits without swinging or overstuffing." },
        { id: "fit", title: "Loaded fit", whatItIs: "Torso sizing, sternum adjustment and side stretch.", howItChanges: "Water weight alters tension and bounce.", whatYouNotice: "Stable carry without restricted breathing." },
        { id: "fluid", title: "Fluid format", whatItIs: "Soft flasks, reservoir or both.", howItChanges: "Front flasks simplify access; reservoirs centralise volume.", whatYouNotice: "Different refill, balance and cleaning routines." },
        { id: "access", title: "Pocket access", whatItIs: "Placement of food, phone, shell and poles.", howItChanges: "Stretch and opening direction determine one-handed reach.", whatYouNotice: "Fewer stops and less unloading." },
        { id: "weather", title: "Fabric and weather", whatItIs: "Breathability, drainage and weather-resistant storage.", howItChanges: "Heat, rain and sweat change comfort and protection needs.", whatYouNotice: "Less heat buildup and better protection for sensitive gear." },
      ],
    },
    comparison: {
      title: "Choose vest volume by the job",
      columns: ["Small vest", "Mid-volume vest", "Larger vest"],
      rows: [
        { label: "Typical use", values: ["Short supported runs", "Long runs and many trail races", "Remote or kit-heavy days"] },
        { label: "Load discipline", values: ["Forces a tight list", "Balances access and reserve", "Carries more but invites overpacking"] },
        { label: "Hydration", values: ["Usually front flasks", "Flasks and often bladder support", "Higher combined capacity"] },
        { label: "Best test", values: ["Phone, keys and fluid", "Full race kit", "Cold-weather or all-day load"] },
      ],
    },
    tradeoffs: {
      title: "Capacity has a cost",
      gains: ["More fluid and mandatory-kit room", "Better load distribution than handheld bottles", "Reachable storage while moving"],
      giveUps: ["More fabric, heat and weight", "Extra volume can bounce when poorly packed", "More pockets and hydration parts to clean"],
    },
    callouts: [{ id: "water-plan", title: "A vest is not a water plan", body: "Capacity does not guarantee enough water. Plan refill points and carry for conditions, duration and route risk; do not rely on an untested source.", tone: "caution" }],
    decision: {
      title: "Choose a vest in six steps",
      steps: [
        { id: "route", title: "Define the longest gap", body: "Estimate time between reliable water and support points." },
        { id: "kit", title: "Lay out required kit", body: "Include layers, food, phone and event-mandated items." },
        { id: "volume", title: "Set minimum volume", body: "Choose the smallest capacity that accepts that full load." },
        { id: "fluid", title: "Choose fluid format", body: "Decide between front flasks, bladder or a mixed setup." },
        { id: "fit", title: "Load-test the fit", body: "Run with full bottles and adjust without restricting breathing." },
        { id: "access", title: "Reach every essential", body: "Confirm you can use food, phone, poles and layers as intended." },
      ],
    },
    examples: {
      title: "Three hydration components and approaches",
      disclaimer: "Examples show different roles. Confirm sizing, included flasks and reservoir compatibility.",
      items: [
        { productId: "prod-adv-skin-12", approachLabel: "High-capacity race vest", whyIllustrates: "Shows a close-fitting vest designed around substantial trail kit and front access.", bestFor: ["Long trail days", "Ultras", "Mandatory-kit races"], tradeoff: "More volume, fabric and cost than short runs require." },
        { productId: "prod-nathan-vaporair-2", approachLabel: "Balanced running vest", whyIllustrates: "Represents a conventional vest setup balancing hydration and reachable storage.", bestFor: ["Long training runs", "Trail races", "Runners wanting distributed carry"], tradeoff: "Fit remains body-specific and must be tested loaded." },
        { productId: "prod-soft-flask-500", approachLabel: "Replaceable soft flask", whyIllustrates: "Highlights that bottle shape, bite valve and pocket compatibility are part of the system.", bestFor: ["Front-flask vests", "Quick refills", "Replacing worn hydration parts"], tradeoff: "A flask is useful only when it fits the chosen vest securely." },
      ],
    },
    compareProductIds: ["prod-adv-skin-12", "prod-nathan-vaporair-2", "prod-soft-flask-500"],
    bestGuideHref: "/best/running-hydration-vests",
    bestGuideLabel: "Best Running Hydration Vests →",
    mistakes: [
      { id: "empty-fit", title: "Trying the vest empty", body: "Water and gear change bounce, pressure and adjustment." },
      { id: "litres", title: "Buying unused capacity", body: "Extra space adds fabric and encourages unnecessary load." },
      { id: "reach", title: "Ignoring pocket reach", body: "A pocket is not useful if you must remove the vest to use it." },
      { id: "flasks", title: "Assuming any flask fits", body: "Bottle dimensions and pocket retention vary." },
      { id: "first-race", title: "Using it first on race day", body: "Load, adjust and run long enough to expose bounce or rubbing." },
    ],
    ctaBest: { title: "Compare current hydration vests", body: "See current choices by capacity, fit, access and value.", ctaLabel: "Best running hydration vests →", href: "/best/running-hydration-vests" },
    productExampleRoles: [
      { productId: "prod-adv-skin-12", roleLabel: "High-capacity race vest" },
      { productId: "prod-nathan-vaporair-2", roleLabel: "Balanced running vest" },
      { productId: "prod-soft-flask-500", roleLabel: "Replaceable soft flask" },
    ],
    productRailTitle: "Compare hydration carry approaches",
  },
  {
    slug: "how-to-choose-running-headlamp",
    displayTitle: "How to Choose a Running Headlamp",
    deck: "Choose beam shape, stable output and fit for your route—not the largest lumen number on the box.",
    eyebrow: "Buying Guide",
    heroImageSrc: "/images/headlamps/products/petzl-swift-rl-hero.jpg",
    heroImageAlt: "Petzl Swift RL running headlamp",
    quickAnswerBullets: [
      "Use a wide, even beam for close terrain and enough throw to read farther ahead at speed.",
      "Compare sustained output and runtime, not peak lumens alone.",
      "Balance the lamp on your head and test bounce with your usual hat.",
      "Choose controls you can operate with cold or wet hands.",
      "Carry backup light when darkness would make a failure consequential.",
    ],
    definition: {
      title: "What makes a headlamp suitable for running",
      paragraphs: [
        "A running headlamp puts hands-free light in the direction you look. The useful beam must reveal nearby footing while giving enough forward visibility for your speed and terrain.",
        "Lumens describe total light output, not beam quality or how long that output lasts. Optics, automatic dimming, heat and battery management determine what you see after the first minutes.",
        "Running also demands stability. Weight distribution, strap geometry, battery placement and compatibility with hats decide whether the lamp stays aimed without excessive tension.",
      ],
    },
    whyItMatters: {
      title: "Why headline brightness is incomplete",
      paragraphs: [
        "A narrow bright hotspot can hide peripheral terrain, while a broad flood can lack forward reach. Mixed road and trail running benefits from a controlled blend.",
        "Many lamps step down from maximum output to manage heat and battery. Real usefulness depends on the sustained mode that covers the whole run.",
      ],
    },
    factors: {
      title: "Five headlamp factors",
      cards: [
        { id: "beam", title: "Beam pattern", whatItIs: "The balance of flood, hotspot and forward throw.", howItChanges: "Optics distribute the same lumen output differently.", whatYouNotice: "Terrain detail nearby and warning farther ahead." },
        { id: "runtime", title: "Sustained runtime", whatItIs: "Useful light duration in a repeatable mode.", howItChanges: "High output, cold and automatic modes change drain.", whatYouNotice: "Whether visibility remains adequate at the end." },
        { id: "fit", title: "Stability and balance", whatItIs: "Lamp weight, straps and battery location.", howItChanges: "Rear battery packs can balance a heavier front.", whatYouNotice: "Less bounce and less need to overtighten." },
        { id: "controls", title: "Controls", whatItIs: "Buttons, lockout and reactive-light behaviour.", howItChanges: "Gloves, rain and mode sequences affect operation.", whatYouNotice: "Faster changes without stopping or accidental activation." },
        { id: "weather", title: "Weather and power", whatItIs: "Ingress rating and rechargeable or replaceable batteries.", howItChanges: "Rain, cold and trip length set resilience needs.", whatYouNotice: "More dependable operation and a practical backup plan." },
      ],
    },
    comparison: {
      title: "Match the beam to the route",
      columns: ["Lit road", "Dark road", "Technical trail"],
      rows: [
        { label: "Priority", values: ["Be seen and fill dark patches", "Forward reach plus edge visibility", "Wide terrain detail plus controlled throw"] },
        { label: "Output", values: ["Modest can be enough", "Stable medium/high mode", "Higher sustained output often useful"] },
        { label: "Fit", values: ["Lightweight simplicity", "Secure single or top strap", "Maximum bounce control"] },
        { label: "Backup", values: ["Route dependent", "Recommended", "Essential when failure strands you"] },
      ],
    },
    tradeoffs: {
      title: "Brightness, runtime and weight",
      gains: ["Higher output supports faster running in full darkness", "Larger batteries extend useful runtime", "Reactive modes can reduce manual changes"],
      giveUps: ["More output consumes battery and creates heat", "Larger batteries add weight", "Complex modes can make controls harder to predict"],
    },
    callouts: [{ id: "backup-light", title: "Plan for light failure", body: "For remote routes or full-dark finishes, carry an independent backup and know the route. A phone flashlight is not a robust primary contingency.", tone: "caution" }],
    decision: {
      title: "Choose a headlamp in six steps",
      steps: [
        { id: "darkness", title: "Define the route", body: "Separate lit streets, unlit roads and technical trails." },
        { id: "speed", title: "Account for speed", body: "Faster running needs useful visibility farther ahead." },
        { id: "beam", title: "Choose beam shape", body: "Prioritise an even flood, suitable throw or a mixed pattern." },
        { id: "runtime", title: "Set sustained runtime", body: "Use the mode you need and add cold-weather reserve." },
        { id: "fit", title: "Run-test the fit", body: "Test with your normal hat and reject bounce or pressure." },
        { id: "backup", title: "Build redundancy", body: "Carry backup light where a failure has real consequences." },
      ],
    },
    examples: {
      title: "Three running-headlamp approaches",
      disclaimer: "These examples illustrate beam, power and fit strategies. Verify current modes and runtimes.",
      items: [
        { productId: "prod-petzl-swift-rl", approachLabel: "High-output reactive lamp", whyIllustrates: "Shows automatic output adjustment and strong illumination in a compact running-focused format.", bestFor: ["Dark trails", "Faster night running", "Reactive-light users"], tradeoff: "Premium price and mode behaviour require familiarisation." },
        { productId: "prod-bd-spot-400-r", approachLabel: "Compact rechargeable lamp", whyIllustrates: "Represents a simpler all-round rechargeable option with moderate output.", bestFor: ["Road running", "Mixed outdoor use", "Buyers prioritising compactness"], tradeoff: "Less specialised balance and output than some trail-running systems." },
        { productId: "prod-silva-trail-runner-free", approachLabel: "Balanced running system", whyIllustrates: "Highlights distributed weight and a beam designed around movement.", bestFor: ["Long night runs", "Runners sensitive to front weight", "Trail use"], tradeoff: "More straps and external power routing than a basic lamp." },
      ],
    },
    compareProductIds: ["prod-petzl-swift-rl", "prod-bd-spot-400-r", "prod-silva-trail-runner-free"],
    bestGuideHref: "/best/running-headlamps",
    bestGuideLabel: "Best Running Headlamps →",
    mistakes: [
      { id: "lumens", title: "Buying peak lumens", body: "Peak output says little about beam shape or sustained runtime." },
      { id: "walk-test", title: "Testing only while standing", body: "Running reveals bounce, pressure and beam movement." },
      { id: "runtime-mode", title: "Using the wrong runtime figure", body: "Compare the exact brightness mode needed for the route." },
      { id: "controls", title: "Ignoring controls", body: "Gloves and rain can make small buttons difficult." },
      { id: "backup", title: "Skipping backup light", body: "A single failure can become a navigation and safety problem." },
    ],
    ctaBest: { title: "Compare current running headlamps", body: "See current choices by beam, runtime, fit and value.", ctaLabel: "Best running headlamps →", href: "/best/running-headlamps" },
    productExampleRoles: [
      { productId: "prod-petzl-swift-rl", roleLabel: "High-output reactive lamp" },
      { productId: "prod-bd-spot-400-r", roleLabel: "Compact rechargeable lamp" },
      { productId: "prod-silva-trail-runner-free", roleLabel: "Balanced running system" },
    ],
    productRailTitle: "Compare running-light approaches",
  },
  {
    slug: "hydration-vest-vs-running-belt",
    displayTitle: "Hydration Vest vs Running Belt",
    deck: "Use a belt for compact loads and a vest when water, layers or mandatory kit exceed stable waist carry.",
    heroImageSrc: "/images/packs/products/nathan-vaporair-2-hero.png",
    heroImageAlt: "Nathan VaporAir 2 running hydration vest",
    quickAnswerBullets: [
      "A belt is the lower-coverage choice for phone, keys, fuel and modest fluid.",
      "A vest carries more water and layers with better load distribution.",
      "The crossover point is the load that stays stable and reachable, not a fixed distance.",
      "Test either option fully loaded at running pace.",
      "For races, mandatory kit can decide before personal preference does.",
    ],
    definition: {
      title: "The practical difference",
      paragraphs: [
        "A running belt concentrates a compact load around the waist. It offers low coverage and quick simplicity when you need a phone, keys, fuel or a small amount of water.",
        "A hydration vest spreads a larger load across the chest, shoulders and back. Front pockets can hold flasks and food while rear storage carries layers and safety kit.",
        "Neither is automatically better by distance. Weather, refill access, mandatory equipment and what your body tolerates determine when a belt stops being enough.",
      ],
    },
    whyItMatters: {
      title: "Why the carry system changes the run",
      paragraphs: [
        "As load grows, a belt can bounce, rotate or press into the waist. A well-fitted vest distributes that weight but adds heat, fabric and adjustment.",
        "Access matters alongside capacity. The best system lets you eat, drink and retrieve essentials without disrupting pace or unpacking everything.",
      ],
    },
    factors: {
      title: "Five ways to decide",
      cards: [
        { id: "load", title: "Total load", whatItIs: "Water, phone, food, layers and safety equipment.", howItChanges: "Longer unsupported time increases weight and bulk.", whatYouNotice: "The point where compact waist carry loses stability." },
        { id: "water", title: "Water volume", whatItIs: "Fluid needed between reliable refills.", howItChanges: "Heat and route access alter the requirement.", whatYouNotice: "Whether bottles fit without dominating the carry." },
        { id: "access", title: "Access", whatItIs: "Ability to reach food, phone and layers.", howItChanges: "Front vest pockets provide more zones; belts keep fewer items close.", whatYouNotice: "How often you stop or remove gear." },
        { id: "coverage", title: "Coverage and heat", whatItIs: "Fabric against torso or waist.", howItChanges: "Vests cover more area and may trap more warmth.", whatYouNotice: "Different comfort in hot or humid weather." },
        { id: "movement", title: "Movement control", whatItIs: "Fit, tension and load placement.", howItChanges: "Uneven packing creates bounce in either system.", whatYouNotice: "Rotation, sloshing, pressure or chafe." },
      ],
    },
    comparison: {
      title: "Vest and belt compared",
      columns: ["Hydration vest", "Running belt"],
      rows: [
        { label: "Best load", values: ["Water, layers, food and kit", "Phone, keys, fuel and compact fluid"] },
        { label: "Coverage", values: ["Higher torso coverage", "Low coverage around waist"] },
        { label: "Access", values: ["Multiple front and rear pockets", "Simple but limited storage"] },
        { label: "Adjustment", values: ["More fit points", "Waist tension and placement"] },
        { label: "Typical limit", values: ["Heat and unnecessary bulk", "Bounce or pressure as load grows"] },
      ],
    },
    tradeoffs: {
      title: "More carry or less coverage",
      gains: ["Vests distribute larger loads and offer more access", "Belts are light, simple and cooler", "Both keep hands free"],
      giveUps: ["Vests add fabric, heat and adjustment", "Belts become unstable with bulky loads", "Poor packing causes bounce in either system"],
    },
    callouts: [{ id: "mandatory-kit", title: "Check the race rules first", body: "A preferred belt is irrelevant if mandatory water, layers or safety equipment will not fit. Pack the published kit list before choosing.", tone: "caution" }],
    decision: {
      title: "Choose your carry system",
      steps: [
        { id: "kit", title: "Lay out the load", body: "Include water, phone, food, layers and mandatory items." },
        { id: "refills", title: "Map refill gaps", body: "Carry for the longest reliable gap, not total event distance." },
        { id: "belt-test", title: "Try the smallest system", body: "Use a belt if the full load stays compact and stable." },
        { id: "vest-point", title: "Recognise the crossover", body: "Move to a vest when water or layers cause bounce, pressure or poor access." },
        { id: "run", title: "Test at pace", body: "Load everything and run over representative terrain." },
        { id: "adjust", title: "Practise access", body: "Drink, eat and retrieve the phone without stopping." },
      ],
    },
    examples: {
      title: "Three carry-system examples",
      disclaimer: "Examples show capacity and access strategies rather than one winner for every run.",
      items: [
        { productId: "prod-adv-skin-12", approachLabel: "Full hydration vest", whyIllustrates: "Shows the capacity and distributed access suited to water, layers and race kit.", bestFor: ["Long unsupported runs", "Trail races", "Large mandatory-kit loads"], tradeoff: "More coverage and capacity than routine short runs need." },
        { productId: "prod-flipbelt-classic", approachLabel: "Broad stretch belt", whyIllustrates: "Demonstrates low-profile storage distributed around the waist.", bestFor: ["Phone and keys", "Road running", "Minimalist carry"], tradeoff: "Limited structure and hydration capacity for heavier loads." },
        { productId: "prod-spibelt-original", approachLabel: "Compact expandable belt", whyIllustrates: "Represents the smallest practical solution for a few essentials.", bestFor: ["Short runs", "Small phones and keys", "Low-coverage carry"], tradeoff: "Concentrated storage can bounce when overfilled." },
      ],
    },
    compareProductIds: ["prod-adv-skin-12", "prod-flipbelt-classic", "prod-spibelt-original"],
    bestGuideHref: "/best/running-hydration-vests",
    bestGuideLabel: "Best Running Hydration Vests →",
    decisionLinks: [
      { label: "Best hydration vests →", href: "/best/running-hydration-vests" },
      { label: "Best running belts →", href: "/best/running-belts" },
    ],
    mistakes: [
      { id: "distance", title: "Choosing by distance alone", body: "Support, heat and mandatory kit change the carry requirement." },
      { id: "empty", title: "Testing empty", body: "Water and a phone reveal movement and pressure." },
      { id: "overfill", title: "Overfilling a belt", body: "A compact belt stops working when the load becomes bulky." },
      { id: "heat", title: "Ignoring vest heat", body: "Extra torso coverage can matter in warm conditions." },
      { id: "access", title: "Packing without access", body: "Frequently used items should be reachable while moving." },
    ],
    ctaBest: { title: "Compare both carry categories", body: "Start with the category that fits your full load, then compare current options.", ctaLabel: "Best hydration vests →", href: "/best/running-hydration-vests" },
    productExampleRoles: [
      { productId: "prod-adv-skin-12", roleLabel: "Full hydration vest" },
      { productId: "prod-flipbelt-classic", roleLabel: "Broad stretch belt" },
      { productId: "prod-spibelt-original", roleLabel: "Compact expandable belt" },
    ],
    productRailTitle: "Compare vest and belt carry",
  },
  {
    slug: "multi-band-gps-running-watches",
    displayTitle: "Multi-Band GPS Running Watches Explained",
    deck: "Multi-band GNSS can improve tracks in difficult reception, but antenna design, software and battery mode still decide the result.",
    heroImageSrc: "/images/watches/products/coros-pace-pro-hero.png",
    heroImageAlt: "COROS Pace Pro multi-band GPS running watch",
    quickAnswerBullets: [
      "Multi-band uses more than one satellite frequency to reduce some reflected-signal errors.",
      "It is most useful around tall buildings, cliffs, forests and other obstructed routes.",
      "It does not guarantee perfect pace, distance or tracks.",
      "Higher-accuracy modes usually consume more battery.",
      "Buy it when your real routes expose a problem—not as a default badge of quality.",
    ],
    definition: {
      title: "What multi-band GPS means",
      paragraphs: [
        "A running watch calculates position from satellite navigation systems, collectively called GNSS. Multi-band or dual-frequency reception listens on more than one frequency from compatible satellites.",
        "The second frequency can help the watch identify and reduce some errors caused by signals reflecting from buildings or terrain before reaching the antenna. It can also improve resilience when the sky view is restricted.",
        "The receiver is only one part of the system. Antenna placement, algorithms, recording settings and satellite geometry still affect the track and live pace.",
      ],
    },
    whyItMatters: {
      title: "Where multi-band earns its battery",
      paragraphs: [
        "Open roads with a clear sky often give a good standard GNSS watch enough signal. In urban canyons, dense forest and steep terrain, reflected or blocked signals make the extra frequency more valuable.",
        "The practical gain is a cleaner route and more credible pace through difficult sections, not laboratory precision. Runners should compare the hardest route they actually use.",
      ],
    },
    factors: {
      title: "Five factors beyond the label",
      cards: [
        { id: "environment", title: "Environment", whatItIs: "Buildings, tree cover, cliffs and sky visibility.", howItChanges: "Obstructions increase reflected and blocked signals.", whatYouNotice: "More track drift and unstable pace in hard sections." },
        { id: "mode", title: "GNSS mode", whatItIs: "GPS-only, all-systems, multi-band or automatic selection.", howItChanges: "More signals can improve resilience while using more power.", whatYouNotice: "Different accuracy and runtime from the same watch." },
        { id: "antenna", title: "Antenna and software", whatItIs: "Hardware placement and position-processing algorithms.", howItChanges: "Good implementation can outperform a weak specification.", whatYouNotice: "Model-level differences despite matching labels." },
        { id: "battery", title: "Battery cost", whatItIs: "Runtime while recording in the selected mode.", howItChanges: "Multi-band and bright displays increase drain.", whatYouNotice: "Less reserve on long events." },
        { id: "pace", title: "Pace behaviour", whatItIs: "How position data becomes live pace and distance.", howItChanges: "Smoothing can stabilise pace but delay changes.", whatYouNotice: "A steadier number that may still lag intervals." },
      ],
    },
    comparison: {
      title: "Choose the right GNSS mode",
      columns: ["Standard/all-systems", "Multi-band", "Automatic mode"],
      rows: [
        { label: "Open sky", values: ["Often sufficient", "Small practical gain", "Can save power by scaling down"] },
        { label: "Urban/forest", values: ["More vulnerable to error", "Usually most valuable", "Quality depends on implementation"] },
        { label: "Battery", values: ["Lower demand", "Higher demand", "Variable compromise"] },
        { label: "Control", values: ["Predictable economy", "Predictable maximum accuracy", "Convenient but less transparent"] },
      ],
    },
    tradeoffs: {
      title: "Cleaner tracks versus longer runtime",
      gains: ["Better resilience in difficult reception", "Cleaner route traces in many obstructed environments", "More dependable distance and pace inputs"],
      giveUps: ["Higher GPS battery consumption", "No guarantee of perfect instant pace", "Higher product cost if bundled with flagship features"],
    },
    callouts: [{ id: "navigation-limit", title: "Accuracy does not replace preparation", body: "A precise track does not guarantee correct maps, a safe route or a working device. Carry appropriate route backup for consequential terrain.", tone: "caution" }],
    finder: { toolSlug: "fitness-watch-finder", title: "Match a watch to your routes", description: "Filter around GPS environment, battery, maps and training needs.", ctaLabel: "Find my fitness watch →" },
    decision: {
      title: "Decide if multi-band is worth it",
      steps: [
        { id: "route", title: "Name the hard route", body: "Identify buildings, forest, cliffs or switchbacks that disrupt tracks." },
        { id: "problem", title: "Define the problem", body: "Separate cosmetic track wobble from unusable pace or navigation." },
        { id: "battery", title: "Set the battery floor", body: "Require enough runtime in the actual multi-band mode." },
        { id: "model", title: "Compare model evidence", body: "Look beyond the label to antenna and software performance." },
        { id: "features", title: "Avoid feature spillover", body: "Do not pay for maps or analytics you do not need merely to get multi-band." },
        { id: "settings", title: "Use modes deliberately", body: "Enable maximum accuracy only where its benefit justifies the drain." },
      ],
    },
    examples: {
      title: "Three levels of running-watch GPS",
      disclaimer: "These watches illustrate product positioning. Firmware, modes and performance can change.",
      items: [
        { productId: "prod-forerunner-970", approachLabel: "Flagship multi-band watch", whyIllustrates: "Combines multi-band reception with maps and a deep training platform.", bestFor: ["Difficult routes", "Navigation", "Feature-heavy training"], tradeoff: "Premium cost and complexity exceed many runners' needs." },
        { productId: "prod-coros-pace-pro", approachLabel: "Light multi-band option", whyIllustrates: "Shows multi-band and maps in a lighter performance-focused package.", bestFor: ["Road and trail training", "Weight-conscious runners", "Battery-minded map users"], tradeoff: "Its ecosystem and extras differ from larger smartwatch platforms." },
        { productId: "prod-forerunner-165", approachLabel: "Standard-GPS alternative", whyIllustrates: "Demonstrates that a capable running watch can serve open routes without multi-band.", bestFor: ["Open-road running", "First GPS watch", "Simpler training needs"], tradeoff: "Less resilient positioning in the most difficult environments." },
      ],
    },
    compareProductIds: ["prod-forerunner-970", "prod-coros-pace-pro", "prod-forerunner-165"],
    bestGuideHref: "/best/running-watches",
    bestGuideLabel: "Best Running Watches →",
    mistakes: [
      { id: "perfect", title: "Expecting perfect tracks", body: "Multi-band reduces some errors; it does not remove every source." },
      { id: "everywhere", title: "Using it everywhere", body: "Open routes may not justify the additional battery drain." },
      { id: "label", title: "Comparing the label only", body: "Antenna, firmware and algorithms create model-level differences." },
      { id: "battery", title: "Reading the wrong battery figure", body: "Use multi-band GPS runtime, not smartwatch runtime." },
      { id: "flagship", title: "Buying unrelated extras", body: "Do not let one GPS requirement force an unnecessary flagship bundle." },
    ],
    ctaFinder: { title: "Build a route-based shortlist", body: "Use the finder to balance GPS mode against battery, maps and training features.", ctaLabel: "Use the Fitness Watch Finder →", href: "/tools/fitness-watch-finder" },
    ctaBest: { title: "Compare current running watches", body: "See current recommendations across value, training and endurance roles.", ctaLabel: "Best running watches →", href: "/best/running-watches" },
    productExampleRoles: [
      { productId: "prod-forerunner-970", roleLabel: "Flagship multi-band watch" },
      { productId: "prod-coros-pace-pro", roleLabel: "Light multi-band option" },
      { productId: "prod-forerunner-165", roleLabel: "Standard-GPS alternative" },
    ],
    productRailTitle: "Compare GPS watch approaches",
  },
  {
    slug: "open-ear-vs-in-ear-running-headphones",
    displayTitle: "Open-Ear vs In-Ear Running Headphones",
    deck: "Choose open-ear for less isolation or in-ear for stronger sound and noise control—then verify fit, controls and route awareness.",
    heroImageSrc: "/images/headphones/products/shokz-openrun-pro-2-hero.png",
    heroImageAlt: "Shokz OpenRun Pro 2 open-ear running headphones",
    quickAnswerBullets: [
      "Open-ear designs leave the ear canal open and reduce isolation from surrounding sound.",
      "In-ear buds usually deliver stronger bass and better noise isolation.",
      "Open-ear does not guarantee that you will notice traffic, people or warnings.",
      "Fit security, wind noise, controls and sweat resistance matter during running.",
      "Use route-appropriate volume and follow local rules regardless of design.",
    ],
    definition: {
      title: "What open-ear and in-ear mean",
      paragraphs: [
        "Open-ear headphones play sound without sealing the ear canal. Bone-conduction models vibrate near the cheekbone, while other designs place small speakers near the ear.",
        "In-ear headphones place a tip or housing in the ear canal. The seal usually improves bass, detail and passive noise isolation, and many models add active noise cancellation or transparency modes.",
        "The choice is a trade between acoustic isolation, sound quality, physical fit and how much environmental sound reaches you. No design removes the need to pay attention.",
      ],
    },
    whyItMatters: {
      title: "Why the route changes the answer",
      paragraphs: [
        "On shared paths and roads, less isolation can make surrounding sounds easier to hear. Wind, playback volume, traffic direction and attention still determine what you actually notice.",
        "In quiet gyms or controlled routes, an in-ear seal can improve sound at lower volume. During hard running, tip fit, sweat and impact can make otherwise excellent earbuds loosen.",
      ],
    },
    factors: {
      title: "Five factors to compare",
      cards: [
        { id: "awareness", title: "Environmental sound", whatItIs: "How much outside sound reaches the ear.", howItChanges: "Open canals admit more sound; seals and cancellation reduce it.", whatYouNotice: "Different awareness of nearby activity, never a guarantee." },
        { id: "fit", title: "Running fit", whatItIs: "Hooks, bands, tips and housing stability.", howItChanges: "Sweat and impact expose weak fit.", whatYouNotice: "Less adjustment and fewer dropped earbuds." },
        { id: "sound", title: "Sound and wind", whatItIs: "Bass, clarity, leakage and wind interference.", howItChanges: "In-ear seals improve bass; open designs compete more with wind.", whatYouNotice: "Different intelligibility at the same route speed." },
        { id: "controls", title: "Controls", whatItIs: "Buttons, touch gestures and voice prompts.", howItChanges: "Sweat, gloves and movement affect operation.", whatYouNotice: "Whether volume and playback changes work without distraction." },
        { id: "durability", title: "Battery and sweat rating", whatItIs: "Runtime, case charging and ingress protection.", howItChanges: "Long runs and heavy sweat demand reserve and suitable protection.", whatYouNotice: "Fewer charging interruptions and failures." },
      ],
    },
    comparison: {
      title: "Open-ear and in-ear compared",
      columns: ["Open-ear", "In-ear"],
      rows: [
        { label: "Ear canal", values: ["Remains open", "Partly or fully sealed"] },
        { label: "Outside sound", values: ["Generally easier to hear", "Reduced by seal; transparency varies"] },
        { label: "Sound", values: ["Less bass, more leakage and wind competition", "Stronger bass and isolation"] },
        { label: "Fit", values: ["Hooks or neckband avoid ear tips", "Tip and housing fit are individual"] },
        { label: "Best context", values: ["Routes where lower isolation is preferred", "Controlled routes, gym or sound priority"] },
      ],
    },
    tradeoffs: {
      title: "Less isolation versus stronger sound",
      gains: ["Open-ear reduces ear-canal blockage", "In-ear usually improves bass and detail", "Both can provide secure sport-specific fits"],
      giveUps: ["Open-ear sound competes with wind and traffic", "In-ear isolation can obscure surrounding sound", "Transparency and open designs can still mask warnings at high volume"],
    },
    callouts: [{ id: "awareness-limit", title: "Awareness is never guaranteed", body: "Open-ear hardware and transparency modes do not ensure you will hear traffic, bikes, people or alarms. Keep volume appropriate, look before crossing and follow local rules.", tone: "caution" }],
    decision: {
      title: "Choose headphones in six steps",
      steps: [
        { id: "route", title: "Classify the route", body: "Separate roads, shared paths, track, treadmill and gym use." },
        { id: "isolation", title: "Choose isolation level", body: "Prefer open-ear for less isolation or in-ear when sound and sealing matter." },
        { id: "fit", title: "Test running fit", body: "Check hooks, band pressure, tips and stability under sweat." },
        { id: "wind", title: "Test real conditions", body: "Judge speech, music and controls in wind and traffic noise." },
        { id: "battery", title: "Set battery reserve", body: "Cover the longest run without depending on mid-run charging." },
        { id: "habits", title: "Set safe habits", body: "Use appropriate volume and visual checks regardless of headphone type." },
      ],
    },
    examples: {
      title: "Three running-headphone approaches",
      disclaimer: "Examples illustrate form factors rather than guaranteeing fit, awareness or safety.",
      items: [
        { productId: "prod-shokz-openrun-pro-2", approachLabel: "Bone-conduction open-ear", whyIllustrates: "Shows a neckband format that leaves the ear canal open.", bestFor: ["Runners avoiding ear tips", "Lower-isolation listening", "Secure band preference"], tradeoff: "Less isolation and bass impact than sealed in-ear buds." },
        { productId: "prod-bose-ultra-open", approachLabel: "Open-ear speaker design", whyIllustrates: "Demonstrates an open design that positions sound near rather than inside the ear.", bestFor: ["Open-ear comfort", "Casual road running", "Listeners prioritising less blockage"], tradeoff: "Premium cost and environmental noise can overpower playback." },
        { productId: "prod-airpods-pro-2", approachLabel: "Sealed in-ear with transparency", whyIllustrates: "Represents strong in-ear sound, cancellation and an electronic transparency option.", bestFor: ["Controlled routes", "Apple users", "Sound and feature priority"], tradeoff: "Tip security varies and transparency is not guaranteed awareness." },
      ],
    },
    compareProductIds: ["prod-shokz-openrun-pro-2", "prod-bose-ultra-open", "prod-airpods-pro-2"],
    bestGuideHref: "/best/running-headphones",
    bestGuideLabel: "Best Running Headphones →",
    mistakes: [
      { id: "safe", title: "Assuming open-ear means safe", body: "Attention, volume and route behaviour still matter." },
      { id: "transparency", title: "Treating transparency as natural hearing", body: "Microphones and processing can miss or distort sounds." },
      { id: "static-fit", title: "Testing fit while stationary", body: "Sweat and impact can loosen secure-feeling earbuds." },
      { id: "ip", title: "Ignoring the sweat rating", body: "Water resistance varies and does not cover every exposure." },
      { id: "controls", title: "Forgetting controls", body: "Touch gestures can become unreliable with sweat or gloves." },
    ],
    ctaBest: { title: "Compare current running headphones", body: "See current open-ear and in-ear picks by fit, sound and use case.", ctaLabel: "Best running headphones →", href: "/best/running-headphones" },
    productExampleRoles: [
      { productId: "prod-shokz-openrun-pro-2", roleLabel: "Bone-conduction open-ear" },
      { productId: "prod-bose-ultra-open", roleLabel: "Open-ear speaker design" },
      { productId: "prod-airpods-pro-2", roleLabel: "Sealed in-ear option" },
    ],
    productRailTitle: "Compare running headphone designs",
  },
];

export const runningRemainingConfigs = RUNNING_REMAINING_PLANS.map(
  buildExplainerFromPlan,
);

export const runningRemainingFaqs: {
  id: string;
  question: string;
  answer: string;
  sportId?: string;
  categoryId?: string;
}[] = [
  { id: "faq-hrm-choose-1", question: "Is a chest strap more accurate than an optical arm monitor?", answer: "A well-fitted chest strap usually responds faster to sharp intensity changes. A good optical arm sensor can be dependable for steady running and may be more comfortable.", sportId: "sport-running" },
  { id: "faq-hrm-choose-2", question: "Do I need ANT+ and Bluetooth?", answer: "Only if your devices require both. List every watch, phone, app and machine you plan to connect, then verify protocols and simultaneous connection limits.", sportId: "sport-running" },
  { id: "faq-hrm-choose-3", question: "Why does my heart-rate monitor spike or drop out?", answer: "Common causes include loose fit, dry chest electrodes, movement, cold conditions, weak battery or wireless interference. Correct setup before interpreting the data.", sportId: "sport-running" },
  { id: "faq-hrm-choose-4", question: "Can a running heart-rate monitor detect a medical problem?", answer: "It can show a reading that deserves attention, but it cannot diagnose or rule out a condition. Seek qualified medical advice for symptoms or concerns.", sportId: "sport-running" },
  { id: "faq-vest-choose-1", question: "What size hydration vest do I need?", answer: "Choose the smallest capacity that holds water, food, layers and mandatory kit for your longest unsupported outing without overstuffing.", sportId: "sport-running" },
  { id: "faq-vest-choose-2", question: "Are front flasks better than a bladder?", answer: "Front flasks are easy to monitor and refill. A bladder can carry more water centrally but is harder to inspect and refill. Many vests support both.", sportId: "sport-running" },
  { id: "faq-vest-choose-3", question: "How tight should a running vest be?", answer: "It should hold a full load without bouncing while allowing unrestricted breathing. Test it loaded and adjust tension as fluid is consumed.", sportId: "sport-running" },
  { id: "faq-vest-choose-4", question: "Can I use any soft flask in any vest?", answer: "No. Flask height, width, valve position and pocket retention vary. Confirm dimensions and compatibility with the specific vest.", sportId: "sport-running" },
  { id: "faq-headlamp-1", question: "How many lumens do I need for running?", answer: "There is no universal number. Lit roads need less than fast technical trails; beam shape and sustained output matter more than peak lumens alone.", sportId: "sport-running" },
  { id: "faq-headlamp-2", question: "Why does a headlamp get dimmer before the battery is empty?", answer: "Many lamps reduce output to control heat or extend runtime. Compare regulated or sustained output in the mode you will use.", sportId: "sport-running" },
  { id: "faq-headlamp-3", question: "Should I carry a backup headlamp?", answer: "Yes when a failure would leave you in consequential darkness, especially on remote routes. The backup should be independent and accessible.", sportId: "sport-running" },
  { id: "faq-headlamp-4", question: "How do I stop a running headlamp from bouncing?", answer: "Balance front and rear weight, use the top strap if supplied and adjust with your usual hat. Test at running pace rather than standing still.", sportId: "sport-running" },
  { id: "faq-vest-belt-1", question: "When should I use a vest instead of a running belt?", answer: "Move to a vest when water, layers or required kit make a belt bounce, press or become difficult to access.", sportId: "sport-running" },
  { id: "faq-vest-belt-2", question: "Is a running belt enough for a half marathon?", answer: "It can be when course support covers water and you carry little gear. Distance alone does not decide; weather, support and mandatory kit do.", sportId: "sport-running" },
  { id: "faq-vest-belt-3", question: "Which is cooler in hot weather?", answer: "A belt usually covers less skin and traps less heat. It is useful only if it can carry the required fluid and gear stably.", sportId: "sport-running" },
  { id: "faq-vest-belt-4", question: "Can a hydration vest replace a belt for every run?", answer: "Yes, but it adds unnecessary coverage and adjustment for small loads. Use the smallest stable system that carries what the route requires.", sportId: "sport-running" },
  { id: "faq-multiband-1", question: "What is multi-band GPS on a running watch?", answer: "It receives compatible satellite signals on more than one frequency, helping reduce some errors from reflected or obstructed signals.", sportId: "sport-running" },
  { id: "faq-multiband-2", question: "Do I need multi-band GPS for road running?", answer: "Often not on open roads. It becomes more useful around tall buildings, dense trees, cliffs and other difficult reception.", sportId: "sport-running" },
  { id: "faq-multiband-3", question: "Does multi-band GPS use more battery?", answer: "Usually yes. Compare runtime in the exact GNSS mode you intend to use and keep enough reserve for your longest activity.", sportId: "sport-running" },
  { id: "faq-multiband-4", question: "Does multi-band guarantee accurate instant pace?", answer: "No. Positioning, antenna design, software and pace smoothing all affect the displayed result.", sportId: "sport-running" },
  { id: "faq-headphones-1", question: "Are open-ear headphones safer for running?", answer: "They generally reduce isolation, but they do not guarantee awareness. Volume, attention, route choice and visual checks still matter.", sportId: "sport-running" },
  { id: "faq-headphones-2", question: "Do open-ear headphones sound as good as in-ear earbuds?", answer: "They usually deliver less bass and isolation, especially in wind or traffic. In-ear models normally provide stronger detail and low-frequency impact.", sportId: "sport-running" },
  { id: "faq-headphones-3", question: "Is transparency mode the same as open-ear listening?", answer: "No. Transparency uses microphones and processing through a sealed or partly sealed earbud, so outside sound can be altered or missed.", sportId: "sport-running" },
  { id: "faq-headphones-4", question: "What should I check for running fit?", answer: "Test stability under impact and sweat, pressure over a long session, control operation and whether hats or glasses interfere.", sportId: "sport-running" },
];
