import type { ExplainerBlock } from "@/lib/guides/explainer-blocks";
import { tocFromExplainer } from "@/lib/guides/explainer-blocks";
import type { LongFormGuideConfig } from "@/lib/guides/long-form-config";

const DAILY_TRAINER_BLOCKS: ExplainerBlock[] = [
  {
    id: "definition",
    type: "prose",
    title: "What is a daily trainer?",
    intro: "A daily trainer is the default running shoe for regular mileage.",
    paragraphs: [
      "A daily trainer is a road running shoe designed to handle the largest share of ordinary training: easy runs, steady mileage and often moderate long runs. It prioritises repeatable comfort, predictable handling and durability over maximum race-day speed.",
      "Daily trainer is a role, not one fixed specification. Cushion can be moderate or high, the ride can be soft or firm, and the shoe can be neutral or stability-focused. What connects the category is breadth: it should work well across more routine sessions than a specialist shoe.",
      "For many runners, one good daily trainer is enough. Add a tempo, max-cushion or race shoe only when a recurring session exposes a real limitation.",
    ],
  },
  {
    id: "core-traits",
    type: "factor-cards",
    title: "What makes a good daily trainer?",
    intro: "The best daily shoe is dependable before it is dramatic.",
    cards: [
      {
        id: "fit",
        title: "Repeatable fit",
        whatItIs: "Secure heel and midfoot with appropriate toe room and width.",
        howItChanges: "Reduces distraction across frequent runs and changing distances.",
        whatYouNotice: "No persistent pressure, slip or need to fight the lacing.",
      },
      {
        id: "cushion",
        title: "Balanced cushioning",
        whatItIs: "Enough foam for routine volume without forcing one softness level.",
        howItChanges: "Supports easy mileage while preserving predictable transitions.",
        whatYouNotice: "Comfort at normal pace without uncontrolled sinking or harshness.",
      },
      {
        id: "handling",
        title: "Stable handling",
        whatItIs: "Geometry you can control through corners, fatigue and uneven road surfaces.",
        howItChanges: "Makes the shoe useful across more ordinary conditions.",
        whatYouNotice: "A planted ride that does not demand perfect form or pace.",
      },
      {
        id: "durability",
        title: "Training durability",
        whatItIs: "Upper, foam and outsole designed for repeated mileage.",
        howItChanges: "Keeps performance consistent enough to justify frequent use.",
        whatYouNotice: "Predictable grip and cushioning rather than a short peak window.",
      },
      {
        id: "versatility",
        title: "Useful pace range",
        whatItIs: "A ride that remains comfortable from easy to steady running.",
        howItChanges: "Reduces the need for a second shoe in simple schedules.",
        whatYouNotice: "The shoe does not feel completely out of place when pace changes.",
      },
    ],
  },
  {
    id: "category-comparison",
    type: "comparison-table",
    title: "Daily trainer vs specialist running shoes",
    columns: ["Primary priority", "Typical compromise"],
    rows: [
      { label: "Daily trainer", values: ["Versatility and repeatability", "Not the softest or fastest specialist"] },
      { label: "Tempo shoe", values: ["Responsive faster training", "Less relaxed for easy mileage"] },
      { label: "Race shoe", values: ["Lowest weight and race efficiency", "Price, durability and everyday usability"] },
      { label: "Max-cushion shoe", values: ["Protection and easy-run comfort", "Weight and agility"] },
      { label: "Stability trainer", values: ["More guided platform", "Can feel restrictive to neutral-shoe preferences"] },
    ],
    footnote: "Categories overlap. A max-cushion or stability shoe can also serve as someone's daily trainer.",
  },
  {
    id: "vs-race",
    type: "prose",
    title: "Daily trainer vs race shoe",
    paragraphs: [
      "Race shoes optimise for a narrower job: running fast on race day. They commonly use lighter construction, premium foam, aggressive geometry and a stiff plate. Daily trainers accept more weight to gain durability, stable handling and broader pace comfort.",
      "A carbon racer can complete daily miles, but capability is not suitability. It may cost more per use, feel awkward at easy pace and provide less outsole or upper robustness.",
      "Use a daily trainer as the anchor. Add a race shoe when you race often enough, have a clear performance goal and have tested the model at intended pace.",
    ],
  },
  {
    id: "vs-tempo-max",
    type: "prose",
    title: "Daily trainer vs tempo and max cushion",
    paragraphs: [
      "Tempo shoes shift the balance toward speed: lower weight, more responsive foam, stiffer geometry or a plate. Some versatile dailies can handle strides and moderate tempo work, but dedicated workout shoes feel sharper when faster sessions become frequent.",
      "Max-cushion shoes shift toward protection and comfort. Some are excellent daily trainers; others feel too heavy or specialised for mixed paces. Stack height alone does not decide the category.",
      "The boundaries are functional. Ask what the shoe does best, what it tolerates and where it becomes a compromise.",
    ],
  },
  {
    id: "daily-use",
    type: "use-case-cards",
    title: "Where a daily trainer fits",
    cards: [
      { id: "easy", title: "Easy runs", description: "The core role: comfortable, controlled mileage without specialised demands." },
      { id: "steady", title: "Steady runs", description: "A versatile daily should remain smooth when pace moves above easy." },
      { id: "long", title: "Moderate long runs", description: "Works when cushioning and fit remain comfortable over time.", href: "/best/running-shoes-long-runs" },
      { id: "treadmill", title: "Treadmill", description: "Road dailies usually transfer well; prioritise fit and breathability." },
      { id: "beginner", title: "First running shoe", description: "Broad capability makes a daily trainer the logical starting category.", href: "/best/running-shoes-beginners" },
      { id: "travel", title: "Travel / one-shoe weeks", description: "A dependable choice when one pair must cover several ordinary sessions." },
    ],
  },
  {
    id: "not-for",
    type: "callout",
    title: "When a daily trainer is not the right tool",
    tone: "accent",
    body: "Choose a specialist when the session repeatedly exposes a limitation: technical trails need grip and protection, race goals may justify a racer, frequent intervals may benefit from a tempo shoe, and very easy high-volume running may favour more cushion. Do not add a specialist for a session you rarely do.",
  },
  {
    id: "fit-first",
    type: "prose",
    title: "Fit matters more in the shoe you use most",
    paragraphs: [
      "Because a daily trainer receives frequent mileage, small fit problems compound. Confirm length, toe room, width, heel lockdown and upper pressure before debating foam technology.",
      "Try the shoe with your running socks and at a representative time of day. Walk, jog and change direction. A comfortable standing fit can still reveal heel slip or forefoot pressure in motion.",
      "Width labels describe upper volume, not necessarily midsole platform width. Check both if you need more room or prefer a planted base.",
    ],
  },
  {
    id: "tradeoffs",
    type: "pros-tradeoffs",
    title: "The value — and limits — of versatility",
    gains: [
      "One pair can cover most routine road mileage",
      "Predictable handling across easy and steady paces",
      "Usually stronger durability priorities than race shoes",
      "Simpler, lower-cost starting point for a rotation",
    ],
    giveUps: [
      "Less speed focus than a tempo or race shoe",
      "Less plush protection than some max-cushion specialists",
      "Broad competence can feel less exciting than a narrow specialist",
      "One daily may not cover technical terrain or extreme conditions",
    ],
    footnote: "A daily trainer should be judged by how few meaningful compromises it creates in your actual week.",
  },
  {
    id: "decision",
    type: "decision-flow",
    title: "How to choose a daily trainer",
    steps: [
      { id: "terrain", title: "Confirm terrain", body: "This category primarily covers road, path and treadmill use; technical trails need different traction." },
      { id: "fit", title: "Solve fit first", body: "Choose correct length, width, heel security and upper comfort before ride preferences." },
      { id: "cushion", title: "Choose cushion feel", body: "Decide whether you prefer balanced, soft or firmer cushioning at everyday pace." },
      { id: "support", title: "Choose platform feel", body: "Select freer neutral geometry or more guided stability based on comfort preference, not diagnosis." },
      { id: "pace", title: "Set the pace range", body: "If one shoe must cover faster running, favour lower weight and a more responsive transition." },
      { id: "durability", title: "Check practical value", body: "Compare outsole coverage, intended role, price and how often you will use the pair." },
    ],
    branches: {
      question: "What must your daily trainer do beyond easy miles?",
      options: [
        { label: "Nothing", result: "Prioritise fit, comfort and durability; speed versatility is optional." },
        { label: "Long runs", result: "Emphasise sustained cushioning, stable geometry and late-run fit." },
        { label: "Some tempo", result: "Bias toward a lighter, responsive daily or daily-tempo hybrid." },
        { label: "Guided support", result: "Compare stability dailies by actual guidance approach and comfort." },
      ],
    },
  },
  {
    id: "examples",
    type: "product-examples",
    title: "Daily trainers across brands and roles",
    disclaimer: "These are examples of different daily-training interpretations, not automatic recommendations for every runner.",
    examples: [
      {
        productId: "prod-ghost-18",
        approachLabel: "Traditional balanced daily",
        whyIllustrates: "Represents the straightforward daily role: regular mileage, familiar geometry and broad everyday intent.",
        bestFor: ["Routine road mileage", "Easy and steady runs", "Runners wanting a conventional daily"],
        tradeoff: "Less specialised for maximum cushion or top-end speed.",
      },
      {
        productId: "prod-novablast-6",
        approachLabel: "Responsive versatile daily",
        whyIllustrates: "Shows the livelier side of the category for runners who want one shoe to cover easy-to-steady pace changes.",
        bestFor: ["Mixed daily mileage", "Steady running", "Versatile one-shoe rotations"],
        tradeoff: "A more energetic ride may not suit runners wanting a subdued, traditional feel.",
      },
      {
        productId: "prod-pegasus-42",
        approachLabel: "Workhorse daily",
        whyIllustrates: "A durable general-training interpretation suited to runners prioritising a dependable default pair.",
        bestFor: ["Frequent training", "Road and treadmill", "Simple rotations"],
        tradeoff: "Less plush than a dedicated max-cushion shoe and less sharp than a tempo tool.",
      },
      {
        productId: "prod-clifton-10",
        approachLabel: "Cushioned daily",
        whyIllustrates: "Demonstrates how a higher-cushion road shoe can still retain a broad daily-training role.",
        bestFor: ["Easy mileage", "Cushion-focused daily use", "Longer routine runs"],
        tradeoff: "More cushioning can reduce ground feel and quickness for faster sessions.",
      },
    ],
  },
  {
    id: "product-comparison",
    type: "product-comparison",
    title: "Compare four daily-training approaches",
    productIds: ["prod-ghost-18", "prod-novablast-6", "prod-pegasus-42", "prod-clifton-10"],
    bestGuideHref: "/best/daily-trainers",
    bestGuideLabel: "Best Daily Trainers →",
    compareHref: "/compare?category=running-shoes&products=brooks-ghost-18,asics-novablast-6,nike-pegasus-42,hoka-clifton-10",
  },
  {
    id: "mistakes",
    type: "mistakes",
    title: "Common daily-trainer mistakes",
    mistakes: [
      { id: "hype", title: "Buying the most exciting shoe", body: "Daily value comes from repeatable fit and use, not the most dramatic first impression." },
      { id: "soft", title: "Assuming softer is always better", body: "Softness, stack and protection are different. Choose the ride you can control comfortably." },
      { id: "fast", title: "Optimising for rare speed sessions", body: "Buy for the majority of your week; add a tempo shoe if faster work becomes frequent." },
      { id: "fit", title: "Accepting a small fit problem", body: "Frequent mileage magnifies pressure, slip and width mismatch." },
      { id: "lifespan", title: "Following a fixed lifespan rule", body: "Wear varies. Inspect outsole, midsole feel, upper integrity and comfort rather than one universal mileage number." },
      { id: "medical", title: "Treating category labels as a diagnosis", body: "Neutral and stability describe shoe design. They do not diagnose gait or injury." },
    ],
  },
  {
    id: "medical",
    type: "callout",
    title: "Comfort guidance is not medical advice",
    tone: "caution",
    body: "Kitletics compares product design and intended use. We do not diagnose gait, prescribe support or claim a daily trainer will prevent injury. Stop and seek qualified clinical advice when running is painful.",
  },
  {
    id: "finder-cta",
    type: "cta",
    title: "Find your everyday match",
    variant: "finder",
    body: "Use the Running Shoe Finder to filter by terrain, fit, cushion, support preference and budget.",
    ctaLabel: "Find my running shoes →",
    href: "/tools/running-shoe-finder",
  },
  {
    id: "one-shoe-or-rotation",
    type: "prose",
    title: "One daily trainer or a rotation?",
    paragraphs: [
      "Stay with one shoe when it is comfortable and covers your normal sessions. This is the simplest and often best-value setup.",
      "Add a second shoe when roles conflict: your daily feels cumbersome at workout pace, insufficiently protective on long runs or unsuitable for trails. The second pair should complement the daily, not duplicate it.",
      "Replace by condition and experience, not fear. Track approximate mileage, inspect wear and notice meaningful changes in comfort or control.",
    ],
  },
  {
    id: "best-cta",
    type: "cta",
    title: "Ready to compare current daily trainers?",
    variant: "best-guide",
    body: "See Kitletics picks by daily role, with product evidence, trade-offs and live comparison data.",
    ctaLabel: "Best Daily Trainers →",
    href: "/best/daily-trainers",
  },
];

export const whatIsADailyTrainerConfig: LongFormGuideConfig = {
  guideSlug: "what-is-a-daily-trainer",
  layout: "explainer",
  eyebrow: "Explainer",
  displayTitle: "What Is a Daily Trainer?",
  deck: "The default running-shoe category explained: what makes a good daily, how it differs from tempo, race and max-cushion shoes, and when one pair is enough.",
  heroImageSrc: "/images/running/products/ghost-18.png",
  heroImageAlt: "Brooks Ghost 18 daily running shoe",
  finder: {
    toolSlug: "running-shoe-finder",
    title: "Find your daily trainer",
    description: "Build a shortlist around your terrain, fit, cushioning and support preferences.",
    ctaLabel: "Find my running shoes →",
  },
  decisionLinks: [
    { label: "Best daily trainers →", href: "/best/daily-trainers" },
    { label: "Best running shoes →", href: "/best/running-shoes" },
    { label: "Plan a shoe rotation →", href: "/tools/shoe-rotation-planner" },
  ],
  glossaryHref: "/guides/running-shoe-terminology",
  glossaryTerms: [
    { id: "daily", term: "Daily trainer", definition: "A versatile shoe designed for the majority of routine running.", icon: "circle" },
    { id: "tempo", term: "Tempo shoe", definition: "A lighter, responsive shoe focused on sustained faster sessions.", icon: "gauge" },
    { id: "race", term: "Race shoe", definition: "A specialised shoe prioritising performance at race pace.", icon: "scale" },
    { id: "max-cushion", term: "Max cushion", definition: "A category with a high level of underfoot cushioning.", icon: "layers" },
    { id: "drop", term: "Heel-to-toe drop", definition: "The height difference between heel and forefoot.", icon: "ruler" },
    { id: "stability", term: "Stability shoe", definition: "A shoe using geometry or structures for a more guided platform.", icon: "shield" },
  ],
  needs: [],
  factors: [],
  fit: [],
  toc: tocFromExplainer([...DAILY_TRAINER_BLOCKS]),
  productExampleRoles: [
    { productId: "prod-ghost-18", roleLabel: "Balanced daily" },
    { productId: "prod-novablast-6", roleLabel: "Responsive daily" },
    { productId: "prod-pegasus-42", roleLabel: "Workhorse daily" },
    { productId: "prod-clifton-10", roleLabel: "Cushioned daily" },
  ],
  productRailTitle: "Examples of daily trainers across brands",
  productRailBrowseHref: "/running/shoes/daily-trainers",
  productRailBrowseLabel: "Browse daily trainers →",
  explainer: {
    layout: "explainer",
    quickAnswerBullets: [
      "A daily trainer is the dependable shoe intended to cover most routine road mileage.",
      "Good dailies balance fit, cushioning, stable handling, durability and a useful pace range.",
      "Daily does not mean one fixed stack, softness or support level.",
      "Tempo, race and max-cushion shoes trade broad versatility for a more specialised strength.",
      "One daily trainer is enough until a recurring session creates a real gap.",
    ],
    medicalNote: "Kitletics explains shoe categories and product design. We do not diagnose gait, prescribe stability or claim footwear prevents injury. Seek qualified clinical advice for pain or medical concerns.",
    methodologyNote: "This guide defines daily trainers by intended role and repeatable use rather than one specification threshold. Examples use current catalog positioning, specifications and manufacturer descriptions; comparison values and prices render from live product data.",
    blocks: [...DAILY_TRAINER_BLOCKS],
  },
};
