import type { ProductFamily } from "@/domain/products/types";
import { runningCatalogFamilies } from "@/content/running/families";
import { runningHydrationFamilies } from "@/content/running/hydration-families";
import { runningClothingFamilies } from "@/content/running/clothing-families";
import { runningPacksCarryFamilies } from "@/content/running/packs-carry-families";
import { runningHeadphonesFamilies } from "@/content/running/headphones-families";
import { runningSunglassesFamilies } from "@/content/running/sunglasses-families";
import { runningHeadlampsFamilies } from "@/content/running/headlamps-families";
import { runningSafetyFamilies } from "@/content/running/safety-families";
import { runningNutritionFamilies } from "@/content/running/nutrition-families";
import { runningRecoveryFamilies } from "@/content/running/recovery-families";
import { padelAllFamilies } from "@/content/padel";
import { racketFamilies } from "@/content/racket";
import { brandHubP56Families } from "@/content/brand-hub-p56-families";

export const productFamilies: ProductFamily[] = [
  {
    id: "fam-novablast",
    brandId: "brand-asics",
    name: "Novablast",
    slug: "novablast",
    categoryId: "cat-running-shoes",
    description: "Bouncy daily trainer family.",
    productIds: ["prod-novablast-6", "prod-novablast-5", "prod-novablast-4"],
  },
  {
    id: "fam-gel-nimbus",
    brandId: "brand-asics",
    name: "GEL-Nimbus",
    slug: "gel-nimbus",
    categoryId: "cat-running-shoes",
    description: "Max-cushion daily trainer family.",
    productIds: ["prod-nimbus-27"],
  },
  {
    id: "fam-pegasus",
    brandId: "brand-nike",
    name: "Pegasus",
    slug: "pegasus",
    categoryId: "cat-running-shoes",
    description: "Versatile daily trainer family.",
    productIds: ["prod-pegasus-42", "prod-pegasus-41"],
  },
  {
    id: "fam-ghost",
    brandId: "brand-brooks",
    name: "Ghost",
    slug: "ghost",
    categoryId: "cat-running-shoes",
    description: "Soft neutral daily trainer.",
    productIds: ["prod-ghost-18", "prod-ghost-16"],
  },
  {
    id: "fam-clifton",
    brandId: "brand-hoka",
    name: "Clifton",
    slug: "clifton",
    categoryId: "cat-running-shoes",
    description: "Lightweight max-cushion daily trainer.",
    productIds: ["prod-clifton-10", "prod-clifton-pro", "prod-clifton-9"],
  },
  {
    id: "fam-endorphin-speed",
    brandId: "brand-saucony",
    name: "Endorphin Speed",
    slug: "endorphin-speed",
    categoryId: "cat-running-shoes",
    description: "Nylon-plated tempo and race shoe.",
    productIds: ["prod-endorphin-speed-5", "prod-endorphin-speed-4"],
  },
  {
    id: "fam-rebel",
    brandId: "brand-new-balance",
    name: "FuelCell Rebel",
    slug: "fuelcell-rebel",
    categoryId: "cat-running-shoes",
    description: "Lightweight daily / uptempo trainer.",
    productIds: ["prod-rebel-v5", "prod-rebel-4"],
  },
  {
    id: "fam-adizero-boston",
    brandId: "brand-adidas",
    name: "Adizero Boston",
    slug: "adizero-boston",
    categoryId: "cat-running-shoes",
    description: "Tempo trainer; also used in HYROX contexts.",
    productIds: ["prod-boston-12", "prod-adizero-boston-13"],
  },
  {
    id: "fam-forerunner",
    brandId: "brand-garmin",
    name: "Forerunner",
    slug: "forerunner",
    categoryId: "cat-gps-watches",
    description: "Running-focused GPS watch family.",
    productIds: [
      "prod-forerunner-970",
      "prod-forerunner-570",
      "prod-forerunner-965",
      "prod-forerunner-265",
      "prod-forerunner-265s",
      "prod-forerunner-255",
      "prod-forerunner-165",
      "prod-forerunner-55",
    ],
  },
  {
    id: "fam-fenix",
    brandId: "brand-garmin",
    name: "Fenix",
    slug: "fenix",
    categoryId: "cat-gps-watches",
    description: "Rugged multisport adventure GPS watches.",
    productIds: ["prod-fenix-8"],
  },
  {
    id: "fam-enduro",
    brandId: "brand-garmin",
    name: "Enduro",
    slug: "enduro",
    categoryId: "cat-gps-watches",
    description: "Ultra-distance battery-focused Garmin watches.",
    productIds: ["prod-enduro-3"],
  },
  {
    id: "fam-instinct",
    brandId: "brand-garmin",
    name: "Instinct",
    slug: "instinct",
    categoryId: "cat-gps-watches",
    description: "Rugged essential GPS watches for outdoor training.",
    productIds: ["prod-instinct-3"],
  },
  {
    id: "fam-vivoactive",
    brandId: "brand-garmin",
    name: "Vivoactive",
    slug: "vivoactive",
    categoryId: "cat-gps-watches",
    description: "Lifestyle multisport watches with strong running tools.",
    productIds: ["prod-vivoactive-6"],
  },
  {
    id: "fam-epix",
    brandId: "brand-garmin",
    name: "Epix",
    slug: "epix",
    categoryId: "cat-gps-watches",
    description: "AMOLED mapping watches (previous-gen value vs Fenix).",
    productIds: ["prod-garmin-epix-pro-gen2"],
  },
  {
    id: "fam-coros-pace",
    brandId: "brand-coros",
    name: "Pace",
    slug: "pace",
    categoryId: "cat-gps-watches",
    description: "Lightweight running GPS watches.",
    productIds: [
      "prod-coros-pace-4",
      "prod-coros-pace-pro",
      "prod-coros-pace-3",
    ],
  },
  {
    id: "fam-coros-apex",
    brandId: "brand-coros",
    name: "Apex",
    slug: "apex",
    categoryId: "cat-gps-watches",
    description: "Premium COROS training watches with maps.",
    productIds: ["prod-coros-apex-4", "prod-coros-apex-2-pro"],
  },
  {
    id: "fam-coros-vertix",
    brandId: "brand-coros",
    name: "Vertix",
    slug: "vertix",
    categoryId: "cat-gps-watches",
    description: "Expedition and ultra battery COROS watches.",
    productIds: ["prod-coros-vertix-2s"],
  },
  {
    id: "fam-suunto-race",
    brandId: "brand-suunto",
    name: "Race",
    slug: "suunto-race",
    categoryId: "cat-gps-watches",
    description: "Performance Suunto racing watches.",
    productIds: ["prod-suunto-race", "prod-suunto-race-s"],
  },
  {
    id: "fam-suunto-vertical",
    brandId: "brand-suunto",
    name: "Vertical",
    slug: "suunto-vertical",
    categoryId: "cat-gps-watches",
    description: "Outdoor Suunto watches with long battery and maps.",
    productIds: ["prod-suunto-vertical-2"],
  },
  {
    id: "fam-suunto-run",
    brandId: "brand-suunto",
    name: "Run",
    slug: "suunto-run",
    categoryId: "cat-gps-watches",
    description: "Accessible Suunto running watches.",
    productIds: ["prod-suunto-run"],
  },
  {
    id: "fam-polar-vantage",
    brandId: "brand-polar",
    name: "Vantage",
    slug: "vantage",
    categoryId: "cat-gps-watches",
    description: "Polar training watches with advanced metrics.",
    productIds: ["prod-polar-vantage-v3"],
  },
  {
    id: "fam-polar-pacer",
    brandId: "brand-polar",
    name: "Pacer",
    slug: "pacer",
    categoryId: "cat-gps-watches",
    description: "Polar running-focused GPS watches.",
    productIds: ["prod-polar-pacer-pro", "prod-polar-pacer"],
  },
  {
    id: "fam-polar-grit",
    brandId: "brand-polar",
    name: "Grit X",
    slug: "grit-x",
    categoryId: "cat-gps-watches",
    description: "Polar outdoor adventure watches.",
    productIds: ["prod-polar-grit-x2"],
  },
  {
    id: "fam-apple-watch-ultra",
    brandId: "brand-apple",
    name: "Apple Watch Ultra",
    slug: "apple-watch-ultra",
    categoryId: "cat-gps-watches",
    description: "Apple’s rugged sports smartwatch line.",
    productIds: ["prod-apple-watch-ultra-3", "prod-apple-watch-ultra-2"],
  },
  {
    id: "fam-apple-watch",
    brandId: "brand-apple",
    name: "Apple Watch",
    slug: "apple-watch",
    categoryId: "cat-gps-watches",
    description: "Mainstream Apple Watch for daily training.",
    productIds: ["prod-apple-watch-series-10"],
  },
  {
    id: "fam-galaxy-watch",
    brandId: "brand-samsung",
    name: "Galaxy Watch",
    slug: "galaxy-watch",
    categoryId: "cat-gps-watches",
    description: "Samsung Galaxy sports and smartwatches.",
    productIds: [
      "prod-samsung-galaxy-watch-ultra",
      "prod-samsung-galaxy-watch-ultra-2",
      "prod-samsung-galaxy-watch-9",
    ],
  },
  {
    id: "fam-amazfit-t-rex",
    brandId: "brand-amazfit",
    name: "T-Rex",
    slug: "t-rex",
    categoryId: "cat-gps-watches",
    description: "Rugged Amazfit outdoor GPS watches.",
    productIds: ["prod-amazfit-t-rex-3-pro"],
  },
  {
    id: "fam-amazfit-active",
    brandId: "brand-amazfit",
    name: "Active",
    slug: "amazfit-active",
    categoryId: "cat-gps-watches",
    description: "Everyday Amazfit fitness watches.",
    productIds: ["prod-amazfit-active-2"],
  },
  {
    id: "fam-amazfit-balance",
    brandId: "brand-amazfit",
    name: "Balance",
    slug: "amazfit-balance",
    categoryId: "cat-gps-watches",
    description: "Amazfit hybrid-training GPS watches with maps.",
    productIds: ["prod-amazfit-balance-3"],
  },
  {
    id: "fam-amazfit-cheetah",
    brandId: "brand-amazfit",
    name: "Cheetah",
    slug: "amazfit-cheetah",
    categoryId: "cat-gps-watches",
    description: "Amazfit dedicated running GPS watches.",
    productIds: ["prod-amazfit-cheetah-2-pro"],
  },
  {
    id: "fam-hrm-pro",
    brandId: "brand-garmin",
    name: "HRM",
    slug: "hrm",
    categoryId: "cat-hrm",
    description: "Garmin heart rate monitor straps.",
    productIds: [
      "prod-hrm-600",
      "prod-hrm-pro-plus",
      "prod-garmin-hrm-200",
      "prod-garmin-hrm-fit",
    ],
  },
  {
    id: "fam-polar-h",
    brandId: "brand-polar",
    name: "H Series",
    slug: "polar-h",
    categoryId: "cat-hrm",
    description: "Polar ECG chest straps.",
    productIds: ["prod-polar-h10", "prod-polar-h9"],
  },
  {
    id: "fam-polar-verity",
    brandId: "brand-polar",
    name: "Verity Sense",
    slug: "verity-sense",
    categoryId: "cat-hrm",
    description: "Polar optical armband HR sensors.",
    productIds: ["prod-polar-verity-sense"],
  },
  {
    id: "fam-wahoo-tickr",
    brandId: "brand-wahoo",
    name: "TICKR / TRACKR",
    slug: "wahoo-tickr",
    categoryId: "cat-hrm",
    description: "Wahoo chest and arm HR monitors.",
    productIds: [
      "prod-wahoo-trackr",
      "prod-wahoo-tickr",
      "prod-wahoo-tickr-x",
      "prod-wahoo-tickr-fit",
    ],
  },
  {
    id: "fam-coros-hrm",
    brandId: "brand-coros",
    name: "Heart Rate Monitor",
    slug: "coros-hrm",
    categoryId: "cat-hrm",
    description: "COROS optical armband heart rate monitor.",
    productIds: ["prod-coros-hrm"],
  },
  {
    id: "fam-scosche-rhythm",
    brandId: "brand-scosche",
    name: "Rhythm",
    slug: "scosche-rhythm",
    categoryId: "cat-hrm",
    description: "Scosche optical armband heart rate monitors.",
    productIds: ["prod-scosche-rhythm-plus-2", "prod-scosche-rhythm24"],
  },
  {
    id: "fam-suunto-hrm",
    brandId: "brand-suunto",
    name: "Smart Heart Rate Belt",
    slug: "suunto-hrm",
    categoryId: "cat-hrm",
    description: "Suunto chest heart rate belts.",
    productIds: ["prod-suunto-smart-hr-belt"],
  },
  {
    id: "fam-adv-skin",
    brandId: "brand-salomon",
    name: "ADV Skin",
    slug: "adv-skin",
    categoryId: "cat-packs-vests",
    description: "Race vest family for trail and ultra.",
    productIds: ["prod-adv-skin-12", "prod-salomon-adv-skin-5"],
  },
  {
    id: "fam-assault-runner",
    brandId: "brand-assault",
    name: "AssaultRunner",
    slug: "assault-runner",
    categoryId: "cat-treadmills",
    description: "Curved non-motorised treadmill family for sprint and conditioning.",
    productIds: ["prod-assault-runner", "prod-assault-runner-elite"],
  },
  {
    id: "fam-mirafit-treadmill",
    brandId: "brand-mirafit",
    name: "Mirafit Treadmill",
    slug: "mirafit-treadmill",
    categoryId: "cat-treadmills",
    description: "Folding motorised home treadmill family.",
    productIds: ["prod-mirafit-treadmill"],
  },
  ...runningCatalogFamilies,
  ...runningHydrationFamilies,
  ...runningPacksCarryFamilies,
  ...runningHeadphonesFamilies,
  ...runningSunglassesFamilies,
  ...runningHeadlampsFamilies,
  ...runningSafetyFamilies,
  ...runningNutritionFamilies,
  ...runningRecoveryFamilies,
  ...runningClothingFamilies,
  ...padelAllFamilies,
  ...racketFamilies,
  ...brandHubP56Families,
];
