/**
 * NL offer backfill for products that previously had no regional offers.
 * Seed/illustrative prices — not live scrapes. lastChecked via SEED_DATES.verified.
 */
import type { Offer } from "@/domain/commerce/types";
import { SEED_DATES } from "@/content/config";

const checked = SEED_DATES.verified;

type Seed = {
  productId: string;
  slug: string;
  price: number;
  retailerId?: string;
  url?: string;
};

function nlOffer(seed: Seed): Offer {
  const retailerId = seed.retailerId ?? "ret-amazon-nl";
  const url = seed.url ?? "https://www.amazon.nl/";
  return {
    id: `offer-${seed.slug}-nl-backfill`,
    productId: seed.productId,
    retailerId,
    region: "NL",
    url,
    currency: "EUR",
    price: seed.price,
    availability: "in-stock",
    lastChecked: checked,
    source: "seed",
    condition: "new",
    status: "active",
  };
}

/** Curated NL EUR prices for missing running shoes (illustrative seed). */
const RUNNING_SHOE_SEEDS: Seed[] = [
  { productId: "prod-superblast-2", slug: "asics-superblast-2", price: 220, retailerId: "ret-asics-direct", url: "https://www.asics.com/nl/nl-nl/" },
  { productId: "prod-cumulus-27", slug: "asics-gel-cumulus-27", price: 150, retailerId: "ret-asics-direct", url: "https://www.asics.com/nl/nl-nl/" },
  { productId: "prod-metaspeed-sky-paris", slug: "asics-metaspeed-sky-paris", price: 250, retailerId: "ret-asics-direct", url: "https://www.asics.com/nl/nl-nl/" },
  { productId: "prod-gt-2000-14", slug: "asics-gt-2000-14", price: 160, retailerId: "ret-asics-direct", url: "https://www.asics.com/nl/nl-nl/" },
  { productId: "prod-vomero-18", slug: "nike-vomero-18", price: 160 },
  { productId: "prod-invincible-3", slug: "nike-invincible-3", price: 190 },
  { productId: "prod-structure-26", slug: "nike-structure-26", price: 140 },
  { productId: "prod-structure-plus", slug: "nike-structure-plus", price: 150 },
  { productId: "prod-glycerin-22", slug: "brooks-glycerin-22", price: 170, retailerId: "ret-brooks-direct", url: "https://www.brooksrunning.com/" },
  { productId: "prod-glycerin-21", slug: "brooks-glycerin-21", price: 140, retailerId: "ret-brooks-direct", url: "https://www.brooksrunning.com/" },
  { productId: "prod-hyperion-max-2", slug: "brooks-hyperion-max-2", price: 180, retailerId: "ret-brooks-direct", url: "https://www.brooksrunning.com/" },
  { productId: "prod-bondi-8", slug: "hoka-bondi-8", price: 170, retailerId: "ret-hoka-direct", url: "https://www.hoka.com/" },
  { productId: "prod-mach-6", slug: "hoka-mach-6", price: 150, retailerId: "ret-hoka-direct", url: "https://www.hoka.com/" },
  { productId: "prod-clifton-pro", slug: "hoka-clifton-pro", price: 160, retailerId: "ret-hoka-direct", url: "https://www.hoka.com/" },
  { productId: "prod-endorphin-pro-4", slug: "saucony-endorphin-pro-4", price: 240 },
  { productId: "prod-endorphin-pro-3", slug: "saucony-endorphin-pro-3", price: 180 },
  { productId: "prod-ride-18", slug: "saucony-ride-18", price: 140 },
  { productId: "prod-triumph-22", slug: "saucony-triumph-22", price: 160 },
  { productId: "prod-peregrine-15", slug: "saucony-peregrine-15", price: 150 },
  { productId: "prod-1080-v14", slug: "new-balance-fresh-foam-x-1080-v14", price: 170 },
  { productId: "prod-1080-v13", slug: "new-balance-fresh-foam-x-1080-v13", price: 140 },
  { productId: "prod-sc-elite-v4", slug: "new-balance-fuelcell-supercomp-elite-v4", price: 250 },
  { productId: "prod-rebel-v5", slug: "new-balance-fuelcell-rebel-v5", price: 150 },
  { productId: "prod-rebel-4", slug: "new-balance-fuelcell-rebel-v4", price: 130 },
  { productId: "prod-sc-trainer-v3", slug: "new-balance-fuelcell-supercomp-trainer-v3", price: 180 },
  { productId: "prod-adizero-evo-sl", slug: "adidas-adizero-evo-sl", price: 150 },
  { productId: "prod-adios-pro-4", slug: "adidas-adizero-adios-pro-4", price: 250 },
  { productId: "prod-cloudmonster-2", slug: "on-cloudmonster-2", price: 180 },
  { productId: "prod-cloudsurfer-next", slug: "on-cloudsurfer-next", price: 150 },
  { productId: "prod-torin-8", slug: "altra-torin-8", price: 160 },
  { productId: "prod-escalante-4", slug: "altra-escalante-4", price: 140 },
  { productId: "prod-lone-peak-8", slug: "altra-lone-peak-8", price: 150 },
  { productId: "prod-aero-glide-2", slug: "salomon-aero-glide-2", price: 150 },
  { productId: "prod-sense-ride-5", slug: "salomon-sense-ride-5", price: 140 },
  { productId: "prod-pulsar-trail-2", slug: "salomon-pulsar-trail-2", price: 150 },
  { productId: "prod-specter-2", slug: "topo-athletic-specter-2", price: 150 },
  { productId: "prod-phantom-3", slug: "topo-athletic-phantom-3", price: 145 },
  { productId: "prod-deviate-nitro-3", slug: "puma-deviate-nitro-3", price: 160 },
  { productId: "prod-magnify-nitro-2", slug: "puma-magnify-nitro-2", price: 140 },
  { productId: "prod-wave-rider-28", slug: "mizuno-wave-rider-28", price: 145 },
  { productId: "prod-wave-rebellion-pro-3", slug: "mizuno-wave-rebellion-pro-3", price: 240 },
  { productId: "prod-trailfly-ultra-g-300-max", slug: "inov8-trailfly-ultra-g-300-max", price: 220 },
  {
    productId: "prod-nnormal-kjerag-02",
    slug: "nnormal-kjerag-02",
    price: 190,
    retailerId: "ret-nnormal-direct",
    url: "https://www.nnormal.com/en_DE/men/shoes/kjr/nnormal-kjerag_02_shoe_green_white-N1ZKGM2-006",
  },
  {
    productId: "prod-nnormal-tomir-02",
    slug: "nnormal-tomir-02",
    price: 170,
    retailerId: "ret-nnormal-direct",
    url: "https://www.nnormal.com/en_DE/men/shoes/tmi/nnormal-tomir_02_shoe_black-N2ZTR25-001",
  },
];

/** Curated NL EUR prices for missing GPS watches (wave1 gaps + wave2 catalog). */
const WATCH_SEEDS: Seed[] = [
  { productId: "prod-forerunner-265", slug: "garmin-forerunner-265", price: 449, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-forerunner-55", slug: "garmin-forerunner-55", price: 179, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-coros-apex-2-pro", slug: "coros-apex-2-pro", price: 499 },
  { productId: "prod-polar-vantage-v3", slug: "polar-vantage-v3", price: 599 },
  { productId: "prod-polar-pacer-pro", slug: "polar-pacer-pro", price: 299 },
  { productId: "prod-suunto-race", slug: "suunto-race", price: 449 },
  { productId: "prod-suunto-race-s", slug: "suunto-race-s", price: 349 },
  { productId: "prod-apple-watch-ultra-2", slug: "apple-watch-ultra-2", price: 899 },
  // Wave 2 GPS watches
  { productId: "prod-fenix-8", slug: "garmin-fenix-8", price: 999, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-enduro-3", slug: "garmin-enduro-3", price: 899, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-instinct-3", slug: "garmin-instinct-3", price: 449, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-vivoactive-6", slug: "garmin-vivoactive-6", price: 299, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-forerunner-265s", slug: "garmin-forerunner-265s", price: 349, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-garmin-epix-pro-gen2", slug: "garmin-epix-pro-gen-2", price: 649, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-coros-apex-4", slug: "coros-apex-4", price: 430 },
  { productId: "prod-coros-pace-4", slug: "coros-pace-4", price: 249 },
  { productId: "prod-coros-vertix-2s", slug: "coros-vertix-2s", price: 699 },
  { productId: "prod-suunto-vertical-2", slug: "suunto-vertical-2", price: 599 },
  { productId: "prod-suunto-run", slug: "suunto-run", price: 199 },
  { productId: "prod-polar-grit-x2", slug: "polar-grit-x2", price: 549 },
  { productId: "prod-polar-pacer", slug: "polar-pacer", price: 199 },
  { productId: "prod-apple-watch-ultra-3", slug: "apple-watch-ultra-3", price: 899 },
  { productId: "prod-apple-watch-series-10", slug: "apple-watch-series-10", price: 449 },
  { productId: "prod-samsung-galaxy-watch-ultra", slug: "samsung-galaxy-watch-ultra", price: 649 },
  { productId: "prod-samsung-galaxy-watch-ultra-2", slug: "samsung-galaxy-watch-ultra-2", price: 699, url: "https://www.samsung.com/" },
  { productId: "prod-samsung-galaxy-watch-9", slug: "samsung-galaxy-watch-9", price: 379, url: "https://www.samsung.com/" },
  { productId: "prod-amazfit-t-rex-3-pro", slug: "amazfit-t-rex-3-pro", price: 249 },
  { productId: "prod-amazfit-active-2", slug: "amazfit-active-2", price: 99 },
  { productId: "prod-amazfit-balance-3", slug: "amazfit-balance-3", price: 369, url: "https://us.amazfit.com/products/balance-3" },
  { productId: "prod-amazfit-cheetah-2-pro", slug: "amazfit-cheetah-2-pro", price: 449, url: "https://us.amazfit.com/products/cheetah-2-pro" },
];

/** Remaining catalog gaps (HRM, packs, accessories, etc.). */
const ACCESSORY_SEEDS: Seed[] = [
  { productId: "prod-hrm-600", slug: "garmin-hrm-600", price: 149, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-garmin-hrm-200", slug: "garmin-hrm-200", price: 79, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-garmin-hrm-fit", slug: "garmin-hrm-fit", price: 99, retailerId: "ret-garmin-direct", url: "https://www.garmin.com/" },
  { productId: "prod-polar-h9", slug: "polar-h9", price: 59 },
  { productId: "prod-wahoo-trackr", slug: "wahoo-trackr", price: 89 },
  { productId: "prod-wahoo-tickr-fit", slug: "wahoo-tickr-fit", price: 79 },
  {
    productId: "prod-scosche-rhythm-plus-2",
    slug: "scosche-rhythm-plus-2",
    price: 89,
    url: "https://www.scosche.com/rhythm-plus-2-armband-heart-rate-monitor",
  },
  { productId: "prod-scosche-rhythm24", slug: "scosche-rhythm24", price: 69 },
  { productId: "prod-suunto-smart-hr-belt", slug: "suunto-smart-heart-rate-belt", price: 79 },

  { productId: "prod-polar-verity-sense", slug: "polar-verity-sense", price: 89 },
  { productId: "prod-wahoo-tickr", slug: "wahoo-tickr", price: 69 },
  { productId: "prod-wahoo-tickr-x", slug: "wahoo-tickr-x", price: 99 },
  { productId: "prod-coros-hrm", slug: "coros-heart-rate-monitor", price: 79 },
  { productId: "prod-ud-adventure-vest", slug: "ultimate-direction-adventure-vest", price: 160 },
  { productId: "prod-camelbak-zephyr", slug: "camelbak-zephyr", price: 140 },
  { productId: "prod-osprey-duro-6", slug: "osprey-duro-6", price: 150 },
  { productId: "prod-osprey-dyna-6", slug: "osprey-dyna-6", price: 150 },
  { productId: "prod-flipbelt-classic", slug: "flipbelt-classic", price: 32 },
  { productId: "prod-nathan-mirage", slug: "nathan-mirage-pak", price: 45 },
  { productId: "prod-spibelt-original", slug: "spibelt-original", price: 28 },
  { productId: "prod-nathan-exoshot", slug: "nathan-exoshot-2", price: 25 },
  { productId: "prod-soft-flask-500", slug: "salomon-soft-flask-500", price: 22 },
  { productId: "prod-hydrapak-softflask-500", slug: "hydrapak-softflask-500", price: 20 },
  { productId: "prod-asics-race-short", slug: "asics-core-split-short", price: 40 },
  { productId: "prod-nike-stride-short", slug: "nike-dri-fit-stride-short", price: 45 },
  { productId: "prod-brooks-ghost-short-sleeve", slug: "brooks-ghost-short-sleeve", price: 40 },
  { productId: "prod-brooks-cascadia-jacket", slug: "brooks-cascadia-jacket", price: 120 },
  { productId: "prod-craft-adv-essence-short", slug: "craft-adv-essence-short", price: 45 },
  { productId: "prod-feetures-elite-light-cushion", slug: "feetures-elite-light-cushion", price: 18 },
  { productId: "prod-balega-hidden-comfort", slug: "balega-hidden-comfort", price: 16 },
  { productId: "prod-injinji-run-midweight", slug: "injinji-run-midweight", price: 18 },
  { productId: "prod-cep-run-compression-sock", slug: "cep-run-compression-sock-3", price: 45 },
  { productId: "prod-shokz-openrun-pro-2", slug: "shokz-openrun-pro-2", price: 179 },
  { productId: "prod-airpods-pro-2", slug: "apple-airpods-pro-2", price: 279 },
  { productId: "prod-bose-ultra-open", slug: "bose-ultra-open-earbuds", price: 299 },
  { productId: "prod-oakley-encoder", slug: "oakley-encoder", price: 229 },
  { productId: "prod-goodr-ogs", slug: "goodr-ogs", price: 25 },
  { productId: "prod-julbo-aerolite", slug: "julbo-aerolite", price: 140 },
  { productId: "prod-petzl-swift-rl", slug: "petzl-swift-rl", price: 135 },
  { productId: "prod-bd-spot-400-r", slug: "black-diamond-spot-400-r", price: 75 },
  { productId: "prod-silva-trail-runner-free", slug: "silva-trail-runner-free-2", price: 160 },
  { productId: "prod-nathan-reflective-vest", slug: "nathan-streak-reflective-vest", price: 35 },
  { productId: "prod-nite-ize-radiant-clip", slug: "nite-ize-radiant-rechargeable-clip-light", price: 22 },
  { productId: "prod-theragun-mini", slug: "therabody-theragun-mini-2", price: 199 },
  { productId: "prod-hypervolt-go-2", slug: "hyperice-hypervolt-go-2", price: 179 },
  { productId: "prod-triggerpoint-grid", slug: "triggerpoint-grid-foam-roller", price: 40 },
  { productId: "prod-oofos-ooriginal", slug: "oofos-ooriginal", price: 60 },
  { productId: "prod-buff-original", slug: "buff-original", price: 22 },
  { productId: "prod-cep-calf-sleeves", slug: "cep-calf-sleeves-3", price: 40 },
  { productId: "prod-body-glide-original", slug: "body-glide-original", price: 12 },
  // Recovery gear wave2 + missing wave1 peers
  { productId: "prod-theragun-prime", slug: "therabody-theragun-prime", price: 299 },
  { productId: "prod-theragun-pro", slug: "therabody-theragun-pro", price: 549 },
  { productId: "prod-renpho-r3", slug: "renpho-r3", price: 89 },
  { productId: "prod-opove-m3-pro", slug: "opove-m3-pro", price: 129 },
  { productId: "prod-timtam-power-massager", slug: "timtam-power-massager", price: 199 },
  { productId: "prod-timtam-power-massager-v3.7", slug: "timtam-power-massager-v3-7", price: 199 },
  { productId: "prod-hypervolt-2", slug: "hyperice-hypervolt-2", price: 299 },
  { productId: "prod-theragun-relief", slug: "therabody-theragun-relief", price: 129 },
  { productId: "prod-triggerpoint-grid-x", slug: "triggerpoint-grid-x", price: 55 },
  { productId: "prod-triggerpoint-grid-travel", slug: "triggerpoint-grid-travel", price: 35 },
  { productId: "prod-rumbleroller-original", slug: "rumbleroller-original", price: 65 },
  { productId: "prod-brazyn-morph", slug: "brazyn-morph", price: 80 },
  { productId: "prod-blackroll-standard", slug: "blackroll-standard", price: 35 },
  { productId: "prod-blackroll-pro", slug: "blackroll-pro", price: 42 },
  { productId: "prod-triggerpoint-mb1", slug: "triggerpoint-mb1", price: 18 },
  { productId: "prod-triggerpoint-mbx", slug: "triggerpoint-mbx", price: 25 },
  { productId: "prod-rad-atom", slug: "rad-atom", price: 30 },
  { productId: "prod-normatec-3", slug: "hyperice-normatec-3", price: 999 },
  { productId: "prod-normatec-go", slug: "hyperice-normatec-go", price: 399 },
  { productId: "prod-therabody-recoveryair", slug: "therabody-recoveryair", price: 899 },
  { productId: "prod-oofos-oolala", slug: "oofos-oolala", price: 70 },
  { productId: "prod-oofos-oocandoo", slug: "oofos-oocandoo", price: 75 },
  { productId: "prod-hoka-ora-recovery-slide", slug: "hoka-ora-recovery-slide", price: 65 },
  { productId: "prod-cep-the-run-calf", slug: "cep-the-run-calf-sleeves", price: 42 },
  { productId: "prod-compressport-r2", slug: "compressport-r2", price: 55 },
  { productId: "prod-2xu-refresh-recovery", slug: "2xu-refresh-recovery", price: 50 },
  { productId: "prod-the-stick", slug: "the-stick", price: 45 },
  { productId: "prod-triggerpoint-stp", slug: "triggerpoint-stp", price: 40 },
  { productId: "prod-hyperice-vyper-3", slug: "hyperice-vyper-3", price: 199 },
  // Hydration wave2 + missing wave1 vest/flask offers
  { productId: "prod-nathan-vaporair-2", slug: "nathan-vaporair-2", price: 130 },
  { productId: "prod-adv-skin-12", slug: "salomon-adv-skin-12", price: 165 },
  { productId: "prod-salomon-adv-skin-5", slug: "salomon-adv-skin-5", price: 145 },
  { productId: "prod-nathan-vaporair-4", slug: "nathan-vaporair-4", price: 150 },
  { productId: "prod-nathan-pinnacle-12", slug: "nathan-pinnacle-12", price: 175 },
  { productId: "prod-ud-race-vest-6", slug: "ultimate-direction-race-vest-6", price: 155 },
  { productId: "prod-camelbak-zephyr-pro", slug: "camelbak-zephyr-pro", price: 170 },
  { productId: "prod-camelbak-circuit", slug: "camelbak-circuit-run-vest", price: 120 },
  { productId: "prod-camelbak-apex-pro", slug: "camelbak-apex-pro", price: 180 },
  { productId: "prod-osprey-duro-lt", slug: "osprey-duro-lt", price: 110 },
  { productId: "prod-osprey-dyna-lt", slug: "osprey-dyna-lt", price: 110 },
  { productId: "prod-osprey-duro-15", slug: "osprey-duro-15", price: 190 },
  { productId: "prod-patagonia-slope-runner", slug: "patagonia-slope-runner-vest", price: 160 },
  { productId: "prod-uswe-pace-8", slug: "uswe-pace-8", price: 165 },
  { productId: "prod-ultraspire-alpha-6", slug: "ultraspire-alpha-6", price: 140 },
  { productId: "prod-ultraspire-spry-5", slug: "ultraspire-spry-5", price: 125 },
  { productId: "prod-compressport-ultrun-s-pack", slug: "compressport-ultrun-s-pack", price: 155 },
  { productId: "prod-raidlight-responsiv-12", slug: "raidlight-responsiv-12", price: 150 },
  { productId: "prod-nnormal-race-vest", slug: "nnormal-race-vest", price: 175 },
  { productId: "prod-kiprun-900-race-5", slug: "kiprun-900-race-5", price: 40, retailerId: "ret-decathlon", url: "https://www.kiprun.com/en-GB/product/unisex-trail-run-competition-water-bottle-holder-vest-kiprun-900-race-5l-white_344527--c183m8786243" },
  { productId: "prod-kiprun-proteam-10", slug: "kiprun-proteam-10", price: 110, retailerId: "ret-decathlon", url: "https://www.decathlon.ie/p/363481-7371417-unisex-running-hydration-vest-kiprun-proteam-10-black.html" },
  { productId: "prod-on-ultra-vest-pro", slug: "on-ultra-vest-pro", price: 190 },
  { productId: "prod-black-diamond-distance-8", slug: "black-diamond-distance-8", price: 160 },
  { productId: "prod-kiprun-trail-10", slug: "kiprun-trail-10", price: 90 },
  { productId: "prod-nathan-peak", slug: "nathan-peak-hydration-waist-pack", price: 55 },
  { productId: "prod-ud-race-belt", slug: "ultimate-direction-race-belt", price: 45 },
  { productId: "prod-ud-ultra-belt", slug: "ultimate-direction-ultra-belt", price: 55 },
  { productId: "prod-naked-running-band", slug: "naked-running-band", price: 55 },
  { productId: "prod-ultraspire-fitted-race-belt", slug: "ultraspire-fitted-race-belt-2", price: 48 },
  { productId: "prod-compressport-free-belt-pro", slug: "compressport-free-belt-pro", price: 45 },
  { productId: "prod-salomon-pulse-belt", slug: "salomon-pulse-belt", price: 42 },
  { productId: "prod-hydrapak-softflask-speed-500", slug: "hydrapak-softflask-speed-500", price: 24 },
  { productId: "prod-hydrapak-skyflask-speed-500", slug: "hydrapak-skyflask-speed-500", price: 28 },
  { productId: "prod-nathan-speeddraw-insulated", slug: "nathan-speeddraw-plus-insulated-18oz", price: 32 },
  { productId: "prod-camelbak-crux-15", slug: "camelbak-crux-15", price: 38 },
  { productId: "prod-osprey-hydraulics-15", slug: "osprey-hydraulics-lt-15", price: 42 },
  { productId: "prod-hydrapak-shape-shift-15", slug: "hydrapak-shape-shift-15", price: 40 },
  { productId: "prod-hydrapak-softflask-250", slug: "hydrapak-softflask-250", price: 16 },
  { productId: "prod-hydrapak-tube-kit", slug: "hydrapak-tube-kit", price: 18 },
  // Clothing wave2 offers
  { productId: "prod-tracksmith-session-short-men", slug: "tracksmith-session-short-men", price: 78 },
  { productId: "prod-tracksmith-session-short-women", slug: "tracksmith-session-short-women", price: 78 },
  { productId: "prod-janji-multi-short-men", slug: "janji-multi-short-men", price: 78 },
  { productId: "prod-janji-pace-short-women", slug: "janji-pace-short-women", price: 68 },
  { productId: "prod-patagonia-strider-pro-men", slug: "patagonia-strider-pro-men", price: 79 },
  { productId: "prod-patagonia-trailfarer-short-women", slug: "patagonia-trailfarer-short-women", price: 75 },
  { productId: "prod-rabbit-fuel-n-fly-men", slug: "rabbit-fuel-n-fly-men", price: 72 },
  { productId: "prod-brooks-sherpa-7-men", slug: "brooks-sherpa-7-men", price: 55 },
  { productId: "prod-brooks-chaser-5-women", slug: "brooks-chaser-5-women", price: 52 },
  { productId: "prod-nb-rc-essential-short-men", slug: "nb-rc-essential-short-men", price: 45 },
  { productId: "prod-lululemon-pace-breaker-men", slug: "lululemon-pace-breaker-men", price: 78 },
  { productId: "prod-lululemon-hotty-hot-women", slug: "lululemon-hotty-hot-women", price: 68 },
  { productId: "prod-adidas-own-the-run-short-men", slug: "adidas-own-the-run-short-men", price: 40 },
  { productId: "prod-on-performance-short-men", slug: "on-performance-short-men", price: 70 },
  { productId: "prod-tracksmith-twilight-half-men", slug: "tracksmith-twilight-half-men", price: 88 },
  { productId: "prod-tracksmith-turnover-tight-women", slug: "tracksmith-turnover-tight-women", price: 118 },
  { productId: "prod-brooks-method-tight-women", slug: "brooks-method-tight-women", price: 85 },
  { productId: "prod-nike-fast-tight-men", slug: "nike-fast-tight-men", price: 75 },
  { productId: "prod-on-performance-tight-women", slug: "on-performance-tight-women", price: 100 },
  { productId: "prod-craft-adv-essence-tight-men", slug: "craft-adv-essence-tight-men", price: 60 },
  { productId: "prod-patagonia-endless-run-tight-women", slug: "patagonia-endless-run-tight-women", price: 99 },
  { productId: "prod-lululemon-fast-and-free-women", slug: "lululemon-fast-and-free-women", price: 128 },
  { productId: "prod-brooks-canopy-jacket-unisex", slug: "brooks-canopy-jacket-men", price: 110 },
  { productId: "prod-brooks-notch-thermal-men", slug: "brooks-notch-thermal-men", price: 100 },
  { productId: "prod-patagonia-houdini-men", slug: "patagonia-houdini-men", price: 119 },
  { productId: "prod-nike-impossibly-light-men", slug: "nike-impossibly-light-men", price: 110 },
  { productId: "prod-on-weather-jacket-men", slug: "on-weather-jacket-men", price: 190 },
  { productId: "prod-craft-adv-essence-light-wind-men", slug: "craft-adv-essence-light-wind-men", price: 80 },
  { productId: "prod-salomon-bonatti-wp-men", slug: "salomon-bonatti-wp-men", price: 180 },
  { productId: "prod-salomon-bonatti-wp-women", slug: "salomon-bonatti-wp-women", price: 180 },
  { productId: "prod-janji-rainrunner-unisex", slug: "janji-rainrunner-men", price: 148 },
  { productId: "prod-tnf-flight-series-jacket-men", slug: "tnf-flight-series-jacket-men", price: 160 },
  { productId: "prod-nike-dri-fit-miler-men", slug: "nike-dri-fit-miler-men", price: 35 },
  { productId: "prod-nike-dri-fit-miler-women", slug: "nike-dri-fit-miler-women", price: 35 },
  { productId: "prod-tracksmith-van-cortlandt-tee-men", slug: "tracksmith-van-cortlandt-tee-men", price: 58 },
  { productId: "prod-janji-run-tee-men", slug: "janji-run-tee-men", price: 48 },
  { productId: "prod-patagonia-capilene-cool-daily-men", slug: "patagonia-capilene-cool-daily-men", price: 49 },
  { productId: "prod-adidas-own-the-run-tee-men", slug: "adidas-own-the-run-tee-men", price: 30 },
  { productId: "prod-tracksmith-harrier-singlet-men", slug: "tracksmith-harrier-singlet-men", price: 68 },
  { productId: "prod-nike-aeroswift-singlet-men", slug: "nike-aeroswift-singlet-men", price: 55 },
  { productId: "prod-asics-race-singlet-men", slug: "asics-race-singlet-men", price: 40 },
  { productId: "prod-tracksmith-brighton-ls-men", slug: "tracksmith-brighton-ls-men", price: 78 },
  { productId: "prod-nike-element-ls-men", slug: "nike-element-ls-men", price: 55 },
  { productId: "prod-patagonia-capilene-thermal-crew-unisex", slug: "patagonia-capilene-thermal-crew-men", price: 89 },
  { productId: "prod-odlo-active-warm-eco-men", slug: "odlo-active-warm-eco-men", price: 55 },
  { productId: "prod-patagonia-capilene-midweight-zip-men", slug: "patagonia-capilene-midweight-zip-men", price: 99 },
  { productId: "prod-odlo-active-warm-eco-bottom-men", slug: "odlo-active-warm-eco-bottom-men", price: 50 },
  { productId: "prod-craft-active-extreme-x-men", slug: "craft-active-extreme-x-men", price: 70 },
  { productId: "prod-patagonia-nano-puff-vest-men", slug: "patagonia-nano-puff-vest-men", price: 179 },
  { productId: "prod-brooks-lsd-thermal-vest-men", slug: "brooks-lsd-thermal-vest-men", price: 90 },
  { productId: "prod-craft-adv-essence-light-wind-vest-men", slug: "craft-adv-essence-light-wind-vest-men", price: 70 },
  { productId: "prod-saxx-kinetic-hd-men", slug: "saxx-kinetic-hd-men", price: 38 },
  { productId: "prod-lululemon-always-in-motion-men", slug: "lululemon-always-in-motion-men", price: 34 },
  { productId: "prod-brooks-dare-crossback", slug: "brooks-dare-crossback", price: 55 },
  { productId: "prod-nike-swoosh-medium-support", slug: "nike-swoosh-medium-support", price: 40 },
  { productId: "prod-lululemon-energy-bra", slug: "lululemon-energy-bra", price: 58 },
  { productId: "prod-tracksmith-brighton-bra", slug: "tracksmith-brighton-bra", price: 68 },
  { productId: "prod-ciele-gocap-athletics", slug: "ciele-gocap-athletics", price: 45 },
  { productId: "prod-brooks-notch-thermal-beanie", slug: "brooks-notch-thermal-beanie", price: 32 },
  { productId: "prod-nike-aerobill-cap", slug: "nike-aerobill-cap", price: 28 },
  { productId: "prod-smartwool-thermal-merino-glove", slug: "smartwool-thermal-merino-glove", price: 35 },
  { productId: "prod-nike-therma-fit-glove", slug: "nike-therma-fit-glove", price: 32 },
  { productId: "prod-craft-adv-lumen-glove", slug: "craft-adv-lumen-glove", price: 35 },
  { productId: "prod-darn-tough-run-1-4", slug: "darn-tough-run-1-4", price: 22 },
  { productId: "prod-smartwool-run-targeted-cushion", slug: "smartwool-run-targeted-cushion", price: 24 },
  { productId: "prod-stance-run-crew", slug: "stance-run-crew", price: 20 },
  { productId: "prod-balega-blister-resist", slug: "balega-blister-resist", price: 18 },
  // Packs & carry wave2
  { productId: "prod-ud-fastpack-20", slug: "ultimate-direction-fastpack-20", price: 175 },
  { productId: "prod-ud-fastpack-her-20", slug: "ultimate-direction-fastpack-her-20", price: 175 },
  { productId: "prod-ud-fastpack-30", slug: "ultimate-direction-fastpack-30", price: 195 },
  { productId: "prod-osprey-talon-velocity-20", slug: "osprey-talon-velocity-20", price: 170 },
  { productId: "prod-osprey-tempest-velocity-20", slug: "osprey-tempest-velocity-20", price: 170 },
  { productId: "prod-osprey-talon-velocity-30", slug: "osprey-talon-velocity-30", price: 190 },
  { productId: "prod-black-diamond-distance-15", slug: "black-diamond-distance-15", price: 180 },
  { productId: "prod-black-diamond-distance-22", slug: "black-diamond-distance-22", price: 200 },
  { productId: "prod-salomon-xa-15", slug: "salomon-xa-15", price: 160 },
  { productId: "prod-camelbak-octane-22", slug: "camelbak-octane-22", price: 155 },
  { productId: "prod-salomon-trailblazer-20", slug: "salomon-trailblazer-20", price: 110 },
  { productId: "prod-salomon-custom-quiver", slug: "salomon-custom-quiver", price: 35 },
  { productId: "prod-leki-trail-running-quiver", slug: "leki-trail-running-quiver", price: 45 },
  { productId: "prod-ud-utility-bag", slug: "ultimate-direction-utility-bag", price: 28 },
  { productId: "prod-salomon-soft-flask-stash", slug: "salomon-soft-flask-stash", price: 25 },
  { productId: "prod-nathan-zippered-stash", slug: "nathan-zippered-stash", price: 22 },
  // Accessories wave2 — headphones, sunglasses, headlamps, safety
  { productId: "prod-shokz-openrun", slug: "shokz-openrun", price: 129 },
  { productId: "prod-shokz-openfit-2", slug: "shokz-openfit-2", price: 169 },
  { productId: "prod-shokz-opendots-one", slug: "shokz-opendots-one", price: 149 },
  { productId: "prod-sony-linkbuds-open", slug: "sony-linkbuds-open", price: 199 },
  { productId: "prod-sony-linkbuds-fit", slug: "sony-linkbuds-fit", price: 179 },
  { productId: "prod-jabra-elite-8-active", slug: "jabra-elite-8-active", price: 199 },
  { productId: "prod-jabra-elite-10", slug: "jabra-elite-10", price: 249 },
  { productId: "prod-beats-powerbeats-pro-2", slug: "beats-powerbeats-pro-2", price: 249 },
  { productId: "prod-beats-fit-pro", slug: "beats-fit-pro", price: 199 },
  { productId: "prod-soundcore-aerofit-2", slug: "soundcore-aerofit-2", price: 99 },
  { productId: "prod-soundcore-sport-x20", slug: "soundcore-sport-x20", price: 129 },
  { productId: "prod-huawei-freeclip", slug: "huawei-freeclip", price: 179 },
  { productId: "prod-suunto-wing", slug: "suunto-wing", price: 199 },
  { productId: "prod-apple-airpods-4", slug: "apple-airpods-4", price: 149 },
  { productId: "prod-oakley-radar-ev-path", slug: "oakley-radar-ev-path", price: 189 },
  { productId: "prod-oakley-sutro-lite", slug: "oakley-sutro-lite", price: 169 },
  { productId: "prod-oakley-kato", slug: "oakley-kato", price: 249 },
  { productId: "prod-oakley-flak-2xl", slug: "oakley-flak-2-0-xl", price: 179 },
  { productId: "prod-smith-shift-mag", slug: "smith-shift-mag", price: 249 },
  { productId: "prod-smith-attack-mag", slug: "smith-attack-mag", price: 229 },
  { productId: "prod-julbo-ultimate", slug: "julbo-ultimate", price: 189 },
  { productId: "prod-julbo-rush", slug: "julbo-rush", price: 159 },
  { productId: "prod-rudy-cutline", slug: "rudy-project-cutline", price: 199 },
  { productId: "prod-100-s3", slug: "100-percent-s3", price: 209 },
  { productId: "prod-roka-phantom-air", slug: "roka-phantom-air", price: 219 },
  { productId: "prod-tifosi-rail", slug: "tifosi-rail", price: 79 },
  { productId: "prod-tifosi-vogel", slug: "tifosi-vogel", price: 69 },
  { productId: "prod-goodr-circle-gs", slug: "goodr-circle-gs", price: 25 },
  { productId: "prod-petzl-nao-rl", slug: "petzl-nao-rl", price: 190 },
  { productId: "prod-petzl-actik-core", slug: "petzl-actik-core", price: 85 },
  { productId: "prod-petzl-iko-core", slug: "petzl-iko-core", price: 95 },
  { productId: "prod-bd-storm-500-r", slug: "black-diamond-storm-500-r", price: 90 },
  { productId: "prod-bd-distance-1500", slug: "black-diamond-distance-1500", price: 200 },
  { productId: "prod-silva-smini", slug: "silva-smini", price: 70 },
  { productId: "prod-ledlenser-neo9r", slug: "ledlenser-neo9r", price: 150 },
  { productId: "prod-ledlenser-neo5r", slug: "ledlenser-neo5r", price: 90 },
  { productId: "prod-fenix-hm65r-t", slug: "fenix-hm65r-t", price: 140 },
  { productId: "prod-biolite-headlamp-800", slug: "biolite-headlamp-800-pro", price: 120 },
  { productId: "prod-biolite-headlamp-425", slug: "biolite-headlamp-425", price: 70 },
  { productId: "prod-nitecore-nu25", slug: "nitecore-nu25-ul", price: 45 },
  { productId: "prod-nitecore-nu43", slug: "nitecore-nu43", price: 65 },
  { productId: "prod-amphipod-xinglet", slug: "amphipod-xinglet", price: 32 },
  { productId: "prod-amphipod-xinglet-optic-beam", slug: "amphipod-xinglet-optic-beam", price: 48 },
  { productId: "prod-amphipod-vizlet", slug: "amphipod-vizlet-led", price: 28 },
  { productId: "prod-proviz-reflect360-vest", slug: "proviz-reflect360-running-vest", price: 55 },
  { productId: "prod-knog-frog-v3", slug: "knog-frog-v3", price: 30 },
  { productId: "prod-knog-cobber-mid", slug: "knog-cobber-mid", price: 45 },
  { productId: "prod-nightrunner-270", slug: "night-runner-270", price: 80 },
  { productId: "prod-nathan-lightbender", slug: "nathan-lightbender-rx", price: 35 },
  { productId: "prod-nathan-strobe", slug: "nathan-lux-strobe-rx", price: 28 },
  { productId: "prod-road-id-wrist", slug: "road-id-wrist-id", price: 25 },
  { productId: "prod-shes-birdie-alarm", slug: "shes-birdie-personal-alarm", price: 30 },
  { productId: "prod-flipbelt-zippered-reflective", slug: "flipbelt-zipper-reflective", price: 38 },
  // Nutrition wave1 — single-serve / pack seed EUR prices (illustrative)
  { productId: "prod-maurten-gel-100", slug: "maurten-gel-100", price: 3.2 },
  { productId: "prod-maurten-gel-100-caf", slug: "maurten-gel-100-caf", price: 3.5 },
  { productId: "prod-maurten-gel-160", slug: "maurten-gel-160", price: 3.9 },
  { productId: "prod-sis-go-isotonic-gel", slug: "sis-go-isotonic-gel", price: 2.5 },
  { productId: "prod-sis-beta-fuel-gel", slug: "sis-beta-fuel-gel", price: 3.4 },
  { productId: "prod-gu-energy-gel", slug: "gu-energy-gel", price: 2.6 },
  { productId: "prod-gu-roctane-gel", slug: "gu-roctane-gel", price: 3.1 },
  { productId: "prod-precision-pf30-gel", slug: "precision-pf30-gel", price: 3.3 },
  { productId: "prod-neversecond-c30-gel", slug: "neversecond-c30-gel", price: 3.2 },
  { productId: "prod-spring-awesome-sauce", slug: "spring-awesome-sauce", price: 3.8 },
  { productId: "prod-huma-gel-original", slug: "huma-gel-original", price: 3.5 },
  { productId: "prod-honey-stinger-gel", slug: "honey-stinger-gel", price: 2.7 },
  { productId: "prod-styrkr-gel30", slug: "styrkr-gel30", price: 3.0 },
  { productId: "prod-226ers-high-energy-gel", slug: "226ers-high-energy-gel", price: 3.1 },
  { productId: "prod-clif-bloks", slug: "clif-bloks", price: 6.5 },
  { productId: "prod-gu-chews", slug: "gu-chews", price: 5.5 },
  { productId: "prod-skratch-chews", slug: "skratch-chews", price: 5.9 },
  { productId: "prod-veloforte-chews", slug: "veloforte-chews", price: 6.2 },
  { productId: "prod-clif-bar-original", slug: "clif-bar-original", price: 2.4 },
  { productId: "prod-naak-ultra-energy-bar", slug: "naak-ultra-energy-bar", price: 3.2 },
  { productId: "prod-powerbar-energize", slug: "powerbar-energize", price: 2.3 },
  { productId: "prod-maurten-drink-mix-160", slug: "maurten-drink-mix-160", price: 28 },
  { productId: "prod-maurten-drink-mix-320", slug: "maurten-drink-mix-320", price: 36 },
  { productId: "prod-sis-beta-fuel-drink", slug: "sis-beta-fuel-drink", price: 24 },
  { productId: "prod-tailwind-endurance", slug: "tailwind-endurance", price: 32 },
  { productId: "prod-precision-pf30-drink", slug: "precision-pf30-drink", price: 26 },
  { productId: "prod-neversecond-c30-drink", slug: "neversecond-c30-drink", price: 25 },
  { productId: "prod-naak-ultra-energy-drink", slug: "naak-ultra-energy-drink", price: 29 },
  { productId: "prod-styrkr-mix90", slug: "styrkr-mix90", price: 27 },
  { productId: "prod-skratch-sport-hydration", slug: "skratch-sport-hydration", price: 22 },
  { productId: "prod-precision-ph1500", slug: "precision-ph1500", price: 24 },
  { productId: "prod-nuun-sport", slug: "nuun-sport", price: 9.5 },
  { productId: "prod-high5-zero", slug: "high5-zero", price: 8.5 },
  { productId: "prod-saltstick-caps", slug: "saltstick-caps", price: 18 },
  { productId: "prod-saltstick-fastchews", slug: "saltstick-fastchews", price: 12 },
  { productId: "prod-high5-energy-gel", slug: "high5-energy-gel", price: 2.4 },
  { productId: "prod-enervit-carbo-gel", slug: "enervit-c2-1-carbo-gel", price: 3.0 },
  { productId: "prod-veloforte-bar", slug: "veloforte-energy-bar", price: 2.8 },

  // Running accessories wave2
  { productId: "prod-buff-coolnet-uv", slug: "buff-coolnet-uv", price: 24 },
  { productId: "prod-buff-merino-lightweight", slug: "buff-merino-lightweight", price: 32 },
  { productId: "prod-buff-polar", slug: "buff-polar", price: 28 },
  { productId: "prod-compressport-armforce", slug: "compressport-armforce", price: 35 },
  { productId: "prod-squirrels-nut-butter", slug: "squirrels-nut-butter", price: 14 },
  { productId: "prod-2toms-sportshield", slug: "2toms-sportshield", price: 13 },
  { productId: "prod-amphipod-reflective-armband", slug: "amphipod-reflective-armband", price: 16 },
  { productId: "prod-dirty-girl-gaiters", slug: "dirty-girl-gaiters", price: 28 },
  { productId: "prod-outdoor-research-ferrosi-gaiters", slug: "outdoor-research-ferrosi-gaiters", price: 45 },
  { productId: "prod-amphipod-airflow-armband", slug: "amphipod-airflow-armband", price: 30 },

  // Hydration / socks / belts wave3
  { productId: "prod-salomon-soft-flask-speed-500", slug: "salomon-soft-flask-speed-500", price: 24 },
  { productId: "prod-ud-body-bottle-500", slug: "ultimate-direction-body-bottle-500", price: 22 },
  { productId: "prod-nathan-softflask-18oz", slug: "nathan-softflask-18oz", price: 20 },
  { productId: "prod-amphipod-hydraform-handheld", slug: "amphipod-hydraform-ergo-lite-handheld", price: 28 },
  { productId: "prod-nathan-quickdraw-plus", slug: "nathan-quickdraw-plus-handheld", price: 26 },
  { productId: "prod-camelbak-quick-grip-chill", slug: "camelbak-quick-grip-chill", price: 32 },
  { productId: "prod-hydrapak-contour-2l", slug: "hydrapak-contour-2l", price: 45 },
  { productId: "prod-salomon-soft-reservoir-15", slug: "salomon-soft-reservoir-15", price: 42 },
  { productId: "prod-bombas-performance-running-quarter", slug: "bombas-performance-running-quarter", price: 18 },
  { productId: "prod-swiftwick-aspire-four", slug: "swiftwick-aspire-four", price: 20 },
  { productId: "prod-hilly-marathon-fresh", slug: "hilly-marathon-fresh", price: 14 },
  { productId: "prod-drymax-run-lite-mesh", slug: "drymax-run-lite-mesh", price: 16 },
  { productId: "prod-sockwell-compression-light", slug: "sockwell-compression-light-cushion", price: 28 },
  { productId: "prod-wrightsock-coolmesh-ii", slug: "wrightsock-coolmesh-ii", price: 18 },
  { productId: "prod-amphipod-airflow-lite-belt", slug: "amphipod-airflow-lite-belt", price: 32 },
  { productId: "prod-fitletic-fully-loaded", slug: "fitletic-fully-loaded", price: 38 },
  { productId: "prod-nathan-zipster-lite", slug: "nathan-zipster-lite", price: 30 },
  { productId: "prod-kiprun-running-belt", slug: "kiprun-running-belt", price: 12 },
];

export const nlOfferBackfill: Offer[] = [
  ...RUNNING_SHOE_SEEDS,
  ...WATCH_SEEDS,
  ...ACCESSORY_SEEDS,
].map(nlOffer);
