import type { Product } from "@/domain/products/types";
import { publishedMeta, scheduledMeta, draftMeta } from "@/content/config";
import { padelAllProducts } from "@/content/padel";
import { fitnessProducts } from "@/content/fitness";
import { racketProducts } from "@/content/racket";
import { categoryFallbackImage } from "@/content/running/media";
import { runningShoesWave2 } from "@/content/running/products/shoes-wave2";
import { runningShoesWave3 } from "@/content/running/products/shoes-wave3-niches";
import { runningNnormalTrail } from "@/content/running/products/nnormal-trail";
import { runningWatchesAndHrm } from "@/content/running/products/watches-hrm";
import { runningWatchesWave2 } from "@/content/running/products/watches-wave2";
import { runningWatchesP75Gaps } from "@/content/running/products/watches-p75-gaps";
import { runningHrmWave2 } from "@/content/running/products/hrm-wave2";
import { runningGearWave1 } from "@/content/running/products/gear-wave1";
import { runningAccessoriesWave2 } from "@/content/running/products/accessories-wave2";
import { runningHydrationWave2 } from "@/content/running/products/hydration-wave2";
import { runningHydrationSocksBeltsWave3 } from "@/content/running/products/hydration-socks-belts-wave3";
import { runningClothingWave2 } from "@/content/running/products/clothing-wave2";
import { runningPacksCarryWave2 } from "@/content/running/products/packs-carry-wave2";
import { runningHeadphonesWave2 } from "@/content/running/products/headphones-wave2";
import { runningSunglassesWave2 } from "@/content/running/products/sunglasses-wave2";
import { runningHeadlampsWave2 } from "@/content/running/products/headlamps-wave2";
import { runningSafetyWave2 } from "@/content/running/products/safety-wave2";
import { runningNutritionWave1 } from "@/content/running/products/nutrition-wave1";
import { runningRecoveryWave2 } from "@/content/running/products/recovery-wave2";
import { applyRunningShoesLaunchReadyEnrichment } from "@/content/running/shoes-launch-ready-enrichment";
import { applyGearCoreLaunchReadyEnrichment } from "@/content/running/gear-core-launch-ready";
import { applyWeakCatLaunchReadyEnrichment } from "@/content/running/weak-cats-launch-ready";
import { applyNmwCompletionEnrichment } from "@/content/running/nmw-completion-launch-ready";
import { applyReviewProductLinkage } from "@/content/running/review-product-linkage";
import { applyAlternativesP65Graph } from "@/content/alternatives-p65-completion";
import { applyDecisionGraphP70Quality } from "@/content/decision-graph-p70-quality";

const pub = publishedMeta();

/**
 * Representative Running seed products for architecture validation.
 * Incomplete specs use null — do not invent values.
 */
const productsRaw: Product[] = [
  {
    id: "prod-novablast-5",
    slug: "asics-novablast-5",
    brandId: "brand-asics",
    familyId: "fam-novablast",
    generation: "5",
    name: "Novablast 5",
    fullName: "ASICS Novablast 5",
    shortDescription:
      "Bouncy neutral daily trainer suited to easy miles and long runs.",
    verdict:
      "A versatile, cushioned daily trainer suited to high-volume road training and long runs, but not the best choice for runners wanting an aggressive race-day shoe or technical trail grip.",
    seoTitle: "ASICS Novablast 5: Specs, Performance & Best Uses",
    seoDescription:
      "See ASICS Novablast 5 specs, use-case scores, strengths, trade-offs, alternatives and where to buy — structured Kitletics recommendations for daily training.",
    releaseDate: "2024-12-01",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-daily-trainers", "sub-neutral", "sub-max-cushion"],
    useCaseIds: [
      "uc-daily-training",
      "uc-long-runs",
      "uc-easy-runs",
      "uc-neutral-runners",
      "uc-comfort",
      "uc-intermediate",
    ],
    specifications: {
      weight: 255,
      heelStack: 41,
      forefootStack: 33,
      drop: 8,
      cushionLevel: "high",
      cushionFeel: "soft",
      stability: "neutral",
      rideCharacter: "rockered",
      energyReturn: "high",
      flexibility: "moderate",
      upper: "Engineered mesh",
      midsole: "FF BLAST PLUS ECO",
      outsole: "AHAR rubber (partial)",
      plate: false,
      plateMaterial: "none",
      terrain: ["road", "treadmill"],
      widthOptions: ["standard"],
      archSupport: "medium",
      grip: "road",
      durability: "moderate",
      breathability: "high",
      raceLegal: true,
      recommendedPaceRange: null,
      recommendedDistance: ["daily", "half", "marathon"],
      recommendedRunnerWeightRange: null,
      trainingTypes: ["easy", "long", "recovery"],
      surface: ["asphalt", "treadmill"],
      weatherSuitability: ["dry", "all-season"],
    },
    strengths: ["Soft energetic ride", "Good for high easy mileage"],
    weaknesses: ["Not a stability shoe", "Less ideal for fast intervals"],
    recommendationScore: 88,
    valueScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-novablast-5", "ASICS Novablast 5 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-nb5-nl", "offer-nb5-uk", "offer-nb5-us"],
    evidenceIds: ["ev-nb5-mfr", "ev-nb5-editorial"],
    relatedProductIds: ["prod-nimbus-27", "prod-ghost-16"],
    alternativeProductIds: ["prod-ghost-16", "prod-clifton-9", "prod-nimbus-27"],
    reviewId: "review-novablast-5",
    ...pub,
  },
  {
    id: "prod-novablast-4",
    slug: "asics-novablast-4",
    brandId: "brand-asics",
    familyId: "fam-novablast",
    generation: "4",
    name: "Novablast 4",
    fullName: "ASICS Novablast 4",
    shortDescription: "Previous-generation Novablast daily trainer.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-daily-trainers", "sub-neutral"],
    useCaseIds: ["uc-daily-training", "uc-easy-runs"],
    specifications: {
      weight: null,
      drop: 8,
      cushionLevel: "high",
      stability: "neutral",
      plate: false,
      plateMaterial: "none",
      terrain: ["road"],
    },
    strengths: ["Often discounted vs current gen"],
    weaknesses: ["Superseded by Novablast 5"],
    recommendationScore: 74,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage("cat-running-shoes", "prod-novablast-4", "ASICS Novablast 4 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-nb4-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-novablast-5"],
    alternativeProductIds: ["prod-novablast-5"],
    ...pub,
  },
  {
    id: "prod-nimbus-27",
    slug: "asics-gel-nimbus-27",
    brandId: "brand-asics",
    familyId: "fam-gel-nimbus",
    generation: "27",
    name: "GEL-Nimbus 27",
    fullName: "ASICS GEL-Nimbus 27",
    shortDescription: "Max-cushion neutral shoe for easy and recovery miles.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-max-cushion", "sub-neutral", "sub-daily-trainers", "sub-recovery-walk"],
    useCaseIds: [
      "uc-easy-runs",
      "uc-recovery-runs",
      "uc-long-runs",
      "uc-heavy",
      "uc-comfort",
      "uc-injury-conscious",
    ],
    specifications: {
      weight: 305,
      heelStack: 43.5,
      forefootStack: 35.5,
      drop: 8,
      cushionLevel: "maximum",
      cushionFeel: "plush",
      stability: "neutral",
      rideCharacter: "protective",
      energyReturn: "moderate",
      flexibility: "stiff",
      upper: "Engineered jacquard mesh",
      midsole: "FF BLAST PLUS ECO + PureGEL",
      outsole: "HYBRID ASICSGRIP (ASICSGRIP + AHARPLUS)",
      plate: false,
      plateMaterial: "none",
      terrain: ["road"],
      widthOptions: ["standard", "wide"],
      archSupport: "medium",
      grip: "road",
      durability: "high",
      breathability: "high",
      raceLegal: true,
      // ASICS does not publish pace or runner-weight bands — leave null (do not invent).
      recommendedPaceRange: null,
      recommendedDistance: ["daily", "half", "marathon"],
      recommendedRunnerWeightRange: null,
      trainingTypes: ["easy", "long", "recovery"],
      surface: ["asphalt", "treadmill"],
      weatherSuitability: ["dry", "wet", "all-season"],
    },
    strengths: ["Maximum cushioning", "Wide options"],
    weaknesses: ["Heavier than tempo shoes"],
    recommendationScore: 86,
    valueScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-nimbus-27", "ASICS GEL-Nimbus 27 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-nimbus-nl", "offer-nimbus-uk"],
    evidenceIds: ["ev-nimbus-mfr", "ev-nimbus-editorial"],
    relatedProductIds: ["prod-novablast-5", "prod-clifton-9"],
    alternativeProductIds: ["prod-clifton-9", "prod-ghost-16"],
    ...pub,
  },
  {
    id: "prod-pegasus-41",
    slug: "nike-pegasus-41",
    brandId: "brand-nike",
    familyId: "fam-pegasus",
    generation: "41",
    name: "Pegasus 41",
    fullName: "Nike Pegasus 41",
    shortDescription: "Versatile daily trainer for mixed pacing.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-treadmill"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-daily-trainers", "sub-neutral"],
    useCaseIds: [
      "uc-daily-training",
      "uc-beginners",
      "uc-intermediate",
      "uc-tempo-runs",
    ],
    specifications: {
      weight: null,
      drop: 10,
      cushionLevel: "medium",
      cushionFeel: "balanced",
      stability: "neutral",
      plate: false,
      plateMaterial: "none",
      terrain: ["road", "treadmill"],
      trainingTypes: ["easy", "tempo", "long"],
      recommendedDistance: ["daily", "10k", "half"],
    },
    strengths: ["Versatile workhorse", "Widely available"],
    weaknesses: ["Not max cushion", "Not a pure racer"],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage("cat-running-shoes", "prod-pegasus-41", "Nike Pegasus 41 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-pegasus41-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-ghost-16", "prod-rebel-4"],
    alternativeProductIds: ["prod-ghost-16", "prod-novablast-5"],
    ...pub,
  },
  {
    id: "prod-ghost-16",
    slug: "brooks-ghost-16",
    brandId: "brand-brooks",
    familyId: "fam-ghost",
    generation: "16",
    name: "Ghost 16",
    fullName: "Brooks Ghost 16",
    shortDescription: "Soft neutral daily trainer popular with beginners.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-daily-trainers", "sub-neutral"],
    useCaseIds: [
      "uc-beginners",
      "uc-daily-training",
      "uc-first-5k",
      "uc-comfort",
      "uc-neutral-runners",
    ],
    specifications: {
      weight: null,
      drop: 12,
      cushionLevel: "high",
      cushionFeel: "soft",
      stability: "neutral",
      plate: false,
      plateMaterial: "none",
      terrain: ["road"],
      widthOptions: ["narrow", "standard", "wide", "extra-wide"],
      trainingTypes: ["easy", "long", "recovery"],
    },
    strengths: ["Beginner-friendly", "Excellent width range"],
    weaknesses: ["Higher drop", "Less energetic than Novablast"],
    recommendationScore: 85,
    valueScore: 83,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage("cat-running-shoes", "prod-ghost-16", "Brooks Ghost 16 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-ghost16-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-novablast-5", "prod-pegasus-41"],
    alternativeProductIds: ["prod-novablast-5", "prod-pegasus-41"],
    ...pub,
  },
  {
    id: "prod-clifton-9",
    slug: "hoka-clifton-9",
    brandId: "brand-hoka",
    familyId: "fam-clifton",
    generation: "9",
    name: "Clifton 9",
    fullName: "HOKA Clifton 9",
    shortDescription: "Lightweight max-cushion daily trainer.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-max-cushion", "sub-daily-trainers", "sub-neutral"],
    useCaseIds: [
      "uc-daily-training",
      "uc-long-runs",
      "uc-heavy",
      "uc-comfort",
    ],
    specifications: {
      weight: null,
      drop: 5,
      cushionLevel: "maximum",
      cushionFeel: "plush",
      stability: "neutral",
      plate: false,
      plateMaterial: "none",
      terrain: ["road"],
      trainingTypes: ["easy", "long", "recovery"],
    },
    strengths: ["Light for the stack", "Smooth rocker"],
    weaknesses: ["Fit can run short for some"],
    recommendationScore: 87,
    valueScore: 79,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-clifton-9", "HOKA Clifton 9 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-clifton9-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-nimbus-27"],
    alternativeProductIds: ["prod-nimbus-27", "prod-novablast-5"],
    ...pub,
  },
  {
    id: "prod-endorphin-speed-4",
    slug: "saucony-endorphin-speed-4",
    brandId: "brand-saucony",
    familyId: "fam-endorphin-speed",
    generation: "4",
    name: "Endorphin Speed 4",
    fullName: "Saucony Endorphin Speed 4",
    shortDescription: "Nylon-plated tempo shoe for workouts and faster long runs.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-tempo", "sub-race", "sub-neutral"],
    useCaseIds: [
      "uc-tempo-runs",
      "uc-intervals",
      "uc-half",
      "uc-marathon",
      "uc-pb",
      "uc-advanced",
    ],
    specifications: {
      weight: null,
      drop: 8,
      cushionLevel: "high",
      cushionFeel: "balanced",
      stability: "neutral",
      energyReturn: "very-high",
      plate: true,
      plateMaterial: "nylon",
      terrain: ["road", "track"],
      trainingTypes: ["tempo", "intervals", "race", "long"],
      recommendedDistance: ["10k", "half", "marathon"],
      raceLegal: true,
    },
    strengths: ["Fast everyday plated shoe", "Versatile race/workout use"],
    weaknesses: ["Overkill for easy recovery jogs"],
    recommendationScore: 90,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-endorphin-speed-4", "Saucony Endorphin Speed 4 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-speed4-nl"],
    evidenceIds: ["ev-speed-editorial"],
    relatedProductIds: ["prod-boston-12"],
    alternativeProductIds: ["prod-boston-12", "prod-rebel-4"],
    ...pub,
  },
  {
    id: "prod-rebel-4",
    slug: "new-balance-fuelcell-rebel-v4",
    brandId: "brand-new-balance",
    familyId: "fam-rebel",
    generation: "4",
    name: "FuelCell Rebel v4",
    fullName: "New Balance FuelCell Rebel v4",
    shortDescription:
      "Previous-generation FuelCell uptempo trainer (~199 g men's US 9) for mixed easy and faster road sessions — unplated, 6 mm drop, not a max-cushion long-run shoe.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-tempo", "sub-daily-trainers", "sub-neutral"],
    useCaseIds: ["uc-tempo-runs", "uc-daily-training", "uc-speed-work"],
    specifications: {
      weight: null,
      drop: 6,
      cushionLevel: "medium",
      cushionFeel: "balanced",
      stability: "neutral",
      rideCharacter: "responsive",
      energyReturn: "high",
      flexibility: "flexible",
      upper: "Engineered mesh",
      midsole: "FuelCell",
      outsole: "Blown rubber",
      plate: false,
      plateMaterial: "none",
      terrain: ["road"],
      widthOptions: ["standard", "wide"],
      archSupport: "medium",
      grip: "road",
      durability: "moderate",
      breathability: "high",
      raceLegal: true,
      recommendedDistance: ["5k", "10k", "daily"],
      trainingTypes: ["easy", "tempo", "intervals"],
      surface: ["asphalt"],
      weatherSuitability: ["dry"],
      genderFit: ["men", "women"],
    },
    strengths: [
      "Light FuelCell pop for tempo, strides and mixed road weeks",
      "Official New Balance wide options alongside standard",
      "Unplated so easy miles stay in play unlike Speed-class nylon plates",
    ],
    weaknesses: [
      "Less protective on long easy and marathon-prep days",
      "Previous generation — Rebel v5 is the current platform",
    ],
    recommendationScore: 81,
    valueScore: 85,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-rebel-4", "New Balance FuelCell Rebel v4 — catalog placeholder"),
    videos: [],
    offerIds: [],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-rebel-v5", "prod-mach-6", "prod-endorphin-speed-4"],
    alternativeProductIds: ["prod-mach-6", "prod-endorphin-speed-4", "prod-pegasus-41"],
    ...pub,
  },
  {
    id: "prod-boston-12",
    slug: "adidas-adizero-boston-12",
    brandId: "brand-adidas",
    familyId: "fam-adizero-boston",
    generation: "12",
    name: "Adizero Boston 12",
    fullName: "Adidas Adizero Boston 12",
    shortDescription:
      "Tempo trainer used for road workouts and often for HYROX training.",
    lifecycleStatus: "current",
    sportIds: ["sport-running", "sport-hyrox"],
    disciplineIds: ["disc-running-road", "disc-running-racing"],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-tempo", "sub-daily-trainers", "sub-neutral"],
    useCaseIds: [
      "uc-tempo-runs",
      "uc-daily-training",
      "uc-long-runs",
      "uc-hyrox-training",
      "uc-half",
      "uc-5k",
    ],
    specifications: {
      weight: null,
      drop: 8,
      cushionLevel: "medium",
      cushionFeel: "balanced",
      stability: "neutral",
      plate: true,
      plateMaterial: "composite",
      terrain: ["road"],
      trainingTypes: ["tempo", "intervals", "long", "race"],
      recommendedDistance: ["5k", "10k", "half"],
    },
    strengths: ["Dual Running + HYROX relevance", "Responsive tempo ride"],
    weaknesses: ["Not a max-cushion easy shoe"],
    recommendationScore: 89,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-running-shoes", "prod-boston-12", "Adidas Adizero Boston 12 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-boston-nl", "offer-boston-uk", "offer-boston-de"],
    evidenceIds: ["ev-boston-editorial"],
    relatedProductIds: ["prod-endorphin-speed-4"],
    alternativeProductIds: ["prod-endorphin-speed-4", "prod-pegasus-41"],
    reviewId: "review-boston-12",
    ...pub,
  },
  {
    id: "prod-forerunner-965",
    slug: "garmin-forerunner-965",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "965",
    name: "Forerunner 965",
    fullName: "Garmin Forerunner 965",
    shortDescription: "AMOLED running watch with maps and training readiness.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-swimming"],
    disciplineIds: ["disc-running-road", "disc-running-trail", "disc-running-racing"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-premium"],
    useCaseIds: ["uc-advanced", "uc-high-mileage", "uc-marathon", "uc-pb"],
    specifications: {
      weight: 52,
      displayType: "amoled",
      displaySize: null,
      touchscreen: true,
      batterySmartwatch: null,
      batteryGps: null,
      multiBandGps: true,
      maps: true,
      navigation: true,
      music: true,
      payments: true,
      heartRate: true,
      ecg: false,
      spo2: true,
      runningDynamics: true,
      trainingReadiness: true,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Full training suite", "Bright AMOLED"],
    weaknesses: ["Premium price"],
    recommendationScore: 92,
    valueScore: 70,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage("cat-gps-watches", "prod-forerunner-965", "Garmin Forerunner 965 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-fr965-nl"],
    evidenceIds: ["ev-fr965-mfr"],
    relatedProductIds: ["prod-forerunner-255", "prod-coros-pace-3"],
    alternativeProductIds: ["prod-coros-pace-3", "prod-forerunner-255"],
    ...pub,
  },
  {
    id: "prod-forerunner-255",
    slug: "garmin-forerunner-255",
    brandId: "brand-garmin",
    familyId: "fam-forerunner",
    generation: "255",
    name: "Forerunner 255",
    fullName: "Garmin Forerunner 255",
    shortDescription: "Mid-range MIP running watch without onboard maps.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: ["uc-intermediate", "uc-beginners", "uc-first-half"],
    specifications: {
      weight: null,
      displayType: "mip",
      touchscreen: false,
      multiBandGps: true,
      maps: false,
      navigation: false,
      music: false,
      payments: false,
      heartRate: true,
      runningDynamics: true,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
    },
    strengths: ["Strong value", "Excellent battery for the price"],
    weaknesses: ["No maps", "No music"],
    recommendationScore: 86,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    images: categoryFallbackImage("cat-gps-watches", "prod-forerunner-255", "Garmin Forerunner 255 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-fr255-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-965", "prod-coros-pace-3"],
    alternativeProductIds: ["prod-coros-pace-3"],
    ...pub,
  },
  {
    id: "prod-coros-pace-3",
    slug: "coros-pace-3",
    brandId: "brand-coros",
    familyId: "fam-coros-pace",
    generation: "3",
    name: "Pace 3",
    fullName: "COROS Pace 3",
    shortDescription: "Lightweight GPS watch with strong battery life.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-road", "disc-running-trail"],
    categoryId: "cat-gps-watches",
    subcategoryIds: ["sub-gps-performance"],
    useCaseIds: ["uc-intermediate", "uc-high-mileage", "uc-marathon"],
    specifications: {
      weight: 30,
      displayType: "mip",
      touchscreen: false,
      multiBandGps: true,
      maps: false,
      navigation: true,
      music: true,
      payments: false,
      heartRate: true,
      runningDynamics: false,
      trainingReadiness: false,
      recoveryMetrics: true,
      waterRating: "5 ATM",
      batteryGps: null,
      batterySmartwatch: null,
    },
    strengths: ["Very light", "Excellent battery"],
    weaknesses: ["Smaller ecosystem than Garmin"],
    recommendationScore: 88,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: categoryFallbackImage("cat-gps-watches", "prod-coros-pace-3", "COROS Pace 3 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-pace3-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: ["prod-forerunner-255", "prod-forerunner-965"],
    alternativeProductIds: ["prod-forerunner-255"],
    ...pub,
  },
  {
    id: "prod-hrm-pro-plus",
    slug: "garmin-hrm-pro-plus",
    brandId: "brand-garmin",
    familyId: "fam-hrm-pro",
    generation: "Pro Plus",
    name: "HRM-Pro Plus",
    fullName: "Garmin HRM-Pro Plus",
    shortDescription:
      "Previous-generation Garmin dynamics chest strap — still strong value vs HRM 600.",
    lifecycleStatus: "previous-generation",
    sportIds: ["sport-running", "sport-cycling", "sport-training"],
    disciplineIds: ["disc-running-road", "disc-running-track"],
    categoryId: "cat-hrm",
    subcategoryIds: ["sub-hrm-chest", "sub-hrm-dynamics"],
    useCaseIds: ["uc-advanced", "uc-intervals", "uc-pb", "uc-marathon"],
    specifications: {
      type: "chest-strap",
      placement: "chest",
      sensingMethod: "ecg-electrical",
      connectivity: ["ant+", "bluetooth"],
      antPlus: true,
      bluetooth: true,
      simultaneousBluetooth: 3,
      battery: "Replaceable coin cell (approx. 1 year — manufacturer claim)",
      batteryType: "replaceable-coin-cell",
      runningDynamics: true,
      paceDistanceSupport: true,
      standaloneRecording: false,
      swimmingSupport: true,
      internalMemory: true,
      waterResistance: "5 ATM",
      replaceableStrap: true,
    },
    strengths: ["Accurate HR", "Running dynamics", "Often better value than HRM 600 on clearance"],
    weaknesses: ["Superseded by HRM 600 for standalone recording and rechargeable battery"],
    recommendationScore: 87,
    valueScore: 88,
    experienceLevels: ["intermediate", "advanced", "elite"],
    images: categoryFallbackImage("cat-hrm", "prod-hrm-pro-plus", "Garmin HRM-Pro Plus — catalog placeholder"),
    videos: [],
    offerIds: ["offer-hrm-nl", "offer-hrm-uk"],
    evidenceIds: ["ev-hrm-mfr"],
    relatedProductIds: ["prod-hrm-600", "prod-forerunner-970"],
    alternativeProductIds: ["prod-hrm-600", "prod-polar-h10", "prod-garmin-hrm-200"],
    ...pub,
  },
  {
    id: "prod-adv-skin-12",
    slug: "salomon-adv-skin-12",
    brandId: "brand-salomon",
    familyId: "fam-adv-skin",
    generation: "12",
    name: "ADV Skin 12",
    fullName: "Salomon ADV Skin 12",
    shortDescription: "12L race vest for trail and ultra hydration.",
    lifecycleStatus: "current",
    sportIds: ["sport-running"],
    disciplineIds: ["disc-running-trail", "disc-running-ultra"],
    categoryId: "cat-packs-vests",
    subcategoryIds: ["sub-pack-hydration-vests", "sub-pack-race-vests"],
    useCaseIds: ["uc-trail-training", "uc-ultra", "uc-long-runs"],
    specifications: {
      capacity: 12,
      weight: 270,
      includedFlasks: 2,
      includedFlaskVolume: 500,
      flaskCount: 2,
      reservoirCompatible: true,
      reservoirIncluded: false,
      totalHydrationCapacity: 2500,
      bladderCompatible: true,
      bottleCapacity: 1000,
      storage: "Multiple front and rear pockets for flasks, gels and mandatory kit",
      frontStorage: "Twin soft-flask pockets + stretch snack pockets",
      rearStorage: "Main zip + stretch rear stash",
      pockets: "Front flask/gel, rear main, side stash",
      phoneStorage: true,
      poleAttachment: true,
      quiverCompatible: true,
      raceKitCapacity: true,
      bounceControl: "high",
      breathability: "high",
      reflectivity: false,
      whistle: true,
      waterResistance: "none",
      fitSystem: "SensiFit + Quicklink",
      sizeRange: "XS–XL",
      sizing: "XS–XL (verify current chart)",
      genderFit: "unisex",
      raceSuitability: ["trail", "ultra"],
    },
    strengths: ["Stable race fit across long trail days", "Enough volume for mandatory ultra kit"],
    weaknesses: ["Overkill for road 10K", "Learning curve to pack pockets efficiently"],
    recommendationScore: 90,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: categoryFallbackImage("cat-packs-vests", "prod-adv-skin-12", "Salomon ADV Skin 12 — catalog placeholder"),
    videos: [],
    offerIds: ["offer-advskin-nl"],
    evidenceIds: ["ev-catalog-mfr", "ev-catalog-editorial"],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  // Draft fixture for publishing-resolver tests — never shown in catalog (noindex).
  // Not a real consumer SKU; keep draft + noindex so it stays BLOCKED for launch.
  {
    id: "prod-draft-example",
    slug: "example-unpublished-trainer",
    brandId: "brand-asics",
    name: "Example Unpublished Trainer",
    fullName: "ASICS Example Unpublished Trainer",
    shortDescription: "Draft product for publishing resolver tests.",
    lifecycleStatus: "upcoming",
    sportIds: ["sport-running"],
    disciplineIds: [],
    categoryId: "cat-running-shoes",
    subcategoryIds: ["sub-daily-trainers"],
    useCaseIds: [],
    specifications: {},
    strengths: [],
    weaknesses: [],
    experienceLevels: [],
    images: [],
    videos: [],
    offerIds: [],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    noindex: true,
    ...draftMeta(),
  },
  ...runningShoesWave2,
  ...runningShoesWave3,
  ...runningNnormalTrail,
  ...runningWatchesAndHrm,
  ...runningWatchesWave2,
  ...runningWatchesP75Gaps,
  ...runningHrmWave2,
  ...runningHydrationWave2,
  ...runningHydrationSocksBeltsWave3,
  ...runningPacksCarryWave2,
  ...runningHeadphonesWave2,
  ...runningSunglassesWave2,
  ...runningHeadlampsWave2,
  ...runningSafetyWave2,
  ...runningNutritionWave1,
  ...runningRecoveryWave2,
  ...runningClothingWave2,
  ...runningGearWave1,
  ...runningAccessoriesWave2,
  ...padelAllProducts,
  ...racketProducts,
  ...fitnessProducts,
];

export const products: Product[] = applyDecisionGraphP70Quality(
  applyAlternativesP65Graph(
    applyReviewProductLinkage(
      applyNmwCompletionEnrichment(
        applyWeakCatLaunchReadyEnrichment(
          applyGearCoreLaunchReadyEnrichment(
            applyRunningShoesLaunchReadyEnrichment(productsRaw),
          ),
        ),
      ),
    ),
  ),
);

/** Scheduled review will reference this published product */
export const scheduledReviewProductId = "prod-novablast-5";

export { scheduledMeta };
