import type { Retailer } from "@/domain/commerce/types";
import { SEED_DATES } from "@/content/config";

const verified = SEED_DATES.verified;

/**
 * Normalized retailers — regional Amazon storefronts are separate Retailers
 * because domains, currencies and affiliate programs differ.
 */
export const retailers: Retailer[] = [
  {
    id: "ret-amazon-nl",
    name: "Amazon.nl",
    slug: "amazon-nl",
    legalName: "Amazon EU S.à r.l.",
    regions: ["NL"],
    currencies: ["EUR"],
    retailerType: "marketplace",
    affiliateNetwork: "amazon",
    homepage: "https://www.amazon.nl",
    allowedHosts: ["www.amazon.nl", "amazon.nl", "amzn.to"],
    shippingRegions: ["NL"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-amazon-uk",
    name: "Amazon.co.uk",
    slug: "amazon-uk",
    regions: ["UK"],
    currencies: ["GBP"],
    retailerType: "marketplace",
    affiliateNetwork: "amazon",
    homepage: "https://www.amazon.co.uk",
    allowedHosts: ["www.amazon.co.uk", "amazon.co.uk", "amzn.to"],
    shippingRegions: ["UK"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-amazon-us",
    name: "Amazon.com",
    slug: "amazon-us",
    regions: ["US"],
    currencies: ["USD"],
    retailerType: "marketplace",
    affiliateNetwork: "amazon",
    homepage: "https://www.amazon.com",
    allowedHosts: ["www.amazon.com", "amazon.com", "amzn.to"],
    shippingRegions: ["US"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-amazon-de",
    name: "Amazon.de",
    slug: "amazon-de",
    regions: ["DE"],
    currencies: ["EUR"],
    retailerType: "marketplace",
    affiliateNetwork: "amazon",
    homepage: "https://www.amazon.de",
    allowedHosts: ["www.amazon.de", "amazon.de", "amzn.to"],
    shippingRegions: ["DE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-decathlon",
    name: "Decathlon",
    slug: "decathlon",
    regions: ["NL", "DE", "FR", "BE"],
    currencies: ["EUR"],
    retailerType: "general-sports-retailer",
    affiliateNetwork: "awin",
    homepage: "https://www.decathlon.nl",
    allowedHosts: [
      "www.decathlon.nl",
      "www.decathlon.de",
      "www.decathlon.fr",
      "www.decathlon.be",
    ],
    shippingRegions: ["NL", "DE", "FR", "BE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-asics-direct",
    name: "ASICS Official",
    slug: "asics-official",
    regions: ["NL", "DE", "UK", "US"],
    currencies: ["EUR", "GBP", "USD"],
    retailerType: "brand-direct",
    affiliateNetwork: "direct",
    homepage: "https://www.asics.com",
    allowedHosts: ["www.asics.com", "asics.com"],
    shippingRegions: ["NL", "DE", "UK", "US"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-nnormal-direct",
    name: "NNormal Official",
    slug: "nnormal-official",
    regions: ["NL", "DE", "UK"],
    currencies: ["EUR", "GBP"],
    retailerType: "brand-direct",
    affiliateNetwork: "direct",
    homepage: "https://www.nnormal.com",
    allowedHosts: ["www.nnormal.com", "nnormal.com"],
    shippingRegions: ["NL", "DE", "UK"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-garmin-direct",
    name: "Garmin Official",
    slug: "garmin-official",
    regions: ["NL", "UK", "US", "DE"],
    currencies: ["EUR", "GBP", "USD"],
    retailerType: "brand-direct",
    affiliateNetwork: "impact",
    homepage: "https://www.garmin.com",
    allowedHosts: ["www.garmin.com", "garmin.com"],
    shippingRegions: ["NL", "UK", "US", "DE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-all4running",
    name: "All4running",
    slug: "all4running",
    regions: ["NL", "BE", "DE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "awin",
    homepage: "https://www.all4running.nl",
    allowedHosts: ["www.all4running.nl", "all4running.nl"],
    shippingRegions: ["NL", "BE", "DE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-runnersworld-nl",
    name: "Runner's World Shop",
    slug: "runnersworld-shop",
    regions: ["NL", "BE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    homepage: "https://www.runnersworldshop.nl",
    allowedHosts: ["www.runnersworldshop.nl", "runnersworldshop.nl"],
    shippingRegions: ["NL", "BE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-hoka-direct",
    name: "HOKA Official",
    slug: "hoka-official",
    regions: ["NL", "DE", "UK", "US"],
    currencies: ["EUR", "GBP", "USD"],
    retailerType: "brand-direct",
    affiliateNetwork: "direct",
    homepage: "https://www.hoka.com",
    allowedHosts: ["www.hoka.com", "hoka.com"],
    shippingRegions: ["NL", "DE", "UK", "US"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-brooks-direct",
    name: "Brooks Official",
    slug: "brooks-official",
    regions: ["NL", "DE", "UK", "US"],
    currencies: ["EUR", "GBP", "USD"],
    retailerType: "brand-direct",
    affiliateNetwork: "direct",
    homepage: "https://www.brooksrunning.com",
    allowedHosts: ["www.brooksrunning.com", "brooksrunning.com"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-amazon-fr",
    name: "Amazon.fr",
    slug: "amazon-fr",
    regions: ["FR"],
    currencies: ["EUR"],
    retailerType: "marketplace",
    affiliateNetwork: "amazon",
    homepage: "https://www.amazon.fr",
    allowedHosts: ["www.amazon.fr", "amazon.fr", "amzn.to"],
    shippingRegions: ["FR"],
    status: "active",
    lastVerifiedAt: verified,
  },
  /**
   * NL/EU padel specialists — researched storefronts for listing Offers.
   * Affiliate programs stay pending until credentials exist; do not invent tags.
   */
  {
    id: "ret-padelmq",
    name: "PadeLMQ",
    slug: "padelmq",
    regions: ["NL", "BE", "DE", "FR"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "other",
    homepage: "https://www.padelmq.com",
    allowedHosts: ["www.padelmq.com", "padelmq.com"],
    shippingRegions: ["NL", "BE", "DE", "FR"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-justpadel",
    name: "Justpadel",
    slug: "justpadel",
    regions: ["NL", "BE", "DE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "awin",
    homepage: "https://www.justpadel.com",
    allowedHosts: ["www.justpadel.com", "justpadel.com"],
    shippingRegions: ["NL", "BE", "DE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-padel2gether",
    name: "Padel2Gether",
    slug: "padel2gether",
    regions: ["NL", "BE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "other",
    homepage: "https://www.padel2gether.nl",
    allowedHosts: ["www.padel2gether.nl", "padel2gether.nl"],
    shippingRegions: ["NL", "BE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-holland-padel",
    name: "Holland Padel",
    slug: "holland-padel",
    regions: ["NL", "BE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "other",
    homepage: "https://www.hollandpadel.com",
    allowedHosts: ["www.hollandpadel.com", "hollandpadel.com"],
    shippingRegions: ["NL", "BE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-padeldirect",
    name: "Padeldirect",
    slug: "padeldirect",
    regions: ["NL", "BE", "DE"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "other",
    homepage: "https://www.padeldirect.nl",
    allowedHosts: ["www.padeldirect.nl", "padeldirect.nl"],
    shippingRegions: ["NL", "BE", "DE"],
    status: "active",
    lastVerifiedAt: verified,
  },
  {
    id: "ret-padelnu",
    name: "PadelNU",
    slug: "padelnu",
    regions: ["NL"],
    currencies: ["EUR"],
    retailerType: "specialist-retailer",
    affiliateNetwork: "other",
    homepage: "https://www.padelnu.nl",
    allowedHosts: ["www.padelnu.nl", "padelnu.nl"],
    shippingRegions: ["NL"],
    status: "active",
    lastVerifiedAt: verified,
  },
  /**
   * ZA storefront researched for future listing Offers.
   * No affiliate program claimed — pending verification.
   */
  {
    id: "ret-takealot",
    name: "Takealot",
    slug: "takealot",
    regions: ["ZA"],
    currencies: ["ZAR"],
    retailerType: "marketplace",
    affiliateNetwork: "other",
    homepage: "https://www.takealot.com",
    allowedHosts: ["www.takealot.com", "takealot.com"],
    shippingRegions: ["ZA"],
    status: "pending",
    lastVerifiedAt: verified,
  },
];
