/**
 * AUTO-GENERATED by scripts/tmp/prelaunch-37-unique-rewrite.ts
 * Unique Expert Research rewrites for previously DUPLICATIVE / scaffold reviews.
 * Do not hand-edit — re-run the rewrite script.
 */
import type { Review } from "@/domain/editorial/types";
import data from "@/content/reviews-unique-rewrite.json";

export const reviewsUniqueRewrite: Review[] = data as Review[];
