/**
 * AUTO-GENERATED by scripts/tmp/prelaunch-54-held-estate.ts
 * Spec-driven unique Expert Research overlays for uniqueness-held reviews.
 */
import type { Review } from "@/domain/editorial/types";
import data from "@/content/reviews-p54-held-finalized.json";

export const reviewsP54HeldFinalized: Review[] = data as Review[];
