/**
 * AUTO-GENERATED by scripts/tmp/prelaunch-53-indexable-diff.ts
 * Spec-driven unique Expert Research overlays for INDEXABLE NEEDS_DIFF reviews.
 */
import type { Review } from "@/domain/editorial/types";
import data from "@/content/reviews-p53-differentiation.json";

export const reviewsP53Differentiation: Review[] = data as Review[];
