import type { ReviewCriteriaDefinition } from "@/domain/editorial/types";

/** Category-specific review score criteria — templates do not hardcode shoe fields. */
export const reviewCriteriaDefinitions: ReviewCriteriaDefinition[] = [
  // Running shoes
  {
    id: "rc-shoe-fit",
    categoryId: "cat-running-shoes",
    key: "fit",
    label: "Fit",
    description: "Length, width, lock-down and sizing consistency.",
    weight: 0.1,
  },
  {
    id: "rc-shoe-comfort",
    categoryId: "cat-running-shoes",
    key: "comfort",
    label: "Comfort",
    description: "All-day and long-run comfort for intended use.",
    weight: 0.12,
  },
  {
    id: "rc-shoe-ride",
    categoryId: "cat-running-shoes",
    key: "ride",
    label: "Ride",
    description: "Overall ride character including transition and rocker.",
    weight: 0.12,
  },
  {
    id: "rc-shoe-cushioning",
    categoryId: "cat-running-shoes",
    key: "cushioning",
    label: "Cushioning",
    description: "Stack feel, softness and protection.",
    weight: 0.12,
  },
  {
    id: "rc-shoe-stability",
    categoryId: "cat-running-shoes",
    key: "stability",
    label: "Stability",
    description: "Platform security for neutral vs stability needs.",
    weight: 0.08,
  },
  {
    id: "rc-shoe-responsiveness",
    categoryId: "cat-running-shoes",
    key: "responsiveness",
    label: "Responsiveness",
    description: "Energy return and snap for faster paces.",
    weight: 0.1,
  },
  {
    id: "rc-shoe-grip",
    categoryId: "cat-running-shoes",
    key: "grip",
    label: "Grip",
    description: "Outsole traction for intended surfaces.",
    weight: 0.06,
  },
  {
    id: "rc-shoe-durability",
    categoryId: "cat-running-shoes",
    key: "durability",
    label: "Durability",
    description: "Expected longevity of foam, upper and outsole.",
    weight: 0.08,
  },
  {
    id: "rc-shoe-versatility",
    categoryId: "cat-running-shoes",
    key: "versatility",
    label: "Versatility",
    description: "Range of run types the shoe handles well.",
    weight: 0.1,
  },
  {
    id: "rc-shoe-value",
    categoryId: "cat-running-shoes",
    key: "value",
    label: "Value",
    description: "Performance relative to typical street price.",
    weight: 0.12,
  },
  // GPS watches
  {
    id: "rc-watch-gps",
    categoryId: "cat-gps-watches",
    key: "gps-accuracy",
    label: "GPS Accuracy",
    description: "Tracking consistency across activities.",
    weight: 0.15,
  },
  {
    id: "rc-watch-battery",
    categoryId: "cat-gps-watches",
    key: "battery",
    label: "Battery",
    description: "Smartwatch and GPS endurance.",
    weight: 0.15,
  },
  {
    id: "rc-watch-maps",
    categoryId: "cat-gps-watches",
    key: "maps",
    label: "Maps",
    description: "On-device mapping and navigation usefulness.",
    weight: 0.1,
  },
  {
    id: "rc-watch-training",
    categoryId: "cat-gps-watches",
    key: "training-features",
    label: "Training Features",
    description: "Workouts, dynamics and coaching tools.",
    weight: 0.15,
  },
  {
    id: "rc-watch-recovery",
    categoryId: "cat-gps-watches",
    key: "recovery-features",
    label: "Recovery Features",
    description: "Readiness, sleep and recovery metrics.",
    weight: 0.1,
  },
  {
    id: "rc-watch-interface",
    categoryId: "cat-gps-watches",
    key: "interface",
    label: "Interface",
    description: "Buttons, touchscreen and daily usability.",
    weight: 0.1,
  },
  {
    id: "rc-watch-smart",
    categoryId: "cat-gps-watches",
    key: "smartwatch-features",
    label: "Smartwatch Features",
    description: "Notifications, music, payments and apps.",
    weight: 0.1,
  },
  {
    id: "rc-watch-value",
    categoryId: "cat-gps-watches",
    key: "value",
    label: "Value",
    description: "Feature set relative to price.",
    weight: 0.15,
  },
];
