/**
 * AUTO-GENERATED by scripts/review-editorial-rebuild.ts
 * Consumer-editorial replacements for reviews with no acceptable clean source.
 */
import type { Review } from "@/domain/editorial/types";
import data from "@/content/reviews-editorial-rebuild.json";

export const reviewsEditorialRebuild: Review[] = data as Review[];
