import type { Tool } from "@/domain/tools/types";
import { publishedMeta } from "@/content/config";
import { padelToolsLive } from "@/content/padel";
import { fitnessTools } from "@/content/fitness";
import { hyroxTools } from "@/content/hyrox/editorial";
import { racketTools } from "@/content/racket";

const pub = publishedMeta();

export const tools: Tool[] = [
  {
    id: "tool-shoe-finder",
    name: "Running Shoe Finder",
    slug: "running-shoe-finder",
    description:
      "Answer questions about terrain, training and goals to get explainable shoe matches.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-running-shoes"],
    useCaseIds: ["uc-daily-training", "uc-beginners", "uc-marathon"],
    goalTags: ["fit", "shoes", "recommendation", "finder", "shoe finder"],
    featured: true,
    priority: 100,
    estimatedTimeMinutes: 2,
    hubImageSrc: "/images/running/products/novablast-6-hero.jpg",
    shortDescription:
      "Find shoes that match your running, goals, fit preferences and budget.",
    icon: "Footprints",
    available: true,
    seoTitle: "Running Shoe Finder: Find the Right Shoes for You | Kitletics",
    seoDescription:
      "Answer a few questions about your running, terrain and preferences to get explainable running shoe recommendations.",
    ...pub,
  },
  {
    id: "tool-watch-finder",
    name: "Fitness Watch Finder",
    slug: "fitness-watch-finder",
    description:
      "Answer questions about training goals, maps, battery and budget to get explainable GPS watch matches.",
    type: "finder",
    sportIds: ["sport-running", "sport-training"],
    categoryIds: ["cat-gps-watches"],
    useCaseIds: ["uc-beginners", "uc-advanced", "uc-marathon", "uc-ultra"],
    goalTags: ["watch", "gps", "fitness watch", "garmin", "coros"],
    icon: "Watch",
    available: true,
    featured: true,
    priority: 78,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match GPS watches to training goals, maps, battery life and budget.",
    seoTitle: "Fitness Watch Finder: Find the Right GPS Watch | Kitletics",
    seoDescription:
      "Answer a few questions about training, maps and budget to get explainable GPS watch recommendations.",
    ...pub,
  },
  {
    id: "tool-pace-calc",
    name: "Running Pace Calculator",
    slug: "running-pace-calculator",
    description:
      "Calculate pace, finish time and distance — with race splits and unit conversion.",
    type: "calculator",
    sportIds: ["sport-running"],
    categoryIds: [],
    useCaseIds: ["uc-5k", "uc-10k", "uc-half", "uc-marathon"],
    goalTags: [
      "pace",
      "training",
      "pace calculator",
      "running pace",
      "marathon pace",
      "min/km",
      "min/mile",
    ],
    icon: "Timer",
    available: true,
    featured: true,
    priority: 90,
    shortDescription:
      "Calculate pace, finish time and distance with race splits.",
    seoTitle: "Running Pace Calculator: Pace, Time & Distance | Kitletics",
    seoDescription:
      "Calculate running pace in min/km or min/mile, finish times, race splits and speed — free and shareable.",
    ...pub,
  },
  {
    id: "tool-race-predictor",
    name: "Race Time Predictor",
    slug: "race-time-predictor",
    description:
      "Estimate equivalent race times across distances from a recent result.",
    type: "calculator",
    sportIds: ["sport-running"],
    categoryIds: [],
    useCaseIds: ["uc-pb", "uc-marathon"],
    goalTags: [
      "race",
      "prediction",
      "race predictor",
      "race time calculator",
      "5k predictor",
      "marathon predictor",
    ],
    icon: "Trophy",
    available: true,
    featured: true,
    priority: 85,
    shortDescription:
      "Estimate equivalent race times across distances from a recent result.",
    seoTitle: "Race Time Predictor: 5K, 10K, Half & Marathon | Kitletics",
    seoDescription:
      "Estimate equivalent race times across 5K, 10K, half marathon and marathon from a recent result using the Riegel model.",
    ...pub,
  },
  {
    id: "tool-rotation",
    name: "Shoe Rotation Planner",
    slug: "shoe-rotation-planner",
    description:
      "Build a running shoe rotation around your training — see coverage, gaps and the best shoe to add next.",
    type: "planner",
    sportIds: ["sport-running"],
    categoryIds: ["cat-running-shoes"],
    useCaseIds: ["uc-high-mileage", "uc-daily-training", "uc-marathon"],
    goalTags: [
      "rotation",
      "shoes",
      "shoe rotation planner",
      "running shoe rotation",
      "how many running shoes",
      "build running shoe rotation",
    ],
    icon: "RefreshCw",
    available: true,
    featured: true,
    priority: 95,
    shortDescription:
      "Plan a shoe rotation around your training — coverage, gaps and what to add next.",
    seoTitle: "Running Shoe Rotation Planner | Kitletics",
    seoDescription:
      "Build a running shoe rotation around your training. See which roles your shoes cover, identify gaps and find the best shoes to add next.",
    ...pub,
  },
  {
    id: "tool-running-hydration-finder",
    name: "Running Hydration Finder",
    slug: "running-hydration-finder",
    description:
      "Answer questions about distance, terrain, water needs and carry style to match vests, belts and flasks.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-packs-vests", "cat-running-belts", "cat-hydration"],
    useCaseIds: [
      "uc-long-runs",
      "uc-trail-training",
      "uc-ultra",
      "uc-marathon",
      "uc-half",
    ],
    goalTags: [
      "hydration",
      "vest",
      "running belt",
      "soft flask",
      "hydration finder",
    ],
    icon: "Droplets",
    available: true,
    featured: true,
    priority: 72,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match hydration vests, belts and flasks to distance, terrain and carry style.",
    seoTitle: "Running Hydration Finder | Kitletics",
    seoDescription:
      "Answer a few questions about distance, water needs and carry style to get explainable hydration gear matches.",
    ...pub,
  },
  {
    id: "tool-running-hrm-finder",
    name: "Running Heart Rate Monitor Finder",
    slug: "running-hrm-finder",
    description:
      "Answer questions about training style, form factor and budget to match chest straps and armband HRMs.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-hrm"],
    useCaseIds: [
      "uc-daily-training",
      "uc-intervals",
      "uc-advanced",
      "uc-hyrox-training",
    ],
    goalTags: [
      "heart rate",
      "hrm",
      "chest strap",
      "armband",
      "polar h10",
      "heart rate monitor finder",
    ],
    icon: "HeartPulse",
    available: true,
    featured: true,
    priority: 74,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match chest straps and optical armbands to training, comfort and budget.",
    seoTitle: "Running Heart Rate Monitor Finder | Kitletics",
    seoDescription:
      "Answer a few questions about form factor, dynamics and budget to get explainable HRM matches.",
    ...pub,
  },
  {
    id: "tool-running-clothing-finder",
    name: "Running Apparel Finder",
    slug: "running-clothing-finder",
    description:
      "Answer questions about training context, fit and priorities to match running clothing and socks.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-running-clothing", "cat-running-socks"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-racing", "uc-beginners"],
    goalTags: ["running apparel", "clothing", "socks", "apparel finder"],
    icon: "Shirt",
    available: true,
    featured: true,
    priority: 68,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match tops, shorts and socks to weather, distance and comfort.",
    seoTitle: "Running Apparel Finder | Kitletics",
    seoDescription:
      "Answer a few questions to get explainable running clothing and sock matches.",
    ...pub,
  },
  {
    id: "tool-running-fuel-finder",
    name: "Running Fuel Finder",
    slug: "running-fuel-finder",
    description:
      "Answer questions about distance, format and stomach tolerance to match gels, chews and drink mixes.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-nutrition"],
    useCaseIds: ["uc-daily-training", "uc-half", "uc-marathon", "uc-ultra"],
    goalTags: ["gels", "fuel", "nutrition", "energy gels", "fuel finder"],
    icon: "Droplets",
    available: true,
    featured: true,
    priority: 66,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match gels, chews and drink mixes to distance and race goals.",
    seoTitle: "Running Fuel Finder | Kitletics",
    seoDescription:
      "Answer a few questions about distance and format to get explainable running fuel matches.",
    ...pub,
  },
  {
    id: "tool-running-recovery-finder",
    name: "Running Recovery Finder",
    slug: "running-recovery-finder",
    description:
      "Answer questions about recovery needs and budget to match massage, compression and mobility tools.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: ["cat-recovery-gear"],
    useCaseIds: ["uc-daily-training", "uc-long-runs", "uc-racing", "uc-beginners"],
    goalTags: ["recovery", "massage gun", "compression", "recovery finder"],
    icon: "HeartPulse",
    available: true,
    featured: true,
    priority: 64,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match recovery tools to how hard you train and what you need after runs.",
    seoTitle: "Running Recovery Finder | Kitletics",
    seoDescription:
      "Answer a few questions to get explainable running recovery gear matches.",
    ...pub,
  },
  {
    id: "tool-running-accessories-finder",
    name: "Running Accessories Finder",
    slug: "running-accessories-finder",
    description:
      "Answer questions about anti-chafe, audio, sunglasses, lights and safety needs to match the right shelf.",
    type: "finder",
    sportIds: ["sport-running"],
    categoryIds: [
      "cat-headphones",
      "cat-sunglasses",
      "cat-running-lights",
      "cat-safety",
      "cat-accessories",
    ],
    useCaseIds: [
      "uc-daily-training",
      "uc-racing",
      "uc-trail-training",
      "uc-beginners",
      "uc-long-runs",
    ],
    goalTags: [
      "anti-chafe",
      "headphones",
      "sunglasses",
      "headlamp",
      "safety",
      "accessories finder",
    ],
    icon: "Sparkles",
    available: true,
    featured: true,
    priority: 62,
    estimatedTimeMinutes: 2,
    shortDescription:
      "Match anti-chafe, headphones, sunglasses, lights and safety gear to the job.",
    seoTitle: "Running Accessories Finder | Kitletics",
    seoDescription:
      "Answer a few questions to get explainable running accessory matches.",
    ...pub,
  },
  {
    id: "tool-compare-products",
    name: "Compare Products",
    slug: "compare-products",
    description:
      "Build a side-by-side comparison of products in the same category — specs, scores and trade-offs.",
    shortDescription:
      "Side-by-side product comparison with structured specs and prices.",
    type: "comparison",
    sportIds: [],
    categoryIds: [],
    useCaseIds: [],
    goalTags: ["compare", "comparison", "side by side"],
    icon: "ArrowLeftRight",
    available: true,
    featured: true,
    priority: 100,
    href: "/compare",
    ...pub,
  },
  ...fitnessTools,
  ...hyroxTools,
  ...padelToolsLive,
  ...racketTools,
];
