import type { SoftDraft } from "@/content/padel/soft-goods/build";

export function bagDrafts(): SoftDraft[] {
  return [
    {
      id: "prod-nox-bag-10",
      existing: true,
      slug: "nox-thermo-bag-10",
      brandId: "brand-nox",
      name: "Thermo Bag 10",
      fullName: "Nox Thermo Bag 10",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://noxsport.com/en/collections/bags",
      sourceName: "NOX bags collection",
      shortDescription:
        "Nox thermo paletero seeded as Thermo Bag 10. The collection URL is not a model-specific product page, so dimensions stay unknown until the exact 10-racket thermo listing is captured.",
      specifications: {
        form: "racket-bag",
        capacity: "unknown",
        racketCompartments: "unknown",
        shoeCompartment: false,
        thermalProtection: true,
        carryStyle: "handles / backpack straps (unverified)",
      },
      strengths: ["Thermo compartment (name)"],
      weaknesses: ["No unique packshot; collection URL only"],
    },
    {
      id: "prod-nox-at10-team-bag",
      slug: "nox-at10-team-paletero",
      brandId: "brand-nox",
      name: "AT10 Team Paletero",
      fullName: "Nox AT10 Team Paletero",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://noxsport.com/en/products/paletero-at10-team-grey-black",
      sourceName: "NOX AT10 TEAM GREY/BLACK",
      shortDescription:
        "42 L Tapia Team paletero: main compartment for three rackets, ThermoTech pocket for two, ventilated shoe slot, removable backpack straps.",
      verdict:
        "I’d take this as the default Nox match bag — thermo for the two frames I actually play, shoes isolated, 42 L without going RH-Pro huge.",
      specifications: {
        form: "racket-bag",
        capacity: "42 L",
        racketCompartments: "3 main + 2 thermo",
        shoeCompartment: true,
        thermalProtection: true,
        dimensions: "600 × 300 × 270 mm",
        carryStyle: "hand + removable backpack straps",
      },
      strengths: ["Manufacturer dimensions", "ThermoTech + shoe vent", "Backpack mode"],
      weaknesses: ["Not a 4+ racket travel duffel"],
      relatedProductIds: ["prod-nox-bag-10", "prod-babolat-rh-pro-padel"],
      alternativeProductIds: ["prod-bullpadel-vertex-backpack", "prod-tecnifibre-tour-endurance-backpack"],
    },
    {
      id: "prod-babolat-rh-pro-padel",
      slug: "babolat-rh-pro-padel",
      brandId: "brand-babolat-padel",
      name: "RH Pro Padel",
      fullName: "Babolat RH Pro Padel",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://www.babolat.com/us/rh-pro/759020.html",
      sourceName: "Babolat RH Pro",
      shortDescription:
        "Large 62 L padel bag: four-racket capacity, one insulated compartment, breathable shoe pocket, three main compartments.",
      verdict:
        "I’d pack RH Pro for a tournament weekend. It’s overkill for a two-racket club night — that’s a backpack job.",
      specifications: {
        form: "racket-bag",
        capacity: "62 L",
        racketCompartments: "4",
        shoeCompartment: true,
        thermalProtection: true,
        dimensions: "63 × 37 × 30 cm",
        carryStyle: "dual straps + two handles",
      },
      strengths: ["Verified 62 L / 4-racket", "Insulated pocket", "Shoe pocket"],
      weaknesses: ["Large for bike/commute"],
      relatedProductIds: ["prod-babolat-court-backpack", "prod-nox-at10-team-bag"],
      alternativeProductIds: ["prod-adidas-protour-padel", "prod-head-tour-team-padel"],
    },
    {
      id: "prod-bullpadel-vertex-backpack",
      slug: "bullpadel-vertex-geo-backpack",
      brandId: "brand-bullpadel",
      name: "Vertex Geo Backpack",
      fullName: "Bullpadel Vertex Geo Backpack",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/bullpadel-vertex-geo-rugzak-intense-blue-2026",
      sourceName: "PadeLMQ Bullpadel Vertex Geo backpack 2026",
      shortDescription:
        "2026 Vertex backpack: thermo compartment for two rackets, ventilated shoe pocket, laptop sleeve, 50 × 35 × 22 cm.",
      verdict:
        "I’d use this as a commute backpack that still keeps two frames out of the sun. Not a 10-racket thermo.",
      specifications: {
        form: "backpack",
        capacity: "2 rackets",
        racketCompartments: "2 thermo",
        shoeCompartment: true,
        thermalProtection: true,
        dimensions: "50 × 35 × 22 cm",
        carryStyle: "backpack + chest strap",
      },
      strengths: ["Thermo + shoes in a backpack", "Vertex 2026 line"],
      weaknesses: ["Retailer PDP, not bullpadel.com"],
      relatedProductIds: ["prod-tecnifibre-tour-endurance-backpack", "prod-nox-at10-team-bag"],
      alternativeProductIds: ["prod-kuikma-paletero", "prod-head-elite-backpack"],
    },
    {
      id: "prod-tecnifibre-tour-endurance-backpack",
      slug: "tecnifibre-tour-endurance-padel-backpack",
      brandId: "brand-tecnifibre-padel",
      name: "Tour Endurance Backpack",
      fullName: "Tecnifibre Tour Endurance Padel Backpack",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/tecnifibre-tour-endurance-rugzak-caqui",
      sourceName: "PadeLMQ Tecnifibre Tour Endurance backpack khaki",
      shortDescription:
        "Tecnifibre Tour Endurance padel backpack with lower shoe well — commute-first day bag, not a thermo paletero.",
      verdict:
        "I’d use this as a two-racket day bag. Don’t confuse it with a Tecnifibre court shoe — that product was a catalog mix-up.",
      specifications: {
        form: "backpack",
        capacity: "day pack",
        racketCompartments: "main + side",
        shoeCompartment: true,
        thermalProtection: false,
        carryStyle: "backpack",
      },
      strengths: ["Authentic packshot", "Shoe well", "Commute form"],
      weaknesses: ["No listed thermo / exact racket count"],
      relatedProductIds: ["prod-bullpadel-vertex-backpack", "prod-babolat-court-backpack"],
      alternativeProductIds: ["prod-head-elite-backpack"],
    },
    {
      id: "prod-babolat-court-backpack",
      slug: "babolat-court-backpack",
      brandId: "brand-babolat-padel",
      name: "Court S",
      fullName: "Babolat Court S Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://www.babolat.com/us/court-s/102-759022.html",
      sourceName: "Babolat Court S",
      shortDescription:
        "Babolat Court S 35 L padel bag: up to two rackets, divided main compartment, outer zip pocket. Manufacturer Court line day bag (not RH Pro).",
      verdict:
        "I’d take Court S for a two-racket club commute. Tournament weekends still get RH Pro.",
      specifications: {
        form: "racket-bag",
        capacity: "35 L",
        racketCompartments: "2",
        shoeCompartment: false,
        thermalProtection: false,
        dimensions: "49 × 26 × 30 cm",
        carryStyle: "straps + handles",
      },
      strengths: ["Verified 35 L / 2-racket", "Manufacturer PDP"],
      weaknesses: ["No insulated compartment"],
      relatedProductIds: ["prod-babolat-rh-pro-padel"],
      alternativeProductIds: ["prod-tecnifibre-tour-endurance-backpack"],
    },
    {
      id: "prod-adidas-protour-padel",
      slug: "adidas-protour-padel-bag",
      brandId: "brand-adidas-padel",
      name: "ProTour 3.5",
      fullName: "Adidas ProTour 3.5 Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/adidas-padeltas-protour-3-5-blauw-brons-2026",
      sourceName: "PadeLMQ Adidas ProTour 3.5 2026",
      shortDescription:
        "Adidas ProTour 3.5 padel racket bag (2026 blue/bronze). Club-to-tournament paletero format with Adidas padel line styling.",
      verdict:
        "I’d take ProTour when I want Adidas kit cohesion and a full paletero. For a published 42 L thermo reference, AT10 Team is clearer.",
      specifications: {
        form: "racket-bag",
        capacity: "paletero",
        racketCompartments: "multi",
        shoeCompartment: true,
        thermalProtection: true,
        carryStyle: "straps + handles",
      },
      strengths: ["Current Adidas ProTour generation", "Paletero format"],
      weaknesses: ["Exact litre count not on this listing"],
      relatedProductIds: ["prod-nox-at10-team-bag", "prod-wilson-super-tour-padel"],
      alternativeProductIds: ["prod-babolat-rh-pro-padel", "prod-bullpadel-vertex-backpack"],
    },
    {
      id: "prod-head-tour-team-padel",
      slug: "head-tour-team-padel-bag",
      brandId: "brand-head-padel",
      name: "Tour Team Padel",
      fullName: "HEAD Tour Team Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://www.head.com",
      sourceName: "HEAD (brand)",
      shortDescription:
        "HEAD Tour Team paletero / racket bag for padel. The brand homepage is not a model-specific product page.",
      specifications: {
        form: "racket-bag",
        capacity: "unknown",
        racketCompartments: "unknown",
        shoeCompartment: false,
        thermalProtection: false,
        carryStyle: "straps + handles",
      },
      strengths: ["HEAD bag family"],
      weaknesses: ["No verified PDP"],
      relatedProductIds: ["prod-head-elite-backpack"],
      alternativeProductIds: ["prod-nox-at10-team-bag"],
    },
    {
      id: "prod-head-elite-backpack",
      slug: "head-elite-padel-backpack",
      brandId: "brand-head-padel",
      name: "Elite Backpack",
      fullName: "HEAD Elite Padel Backpack",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.tennis-point.co.uk/products/head-tour-team-elite-backpack-limeblue-00637502591000",
      sourceName: "Tennis-Point HEAD Tour Team Elite Backpack",
      shortDescription:
        "HEAD Tour Team Elite backpack: padded compartment for up to two rackets, main storage, integrated shoe compartment, ~52 × 35 × 19 cm.",
      verdict:
        "I’d use Elite as a two-racket day pack. Not a thermo tournament paletero.",
      specifications: {
        form: "backpack",
        capacity: "2 rackets",
        racketCompartments: "2 padded",
        shoeCompartment: true,
        thermalProtection: false,
        dimensions: "52 × 35 × 19 cm",
        carryStyle: "backpack",
      },
      strengths: ["Shoe compartment", "Two-racket padded slot"],
      weaknesses: ["Retailer PDP; not a dedicated padel thermo bag"],
      relatedProductIds: ["prod-head-tour-team-padel"],
      alternativeProductIds: ["prod-tecnifibre-tour-endurance-backpack"],
    },
    {
      id: "prod-wilson-super-tour-padel",
      slug: "wilson-super-tour-padel-bag",
      brandId: "brand-wilson-padel",
      name: "Bela Super Tour",
      fullName: "Wilson Bela Super Tour Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/wilson-bela-super-tour-padel-tas-rood",
      sourceName: "PadeLMQ Wilson Bela Super Tour bag",
      shortDescription:
        "Wilson Bela Super Tour padel bag — high-capacity tournament paletero for players carrying multiple frames and weekend kit.",
      verdict:
        "I’d pack Super Tour for tournament weekends. For a bike commute with two frames, Vertex Geo or Tour Endurance is the lighter job.",
      specifications: {
        form: "tournament-bag",
        capacity: "high",
        racketCompartments: "multi",
        shoeCompartment: true,
        thermalProtection: true,
        carryStyle: "straps + handles",
      },
      strengths: ["Tournament volume", "Bela line"],
      weaknesses: ["Bulky for minimalist club nights"],
      relatedProductIds: ["prod-babolat-rh-pro-padel", "prod-nox-at10-xxl-bag"],
      alternativeProductIds: ["prod-nox-at10-team-bag", "prod-bullpadel-vertex-backpack"],
    },
    {
      id: "prod-kuikma-paletero",
      slug: "kuikma-padel-paletero",
      brandId: "brand-kuikma",
      name: "Kuikma Paletero",
      fullName: "Kuikma Padel Paletero",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://www.decathlon.nl/search?Ntt=kuikma%20paletero",
      sourceName: "Decathlon Kuikma paletero (range search)",
      shortDescription:
        "Decathlon Kuikma paletero for club commute. The search URL is not a model-specific product page, so capacity is unknown.",
      specifications: {
        form: "racket-bag",
        capacity: "unknown",
        racketCompartments: "unknown",
        shoeCompartment: false,
        thermalProtection: false,
        carryStyle: "handles",
      },
      strengths: ["Value / EU availability"],
      weaknesses: ["Search URL only"],
      relatedProductIds: ["prod-nox-at10-team-bag"],
      alternativeProductIds: ["prod-bullpadel-vertex-backpack"],
    },
    {
      id: "prod-nox-pro-series-bag",
      slug: "nox-pro-series-padel-bag",
      brandId: "brand-nox",
      name: "Pro Series Bag",
      fullName: "Nox Pro Series Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://noxsport.com/en/collections/bags",
      sourceName: "NOX bags collection",
      shortDescription:
        "Nox Pro Series paletero. The collection page does not identify a specific model, so thermo features and racket count are unknown.",
      specifications: {
        form: "racket-bag",
        capacity: "unknown",
        racketCompartments: "unknown",
        shoeCompartment: false,
        thermalProtection: false,
        carryStyle: "straps + handles",
      },
      strengths: ["Nox Pro Series line"],
      weaknesses: ["Collection URL only"],
      relatedProductIds: ["prod-nox-at10-team-bag", "prod-nox-at10-xxl-bag"],
      alternativeProductIds: ["prod-adidas-protour-padel"],
    },
    {
      id: "prod-nox-at10-xxl-bag",
      slug: "nox-at10-xxl-padel-bag",
      brandId: "brand-nox",
      name: "AT10 XXL",
      fullName: "Nox AT10 XXL Padel Bag",
      categoryId: "cat-padel-bags",
      sourceUrl:
        "https://www.padelmq.com/en-eu/products/nox-at10-xxl-padel-bag-black-red-agustin-tapia",
      sourceName: "PadeLMQ Nox AT10 XXL",
      shortDescription:
        "90 L Agustín Tapia AT10 XXL padel bag: up to five rackets, ThermoTech racket compartment, ventilated shoe compartment, backpack straps. Dimensions 700 × 300 × 450 mm.",
      verdict:
        "I’d pack XXL for tournament travel when RH Pro still feels tight. It is the wrong bag for a one-racket bike commute.",
      specifications: {
        form: "tournament-bag",
        capacity: "90 L",
        racketCompartments: "up to 5",
        shoeCompartment: true,
        thermalProtection: true,
        dimensions: "700 × 300 × 450 mm",
        carryStyle: "backpack straps + handles",
      },
      strengths: ["Published 90 L", "Thermo + shoes", "5-racket capacity"],
      weaknesses: ["Bulky for daily club nights"],
      relatedProductIds: ["prod-nox-at10-team-bag", "prod-babolat-rh-pro-padel"],
      alternativeProductIds: ["prod-wilson-super-tour-padel", "prod-babolat-rh-pro-padel"],
    },
    {
      id: "prod-siux-paletero",
      slug: "siux-padel-paletero",
      brandId: "brand-siux",
      name: "Siux Paletero",
      fullName: "Siux Padel Paletero",
      categoryId: "cat-padel-bags",
      sourceUrl: "https://www.siuxpadel.com",
      sourceName: "Siux (brand)",
      shortDescription:
        "Siux paletero from the racket brand’s bag line. The homepage is not a model-specific product page.",
      specifications: {
        form: "racket-bag",
        capacity: "unknown",
        racketCompartments: "unknown",
        shoeCompartment: false,
        thermalProtection: false,
        carryStyle: "straps + handles",
      },
      strengths: ["Siux ecosystem"],
      weaknesses: ["No verified PDP"],
      relatedProductIds: ["prod-nox-at10-team-bag"],
      alternativeProductIds: ["prod-bullpadel-vertex-backpack"],
    },
  ];
}
