import type { SoftDraft } from "@/content/padel/soft-goods/build";

export function ballDrafts(): SoftDraft[] {
  return [
    {
      id: "prod-head-padel-pro-s",
      existing: true,
      slug: "head-padel-pro-s-balls",
      brandId: "brand-head-padel",
      name: "Padel Pro S+",
      fullName: "HEAD Padel Pro S+",
      categoryId: "cat-padel-balls",
      lifecycle: "current",
      sourceUrl: "https://www.padelmq.com/en-nl/products/head-pro-s",
      sourceName: "PadeLMQ / HEAD Pro S+",
      shortDescription:
        "HEAD’s faster competition can — thicker natural-rubber core and compact felt. Official women’s ball at the 2026 Valencia Premier Padel P1.",
      verdict:
        "I’d open this when the court is slow and I want the ball to stay through the glass. Control players who already find Pro+ plenty fast should skip it.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "fast",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        officialApproval: "Premier Padel Valencia P1 2026 (women’s draw)",
        coreMaterial: "thicker natural rubber",
        feltMaterial: "compact felt",
        intendedConditions: "slow courts, cool/humid, sea-level club play",
        freshnessStatus: "current",
      },
      strengths: [
        "Faster bounce than Pro+",
        "Durability claim vs previous Pro S",
        "Tournament positioning",
      ],
      weaknesses: ["Too lively for some beginner sessions"],
      relatedProductIds: ["prod-head-padel-pro-plus", "prod-wilson-padel-premier-speed"],
      alternativeProductIds: ["prod-kuikma-pb-speed", "prod-dunlop-pro-padel"],
    },
    {
      id: "prod-head-padel-pro-plus",
      slug: "head-padel-pro-plus",
      brandId: "brand-head-padel",
      name: "Padel Pro+",
      fullName: "HEAD Padel Pro+",
      categoryId: "cat-padel-balls",
      sourceUrl: "https://www.padelmq.com/en-nl/products/head-pro-tube",
      sourceName: "PadeLMQ / HEAD Pro+",
      shortDescription:
        "HEAD’s control-oriented competition can — thinner synthetic-rubber core that retains pressure. FEP-official; men’s ball at Valencia Premier Padel P1 2026.",
      verdict:
        "I’d pick Pro+ for match play when I want the ball to sit a fraction longer than Pro S+. Same HEAD family, slower personality.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        officialApproval: "FEP; Premier Padel Valencia P1 2026 (men’s draw)",
        coreMaterial: "thinner synthetic rubber",
        feltMaterial: "exclusive durability felt (manufacturer claim)",
        intendedConditions: "standard club/competition pace",
        freshnessStatus: "current",
      },
      strengths: ["Control-first competition can", "Pressure retention claim", "Current HEAD flagship"],
      weaknesses: ["Not the fastest HEAD can"],
      relatedProductIds: ["prod-head-padel-pro-s", "prod-wilson-padel-premier"],
      alternativeProductIds: ["prod-kuikma-pb-control", "prod-bullpadel-premium-pro"],
    },
    {
      id: "prod-head-padel-team",
      slug: "head-padel-team",
      brandId: "brand-head-padel",
      name: "Padel Team",
      fullName: "HEAD Padel Team",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://padelmarket.com/en-eu/products/head-padel-team-3-tubes-of-3-balls",
      sourceName: "Padel Market HEAD Team",
      shortDescription:
        "Slower HEAD training/beginner can. Manufacturer positions it as long-lasting and easy to control while skills build.",
      verdict:
        "I’d use Team for first-hour coaching and mixed socials. It is not a substitute for Pro+/Pro S+ on a fast outdoor court.",
      specifications: {
        ballType: "training",
        use: "training",
        speed: "slow",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        intendedConditions: "beginner sessions, slow social play",
        freshnessStatus: "current",
      },
      strengths: ["Beginner-friendly speed", "HEAD availability", "Training positioning"],
      weaknesses: ["Too slow for match-pace play"],
      relatedProductIds: ["prod-tecnifibre-padel-team", "prod-head-padel-one"],
      alternativeProductIds: ["prod-kuikma-pb-club"],
      experienceLevels: ["beginner"],
    },
    {
      id: "prod-head-padel-one",
      slug: "head-padel-one",
      brandId: "brand-head-padel",
      name: "Padel One",
      fullName: "HEAD Padel One",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://padelmarket.com/en-gb/products/head-padel-one-tube-of-3-balls",
      sourceName: "Padel Market HEAD Padel One",
      shortDescription:
        "HEAD’s intermediate can — faster than Team, not as hot as Pro S+. Positioned for players stepping up from recreational pace.",
      verdict:
        "I’d shortlist One for club nights when Pro+ feels like overkill and Team feels dead.",
      specifications: {
        ballType: "training",
        use: "training",
        speed: "medium",
        pressurization: "pressurized",
        durability: "moderate",
        packSize: "3-ball can",
        ballsPerCan: 3,
        freshnessStatus: "current",
      },
      strengths: ["Mid-pace step-up", "HEAD range consistency"],
      weaknesses: ["Not a tournament flagship"],
      relatedProductIds: ["prod-head-padel-team", "prod-head-padel-pro-plus"],
      alternativeProductIds: ["prod-tecnifibre-padel-team"],
      experienceLevels: ["beginner", "intermediate"],
    },
    {
      id: "prod-kuikma-pb-speed",
      slug: "kuikma-pb-speed",
      brandId: "brand-kuikma",
      name: "Padel Speed",
      fullName: "Kuikma Padel Speed",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.decathlon.ph/p/pressurised-padel-balls-kuikma-pb-speed-pack-of-3-kuikma-8788980.html",
      sourceName: "Decathlon / Kuikma PB Speed",
      shortDescription:
        "FIP-approved Kuikma pressurised 3-pack for slow conditions (cool, humid, sea-level). Dense core, faster acceleration.",
      verdict:
        "I’d open PB Speed on a cold Dutch evening when HEAD Pro S+ is overkill on price. Skip it in heat/altitude — that’s PB Control’s job.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "fast",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        officialApproval: "FIP",
        intendedConditions: "cool, humid, sea-level / slow courts",
        freshnessStatus: "current",
      },
      strengths: ["FIP approval", "Value vs HEAD flagship", "Fast in cool weather"],
      weaknesses: ["Not the control can for heat/altitude"],
      relatedProductIds: ["prod-kuikma-pb-control", "prod-kuikma-pb-club"],
      alternativeProductIds: ["prod-head-padel-pro-s", "prod-wilson-padel-premier-speed"],
    },
    {
      id: "prod-kuikma-pb-control",
      slug: "kuikma-pb-control",
      brandId: "brand-kuikma",
      name: "PB Control",
      fullName: "Kuikma PB Control",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.decathlon.in/p/8750703/pressurised-padel-balls-kuikma-pb-control-pack-of-3",
      sourceName: "Decathlon Kuikma PB Control",
      shortDescription:
        "FIP-approved Kuikma pressurised 3-pack for fast conditions (heat, altitude). High synthetic-felt share for abrasion resistance.",
      verdict:
        "I’d pack PB Control for summer outdoor courts. If the ball already feels dead in January, I’d reach for PB Speed instead.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        officialApproval: "FIP",
        intendedConditions: "heat, altitude / fast courts",
        freshnessStatus: "current",
      },
      strengths: ["FIP approval", "Control in heat/altitude", "Club durability"],
      weaknesses: ["Less punch than PB Speed in the cold"],
      relatedProductIds: ["prod-kuikma-pb-speed", "prod-head-padel-pro-plus"],
      alternativeProductIds: ["prod-wilson-padel-premier"],
    },
    {
      id: "prod-kuikma-pb-club",
      slug: "kuikma-pb-club",
      brandId: "brand-kuikma",
      name: "PB Club",
      fullName: "Kuikma PB Club",
      categoryId: "cat-padel-balls",
      sourceUrl: "https://www.decathlon.nl/search?Ntt=kuikma%20pb%20club",
      sourceName: "Decathlon Kuikma PB Club (range search)",
      shortDescription:
        "Kuikma’s club-durability pressurised can. Manufacturer positions it for frequent training bounce, not Premier Padel match play.",
      verdict:
        "I’d buy Club by the crate for coaching. Match night still gets a FIP can.",
      specifications: {
        ballType: "training",
        use: "training",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        freshnessStatus: "current",
      },
      strengths: ["Training volume", "Decathlon availability", "Durability-first"],
      weaknesses: ["Search URL until a NL PDP is verified; packshot pending"],
      relatedProductIds: ["prod-tecnifibre-padel-team", "prod-head-padel-team"],
      alternativeProductIds: ["prod-tecnifibre-padel-team"],
      experienceLevels: ["beginner", "intermediate"],
    },
    {
      id: "prod-wilson-padel-premier",
      slug: "wilson-padel-premier",
      brandId: "brand-wilson-padel",
      name: "Padel Premier",
      fullName: "Wilson Padel Premier",
      categoryId: "cat-padel-balls",
      sourceUrl: "https://www.padelmq.com/en-nl/products/wilson-premier-tube",
      sourceName: "PadeLMQ Wilson Premier tube",
      shortDescription:
        "Wilson’s standard Premier Padel competition can — the control-oriented sibling of Premier Speed in the current Wilson padel ball pair.",
      verdict:
        "I’d open Premier when I want Wilson familiarity without the Speed can’s extra pace. Compare it to HEAD Pro+ on control days.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        intendedConditions: "standard club/competition pace",
        freshnessStatus: "current",
      },
      strengths: ["Current Wilson competition can", "EU retail availability"],
      weaknesses: ["Less explicit condition guidance than Premier Speed"],
      relatedProductIds: ["prod-wilson-padel-premier-speed", "prod-head-padel-pro-plus"],
      alternativeProductIds: ["prod-bullpadel-premium-pro", "prod-dunlop-pro-padel"],
    },
    {
      id: "prod-wilson-padel-premier-speed",
      slug: "wilson-padel-premier-speed",
      brandId: "brand-wilson-padel",
      name: "Premier Padel Speed",
      fullName: "Wilson Premier Padel Speed",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/wilson-padel-premier-speed-tube",
      sourceName: "PadeLMQ Wilson Premier Speed tube",
      shortDescription:
        "Official Premier Padel circuit Speed can with Dura-Wave felt and a faster core. Positioned for slower courts, cold climates, and altitudes below ~600 m.",
      verdict:
        "I’d pack Speed for cold Dutch evenings and slow glass. On a hot outdoor court I’d reach for standard Premier or HEAD Pro+ instead.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "fast",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        officialApproval: "Premier Padel circuit",
        feltMaterial: "Dura-Wave",
        intendedConditions: "slow courts, cold climates, altitude below ~600 m",
        freshnessStatus: "current",
      },
      strengths: ["Premier Padel official Speed can", "Clear condition positioning"],
      weaknesses: ["Too lively for already-fast summer outdoors"],
      relatedProductIds: ["prod-wilson-padel-premier", "prod-head-padel-pro-s"],
      alternativeProductIds: ["prod-kuikma-pb-speed", "prod-head-padel-pro-s"],
    },
    {
      id: "prod-bullpadel-premium-pro",
      slug: "bullpadel-premium-pro",
      brandId: "brand-bullpadel",
      name: "Premium Pro",
      fullName: "Bullpadel Premium Pro",
      categoryId: "cat-padel-balls",
      sourceUrl: "https://www.padelmq.com/en-nl/products/premium-pro-tube",
      sourceName: "PadeLMQ Bullpadel Premium Pro tube",
      shortDescription:
        "Bullpadel’s current Premium Pro competition/training can — the commercially available successor naming to older Premium Gold listings.",
      verdict:
        "I’d shortlist Premium Pro when the club already stocks Bullpadel. HEAD Pro+/Pro S+ remain the clearer 2026 HEAD pair for speed vs control.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        freshnessStatus: "current",
      },
      strengths: ["Current Bullpadel can", "EU specialist availability"],
      weaknesses: ["Less explicit speed positioning than HEAD Pro pair"],
      relatedProductIds: ["prod-head-padel-pro-plus", "prod-dunlop-pro-padel"],
      alternativeProductIds: ["prod-wilson-padel-premier", "prod-babolat-court-padel-balls"],
    },
    {
      id: "prod-bullpadel-premium-gold",
      slug: "bullpadel-premium-gold",
      brandId: "brand-bullpadel",
      name: "Premium Gold",
      fullName: "Bullpadel Premium Gold",
      categoryId: "cat-padel-balls",
      lifecycle: "discontinued",
      sourceUrl: "https://www.bullpadel.com",
      sourceName: "Bullpadel (historical Premium Gold naming)",
      shortDescription:
        "Historical Bullpadel Premium Gold naming. Prefer current Premium Pro for shopping decisions.",
      specifications: {
        ballType: "official",
        use: "unknown",
        speed: "unknown",
        pressurization: "pressurized",
        durability: "unknown",
        packSize: "3-ball can",
        freshnessStatus: "previous_generation",
      },
      strengths: ["Historical catalog continuity"],
      weaknesses: ["Superseded by Premium Pro — do not recommend in Best Guides"],
      relatedProductIds: ["prod-bullpadel-premium-pro"],
      alternativeProductIds: ["prod-bullpadel-premium-pro"],
    },
    {
      id: "prod-adidas-aditour-padel",
      slug: "adidas-aditour-padel-balls",
      brandId: "brand-adidas-padel",
      name: "Aditour",
      fullName: "Adidas Aditour Padel Balls",
      categoryId: "cat-padel-balls",
      lifecycle: "discontinued",
      sourceUrl: "https://www.adidas.com",
      sourceName: "Adidas (historical Aditour naming)",
      shortDescription:
        "Historical Adidas Aditour padel ball naming. Prefer current Adidas Speed RX for shopping decisions.",
      specifications: {
        ballType: "official",
        use: "unknown",
        speed: "unknown",
        pressurization: "pressurized",
        durability: "unknown",
        packSize: "3-ball can",
        freshnessStatus: "discontinued",
      },
      strengths: ["Historical Adidas padel ecosystem"],
      weaknesses: ["Stale naming — replaced by Speed RX in EU retail"],
      relatedProductIds: ["prod-adidas-speed-rx"],
      alternativeProductIds: ["prod-adidas-speed-rx"],
    },
    {
      id: "prod-adidas-speed-rx",
      slug: "adidas-speed-rx-padel-balls",
      brandId: "brand-adidas-padel",
      name: "Speed RX",
      fullName: "Adidas Speed RX Padel Balls",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/adidas-speed-rx-bal-2023-1-tube-3-ballen",
      sourceName: "PadeLMQ Adidas Speed RX tube",
      shortDescription:
        "Current Adidas padel competition can sold as Speed RX in EU specialist retail — the practical successor to older Aditour listings.",
      verdict:
        "I’d consider Speed RX when Adidas kit is already in the bag. For a HEAD-style speed/control fork, Pro S+ vs Pro+ is clearer.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "fast",
        pressurization: "pressurized",
        durability: "moderate",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        freshnessStatus: "current",
      },
      strengths: ["Current Adidas EU can", "Specialist availability"],
      weaknesses: ["Less explicit condition positioning than Wilson Speed / Kuikma pair"],
      relatedProductIds: ["prod-head-padel-pro-s", "prod-wilson-padel-premier-speed"],
      alternativeProductIds: ["prod-dunlop-pro-padel", "prod-babolat-court-padel-balls"],
    },
    {
      id: "prod-babolat-court-padel-balls",
      slug: "babolat-court-padel-balls",
      brandId: "brand-babolat-padel",
      name: "Court Padel",
      fullName: "Babolat Court Padel Balls",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/babolat-court-padel-ballen-tube",
      sourceName: "PadeLMQ Babolat Court Padel tube",
      shortDescription:
        "Babolat Court padel 3-ball can — club/competition pressurized ball sold alongside Babolat padel bags and shoes.",
      verdict:
        "I’d open Court when Babolat is the club default. For a deliberate fast vs control choice, I’d still compare HEAD Pro S+ and Pro+.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "medium",
        pressurization: "pressurized",
        durability: "moderate",
        packSize: "3-ball can",
        ballsPerCan: 3,
        freshnessStatus: "current",
      },
      strengths: ["Babolat padel ecosystem", "EU specialist availability"],
      weaknesses: ["Less explicit speed positioning than HEAD/Wilson pairs"],
      relatedProductIds: ["prod-head-padel-pro-plus", "prod-bullpadel-premium-pro"],
      alternativeProductIds: ["prod-dunlop-pro-padel", "prod-wilson-padel-premier"],
    },
    {
      id: "prod-dunlop-pro-padel",
      slug: "dunlop-pro-padel",
      brandId: "brand-dunlop-padel",
      name: "Fort Padel",
      fullName: "Dunlop Fort Padel",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.zonadepadel.uk/dunlop-padel/11377-bottle-balls-dunlop-fort-padel.html",
      sourceName: "Zona de Padel Dunlop Fort Padel",
      shortDescription:
        "Current EU Dunlop Fort Padel pressurized competition can (FIP-approved) — the commercially stocked Fort line that superseded older Pro naming in specialist retail.",
      verdict:
        "I’d shortlist Fort when price and club stock matter more than a HEAD speed/control fork.",
      specifications: {
        ballType: "official",
        use: "competition",
        speed: "fast",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        officialApproval: "FIP",
        freshnessStatus: "current",
      },
      strengths: ["Widely stocked EU can", "FIP approval", "Extra-bounce positioning"],
      weaknesses: ["Less published condition guidance than Wilson Speed / Kuikma"],
      relatedProductIds: ["prod-head-padel-pro-plus", "prod-bullpadel-premium-pro"],
      alternativeProductIds: ["prod-babolat-court-padel-balls", "prod-adidas-speed-rx"],
    },
    {
      id: "prod-tecnifibre-padel-team",
      slug: "tecnifibre-padel-team-balls",
      brandId: "brand-tecnifibre-padel",
      name: "Padel Team",
      fullName: "Tecnifibre Padel Team",
      categoryId: "cat-padel-balls",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/tube-van-3-tecnifibre-padel-team-ballen",
      sourceName: "PadeLMQ Tecnifibre Padel Team tube",
      shortDescription:
        "Tecnifibre Padel Team pressurized training/club can — durability-first option for coaching volume and demoted match cans.",
      verdict:
        "I’d buy Team tubes for training crates. Match night still gets a competition can (HEAD Pro+/Pro S+ or Wilson Premier).",
      specifications: {
        ballType: "training",
        use: "training",
        speed: "medium",
        pressurization: "pressurized",
        durability: "high",
        packSize: "3-ball can",
        ballsPerCan: 3,
        cansPerBox: 24,
        freshnessStatus: "current",
      },
      strengths: ["Training volume pricing", "EU specialist availability"],
      weaknesses: ["Not a tournament flagship"],
      relatedProductIds: ["prod-head-padel-team", "prod-kuikma-pb-club"],
      alternativeProductIds: ["prod-head-padel-team"],
      experienceLevels: ["beginner", "intermediate"],
    },
  ];
}
