import type { Brand } from "@/domain/products/types";
import { publishedMeta } from "@/content/config";

const pub = publishedMeta();

export const padelSoftGoodsBrands: Brand[] = [
  {
    id: "brand-hesacore",
    name: "Hesacore",
    slug: "hesacore",
    country: "Spain",
    description: "Structured cushion grips for padel and tennis handles.",
    homepage: "https://www.hesacore.com",
    ...pub,
  },
  {
    id: "brand-dunlop-padel",
    name: "Dunlop",
    slug: "dunlop-padel",
    country: "United Kingdom",
    description: "Dunlop padel balls and court equipment sold across EU specialists.",
    homepage: "https://www.dunlopsports.com",
    ...pub,
  },
  {
    id: "brand-tretorn-padel",
    name: "Tretorn",
    slug: "tretorn-padel",
    country: "Sweden",
    description: "Tretorn Serie+ padel balls and court equipment.",
    homepage: "https://www.tretorn.eu",
    ...pub,
  },
  {
    id: "brand-tourna",
    name: "Tourna",
    slug: "tourna",
    country: "USA",
    description: "Tourna absorbent and tacky overgrips used widely in padel.",
    homepage: "https://www.uniquesports.com",
    ...pub,
  },
  {
    id: "brand-shockout",
    name: "ShockOut",
    slug: "shockout",
    country: "Spain",
    description: "Ergonomic padel grip systems and vibration accessories.",
    homepage: "https://shockoutpadel.com",
    ...pub,
  },
  {
    id: "brand-tuboplus",
    name: "TuboPlus",
    slug: "tuboplus",
    country: "Spain",
    description: "TuboPlus padel and tennis ball pressurization systems.",
    homepage: "https://tubo.plus",
    ...pub,
  },
  {
    id: "brand-ball-rescuer",
    name: "Ball Rescuer",
    slug: "ball-rescuer",
    country: "Netherlands",
    description: "Can-adapter ball pressurizer systems sold in NL/EU.",
    homepage: "https://www.oudetennisballen.com",
    ...pub,
  },
  {
    id: "brand-softee",
    name: "Softee",
    slug: "softee",
    country: "Spain",
    description: "Softee padel accessories including ball pressurizers.",
    homepage: "https://www.softee.es",
    ...pub,
  },
  {
    id: "brand-pascal-box",
    name: "Pascal Box",
    slug: "pascal-box",
    country: "Spain",
    description: "Pascal Box ball pressurization containers and compressors.",
    homepage: "https://pascalbox.com",
    ...pub,
  },
  {
    id: "brand-slazenger-padel",
    name: "Slazenger",
    slug: "slazenger-padel",
    country: "United Kingdom",
    description: "Slazenger racket-sport balls; padel SKUs under verification.",
    homepage: "https://www.slazenger.com",
    ...pub,
  },
  {
    id: "brand-volt-padel",
    name: "Volt",
    slug: "volt-padel",
    country: "Spain",
    description: "Volt padel equipment and Premium padel balls.",
    homepage: "https://www.voltpadel.com",
    ...pub,
  },
  {
    id: "brand-rs-padel",
    name: "RS",
    slug: "rs-padel",
    country: "Sweden",
    description: "RS Sports padel balls and gear for Nordics/EU.",
    homepage: "https://rs-sports.com",
    ...pub,
  },
  {
    id: "brand-bounce-tube",
    name: "Bounce Tube",
    slug: "bounce-tube",
    country: "Netherlands",
    description: "Bounce Tube padel ball pressurizer systems.",
    homepage: "https://www.tennispro.nl",
    ...pub,
  },
  {
    id: "brand-4on",
    name: "4ON",
    slug: "4on",
    country: "Spain",
    description: "4ON TotalGrip and padel grip enhancers.",
    homepage: "https://4onpadel.com",
    ...pub,
  },
  {
    id: "brand-yonex-padel",
    name: "Yonex",
    slug: "yonex-padel",
    country: "Japan",
    description: "Yonex overgrips used crossover in padel.",
    homepage: "https://www.yonex.com",
    ...pub,
  },
  {
    id: "brand-enebe",
    name: "Enebe",
    slug: "enebe",
    country: "Spain",
    description: "Enebe padel accessories and protectors.",
    homepage: "https://www.enebe.com",
    ...pub,
  },
  {
    id: "brand-vibora",
    name: "Vibora",
    slug: "vibora",
    country: "Spain",
    description: "Vibora padel accessories.",
    homepage: "https://www.viborapadel.com",
    ...pub,
  },
  {
    id: "brand-osaka-padel",
    name: "Osaka",
    slug: "osaka-padel",
    country: "Netherlands",
    description: "Osaka padel gear and balls.",
    homepage: "https://www.osaka.world",
    ...pub,
  },
  {
    id: "brand-pallap",
    name: "Pallap",
    slug: "pallap",
    country: "Spain",
    description: "Pallap niche padel balls.",
    homepage: "https://www.pallap.com",
    ...pub,
  },
  {
    id: "brand-fila-padel",
    name: "Fila",
    slug: "fila-padel",
    country: "Italy",
    description: "Fila padel balls listed in EU specialist comparisons.",
    homepage: "https://www.fila.com",
    ...pub,
  },
  {
    id: "brand-prince-padel",
    name: "Prince",
    slug: "prince-padel",
    country: "USA",
    description: "Prince padel club balls under verification.",
    homepage: "https://www.princetennis.com",
    ...pub,
  },
  {
    id: "brand-alacran",
    name: "Alacran",
    slug: "alacran",
    country: "Spain",
    description: "Alacran padel accessories.",
    homepage: "https://www.alacranpadel.com",
    ...pub,
  },
  {
    id: "brand-sane",
    name: "Sane",
    slug: "sane",
    country: "Argentina",
    description: "Sane padel balls, bags, and grips sold across ES/IT/EU specialists.",
    homepage: "https://padelsane.com",
    ...pub,
  },
  {
    id: "brand-noene",
    name: "Noene",
    slug: "noene",
    country: "Spain",
    description: "Noene anti-shock replacement grips and undergrips for padel.",
    homepage: "https://www.noene.com",
    ...pub,
  },
];
