import type { SoftDraft } from "@/content/padel/soft-goods/build";

export function gripDrafts(): SoftDraft[] {
  return [
    {
      id: "prod-wilson-overgrip",
      existing: true,
      slug: "wilson-padel-overgrip-pack",
      brandId: "brand-wilson-padel",
      name: "Pro Padel Overgrip",
      fullName: "Wilson Pro Padel Overgrip 3-Pack",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://au.wilson.com/products/pro-padel-overgrip",
      sourceName: "Wilson Pro Padel Overgrip",
      shortDescription:
        "Wilson’s padel-length Pro Overgrip: thin stretch felt, lightly tacky, 3-pack. The registered packshot is Wilson Padel Pro Overgrip white.",
      verdict:
        "I’d wrap this as the default overgrip. Thin enough that it doesn’t jump a grip size; replace every few humid sessions.",
      specifications: {
        gripType: "overgrip",
        thickness: "thin (~0.6 mm class — manufacturer “super thin”)",
        tack: "light",
        absorption: "moderate",
        feel: "thin stretch felt",
        packQuantity: "3",
      },
      strengths: ["Padel-length wrap", "Widely available", "Authentic 3-pack packshot"],
      weaknesses: ["Not the driest option for heavy sweat"],
      relatedProductIds: ["prod-head-xtreme-soft", "prod-bullpadel-gb1200"],
      alternativeProductIds: ["prod-nox-pro-overgrip", "prod-kuikma-overgrip"],
    },
    {
      id: "prod-bullpadel-gb1200",
      slug: "bullpadel-hac-overgrip",
      brandId: "brand-bullpadel",
      name: "HaC",
      fullName: "Bullpadel HaC Overgrip 3-Pack",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.zonadepadel.uk/bullpadel/1390-overgrips-gb1200-blancos.html",
      sourceName: "Zona de Padel Bullpadel GB1200",
      shortDescription:
        "Thin, absorbent Bullpadel HaC overgrip 3-pack. Packshot shows HaC Comfort, not a GB1200 blister.",
      verdict:
        "I’d pick GB1200 when Wilson Pro feels slippery mid-set. It’s a padel-native wrap, not a tennis leftover.",
      specifications: {
        gripType: "overgrip",
        thickness: "thin",
        tack: "unknown",
        absorption: "high",
        feel: "thin / light",
        packQuantity: "3",
      },
      strengths: ["Absorption-first", "Padel brand"],
      weaknesses: ["Specialist PDP, not bullpadel.com"],
      relatedProductIds: ["prod-wilson-overgrip", "prod-nox-pro-overgrip"],
      alternativeProductIds: ["prod-head-xtreme-soft"],
    },
    {
      id: "prod-nox-pro-overgrip",
      slug: "nox-pro-overgrip",
      brandId: "brand-nox",
      name: "Pro Overgrip",
      fullName: "Nox Pro Overgrip 3-Pack",
      categoryId: "cat-padel-grips",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/nox-pro-overgrip-wit-3-pack",
      sourceName: "PadeLMQ Nox Pro Overgrip white 3-pack",
      shortDescription:
        "Nox Pro padel overgrip white 3-pack — absorbent wrap positioned for humid sessions when thin tack alone fails.",
      verdict:
        "I’d wrap Nox Pro when Wilson feels slippery mid-set and I want a padel-native absorbent alternative to HaC.",
      specifications: {
        gripType: "overgrip",
        thickness: "thin",
        tack: "light",
        absorption: "high",
        feel: "absorbent padel wrap",
        packQuantity: "3",
        perforated: false,
      },
      strengths: ["Padel-native 3-pack", "Absorption-first job"],
      weaknesses: ["Less of a tack-first story than Wilson Pro"],
      relatedProductIds: ["prod-bullpadel-gb1200", "prod-wilson-overgrip"],
      alternativeProductIds: ["prod-wilson-overgrip", "prod-head-xtreme-soft"],
    },
    {
      id: "prod-head-xtreme-soft",
      slug: "head-xtreme-soft-overgrip",
      brandId: "brand-head-padel",
      name: "Xtreme Soft",
      fullName: "HEAD Xtreme Soft Overgrip",
      categoryId: "cat-padel-grips",
      sourceUrl:
        "https://www.padelmq.com/en-nl/products/head-xtreme-soft-overgrip-wit",
      sourceName: "PadeLMQ HEAD Xtreme Soft white",
      shortDescription:
        "HEAD Xtreme Soft overgrip — soft, tacky wrap used across racket sports including padel handles. Sold per grip on this listing.",
      verdict:
        "I’d use Xtreme Soft when I want a softer, tackier feel than Wilson Pro. Replace often — soft wraps die fast in humidity.",
      specifications: {
        gripType: "overgrip",
        thickness: "thin",
        tack: "tacky",
        absorption: "moderate",
        feel: "soft",
        packQuantity: "1",
      },
      strengths: ["Soft tacky feel", "Widely stocked"],
      weaknesses: ["Sold per grip on this listing — buy multipacks for value"],
      relatedProductIds: ["prod-wilson-overgrip", "prod-nox-pro-overgrip"],
      alternativeProductIds: ["prod-wilson-overgrip", "prod-bullpadel-gb1200"],
    },
    {
      id: "prod-babolat-pro-response",
      slug: "babolat-pro-response-overgrip",
      brandId: "brand-babolat-padel",
      name: "Pro Response",
      fullName: "Babolat Pro Response Overgrip",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.babolat.com/gb/pro-response-x3/653048.html",
      sourceName: "Babolat Pro Response X3",
      shortDescription:
        "Thin 0.45 mm tacky Babolat overgrip (3-pack) with high absorption — used across racket sports including padel handles.",
      specifications: {
        gripType: "overgrip",
        thickness: "0.45 mm",
        tack: "tacky",
        absorption: "high",
        feel: "thin tacky",
        packQuantity: "3",
      },
      strengths: ["Manufacturer thickness", "Thin tacky wrap"],
      weaknesses: ["Shared racket-sports grip, not padel-exclusive"],
      relatedProductIds: ["prod-wilson-overgrip"],
      alternativeProductIds: ["prod-head-xtreme-soft"],
    },
    {
      id: "prod-kuikma-overgrip",
      slug: "kuikma-padel-overgrip",
      brandId: "brand-kuikma",
      name: "Kuikma Overgrip Pro",
      fullName: "Kuikma Padel Overgrip Pro",
      categoryId: "cat-padel-grips",
      sourceUrl:
        "https://www.decathlon.sg/p/padel-overgrip-pro-kuikma-8981669.html",
      sourceName: "Decathlon Kuikma Padel Overgrip Pro",
      shortDescription:
        "Decathlon Kuikma Pro overgrip (~0.6 mm): non-slip, stretchy, sweat-absorbing club value wrap.",
      specifications: {
        gripType: "overgrip",
        thickness: "~0.6 mm",
        tack: "moderate",
        absorption: "high",
        feel: "stretch non-slip",
        packQuantity: "1+",
      },
      strengths: ["Decathlon PDP", "Value / EU stock"],
      weaknesses: ["Sold as single/club packs — confirm local pack count"],
      relatedProductIds: ["prod-wilson-overgrip"],
      alternativeProductIds: ["prod-bullpadel-gb1200"],
    },
    {
      id: "prod-head-hydrosorb",
      slug: "head-hydrosorb-replacement-grip",
      brandId: "brand-head-padel",
      name: "Hydrosorb",
      fullName: "HEAD Hydrosorb Replacement Grip",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.head.com",
      sourceName: "HEAD (brand)",
      shortDescription:
        "HEAD Hydrosorb comfort replacement grip (base grip, not an overgrip). The brand homepage is not a product page.",
      specifications: {
        gripType: "replacement",
        thickness: "unknown",
        tack: "unknown",
        absorption: "high",
        feel: "cushioned replacement",
        packQuantity: "1",
      },
      strengths: ["Replacement vs overgrip distinction"],
      weaknesses: ["No verified PDP"],
      relatedProductIds: ["prod-head-xtreme-soft"],
      alternativeProductIds: ["prod-babolat-syntec-pro"],
    },
    {
      id: "prod-babolat-syntec-pro",
      slug: "babolat-syntec-pro-replacement-grip",
      brandId: "brand-babolat-padel",
      name: "Syntec Pro",
      fullName: "Babolat Syntec Pro Replacement Grip",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.babolat.com/us/syntec-pro/670051.html",
      sourceName: "Babolat Syntec Pro",
      shortDescription:
        "Babolat Syntec Pro 1.9 mm replacement (base) grip. Distinct from Pro Response overgrip.",
      specifications: {
        gripType: "replacement",
        thickness: "1.9 mm",
        tack: "sticky / traction",
        absorption: "high",
        feel: "replacement base grip",
        packQuantity: "1",
      },
      strengths: ["Manufacturer thickness", "Replacement vs overgrip distinction"],
      weaknesses: ["Shared racket-sports grip"],
      relatedProductIds: ["prod-babolat-pro-response"],
      alternativeProductIds: ["prod-head-hydrosorb"],
    },
    {
      id: "prod-hesacore-padel",
      slug: "hesacore-padel-grip",
      brandId: "brand-hesacore",
      name: "Hesacore",
      fullName: "Hesacore Padel Grip",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.padelmq.com/en-nl/products/hesacore-grip",
      sourceName: "PadeLMQ Bullpadel Hesacore Grip Tour",
      shortDescription:
        "Structured ergonomic cushion grip system. Changes handle shape and perceived thickness — comfort preference only, not a medical claim.",
      verdict:
        "I’d try Hesacore when a standard replacement feels skinny after a long session. It is not an overgrip pack and it is not interchangeable with Wilson Pro.",
      specifications: {
        gripType: "cushion",
        thickness: "structured / raised",
        tack: "unknown",
        absorption: "unknown",
        feel: "structured cushion",
        packQuantity: "1",
        installationMethod: "replace base grip / install cushion sleeve per manufacturer",
        handleThicknessEffect: "increases effective handle girth",
        claimedBenefits: "structured comfort / finger channel feel (manufacturer positioning)",
      },
      strengths: ["Distinct cushion geometry", "Authentic packshot"],
      weaknesses: ["Not a thin overgrip; fit is personal"],
      relatedProductIds: ["prod-head-hydrosorb", "prod-wilson-overgrip"],
      alternativeProductIds: ["prod-wilson-overgrip", "prod-bullpadel-gb1200"],
    },
    {
      id: "prod-adidas-padel-overgrip",
      slug: "adidas-padel-overgrip",
      brandId: "brand-adidas-padel",
      name: "Adidas Padel Overgrip",
      fullName: "Adidas Padel Overgrip",
      categoryId: "cat-padel-grips",
      sourceUrl: "https://www.adidas.com",
      sourceName: "Adidas (brand)",
      shortDescription:
        "Adidas padel overgrip pack. The brand homepage is not a product page.",
      specifications: {
        gripType: "overgrip",
        thickness: "unknown",
        tack: "unknown",
        absorption: "unknown",
        feel: "unknown",
        packQuantity: "3",
      },
      strengths: ["Adidas padel line"],
      weaknesses: ["No verified PDP"],
      relatedProductIds: ["prod-wilson-overgrip"],
      alternativeProductIds: ["prod-head-xtreme-soft"],
    },
  ];
}
