import type { CatalogProductMediaSource } from "@/content/catalog-product-media";

/**
 * Authentic unique packshots for padel shoes (recovery) and soft goods.
 * CATALOG_PRODUCT_MEDIA wins on ID collision.
 *
 * Only entries that pass exact-product media identity (MEDIA_VERIFIED) remain.
 * Identity failures were revoked 2026-09-14
 * (72 entries) — see data/staging/padel-media-identity-revoke.json.
 */
export const PADEL_SECONDARY_PRODUCT_MEDIA: Record<
  string,
  CatalogProductMediaSource
> = {
  "prod-bullpadel-vertex-w": {
    productId: "prod-bullpadel-vertex-w",
    src: "/images/padel/products/bullpadel-vertex-w-hero.jpg",
    sourceUrl: "https://www.bullpadel.com",
    source: "Bullpadel Vertex-W packshot (Vibram) — recovered from mis-assigned Varlion file",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-tecnifibre-tour-endurance-backpack": {
    productId: "prod-tecnifibre-tour-endurance-backpack",
    src: "/images/padel/products/tecnifibre-tour-endurance-padel-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/tecnifibre-tour-endurance-rugzak-caqui",
    source: "PadeLMQ Tecnifibre Tour Endurance backpack khaki",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-kuikma-pb-speed": {
    productId: "prod-kuikma-pb-speed",
    src: "/images/padel/products/kuikma-pb-speed-hero.jpg",
    sourceUrl: "https://www.decathlon.ph/p/pressurised-padel-balls-kuikma-pb-speed-pack-of-3-kuikma-8788980.html",
    source: "Decathlon Kuikma Padel Speed can",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-nox-at10-team-bag": {
    productId: "prod-nox-at10-team-bag",
    src: "/images/padel/products/nox-at10-team-paletero-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/paletero-at10-team-grey-black",
    source: "NOX AT10 TEAM GREY/BLACK paletero",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-babolat-rh-pro-padel": {
    productId: "prod-babolat-rh-pro-padel",
    src: "/images/padel/products/babolat-rh-pro-padel-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/rh-pro/759020.html",
    source: "Babolat RH Pro Padel bag",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-gb1200": {
    productId: "prod-bullpadel-gb1200",
    src: "/images/padel/products/bullpadel-hac-overgrip-hero.jpg",
    sourceUrl: "https://www.zonadepadel.uk/bullpadel/1390-overgrips-gb1200-blancos.html",
    source: "Bullpadel HaC Comfort overgrip 3-pack (Zona de Padel)",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-head-padel-pro-plus": {
    productId: "prod-head-padel-pro-plus",
    src: "/images/padel/products/head-padel-pro-plus-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/head-pro-tube",
    source: "PadeLMQ HEAD Pro+ 3-ball tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-wilson-padel-premier": {
    productId: "prod-wilson-padel-premier",
    src: "/images/padel/products/wilson-padel-premier-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/wilson-premier-tube",
    source: "PadeLMQ Wilson Premier padel tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-wilson-padel-premier-speed": {
    productId: "prod-wilson-padel-premier-speed",
    src: "/images/padel/products/wilson-padel-premier-speed-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/wilson-padel-premier-speed-tube",
    source: "PadeLMQ Wilson Premier Padel Speed tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-premium-pro": {
    productId: "prod-bullpadel-premium-pro",
    src: "/images/padel/products/bullpadel-premium-pro-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/premium-pro-tube",
    source: "PadeLMQ Bullpadel Premium Pro tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-dunlop-pro-padel": {
    productId: "prod-dunlop-pro-padel",
    src: "/images/padel/products/dunlop-pro-padel-hero.jpg",
    sourceUrl: "https://www.zonadepadel.uk/dunlop-padel/11377-bottle-balls-dunlop-fort-padel.html",
    source: "Zona de Padel Dunlop Fort Padel",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-babolat-court-padel-balls": {
    productId: "prod-babolat-court-padel-balls",
    src: "/images/padel/products/babolat-court-padel-balls-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/babolat-court-padel-ballen-tube",
    source: "PadeLMQ Babolat Court Padel tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-vertex-backpack": {
    productId: "prod-bullpadel-vertex-backpack",
    src: "/images/padel/products/bullpadel-vertex-geo-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/bullpadel-vertex-geo-rugzak-intense-blue-2026",
    source: "PadeLMQ Bullpadel Vertex Geo backpack 2026",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-adidas-protour-padel": {
    productId: "prod-adidas-protour-padel",
    src: "/images/padel/products/adidas-protour-padel-bag-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/adidas-padeltas-protour-3-5-blauw-brons-2026",
    source: "PadeLMQ Adidas ProTour 3.5 padel bag 2026",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-wilson-super-tour-padel": {
    productId: "prod-wilson-super-tour-padel",
    src: "/images/padel/products/wilson-super-tour-padel-bag-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/wilson-bela-super-tour-padel-tas-rood",
    source: "PadeLMQ Wilson Bela Super Tour padel bag",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-nox-at10-xxl-bag": {
    productId: "prod-nox-at10-xxl-bag",
    src: "/images/padel/products/nox-at10-xxl-padel-bag-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-eu/products/nox-at10-xxl-padel-bag-black-red-agustin-tapia",
    source: "PadeLMQ Nox AT10 XXL padel bag",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-nox-pro-overgrip": {
    productId: "prod-nox-pro-overgrip",
    src: "/images/padel/products/nox-pro-overgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/nox-pro-overgrip-wit-3-pack",
    source: "PadeLMQ Nox Pro Overgrip white 3-pack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-xtreme-soft": {
    productId: "prod-head-xtreme-soft",
    src: "/images/padel/products/head-xtreme-soft-overgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/head-xtreme-soft-overgrip-wit",
    source: "PadeLMQ HEAD Xtreme Soft overgrip white",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-hesacore-padel": {
    productId: "prod-hesacore-padel",
    src: "/images/padel/products/hesacore-padel-grip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/hesacore-grip",
    source: "PadeLMQ Bullpadel Hesacore Grip Tour",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-frame-protector": {
    productId: "prod-bullpadel-frame-protector",
    src: "/images/padel/products/bullpadel-frame-protector-3-pack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/bullpadel-frame-protector-zwart-3-stuks",
    source: "PadeLMQ Bullpadel Frame Protector black 3-pack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-nox-frame-protector": {
    productId: "prod-nox-frame-protector",
    src: "/images/padel/products/nox-transparent-frame-protector-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/nox-protection-tape-transparant-framebeschermer",
    source: "PadeLMQ Nox transparent protection tape",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-pascal-box": {
    productId: "prod-bullpadel-pascal-box",
    src: "/images/padel/products/bullpadel-pascal-box-3b-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/pascal-box-3b",
    source: "PadeLMQ Bullpadel Pascal Box 3B",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-x3-pressurizer": {
    productId: "prod-head-x3-pressurizer",
    src: "/images/padel/products/head-x3-ball-pressurizer-hero.jpg",
    sourceUrl: "https://padelproshop.com/en/products/pressurizer-head-x3-pump",
    source: "PadelPROShop HEAD X3 PUMP pressurizer",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-bullpadel-custom-weight": {
    productId: "prod-bullpadel-custom-weight",
    src: "/images/padel/products/bullpadel-protector-custom-weight-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/bullpadel-protector-custom-weight-4-stuks",
    source: "PadeLMQ Bullpadel Protector Custom Weight 4-pack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-adidas-speed-rx": {
    productId: "prod-adidas-speed-rx",
    src: "/images/padel/products/adidas-speed-rx-padel-balls-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/adidas-speed-rx-bal-2023-1-tube-3-ballen",
    source: "PadeLMQ Adidas Speed RX tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-tecnifibre-padel-team": {
    productId: "prod-tecnifibre-padel-team",
    src: "/images/padel/products/tecnifibre-padel-team-balls-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/tube-van-3-tecnifibre-padel-team-ballen",
    source: "PadeLMQ Tecnifibre Padel Team tube",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-padel-team": {
    productId: "prod-head-padel-team",
    src: "/images/padel/products/head-padel-team-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-eu/products/head-padel-team-3-tubes-of-3-balls",
    source: "Padel Market HEAD Team 3-tube pack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-head-padel-one": {
    productId: "prod-head-padel-one",
    src: "/images/padel/products/head-padel-one-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-gb/products/head-padel-one-tube-of-3-balls",
    source: "Padel Market HEAD Padel One",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
  },
  "prod-kuikma-pb-control": {
    productId: "prod-kuikma-pb-control",
    src: "/images/padel/products/kuikma-pb-control-hero.jpg",
    sourceUrl: "https://www.decathlon.in/p/8750703/pressurised-padel-balls-kuikma-pb-control-pack-of-3",
    source: "Decathlon Kuikma PB Control",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-babolat-court-backpack": {
    productId: "prod-babolat-court-backpack",
    src: "/images/padel/products/babolat-court-backpack-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/court-s/102-759022.html",
    source: "Babolat Court S padel bag (Court line)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1039,
    height: 1039,
  },
  "prod-head-elite-backpack": {
    productId: "prod-head-elite-backpack",
    src: "/images/padel/products/head-elite-padel-backpack-hero.jpg",
    sourceUrl: "https://www.tennis-point.co.uk/products/head-tour-team-elite-backpack-limeblue-00637502591000",
    source: "Tennis-Point HEAD Tour Team Elite Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-kuikma-overgrip": {
    productId: "prod-kuikma-overgrip",
    src: "/images/padel/products/kuikma-padel-overgrip-hero.jpg",
    sourceUrl: "https://www.decathlon.sg/p/padel-overgrip-pro-kuikma-8981669.html",
    source: "Decathlon Kuikma Padel Overgrip Pro",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-babolat-pro-response": {
    productId: "prod-babolat-pro-response",
    src: "/images/padel/products/babolat-pro-response-overgrip-hero.jpg",
    sourceUrl: "https://www.babolat.com/gb/pro-response-x3/653048.html",
    source: "Babolat Pro Response X3",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1010,
    height: 1011,
  },
  "prod-babolat-syntec-pro": {
    productId: "prod-babolat-syntec-pro",
    src: "/images/padel/products/babolat-syntec-pro-replacement-grip-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/syntec-pro/670051.html",
    source: "Babolat Syntec Pro",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
  },
  "prod-head-x3-pump": {
    productId: "prod-head-x3-pump",
    src: "/images/padel/accessories/head-x3-pump-hero.jpg",
    sourceUrl: "https://padelproshop.com/en/products/pressurizer-head-x3-pump",
    source: "og:image · head X3 Pump",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 768,
    height: 768,
    retrievedAt: "2026-09-13",
  },
  "prod-head-coello-tour-bag": {
    productId: "prod-head-coello-tour-bag",
    src: "/images/padel/bags/head-coello-tour-bag-hero.jpg",
    sourceUrl: "https://elpadel.ae/product/head-coello-tour-padel-bag-2026/",
    source: "og:image · head Coello Tour Bag",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-head-tour-backpack-25l": {
    productId: "prod-head-tour-backpack-25l",
    src: "/images/padel/bags/head-tour-backpack-25l-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-gb/products/head-tour-backpack-25l-2026-black-backpack",
    source: "og:image · head Tour Backpack 25L",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-kuikma-pb-club": {
    productId: "prod-kuikma-pb-club",
    src: "/images/padel/balls/kuikma-pb-club-hero.jpg",
    sourceUrl: "https://padelracketkopen.nl/padel-ballen/kuikma-pb-club-18x-4st/",
    source: "og:image · kuikma PB Club",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1024,
    height: 1024,
    retrievedAt: "2026-09-13",
  },
  "prod-babolat-court": {
    productId: "prod-babolat-court",
    src: "/images/padel/balls/babolat-court-hero.jpg",
    sourceUrl: "https://www.babolat.com/gb/court-x3/501098.html",
    source: "og:image · babolat Court",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1016,
    height: 1016,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-one": {
    productId: "prod-black-crown-one",
    src: "/images/padel/balls/black-crown-one-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en/products/black-crown-one-padel-ball-box",
    source: "retailer-shopify-json · black-crown One",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-pro": {
    productId: "prod-black-crown-pro",
    src: "/images/padel/balls/black-crown-pro-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en-nl/products/black-crown-pro-padel-balls-tube",
    source: "retailer-shopify-json · black-crown Pro",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-fip-next-pro": {
    productId: "prod-bullpadel-fip-next-pro",
    src: "/images/padel/balls/bullpadel-fip-next-pro-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-gb/products/bullpadel-next-pro-tube-of-3-balls",
    source: "og:image · bullpadel FIP Next Pro",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-next": {
    productId: "prod-bullpadel-next",
    src: "/images/padel/balls/bullpadel-next-hero.jpg",
    sourceUrl: "https://mrhsport.com/blogs/the-clubhouse-blog/bullpadel-padel-balls-explained-premium-pro-next-next-pro",
    source: "og:image · bullpadel Next",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-speed-tech": {
    productId: "prod-drop-shot-speed-tech",
    src: "/images/padel/balls/drop-shot-speed-tech-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/drop-shot-jon-sanz-axion-attack-1-5-2025?_pos=1&_psq=drop-shot+Speed+Tech&_psid=dcf6c5764&_ss=e",
    source: "padelmq-suggest · drop-shot Speed Tech",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-training-tech": {
    productId: "prod-drop-shot-training-tech",
    src: "/images/padel/balls/drop-shot-training-tech-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/drop-shot-quantum-soft-w-2026?_pos=1&_psq=drop-shot+Training+Tech&_psid=33da30369&_ss=e",
    source: "padelmq-suggest · drop-shot Training Tech",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-dunlop-eco": {
    productId: "prod-dunlop-eco",
    src: "/images/padel/balls/dunlop-eco-hero.jpg",
    sourceUrl: "https://padelgearpro.nl/dunlop-eco-padel-24x3-review/",
    source: "og:image · dunlop Eco",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1024,
    height: 576,
    retrievedAt: "2026-09-13",
  },
  "prod-dunlop-pro": {
    productId: "prod-dunlop-pro",
    src: "/images/padel/balls/dunlop-pro-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en/products/dunlop-pro-padel-ball-tube",
    source: "retailer-shopify-json · dunlop Pro",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-fila-premium-pro": {
    productId: "prod-fila-premium-pro",
    src: "/images/padel/balls/fila-premium-pro-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/premium-pro-tube?_pos=1&_psq=fila+Premium+Pro&_psid=ceaed0e8a&_ss=e",
    source: "padelmq-suggest · fila Premium Pro",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-nerbo": {
    productId: "prod-nox-nerbo",
    src: "/images/padel/balls/nox-nerbo-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/nerbo-balls-3",
    source: "og:image · nox Nerbo",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-nerbo-speed": {
    productId: "prod-nox-nerbo-speed",
    src: "/images/padel/balls/nox-nerbo-speed-hero.jpg",
    sourceUrl: "https://funpadel.pt/nox-nerbo-speed-balls-tube",
    source: "json-ld · nox Nerbo+ Speed",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-pro-titanium": {
    productId: "prod-nox-pro-titanium",
    src: "/images/padel/balls/nox-pro-titanium-hero.jpg",
    sourceUrl: "https://noxsport.com/en/collections/padel-balls-pro-titanium",
    source: "og:image · nox Pro Titanium",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 707,
    retrievedAt: "2026-09-13",
  },
  "prod-osaka-pro-tour": {
    productId: "prod-osaka-pro-tour",
    src: "/images/padel/balls/osaka-pro-tour-hero.jpg",
    sourceUrl: "https://osakaworld.com/en-us/products/osaka-pro-tour-padel-ball-3-ball-can-no-color-1",
    source: "retailer-shopify-json · osaka Pro Tour",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-osaka-vision": {
    productId: "prod-osaka-vision",
    src: "/images/padel/balls/osaka-vision-hero.jpg",
    sourceUrl: "https://osakaworld.com/en-gb/products/osaka-vision-padel-ball-3-ball-can-no-color",
    source: "retailer-shopify-json · osaka Vision",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-oxdog-boost": {
    productId: "prod-oxdog-boost",
    src: "/images/padel/balls/oxdog-boost-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en/products/oxdog-boost-padel-ball-tube",
    source: "retailer-shopify-json · oxdog Boost",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 394,
    height: 700,
    retrievedAt: "2026-09-13",
  },
  "prod-rs-champions-choice": {
    productId: "prod-rs-champions-choice",
    src: "/images/padel/balls/rs-champions-choice-hero.jpg",
    sourceUrl: "https://rs-sports.com/en-us/products/rs-champions-choice-x-1",
    source: "retailer-shopify-json · rs Champions Choice",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 735,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-rs-nova-x": {
    productId: "prod-rs-nova-x",
    src: "/images/padel/balls/rs-nova-x-hero.jpg",
    sourceUrl: "https://rs-sports.com/en-global/products/rs-padel-nova-x",
    source: "retailer-shopify-json · rs Nova X",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 735,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-neo": {
    productId: "prod-siux-neo",
    src: "/images/padel/balls/siux-neo-hero.jpg",
    sourceUrl: "https://www.siuxpadel.com/en/blogs/press/nace-siux-neo-las-nuevas-pelotas-de-padel-disenadas-para-cada-tipo-de-jugador",
    source: "og:image · siux Neo",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 900,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-neo-speed-neo-s": {
    productId: "prod-siux-neo-speed-neo-s",
    src: "/images/padel/balls/siux-neo-speed-neo-s-hero.jpg",
    sourceUrl: "https://padel-magazine.co.uk/siux-obtains-approval-from-the-fip-for-its-neo-and-neo-speed-balls/",
    source: "og:image · siux Neo Speed (Neo S)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 675,
    retrievedAt: "2026-09-13",
  },
  "prod-tecnifibre-padel-tour": {
    productId: "prod-tecnifibre-padel-tour",
    src: "/images/padel/balls/tecnifibre-padel-tour-hero.jpg",
    sourceUrl: "https://www.squashgearpro.com/shop/140-padel-tennis-balls/1907-tecnifibre-padel-tour-padel-balls---1-tube/",
    source: "og:image · tecnifibre Padel Tour",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-tretorn-serie-padel-control": {
    productId: "prod-tretorn-serie-padel-control",
    src: "/images/padel/balls/tretorn-serie-padel-control-hero.jpg",
    sourceUrl: "https://www.tretorn.eu/gb/serie-padel-control-padel-ball-men-women-474481070",
    source: "og:image · tretorn Serie+ Padel Control",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-tretorn-serie-padel-tour": {
    productId: "prod-tretorn-serie-padel-tour",
    src: "/images/padel/balls/tretorn-serie-padel-tour-hero.jpg",
    sourceUrl: "https://www.tretorn.eu/gb/serie-padel-tour-padel-ball-men-women-474470070",
    source: "og:image · tretorn Serie+ Padel Tour",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-volt-premium": {
    productId: "prod-volt-premium",
    src: "/images/padel/balls/volt-premium-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/premium-pro-doos-24-tubes-72-ballen?_pos=1&_psq=volt+Premium&_psid=341f8b154&_ss=e",
    source: "padelmq-suggest · volt Premium",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-premier-padel": {
    productId: "prod-wilson-premier-padel",
    src: "/images/padel/balls/wilson-premier-padel-hero.jpg",
    sourceUrl: "https://padelshop.com/nl/products/wilson-premier-padel-balls-1-can",
    source: "retailer-shopify-json · wilson Premier Padel",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-rush-100": {
    productId: "prod-wilson-rush-100",
    src: "/images/padel/balls/wilson-rush-100-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/wilson-rush-pro-5-clay-schoenen-zwart-wit?_pos=1&_psq=wilson+Rush+100&_psid=cc476955b&_ss=e",
    source: "padelmq-suggest · wilson Rush 100",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-head-tour-team-padel": {
    productId: "prod-head-tour-team-padel",
    src: "/images/padel/bags/head-tour-team-padel-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-tour-padel-l-blauwe-padeltas-2026?_pos=1&_psq=head+Tour+Team+Padel&_psid=d6834d8fc&_ss=e",
    source: "padelmq-suggest · head Tour Team Padel",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-control-2026": {
    productId: "prod-adidas-control-2026",
    src: "/images/padel/bags/adidas-control-2026-hero.jpg",
    sourceUrl: "https://padelproshop.com/en-de/products/padel-bag-adidas-control-white-2026",
    source: "og:image · adidas Control 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-protour-backpack-2026": {
    productId: "prod-adidas-protour-backpack-2026",
    src: "/images/padel/bags/adidas-protour-backpack-2026-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/uk/bag-adidas-protour-2026-ab1ma6u26",
    source: "og:image · adidas ProTour Backpack 2026",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-tour": {
    productId: "prod-adidas-tour",
    src: "/images/padel/bags/adidas-tour-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/adidas-padeltas-tour-3-5-silver-2026?_pos=1&_psq=adidas+Tour&_psid=674e7ab7e&_ss=e",
    source: "padelmq-suggest · adidas Tour",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-babolat-rh-perf": {
    productId: "prod-babolat-rh-perf",
    src: "/images/padel/bags/babolat-rh-perf-hero.jpg",
    sourceUrl: "https://www.babolat.com/us/rh-perf/759021.html",
    source: "og:image · babolat RH Perf",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1114,
    height: 1114,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-spartan": {
    productId: "prod-black-crown-spartan",
    src: "/images/padel/bags/black-crown-spartan-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/black-crown-spartan-rugzak-zwart-rood",
    source: "og:image · black-crown Spartan",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-thunder": {
    productId: "prod-black-crown-thunder",
    src: "/images/padel/bags/black-crown-thunder-hero.jpg",
    sourceUrl: "https://www.padelshack.com/product/black-crown-thunder-padel-bag-2026-blackblack/",
    source: "og:image · black-crown Thunder",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-ultimate-pro-2-0": {
    productId: "prod-black-crown-ultimate-pro-2-0",
    src: "/images/padel/bags/black-crown-ultimate-pro-2-0-hero.jpg",
    sourceUrl: "https://www.padelshack.com/product/black-crown-ultimate-pro-20-padel-racket-bag-2025-navy/",
    source: "og:image · black-crown Ultimate Pro 2.0",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-casual-bpp26016": {
    productId: "prod-bullpadel-casual-bpp26016",
    src: "/images/padel/bags/bullpadel-casual-bpp26016-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-padeltas-casual-zwart-2026?_pos=1&_psq=bullpadel+Casual+BPP26016&_psid=1e4019b93&_ss=e",
    source: "padelmq-suggest · bullpadel Casual BPP26016",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-elite-bpp26019": {
    productId: "prod-bullpadel-elite-bpp26019",
    src: "/images/padel/bags/bullpadel-elite-bpp26019-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-padeltas-elite-2025?_pos=1&_psq=bullpadel+Elite+BPP26019&_psid=a3156dcd3&_ss=e",
    source: "padelmq-suggest · bullpadel Elite BPP26019",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1188,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-icon-bpp26023": {
    productId: "prod-bullpadel-icon-bpp26023",
    src: "/images/padel/bags/bullpadel-icon-bpp26023-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-icon-2026?_pos=1&_psq=bullpadel+Icon+BPP26023&_psid=88dc90a77&_ss=e",
    source: "padelmq-suggest · bullpadel Icon BPP26023",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-ionic-bpp26005": {
    productId: "prod-bullpadel-ionic-bpp26005",
    src: "/images/padel/bags/bullpadel-ionic-bpp26005-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-ionic-control-2025?_pos=1&_psq=bullpadel+Ionic+BPP26005&_psid=4a59d8039&_ss=e",
    source: "padelmq-suggest · bullpadel Ionic BPP26005",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 960,
    height: 960,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-neuron-bpm26020": {
    productId: "prod-bullpadel-neuron-bpm26020",
    src: "/images/padel/bags/bullpadel-neuron-bpm26020-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-neuron-2025?_pos=1&_psq=bullpadel+Neuron+BPM26020&_psid=b8d253a38&_ss=e",
    source: "padelmq-suggest · bullpadel Neuron BPM26020",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-pearl-bpm27017": {
    productId: "prod-bullpadel-pearl-bpm27017",
    src: "/images/padel/bags/bullpadel-pearl-bpm27017-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-pearl-2026?_pos=1&_psq=bullpadel+Pearl+BPM27017&_psid=c7ec28c48&_ss=e",
    source: "padelmq-suggest · bullpadel Pearl BPM27017",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-tour-bpp26015": {
    productId: "prod-bullpadel-tour-bpp26015",
    src: "/images/padel/bags/bullpadel-tour-bpp26015-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-premier-padel-tour-crudo-2026?_pos=1&_psq=bullpadel+Tour+BPP26015&_psid=a0dd10ed9&_ss=e",
    source: "padelmq-suggest · bullpadel Tour BPP26015",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-wonder-bpp26024": {
    productId: "prod-bullpadel-wonder-bpp26024",
    src: "/images/padel/bags/bullpadel-wonder-bpp26024-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-wonder-2026-kopie?_pos=1&_psq=bullpadel+Wonder+BPP26024&_psid=b2f00312e&_ss=e",
    source: "padelmq-suggest · bullpadel Wonder BPP26024",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-xplo-bpp26022": {
    productId: "prod-bullpadel-xplo-bpp26022",
    src: "/images/padel/bags/bullpadel-xplo-bpp26022-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-xplo-2025-volledig-nieuw-model?_pos=1&_psq=bullpadel+Xplo+BPP26022&_psid=6f8a09136&_ss=e",
    source: "padelmq-suggest · bullpadel Xplo BPP26022",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-bpm26007-bpm26008-vertex": {
    productId: "prod-bullpadel-bpm26007-bpm26008-vertex",
    src: "/images/padel/bags/bullpadel-bpm26007-bpm26008-vertex-hero.jpg",
    sourceUrl: "https://padelshop.com/products/bullpadel-bpm26008-vertex-backpack",
    source: "retailer-shopify-json · bullpadel BPM26007 / BPM26008 Vertex",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-blitz": {
    productId: "prod-drop-shot-blitz",
    src: "/images/padel/bags/drop-shot-blitz-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-worldwide/products/drop-shot-blitz-2025-mochila",
    source: "retailer-shopify-json · drop-shot Blitz",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-head-coello-pro-x-backpack": {
    productId: "prod-head-coello-pro-x-backpack",
    src: "/images/padel/bags/head-coello-pro-x-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-backpack-coello-pro-x-grijs-2026?_pos=1&_psq=head+Coello+Pro+X+Backpack&_psid=816c83831&_ss=e",
    source: "padelmq-suggest · head Coello Pro X Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-head-coello-pro-x-duffle-l": {
    productId: "prod-head-coello-pro-x-duffle-l",
    src: "/images/padel/bags/head-coello-pro-x-duffle-l-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-padeltas-coello-pro-x-duffle-zwart-2026?_pos=1&_psq=head+Coello+Pro+X+Duffle+L&_psid=91f98567c&_ss=e",
    source: "padelmq-suggest · head Coello Pro X Duffle L",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-head-coello-tour-backpack": {
    productId: "prod-head-coello-tour-backpack",
    src: "/images/padel/bags/head-coello-tour-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-backpack-coello-tour-grijs-2026?_pos=1&_psq=head+Coello+Tour+Backpack&_psid=fd2bc902b&_ss=e",
    source: "padelmq-suggest · head Coello Tour Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-head-pro-x-bag-l": {
    productId: "prod-head-pro-x-bag-l",
    src: "/images/padel/bags/head-pro-x-bag-l-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-pro-x-tote-bag-22l-lichtgrijs?_pos=1&_psq=head+Pro+X+Bag+L&_psid=2df23c526&_ss=e",
    source: "padelmq-suggest · head Pro X Bag L",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-lok-aventure-gen-2": {
    productId: "prod-lok-aventure-gen-2",
    src: "/images/padel/bags/lok-aventure-gen-2-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-worldwide/products/lok-aventure-gen-2-2026-backpack",
    source: "og:image · lok Aventure Gen 2",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-lok-maxx-gen-2": {
    productId: "prod-lok-maxx-gen-2",
    src: "/images/padel/bags/lok-maxx-gen-2-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-eu/products/lok-maxx-gen-2-black-orange-2026-backpack",
    source: "og:image · lok Maxx Gen 2 Paletero",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-at10-competition-trolley": {
    productId: "prod-nox-at10-competition-trolley",
    src: "/images/padel/bags/nox-at10-competition-trolley-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/paletero-at10-competition-trolley-2024",
    source: "retailer-shopify-json · nox AT10 Competition Trolley",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-at10-team": {
    productId: "prod-nox-at10-team",
    src: "/images/padel/bags/nox-at10-team-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/paletero-at10-team-grey-black",
    source: "retailer-shopify-json · nox AT10 Team",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-luxury-master-backpack": {
    productId: "prod-nox-luxury-master-backpack",
    src: "/images/padel/bags/nox-luxury-master-backpack-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/backpack-luxury-master-series",
    source: "og:image · nox Luxury Master Backpack",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-luxury-master-series": {
    productId: "prod-nox-luxury-master-series",
    src: "/images/padel/bags/nox-luxury-master-series-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/nox-luxury-master-series-padeltas-zwart-wit-agustin-tapia",
    source: "og:image · nox Luxury Master Series",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-luxury-open-backpack": {
    productId: "prod-nox-luxury-open-backpack",
    src: "/images/padel/bags/nox-luxury-open-backpack-hero.jpg",
    sourceUrl: "https://noxsport.com/en/products/backpack-luxury-open-series-black-red",
    source: "og:image · nox Luxury Open Backpack",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-luxury-open-series": {
    productId: "prod-nox-luxury-open-series",
    src: "/images/padel/bags/nox-luxury-open-series-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/nox-luxury-open-series-padeltas-zwart-rood-agustin-tapia",
    source: "og:image · nox Luxury Open Series",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-pro-series-backpack": {
    productId: "prod-nox-pro-series-backpack",
    src: "/images/padel/bags/nox-pro-series-backpack-hero.jpg",
    sourceUrl: "https://padelshop.com/products/nox-pro-series-white-backpack",
    source: "retailer-shopify-json · nox Pro Series Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-oxdog-hyper-tour-thermo-backpack": {
    productId: "prod-oxdog-hyper-tour-thermo-backpack",
    src: "/images/padel/bags/oxdog-hyper-tour-thermo-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/hyper-pro-thermo-padel-bag?_pos=1&_psq=oxdog+Hyper+Tour+Thermo+Backpack&_psid=31fe543a0&_ss=e",
    source: "padelmq-suggest · oxdog Hyper Tour Thermo Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 921,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-padel-overgrip": {
    productId: "prod-adidas-padel-overgrip",
    src: "/images/padel/grips/adidas-padel-overgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/adidas-overgrip-oranje?_pos=1&_psq=adidas+Adidas+Padel+Overgrip&_psid=d20f41bf6&_ss=e",
    source: "padelmq-suggest · adidas Adidas Padel Overgrip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-babolat-vs-original": {
    productId: "prod-babolat-vs-original",
    src: "/images/padel/grips/babolat-vs-original-hero.jpg",
    sourceUrl: "https://tennisshot.gr/en-gb/babolat-vs-original-white-x1-padel",
    source: "json-ld · babolat VS Original",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-black-crown-perforated": {
    productId: "prod-black-crown-black-crown-perforated",
    src: "/images/padel/grips/black-crown-black-crown-perforated-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/black-crown-patron-xtrem-2025?_pos=1&_psq=black-crown+Black+Crown+Perforated&_psid=c033de535&_ss=e",
    source: "padelmq-suggest · black-crown Black Crown Perforated",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-comfort-overgrip": {
    productId: "prod-bullpadel-comfort-overgrip",
    src: "/images/padel/grips/bullpadel-comfort-overgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-overgrips-geel?_pos=1&_psq=bullpadel+Comfort+Overgrip&_psid=d32335c4b&_ss=e",
    source: "padelmq-suggest · bullpadel Comfort Overgrip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-club": {
    productId: "prod-drop-shot-club",
    src: "/images/padel/grips/drop-shot-club-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/int/3-pack-of-drop-shot-club-overgrips",
    source: "og:image · drop-shot Club",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-super-tacky": {
    productId: "prod-drop-shot-super-tacky",
    src: "/images/padel/grips/drop-shot-super-tacky-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/uk/tub-of-drop-shot-super-tacky-x60-overgrips-30041-p",
    source: "og:image · drop-shot Super Tacky",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-head-xtreme-soft-xtremesoft": {
    productId: "prod-head-xtreme-soft-xtremesoft",
    src: "/images/padel/grips/head-xtreme-soft-xtremesoft-hero.jpg",
    sourceUrl: "https://padel.how/equipment/overgrip/head-xtremesoft-overgrip-review/",
    source: "og:image · head Xtreme Soft / XtremeSoft",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1008,
    height: 756,
    retrievedAt: "2026-09-13",
  },
  "prod-hesacore-pro-carbon": {
    productId: "prod-hesacore-pro-carbon",
    src: "/images/padel/grips/hesacore-pro-carbon-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/hesacore-tour-grip-carbon?_pos=1&_psq=hesacore+Pro+Carbon&_psid=695c97206&_ss=e",
    source: "padelmq-suggest · hesacore Pro Carbon",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 333,
    height: 333,
    retrievedAt: "2026-09-13",
  },
  "prod-hesacore-tour-original": {
    productId: "prod-hesacore-tour-original",
    src: "/images/padel/grips/hesacore-tour-original-hero.jpg",
    sourceUrl: "https://eu.hesacore.com/products/padel-hesacore-tour-grip",
    source: "retailer-shopify-json · hesacore Tour / Original",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-elite-overgrip": {
    productId: "prod-siux-elite-overgrip",
    src: "/images/padel/grips/siux-elite-overgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/siux-trilogy-elite-2026?_pos=1&_psq=siux+Elite+Overgrip&_psid=38bd99a29&_ss=e",
    source: "padelmq-suggest · siux Elite Overgrip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-premier-soft": {
    productId: "prod-starvie-premier-soft",
    src: "/images/padel/grips/starvie-premier-soft-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/starvie-brava-soft-2025?_pos=1&_psq=starvie+Premier+Soft&_psid=68e1ab262&_ss=e",
    source: "padelmq-suggest · starvie Premier Soft",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 450,
    height: 450,
    retrievedAt: "2026-09-13",
  },
  "prod-tecnifibre-players-pro-feel": {
    productId: "prod-tecnifibre-players-pro-feel",
    src: "/images/padel/grips/tecnifibre-players-pro-feel-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/pt/pack-30-overgrips-tecnifibre-players-pro-feel",
    source: "og:image · tecnifibre Players Pro Feel",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-profile-padel": {
    productId: "prod-wilson-profile-padel",
    src: "/images/padel/grips/wilson-profile-padel-hero.jpg",
    sourceUrl: "https://www.tradeinn.com/smashinn/en/wilson-profile-padel-overgrip/139879280/p",
    source: "og:image · wilson Profile Padel",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-oxdog-gold-pro": {
    productId: "prod-oxdog-gold-pro",
    src: "/images/padel/grips/oxdog-gold-pro-hero.jpg",
    sourceUrl: "https://oxdogpadel.com/en-us/products/gold-pro-overgrip-x3",
    source: "retailer-shopify-json · oxdog Gold Pro",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-oxdog-gold-sticky": {
    productId: "prod-oxdog-gold-sticky",
    src: "/images/padel/grips/oxdog-gold-sticky-hero.jpg",
    sourceUrl: "https://oxdogpadel.com/en-us/products/gold-sticky-overgrip-x3",
    source: "retailer-shopify-json · oxdog Gold Sticky",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-volt-volt-premium": {
    productId: "prod-volt-volt-premium",
    src: "/images/padel/grips/volt-volt-premium-hero.jpg",
    sourceUrl: "https://padelpop.lt/produktas/volt-premium-padelio-overgripai/",
    source: "og:image · volt Volt Premium",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-royal-padel-royal-overgrip": {
    productId: "prod-royal-padel-royal-overgrip",
    src: "/images/padel/grips/royal-padel-royal-overgrip-hero.jpg",
    sourceUrl: "https://royalpadel.com/en/product/bobina-overgrips-royal-padel-60/",
    source: "og:image · royal Royal Overgrip",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1024,
    height: 1024,
    retrievedAt: "2026-09-13",
  },
  "prod-4on-swiftgrip": {
    productId: "prod-4on-swiftgrip",
    src: "/images/padel/grips/4on-swiftgrip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/swiftgrip?_pos=1&_psq=4on+SwiftGrip&_psid=ee76e615a&_ss=e",
    source: "padelmq-suggest · 4on SwiftGrip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 900,
    retrievedAt: "2026-09-13",
  },
  "prod-head-prime-tour": {
    productId: "prod-head-prime-tour",
    src: "/images/padel/grips/head-prime-tour-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/bolsa-30-uds-overgrip-head-prime-tour-285641-bk",
    source: "og:image · head Prime Tour",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-4on-totalgrip": {
    productId: "prod-4on-totalgrip",
    src: "/images/padel/accessories/4on-totalgrip-hero.jpg",
    sourceUrl: "https://www.4on.store/products/totalgrip/4on-totalgrip-spray",
    source: "og:image · 4on TotalGrip",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-ball-rescuer-ball-rescuer": {
    productId: "prod-ball-rescuer-ball-rescuer",
    src: "/images/padel/accessories/ball-rescuer-ball-rescuer-hero.jpg",
    sourceUrl: "https://ballrescuer.com/en-nl",
    source: "og:image · ball-rescuer Ball Rescuer",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 540,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-black-crown-wristband": {
    productId: "prod-black-crown-black-crown-wristband",
    src: "/images/padel/accessories/black-crown-black-crown-wristband-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/black-crown-polsbanden-2-stuks?_pos=1&_psq=black-crown+Black+Crown+Wristband&_psid=1f5bd4f50&_ss=e",
    source: "padelmq-suggest · black-crown Black Crown Wristband",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-custom-weight-grip": {
    productId: "prod-bullpadel-custom-weight-grip",
    src: "/images/padel/accessories/bullpadel-custom-weight-grip-hero.jpg",
    sourceUrl: "https://www.padelnuestro.com/int/box-12-pcs-blister-3-pcs-protector-bullpadel-custom-weight-black-111273-p",
    source: "og:image · bullpadel Custom Weight Grip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-frame-protector-uni": {
    productId: "prod-bullpadel-frame-protector-uni",
    src: "/images/padel/accessories/bullpadel-frame-protector-uni-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/bullpadel-frame-guard-transparant-3-stuks?_pos=1&_psq=bullpadel+Frame+Protector+Uni&_psid=e92e20b70&_ss=e",
    source: "padelmq-suggest · bullpadel Frame Protector Uni",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-enebe-enebe-protector-line": {
    productId: "prod-enebe-enebe-protector-line",
    src: "/images/padel/accessories/enebe-enebe-protector-line-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/enebe-dentado-frame-protector-zwart?_pos=1&_psq=enebe+Enebe+Protector+line&_psid=d76accf8c&_ss=e",
    source: "padelmq-suggest · enebe Enebe Protector line",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-head-antishock-skin": {
    productId: "prod-head-antishock-skin",
    src: "/images/padel/accessories/head-antishock-skin-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/head-anti-shock-skin-protector-transparant?_pos=1&_psq=head+Antishock+Skin&_psid=36af542d2&_ss=e",
    source: "padelmq-suggest · head Antishock Skin",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 550,
    height: 550,
    retrievedAt: "2026-09-13",
  },
  "prod-nox-weight-balancer-2-4g": {
    productId: "prod-nox-weight-balancer-2-4g",
    src: "/images/padel/accessories/nox-weight-balancer-2-4g-hero.jpg",
    sourceUrl: "https://www.extreme-tennis.eu/padel-accessories/23570-nox-weight-balancer-padel.html",
    source: "og:image · nox Weight Balancer 2-4g",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-shockout-gravity": {
    productId: "prod-shockout-gravity",
    src: "/images/padel/accessories/shockout-gravity-hero.jpg",
    sourceUrl: "https://www.shockout.es/tienda/gravity/gravity/",
    source: "og:image · shockout Gravity+",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-softee-softee-protector": {
    productId: "prod-softee-softee-protector",
    src: "/images/padel/accessories/softee-softee-protector-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/softee-protector-dentado-zwart?_pos=1&_psq=softee+Softee+Protector&_psid=ce19b3f63&_ss=e",
    source: "padelmq-suggest · softee Softee Protector",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-transparent-protector-2026": {
    productId: "prod-starvie-transparent-protector-2026",
    src: "/images/padel/accessories/starvie-transparent-protector-2026-hero.jpg",
    sourceUrl: "https://www.padelshack.com/product/starvie-transparent-protector-2026/",
    source: "og:image · starvie Transparent Protector 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-vibora-vibor-a-transparent": {
    productId: "prod-vibora-vibor-a-transparent",
    src: "/images/padel/accessories/vibora-vibor-a-transparent-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/vibora-diva-swarovski-tas-bruin?_pos=1&_psq=vibora+Vibor-A+Transparent&_psid=c5b49c839&_ss=e",
    source: "padelmq-suggest · vibora Vibor-A Transparent",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-accessory-pouch-2026": {
    productId: "prod-adidas-accessory-pouch-2026",
    src: "/images/padel/accessories/adidas-accessory-pouch-2026-hero.jpg",
    sourceUrl: "https://padelmarket.com/en/products/adidas-accessory-bag-red-black-2026-ale-galan-toiletry-bag",
    source: "og:image · adidas Accessory Pouch 2026",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-adidas-shoe-bag-ale-gal-n": {
    productId: "prod-adidas-shoe-bag-ale-gal-n",
    src: "/images/padel/accessories/adidas-shoe-bag-ale-gal-n-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/adidas-ale-galan-3-5-schoentas-zwart-rood?_pos=1&_psq=adidas+Shoe+Bag+Ale+Gal%C3%A1n&_psid=65fb4f4fa&_ss=e",
    source: "padelmq-suggest · adidas Shoe Bag Ale Galán",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-4on-totalgrip-paste": {
    productId: "prod-4on-totalgrip-paste",
    src: "/images/padel/accessories/4on-totalgrip-paste-hero.jpg",
    sourceUrl: "https://www.4on.store/products/totalgrip/4on-totalgrip-paste",
    source: "og:image · 4on TotalGrip Paste",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-royal-padel-force": {
    productId: "prod-royal-padel-force",
    src: "/images/padel/bags/royal-padel-force-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/royal-padel-force-zwarte-padeltas-2026",
    source: "og:image · royal Force",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-nomad": {
    productId: "prod-siux-nomad",
    src: "/images/padel/bags/siux-nomad-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/siux-nomad-rugzak-zwart-blauw-2026",
    source: "og:image · siux Nomad",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-electra-stupa-2026": {
    productId: "prod-siux-electra-stupa-2026",
    src: "/images/padel/bags/siux-electra-stupa-2026-hero.jpg",
    sourceUrl: "https://www.siuxpadel.com/products/paletero-siux-electra-stupa-2026",
    source: "retailer-shopify-json · siux Electra Stupa 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-tour": {
    productId: "prod-siux-tour",
    src: "/images/padel/bags/siux-tour-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/siux-tour-rugzak-zwart-2026",
    source: "og:image · siux Tour",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-siux-trail": {
    productId: "prod-siux-trail",
    src: "/images/padel/bags/siux-trail-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/siux-trail-rugzak-grijs-2026",
    source: "og:image · siux Trail",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-hard-eva": {
    productId: "prod-starvie-hard-eva",
    src: "/images/padel/bags/starvie-hard-eva-hero.jpg",
    sourceUrl: "https://starvie.com/en/products/hard-eva-black",
    source: "retailer-shopify-json · starvie Hard Eva",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-hard-eva-backpack": {
    productId: "prod-starvie-hard-eva-backpack",
    src: "/images/padel/bags/starvie-hard-eva-backpack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/starvie-hard-eva-zwarte-rugzak?_pos=1&_psq=starvie+Hard+Eva+Backpack&_psid=b8736d2d8&_ss=e",
    source: "padelmq-suggest · starvie Hard Eva Backpack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-pro-master": {
    productId: "prod-starvie-pro-master",
    src: "/images/padel/bags/starvie-pro-master-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/starvie-pro-master-padel-tas",
    source: "og:image · starvie Pro Master",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-starvie-tactic-pro": {
    productId: "prod-starvie-tactic-pro",
    src: "/images/padel/bags/starvie-tactic-pro-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/starvie-tactic-pro-padel-tas?_pos=1&_psq=starvie+Tactic+Pro&_psid=cf84a6d9c&_ss=e",
    source: "padelmq-suggest · starvie Tactic Pro",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1100,
    height: 1100,
    retrievedAt: "2026-09-13",
  },
  "prod-tecnifibre-tour-endurance-bag": {
    productId: "prod-tecnifibre-tour-endurance-bag",
    src: "/images/padel/bags/tecnifibre-tour-endurance-bag-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/tecnifibre-tour-endurance-sporttas-wit-blauw?_pos=1&_psq=tecnifibre+Tour+Endurance+Bag&_psid=3eedab0eb&_ss=e",
    source: "padelmq-suggest · tecnifibre Tour Endurance Bag",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-bela-super-tour-backpack": {
    productId: "prod-wilson-bela-super-tour-backpack",
    src: "/images/padel/bags/wilson-bela-super-tour-backpack-hero.jpg",
    sourceUrl: "https://tennisshot.gr/en-gb/wilson-bela-super-tour-padel-backpack",
    source: "json-ld · wilson Bela Super Tour Backpack",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 800,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-super-tour-2026": {
    productId: "prod-wilson-super-tour-2026",
    src: "/images/padel/bags/wilson-super-tour-2026-hero.jpg",
    sourceUrl: "https://www.padelshack.com/product/wilson-tour-super-red-padel-racket-bag-2026/",
    source: "og:image · wilson Super Tour 2026",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-black-crown-plus": {
    productId: "prod-black-crown-plus",
    src: "/images/padel/bags/black-crown-plus-hero.jpg",
    sourceUrl: "https://www.padelmq.com/en/products/black-crown-plus-black-padel-bag",
    source: "retailer-shopify-json · black-crown Plus",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-lok-one-gen-2": {
    productId: "prod-lok-one-gen-2",
    src: "/images/padel/bags/lok-one-gen-2-hero.jpg",
    sourceUrl: "https://www.padelshack.com/product/lok-racket-bag-one-gen-2-blackorange-2026/",
    source: "og:image · lok One Gen 2",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 610,
    height: 610,
    retrievedAt: "2026-09-13",
  },
  "prod-lok-accessory-bag-gen-2": {
    productId: "prod-lok-accessory-bag-gen-2",
    src: "/images/padel/bags/lok-accessory-bag-gen-2-hero.jpg",
    sourceUrl: "https://padelmarket.com/en/products/lok-gen-2-black-orange-2026-toiletry-bag",
    source: "og:image · lok Accessory Bag Gen 2",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-volt-volt-padelbag": {
    productId: "prod-volt-volt-padelbag",
    src: "/images/padel/bags/volt-volt-padelbag-hero.jpg",
    sourceUrl: "https://padelshop.com/products/volt-padel-bag-black",
    source: "retailer-shopify-json · volt Volt Padelbag",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-wilson-wilson-replacement-grip": {
    productId: "prod-wilson-wilson-replacement-grip",
    src: "/images/padel/grips/wilson-wilson-replacement-grip-hero.jpg",
    sourceUrl: "https://www.padelmq.com/products/wilson-pro-overgrip-perforated-wit?_pos=1&_psq=wilson+Wilson+Replacement+Grip&_psid=ba663ef1a&_ss=e",
    source: "padelmq-suggest · wilson Wilson Replacement Grip",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 800,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-bpm26002-hack": {
    productId: "prod-bullpadel-bpm26002-hack",
    src: "/images/padel/bags/bullpadel-bpm26002-hack-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/bullpadel-hack-rugzak-grijsgroen-2026",
    source: "manual-approve · bullpadel BPM26002 Hack",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-bpp26001-vertex": {
    productId: "prod-bullpadel-bpp26001-vertex",
    src: "/images/padel/bags/bullpadel-bpp26001-vertex-hero.jpg",
    sourceUrl: "https://padelmarket.com/en-eu/products/bullpadel-bpp-26001-vertex-black-2026-juan-tello-racket-bag",
    source: "manual-approve · bullpadel BPP26001 Vertex",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-bullpadel-bpp26022-xplo": {
    productId: "prod-bullpadel-bpp26022-xplo",
    src: "/images/padel/bags/bullpadel-bpp26022-xplo-hero.jpg",
    sourceUrl: "https://www.padelmq.com/nl-nl/products/bullpadel-padeltas-xplo-zwart-2026-martin-di-nenno",
    source: "manual-approve · bullpadel BPP26022 XPLO",
    licence: "retailer-authorized",
    attribution: "© Brand — official / authorized product photography",
    width: 1000,
    height: 1000,
    retrievedAt: "2026-09-13",
  },
  "prod-kuikma-pl-900-elite": {
    productId: "prod-kuikma-pl-900-elite",
    src: "/images/padel/bags/kuikma-pl-900-elite-hero.jpg",
    sourceUrl: "https://padelmad.co.uk/equipment/accessories/kuikma-insulated-padel-bag-elite-review/",
    source: "page-img · kuikma PL 900 Elite",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-drop-shot-tournament-tech": {
    productId: "prod-drop-shot-tournament-tech",
    src: "/images/padel/balls/drop-shot-tournament-tech-hero.jpg",
    sourceUrl: "https://padelproshop.com/en-mtcy/products/can-of-drop-shot-padel-balls-tournament-pro",
    source: "manual-approve · drop-shot Tournament Tech",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1024,
    height: 1024,
    retrievedAt: "2026-09-13",
  },
  "prod-varlion-summum-pro-w": {
    productId: "prod-varlion-summum-pro-w",
    src: "/images/padel/balls/varlion-summum-pro-w-hero.jpg",
    sourceUrl: "https://www.varlion.com/gb/padel/balls/summum-pro-w-ball-box-24-units.html",
    source: "Varlion Summum Pro W ball box",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-varlion-summum-pro": {
    productId: "prod-varlion-summum-pro",
    src: "/images/padel/bags/varlion-summum-pro-hero.jpg",
    sourceUrl: "https://www.varlion.com/gb/padel/bags/padel-racket-bags/padel-bag-summum-pro-.html",
    source: "Varlion Summum Pro padel bag",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-yonex-super-grap": {
    productId: "prod-yonex-super-grap",
    src: "/images/padel/grips/yonex-super-grap-hero.jpg",
    sourceUrl: "https://www.totalpadel.com/Yonex_Super_Grap_Overgrip_Black/descpageYONEX-YSOG-EN.html",
    source: "Yonex Super Grap overgrip (Tennis Warehouse Europe)",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 900,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-varlion-summum-pro-s": {
    productId: "prod-varlion-summum-pro-s",
    src: "/images/padel/balls/varlion-summum-pro-s-hero.jpg",
    sourceUrl: "https://www.varlion.com/gb/padel/balls/summum-pro-s-ball-box-24-units.html",
    source: "Varlion Summum Pro S ball box",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1200,
    height: 1200,
    retrievedAt: "2026-09-13",
  },
  "prod-4on-pro-t1": {
    productId: "prod-4on-pro-t1",
    src: "/images/padel/balls/4on-pro-t1-hero.jpg",
    sourceUrl:
      "https://www.4on.store/products/padelballs/4on-pro-t1-padel-balls-3p-tube",
    source: "4on manufacturer store — Pro T1 3-pack tube packshot",
    licence: "manufacturer-marketing",
    attribution: "© Brand — official / authorized product photography",
    width: 1134,
    height: 1700,
    retrievedAt: "2026-09-14",
  },
};
