#!/usr/bin/env tsx
/**
 * Upgrade thin Buy if / Skip if seeds to Vomero-standard decision lines.
 *
 * Default: report only (enriched page path).
 * --write: persist upgraded audience signals into source content files.
 *
 * Usage:
 *   npm run reviews:upgrade-audience
 *   npm run reviews:upgrade-audience -- --fail
 *   npm run reviews:upgrade-audience -- --write
 *   npm run reviews:upgrade-audience -- --write --dry-run
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Review } from "@/domain/editorial/types";
import { reviewsWave1 } from "@/content/reviews-wave1";
import { reviewsBackfill } from "@/content/reviews-backfill";
import { reviewsWatchesWave2 } from "@/content/reviews-watches-wave2";
import { reviews as allReviewsExport } from "@/content/reviews";
import { hrmFlagshipReviews } from "@/content/running/reviews/hrm-flagship";
import { gpsWatchFlagshipReviews } from "@/content/running/reviews/gps-watch-flagship";
import { getBrandById, getProductById, getReviews } from "@/repositories";
import {
  audienceSignalsAreThin,
  ensureAudienceSignals,
} from "@/lib/review/audience-signals";
import { enrichReviewForPage } from "@/lib/review/enrich-review-for-page";
import { publishedMeta } from "@/content/config";

function flag(name: string): boolean {
  return process.argv.includes(`--${name}`);
}

function reviewToTsLiteral(r: Review): string {
  const pub = r.status === "published";
  const lines: string[] = [];
  lines.push(`  {`);
  lines.push(`    id: ${JSON.stringify(r.id)},`);
  lines.push(`    slug: ${JSON.stringify(r.slug)},`);
  lines.push(`    productId: ${JSON.stringify(r.productId)},`);
  lines.push(`    title: ${JSON.stringify(r.title)},`);
  if (r.subtitle) lines.push(`    subtitle: ${JSON.stringify(r.subtitle)},`);
  lines.push(`    reviewType: ${JSON.stringify(r.reviewType)},`);
  lines.push(`    bottomLine: ${JSON.stringify(r.bottomLine)},`);
  lines.push(`    verdict: ${JSON.stringify(r.verdict)},`);
  lines.push(`    score: ${r.score},`);
  lines.push(`    summary: ${JSON.stringify(r.summary)},`);
  lines.push(`    reviewerId: ${JSON.stringify(r.reviewerId)},`);
  lines.push(`    testingContext: ${JSON.stringify(r.testingContext)},`);
  lines.push(`    editorialDisclosure: ${JSON.stringify(r.editorialDisclosure)},`);
  lines.push(`    sections: ${JSON.stringify(r.sections)},`);
  lines.push(`    pros: ${JSON.stringify(r.pros)},`);
  lines.push(`    cons: ${JSON.stringify(r.cons)},`);
  lines.push(`    whoShouldBuy: ${JSON.stringify(r.whoShouldBuy)},`);
  lines.push(`    whoShouldAvoid: ${JSON.stringify(r.whoShouldAvoid)},`);
  lines.push(`    scoreBreakdown: ${JSON.stringify(r.scoreBreakdown)},`);
  lines.push(`    evidenceIds: ${JSON.stringify(r.evidenceIds)},`);
  lines.push(`    alternativeProductIds: ${JSON.stringify(r.alternativeProductIds)},`);
  lines.push(`    comparisonIds: ${JSON.stringify(r.comparisonIds)},`);
  lines.push(`    faqIds: [],`);
  if (r.seoTitle) lines.push(`    seoTitle: ${JSON.stringify(r.seoTitle)},`);
  if (r.seoDescription) lines.push(`    seoDescription: ${JSON.stringify(r.seoDescription)},`);
  if (pub) {
    lines.push(`    ...pub,`);
  } else {
    lines.push(`    status: ${JSON.stringify(r.status)},`);
    lines.push(`    createdAt: pub.createdAt,`);
    lines.push(`    updatedAt: pub.updatedAt,`);
    lines.push(`    lastVerifiedAt: pub.lastVerifiedAt,`);
  }
  lines.push(`  }`);
  return lines.join("\n");
}

function writeBackfillFile(reviews: Review[], dryRun: boolean): string {
  const path = join(process.cwd(), "src/content/reviews-backfill.ts");
  const header = `/**
 * AUTO-GENERATED by scripts/upgrade-review-audience.ts --write
 * Buy if / Skip if upgraded to Vomero-standard decision lines.
 * Re-run: npm run reviews:upgrade-audience -- --write
 */
import type { Review } from "@/domain/editorial/types";
import { publishedMeta } from "@/content/config";

const pub = publishedMeta();

export const reviewsBackfill: Review[] = [
`;
  const body = reviews.map(reviewToTsLiteral).join(",\n");
  const file = `${header}${body}\n];\n`;
  if (!dryRun) writeFileSync(path, file, "utf8");
  return path;
}

function upgradeReview(review: Review): Review {
  const product = getProductById(review.productId, { isDev: true });
  if (!product) return review;
  const brand = getBrandById(product.brandId, { isDev: true });
  if (!audienceSignalsAreThin(review)) return review;
  const next = ensureAudienceSignals(review, product, brand);
  return {
    ...review,
    whoShouldBuy: next.whoShouldBuy,
    whoShouldAvoid: next.whoShouldAvoid,
  };
}

function formatStringArray(values: string[], indent = "    "): string {
  const inner = values.map((v) => `${indent}  ${JSON.stringify(v)}`).join(",\n");
  return `[\n${inner},\n${indent}]`;
}

function patchAudienceArrays(
  filePath: string,
  review: Review,
  upgraded: Review,
  dryRun: boolean,
  keys: { buy: string; avoid: string } = {
    buy: "whoShouldBuy",
    avoid: "whoShouldAvoid",
  },
): boolean {
  if (
    JSON.stringify(review.whoShouldBuy) === JSON.stringify(upgraded.whoShouldBuy) &&
    JSON.stringify(review.whoShouldAvoid) === JSON.stringify(upgraded.whoShouldAvoid)
  ) {
    return false;
  }
  let src = readFileSync(filePath, "utf8");
  const buyNeedle = `${keys.buy}: ${JSON.stringify(review.whoShouldBuy)}`;
  const buyRepl = `${keys.buy}: ${JSON.stringify(upgraded.whoShouldBuy)}`;
  const avoidNeedle = `${keys.avoid}: ${JSON.stringify(review.whoShouldAvoid)}`;
  const avoidRepl = `${keys.avoid}: ${JSON.stringify(upgraded.whoShouldAvoid)}`;
  let changed = false;
  if (src.includes(buyNeedle)) {
    src = src.split(buyNeedle).join(buyRepl);
    changed = true;
  }
  if (src.includes(avoidNeedle)) {
    src = src.split(avoidNeedle).join(avoidRepl);
    changed = true;
  }

  // Multiline arrays (reviews-watches-wave2 drafts use buy/avoid blocks)
  if (!changed) {
    const slugEsc = review.slug.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const blockRe = new RegExp(
      `(slug:\\s*"${slugEsc}"[\\s\\S]*?)${keys.buy}:\\s*\\[[\\s\\S]*?\\],\\s*${keys.avoid}:\\s*\\[[\\s\\S]*?\\],`,
      "m",
    );
    if (blockRe.test(src)) {
      src = src.replace(
        blockRe,
        `$1${keys.buy}: ${formatStringArray(upgraded.whoShouldBuy)},\n    ${keys.avoid}: ${formatStringArray(upgraded.whoShouldAvoid)},`,
      );
      changed = true;
    }
  }

  if (changed && !dryRun) writeFileSync(filePath, src, "utf8");
  return changed;
}

async function persistAudience(dryRun: boolean): Promise<{
  backfill: number;
  wave1: number;
  watchesWave2: number;
  hand: number;
  remainingThin: number;
}> {
  const nextBackfill = reviewsBackfill.map(upgradeReview);
  const backfill = nextBackfill.filter(
    (r, i) => JSON.stringify(r) !== JSON.stringify(reviewsBackfill[i]),
  ).length;
  writeBackfillFile(nextBackfill, dryRun);

  let wave1 = 0;
  const wavePath = join(process.cwd(), "src/content/reviews-wave1.ts");
  for (const review of reviewsWave1) {
    const upgraded = upgradeReview(review);
    if (patchAudienceArrays(wavePath, review, upgraded, dryRun)) wave1 += 1;
  }

  let watchesWave2 = 0;
  const watchesPath = join(process.cwd(), "src/content/reviews-watches-wave2.ts");
  const nextWatches: Review[] = [];
  for (const review of reviewsWatchesWave2) {
    const upgraded = upgradeReview(review);
    nextWatches.push(upgraded);
    if (
      patchAudienceArrays(watchesPath, review, upgraded, dryRun, {
        buy: "buy",
        avoid: "avoid",
      })
    ) {
      watchesWave2 += 1;
    }
  }

  let hand = 0;
  const coveredIds = new Set([
    ...reviewsWave1.map((r) => r.id),
    ...reviewsBackfill.map((r) => r.id),
    ...reviewsWatchesWave2.map((r) => r.id),
  ]);
  const handTargets: Array<{ review: Review; path: string }> = [
    {
      review: allReviewsExport.find((r) => r.slug === "saucony-peregrine-15")!,
      path: join(process.cwd(), "src/content/running/reviews/peregrine-15.ts"),
    },
    ...hrmFlagshipReviews.map((review) => ({
      review,
      path: join(process.cwd(), "src/content/running/reviews/hrm-flagship.ts"),
    })),
    ...gpsWatchFlagshipReviews.map((review) => ({
      review,
      path: join(process.cwd(), "src/content/running/reviews/gps-watch-flagship.ts"),
    })),
  ].filter((t) => t.review);

  for (const r of allReviewsExport) {
    if (coveredIds.has(r.id)) continue;
    if (handTargets.some((t) => t.review.id === r.id)) continue;
    handTargets.push({
      review: r,
      path: join(process.cwd(), "src/content/reviews.ts"),
    });
  }

  for (const { review, path } of handTargets) {
    if (!audienceSignalsAreThin(review)) continue;
    const upgraded = upgradeReview(review);
    if (patchAudienceArrays(path, review, upgraded, dryRun)) hand += 1;
  }

  // Count thin against merged live sources (watches wave2 wins over backfill)
  const wave1ById = new Map(reviewsWave1.map((r) => [r.id, upgradeReview(r)]));
  const watchByProduct = new Map(
    nextWatches
      .filter((r) => !["saucony-peregrine-15"].includes(r.slug))
      .map((r) => [r.productId, r]),
  );
  const backfillOverrideSlugs = new Set([
    "saucony-peregrine-15",
    ...hrmFlagshipReviews.map((r) => r.slug),
    ...gpsWatchFlagshipReviews.map((r) => r.slug),
  ]);

  let remainingThin = 0;
  for (const r of allReviewsExport) {
    const live =
      wave1ById.get(r.id) ??
      (backfillOverrideSlugs.has(r.slug)
        ? upgradeReview(r)
        : watchByProduct.get(r.productId) ??
          nextBackfill.find((b) => b.id === r.id) ??
          upgradeReview(r));
    if (audienceSignalsAreThin(live)) remainingThin += 1;
  }

  return { backfill, wave1, watchesWave2, hand, remainingThin };
}

async function main(): Promise<void> {
  const fail = flag("fail");
  const write = flag("write");
  const dryRun = flag("dry-run");
  void publishedMeta;

  if (write) {
    const result = await persistAudience(dryRun);
    console.log(
      `${dryRun ? "Dry-run" : "Wrote"} audience upgrades — backfill ${result.backfill} · wave1 ${result.wave1} · watchesWave2 ${result.watchesWave2} · hand ${result.hand} · remaining thin ${result.remainingThin}`,
    );
    if (fail && result.remainingThin > 0) process.exit(1);
    return;
  }

  const reviews = getReviews({ isDev: true });
  let thinBefore = 0;
  let thinAfter = 0;
  const samples: Array<{
    slug: string;
    beforeBuy: string[];
    afterBuy: string[];
    afterAvoid: string[];
  }> = [];

  for (const review of reviews) {
    const product = getProductById(review.productId, { isDev: true });
    if (!product) continue;
    const brand = getBrandById(product.brandId, { isDev: true });
    if (audienceSignalsAreThin(review)) thinBefore += 1;
    const upgraded = ensureAudienceSignals(review, product, brand);
    const fake = {
      ...review,
      whoShouldBuy: upgraded.whoShouldBuy,
      whoShouldAvoid: upgraded.whoShouldAvoid,
    };
    if (audienceSignalsAreThin(fake)) thinAfter += 1;
    if (samples.length < 8 && audienceSignalsAreThin(review)) {
      samples.push({
        slug: review.slug,
        beforeBuy: review.whoShouldBuy ?? [],
        afterBuy: upgraded.whoShouldBuy,
        afterAvoid: upgraded.whoShouldAvoid,
      });
    }
    enrichReviewForPage(review, product, { brand });
  }

  const report = {
    total: reviews.length,
    thinBefore,
    thinAfter,
    samples,
  };

  const outDir = join(process.cwd(), "data", "staging", "reviews");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "audience-upgrade-report.json");
  writeFileSync(outPath, JSON.stringify(report, null, 2));

  console.log(
    `Reviews ${report.total} · thin Buy/Skip before ${thinBefore} · after enrich ${thinAfter}`,
  );
  console.log(`Wrote ${outPath}`);
  console.log(`Tip: persist with npm run reviews:upgrade-audience -- --write`);
  if (fail && thinAfter > 0) {
    console.error("Still thin after upgrade:", thinAfter);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
