/**
 * AUTO-GENERATED by scripts/tmp/prelaunch-54-held-estate.ts
 * Reviews that cannot be finished without fabricating first-hand tests
 * or inventing specs the catalog does not support.
 */
export const BLOCKED_EVIDENCE_REVIEW_SLUGS = new Set<string>([]);

export function isBlockedEvidenceReview(slug: string): boolean {
  return BLOCKED_EVIDENCE_REVIEW_SLUGS.has(slug);
}
