/**
 * AUTO-GENERATED by scripts/tmp/prelaunch-54-held-estate.ts
 * Day-1 index holds for remaining DUPLICATIVE / undifferentiable reviews.
 * Empty after Fix 54 when the live category-peer cluster is clean.
 */
export const CONTENT_UNIQUENESS_REVIEW_HOLDS = new Set<string>([]);

export function isContentUniquenessReviewHeld(slug: string): boolean {
  return CONTENT_UNIQUENESS_REVIEW_HOLDS.has(slug);
}
