import type { SeedSpec } from "./queue-types";

const DB = "campaign-database";
const FINDER = "campaign-finder";
const MKT = "campaign-market-2026";
const A_DB = "asset-shoe-database";
const A_FIND = "asset-shoe-finder";
const A_BEST = "asset-best-running-shoes";
const A_DAILY = "asset-best-daily-trainers";
const A_CHOOSE = "asset-guide-choose-shoes";
const A_DROP = "asset-guide-drop";
const _A_MKT = "asset-research-market-2026";
const _A_CMP = "asset-compare";

/**
 * First serious prospecting queue. Every row has a specific page that already
 * teaches, cites data, or maintains a resource — not merely a running homepage.
 * Contacts are CONTACT_UNKNOWN unless a public editorial address was verified.
 */
export const INITIAL_QUEUE: SeedSpec[] = [
  {
    id: "fellrnr-table",
    name: "Fellrnr shoe metric table",
    domain: "fellrnr.com",
    homepageUrl: "https://fellrnr.com/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Already publishes a public comparison table of drop, stack, weight and cushioning.",
    type: "DATABASE_CITATION",
    url: "https://fellrnr.com/wiki/Shoes-metric-table",
    topic: "Running shoe drop, stack and weight table",
    relevance: 98,
    authority: 72,
    likelihood: 70,
    editorial: 88,
    relationship: 18,
    evidence: "Live wiki table of shoe metrics. Natural complementary cite for a current searchable catalog.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The table is static and hand-maintained; Kitletics is a current, filterable dataset of the same specs.",
    pitchOverride: "Offer a live searchable catalog of weight, drop and stack as a companion to the wiki table.",
    subjectLine: "A current drop/stack/weight table to sit beside your shoe metric wiki",
    publicContactRoute: "Wiki / site owner identity on fellrnr.com — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "fellrnr-look",
    name: "Fellrnr — what to look for in shoes",
    domain: "fellrnr.com",
    homepageUrl: "https://fellrnr.com/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Education page that already links out to his science-of-shoes framework.",
    type: "RESOURCE_PAGE",
    url: "http://fellrnr.com/wiki/What_to_Look_for_in_Running_Shoes",
    topic: "What to look for in running shoes",
    relevance: 90,
    authority: 72,
    likelihood: 62,
    editorial: 86,
    relationship: 16,
    evidence: "Resource page with methodology. Same operator as the metric table — one outreach thread, this URL as the education hook.",
    campaignId: DB,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "The explainer already sends readers to specs; a current catalog plus a how-to-choose page is the missing public lookup.",
    pitchOverride: "Pair the wiki explainer with How to Choose Running Shoes and the live database for numbers.",
    subjectLine: "A public lookup to sit next to What to Look for in Running Shoes",
    publicContactRoute: "Same operator as the metric table — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "aapsm-runshoe",
    name: "AAPSM running shoe resources",
    domain: "aapsm.org",
    homepageUrl: "http://www.aapsm.org/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Sports-medicine podiatry society already maintains a shoe terminology resource with further-reading links.",
    type: "UNIVERSITY_RESEARCH",
    url: "http://www.aapsm.org/runshoe.html",
    topic: "Stack height vs offset/drop for clinicians",
    relevance: 94,
    authority: 80,
    likelihood: 64,
    editorial: 90,
    relationship: 12,
    evidence: "Resource page that already distinguishes stack vs drop and links Podiatry Today. Perfect further-reading slot for a neutral dataset.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The page already has a Runner's Resources list. A current stack/drop/weight catalog is the missing public dataset.",
    pitchOverride: "Offer a citeable, current stack/drop/weight catalog for the further-reading list — not a Best-of page.",
    subjectLine: "A current stack/drop catalog for the AAPSM running-shoe resource list",
    publicContactRoute: "aapsm.org contact / member directory — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "running-channel-stack",
    name: "The Running Channel",
    domain: "therunningchannel.com",
    homepageUrl: "https://therunningchannel.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "GB",
    language: "en",
    market: "global",
    whyRelevant: "Published an explainer that defines stack and drop and tells readers every review lists those numbers.",
    type: "DATA_CITATION",
    url: "https://therunningchannel.com/running-shoe-stack-height/",
    topic: "Running shoe stack height and drop explained",
    relevance: 96,
    authority: 78,
    likelihood: 66,
    editorial: 84,
    relationship: 14,
    evidence: "Mark Dredge explainer, 8 Jul 2026. Already teaches the metrics the database publishes.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The article tells readers reviews list stack and drop but does not point to a living catalog of current models.",
    pitchOverride: "Add a current searchable catalog so readers can look up stack/drop/weight instead of a static example.",
    subjectLine: "A live stack/drop catalog to sit under your stack-height explainer",
    publicContactRoute: "therunningchannel.com/contact or byline on the article — no email stored.",
    contactName: "Mark Dredge",
    contactRole: "gear_editor",
    competitorGap: "Does not need RunRepeat; the explainer is first-party. Complementary public table.",
  },
  {
    id: "canadian-running-drop",
    name: "Canadian Running Magazine",
    domain: "runningmagazine.ca",
    homepageUrl: "https://runningmagazine.ca/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "CA",
    language: "en",
    market: "CA",
    whyRelevant: "Long-form drop explainer with clinician quotes and transition guidance.",
    type: "DATA_CITATION",
    url: "https://runningmagazine.ca/sections/gear/deconstructing-heel-to-toe-offset-aka-drop-in-running-shoes/",
    topic: "Heel-to-toe offset / drop",
    relevance: 95,
    authority: 76,
    likelihood: 63,
    editorial: 88,
    relationship: 12,
    evidence: "Gear section explainer citing clinician Sheppard. Already a data story without a living table.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "Readers are told not to jump drop ranges; a current catalog lets them check the drop they already own.",
    pitchOverride: "Point the drop explainer at How we explain drop plus the live catalog for current millimetre values.",
    subjectLine: "A current drop lookup for your heel-to-toe offset explainer",
    publicContactRoute: "runningmagazine.ca/contact — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "wisdom-running-drop",
    name: "Wisdom Running",
    domain: "wisdomrunning.com",
    homepageUrl: "https://wisdomrunning.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Dedicated drop-choice guide with injury-history tables — already a resource page.",
    type: "RESOURCE_PAGE",
    url: "https://wisdomrunning.com/heel-to-toe-drop-in-running-shoes/",
    topic: "Heel-to-toe drop how to choose",
    relevance: 92,
    authority: 58,
    likelihood: 72,
    editorial: 82,
    relationship: 20,
    evidence: "Independent explainer (Jul 2026) that already behaves like a resource. Moderate authority, high relevance and likelihood.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The guide tells people to pick a drop range then sanity-check it; a live catalog is the lookup step.",
    pitchOverride: "Offer the database as the lookup after their 60-second drop picker.",
    subjectLine: "A searchable drop/stack catalog for your heel-to-toe drop guide",
    publicContactRoute: "Site contact / about — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "runners-blueprint-drop",
    name: "Runners Blueprint",
    domain: "runnersblueprint.com",
    homepageUrl: "https://www.runnersblueprint.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach explainer with drop ranges by injury history — education intent, not a homepage.",
    type: "COACH_RESOURCE",
    url: "https://www.runnersblueprint.com/heel-to-toe-drop/",
    topic: "Heel-to-toe drop for coaches and beginners",
    relevance: 88,
    authority: 60,
    likelihood: 68,
    editorial: 78,
    relationship: 16,
    evidence: "Coach-authored drop guide. Good finder + database pair.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "The page already teaches drop; Kitletics can add a how-to-choose guide and a catalog so readers do not stop at a table of ranges.",
    pitchOverride: "How to Choose Running Shoes as the teaching companion; database for millimetre lookup.",
    subjectLine: "A choose-shoes guide to sit next to your drop explainer",
    publicContactRoute: "runnersblueprint.com/contact or about — no email stored.",
    contactRole: "coach",
  },
  {
    id: "strength-running-choose",
    name: "Strength Running",
    domain: "strengthrunning.com",
    homepageUrl: "https://strengthrunning.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach education page on choosing shoes by fit, not gait labels.",
    type: "COACH_RESOURCE",
    url: "https://strengthrunning.com/2011/11/how-to-choose-running-shoes/",
    topic: "How to choose running shoes",
    relevance: 90,
    authority: 74,
    likelihood: 64,
    editorial: 86,
    relationship: 18,
    evidence: "Evergreen coach guide. Jason Fitzgerald is publicly named; no email stored.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "The article argues fit over gait labels — same thesis as Kitletics' how-to-choose page, with a finder for readers who want a next step.",
    pitchOverride: "How to Choose Running Shoes + Running Shoe Finder for readers who finish the essay and still need a shortlist.",
    subjectLine: "A decision tool for readers who finish How to Choose Running Shoes",
    publicContactRoute: "strengthrunning.com/contact — no email stored.",
    contactName: "Jason Fitzgerald",
    contactRole: "coach",
  },
  {
    id: "strength-running-klein",
    name: "Strength Running × Matt Klein",
    domain: "strengthrunning.com",
    homepageUrl: "https://strengthrunning.com/",
    category: "FITNESS_MEDIA",
    mix: "podcast",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Interview with Doctors of Running's Matt Klein on choosing shoes as tools.",
    type: "EXPERT_QUOTE",
    url: "https://strengthrunning.com/2023/07/how-to-choose-the-perfect-running-shoe-matt-klein/",
    topic: "Choosing shoes with a clinician",
    relevance: 88,
    authority: 74,
    likelihood: 58,
    editorial: 88,
    relationship: 22,
    evidence: "Already platforms DoR. Complementary public dataset is the Kitletics angle, not a request that DoR link back.",
    campaignId: FINDER,
    recommendedAssetId: A_DAILY,
    whyTheyMightLink: "Show notes already send people to a clinician; Best Daily Trainers + Finder is the practical next click for easy-day shoes.",
    pitchOverride: "Daily-trainer shortlist and finder as the listener next step after the Klein interview.",
    subjectLine: "A daily-trainer next step for the Matt Klein shoe episode",
    publicContactRoute: "strengthrunning.com/contact — no email stored.",
    contactName: "Jason Fitzgerald",
    contactRole: "coach",
    competitorGap: "Page features Doctors of Running (Matt Klein). Kitletics is a complementary public catalog, not a substitute review lab.",
  },
  {
    id: "irunfar-best-trail",
    name: "iRunFar",
    domain: "irunfar.com",
    homepageUrl: "https://www.irunfar.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Best trail shoes guide with buying advice, FAQs and testing methodology — already a resource hub.",
    type: "ROUNDUP_INCLUSION",
    url: "https://www.irunfar.com/best-trail-running-shoes",
    topic: "Best trail running shoes / how they test",
    relevance: 86,
    authority: 88,
    likelihood: 48,
    editorial: 92,
    relationship: 10,
    evidence: "Bryon Powell guide with methodology. High editorial quality; likelihood modest because they already own the roundup.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Buying-advice section discusses drop and cushioning; a road/trail spec catalog is a supporting dataset, not a competing trail roundup.",
    pitchOverride: "Cite the database as the current spec lookup beneath the buying-advice / methodology block.",
    subjectLine: "A current spec catalog under your trail-shoe buying advice",
    publicContactRoute: "irunfar.com/about or contact — no email stored.",
    contactName: "Bryon Powell",
    contactRole: "editor",
  },
  {
    id: "irunfar-index",
    name: "iRunFar trail shoe review index",
    domain: "irunfar.com",
    homepageUrl: "https://www.irunfar.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Explicit review index / brand directory — a resource page by design.",
    type: "RESOURCE_PAGE",
    url: "https://www.irunfar.com/trail-running-shoe-reviews",
    topic: "Trail running shoe review directory",
    relevance: 84,
    authority: 88,
    likelihood: 44,
    editorial: 90,
    relationship: 8,
    evidence: "Index of ~400 reviews. Supporting dataset only; do not pitch a competing trail Best-of.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The directory is reviews; a spec catalog is the missing cross-model lookup (weight/drop/stack) for models they have not re-reviewed this season.",
    pitchOverride: "Position the database as a spec sidecar to the review index, not a replacement for iRunFar tests.",
    subjectLine: "A spec sidecar for the trail shoe review index",
    publicContactRoute: "irunfar.com/about — no email stored.",
    contactName: "Bryon Powell",
    contactRole: "editor",
  },
  {
    id: "prorun-kies",
    name: "ProRun",
    domain: "prorun.nl",
    homepageUrl: "https://www.prorun.nl/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Dutch buying-advice article on choosing shoes (pronation, terrain, specialist shops).",
    type: "RESOURCE_PAGE",
    url: "https://www.prorun.nl/gadgets_gear/kies-de-juiste-schoen/",
    topic: "Kies de juiste hardloopschoen",
    relevance: 96,
    authority: 78,
    likelihood: 68,
    editorial: 82,
    relationship: 22,
    evidence: "Specific gadgets_gear education URL, not the homepage. NL primary market.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "The article sends people to specialist shops; a Dutch-usable finder plus catalog is the online next step.",
    pitchOverride: "Running Shoe Finder + database as the online vervolgstap after ‘kies de juiste schoen’.",
    subjectLine: "Een schoenkiezer naast jullie ‘Kies de juiste schoen’",
    publicContactRoute: "prorun.nl colofon / contact — no email stored.",
    contactRole: "running_editor",
  },
  {
    id: "prorun-advies",
    name: "ProRun shoe advice",
    domain: "prorun.nl",
    homepageUrl: "https://www.prorun.nl/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Advice piece that already discusses drop variation and shoe mixing.",
    type: "DATA_CITATION",
    url: "https://www.prorun.nl/gadgets_gear/een-advies-voor-de-aanschaf-van-de-beste-hardloopschoenen/",
    topic: "Advies aanschaf hardloopschoenen",
    relevance: 92,
    authority: 78,
    likelihood: 64,
    editorial: 80,
    relationship: 20,
    evidence: "Mentions drop variation when mixing shoes. Database is the lookup.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "They tell experienced runners to mix drop and cushioning; a current catalog makes that advice checkable.",
    pitchOverride: "Cite the database so readers can compare drop/stack/weight of the shoes they already rotate.",
    subjectLine: "Een actuele drop/stack-tabel bij jullie schoenadvies",
    publicContactRoute: "prorun.nl colofon — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "prorun-bas",
    name: "ProRun — Bas Stigter shoe video",
    domain: "prorun.nl",
    homepageUrl: "https://www.prorun.nl/",
    category: "RUNNING_MEDIA",
    mix: "journalist",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Named presenter (former specialty-store owner) teaching how to buy trainers.",
    type: "EXPERT_QUOTE",
    url: "https://www.prorun.nl/video/waar-let-je-op-bij-het-kopen-van-hardloopschoenen-tips-van-bas-stigter/",
    topic: "Waar let je op bij het kopen van hardloopschoenen",
    relevance: 90,
    authority: 78,
    likelihood: 60,
    editorial: 80,
    relationship: 18,
    evidence: "Public byline: Bas Stigter. No email stored. Video already is education intent.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Description box can point from the video to a durable written choose-shoes guide and finder.",
    pitchOverride: "How to Choose Running Shoes as the written companion to the Bas Stigter video.",
    subjectLine: "Een geschreven schoengids onder de video van Bas Stigter",
    publicContactRoute: "ProRun video page / colofon — no email stored.",
    contactName: "Bas Stigter",
    contactRole: "gear_editor",
  },
  {
    id: "runners-nl-drop",
    name: "Runners.nl",
    domain: "runners.nl",
    homepageUrl: "https://www.runners.nl/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Dedicated heeldrop explainer that already separates drop from stack height.",
    type: "DATA_CITATION",
    url: "https://www.runners.nl/nieuws/1307271/wat-is-een-heeldrop-hardlopen.html",
    topic: "Wat is een heeldrop?",
    relevance: 94,
    authority: 70,
    likelihood: 66,
    editorial: 80,
    relationship: 16,
    evidence: "NL education URL with explicit drop vs stack. High asset fit for database + drop guide.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The article explains the millimetres but cannot stay current as models change; the database can.",
    pitchOverride: "Live drop/stack/weight catalog as the lookup under ‘Wat is een heeldrop?’",
    subjectLine: "Een actuele heeldrop-tabel onder jullie explainer",
    publicContactRoute: "runners.nl contact/colofon — no email stored.",
    contactRole: "running_editor",
  },
  {
    id: "runners-nl-faq",
    name: "Runners.nl shoe FAQ",
    domain: "runners.nl",
    homepageUrl: "https://www.runners.nl/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "15-question FAQ covering drop, pronation, carbon plates — a resource page.",
    type: "RESOURCE_PAGE",
    url: "https://www.runners.nl/nieuws/1297668/hardloopschoenen-faq.html",
    topic: "Hardloopschoenen FAQ",
    relevance: 90,
    authority: 70,
    likelihood: 64,
    editorial: 78,
    relationship: 14,
    evidence: "FAQ already answers ‘what is drop’. Finder + choose-shoes is the decision layer.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "FAQ answers definitions; the finder helps the reader who still does not know which shoe to try.",
    pitchOverride: "Running Shoe Finder as the next step after the FAQ.",
    subjectLine: "Een schoenkiezer onder jullie hardloopschoenen-FAQ",
    publicContactRoute: "runners.nl contact — no email stored.",
    contactRole: "running_editor",
  },
  {
    id: "athletics-weekly-choose",
    name: "Athletics Weekly",
    domain: "athleticsweekly.com",
    homepageUrl: "https://athleticsweekly.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "Performance desk explainer that busts shoe jargon and sends people to specialist shops.",
    type: "RESOURCE_PAGE",
    url: "https://athleticsweekly.com/performance/how-to-choose-the-right-running-shoes-1039931423/",
    topic: "How to choose the right running shoes",
    relevance: 88,
    authority: 82,
    likelihood: 52,
    editorial: 86,
    relationship: 10,
    evidence: "UK athletics title with a genuine education URL.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "The piece already exists as further reading; Kitletics' guide is a durable companion with a finder attached.",
    pitchOverride: "How to Choose Running Shoes as a cited explainer; Finder for readers who want a shortlist.",
    subjectLine: "A durable choose-shoes companion to your AW footwear explainer",
    publicContactRoute: "athleticsweekly.com/contact — no email stored.",
    contactRole: "sports_editor",
  },
  {
    id: "rw-us-buy",
    name: "Runner's World",
    domain: "runnersworld.com",
    homepageUrl: "https://www.runnersworld.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Evergreen how-to-buy guide that already defines drop, midsole and gait.",
    type: "RESOURCE_PAGE",
    url: "https://www.runnersworld.com/gear/a20842305/how-to-buy-the-right-running-shoes/",
    topic: "How to buy the right running shoes",
    relevance: 90,
    authority: 94,
    likelihood: 28,
    editorial: 86,
    relationship: 6,
    evidence: "High authority, low likelihood without a source request. Do not guess an editor email.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Only as a supporting dataset/finder if a gear editor is updating the anatomy section — not a cold Best-of swap.",
    pitchOverride: "Database as the spec lookup inside the anatomy/drop section; never pitch the homepage.",
    subjectLine: "A current spec lookup for the RW how-to-buy anatomy section",
    publicContactRoute: "HARO / Qwoted / Featured or public masthead later — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "rw-us-best",
    name: "Runner's World Best Running Shoes",
    domain: "runnersworld.com",
    homepageUrl: "https://www.runnersworld.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Flagship 2026 best-shoes roundup with testing notes — roundup intent.",
    type: "ROUNDUP_INCLUSION",
    url: "https://www.runnersworld.com/gear/a19663621/best-running-shoes/",
    topic: "Best running shoes 2026",
    relevance: 82,
    authority: 94,
    likelihood: 22,
    editorial: 84,
    relationship: 4,
    evidence: "They already own the roundup. Kitletics Best Guide is a methodology-backed alternative cite only if they want an independent shortlist. Low likelihood.",
    campaignId: DB,
    recommendedAssetId: A_BEST,
    whyTheyMightLink: "Unlikely as a primary cite. If they add ‘further testing’ links, the database is the honest offer; Best Guide only for methodology comparison.",
    pitchOverride: "Do not ask to be listed. Offer the database as a public spec table their testers can check.",
    subjectLine: "A public spec table your shoe testers can check",
    publicContactRoute: "Source-request platforms — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "rw-uk-choose",
    name: "Runner's World UK",
    domain: "runnersworld.com",
    homepageUrl: "https://www.runnersworld.com/uk/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "UK choose-shoes guide covering types, drop and trail specs.",
    type: "RESOURCE_PAGE",
    url: "https://www.runnersworld.com/uk/gear/shoes/a60800005/how-to-choose-running-shoes/",
    topic: "How to choose running shoes (UK)",
    relevance: 86,
    authority: 90,
    likelihood: 26,
    editorial: 84,
    relationship: 4,
    evidence: "Same Hearst family as US RW. Treat as a separate desk, still no email.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Education URL already exists; Kitletics is a supporting how-to and finder if the UK desk updates further reading.",
    pitchOverride: "How to Choose Running Shoes as a supporting explainer, not a competing UK roundup.",
    subjectLine: "A supporting choose-shoes explainer for the RW UK guide",
    publicContactRoute: "RW UK masthead / source requests — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "trail-runner-tips",
    name: "Trail Runner",
    domain: "trailrunnermag.com",
    homepageUrl: "https://www.trailrunnermag.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Gear desk tips for picking trail shoes by terrain and lugs.",
    type: "RESOURCE_PAGE",
    url: "https://www.trailrunnermag.com/gear/shoes/tips-for-picking-your-next-trail-shoes/",
    topic: "Tips for picking trail shoes",
    relevance: 84,
    authority: 80,
    likelihood: 46,
    editorial: 84,
    relationship: 8,
    evidence: "Outside network trail title. Education URL, not homepage.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Terrain advice still leaves readers needing specs (drop/stack/weight) for models they already like on the road.",
    pitchOverride: "Database as the spec check when matching a trail shoe to a known road drop.",
    subjectLine: "A spec check when matching trail shoes to a road drop",
    publicContactRoute: "trailrunnermag.com/contact — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "womens-running-trail",
    name: "Women's Running",
    domain: "womensrunning.co.uk",
    homepageUrl: "https://www.womensrunning.co.uk/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "Trail-shoe roundup that includes a how-to-choose block (drop, lugs, fit).",
    type: "ROUNDUP_INCLUSION",
    url: "https://www.womensrunning.co.uk/gear/the-best-trail-running-shoes/",
    topic: "Best trail running shoes / how to choose",
    relevance: 80,
    authority: 72,
    likelihood: 50,
    editorial: 80,
    relationship: 10,
    evidence: "UK women’s running title with an embedded education section.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "How-to block can cite a durable choose-shoes guide; Finder for readers who are not trail-specific.",
    pitchOverride: "How to Choose Running Shoes as the education cite inside the how-to block.",
    subjectLine: "A choose-shoes explainer for your trail-shoe how-to block",
    publicContactRoute: "womensrunning.co.uk/contact — no email stored.",
    contactRole: "gear_editor",
  },
  {
    id: "morning-shakeout",
    name: "The Morning Shakeout",
    domain: "themorningshakeout.com",
    homepageUrl: "https://themorningshakeout.com/",
    category: "NEWSLETTERS",
    mix: "newsletter",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Independent running newsletter that already covers gear and industry context.",
    type: "NEWSLETTER",
    url: "https://themorningshakeout.com/about/",
    topic: "Running industry / gear notes",
    relevance: 84,
    authority: 72,
    likelihood: 58,
    editorial: 90,
    relationship: 16,
    evidence: "About page lists a public editorial inbox. Verified 2026-09-13 from themorningshakeout.com/about/.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Mario already writes industry notes; a current catalog is a one-line resource, not a roundup ask.",
    pitchOverride: "One-sentence resource: searchable current drop/stack/weight catalog, no account.",
    subjectLine: "A current running-shoe spec catalog you can mention once",
    publicContactRoute: "https://themorningshakeout.com/about/",
    contactName: "Mario Fraioli",
    contactRole: "newsletter_editor",
    contactEmail: "mario@themorningshakeout.com",
    contactSource: "https://themorningshakeout.com/about/",
    contactStatus: "CONFIRMED",
  },
  {
    id: "sweat-science",
    name: "Sweat Science (Alex Hutchinson)",
    domain: "sweatscience.substack.com",
    homepageUrl: "https://sweatscience.substack.com/",
    category: "DATA_RESEARCH",
    mix: "journalist",
    country: "CA",
    language: "en",
    market: "global",
    whyRelevant: "Science journalist already covering shoe comfort, supershoes and stack-limit debates.",
    type: "RESEARCH_CITATION",
    url: "https://sweatscience.substack.com/p/running-shoe-comfort-ketones-for",
    topic: "Running shoe comfort / supershoes",
    relevance: 82,
    authority: 88,
    likelihood: 40,
    editorial: 94,
    relationship: 8,
    evidence: "Public byline. Also writes for Outside and Canadian Running. No email stored.",
    campaignId: MKT,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "He cites studies; a transparent catalog with sample sizes is a methods-friendly supporting source when a column needs current market context.",
    pitchOverride: "Database + methodology, never a Best page. Market 2026 only when a URL exists.",
    subjectLine: "A documented running-shoe catalog (with coverage) for shoe-science columns",
    publicContactRoute: "Sweat Science Substack / Outside contributor page — no email stored.",
    contactName: "Alex Hutchinson",
    contactRole: "data_journalist",
  },
  {
    id: "wirecutter-shoes",
    name: "Wirecutter",
    domain: "nytimes.com",
    homepageUrl: "https://www.nytimes.com/wirecutter/",
    category: "MAINSTREAM_MEDIA",
    mix: "mainstream",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Best-running-shoes guide with an explicit how-we-tested method and drop criteria.",
    type: "ROUNDUP_INCLUSION",
    url: "https://www.nytimes.com/wirecutter/reviews/best-running-shoes/",
    topic: "Best running shoes / how Wirecutter tests",
    relevance: 88,
    authority: 96,
    likelihood: 24,
    editorial: 92,
    relationship: 4,
    evidence: "They already document drop ranges in selection criteria. High authority, hard desk. No email.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Scout-report / sources section sometimes cites specialist databases. Kitletics is a public spec table their researchers can check.",
    pitchOverride: "Offer the database as a public spec source for the scout report — not a request to replace their picks.",
    subjectLine: "A public spec table for Wirecutter’s running-shoe scout report",
    publicContactRoute: "Wirecutter contact / tips forms — no email stored.",
    contactRole: "commerce_editor",
  },
  {
    id: "wirecutter-carbon",
    name: "Wirecutter carbon-plate explainer",
    domain: "nytimes.com",
    homepageUrl: "https://www.nytimes.com/wirecutter/",
    category: "MAINSTREAM_MEDIA",
    mix: "mainstream",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Dedicated carbon-plate explainer — data/education intent.",
    type: "DATA_CITATION",
    url: "https://www.nytimes.com/wirecutter/reviews/carbon-plate-running-shoes/",
    topic: "Carbon-plate running shoes",
    relevance: 80,
    authority: 96,
    likelihood: 22,
    editorial: 90,
    relationship: 4,
    evidence: "Education URL. Carbon vs non-carbon study is planned — do not pitch unpublished numbers.",
    campaignId: MKT,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "If they update the explainer, a live catalog (plated flag + weight/price when computable) is the supporting table.",
    pitchOverride: "Live database now; carbon study only after a public URL.",
    subjectLine: "A current catalog (including plated models) for the carbon-plate explainer",
    publicContactRoute: "Wirecutter tips — no email stored.",
    contactRole: "commerce_editor",
  },
  {
    id: "rei-road",
    name: "REI Expert Advice",
    domain: "rei.com",
    homepageUrl: "https://www.rei.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Expert Advice how-to-choose running shoes — editorial resource on a retailer domain.",
    type: "RETAILER_RESOURCE",
    url: "https://www.rei.com/learn/expert-advice/running-shoes.html",
    topic: "How to choose running shoes",
    relevance: 86,
    authority: 90,
    likelihood: 38,
    editorial: 78,
    relationship: 8,
    evidence: "Learn/expert-advice URL, not a PDP. REVIEW for commercial intent. Pitch finder/guide only.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Further-reading / related-reading blocks already exist on REI Learn. Independent how-to + finder is a non-SKU cite.",
    pitchOverride: "How to Choose Running Shoes + Finder. Never a product PDP.",
    subjectLine: "An independent choose-shoes guide for REI Expert Advice further reading",
    publicContactRoute: "REI Learn / expert advice contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "rei-trail",
    name: "REI trail-shoe buying guide",
    domain: "rei.com",
    homepageUrl: "https://www.rei.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Trail-shoe Expert Advice page — resource intent on a retailer domain.",
    type: "RETAILER_RESOURCE",
    url: "https://www.rei.com/learn/expert-advice/trail-running-shoes.html",
    topic: "How to choose trail-running shoes",
    relevance: 78,
    authority: 90,
    likelihood: 34,
    editorial: 78,
    relationship: 6,
    evidence: "Same Learn programme. REVIEW commercial. Education URL is real.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Trail guide tells people to match drop to road shoes — the database is how they check the road drop they already own.",
    pitchOverride: "Database as the drop/stack lookup when matching trail to road.",
    subjectLine: "A drop lookup when matching trail shoes to a road rotation",
    publicContactRoute: "REI Learn — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "running-warehouse",
    name: "Running Warehouse Learning Center",
    domain: "runningwarehouse.com",
    homepageUrl: "https://www.runningwarehouse.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Specialty retailer with a genuine how-to-pick education article.",
    type: "RETAILER_RESOURCE",
    url: "https://www.runningwarehouse.com/learningcenter/gear_guides/footwear/how_to_pick_running_shoes.html",
    topic: "How to pick running shoes",
    relevance: 88,
    authority: 76,
    likelihood: 42,
    editorial: 70,
    relationship: 10,
    evidence: "Learning Center URL. REVIEW commercial. Strong education intent.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Learning Center already hosts guides; an independent finder is a non-SKU tool they can cite for readers still stuck after the article.",
    pitchOverride: "Running Shoe Finder as a decision tool, not a competing store.",
    subjectLine: "An independent shoe finder for the Learning Center",
    publicContactRoute: "runningwarehouse.com/contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "runners-need-choose",
    name: "Runners Need",
    domain: "runnersneed.com",
    homepageUrl: "https://www.runnersneed.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "Expert-advice choosing-shoes guide plus gait-analysis CTA.",
    type: "RETAILER_RESOURCE",
    url: "https://www.runnersneed.com/expert-advice/gear-guides/choosing-the-right-running-shoes.html",
    topic: "Choosing the right running shoes",
    relevance: 82,
    authority: 74,
    likelihood: 36,
    editorial: 68,
    relationship: 8,
    evidence: "UK specialty retail education URL. REVIEW. Pitch finder/guide only.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Further-reading on an education URL; Kitletics is independent of their gait-analysis SKU funnel.",
    pitchOverride: "How to Choose Running Shoes as an independent explainer.",
    subjectLine: "An independent choose-shoes explainer for your expert-advice guide",
    publicContactRoute: "runnersneed.com customer services — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "runners-need-marathon",
    name: "Runners Need marathon kit list",
    domain: "runnersneed.com",
    homepageUrl: "https://www.runnersneed.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "Marathon kit checklist that already specifies broken-in road shoes matched to gait.",
    type: "RETAILER_RESOURCE",
    url: "https://www.runnersneed.com/expert-advice/gear-guides/marathon-kit-list.html",
    topic: "Marathon kit list / race-day shoes",
    relevance: 80,
    authority: 74,
    likelihood: 40,
    editorial: 66,
    relationship: 8,
    evidence: "Classic ‘marathon equipment guide’ intent. Finder helps first-timers who are not in-store.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Kit list says match shoes to gait and never race in new shoes; the finder is the online narrowing step.",
    pitchOverride: "Running Shoe Finder for first-time marathoners reading the kit list remotely.",
    subjectLine: "A shoe finder for first-timers reading your marathon kit list",
    publicContactRoute: "runnersneed.com — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "zappos-drop",
    name: "Zappos drop explainer",
    domain: "zappos.com",
    homepageUrl: "https://www.zappos.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Retail education page devoted to heel-to-toe drop, quoting clinicians.",
    type: "RETAILER_RESOURCE",
    url: "https://www.zappos.com/c/what-is-heel-to-toe-drop",
    topic: "What heel-to-toe drop is",
    relevance: 86,
    authority: 84,
    likelihood: 32,
    editorial: 64,
    relationship: 6,
    evidence: "Education URL on a general retailer. REVIEW. Quotes Abby Douek / Beverly.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "Explainer needs a current millimetre lookup; Kitletics drop guide + database is independent of Zappos SKUs.",
    pitchOverride: "Drop guide + database as further reading, not a store link.",
    subjectLine: "A current drop lookup for the Zappos heel-to-toe explainer",
    publicContactRoute: "Zappos customer care — do not use for editorial. No email stored.",
    contactRole: "unknown",
  },
  {
    id: "tristate-stack",
    name: "Tri-State Outfitters",
    domain: "t-state.com",
    homepageUrl: "https://t-state.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Independent shop article explaining stack height vs heel drop with model examples.",
    type: "RETAILER_RESOURCE",
    url: "https://t-state.com/stack-height-and-heel-drop/",
    topic: "Stack height and heel drop",
    relevance: 88,
    authority: 48,
    likelihood: 70,
    editorial: 72,
    relationship: 18,
    evidence: "Specialty running retailer education post. Moderate authority, high relevance and likelihood.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "They already teach the specs; a live catalog is the national lookup their local article cannot maintain.",
    pitchOverride: "Database as the always-current spec table next to the explainer.",
    subjectLine: "A current stack/drop catalog beside your shop explainer",
    publicContactRoute: "t-state.com contact — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "cleveland-clinic",
    name: "Cleveland Clinic",
    domain: "health.clevelandclinic.org",
    homepageUrl: "https://health.clevelandclinic.org/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Hospital explainer on picking running shoes (fit, gait, drop, cushion).",
    type: "UNIVERSITY_RESEARCH",
    url: "https://health.clevelandclinic.org/how-to-pick-the-running-shoe-that-is-best-for-you",
    topic: "How to pick the running shoe that is best for you",
    relevance: 84,
    authority: 90,
    likelihood: 34,
    editorial: 86,
    relationship: 6,
    evidence: "Named clinician (Christina Schilero, DPM). Institutional likelihood modest. No email.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Further-reading on a patient explainer; Kitletics how-to-choose is consumer-facing and non-commercial enough if they allow external resources.",
    pitchOverride: "How to Choose Running Shoes as a patient-friendly next read. Never a Best-of.",
    subjectLine: "A patient-friendly choose-shoes guide to pair with the Clinic explainer",
    publicContactRoute: "Cleveland Clinic media / health.clevelandclinic.org — no email stored.",
    contactName: "Christina Schilero, DPM",
    contactRole: "unknown",
  },
  {
    id: "modpod-drop",
    name: "ModPod Podiatry",
    domain: "modpodpodiatry.com.au",
    homepageUrl: "https://www.modpodpodiatry.com.au/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "AU",
    language: "en",
    market: "AU",
    whyRelevant: "Clinic explainer dedicated to running-shoe drop / offset.",
    type: "UNIVERSITY_RESEARCH",
    url: "https://www.modpodpodiatry.com.au/running-shoe-drop-explained/",
    topic: "Running shoe drop explained",
    relevance: 90,
    authority: 52,
    likelihood: 68,
    editorial: 80,
    relationship: 14,
    evidence: "Clinical education URL. High relevance, modest authority.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Patients are told to match drop to injury history; a catalog lets them check the drop of shoes they already own.",
    pitchOverride: "Database as the millimetre lookup under the clinic explainer.",
    subjectLine: "A drop/stack lookup for patients reading your offset explainer",
    publicContactRoute: "Clinic contact form — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "velocirunning-drop",
    name: "Veloci Running",
    domain: "velocirunning.com",
    homepageUrl: "https://velocirunning.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Drop guide that already cites RunRepeat’s heel-to-toe-drop article as a source.",
    type: "COMPETITOR_LINK_GAP",
    url: "https://velocirunning.com/blogs/informational/running-shoe-heel-drop-guide",
    topic: "Running shoe heel drop guide",
    relevance: 93,
    authority: 50,
    likelihood: 74,
    editorial: 76,
    relationship: 16,
    evidence: "Footnotes cite RunRepeat ‘Heel to Toe Drop: The Ultimate Guide’. Confirmed competitor-gap page.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "They already cite a lab-data explainer. Kitletics is a current catalog of the same millimetres across the market, complementary to RunRepeat’s lab cuts.",
    pitchOverride: "Complementary public catalog: current models’ published drop/stack/weight, with coverage — not a claim to replace RunRepeat lab tests.",
    subjectLine: "A current drop catalog to sit beside your RunRepeat citation",
    publicContactRoute: "velocirunning.com/blogs contact — no email stored.",
    contactRole: "site_owner",
    competitorGap: "Cites RunRepeat (runrepeat.com/guides/heel-to-toe-drop) as source [3] in the heel-drop guide.",
  },
  {
    id: "michigan-foot",
    name: "Michigan Foot Doctors",
    domain: "michiganfootdoctors.com",
    homepageUrl: "https://www.michiganfootdoctors.com/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Podiatry explainer on maximalist vs minimalist stack and drop ranges.",
    type: "UNIVERSITY_RESEARCH",
    url: "https://www.michiganfootdoctors.com/maximalist-vs-minimalist-shoes-podiatrist/",
    topic: "Maximalist vs minimalist stack and drop",
    relevance: 82,
    authority: 54,
    likelihood: 60,
    editorial: 78,
    relationship: 10,
    evidence: "Clinical education. Database is the current market illustration of the millimetre ranges they quote.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The article quotes millimetre bands; a live catalog shows which current models sit in each band.",
    pitchOverride: "Database as the current-model illustration of maximalist vs minimalist ranges.",
    subjectLine: "Current models in the stack/drop bands your podiatry explainer describes",
    publicContactRoute: "Clinic contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "rrca-runners",
    name: "Road Runners Club of America",
    domain: "rrca.org",
    homepageUrl: "https://www.rrca.org/",
    category: "COMMUNITY",
    mix: "club",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "National club education page that already covers shoes (replace 300–500 miles, specialty store).",
    type: "RUNNING_CLUB",
    url: "https://www.rrca.org/education/for-runners/",
    topic: "For runners — getting started / shoes",
    relevance: 80,
    authority: 76,
    likelihood: 58,
    editorial: 72,
    relationship: 18,
    evidence: "Education/for-runners URL. Classic club-resource intent.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "The getting-started block is thin on how to choose a first shoe; Finder + how-to-choose is the missing tool for club newbies.",
    pitchOverride: "Running Shoe Finder + How to Choose Running Shoes for the For Runners education page.",
    subjectLine: "A first-shoe finder for RRCA’s For Runners page",
    publicContactRoute: "rrca.org/about / national office listing — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "runners-connect-race",
    name: "Runners Connect",
    domain: "runnersconnect.net",
    homepageUrl: "https://runnersconnect.net/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach interview on finding a race-day shoe — training-resource intent.",
    type: "COACH_RESOURCE",
    url: "https://runnersconnect.net/running-interviews/how-to-find-your-perfect-shoe-for-race-day/",
    topic: "How to find your perfect shoe for race day",
    relevance: 84,
    authority: 68,
    likelihood: 56,
    editorial: 80,
    relationship: 14,
    evidence: "Coaches Hayley and Alex publicly named on the episode page. No email stored.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Show notes argue comfort over marketing; Finder operationalises that for listeners.",
    pitchOverride: "Running Shoe Finder as the listener next step after the race-day shoe episode.",
    subjectLine: "A shoe finder for listeners of the race-day shoe episode",
    publicContactRoute: "runnersconnect.net/contact — no email stored.",
    contactRole: "coach",
  },
  {
    id: "canadian-shakeout-hutchinson",
    name: "Canadian Running Shakeout Podcast",
    domain: "runningmagazine.ca",
    homepageUrl: "https://runningmagazine.ca/",
    category: "PODCASTS",
    mix: "podcast",
    country: "CA",
    language: "en",
    market: "CA",
    whyRelevant: "Episode with Alex Hutchinson on the carbon-shoe revolution — data-story intent.",
    type: "PODCAST",
    url: "https://runningmagazine.ca/shakeout-podcast/the-shakeout-podcast-alex-hutchinson-breaks-down-the-carbon-shoe-revolution/",
    topic: "Carbon shoe revolution",
    relevance: 78,
    authority: 76,
    likelihood: 40,
    editorial: 86,
    relationship: 10,
    evidence: "Named hosts and guest. Complementary to Market 2026 when live; database now.",
    campaignId: MKT,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Show notes for a science-of-shoes episode can list a public catalog. Do not claim Market 2026 is published.",
    pitchOverride: "Database as a public spec source in carbon-shoe show notes.",
    subjectLine: "A public spec catalog for carbon-shoe episode notes",
    publicContactRoute: "runningmagazine.ca/contact — no email stored.",
    contactName: "Kate Van Buskirk",
    contactRole: "running_editor",
  },
  {
    id: "believe-methodology",
    name: "Believe in the Run — how reviews work",
    domain: "believeintherun.com",
    homepageUrl: "https://believeintherun.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Public methodology page. Competitor — use for gap import, not a ‘please link to us’ homepage ask.",
    competitor: true,
    type: "COMPETITOR_LINK_GAP",
    url: "https://believeintherun.com/how-our-reviews-work/",
    topic: "How BITR reviews work",
    relevance: 70,
    authority: 84,
    likelihood: 20,
    editorial: 82,
    relationship: 6,
    evidence: "Contact form at believeintherun.com/contact. Do not use shop info@ as editorial. Import their backlinks first.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Unlikely to cite a peer catalog. Value is the sites that already link here — import Ahrefs CSV.",
    pitchOverride: "Do not send a link ask. Import referring domains. If a methodology page wants a public spec table, the database is the offer.",
    subjectLine: "Not a send — import BITR backlinks first",
    publicContactRoute: "https://believeintherun.com/contact/ (form). No editorial email stored.",
    contactRole: "editor",
    competitorGap: "This domain is itself a competitor (Believe in the Run). Treat as gap-import source.",
    doNotSend: true,
  },
  {
    id: "dor-resources",
    name: "Doctors of Running resource hub",
    domain: "doctorsofrunning.com",
    homepageUrl: "https://www.doctorsofrunning.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Clinician resource hub (beginner guide, stability, carbon plates) — competitor peer.",
    competitor: true,
    type: "RESEARCH_CITATION",
    url: "https://www.doctorsofrunning.com/reviews/",
    topic: "Running shoe resource pages",
    relevance: 88,
    authority: 82,
    likelihood: 28,
    editorial: 92,
    relationship: 10,
    evidence: "Matt Klein publicly named via Strength Running interview. Do not invent an email. Import backlinks; optional peer dataset cite.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Their resource pages are reviews + clinical guides. A public spec catalog is complementary if they want a living table they do not maintain.",
    pitchOverride: "Peer offer: current catalog for stack/drop/weight. Import referring domains first.",
    subjectLine: "A public spec catalog that sits beside DoR resource pages (not a review replacement)",
    publicContactRoute: "doctorsofrunning.com contact — no email stored.",
    contactName: "Matt Klein",
    contactRole: "unknown",
    competitorGap: "Competitor. Sites that already link here are the real queue via CSV import.",
    doNotSend: true,
  },
  {
    id: "rtr-index",
    name: "Road Trail Run review index",
    domain: "roadtrailrun.com",
    homepageUrl: "https://www.roadtrailrun.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Brand-indexed multi-tester reviews with spec tables — competitor peer.",
    competitor: true,
    type: "DATABASE_CITATION",
    url: "https://www.roadtrailrun.com/p/blog-page.html",
    topic: "Road and trail shoe review index",
    relevance: 86,
    authority: 78,
    likelihood: 26,
    editorial: 88,
    relationship: 8,
    evidence: "Index URL. Import backlinks. Spec tables in individual reviews are the complementary-cite hook.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Reviews already list stack/drop/weight per shoe; a cross-market catalog is useful when a comparison roundup needs more than ten models.",
    pitchOverride: "Database as a wider-market spec table for comparison roundups.",
    subjectLine: "A wider-market spec table for RTR comparison roundups",
    publicContactRoute: "roadtrailrun.com about/contact — no email stored.",
    contactRole: "editor",
    competitorGap: "Competitor. Import referring domains. Individual comparison posts (e.g. super-trainer roundups) are the pitch surface.",
    doNotSend: true,
  },
  {
    id: "asics-nl-drop",
    name: "ASICS NL advice — what is drop",
    domain: "asics.com",
    homepageUrl: "https://www.asics.com/",
    category: "BRANDS",
    mix: "brand",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Brand education page that already explains drop vs stack for Dutch readers.",
    type: "BRAND_PR",
    url: "https://www.asics.com/nl/nl-nl/asics-advice/what-is-heel-drop/",
    topic: "Wat is drop?",
    relevance: 74,
    authority: 92,
    likelihood: 14,
    editorial: 60,
    relationship: 4,
    evidence: "Brand-owned advice. They will not usually cite a third-party catalog. REVIEW. Do not cold-email for a backlink.",
    campaignId: MKT,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Only if brand journalism/PR wants an independent market snapshot. Not a send this month.",
    pitchOverride: "Defer. Independent catalog is useful internally for PR, not as a footer link.",
    subjectLine: "Not a send — brand education page, no cold link ask",
    publicContactRoute: "ASICS press / advice pages — no email stored.",
    contactRole: "pr_contact",
    doNotSend: true,
  },
  {
    id: "nike-pick",
    name: "Nike — how to pick running shoes",
    domain: "nike.com",
    homepageUrl: "https://www.nike.com/",
    category: "BRANDS",
    mix: "brand",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Brand education article that already quotes coach Jason Fitzgerald.",
    type: "BRAND_PR",
    url: "https://www.nike.com/a/how-to-pick-the-right-running-shoes",
    topic: "How to pick the right running shoes",
    relevance: 70,
    authority: 98,
    likelihood: 10,
    editorial: 58,
    relationship: 4,
    evidence: "Quotes Strength Running’s Jason Fitzgerald. Brand page will not cite a competitor catalog. Watchlist only.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "They already cite a coach. Unlikely to add Kitletics. Do not cold-email Nike.com for a link.",
    pitchOverride: "Do not send. Note the Fitzgerald quote as a relationship signal toward Strength Running, not Nike.",
    subjectLine: "Not a send",
    publicContactRoute: "Nike media — no email stored.",
    contactRole: "pr_contact",
    competitorGap: "Cites Strength Running / Jason Fitzgerald. The coach page is the real prospect.",
    doNotSend: true,
  },
  {
    id: "rw-warehouse-drop",
    name: "Running Warehouse — offsets explained",
    domain: "runningwarehouse.com",
    homepageUrl: "https://www.runningwarehouse.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Learning Center already defines heel-to-toe drop ranges and tells readers to calculate heel minus forefoot.",
    type: "DATA_CITATION",
    url: "https://www.runningwarehouse.com/learningcenter/gear_guides/footwear/heel-toe-drop.html",
    topic: "Running shoe offsets / heel-to-toe drop",
    relevance: 94,
    authority: 76,
    likelihood: 48,
    editorial: 74,
    relationship: 12,
    evidence: "Dedicated offset explainer. REVIEW commercial. Strong spec-link intent.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "The page tells people to subtract heel and forefoot heights; a current catalog is that lookup.",
    pitchOverride: "Database as the live heel/forefoot/drop table the Learning Center article currently asks readers to assemble by hand.",
    subjectLine: "A live drop/stack table for the Running Warehouse offset explainer",
    publicContactRoute: "runningwarehouse.com/contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "fleet-feet-drop",
    name: "Fleet Feet — heel-to-toe drop",
    domain: "fleetfeet.com",
    homepageUrl: "https://www.fleetfeet.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Specialty-store education article that already defines drop and injury-history trade-offs.",
    type: "RETAILER_RESOURCE",
    url: "https://www.fleetfeet.com/blog/what-is-heel-to-toe-drop-and-why-does-it-matter",
    topic: "What is heel-to-toe drop",
    relevance: 90,
    authority: 80,
    likelihood: 40,
    editorial: 72,
    relationship: 10,
    evidence: "Named outfitter Dewey quoted on-page. REVIEW commercial. Education URL, not a homepage.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "Readers still leave the article without a way to look up current model drop numbers.",
    pitchOverride: "Drop guide + database as the lookup after the explainer. Independent, not a competing store.",
    subjectLine: "A drop lookup to sit under the Fleet Feet heel-to-toe explainer",
    publicContactRoute: "fleetfeet.com/contact or store education desk — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "fleet-feet-anatomy",
    name: "Fleet Feet — running shoe anatomy",
    domain: "fleetfeet.com",
    homepageUrl: "https://www.fleetfeet.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Anatomy explainer already defines stack vs drop for shoppers.",
    type: "RETAILER_RESOURCE",
    url: "https://www.fleetfeet.com/blog/running-shoe-anatomy-6-parts-that-shape-comfort-and-performance",
    topic: "Running shoe anatomy — stack and drop",
    relevance: 86,
    authority: 80,
    likelihood: 38,
    editorial: 70,
    relationship: 10,
    evidence: "Education article with stack/drop definitions. REVIEW. Second Fleet Feet page — one owner for outreach.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "Anatomy pages often end in a store CTA; an independent how-to-choose page is a complementary education cite.",
    pitchOverride: "How to Choose Running Shoes as the non-SKU explainer after anatomy.",
    subjectLine: "A choose-shoes explainer to pair with your anatomy guide",
    publicContactRoute: "fleetfeet.com/contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "marathon-sports-101",
    name: "Marathon Sports — Running Shoes 101",
    domain: "marathonsports.com",
    homepageUrl: "https://www.marathonsports.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Specialty retailer already publishes a drop-range buying guide (low / moderate / high).",
    type: "RETAILER_RESOURCE",
    url: "https://www.marathonsports.com/blog/running-shoes-101-your-guide-to-choosing-running-shoes",
    topic: "Running shoes 101 / drop ranges",
    relevance: 88,
    authority: 70,
    likelihood: 44,
    editorial: 72,
    relationship: 12,
    evidence: "Guide defines 1–4 / 5–8 / 9+ mm drop with beginner advice. REVIEW commercial.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "The article still sends people into the store; Finder helps remote readers shortlist before a gait analysis.",
    pitchOverride: "Running Shoe Finder as a pre-visit shortlist, not a replacement for their fitting.",
    subjectLine: "A pre-visit shoe finder for the Running Shoes 101 page",
    publicContactRoute: "marathonsports.com contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "de-hardloopwinkel-beginners",
    name: "De Hardloopwinkel — schoenen voor beginners",
    domain: "dehardloopwinkel.nl",
    homepageUrl: "https://www.dehardloopwinkel.nl/",
    category: "RETAILERS",
    mix: "retailer",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "NL specialist store with a genuine beginner-shoe education article.",
    type: "RETAILER_RESOURCE",
    url: "https://www.dehardloopwinkel.nl/blog/hardloopschoenen-voor-beginners/",
    topic: "Hardloopschoenen voor beginners",
    relevance: 90,
    authority: 62,
    likelihood: 50,
    editorial: 68,
    relationship: 16,
    evidence: "Beginner education URL naming daily-trainer archetypes (Ghost, Cumulus, Ride, 880). REVIEW commercial. NL-first.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Beginners still leave the article needing a way to match job (easy miles vs race). Finder is that filter.",
    pitchOverride: "Nederlandse schoenkiezer naast het beginner-artikel — geen webshop-concurrentie-pitch.",
    subjectLine: "Een onafhankelijke schoenkiezer bij jullie beginner-gids",
    publicContactRoute: "dehardloopwinkel.nl contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "triathlon24-tips",
    name: "Triathlon24 — schoenen kiezen",
    domain: "triathlon24.nl",
    homepageUrl: "https://www.triathlon24.nl/",
    category: "RETAILERS",
    mix: "retailer",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "NL education post already explains stack height vs drop for buyers.",
    type: "RETAILER_RESOURCE",
    url: "https://www.triathlon24.nl/blog/7-handige-tips-om-de-juiste-hardloopschoenen-te-kiezen/",
    topic: "Stack height en drop bij hardloopschoenen",
    relevance: 86,
    authority: 58,
    likelihood: 46,
    editorial: 66,
    relationship: 12,
    evidence: "Seven-tip guide with dedicated stack and drop sections. REVIEW. Strong spec-education intent.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Defines the terms but does not offer a current model table.",
    pitchOverride: "Database as the live stack/drop lookup after the definitions.",
    subjectLine: "Een actuele drop/stack-tabel bij jullie schoenen-tips",
    publicContactRoute: "triathlon24.nl contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "runners-nl-marathon",
    name: "Runners.nl — marathonschoenen",
    domain: "runners.nl",
    homepageUrl: "https://www.runners.nl/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "NL",
    language: "nl",
    market: "NL",
    whyRelevant: "Already publishes a marathon-shoe decision article citing comfort research.",
    type: "RESOURCE_PAGE",
    url: "https://www.runners.nl/nieuws/marathonschoenen-bepalen",
    topic: "Hoe bepaal je de juiste schoenen voor een marathon",
    relevance: 88,
    authority: 72,
    likelihood: 52,
    editorial: 78,
    relationship: 14,
    evidence: "Education article, not a homepage. Complements the existing heeldrop and FAQ rows. One NL owner for outreach.",
    campaignId: FINDER,
    recommendedAssetId: A_DAILY,
    whyTheyMightLink: "The piece warns against racing in an untested carbon shoe; Best Daily Trainers is the training-shoe counterpart.",
    pitchOverride: "Daily trainers guide for the ‘do not race in an untested shoe’ section.",
    subjectLine: "Een daily-trainer gids bij jullie marathonschoen-artikel",
    publicContactRoute: "runners.nl redactie / contact — no email stored.",
    contactRole: "editor",
  },
  {
    id: "cadence-drop",
    name: "Cadence — heel drop explained",
    domain: "run-cadence.com",
    homepageUrl: "https://www.run-cadence.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach-facing explainer that already resists overinterpreting drop and still needs current numbers.",
    type: "COACH_RESOURCE",
    url: "https://www.run-cadence.com/blog/heel-drop-explained-how-shoe-drop-affects-your-running-form-and-performance",
    topic: "Heel drop explained for coaches and athletes",
    relevance: 90,
    authority: 58,
    likelihood: 56,
    editorial: 82,
    relationship: 14,
    evidence: "Long-form education with drop ranges and ‘how to choose’ questions. Not a brand SKU page.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "The guide tells athletes to check current drop, not to chase a number. Database is that check.",
    pitchOverride: "Drop guide + live catalog as the lookup the article currently leaves to the reader.",
    subjectLine: "A current drop catalog beside your heel-drop explainer",
    publicContactRoute: "run-cadence.com/contact — no email stored.",
    contactRole: "coach",
  },
  {
    id: "nextgait-drop",
    name: "NextGait — heel drop explained",
    domain: "nextgait.com",
    homepageUrl: "https://nextgait.com/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "Clinical gait-education page with situation-to-drop tables (new runner, Achilles, knee).",
    type: "UNIVERSITY_RESEARCH",
    url: "https://nextgait.com/heel-drop-explained-for-runners/",
    topic: "Heel drop explained for runners",
    relevance: 92,
    authority: 60,
    likelihood: 54,
    editorial: 84,
    relationship: 12,
    evidence: "Clinic education URL with explicit drop ranges. Natural database companion.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Tables tell patients which drop range to start in; they still need current models in that range.",
    pitchOverride: "Database filtered by drop as the living table next to the clinical ranges.",
    subjectLine: "A searchable drop catalog for the NextGait heel-drop tables",
    publicContactRoute: "nextgait.com contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "shoefitlab-2026",
    name: "ShoeFitLab — 2026 heel-drop study",
    domain: "shoefitlab.com",
    homepageUrl: "https://shoefitlab.com/",
    category: "DATA_RESEARCH",
    mix: "research",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Already published a 279-shoe drop/stack market snapshot — demonstrated data-citation intent.",
    type: "DATABASE_CITATION",
    url: "https://shoefitlab.com/blog/heel-drop-stack-height-study-2026",
    topic: "State of heel drop 2026",
    relevance: 94,
    authority: 64,
    likelihood: 50,
    editorial: 86,
    relationship: 16,
    evidence: "Original catalog analysis (279 models, average 8.1 mm drop). Complementary public table, not a guest post.",
    campaignId: MKT,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "They already do market math; Kitletics is a current, regional-price catalog they can cite when a figure needs a living source. Do not pitch unpublished Market 2026 numbers.",
    pitchOverride: "Live database as a second public table for readers who want to inspect the current catalog, not a competing study claim.",
    subjectLine: "A public spec catalog to sit beside your 2026 drop/stack snapshot",
    publicContactRoute: "shoefitlab.com contact / about — no email stored.",
    contactRole: "data_journalist",
  },
  {
    id: "guardian-uk-best",
    name: "The Guardian — best running shoes UK",
    domain: "theguardian.com",
    homepageUrl: "https://www.theguardian.com/",
    category: "MAINSTREAM_MEDIA",
    mix: "mainstream",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "2026 Filter roundup already lists drop and weight per pick — commerce desk with spec intent.",
    type: "ROUNDUP_INCLUSION",
    url: "https://www.theguardian.com/thefilter/2026/apr/24/best-running-shoes-men-women-uk-tested",
    topic: "Best running shoes UK 2026",
    relevance: 78,
    authority: 94,
    likelihood: 22,
    editorial: 86,
    relationship: 6,
    evidence: "24 Apr 2026 Filter piece lists drop per shoe. High authority, modest likelihood. Pitch database as methodology support, not a Best-of swap.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Roundup already publishes drop; a public catalog is the ‘how we checked specs’ cite.",
    pitchOverride: "Database as the spec-check source under the methodology, never a competing Top 10.",
    subjectLine: "A public spec catalog if The Filter wants a living drop/weight source",
    publicContactRoute: "Guardian Filter / source-request platforms — no email stored.",
    contactRole: "commerce_editor",
  },
  {
    id: "guardian-us-womens",
    name: "The Guardian US — women’s running shoes",
    domain: "theguardian.com",
    homepageUrl: "https://www.theguardian.com/",
    category: "MAINSTREAM_MEDIA",
    mix: "mainstream",
    country: "US",
    language: "en",
    market: "US",
    whyRelevant: "2026 US Filter test already publishes heel/toe stack and drop per model.",
    type: "DATA_CITATION",
    url: "https://www.theguardian.com/thefilter-us/2026/aug/23/best-womens-trail-road-running-shoes",
    topic: "Best women’s road and trail shoes 2026",
    relevance: 80,
    authority: 94,
    likelihood: 20,
    editorial: 86,
    relationship: 6,
    evidence: "23 Aug 2026. Explicit stack and drop fields. Same desk as UK Filter — one outreach owner.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "They already treat stack/drop as required fields; a living catalog is the update path between tests.",
    pitchOverride: "Database as the living spec table between annual Filter tests.",
    subjectLine: "A living stack/drop table between Filter shoe tests",
    publicContactRoute: "Guardian Filter US — no email stored.",
    contactRole: "commerce_editor",
  },
  {
    id: "trainingpeaks-shoe",
    name: "TrainingPeaks — find your perfect shoe",
    domain: "trainingpeaks.com",
    homepageUrl: "https://www.trainingpeaks.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach platform already publishes a drop-rotation education article.",
    type: "COACH_RESOURCE",
    url: "https://www.trainingpeaks.com/blog/how-to-find-your-perfect-running-shoe/",
    topic: "How to find your perfect running shoe",
    relevance: 88,
    authority: 82,
    likelihood: 48,
    editorial: 80,
    relationship: 12,
    evidence: "Lexi Miller byline. Article already advises matching drop to session type.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Coaches reading TrainingPeaks still need a way to shortlist daily vs workout shoes for athletes.",
    pitchOverride: "Finder as the athlete-facing shortlist; database if they want drop numbers.",
    subjectLine: "A shoe finder coaches can send athletes after your perfect-shoe article",
    publicContactRoute: "trainingpeaks.com/blog contact / author page — no email stored.",
    contactName: "Lexi Miller",
    contactRole: "coach",
  },
  {
    id: "mcmillan-supershoes",
    name: "McMillan Running — super shoes",
    domain: "mcmillanrunning.com",
    homepageUrl: "https://www.mcmillanrunning.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach education page that already separates super racers from super trainers.",
    type: "COACH_RESOURCE",
    url: "https://www.mcmillanrunning.com/super-shoes/",
    topic: "Should you wear super shoes",
    relevance: 84,
    authority: 76,
    likelihood: 50,
    editorial: 82,
    relationship: 14,
    evidence: "Greg McMillan named. Distinguishes race super shoes vs daily trainers — Best Daily Trainers / Finder fit.",
    campaignId: FINDER,
    recommendedAssetId: A_DAILY,
    whyTheyMightLink: "Athletes still ask ‘what do I wear on easy days’; Best Daily Trainers answers without pushing a plated shoe.",
    pitchOverride: "Best Daily Trainers as the easy-day counterpart to the super-shoe article.",
    subjectLine: "A daily-trainer guide to sit next to your super-shoe advice",
    publicContactRoute: "mcmillanrunning.com contact — no email stored.",
    contactName: "Greg McMillan",
    contactRole: "coach",
  },
  {
    id: "laura-norris-rotation",
    name: "Laura Norris — shoe rotation",
    domain: "lauranorrisrunning.com",
    homepageUrl: "https://lauranorrisrunning.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach article already tells runners to keep drop in the same range across a rotation.",
    type: "COACH_RESOURCE",
    url: "https://lauranorrisrunning.com/running-shoe-rotation/",
    topic: "How to build a running shoe rotation",
    relevance: 92,
    authority: 66,
    likelihood: 60,
    editorial: 88,
    relationship: 16,
    evidence: "30 Jul 2024. Explicit drop-range classes (low / medium / high). Database is the lookup.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Readers are told to match drop across pairs but are not given a current catalog.",
    pitchOverride: "Database as the drop/stack lookup when building a two- or three-shoe rotation.",
    subjectLine: "A drop catalog for the shoe-rotation article",
    publicContactRoute: "lauranorrisrunning.com / Stride Science about — no email stored.",
    contactName: "Laura Norris",
    contactRole: "coach",
  },
  {
    id: "laura-norris-switch",
    name: "Laura Norris — switching models",
    domain: "lauranorrisrunning.com",
    homepageUrl: "https://lauranorrisrunning.com/",
    category: "FITNESS_MEDIA",
    mix: "coach",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Coach page already advises matching stability, drop and cushion when a favorite is discontinued.",
    type: "COACH_RESOURCE",
    url: "https://lauranorrisrunning.com/switch-new-pair-running-shoes/",
    topic: "How to find a new model of running shoes",
    relevance: 88,
    authority: 66,
    likelihood: 56,
    editorial: 86,
    relationship: 16,
    evidence: "Education URL. Complements the rotation article. One owner for outreach.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "When a model dies, Finder + database is how athletes stay in the same drop/cushion band.",
    pitchOverride: "Finder for ‘my shoe was discontinued’ — match drop and job, not a random replacement.",
    subjectLine: "A shoe finder for the discontinued-model article",
    publicContactRoute: "lauranorrisrunning.com — no email stored.",
    contactName: "Laura Norris",
    contactRole: "coach",
  },
  {
    id: "stride-science",
    name: "Stride Science (Laura Norris)",
    domain: "lauranorrisrunning.substack.com",
    homepageUrl: "https://lauranorrisrunning.substack.com/",
    category: "NEWSLETTERS",
    mix: "newsletter",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Evidence-based running newsletter from a coach who already writes shoe-rotation and drop guidance.",
    type: "NEWSLETTER",
    url: "https://lauranorrisrunning.substack.com/about",
    topic: "Evidence-based running / footwear loading",
    relevance: 80,
    authority: 64,
    likelihood: 52,
    editorial: 88,
    relationship: 14,
    evidence: "About page confirms the newsletter and points to lauranorrisrunning.com. No email published there — do not invent one.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Newsletter issues that mention drop or rotation can footnote a public catalog.",
    pitchOverride: "One-line resource for a footwear issue: current drop/stack catalog, no account.",
    subjectLine: "A public spec catalog if a Stride Science issue covers drop or rotation",
    publicContactRoute: "https://lauranorrisrunning.substack.com/about — no email stored.",
    contactName: "Laura Norris",
    contactRole: "newsletter_editor",
  },
  {
    id: "tread-lightly-shoes",
    name: "Tread Lightly Podcast — shoe jargon",
    domain: "lauranorrisrunning.com",
    homepageUrl: "https://lauranorrisrunning.com/",
    category: "PODCASTS",
    mix: "podcast",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Episode already explains carbon vs nylon plates, heel drop and stack jargon.",
    type: "PODCAST",
    url: "https://lauranorrisrunning.com/tread-lightly-podcast/",
    topic: "Running shoe specs explained (podcast)",
    relevance: 86,
    authority: 64,
    likelihood: 48,
    editorial: 84,
    relationship: 14,
    evidence: "Show index lists ‘Cutting through the Running Shoe BS — Carbon vs Nylon Plates, Heel Drop’. Show-notes resource intent.",
    campaignId: DB,
    recommendedAssetId: A_DB,
    whyTheyMightLink: "Show notes for a jargon episode are the natural place for a public spec catalog.",
    pitchOverride: "Database as the one resource in shoe-jargon show notes. Do not ask for a spoken ad.",
    subjectLine: "A spec catalog for the Tread Lightly shoe-jargon episode notes",
    publicContactRoute: "lauranorrisrunning.com/tread-lightly-podcast — no email stored.",
    contactName: "Laura Norris",
    contactRole: "coach",
  },
  {
    id: "slowtwitch-beginner",
    name: "Slowtwitch — beginner running shoes",
    domain: "slowtwitch.com",
    homepageUrl: "https://slowtwitch.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Triathlon publication already hosts a beginner running-shoe education article.",
    type: "RESOURCE_PAGE",
    url: "https://slowtwitch.com/running/a-beginners-guide-to-finding-the-perfect-running-shoe/",
    topic: "Beginner’s guide to finding the perfect running shoe",
    relevance: 82,
    authority: 74,
    likelihood: 46,
    editorial: 76,
    relationship: 10,
    evidence: "Education URL covering job, gait and shop fitting. Finder is the remote shortlist.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Triathletes still guess between daily trainers and race shoes; Finder forces the job question.",
    pitchOverride: "Finder as the shortlist before the run-shop visit the article already recommends.",
    subjectLine: "A running-shoe finder for the Slowtwitch beginner guide",
    publicContactRoute: "slowtwitch.com contact — no email stored.",
    contactRole: "editor",
  },
  {
    id: "runners-cove-choose",
    name: "Runners Cove — how to choose",
    domain: "runnerscove.com",
    homepageUrl: "https://runnerscove.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Already teaches stack vs drop with concrete model examples.",
    type: "RESOURCE_PAGE",
    url: "https://runnerscove.com/running-tips/how-to-choose-running-shoes/",
    topic: "How to choose the right running shoes",
    relevance: 86,
    authority: 54,
    likelihood: 52,
    editorial: 74,
    relationship: 12,
    evidence: "Education article distinguishing high stack vs low drop, with daily-trainer examples.",
    campaignId: FINDER,
    recommendedAssetId: A_CHOOSE,
    whyTheyMightLink: "The how-to still needs a current catalog when examples age out.",
    pitchOverride: "How to Choose Running Shoes + database as the living companion.",
    subjectLine: "A current choose-shoes companion for the Runners Cove guide",
    publicContactRoute: "runnerscove.com contact — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "runkituk-choose",
    name: "Run Kit UK — how to choose",
    domain: "runkituk.co.uk",
    homepageUrl: "https://runkituk.co.uk/",
    category: "FITNESS_MEDIA",
    mix: "publication",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "UK beginner/education site already publishes a how-to-choose running-shoe page.",
    type: "RESOURCE_PAGE",
    url: "https://runkituk.co.uk/how-to-choose-the-right-running-shoes/",
    topic: "How to choose the right running shoes",
    relevance: 84,
    authority: 50,
    likelihood: 54,
    editorial: 72,
    relationship: 12,
    evidence: "Education URL; points readers to specialist shops. Finder is the pre-shop filter.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Beginner UK readers still arrive overwhelmed; Finder matches the article’s ‘you probably do not need a carbon plate’ message.",
    pitchOverride: "Finder as the decision tool after the how-to, before the shop visit.",
    subjectLine: "A shoe finder to pair with your how-to-choose page",
    publicContactRoute: "runkituk.co.uk contact — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "boreal-choose",
    name: "Boréal Running — how to choose",
    domain: "borealrunning.com",
    homepageUrl: "https://borealrunning.com/",
    category: "RETAILERS",
    mix: "retailer",
    country: "CA",
    language: "en",
    market: "CA",
    whyRelevant: "Specialty retailer buying guide already walks gait, surface and cushioning.",
    type: "RETAILER_RESOURCE",
    url: "https://borealrunning.com/en/blogs/running-shoe-buying-guide/how-to-choose-running-shoes",
    topic: "How to choose running shoes",
    relevance: 82,
    authority: 52,
    likelihood: 42,
    editorial: 70,
    relationship: 10,
    evidence: "27 Jan 2026 buying guide. REVIEW commercial. Education intent is real.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Guide ends at the store; Finder helps remote Canadian readers shortlist daily trainers.",
    pitchOverride: "Finder as a pre-visit tool. Independent, not a competing cart.",
    subjectLine: "An independent shoe finder for the Boréal buying guide",
    publicContactRoute: "borealrunning.com contact — no email stored.",
    contactRole: "unknown",
  },
  {
    id: "correrjuntos-drop",
    name: "CorrerJuntos — drop explained",
    domain: "correrjuntos.com",
    homepageUrl: "https://www.correrjuntos.com/",
    category: "RUNNING_MEDIA",
    mix: "publication",
    country: "ES",
    language: "en",
    market: "EU",
    whyRelevant: "Education article already separates drop from cushioning and names Altra vs Brooks geometry.",
    type: "DATA_CITATION",
    url: "https://www.correrjuntos.com/blog/en/running-shoe-drop-explained",
    topic: "Running shoe drop explained",
    relevance: 84,
    authority: 52,
    likelihood: 48,
    editorial: 74,
    relationship: 10,
    evidence: "English-language drop explainer on an EU running site. Database is the current-number companion.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "Defines drop ranges but has no living catalog.",
    pitchOverride: "Drop guide + database as the lookup after the definitions.",
    subjectLine: "A live drop catalog for the CorrerJuntos explainer",
    publicContactRoute: "correrjuntos.com contact — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "altra-zero-drop",
    name: "Altra — zero-to-low drop explainer",
    domain: "altrarunning.com",
    homepageUrl: "https://www.altrarunning.com/",
    category: "BRANDS",
    mix: "brand",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Brand education on zero-to-low drop with clinical transition advice.",
    type: "BRAND_PR",
    url: "https://www.altrarunning.com/en-us/blogs/run-better-blog/gait-happens-zero-to-low-drop",
    topic: "Zero-to-low drop footwear",
    relevance: 72,
    authority: 86,
    likelihood: 12,
    editorial: 62,
    relationship: 4,
    evidence: "Brand blog. Will not usually cite a third-party catalog. Watchlist / relationship signal only.",
    campaignId: DB,
    recommendedAssetId: A_DROP,
    whyTheyMightLink: "Only if brand journalism wants an independent catalog of current zero/low-drop models. Not a send.",
    pitchOverride: "Defer. Do not cold-email Altra for a backlink.",
    subjectLine: "Not a send — brand education page",
    publicContactRoute: "Altra press — no email stored.",
    contactRole: "pr_contact",
    doNotSend: true,
  },
  {
    id: "running4beginners-parkrun",
    name: "Running for Beginners — first parkrun",
    domain: "running4beginners.co.uk",
    homepageUrl: "https://running4beginners.co.uk/",
    category: "COMMUNITY",
    mix: "club",
    country: "GB",
    language: "en",
    market: "UK",
    whyRelevant: "Community beginner guide that already tells first-timers to get fitted for running shoes.",
    type: "RUNNING_CLUB",
    url: "https://running4beginners.co.uk/first-parkrun-what-to-expect/",
    topic: "First parkrun kit / shoes",
    relevance: 76,
    authority: 48,
    likelihood: 50,
    editorial: 70,
    relationship: 14,
    evidence: "Community education URL. Shoe intent is present but secondary to event logistics — honest club-mix row.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "The page says specialist fitting matters; Finder is the remote first pass before a shop.",
    pitchOverride: "Finder for first-timers who are not ready for a plated shoe. Usefulness, not a parkrun homepage dump.",
    subjectLine: "A beginner shoe finder for the first-parkrun guide",
    publicContactRoute: "running4beginners.co.uk contact — no email stored.",
    contactRole: "site_owner",
  },
  {
    id: "strength-running-podcast",
    name: "Strength Running Podcast",
    domain: "strengthrunning.com",
    homepageUrl: "https://strengthrunning.com/",
    category: "PODCASTS",
    mix: "podcast",
    country: "US",
    language: "en",
    market: "global",
    whyRelevant: "Jason Fitzgerald already writes shoe-choice explainers; the podcast is the audio surface for the same audience.",
    type: "PODCAST",
    url: "https://strengthrunning.com/about/",
    topic: "Coaching / gear episodes",
    relevance: 78,
    authority: 72,
    likelihood: 42,
    editorial: 84,
    relationship: 16,
    evidence: "About page confirms the podcast. Prefer pitching against a named shoe episode; this row exists so mix is honest. Contact unknown.",
    campaignId: FINDER,
    recommendedAssetId: A_FIND,
    whyTheyMightLink: "Show notes for a shoe or injury episode can list Finder + How to Choose. Do not spray a generic podcast ask.",
    pitchOverride: "Use only with a named episode. Same owner as the Strength Running articles.",
    subjectLine: "A shoe finder for a Strength Running episode on easy-day shoes",
    publicContactRoute: "strengthrunning.com/about — no email stored.",
    contactName: "Jason Fitzgerald",
    contactRole: "coach",
  },
]
