import type { Product } from "@/domain/products/types";
import type { Brand } from "@/domain/products/types";
import type { ProductCategory } from "@/domain/sports/types";
import type { BestGuide, BuyingGuide, Comparison, GearSetup } from "@/domain/editorial/types";
import type { Tool } from "@/domain/tools/types";
import type { Offer } from "@/domain/commerce/types";
import { publishedMeta } from "@/content/config";

const pub = publishedMeta();

export const padelSportId = "sport-padel" as const;

export const padelCategories: ProductCategory[] = [
  {
    id: "cat-padel-rackets",
    name: "Padel Rackets",
    slug: "padel-rackets",
    pathSegment: "rackets",
    icon: "CircleDot",
    description: "Control, power and hybrid padel rackets.",
    sportIds: [padelSportId],
    sortOrder: 10,
    seoTitle: "Padel Rackets: Compare Control, Power & Hybrid Frames",
    seoDescription:
      "Compare padel rackets by shape, balance and play style. Browse Kitletics shortlists or use the Padel Racket Finder.",
    ...pub,
  },
  {
    id: "cat-padel-shoes",
    name: "Padel Shoes",
    slug: "padel-shoes",
    pathSegment: "shoes",
    icon: "Footprints",
    description: "Court shoes built for padel movement and grip.",
    sportIds: [padelSportId],
    sortOrder: 20,
    ...pub,
  },
  {
    id: "cat-padel-bags",
    name: "Padel Bags",
    slug: "padel-bags",
    pathSegment: "bags",
    icon: "Briefcase",
    description: "Racket bags and court packs.",
    sportIds: [padelSportId],
    sortOrder: 30,
    ...pub,
  },
  {
    id: "cat-padel-balls",
    name: "Padel Balls",
    slug: "padel-balls",
    pathSegment: "balls",
    icon: "Circle",
    description: "Official and training padel balls.",
    sportIds: [padelSportId],
    sortOrder: 40,
    ...pub,
  },
  {
    id: "cat-padel-grips",
    name: "Grips & Overgrips",
    slug: "padel-grips",
    pathSegment: "grips",
    icon: "Layers",
    description: "Replacement grips and overgrips.",
    sportIds: [padelSportId],
    sortOrder: 50,
    ...pub,
  },
  {
    id: "cat-padel-accessories",
    name: "Accessories",
    slug: "padel-accessories",
    pathSegment: "accessories",
    icon: "Sparkles",
    description: "Protectors, dampeners and court essentials.",
    sportIds: [padelSportId],
    sortOrder: 60,
    ...pub,
  },
  {
    id: "cat-padel-clothing",
    name: "Clothing",
    slug: "padel-clothing",
    pathSegment: "clothing",
    icon: "Shirt",
    description: "Padel apparel and court wear.",
    sportIds: [padelSportId],
    sortOrder: 70,
    ...pub,
  },
];

export const padelBrands: Brand[] = [
  { id: "brand-nox", name: "Nox", slug: "nox", logo: "/images/padel/brands/nox.svg", country: "Spain", description: "Padel rackets and court gear.", homepage: "https://www.noxpadel.com", ...pub },
  { id: "brand-bullpadel", name: "Bullpadel", slug: "bullpadel", logo: "/images/padel/brands/bullpadel.svg", country: "Spain", description: "Padel rackets and equipment.", homepage: "https://www.bullpadel.com", ...pub },
  { id: "brand-adidas-padel", name: "Adidas Padel", slug: "adidas-padel", logo: "/images/brands/adidas-logo.svg", country: "Germany", description: "Adidas padel rackets and shoes (Adidas padel vertical entity).", homepage: "https://www.adidas.com", ...pub },
  { id: "brand-head-padel", name: "Head", slug: "head", logo: "/images/padel/brands/head.svg", country: "Austria", description: "Head padel and racket sports.", homepage: "https://www.head.com", ...pub },
  { id: "brand-wilson-padel", name: "Wilson", slug: "wilson", logo: "/images/padel/brands/wilson.svg", country: "USA", description: "Wilson padel rackets.", homepage: "https://www.wilson.com", ...pub },
  { id: "brand-siux", name: "Siux", slug: "siux", logo: "/images/padel/brands/siux.svg", country: "Spain", description: "Siux padel rackets.", homepage: "https://www.siuxpadel.com", ...pub },
  { id: "brand-babolat-padel", name: "Babolat", slug: "babolat", logo: "/images/padel/brands/babolat.svg", country: "France", description: "Babolat padel equipment.", homepage: "https://www.babolat.com", ...pub },
  { id: "brand-starvie", name: "StarVie", slug: "starvie", logo: "/images/padel/brands/starvie.svg", country: "Spain", description: "StarVie padel rackets.", homepage: "https://www.starvie.com", ...pub },
];

function img(id: string, src: string, alt: string) {
  return { id, src, alt, type: "image" as const };
}

export const padelProducts: Product[] = [
  {
    id: "prod-nox-at10-18k-2026",
    slug: "nox-at10-genius-18k-2026",
    brandId: "brand-nox",
    name: "AT10 Genius 18K 2026",
    fullName: "Nox AT10 Genius 18K 2026",
    shortDescription: "Hybrid teardrop racket balancing control and power for intermediate to advanced players.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-balanced", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 360,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium-EVA",
      face: "18K carbon",
      sweetSpot: "medium-large",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Versatile hybrid feel", "Strong all-court option"],
    weaknesses: ["Not the lightest frame"],
    recommendationScore: 94,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-nox-at10", "/images/padel/products/racket-1.png", "Nox AT10 Genius 18K 2026 padel racket")],
    videos: [],
    offerIds: ["offer-nox-at10-nl", "offer-nox-at10-nl-2"],
    evidenceIds: [],
    relatedProductIds: ["prod-bullpadel-vertex-04"],
    alternativeProductIds: ["prod-babolat-technical-viper"],
    ...pub,
  },
  {
    id: "prod-bullpadel-vertex-04",
    slug: "bullpadel-vertex-04-2026",
    brandId: "brand-bullpadel",
    name: "Vertex 04 2026",
    fullName: "Bullpadel Vertex 04 2026",
    shortDescription: "Attacking diamond racket for players who finish points with power.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Attacking power", "Stable through the smash"],
    weaknesses: ["Less forgiving for beginners"],
    recommendationScore: 91,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-vertex", "/images/padel/products/racket-2.png", "Bullpadel Vertex 04 2026 padel racket")],
    videos: [],
    offerIds: ["offer-vertex-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-nox-at10-18k-2026"],
    alternativeProductIds: ["prod-head-coello-pro"],
    ...pub,
  },
  {
    id: "prod-babolat-technical-viper",
    slug: "babolat-technical-viper-2026",
    brandId: "brand-babolat-padel",
    name: "Technical Viper 2026",
    fullName: "Babolat Technical Viper 2026",
    shortDescription: "Power-focused racket for aggressive attackers.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "compact",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Explosive power", "Strong finishing shots"],
    weaknesses: ["Demanding for beginners"],
    recommendationScore: 89,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    images: [img("img-viper", "/images/padel/products/racket-3.png", "Babolat Technical Viper 2026 padel racket")],
    videos: [],
    offerIds: ["offer-viper-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-siux-diablo"],
    alternativeProductIds: ["prod-nox-at10-18k-2026"],
    ...pub,
  },
  {
    id: "prod-head-coello-pro",
    slug: "head-coello-pro-2026",
    brandId: "brand-head-padel",
    name: "Coello Pro 2026",
    fullName: "Head Coello Pro 2026",
    shortDescription: "Value-focused hybrid racket with approachable handling.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-beginner", "uc-padel-balanced", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 350,
      weightMax: 365,
      thicknessMm: 38,
      core: "soft-EVA",
      face: "fiberglass/carbon",
      sweetSpot: "large",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Strong value", "Forgiving for intermediates"],
    weaknesses: ["Less premium face materials"],
    recommendationScore: 86,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate"],
    images: [img("img-coello", "/images/padel/products/racket-4.png", "Head Coello Pro 2026 padel racket")],
    videos: [],
    offerIds: ["offer-coello-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-wilson-bela-pro"],
    alternativeProductIds: ["prod-bullpadel-vertex-04"],
    ...pub,
  },
  {
    id: "prod-siux-diablo",
    slug: "siux-diablo-revolution-2026",
    brandId: "brand-siux",
    name: "Diablo Pro 2026",
    fullName: "Siux Diablo Pro 2026",
    shortDescription:
      "Balanced teardrop Diablo Pro for advanced all-court play — control-first with enough pop to finish.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-beginner", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 355,
      weightMax: 375,
      thicknessMm: 38,
      core: "EVA",
      face: "24K-textreme-carbon",
      sweetSpot: "medium",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Versatile hybrid shape", "Spin-friendly 3D face", "Pro-line build"],
    weaknesses: ["Premium price", "Firm for absolute beginners"],
    recommendationScore: 88,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-diablo", "/images/padel/products/siux-diablo-hero.png", "Siux Diablo Pro 2026 padel racket")],
    videos: [],
    offerIds: ["offer-diablo-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-bullpadel-vertex-04"],
    alternativeProductIds: ["prod-head-coello-pro"],
    ...pub,
  },
  {
    id: "prod-adidas-courtstabil",
    slug: "adidas-courtstabil-padel",
    brandId: "brand-adidas-padel",
    name: "CourtStabil Padel",
    fullName: "Adidas CourtStabil Padel",
    shortDescription: "Stable padel court shoe for lateral movement.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-shoes",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Court grip", "Lateral support"],
    weaknesses: [],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: [img("img-shoes", "/images/padel/products/shoes.svg", "Adidas CourtStabil padel shoes")],
    videos: [],
    offerIds: ["offer-shoes-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-head-padel-pro-s",
    slug: "head-padel-pro-s-balls",
    brandId: "brand-head-padel",
    name: "Padel Pro S",
    fullName: "Head Padel Pro S Balls",
    shortDescription: "Official-style padel ball tub for match play.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-balls",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Consistent bounce"],
    weaknesses: [],
    recommendationScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-balls", "/images/padel/products/balls.svg", "Head Padel Pro S balls")],
    videos: [],
    offerIds: ["offer-balls-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-wilson-overgrip",
    slug: "wilson-padel-overgrip-pack",
    brandId: "brand-wilson-padel",
    name: "Padel Overgrip Pack",
    fullName: "Wilson Padel Overgrip Pack",
    shortDescription: "Absorbent overgrips for padel handles.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-grips",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Grip in humid play"],
    weaknesses: [],
    recommendationScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-grips", "/images/padel/products/grips.svg", "Wilson padel overgrip pack")],
    videos: [],
    offerIds: ["offer-grips-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-nox-bag-10",
    slug: "nox-thermo-bag-10",
    brandId: "brand-nox",
    name: "Thermo Bag 10",
    fullName: "Nox Thermo Bag 10",
    shortDescription: "Thermo padel bag for rackets and court kit.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-bags",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Thermo compartment"],
    weaknesses: [],
    recommendationScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-bag", "/images/padel/products/bag.svg", "Nox Thermo Bag 10")],
    videos: [],
    offerIds: ["offer-bag-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
    // SVG placeholder only — hold out of published catalog until authentic packshot
    status: "draft",
  },
  {
    id: "prod-wilson-bela-pro",
    slug: "wilson-bela-pro-v2-2026",
    brandId: "brand-wilson-padel",
    name: "Bela Pro V2 2026",
    fullName: "Wilson Bela Pro V2 2026",
    shortDescription: "Attacking racket used in featured comparisons.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Attacking profile"],
    weaknesses: [],
    recommendationScore: 87,
    experienceLevels: ["advanced"],
    images: [img("img-bela", "/images/padel/products/racket-4.png", "Wilson Bela Pro V2 2026")],
    videos: [],
    offerIds: ["offer-bela-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-babolat-technical-viper"],
    alternativeProductIds: ["prod-nox-at10-18k-2026"],
    ...pub,
  },
];

export const padelOffers: Offer[] = [
  { id: "offer-nox-at10-nl", productId: "prod-nox-at10-18k-2026", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 219.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-nox-at10-nl-2", productId: "prod-nox-at10-18k-2026", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 229.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-vertex-nl", productId: "prod-bullpadel-vertex-04", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 259.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-viper-nl", productId: "prod-babolat-technical-viper", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 279.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-coello-nl", productId: "prod-head-coello-pro", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 149.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-diablo-nl", productId: "prod-siux-diablo", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 189.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-shoes-nl", productId: "prod-adidas-courtstabil", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 89.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-balls-nl", productId: "prod-head-padel-pro-s", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 6.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-grips-nl", productId: "prod-wilson-overgrip", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 9.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-bag-nl", productId: "prod-nox-bag-10", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 79.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-bela-nl", productId: "prod-wilson-bela-pro", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 249.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
];

export const padelBestGuides: BestGuide[] = [
  {
    id: "best-padel-rackets",
    slug: "padel-rackets",
    title: "Best Padel Rackets",
    sportId: padelSportId,
    categoryId: "cat-padel-rackets",
    useCaseIds: [],
    rankingMode: "category-picks",
    intro:
      "A structured shortlist of padel rackets mapped to play style — not a generic top-10 list.",
    selectionMethodology:
      "Products are scored via explainable recommendation factors (control, power, maneuverability, value) against play profiles. Specs load from Product entities.",
    selectionCriteria: [
      {
        key: "shape",
        label: "Shape",
        description: "Round, teardrop or diamond play profile.",
      },
      {
        key: "balance",
        label: "Balance",
        description: "Maneuverability vs power bias.",
      },
      {
        key: "value",
        label: "Value",
        description: "Performance relative to street price.",
      },
    ],
    recommendations: [
      {
        productId: "prod-bullpadel-vertex-05",
        rank: 1,
        awardType: "best-overall",
        rationale:
          "Balanced diamond attack with a more forgiving sweet spot than most pure power frames — strong all-court pick for advanced intermediates.",
        evidenceIds: ["ev-wave26-editorial"],
      },
      {
        productId: "prod-nox-at10-12k-2026",
        rank: 2,
        badge: "Best Premium Attack",
        rationale:
          "2026 AT10 Genius 12K Alum Xtrem — refined diamond power with Weight Balance tuning for advanced finishers.",
        evidenceIds: ["ev-wave26-editorial"],
      },
      {
        productId: "prod-siux-diablo",
        rank: 3,
        badge: "Best Beginner / Maneuverability",
        rationale: "Round, low-balance frame for easier handling and forgiveness.",
      },
      {
        productId: "prod-babolat-counter-viper",
        rank: 4,
        badge: "Best Control",
        rationale: "Control-oriented Viper line for placement-first intermediates.",
      },
      {
        productId: "prod-bullpadel-hack-04",
        rank: 5,
        badge: "Best Power",
        rationale: "Direct attacking Hack 04 for advanced net finishers.",
        evidenceIds: ["ev-wave26-editorial"],
      },
      {
        productId: "prod-head-coello-pro",
        rank: 6,
        awardType: "best-value",
        rationale: "Approachable hybrid performance without flagship pricing.",
      },
      {
        productId: "prod-adidas-metalbone-hrd",
        rank: 7,
        badge: "Best Premium Power",
        rationale: "High-rigidity Metalbone for players who prioritize finishing authority.",
      },
    ],
    comparisonProductIds: [
      "prod-bullpadel-vertex-05",
      "prod-nox-at10-12k-2026",
      "prod-siux-diablo",
      "prod-babolat-counter-viper",
      "prod-bullpadel-hack-04",
      "prod-head-coello-pro",
      "prod-adidas-metalbone-hrd",
    ],
    buyingAdvice:
      "Match shape and balance to your level first, then refine by feel and budget.",
    faqIds: [],
    relatedToolSlugs: ["padel-racket-finder"],
    ...pub,
  },
];

export const padelComparisons: Comparison[] = [
  {
    id: "cmp-nox-bullpadel",
    slug: "nox-at10-genius-18k-2026-vs-bullpadel-vertex-04-2026",
    title: "Nox AT10 Genius 18K 2026 vs Bullpadel Vertex 04 2026",
    productIds: ["prod-nox-at10-18k-2026", "prod-bullpadel-vertex-04"],
    categoryId: "cat-padel-rackets",
    comparisonType: "hybrid",
    summary: "Hybrid versatility versus control-first diamond geometry.",
    criteria: [
      { key: "control", label: "Control", winnerProductId: "prod-bullpadel-vertex-04" },
      { key: "power", label: "Power", winnerProductId: "prod-nox-at10-18k-2026" },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-control",
        productId: "prod-bullpadel-vertex-04",
        rationale: "Control-first diamond geometry for placement and defence.",
      },
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-nox-at10-18k-2026",
        rationale: "Hybrid all-court versatility when you attack and defend equally.",
      },
      {
        useCaseId: "uc-padel-power",
        productId: "prod-nox-at10-18k-2026",
        rationale: "More finishing bias than Vertex while staying all-court usable.",
      },
    ],
    chooseProductReasons: [
      { productId: "prod-bullpadel-vertex-04", reason: "You prioritise control." },
      { productId: "prod-nox-at10-18k-2026", reason: "You want all-court hybrid play." },
    ],
    verdict: "Choose Vertex for control; AT10 for all-court hybrid play.",
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-babolat-wilson",
    slug: "babolat-technical-viper-2026-vs-wilson-bela-pro-v2-2026",
    title: "Babolat Technical Viper 2026 vs Wilson Bela Pro V2 2026",
    productIds: ["prod-babolat-technical-viper", "prod-wilson-bela-pro"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary: "Two attacking rackets for advanced power players.",
    criteria: [{ key: "power", label: "Power" }],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-power",
        productId: "prod-babolat-technical-viper",
        rationale: "Pure attacking bias for finishers who already generate head speed.",
      },
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-wilson-bela-pro",
        rationale: "Still attack-capable with a different stiffness/head-feel profile.",
      },
    ],
    verdict: "Both favour attackers; pick by preference for stiffness and head feel.",
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-head-siux",
    slug: "head-coello-pro-2026-vs-siux-diablo-revolution-2026",
    title: "Head Coello Pro 2026 vs Siux Diablo Revolution 2026",
    productIds: ["prod-head-coello-pro", "prod-siux-diablo"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary: "Value hybrid versus maneuverable round control.",
    criteria: [{ key: "value", label: "Value", winnerProductId: "prod-head-coello-pro" }],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-head-coello-pro",
        rationale: "Value hybrid versatility for intermediate all-court play.",
      },
      {
        useCaseId: "uc-padel-control",
        productId: "prod-siux-diablo",
        rationale: "Rounder, quicker handling for defensive and counter-punch play.",
      },
      {
        useCaseId: "uc-padel-beginner",
        productId: "prod-siux-diablo",
        rationale: "More maneuverable shape class for developing timing.",
      },
    ],
    verdict: "Coello for value versatility; Diablo for quick defensive handling.",
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-nox-babolat",
    slug: "nox-at10-genius-18k-2026-vs-babolat-technical-viper-2026",
    title: "Nox AT10 Genius 18K 2026 vs Babolat Technical Viper 2026",
    productIds: ["prod-nox-at10-18k-2026", "prod-babolat-technical-viper"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary: "Hybrid all-court racket versus pure power attacker.",
    criteria: [{ key: "power", label: "Power", winnerProductId: "prod-babolat-technical-viper" }],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-nox-at10-18k-2026",
        rationale: "Hybrid all-court balance when you need attack and defence.",
      },
      {
        useCaseId: "uc-padel-power",
        productId: "prod-babolat-technical-viper",
        rationale: "Finishing power when smash output is the priority.",
      },
    ],
    verdict: "AT10 for balance; Viper when finishing power is the priority.",
    faqIds: [],
    ...pub,
  },
];

export const padelBuyingGuides: BuyingGuide[] = [
  {
    id: "guide-choose-padel-racket",
    slug: "how-to-choose-a-padel-racket",
    title: "How to Choose a Padel Racket",
    sportId: padelSportId,
    categoryId: "cat-padel-rackets",
    relatedProductIds: [
      "prod-bullpadel-vertex-05",
      "prod-nox-at10-12k-2026",
      "prod-nox-ml10-pro-cup",
      "prod-head-coello-pro",
    ],
    relatedUseCaseIds: [
      "uc-padel-beginner",
      "uc-padel-control",
      "uc-padel-balanced",
      "uc-padel-power",
    ],
    quickAnswer:
      "Start with your level and whether you need control, balance, or power — then use shape, weight, and balance as secondary filters. Carbon K-count alone is not a quality ranking.",
    relatedBestGuideIds: ["best-padel-rackets"],
    relatedToolSlugs: ["padel-racket-finder"],
    sections: [
      {
        id: "s-quick",
        heading: "Quick answer",
        body: "Beginners usually do better with lighter, more forgiving rackets (often round or soft teardrop) that keep the sweet spot accessible. Intermediate players can move toward teardrop / hybrid balance. Advanced attackers often choose diamond or high-balance molds — but only when timing and preparation already support that head weight.",
      },
      {
        id: "s-level",
        heading: "Start with your level",
        body: "Level is the strongest filter. A diamond flagship will not teach timing; it will punish late preparation. If you are still building consistency, prioritise forgiveness and maneuverability over peak smash power. Kitletics Recommendation contexts (beginner / intermediate / advanced) encode this explicitly — do not rely on shape stereotypes alone.",
      },
      {
        id: "s-power-control",
        heading: "Power vs control",
        body: "Power-oriented rackets typically combine higher balance, stiffer faces, and smaller sweet zones that reward clean contact. Control-oriented rackets keep mass lower or more centred, often with softer cores, so you can place the ball without overhitting. Balanced options sit between — useful when you attack and defend in equal measure.",
      },
      {
        id: "s-shape",
        heading: "Shape",
        body: "Manufacturers describe shapes as round, teardrop, diamond, or hybrid. Round often correlates with larger sweet spots; diamond with higher sweet spots and power potential; teardrop / hybrid with middle-ground play. Treat shape as one signal among weight, balance, and core — never as a complete decision.",
      },
      {
        id: "s-weight",
        heading: "Weight",
        body: "Adult padel rackets commonly sit roughly in the 350–380 g band. Prefer published ranges (e.g. 360–375 g) over a single invented midpoint. Lighter racks swing faster and ease defence; heavier racks can feel more stable on hard contact if you can accelerate them.",
      },
      {
        id: "s-balance",
        heading: "Balance",
        body: "Low / mid-low balance helps manoeuvre at the net and on defence. Mid-high / high balance shifts mass toward the head for smash leverage — at the cost of late-swing forgiveness. Do not infer balance from shape alone; verify manufacturer or measured balance when available.",
      },
      {
        id: "s-core",
        heading: "Core / feel",
        body: "Soft EVA tends to feel more cushioned and forgiving; harder EVA returns energy more abruptly. Multi-density constructions mix zones. Keep manufacturer core names as marketing labels and use Kitletics normalized core classes for comparison.",
      },
      {
        id: "s-surface",
        heading: "Surface",
        body: "Fiberglass faces are often softer and more accessible; carbon faces (3K–24K and hybrids) vary widely. K-count is not a universal quality hierarchy — construction, resin, and core matter more than marketing weave numbers.",
      },
      {
        id: "s-sweet",
        heading: "Sweet spot",
        body: "A larger, more central sweet spot helps inconsistent contact. Smaller, higher sweet spots reward clean attackers. Pair sweet-spot claims with independent evidence when possible; marketing diagrams alone are weak evidence.",
      },
      {
        id: "s-style",
        heading: "Playing style",
        body: "Defenders and counter-punchers usually want control and maneuverability. All-court players want balance. Finishers who already generate racket-head speed can justify power molds. Use the Padel Racket Finder when you have a current racket and want a structured delta (e.g. less head-heavy, more control).",
      },
      {
        id: "s-budget",
        heading: "Budget",
        body: "Set a regional budget band and let live Offers decide availability — not MSRP folklore. Previous-generation flagships can be strong value when construction still fits your profile. Kitletics never ranks by affiliate commission.",
      },
      {
        id: "s-mistakes",
        heading: "Common mistakes",
        body: "Buying a pro’s diamond racket as a beginner; treating carbon weave as a quality ladder; ignoring weight ranges; assuming shape equals balance; attaching an old generation’s retailer listing to a new model year.",
      },
      {
        id: "s-finder",
        heading: "Use the Finder next",
        body: "When you know level, style, and budget, run the Padel Racket Finder for explainable matches, then compare top options and check regional Offers. Pair with the Best Padel Rackets shortlist when you want editorial awards rather than personalized scoring.",
      },
    ],
    faqIds: [],
    ...pub,
  },
  {
    id: "guide-choose-padel-shoes",
    slug: "how-to-choose-padel-shoes",
    title: "How to Choose Padel Shoes",
    sportId: padelSportId,
    categoryId: "cat-padel-shoes",
    relatedProductIds: ["prod-adidas-courtstabil"],
    relatedUseCaseIds: [],
    sections: [
      {
        id: "s1",
        heading: "Grip and lateral support",
        body: "Padel movement is sharp and sideways. Prioritise court outsoles and stable uppers over running-shoe cushion.",
      },
    ],
    faqIds: [],
    ...pub,
  },
  {
    id: "guide-padel-grips",
    slug: "padel-grips-overgrips-explained",
    title: "Padel Grips & Overgrips Explained",
    sportId: padelSportId,
    categoryId: "cat-padel-grips",
    relatedProductIds: ["prod-wilson-overgrip"],
    relatedUseCaseIds: [],
    sections: [
      {
        id: "s1",
        heading: "Grip stack and feel",
        body: "Replacement grips set diameter; overgrips fine-tune tack and moisture control between sessions.",
      },
    ],
    faqIds: [],
    ...pub,
  },
];

export const padelSetups: GearSetup[] = [
  {
    id: "setup-padel-starter",
    slug: "padel-starter-kit",
    title: "Padel Starter Kit",
    sportId: padelSportId,
    description:
      "A practical starter kit: racket, shoes, balls and overgrips. Add a thermo bag when you start carrying shoes and extras.",
    useCaseIds: [],
    budgetRange: { min: 200, max: 450, currency: "EUR" },
    items: [
      { productId: "prod-head-coello-pro", role: "Padel Racket", notes: "Essential — forgiving enough for new players while still current." },
      { productId: "prod-adidas-courtstabil", role: "Padel Shoes", notes: "Essential — court outsole and lateral support." },
      { productId: "prod-head-padel-pro-s", role: "Padel Balls", notes: "Essential — pressurized competition/training cans." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Useful — refresh tack every few sessions." },
    ],
    ...pub,
  },
];

export const padelTools: Tool[] = [
  {
    id: "tool-padel-racket-finder",
    name: "Padel Racket Finder",
    slug: "padel-racket-finder",
    description: "Answer questions about level, style and budget to get structured racket matches.",
    type: "finder",
    sportIds: [padelSportId],
    categoryIds: ["cat-padel-rackets"],
    useCaseIds: [],
    goalTags: ["padel", "racket", "recommendation"],
    icon: "CircleDot",
    available: false,
    ...pub,
  },
];
