import type { Product } from "@/domain/products/types";
import type { Brand } from "@/domain/products/types";
import type { ProductCategory } from "@/domain/sports/types";
import type { GearSetup } from "@/domain/editorial/types";
import type { Tool } from "@/domain/tools/types";
import type { Offer } from "@/domain/commerce/types";
import { publishedMeta } from "@/content/config";

const pub = publishedMeta();

export const padelSportId = "sport-padel" as const;

export const padelCategories: ProductCategory[] = [
  {
    id: "cat-padel-rackets",
    name: "Padel Rackets",
    slug: "padel-rackets",
    pathSegment: "rackets",
    icon: "CircleDot",
    description: "Control, power and hybrid padel rackets.",
    sportIds: [padelSportId],
    sortOrder: 10,
    seoTitle: "Padel Rackets: Compare Control, Power & Hybrid Frames",
    seoDescription:
      "Compare padel rackets by shape, balance and play style. Browse Kitletics shortlists or use the Padel Racket Finder.",
    ...pub,
  },
  {
    id: "cat-padel-shoes",
    name: "Padel Shoes",
    slug: "padel-shoes",
    pathSegment: "shoes",
    icon: "Footprints",
    description: "Court shoes built for padel movement and grip.",
    sportIds: [padelSportId],
    sortOrder: 20,
    ...pub,
  },
  {
    id: "cat-padel-bags",
    name: "Padel Bags",
    slug: "padel-bags",
    pathSegment: "bags",
    icon: "Briefcase",
    description: "Racket bags and court packs.",
    sportIds: [padelSportId],
    sortOrder: 30,
    ...pub,
  },
  {
    id: "cat-padel-balls",
    name: "Padel Balls",
    slug: "padel-balls",
    pathSegment: "balls",
    icon: "Circle",
    description: "Official and training padel balls.",
    sportIds: [padelSportId],
    sortOrder: 40,
    ...pub,
  },
  {
    id: "cat-padel-grips",
    name: "Grips & Overgrips",
    slug: "padel-grips",
    pathSegment: "grips",
    icon: "Layers",
    description: "Replacement grips and overgrips.",
    sportIds: [padelSportId],
    sortOrder: 50,
    ...pub,
  },
  {
    id: "cat-padel-accessories",
    name: "Accessories",
    slug: "padel-accessories",
    pathSegment: "accessories",
    icon: "Sparkles",
    description: "Protectors, dampeners and court essentials.",
    sportIds: [padelSportId],
    sortOrder: 60,
    ...pub,
  },
  {
    id: "cat-padel-clothing",
    name: "Clothing",
    slug: "padel-clothing",
    pathSegment: "clothing",
    icon: "Shirt",
    description: "Padel apparel and court wear.",
    sportIds: [padelSportId],
    sortOrder: 70,
    ...pub,
  },
];

export const padelBrands: Brand[] = [
  { id: "brand-nox", name: "Nox", slug: "nox", logo: "/images/padel/brands/nox.svg", country: "Spain", description: "Padel rackets and court gear.", homepage: "https://www.noxpadel.com", ...pub },
  { id: "brand-bullpadel", name: "Bullpadel", slug: "bullpadel", logo: "/images/padel/brands/bullpadel.svg", country: "Spain", description: "Padel rackets and equipment.", homepage: "https://www.bullpadel.com", ...pub },
  { id: "brand-adidas-padel", name: "Adidas Padel", slug: "adidas-padel", logo: "/images/brands/adidas-logo.svg", country: "Germany", description: "Adidas padel rackets and shoes (Adidas padel vertical entity).", homepage: "https://www.adidas.com", ...pub },
  { id: "brand-head-padel", name: "Head", slug: "head", logo: "/images/padel/brands/head.svg", country: "Austria", description: "Head padel and racket sports.", homepage: "https://www.head.com", ...pub },
  { id: "brand-wilson-padel", name: "Wilson", slug: "wilson", logo: "/images/padel/brands/wilson.svg", country: "USA", description: "Wilson padel rackets.", homepage: "https://www.wilson.com", ...pub },
  { id: "brand-siux", name: "Siux", slug: "siux", logo: "/images/padel/brands/siux.svg", country: "Spain", description: "Siux padel rackets.", homepage: "https://www.siuxpadel.com", ...pub },
  { id: "brand-babolat-padel", name: "Babolat", slug: "babolat", logo: "/images/padel/brands/babolat.svg", country: "France", description: "Babolat padel equipment.", homepage: "https://www.babolat.com", ...pub },
  { id: "brand-starvie", name: "StarVie", slug: "starvie", logo: "/images/padel/brands/starvie.svg", country: "Spain", description: "StarVie padel rackets.", homepage: "https://www.starvie.com", ...pub },
];

function img(id: string, src: string, alt: string) {
  return { id, src, alt, type: "image" as const };
}

export const padelProducts: Product[] = [
  {
    id: "prod-nox-at10-18k-2026",
    slug: "nox-at10-genius-18k-2026",
    brandId: "brand-nox",
    name: "AT10 Genius 18K 2026",
    fullName: "Nox AT10 Genius 18K 2026",
    shortDescription: "Hybrid teardrop racket balancing control and power for intermediate to advanced players.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-balanced", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 360,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium-EVA",
      face: "18K carbon",
      sweetSpot: "medium-large",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Versatile hybrid feel", "Strong all-court option"],
    weaknesses: ["Not the lightest frame"],
    recommendationScore: 94,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-nox-at10", "/images/padel/products/racket-1.png", "Nox AT10 Genius 18K 2026 padel racket")],
    videos: [],
    offerIds: ["offer-nox-at10-nl", "offer-nox-at10-nl-2"],
    evidenceIds: [],
    relatedProductIds: ["prod-bullpadel-vertex-04"],
    alternativeProductIds: ["prod-babolat-technical-viper"],
    ...pub,
  },
  {
    id: "prod-bullpadel-vertex-04",
    slug: "bullpadel-vertex-04-2026",
    brandId: "brand-bullpadel",
    name: "Vertex 04 2026",
    fullName: "Bullpadel Vertex 04 2026",
    shortDescription: "Attacking diamond racket for players who finish points with power.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Attacking power", "Stable through the smash"],
    weaknesses: ["Less forgiving for beginners"],
    recommendationScore: 91,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-vertex", "/images/padel/products/racket-2.png", "Bullpadel Vertex 04 2026 padel racket")],
    videos: [],
    offerIds: ["offer-vertex-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-nox-at10-18k-2026"],
    alternativeProductIds: ["prod-head-coello-pro"],
    ...pub,
  },
  {
    id: "prod-babolat-technical-viper",
    slug: "babolat-technical-viper-2026",
    brandId: "brand-babolat-padel",
    name: "Technical Viper 2026",
    fullName: "Babolat Technical Viper 2026",
    shortDescription: "Power-focused racket for aggressive attackers.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "compact",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Explosive power", "Strong finishing shots"],
    weaknesses: ["Demanding for beginners"],
    recommendationScore: 89,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    images: [img("img-viper", "/images/padel/products/racket-3.png", "Babolat Technical Viper 2026 padel racket")],
    videos: [],
    offerIds: ["offer-viper-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-siux-diablo"],
    alternativeProductIds: ["prod-nox-at10-18k-2026"],
    ...pub,
  },
  {
    id: "prod-head-coello-pro",
    slug: "head-coello-pro-2026",
    brandId: "brand-head-padel",
    name: "Coello Pro 2026",
    fullName: "Head Coello Pro 2026",
    shortDescription: "Value-focused hybrid racket with approachable handling.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-beginner", "uc-padel-balanced", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 350,
      weightMax: 365,
      thicknessMm: 38,
      core: "soft-EVA",
      face: "fiberglass/carbon",
      sweetSpot: "large",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Strong value", "Forgiving for intermediates"],
    weaknesses: ["Less premium face materials"],
    recommendationScore: 86,
    valueScore: 92,
    experienceLevels: ["beginner", "intermediate"],
    images: [img("img-coello", "/images/padel/products/racket-4.png", "Head Coello Pro 2026 padel racket")],
    videos: [],
    offerIds: ["offer-coello-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-wilson-bela-pro"],
    alternativeProductIds: ["prod-bullpadel-vertex-04"],
    ...pub,
  },
  {
    id: "prod-siux-diablo",
    slug: "siux-diablo-revolution-2026",
    brandId: "brand-siux",
    name: "Diablo Pro 2026",
    fullName: "Siux Diablo Pro 2026",
    shortDescription:
      "Balanced teardrop Diablo Pro for advanced all-court play — control-first with enough pop to finish.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-beginner", "uc-padel-control"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 355,
      weightMax: 375,
      thicknessMm: 38,
      core: "EVA",
      face: "24K-textreme-carbon",
      sweetSpot: "medium",
      powerPositioning: "medium",
      controlPositioning: "high",
    },
    strengths: ["Versatile hybrid shape", "Spin-friendly 3D face", "Pro-line build"],
    weaknesses: ["Premium price", "Firm for absolute beginners"],
    recommendationScore: 88,
    valueScore: 84,
    experienceLevels: ["intermediate", "advanced"],
    images: [img("img-diablo", "/images/padel/products/siux-diablo-hero.png", "Siux Diablo Pro 2026 padel racket")],
    videos: [],
    offerIds: ["offer-diablo-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-bullpadel-vertex-04"],
    alternativeProductIds: ["prod-head-coello-pro"],
    ...pub,
  },
  {
    id: "prod-adidas-courtstabil",
    slug: "adidas-courtquick-padel",
    brandId: "brand-adidas-padel",
    name: "Courtquick Padel",
    fullName: "Adidas Courtquick Padel",
    shortDescription:
      "Current Adidas Courtquick padel court shoe for stable lateral movement.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-shoes",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Court grip", "Lateral support"],
    weaknesses: [],
    recommendationScore: 84,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate"],
    images: [img("img-shoes", "/images/padel/products/shoes.svg", "Adidas Courtquick padel shoes")],
    videos: [],
    offerIds: ["offer-shoes-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-head-padel-pro-s",
    slug: "head-padel-pro-s-balls",
    brandId: "brand-head-padel",
    name: "Padel Pro S",
    fullName: "Head Padel Pro S Balls",
    shortDescription: "Official-style padel ball tub for match play.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-balls",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Consistent bounce"],
    weaknesses: [],
    recommendationScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-balls", "/images/padel/products/balls.svg", "Head Padel Pro S balls")],
    videos: [],
    offerIds: ["offer-balls-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-wilson-overgrip",
    slug: "wilson-padel-overgrip-pack",
    brandId: "brand-wilson-padel",
    name: "Padel Overgrip Pack",
    fullName: "Wilson Padel Overgrip Pack",
    shortDescription: "Absorbent overgrips for padel handles.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-grips",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Grip in humid play"],
    weaknesses: [],
    recommendationScore: 78,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-grips", "/images/padel/products/grips.svg", "Wilson padel overgrip pack")],
    videos: [],
    offerIds: ["offer-grips-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
  },
  {
    id: "prod-nox-bag-10",
    slug: "nox-thermo-bag-10",
    brandId: "brand-nox",
    name: "Thermo Bag 10",
    fullName: "Nox Thermo Bag 10",
    shortDescription: "Thermo padel bag for rackets and court kit.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-bags",
    subcategoryIds: [],
    useCaseIds: [],
    specifications: {},
    strengths: ["Thermo compartment"],
    weaknesses: [],
    recommendationScore: 82,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    images: [img("img-bag", "/images/padel/products/bag.svg", "Nox Thermo Bag 10")],
    videos: [],
    offerIds: ["offer-bag-nl"],
    evidenceIds: [],
    relatedProductIds: [],
    alternativeProductIds: [],
    ...pub,
    // SVG placeholder only — hold out of published catalog until authentic packshot
    status: "draft",
  },
  {
    id: "prod-wilson-bela-pro",
    slug: "wilson-bela-pro-v2-2026",
    brandId: "brand-wilson-padel",
    name: "Bela Pro V2 2026",
    fullName: "Wilson Bela Pro V2 2026",
    shortDescription: "Attacking racket used in featured comparisons.",
    lifecycleStatus: "current",
    sportIds: [padelSportId],
    disciplineIds: [],
    categoryId: "cat-padel-rackets",
    subcategoryIds: [],
    useCaseIds: ["uc-padel-power"],
    specifications: {
      shape: "diamond",
      balance: "head-heavy",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "hard-EVA",
      face: "carbon",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    strengths: ["Attacking profile"],
    weaknesses: [],
    recommendationScore: 87,
    experienceLevels: ["advanced"],
    images: [img("img-bela", "/images/padel/products/racket-4.png", "Wilson Bela Pro V2 2026")],
    videos: [],
    offerIds: ["offer-bela-nl"],
    evidenceIds: [],
    relatedProductIds: ["prod-babolat-technical-viper"],
    alternativeProductIds: ["prod-nox-at10-18k-2026"],
    ...pub,
  },
];

export const padelOffers: Offer[] = [
  { id: "offer-nox-at10-nl", productId: "prod-nox-at10-18k-2026", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 219.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-nox-at10-nl-2", productId: "prod-nox-at10-18k-2026", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 229.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-vertex-nl", productId: "prod-bullpadel-vertex-04", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 259.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-viper-nl", productId: "prod-babolat-technical-viper", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 279.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-coello-nl", productId: "prod-head-coello-pro", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 149.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-diablo-nl", productId: "prod-siux-diablo", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 189.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-shoes-nl", productId: "prod-adidas-courtstabil", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 89.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-balls-nl", productId: "prod-head-padel-pro-s", retailerId: "ret-decathlon", region: "NL", url: "https://www.decathlon.nl/", currency: "EUR", price: 6.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-grips-nl", productId: "prod-wilson-overgrip", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 9.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-bag-nl", productId: "prod-nox-bag-10", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 79.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
  { id: "offer-bela-nl", productId: "prod-wilson-bela-pro", retailerId: "ret-amazon-nl", region: "NL", url: "https://www.amazon.nl/", currency: "EUR", price: 249.95, availability: "in-stock", lastChecked: pub.lastVerifiedAt! },
];

export { padelBestGuides } from "@/content/padel/best-guides";

export { padelComparisons } from "@/content/padel/comparisons";

export { padelBuyingGuides } from "@/content/padel/buying-guides";

export const padelSetups: GearSetup[] = [
  {
    id: "setup-padel-starter",
    slug: "padel-starter-kit",
    title: "Padel Essentials Starter Kit",
    sportId: padelSportId,
    description:
      "Core essentials for first regular sessions: forgiving racket, court shoes, pressurized balls and overgrips. Add a bag when you start carrying shoes and extras.",
    useCaseIds: [],
    budgetRange: { min: 200, max: 450, currency: "EUR" },
    items: [
      { productId: "prod-bullpadel-indiga-ctr", role: "Padel Racket", notes: "Essential — forgiving SoftEva round for developing contact (not a pro diamond)." },
      { productId: "prod-adidas-courtstabil", role: "Padel Shoes", notes: "Essential — court outsole and lateral support." },
      { productId: "prod-head-padel-pro-s", role: "Padel Balls", notes: "Essential — pressurized competition/training cans." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Useful — refresh tack every few sessions." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-beginner",
    slug: "padel-beginner-kit",
    title: "Beginner Padel Kit",
    sportId: padelSportId,
    description:
      "First months on court: forgiving racket, proper shoes, match + training ball options, overgrips, and an optional compact club bag when you stop borrowing pockets.",
    useCaseIds: ["uc-padel-beginner"],
    budgetRange: { min: 220, max: 520, currency: "EUR" },
    items: [
      { productId: "prod-bullpadel-indiga-ctr", role: "Padel Racket", notes: "Essential — SoftEva round for contact learning." },
      { productId: "prod-adidas-courtstabil", role: "Padel Shoes", notes: "Essential — lateral court grip." },
      { productId: "prod-head-padel-pro-s", role: "Competition Balls", notes: "Essential — fresh cans for honest bounce." },
      { productId: "prod-kuikma-pb-speed", role: "Training / Value Balls", notes: "Useful — value FIP fast can for practice crates." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Essential — spare wraps in the bag." },
      { productId: "prod-nox-at10-team-bag", role: "Club Bag", notes: "Optional — add when you carry shoes + a second frame." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-club",
    slug: "padel-club-player-kit",
    title: "Regular Club Player Kit",
    sportId: padelSportId,
    description:
      "Weekly club nights: all-court racket, stable shoes, competition cans, overgrips, and a 42 L thermo paletero.",
    useCaseIds: ["uc-padel-balanced"],
    budgetRange: { min: 350, max: 750, currency: "EUR" },
    items: [
      { productId: "prod-nox-at10-12k-2026", role: "Padel Racket", notes: "Essential — Genius teardrop all-court for mixed club weeks." },
      { productId: "prod-asics-gel-resolution-padel", role: "Padel Shoes", notes: "Essential — high lateral stability for glass cuts." },
      { productId: "prod-head-padel-pro-s", role: "Padel Balls", notes: "Essential — competition cans for league nights." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Essential — refresh before match night." },
      { productId: "prod-nox-at10-team-bag", role: "Club Bag", notes: "Essential — ~42 L thermo paletero with shoe slot." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-competitive",
    slug: "padel-competitive-player-kit",
    title: "Competitive Player Kit",
    sportId: padelSportId,
    description:
      "League and competitive club play: current attack/all-court frame, Resolution-class shoes, match cans, overgrips, tournament-capable bag, and rim protection.",
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    budgetRange: { min: 450, max: 950, currency: "EUR" },
    items: [
      { productId: "prod-bullpadel-vertex-05", role: "Padel Racket", notes: "Essential — current diamond with usable attack zone (Hack 04 if finishing leads)." },
      { productId: "prod-asics-gel-resolution-padel", role: "Padel Shoes", notes: "Essential — plush stability for hard weeks." },
      { productId: "prod-head-padel-pro-s", role: "Padel Balls", notes: "Essential — match cans only." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Essential — start each match with tack." },
      { productId: "prod-babolat-rh-pro-padel", role: "Tournament Bag", notes: "Essential — ~62 L / multi-racket weekend volume." },
      { productId: "prod-bullpadel-frame-protector", role: "Frame Protector", notes: "Useful — glass/mesh scrape insurance." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-tournament-day",
    slug: "padel-tournament-day-kit",
    title: "Tournament Day Kit",
    sportId: padelSportId,
    description:
      "Match-day travel: primary frame, stable shoes, unopened competition cans, spare overgrips, large thermo bag, rim protector — pressurizer only if you stretch cans across a multi-day event.",
    useCaseIds: ["uc-padel-power"],
    budgetRange: { min: 500, max: 1100, currency: "EUR" },
    items: [
      { productId: "prod-bullpadel-vertex-05", role: "Primary Racket", notes: "Essential — current competitive frame you already trust." },
      { productId: "prod-asics-gel-resolution-padel", role: "Padel Shoes", notes: "Essential — broken-in match shoes." },
      { productId: "prod-head-padel-pro-s", role: "Competition Balls", notes: "Essential — unopened cans for match bounce." },
      { productId: "prod-wilson-overgrip", role: "Spare Overgrips", notes: "Essential — mid-match swaps." },
      { productId: "prod-nox-at10-xxl-bag", role: "Tournament Bag", notes: "Essential — ~90 L / multi-racket travel volume." },
      { productId: "prod-bullpadel-frame-protector", role: "Frame Protector", notes: "Useful — spare tape for weekend scrapes." },
      { productId: "prod-head-x3-pressurizer", role: "Pressurizer", notes: "Optional — only if you stretch cans across a multi-day event." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-commuter",
    slug: "padel-commuter-kit",
    title: "Padel Commuter Kit",
    sportId: padelSportId,
    description:
      "Hands-free desk-to-court days: forgiving-enough racket, court shoes, a can of balls, overgrips, and a backpack — not a 90 L tournament cavern.",
    useCaseIds: [],
    budgetRange: { min: 250, max: 550, currency: "EUR" },
    items: [
      { productId: "prod-bullpadel-indiga-ctr", role: "Padel Racket", notes: "Essential — one frame you can carry daily." },
      { productId: "prod-adidas-courtstabil", role: "Padel Shoes", notes: "Essential — court outsole in the shoe well." },
      { productId: "prod-head-padel-pro-s", role: "Padel Balls", notes: "Essential — one fresh can." },
      { productId: "prod-wilson-overgrip", role: "Overgrips", notes: "Useful — spare wrap in a side pocket." },
      { productId: "prod-tecnifibre-tour-endurance-backpack", role: "Backpack", notes: "Essential — commute-first day pack with shoe well." },
    ],
    ...pub,
  },
  {
    id: "setup-padel-budget",
    slug: "padel-budget-starter-kit",
    title: "Budget Starter Kit",
    sportId: padelSportId,
    description:
      "Lowest sensible spend to start properly: value Kuikma comfort racket and shoes, value fast balls, overgrips — skip bags and pressurizers until you play enough to need them.",
    useCaseIds: ["uc-padel-beginner"],
    budgetRange: { min: 150, max: 350, currency: "EUR" },
    items: [
      { productId: "prod-kuikma-pr-comfort-soft", role: "Padel Racket", notes: "Essential — soft round value on-ramp." },
      { productId: "prod-kuikma-ps-990", role: "Padel Shoes", notes: "Essential — value padel court shoe." },
      { productId: "prod-kuikma-pb-speed", role: "Padel Balls", notes: "Essential — value FIP fast competition can." },
      { productId: "prod-kuikma-overgrip", role: "Overgrips", notes: "Useful — replace often; do not stretch dead wraps." },
    ],
    ...pub,
  },
];

export const padelTools: Tool[] = [
  {
    id: "tool-padel-racket-finder",
    name: "Padel Racket Finder",
    slug: "padel-racket-finder",
    description:
      "Flagship adaptive matcher for padel rackets — best match plus control, power, comfort and value alternatives with clear reasons. Affiliate commission never ranks results.",
    type: "finder",
    sportIds: [padelSportId],
    categoryIds: ["cat-padel-rackets"],
    useCaseIds: [],
    goalTags: ["padel", "racket", "recommendation"],
    icon: "CircleDot",
    available: false,
    ...pub,
  },
];
