/**
 * Prompt 26 — New 2026 padel products + overlay patches.
 * Does not mutate padel/seed.ts or wave25.ts — products/offers/recs/families/comparisons/patches only.
 */

import type { Product, Brand, ProductFamily } from "@/domain/products/types";
import type { Offer } from "@/domain/commerce/types";
import type {
  Recommendation,
  Evidence,
  AlternativeRelationship,
} from "@/domain/recommendations/types";
import type { Comparison } from "@/domain/editorial/types";
import type { ProductRelationship } from "@/domain/relationships/types";
import { publishedMeta, SEED_DATES } from "@/content/config";

const relMeta = {
  status: "approved" as const,
  createdAt: SEED_DATES.created,
  updatedAt: SEED_DATES.updated,
  lastVerifiedAt: SEED_DATES.verified,
};

const pub = publishedMeta();
const padelSportId = "sport-padel" as const;
const tennisSportId = "sport-tennis" as const;

const RACKET_SVGS = [
  "/images/padel/products/racket-1.svg",
  "/images/padel/products/racket-2.svg",
  "/images/padel/products/racket-3.svg",
  "/images/padel/products/racket-4.svg",
  "/images/padel/products/racket-5.svg",
] as const;

function padelImg(productId: string, index: number, alt: string) {
  return [
    {
      id: `img-${productId}`,
      src: RACKET_SVGS[index % RACKET_SVGS.length]!,
      alt: `${alt} — catalog placeholder — product photograph unavailable`,
      type: "image" as const,
      source: "Kitletics padel placeholder",
      usageType: "hero" as const,
      licence: "kitletics-owned" as const,
    },
  ];
}

function shoeImg(productId: string, alt: string) {
  return [
    {
      id: `img-${productId}`,
      src: "/images/padel/products/shoes.svg",
      alt: `${alt} — catalog placeholder — product photograph unavailable`,
      type: "image" as const,
      source: "Kitletics padel placeholder",
      usageType: "hero" as const,
      licence: "kitletics-owned" as const,
    },
  ];
}

/** NL / DE / UK Amazon triplet; optional Decathlon NL when value-oriented. */
function offerRegions(
  productId: string,
  slug: string,
  priceEur: number,
  opts?: { decathlon?: boolean },
): Offer[] {
  const gbp = Math.round(priceEur * 0.86 * 100) / 100;
  const de = Math.round(priceEur * 1.02 * 100) / 100;
  const offers: Offer[] = [
    {
      id: `offer-${slug}-nl`,
      productId,
      retailerId: "ret-amazon-nl",
      region: "NL",
      url: "https://www.amazon.nl/",
      currency: "EUR",
      price: priceEur,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-de`,
      productId,
      retailerId: "ret-amazon-de",
      region: "DE",
      url: "https://www.amazon.de/",
      currency: "EUR",
      price: de,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
    {
      id: `offer-${slug}-uk`,
      productId,
      retailerId: "ret-amazon-uk",
      region: "UK",
      url: "https://www.amazon.co.uk/",
      currency: "GBP",
      price: gbp,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    },
  ];
  if (opts?.decathlon) {
    offers.push({
      id: `offer-${slug}-decathlon-nl`,
      productId,
      retailerId: "ret-decathlon",
      region: "NL",
      url: "https://www.decathlon.nl/",
      currency: "EUR",
      price: Math.round(priceEur * 0.97 * 100) / 100,
      availability: "in-stock",
      lastChecked: pub.lastVerifiedAt!,
    });
  }
  return offers;
}

function offerIdsFor(slug: string, withDecathlon?: boolean): string[] {
  const ids = [`offer-${slug}-nl`, `offer-${slug}-de`, `offer-${slug}-uk`];
  if (withDecathlon) ids.push(`offer-${slug}-decathlon-nl`);
  return ids;
}

/** Brands not already in seed / wave25. */
export const wave26Brands: Brand[] = [
  {
    id: "brand-oxdog",
    name: "Oxdog",
    slug: "oxdog",
    country: "Sweden",
    description: "Swedish padel rackets known for round Sense frames and balance tuning.",
    homepage: "https://oxdogpadel.com",
    ...pub,
  },
  {
    id: "brand-royal-padel",
    name: "Royal Padel",
    slug: "royal-padel",
    country: "Spain",
    description: "Spanish padel brand; M27 control line is a club favourite.",
    homepage: "https://royalpadel.com",
    ...pub,
  },
  {
    id: "brand-black-crown",
    name: "Black Crown",
    slug: "black-crown",
    country: "Spain",
    description: "Accessible Spanish padel rackets for club and progressive players.",
    homepage: "https://www.blackcrown.es",
    ...pub,
  },
  {
    id: "brand-tecnifibre-padel",
    name: "Tecnifibre Padel",
    slug: "tecnifibre-padel",
    country: "France",
    description: "French racket-sports brand; Wall Breaker is the padel attack flagship (Tecnifibre padel vertical entity).",
    homepage: "https://www.tecnifibre.com",
    logo: "/images/brands/tecnifibre-logo.svg",
    ...pub,
  },
  {
    id: "brand-lok",
    name: "Lok",
    slug: "lok",
    country: "Spain",
    description: "Value-oriented Spanish padel rackets for club players.",
    homepage: "https://www.lokpadel.com",
    ...pub,
  },
  {
    id: "brand-joma",
    name: "Joma",
    slug: "joma",
    country: "Spain",
    description: "Spanish court footwear and apparel; T.Slam is a padel staple.",
    homepage: "https://www.joma-sport.com",
    ...pub,
  },
];

type Wave26Draft = {
  id: string;
  slug: string;
  brandId: string;
  familyId?: string;
  generation?: string;
  name: string;
  fullName: string;
  shortDescription: string;
  categoryId: "cat-padel-rackets" | "cat-padel-shoes";
  sportIds: string[];
  useCaseIds: string[];
  specifications: Product["specifications"];
  strengths: string[];
  weaknesses: string[];
  recommendationScore: number;
  valueScore: number;
  experienceLevels: Product["experienceLevels"];
  priceEur: number;
  imgIndex: number;
  decathlonOffer?: boolean;
  relatedProductIds?: string[];
  alternativeProductIds?: string[];
};

const wave26Drafts: Wave26Draft[] = [
  {
    id: "prod-bullpadel-vertex-05",
    slug: "bullpadel-vertex-05-2026",
    brandId: "brand-bullpadel",
    familyId: "fam-bullpadel-vertex",
    generation: "05",
    name: "Vertex 05 2026",
    fullName: "Bullpadel Vertex 05 2026",
    shortDescription:
      "Diamond Vertex 05 with Xtend Carbon 12K faces and MultiEva core for advanced all-court attack. Specs synthesised from manufacturer ranges and EU retailer listings — not first-hand lab testing.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "diamond",
      balance: "mid-high",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium/hard EVA",
      manufacturerCoreName: "MultiEva",
      face: "12K carbon",
      sweetSpot: "medium-large",
      powerPositioning: "high",
      controlPositioning: "medium-high",
      playerLevel: "advanced",
    },
    strengths: ["Attacking diamond stability", "12K carbon response", "Wide advanced sweet zone"],
    weaknesses: ["Demanding for absolute beginners", "Premium street price"],
    recommendationScore: 93,
    valueScore: 78,
    experienceLevels: ["advanced", "elite"],
    priceEur: 319,
    imgIndex: 0,
    relatedProductIds: ["prod-bullpadel-hack-04", "prod-bullpadel-vertex-04"],
    alternativeProductIds: ["prod-nox-at10-12k-2026", "prod-adidas-metalbone-3-3-2026"],
  },
  {
    id: "prod-bullpadel-hack-04",
    slug: "bullpadel-hack-04-2026",
    brandId: "brand-bullpadel",
    familyId: "fam-bullpadel-hack",
    generation: "04",
    name: "Hack 04 2026",
    fullName: "Bullpadel Hack 04 2026",
    shortDescription:
      "Aggressive diamond Hack 04 built for finishing power with MultiEva and stiff carbon faces. Editorial positioning from manufacturer specs and independent review consensus — not personal testing.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-power"],
    specifications: {
      shape: "diamond",
      balance: "mid-high",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium/hard EVA",
      manufacturerCoreName: "MultiEva",
      face: "TriCarbon 18K",
      sweetSpot: "compact",
      powerPositioning: "high",
      controlPositioning: "medium",
      playerLevel: "advanced",
    },
    strengths: ["Explosive smash profile", "High structural rigidity", "CustomWeight tuning"],
    weaknesses: ["Low forgiveness off-centre", "Arm-demanding stiffness"],
    recommendationScore: 91,
    valueScore: 76,
    experienceLevels: ["advanced", "elite"],
    priceEur: 309,
    imgIndex: 1,
    relatedProductIds: ["prod-bullpadel-vertex-05", "prod-bullpadel-hack-03"],
    alternativeProductIds: ["prod-adidas-metalbone-3-3-2026", "prod-adidas-metalbone-hrd"],
  },
  {
    id: "prod-nox-at10-12k-2026",
    slug: "nox-at10-genius-12k-alum-xtrem-2026",
    brandId: "brand-nox",
    familyId: "fam-nox-at10",
    generation: "2026-12k",
    name: "AT10 Genius 12K Alum Xtrem 2026",
    fullName: "Nox AT10 Genius 12K Alum Xtrem 2026",
    shortDescription:
      "Diamond AT10 Attack-line 12K Alum Xtrem for power-leaning advanced play with mid-high balance. Catalogued from Nox/retailer ranges; not a first-hand Kitletics test.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "diamond",
      balance: "mid-high",
      weightMin: 360,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium/hard EVA",
      manufacturerCoreName: "HR3 Black EVA",
      face: "12K carbon Alum Xtrem",
      sweetSpot: "compact",
      powerPositioning: "high",
      controlPositioning: "medium",
      playerLevel: "advanced",
    },
    strengths: ["Alum Xtrem face punch", "Attacking diamond geometry", "Pro-line finishing reserve"],
    weaknesses: ["Compact sweet spot", "Less round-frame forgiveness"],
    recommendationScore: 92,
    valueScore: 77,
    experienceLevels: ["advanced", "elite"],
    priceEur: 329,
    imgIndex: 2,
    relatedProductIds: ["prod-nox-at10-18k-2026", "prod-bullpadel-vertex-05"],
    alternativeProductIds: ["prod-adidas-metalbone-3-3-2026", "prod-bullpadel-hack-04"],
  },
  {
    id: "prod-adidas-metalbone-3-3-2026",
    slug: "adidas-metalbone-2026",
    brandId: "brand-adidas-padel",
    familyId: "fam-adidas-metalbone",
    generation: "2026",
    name: "Metalbone 2026",
    fullName: "Adidas Metalbone 2026",
    shortDescription:
      "Standard Metalbone 2026 diamond attacker with Soft Performance EVA and aluminised carbon — distinct from the stiffer HRD variant. Specs from Adidas/retailer listings.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "diamond",
      balance: "mid-high",
      weightMin: 365,
      weightMax: 375,
      thicknessMm: 38,
      core: "soft/medium EVA",
      manufacturerCoreName: "Soft Performance EVA",
      face: "Carbon Aluminized 16K",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
      playerLevel: "advanced",
    },
    strengths: ["Weight & Balance customisation", "Power with softer EVA output", "Attacking diamond mold"],
    weaknesses: ["Still demanding for beginners", "Premium pricing"],
    recommendationScore: 90,
    valueScore: 79,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 299,
    imgIndex: 3,
    relatedProductIds: ["prod-adidas-metalbone-hrd", "prod-bullpadel-hack-04"],
    alternativeProductIds: ["prod-nox-at10-12k-2026", "prod-bullpadel-vertex-05"],
  },
  {
    id: "prod-head-extreme-motion-2026",
    slug: "head-extreme-motion-2026",
    brandId: "brand-head-padel",
    familyId: undefined,
    generation: "2026",
    name: "Extreme Motion 2026",
    fullName: "Head Extreme Motion 2026",
    shortDescription:
      "Head Extreme Motion used as the current control/maneuverability-leaning Extreme option — a round-leaning / lighter Extreme-line frame. A distinct Head Delta Pro 2026 control SKU was not clearly confirmed across EU catalogs at editorial time, so Extreme Motion is catalogued instead of inventing Delta Pro specs.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-control", "uc-padel-balanced"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 350,
      weightMax: 370,
      thicknessMm: 38,
      core: "medium EVA",
      manufacturerCoreName: "Power Foam",
      face: "carbon",
      sweetSpot: "medium-large",
      powerPositioning: "medium",
      controlPositioning: "medium-high",
      playerLevel: "intermediate-advanced",
    },
    strengths: ["Faster Extreme handling", "Approachable sweet zone", "Balanced intermediate path"],
    weaknesses: ["Less pure smash than diamond power flags", "Not a confirmed Delta Pro control mold"],
    recommendationScore: 84,
    valueScore: 83,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 209,
    imgIndex: 4,
    relatedProductIds: ["prod-head-extreme-pro-padel", "prod-head-coello-pro"],
    alternativeProductIds: ["prod-wilson-blade-pro-padel", "prod-varlion-lw-carbon-difusor"],
  },
  {
    id: "prod-tecnifibre-wall-breaker-365-2026",
    slug: "tecnifibre-wall-breaker-365",
    brandId: "brand-tecnifibre-padel",
    generation: "365",
    name: "Wall Breaker 365",
    fullName: "Tecnifibre Wall Breaker 365",
    shortDescription:
      "Current Tecnifibre padel flagship teardrop for advanced attackers; manufacturer cites ~365 g with soft EVA and carbon faces. Weight stored as a range (± variance), not a single invented gram figure.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-power", "uc-padel-balanced"],
    specifications: {
      shape: "teardrop",
      balance: "mid-high",
      weightMin: 355,
      weightMax: 375,
      thicknessMm: 38,
      core: "soft EVA",
      manufacturerCoreName: "EVA Soft",
      face: "carbon / Carbon Shield",
      sweetSpot: "medium",
      powerPositioning: "high",
      controlPositioning: "medium",
      playerLevel: "advanced",
    },
    strengths: ["Teardrop finishing bias", "X-TOP abrasion protection", "Attacking spin skin"],
    weaknesses: ["Less round-frame forgiveness", "Stiffer than beginner soft frames"],
    recommendationScore: 86,
    valueScore: 82,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 219,
    imgIndex: 0,
    relatedProductIds: ["prod-babolat-technical-viper", "prod-babolat-counter-viper"],
    alternativeProductIds: ["prod-head-extreme-pro-padel", "prod-adidas-metalbone-3-3-2026"],
  },
  {
    id: "prod-oxdog-sense-pro-2026",
    slug: "oxdog-sense-pro",
    brandId: "brand-oxdog",
    generation: "classics",
    name: "Sense Pro",
    fullName: "Oxdog Sense Pro",
    shortDescription:
      "Round Oxdog Sense Pro (Classics / current catalog) with HES Carbon and mid balance for control-first intermediates. Editorial from Oxdog product pages — not personal testing.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-control", "uc-padel-balanced"],
    specifications: {
      shape: "round",
      balance: "medium",
      weightMin: 360,
      weightMax: 370,
      thicknessMm: 38,
      core: "medium foam",
      face: "HES carbon",
      sweetSpot: "large",
      powerPositioning: "medium",
      controlPositioning: "high",
      playerLevel: "intermediate-advanced",
    },
    strengths: ["Round forgiveness", "RBS balance tuning", "Spin-friendly sandy face"],
    weaknesses: ["Less diamond smash peak", "Fewer EU big-box listings than Iberian brands"],
    recommendationScore: 87,
    valueScore: 81,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 269,
    imgIndex: 1,
    relatedProductIds: ["prod-royal-padel-rp-m27-2026", "prod-varlion-lw-carbon-difusor"],
    alternativeProductIds: ["prod-nox-ml10-pro-cup", "prod-siux-diablo"],
  },
  {
    id: "prod-royal-padel-rp-m27-2026",
    slug: "royal-padel-m27-poly-2026",
    brandId: "brand-royal-padel",
    generation: "2026-poly",
    name: "M27 Poly 2026",
    fullName: "Royal Padel M27 Poly 2026",
    shortDescription:
      "Current Royal Padel M27 Poly 2026 — round control flagship with soft polyethylene core and 3K carbon faces. Distinct from older M27 Hybrid SKUs.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-control", "uc-padel-beginner", "uc-padel-balanced"],
    specifications: {
      shape: "round",
      balance: "medium",
      weightMin: 360,
      weightMax: 380,
      thicknessMm: 38,
      core: "soft polyethylene",
      manufacturerCoreName: "Polyethylene Soft",
      face: "3K carbon",
      sweetSpot: "large",
      powerPositioning: "medium",
      controlPositioning: "high",
      playerLevel: "intermediate",
    },
    strengths: ["Large forgiving sweet spot", "Shock Absorption comfort", "Control-first round mold"],
    weaknesses: ["Heavier top of range", "Less explosive than diamond attackers"],
    recommendationScore: 88,
    valueScore: 80,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 279,
    imgIndex: 2,
    relatedProductIds: ["prod-oxdog-sense-pro-2026", "prod-nox-ml10-pro-cup"],
    alternativeProductIds: ["prod-varlion-lw-carbon-difusor", "prod-kuikma-pr-soft-500"],
  },
  {
    id: "prod-black-crown-special-one-soft",
    slug: "black-crown-special-one-soft",
    brandId: "brand-black-crown",
    generation: "soft",
    name: "Special One Soft",
    fullName: "Black Crown Special One Soft",
    shortDescription:
      "Value round/soft Black Crown for beginners prioritising forgiveness over premium face tech. Club-oriented editorial pick.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-beginner", "uc-padel-control"],
    specifications: {
      shape: "round",
      balance: "low",
      weightMin: 350,
      weightMax: 365,
      thicknessMm: 38,
      core: "soft EVA",
      face: "fiberglass",
      sweetSpot: "large",
      powerPositioning: "low",
      controlPositioning: "high",
      playerLevel: "beginner",
    },
    strengths: ["Soft forgiving feel", "Beginner-friendly price", "Easy defensive handling"],
    weaknesses: ["Limited smash authority", "Less durable face than 12K carbon flags"],
    recommendationScore: 81,
    valueScore: 93,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 99,
    imgIndex: 3,
    decathlonOffer: true,
    relatedProductIds: ["prod-kuikma-pr-soft-500", "prod-lok-maxx-flow"],
    alternativeProductIds: ["prod-siux-diablo", "prod-head-coello-pro"],
  },
  {
    id: "prod-lok-maxx-flow",
    slug: "lok-maxx-flow",
    brandId: "brand-lok",
    generation: "gen2",
    name: "Maxx Flow",
    fullName: "Lok Maxx Flow",
    shortDescription:
      "Value teardrop Lok for progressing beginners who want a bit more output than ultra-soft round starters.",
    categoryId: "cat-padel-rackets",
    sportIds: [padelSportId],
    useCaseIds: ["uc-padel-beginner", "uc-padel-balanced"],
    specifications: {
      shape: "teardrop",
      balance: "medium",
      weightMin: 350,
      weightMax: 370,
      thicknessMm: 38,
      core: "soft/medium EVA",
      face: "fiberglass/carbon",
      sweetSpot: "medium-large",
      powerPositioning: "medium",
      controlPositioning: "medium-high",
      playerLevel: "beginner-intermediate",
    },
    strengths: ["Approachable hybrid shape", "Strong value", "Room to grow into club play"],
    weaknesses: ["Not a tour-stiff power diamond", "Fewer independent lab measurements"],
    recommendationScore: 83,
    valueScore: 91,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 119,
    imgIndex: 4,
    decathlonOffer: true,
    relatedProductIds: ["prod-black-crown-special-one-soft", "prod-head-coello-pro"],
    alternativeProductIds: ["prod-kuikma-pr-soft-500", "prod-nox-ml10-pro-cup"],
  },
  {
    id: "prod-asics-gel-resolution-padel",
    slug: "asics-gel-resolution-padel",
    brandId: "brand-asics",
    name: "Gel-Resolution Padel",
    fullName: "ASICS Gel-Resolution Padel",
    shortDescription:
      "Court shoe from the Gel-Resolution family adapted for padel lateral load; also used on tennis hard courts. Shared sport tagging reflects dual-court use.",
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId, tennisSportId],
    useCaseIds: [],
    specifications: {
      cushioning: "GEL midfoot/heel",
      outsole: "AHAR court",
      support: "high lateral",
    },
    strengths: ["Lateral stability", "Familiar Resolution lockdown", "Durable court outsole"],
    weaknesses: ["Heavier than race-light court shoes"],
    recommendationScore: 88,
    valueScore: 78,
    experienceLevels: ["intermediate", "advanced", "elite"],
    priceEur: 139,
    imgIndex: 0,
    relatedProductIds: ["prod-asics-gel-challenger-court", "prod-babolat-jet-premura"],
    alternativeProductIds: ["prod-joma-t-slam", "prod-adidas-courtstabil"],
  },
  {
    id: "prod-asics-gel-challenger-court",
    slug: "asics-gel-challenger-court",
    brandId: "brand-asics",
    name: "Gel-Challenger Court",
    fullName: "ASICS Gel-Challenger Court",
    shortDescription:
      "Value ASICS court shoe suitable for padel and tennis hard-court sessions when Resolution pricing is too high.",
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId, tennisSportId],
    useCaseIds: [],
    specifications: {
      cushioning: "GEL",
      outsole: "court rubber",
      support: "medium-high lateral",
    },
    strengths: ["Strong value", "Solid lateral grip", "Dual-sport court use"],
    weaknesses: ["Less premium upper than Resolution"],
    recommendationScore: 84,
    valueScore: 90,
    experienceLevels: ["beginner", "intermediate"],
    priceEur: 99,
    imgIndex: 1,
    decathlonOffer: true,
    relatedProductIds: ["prod-asics-gel-resolution-padel", "prod-joma-t-slam"],
    alternativeProductIds: ["prod-head-revolt-pro-court", "prod-adidas-courtstabil"],
  },
  {
    id: "prod-babolat-jet-premura",
    slug: "babolat-jet-premura",
    brandId: "brand-babolat-padel",
    name: "Jet Premura",
    fullName: "Babolat Jet Premura",
    shortDescription:
      "Padel-focused Babolat Jet Premura with Michelin outsole heritage; often worn for padel and shared clay/hard court tennis sessions.",
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId, tennisSportId],
    useCaseIds: [],
    specifications: {
      cushioning: "KPRS-X / responsive foam",
      outsole: "Michelin padel",
      support: "medium-high",
    },
    strengths: ["Padel-specific outsole", "Quick directional changes", "Brand court ecosystem"],
    weaknesses: ["Premium vs club value shoes"],
    recommendationScore: 87,
    valueScore: 80,
    experienceLevels: ["intermediate", "advanced"],
    priceEur: 129,
    imgIndex: 2,
    relatedProductIds: ["prod-asics-gel-resolution-padel", "prod-joma-t-slam"],
    alternativeProductIds: ["prod-head-revolt-pro-court", "prod-adidas-courtstabil"],
  },
  {
    id: "prod-joma-t-slam",
    slug: "joma-t-slam",
    brandId: "brand-joma",
    name: "T.Slam",
    fullName: "Joma T.Slam",
    shortDescription:
      "Popular Joma padel court shoe with strong lateral support and value positioning across EU club markets.",
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId, tennisSportId],
    useCaseIds: [],
    specifications: {
      cushioning: "Reactive / phylon",
      outsole: "DURABILITY rubber",
      support: "high lateral",
    },
    strengths: ["Club-proven grip", "Competitive price", "Stable base"],
    weaknesses: ["Fit can run narrow for some feet"],
    recommendationScore: 86,
    valueScore: 88,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 109,
    imgIndex: 3,
    decathlonOffer: true,
    relatedProductIds: ["prod-babolat-jet-premura", "prod-asics-gel-challenger-court"],
    alternativeProductIds: ["prod-adidas-courtstabil", "prod-head-revolt-pro-court"],
  },
  {
    id: "prod-head-revolt-pro-court",
    slug: "head-revolt-pro-court",
    brandId: "brand-head-padel",
    name: "Revolt Pro Court",
    fullName: "Head Revolt Pro Court",
    shortDescription:
      "Head Revolt Pro court shoe for padel and tennis hard courts — shared sport IDs reflect dual-use reality.",
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId, tennisSportId],
    useCaseIds: [],
    specifications: {
      cushioning: "Head midsole",
      outsole: "Hybrasion court",
      support: "medium-high",
    },
    strengths: ["Familiar tennis-court platform", "Decent lateral hold", "Wide EU availability"],
    weaknesses: ["Less padel-specific than Jet Premura"],
    recommendationScore: 83,
    valueScore: 84,
    experienceLevels: ["beginner", "intermediate", "advanced"],
    priceEur: 119,
    imgIndex: 4,
    relatedProductIds: ["prod-asics-gel-resolution-padel", "prod-babolat-jet-premura"],
    alternativeProductIds: ["prod-joma-t-slam", "prod-adidas-courtstabil"],
  },
];

export const wave26Products: Product[] = wave26Drafts.map((d) => {
  const isShoe = d.categoryId === "cat-padel-shoes";
  return {
    id: d.id,
    slug: d.slug,
    brandId: d.brandId,
    familyId: d.familyId,
    generation: d.generation,
    name: d.name,
    fullName: d.fullName,
    shortDescription: d.shortDescription,
    lifecycleStatus: "current" as const,
    sportIds: d.sportIds,
    disciplineIds: [],
    categoryId: d.categoryId,
    subcategoryIds: [],
    useCaseIds: d.useCaseIds,
    specifications: d.specifications,
    strengths: d.strengths,
    weaknesses: d.weaknesses,
    recommendationScore: d.recommendationScore,
    valueScore: d.valueScore,
    experienceLevels: d.experienceLevels,
    images: isShoe
      ? shoeImg(d.id, d.fullName)
      : padelImg(d.id, d.imgIndex, d.fullName),
    videos: [],
    offerIds: offerIdsFor(d.slug, d.decathlonOffer),
    evidenceIds: ["ev-wave26-editorial"],
    relatedProductIds: d.relatedProductIds ?? [],
    alternativeProductIds: d.alternativeProductIds ?? [],
    ...pub,
  };
});

/**
 * Overlay patches for existing seed/wave25 products — applied by merge layer, not by mutating those files.
 */
export const wave26ProductPatches: Record<string, Partial<Product>> = {
  "prod-nox-at10-18k-2026": {
    familyId: "fam-nox-at10",
    generation: "2026-18k",
    specifications: {
      shape: "diamond",
      balance: "mid-high",
      weightMin: 360,
      weightMax: 375,
      thicknessMm: 38,
      core: "medium-EVA",
      face: "18K carbon",
      sweetSpot: "compact",
      powerPositioning: "high",
      controlPositioning: "medium",
    },
    relatedProductIds: ["prod-nox-at10-12k-2026", "prod-bullpadel-vertex-05"],
    evidenceIds: ["ev-wave26-editorial"],
  },
  "prod-bullpadel-vertex-04": {
    name: "Vertex 04",
    fullName: "Bullpadel Vertex 04",
    slug: "bullpadel-vertex-04",
    familyId: "fam-bullpadel-vertex",
    generation: "04",
    lifecycleStatus: "previous-generation",
    shortDescription:
      "Previous-generation diamond Vertex for attackers; superseded by Vertex 05 2026 for current catalog picks.",
    relatedProductIds: ["prod-bullpadel-vertex-05", "prod-nox-at10-18k-2026"],
    evidenceIds: ["ev-wave26-editorial"],
  },
  "prod-bullpadel-hack-03": {
    name: "Hack 03",
    fullName: "Bullpadel Hack 03",
    slug: "bullpadel-hack-03",
    familyId: "fam-bullpadel-hack",
    generation: "03",
    lifecycleStatus: "previous-generation",
    shortDescription:
      "Previous-generation diamond Hack for advanced finishers; Hack 04 2026 is the current attack update.",
    relatedProductIds: ["prod-bullpadel-hack-04", "prod-bullpadel-vertex-04"],
    evidenceIds: ["ev-wave26-editorial"],
  },
  "prod-adidas-metalbone-hrd": {
    familyId: "fam-adidas-metalbone",
    generation: "2026-hrd",
    relatedProductIds: ["prod-adidas-metalbone-3-3-2026", "prod-babolat-technical-viper"],
  },
  "prod-babolat-technical-viper": {
    familyId: "fam-babolat-viper",
    generation: "technical-2026",
    relatedProductIds: ["prod-babolat-counter-viper", "prod-bullpadel-hack-04"],
  },
  "prod-babolat-counter-viper": {
    familyId: "fam-babolat-viper",
    generation: "counter-2026",
  },
  /** Accessories remain padel-only — do not tag as tennis crossover. */
  "prod-head-padel-pro-s": {
    sportIds: [padelSportId],
  },
  "prod-wilson-overgrip": {
    sportIds: [padelSportId],
  },
  "prod-nox-bag-10": {
    sportIds: [padelSportId],
  },
  /** Existing CourtStabil is padel-primary; keep padel-only unless dual-use confirmed. */
  "prod-adidas-courtstabil": {
    categoryId: "cat-padel-shoes",
    sportIds: [padelSportId],
    alternativeProductIds: [
      "prod-joma-t-slam",
      "prod-asics-gel-challenger-court",
      "prod-babolat-jet-premura",
    ],
  },
};

export const wave26Offers: Offer[] = wave26Drafts.flatMap((d) =>
  offerRegions(d.id, d.slug, d.priceEur, { decathlon: d.decathlonOffer }),
);

export const wave26Evidence: Evidence[] = [
  {
    id: "ev-wave26-editorial",
    type: "editorial-research",
    source: "Kitletics editorial analysis — padel catalog",
    summary:
      "Editorial research synthesising manufacturer pages, EU retailer listings, and independent review consensus for 2026 padel models. Not personal lab or on-court testing by Kitletics.",
    verifiedAt: SEED_DATES.verified,
    confidence: "medium",
  },
];

function padelRec(input: {
  id: string;
  productId: string;
  useCaseId: string;
  score: number;
  factors: Recommendation["factors"];
  strengths: string[];
  compromises: string[];
  explanation: string;
}): Recommendation {
  return {
    ...input,
    sportId: padelSportId,
    evidenceIds: ["ev-wave26-editorial"],
  };
}

export const wave26Recommendations: Recommendation[] = [
  padelRec({
    id: "rec-vertex05-power",
    productId: "prod-bullpadel-vertex-05",
    useCaseId: "uc-padel-power",
    score: 93,
    factors: [
      { key: "power", label: "Power", score: 94, weight: 0.45 },
      { key: "control", label: "Control", score: 88, weight: 0.35 },
      { key: "stability", label: "Stability", score: 92, weight: 0.2 },
    ],
    strengths: ["Diamond attack", "12K MultiEva response"],
    compromises: ["Premium price", "Not beginner soft"],
    explanation: "Flagship Vertex 05 when advanced players want power with usable control.",
  }),
  padelRec({
    id: "rec-vertex05-balanced",
    productId: "prod-bullpadel-vertex-05",
    useCaseId: "uc-padel-balanced",
    score: 90,
    factors: [
      { key: "versatility", label: "Versatility", score: 90, weight: 0.45 },
      { key: "power", label: "Power", score: 92, weight: 0.35 },
      { key: "control", label: "Control", score: 88, weight: 0.2 },
    ],
    strengths: ["All-court diamond", "Medium-large sweet zone"],
    compromises: ["Still attack-biased vs round control"],
    explanation: "Balanced advanced pick when Vertex geometry leads both attack and redirection.",
  }),
  padelRec({
    id: "rec-hack04-power",
    productId: "prod-bullpadel-hack-04",
    useCaseId: "uc-padel-power",
    score: 94,
    factors: [
      { key: "power", label: "Power", score: 96, weight: 0.55 },
      { key: "stiffness", label: "Stiffness", score: 92, weight: 0.25 },
      { key: "forgiveness", label: "Forgiveness", score: 68, weight: 0.2 },
    ],
    strengths: ["Maximum finishing punch", "Rigid diamond structure"],
    compromises: ["Demanding sweet spot", "Arm load"],
    explanation: "Hack 04 for advanced finishers who prioritise smash authority over comfort.",
  }),
  padelRec({
    id: "rec-at10-12k-power",
    productId: "prod-nox-at10-12k-2026",
    useCaseId: "uc-padel-power",
    score: 92,
    factors: [
      { key: "power", label: "Power", score: 93, weight: 0.5 },
      { key: "attack", label: "Attack", score: 91, weight: 0.3 },
      { key: "control", label: "Control", score: 78, weight: 0.2 },
    ],
    strengths: ["12K Alum Xtrem punch", "Diamond attack mold"],
    compromises: ["Compact sweet spot"],
    explanation: "AT10 12K Alum Xtrem when Nox attack geometry is preferred over Vertex/Hack.",
  }),
  padelRec({
    id: "rec-at10-12k-balanced",
    productId: "prod-nox-at10-12k-2026",
    useCaseId: "uc-padel-balanced",
    score: 86,
    factors: [
      { key: "power", label: "Power", score: 90, weight: 0.4 },
      { key: "versatility", label: "Versatility", score: 84, weight: 0.4 },
      { key: "control", label: "Control", score: 78, weight: 0.2 },
    ],
    strengths: ["Attack-capable AT10", "Pro-line materials"],
    compromises: ["Less forgiving than round control frames"],
    explanation: "Balanced only for advanced players already comfortable with diamond attack frames.",
  }),
  padelRec({
    id: "rec-metalbone-power",
    productId: "prod-adidas-metalbone-3-3-2026",
    useCaseId: "uc-padel-power",
    score: 91,
    factors: [
      { key: "power", label: "Power", score: 93, weight: 0.5 },
      { key: "tunability", label: "Tunability", score: 90, weight: 0.3 },
      { key: "control", label: "Control", score: 80, weight: 0.2 },
    ],
    strengths: ["Weight & Balance system", "Softer EVA than HRD"],
    compromises: ["Still advanced-biased"],
    explanation: "Standard Metalbone 2026 for attackers who want power with Soft Performance EVA feel.",
  }),
  padelRec({
    id: "rec-metalbone-balanced",
    productId: "prod-adidas-metalbone-3-3-2026",
    useCaseId: "uc-padel-balanced",
    score: 85,
    factors: [
      { key: "versatility", label: "Versatility", score: 84, weight: 0.45 },
      { key: "power", label: "Power", score: 90, weight: 0.35 },
      { key: "feel", label: "Feel", score: 86, weight: 0.2 },
    ],
    strengths: ["Customisable balance", "Less harsh than HRD"],
    compromises: ["Diamond geometry still attack-first"],
    explanation: "Balanced Metalbone when Soft EVA helps mid-court exchanges without dropping power.",
  }),
  padelRec({
    id: "rec-extreme-motion-control",
    productId: "prod-head-extreme-motion-2026",
    useCaseId: "uc-padel-control",
    score: 84,
    factors: [
      { key: "control", label: "Control", score: 86, weight: 0.45 },
      { key: "maneuverability", label: "Maneuverability", score: 88, weight: 0.35 },
      { key: "power", label: "Power", score: 74, weight: 0.2 },
    ],
    strengths: ["Faster Extreme handling", "Approachable sweet zone"],
    compromises: ["Not a confirmed Delta Pro control mold"],
    explanation: "Control-leaning Head Extreme Motion when Delta Pro 2026 was not clearly catalogued.",
  }),
  padelRec({
    id: "rec-extreme-motion-balanced",
    productId: "prod-head-extreme-motion-2026",
    useCaseId: "uc-padel-balanced",
    score: 83,
    factors: [
      { key: "versatility", label: "Versatility", score: 85, weight: 0.5 },
      { key: "control", label: "Control", score: 84, weight: 0.5 },
    ],
    strengths: ["Intermediate-friendly Extreme", "Hybrid usability"],
    compromises: ["Less smash than Hack/Metalbone"],
    explanation: "Balanced Extreme Motion for intermediates building toward attack without a pure diamond.",
  }),
  padelRec({
    id: "rec-wall-breaker-power",
    productId: "prod-tecnifibre-wall-breaker-365-2026",
    useCaseId: "uc-padel-power",
    score: 86,
    factors: [
      { key: "power", label: "Power", score: 88, weight: 0.5 },
      { key: "spin", label: "Spin", score: 86, weight: 0.3 },
      { key: "value", label: "Value", score: 82, weight: 0.2 },
    ],
    strengths: ["Teardrop finishing", "Spin skin"],
    compromises: ["Less round forgiveness"],
    explanation: "Tecnifibre Wall Breaker when French teardrop attack is preferred.",
  }),
  padelRec({
    id: "rec-oxdog-control",
    productId: "prod-oxdog-sense-pro-2026",
    useCaseId: "uc-padel-control",
    score: 88,
    factors: [
      { key: "control", label: "Control", score: 90, weight: 0.5 },
      { key: "forgiveness", label: "Forgiveness", score: 90, weight: 0.3 },
      { key: "power", label: "Power", score: 74, weight: 0.2 },
    ],
    strengths: ["Round Sense mold", "Large sweet spot"],
    compromises: ["Less smash peak"],
    explanation: "Oxdog Sense Pro for control-first intermediates who want round forgiveness.",
  }),
  padelRec({
    id: "rec-oxdog-balanced",
    productId: "prod-oxdog-sense-pro-2026",
    useCaseId: "uc-padel-balanced",
    score: 85,
    factors: [
      { key: "versatility", label: "Versatility", score: 86, weight: 0.45 },
      { key: "control", label: "Control", score: 88, weight: 0.35 },
      { key: "value", label: "Value", score: 81, weight: 0.2 },
    ],
    strengths: ["Control with usable power", "RBS tuning"],
    compromises: ["Not a pure attacker"],
    explanation: "Balanced Sense Pro when round control still needs mid-court punch.",
  }),
  padelRec({
    id: "rec-m27-control",
    productId: "prod-royal-padel-rp-m27-2026",
    useCaseId: "uc-padel-control",
    score: 90,
    factors: [
      { key: "control", label: "Control", score: 94, weight: 0.5 },
      { key: "forgiveness", label: "Forgiveness", score: 92, weight: 0.35 },
      { key: "comfort", label: "Comfort", score: 90, weight: 0.15 },
    ],
    strengths: ["Large sweet spot", "Shock Absorption"],
    compromises: ["Heavier upper weight band"],
    explanation: "M27 Poly 2026 when placement and comfort lead the buying decision.",
  }),
  padelRec({
    id: "rec-m27-beginner",
    productId: "prod-royal-padel-rp-m27-2026",
    useCaseId: "uc-padel-beginner",
    score: 84,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 92, weight: 0.5 },
      { key: "control", label: "Control", score: 90, weight: 0.35 },
      { key: "value", label: "Value", score: 72, weight: 0.15 },
    ],
    strengths: ["Round forgiveness", "Comfortable polyethylene core"],
    compromises: ["Pricey vs Kuikma/Black Crown starters"],
    explanation: "Beginner-friendly only when budget allows a premium round control frame.",
  }),
  padelRec({
    id: "rec-black-crown-beginner",
    productId: "prod-black-crown-special-one-soft",
    useCaseId: "uc-padel-beginner",
    score: 89,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 93, weight: 0.5 },
      { key: "value", label: "Value", score: 94, weight: 0.35 },
      { key: "power", label: "Power", score: 58, weight: 0.15 },
    ],
    strengths: ["Soft round starter", "Low price"],
    compromises: ["Limited attack ceiling"],
    explanation: "Value beginner Soft when forgiveness and budget dominate.",
  }),
  padelRec({
    id: "rec-lok-beginner",
    productId: "prod-lok-maxx-flow",
    useCaseId: "uc-padel-beginner",
    score: 86,
    factors: [
      { key: "forgiveness", label: "Forgiveness", score: 88, weight: 0.4 },
      { key: "value", label: "Value", score: 92, weight: 0.4 },
      { key: "versatility", label: "Versatility", score: 82, weight: 0.2 },
    ],
    strengths: ["Teardrop growth path", "Strong value"],
    compromises: ["Not ultra-soft round"],
    explanation: "Lok Maxx Flow for beginners who want a hybrid shape with room to progress.",
  }),
  padelRec({
    id: "rec-lok-balanced",
    productId: "prod-lok-maxx-flow",
    useCaseId: "uc-padel-balanced",
    score: 82,
    factors: [
      { key: "versatility", label: "Versatility", score: 84, weight: 0.5 },
      { key: "value", label: "Value", score: 91, weight: 0.5 },
    ],
    strengths: ["Hybrid value", "Club-ready"],
    compromises: ["Not premium face materials"],
    explanation: "Balanced value Lok when budget caps premium diamond flags.",
  }),
];

/**
 * AlternativeRelationship only allows the domain enum (cheaper|premium|faster|…).
 * Generation links use premium / better-value with reasons describing previous/next generation.
 */
export const wave26Alternatives: AlternativeRelationship[] = [
  {
    id: "alt-vertex04-to-05",
    sourceProductId: "prod-bullpadel-vertex-04",
    alternativeProductId: "prod-bullpadel-vertex-05",
    similarityScore: 88,
    reasons: [
      "Next generation in fam-bullpadel-vertex",
      "Same diamond attack role with updated 12K MultiEva construction",
    ],
    relationshipType: "premium",
  },
  {
    id: "alt-vertex05-to-04",
    sourceProductId: "prod-bullpadel-vertex-05",
    alternativeProductId: "prod-bullpadel-vertex-04",
    similarityScore: 88,
    reasons: [
      "Previous generation Vertex 04",
      "Similar diamond role at typically lower clearance pricing",
    ],
    relationshipType: "better-value",
  },
  {
    id: "alt-hack03-to-04",
    sourceProductId: "prod-bullpadel-hack-03",
    alternativeProductId: "prod-bullpadel-hack-04",
    similarityScore: 86,
    reasons: [
      "Next generation in fam-bullpadel-hack",
      "Updated diamond power platform over Hack 03",
    ],
    relationshipType: "premium",
  },
  {
    id: "alt-hack04-to-03",
    sourceProductId: "prod-bullpadel-hack-04",
    alternativeProductId: "prod-bullpadel-hack-03",
    similarityScore: 86,
    reasons: [
      "Previous generation Hack 03",
      "Same attacking role when current Hack 04 stock or budget is constrained",
    ],
    relationshipType: "better-value",
  },
  {
    id: "alt-vertex05-hack04",
    sourceProductId: "prod-bullpadel-vertex-05",
    alternativeProductId: "prod-bullpadel-hack-04",
    similarityScore: 82,
    reasons: ["Same brand diamond attack tier", "Hack leans more pure smash / less balanced"],
    relationshipType: "faster",
  },
  {
    id: "alt-hack04-vertex05",
    sourceProductId: "prod-bullpadel-hack-04",
    alternativeProductId: "prod-bullpadel-vertex-05",
    similarityScore: 82,
    reasons: ["Same brand diamond attack tier", "Vertex offers more usable control reserve"],
    relationshipType: "more-stable",
  },
  {
    id: "alt-at10-12k-metalbone",
    sourceProductId: "prod-nox-at10-12k-2026",
    alternativeProductId: "prod-adidas-metalbone-3-3-2026",
    similarityScore: 80,
    reasons: ["Diamond power competitors", "Metalbone Soft EVA vs Alum Xtrem face feel"],
    relationshipType: "more-stable",
  },
  {
    id: "alt-metalbone-at10-12k",
    sourceProductId: "prod-adidas-metalbone-3-3-2026",
    alternativeProductId: "prod-nox-at10-12k-2026",
    similarityScore: 80,
    reasons: ["Diamond power competitors", "AT10 12K for Nox attack geometry"],
    relationshipType: "faster",
  },
  {
    id: "alt-vertex05-at10-12k",
    sourceProductId: "prod-bullpadel-vertex-05",
    alternativeProductId: "prod-nox-at10-12k-2026",
    similarityScore: 84,
    reasons: ["Flagship diamond attackers", "Different brand ecosystems and face constructions"],
    relationshipType: "faster",
  },
  {
    id: "alt-at10-12k-vertex05",
    sourceProductId: "prod-nox-at10-12k-2026",
    alternativeProductId: "prod-bullpadel-vertex-05",
    similarityScore: 84,
    reasons: ["Flagship diamond attackers", "Vertex 05 for slightly wider sweet-zone positioning"],
    relationshipType: "more-stable",
  },
  {
    id: "alt-at10-18k-to-12k",
    sourceProductId: "prod-nox-at10-18k-2026",
    alternativeProductId: "prod-nox-at10-12k-2026",
    similarityScore: 85,
    reasons: ["Same AT10 family", "12K Alum Xtrem is the stiffer attack sibling"],
    relationshipType: "premium",
  },
  {
    id: "alt-metalbone-hrd-to-standard",
    sourceProductId: "prod-adidas-metalbone-hrd",
    alternativeProductId: "prod-adidas-metalbone-3-3-2026",
    similarityScore: 87,
    reasons: ["Same Metalbone family", "Standard Soft Performance EVA is more approachable than HRD"],
    relationshipType: "beginner-friendly",
  },
  {
    id: "alt-m27-oxdog",
    sourceProductId: "prod-royal-padel-rp-m27-2026",
    alternativeProductId: "prod-oxdog-sense-pro-2026",
    similarityScore: 78,
    reasons: ["Round control peers", "Both prioritise forgiveness over pure smash"],
    relationshipType: "more-stable",
  },
  {
    id: "alt-kuikma-black-crown",
    sourceProductId: "prod-kuikma-pr-soft-500",
    alternativeProductId: "prod-black-crown-special-one-soft",
    similarityScore: 80,
    reasons: ["Value soft beginners", "Similar forgiveness-first role"],
    relationshipType: "beginner-friendly",
  },
  {
    id: "alt-black-crown-lok",
    sourceProductId: "prod-black-crown-special-one-soft",
    alternativeProductId: "prod-lok-maxx-flow",
    similarityScore: 76,
    reasons: ["Value starter tier", "Lok adds teardrop hybrid output"],
    relationshipType: "faster",
  },
  {
    id: "alt-resolution-challenger",
    sourceProductId: "prod-asics-gel-resolution-padel",
    alternativeProductId: "prod-asics-gel-challenger-court",
    similarityScore: 82,
    reasons: ["Same ASICS court ecosystem", "Challenger is cheaper daily option"],
    relationshipType: "cheaper",
  },
  {
    id: "alt-challenger-resolution",
    sourceProductId: "prod-asics-gel-challenger-court",
    alternativeProductId: "prod-asics-gel-resolution-padel",
    similarityScore: 82,
    reasons: ["Same ASICS court ecosystem", "Resolution adds premium lockdown/cushion"],
    relationshipType: "more-cushioned",
  },
  {
    id: "alt-premura-joma",
    sourceProductId: "prod-babolat-jet-premura",
    alternativeProductId: "prod-joma-t-slam",
    similarityScore: 74,
    reasons: ["Padel court shoes", "Joma typically better value"],
    relationshipType: "better-value",
  },
  {
    id: "alt-joma-premura",
    sourceProductId: "prod-joma-t-slam",
    alternativeProductId: "prod-babolat-jet-premura",
    similarityScore: 74,
    reasons: ["Padel court shoes", "Premura is the premium padel-specific outsole option"],
    relationshipType: "premium",
  },
  {
    id: "alt-courtstabil-joma",
    sourceProductId: "prod-adidas-courtstabil",
    alternativeProductId: "prod-joma-t-slam",
    similarityScore: 72,
    reasons: ["Padel court stability shoes", "Similar lateral-support role"],
    relationshipType: "better-value",
  },
];

export const wave26Families: ProductFamily[] = [
  {
    id: "fam-nox-at10",
    brandId: "brand-nox",
    name: "AT10 Genius",
    slug: "nox-at10-genius",
    categoryId: "cat-padel-rackets",
    description: "Nox AT10 Genius family — Agustín Tapia signature line across carbon grades.",
    productIds: ["prod-nox-at10-12k-2026", "prod-nox-at10-18k-2026"],
  },
  {
    id: "fam-bullpadel-vertex",
    brandId: "brand-bullpadel",
    name: "Vertex",
    slug: "bullpadel-vertex",
    categoryId: "cat-padel-rackets",
    description: "Bullpadel Vertex diamond attack family.",
    productIds: ["prod-bullpadel-vertex-05", "prod-bullpadel-vertex-04"],
  },
  {
    id: "fam-bullpadel-hack",
    brandId: "brand-bullpadel",
    name: "Hack",
    slug: "bullpadel-hack",
    categoryId: "cat-padel-rackets",
    description: "Bullpadel Hack diamond power family.",
    productIds: ["prod-bullpadel-hack-04", "prod-bullpadel-hack-03"],
  },
  {
    id: "fam-adidas-metalbone",
    brandId: "brand-adidas-padel",
    name: "Metalbone",
    slug: "adidas-metalbone",
    categoryId: "cat-padel-rackets",
    description: "Adidas Metalbone attack family including standard and HRD variants.",
    productIds: ["prod-adidas-metalbone-3-3-2026", "prod-adidas-metalbone-hrd"],
  },
  {
    id: "fam-babolat-viper",
    brandId: "brand-babolat-padel",
    name: "Viper",
    slug: "babolat-viper",
    categoryId: "cat-padel-rackets",
    description: "Babolat Viper family spanning Technical and Counter lines.",
    productIds: ["prod-babolat-technical-viper", "prod-babolat-counter-viper"],
  },
];

export const wave26Comparisons: Comparison[] = [
  {
    id: "cmp-vertex05-vs-hack04",
    slug: "bullpadel-vertex-05-vs-hack-04-2026",
    title: "Bullpadel Vertex 05 vs Hack 04 2026",
    shortDescription: "Two Bullpadel diamond attackers with different control reserves.",
    productIds: ["prod-bullpadel-vertex-05", "prod-bullpadel-hack-04"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary:
      "Vertex 05 targets advanced players who still need usable control; Hack 04 pushes further into pure finishing power.",
    verdict:
      "No universal winner — choose Vertex 05 when you want attack with a wider usable zone; choose Hack 04 when smash authority outweighs forgiveness.",
    criteria: [
      {
        key: "power",
        label: "Power",
        winnerProductId: "prod-bullpadel-hack-04",
        notes: "Hack profiles denser MultiEva / stiffer attack response.",
      },
      {
        key: "control",
        label: "Control",
        winnerProductId: "prod-bullpadel-vertex-05",
        notes: "Vertex 05 positions a larger usable sweet zone for redirects.",
      },
      {
        key: "forgiveness",
        label: "Forgiveness",
        winnerProductId: "prod-bullpadel-vertex-05",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-power",
        productId: "prod-bullpadel-hack-04",
        rationale: "Maximum finishing bias within the Bullpadel diamond pair.",
      },
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-bullpadel-vertex-05",
        rationale: "More usable mid-court control while staying attack-capable.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-bullpadel-vertex-05",
        context: "Advanced all-court attack",
        reason: "You want diamond power without Hack-level unforgiveness.",
      },
      {
        productId: "prod-bullpadel-hack-04",
        context: "Left-side finishing",
        reason: "You prioritise smash output and can live with a compact sweet spot.",
      },
    ],
    evidenceIds: ["ev-wave26-editorial"],
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-at10-12k-vs-metalbone",
    slug: "nox-at10-12k-vs-adidas-metalbone-2026",
    title: "Nox AT10 12K Alum Xtrem vs Adidas Metalbone 2026",
    shortDescription: "Diamond power flagships with different face/core philosophies.",
    productIds: ["prod-nox-at10-12k-2026", "prod-adidas-metalbone-3-3-2026"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary:
      "Both are diamond attackers; AT10 12K emphasises Alum Xtrem face response while Metalbone leans Soft Performance EVA with Weight & Balance tuning.",
    verdict:
      "Contextual — pick AT10 12K for Nox attack geometry and Alum Xtrem punch; pick Metalbone when Soft EVA feel and on-racket weight tuning matter more.",
    criteria: [
      {
        key: "power",
        label: "Power",
        notes: "Both high; preference depends on face stiffness vs Soft EVA output.",
      },
      {
        key: "tunability",
        label: "Tunability",
        winnerProductId: "prod-adidas-metalbone-3-3-2026",
        notes: "Metalbone Weight & Balance system is the clearer adjustment story.",
      },
      {
        key: "face-response",
        label: "Face response",
        winnerProductId: "prod-nox-at10-12k-2026",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-power",
        productId: "prod-nox-at10-12k-2026",
        rationale: "Alum Xtrem diamond attack when raw face punch leads.",
      },
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-adidas-metalbone-3-3-2026",
        rationale: "Soft Performance EVA helps mid-court exchanges inside a power mold.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-nox-at10-12k-2026",
        reason: "You want Nox AT10 attack geometry with 12K Alum Xtrem.",
      },
      {
        productId: "prod-adidas-metalbone-3-3-2026",
        reason: "You want Soft EVA Metalbone feel plus Weight & Balance tuning.",
      },
    ],
    evidenceIds: ["ev-wave26-editorial"],
    faqIds: [],
    ...pub,
  },
  {
    id: "cmp-vertex05-vs-at10-12k",
    slug: "bullpadel-vertex-05-vs-nox-at10-12k-2026",
    title: "Bullpadel Vertex 05 vs Nox AT10 12K Alum Xtrem 2026",
    shortDescription: "Two 2026 diamond flagships from rival Spanish ecosystems.",
    productIds: ["prod-bullpadel-vertex-05", "prod-nox-at10-12k-2026"],
    categoryId: "cat-padel-rackets",
    comparisonType: "editorial",
    summary:
      "Vertex 05 pairs 12K MultiEva with a medium-large sweet-zone story; AT10 12K Alum Xtrem is the more compact, punch-first sibling in the Nox attack lane.",
    verdict:
      "No single winner — Vertex 05 if you want slightly more usable control inside a diamond; AT10 12K if you prefer Nox Alum Xtrem attack response.",
    criteria: [
      {
        key: "control",
        label: "Control",
        winnerProductId: "prod-bullpadel-vertex-05",
      },
      {
        key: "power",
        label: "Power",
        notes: "Both high; AT10 12K reads more compact/aggressive on paper.",
      },
      {
        key: "sweet-spot",
        label: "Sweet spot",
        winnerProductId: "prod-bullpadel-vertex-05",
      },
    ],
    recommendationsByUseCase: [
      {
        useCaseId: "uc-padel-balanced",
        productId: "prod-bullpadel-vertex-05",
        rationale: "Wider usable zone for advanced all-court diamond play.",
      },
      {
        useCaseId: "uc-padel-power",
        productId: "prod-nox-at10-12k-2026",
        rationale: "Compact Alum Xtrem attack when finishing leads.",
      },
    ],
    chooseProductReasons: [
      {
        productId: "prod-bullpadel-vertex-05",
        reason: "You want Bullpadel Vertex geometry with a medium-large sweet zone.",
      },
      {
        productId: "prod-nox-at10-12k-2026",
        reason: "You want Nox AT10 Alum Xtrem punch in a diamond mold.",
      },
    ],
    evidenceIds: ["ev-wave26-editorial"],
    faqIds: [],
    ...pub,
  },
];

/** Structural generation + flagship competitor edges for Prompt 26 graph QA. */
export const wave26Relationships: ProductRelationship[] = [
  {
    id: "rel-w26-vertex-05-04-prev",
    sourceProductId: "prod-bullpadel-vertex-05",
    targetProductId: "prod-bullpadel-vertex-04",
    type: "previous-generation",
    categoryId: "cat-padel-rackets",
    strength: 92,
    reasons: [
      "Same Vertex family diamond attack role",
      "Vertex 04 is the immediate prior generation vs Vertex 05",
    ],
    evidenceIds: ["ev-wave26-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-vertex-04-05-next",
    sourceProductId: "prod-bullpadel-vertex-04",
    targetProductId: "prod-bullpadel-vertex-05",
    type: "next-generation",
    categoryId: "cat-padel-rackets",
    strength: 92,
    reasons: ["Current Vertex 05 succeeding Vertex 04"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-hack-04-03-prev",
    sourceProductId: "prod-bullpadel-hack-04",
    targetProductId: "prod-bullpadel-hack-03",
    type: "previous-generation",
    categoryId: "cat-padel-rackets",
    strength: 90,
    reasons: [
      "Same Hack family diamond power role",
      "Hack 03 is the immediate prior generation vs Hack 04",
    ],
    evidenceIds: ["ev-wave26-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-hack-03-04-next",
    sourceProductId: "prod-bullpadel-hack-03",
    targetProductId: "prod-bullpadel-hack-04",
    type: "next-generation",
    categoryId: "cat-padel-rackets",
    strength: 90,
    reasons: ["Current Hack 04 succeeding Hack 03"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: true,
    ...relMeta,
  },
  {
    id: "rel-w26-vertex05-vs-hack04",
    sourceProductId: "prod-bullpadel-vertex-05",
    targetProductId: "prod-bullpadel-hack-04",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 88,
    reasons: [
      "Same-brand flagship choice: Vertex sweet-zone vs Hack power mold",
    ],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-vertex05-vs-at10-12k",
    sourceProductId: "prod-bullpadel-vertex-05",
    targetProductId: "prod-nox-at10-12k-2026",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 86,
    reasons: ["Competing premium diamond attack platforms for advanced players"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-at10-12k-vs-metalbone",
    sourceProductId: "prod-nox-at10-12k-2026",
    targetProductId: "prod-adidas-metalbone-3-3-2026",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 84,
    reasons: ["Premium diamond power competitors across Nox and Adidas lines"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-ml10-vs-diablo",
    sourceProductId: "prod-nox-ml10-pro-cup",
    targetProductId: "prod-siux-diablo",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 80,
    reasons: ["Control / maneuverability-oriented round-to-hybrid alternatives"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-coello-vs-viper",
    sourceProductId: "prod-head-coello-pro",
    targetProductId: "prod-babolat-technical-viper",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 82,
    reasons: ["Attacking teardrop / diamond mid-premium competitors"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-oxdog-vs-ml10",
    sourceProductId: "prod-oxdog-sense-pro-2026",
    targetProductId: "prod-nox-ml10-pro-cup",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 78,
    reasons: ["Softer control-oriented options when feel and handling lead"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-royal-vs-lok",
    sourceProductId: "prod-royal-padel-rp-m27-2026",
    targetProductId: "prod-lok-maxx-flow",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 76,
    reasons: ["Balanced club-level alternatives outside the ultra-premium tier"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-extreme-vs-black-crown",
    sourceProductId: "prod-head-extreme-motion-2026",
    targetProductId: "prod-black-crown-special-one-soft",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 74,
    reasons: ["Maneuverable intermediate options with accessible pricing"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-bela-vs-blade-pro",
    sourceProductId: "prod-wilson-bela-pro",
    targetProductId: "prod-wilson-blade-pro-padel",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 80,
    reasons: ["Same-brand Wilson padel choice: Bela attack vs Blade Pro control bias"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-titania-vs-basalto",
    sourceProductId: "prod-starvie-titania-kepler",
    targetProductId: "prod-starvie-basalto-osiris",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 78,
    reasons: ["StarVie family pairing across soft/control and firmer constructions"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-counter-vs-technical-viper",
    sourceProductId: "prod-babolat-counter-viper",
    targetProductId: "prod-babolat-technical-viper",
    type: "direct-competitor",
    categoryId: "cat-padel-rackets",
    strength: 86,
    reasons: ["Same Viper family decision: Counter control vs Technical attack"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-extreme-pro-vs-motion",
    sourceProductId: "prod-head-extreme-pro-padel",
    targetProductId: "prod-head-extreme-motion-2026",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 82,
    reasons: ["Head Extreme line options across Pro and Motion positioning"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-canyon-vs-wall-breaker",
    sourceProductId: "prod-drop-shot-canyon-pro",
    targetProductId: "prod-tecnifibre-wall-breaker-365-2026",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 72,
    reasons: ["Specialist-brand power-oriented alternatives outside the ultra-premium tier"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
  {
    id: "rel-w26-varlion-vs-ml10",
    sourceProductId: "prod-varlion-lw-carbon-difusor",
    targetProductId: "prod-nox-ml10-pro-cup",
    type: "similar",
    categoryId: "cat-padel-rackets",
    strength: 74,
    reasons: ["Control-leaning round / soft constructions for placement-first play"],
    evidenceIds: ["ev-wave26-editorial"],
    directional: false,
    ...relMeta,
  },
];
